### ISSUE TITLE
move to external file json_data var on HTML output

### ISSUE THREAD

**Issue by jabiertxof** [allinurl/goaccess#1000]
Hi could be cool have the variable json_data at the same place than the output in HTML to dont need to process two times or parse the result. 
Maybe can be a option like: html_output_json_data:<inline|external|both>

**Comment by jabiertxof** [comment]
Maybe is not a good idea because we write from std out the filo so only one file, maybe a option to parse a JSON file to create a HTML report could be better.

**Comment by allinurl** [comment]
Hi @jabiertxof, Sorry I'm not sure I follow this. Can I ask you what would be the reason to have the json_data variable on a different file? I believe right now it's being parsed only once upon loading the document.

**Comment by jabiertxof** [comment]
Hi, Sorry for the noise. I can parse the JSON data without processsing logs, so don need this and is much better as it. Thanks for the fast reply.

**Comment by jabiertxof** [comment]
For anyone came later, if you dont give log files goacces process again with the same data but without processing files, and you can output to JS or CSV if your original request is HTML.
