### ISSUE TITLE
Problems with referers (KeyPrases from google)

### ISSUE THREAD

**Issue by jabiertxof** [allinurl/goaccess#1002]
Hi Im looking for keyprases from google not empty. Attached are a report in JSON format.
querystrings from google.es and google it are striped it. In the original  NGINX log they show.

Thanks in advance for the help.

[goaccess-1517393407555.txt](https://github.com/allinurl/goaccess/files/1681256/goaccess-1517393407555.txt)

**Comment by allinurl** [comment]
Can you please post the original lines from your access log? Thanks.

**Comment by jabiertxof** [comment]
Yes of course:

    less ./cdr-mks.access.log.1 | grep "q="
    165.72.200.11 - - [29/Jan/2018:15:12:58 +0000] "GET / HTTP/1.1" 200 17805 "https://www.google.es/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&ved=0ahUKEwjh_prwuv3YAhWD3KQKHTuNDYoQFggnMAA&url=https%3A%2F%2Fwww.delreino.es%2F&usg=AOvVaw2EWNN9YGQJi7qIepkou0go" "Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; Touch; rv:11.0) like Gecko"
    192.168.20.1 - - [30/Jan/2018:14:52:30 +0000] "GET /info/6-cookies HTTP/2.0" 200 23207 "https://www.google.es/search?hl=es&source=hp&biw=&bih=&q=delreino+conservas+google.es+marker&btnG=Buscar+con+Google&gbv=1" "Mozilla/5.0 (X11; Linux x86_64; rv:58.0) Gecko/20100101 Firefox/58.0"
    192.168.20.1 - - [30/Jan/2018:16:03:49 +0000] "GET /tienda/ofertas-8 HTTP/2.0" 200 20543 "https://www.google.it/search?q=delreino+conservas+google.it+marker&gbv=1&sei=WJdwWv2AEof6UNXHmagL" "Mozilla/5.0 (X11; Linux x86_64; rv:58.0) Gecko/20100101 Firefox/58.0"

**Comment by jabiertxof** [comment]
Maybe the problem the querries are done by my in the same conexion?
165.72.200.11 q=""
192.168.20.1 is a subnetwork inside the same conexion of the server.

**Comment by allinurl** [comment]
@jabiertxof For those three requests, what output do you get in goaccess and what output do you expect to get? Thanks.

**Comment by jabiertxof** [comment]
Not sure how display goacces the keyfrases but try to imagine:
for the first one nonthing (165.72.200.11) q is empry.
for 192.168.20.1:
* 2 match - 1 "test conservas google.es marker" 2 - "test conservas google.it marker"
also a individual space split key counter couls be useful.
Thanks!

**Comment by allinurl** [comment]
Can you please try building from [**development**](https://github.com/allinurl/goaccess#build-from-github-development)? I just tested the strings you posted above and it did work for me. Please let me know how it goes. Thanks.

**Comment by jabiertxof** [comment]
I update the code, in one days or two report here. Thanks!

**Comment by allinurl** [comment]
Any updates?

**Comment by jabiertxof** [comment]
SORRY forget to reply!!!! Now keywords works. 
Just for curiosity static request panels are empty, is normal?
Thanks in advance.

**Comment by jabiertxof** [comment]
Another question with BTree storage, unique visitors are counted remembering previous users/IP in the database or are only in each process?

**Comment by allinurl** [comment]
Do you have static requests in your data set that have any of the [**following**](https://github.com/allinurl/goaccess/blob/master/config/goaccess.conf#L552) extensions? If you use `--load-from-disk`, it will count only new unique visitors. Take a look at the `PROCESSING LOGS INCREMENTALLY` section in the [**man page**](https://goaccess.io/man#examples).

**Comment by jabiertxof** [comment]
thanks @allinurl I open a new bug with the static files panel

**Comment by jabiertxof** [comment]
Finaly find the problem. Google has stopped his referer parameters in SSL searches so keywords usualy are not filled :(

https://stackoverflow.com/questions/12181375/how-to-get-the-referer-search-query-from-google

Thanks so much for your help!
