### ISSUE TITLE
goaccess 1.2 stalled charts

### ISSUE THREAD

**Issue by jazzl0ver** [allinurl/goaccess#1003]
Command line:
```
/usr/bin/goaccess - --port=7890 -o /var/www/html/report.html --load-from-disk --keep-db-files --db-path=/var/lib/goaccess/ --compression bz2 --real-time-html  < <(/usr/bin/socat -t3 -u UNIX-RECV:/tmp/haproxy.sock -) >/dev/null
```
/var/www/html/report.html as well as tcb files in /var/lib/goaccess/ are up to date.
The dashboard shows:
![image](https://user-images.githubusercontent.com/2444175/35727648-dfb3f516-0819-11e8-9b68-481d663feb87.png)
Stalled unique visitors per day:
![image](https://user-images.githubusercontent.com/2444175/35727683-021f5e38-081a-11e8-8bb7-3695629f2952.png)

Please, advise!

**Comment by allinurl** [comment]
Can you elaborate a bit more what you mean stalled charts? Are the tables updating properly? Also, I assume your chart from the second screenshot shows up until 08/Dec?

**Comment by jazzl0ver** [comment]
The table files are updating properly, but the charts show data just up to Dec 8. Neither later Dec nor Jan or Feb is shown. I tried to restart goaccess but that didn't help.

**Comment by allinurl** [comment]
Could you please post a screenshot of your table along with the chart (the whole visitors panel) just to see the order in which the dates are showing up? Also, can you please build from [development](https://github.com/allinurl/goaccess#build-from-github-development) and let me know if that solves the issue? Thanks.

**Comment by jazzl0ver** [comment]
This is weird but today all looks good:
![image](https://user-images.githubusercontent.com/2444175/35934566-fe74ba1a-0c4e-11e8-80bb-08f6d8e76bbd.png)
Didn't do anything for last couple days..

**Comment by allinurl** [comment]
Great to hear that. If for some reason, it occurs again, please feel free to reopen this. Thanks.

**Comment by jazzl0ver** [comment]
Hi. It's just happened again:
![image](https://user-images.githubusercontent.com/2444175/41109138-efeed212-6a7e-11e8-8f2c-f37dc3402196.png)
![image](https://user-images.githubusercontent.com/2444175/41109155-fb0ec2ec-6a7e-11e8-8ccc-c2dae79f43a3.png)
I've restarted it yesterday but that didn't help.
```
# ps -ef|grep goaccess
root      1258  1236 12 15:10 pts/1    00:00:51 /usr/bin/goaccess - --port=4789 -p /etc/goaccess.conf -o /var/www/html/report.html --load-from-disk --keep-db-files --db-path=/var/lib/goaccess/ --compression bz2 --real-time-html

# /usr/bin/goaccess -V
GoAccess - 1.2.
For more details visit: http://goaccess.io
Copyright (C) 2009-2016 by Gerardo Orellana

Build configure arguments:
  --enable-utf8
  --enable-geoip=legacy
  --enable-tcb=btree

# pwd
/root/goaccess-1.2
# git rev-parse HEAD
d4b1a1f812887c2dd5b89d52ea96b5e4297ce408

# ls -la /usr/bin/goaccess
-rwxr-xr-x 1 root root 630648 May 22 14:05 /usr/bin/goaccess
```

**Comment by allinurl** [comment]
Since I've been pushing some updates to the html report, can I ask you to build from development again or `git pull --rebase` and let me know if that helps. Thanks.

**Comment by jazzl0ver** [comment]
Seems to be better now - after restarting goaccess shows the up-to-date data. Thanks!

**Comment by allinurl** [comment]
Unfortunately I haven't been able to reproduce this on my side. I'm thinking this could be related to the btree storage, though the odd thing is that you said the tables are working fine...

**Comment by jazzl0ver** [comment]
What if I archive the current tcb files along with goaccess.conf and send them to you? Would you be able to try them onto your side?

**Comment by allinurl** [comment]
Before doing that, would you be able to try this out by building goaccess without btree support but instead using the default hash tables? Thanks

**Comment by jazzl0ver** [comment]
will it still be able to keep db files on disk?

**Comment by jazzl0ver** [comment]
just built it and now it complains:
```
/usr/bin/goaccess: unrecognized option '--load-from-disk'
```

**Comment by allinurl** [comment]
It won't persist data on disk, I just want to make sure it's not related to the btree storage. Just for testing purposes.

**Comment by jazzl0ver** [comment]
But how to load the db files in this case?

**Comment by allinurl** [comment]
For now you can't, you will need to run goaccess against the current access log and see if the charts still get stalled. e.g., 

    goaccess access.log --port=7890 -o /var/www/html/report.html --real-time-html

**Comment by allinurl** [comment]
does it stall with the hash tables as well after some time?

**Comment by jazzl0ver** [comment]
i didn't check that. i need to keep history

**Comment by allinurl** [comment]
That's why I said if you could help test it out. Otherwise I'm not sure I can fix this since btree is going away (being replaced) and we're not sure if it's happening only with btree or hash tables as well.

**Comment by jazzl0ver** [comment]
ok. i'll try to run w/o btree. will let you know if/when it happen

**Comment by jazzl0ver** [comment]
the counters are growing but the charts are empty:
![image](https://user-images.githubusercontent.com/2444175/52288102-8ffe4500-297c-11e9-8bd5-a3a5ae63f56c.png)
```
cat /proc/$(pgrep socat)/fd/5 | /usr/bin/goaccess - --port=7890 -p /etc/goaccess/goaccess.conf -o /var/www/html/report.html --real-time-html
```

**Comment by jazzl0ver** [comment]
oh boy.. i've figured it out. there was an error in log_format line:
```
log_format %^ %^ %^ %^ [%d:%t.%^] %^ %^ %^/%^/%^/%^/%^/%^/%L %^ %^ %^ "%r" %s {%^|%^|%^|%u} %^ %^=%b %^ %h:%^ %^ %^ %^
```
and it failed to parse the log lines like this:
```
Feb  5 17:17:51 ...
```
while successfully parsed, for example:
```
Feb  25 17:17:51 
```
so, i ended up with this workaround:
```
log_format %^ %~ %^ %^ %^ [%d:%t.%^] %^ %^ %^/%^/%^/%^/%^/%^/%L %^ %^ %^ "%r" %s {%^|%^|%^|%u} %^ %^=%b %^ %h:%^ %^ %^ %^
```
and now it works as expected!

I truly apologies for bothering you with this :((
