### ISSUE TITLE
Inconsistent date range for the same logs

### ISSUE THREAD

**Issue by millsjustin** [allinurl/goaccess#1004]
When I run goaccess with ```date-spec date``` I get a date range of ```01/Jan/2018 — 31/Jan/2018``` but when I run goaccess on the same logs with ```date-spec hr``` I get a date range of ```06/Jan/2018 — 31/Jan/2018``` all other numbers in the report except ```Unique Visitors``` are the same.

Do you have any idea what might be causing this problem?

I'm running the latest version compiled from github just a few days ago.

**Comment by allinurl** [comment]
Great question! GoAccess will display only 365 items per panel, so I'm guessing `date-spec=hr` is actually bringing the whole 365 items sorted by date.

**Comment by millsjustin** [comment]
Yep that's what's happening. I just ran it on the same logs with the output set to json and few different values for ```--max-items```. When I increase ```--max-items``` enough it shows ```"start_date": "01/Jan/2018","end_date": "31/Jan/2018"``` like I would expect.

The man page says I can't increase the number of max items for an html output. Is there a way I can adjust the date range that shows at the top right section of the page?

**Comment by allinurl** [comment]
Currently there's no way to adjust the date range other than changing the [hard-coded](https://github.com/allinurl/goaccess/blob/master/src/commons.h#L60) max number of choices. However, I do expect to have this option when the filtering **#117** feature is released.

**Comment by millsjustin** [comment]
I increased the hard-coded max number and recompiled. That's working for me for now. Thanks for your help with this!

**Comment by allinurl** [comment]
No problem. Stay tuned for the upcoming release :)
