### ISSUE TITLE
Unable to parse custom access log

### ISSUE THREAD

**Issue by gaurav865** [allinurl/goaccess#1006]
Hi,

I am unable to parse below log entries through goaccess. Pls help to set 

```
172.2.4.9 - - [03/Feb/2018:13:01:34 +0530] TIME:0 "POST /bakingapp/service HTTP/1.1" 200 455 303245 APPSERVER1:9098 - - "-"
172.2.4.9 - - [03/Feb/2018:13:01:44 +0530] TIME:0 "POST /bakingapp/entry?bridgeEndpoint=true&fldLoginUserId=37265222&fldSessionId=1593842712JJPNIISB&fldDeviceId=11&fldWebServerId=YG&fldTxnId=MNU&fldAppServerId=ZZ&fldLangId=eng&fldScrnSeqNbr=09&fldAppId=RS HTTP/1.1" 200 47433 170301 APPSERVER1:9098 - - "-"
172.2.4.9 - - [03/Feb/2018:13:01:46 +0530] TIME:0 "GET /bakingapp/entry?fldRequestId=&fldSessionId=238113242SWKWFOKRN&fldFcatSessionId=&fldOrgTxnId=CCB&fldScrnSeqNbr=01&fldClientSessionId=&fldRsaTxnId=&fldTxnId=CCB&fldAppId=RS&fldUserRefNo=&fldDateTime HTTP/1.1" 200 1312 79992 APPSERVER1:9098 - - "-"
172.2.4.9 - - [03/Feb/2018:13:01:53 +0530] TIME:0 "POST /bakingapp/entry HTTP/1.1" 200 766 166333 APPSERVER1:9098 - - "https://appuat.bankuat.com/bakingapp/entry?fldAppId=RS&fldTxnId=MNU&fldScrnSeqNbr=01&fldSessionId=2015367400ZEXWESWC&fldTxnRequest=accounts"
```

**Comment by allinurl** [comment]
Can you please describe fields so I can post the corresponding log-format?  Thanks.

**Comment by gaurav865** [comment]
If i remove TIME:0 from above log then i am able to parse the log using NCSA combined log format. 

Getting below error parsing the log with TIME:0 field

Token ‘OST’ doesn’t match specifier ‘%s’
Token ‘ET’ doesn’t match specifier ‘%s’

**Comment by allinurl** [comment]
As I said before, I'd need you to please describe each of the fields so I can come up with the right format.

**Comment by gaurav865** [comment]
Please refer below my apache logformat 

LogFormat “%h %l %u %t TIME:%T \”%r\” %>s %b %D %{WAS}e %{fldAppId}i %{fldScrnSeqNbr}i \”%{Referer}i\”” common

**Comment by allinurl** [comment]
This should do it:

    goaccess access.log --log-format='%h %^[%d:%t %^] %^"%r" %s %b %D %v %^' --date-format=%d/%b/%Y --time-format=%T --ignore-panel=OS --ignore-panel=BROWSERS --ignore-panel=REFERRING_SITES

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
