### ISSUE TITLE
Logback log format trouble with Date/Time

### ISSUE THREAD

**Issue by mike-robinson** [allinurl/goaccess#1010]
I have tried many, many combinations but cannot get goaccess to parse my log file. Apparently, it has to do with the data/time format the log has. Could you shed some light on this? Thanks.

I modified the goacc ess configuration file such that there are only a few uncommented sections:

```
time-format %H:%M:%S
date-format %b %d
log-format %d %T %v %p %c{0} - %q - %X{username} : %X{company}

```
I get the errors

```
IPv4/6 is required.
Format Errors - Verify your log/date/time format

```
The Logback pattern

    %d{MMM dd HH:mm:ss} %p %c{0} - %m - %X{username} : %X{company}

Sample log line

    Feb 12 15:29:29 LAPTOP-MHM31I0V INFO ComboDescriptionCell - ComboBox is going to be showed with 154 items. Current selection is -1  - Francisco Sepulveda  : Great Plains Stainless Company

Broken down

```
**_(%d)_** Feb 12 15:29:29 
**_(%p)_** LAPTOP-MHM31I0V 
**_(%c{0})_** INFO 
**_(%m)_** ComboDescriptionCell - ComboBox is going to be showed with 154 items. Current selection is -1 
_(- %X{username})_ - Francisco Sepulveda 
**_(: %X{company})_** : Great Plains Stainless Company
```

**Comment by mike-robinson** [comment]
You're correct. It is from an application running under Tomcat. Sorry to hear GoAccess is restricted to access logs. Thanks for your quick response.

**Comment by allinurl** [comment]
Closing this. FWIW **#845** may eventually give some flexibility to goaccess.
