### ISSUE TITLE
Hello, I would like to collaborate with your translator project in Spanish since it is my native language, I can translate any document that has text

### ISSUE THREAD

**Issue by LuigiBaute** [allinurl/goaccess#1013]

**Comment by allinurl** [comment]
Thank you for offering your help. French and Spanish were recently added per this [**PR**](https://github.com/allinurl/goaccess/issues/858#issuecomment-320257517) (#859). They will be shipped in the upcoming release. Stay tuned! 

As new features are added, I'd certainly appreciate your help on that. Please keep an eye on project for new features that may need a translation,
