### ISSUE TITLE
Help with parsing cloudwatch file.

### ISSUE THREAD

**Issue by brentski** [allinurl/goaccess#1015]
I am sending nginx logs to cloudwatch and then sending the cloudwatch logs to S3.  I have tried several of the built in log formats and then tried my hand  from reading the man pages for time formats.  I have had no luck parsing these.  Any help would be appreciated.  I have attached the first 10 or 12 lines of the log file.

[logs.txt](https://github.com/allinurl/goaccess/files/1729839/logs.txt)

**Comment by allinurl** [comment]
Please try this;

    goaccess logs.txt --log-format='%^ %h %^[%d:%t %^] %v "%r" %s %b "%R" "%u"' --date-format=%d/%b/%Y --time-format=%T

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.

**Comment by brentski** [comment]
Thank you so much! Look forward to working more with goaccess.
