### ISSUE TITLE
Static Resources Panel empty

### ISSUE THREAD

**Issue by jabiertxof** [allinurl/goaccess#1016]
Static Resources Panel empty in trunk (not sure how revision but has 1 or 2 weeks only.

In my log I have some css (like mycss.css?hash=XXXXXXX9) ans images in JPG, SVG and PNG formats (maybe more extensions but this 4 sure. .jpg files don't have ?hash).
I hope I can send a partial log soon and put my branch revision.

Thanks so much for this great piece of code!

**Comment by allinurl** [comment]
Please use `--all-static-files` to include static files that contain a query string.

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.

**Comment by jabiertxof** [comment]
Sorry for don reply fast, Im on middle of server migration...
Is a mine problem, Im logging static files in other file.
Sorry for the noise!

**Comment by allinurl** [comment]
@jabiertxof no problem. Glad you were able to figure it out :)

**Comment by jabiertxof** [comment]
Thanks!
