### ISSUE TITLE
Error occured at: src/parser.c - read_log - 2669

### ISSUE THREAD

**Issue by kete1987** [allinurl/goaccess#1018]
Hi, 

I have the following error when we invoke goaccess:

> GoAccess - version 1.2 - Mar  7 2017 06:40:58
> Config file: /etc/goaccess.conf
> 
> Fatal error has occurred
> Error occured at: src/parser.c - read_log - 2669
> Unable to open the specified log file. No such file or directory

My config file has the following:
```
time-format %H:%M:%S
date-format %d/%b/%Y
log-format %h %^[%d:%t %^] "%r" %s %b "%R" "%u"
```

And some example traces of my log are:
```
90.68.17.241 - - [17/Feb/2018:20:15:00 +0100] "GET /escudos.php HTTP/1.1" 200 195 "-" "Dalvik/2.1.0 (Linux; U; Android 7.0; SM-G935F Build/NRD90M)"
79.144.48.17 - - [17/Feb/2018:20:15:00 +0100] "GET /escudos.php HTTP/1.1" 302 249 "-" "Dalvik/2.1.0 (Linux; U; Android 5.1.1; SM-J500FN Build/LMY48B)"
```

Is something wrong in my log-format?
Thanks in advance!

**Comment by allinurl** [comment]
How did you invoke goaccess? The following should work:

    goaccess /path/access.log --log-format=COMBINED

**Comment by kete1987** [comment]
I usually try with  
`goaccess -f ${LOGFILE} -a > /var/www/html/report/report.html`
Using your command, it returns:
```
:~$ sudo goaccess /var/log/apache2/access.log.1518652800 --log-format=COMBINED

GoAccess - version 1.2 - Mar  7 2017 06:40:58
Config file: /etc/goaccess.conf

Fatal error has occurred
Error occured at: src/parser.c - read_log - 2669
Unable to open the specified log file. Device or resource busy
```

**Comment by allinurl** [comment]
You must be using the same log from a different process and thus goaccess can't open it. Please make sure no other process is using it and try again. This may help:

>     lsof +D /path
> 
> That will recurse through the filesystem under /path, so beware doing it on large directory trees.
> 
> Once you know which processes have files open, you can exit those apps, or kill them with the kill(1) or pkill command.

**Comment by kete1987** [comment]
Hi, 

It's solved, i had a rookie error (in my config file I had uncommented log-file parameter)

Thanks for your help, i close the issue

**Comment by allinurl** [comment]
@kete1987 Glad to hear that :)

**Comment by dshook** [comment]
For me this was caused by goaccess not being able to create the report file in the folder.  I had to manually create the report file first with `touch`
