### ISSUE TITLE
Problem translating nginx config format ($time_iso8601)

### ISSUE THREAD

**Issue by przemoc** [allinurl/goaccess#1019]
I wanted to try this tool, but I'm having a little problem in converting following nginx format, which I dubbed `iso8601_host_timed`:
```
$time_iso8601: $remote_addr $remote_user ($server_name) $host "$request" $status $body_bytes_sent [$request_time] "$http_referer" "$http_user_agent" "$http_x_forwarded_for"
```
I thought that following goaccess config should fit it:
```
date-format %F
time-format %T%:z
log-format %dT%t: %h %e (%^) %v "%r" %s %b [%T] "%R" "%u" "~h"
```
but it's not working. I verified that date+time-format is correct
```
$ date +%FT%T%:z
2018-02-17T23:14:07+01:00
```

Example from access.log:
```
2018-02-17T06:30:19+01:00: 46.229.164.98 - (przemoc.net) przemoc.net "GET /robots.txt HTTP/1.1" 404 162 [0.090] "-" "Mozilla/5.0 (compatible; SemrushBot/1.2~bl; +http://www.semrush.com/bot.html)" "-"
```

goaccess output:
```
Parsed 1 lines producing the following errors:

Token '06' doesn't match specifier '%t'

Format Errors - Verify your log/date/time format
```

I'm using goaccess 1.2 in debian stretch (from stretch-backports repository).
Can you help a bit in finding proper config?

**Comment by allinurl** [comment]
Give this a shot:

    goaccess access.log --log-format='%dT%t+%^ %h %^ %^ %v "%r" %s %b [%T] "%R" "%u" %^' --date-format=%Y-%m-%d --time-format=%T

**Comment by przemoc** [comment]
Your config worked, thanks! Let me comment it a bit.

Changing time-format from `%F` to `%Y-%m-%d` isn't necessary.

I see that part of the time problem could be `%:z` (`±hh:mm`), because it's non-POSIX thing (it's possibly more conforming to ISO 8601 time zone designators, though, but I'm not sure if using colon in TZ is truly required when time part already uses colon too, and I suspect it's not really necessary, yet that's what nginx does), but even with TZ notation stripped from inner colon in log, `%z` (`±hhmm`) still doesn't work. Is goaccess unable to parse TZ data? If yes, then your format wouldn't work in the west, where `+` would be replaced by `-` in time zone designators.

You replaced `%e` (nginx's `$remote_user`) with `%^`, which doesn't seem necessary here.

For a moment I was afraid that I should not surround ignoring specifier (`$^`), as you removed parentheses around nginx's `$server_name` (which doesn't have equivalent specifier in goaccess, that's why I went with `$^`), but it also isn't needed.

Last important thing is seemingly nginx's `$http_x_forwarded_for`, which you cannot capture within goaccess log-format using `~h` if you already have `%h` there.

It looks I'll go with following config for now:
```
log-format %dT%t+%^ %h %e (%^) %v "%r" %s %b [%T] "%R" "%u" %^
date-format %F
time-format %T
```
but having support for time zone designators in goaccess would be nice.

**Comment by allinurl** [comment]
Great points you brought here. As you noticed, goaccess doesn't yet support time zones, it will literally output whatever time zone your access log contains. Thus I stripped it in my previous comment. However, issue #496 plans to implement this.

Sorry, I totally missed the `$remote_user` from your question. `%e` should do the job.

For clarity you can certainly keep the parenthesis, though, I tend to keep the goaccess' log-format as short as possible.

GoAccess will attempt to extract the client IP address either by using `%h` OR  using `~h` in the case of `$http_x_forwarded_for`. In your example I ended up using `%h` since I assumed `$remote_addr` is the client IP. If you need to extract it from `$http_x_forwarded_for`, then you can do so using `~h`, just make sure you specified the delimiters used in `$http_x_forwarded_for`.

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.

**Comment by C-Cyborg** [comment]
Hi, any suggest about my nginx format?

'$http_x_forwarded_for - $remote_user [$time_iso8601] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent" $request_time $upstream_response_time $pipe $upstream_addr';

Thanks

**Comment by allinurl** [comment]
@C-Cyborg Please open a new issue and post a few lines from your log.
