### ISSUE TITLE
configure: error: *** Missing development libraries for ncursesw

### ISSUE THREAD

**Issue by solarcellsky** [allinurl/goaccess#102]
sudo ./configure --enable-geoip --enable-utf8
Password:
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... ./install-sh -c -d
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking for pthread_create in -lpthread... yes
checking for GeoIP_new in -lGeoIP... yes
checking for mvaddwstr in -lncursesw... no
configure: error: **\* Missing development libraries for ncursesw

Mac OS x 10.9.2

**Comment by xokvictor** [comment]
Tnx!

**Comment by szarouski** [comment]
I'm on debian 7, I had to install `apt-get install libncurses5-dev` to make it work.

**Comment by Wislow** [comment]
I had same problem, but I figure it out that I didn't have geoIP Library. So, I found this site and install the library. (My server is centOS)
http://www.spidersoft.com.au/2012/how-to-install-geoip-extension-on-centos/

yum install GeoIP-devel

and after install this library, I commanded, 

sudo ./configure --enable-geoip 

then Makefile was created (not Makefile.in or Makefile.am), and I could execute the command "make" ! 

hope somebody get help from this comment!
thanks.

**Comment by FelixZhu** [comment]
apt-get install libgeoip-dev
apt-get install libncurses5-dev

**Comment by allinurl** [comment]
Please use `libncursesw5-dev`. Table [here](http://goaccess.io/download#dependencies)

    # apt get install libncursesw5-dev libglib2.0-dev libgeoip-dev

**Comment by sjash** [comment]
I'm using Centos 6.6 and when I tried to install GeoIP-devel it is showing dependency for Geo-IP. But after downlaoding it,it is again asking for GeoIP-data and when I tried GeoIP-data it is asking for Geo-IP.

Please Help.Thanks in advance.

**Comment by allinurl** [comment]
Please try:

    yum install GeoIP GeoIP-devel GeoIP-data

Otherwise, please look take a look at this [answer](https://github.com/allinurl/goaccess/issues/243).

**Comment by swooningfish** [comment]
@Wislow You need to also pull the ncurses-devel 

 yum install ncurses-devel

**Comment by chhantyal** [comment]
For Ubuntu  `sudo apt-get install libgeoip-dev`

**Comment by ustcltx** [comment]
![image](https://cloud.githubusercontent.com/assets/6998333/20638834/dc12a2f4-b3ec-11e6-993c-ad3cbd64bf93.png)

can anyone help me ?

**Comment by ustcltx** [comment]
![image](https://cloud.githubusercontent.com/assets/6998333/20638855/c35bff20-b3ed-11e6-9dc8-fa11c8cec165.png)

 **I'd be grateful if anyone can help Me.**

**Comment by allinurl** [comment]
@ustcltx Seems like you are building from development? In any event, usually you have to do autoreconf again after installing any dep, please run:

    $ sudo autoreconf -fiv
    $ ./configure --enable-geoip --enable-utf8

**Comment by stonefury** [comment]
yum install geoip

**Comment by Rebolon** [comment]
for me on centos6 it worked with this: `sudo yum install ncurses-devel`

**Comment by thachnv92** [comment]
> apt-get install libgeoip-dev
> apt-get install libncurses5-dev

many thank ^^

**Comment by bor8** [comment]
What is the difference between

```
sudo apt update
apt-get install libncurses5-dev
```

and

```
sudo apt update
apt-get install libncursesw5-dev
```
?

**Comment by thachnv92** [comment]
> What is the difference between
> 
> ```
> sudo apt update
> apt-get install libncurses5-dev
> ```
> 
> and
> 
> ```
> sudo apt update
> apt-get install libncursesw5-dev
> ```
> 
> ?
> 
> Maybe: [avanov/ansible-galaxy-pyenv#44](https://github.com/avanov/ansible-galaxy-pyenv/issues/44)

It's difference.
libncurses5-dev # libncursesw5-dev

**Comment by allinurl** [comment]
@thachnv92 libncursesw5 - shared libraries for terminal handling (wide character legacy version).

**Comment by bor8** [comment]
What is a wide character?

**Comment by allinurl** [comment]
@bor8 https://en.wikipedia.org/wiki/Wide_character

**Comment by banbushi** [comment]
> [@Wislow](https://github.com/Wislow) You need to also pull the ncurses-devel
> 
> yum install ncurses-devel


this reslove my problem!
