### ISSUE TITLE
Apache Custom Log Format

### ISSUE THREAD

**Issue by TheHitchhiker** [allinurl/goaccess#1020]
Hello, I can't seem to figure out this custom log format for goaccess:

Apahce LogFormat:

    "%{Host}i:%p %a %l %u %t \"%r\" %>s %O \"%{Referer}i\" \"%{User-Agent}i\" %{%s}t %D %P"

Example:

    10.61.244.2:80 10.61.244.1 - - [18/Feb/2018:17:49:27 +0000] "GET /favicon.ico HTTP/1.1" 404 502 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:58.0) Gecko/20100101 Firefox/58.0" 1518976167 207 527

What I tried:
log-format "%H:%p %a %l %u %t "%r" %s %O "%R" "%u" \t%s %D %P

Can someone help me ?

**Comment by allinurl** [comment]
Please try this:

    goaccess access.log --log-format='%h: %^[%d:%t %^] "%r" %s %b "%R" "%u" %^ %D %^' --date-format=%d/%b/%Y --time-format=%T

**Comment by TheHitchhiker** [comment]
It works perfectly. Thank you !

**Comment by allinurl** [comment]
Glad to hear that :)
