### ISSUE TITLE
No time format was found on your conf file.?

### ISSUE THREAD

**Issue by EnricoSx** [allinurl/goaccess#1021]
GoAccess - version 0.9.4
ubuntu 16.04 
nginx

    goaccess -f /var/log/nginx/access.log --log-format=COMBINED -o /var/www/shopthanks.com/html/goaccess.html

```
GoAccess - version 0.9.4 - Feb  7 2016 10:13:32
Config file: /etc/goaccess.conf

Fatal error has occurred
Error occured at: src/parser.c - verify_formats - 1807
No time format was found on your conf file.
```

[goaccess.conf.txt](https://github.com/allinurl/goaccess/files/1736801/goaccess.conf.txt)
Linux webserver 4.4.0-112-generic #135-Ubuntu SMP Fri Jan 19 11:48:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
`

**Comment by allinurl** [comment]
Please use the latest version of goaccess in order to use `--log-format=COMBINED` otherwise you'd need to uncomment the log/date/time formats in your goaccess.conf

**Comment by EnricoSx** [comment]
i used apt , ok i download the latest

**Comment by allinurl** [comment]
did it work this time?

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.

**Comment by chamdan55** [comment]
what the meaning uncomment log/date/time format?

**Comment by allinurl** [comment]
@chamdan55 You either need to specify those three options as command line options or via the config file (meaning remove the leading `#`).
