### ISSUE TITLE
No output from command (cygwin)

### ISSUE THREAD

**Issue by warrenspe** [allinurl/goaccess#1022]
Hi there!

I'm trying to analyze a static log file on my machine using goaccess 1.2 over cygwin.

I am testing using a simple log file:
```
$ cat test.log
127.0.0.1 user-identifier frank [10/Oct/2000:13:55:36 -0700] "GET /apache_pb.gif HTTP/1.0" 200 2326
```

```
$ goaccess test.log --log-format=COMMON -o test.json

$ echo $?
0

$ ls
test.log
```

I'm not entirely sure what I'm doing wrong here .. any assistance anyone could provide would be much appreciated!

Cheers,

Warren

**Comment by allinurl** [comment]
Did it output `test.json`? Looks like `echo $?` shows that it succeed.

**Comment by allinurl** [comment]
My bad ignore my previous comment...

**Comment by allinurl** [comment]
Let me test this on cygwin. Just ran a test on a linux box and it did output `test.json`. BTW, are you using a specific version of cygwin?

**Comment by warrenspe** [comment]
Howdy!

I'm using Cygwin V `2.10.0(0.325/5/3)`

**Comment by allinurl** [comment]
Just tested this on

    CYGWIN_NT-6.1 user-PC 2.10.0(0.325/5/3) 2018-02-02 15:16 x86_64 Cygwin

However I do get a `test.json` out of it. Could you please attach your test.log so I can run it against the exact same file? Thanks.

**Comment by warrenspe** [comment]
First thing when I'm back in the office tomorrow morning. Assuming that it does work for you though, are there any debugging logs or something along those lines which I could use to try to pin down the problem?  Worst case scenario, I can recompile and try stepping through with gdb if I can figure out whereabouts in the source to look for problems

**Comment by allinurl** [comment]
You could configure with `--enable-debug` and then use `--log-debug=<filename>`, though, I'm not sure it will output something useful since `$ echo $? = 0`. 

If my memory doesn't fail, I do remember a similar report a while back, but I can't remember if it was due to \r\n on Windows or something else. I'll see if I can find it. Also, can I ask you to try to build from [**development**](https://github.com/allinurl/goaccess#build-from-github-development) and see if the issue is present in there? Thanks

**Comment by warrenspe** [comment]
Mmm; I think I know what the problem is, and I don't think it has to do with goaccess - I'm presuming goaccess uses threads?  For some reason my cygwin distribution crashes whenever it runs a threaded program, returning an error code of 0 regardless of what it ran.  (I'd forgotten it did that..).

My apologies for the wild goose chase!

**Comment by allinurl** [comment]
It does fire up a few threads. No worries. Glad you were able to find the problem. Feel free to reopen this if needed.
