### ISSUE TITLE
HTML does not work using Ubuntu's 16.04 package

### ISSUE THREAD

**Issue by acklenx** [allinurl/goaccess#1024]
I'm trying to get this command to work 

    goaccess /var/log/apache2/access.log -o ~/report.html --log-format=COMBINED --real-time-html

but I get this error:

> goaccess: unrecognized option '--real-time-html'

I have a fresh apache2 install on a fresh ubuntu 16.04 install after installing goaccess I CAN run this command just fine (it's very nice):

    goaccess -f /var/log/apache2/access.log

and after selecting "NCSA Combined Log Format" I can then see the report
I can also select "Common Log Format  (CLF)" and get a report
...but anything other format selection fails and says invalid format... but that's expected.

other commands that fail:

    goaccess -f /var/log/apache2/access.log -o ~/report.html

> Fatal error has occurred
> Error occured at: src/parser.c - verify_formats - 1807
> No time format was found on your conf file.

    goaccess /var/log/apache2/access.log -o ~/report.html

Shows options

    goaccess /var/log/apache2/access.log -o ~/report.html --log-format=COMBINED

Shows options

What am I missing?  I figured after a fresh install of OS, Apache, and goaccess it would work...but I'm am mistaken

**Comment by allinurl** [comment]
From your output, I'm guessing you are using an old version of goaccess. Ubuntu's repo doesn't usually keep the latest packages. Please consider using the [**official repo**](https://goaccess.io/download#official-repo) or building from source. 

The latest version should let you run those commands. Let me know how it goes. Thanks.

**Comment by acklenx** [comment]
It's beautiful!!

thanks, after the update from the official repo to a current version it works.

**Comment by allinurl** [comment]
Great to hear that :) Closing this.
