### ISSUE TITLE
nohup Unable to open the specified log file

### ISSUE THREAD

**Issue by l36t** [allinurl/goaccess#1025]
When I excute : 

    nohup /usr/local/goaccess/bin/goaccess /usr/local/goaccess/bin/logs/1550/xtougu.access.log  -p /root/.goaccessrc  -o /usr/local/nginx/html/realtime.html --real-time-html &

The error log shows :

```
Fatal error has occurred
Error occured at: src/parser.c - read_log - 2669
Unable to open the specified log file. No such file or directory

```

If I remove nohup,It works ok.How to solve this problem?

**Comment by allinurl** [comment]
You can try daemonizing it instead,

    /usr/local/goaccess/bin/goaccess /usr/local/goaccess/bin/logs/1550/xtougu.access.log -p /root/.goaccessrc -o /usr/local/nginx/html/realtime.html --real-time-html --daemonize

**Comment by allinurl** [comment]
Any updates?

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.

**Comment by sakuya-go** [comment]
I have the same problem, nohup dosen't work, but I find another way to solve it, use tmux tool, it is more practical.

**Comment by zyzypy** [comment]
--daemonize  works
