### ISSUE TITLE
GeoIP with IPv6 and IPv4 doesn't work

### ISSUE THREAD

**Issue by Bodenhaltung** [allinurl/goaccess#1026]
Hi,

if i load the v6 Database, i get no IPv4 adresses resolved and if i load the v4 i get only the v4 resolved. In the v6 database are already the v4 addresses included, i see that directly in nginx worked fine.

**Comment by allinurl** [comment]
I think you need to provide two separate databases to get IPv4 and IPv6 working, #594 will address that. I can't find any docs that IPv6 databases will resolve IPv4 addresses.

**Comment by allinurl** [comment]
Closing as it's a duplicate from #594.

Feel free to reopen it if needed.
