### ISSUE TITLE
Caddy log format

### ISSUE THREAD

**Issue by midzer** [allinurl/goaccess#1027]
Hi all,
great project first of all :+1: 
Following getting started section, I have issues configuring log format for Caddy server.

Default format in `access.log`:
```
11.11.11.11 - - [24/Feb/2018:10:47:27 +0100] "GET / HTTP/2.0" 304 0
11.11.11.11 - - [24/Feb/2018:10:47:28 +0100] "GET /assets/css/main.css HTTP/2.0" 304 0
```
I've masked IPv4 but it could be IPv6 as well.

Thanks for your support and have a nice day
midzer

**Comment by allinurl** [comment]
Looks like COMMON log format. Please try:

    goaccess access.log --log-format=COMMON

**Comment by midzer** [comment]
After upgrading to Official GoAccess Debian & Ubuntu repository, it worked flawlessly with COMMON log format. Thanks @allinurl

**Comment by allinurl** [comment]
Glad that did the job :)
