### ISSUE TITLE
Feature: some "crossing" over data

### ISSUE THREAD

**Issue by Geobert** [allinurl/goaccess#1028]
Hi,

I just discover goaccess and I'm very impressed. I was looking for some analytics without database and PHP for my static web site and goaccess is doing a quite nice job for this!

However, it would be nice to have some crossing accross some data. For example:
* unfold one request to see where it come from (crossing requests with visitor host)
* unfold visitor host to see which request it has done (crossing visitor host with requests)

same for not found url and so on…

Cheers!

**Comment by allinurl** [comment]
Glad to hear you found it useful! Great suggestions, I plan to have these features as part of #117. Please stay tuned for the upcoming versions.

**Comment by allinurl** [comment]
Closing this as it's a duplicate from #117. Feel free to reopen it if needed.
