### ISSUE TITLE
netdata log_format not working: token already set for '%r' specifier

### ISSUE THREAD

**Issue by gllmhyt** [allinurl/goaccess#1029]
I'm using a [custom Nginx log_format](https://github.com/firehol/netdata/blob/master/conf.d/python.d/web_log.conf#L98) from netdata:

    log_format netdata '$remote_addr - $remote_user [$time_local] '
                   '"$request" $status $body_bytes_sent '
                   '$request_length $request_time $upstream_response_time '
                   '"$http_referer" "$http_user_agent"';
    access_log /var/log/nginx/access.log netdata;

Therefore I used [nginx2goaccess](https://github.com/stockrt/nginx2goaccess) to produce the GoAccess configuration lines. It gave me this:

    $ ./nginx2goaccess.sh '$remote_addr - $remote_user [$time_local] "$request" $status $body_bytes_sent $request_length $request_time $upstream_response_time "$http_referer" "$http_user_agent"'

    - Generated goaccess config:
    time-format %T
    date-format %d/%b/%Y
    log_format %h - %^ [%d:%t %^] "%r" %s %b %r_length %T %^ "%R" "%u"

I restarted the Nginx service then rotated it's logs, then restarted GoAccess. But it's giving me this error:

    Format Errors - Verify your log/date/time format
    /var/log/nginx/access.log
    Parsed 10 lines producing the following errors:

    Token already set for '%r' specifier.
    Token already set for '%r' specifier.
    Token already set for '%r' specifier.
    Token already set for '%r' specifier.
    Token already set for '%r' specifier.
    Token already set for '%r' specifier.
    Token already set for '%r' specifier.
    Token already set for '%r' specifier.
    Token already set for '%r' specifier.
    Token already set for '%r' specifier.

Here's the 10 first lines of my ```access.log```:

 ```
2a02:578:854a:600:7527:d90:264f:4d5 - - [25/Feb/2018:12:53:17 +0100] "GET /api/v1/alarms?active&_=1519558522977 HTTP/2.0" 200 732 "https://ns3003126.postblue.info/" "Mozilla/5.0 (X11; Linux x86_64; rv:59.0) Gecko/20100101 Firefox/59.0"
2a02:578:854a:600:7527:d90:264f:4d5 - - [25/Feb/2018:12:53:17 +0100] "GET /api/v1/alarms?active&_=1519558522977 HTTP/2.0" 200 732 266 0.008 0.008 "https://ns3003126.postblue.info/" "Mozilla/5.0 (X11; Linux x86_64; rv:59.0) Gecko/20100101 Firefox/59.0"
91.121.109.55 - - [25/Feb/2018:12:53:19 +0100] "GET /autoblogs/wwwinternetactunet_8a3fe3331e0ad7327e18d9fe6ec3f0ad04dcea58/?Retour-%C3%A0-la-normal HTTP/1.1" 404 134 "-" "Mozilla/5.0 (compatible; MJ12bot/v1.4.8; http://mj12bot.com/)"
91.121.109.55 - - [25/Feb/2018:12:53:19 +0100] "GET /autoblogs/wwwinternetactunet_8a3fe3331e0ad7327e18d9fe6ec3f0ad04dcea58/?Retour-%C3%A0-la-normal HTTP/1.1" 404 134 464 0.000 - "-" "Mozilla/5.0 (compatible; MJ12bot/v1.4.8; http://mj12bot.com/)"
2a02:578:854a:600:7527:d90:264f:4d5 - postblue [25/Feb/2018:12:53:21 +0100] "PROPFIND /remote.php/dav/files/postblue/ HTTP/1.1" 207 527 "-" "Mozilla/5.0 (Linux) mirall/2.3.3 (Nextcloud)"
2a02:578:854a:600:7527:d90:264f:4d5 - postblue [25/Feb/2018:12:53:21 +0100] "PROPFIND /remote.php/dav/files/postblue/ HTTP/1.1" 207 527 747 0.310 0.310 "-" "Mozilla/5.0 (Linux) mirall/2.3.3 (Nextcloud)"
2001:41d0:98:bb01::9 - - [25/Feb/2018:12:53:23 +0100] "GET /feed/ HTTP/1.1" 301 178 "-" "Tiny Tiny RSS/17.12 (e7c9bc6) (http://tt-rss.org/)"
2001:41d0:98:bb01::9 - - [25/Feb/2018:12:53:23 +0100] "GET /feed/ HTTP/1.1" 301 178 153 0.000 - "-" "Tiny Tiny RSS/17.12 (e7c9bc6) (http://tt-rss.org/)"
2001:41d0:98:bb01::9 - - [25/Feb/2018:12:53:23 +0100] "GET /feed/ HTTP/1.1" 301 39 "-" "Tiny Tiny RSS/17.12 (e7c9bc6) (http://tt-rss.org/)"
2001:41d0:98:bb01::9 - - [25/Feb/2018:12:53:23 +0100] "GET /feed/ HTTP/1.1" 301 39 153 0.026 0.026 "-" "Tiny Tiny RSS/17.12 (e7c9bc6) (http://tt-rss.org/)"
```

I've read [the list of specifiers here](https://goaccess.io/man#custom-log) but I don't understand where it's failing. Can you please help? Thank you.

**Comment by allinurl** [comment]
Please try this:

    goaccess access.log --log-format='%h %^ %e [%d:%t %^] "%r" %s %b %^ %T %^ "%R" "%u"' --date-format=%d/%b/%Y --time-format=%T

One thing, looks like some of your requests are missing some fields which could cause inconsistencies, e.g.,

    '$request_length $request_time $upstream_response_time '

```
2001:41d0:98:bb01::9 - - [25/Feb/2018:12:53:23 +0100] "GET /feed/ HTTP/1.1" 301 39 "-" "Tiny Tiny RSS/17.12 (e7c9bc6) (http://tt-rss.org/)"
2001:41d0:98:bb01::9 - - [25/Feb/2018:12:53:23 +0100] "GET /feed/ HTTP/1.1" 301 39 153 0.026 0.026 "-" "Tiny Tiny RSS/17.12 (e7c9bc6) (http://tt-rss.org/)"
```

**Comment by gllmhyt** [comment]
I tried your configuration and at least I can run GoAccess again, thank you.
I will look after the missing length, time, etc. Do you have a suggestion where to start looking?

**Comment by allinurl** [comment]
To me they look like a duplicate entry of the same request. If you are forwarding the logs to a centralize server, then that could be an issue. Or it could simply be an nginx config issue.  log directives within a Server Blocks can conflict with log directives from the "Main" configuration sections.

Closing this, feel free to reopen it if needed.
