### ISSUE TITLE
Goaccess docker ssl-cert unrecognized

### ISSUE THREAD

**Issue by panromir** [allinurl/goaccess#1030]
Hello there,

in reference to this issue: https://github.com/allinurl/goaccess/issues/807
I have been using the latest remote Docker image and it has been throwing me the same error, which means I can't use the Webhook for real-time html.

```goaccess: unrecognized option: ssl-cert```

**Comment by allinurl** [comment]
Please make sure to build your image using `--with-openssl`, e.g.,

    ./configure --enable-utf8 --enable-geoip=legacy --with-openssl

**Comment by stoyandimov** [comment]
Hi @allinurl,

I'm using docker hub's [allinurl/goaccess](https://hub.docker.com/r/allinurl/goaccess/) in my docker-compose file. This one also appears to be built without the `--with-openssl` flag.

Have you considered adding SSL support to that image in the near future, or should we better build our own goaccess with `--with-openssl` and create a new image?

**Comment by stoyandimov** [comment]
Hi again,

I slightly changed the `Dockerfile` and rebuilt the image. I also decided to share the update (PR https://github.com/allinurl/goaccess/pull/1036).

Let me know what you think.

**Comment by allinurl** [comment]
PR merged. It's now built using `--with-openssl` Thank you.
