### ISSUE TITLE
Lot's of undescribed traffic

### ISSUE THREAD

**Issue by Ralle** [allinurl/goaccess#1031]
Hey guys,

I would like to know what's up with this:
![screenshot 2018-02-27 10 42 31](https://user-images.githubusercontent.com/467309/36721359-fcad5b0e-1baa-11e8-8f07-c8f0b53ff52e.png)

I am getting the sense that this is happening with link rewrites or something.

I am running Nginx, here is my config:
```
time-format %H:%M:%S
date-format %d/%b/%Y
log-format %h %^[%d:%t %^] "%r" %s %b "%R" "%u"
```

Here is a typical line
`85.167.134.7 - - [27/Feb/2018:09:16:30 +0000] "GET /misc/ra-profile-post-script?_v=348b8632 HTTP/2.0" 200 393 "https://www.hiveworkshop.com/threads/warcraft-iii-patch-1-29-ptr.303503/page-13" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36"
`

Is it because certain lines are not parsed or what?

**Comment by allinurl** [comment]
Looks like your server may not be processing some requests or perhaps you are getting bogus requests from specific clients. You can probably find these requests as:

    cat /var/log/nginx/access.log | awk '{print $6}'

**Comment by Ralle** [comment]
I got a few SSL_do_handshake which I filtered out with grep and it still happens. The rest are GET, POST a few HEAD and one OPTIONS.

Is there no way to have the program output the lines with no URL?

**Comment by Ralle** [comment]
The thing I am wondering about is the first line. Is it a summary or is it log lines not being parsed?

**Comment by Ralle** [comment]
I think this might be a duplicate of #319.

**Comment by allinurl** [comment]
It looks like you are using an old version (<1.0) of goaccess. I'd definitely recommend upgrading to the latest version and see if the issue is fixed in there. Please let me know.

BTW, if you are using debian/ubuntu, you may want to either build from [source](https://goaccess.io/download#installation) or use the [official deb repo](https://goaccess.io/download#official-repo).

**Comment by Ralle** [comment]
Yeah. I was on 0.9.4. I fixed it this way instead:

        cat access.log | sed --expression='s/HTTP\/2.0/HTTP\/1.1/g' | goaccess

**Comment by allinurl** [comment]
Glad to hear that fixed the issue :+1:
