### ISSUE TITLE
Complete Apache status codes

### ISSUE THREAD

**Issue by szepeviktor** [allinurl/goaccess#1037]
Please consider adding new statuses, mainly 4xx
https://ci.apache.org/projects/httpd/trunk/doxygen/group__HTTP__Status.html
Thank you.

**Comment by allinurl** [comment]
These have been updated. Closing this. Feel free to reopen it if needed.

**Comment by szepeviktor** [comment]
Thank you

**Comment by szepeviktor** [comment]
You may add `Closes #1037` to the commit message to automatically close the issue
https://github.com/allinurl/goaccess/commit/828127f2be45ad8cda8b1d5a83aa93ff1078657b
