### ISSUE TITLE
Chinese localization?

### ISSUE THREAD

**Issue by aishikoyo** [allinurl/goaccess#1043]
It will be great if you could add a Chinese language pack in goaccess. Do you have plans for that? Please let me know.

**Comment by allinurl** [comment]
It would be great if we could add Chinese. Would you be able to translate the relevant labels? All the i18n plumbing has been done (gettext) and it'll be out in the next release. [**Here**](https://github.com/allinurl/goaccess/blob/master/src/labels.h) are the labels that need to be translated.

These are the steps:

1. Add `zh_CN` to the po/LINGUAS
2. Create a `po/zh_CN.po` file and add all your translations in there. See [fr.po](https://github.com/allinurl/goaccess/blob/master/po/fr.po)
3. run `intltool-update zh_CN` inside the po folder
4. run `intltool-update --pot`
5. Please submit a PR so I can merge it here.

If your locale is set to `zh_CN`, goaccess' output will automatically display its content in Chinese.

Let me know if you have any questions. Thanks!

**Comment by aishikoyo** [comment]
No problem! I would love to translate the labels. I will do a PR after it's done.

**Comment by allinurl** [comment]
Thanks very much! This has been added. Here's a screenshot:

![goaccess-chinese](https://user-images.githubusercontent.com/5005367/37741464-7fecec56-2d2f-11e8-8a7f-6b2ff0610887.png)

Let me know if that looks/reads well.

**Comment by StrongFu** [comment]
Hello, cowaxess_x64 has been installed under Windows system, how to implement the output report.html file is in Chinese？thinks!

remark: Execute export lang=zh_ CN. UTF-8 is invalid

**Comment by allinurl** [comment]
@StrongFu please feel free to post this question under https://github.com/allinurl/goaccess/issues/1505
