### ISSUE TITLE
Too many failed requests

### ISSUE THREAD

**Issue by eibravomacias** [allinurl/goaccess#1044]
Hello,
First of all I would like to thank you for such an amazing tool.
Having said that I have a question about the failed requests number that I'm getting.
I've been saving the failed requests in a file and I don't understand why they're registering as failed if the reponse is a HTTP 200 99% of the time.
Here are some examples:

```
[13/Mar/2018:16:54:35 +0100] [www.funiber.org:443] [client 181.201.145.255] "GET /themes/funiber/css/global.min.css?p5hyh2 HTTP/1.1" 200 17419 "Mozilla/5.0 (Linux; Android 7.0; 9008A Build/NRD90M) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.137 Mobile Safari/537.36"
[13/Mar/2018:16:54:36 +0100] [www.funiber.org:443] [client 181.49.111.222] "GET /core/assets/vendor/jquery/jquery.min.js?v=2.2.4 HTTP/1.1" 200 29822 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36"
[13/Mar/2018:16:54:37 +0100] [www.funiber.org:443] [client 181.201.145.255] "GET /core/misc/drupalSettingsLoader.js?v=8.3.7 HTTP/1.1" 200 394 "Mozilla/5.0 (Linux; Android 7.0; 9008A Build/NRD90M) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.137 Mobile Safari/537.36"
[13/Mar/2018:16:54:37 +0100] [www.funiber.org.br:443] [client 197.158.6.151] "POST /libraries/websites/forms HTTP/1.1" 200 5470 "Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36"
[13/Mar/2018:16:54:38 +0100] [www.funiber.org:443] [client 181.177.139.208] "GET /sites/default/files/2017-11/santacruz.png HTTP/1.1" 200 90531 "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko"
```
Is there any way a could know why are these requests marked as failed?

Thank you in advance.

**Comment by allinurl** [comment]
Could you please post the log/date/time-format you are using? Also, if lines are longer than 4096, then you want to build using `--with-getline`.

**Comment by eibravomacias** [comment]
This is the log format I use:

--log-format='[%d:%t %^] [%v:%^] [%^ %h] "%r" %s %b "%u"'

**Comment by allinurl** [comment]
Can you please post the date and time-format as well? Thanks

**Comment by eibravomacias** [comment]
Here's the requested info:

--log-format='[%d:%t %^] [%v:%^] [%^ %h] "%r" %s %b "%u"' --date-format=%d/%b/%Y --time-format=%T

**Comment by allinurl** [comment]
Strange, can I ask you to please parse the exact same log again and see if you still get those invalid lines? BTW, how are you retrieving these invalid requests?

**Comment by eibravomacias** [comment]
Still getting those invalid requests. I use --invalid-requests=failed.log to get them.

**Comment by allinurl** [comment]
Have you tried building using `--with-getline` and see if that solves the issue? 

Otherwise, I'd probably need either the whole access log or at least a portion of it (containing a few of the failing lines and a few that are successful). Thanks.

**Comment by eibravomacias** [comment]
I tried using --with-getline but it fails to recognize that option.
I'll upload a portion of the access log. Hope you can help me detect what's the issue.

[ssl_access.log](https://github.com/allinurl/goaccess/files/1813333/ssl_access.log)

**Comment by allinurl** [comment]
I parsed your sample log and I don't get any failed requests. Are you in the latest version? Did you build as:

    $ ./configure --with-getline --enable-utf8 --enable-geoip=legacy
    $ make
    # make install

**Comment by eibravomacias** [comment]
Hello,
I did it all over again and built it as you said but I'm still getting the same amount of failed requests (at least one per second).
Here's what I'm using:
tail -f -n +0 /var/log/apache2/funiber*/*access.log | grep "^\[" | goaccess -o /var/www/html/report.html --log-format='[%d:%t %^] [%v:%^] [%^ %h] "%r" %s %b "%u"' --date-format=%d/%b/%Y --time-format=%T --ignore-panel=REFERRING_SITES --real-time-html --port=10000

**Comment by allinurl** [comment]
First, I'd try running goaccess without tail nor grep and parse the log with goaccess only and see how many failed requests you get. Also, what output are you getting with:

    tail -f -n +0 /var/log/apache2/funiber*/*access.log | grep "^["

or

    tail -f -n +0 /var/log/apache2/funiber*/*access.log | grep "^["  > /tmp/test.log

Please make sure it's outputting the lines as you expect and in fact match your `log-format`.

BTW, did you parse the sample log you posted above and did you get any failed requests?

**Comment by eibravomacias** [comment]
The thing is I need to parse several log files from different directories. That's why I use tail and grep (to parse the lines I need). If I run `tail -f -n +0 /var/log/apache2/funiber*/*access.log | grep "^\["` I do get the info I expect in the right log format.
When I parse the log file from the beginning it doesn't get any failed requests, but when it starts reading the logs in real time it does. It's weird.

**Comment by allinurl** [comment]
> did you parse the sample log you posted above and did you get any failed requests?

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.

**Comment by jupitergao** [comment]
I have this problem, too. When I " tail -f xxx | grep yyy | goaccess - " , grep output break lines, " tail -f xxx | grep **--line-bufferd** yyy | goaccess - " work fine.
