### ISSUE TITLE
goaccess not working with cron and not showing full log

### ISSUE THREAD

**Issue by AndreasJacobsen** [allinurl/goaccess#1047]
hello, I can manually run GoAccess just fine with the command
`sudo goaccess -f /var/log/nginx/access.log -a > /var/www/logs/report.html`

but when trying to run the same command in cron I just get an empty output. 
`PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
0 * * * * sudo goaccess -f /var/log/nginx/access.log -a > /var/www/logs/report.html`

it also seems that the log file goes way further back than GoAccess actually shows, I'd really appreciate it if someone could help :)

**Comment by allinurl** [comment]
You probably want to add it to root's crontab instead.

    sudo crontab -e

and then try adding:

    goaccess /var/log/nginx/access.log -a -o /var/www/logs/report.html

Otherwise you could write a bash script with goaccess on it and run the script from the cron. Let me know if that solves the issue.

**Comment by AndreasJacobsen** [comment]
that fixed it, thanks!

**Comment by allinurl** [comment]
Glad to hear that :)
