### ISSUE TITLE
when run from crontab, does not work?

### ISSUE THREAD

**Issue by Geobert** [allinurl/goaccess#1048]
This will be a bit complicated but I don't know where to ask after searching for a month.

I took my inspiration from https://www.tombrossman.com/blog/2017/faster-and-more-accurate-analytics-with-goaccess/

but with some changes.

I have `functions.sh`:
```sh
BLACKLIST='/home/geob/goaccess/spammers.txt'

process_log_worker() {
grep --line-buffered -E "GET /posts/.*/ H" | goaccess --config-file /home/geob/.goaccess.conf $(printf -- "--ignore-referer=%s " $(<$BLACKLIST)) --no-progress  ;
}

process_log() { if [[ -z "$1" ]]; then process_log_worker; else process_log_worker <<< "$1"; fi ; }
```

`incremental_cat_access_log.sh` (the workaround given by @allinurl):
```sh
LOG=/var/log/nginx/access.log
LASTREAD=/home/geob/goaccess/cron/goaccess.last

OFFSET=$(sed -n '$=' $LOG)
START=1
if [[ -s $LASTREAD ]]; then
  START=$(<$LASTREAD)
  START="$(($START + 1))"
fi

sed -n $START','$OFFSET'p' < $LOG
echo "$OFFSET" > "$LASTREAD"
```

Then `cron-goaccess.sh`:
```sh
#!/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

source /home/geob/goaccess/cron/functions.sh

cd /home/geob/goaccess/cron

/home/geob/goaccess/cron/incremental_cat_access_log.sh | process_log
```

if I run the script manually, all is working.

If I let crontab launch the script, I have no error, the report.html is generated (the timestamp matches) but the data are not updated. 

I have no idea why. Please send help ^^'

here the cron job:
`0,30 * * * * /home/geob/goaccess/cron/cron-goaccess.sh >> /home/geob/goaccess/cron/cron.log 2>> /home/geob/goaccess/cron/cron.err`

EDIT: I found something related https://askubuntu.com/a/330717

but I'm already sending the content in a pipe

EDIT2: my config has this:
```
keep-db-files true

# On-disk B+ Tree
# Load previously stored data from disk.
# Database files need to exist. See `keep-db-files`.
load-from-disk true

# On-disk B+ Tree
# Path where the on-disk database files are stored.
# The default value is the /tmp/ directory
# Note the trailing forward-slash.
#
db-path /home/geob/goaccess/
```

**Comment by Geobert** [comment]
I begin to think that de DB stuff is not working while running in `cron` :-/

**Comment by allinurl** [comment]
Can you try adding `-`. e.g.,

    grep --line-buffered -E "GET /posts/.*/ H" | goaccess - --config-file /home/geob/.goaccess.conf $(printf -- "--ignore-referer=%s " $(<$BLACKLIST)) --no-progress  ;

and run it from the cron again. Let me know if that solves the issue.

**Comment by Geobert** [comment]
It works! Thanks!

Can you explain me what's going on? My script skills are way rusty (not done any for years) ^^

**Comment by allinurl** [comment]
Per convention, the extra dash tells goaccess to read from the standard input. This is needed since the cron doesn't give a TTY so `isatty(3)` fails when no filename is passed.
