### ISSUE TITLE
Get monthly records with needing to specify day number.

### ISSUE THREAD

**Issue by robertmylne** [allinurl/goaccess#1050]
If we want to parse only a certain time-frame from DATE a to DATE b, we can do:
`# sed -n '/5\/Nov\/2010/,/5\/Dec\/2010/ p' access.log | goaccess -a -`

How can I do something similar to this, but just get the records for a month?

Example: everything in `Feb 2010`, so I don't need to calculate whether it is a leap year or how many days are in the month etc etc.

**Comment by allinurl** [comment]
You could simply do:

    grep 'Mar\/2018' /var/log/apache2/access.log | goaccess --log-format=COMBINED

or you can play also with `date`, e.g. to get only today's entries,

    grep `date +"%d/%b"` /var/log/apache2/access.log | goaccess --log-format=COMBINED

**Comment by robertmylne** [comment]
Perfect thank you :)

Could I please ask if you have an example for getting data for a single hour as well?

**Comment by allinurl** [comment]
Glad to hear that worked:)

You can do something like (assuming you have a COMBINED log)

    awk -F'[: ]' '$5~/06/' /var/log/apache2/access.log | goaccess --log-format=COMBINED -

That will match the hour field (fifth) to 06 (6am).

And you can always combine multiple pipes, e.g.,

    grep 'Mar\/2018' /var/log/apache2/access.log | awk -F'[: ]' '$5~/06/'  | goaccess --log-format=COMBINED -

This should get much easier when #117 is implemented :)

**Comment by robertmylne** [comment]
Thank you for your help :)

Is there a way to do it for multiple files at the same time, like in cPanel it has 2 files one for ssl and one for non ssl. So if the domain has been changed it is spread over multiple log files.

**Comment by allinurl** [comment]
> Is there a way to do it for multiple files at the same time, like in cPanel it has 2 files one for ssl and one for non ssl. So if the domain has been changed it is spread over multiple log files.

For multiple files you can simply cat those files and then grep as above. e.g.,

    cat /var/log/apache2/access.log /var/log/apache2/access-ssl.log | grep 'Mar\/2018' | awk -F'[: ]' '$5~/06/'  | goaccess --log-format=COMBINED -

**Comment by allinurl** [comment]
Closing this. Feel free to reopen if needed.
