### ISSUE TITLE
How to specify the XFF field in GoAccess?

### ISSUE THREAD

**Issue by herzcthu** [allinurl/goaccess#1059]
I'm getting "Token for '%h' specifier is NULL." when I use ~h in my log-format.
My web access log format is
```
LogFormat "%{X-Forwarded-For}i %h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" proxy
```
my goaccess log-format is
```
log-format ~h %h %^ %^ %^ [%d:%t %^] "%m %U %H" %s %b "%R" "%u"
```

**Comment by allinurl** [comment]
You need to specify the delimiters as noted in the [**man page**](https://goaccess.io/man#custom-log) if you are using `~h`. Or you can simply use `%h`

**Comment by allinurl** [comment]
Any updates on this?

**Comment by herzcthu** [comment]
I do not have quote in XFF field.
I would like to know if ~h{,} is valid.

**Comment by allinurl** [comment]
That looks valid. Can you please post a few sample lines that I can look into it? Thanks.

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.

**Comment by herzcthu** [comment]
Please check this invalid log.
I've replaced actual url path with * because it has some private data from my job.
This is log format I've used -
log-format ~h{,} %h %^ %^ [%d:%t %^] "%m %U %H" %s %b "%R" "%u"

`
45.112.176.45 162.158.166.195 - - [31/May/2018:00:00:00 +0630] "GET ********************HTTP/1.1" 200 409 "-" "Dalvik/2.1.0 (Linux; U; Android 8.0.0; ONEPLUS A5010 Build/OPR1.170623.032)"
45.112.176.45 162.158.166.195 - - [31/May/2018:00:00:00 +0630] "POST ********************HTTP/1.1" 200 2831 "-" "Android Mobile;11160;;Android;8.0.0;OnePlus;OnePlus5T;1080x2034"
45.112.176.45 162.158.166.195 - - [31/May/2018:00:00:00 +0630] "GET ********************HTTP/1.1" 200 409 "-" "Dalvik/2.1.0 (Linux; U; Android 8.0.0; ONEPLUS A5010 Build/OPR1.170623.032)"
103.42.216.55 162.158.167.100 - - [31/May/2018:00:00:00 +0630] "GET ********************HTTP/1.1" 200 409 "-" "Dalvik/2.1.0 (Linux; U; Android 6.0.1; SM-N910H Build/MMB29K)"
45.112.176.45 162.158.166.195 - - [31/May/2018:00:00:00 +0630] "POST ********************HTTP/1.1" 200 2831 "-" "Android Mobile;11160;;Android;8.0.0;OnePlus;OnePlus5T;1080x2034"
103.42.216.55 162.158.167.100 - - [31/May/2018:00:00:00 +0630] "GET ********************HTTP/1.1" 200 409 "-" "Dalvik/2.1.0 (Linux; U; Android 6.0.1; SM-N910H Build/MMB29K)"
45.112.176.45 162.158.166.195 - - [31/May/2018:00:00:01 +0630] "POST ********************HTTP/1.1" 200 172 "-" "Android Mobile;11160;;Android;8.0.0;OnePlus;OnePlus5T;1080x2034"
45.112.176.45 162.158.166.195 - - [31/May/2018:00:00:01 +0630] "GET ********************HTTP/1.1" 200 409 "-" "Dalvik/2.1.0 (Linux; U; Android 8.0.0; ONEPLUS A5010 Build/OPR1.170623.032)"
45.112.176.45 162.158.166.195 - - [31/May/2018:00:00:01 +0630] "GET ********************HTTP/1.1" 200 409 "-" "Dalvik/2.1.0 (Linux; U; Android 8.0.0; ONEPLUS A5010 Build/OPR1.170623.032)"
`

**Comment by allinurl** [comment]
@herzcthu Please attach a few sample lines from your log as I'm not sure how is delimited from your post above. Thanks.

**Comment by herzcthu** [comment]
I've edited above comment. Is that enough or do I need to upload more?
Thanks

**Comment by allinurl** [comment]
@herzcthu This should do it (assumes there's a space between the request file and the protocol, e.g., 

    /index.html HTTP/1.1

format

    goaccess access.log --log-format='~h{ } %^[%d:%t %^] "%r" %s %b "%R" "%u"' --date-format='%d/%b/%Y' --time-format=%T
