### ISSUE TITLE
goaccess 1.2 - Apache 2.4 Logs - Token 'localhost' doesn't match specifier '%h' 

### ISSUE THREAD

**Issue by kevinrsalisbury** [allinurl/goaccess#1060]
Sample apache 2.4 log (non-virtual host);

```
157.55.39.22 - - [27/Mar/2018:14:55:42 -0400] "GET /robots.txt HTTP/1.1" 302 218 "-" "Mozilla/5.0 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)"
157.55.39.22 - - [27/Mar/2018:14:55:42 -0400] "GET /robots.txt HTTP/1.1" 200 157
localhost - - [27/Mar/2018:14:56:08 -0400] "GET /server-status?auto HTTP/1.1" 406 - "-" "Python-urllib/2.7"
```

Installed goaccess 1.2 with no issues. 

Set goaccess.conf for apache 2.4;
```
 -NCSA Combined Log Format %h %^[%d:%t %^] "%r" %s %b "%R" "%u"
 -Date Format - %d/%b/%Y
 -Time Format - %H:%M:%S
```

Result;

    Token 'localhost' doesn't match specifier '%h'

**Comment by allinurl** [comment]
Are you resolving each IP (DNS lookups)? i.e., `HostnameLookups`, othewise you should be getting an IP instead, e.g., 127.0.0.1

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.

**Comment by desarrollocdb** [comment]
Hello, I have a similar problem.

HostnameLookups: double


Any suggestion?

**Comment by allinurl** [comment]
@desarrollocdb I'd try passing `--no-ip-validation`. Otherwise, you can always set it to `Off`.

**Comment by desarrollocdb** [comment]
Thanks, this has worked.
