### ISSUE TITLE
"git clone https://github.com/allinurl/goaccess.git" Do not work

### ISSUE THREAD

**Issue by thilinakasun** [allinurl/goaccess#1062]
As per the instructions given for getting goaccess via git (Build from GitHub (Development)), it is noted that the given "git clone" command exsits with below error ..

**[root@abcd ~]# git clone https://github.com/allinurl/goaccess.git**
**Initialized empty Git repository in /root/goaccess-1.2/goaccess/.git/**
**error:  while accessing https://github.com/allinurl/goaccess.git/info/refs**

**fatal: HTTP request failed**
**[root@abcd ~]#**

Source : https://github.com/allinurl/goaccess

To over come this issue, uses can use below "git clone" command;

**[root@abcd ~]# git clone git@github.com:allinurl/goaccess.git**

**Comment by allinurl** [comment]
It does work for me. 

```
~$  git clone https://github.com/allinurl/goaccess.git
Cloning into 'goaccess'...
remote: Counting objects: 11517, done.
remote: Compressing objects: 100% (89/89), done.
remote: Total 11517 (delta 94), reused 126 (delta 69), pack-reused 11355
Receiving objects: 100% (11517/11517), 4.72 MiB | 1.32 MiB/s, done.
Resolving deltas: 100% (7876/7876), done.
Checking connectivity... done.
```

Maybe [**this**](https://stackoverflow.com/questions/12538130/cant-clone-a-github-repo-on-linux-via-https) helps?

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
