### ISSUE TITLE
Unable to open GeoIP2 database: /usr/share/GeoIP/GeoIP.dat

### ISSUE THREAD

**Issue by Hugo14453** [allinurl/goaccess#1063]
Hello,

I am trying to use GeoIP2 but I run into the following error:
```
$ sudo goaccess --config-file temp.conf

GoAccess - version 1.2 - Mar 30 2018 15:52:01
Config file: temp.conf
Fatal error has occurred
Error occurred at: src/geoip2.c - init_geoip - 92
Unable to open GeoIP2 database: /usr/share/GeoIP/GeoIP.dat
```

**My configuration file is attached.**
I am running Ubuntu 18.04 beta.

The following is a line from my nginx access.log, some parts have been censored.
`<mysite> <ip.address> - - [22/Mar/2018:19:58:13 +0000] "GET / HTTP/1.1" 301 185 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:59.0) Gecko/20100101 Firefox/59.0"`

I got my GeoIP database from installing libmaxminddb-dev from the Ubuntu package library. I have tested the database using geoiplookup.
```
$ geoiplookup -f /usr/share/GeoIP/GeoIP.dat 8.8.8.8
GeoIP Country Edition: US, United States
```
I compiled GoAccess from source using the following parameters:
`./configure --enable-utf8 --enable-geoip=mmdb --enable-debug --enable-tcb=btree --with-openssl`

[temp.txt](https://github.com/allinurl/goaccess/files/1864181/temp.txt)

**Comment by allinurl** [comment]
Please make sure you are using the mmdb database.

> # For GeoIP2 City database:
> # wget -N http://geolite.maxmind.com/download/geoip/database/GeoLite2-City.mmdb.gz
> # gunzip GeoLite2-City.mmdb.gz
> #
> # For GeoIP2 Country database:
> # wget -N http://geolite.maxmind.com/download/geoip/database/GeoLite2-Country.mmdb.gz
> # gunzip GeoLite2-Country.mmdb.gz

**Comment by Hugo14453** [comment]
That worked, thank you :)
Please consider updating the GeoIP section of the [config template](https://github.com/allinurl/goaccess/blob/master/config/goaccess.conf#L645) that confused me a lot

**Comment by allinurl** [comment]
Thanks. Should be there a [few lines below](https://github.com/allinurl/goaccess/blob/master/config/goaccess.conf#L660).

**Comment by Hugo14453** [comment]
yeah I'm not sure how I missed that.
I got confused because the config you get from http://tar.goaccess.io/goaccess-1.2.tar.gz doesn't have it :(

**Comment by allinurl** [comment]
Got it. I may have missed that. Thanks for pointing that out. Should be there in the next release.
