### ISSUE TITLE
is it possible to define new customized filed in log format

### ISSUE THREAD

**Issue by theSalt** [allinurl/goaccess#1065]
my tomcat log format is

`pattern="%a %{jira.request.id}r %{jira.request.username}r %t &quot;%m %U%q %H&quot; %s %b %D &quot;%{Referer}i&quot; &quot;%{User-Agent}i&quot; &quot;%{jira.request.assession.id}r&quot;`

is it possible to show the  `username`  in the goaccess result ,  I could only ignore it by `^%` so far,
But it's really necessary to get the statistics of username hints.

**Comment by allinurl** [comment]
`%e` should display the authenticated user.

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
