### ISSUE TITLE
XFF with space

### ISSUE THREAD

**Issue by Degracio** [allinurl/goaccess#1067]
I have the following log
1.1.1.1 2.2.2.2 - - [29/Mar/2018:23:59:51 -0500] "PATCH /some/path/1071753? HTTP/1.1" - 154 "-" "Synapse-PT-HttpComponents-NIO"

Using the following command
--log-format='~h{ } %^ %^[%d:%t %^] "%r" %s %b "%R" "%u"' --date-format='%d/%B/%Y' --time-format='%H:%M:%S'

I have tried a number of other ways from previous issues posted here but nothing seems to work.

I am able to parse entries without an XFF address, for example;

127.0.0.1 - - [29/Mar/2018:23:59:51 -0500] "PATCH /some/path/1071753? HTTP/1.1" - 154 "-" "Synapse-PT-HttpComponents-NIO"

with;

--log-format='%h %^[%d:%t %^] "%r" %s %b "%R" "%u"' --date-format='%d/%B/%Y' --time-format='%H:%M:%S'

but again, the entries with XFF are missed.

**Comment by allinurl** [comment]
Currently goaccess does require a valid HTTP status code thus it's throwing an invalid token for `%s`. You can try ignoring that field though:

    --log-format='~h{ } %^ %^[%d:%t %^] "%r" %^ %b "%R" "%u"'

**Comment by Degracio** [comment]
Thanks. I was able to get it to work after ignoring that field and playing around with %h  field some more.
