### ISSUE TITLE
Redirect Analysis

### ISSUE THREAD

**Issue by rkno82** [allinurl/goaccess#1069]
Hi,

we have a vast amount of http redirects and want to analyse which of the configured redirects is still being used.
We are using httpd and have a custom log format contains:

- http host of the request
- http uri of the request
- http referer of the request
- http location of the response

Is it possible to analyse that with GoAccess?

Thanks,
Robert

**Comment by allinurl** [comment]
It sounds like goaccess should be able to parse your log without issues. It would be great if you can post a few sample lines from your access log to come up with a possible log-format.

**Comment by allinurl** [comment]
Any updates on this?

**Comment by rkno82** [comment]
Hi Gerardo,

currently I cannot provide logs as we are still planning.
Your answers enabled me to use GoAccess for the reporting.


Thanks!
