### ISSUE TITLE
[question] Substitute for webalizer/awstats?

### ISSUE THREAD

**Issue by markc** [allinurl/goaccess#107]
I can't find a mailing-list or forum so hopefully asking this here under "questions" is appropriate. Would anyone have a guideline or tutorial about how I could effectively replace webalizer with goaccess?

For instance, crontab example(s), exact CLI args, and general methodology involved in providing a goaccess substitute for webalizer so the goaccess facility provides similar features. I can see how I could create daily, weekly or even monthly goaccess snapshots per day, week or moth, but how would I link them together to provide amalgamated monthly or annual stats?

Is anyone using goaccess to provide ongoing per domain stats to end users (rather than live, via email or single web page snapshots)?

**Comment by pwFoo** [comment]
Daily, weekly and monthly reports are simple to generate. Additional a index.php (for example) is needed as start page to browse different reports. 

But how should yearly reports generated? Just use --keep-db-files, --load-from-disk and --db-path (define file-db path?) to add every daily report to the yearly? Clean db-files and write a new report every year?

**Comment by allinurl** [comment]
That's right. To create yearly reports you could either process the logs incrementally, or retroactively parse the whole year worth of logs. If you are looking to incrementally create a report, here's how to do it.

**Note:** You will need to ensure you are using the on-disk B+Tree database.

- A data set must be persisted first with `--keep-db-files`, then the same data set can be loaded with `--load-from-disk`.
- If new data is passed (piped or through a log file), it will append it to the original data set.
- To preserve the data at all times, `--keep-db-files` must be used.
- If `--load-from-disk` is used without `--keep-db-files`, database files will be deleted upon closing the program.
- By default, it stores the database files under `/tmp`, you can change the path using `--db-path=/path`.

#### Examples ####

    // last month access log
    goaccess -f access.log.1 --keep-db-files

then, load it with

    // append this month access log, and preserve new data
    goaccess -f access.log --load-from-disk --keep-db-files

To read persisted data only (without parsing new data)

    goaccess --load-from-disk --keep-db-files

**Comment by pwFoo** [comment]
Thanks, but options --keep-db-files and --dp-path seems not implemented with version 0.8.5?

    /usr/bin/goaccess: unrecognized option '--db-path'

I take a look if there is a up-to-date repo... (CentOS7)

**Comment by allinurl** [comment]
In v0.8.5 all those options are implemented. However, >= v0.9.3 added the ability to process logs incrementally. 

Also, make sure to use `--enable-tcb=btree `

    # ./configure --enable-utf8 --enable-geoip --enable-tcb=btree 
    # make
    # make install

**Comment by pwFoo** [comment]
I would use it from a CentOS7 yum repo, but it seems build without --enable-tcb=btree :(
Thanks for your help. I take a look. Maybe there is a repo with this enabled. I would prefer yum repos over manually installed packages.

**Comment by allinurl** [comment]
Feel free to post the yum repo if you find one. Thanks!

**Comment by lapazi** [comment]
Hi !

Sorry about commenting this old thread but I could not find a better one.

I have installed Ubuntu 16.04 and with it a got my hands on to goaccess 0.9.4.
I used to generate stats with awstats but goaccess seems to be a better solution because of its realtime statistics.

I'm also missing daily, weekly,  monthly and yearly reports. Now I have this basic command in my hourly cron:

sudo /usr/bin/goaccess -f /var/log/nginx/access.log -a > /var/www/html/dev/stats/report.html

That is working like it should. Creating static report.html once in a hour.

Could someone give me some more instructions how to make that kind of index.php -page? And how to use use those commands allinurl mentioned:
goaccess -f access.log.1 --keep-db-files
goaccess -f access.log --load-from-disk --keep-db-files

Or maybe there is an example somewhere that a could study?

Thanks in advance for your patience.

**Comment by allinurl** [comment]
@lapazi Not sure I follow your question about `make that kind of index.php`. Are you looking to output an index file? e.g., 

    sudo /usr/bin/goaccess -f /var/log/nginx/access.log -a > /var/www/html/dev/stats/index.html

Have you looked at the [**man page examples**](https://goaccess.io/man#examples) on how to process logs incrementally? Or do you have a specific question about this feature?

**Comment by lapazi** [comment]
Thanks for your answer.

I was referring to pwFoos comment on additional index.php and how to generate it automatically. And from that page easily to browse different report pages day week month year etc. But I do not know php so I have look for examples and try to fit those examples with in my environment.

I'll try to look the examples from manual pages.
