### ISSUE TITLE
unable to convert the apache2 access.log with avg Time served.

### ISSUE THREAD

**Issue by Thavasipitchiahraja** [allinurl/goaccess#1071]
Please help in converting the apache2 access.log with avg time served,cum time served and max Time served.

Apache2 access.log example:

```
12.36.9.1 - - [25/Mar/2018:06:39:25 +0000] "GET /HS01/login.ctl HTTP/1.1" 200 3544 "https://sid-adminportal.westus.cloudapp.azure.com/login.ctl" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36"
12.36.9.1 - - [25/Mar/2018:06:43:13 +0000] "GET /login.ctl HTTP/1.1" 200 3544 "https://sid-adminportal.westus.cloudapp.azure.com/login.ctl" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36"
12.36.9.1 - - [25/Mar/2018:06:47:44 +0000] "GET /login.ctl HTTP/1.1" 200 3544 "https://sid-adminportal.westus.cloudapp.azure.com/login.ctl" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.162 Safari/537.36"
12.36.9.1 - - [25/Mar/2018:06:49:27 +0000] "GET /login.ctl HTTP/1.1" 200 3544 "https://sid-adminportal.westus.cloudapp.azure.com/login.ctl" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36"
12.36.9.1 - - [25/Mar/2018:06:53:15 +0000] "GET /login.ctl HTTP/1.1" 200 3544 "https://sid-adminportal.westus.cloudapp.azure.com/login.ctl" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36"
12.36.9.1 - - [25/Mar/2018:06:57:46 +0000] "GET /login.ctl HTTP/1.1" 200 3544 "https://sid-adminportal.westus.cloudapp.azure.com/login.ctl" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.162 Safari/537.36"
```

GoAccess command used:

    goaccess -f /home/tzfadmin/access.log --log-format='%h %^[%d:%T %^] "%r" %s %b "%R" "%u"' --date-format='%d/%b/%Y' --time-format='%T' -a >  apache2accesslog.html

I am able to convert the apache2 access.log with the goaccess but unable to see the values.
I have attached the screen shot for reference
![capture](https://user-images.githubusercontent.com/38071402/38306077-f2e9f61a-382c-11e8-9ceb-8a790a45ec07.PNG)

Please Help!!!

**Comment by allinurl** [comment]
Please edit your apache2.conf file, e.g.,

    vim /etc/apache2/apache2.conf

and update your LogFormat variable so it looks like:

    LogFormat "%h %l %u %t \"%r\" %>s %O \"%{Referer}i\" \"%{User-Agent}i\" %D" combined

then you can use goaccess as:

    goaccess /home/tzfadmin/access.log --log-format='%h %^[%d:%t %^] "%r" %s %b "%R" "%u" %D' --date-format='%d/%b/%Y' --time-format='%T' -a -o apache2accesslog.html

**Comment by allinurl** [comment]
BTW, you will need to restart apache2. e.g., 

    service apache2 restart

**Comment by Thavasipitchiahraja** [comment]
Ok Thank you I will check and let you know

**Comment by Thavasipitchiahraja** [comment]
Yes it worked for me Thankyou!!!!!

**Comment by allinurl** [comment]
Glad that did the job :)
