### ISSUE TITLE
Is it possible to create custom panel?

### ISSUE THREAD

**Issue by abregar** [allinurl/goaccess#1074]
I would like to create some custom panel (like 'top NOT_FOUND urls' but for top 50x urls.
Is this possible and are there any guidelines for this?
Thank you in advance!

**Comment by allinurl** [comment]
Great question. It's not possible currently, but #515 should address this.

If you are up to the challenge, you could code your custom panel, e.g., This might be the closest commit for a single panel. Shouldn't be too bad :)

https://github.com/allinurl/goaccess/commit/1c2750ba0419a79b71642ac29956f1f4028a2bb3

**Comment by abregar** [comment]
Challenge accepted, will check it out. Thank you for the hint.
