### ISSUE TITLE
Format Errors - Verify your log/date/time format

### ISSUE THREAD

**Issue by wademac** [allinurl/goaccess#1075]
get error: 

    Token '"OPTIONS' doesn't match specifier '%t'  

I think the UTC maybe messing this up?

log format in apache is: 

    %v %{X-Forwarded-For}i%l %u %t \"%r\" %>s %b \\"%{Referer}i\" \"%{User-Agent}i\"

sample log:

    this.domain.com 61.71.68.214, 16.158.63.99, 0.0.0.0- - [08/Apr/2018:14:15:05 -0300] "GET //search/assets/images/common/2048-1.jpg HTTP/1.1" 200 171198 "https://www.domain.com/" "Mozilla/5.0 (iPad; CPU OS 10_3_1 like Mac OS X) AppleWebKit/602.1.50 (KHTML, like Gecko) GSA/38.0.172903409 Mobile/14E304 Safari/602.1"

**Comment by allinurl** [comment]
Can you please post the log-format you are using in goaccess? Thanks.

**Comment by wademac** [comment]
# Common Log Format (CLF) with Virtual Host
log-format %v:%^ %h %^[%d:%t %^] "%r" %s %b

**Comment by allinurl** [comment]
goaccess access.log --log-format='%v ~h{, } %^[%d:%t %^] "%r" %s %b "%R" "%u"' --date-format=%d/%b/%Y --time-format=%T

**Comment by wademac** [comment]
how can I export this to a html report?

**Comment by allinurl** [comment]
goaccess /var/log/apache2/access.log -o report.html

Please take a look at the docs for more info. https://goaccess.io/faq#html-report

**Comment by wademac** [comment]
thanks but the reason I asked is I did RTFM and did a man goaccess and when I try to run a report with the option -o /logs/report.html at the end I get nothing.

**Comment by allinurl** [comment]
Can you please exactly the command you are running?

**Comment by wademac** [comment]
I placed the formats you suggested in the goaccess.conf 
goaccess access.log -o /report.html

running Ubuntu 18.04

**Comment by wademac** [comment]
it does not create the report ... weird

**Comment by wademac** [comment]
I removed and installed apache and php on the box thinking that maybe something but not.

**Comment by allinurl** [comment]
This appears to be an isolated issue. Are you able to run it through gdb? I don't see why it's not able to create the report and even if it was a permissions issue, it should have triggered some sort of error. Can you try it on a different machine, e.g., laptop?

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.

**Comment by markflyfly** [comment]
@allinurl can i ask you for this format,thk!
log_format  main  '$remote_addr - $remote_user [$time_local] "$request" "$upstream_response_time"'
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

**Comment by markflyfly** [comment]
this is my nginx.conf log_format config ,how to change to goaaccess can read format

**Comment by allinurl** [comment]
@markflyfly please post a few lines from your access.log. Thanks.
