### ISSUE TITLE
extract all visitors and page views

### ISSUE THREAD

**Issue by expressmarketing** [allinurl/goaccess#1078]
I have a few questions in relation to visitors.
I am trying to find a way to extract some specific info from the logs.

As per your docs goaccess reports unique visitors , 
1. What are the conditions for a visitor to be considered unique ?
2. is there a way to report the total number of visitors to the site regardless if some of them are double up ( non-unique visitors )
3. In relation to page-views as specified in the docs i tried to use
awk '$7~/\.html|\.htm|\.php/' access.log | goaccess -
My issue is the hosted site is WordPress and the pages have no extension;
- home page in the logs file is listed as: '/'
- contact page is listed as: '/contact' etc.

The above log parsing won't work in this case scenario where the pages or posts don't have an extension, is there a way to extract page views in this case scenario ?

Thank You

**Comment by allinurl** [comment]
1. Hits/requests having the same IPv4/6, date and user agent are considered a unique visitor.
2. Not exactly, but probably you could deduce this from the Visitors (IPs) panel by looking at how many unique visitors there are for a single IP.
3. To extract page views that don't contain an extension (assuming a COMBINED log format), you could use:

` ` ` 
    awk '$7!~/\..*$/' access.log | goaccess --log-format=COMBINED -
` ` `

**Comment by expressmarketing** [comment]
Thank you for the great insight in how the goaccess works.
I will give this a try.

Thank you

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
