### ISSUE TITLE
Unable to open the specified log file. No such file or directory

### ISSUE THREAD

**Issue by ajcastro** [allinurl/goaccess#1080]
![image](https://user-images.githubusercontent.com/4918318/38650010-213801ba-3e2c-11e8-89e3-77102c1a58bc.png)

How can I solve this? Thanks!

**Comment by ajcastro** [comment]
Solved! It just needs to set the right path to `access.log`. It should be `/var/log/nginx/access.log`. There are other log files in `/var/log/nginx/`, how about those log files? Is it already included in report.html?

**Comment by allinurl** [comment]
You need to parse each access log.

    goaccess /var/log/nginx/access.log /var/log/nginx/access.log.1 ...

OR

    zcat /var/log/nginx/access.log.*.gz | goaccess access.log -

**Comment by ajcastro** [comment]
Thanks for the clarification!

**Comment by M034B5** [comment]
how can this be solved in docker? because i'm getting the same error.

i have created /srv/logs/access.log
and i mounted it in the docker command like this `-v "/srv/goaccess/logs:/srv/logs"`

**Comment by allinurl** [comment]
@M034B5 Did you follow [**this**](https://github.com/allinurl/goaccess#docker)?

**Comment by M034B5** [comment]
> @M034B5 Did you follow [**this**](https://github.com/allinurl/goaccess#docker)?

Oops forgot to update my post, everything ran smoothly. I skimmed through some closed issues back then and solved my problem, Documentation lacks a lot of information. But all good now. Thanks!

**Comment by lelas** [comment]
> > @M034B5 Did you follow [**this**](https://github.com/allinurl/goaccess#docker)?
> 
> Oops forgot to update my post, everything ran smoothly. I skimmed through some closed issues back then and solved my problem, Documentation lacks a lot of information. But all good now. Thanks!

Mind sharing your findings? I'm having the same issue.

**Comment by allinurl** [comment]
@lelas Are you still having this issue? Can you please share how you are running goaccess? also, are you able to tail the log?

**Comment by stefantalpalaru** [comment]
On Gentoo, goaccess comes installed with a predefined "log-file" entry in "/etc/goaccess/goaccess.conf".
This takes precedence over any log file specified on the command line, surprisingly enough:
```bash
goaccess /some/other/file.log
[...]
Unable to open the specified log file '/var/log/apache2/access.log'. No such file or directory
```
The fix is to comment out that "log-file" directive in the config file.

**Comment by allinurl** [comment]
@stefantalpalaru Could you check whether this has been fixed in the upcoming versions? It looks like Gentoo might still be shipping an older release. I believe this issue has already been addressed. You could also try passing `--no-global-config`.

**Comment by stefantalpalaru** [comment]
> It looks like Gentoo might still be shipping an older release.

Yes, but that's not the problem.
These stable geniuses uncomment the "log-file" directive in the upstream config file. On purpose: https://github.com/gentoo/gentoo/blob/02ebfbfd0601a42952aecdd3e131937d48056200/net-analyzer/goaccess/goaccess-1.9.3.ebuild#L37
You would be surprised how many Gentoo developers do not actually use the packages they maintain...

Anyway, a fixed - and up to date - ebuild is available in my overlay: https://github.com/stefantalpalaru/gentoo-overlay
