### ISSUE TITLE
The page at 'https://domain.com/report.html' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://domain.com:7890/

### ISSUE THREAD

**Issue by ajcastro** [allinurl/goaccess#1081]
![image](https://user-images.githubusercontent.com/4918318/38650591-619699ee-3e2f-11e8-9e45-7a9f453546f1.png)

**Comment by allinurl** [comment]
Please make sure to either run it through `wss` or use HTTP instead of HTTPS to open the report.

**Comment by allinurl** [comment]
Any updates on this?

**Comment by ajcastro** [comment]
Sorry for the late reply just saw the notification now. How will I run it through `wss` ?

**Comment by allinurl** [comment]
You will need to specify a wss URL using `--ws-url=<host>`. Note that the host should point to the location where GoAccess is running and parsing logs. Also, make sure host is a valid host and should not contain http on it. e.g.,

    --ws-url=wss://daragahomedepot.com 

To output real time data over a TLS/SSL connection, you need to use `--ssl-cert=<cert.crt>` and `--ssl-key=<priv.key>`. Also, you will need to build with `--with-openssl`

**Comment by ajcastro** [comment]
Cool thanks! 
Is it in the docs? How to run build --with-openssl?

**Comment by allinurl** [comment]
Yeah, you can find it on the [**FAQ**](https://goaccess.io/faq#html-report) or in the [**ManPage**](https://goaccess.io/man#options). 

```
$ wget http://tar.goaccess.io/goaccess-1.2.tar.gz
$ tar -xzvf goaccess-1.2.tar.gz
$ cd goaccess-1.2/
$ ./configure --enable-utf8 --enable-geoip=legacy --with-openssl
$ make
# make install
```

Please take a look at the [**Downloads**](Distribution Packages) page to figure out which OpenSSL package you need. If you built form the official deb repo, then the binary has already support for it. You can always run, `goaccess --help` and see if the `--ssl-*` options are listed, if they are, then you just need to specify the paths and --ws-url=wss://host

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
