### ISSUE TITLE
add ssl_protocol distribution panel

### ISSUE THREAD

**Issue by VinceRafale** [allinurl/goaccess#1086]
Hello,

As an enhancement is it possible to have a panel displaying the ratio/usage of ssl_protocol?
This information is available by default for aws cloudfront logs for example.

Thanks

**Comment by allinurl** [comment]
Sounds like we could add a panel dedicated for this. Do you have some sample data that I can look? Thanks.

**Comment by MrSorcus** [comment]
Nginx log format
```
log_format goaccess "[$time_local] $remote_addr $http_host $ssl_cipher $ssl_protocol"
  "\"$http_user_agent\" \"$http_referer\" "
  "\"$request\" $status $bytes_sent $request_time";
```
Logs
```
[19/May/2019:16:47:55 +0000] 2a01:7e01::1 mail.example.com TLS_AES_256_GCM_SHA384 TLSv1.3 "Mozilla/5.0 (X11; Linux x86_64; rv:66.0) Gecko/20100101 Firefox/66.0" "https://mail.example.com/?_task=mail&_mbox=INBOX" "POST /?_task=mail&_action=refresh HTTP/2.0" 200 448 1.042
[19/May/2019:16:47:57 +0000] 2a01:7e01::1 example.com TLS_AES_256_GCM_SHA384 TLSv1.3 "curl/7.64.1" "-" "GET / HTTP/2.0" 403 234 0.058
```
Nginx version 1.15.12

**Comment by MrSorcus** [comment]
Something similar for AWS here - https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/AccessLogs.html (`ssl-protocol` & `ssl-cipher`)

**Comment by allinurl** [comment]
So essentially you want to display a panel containing the TLS version and cipher?

**Comment by MrSorcus** [comment]
Not sure how must it be present in GoAccess.

**Comment by whalehub** [comment]
@allinurl I'm also interested in this feature. My use case is monitoring the rate of support for TLSv1.3 among the visitors of my site so I can make informed decisions in regards to deprecating the use of earlier versions.

Here's a quick mock-up of what I imagine the corresponding panel to look like:

![vivaldi_2020-06-09_16-46-18](https://user-images.githubusercontent.com/44198148/84163018-5312f880-aa71-11ea-9cff-6a962381c336.png)

**Comment by allinurl** [comment]
@whalehub Thanks for sharing that, it helps a lot! I can  probably add this to the upcoming version. For reference, do you know where I can find the ciphers for each TLS version?

**Comment by whalehub** [comment]
@allinurl You're welcome. I can recommend the following source.

TLSv1.3: https://ciphersuite.info/search/?tls=tls13&singlepage=true

TLSv1.2: https://ciphersuite.info/search/?tls=tls12&singlepage=true

TLSv1.0 and TLSv1.1 use the same cipher suites: https://ciphersuite.info/search/?tls=tls10&singlepage=true

**Comment by whalehub** [comment]
@allinurl Is this still planned for a future version?

**Comment by allinurl** [comment]
@whalehub it certainly is. Thanks for the reminder!

**Comment by allinurl** [comment]
This has been added per #1727. It will be out this week. Stay tuned!

**Comment by whalehub** [comment]
@allinurl Works nicely so far. Thanks! 🎉

**nginx.conf**
```
    log_format vcombined
      '$host:$server_port $remote_addr - $remote_user [$time_local] $ssl_protocol $ssl_cipher '
      '"$request" $status $body_bytes_sent "$http_referer" "$http_user_agent"';
```

**goaccess.conf**
```
time-format %H:%M:%S
date-format %d/%b/%Y
log-format %v:%^ %h %^[%d:%t %^] %K "%r" %s %b "%R" "%u"
```

![raw](https://user-images.githubusercontent.com/44198148/99357610-7a85b100-28ac-11eb-8d53-7c0c1bf6b274.png)
