### ISSUE TITLE
How to analyse Dante Socks server logs with GoAccess?

### ISSUE THREAD

**Issue by Enfield** [allinurl/goaccess#1087]
For example:

    Apr 13 11:35:13 (1523619313.153088) danted[6894]: info: pass(1): tcp/connect [: username%MY_USERNAME@94.25.169.233.27725 167.99.247.172.1080 -> 167.99.247.172.27725 149.154.163.37.44

Date is three different columns, can i parse it with GoAccess?

**Comment by allinurl** [comment]
Can you please describe the fields you've got in there? Thanks.

**Comment by Enfield** [comment]
Apr 13 11:35:13 (1523619313.153088) danted[6894]: info: pass(1): tcp/connect [: username%MY_USERNAME@94.25.169.233.27725 167.99.247.172.1080 -> 167.99.247.172.27725 149.154.163.37.44

month day time (timestamp with microseconds) ignore ignore ignore protocol[:username%user@ipv4.port ipv4.port -> ipv4.port ipv4.port

**Comment by allinurl** [comment]
Unfortunately there's no delimiter for those IPs,  e.g., `94.25.169.233.27725`. If you could split the last part, then it you could do:

    goaccess access.log --log-format='%^(%x.%^) %v: %^ %^ %U %^ %e@%h:%^ %^ %^' --date-format=%s --time-format=%s --ignore-panel=REQUESTS_STATIC --ignore-panel=NOT_FOUND --ignore-panel=OS --ignore-panel=BROWSERS --ignore-panel=REFERRERS --ignore-panel=REFERRING_SITES --ignore-panel=STATUS_CODES --http-method=no --http-protocol=no
