### ISSUE TITLE
HaProxy & Goaccess - doesn't match specifier '%h'

### ISSUE THREAD

**Issue by andygr** [allinurl/goaccess#1092]
Hi,
I setup HaProxy and custom logs by using this page:

https://serverfault.com/questions/764098/haproxy-log-custom-format-for-goaccess

However when i am trying to use goAccess, i am getting this:

```
Parsed 10 lines producing the following errors:

Token '192.168.1.254 - - [18/Apr/2018' doesn't match specifier '%h'
Token '192.168.1.254 - - [18/Apr/2018' doesn't match specifier '%h'
Token '192.168.1.254 - - [18/Apr/2018' doesn't match specifier '%h'
Token '192.168.1.254 - - [18/Apr/2018' doesn't match specifier '%h'
Token '192.168.1.254 - - [18/Apr/2018' doesn't match specifier '%h'
Token '192.168.1.254 - - [18/Apr/2018' doesn't match specifier '%h'
Token '192.168.1.254 - - [18/Apr/2018' doesn't match specifier '%h'
Token '192.168.1.254 - - [18/Apr/2018' doesn't match specifier '%h'
Token '192.168.1.254 - - [18/Apr/2018' doesn't match specifier '%h'
Token '192.168.1.254 - - [18/Apr/2018' doesn't match specifier '%h'

Format Errors - Verify your log/date/time format

```

The Haproxy request is:

    Apr 18 22:14:03 localhost haproxy[26325]: 192.168.1.200:1935 192.168.1.254 [18/Apr/2018:22:14:02.636] GET /vod/_definst_/shakira/smil:shakira.smil/media_w1294851853_b898000_sleng_t64TWlkMg==_tkY2RubG90dXNzdGFydHRpbWU9MCZjZG5sb3R1c2VuZHRpbWU9MCZjZG5sb3R1c2hhc2g9T2tWdjZsTmFYX0FtVHBmOHRvWkhkV0ZfZWZCMDBabGljckZCaUhtWWtkZz0=_5.ts HTTP/1.1 200 1209894 {http://81.86.200.163/Video_Clip_shakira.html|Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36}

goAccess command:

    /usr/local/bin/goaccess -f /var/log/haproxy.log -a -o /var/www/html/report.html

Thanks
Andrew

**Comment by allinurl** [comment]
This should do it:

    goaccess access.log --log-format='%^:%^: %^: %h:%^ %^[%d:%t.%^] %m %U %H %s %b {%R|%u}' --date-format=%d/%b/%Y --time-format=%T

**Comment by andygr** [comment]
Thank you, your suggestion worked

**Comment by alflinux** [comment]
Hi ,

I tried different strings to have goaccess working but always get doesn't match specifier '%s'

This is my haproxy log format

%ci:%cp\ [%T]\ %ft\ %b/%s\ %Tq/%Tw/%Tc/%Tr/%Tt\ %ST\ %B\ %CC\ %CS\ %tsc\ %ac/%fc/%bc/%sc/%rc\ %sq/%bq\ %hr\ %hs\ %{+Q}r

Thanks

**Comment by allinurl** [comment]
@alflinux Please post a few sample lines from your log.

**Comment by alflinux** [comment]
Apr 19 10:47:28 ha01 haproxy[37144]:   9.3.1.3:47548 [19/Apr/2019:10:47:28 +0000] cdn-https~ ats/ats04082 288/0/0/61/349 200 832 - - ---- 37/25/0/1/0 0/0 {js.xm-cdn.it|Mozilla/5.0 (Windows NT 6.1; rv:66.0) Gecko/20100101 Firefox/66.0|https://www.pippo.it/} {http/1.1 ats.xx01.lost.dev-84 (a-cdn [uAcRw f p eS:t cCDi p s ])} "GET /prova/http/config.js HTTP/1.1"
