### ISSUE TITLE
Token 'haproxy-systemd-wrapper' doesn't match specifier '%h'

### ISSUE THREAD

**Issue by andygr** [allinurl/goaccess#1093]
Hi,

Today i merged all the haproxy logs with the tool: logresolvemerge.pl

After the merged i run the command: 

    goaccess access.log --log-format='%^:%^: %^: %h:%^ %^[%d:%t.%^] %m %U %H %s %b {%R|%u}' --date-format=%d/%b/%Y --time-format=%T

and i got this error:

```
Parsed 10 lines producing the following errors:
Token 'haproxy-systemd-wrapper' doesn't match specifier '%h'
Token for '%h' specifier is NULL.
Token for '%h' specifier is NULL.
Token for '%h' specifier is NULL.
Token for '%h' specifier is NULL.
Token for '%h' specifier is NULL.
Token for '%h' specifier is NULL.
Token for '%h' specifier is NULL.
Token for '%h' specifier is NULL.
Token for '%h' specifier is NULL.
Format Errors - Verify your log/date/time format
```

Before the merge i was able to parse the logs with goaccess. This is one of the last requests:

    Apr 19 06:09:59 localhost haproxy[26325]: 192.168.1.200:80 192.168.1.254 [19/Apr/2018:06:09:59.516] GET / HTTP/1.1 401 675 {|Mozilla/5.0 (Windows NT 6.1; WOW64)AppleWebKit/537.11 (KHTML, like Gecko) Chrome/23.0.1271.64 Safari/537.11}

**Comment by allinurl** [comment]
For the line you posted above, that works fine for me. Are you sure you don't have any other log-format in your config file?

    goaccess access.log --log-format='%^:%^: %^: %h:%^ %^[%d:%t.%^] %m %U %H %s %b {%R|%u}' --date-format=%d/%b/%Y --time-format=%T
![369x318_scrot](https://user-images.githubusercontent.com/5005367/39014163-36caf862-43df-11e8-80a6-767742dd4565.png)

**Comment by andygr** [comment]
Thanks for the reply.

I checked the logs and i found some haproxy-systemd-wrapper lines at the top of the file. I removed them and now is working again
