### ISSUE TITLE
failed output ?GET in openSuse 

### ISSUE THREAD

**Issue by setiyaaji** [allinurl/goaccess#1094]
i am using OS openSuse leap 42.3

proces installing following README.md :
![screenshot_20180420_102630](https://user-images.githubusercontent.com/22635587/39029400-c8994f2c-4485-11e8-9559-2f795ed85e64.png)

i am using apache,
I have changed the etc/goaccess.conf as needed apache

i run in terminal ==   # goaccess access.log -a > /var/ww/html/report.html
and nothing error report but i open browser but look like this
![screenshot_20180420_103638](https://user-images.githubusercontent.com/22635587/39029584-bc4e7836-4486-11e8-9c3f-8c8f3df54567.png)

i dont run ./configure --enable-utf8 --enable-geoip=legacy
because i am install using zypper, not using pagkage (goaccess-1.2.tar.gz)

this syntax ( ./configure --enable-utf8 --enable-geoip=legacy ) effected the output?
how i can using goaccess and work? please help

**Comment by allinurl** [comment]
Thanks for reporting this. It appears the openSUSE package may be wrong, somebody posted the same [**issue**](https://github.com/allinurl/goaccess/issues/1012#issuecomment-366898288). Installing from source should solve the issue.

**Comment by setiyaaji** [comment]
temporary solution for openSuse don't install from zypper, using this :

$ wget https://tar.goaccess.io/goaccess-1.2.tar.gz
$ tar -xzvf goaccess-1.2.tar.gz
$ cd goaccess-1.2/
$ ./configure --enable-utf8  --enable-geoip=legacy
$ make
# make install

at step ( $ ./configure --enable-utf8  --enable-geoip=legacy ) just use $ ./configure --enable-utf8 , but take some effect for output you can't see chart GEO LOCATION

------
please help me to find GeoIP Library for openSuse
some pict =
![screenshot_20180421_085806](https://user-images.githubusercontent.com/22635587/39079334-5025b34c-4542-11e8-83f1-572255a0e9f0.png)

btw, Thanks  (-_-)

**Comment by allinurl** [comment]
You can install GeoIP from source, e.g.,

```
$ wget https://github.com/maxmind/geoip-api-c/releases/download/v1.6.12/GeoIP-1.6.12.tar.gz
$ tar -xzvf GeoIP-1.6.12.tar.gz && cd GeoIP-1.6.12/
$ ./configure
$ make
# make install

```
then run 

```
$ cd goaccess-1.2/
$ ./configure --enable-utf8 --enable-geoip=legacy
$ make
$ sudo make install
```

Let me know how that goes.

**Comment by allinurl** [comment]
Glad to hear that solved the issue. Closing this.
