### ISSUE TITLE
Unsure about logs

### ISSUE THREAD

**Issue by florensie** [allinurl/goaccess#1095]
I'm not quite sure what log type I'm supposed to use. I use nginx but I use it both to serve static html+css+javascript but I also use it with uwsgi and python-flask. (I also have webdav through nginx but that's not really needed in my stats)

**Comment by allinurl** [comment]
Can you please post a few lines from your access log? Thanks.

**Comment by florensie** [comment]
Is this my nginx log or my flask log or something else?

**Comment by allinurl** [comment]
Please try:

    --log-format '%h %^[%d:%t %^] "%r" %s %b "%R" "%u" %^' --date-format=%d/%b/%Y --time-format=%T

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
