### ISSUE TITLE
Strange format error when i config in commandline dialog

### ISSUE THREAD

**Issue by LEAFERx** [allinurl/goaccess#1097]
run `goaccess access.log`
get:
![1](https://user-images.githubusercontent.com/20595509/39193495-4850c1d8-480e-11e8-9298-ba25cf168252.jpg)
![2](https://user-images.githubusercontent.com/20595509/39193496-4887ec4e-480e-11e8-993d-60c05600f3ca.jpg)

seems like it automatically add "access.log" in the tail

**Comment by LEAFERx** [comment]
OS: Ubuntu 16.04 LTS
Installing ways: apt
Goaccess version: 1.2-1

**Comment by allinurl** [comment]
Does it work if you specify the log-format from the command line? e.g.,

    goaccess access.log --log-format=COMBINED

**Comment by LEAFERx** [comment]
It outputs nothing..
I guess it's succeed?

**Comment by allinurl** [comment]
Can you please post a few lines from your access log and also what's the output of just running `date`?

**Comment by LEAFERx** [comment]
I solved the problem and now it works fine.
Thanks!
BTW, how to set my nginx log_format to fit "VCOMBINED"? Cloud you give me an example?

**Comment by allinurl** [comment]
Glad you solved the issue!

As far as VCOMBINED, if you have multiple server blocks you can add this to your log_format var.

    '$host:$server_port '

Take a look at [**this**](https://gist.github.com/jyap808/10570005#gistcomment-2527235).
