### ISSUE TITLE
more modern logo

### ISSUE THREAD

**Issue by linadesteem** [allinurl/goaccess#1103]
Hi, I would like to contribute to this project, I am a graphic designer.
I made a logo modern logo for this project.

![ga](https://user-images.githubusercontent.com/35618068/39407884-a18e8ef0-4bf7-11e8-9ce1-ab5e87b38690.jpg)
![ga](https://user-images.githubusercontent.com/35618068/39407887-a5d518c6-4bf7-11e8-8877-03a43bc8e35a.png)

Fell free to use it
if you need .svg file i can make a PR for this logo

**Comment by allinurl** [comment]
Thanks for your contribution, I do appreciate it. At the moment I have no plans to change the logo, but if this ever comes up, I'd certainly get in touch. Thanks again.
