### ISSUE TITLE
How to analyze log with dashes (COMMON log format)

### ISSUE THREAD

**Issue by dimitoglou** [allinurl/goaccess#1105]
Hello, 
I am trying to analyze a log that is a variation of the Apache/NCSA Combined Log Format. I get a %b token error but I believe it is a misalignment (the %b is correct) due to the two dashes between the IP and the date (example below). 

76.xxx.xxx.xxx - - [01/Jul/2008:00:00:13 -0400] "GET /data/tiny.gif HTTP/1.1" 200 13737
219.xxx.xx.xxx - - [01/Jul/2008:00:00:13 -0400] "GET /data/tiny_195.gif HTTP/1.0" 200 12691

What would the goaccess log format be to account for the dashes?

**Comment by dimitoglou** [comment]
Thank you!  Worked like a charm from the command prompt. 
Just so that I know, is there a comparable /etc/goaccess.conf parameter that would have the same effect as `--log-format=COMMON`?

**Comment by allinurl** [comment]
Glad that did the job :)

Yes, you can use pretty much any of the command line options in the [config file](https://github.com/allinurl/goaccess/blob/master/config/goaccess.conf#L102), just remove the `--` and the `=`, e.g.,

    log-format COMMON

Closing this. Feel free to reopen it if needed.
