### ISSUE TITLE
No date format was found on your conf file

### ISSUE THREAD

**Issue by daBee** [allinurl/goaccess#1106]
`Fatal error has occurred
Error occured at: src/parser.c - parse_log - 2705
No date format was found on your conf file.`

Version 1.2
FreeBSD 11.1

In `/usr/local/etc/goaccess.conf`:

`time-format %H:%M:%S` 

in `~/.goaccessrc`:

`time-format %T`
`date-format %d/%b/%Y`
`log_format %h - %^ [%d:%t %^] "%r" %s %b "%R" "%u"`

So two time-formats provided, yet I'm getting this error.

**Comment by allinurl** [comment]
Can you try specifying these command line options in-line? e.g.,

    goaccess access.log --log-format='%h - %^ [%d:%t %^] "%r" %s %b "%R" "%u"' --date-format=%d/%b/%Y --time-format=%T

or can you please try:

    goaccess access.log -p /usr/local/etc/goaccess.conf  --no-global-config

**Comment by daBee** [comment]
OK the first one worked.  Reworked my script, and this is what comes back:

`testy.sh: line 12: unexpected EOF while looking for matching `''
`testy.sh: line 16: syntax error: unexpected end of file`

**Comment by allinurl** [comment]
Can you please post your whole script?

**Comment by allinurl** [comment]
Please check your `src` variable, there's some extra quotes in there... e.g.,

```
clear
echo "RF_scripts/admin/goaccess/testy.sh"

today=$(date -v -1d +%Y-%m-%B)
src=/var/log/nginx/access_pass1.log
fname=/home/adminuser/goaccess/$today_access_pass1.html
echo $src
echo $fname

goaccess $src --log-format='%h - %^ [%d:%t %^] "%r" %s %b "%R" "%u"' --date-format=%d/%b/%Y --time-format=%T --no-query-string --real-os --output=$fname
```

**Comment by daBee** [comment]
Everything is fine now.  Not sure what happened.  The log is fine, but my syntax was different than what I posted here.
