### ISSUE TITLE
Cronjob issues

### ISSUE THREAD

**Issue by christ0ph3r** [allinurl/goaccess#1107]
Hello.  Thanks for Goaccess. The following command works without a cron job:  
```
zcat -f /var/log/apache2/access.log /var/log/apache2/access.log.{1..16} | goaccess -o /var/www/html/analytics123456789.html
```

When it runs on a crob job, it only seems to take in account the first access log `/var/log/apache2/access.log` and doesn't get data for the rest.

**Comment by allinurl** [comment]
Can you try adding a single dash to goaccess, i.e., 

    zcat -f /var/log/apache2/access.log /var/log/apache2/access.log.{1..16} | goaccess - -o /var/www/html/analytics123456789.html

**Comment by christ0ph3r** [comment]
Just tried and no luck, and I tried it before when I was first reading into this issue.  It is only showing `/var/log/apache2/access.log` when doing it with a cron job.  When I run the command in the CLI, it works.

And I am running `GoAccess - 1.2`.

**Comment by christ0ph3r** [comment]
```zcat -f /var/log/apache2/access.log.* | goaccess - -o /var/www/html/analytics123456789.html```

That works ^^^ and is better anyways.  Going to close this.  Thanks for your help.
