### ISSUE TITLE
Tab "REQUESTED FILES (URLS)" only shows "http 200" returncodes, which is not correct/helpful

### ISSUE THREAD

**Issue by PepeLopez** [allinurl/goaccess#1108]
The tab called "REQUESTED FILES (URLS)", which shows sucessfully requested files, only use requests which generated an 200 http response code (200 ^= "successful").

Well, this may look correct, but has flaws, especially when making forwarded POST requests:
When you have forums or bulletin boards (e.g. vBulletin) the user is writing a post, and send it, afterwards he's redirected to the thread which he opened or replied to. So this is happening:
User posts to e.g. "newtopic.php" via POST and get a returncode 303 (see also [HTTP_303 on Wikipedia](https://en.wikipedia.org/wiki/HTTP_303) ), which forwards the user to the topic. So, 1 POST request (http 303) and 1 GET request (http 200) are made.
Even the 303 returned page is "successful", however, it's not shown in the "REQUESTED FILES (URLS)" tab, which isn't correct at all.

I couldn't find a quick solution to add response code 303 to that tab, so IMHO it's a real issue, at least there should be a config value for it.

Any thoughts?

**Comment by allinurl** [comment]
It should display pretty much any status code. Are you you have enough 303s to make it into the top 50/366 items? You can try parsing a few 303s and you should see them in the report.

**Comment by allinurl** [comment]
Any  updates on this?

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
