### ISSUE TITLE
[SOLVED] Log formatting isn't clear

### ISSUE THREAD

**Issue by kaldown** [allinurl/goaccess#1109]
I just can't understand what all this
```
#log-format %dT%t.%^ %^ %h:%^ %^ %T %^ %^ %^ %s %^ %b "%r" "%u"
```
for instance if I have a log formatted as the following, how should I configure my goaccess to parce this?
```
'remote=$remote_addr x_forwarded_for=$http_x_forwarded_for [$time_local] status=$status request_time=$request_time host=$host request="$request" $bytes_sent "$http_referer" "$http_user_agent" "$gzip_ratio"';
```

thanks

**Comment by allinurl** [comment]
Please post some lines from your access log. Thanks.

**Comment by kaldown** [comment]
remote=222.22.222.22 x_forwarded_for=111.11.111.111 [04/May/2018:06:25:04 +0200] status=204 request_time=0.000 host=api.site.com request="OPTIONS /api/someHook/getAll HTTP/1.1" 246 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36" "-"
remote=333.333.333.33 x_forwarded_for=- [04/May/2018:06:25:05 +0200] status=200 request_time=0.001 host=api.site.com request="GET /ping HTTP/1.1" 394 "-" "Mozilla/5.0 (compatible; Cloudflare-Traffic-Manager/1.0; +https://www.cloudflare.com/traffic-manager/; pool-id: ksajdkljsakldj)" "-"

**Comment by allinurl** [comment]
Please try:

    goaccess access.log --log-format='%^=%h %^[%d:%t %^] %^=%s %^=%T %^=%v %^="%r" %b "%R" "%u" %^' --date-format=%d/%b/%Y --time-format=%T

**Comment by kaldown** [comment]
thanks a lot, it works!
exactly what I need
