### ISSUE TITLE
Get Started page error

### ISSUE THREAD

**Issue by bigbgh** [allinurl/goaccess#1114]
There is an error in the documentation on the Get Started page on the website (https://goaccess.io/get-started).

The examples under steps 3.1, 3.2 and 3.3 have omitted the -f argument. For example, step 3.1 should read:
goaccess -f access.log -c

**Comment by allinurl** [comment]
The `-f` is optional. In fact, it was deprecated a while back. I'd recommend not using it and simply specifying the path to the log(s). Please make sure you are running the latest version.

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
