### ISSUE TITLE
nginx log format error 1033

### ISSUE THREAD

**Issue by pan781023** [allinurl/goaccess#1115]
I'm trying to use goaccess on ubuntu 16.04 for analyze nginx log and using a custom log format in my goaccess.conf.
here's my goaccess.conf file:

```
time-format %T
date-format %d/%b/%Y
log_format [%d:%t %^] %s %h "%^" %T %v "%r" %r_length %b "%R" "%u"

```

Here's the error I get when I run goaccess  -f access_log
goaccess  -f access_log
```

GoAccess - version 0.9.4 - Feb  7 2016 10:13:30
Config file: /etc/goaccess.conf

Fatal error has occurred
Error occured at: src/goaccess.c - main - 1033
Nothing valid to process.
```
this is my log format 
```
[$time_local] $status $remote_addr "$http_x_forwarded_for" $request_time $host "$request" $request_length $bytes_sent "$http_referer" "$http_user_agent"
```
this is my access log 
```
[15/May/2018:00:05:48 +0800] 200 127.0.0.1 "XX.XXX.XX.XXX" 0.202 www.xxx.com "GET /XXXXXXX/cover.jpg HTTP/1.0" 609 4811 "http://XXXXXXX/4992" "Mozilla/5.0 (iPhone; CPU iPhone OS 11_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.0 Mobile/15E148 Safari/604.1"
```

thanks

**Comment by allinurl** [comment]
This should work and please make sure to upgrade to the latest version.

    goaccess access.log --log-format='[%d:%t %^] %s %h %^ %T %v "%r" %^ %b "%R" "%u"' --date-format=%d/%b/%Y --time-format=%T

**Comment by pan781023** [comment]
upgrade 1.2 is working 
thanks very much

**Comment by allinurl** [comment]
Glad that worked. Stay tuned for the upcoming release!
