### ISSUE TITLE
How can you implement real-time statistics by merging two or more redundant server (S3) access logs?

### ISSUE THREAD

**Issue by smc0210** [allinurl/goaccess#1117]
Using aws
The load balancer combines the access logs of each of the two redundant servers into one
I want to see real-time reports

I tested it on a single server and it works fine.
I do not know how to implement real-time reports for two or more servers.

**Comment by allinurl** [comment]
You will need to read the combined access log from the load balancer. It should be pretty much the same thing as reading from a single server. Are you having any specific issue that I can help with?

**Comment by allinurl** [comment]
Take a look at [**this**](https://dchua.com/2015/09/03/parsing-s3-logs/) post, it may help get what you are looking for.

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
