### ISSUE TITLE
Real time not working because of invalid JSON

### ISSUE THREAD

**Issue by h0gar** [allinurl/goaccess#1119]
On my server, real time is failing because in the json received through the websocket, I have this:

`"protocol":"HTTP/1.1\N",`

I found this line in my logs:

> 11.11.11.11 - - [18/May/2018:09:42:00 +0200] "GET / HTTP/1.1\n" 400 3257 350 194 "-" "-"

Parsed with this log-format:

> log-format %h %^ %^ [%d:%t %^] "%r" %s %b %^ %D "%R" "%u"

**Comment by allinurl** [comment]
I believe this is fixed upstream. Can I ask you to please build from [**development**](https://github.com/allinurl/goaccess#build-from-github-development) to see if that addresses the issue? Thanks.

**Comment by h0gar** [comment]
Indeed, it fixed the issue, thank you.

**Comment by allinurl** [comment]
Great! Thanks for reporting it!
