### ISSUE TITLE
help custom log format

### ISSUE THREAD

**Issue by shaheen79** [allinurl/goaccess#1120]
hey guy ~
i have format config error~
check plz~ 

my custom log : 

    10.6.255.4 11570 - [19/May/2018:17:15:50 +0900] "GET /redgate/top/planevent/A_sh_comm_mainmall_9_2 HTTP/1.1" 200 1902 "http://shopjg.tj.com/v1/spw/common/partner.json" "Java/1.8.0_31"

**Comment by allinurl** [comment]
This should do it:

    goaccess access.log --log-format='%h %D %^[%d:%t %^] "%r" %s %b "%R" "%u"' --date-format=%d/%b/%Y --time-format=%T

**Comment by allinurl** [comment]
Closing this.
