### ISSUE TITLE
daemon update interval?

### ISSUE THREAD

**Issue by curby** [allinurl/goaccess#1125]
Hi there, I have the live html page connected to the wss daemon (gear icon has the green dot), but it doesn't actually seem to update.  Compared to rt.goaccess.io, the last updated timestamp in the upper right never changes, and it doesn't say "GoAccess Real-Time HTML Report" below the timestamp.  What am I doing wrong?  Thanks!

My configuration:

```
$ cat goaccess.conf | egrep -v '^[[:space:]]*(#|//|$)'
time-format %H:%M:%S
date-format %d/%b/%Y
log-format %h %^[%d:%t %^] "%r" %s %b "%R" "%u"
config-dialog false
hl-header true
json-pretty-print false
no-color false
no-column-names false
no-csv-summary false
no-progress false
no-tab-scroll false
with-mouse false
daemonize true
real-time-html true
ssl-cert /etc/letsencrypt/live/example.com/fullchain.pem
ssl-key /etc/letsencrypt/live/example.com/privkey.pem
ws-url wss://example.com
log-file /var/log/apache2/www.example.com.log
log-file /var/log/apache2/www.example.com.log.1
debug-file /tmp/goaccessdebug.log
agent-list false
with-output-resolver false
http-method yes
http-protocol yes
output-format /var/www/www.example.com/scripts/goaccess.html
no-query-string false
no-term-resolver false
444-as-404 false
4xx-to-unique-count false
all-static-files false
double-decode false
ignore-crawlers false
crawlers-only false
ignore-panel REFERRERS
ignore-panel KEYPHRASES
real-os true
static-file .css
static-file .js
static-file .jpg
static-file .png
static-file .gif
static-file .ico
static-file .jpeg
static-file .pdf
static-file .txt
static-file .csv
static-file .zip
static-file .mp3
static-file .mp4
static-file .mpeg
static-file .mpg
static-file .exe
static-file .swf
static-file .woff
static-file .woff2
static-file .xls
static-file .xlsx
static-file .doc
static-file .docx
static-file .ppt
static-file .pptx
static-file .iso
static-file .gz
static-file .rar
static-file .svg
static-file .bmp
static-file .tar
static-file .tgz
static-file .tiff
static-file .tif
static-file .ttf
static-file .flv
keep-db-files true
load-from-disk true
db-path /var/lib/goaccess/```

**Comment by allinurl** [comment]
I don't see anything wrong with your config file, especially since you are seeing the green icon. 

Can you please try running goaccess with `daemonize off` and see if that spits out some sort of error? Also, do you see any errors on the browser's console? Thanks.

**Comment by curby** [comment]
I'll try `daemonize off` in a bit, but I did notice some errors.  In my regular Chrome configuration I get:
<img width="1212" alt="screen shot 2018-05-23 at 12 58 35 pm" src="https://user-images.githubusercontent.com/1174486/40445538-9c6a4550-5e89-11e8-9e18-1ea2e28774ea.png">

In incognito mode I still get some:
<img width="1214" alt="screen shot 2018-05-23 at 12 59 55 pm" src="https://user-images.githubusercontent.com/1174486/40445556-aef834a2-5e89-11e8-856e-134b9b4628c1.png">

**Comment by allinurl** [comment]
Might be a UTF issue which should be fixed upstream. Can I ask you to please build from [**development**](https://github.com/allinurl/goaccess#build-from-github-development) and try again?

**Comment by curby** [comment]
Haven't built from development yet, but I tried with daemonize false.  No errors are emitted.

When I turned daemonize back on, it doesn't seem to start:

```
$ goaccess
Daemonized GoAccess: 31690
$ ps aux | grep -i goac
curby    31726  0.0  0.0  12788   972 pts/4    S+   18:00   0:00 grep --color=auto -i goac
```

I got this before when I had a typo in my `ssl-cert` and `ssl-key` configuration directives, but I checked them just now and the files exist, plus my user can read them.  Should I move this to a separate issue?

**Comment by allinurl** [comment]
Please make sure all of your paths are absolute and valid. It uses `chdir ("/")` so it will quit if it can't find it.

**Comment by curby** [comment]
Yup, paths are absolute and are valid.  Some more verbose output/logging options might make this easier to troubleshoot.

**Comment by allinurl** [comment]
I agree, I need to make it more verbose. Please give the upstream build a shot and let me know if that addresses the issue. Otherwise, we can look further at this. Thanks.

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
