### ISSUE TITLE
goaccess suddenly stops 

### ISSUE THREAD

**Issue by legale** [allinurl/goaccess#1127]
Hello. My site is ssl protected so i need wss which needs --ssl-cert and --ssl-key

I have compiled goaccess from this git repo. The problem is that when i start goaccess
`goaccess /var/log/nginx/access.log -o /var/www/html/report.html --log-format=COMBINED --real-time-html --ssl-cert=/etc/letsencrypt/live/sevenlight.ru/fullchain.pem --ssl-key=/etc/letsencrypt/live/sevenlight.ru/privkey.pem`

it suddenly stops after about 3 seconds.

**Comment by allinurl** [comment]
What output do you get in your browser's console?

**Comment by legale** [comment]
Question is not actual anymore. Just wrong cert file. Now everything works smooth.

**Comment by allinurl** [comment]
Glad to hear that :)
