### ISSUE TITLE
Why UNIQUE VISITORS PER DAY is only one?

### ISSUE THREAD

**Issue by legale** [allinurl/goaccess#1128]
Hello again. 
Goaccess version is 1.2.1 from git sources as of today.
` goaccess /var/log/nginx/access.log -o /var/www/html/report.html --log-format=COMBINED --real-time-html --ssl-cert=/etc/letsencrypt/live/sevenlight.ru/cert.pem --ssl-key=/etc/letsencrypt/live/sevenlight.ru/privkey.pem`

https://sevenlight.ru/report.html

access.log 2 last lines:
```
141.8.143.175 - - [27/May/2018:18:02:54 +0300] "GET /products/svetil'nik_podvesnoj_kemar_n__gn HTTP/1.1" 200 18679 "-" "Mozilla/5.0 (compatible; YandexBot/3.0; +http://yandex.com/bots)"
84.201.133.36 - - [27/May/2018:18:02:54 +0300] "GET /catalog/svetodiodnye-lyustry-dlya-natyazhnyh-potolkov/kolichestvo_lamp-11-3-38-8-9-20-2.8/forma_plafona-polukrug HTTP/1.1" 200 26053 "-" "Mozilla/5.0 (compatible; YandexBot/3.0; +http://yandex.com/bots)"
```

Why UNIQUE VISITORS PER DAY is only one?

**Comment by allinurl** [comment]
It looks like you only have one day worth of data. If you are rotating the log daily, that might be the issue. Otherwise you can parse multiple logs, e.g.,

    goaccess access.log access.log.1

**Comment by legale** [comment]
Ok. Thanks.
