### ISSUE TITLE
Apache custom log format

### ISSUE THREAD

**Issue by rotemreiss** [allinurl/goaccess#1130]
I saw there are already some questions about it, but I'm trying to make it work for about 2 hours, and I still don't see the light at the end of the tunnel.
I assume that you guys can do it in 2 min..

    LogFormat "%t %{X-Forwarded-For}i %v %u \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\""

Example:

    [29/May/2018:15:15:51 +0300] 80.111.111.111 blabla.com - "POST /page/123 HTTP/1.1" 302 - "http://blabla.com/page/123" "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36"

Thanks :)

**Comment by allinurl** [comment]
This should do it :)

    goaccess access.log --log-format='[%d:%t %^] %h %v %^ "%r" %s %b "%R" "%u"' --date-format=%d/%b/%Y --time-format=%T

**Comment by rotemreiss** [comment]
Damn! You are good at your job 🥇 
Thanks a lot, you saved me few more hours of frustration.

**Comment by allinurl** [comment]
Glad to hear that did the job :)
