### ISSUE TITLE
deb.goaccess.io: doesn't support architecture 'arm64' / 'armhf'

### ISSUE THREAD

**Issue by TCB13** [allinurl/goaccess#1132]
Hello,

I was trying to install this on a ARM64 device, however:
````````
apt-get install goaccess
Reading package lists... Done
N: Skipping acquire of configured file 'main/binary-arm64/Packages' as repository 'http://deb.goaccess.io stretch InRelease' doesn't support architecture 'arm64'
N: Skipping acquire of configured file 'main/binary-armhf/Packages' as repository 'http://deb.goaccess.io stretch InRelease' doesn't support architecture 'armhf'
````````

Can you please add ARM64/ARMHF to the repo? **Many thanks for the great project**.

````````
lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.4 (stretch)
Release:	9.4
Codename:	stretch

uname -r
4.14.18-sunxi64

lscpu
Architecture:          aarch64
Byte Order:            Little Endian
CPU(s):                4
On-line CPU(s) list:   0-3
Thread(s) per core:    1
Core(s) per socket:    4
Socket(s):             1
NUMA node(s):          1
Model:                 4
CPU max MHz:           816.0000
CPU min MHz:           408.0000
BogoMIPS:              48.00
NUMA node0 CPU(s):     0-3
Flags:                 fp asimd evtstrm aes pmull sha1 sha2 crc32 cpuid
````````

**Comment by 4f8p** [comment]
I will reply instead of @allinurl.

**In general very difficult to run on `armhf/arm64` device.** Trying to cope with increases the burden on developer.

I will tell you the solution. Please choose.

- If you can run the **Docker**:tm:. :whale2:

[4f8p/goaccess-docker](https://github.com/4f8p/goaccess-docker)

Please use the `Dockerfile` which in my repository. This image corresponds to the build on `Raspberry Pi 3`.

**Support is not possible.** But maybe you can expect it.

- Console mode required, or can't run **Docker**:tm:. :no_entry: :whale2:

[Debian package](https://packages.debian.org/buster/goaccess)

Here is the package of `armhf/arm64` device.
If you can `debuild`, we recommend you build on the actual machine by replacing contents of this package.

I hope this will help.

**Comment by TCB13** [comment]
I'm currently using the Debian package however it is old.

**Comment by allinurl** [comment]
Folks, goaccess is now available in the [deb repo](https://goaccess.io/download#official-repo) for arm64.

```
goaccess |    1:1.5.7-jammy |    jammy | arm64, amd64
goaccess |   1:1.5.7-impish |   impish | amd64
goaccess |   1:1.5.7-bionic |   bionic | arm64, amd64
goaccess |    1:1.5.7-focal |    focal | arm64
goaccess |  1:1.5.7-stretch |  stretch | amd64, i386
goaccess |  1:1.5.7-hirsute |  hirsute | amd64
goaccess |   2:1.5.7-buster |   buster | arm64, amd64
goaccess | 1:1.5.7-bullseye | bullseye | amd64
```

Closing this. Feel free to reopen it if needed.

**Comment by letompouce** [comment]
Raspberry4 identifies itself as `armhf`:
```
root@raspberry:~ # egrep -i ^model /proc/cpuinfo  | sort -u
model name      : ARMv7 Processor rev 3 (v7l)
Model           : Raspberry Pi 4 Model B Rev 1.5
root@raspberry:~ # dpkg --print-architecture 
armhf
```

As a result, in a Ubuntu Bionic container, `apt update` will complain:

```
N: Skipping acquire of configured file 'main/binary-armhf/Packages' as repository 'http://deb.goaccess.io bionic InRelease' doesn't support architecture 'armhf'
```

It would be nice to get upstream packages for this architecture as well! :pray:

**Comment by allinurl** [comment]
@letompouce armhf is now supported as well, give it a shot and let me know.
```
goaccess |    2:1.6.2-jammy |    jammy | armhf, arm64, amd64
goaccess |   1:1.6.2-impish |   impish | amd64
goaccess |   1:1.6.2-bionic |   bionic | armhf, arm64, amd64, i386
goaccess |    1:1.6.2-focal |    focal | arm64, amd64
goaccess |   1:1.6.2-xenial |   xenial | armhf, arm64, amd64, i386
goaccess |  1:1.6.2-stretch |  stretch | armhf, arm64, amd64, i386
goaccess |   2:1.6.2-buster |   buster | arm64, amd64
goaccess | 1:1.6.2-bullseye | bullseye | armhf, arm64, amd64, i386
```

**Comment by letompouce** [comment]
@allinurl it works like a charm, thanks!

While we're on it, and out of curiosity, would you please tell me why all architectures are supported by every Debian/Ubuntu releases? i.e. why no armhf for buster?

**Comment by allinurl** [comment]
@letompouce Glad that worked :)

Good question, actually it was giving me some SSL verification errors on those armhf releases, here's the [**log**](https://github.com/allinurl/goaccess/runs/7750378324?check_suite_focus=true#step:3:1759). Have you seen anything similar to this? Installing `ca-certificates` nor running `update-ca-certificates` helped.

**Comment by letompouce** [comment]
This one beats me. :-|
