### ISSUE TITLE
debugging error

### ISSUE THREAD

**Issue by helofsf** [allinurl/goaccess#1137]
our log sample like below

    2018-06-05	16:45:53	95.17.199.99	GET	/test.justice.com/hello/test.jpg	200	9785	0	"-"	"Dalvik/2.1.0 (Linux; U; Android 6.0; C1_Mini Build/MRA58K)"	"-"	"-"	9432

when I try to run I got error like

    Token '2018-06-05	16:45:53	95.17.199.99	GET	/test.justice.com/hello/test.jpg	200	9785 0	"-"	"Dalvik/2.1.0' doesn't match specifier '%d'

Format Errors - Verify your log/date/time format

cli like below

    goaccess log.log --log-format='%d %t %h %^ %^ %^ %^ %^ "%^" "%^" "%^" "%^" %^' --date-format=%Y-%m-%d --time-format=%H:%M:%S

**Comment by allinurl** [comment]
Can you please attach on a file a few sample lines from your log? Also, can you please describe the fields you got in there? Thanks.

**Comment by allinurl** [comment]
Any updates on this?

**Comment by allinurl** [comment]
Closing this. You can try the following:

    goaccess access.log --log-format='%d %t %h %m %U %s %bq "%R" "%u"' --date-format=%Y-%m-%d --time-format=%T
