### ISSUE TITLE
Custom NGINX logs - Token for '%h' specifier is NULL.

### ISSUE THREAD

**Issue by Mecanik** [allinurl/goaccess#1141]
Hi, I`m trying to parse some custom log format but unfortunately I do not understand how this pattern needs to be...

I tried: 

```
time-format %H:%M:%S
date-format %d/%b/%Y
log-format %^ - %^ [%d:%t %^]  "%r" %s %b "%R" "%u" %T ~h{," }
```

And:

```
log-format %v %h %^[%d:%t %^] "%r" %s %b "%R" "%u" %T %^
date-format %d/%b/%Y
time-format %T
```

And other modes as well, but they all fail with "Token for '%h' specifier is NULL".

Here are some ACCESS logs for reference:

```
- - **IP_MASKED** - - [12/Jun/2018:11:49:30 +0200] "GET **URL_MASKED** HTTP/1.1" "GET http://**URL_MASKED** HTTP/1.1" 200 331 **REFERER_MASKED** **UA_MASKED**  CF-RAY: - Cookie-Got: - Cookie-Set: - Challenge-Browser: -
- - *IP_MASKED* - - [12/Jun/2018:11:49:31 +0200] "GET **URL_MASKED** HTTP/1.1" "GET http://**URL_MASKED** HTTP/1.1" 200 332 **REFERER_MASKED** **UA_MASKED**  CF-RAY: - Cookie-Got: - Cookie-Set: - Challenge-Browser: -
- - *IP_MASKED* - - [12/Jun/2018:11:49:31 +0200] "GET **URL_MASKED** HTTP/1.1" "GET http://**URL_MASKED**  HTTP/1.1" 200 14217 - - 0.011  CF-RAY: - Cookie-Got: - Cookie-Set: - Challenge-Browser: -
```

Apologies for masking values, but I cannot disclose them as this is sensitive data.

Would you be able to kindly help me out with the correct log-format please ?

I would really appreciate it.

**Comment by allinurl** [comment]
This works for me:

    goaccess access.log --log-format='%^ %^ %h %^[%d:%t %^] "%r" "%^" %s %b %R %u %^' --date-format=%d/%b/%Y --time-format=%T

This is assuming you have duplicate the request field (`"GET **URL_MASKED** HTTP/1.1" "GET http://**URL_MASKED**  HTTP/1.1"`). Also it assumes there aren't any spaces in the referrer and the user agent. Otherwise, please attach a sample text file with real data to this issue and I can take a look.

**Comment by Mecanik** [comment]
@allinurl Thanks, I tried your example but I get the same result and with an extra error:

```
Token for '%h' specifier is NULL.
Format Errors - Verify your log/date/time format
```

Here is real data that expires in 60 minutes: https://pastebin.com/B8MJZgGY

Many thanks for your help.

**Comment by allinurl** [comment]
Unfortunately there's no way to parse it as there are not delimiters in your user agent nor referrer. If you add delimiters to those fields in your, it should work, otherwise, the closest you could do is:

    goaccess access.log --log-format='%^ %^ %h %^[%d:%t %^] "%r" "%^" %s %b %^' --date-format=%d/%b/%Y --time-format=%T --ignore-panel=OS --ignore-panel=BROWSERS --ignore-panel=REFERRING_SITES

**Comment by Mecanik** [comment]
@allinurl Thanks again, so basically my log format in NGINX is shit. 

Let me show it to you and if you want, point me to the right direction to make it work: 

https://pastebin.com/h8FNjzJT

**Comment by Mecanik** [comment]
Thanks, seems to work but there is some issue with the date-format.

**Comment by Mecanik** [comment]
I don't get it, I even copy pasted the default log format from NGINX and it's still failing. Am I missing some changes ?

**Comment by allinurl** [comment]
Are you talking about your NGINX config file? or goaccess?

**Comment by Mecanik** [comment]
Yes, I managed to make it work using a combine log_format in NGINX, but it's really weird as it works for a few minutes and then it has parse errors.

**Comment by Mecanik** [comment]
Thanks for everything.
