### ISSUE TITLE
Token 'Jun' doesn't match specifier '%h'

### ISSUE THREAD

**Issue by lblBotAkz** [allinurl/goaccess#1144]
can pls help n show me how to fix the error
i dunno which format is wrong n how to fix

# here is my log file
Jun 14 12:34:02 failover systemd: Started Session 352431 of user cetakbaj.
Jun 14 12:34:02 failover systemd: Starting Session 352431 of user cetakbaj.
Jun 14 12:34:02 failover systemd: Started Session 352432 of user cetakbaj.
Jun 14 12:34:02 failover systemd: Starting Session 352432 of user cetakbaj.
Jun 14 12:34:02 failover systemd: Started Session 352433 of user cetakbaj.
Jun 14 12:34:02 failover systemd: Starting Session 352433 of user cetakbaj.
Jun 14 12:34:02 failover systemd: Started Session 352435 of user cetakbaj.
Jun 14 12:34:02 failover systemd: Starting Session 352435 of user cetakbaj.
Jun 14 12:34:02 failover systemd: Started Session 352434 of user cetakbaj.
Jun 14 12:34:02 failover systemd: Starting Session 352434 of user cetakbaj.

# here is my goaccess.conf

Time Format Options (required)
time-format %H:%M:%S

Date Format Options (required)
date-format %d/%b/%Y

Log Format Options (required)
NCSA Combined Log Format
log-format %h %^[%d:%t %^] "%r" %s %b "%R" "%u"

**Comment by allinurl** [comment]
It looks like your log it's not an access.log. GoAccess parses specifically the web access log.
