### ISSUE TITLE
Include OS and Browsers version

### ISSUE THREAD

**Issue by Elli-Rid** [allinurl/goaccess#1146]
By default goaccess not showing OS and Browsers version, (FAQ page told me it does). How I can configure log-format to get this info?
Example of my log string: `172.31.16.82 - - [12/Jun/2018:20:01:07 +0000] "GET /portal_static/static/media/icon_walk.ffa02836.svg HTTP/1.1" 200 1537 "https://path" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.79 Safari/537.36"`

**Comment by allinurl** [comment]
It looks like you have a combined log format. Did you try?

    goaccess access.log --log-format=COMBINED -a

**Comment by allinurl** [comment]
This should be covered when #117 is implemented. You will be able to get this by filtering by specific term, e.g., `Firefox` and it will bring all OSs that match `Firefox`.

**Comment by allinurl** [comment]
Closing this as it will be implemented by #117. Feel free to reopen it if needed.
