### ISSUE TITLE
Y value go outside of panel

### ISSUE THREAD

**Issue by twproject** [allinurl/goaccess#1149]
Hi,
  if i have value with 4 or 5 digits, it goes out of the panel

![2018-06-18 09_19_42-server statistics](https://user-images.githubusercontent.com/7046065/41523056-e718dff4-72d8-11e8-9475-df6811de436e.png)

**Comment by allinurl** [comment]
I think this was fixed upstream. Can I ask you to please build from [**development**](https://github.com/allinurl/goaccess#build-from-github-development) and test this out?

**Comment by twproject** [comment]
I installed it via yum so i need to revert and install manually. I'll do the job

**Comment by mhow2** [comment]
Looks fixed in current dev build.

**Comment by allinurl** [comment]
Great. Closing this. Feel free to reopen it if needed.
