### ISSUE TITLE
Error in report when import multple logs

### ISSUE THREAD

**Issue by chiendv** [allinurl/goaccess#1150]
![screen shot 2018-06-19 at 9 55 13 am](https://user-images.githubusercontent.com/468522/41573441-e71b7fa6-73a6-11e8-8bcb-c31565a8b397.png)

When I import multiple files, the report is wrong. 
It look like all of them will be count into the day when the logs was imported.
In the photo, June 18 is the day which I ran command to import

**Comment by allinurl** [comment]
Can you please elaborate a bit more why the report is wrong? Have you counted using grep how many hits you are getting for all the logs you are parsing? e.g.,

    cat access.log access.log.1 | grep '18/Jun/2018' | wc -l

**Comment by chiendv** [comment]
My command is very simple:
 goaccess access.log-20180610 access.log-20180611 access.log-20180612 access.log-20180613 access.log-20180614 access.log-20180615 access.log-20180616 access.log-20180617 access.log-20180618 -o /usr/share/nginx/html/index.html  --load-from-disk --keep-db-files

**Comment by allinurl** [comment]
Can you run it with out ` --load-from-disk --keep-db-files`? 

Also, please run this command:

    cat access.log-20180610 access.log-20180611 access.log-20180612 access.log-20180613 access.log-20180614 access.log-20180615 access.log-20180616 access.log-20180617 access.log-20180618 | grep '18/Jun/2018' | wc -l

**Comment by chiendv** [comment]
I realize it was wrong because I set this command in cronjob:

> 0 * * * * goaccess /var/log/nginx/access.log -o /usr/share/nginx/html/index.html  --load-from-disk --keep-db-files

There are any way to run this command hourly and avoid duplicate value?

**Comment by allinurl** [comment]
Take a look at [**this**](https://github.com/allinurl/goaccess/issues/334#issuecomment-307569697).
