### ISSUE TITLE
Report not showing CUM T.S., AVG T.S., 

### ISSUE THREAD

**Issue by Jameswc5** [allinurl/goaccess#1155]
Hey,

When I open the report it looks good but missing the AVG T.S, etc.  Based on research guessing Im not picking the correct options but struggling a bit. Lookin for some advice. 

**Running:**
goaccess.exe apache_alc_access.log -a -o report.html

**Log format:**

1.1.1.1 2.2.2.2 - [19/Jun/2018:03:11:40 -0300] "POST /api/pam/login HTTP/1.1" 200 1107 472104 "-" "Jakarta Commons-HttpClient/3.1"

**usr/local/etc/config is:**
time-format %T

date-format %d/%b/%Y

log-format %h %^[%d:%t %^] "%r" %s %b "%R" "%u"

**Comment by allinurl** [comment]
This should work:

    goaccess access.log --log-format='%h %^[%d:%t %^] "%r" %s %b %D "%R" "%u"' --date-format=%d/%b/%Y --time-format=%T
