### ISSUE TITLE
deb.goaccess.io unreachable - connection timed out

### ISSUE THREAD

**Issue by troubleshooter** [allinurl/goaccess#1158]
Hello,

For the past few days, I've had the following error with `apt-get update`:

`Err:11 http://deb.goaccess.io stretch InRelease`
`Could not connect to deb.goaccess.io:80 (107.170.196.4), connection timed out`
`Reading package lists... Done`
`W: Failed to fetch http://deb.goaccess.io/dists/stretch/InRelease  Could not connect to deb.goaccess.io:80 (107.170.196.4), connection timed out`
`W: Some index files failed to download. They have been ignored, or old ones used instead.`

Thanks,
Terry

**Comment by BjornW** [comment]
I seem to have a similar issue: 


```
[...]
Ign:12 http://deb.goaccess.io bionic InRelease                           
Err:14 http://deb.goaccess.io bionic Release       
  404  Not Found [IP: 107.170.196.4 80]
Reading package lists... Done                      
E: The repository 'http://deb.goaccess.io bionic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
```

**Comment by allinurl** [comment]
Thank you for letting me know. I just added bionic to the list. Please give it a shot once again and let me know how it goes.

**Comment by spoonerandrew** [comment]
I just tried the bionic repo and it now works:-

`
[...]
Get:5 http://deb.goaccess.io bionic InRelease [3,239 B]     
[...]
`

**Comment by allinurl** [comment]
@spoonerandrew Thanks for confirming that :)

**Comment by troubleshooter** [comment]
stretch seems to be working now.

**Comment by allinurl** [comment]
@troubleshooter strange, here's the output I get on a vanilla stretch install:

```
Get:12 http://deb.goaccess.io stretch InRelease [3,240 B]                          
Get:13 http://deb.goaccess.io stretch/main amd64 Packages [615 B]
```

Do you mind sending me your IP to hello at goaccess.io to see if for some reason it blacklisted on my end? Thanks

**Comment by troubleshooter** [comment]
@allinurl It's now working on our end. No clue what the change was that caused it to work again. Thanks.

**Comment by troubleshooter** [comment]
Figured out what the problem was. Apparently the deb.goaccess.io IP is on one of the blacklists we use for our firewall. I'm in the process of narrowing down which list. I'll let you know which one it is.

**Comment by troubleshooter** [comment]
The entire netblock of 107.170.0.0/16 is in the Pushing Inertia [blocklist](https://github.com/pushinginertia/ip-blacklist).
We enabled it to test it and someone forgot to remove it. We've discontinued using this list. Sorry for any confusion.

**Comment by allinurl** [comment]
@troubleshooter Interesting finding. Thanks for posting this and I'm glad you found the issue. I'd be curious to know why the whole /16 block is in there...

Closing this, feel free to reopen it if needed.

**Comment by Lusitaniae** [comment]
Same issue?

```
Err:10 https://deb.goaccess.io hirsute Release
  404  Not Found [IP: 67.205.130.138 443]
Reading package lists... Done
E: The repository 'https://deb.goaccess.io hirsute Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

```

**Comment by allinurl** [comment]
@Lusitaniae Thanks for pointing that out. The next release which is planned to be out pretty soon will have support for Ubuntu 21.04 (hirsute). A workaround for now is to update your `/etc/apt/sources.list.d/goaccess.list` and replace `hirsute` for `focal`

**Comment by Lusitaniae** [comment]
Good point, thank you

**Comment by Karamellwuerfel** [comment]
Hello, sadly I cant connect to the jessie version of deb.goaccess.io

my sources.list/goaccess.list file looks like this 
`deb [signed-by=/usr/share/keyrings/goaccess.gpg] https://deb.goaccess.io/ jessie main`

The error I got is the following:
`W: Failed to fetch https://deb.goaccess.io/dists/jessie/main/binary-amd64/Packages  HttpError404`

Many thanks!

**Comment by allinurl** [comment]
@Karamellwuerfel goaccess no longer offers a deba package for the jessie release, it looks like support ended on 30 June 2020. You could try changing the release name in your goaccess.list and see if that would work. Sorry about that.

**Comment by Karamellwuerfel** [comment]
Thanks anyways @allinurl. Any suggestion on what to change it?

**Comment by allinurl** [comment]
You could try using `stretch` instead of `jessie`. e.g.,

    deb [signed-by=/usr/share/keyrings/goaccess.gpg] https://deb.goaccess.io/ stretch main

Again, not sure if it would work as there may be dependencies that are not in Jessie but are in stretch. Give it a shot and let me know how it goes.

**Comment by Karamellwuerfel** [comment]
@allinurl  Thanks for your quick reply!
Well, the apt-update worked. But sadly the installation failed with:
```The following packages have unmet dependencies:
 goaccess : Depends: libncursesw5 (>= 6.0) but 5.9+20140913-1+deb8u3 is to be installed
            Depends: libmaxminddb0 (>= 1.2.0) but it is not installable
E: Unable to correct problems, you have held broken packages.```

**Comment by allinurl** [comment]
Yeah, at this point, I would suggest [**building**](https://goaccess.io/download#installation) from source. At the bottom of the page, please take a look at the packages needed.

**Comment by Karamellwuerfel** [comment]
So can I build it manually and then use it in a cronjob?
Thanks!

**Comment by allinurl** [comment]
You certainly can.

**Comment by dooley** [comment]
2024-09-23: 

`Err:16 https://deb.goaccess.io jammy InRelease
  Could not connect to deb.goaccess.io:443 (172.110.195.161). - connect (113: No route to host) Could not connect to deb.goaccess.io:443 (2001:470:1f10:121::2), connection timed out`

` W: Failed to fetch https://deb.goaccess.io/dists/jammy/InRelease  Could not connect to deb.goaccess.io:443 (172.110.195.161). - connect (113: No route to host) Could not connect to deb.goaccess.io:443 (2001:470:1f10:121::2), connection timed out
`

**Comment by allinurl** [comment]
@dooley Thanks for the update! The service was temporarily down while I was updating the servers. I may need to take them down briefly again, but I’ll do my best to keep it quick. It should be back up now, as you’ve noticed.
