### ISSUE TITLE
How to make this work with goaccess?

### ISSUE THREAD

**Issue by jonasv** [allinurl/goaccess#1159]
Hi,

is this possible to make this work with goaccess ? This is modified output from apache.

    25/Jun/2018:11:52:43 +0000	13.65.19.104	159.27.56.29	443	-	-	GET /192325 HTTP/1.1	200	214523	https://www.testhost.de/hos/192325?language=en-us	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36	214261	146968	4040	218168	-	-	www.testhost.de	uniqueid=9312302e.56f754e0d3ex1; language=en-us; http_referrer=; pagination=1; _cookie={\"xxx\":{\"7\":[82,139,168,447,601,608,689,2572,3490,3632]},\"xxx_date\":\"2018-06-25T11:01:41.196Z\"}; _ga=GA1.2.1191927256.1129924501; _gid=GA1.2.131116c26.15x992x5x1; IR_gbd=testhost.de; IR_PI=1529924501331.yvtfhm16l2n; mt.v=2.1189921964.1529924501511; mt.pc=2.1; scs=%7B%; cq-tmde-ld=1229924101!0!o!8aa7e19cd3aba19cd4861374d8506fcf!; cluster=xxx3; PHPSESSID=6728e3a; XXX_AI_112325=1; XXSID=09E%B1; xxxReturning=false; xxxLastPurchaseDate=0; xxxLastVisitedCategory=xxx; xxxLastVisitedCategoryUrl=https%3A%2F%2Fwww.testhost.de; xxxDummyLastPurchasedMainCategoryUrl=en-us; xxxDummyLastPurchasedSubCategoryUrl=en-us; mx1.g.4xx0=2.1139921964.1529924101511; __gads=ID=25554c19d126a:T=1149924502:S=ALNI_MbFUOsmOITIM9ojLHuxxGC-APjxw; lastvisitedProductName=sion; current-currency=EUR; __qca=503051; _hjIncludedInSample=1; spUID=5dc1; ORIGIN_592325=xxx; brand=xxx; welcomexxx=1; _#stxxx=xxx; xxxLastVisitedProductUrl=www.testhost.de; s_sess=xxx; QSI_S_ZN_3L945rfgEUG4tGB=xxx; xxx_1514=www.testhost.de; insXrSV=xxx; s_pers=xxx; RT=\"xxx\"; SESSID=xxx

As you can see delimiter is not alwayas tab, but it can be a semicolon together with the white space, not sure if this would be an issue?

**Comment by allinurl** [comment]
It might be possible, can you please describe the fields you've got in there? Thanks.

**Comment by allinurl** [comment]
any updates on this?

**Comment by jonasv** [comment]
Yeah, all sorted internally, thanks though

**Comment by allinurl** [comment]
Glad you were able to figure all out :)
