### ISSUE TITLE
Unable to update using deb.goaccess.io - unmet dependency

### ISSUE THREAD

**Issue by troubleshooter** [allinurl/goaccess#1160]
Hello,

I am getting this error when trying to update:

```
The following packages have unmet dependencies:
goaccess : Depends: libssl1.0.0 (>= 1.0.0) but it is not installable
E: Unable to correct problems, you have held broken packages.
```

libssl1.0.2 is installed. There is no libssl1.0.0 available to install to get around this.

Thanks,
Terry

**Comment by lolzim** [comment]
Hi,

same here, on debian stretch

Best regards

**Comment by lucaferrario** [comment]
Hi,
same here, Debian Stretch (9.4). I have both "libssl1.0.2" and "libssl1.1" packages installed and up to date.

**Comment by dud0n** [comment]
I confirm, "goaccess: Depends on: libssl1.0.0 (> = 1.0.0), but it is not installed" 
ii libssl1.0.2: amd64 1.0.2l-2 + deb9u3 
ii libssl1.1: amd64 1.1.0f-3 + deb9u2

**Comment by iamra** [comment]
confirmed. same issue installing from the official Debian goaccess repo.

**Comment by allinurl** [comment]
I can confirm this, I need to build this package again.

**Comment by familyman-131** [comment]
confirm
fresh installed debian 9
try to install goaccess with this man
https://goaccess.io/download#official-repo

```
# aptitude install goaccess
The following NEW packages will be installed:
  geoip-database{a} goaccess{b} libgeoip1{a}
0 packages upgraded, 3 newly installed, 0 to remove and 0 not upgraded.
Need to get 2,544 kB of archives. After unpacking 8,272 kB will be used.
The following packages have unmet dependencies:
 goaccess : Depends: libssl1.0.0 (>= 1.0.0) which is a virtual package and is not provided by any available package

The following actions will resolve these dependencies:

     Keep the following packages at their current version:
1)     goaccess [Not Installed]

# aptitude search libssl1
p   libssl1.0-dev                                                               - Secure Sockets Layer toolkit - development files
i   libssl1.0.2                                                                 - Secure Sockets Layer toolkit - shared libraries
p   libssl1.0.2-dbg                                                             - Secure Sockets Layer toolkit - debug information
i   libssl1.1 

```

**Comment by allinurl** [comment]
This should be resolved. Please give this a shot per this [**instructions**](https://goaccess.io/download#official-repo) and let me know if that solves the issue from your side. Thanks!

**Comment by lolzim** [comment]
Ok for me, thank you!

**Comment by allinurl** [comment]
Great! Closing this.
