### ISSUE TITLE
Real-time stats with multiple log files

### ISSUE THREAD

**Issue by vbrandl** [allinurl/goaccess#1162]
I'd like to create real-time stats over multiple log files. Most of the logfiles are compressed using gzip and only the 2 newest files are uncompressed.
For a one-time analysis, I cat just execute
```
$ cat access.log access.log.1 <(zcat access.log.*.gz) | goaccess
```
but this won't create real-time statistics since the cat operation is only performed once when starting the command.

Is there a way to use multiple logfiles where some of them are compressed and some aren't?

**Comment by allinurl** [comment]
Have you tried passing the log as?

    # zcat access.log.*.gz | goaccess access.log access.log.1 -

**Comment by vbrandl** [comment]
Cool thanks. This seems to work fine.
