### ISSUE TITLE
Docker with UNRAID - GoAccess 1.2 crashed by Sig 11

### ISSUE THREAD

**Issue by nyid** [allinurl/goaccess#1164]
Hello, I'm using the allinurl/goaccess container and I'm having trouble getting it running. I followed the directions regarding mapped volumes and created a simple configuration file. 

**UNRAID configuration**
![capture](https://user-images.githubusercontent.com/5327772/42115737-71fa1ef4-7bb1-11e8-995d-632297e6ee02.PNG)

**goaccess.conf which is located in /mnt/user/system/appdata/goaccess/data/**
log-format COMBINED
log-file /srv/logs/nginx/access.log
output /srv/report/index.html
real-time-html true

**Log Output**
GoAccess - version 1.2 - Jun 29 2018 03:56:40

Config file:
==7== GoAccess 1.2 crashed by Sig 11
==7==
==7==
==7== Please report it by opening an issue on GitHub

GoAccess - version 1.2 - Jun 29 2018 03:56:40

Config file:
==7== GoAccess 1.2 crashed by Sig 11
==7==
==7==
==7== Please report it by opening an issue on GitHub

**Comment by allinurl** [comment]
Hello. Question, did you build with `--enable-tcb=btree`?

**Comment by nyid** [comment]
No, I did not build from source or create the image. I'm using the image from this Docker repository: [https://hub.docker.com/r/allinurl/goaccess/](https://hub.docker.com/r/allinurl/goaccess/).

**Comment by allinurl** [comment]
Are you able to follow these [**steps**](https://github.com/allinurl/goaccess#docker) and see if you get the same issue? Thanks.

**Comment by nyid** [comment]
Hi allinurl, those are the directions that I followed when setting up the container. I set up the directories, created the configuration file, and used the prebuilt docker image. The error is reproducible every time. Not sure if this is relevant but the date and time in the logs is always the same-- "Jun 29 2018 03:56:40".

**Comment by gkelekov** [comment]
Hi allinuri. I can confirm issue nyid reported. I have the same problem. I tried also tied prebuild image. I'm trying to parse my NGINX logs, and have no difficulty with setup and config when running GoAccess on Linux.
Config file has configuration for log-format (my custom log as I have some special stuff added to NGINIX), log-file, output and real-time-html enabled and set.
Here is docker container log when container is started:
    GoAccess - version 1.2 - Jun 29 2018 03:56:40
    Config file:
    ==7== GoAccess 1.2 crashed by Sig 11
    ==7==
    ==7==

**Comment by allinurl** [comment]
I'm looking into this. It appears to be a regression though. I'll post back as soon as I push a fix for this! Thanks!

**Comment by hank** [comment]
Bump - what ever happened here? Has this been addressed in 1.3?

**Comment by allinurl** [comment]
@nyid are you still getting this issue in 1.3? how are you running it? thanks

**Comment by nyid** [comment]
I just now installed goaccess 1.3 from Unraid Community Applications and it appears to be working right out of the box. The issue I was having earlier is no longer present.
