### ISSUE TITLE
Docker  GoAccess 1.2 crashed by Sig 11 

### ISSUE THREAD

**Issue by fraoustin** [allinurl/goaccess#1165]
Hi
I use goaccess 1.2 with docker 18.03ce

When i run

`docker run --rm -v $PWD:/srv/report -v $PWD:/srv/data -v $PWD:/srv/logs allinurl/goaccess`

I have result

> GoAccess - version 1.2 - Jun 29 2018 03:56:40
> Config file: 
> ==7== GoAccess 1.2 crashed by Sig 11
> ==7==
> ==7==
> ==7== Please report it by opening an issue on GitHub

I have search and control that /srv/report, data and logs exist

> docker run --rm -v $PWD:/srv/report -v $PWD:/srv/data -v $PWD:/srv/logs allinurl/goaccess ls -l /srv/
> total 12
> drwxr-xr-x    2 1000     1000          4096 Jul  1 07:54 data
> drwxr-xr-x    2 1000     1000          4096 Jul  1 07:54 logs
> drwxr-xr-x    2 1000     1000          4096 Jul  1 07:54 report

But if i control that /srv/report, data and logs exist **after** run goaccess

> docker run --rm -v $PWD:/srv/report -v $PWD:/srv/data -v $PWD:/srv/logs allinurl/goaccess goaccess --config-file /srv/data/goaccess.conf; ls -l /srv/
> 
> GoAccess - version 1.2 - Jun 29 2018 03:56:40
> Config file: 
> ==7== GoAccess 1.2 crashed by Sig 11
> ==7==
> ==7==
> ==7== Please report it by opening an issue on GitHub
> total 4
> drwxr-xr-x 10 root root 4096 août  25  2016 seafile

After run goaccess , i have not data, report and logs but a seafile directory.

I think the problem of crash comes from there

**Comment by pravdomil** [comment]
see https://github.com/allinurl/goaccess/issues/1168

**Comment by fraoustin** [comment]
It's ok for me
thank
