### ISSUE TITLE
Docker GoAccess 1.2 crashed by Sig 11

### ISSUE THREAD

**Issue by pravdomil** [allinurl/goaccess#1168]
## Steps to reproduce
Run script from readme:
```sh
docker run --restart=always -d -p 8080:7890 \
  -v "/srv/goaccess/data:/srv/data"         \
  -v "/srv/goaccess/logs:/srv/logs"         \
  -v "/srv/goaccess/html:/srv/report"       \
  --name=goaccess allinurl/goaccess
```

And then run `docker logs goaccess`

```
GoAccess - version 1.2 - Jun 29 2018 03:56:40
Config file: 
==5== GoAccess 1.2 crashed by Sig 11
==5==
==5==
==5== Please report it by opening an issue on GitHub
```

## Docker version
```
Client:
 Version:      18.05.0-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   f150324
 Built:        Wed May  9 22:16:25 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.05.0-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   f150324
  Built:        Wed May  9 22:14:32 2018
  OS/Arch:      linux/amd64
  Experimental: false
```

**Comment by pravdomil** [comment]
after some investigation the error is caused by reading `goaccess.conf`, even if the conf is empty it crashes

**Comment by allinurl** [comment]
Thanks for reporting this. I'm looking into it and I'll post back as soon as possible.

**Comment by pravdomil** [comment]
I managed to run `goaccess` in docker only with config stored in `/usr/local/etc`.

**Comment by andyjk15** [comment]
This is also happens if you create the `goaccess.conf` and build the image, not just pull the docker image

**Comment by monkeydri** [comment]
@pravdomil could you elaborate ?

I used the conf file from the docker container /usr/local/etc/goaccess.conf as conf file but still no luck :

`docker run --rm -v $PWD/report:/srv/report -v $PWD/conf:/srv/data -v $PWD/logs:/srv/logs allinurl/goaccess`

```
GoAccess - version 1.2 - Jun 29 2018 03:56:40
Config file:
==7== GoAccess 1.2 crashed by Sig 11
==7==
==7==
==7== Please report it by opening an issue on GitHub
```

All dirs are present on host and correctly mounted on container. goaccess.conf is inside conf dir on host.

**Comment by pravdomil** [comment]
I have updated my comment

**Comment by monkeydri** [comment]
Thank you but I still don't get it. Is it not what I have done by `docker run --rm -v $PWD/report:/srv/report -v $PWD/logs:/srv/logs allinurl/goaccess goaccess --config-file=/usr/local/etc/goaccess.conf` ?

**Comment by pravdomil** [comment]
I have used `docker-compose`, try run `docker run --rm -v $PWD/report:/srv/report -v $PWD/logs:/srv/logs allinurl/goaccess goaccess`

**Comment by monkeydri** [comment]
still no luck. Moreover trying to run goaccess without options shows the help.

I then tried to run goaccess from inside the container in a shell :

`docker run -it --entrypoint=/bin/ash -v $PWD/report:/srv/report -v $PWD/proxy/logs:/srv/logs allinurl/goaccess -i`

then `goaccess --config-file /usr/local/etc/goaccess.conf`

```
GoAccess - version 1.2 - Jun 29 2018 03:56:40
Config file:
==8== GoAccess 1.2 crashed by Sig 11
==8==
==8==
```

whereas /usr/local/etc/goaccess.conf is there with following contents : [/usr/local/etc/goaccess.conf](https://gist.github.com/monkeydri/615b0d67bf0bc2df14c3c04497dfef62)

**Comment by pravdomil** [comment]
>  Moreover trying to run goaccess without options shows the help.

you need to pass your log filepath `docker run -v ./srv:/srv allinurl/goaccess goaccess access.log` works fine

**Comment by monkeydri** [comment]
Alright thank you very much for your help @pravdomil that's it !

I will now try to find which option in the `goaccess.conf` files is causing this bug.

**Comment by pravdomil** [comment]
`--config-file` causes crash
