### ISSUE TITLE
Custom log format

### ISSUE THREAD

**Issue by rodrigosaraiva** [allinurl/goaccess#1172]
I have this kind of log:

localhost:8081 172.18.0.1 - - [2018-07-04T10:48:08Z] "GET /static/assets/js/frontend.653c45cfcabfa46fa8df.js" 200 1472538 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36"

I am using this log-format:
log-format %v:%^ %h - %^ [%Y-%m-%dT%H:%M:%S%^] "%r" %s %b "%R" "%u"

Not have success, and the 07 is exactly the value for month here:

Parsed 10 lines producing the following errors:
Token '07' doesn't match specifier '%m'
Format Errors - Verify your log/date/time format

Anyone know what is going here? I tried change, but there is no many things to change related to month.

**Comment by meehow** [comment]
`%m` is a request method http://httpd.apache.org/docs/current/mod/mod_log_config.html

You are trying to mix log format with date/time format, but it should be specified in separate parameters (log-format, date-format and time-format).

**Comment by rodrigosaraiva** [comment]
I solved the problem with this format:

time-format %H:%M:%SZ
date-format %Y-%m-%d
log-format %v:%^ %h - %^ [%dT%t] "%r" %s %b "%R" "%u"
