### ISSUE TITLE
No valid hits on custom log

### ISSUE THREAD

**Issue by alex-jitbit** [allinurl/goaccess#1173]
here's my log format:

`05:28:25.644 /folder/file.php - "hostname.com" - 127.0.0.1 GET 418`

I run with a `-c` option and configure the following log format:

`%~ %U %~ %~ %~ %~ %m %b`

I get "no valid hits". I also get "please specify date format" but I have no date in my log... So I just set it to %d (because it does not let me continue without one)

Also, THERE'S NO CONFIG FILE. I searched my whole hard drive.

PS. running on windows ubuntu-subsystem, installed via `apt-get install goaccess`

**Comment by alex-jitbit** [comment]
created a `~/.goaccessrc` file with the following content - still not working

```
log-format %^ %U %q %^ %^ %^ %m %b
date-format %d/%b/%Y```

**Comment by allinurl** [comment]
You need a valid date and time in order for the parser to properly read the log.

**Comment by alex-jitbit** [comment]
@allinurl thanks

**Comment by alex-jitbit** [comment]
Still not working. "No valid hits"

`2018-07-12 12:25:25.091 /folder/file.js v=6767-22501 "hostname.com" "173.00.0.0" 162.0.0.0 GET 3719`

`%d %^ %r %q %^ %^ %^ %m %b`

date format `%Y-%m-%d`

PS. Also, why does it keep prompting me for format even if I have created a ~/.goaccess file?

**Comment by allinurl** [comment]
This should do it:

    goaccess access.log --log-format='%d %t.%^ %U %q "%v" "%h" %^ %m %b' --date-format=%Y-%m-%d --time-format=%T

It should be `~/.goaccessrc` Please build from development, it should address this issue you mentioned above. Otherwise, feel free to  specify it as `-p ~/.goaccessrc`

**Comment by alex-jitbit** [comment]
It gives me `Unknown option '--'`.

**Comment by alex-jitbit** [comment]
Thanks it finally works, turns out I just had a rally old version.
