### ISSUE TITLE
Log parsing not picking up all log entries with custom log format

### ISSUE THREAD

**Issue by distractal** [allinurl/goaccess#1176]
Hi,

Using nginx 1.10.3 and GoAccess 0.9.4, with the following log format:
log_format request_time_ssl '$remote_addr $http_cf_connecting_ip - $remote_user [$time_local] ' '"$request" $status $body_bytes_sent ' '"$http_referer" "$http_user_agent" ' '$ssl_protocol/$ssl_cipher ' '$request_time';

Sample log output (with replaced identifiable information):
1111:1111:1111:1111:1111:1111:1111:1111 1111:1111:1111:1111:1111:1111:1111:1111 - userid [16/Jul/2018:12:37:58 -0400] "GET /path1/path2/path3/path4/203384.jpg HTTP/1.1" 200 75328 "https://subdomain.website.com/path1/path2/path3.cgi" "Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_75 like Mac OS X) AppleWebKit/452.3.65 (KHTML, like Gecko) CriOS/64.1.6492.34 Mobile/66B200 Safari/452.3" TLSv1.2/ECDHE-RSA-AES256-SHA384 0.021

time-format %H:%M:%S
date-format %d/%b/%Y
log-format %h ~h - %e [%d:%t %^] "%r" %s %b "%R" "%u" %^/%^ %T

GoAccess tells me there are 56 hits, while if I check for HTTP status 200 codes:
root@ubuntu:~# fgrep -c 200 access.log.1 
113

If I check for HTTP status codes, I would think I would see all requests, but I see a total of 56 again... again, total requests:
root@ubuntu:~# fgrep -c "" access.log.1
170

Am I doing something wrong?

**Comment by allinurl** [comment]
Please make sure you are on the latest version since some of the format specifiers were introduced recently. Also try this format using the [**latest**](https://goaccess.io/download) version:

    goaccess access.log --log-format='%h %^ %^ %e [%d:%t %^] "%r" %s %b "%R" "%u" %^ %T' --date-format='%d/%b/%Y' --time-format=%T

**Comment by distractal** [comment]
Bingo... added GoAccess repo instead of using default apt-get and reran apt install, added your recommended changes to the config file, works great!

Thank you, and thank you for this wonderful tool.
