### ISSUE TITLE
unable to set the exact log format

### ISSUE THREAD

**Issue by dineshkumar4728** [allinurl/goaccess#1182]
Hi,
i am new to goaccess ,while i am processing  my log file i am getting errors .can anyone help me with the exact formats.
my data looks like:

Jul 26 15:48:21 quickstart NetworkManager[4656]: <info> Activation (eth0) Stage 5 of 5 (IP Configure Commit) scheduled...
Jul 26 15:48:21 quickstart NetworkManager[4656]: <info> Activation (eth0) Stage 4 of 5 (IP4 Configure Get) complete.
Jul 26 15:48:21 quickstart NetworkManager[4656]: <info> Activation (eth0) Stage 5 of 5 (IP Configure Commit) started...
Jul 26 15:48:21 quickstart NetworkManager[4656]: <info> (eth0): device state change: ip-config -> activated (reason 'none') [7 8 0]
Jul 26 15:48:21 quickstart NetworkManager[4656]: <info> Policy set 'System eth0' (eth0) as default for IPv4 routing and DNS.

i am getting this errors:
Token 'Jul' doesn't match specifier '%h'
Token 'Jul' doesn't match specifier '%h'
Token 'Jul' doesn't match specifier '%h'
Token 'Jul' doesn't match specifier '%h'

Thanks.

**Comment by allinurl** [comment]
Hello, GoAccess is a web log analyzer tool so unfortunately you won't be able to parse your log.
