### ISSUE TITLE
Piping both outputs to goaccess (multiple pipes)

### ISSUE THREAD

**Issue by fractured** [allinurl/goaccess#1183]
Hello,

I'm quite new to linux, and found myself stuck trying to pipe two things at the same time from the access_log into the goaccess report. 

For example:

I'm trying to pipe statistics only for certain url, like this:
grep -h -i 'example.com' /var/log/httpd/access_log | goaccess -a -o /usr/local/goaccess/testreport.html -

But I also want to, at the same time pipe the statistics for only previous day.
I've seen in the documentation something like: 
sed -n '/'$(date '+%d\/%b\/%Y' -d 'yesterday')'/,$ p' /var/log/httpd/access_log | goaccess -a -o /usr/local/goaccess/testreport.html -

Is there a good way to combine both of these options so I can generate html output for only example.com url and only for previous day?

**Comment by allinurl** [comment]
Great question, you can add additional pipes, e.g.,

    sed -n '/'$(date '+%d/%b/%Y' -d 'yesterday')'/,$ p' /var/log/httpd/access_log | grep -h -i 'example.com' | goaccess -a -o /usr/local/goaccess/testreport.html -

**Comment by fractured** [comment]
Thank you!
That worked perfectly. I was not aware I could just add additional pipes, while performing them with different commands.
