### ISSUE TITLE
Combined Log Format :(

### ISSUE THREAD

**Issue by melliston** [allinurl/goaccess#1186]
This is a sample of my log file format

```
82.132.220.242 - - [02/Aug/2018:10:50:35 +0100] "GET /printer/api/orderrequest_new.php?a=15776&u=15652&p=874651" 200 14 "-" "-"
95.129.20.19 - - [02/Aug/2018:10:50:35 +0100] "GET /printer/api/orderrequest_new.php?a=8058&u=7943&p=607673" 200 14 "-" "-"
95.129.20.20 - - [02/Aug/2018:10:50:35 +0100] "GET /printer/api/orderrequest_new.php?a=16783&u=16658&p=523873" 200 14 "-" "-"
95.129.20.19 - - [02/Aug/2018:10:50:35 +0100] "GET /printer/api/orderrequest_new.php?a=16843&u=16718&p=167662" 200 14 "-" "-"
82.132.237.109 - - [02/Aug/2018:10:50:35 +0100] "GET /printer/api/message_process.php?a=15558&u=15434&p=607472" 200 16 "-" "-"
95.129.20.20 - - [02/Aug/2018:10:50:35 +0100] "GET /printer/api/orderrequest_new.php?a=14184&u=14069&p=637209" 200 14 "-" "-"
95.129.20.20 - - [02/Aug/2018:10:50:35 +0100] "GET /printer/api/orderrequest_new.php?a=15912&u=15789&p=235474" 200 14 "-" "-"
95.129.20.18 - - [02/Aug/2018:10:50:35 +0100] "GET /printer/api/orderrequest_new.php?a=16708&u=16583&p=395125" 200 14 "-" "-"
213.205.194.11 - - [02/Aug/2018:10:50:35 +0100] "GET /printer/api/pushreporting.php?a=15749&u=15625&p=984323&signalAv=63&signa
```

I have tried: %h %^[%d:%t %^] "%r" %s %b "%R" "%u"

**Comment by allinurl** [comment]
Try:

    goaccess access.log --log-format=COMBINED

**Comment by melliston** [comment]
Hi Thanks allinurl however the requested files doesnt show the correct data I dont think. It is showing:

 1356611 99.63% 8578 74.17%   40.57 MiB ---  ---      -
 1636     0.12%    1  0.01%   37.24 MiB POST HTTP/1.1 /ext/api/
 384      0.03%  175  1.51%    4.04 MiB GET  HTTP/1.1 /
 46	  0.00%   15  0.13%   24.13 KiB GET  HTTP/1.1 /inc/img/wholesaler/16850png


Is that correct? It doesnt feel correct.

Many thanks.

Matthew

**Comment by allinurl** [comment]
As far as how is the data being outputted, looks right to me. Why would  you say is not right? Feel free to attach the whole log and I can verify this.

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
