### ISSUE TITLE
UniqueID from Apache

### ISSUE THREAD

**Issue by domainoverflow** [allinurl/goaccess#1189]
Hi @allinurl , Thank you for GoAccess. 

In our context, we use the Apache unique ID on our logs:

    %{UNIQUE_ID}e %h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"

Which produces an output as such: 

    W05TOAAhHiEXJHDTpZ1psQAAACc 165.227.40.119 - - [17/Jul/2018:20:36:08 +0000] "HEAD /games/turtles.php HTTP/1.1" 200 - "-" "Mozilla/5.0 (Windows NT 5.1; rv:21.0) Gecko/20130331 Firefox/21.0"

I tried editing the log format options within GoAccess but it still not happy with the unique id 
(Token 'W05TOAAhHiEXJHDTpZ1psQAAACc' doesn't match specified).

Please, is it possible to convince GoAccess to like our logs ? 

Thanks in advance for your time, appreciated.

**Comment by allinurl** [comment]
Please try this, it should work:

    goaccess access.log --log-format='%v %h %^[%d:%t %^] "%r" %s %b "%R" "%u"' --date-format=%d/%b/%Y --time-format=%T

**Comment by domainoverflow** [comment]
Thank you @allinurl ,  it worked, I had not realised the brackets around the dates  ( %^[%d:%t %^] ) ... thank you!

**Comment by allinurl** [comment]
Glad that worked :)
