### ISSUE TITLE
xcrun: error: brew install goaccess

### ISSUE THREAD

**Issue by imvieira** [allinurl/goaccess#1190]
IGOR:log igor$ brew install goaccess 
==> Installing dependencies for goaccess: tokyo-cabinet
==> Installing goaccess dependency: tokyo-cabinet
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
Error: Failure while executing; `git config --local --replace-all homebrew.private true` exited with 1.
IGOR:log igor$

**Comment by imvieira** [comment]
IGOR:~ root# cp /usr/bin/xcrun /Library/Developer/CommandLineTools/usr/bin/
IGOR:~ root# chmod 777 /Library/Developer/CommandLineTools/usr/bin/*
IGOR:~ root# logout
IGOR:log igor$

IGOR:log igor$ brew install goaccess
Updating Homebrew...
==> Installing dependencies for goaccess: tokyo-cabinet
==> Installing goaccess dependency: tokyo-cabinet
xcode-select: error: malformed developer path ("/Library/Developer/CommandLineTools")
Error: Failure while executing; git config --local --replace-all homebrew.private true exited with 1.
IGOR:log igor$

**Comment by allinurl** [comment]
Please report this to the [Homebrew](https://github.com/Homebrew/homebrew-core/blob/30abddeed8f2b8d6e3d7b5ee313ddcd2c8ff1671/Formula/goaccess.rb) repo as they handle this package. Thanks.
