### ISSUE TITLE
Support for Wordpress Multisite, ie no virtual hosts but multiple domains

### ISSUE THREAD

**Issue by hfrid** [allinurl/goaccess#1194]
We run a WPMU (wordpress multisite) with hundreds of domains. They all use the same log file but there are no virtual hosts. 

Rows from log file:

`192.168.0.10- - [08/Aug/2018:11:20:02 +0200] "GET /a-beginners-guide-to-making-fire/ HTTP/1.1" 200 20898 "-" "Mozilla/5.0 (compatible; Dataprovider.com;)" asite.co.uk/a-beginners-guide-to-making-fire/
192.168.0.10- - [08/Aug/2018:11:20:03 +0200] "GET /author/wp_admin/ HTTP/1.1" 200 25460 "-" "Mozilla/5.0 (compatible; Dataprovider.com;)" newsite.co.uk/author/wp_admin/
192.168.0.10- - [08/Aug/2018:11:20:04 +0200] "GET /ads.txt HTTP/1.1" 404 13427 "-" "Mozilla/5.0 (compatible; Dataprovider.com;)" alovelysite.co.uk/ads.txt
192.168.0.10- - [08/Aug/2018:11:20:04 +0200] "GET / HTTP/1.1" 200 21667 "-" "Mozilla/5.0 (Linux; Android 5.1.1; SM-G925F Build/LMY47X) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.94 Mobile Safari/537.36" othersite.co.uk/index.php
`

**Comment by allinurl** [comment]
You can do this by doing some log preprocessing. Please take a look at #673 or at the [examples](https://goaccess.io/man#examples) section (virtual hosts) for how to distinguish those requests.

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
