### ISSUE TITLE
How can I set my custom JSON log format in GoAccess

### ISSUE THREAD

**Issue by ffelipek07** [allinurl/goaccess#1195]
log_format logstash_json '{ "@timestamp": "$time_iso8601", "remote_addr": "$remote_addr", "remote_user": "$remote_user", "http_host": "$host", "body_bytes_sent": "$body_bytes_sent", "request_time": $request_time, "status": $status, "short_message": "$request", "request": "$request", "request_method": "$request_method", "http_referrer": "$http_referer", "http_user_agent": "$http_user_agent", "request_time": "$request_time", "upstream_connect_time": "$upstream_connect_time", "upstream_header_time": "$upstream_header_time", "upstream_response_time": "$upstream_response_time"}';

{ "@timestamp": "2018-08-08T08:17:23-03:00", "remote_addr": "0.0.0.0", "remote_user": "-", "http_host": "localhost", "body_bytes_sent": "98", "request_time": 0.493, "status": 200, "short_message": "POST /index.php HTTP/2.0", "request": "POST /index.php HTTP/2.0", "request_method": "POST", "http_referrer": "localhost", "http_user_agent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36", "request_time": "0.493", "upstream_connect_time": "0.000", "upstream_header_time": "0.492", "upstream_response_time": "0.492"}

Could you help me ?

**Comment by ffelipek07** [comment]
I custom this way .

log-format log-format %^: "%dT%t+%^", %^: "%h", %^: "%u", %^: "%v", %^: "%b", %^: "%r", %^: "%s", %^: "%R", %^: "%R", %^: "%H", %^: "%R", %^: "%u",  %^: "%D",  %^: "%U", %^: "%D", %^: "%D"

But not work

Parsed 10 lines producing the following errors:

Token for '%t' specifier is NULL.
Token for '%t' specifier is NULL.
Token for '%t' specifier is NULL.
Token for '%t' specifier is NULL.
Token for '%t' specifier is NULL.
Token for '%t' specifier is NULL.
Token for '%t' specifier is NULL.
Token for '%t' specifier is NULL.
Token for '%t' specifier is NULL.
Token for '%t' specifier is NULL.

**Comment by allinurl** [comment]
Sorry I don't understand your question.

**Comment by ffelipek07** [comment]
Hi works fine but
I would like to know, I have many vhosts, I would like to add it to a single html file, how would I make this setting?  log-format=COMBINED

goaccess ssl-localhost.access.log --log-format='%^: "%dT%t-%^", %^: "%h", %^: "%e", %^: "%v", %^: "%b", %^: %T, %^: %s, %^: "%^", %^: "%r", %^: "%^", %^: "%R", %^: "%u" %^' --date-format=%Y-%m-%d --time-format=%T  -o /var/www/localhost/latest/report.html

**Comment by ffelipek07** [comment]
I would like to add more than one log file and monitor them in realtime
How would the command be?
goaccess 01.access.log 02.access.log 03 access.log  

Would you help me?

**Comment by allinurl** [comment]
goaccess access.log access.log.1 access.log.2 --log-format='%^: "%dT%t-%^", %^: "%h", %^: "%e", %^: "%v", %^: "%b", %^: %T, %^: %s, %^: "%^", %^: "%r", %^: "%^", %^: "%R", %^: "%u" %^' --date-format=%Y-%m-%d --time-format=%T

**Comment by ffelipek07** [comment]
It worked, I have a doubt, I believe that basic. For me to check in real time the access entries would basically be this command. I added the above parameters in the file "/etc/goaccess.conf"

log-format %^: "%dT%t-%^", %^: "%h", %^: "%e", %^: "%v", %^: "%b", %^: %T, %^: %s, %^: "%^", %^: "%r", %^: "%^", %^: "%R", %^: "%u" %^

goaccess /var/log/nginx/ssl-vhost.com.br.access.log -o /var/www/vhost/report.html --real-time-html --daemonize

I would like to know how I can access them from an aws s3?

**Comment by allinurl** [comment]
Take a look at [**this**](https://dchua.com/2015/09/03/parsing-s3-logs/), it may help.

Closing this. Feel free to reopen it if needed.
