### ISSUE TITLE
how can i parse this json？

### ISSUE THREAD

**Issue by TesKO666** [allinurl/goaccess#1196]
nginx.conf

```
access_log_json '{"user_ip":"$http_x_real_ip","lan_ip":"$remote_addr","log_time":"$time_iso8601","user_req":"$request","http_code":"$status","body_bytes_sents":"$body_bytes_sent","req_time":"$request_time","user_ua":"$http_user_agent"}';
```
nginx log:

    {"user_ip":"-","lan_ip":"192.168.120.1","log_time":"2018-08-09T17:45:09+08:00","user_req":"GET /common/js/index.js HTTP/1.1","http_code":"200","body_bytes_sents":"3230","req_time":"0.012","user_ua":"Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.125 Safari/537.36"}

**Comment by TesKO666** [comment]
thinks

**Comment by allinurl** [comment]
Assuming you have a valid IP for `user_ip`, this works:

    goaccess access.log --log-format='%^:"%h",%^,%^:"%dT%t+%^",%^:"%r",%^:"%s",%^:"%b",%^:"%T",%^:"%u"' --date-format='%Y-%m-%d' --time-format=%T

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
