### ISSUE TITLE
make `%h` match anonymized ip

### ISSUE THREAD

**Issue by thomasleveil** [allinurl/goaccess#1197]
The access log file I would like to parse has anonymized ip adresses: `123.213.122.x`. Goaccess fails to parse those. Is there anything that can be done for such a case?

**Comment by allinurl** [comment]
You will have to do some preprocessing to the IP field and then pipe the output to goaccess. Either `sed` or `awk` should do the job fairly easy.

Note that upstream added the option `--anonymize-ip`  to anonymize IPv/4/6 so there's no need to that beforehand. This will be shipped in the upcoming version.

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
