### ISSUE TITLE
Log parse error (may be "%~" not working as expect)

### ISSUE THREAD

**Issue by steelywing** [allinurl/goaccess#1198]
Goaccess V1.2

I parse the following log using this log format (Squid) `%x.%^ %~%L %h %^/%s %b %m %U` but get error `Token '' doesn't match specifier '%h'`

[test.log](https://github.com/allinurl/goaccess/files/2279983/test.log)

```
1533744000.777     11 1.1.1.1 TCP_MISS/200 1390 GET http://cdn.content.prod.cms.msn.com/multipletile/summary/alias/experiencebyname/today? - ORIGINAL_DST/173.223.45.94 text/xml
```

But if I replace the spaces with 1 space in log, and remove  `%~` in the log format, it works.

```
1533744000.777 11 1.1.1.1 TCP_MISS/200 1390 GET http://cdn.content.prod.cms.msn.com/multipletile/summary/alias/experiencebyname/today? - ORIGINAL_DST/173.223.45.94 text/xml
```

**Comment by steelywing** [comment]
NVM, I found the master branch has fix the `%~`.

**Comment by allinurl** [comment]
Glad to hear that!
