### ISSUE TITLE
[One of those] Format Errors - Verify your log/date/time format

### ISSUE THREAD

**Issue by asciifaceman** [allinurl/goaccess#1199]
I'm really struggling with log format. I was told the logs were supposed to be w3c but I guess they aren't.

```
#Fields: date	time	cs-method	c-ip	cs-version	cs-referrer	cs-user-agent	filesize	cs-bytes	sc-bytes	s-ip	time-taken	sc-status	cs-uri-query	cs-uri-stem	x-byte-range	comment
```

ex.

```
2018-07-10	11:23:12	GET	ip.ip.ip.ip	https	-	Xtream-Codes IPTV Panel Pro	4057980	159	4058361	ip.ip.ip.ip	0.033	200	-	/path/to/file.ext	-	-
```

**Comment by allinurl** [comment]
Please try this:

    goaccess access.log --log-format='%d\t%t\t%m\t%h\t%^\t%R\t%u\t%b\t%^\t%^\t%v\t%T\t%s\t%^\t%U\t%^' --date-format=%Y-%m-%d --time-format=%T

**Comment by asciifaceman** [comment]
Holy cow @allinurl this looks great.

I may not understand the log format, but it looks phenomenal once right. It isn't relevant right now, but would it be overly annoying if I opened another issue in the future as the log format might change slightly to capture individual values out of one of these field - or should this one remain open.

I'm sure you get these a lot and they are quite a burden.

**Comment by allinurl** [comment]
Glad that worked :) Feel free to open a new issue if things change. Closing this.
