### ISSUE TITLE
just process some modules

### ISSUE THREAD

**Issue by abgit** [allinurl/goaccess#12]
On big logs, when we have millions of hosts, we get a very very big export with lots of info. And sometimes that *aditional* info is not necessary.

I propose to have a way to select modules to process.
So, we can choose if we want to process "hosts", "referer", "404" or other modules. This way we can define modules to process (or as an alternative modules do exclude).

Something like:

    # goaccess  -p general,unique,requested -f access.log

so, in previous example, goaccess will only process and give information about general stats, unique visits per day and requested pages only.

What do you think?

**Comment by allinurl** [comment]
This has been implemented in v0.9. Thanks.
