### ISSUE TITLE
Fish shell buffering issue

### ISSUE THREAD

**Issue by shrhawk-entertainer** [allinurl/goaccess#1204]
`tail -f -n 2000 /var/log/nginx.access.log | grep -v --line-buffered "nginx_report.html" | goaccess -o nginx_report.html --real-time-html --addr=127.0.0.1 --log-format='%h - %^ [%d:%t %^] "%r" %s %b "%R" "%u" "%^" %T %^' --time-format='%T' --date-format='%d/%b/%Y'`

while running this command on fish shell nothing happens and its stuck if i press `ctrl + c` then i got the message `WebSocket server ready to accept new client connections`

If i run this command without grep its working fine on fish shell example
`tail -f -n 2000 /var/log/nginx.access.log | goaccess -o nginx_report.html --real-time-html --addr=127.0.0.1 --log-format='%h - %^ [%d:%t %^] "%r" %s %b "%R" "%u" "%^" %T %^' --time-format='%T' --date-format='%d/%b/%Y'` and show instantly
`WebSocket server ready to accept new client connections`

**Comment by allinurl** [comment]
Thanks for pointing this out. This is probably an issue directly with fish shell. e.g., [**3702**](https://github.com/fish-shell/fish-shell/issues/3702), [**1396**](https://github.com/fish-shell/fish-shell/issues/1396).

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
