### ISSUE TITLE
I find the value of "unique visitors" is not right!

### ISSUE THREAD

**Issue by Haitianisgood** [allinurl/goaccess#1205]
env：
GoAccess - 1.2
ubuntu 14.04

my goaccess command:

```
goaccess -f /srv/logs/access.log -o report.html 
```
The result of "unique visitors" is : '10704"

But if I use shell command:

```
cat /srv/logs/access.log |awk '{print $1}'|sort|uniq -c|wc -l
````
The result is : "5025"

**Comment by allinurl** [comment]
Please note that HTTP requests containing the **same IP**, the **same date**, and the **same user agent** are considered a unique visitor. In your case, I'm assuming you are only taking unique IPs. 

The unique IPs count should be displayed right above the data column in the Visitors Panel.

**Comment by Haitianisgood** [comment]
Thank you for you reply!
In my opinion the "HTTP requests containing the same IP, the same date, and the same user agent are considered a unique visitor" should be less than unique IPs. Because it have too many restrictions.

I think one IP requested two or more API should be one unique visitor,is it right?

**Comment by allinurl** [comment]
Not really. Think about a house where all of them go out with the same public IP, but each house member has a different device, e.g., D1 => Chrome, D2 => iPad, D3 => Android Firefox. All of them using the same IP but different agent. Thus IP, Date and Agent = unique visitor.

**Comment by Haitianisgood** [comment]
Thank you very much for you reply again!
What you explain is very well!It is real fact!
