### ISSUE TITLE
Trying to parse this Nginx Json 

### ISSUE THREAD

**Issue by Bornel45** [allinurl/goaccess#1208]
Hello !

 I'm trying to parse logs from Nginx send to stdout inside a container.
 
On the host server, I get the output into /var/lib/docker/containers/'IDcontainer'/IDcontainer-json.log

 **In the nginx container my custom logs have this format**
`
 '$remote_addr - $remote_user [$time_local] '
                       '"$request" $status $body_bytes_sent '
                       '"$http_referer" "$http_user_agent" '
                       '"$http_x_forwarded_for" $request_id '; `

 **And here is a line that comes out of IDcontainer-json.log, which I try to get in GoAccess**.

`
{"log":"77.136.196.228 - - [16/Aug/2018:08:39:23 +0000] \"GET /raster/facilities/17/66403/45102.png HTTP/1.1\" 200 1228 \"https://www.geovelo.fr/paris/itinerary/search?profile=MEDIAN\u0026bikeType=TRADITIONAL\u0026wayPoints=48.839039,2.383081\" \"Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_3 like Mac OS X) AppleWebKit/603.3.8 (KHTML, like Gecko) Version/10.0 Mobile/14G60 Safari/602.1\" \"-\" fb23de4aaa3f44adc066e06e5b8b46cd \n","stream":"stdout",cs"time":"2018-08-16T08:39:23.864113722Z"}`

**So I tried to interpret it that way... but it doesn't work**

` goaccess -f log --log-format=‘%^:%h - -  [%d:%t +%^] \"%r" %s %b \%R \%u ~h %^ %^","%^":"%^",%^"%^":"%^‘ --date-format=‘%d/%b/%Y’ --time-format=’%T’ `

 **If someone can help me with the format of the goaccess command ?** 

 PS : 
 This is the output of a docker logs  : 
 `92.184.104.172 - - [16/Aug/2018:09:33:40 +0000] "GET /raster/facilities/16/33110/22811.png HTTP/1.1" 200 355 "-" "Geovelo/6604 CFNetwork/897.15 Darwin/17.5.0" "-" d812d1c4d15b4793f2e48776ec6e229b`

**Comment by allinurl** [comment]
I'm confused, are you trying to parse the JSON format or the combined format?

**Comment by Bornel45** [comment]
Sorry, 
 I have these data, one of the lines of the log file(each line is a json) is :
` {"log":"77.136.196.228 - - [16/Aug/2018:08:39:23 +0000] \"GET /raster/facilities/17/66403/45102.png HTTP/1.1\" 200 1228 \"https://www.geovelo.fr/paris/itinerary/search?profile=MEDIAN\u0026bikeType=TRADITIONAL\u0026wayPoints=48.839039,2.383081\" \"Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_3 like Mac OS X) AppleWebKit/603.3.8 (KHTML, like Gecko) Version/10.0 Mobile/14G60 Safari/602.1\" \"-\" fb23de4aaa3f44adc066e06e5b8b46cd \n","stream":"stdout",cs"time":"2018-08-16T08:39:23.864113722Z"} `

So I want to interpret with Goaccess this whole log file, where each line is a json.
 So I tried this: 
 ` goaccess -f log --log-format=‘%^:%h - - [%d:%t +%^] \"%r" %s %b \%R \%u ~h %^ %^","%^":"%^",%^"%^":"%^‘ --date-format=‘%d/%b/%Y’ --time-format=’%T`
 Its not working
Could you help me create this log/date/time format? 
 
 Thank you.

Sorry if you misunderstand me, English is not my first language.

**Comment by allinurl** [comment]
You will need to change the escaping on the referrer in other to properly parse that field (i.e., conflicts with `\"`, `\u0026`), this partially works:

    goaccess access.log --log-format='%^:"%h %^[%d:%t %^] %^"%m %U %H\\"  %s %b %^"%^" %^"%u\\" %^' --date-format=%d/%b/%Y --time-format=%T

**Comment by Bornel45** [comment]
Hello, thanks for your return, the last order works well for our needs but,
 The %s and %b are not functional, especially the %s that really interests me, I have : 
 100% unknown status

I did some testing but it doesn't work, if you have any idea

**Comment by allinurl** [comment]
For the lines you posted above, my previous post works fine. e.g.,

![2018-08-27-143117_665x114_scrot](https://user-images.githubusercontent.com/5005367/44693821-de073800-aa2f-11e8-8ad5-7bc7a7ecd049.png)

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
