### ISSUE TITLE
how do you create your live demo?

### ISSUE THREAD

**Issue by egy1st** [allinurl/goaccess#1209]
what is the statment you use to generate the stats found in your live demo at https://rt.goaccess.io/?20180613194436

**Comment by allinurl** [comment]
goaccess /var/log/nginx/access.log --real-time-html -o /var/www/rt/index.html -p 9870 -a --ws-url=wss://rt.goaccess,io --ssl-cert=/var/www/ssl/cert.crt --ssl-key=/var/www/ssl/rt.key -d --hour-spec=min --date-spec=hr --enable-panel=REFERRERS

**Comment by egy1st** [comment]
Thank you. You are really great
