### ISSUE TITLE
trouble parsing nginx log

### ISSUE THREAD

**Issue by ITwrx** [allinurl/goaccess#121]
really looking forward to trying out goaccess but i'm having trouble getting my nginx log parsed. goaccesss reports "Message: Nothing valid to process."

an example log entry: "192.168.1.1 - - [08/Jun/2014:14:50:58 -0400]  "GET /some_slug HTTP/1.1" 200 5082 localhost"http://192.168.1.2/some_slug2" "Mozilla/5.0 (X11; $(X11; Linux x86_64; rv:29.0) Gecko/20100101 Firefox/29.0""

and my relevant nginx.conf stuff: "## Log format:
        log_format main '$remote_addr - $remote_user [$time_local]  '
        '"$request" $status $bytes_sent ''$server_name'
        '"$http_referer" "$http_user_agent" ';"

what i have right now in goaccess.conf: "log-format %a - %u [%d/%b/%Y:%T -%z ] "%r" %s %b $v "%R" "%U""

and for date-format in goaccess.conf: "date-format %d/%b/%Y:%T %z"

thanks in advance

**Comment by ssbarnea** [comment]
I would like to configure nginx in such was that goaccess would recognize the log format without having to configure it. What would you recommend? Also added at http://serverfault.com/questions/702587/what-would-be-a-portable-nignx-http-access-log-format-to-use-with-nginx

**Comment by allinurl** [comment]
Quoting from this [post](http://serverfault.com/a/702614/86456):

> Nginx by default will output a combined log format (NCSA). 
> 
> GoAccess will automatically recognize it if you pick the first option from the configuration dialog (or permanently uncomment the NCSA Combined Log Fo
> 
> If you are interested to log the request time, then you need to modify your nginx config file and add your custom log format:
> 
>     vi /etc/nginx/nginx.conf
> 
> then add:
> 
>     log_format timed_combined '$remote_addr - $remote_user [$time_local] ' '"$request" $status $body_bytes_sent ' '"$http_referer" "$http_user_agent" 
> 
> and change the access log to use the new format:
> 
>     access_log /var/log/nginx/timed.log timed_combined;
> 
> and restart nginx
> 
> Make sure your access.log is now logging the request time. Then you can add `%T` to your goaccess `log-format` as: 
> 
>     log-format %h %^[%d:%t %^] "%r" %s %b "%R" "%u" %T

**Comment by ip75** [comment]
see carefully locale.
export LANG=en_US.UTF-8 before run goaccess if your month name in English
