### ISSUE TITLE
Correct use of --db-path when incrementally processing logfile per vhost

### ISSUE THREAD

**Issue by adrinux** [allinurl/goaccess#1211]
I have nginx logging to a separate file for each vhost and rotated daily.
I set up automated log processing each day and used --load-from-disk --keep-db-files to persist data and incrementally process.
My one problem was that reports only covered one day - I've now realized I left db-path to the default /tmp and the data was likely being erased daily...

So now I'll add in --db-path /data/goaccess - but is that enough? If I call goaccess for each log file will it mung all the data into one database or have the sense to keep each log file's persistent data seperate? Or do I need to specify a different db-path for each sites log?

e.g do I need:
```
goaccess -f dogs.log.1 --db-path /data/goaccess/ --load-from-disk --keep-db-files -a -o dogs.html
goaccess -f cats.log.1 --db-path /data/goaccess/ --load-from-disk --keep-db-files -a -o cats.html
```
or
```
goaccess -f dogs.log.1 --db-path /data/goaccess/dogs --load-from-disk --keep-db-files -a -o dogs.html
goaccess -f cats.log.1 --db-path /data/goaccess/cats --load-from-disk --keep-db-files -a -o cats.html
```

**Comment by allinurl** [comment]
The second one `--db-path /data/goaccess/dogs`. And if you ever need to run multiple instances in real-time, then please take a look at [**this**](https://github.com/allinurl/goaccess/issues/625#issuecomment-272905761).

**Comment by adrinux** [comment]
Perfect answer, thanks!
