### ISSUE TITLE
log_format Rackspace CDN

### ISSUE THREAD

**Issue by RacontR** [allinurl/goaccess#1212]
Hi I'm trying to use logs like this:

    82.238.223.252 - - [21/07/2018:07:02:42 +0000] "GET /44a02e565ee88a-889f3ec3de0e4587e8addaf0cfbe.ssl.cf3.rackcdn.com/opti/desktop-tasse-5a9ba768c4.gif HTTP/1.1" 200 141315

With 

```
time-format %H:%M:%S
log_format %^ %^ %h %^[%d:%^] "%r" %s %b "%R" "%u"
date_format %d/%b/%Y

```
But I can't get it to work
Thanks for your help ;)

**Comment by allinurl** [comment]
That looks like the common log format, please try:

    goaccess access.log --log-format=COMMON

**Comment by RacontR** [comment]
Thanks for the quick ( very ) response
Sorry I'm new to this ;)
when I run: goaccess -f "parsed-combined/2018" -a -o "/var/www/html/bnp.html" --log-format=COMMON

I get 
GoAccess - version 0.9.4 - Feb  7 2016 10:13:32
Config file: /etc/goaccess.conf

Fatal error has occurred
Error occured at: src/parser.c - verify_formats - 1807
No time format was found on your conf file.
thanks again

**Comment by RacontR** [comment]
I actually get Fatal error has occurred
Error occured at: src/goaccess.c - main - 1033
Nothing valid to process.

**Comment by allinurl** [comment]
Looks like you are running an older version of goaccess. Please upgrade to the latest [**version**](https://github.com/allinurl/goaccess#installation) and let me know if that solves the issue.

**Comment by RacontR** [comment]
Hello again , so I updated goaccess 
but I get Token '21/07/2018' doesn't match specifier '%d'
                                            +-----------------------------------------------------------+
                                             | Log Format Configuration                                  |
                                             | [SPACE] to toggle - [ENTER] to proceed - [q]uit           |
                                             |                                                           |
                                             | [x] NCSA Combined Log Format                              |
                                             | [ ] NCSA Combined Log Format with Virtual Host            |
                                             | [ ] Common Log Format (CLF)                               |
                                             | [ ] Common Log Format (CLF) with Virtual Host             |
                                             | [ ] W3C                                                   |
                                             | [ ] Squid Native Format                                   |
                                             |                                                           |
                                             | Log Format - [c] to add/edit format                       |
                                             | %h %^[%d:%t %^] "%r" %s %b "%R" "%u"                      |
                                             |                                                           |
                                             | Date Format - [d] to add/edit format                      |
                                             | %d/%b/%Y                                                  |
                                             |                                                           |
                                             | Time Format - [t] to add/edit format                      |
                                             | %H:%M:%S                                                  |
                                             +-----------------------------------------------------------+

Thanks

**Comment by allinurl** [comment]
Please use `%d/%m/%Y ` for the date format.

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
