### ISSUE TITLE
Older data wiped

### ISSUE THREAD

**Issue by LoZio** [allinurl/goaccess#1215]
Sequence of events:
1. built goaccess
2. run it against current access.log (rotated daily). Static html produced and fine
3. saw it was good, so run it against the old gzipped logs. Again html was fine and older data visible
4. cron execution against current access.log: html generated and older data trashed, I see only today's data

I didn't expected older data to be deleted. Is this normal?
Also, when having two months of data, how can I scroll/zoom to see only one specific period?
Thanks

**Comment by LoZio** [comment]
Yes, Tokio, but I assume to have borked something myself. Not having the option to scroll in any case is a show stopper right now.

**Comment by allinurl** [comment]
Stay tuned for #117. Closing this, feel free to reopen it if needed.
