### ISSUE TITLE
Trouble parsing AWS ALB logs

### ISSUE THREAD

**Issue by LoZio** [allinurl/goaccess#1216]
I found an old post about parsin AWS ALB (not ELB) logs but it refers to an older and not currently used version of the logs. The current one is described here: https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-access-logs.html

I'm using this format 
`%^ %dT%t.%^ %^ %h:%^ %^:%^ %T %^ %^ %s %^ ^% %b "%r" "%u" %^ %^ %^ "%^" "%^" "%^" %^ %^ "%^" "%^"`
that I derived from the old one, but it always fails with:
`IPv4/6 is required.`

I use `--date-format='%Y-%m-%d'` and `--time-format=%T`. 
Attached are a couple of sanitized line from the real log.

I can't find where the problem is, it seems breaking also parsing a couple of fields...
Thanks

[alb.txt](https://github.com/allinurl/goaccess/files/2318015/alb.txt)

**Comment by allinurl** [comment]
This works for me:

    goaccess access.log --log-format='%^ %dT%t.%^ %v %h:%^ %^ %^ %T %^ %s %^ %^ %b "%r" "%u" %^' --date-format=%Y-%m-%d --time-format=%T

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
