### ISSUE TITLE
use GoAccess central for multiple hosts

### ISSUE THREAD

**Issue by codeagencybe** [allinurl/goaccess#1218]
Hello

Can I use GoAccess for centrale usage? 
I have 1 dedicated server for all metrics stuff, but I want to give all my customers their own personal "statatistics" page from their website. 
Each website is running on their own host or on a host sharing other service containers with other clients (depending on the size of the project). 

So basically, I want to keep everything central on 1 server and have some kind of "agent/daemon" running on the child hosts so the logs are available for the central to render the statistics. 

Anybody who can explain me more how to do this with GoAccess please? 

Thanks!

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
