### ISSUE TITLE
Better Support for Streaming Services like Icecast / SHOUTcast

### ISSUE THREAD

**Issue by scysys** [allinurl/goaccess#1219]
Maybe you can add an better Support for Streaming Servers like Icecast and so on.

**Comment by allinurl** [comment]
Thanks for bringing this up. Aren't these access logs compatible with other httpd log formats? Would you be able to post a few sample lines from the corresponding streaming service access log?

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.

**Comment by leixet** [comment]
This is how the Icecast logs look:

149.202.66.234 - - [25/Nov/2018:06:25:22 +0100] "GET /stream HTTP/1.x" 200 29338 "-" "Mozilla/5.0" 0
134.0.11.238 - - [25/Nov/2018:06:25:24 +0100] "GET /admin/stats HTTP/1.0" 200 1980 "-" "-" 0
208.94.247.82 - - [25/Nov/2018:06:25:33 +0100] "GET /stream HTTP/1.0" 200 55812 "-" "Winamp 2.81" 1
208.94.247.82 - - [25/Nov/2018:06:25:49 +0100] "GET /stream HTTP/1.0" 200 54211 "-" "Winamp 2.81" 1
208.94.247.82 - - [25/Nov/2018:06:26:08 +0100] "GET /stream HTTP/1.0" 200 49828 "-" "Winamp 2.81" 0
134.0.11.238 - - [25/Nov/2018:06:26:13 +0100] "GET /admin/stats HTTP/1.0" 200 1980 "-" "-" 0

**Comment by allinurl** [comment]
@leixet Can I ask what is the last field you have in there? 0, 1, etc...

**Comment by leixet** [comment]
Yes. I think its the duration of the connection to the stream, in seconds...

**Comment by leixet** [comment]
> @leixet Can I ask what is the last field you have in there? 0, 1, etc...

Yes @allinurl. I think its the duration of the connection to the stream, in seconds...

**Comment by allinurl** [comment]
Please try:

    goaccess access.log --log-format='%h %^[%d:%t %^] "%r" %s %b "%R" "%u" %T' --date-format=%d/%b/%Y --time-format=%T
