### ISSUE TITLE
src/output.c - output_html - 1168 error

### ISSUE THREAD

**Issue by voiddeveloper** [allinurl/goaccess#1220]
http://tristan91.tistory.com/424
I installed as described in above url.

$ goaccess /var/log/nginx/access.log --log-format=COMBINED -a -o /nginx/web_front/admin.html

Entering this command, the html file was executed.

$ goaccess /var/log/nginx/access.log -o /ngnix/web_front/report.html --log-format=COMBINED --real-time-html

However, the above command was entered in order to know in real time, but the following error occurred.

![screen shot 2018-08-30 at 12 09 36 pm](https://user-images.githubusercontent.com/17779284/44827383-dde48380-ac4d-11e8-87eb-adee2834151a.png)

How can we fix it?

**Comment by voiddeveloper** [comment]
Not in "/nginx/web_front" but change to "var/www/html".
Why is that?

**Comment by allinurl** [comment]
I'm not sure I follow, did it work after changing the path?

**Comment by voiddeveloper** [comment]
@allinurl 
 Yes, it works. But I want to create a "report.html" in the folder "/nginx/web_front/".

**Comment by allinurl** [comment]
You need to make sure that `/nginx/web_front/` exists and that you have write permissions to it. What's the output of `ls /nginx/web_front/`?

**Comment by voiddeveloper** [comment]
@allinurl 

![screen shot 2018-08-31 at 2 43 54 pm](https://user-images.githubusercontent.com/17779284/44894746-56217680-ad2c-11e8-818e-8cc350757d0d.png)

I logged in with a root account and also have write access to the /nginx/web_front/" folder.
What is the meaning of output in "What's the output of ls /nginx/web_front/?"
To give you a guess, I'm working on a web project and inside the "web_front" folder are the php, css, and js files.

**Comment by allinurl** [comment]
Can you please run the command I posted:

    # ls -lath /nginx/web_front/

**Comment by allinurl** [comment]
Closing this.  Feel free to reopen it if needed.

**Comment by matichewer** [comment]
What's the solution?

**Comment by allinurl** [comment]
@matichewer this appears to be a perm issue. Make sure you can write to that folder. You can always try writing the report to a different path.
