### ISSUE TITLE
right align Hits column

### ISSUE THREAD

**Issue by minusf** [allinurl/goaccess#1222]
all the other columns are right aligned, except `Hits`.  Is there any reason for this?

```
 Hits
 -------
 3628036
 66173
 48816
 41865
 38092
 37665
 37387
```

**Comment by allinurl** [comment]
Not really other than I got used to reading it that way since v0.1. I pushed a change for this. It will be out in the upcoming release. Otherwise, feel free to build from [development](https://github.com/allinurl/goaccess#build-from-github-development). Thanks for bring this up!
