### ISSUE TITLE
Can I get one vale from nginx log $request_body?

### ISSUE THREAD

**Issue by Haitianisgood** [allinurl/goaccess#1223]
In my header request_body have many value,like app_version,os_version,user_id...

Can I get one vale from nginx log $request_body?

**Comment by allinurl** [comment]
In your log, what `request_body` looks like? Could you please post a few sample lines?

**Comment by Haitianisgood** [comment]
request_body:

```
appid=1&mac=d7909c4f6d3a4xe9842ccf57dc23b656&version=6.2.9&count=200&screen=375.000000%20x%20667.000000&from=d&seq=52769&os=ios10.3.3&userId=13999218&token=84a8867aebxea814e830f8f5bfb1a79f&versionCode=20180203&model=iPhone%206
```

**Comment by allinurl** [comment]
If you are not using%e within your log, you can certainly use that to output `request_body`. e.g.,

    --log-format='%h %^[%d:%t %^] "%r" %s %b "%R" "%u" %e'

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
