### ISSUE TITLE
Goaccess IIS 

### ISSUE THREAD

**Issue by coingamil** [allinurl/goaccess#1225]
Hello,

How can I run goaccess for IIS?

I have installed the following packages on Cygwin:
wget
libgeoıp-devel
libncurses-devel
libncursesw10
gcc core
Make
automake
with gettext

I did goaccess and TokyoCabinet setup in Cygwin64. But I could not find what command to get the real time information. I am very happy if you can help with the subject.

**Comment by allinurl** [comment]
Please take a look at the man page [**examples**](https://goaccess.io/man#examples) section on how to run goaccess in real-time.

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
