### ISSUE TITLE
How can I set my custom JSON log format in GoAccess

### ISSUE THREAD

**Issue by follow2015** [allinurl/goaccess#1226]
This is my nginx log format

{"remote_addr":"115.115.121.2" ,"host":"www.xxxxx.com" ,"server_addr":"109.211.11.5" ,"timestamp":"2018-09-05T16:13:28+08:00" ,"request_time":0.163, "remote_user":"-",  "request":"GET /user/login/status HTTP/2.0" ,"status":200, "body_sent":10 ,"http_referer":"https://www.xxxxx.com/buy/ddos" ,"http_user_agent":"Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36" ,"http_x_forwarded_for":"-"}

and this is my goaccess log format

log-format "%^: "%h","%^,"%^: "%dT%t+%^","%^: %T,"%^,"%^: "%r","%^: %s,"%^: "%R","%^: "%u" %^
date-format %Y-%m-%d
time-format %H:%M:%S

but it's not work

1.logng... [0] [0/s]
Parsed 6 lines producing the following errors:

Token '27.0.0.1" ,"timestamp":"2018-09-05' doesn't match specifier '%d'

Could you tell me how to adjust this
Thank you!

**Comment by follow2015** [comment]
Can support log processing in json format？

**Comment by allinurl** [comment]
Yes, it certainly can:

    goaccess access.log --log-format='%^:"%h" ,%^:"%v" ,%^:%^:"%dT%t+%^" ,%^:%T, %^:"%e", %^:"%r" ,%^:%s, %^:%^:"%R" ,%^:"%u" %^' --date-format=%Y-%m-%d --time-format=%T

**Comment by follow2015** [comment]
log--format %^:"%h","%^,"%^,"%^:"%dT%t+%^","%^:%T,"%^,"%^:"%r","%^:%s,"%^:"%R","%^:"%u" %^
This configuration can be used, but it is somewhat different from yours.
Seems to have discarded some data.
