### ISSUE TITLE
Can not build with openssl on Ubuntu 18.04.1

### ISSUE THREAD

**Issue by ScrewLooseDan** [allinurl/goaccess#1227]
I followed the build instructions from the [Download page](https://goaccess.io/download), using the `--with-openssl` flag. The table on that page indicates `libssl-dev` is required.  However, even with the library installed I continued to get the following error while running `./configure --with-openssl --enable-utf8 --enable-geoip=legacy`:
```
checking for SSL_library_init in -lssl... no
configure: error: ssl library missing
```
Through a little testing I discovered `libssl1.0-dev` was actually required and appeared to build .  It appears that `libssl-dev` is using `libssl1.1` and didn't appear to be compatible.

Can the documentation be updated to reflect this requirement if there's not a more obvious solution?

**Comment by allinurl** [comment]
Could you please try building from [development](https://github.com/allinurl/goaccess#build-from-github-development). I believe this has been fixed upstream. Thanks.

**Comment by ScrewLooseDan** [comment]
14 days ago when I opened this issue, I believe I had tried building from development.  But, I'll try again when I get a chance.

**Comment by allinurl** [comment]
I ran a test on 18.04 and I was able to build from development. I've added a note to the `--with-openssl` [option](https://goaccess.io/download#installation). 

Closing this. Feel free to post any additional comments or reopen it if needed.

**Comment by gps3dx** [comment]
I managed to compile "--with-openssl" with:
./configure --with-getline --with-openssl --enable-tcb=btree --enable-geoip=mmdb --enable-utf8 CFLAGS="-O3 -static" LIBS="-ltinfo -lcrypto -lz -ldl -static-libgcc"

**Comment by allinurl** [comment]
@gps3dx Please note that there's no longer `--enable-tcb=btree`.
