### ISSUE TITLE
Not able to create log-format for logrus (golang)

### ISSUE THREAD

**Issue by sudhanshu16** [allinurl/goaccess#1229]
Hey!

I have been working with [logrus](https://github.com/Sirupsen/logrus) for quite some time now. And been trying to figure out the log-format for goaccess since the last couple of hours. 
It logs according to levels and the sample data is the following:
```
{"level":"error","msg":"Not Found","time":"2018-09-10T02:50:24+05:30"}
{"level":"info","msg":"[0.608ms] GET / HTTP/1.1 404 77","time":"2018-09-10T02:50:24+05:30"}
{"level":"info","msg":"[0.082ms] OPTIONS /api/getCafeData HTTP/1.1 200 0","time":"2018-09-10T02:50:44+05:30"}
{"level":"info","msg":"[2.20ms] Query SQL: SELECT \"cafe_id\" FROM \"table\" WHERE \"code\"='ABCD'","time":"2018-09-10T02:50:44+05:30"}
{"level":"info","msg":"[0.74ms] Query SQL: SELECT * FROM \"cafe\" WHERE \"id\"=1","time":"2018-09-10T02:50:44+05:30"}
{"level":"info","msg":"[0.92ms] Query SQL: SELECT * FROM \"item\" WHERE \"cafe_id\"=1","time":"2018-09-10T02:50:44+05:30"}
{"level":"info","msg":"[8.939ms] POST /api/getCafeData HTTP/1.1 200 50498","time":"2018-09-10T02:50:44+05:30"}
```
And the goaccess comand I have come up with (so far) is:
` goaccess -f sveet.log --log-format='%^:"%e"%^:"%^"%^:"[%T]%^ %m %U %H %s %b"%^:"%dT%t"%^' --date-format='%Y-%m-%d' --time-format='%H:%M:%S'
`

Looking forward to some help 💯

**Comment by allinurl** [comment]
goaccess requires a valid IPv4/6 which appears to be missing in your log. Are you logging this field?

**Comment by sudhanshu16** [comment]
I am not doing that. Actually the app is a go process which outputs the log as specified. 
The application is proxied through apache. 
I want to analyse these logs. 
I could manually append the host to the error string if that is required

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
