### ISSUE TITLE
patterns with pipe delimiter not working

### ISSUE THREAD

**Issue by NaitYoussef** [allinurl/goaccess#1230]
Hello,
When I tried the following :

`goaccess  oneline_access_log.log  --log-format='%^[%d:%t %^]|%h|"%r"|%v' --date-format=%d/%b/%Y --time-format=%T`

on the following file :

`[04/Sep/2018:18:37:38 +0200]|22.22.22.22|"GET /api/v3/resource HTTP/1.1"|machin`

and I get the following error :

```
Parsed 1 lines producing the following errors:

Token '' doesn't match specifier '%h'

Format Errors - Verify your log/date/time format
```

When I change the pipe delimiter and use space delimiter for instance it works fine, is this the nominal behaviour ?

**Comment by allinurl** [comment]
Please try:

    goaccess access.log --log-format='[%d:%t %^]||%h|"%r"|%v' --date-format=%d/%b/%Y --time-format=%T

**Comment by NaitYoussef** [comment]
When I try the suggested solution, the report is successfully generated but the 'Virtual Host" is not correct, bellow an image that show the described behaviour:

![image](https://user-images.githubusercontent.com/6217786/45413623-e9867000-b679-11e8-9de0-74dfc15b72aa.png)

And when I add the 'HTTP Status' after the 'Virtual Host' I get the same error again. Bellow an example that illustrates the issue:

Log file : 
`[04/Sep/2018:18:37:38 +0200]|22.22.22.22|"GET /api/v3/resource HTTP/1.1"|machin|200`
Goaccess command:
`goaccess oneline_access_log.log --log-format='[%d:%t %^]||%h|"%r"|%v|%s' --date-format=%d/%b/%Y --time-format=%T`
Output:
```
Parsed 1 lines producing the following errors:

Token 'machin|200' doesn't match specifier '%s'

Format Errors - Verify your log/date/time format
```

**Comment by allinurl** [comment]
I've pushed a fix for this. Please build from [**development**](https://github.com/allinurl/goaccess#build-from-github-development) and let me know if that solves the issue for you.

    goaccess access.log --log-format='[%d:%t %^]|%h|"%r"|%v|%s' --date-format=%d/%b/%Y --time-format=%T

**Comment by lgomesrj** [comment]
Hi my name is Leonardo and I'm trying to read a syslog file. I have just one trouble, follow:
Token 'Oct' doesn't match specifier '%h'
 The "Oct" represent the month parameter and I don't know how can I setup this and also how parameter to use.

**Comment by allinurl** [comment]
@lgomesrj Please post a few lines from your access log.

**Comment by allinurl** [comment]
@NaitYoussef Closing this. Feel free to reopen it if needed.

**Comment by lgomesrj** [comment]
> @lgomesrj Please post a few lines from your access log.



08/08/2017,15:00:59,1,D,TCP,,45.125.50.121,35522,146.134.94.95,35741,SA,bridge1,Filtro de pacote,Alerta,-
08/08/2017,15:00:59,1,D,TCP,,119.114.60.174,55865,146.134.135.239,23,S,bridge1,Filtro de pacote,Alerta,21
08/08/2017,15:00:59,1,D,TCP,,139.162.121.251,40853,146.134.99.194,3128,S,bridge1,Filtro de pacote,Alerta,-
08/08/2017,15:00:59,1,D,TCP,,38.131.233.68,43477,146.134.195.85,23,S,bridge1,Filtro de pacote,Alerta,-

=============================================================
Oct  2 07:35:03 secsystem systemd[1]: Reloaded Anonymizing overlay network for TCP (multi-instance-master).
Oct  2 07:35:03 secsystem systemd[1]: Stopping Zabbix Agent...
Oct  2 07:35:03 secsystem systemd[1]: Stopped Zabbix Agent.
Oct  2 07:35:03 secsystem systemd[1]: Starting Zabbix Agent...                                                                                                       
Oct  2 07:35:03 secsystem systemd[1]: Started Zabbix Agent.                                                                                                          
Oct  2 07:35:03 secsystem systemd[1]: Reloaded Anonymizing overlay network for TCP.                                                                                  
Oct  2 07:35:10 secsystem anacron[1558]: Job `cron.daily' terminated                                                                                                 
Oct  2 07:35:10 secsystem anacron[1558]: Normal exit (1 job run)                                                                                                     
Oct  2 07:39:01 secsystem CRON[2107]: (root) CMD (  [ -x /usr/lib/php/sessionclean ] && /usr/lib/php/sessionclean)

**Comment by allinurl** [comment]
@lgomesrj goaccess is a log analyzer for web server access logs. You will need to use a different tool to analyze your log.

**Comment by lgomesrj** [comment]
> @lgomesrj goaccess is a log analyzer for web server access logs. You will need to use a different tool to analyze your log.

Ok. Tks for your help.
