### ISSUE TITLE
Add note to either man page or website that GeoIP Cities is only shown in the hosts panel

### ISSUE THREAD

**Issue by johnbyers** [allinurl/goaccess#1231]
I successfully got GeoIP cities working, but was confused when I couldn't drill down in the Geo Location panel beyond Continent/Country. It wasn't until seeing Issue 750 that I learned cities are only shown in the hosts panel. I think an official source should mention that cities are only shown in the hosts panel, either the man page or maybe the Goaccess website.

**Comment by johnbyers** [comment]
I'd be happy to contribute this sort of thing if someone can point me in the direction of either the web page or the man page source.

**Comment by allinurl** [comment]
Thanks for pointing that out. I can certainly add this to the man page. Any specific place you think it should go?

**Comment by johnbyers** [comment]
I think in a note in the GEOLOCATION OPTIONS section where it explains `--geoip-database=<geofile>` would be good.

**Comment by allinurl** [comment]
I've added this to the `--geoip-database=<geofile>` [section](https://goaccess.io/man#options). Thanks!
