### ISSUE TITLE
Get URL's matching 3XX,5XX

### ISSUE THREAD

**Issue by rccerezuela** [allinurl/goaccess#1235]
How can I filter the URL's matching 3XX or/and 5XX criteria?
For instance, I can see 404 URL's:

![image](https://user-images.githubusercontent.com/5818575/45713742-1eba2300-bb90-11e8-8b8d-f6c1d37be1e4.png)

I see this in the documentation: `$ awk '$9~/500/' access.log | goaccess -`
But, is it a way for having it grouped in reports?

Thanks in advance!

**Comment by allinurl** [comment]
Very close to what you have there:

    # tail -f -n +0 access.log | awk '$9~/3[0-9]{2}|5[0-9]{2}/' | goaccess -o out.html -

Please note that assumes `$9` is your status code field (Combined format), else you can always find it using: 

    # tail -10 access.log | awk '{print $9}'

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
