### ISSUE TITLE
macOS High Sierra is registered as Puma

### ISSUE THREAD

**Issue by hashworks** [allinurl/goaccess#1236]
I'm using goaccess v1.2. In my nginx access log I have multiple requests from Mac OS X 10.13 "High Sierra":

```
$ grep "Mac OS X 10.13" access.log | wc -l                                                                          
11745
``` 

Examples:
```
<ip> - - [05/Sep/2018:00:16:44 +0200] "GET /path HTTP/1.1" 301 178 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:58.0) Gecko/20100101 Firefox/58.0"            
<ip> - - [05/Sep/2018:00:16:45 +0200] "GET /path HTTP/1.1" 404 26419 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:58.0) Gecko/20100101 Firefox/58.0"          
<ip> - - [05/Sep/2018:00:55:29 +0200] "GET /path HTTP/1.1" 200 28321 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0.3 Safari/604.5.6"
<ip> - - [05/Sep/2018:01:19:19 +0200] "GET /path HTTP/1.1" 302 4962 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36"
```

However, all of those (and more) are noted as OS X 10.1 Puma (from 2001):
![goaccess output](https://fb.hash.works/fW3KB/)

And I'm quite sure that we don't get any requests from that. Sierra and El Capitan get counted just fine:
```
$ grep "Mac OS X 10.12" access.log | wc -l                                                                          
1446                                                                                                   
$ grep "Mac OS X 10.11" access.log | wc -l                                                                          
1406  
``` 

Edit: I also just tried with the current master, same result.

**Comment by allinurl** [comment]
Thanks for reporting this. It looks like `10.13` and `10_13_3` are both valid. I'm guessing [here's](https://github.com/allinurl/goaccess/blob/master/src/opesys.c#L202) where is failing. Let me take a look at this and I'll post back as soon as I find out what's going on.

**Comment by allinurl** [comment]
It looks like this is fixed upstream. Please build from [**development**](https://github.com/allinurl/goaccess#build-from-github-development) and let me know if that fixes the issue for you.

**Comment by hashworks** [comment]
You're right. I actually build from master to test this yesterday, but used the wrong binary in the end. My bad!
