### ISSUE TITLE
Macintosh OS names should include version numbers

### ISSUE THREAD

**Issue by hashworks** [allinurl/goaccess#1238]
As someone who has never used Macintosh in my live I find it quite difficult to differentiate names like `OS X El Capitan` from `OS X Yosemite`, I always have to look it up:

![goaccess output](https://fb.hash.works/fW3KB/)

It would be great to include version numbers:
* OS X 10.11 El Capitan
* OS X 10.9 Yosemite

**Comment by allinurl** [comment]
Thanks for pointing that out. I pushed a fix for this. It will be shipped in the upcoming release.
