### ISSUE TITLE
Time Distribution by HTTP Status code

### ISSUE THREAD

**Issue by zoulja** [allinurl/goaccess#1241]
Is there any way to generate Time Distribution by HTTP Status code chart?
Actually one of most important charts for analysis.

**Comment by allinurl** [comment]
You can preprocess and feed that goaccess e.g.,

    # awk '$9~/500/' access.log | goaccess -

**Comment by zoulja** [comment]
I got the point, but it's really resource consuming and not user-friendly way.
Is there any chance such function will be added in the future?
