### ISSUE TITLE
Need assistance with a timestamp containing miliseconds

### ISSUE THREAD

**Issue by zoulja** [allinurl/goaccess#1242]
I have access log in the following format:

    $datetime|$remote_addr:$remote_port|"$scheme://$host$request_uri" $status $body_bytes_sent "$http_referer" "$http_user_agent" "$http_x_forwarded_for" "$upstream_addr" "$upstream_status" "$upstream_connect_time" "$request_time"

Sample:

    2018-09-24 18:56:01:121|2.23.12.40:29390|"http://requested_URL" 206 24387 "-" "user-agent" "2.23.64.12" "3.69.96.27:80" "206" "0.001" "0.656"

I almost made it work, but can't get how to proceed miliseconds.
Here is what I have tried:

    '%d %T:%^|%h:%^|"%r" %s %b "%R" "%u "%^" "%^" "%^" "%^" "%T"' --date-format=%Y-%m-%d --time-format=%k:%M:%S - shows almost all statistics but no time distribution

    '%d %t:%^|%h:%^|"%r" %s %b "%R" "%u "%^" "%^" "%^" "%^" "%T"' --date-format=%Y-%m-%d --time-format=%k:%M:%S:%L 

and

    '%d %t|%h:%^|"%r" %s %b "%R" "%u "%^" "%^" "%^" "%^" "%T"' --date-format=%Y-%m-%d --time-format=%k:%M:%S:%L

lead to
```
Token '12' doesn't match specifier '%t'
Token '12' doesn't match specifier '%t'

```
How I can skip miliseconds and get correct time distribution chart?

**Comment by allinurl** [comment]
Can you please try with `--time-format=%T:%3N`? (haven't tested)

**Comment by zoulja** [comment]
I have tried. Time distribution chart is empty :(

**Comment by allinurl** [comment]
It looks like `strftime()` doesn't support the milliseconds. So you will have to do some preprocessing and strip it out.  Please build from [**development**](https://github.com/allinurl/goaccess#build-from-github-development) so you can properly parse a log containing pipes on it.

This works for me:

    sed 's@\(..\):\(..\):\(..\):\(...\)@\1:\2:\3@' access.log | goaccess --log-format='%d %t|%h:%^|"%U" %s %b "%R" "%u" %^ %^ %^ %^ "%T"' --date-format=%Y-%m-%d --time-format=%T --http-method=no --http-protocol=no

**Comment by zoulja** [comment]
Oh, so there simple way to teach parser that it should ignore miliseconds field?
Frankly speaking I was expecting --time-format=%k:%M:%S and %t:%^ should do the trick, why it doesn' work?
One more doubt about pipes - for me only time distribution chart doesn't work, but other things seem to be ok, what's exactly the problem about pipes?

**Comment by allinurl** [comment]
- There's no simpler way. If this becomes an issue for folks, I can work on a fix directly in goaccess. I'm not sure so far people are recording the ms part though. Is there any reason why you are recording the ms field? are you running nginx/apache?
- `%t:%^` is only grabbing the hour part and discards everything else, thus it doesn't solve the issue.
- A bug was reported not too long time a go regarding pipes as delimiters. This was fixed upstream. If you don't build from development, it's likely it won't parse each field correctly or miss some panels as in your case.

**Comment by mathieu-aubin** [comment]
Wow, logs containing millisconds, thats hardcore.

i manage servers with over 32 million requests a day and frankly never saw the need for using milliseconds. I am curious as to why you log this way too.

**Comment by zoulja** [comment]
It's defaul configuration provided by solution's vendor.
Yes, it's Nginx log.
If you guys insist it's overhead - I will change it :)

**Comment by allinurl** [comment]
@zoulja Please try the following before building from development:

    # apt-get install gettext autopoint

**Comment by zoulja** [comment]
@allinurl, sorry for bothering you, but I have SUSE, in isolated environment, so it's not  that simple.
I understand resources of one person is not enough to support all distros, so let's close this, I will stay on 1.2

**Comment by allinurl** [comment]
Try:

    # zypper in gettext-tools

Closing this. Feel free to reopen it if needed.
