### ISSUE TITLE
Debian 9   package with  missing some options 

### ISSUE THREAD

**Issue by miroslavzlatinov** [allinurl/goaccess#1243]
Hello , installed goaccess from repo  
goaccess |      2:1.2 | http://deb.goaccess.io stretch/main amd64 Packages

when enabled some options in  config file recieved 
 
goaccess: unrecognized option '--std-geoip'
goaccess: unrecognized option '--geoip-database'
goaccess: unrecognized option '--keep-db-files' 
goaccess: unrecognized option '--db-path'

am i missing some previos enable option or it is not included ?

**Comment by allinurl** [comment]
Thanks for reporting this. For on-disk support, please try: 

    # apt-get install goaccess-tcb

GeoIP support wasn't included in the last built (see #1191). This will be included for sure in the upcoming release, which BTW, it replaces the existing on-disk support so you could simply install as `# apt-get install goaccess`. 

If you need GeoIP, please build from [**source**](https://goaccess.io/download#installation).
