### ISSUE TITLE
Need assistance with a timestamp containing miliseconds log/date/time format question

### ISSUE THREAD

**Issue by hichnicksemen** [allinurl/goaccess#1245]

**Comment by hichnicksemen** [comment]
Hi!

I try to convert log:
` log_format  main    '$remote_addr - $remote_user [$time_local] "$request" $status $body_bytes_sent '
                        '"$http_referer" "$http_user_agent" "$http_x_forwarded_for" '
                        '"ticket=$cookie_ticket,tracking=$cookie_tracking,_lang=$cookie__lang" "-" "$upstream_http_x_auth_ticket" '
                        '"[cs=$upstream_cache_status, request_time=$request_time, upstream_response_time=$upstream_response_time, upstream_response_length=$upstream_response_length, upstream=$upstream_addr//$upstream_status]" '
                        '"[$host]"';`

With nginx2goaccess.sh it shows:
`log_format %h - %^ [%d:%t %^] "%r" %s %b "%R" "%u" "%^" "ticket=%^,tracking=%^,_lang=%^" "-" "%^" "[cs=%^, request_time=%T, upstream_response_time=%^, upstream_response_length=%^, upstream=%^//%^]" "[%v]"`

But no T.S. data in html report.

**Comment by allinurl** [comment]
Please post a few lines from your access log. Thanks.

**Comment by hichnicksemen** [comment]
`213.87.128.59 - - [28/Sep/2018:14:50:09 +0300] "GET /api/timetable/lessons?fromdate=2018.09.24&todate=2018.09.29&groupoid=9523&receiverType=3 HTTP/2.0" 200 2710 "https://www.hse.ru/ba/economics/timetable?fromdate=2018.09.24&todate=2018.09.29&groupoid=9523&receiverType=3&timetable-courses=1&timetable-groups=9523" "Mozilla/5.0 (iPhone; CPU iPhone OS 11_4_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.0 Mobile/15E148 Safari/604.1" "-" "ticket=-,tracking=W9JpHliQixZWRxM8AyeGAg==,_lang=-" "-" "-" "[cs=HIT, request_time=0.000, upstream_response_time=-, upstream_response_length=-, upstream=-//-]" "[www.hse.ru]"
5.9.32.222 - - [28/Sep/2018:14:50:09 +0300] "GET /en/news/keywords/211414447/ HTTP/1.1" 200 8745 "-" "Mozilla/5.0 (compatible; MegaIndex.ru/2.0; +http://megaindex.com/crawler)" "-" "ticket=-,tracking=CgAGP1uuEn8dNUrRAxJbAg,_lang=-" "-" "-" "[cs=EXPIRED, request_time=0.574, upstream_response_time=0.572, upstream_response_length=37468, upstream=10.0.6.92:12606//200]" "[scr.hse.ru]"
66.249.64.133 - - [28/Sep/2018:14:50:09 +0300] "GET /lfk/ HTTP/1.1" 200 9505 "-" "Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.96 Mobile Safari/537.36 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)" "-" "ticket=-,tracking=-,_lang=-" "-" "-" "[cs=HIT, request_time=0.000, upstream_response_time=-, upstream_response_length=-, upstream=-//-]" "[phil.hse.ru]"
`

Thank you!

**Comment by allinurl** [comment]
This should work, please try:

    goaccess access.log --log-format='%h %^[%d:%t %^] "%r" %s %b "%R" "%u" "%^" "%^" "%^" "%^" "%^ %^=%T, %^"' --date-format='%d/%b/%Y' --time-format=%T

**Comment by hichnicksemen** [comment]
It works in terminal, but i need html real time:
`goaccess -o /report.html --real-time-html --port=8080 --log-format='%h %^[%d:%t %^] "%r" %s %b "%R" "%u" "%^" "%^" "%^" "%^" "%^ %^=%T, %^"' --date-format='%d/%b/%Y' --time-format=%T`
![fireshot capture 27 - server statistics - http___webproject pro_report html](https://user-images.githubusercontent.com/3232931/46207280-7ba39f00-c32f-11e8-99e5-dae897097daa.png)

**Comment by allinurl** [comment]
That should do it. However, please note goaccess doesn't yet a have a built-in web server, so you need to place the report.html file under your apache/nginx/other web server document root folder. Also please ensure port 8080 is opened and that it's not being used by your web server (otherwise you can always use the default port 7890 and open that port).

**Comment by hichnicksemen** [comment]
Ok thanks anyway! i'll try again.
