### ISSUE TITLE
Ignoring user-agents (bots)

### ISSUE THREAD

**Issue by da2x** [allinurl/goaccess#125]
Hi. There should be an option (possibly by default)  to hide certain hyper-active bots like Pingdom or UptimeRobot by User-Agent.

**Comment by n0ego** [comment]
Hi. It's currently marked Pingdom and UptimeRobot as Uptime in the source code. Does this mean they are on the list of crawlers? I'm running Goaccess 0.9.3 and Pingdom/UptimeRobot still appear as top results in the Visitor hostnames and IPs panel.

**Comment by allinurl** [comment]
@n0ego They're not, they are in the "Uptime" category. 

I do agree that having the ability to list them on a text file would be much easier. A drawback with this would be that the size of the list is actually proportional to the run time, so having a long list could slow down the parsing. Nonetheless, feel free to open a new issue with this request so I can look into it.

**Comment by n0ego** [comment]
I've opened a new issue [https://github.com/allinurl/goaccess/issues/560](560). Do you know how to exclude/ignore Uptime category form the stats similar to crawler list or how the Uptime category works?

Many thanks.

**Comment by allinurl** [comment]
@n0ego Right now you can't without doing some pre-processing. For example, you could do:

    # grep -v "`cat exclude_bots_list_file`" access.log | goaccess

The upcoming filters functionality (issue #117) should be able to handle this.
