### ISSUE TITLE
Hi my name is Leonardo and I'm trying to read a syslog file. I have just one trouble, follow:

### ISSUE THREAD

**Issue by lgomesrj** [allinurl/goaccess#1252]
Token 'Oct' doesn't match specifier '%h'
 The "Oct" represent the month parameter and I don't know how can I setup this and also how parameter to use.

_Originally posted by @lgomesrj in https://github.com/allinurl/goaccess/issues/1230#issuecomment-426313497_

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
