### ISSUE TITLE
Analyze HA Proxy logs in real time?

### ISSUE THREAD

**Issue by anduingaiden** [allinurl/goaccess#1253]
Is there a way to perform a real-time HA Proxy log analysis using GoAccess? I have searched on the internet and I just could find some tries (much of them failed) to parse the log to open it statically later.

My HA Proxy log format is something like:

    Oct  2 15:52:26 qq2-we-vm-hap01 haproxy[18366]: 10.0.0.1:44755 [02/Oct/2018:15:52:26.272] QQ_443_FE~ TEST_API_443_BE/QQ2-WE-VM-WEB01-443 10/0/5/29/44 200 1478 - - ---- 2/1/0/1/0 0/0 {testapi.lalala.net} "GET /v1//lolololol/216 HTTP/1.1"

Thanks in advance!

**Comment by allinurl** [comment]
Could you please describe the fields you got there? Thanks

**Comment by anduingaiden** [comment]
Hi allinurl, sorry but I did not understand what you ask. The fields I have on my haproxy logs are depicted above. I just want to know if there is a way to do a reali-time parsing and monitoring on a haproxy log.

I know that I can parse a haproxy log if I execute the following command:
`goaccess -f haproxy.log --log-format='%^  %^ %^:%^:%^ %^ %^[%^]: %h:%^ [%d:%t.%^] %^ %^ %^/%^/%^/%^/%L %s %b %^ %^ %^ %^/%^/%^/%^/%^ %^/%^ "%r"' --date-format='%d/%b/%Y' --time-format='%H:%M:%S' -q`

But after I do that  all I have is static information, It will not be updated by the time the log receives new entries. Is there a way to do that? 
Thanks in advance!

**Comment by allinurl** [comment]
Yes you can certainly parse the log in real-time. Please make sure you are running the latest version and let me know if that solves the issue for you.

**Comment by allinurl** [comment]
Please make sure to add `--real-time-html` to your command. Some examples [**here**](https://github.com/allinurl/goaccess#usage--examples).

Closing this, feel free to reopen it as needed.
