### ISSUE TITLE
Do not get goaccess to work with my log file

### ISSUE THREAD

**Issue by Jurnjuistdit** [allinurl/goaccess#1255]
Hi, I went through all kind of issues, but I am not able to get the default vcombined to work

THis is an example of a line:

testma.mantagifts.com:443 ip-217-105-39-28.ip.prioritytelecom.net - mantasalesapp [04/Oct/2018:07:53:48 +0200] "POST /sales_app/backups/backup.php HTTP/1.1" 200 427 "-" "Appcelerator Titanium/7.4.0 (iPad/12.0; iOS; en_US;)"

This is my command:
> goaccess /var/log/apache2/access_ssl_testma.mantagifts.com.log --log-format=VCOMBINED

..
Token 'ip-217-105-39-28.ip.prioritytelecom.net' doesn't match specifier '%h'
..
Format Errors - Verify your log/date/time format

I have tried multiple thinkgs (custom log, time etc),but nothing seem to work. Can you help me with this?
Thanks

**Comment by allinurl** [comment]
You need a valid IPv4/6. GoAccess doesn't parse the hostname as it's not completely unique. You will need to strip it out from your log and replace it with a valid IP, or skip resolving the IP.

**Comment by Jurnjuistdit** [comment]
Ok, thanks. Will manage this

**Comment by allinurl** [comment]
Closing this, feel free to reopen it if needed.
