### ISSUE TITLE
tail -f access.log,when logrotate  run, real-time-html  will not update

### ISSUE THREAD

**Issue by sbmzhcn** [allinurl/goaccess#1257]
when i use cmd 

`tail -f /var/log/nginx/access.log | /usr/local/bin/goaccess -o /home/wwwroot/default/report.html --real-time-html --log-format='%^ %^[%d:%t %^] "%r" %s %b "%R" "%u" "%h"' --date-format=%d/%b/%Y --time-format=%T  --keep-db-files --load-from-disk  --db-path=/home/wwwroot/default/ `

work normal. 

but when logrotate run (daily run).  **report.html** data will not update. so i have to rerun above cmd `tailf -f ....`

**Comment by allinurl** [comment]
Please use `tail -F` instead.

**Comment by sbmzhcn** [comment]
thank you.   @allinurl 
https://unix.stackexchange.com/questions/410471/tail-f-but-when-the-file-is-deleted-and-re-created-not-appended
