### ISSUE TITLE
Question regarding log-format

### ISSUE THREAD

**Issue by artiskool** [allinurl/goaccess#1258]
First of, I would like to thank you for building this awesome and free app. I just want to inquire how virtual hostname or IP works?

For example I have logs like:

**66.249.71.43** - - [01/Oct/2018:07:14:57 +0000] "GET / HTTP/1.1" 401 4230 "-" "Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.96           Mobile Safari/537.36 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"

**hostname-66.domain.com** - - [01/Oct/2018:07:14:57 +0000] "GET / HTTP/1.1" 401 4230 "-" "Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.96           Mobile Safari/537.36 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"

%h tag the second sample log as invalid requests and %v won't work. Is there something like %h|%v or something like that?

Thanks.

**Comment by allinurl** [comment]
Thanks. Glad you found it useful. 

GoAccess doesn't parse the hostname as it's not completely unique. You will need to strip it out from your log and replace it with a valid IP, or skip resolving the IP.

**Comment by artiskool** [comment]
I'm running on Ubuntu + Apache.

I tried using `log-format COMBINED` it works but it has a lot of `Failed Requests` due to hostname or DNS since logs with `hostname-66.domain.com` for instance will be treated as invalid-request while `log-format VCOMBINED` creates an error.

**Comment by allinurl** [comment]
You will need to change your apache config to `HostnameLookups Off`

**Comment by artiskool** [comment]
Actually it's already Off by default and I did not make any change to that config. Unfortunately I can change the apache logging format but it may cause incompatibility issue with the existing logs.

**Comment by allinurl** [comment]
The only workaround I can think of would be to replace those entries with a bogus IP, e.g., 127.0.0.1. awk, sed, etc, may help in this case. 

If you are able to change the config so that your apache doesn't resolve it, would be better though.

**Comment by artiskool** [comment]
Thanks a lot of your help. One more thing, does it affect the way GoAccess calculates Geo Location panel if changing hostnames to bogus IP?

**Comment by allinurl** [comment]
No problem. It will affect Geolocation as well as unique visitors count.You could run `nslookup` and resolve the IP but it will be messy and could take time.

**Comment by artiskool** [comment]
Thank you very much for accommodating my questions.
