### ISSUE TITLE
macOS server 5 with HAPROXY

### ISSUE THREAD

**Issue by darkjlz** [allinurl/goaccess#1260]
Hi,
I cannot find out the parsing parameters for the access log for macOS / Haproxy.

2 examples : 

    default 216.244.66.240 - - [07/Oct/2018:23:19:17 +0200] "GET /robots.txt HTTP/1.1" 404 269 "-" "Mozilla/5.0 (compatible; DotBot/1.1; http://www.opensiteexplorer.org/dotbot, help@moz.com)"
    default 127.0.0.1 - - [07/Oct/2018:23:15:57 +0200] "OPTIONS * HTTP/1.0" 200 - "-" "Apache/2.4.33 (Unix) LibreSSL/2.2.7 PHP/7.1.16 (internal dummy connection)"

Any ideas  ? thanks

**Comment by allinurl** [comment]
This should work:

    goaccess access.log --log-format='%v %h %^[%d:%t %^] "%r" %s %b "%R" "%u"' --date-format=%d/%b/%Y --time-format=%T

**Comment by darkjlz** [comment]
Amazing , **thank you so much**, it works !
