### ISSUE TITLE
Slows to a crawl on large access_log file...

### ISSUE THREAD

**Issue by geneb** [allinurl/goaccess#1262]
I'm feeding a 22GB access_log file (Apache) to v1.2 of goaccess.  It's been working on the file for four days and the more lines it processes, the slower it gets.  It's currently around 45 million lines into the file and is showing a process rate of 178 lines/sec.  When it first started, the lines/sec rate was over 15,000.

Is this a known issue?  
Here's how I'm running goaccess:
goaccess access_log -o goreport.html

tnx.

g.

**Comment by allinurl** [comment]
Sounds like it could be resolving some collisions on the hash table or btree. Could also be I/O bound. Are you running the on-disk storage or the default in-memory storage?

**Comment by geneb** [comment]
The only changes I've made to the configuration file was to let it know the time, date, and log formats.  The process is running on a fairly idle Dell R710, so I would be astonished if it was I/O bound.

I take it changing it from the default to on-disk would drastically improve the performance?

tnx.

**Comment by allinurl** [comment]
I'd actually say is the other way around. The on-disk storage is going away in the upcoming version as it hasn't been performing as expected. The in-memory storage should give you better performance. What is the output of `goaccess -s` ? Thanks

**Comment by geneb** [comment]
"Built using Tokyo Cabinet On-Disk B+ Tree"

**Comment by geneb** [comment]
Well like I mentioned before, the log file is 22GB in size - the machine only has 8GB of RAM allocated to it.
wc -l access_log returned a count of 100,693,427.
I didn't install goaccess from source - I installed it from yum (CentOS7).
A typical log entry looks like:  (it's the first line in the file)
65-78-97-139.c3-0.smt-ubr1.atw-smt.pa.cable.rcn.com - - [29/Oct/2005:21:02:54 -0
700] "GET /~geneb/f111-1.jpg HTTP/1.1" 200 66859 "http://images.google.com/imgre
s?imgurl=http://www.simpits.org/~geneb/f111-1.jpg&imgrefurl=http://forums.frugal
sworld.com/vbb/showthread.php%3Ft%3D85176&h=768&w=1024&sz=538&tbnid=izw5Y7p4keAJ
:&tbnh=112&tbnw=150&hl=en&prev=/images%3Fq%3DF-111%26start%3D20%26svnum%3D10%26h
l%3Den%26hs%3DE6i%26lr%3D%26client%3Dfirefox-a%26rls%3Dorg.mozilla:en-US:officia
l%26sa%3DN&frame=small" "Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.7.
12) Gecko/20050915 Firefox/1.0.7"

Suggestions?  I've killed the process - it would acknowledge the cancel, but didn't quit.
Thanks for the help!
g.

**Comment by allinurl** [comment]
I'd try building from [source](https://github.com/allinurl/goaccess#build-from-release) and see how it goes. I've been able to fit ~100M in a 8GB ram machine (tight but just keep an eye on it)

**Comment by geneb** [comment]
FYI, after re-running with the -q option, the process finished in about 5 hours.

**Comment by allinurl** [comment]
Using the on-disk storage or in-memory?

**Comment by geneb** [comment]
I never changed the default, so it was in-memory.

**Comment by allinurl** [comment]
Great! I thought you were using the `Built using Tokyo Cabinet On-Disk B+ Tree`. 

Closing this. Feel free to reopen it if needed.
