### ISSUE TITLE
Token '+0900]' doesn't match specifier '%h'? 

### ISSUE THREAD

**Issue by daebok** [allinurl/goaccess#1264]
I can't figure out why goaccess  error. What's wrong?

```
daum.net - - - [16/Jul/2018:00:00:00 +0900] "GET /resources/js/linkURL.js HTTP/1.1" 200 1185 "http://www.daum.net/mobile/news/view.do?ref=A&ncd=4009294" "Mozilla/5.0 (Linux; Android 7.0; SM-N920S Build/NRD90M) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Crosswalk/20.50.533.55 Mobile Safari/537.36 NAVER(inapp; search; 590; 8.8.2)"
```

```
$ goaccess access.log --log-format=VCOMBINED
Parsed 10 lines producing the following errors:

Token '+0900]' doesn't match specifier '%h'
Token '+0900]' doesn't match specifier '%h'
Token '+0900]' doesn't match specifier '%h'
Token '+0900]' doesn't match specifier '%h'
Token '+0900]' doesn't match specifier '%h'
Token '+0900]' doesn't match specifier '%h'
Token '+0900]' doesn't match specifier '%h'
Token '+0900]' doesn't match specifier '%h'
Token '+0900]' doesn't match specifier '%h'
Token '+0900]' doesn't match specifier '%h'

Format Errors - Verify your log/date/time format
```

```
LOG_FORMAT='%v %{X_FORWARDED_FOR}i %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\""'
```

```
$goaccess --version
GoAccess - 1.2.
For more details visit: http://goaccess.io
Copyright (C) 2009-2016 by Gerardo Orellana
```

**Comment by b350** [comment]
Same

log sample
`
XXX.XXX.XXX.XXX - - [09/Oct/2018:15:19:59 +0000] "GET / HTTP/1.1" 200 705 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:62.0) Gecko/20100101 Firefox/62.0" 332 1048`

config
```
time-format %H:%M:%S
date-format %d/%b/%Y
log-format %v:%^ %h %^[%d:%t %^] "%r" %s %b "%R" "%u"
```


error
```
Parsed 10 lines producing the following errors:

Token '+0000]' doesn't match specifier '%h'
Token '+0000]' doesn't match specifier '%h'
Token '-' doesn't match specifier '%h'
Token '-' doesn't match specifier '%h'
Token '-' doesn't match specifier '%h'
Token '-' doesn't match specifier '%h'
Token '+0000]' doesn't match specifier '%h'
Token '+0000]' doesn't match specifier '%h'
Token '+0000]' doesn't match specifier '%h'
Token '+0000]' doesn't match specifier '%h'
Format Errors - Verify your log/date/time format
```

**Comment by allinurl** [comment]
@b350  What fields are `332 1048`? Also, you don't appear to be logging the virtual host so won't be able to output that unless you add it to your apache/nginx config.

**Comment by allinurl** [comment]
@daebok You need a valid IPv4/6 so goaccess can parse it, are you resolving the IP?

**Comment by b350** [comment]
@allinurl I dunno, some numbers...
![numbers](https://user-images.githubusercontent.com/43731239/46744051-0632b980-ccb3-11e8-83c9-a5e34d5debde.PNG)

Sorry maybe I do not understand, I use the server control panel, It uses one access.log file for all domains.

**Comment by allinurl** [comment]
@b350 This should work (assumes the last field is the time taken to serve the req in micro secs):

    goaccess access.log --log-format='%h %^[%d:%t %^] "%r" %s %b "%R" "%u" %^ %D' --date-format=%d/%b/%Y --time-format=%T

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.

**Comment by teejaswin** [comment]
goaccess nginx_01.log --log-format='%h %^[%d:%t %^] "%r" %s %b "%R" "%u" %^ %D' --date-format=%d/%b/%Y --time-format=%T
Parsed 10 lines producing the following errors:

Token 'aurora_web_01_nginx.2.v91jxf20sutt@aurora-prod-web-1' doesn't match specifier '%h'
Token 'aurora_web_01_nginx.2.v91jxf20sutt@aurora-prod-web-1' doesn't match specifier '%h'
Token 'aurora_web_01_nginx.2.od8mdsws01ai@aurora-prod-web-1' doesn't match specifier '%h'
Token 'aurora_web_01_nginx.2.v91jxf20sutt@aurora-prod-web-1' doesn't match specifier '%h'
Token 'aurora_web_01_nginx.2.od8mdsws01ai@aurora-prod-web-1' doesn't match specifier '%h'
Token 'aurora_web_01_nginx.2.v91jxf20sutt@aurora-prod-web-1' doesn't match specifier '%h'
Token 'aurora_web_01_nginx.2.od8mdsws01ai@aurora-prod-web-1' doesn't match specifier '%h'
Token 'aurora_web_01_nginx.2.v91jxf20sutt@aurora-prod-web-1' doesn't match specifier '%h'
Token 'aurora_web_01_nginx.2.od8mdsws01ai@aurora-prod-web-1' doesn't match specifier '%h'
Token 'aurora_web_01_nginx.2.v91jxf20sutt@aurora-prod-web-1' doesn't match specifier '%h'

Format Errors - Verify your log/date/time format




I use the same above-mentioned format but still, I am getting error can you suggest me so suggestions

**Comment by allinurl** [comment]
@teejaswin please post some sample lines from your access log.
