### ISSUE TITLE
%h from this if available otherwise default to that

### ISSUE THREAD

**Issue by deepsets** [allinurl/goaccess#1266]
With log data like this

    [11/Oct/2018:00:00:01 +0300] 127.0.0.xx "-" "-" "monitor" "GET /server/abc/ HTTP/1.1" 200 80 10
    [11/Oct/2018:00:00:01 +0300] 10.37.140.xx "-" "-" "-" "GET /health/ptp " 200 2 83
    [11/Oct/2018:00:00:22 +0300] 10.37.140.xx "54.195.7.xx,54.195.7.xx" "-" "Monitor Bot" "GET /server/wws HTTP/1.1" 200 9015 14

the following settings works fine

`log-format %^[%d:%t %^] %h %^ "%R" "%u" "%r" %s %b %D`
`time-format %H:%M:%S`
`date-format %d/%b/%Y`

But I would like to use "54.195.7.xx,54.195.7.xx" as %h when ever is available. To be more precise, use column 3 when data available, otherwise default to column 2.

**Comment by allinurl** [comment]
I'm curious as to why you want %h to be two IPs, what would be the use case?

**Comment by deepsets** [comment]
That column is set by {X-Forwarded-For} an should be external (internet) IPs. Would like goaccess to use one of those i guess and use it as primary source for client IP address. Looking through the log the two IPs are always the same. So how can I pick the first one if available?

**Comment by allinurl** [comment]
I'm not sure is possible. In the first two lines you posted above, there's no data on that field, `"-"`. goaccess requires a valid IPv4/6 consistently in order to uniquely identify the hit. I'm guessing the first IP is the server's IP so it wouldn't be of much use.

**Comment by allinurl** [comment]
The only possible way would be to add an option to define a default ip address in case `%h` (or `~h`) is empty. Closing this as it is a dup of **#679** .
