### ISSUE TITLE
What's the "\N" in ["protocol": "HTTP/1.1\N"]

### ISSUE THREAD

**Issue by qijianjun** [allinurl/goaccess#1267]
Hi, I found some json output files have `"protocol": "HTTP/1.1\N"` string and thus can't be loaded by **python json.loads()**, I don't know why there is a "\N", maybe it should be ""protocol": "HTTP/1.1" or "protocol": "HTTP/1.1\\N"?

**Comment by allinurl** [comment]
Can I ask what version of goaccess are you using? Could you please build from [**development**](https://github.com/allinurl/goaccess#build-from-github-development), there were a few fixes upstream that should address issues with the json parser.

**Comment by allinurl** [comment]
Might be related to #960.

**Comment by qijianjun** [comment]
I use version 1.2 now.
This problem doesn't matter much, I have done a little code work to workaround it.

```
$ goaccess --version
GoAccess - 1.2.
For more details visit: http://goaccess.io
Copyright (C) 2009-2016 by Gerardo Orellana
```

**Comment by allinurl** [comment]
Closing this as you have found a solution to this. Feel free to post it. Thanks.
