### ISSUE TITLE
How to generate .json output correctly

### ISSUE THREAD

**Issue by anthony-wh** [allinurl/goaccess#1268]
Can you please update you documentation with more examples how to use commands correctly?

```
To generate a JSON report:
# goaccess access.log -a -d -o report.json
```

But this generate empty .json file :/  

Also when I'm trying to generate with --json-pretty-print --enable-panel=<REQUESTS_STATIC>

I got:
`syntax error near unexpected token `newline'`

 I'm trying to get a json file with only one table REQUESTS_STATIC, if someone would share an example it would be great.

Btw, is there any way to disable css and js in output json file?

**Comment by allinurl** [comment]
Can I ask what version of goaccess are you using? Could you please build from [**development**](https://github.com/allinurl/goaccess#build-from-github-development), there were a few fixes upstream that should address issues with the json parser.

**Comment by anthony-wh** [comment]
I use goaccess-1.2

Thanks, i will try to install development, should I delete 1.2 before or they can be installed both?

**Comment by allinurl** [comment]
Yes.

    # make uninstall

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
