### ISSUE TITLE
Need Help with custom nginx access Logs

### ISSUE THREAD

**Issue by arihantdaga** [allinurl/goaccess#1275]
Hello guys,
I came across this library and after seeing demo i think its really great, i want to use it, however i couldnt figure out right configuration for my cusom nginx log format.. 

This is what i have in my nginx conf for custom format. 
```
'$remote_addr - $remote_user [$time_local] "$request" '
'$status $body_bytes_sent "$http_referer" '
'"$http_user_agent" "$http_x_forwarded_for"';
```
And this is how a line of access log look like for me -
```
27.49.201.3 - - [20/Oct/2018:23:45:19 +0530] "GET /updatefirmware HTTP/1.0" 200 2 "-" "MyClient" "-"
```

Can somebody please help me with right configuration for parsing these logs...

**Comment by allinurl** [comment]
This should work:

    goaccess access.log --log-format='%h %^[%d:%t %^] "%r" %s %b "%R" "%u" %^' --date-format=%d/%b/%Y --time-format=%T

**Comment by arihantdaga** [comment]
It Did.. @allinurl  Thanks a lot.. This is awesome..

**Comment by allinurl** [comment]
Great! Closing this.
