### ISSUE TITLE
Parsing timestamps from Traefik

### ISSUE THREAD

**Issue by ipmb** [allinurl/goaccess#1276]
Example timestamp `2018-10-12T17:20:36.403088507Z`

`%T` doesn't seem to be able to parse that sort of precision. I tried a few different methods without success.

**Comment by allinurl** [comment]
The following format should do it: `2018-10-12T17:20:36.403088507Z` = `%dT%t.%^`

**Comment by ipmb** [comment]
Perfect... thanks!
