### ISSUE TITLE
on-disk data retention

### ISSUE THREAD

**Issue by lencell** [allinurl/goaccess#1277]
I would like to know if it's possible to add a feature that would allow to select data retention for on-disk storage.

As I understand it is now either storing them forever, or removing everything on startup if `--keep-db-files` isn't specified.

Would it be possible to add, probably with a new startup option, the possibility to automatically remove all data that is older than X days (or weeks or month) to only keep the most recent data(both on disk and on display on the web UI) without having to wipe everything

**Comment by allinurl** [comment]
I like this idea. I can look into it. Thanks for the suggestion. Stay tuned!

**Comment by lencell** [comment]
Thank you, I'm glad to read this and will definitely follow it. I can help testing it if necessary.

**Comment by allinurl** [comment]
This has been implemented as [**v1.4**](https://goaccess.io/download). You can use `--keep-last=<numdays>`.  Give it a shot and post feel free to share the results.
