### ISSUE TITLE
Avg. T.S, Cum. T. & Max. T.S columns with apache or nginx default config

### ISSUE THREAD

**Issue by ivanhuay** [allinurl/goaccess#1278]
in a clean intallation of apache im just doing 

```
goaccess  /var/log/apache2/access.log -o /var/www/html/report.html --log-format=COMBINED --real-time-html
```
and Avg. T.S, Cum. T. & Max. T.S columns Not Showing
![image](https://user-images.githubusercontent.com/5782286/47369480-29e5fe80-d6ba-11e8-8ce5-cd4df8c32c9e.png)

but i can see these columns in live demo
https://rt.goaccess.io/?20180926071813

![image](https://user-images.githubusercontent.com/5782286/47369562-5437bc00-d6ba-11e8-8d71-a5bd4d6db082.png)

default debian `apache.conf` logFormat section
```
LogFormat "%v:%p %h %l %u %t \"%r\" %>s %O \"%{Referer}i\" \"%{User-Agent}i\"" vhost_combined
LogFormat "%h %l %u %t \"%r\" %>s %O \"%{Referer}i\" \"%{User-Agent}i\"" combined
LogFormat "%h %l %u %t \"%r\" %>s %O" common
LogFormat "%{Referer}i -> %U" referer
LogFormat "%{User-agent}i" agent
```

i also tried nginx with the same result

**Comment by allinurl** [comment]
You will need to add `%D` to your [apache log](https://httpd.apache.org/docs/current/mod/mod_log_config.html) format so it starts logging the time taken to serve the request, in microseconds. Then in goaccess you can add as well the `%D` to the `log-format` variable.

**Comment by ivanhuay** [comment]
that worked for me thanks!
