### ISSUE TITLE
Custom log formating

### ISSUE THREAD

**Issue by ashrafyassin** [allinurl/goaccess#1279]
hey, i need to know if i can use this tool to analyze my log files which are not web server logs : 
a sample of my log files:

    14224430529 | TX: id: 401550a, data:  27 0 0 0 0 0 0 212, dlc: 8, flags: 30004
    14224430597 | TX: id: 401550a, data:  27 0 0 0 0 0 0 213, dlc: 8, flags: 30004
    14224430662 | RX: id: 401550a, data:  27 0 0 0 0 0 0 214, dlc: 8, flags: 30004

where the first column is a timestamp, and it does not have an IP field or protocol
and i wanted to analyze this based on some calculation of mine 

 if so , how can i configure it to work with my logs
thanks

**Comment by allinurl** [comment]
Unfortunately you can't. To properly parse a log it needs a valid IPv4/6, date/time and the request.
