### ISSUE TITLE
When I add the --ignore-panel=VISITORS param, the time on top right corner turns to undefined

### ISSUE THREAD

**Issue by ip192** [allinurl/goaccess#1286]
Heres my commands:
```
/usr/local/bin/goaccess /var/log/nginx/access.log -o /usr/share/nginx/html/report.html 
--ignore-panel=VISITORS --real-time-html --daemonize
```
The time string on the top right corner turns to `UNDEFINED - UNDEFINED`. If I replace `VISITORS` with `REQUESTS`, it becomes normal.

Is that something to do with the language?(By the way, I install it on my centos7 with `zh_CN` env)

**Comment by allinurl** [comment]
The time string on the top right corner depends on the VISITORS panel and thus `UNDEFINED`, I'll have a fix for this soon. Thanks.

ref:
https://github.com/allinurl/goaccess/blob/master/src/output.c#L251

**Comment by allinurl** [comment]
This has been fixed and will be pushed out in the upcoming version. Thanks again for reporting it.
