### ISSUE TITLE
【Resolved】To perform a static link to "OpenSSL" library?

### ISSUE THREAD

**Issue by 4f8p** [allinurl/goaccess#1287]
I'm trying to replace the base image with "BusyBox" using "multi-stage build" function introduced in Docker 17.05 or later.

However, it fails to build when you try to static link the "OpenSSL" library fails. 🤔
**(Apparently it seems that configure fails because "SSL_CTX_new" can't be found.)**

I tried several approaches already _(eg setting static flags on pkg-config)_, but everything failed.
How can I solve a static link to the "OpenSSL" library?

If successful in this attempt, I plan to donate it to the GoAccess project.
Thanks.

---

"OpenSSL" By using the "LibreSSL" library instead of the library, solved this problem. :raised_hands:

**Comment by allinurl** [comment]
Thanks for sharing the solution!
