### ISSUE TITLE
Goaccess show error data on real-time HTML report due to loading wrong data from multiple websocket service

### ISSUE THREAD

**Issue by gaohaoning** [allinurl/goaccess#1289]
I need to run multiple goaccess processs with --real-time-html option to analyze multiple logs.
my commands are:

    /usr/bin/goaccess --real-time-html -o /data/html/log1/index.html -f log/log1.log --port=7890
    /usr/bin/goaccess --real-time-html -o /data/html/log2/index.html -f log/log2.log --port=7891
...

when only 1 process is running, everything is ok, and I can see the data frames of websocket on Chrome, every data frame is generally the same length;

But when 2 or more processes are running, 2 things happened:
1. On the terminal which goaccess processes are running, "SIGPIPE caught!" came out continuously;
2. On the web page, the dashboard are showing wrong data discontinuously, and I notice that the websocket data frames received by the browser are quite different in length(which means the web page are receiving different websocket data frames from other goaccess processes), when the data frame length are similiar to the data length when only 1 goaccess process is running, the data shown on the web page are right, when the data frame length ars different, the data ares wrong.

It seems like that even I run the goaccess process with "--port" option to specify different port for every WebSocket process, multiple websocket services ares still mixed up.

**Comment by allinurl** [comment]
Please take a look at this [**post** ](https://github.com/allinurl/goaccess/issues/625#issuecomment-272905761) for details on multiple instances and the options needed

**Comment by gaohaoning** [comment]
after run different processes with --fifo-in --fifo-out option，everything goes fine.
Thx a log~
@allinurl
