### ISSUE TITLE
custom log format / additional identifiers

### ISSUE THREAD

**Issue by pille** [allinurl/goaccess#1290]
i'm trying to make goaccess understand my custom log format. basically it's standard apache, but extended by some fields. i've read parser.c to build my own format, but failed to find the following identifiers:

```
 127.0.0.1- - [01/Nov/2018:07:48:51 +0000] "GET / HTTP/1.1" 302 120 "-" "Mozilla/5.0" 616 6347 mod_deflate: In:124 Out:102:82pct 62485 0 - localhost
<---------------- A P A C H E  F O R M A T ----------------------------------------->  %I  %O  mod_deflate: In:%IC Out:%OC:%Cpct   %D %k %s   %v
```
%I received bytes (total)
%O sent bytes (total)
%IC compression input bytes
%OC compresseion output bytes
%C compression ratio
%k keepalive requests
%s status 

here's the apache log format config:
```
LogFormat "%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\" %I %O mod_deflate: In:%{deflate_in_info}n Out:%{deflate_out_info}n:%{deflate_ratio_info}npct %D %k %X %V"
```

in general it would be useful to have a "ignore"-identifier, so that we can parse logs, even though some fields are not implemented.

**Comment by allinurl** [comment]
Please try the following:

    goaccess access.log --log-format='%h %^[%d:%t %^] "%r" %s %b "%R" "%u" %^ %^ %^ %^ %^ %D %^' --date-format=%d/%b/%Y --time-format=%T

**Comment by allinurl** [comment]
Closing this. Please feel free to open a new issue so I can look into the compression ratio panel. Thanks.
