### ISSUE TITLE
Request: Please update the pot file.

### ISSUE THREAD

**Issue by 4f8p** [allinurl/goaccess#1300]
I declared to send a Docker image with a pull request before.
However, given the burden of the developers, I judged that the decision was not good and changed the policy.

Since satisfactory results were obtained with some tests, I decided to release it as an **Unofficial** Docker image.
At the same time, I had some experimental features implemented.

## Main subject

[Demonstration](http://goaccess.4f8p.com/)

Looking at this, most are localized, but there are parts that are not partially localized.
There seems to be a missing part in the pot file.

Especially not priority, but please update the pot file.
As soon as the missing part is complemented, I update the localization file.

Thanks.

**Comment by allinurl** [comment]
This is really nice. Thanks for sharing it!

**Comment by 4f8p** [comment]
Don't mention it. :sunglasses:

It already functions in part of the staging environment and has earned high reputation "It became easy to find high-load process".

I will continue to maintain Japanese localization. If I can be of assistance, please don't hesitate to contact me.

Best regards,

**Comment by 4f8p** [comment]
#1301 `Bandwidth` :arrow_right: `Tx. Amount`
