### ISSUE TITLE
Incorrect term used (bandwidth)

### ISSUE THREAD

**Issue by tlleech** [allinurl/goaccess#1301]
I often find that people describing the amount of data as "bandwidth". It is incorrect.

Can we please use the correct term? Please refer to the following url (Bandwidth in web hosting section):
https://en.wikipedia.org/wiki/Bandwidth_(computing)#Network_bandwidth_consumption

**Comment by allinurl** [comment]
I can certainly change that. Thanks for the heads up.

**Comment by allinurl** [comment]
This has been changed and will be pushed in the upcoming release. Thanks again!
