### ISSUE TITLE
Show full URL in Data column

### ISSUE THREAD

**Issue by manacim** [allinurl/goaccess#1302]
Hello, I have 18 sites with their own logs. Data column does not show which domain the URLs belongs to so it only shows /URI. Here's my log format:

`%h %D %^ [%d:%t %^] %^ "%r" %s %b "%R" "%u"`

Is this an Nginx issue or log format? Also I used EasyEngine.io to setup my sites.

```
# Nginx log format Settings
log_format rt_cache '$remote_addr $upstream_response_time $upstream_cache_status [$time_local] '
'$http_host "$request" $status $body_bytes_sent '
'"$http_referer" "$http_user_agent"';
```

![](https://i.imgur.com/sj8NzXQ.png)

**Comment by allinurl** [comment]
Please take a look at the **Virtual Host** [examples](https://goaccess.io/man#examples) section, it should show you how to append the virtual host to the request.

**Comment by manacim** [comment]
Thank you, this did the trick:

`awk '$8=$6$8'`

I have goaccess installed on my computer and not on the server so I'm doing a passwordless tail to the server and then piping it to goaccess.
