### ISSUE TITLE
Add Haiku user agents - os detection

### ISSUE THREAD

**Issue by kallisti5** [allinurl/goaccess#1307]
Haiku has several user agents that can be used for OS detection:

Web Browser:
  * "Mozilla/5.0 (Macintosh; Intel Haiku R1 x86)"  - WebPositive web browser running on Haiku

Various Operating System internals:
  * "Services Kit (Haiku)"  - Haiku's package management system
  * "HaikuDepot/0.0.2" - Haiku's desktop software center

We have "Macintosh" in the User Agent for now to prevent random sites from giving us mobile pages due to User Agent sniffing + horrible assumptions.

**Comment by pulkomandy** [comment]
Don't touch the web browser user agent. It took me month of tuning so that websites don't go "WebKit and not Macintosh? Must be some kind of iPhone" and serve us mobile pages.

Yes, user agent sniffing is still a thing :(

**Comment by allinurl** [comment]
v1.3 has been released. It includes the ability to specify a custom list of browsers using --browsers-file=<path>. Please take a look at the sample file [**here**](https://github.com/allinurl/goaccess/blob/master/config/browsers.list).
