### ISSUE TITLE
Filter out unused browser sockets

### ISSUE THREAD

**Issue by Aeyoun** [allinurl/goaccess#131]
Browsers (Chromium based and others) open two TCP sockets to the server. However, if few resources are served one remains unused and the browser eventually closes the unused socket. In access logs from nginx/apache, this will look like the below line. These lines should be disregarded entirely (empty timed out request).

    127.0.0.1 - - [03/Jul/2014:23:46:44 +0200] "-" 400 0 "-" "-"
    127.0.0.1 - - [03/Jul/2014:23:46:47 +0200] "-" 400 0 "-" "-"

About 8 % of my logs consist of lines like the above.

**Comment by allinurl** [comment]
Daniel , I was looking at this, however, I haven't been able to reproduce it using Chrome. Do you know how to replicate it? that way I know exactly how to disregard them.  Thanks.

**Comment by Aeyoun** [comment]
Minimal HTML page on a server should do the trick. Not sure how much caching is involved. Try altering the domain? Load up the page, wait three minutes and look in the logs. All my servers are setup with HTTPS. Not sure if that is involved and I haven’t got the opportunity to test again just now.

**Comment by aphorise** [comment]
This is the responsibility of the log collector / maintainer to ensure that an appropriate setup is in place on their web-server and that a consistent scheme / format is in use with their own logs.

To express bluntly all thats required - is:
1 - additional `cat`-`awk`-`grep` re-adjustments such as:
```grep -v '"-" 400 0 "-" "-"' raw.log > clean.log```
2 - or better yet proper configuration as part of vhost such as that of `apache2`:
```
# vhost (/etc/apache2/sites-enabled/...)
	ErrorLog /var/log/apache2/error.log
	CustomLog /var/log/apache2/access_combined.log combined env=!dontlog
	<Directory /var/www/>
		DirectoryIndex index.php index.html
		Options Includes FollowSymLinks
		Options Indexes FollowSymLinks MultiViews
		AllowOverride all
		Order allow,deny
		allow from all
		SetEnvIf Remote_Addr "127.0.0.1" dontlog
		# # // which will ignore everything from localhost see additional directives like `Request_URI`
	</Directory>
```

It may be nice to have additional exclusion (eg: regex) patterns for stdin data to be explicitly use only or exclude certain patterns where adjustments to the log are beyond the scope of the user - however IMO this particular request has been prematurely made and ought to be closed.

**Comment by allinurl** [comment]
I agree with @aphorise. I think this can be addressed before parsing the log with goaccess. `grep, sed, etc`. However, I added the ability to ignore parsing status codes using `--ignore-status=<code>`. This option can be applied multiple times for multiple codes.

This has been pushed out to master. Feel free to try it out from [dev](http://goaccess.io/download#build). It will be out in the upcoming version.
