### ISSUE TITLE
Separate MS Edge from less capable MS Internet Explorer (perhaps optionally).

### ISSUE THREAD

**Issue by kenguest** [allinurl/goaccess#1314]
It would be useful to, perhaps optionally, not have MS Edge in the same category as the less capable MS Internet Explorer.
This is because more modern website work better with Edge than with IE (check out https://caniuse.com/#compare=ie+11,edge+18&compare_cats=HTML5,JS,JS%20API,Security ) so it should go into its own category I think.

**Comment by allinurl** [comment]
I can certainly make this change. Especially after they just decided to move to Chromium. Thanks for bringing this up.

**Comment by kenguest** [comment]
...and thanks for considering it! 👍

**Comment by allinurl** [comment]
This has been updated upstream. It will be pushed out in the upcoming release. Thanks again.

**Comment by kenguest** [comment]
fantastic - thank you!
