### ISSUE TITLE
Warning in manpage (trivial)

### ISSUE THREAD

**Issue by nodens** [allinurl/goaccess#1316]
Hi,

while preparing an update of the debian package, I noticed a warning on the manpage (actually lintian noticed it for me):

`usr/share/man/man1/goaccess.1.gz 325: warning [p 5, 9.5i]: cannot adjust line`

The issue is it cannot break any word in the json line, of course. And indeed it shouldn't break the line with a hyphen like it would in a sentence.

There is also a duplicated line that cause a warning (415).

I'll provide a PR.

Cheers,

nodens

**Comment by allinurl** [comment]
Merged. Thanks!
