### ISSUE TITLE
currently the dashboard shows a default time frame like 01/DEC/2018 — 03/DEC/2018 , can this time frame be altered?

### ISSUE THREAD

**Issue by rnjailamba** [allinurl/goaccess#1321]

**Comment by allinurl** [comment]
The date/time format? or a filtering option? For the former, #1310, for the later #117.

**Comment by rnjailamba** [comment]
filtering within a particular time tinterval ex. 01/DEC/2018 12:48 to 01/DEC/2018 12:56..

**Comment by allinurl** [comment]
#117 will address this.
