### ISSUE TITLE
How to specify log-format only?

### ISSUE THREAD

**Issue by xiangnanscu** [allinurl/goaccess#1325]
When I run `goaccess logs/error.log -o dist/report.html --log-format=COMBINED`, everything is OK.
I don't know where to apply this log format `%h [%d:%t %^] "%r" %s %b "%R" "%u" %T` while the rest configurations stay the same.
## I tried the content below in ~/.goaccessrc
```
log-format %h [%d:%t %^] "%r" %s %b "%R" "%u" %T
```
and run `goaccess logs/error.log -o dist/report.html`, get error
```
root@iZ94x23urx9Z:~/b# goaccess logs/error.log -o dist/report.html

GoAccess - version 1.3 - Dec  5 2018 20:01:20
Config file: /root/.goaccessrc

Fatal error has occurred
Error occurred at: src/parser.c - parse_log - 2764
No time format was found on your conf file.
```

##  I tried specify in command:
```
goaccess logs/error.log -o dist/report.html --log-format="%h [%d:%t %^] \"%r\" %s %b \"%R\" \"%u\" %T"
```
and get error:
```
GoAccess - version 1.3 - Dec  5 2018 20:01:20
Config file: No config file used

Fatal error has occurred
Error occurred at: src/parser.c - parse_log - 2764
No time format was found on your conf file.
```

**Comment by xiangnanscu** [comment]
Seems I've to specify time format. But I only want to set log-format, is there any way to get this?

**Comment by xiangnanscu** [comment]
I tried `~/.goaccessrc` as below:
```
date-format %d/%b/%Y
time-format %H:%M:%S
log-format %h %^[%d:%t %^] "%r" %s %b "%R" "%u" %T
```
and run `goaccess logs/error.log -o dist/report.html`, error disappear, but the `Init. Proc. Time` is `0` which should be `11`. 
## log file is only two lines:
```
127.0.0.1 [18/Nov/2018:23:13:45 +0800] "GET /orgConfigUsers HTTP/1.1" 200 581 "http://tcpip.vip:9000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36" 11
127.0.0.1 [18/Nov/2018:23:14:45 +0800] "GET /orgConfigUsers HTTP/1.1" 200 581 "http://tcpip.vip:9000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36" 11

```
Is this normal or I miss something?

**Comment by allinurl** [comment]
This should work.

    goaccess access.log --log-format='%h [%d:%t %^] "%r" %s %b "%R" "%u" %T' --date-format=%d/%b/%Y --time-format=%T -o report.html
 
I'm not sure what you mean with `Init. Proc. Time` is 0 which should be 11.

**Comment by xiangnanscu** [comment]
thanks.
