### ISSUE TITLE
Please help with my error log-format (custom nginx)

### ISSUE THREAD

**Issue by ilyazakruta** [allinurl/goaccess#1326]
Hi
tried this

    log-format %d %t %^ %^ %^ %^ "%r" %s %b "%R" "%u" "%T" "%^" "%^" "%^"

log file errors.log

    2018/12/02 06:33:08 [error] 8001#8001: *655829940 "/var/www/html/index.html" is not found (2: No such file or directory), client: 104.222.43.41, server: , request: "GET / HTTP/1.1", host: "news1.golderynsaffet.webcam"

received
```
Token 'OST' doesn't match specifier '%s'
Token 'ET' doesn't match specifier '%s'
Token 'ET' doesn't match specifier '%s'
Token 'OST' doesn't match specifier '%s'
Token 'ET' doesn't match specifier '%s'
Token 'OST' doesn't match specifier '%s'
Token 'ET' doesn't match specifier '%s'
Token 'OST' doesn't match specifier '%s'
Token 'ET' doesn't match specifier '%s'
Token 'ET' doesn't match specifier '%s'
```

please tell me how to make a format? 
explain to me how you do it. I do not understand, but I want to learn

**Comment by ilyazakruta** [comment]
log-format %d %t %^ %^ %^ %^ %^ %^ %^ %^ %^ %^ %^ %^ %^ ~h{,} %^ "%r" %v

**Comment by ilyazakruta** [comment]
html is not exported (

**Comment by allinurl** [comment]
The following should work for the line you posted. However, please note goaccess is NOT an error log parser, so depending on the message, it will work or it may not.

    goaccess access.log --log-format='%d %t %^ %^ "%^" %^, %^: %h, %^"%r", %^: "%v"' --date-format='%Y/%m/%d' --time-format=%T

**Comment by ilyazakruta** [comment]
Parsing... [0] [0/s]
not exported

**Comment by allinurl** [comment]
As I said, you need to parse an access log not an error log for goaccess to work.
