### ISSUE TITLE
Recommend way to run goaccess realtime in the background?

### ISSUE THREAD

**Issue by xiangnanscu** [allinurl/goaccess#1327]
I want to do this in my production server so it should be light weight (so things like npm `forever` is not OK even if it is almost there), and be simple (so `supervisor` is out ).

**Comment by neocogent** [comment]
I run goaccess behind an nginx proxy using ssl with admin pwd auth. I use a systemd service to start and run goaccess. You can see my example configs and service files for [gopanel](https://github.com/neocogent/gopanel) in etc folder. This all fits nicely into a working nginx server.

**Comment by allinurl** [comment]
@neocogent Thanks for posting that!

@xiangnanscu Alternatively you can simply running goaccess with the default in-memory storage (assuming your dataset fits in mem) and running it as a daemon should do the trick. e.g., 

    goaccess /var/log/apache2/access.log -o /usr/share/nginx/html/site/report.html --real-time-html --daemon

**Comment by xiangnanscu** [comment]
@neocogent @allinurl thank you

**Comment by goalbased** [comment]
> @neocogent Thanks for posting that!
> 
> @xiangnanscu Alternatively you can simply running goaccess with the default in-memory storage (assuming your dataset fits in mem) and running it as a daemon should do the trick. e.g.,
> 
> ```
> goaccess /var/log/apache2/access.log -o /usr/share/nginx/html/site/report.html --real-time-html --daemon
> ```

How to stop it? Thank you

**Comment by allinurl** [comment]
@goalbased  `pkill goaccess`

**Comment by sivasankarsani737** [comment]
@allinurl Does it refresh the page everytime..??

I have ran the --daemon , but not getting the latest-counts on dashboard.

**Comment by allinurl** [comment]
@sivasankarsani737 make sure it's in fact connected to the WS server. The easiest indicator is the green dot next to the settings icon on the HTML report. You can also check the network WS tab under your browser's dev tools.
