### ISSUE TITLE
Can't read log files using cron or systemd

### ISSUE THREAD

**Issue by camaer** [allinurl/goaccess#1332]
I have and issue where using setting goaccess as a service using systemd or just settings it up in the crontab do not seems to read all the logs file. 

Here's the command I'm using in cron:
`/bin/zcat /var/log/nginx/access.log.*.gz | /usr/bin/goaccess /var/log/nginx/access.log /var/log/nginx/access.log.1 - -p /etc/goaccess/goaccess.conf -o /var/www/html/goaccess/report.html`

I have no errors in journalctl and goaccess starts correctly but it does not read all the other logs file.
Same issue when calling a script that contains the same command. I also tried to combine all the logs into one giant file but to no avail. Works fine when executed manually.

I'm using Ubuntu 16.04

Any ideas ?
Thanks

**Comment by allinurl** [comment]
Which version are you running?

**Comment by camaer** [comment]
1.3 Stable from the repo for Ubuntu/Debian

**Comment by PierrePlessy** [comment]
I have the same problem and i fixed it in create a script.

```
#!/bin/bash

set -e
set -u

zcat -f /var/log/nginx/access.log* | grep -v -f exclude_list.txt > /tmp/all_logs.log
goaccess /tmp/all_logs.log -p /etc/goaccess.conf -o /var/www/html/goaccess/index.html

```

I cut the command in two step :
- unzip all logs 
- parse logs with goaccess 

It's works manually and with crontab for me. I execute the script as sudo.

I'm using Debian8 & 9.

I hope this will help you.

**Comment by camaer** [comment]
Worked perfectly ! Thanks !

**Comment by allinurl** [comment]
Closing this. Thanks for sharing your solution!
