### ISSUE TITLE
Using custom output files doesn't work

### ISSUE THREAD

**Issue by fhe81** [allinurl/goaccess#1333]
When using a custom output file I always get the error 1168.

I use Apache on Mac. GoAccess is called as admin. All rights on the target directory are granted. I tried with and without existing report.html file in the destination directory.

GoAccess is called by "sudo goaccess /var/log/apache2/access_log -a > /Library/WebServer/Documents/stats/report.html --real-time-html" on the local server.

This is my config:
[goaccess.conf.txt](https://github.com/allinurl/goaccess/files/2696395/goaccess.conf.txt)

The console output works well.

**Comment by allinurl** [comment]
Strange, are you running this as root? Also have you tried writing to a file using the same user you are running goaccess? e.g.,

    $ touch /Library/WebServer/Documents/stats/file.txt

Also what's the output of `ls -lath /Library/WebServer/Documents/stats/`?

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
