### ISSUE TITLE
Custom log log/date/time format

### ISSUE THREAD

**Issue by 905839698** [allinurl/goaccess#1334]
39.108.196.70 - - [21/Dec/2018:14:25:25 +0800] "POST http://www.aiyilearning.com/course/6934/task/14323/trigger" "200" 461 "http://www.aiyilearning.com/course/6934/task/14323/show" "127.0.0.1:9000" "0.034" "0.034" "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36" "183.240.202.116"

Parsed 1 linesproducing the following errors:

Token '"200"' doesn't match specifier '%s'

Format Errors - Verify your log/date/time format

**Comment by allinurl** [comment]
goaccess access.log --log-format='%h %^[%d:%t %^] "%m %U" "%s" %b "%R" "%v" "%T" %^ "%u" %^' --date-format=%d/%b/%Y --time-format=%T --http-protocol=no

**Comment by allinurl** [comment]
Closing this, feel free to reopen it if needed.
