### ISSUE TITLE
error generating html file

### ISSUE THREAD

**Issue by waldbone** [allinurl/goaccess#1335]
Hello, first, sorry for my english!

I have big problems with my goaccess and need help.

-----------------------------------------------------------------------------------------
1.) the config file:

```
...
time-format %H:%M:%S
...
date-format %Y-%m-%d
...
# NCSA Combined Log Format
#
#log-format %h %^[%d:%t %^] "%r" %s %b "%R" "%u"
#
# NCSA Combined Log Format with Virtual Host
#
#log-format %^:%^ %h %^[%d:%t %^] "%r" %s %b "%R" "%u"
#
# Common Log Format (CLF)
#
#log-format %h %^[%d:%t %^] "%r" %s %b
#
# Common Log Format (CLF) with Virtual Host
#
#log-format %^:%^ %h %^[%d:%t %^] "%r" %s %b
```
-----------------------------------------------------------------------------------------

2.) This procedures work perfefect
  a.) `goaccess -f /var/log/apache2/access.log`
  b.) `goaccess -f /var/log/apache2/access.log -a`

In the next windows "Log Format Configuration" i select the option "**NCSA Combinet Log Format**" OR "**Common Log Format (CLF)**" and it works perfekt. Other options in the windows doesnt work.

-----------------------------------------------------------------------------------------

3.) Error 1
  a.) `goaccess -f /var/log/apache2/access.log -a --log-format=COMBINED`
  b.) `goaccess -f /var/log/apache2/access.log -a --log-format=COMMON`
  c.) `goaccess -f /var/log/apache2/access.log --log-format=COMBINED`
  d.) `goaccess -f /var/log/apache2/access.log --log-format=COMMON`

All of this commands return the same error messages:
     **Fatal error has occurred
     Error occured at: src/goaccess.c - main - 1033
     Nothing valid to process.**

-----------------------------------------------------------------------------------------

4.) Error 2
I aktivated in the config file this option:
`log-format %h %^[%d:%t %^] "%r" %s %b "%R" "%u"`

  a.) `goaccess -f /var/log/apache2/access.log`
  b.) `goaccess -f /var/log/apache2/access.log -a`
  c.) `goaccess -f /var/log/apache2/access.log -a --log-format=COMBINED`
  d.) `goaccess -f /var/log/apache2/access.log -a --log-format=COMMON`
  e.) `goaccess -f /var/log/apache2/access.log --log-format=COMBINED`
  f.) `goaccess -f /var/log/apache2/access.log --log-format=COMMON`

All of this commands return the same error messages:
     **Fatal error has occurred
     Error occured at: src/goaccess.c - main - 1033
     Nothing valid to process.**

WHAT IS WRONG?? It also not possible to generate a html file.
Please help.

**Comment by allinurl** [comment]
What version of goaccess are you running? 

Just trying to understand what you are saying, basically if you select the option from the ncurses dialog then it works but if you specify it as a command line option it doesn't?

**Comment by waldbone** [comment]
@allinurl: yes, that's right. 
If i select this two options **"NCSA Combinet Log Format"** and **"Common Log Format (CLF)"** in the dialog it works, but if i write the log-format 
`log-format=COMBINED` or 
`log-format=COMMON` direkt in the command line it doesn't work.

My GoAccess version: **0.9.4**

**Comment by waldbone** [comment]
> 
> 
> What version of goaccess are you running?
> 
> Just trying to understand what you are saying, basically if you select the option from the ncurses dialog then it works but if you specify it as a command line (see Point 3.) option it doesn't?

@allinurl: yes, that's right.

If i select this two options "**NCSA Combinet Log Format**" and "**Common Log Format (CLF)**" in the dialog it works, but if i write the log-format
`log-format=COMBINED` or
`log-format=COMMON` direkt in the command line it doesn't work.

My GoAccess version: 0.9.4

**Comment by waldbone** [comment]
> 
> 
> What version of goaccess are you running?
> 
> Just trying to understand what you are saying, basically if you select the option from the ncurses dialog then it works but if you specify it as a command line option it doesn't?

@allinurl: yes, that's right.

If i select this two options "**NCSA Combinet Log Format**" or "**Common Log Format (CLF)**" in the dialog it works, but if i write the log-format
`log-format=COMBINED` or
`log-format=COMMON` direkt in the command line (see Point 3. ) it doesn't work.

My GoAccess version: 0.9.4

**Comment by allinurl** [comment]
Can you please attach a text file with a few sample lines from your access log? Thanks.

**Comment by waldbone** [comment]
> 
> 
> Can you please attach a text file with a few sample lines from your access log? Thanks.

`Dec 28 11:24:08 myserver sshd[7427]: Invalid user wifi from 148.204.48.2 port 44934
Dec 28 11:24:08 myserver sshd[7427]: input_userauth_request: invalid user wifi [preauth]
Dec 28 11:24:08 myserver sshd[7427]: pam_unix(sshd:auth): check pass; user unknown
Dec 28 11:24:08 myserver sshd[7427]: pam_unix(sshd:auth): authentication failure; logname= uid=0 euid=0 tty=ssh ruser= rhost=148.204.48.2
Dec 28 11:24:10 myserver sshd[7427]: Failed password for invalid user wifi from 148.204.48.2 port 44934 ssh2
Dec 28 11:24:11 myserver sshd[7427]: Received disconnect from 148.204.48.2 port 44934:11: Bye Bye [preauth]
Dec 28 11:24:11 myserver sshd[7427]: Disconnected from 148.204.48.2 port 44934 [preauth]

Dec 28 11:27:10 myserver sshd[7431]: Invalid user ggitau from 159.65.135.64 port 47680
Dec 28 11:27:10 myserver sshd[7431]: input_userauth_request: invalid user ggitau [preauth]
Dec 28 11:27:10 myserver sshd[7431]: pam_unix(sshd:auth): check pass; user unknown
Dec 28 11:27:10 myserver sshd[7431]: pam_unix(sshd:auth): authentication failure; logname= uid=0 euid=0 tty=ssh ruser= rhost=159.65.135.64
Dec 28 11:27:12 myserver sshd[7431]: Failed password for invalid user ggitau from 159.65.135.64 port 47680 ssh2
Dec 28 11:27:12 myserver sshd[7431]: Received disconnect from 159.65.135.64 port 47680:11: Bye Bye [preauth]
Dec 28 11:27:12 myserver sshd[7431]: Disconnected from 159.65.135.64 port 47680 [preauth]
Dec 28 11:35:08 myserver sshd[7489]: Invalid user postgres from 177.124.89.14 port 49317
Dec 28 11:35:08 myserver sshd[7489]: input_userauth_request: invalid user postgres [preauth]
Dec 28 11:35:08 myserver sshd[7489]: pam_unix(sshd:auth): check pass; user unknown
Dec 28 11:35:08 myserver sshd[7489]: pam_unix(sshd:auth): authentication failure; logname= uid=0 euid=0 tty=ssh ruser= rhost=177.124.89.14
Dec 28 11:35:10 myserver sshd[7489]: Failed password for invalid user postgres from 177.124.89.14 port 49317 ssh2
Dec 28 11:35:10 myserver sshd[7489]: Received disconnect from 177.124.89.14 port 49317:11: Bye Bye [preauth]
Dec 28 11:35:10 myserver sshd[7489]: Disconnected from 177.124.89.14 port 49317 [preauth]
Dec 28 11:35:30 myserver sshd[7491]: Received disconnect from 223.111.139.211 port 55430:11:  [preauth]
Dec 28 11:35:30 myserver sshd[7491]: Disconnected from 223.111.139.211 port 55430 [preauth]`

**Comment by waldbone** [comment]
> 
> 
> Can you please attach a text file with a few sample lines from your access log? Thanks.

`111.111.111.111 - user1 [30/Dec/2018:11:59:04 +0100] "GET /nextcloud/ocs/v2.php/apps/notifications/api/v1/notifications?format=json HTTP/1.1" 200 974 "-" "Mozilla/5.0 (Windows) mirall/2.3.3 (build 1) (Nextcloud)"
111.111.111.111 - user1 [30/Dec/2018:11:59:12 +0100] "PROPFIND /nextcloud/remote.php/dav/files/user1/ HTTP/1.1" 207 1368 "-" "Mozilla/5.0 (Windows) mirall/2.3.3 (build 1) (Nextcloud)"
111.111.111.111 - user1 [30/Dec/2018:11:59:28 +0100] "PROPFIND /nextcloud/remote.php/dav/files/user1/ HTTP/1.1" 207 1368 "-" "Mozilla/5.0 (Windows) mirall/2.3.3 (build 1) (Nextcloud)"
111.111.111.111 - user1 [30/Dec/2018:11:59:42 +0100] "PROPFIND /nextcloud/remote.php/dav/files/user1/ HTTP/1.1" 207 1368 "-" "Mozilla/5.0 (Windows) mirall/2.3.3 (build 1) (Nextcloud)"
111.111.111.111 - user1 [30/Dec/2018:11:59:58 +0100] "PROPFIND /nextcloud/remote.php/dav/files/user1/ HTTP/1.1" 207 1368 "-" "Mozilla/5.0 (Windows) mirall/2.3.3 (build 1) (Nextcloud)"
111.111.111.111 - - [30/Dec/2018:12:00:05 +0100] "GET / HTTP/1.1" 302 479 "-" "Mozilla/5.0 (compatible; PRTG Network Monitor (www.paessler.com); Windows)"
111.111.111.111 - - [30/Dec/2018:12:00:07 +0100] "GET / HTTP/1.1" 200 5420 "-" "Mozilla/5.0 (compatible; PRTG Network Monitor (www.paessler.com); Windows)"
111.111.111.111 - user1 [30/Dec/2018:12:00:12 +0100] "PROPFIND /nextcloud/remote.php/dav/files/user1/ HTTP/1.1" 207 1368 "-" "Mozilla/5.0 (Windows) mirall/2.3.3 (build 1) (Nextcloud)"
111.111.111.111 - user1 [30/Dec/2018:12:00:28 +0100] "PROPFIND /nextcloud/remote.php/dav/files/user1/ HTTP/1.1" 207 1368 "-" "Mozilla/5.0 (Windows) mirall/2.3.3 (build 1) (Nextcloud)"
111.111.111.111 - user1 [30/Dec/2018:12:00:42 +0100] "PROPFIND /nextcloud/remote.php/dav/files/user1/ HTTP/1.1" 207 1368 "-" "Mozilla/5.0 (Windows) mirall/2.3.3 (build 1) (Nextcloud)"
111.111.111.111 - user1 [30/Dec/2018:12:00:58 +0100] "PROPFIND /nextcloud/remote.php/dav/files/user1/ HTTP/1.1" 207 1368 "-" "Mozilla/5.0 (Windows) mirall/2.3.3 (build 1) (Nextcloud)"
111.111.111.111 - user1 [30/Dec/2018:12:01:12 +0100] "PROPFIND /nextcloud/remote.php/dav/files/user1/ HTTP/1.1" 207 1368 "-" "Mozilla/5.0 (Windows) mirall/2.3.3 (build 1) (Nextcloud)"
111.111.111.111 - user1 [30/Dec/2018:12:01:28 +0100] "PROPFIND /nextcloud/remote.php/dav/files/user1/ HTTP/1.1" 207 1368 "-" "Mozilla/5.0 (Windows) mirall/2.3.3 (build 1) (Nextcloud)"
111.111.111.111 - user1 [30/Dec/2018:12:01:31 +0100] "GET /nextcloud/ocs/v2.php/apps/notifications/api/v1/notifications?format=json HTTP/1.1" 200 831 "-" "Mozilla/5.0 (Windows) mirall/2.3.3 (build 1) (Nextcloud)"
111.111.111.111 - user1 [30/Dec/2018:12:01:43 +0100] "PROPFIND /nextcloud/remote.php/dav/files/user1/ HTTP/1.1" 207 6114 "-" "Mozilla/5.0 (Windows) mirall/2.3.3 (build 1) (Nextcloud)"
111.111.111.111 - user1 [30/Dec/2018:12:01:58 +0100] "PROPFIND /nextcloud/remote.php/dav/files/user1/ HTTP/1.1" 207 6114 "-" "Mozilla/5.0 (Windows) mirall/2.3.3 (build 1) (Nextcloud)"
111.111.111.111 - user1 [30/Dec/2018:12:02:12 +0100] "PROPFIND /nextcloud/remote.php/dav/files/user1/ HTTP/1.1" 207 1368 "-" "Mozilla/5.0 (Windows) mirall/2.3.3 (build 1) (Nextcloud)"
111.111.111.111 - user1 [30/Dec/2018:12:02:28 +0100] "PROPFIND /nextcloud/remote.php/dav/files/user1/ HTTP/1.1" 207 1368 "-" "Mozilla/5.0 (Windows) mirall/2.3.3 (build 1) (Nextcloud)"
`

**Comment by waldbone** [comment]
> 
> 
> Please upgrade to the [**latest**](https://goaccess.io/download) version. It should work in there.

Now it works perfectly. Thanks!
