### ISSUE TITLE
Do I need to use new port for second a second instance of GoAccess?

### ISSUE THREAD

**Issue by errar51** [allinurl/goaccess#1336]
Hi, for my first real time log for domain1 I use this command and it work fine:

    goaccess /var/log/nginx/domain1/access.log -o /firstdata/domain1/html/goaccess/report.html --log-format=COMBINED --real-time-html --html-prefs='{"theme":"bright","perPage":20,"layout":"vertical","showTables":true,"visitors":{"plot":{"chartType":"bar"}}}' --daemonize

now if I need to track another real time report for a different site, do I just issue same command but add a different port --port=8035, is that right? if I don't, won't the websocket just point to the first log? 

    goaccess /var/log/nginx/domain2/access.log -o /firstdata/domain2/html/goaccess/report.html --log-format=COMBINED --real-time-html --html-prefs='{"theme":"bright","perPage":20,"layout":"vertical","showTables":true,"visitors":{"plot":{"chartType":"bar"}}}' --port=8035 --daemonize

Please tell me if I'm wrong.

**Comment by errar51** [comment]
Well I just try to issue the second command after the first and the real time just stop updating completely :(.

**Comment by allinurl** [comment]
Please take a look at [**this post**](https://github.com/allinurl/goaccess/issues/625#issuecomment-272905761), it should address your question.

**Comment by errar51** [comment]
> Please take a look at [**this post**](https://github.com/allinurl/goaccess/issues/625#issuecomment-272905761), it should address your question.

This works. Thank you.

**Comment by allinurl** [comment]
Great. Closing this.
