### ISSUE TITLE
How to use Chinese with GoAccess?

### ISSUE THREAD

**Issue by damaainan** [allinurl/goaccess#1337]
Hello，everyone， i want make out to use chinese, but i don't want to change LANG. Have any method to realize this?

**Comment by damaainan** [comment]
Like this
```
export LANG="zh_CN.UTF-8"      
goaccess -a -d -f access.log -p goaccess.conf -o report_all.html  
export LANG="en_US.UTF-8"     
````

**Comment by allinurl** [comment]
You have to set `LANG` as it relies on `gettext` to perform the translations.

**Comment by allinurl** [comment]
You could try something like:

    LANG="zh_CN.UTF-8" bash -c 'goaccess access.log --log-format=COMBINED'

**Comment by knight0zh** [comment]
> You could try something like:
> 
> ```
> LANG="zh_CN.UTF-8" bash -c 'goaccess access.log --log-format=COMBINED'
> ```

@allinurl 


root@123.123.123.123-bmpt report # LANG="zh_CN.UTF-8" bash -c 'goaccess  /data/logs/nginx/www.gtarcade.com.access.log -o /data/html/report/www.html --log-format='%h %^[%d:%t %^] %v "%r" "%s" %b "%R" "%u" %^'  --real-time-html --time-format=%T --date-format='%d/%b/%Y' '
Parsing... [0] [0/s]
GoAccess - version 1.3 - Dec 25 2018 09:57:00
Config file: No config file used

Fatal error has occurred
Error occurred at: src/parser.c - parse_log - 2764
未在配置文件中设置时间格式

**Comment by allinurl** [comment]
Please ensure you properly escape the quotes. e.g.,

    # LANG="zh_CN.UTF-8" bash -c 'goaccess  /data/logs/nginx/www.gtarcade.com.access.log -o /data/html/report/www.html --log-format=\'%h %^[%d:%t %^] %v "%r" "%s" %b "%R" "%u" %^\'  --real-time-html --time-format=%T --date-format=%d/%b/%Y'

**Comment by JianYu97** [comment]
> LANG="zh_CN.UTF-8" bash -c

very good , I succeeded in using Chinese

**Comment by allinurl** [comment]
Awesome. Closing this. Feel free to reopen it if needed.

**Comment by allinurl** [comment]
Is Chinese locals installed on the machine? e.g., ‘locale -a’

**Comment by oodenough** [comment]
If not, you may install with `sudo apt install language-pack-zh-hans` on Debian/Ubuntu. And then execute `LANG="zh_CN.UTF-8" bash -c 'goaccess ...'`.
