### ISSUE TITLE
Try to parse Nginx logs in JSON format

### ISSUE THREAD

**Issue by Pinaute** [allinurl/goaccess#1339]
Hi,
I am trying to analyze the logs of Nginx send on stdout in a container, the logs are in json format.

Below my Nginx log format:
`log_format vhost  '$host $remote_addr - $remote_user [$time_local] ''"$request" $status $body_bytes_sent ''"$http_referer" "$http_user_agent"';`

And here is a line of logs from the Nginx container:
`{"log":"\u001b[0;33;1mnginx.1    | \u001b[0mdrive.mysite.com 123.123.123.123 - - [26/Dec/2018:12:29:09 +0000] \"GET /storage/1.5/1/storage/clients?full=1\u0026limit=1000 HTTP/2.0\" 200 844 \"-\" \"Firefox/64.0 (Linux x86_64) FxSync/1.66.0.20181212012434.desktop\"\n","stream":"stdout","time":"2018-12-26T12:29:09.74181707Z"}`

So I want to interpret with Goaccess this whole log file, where each line is a json.
So I tried this:
```
./nginx2goaccess.sh '$host $remote_addr - $remote_user [$time_local] ''"$request" $status $body_bytes_sent ''"$http_referer" "$http_user_agent"';
- Generated goaccess config:
time-format %T
date-format %d/%b/%Y
log_format %v %h - %^ [%d:%t %^] "%r" %s %b "%R" "%u"
```
Could you help me create this log for Goaccess
Thanks.

**Comment by allinurl** [comment]
Are `\u001b[0;33`, `\u001b[0m` typos or actual escape sequences?

**Comment by allinurl** [comment]
Also, please post several lines from your access log. Thanks!

**Comment by Pinaute** [comment]
it works, thank you !

**Comment by allinurl** [comment]
Great! Closing this.
