### ISSUE TITLE
Fetch logs using FTP

### ISSUE THREAD

**Issue by Yokutto** [allinurl/goaccess#1342]
Is there any way to download logs from another server using FTP and make the goaccess read them in real time? If it does not exist, it would be a good option because the goaccess takes a lot of CPU on servers with high traffic.

**Comment by allinurl** [comment]
You can certainly use something like sftp or even better, sshfs and read the mounted log with goaccess.

**Comment by Yokutto** [comment]
You can give me an example of configuration that i can use?

Another question, I tried to use GoAcess to read a log created by a CDN that I use, but it always gives an error with the filter, I think and because the UserAgent is in the middle of the log, then goaccess can not differentiate a filter from other. In the examples inside the configuration, I have seen that the useragent is always inside quotation marks or something. Is there any way to make the goaccess read this type of log?

A line of the log
> 2019-01-03	19:16:34	GET	187.x.x.x	http	-	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36	155	672	509	151.139.61.116	0.012	200	-	/path/example.png	-	-

Filter that i use: 

> %d %t %m %h %H %R %u %^ %b %^ %^ %T %s %q %U %^ %^

Thanks for your help

**Comment by allinurl** [comment]
You can try this:

```
# apt-get install sshfs
# mkdir server
# sshfs root@remote-server.com:/data/www/nginx/logs/ ./server/
```

For your log, unofnurtly you won't be able since you are not delimiting some of the fields, for instance, the user agent has spaces in between but is not enclosed within quotes.

**Comment by Yokutto** [comment]
I will try to resolve it with my CDN. Thanks for you help, have a good 2019.

**Comment by allinurl** [comment]
Thank you, you as well!
