### ISSUE TITLE
Apache2 error log format

### ISSUE THREAD

**Issue by fakename10** [allinurl/goaccess#1343]
I have Apache on an Ubuntu setup with errorlog file that looks like this

> [Wed Jan 02 06:25:31.604168 2019] [mpm_prefork:notice] [pid 20659] AH00163: Apache/2.4.29 (Ubuntu) configured -- resuming normal operations
> [Wed Jan 02 06:25:31.604188 2019] [core:notice] [pid 20659] AH00094: Command line: '/usr/sbin/apache2'

I am trying to read it with goaccess using this command, but need help with date and time format
goaccess /var/log/apache2/error..log --log-format='[%^ %d %t.%^ %^] [%^] [%^] [%^ %h:%^] %^: %U, %^: %R'

Thanks,
Nick

**Comment by allinurl** [comment]
At this time, unfortunately you cannot analyze error logs.

**Comment by allinurl** [comment]
Closing this, feel free to reopen it if needed.

**Comment by Josh-of-TT** [comment]
Will this feature ever be available?

**Comment by allinurl** [comment]
@Josh-of-TT There are no immediate plans but I also don't want to completely close it and say it won't ever be available :)
