### ISSUE TITLE
--keep-db-files not available

### ISSUE THREAD

**Issue by JianYu97** [allinurl/goaccess#1344]
When I want to use --keep-db-files command, it prompts me that it does not exist. When I recompile configure: error:*** Missing development libraries for Tokyo Cabinet Database./configure --enable-utf8 --enable-geoip=legacy --enable-tcb=btree.But when I do./configure --enable-utf8 --enable-geoip=legacy --enable-tcb, it works. Will the btree open

**Comment by JianYu97** [comment]
Storage method: in-memory Hash Database (Default) is displayed as follows after successful compilation

**Comment by allinurl** [comment]
That's right. If `btree` or `memhash` is not specified, it defaults to the main hash tables.

**Comment by JianYu97** [comment]
> 那就对了。如果指定`btree`或未`memhash`指定，则默认为主哈希表。

**Comment by JianYu97** [comment]
> That's right. If `btree` or `memhash` is not specified, it defaults to the main hash tables.

I want to use --keep-db-files this parameter how should I compile --keep-db-files is based on btree

**Comment by allinurl** [comment]
This should enable `--keep-db-files` and `--load-from-disk`:

    $ ./configure --enable-utf8 --enable-geoip=legacy --enable-tcb=btree
    $ make
    # make install

or to uninstall

    # make uninstall

**Comment by JianYu97** [comment]
> This should enable `--keep-db-files` and `--load-from-disk`:
> 
> ```
> $ ./configure --enable-utf8 --enable-geoip=legacy --enable-tcb=btree
> $ make
> # make install
> ```
> or to uninstall
> 
> ```
> # make uninstall
> ```
Configure: error: *** Missing development libraries for Tokyo Cabinet Database

**Comment by JianYu97** [comment]
> Please try:
> 
> ```
> # apt-get install libtokyocabinet-dev
> ```

I'm sorry to reply you so late. I can't find it using yum search using centos7 system

**Comment by JianYu97** [comment]
I think I've found a solution. Thank you very much 
yum install tokyocabinet-devel ncurses-devel geoip-devel bzip2-devel
./configure --enable-utf8 --enable-geoip=legacy --enable-tcb=btree
