### ISSUE TITLE
HAPROXY + GOACCESS

### ISSUE THREAD

**Issue by valcenirh** [allinurl/goaccess#1352]
HI,

I am using version 1.9 of haproxy, trying to link to goaccess is presenting the error below ....

Command:

    goaccess -f /var/log/haproxy.log --log-format = '% ^]% ^% h:% ^ [% d:% t.% ^]% ^ /% ^ /% ^ /% ^ % Y /% Y '--time-format ='% H:% M:% S '

Error:
Parsed 1 linesproducing the following errors:

Token '"POST /teste/teste.svc HTTP / 1.1" 200 1168 "% Referrer" "% User-Agent" n 192.168.0.40' does not match specifier '% h'

Can you please help me?

**Comment by jazzl0ver** [comment]
Here is my config for haproxy:
```
time-format %H:%M:%S
date-format %d/%b/%Y
log_format %^ %^ %^ %^ [%d:%t.%^] %^ %^ %^/%^/%^/%^/%L %^ %^ %^ "%r" %s {%^|%^|%^|%u} %^ %^=%b %^ %h:%^ %^ %^ %^
```
HTH

**Comment by allinurl** [comment]
@valcenirh can you please post a few lines from your access log?

**Comment by roma-glushko** [comment]
Hi @allinurl , I'm also using Haproxy + Httpd and got only a couple of IPs detected. My access log looks like this

`127.0.0.1 - - [16/Feb/2019:00:00:00 -0500] "GET /path?auto HTTP/1.1" 302 - "-" "Go-http-client/1.1"`

`127.0.0.1 67.67.67.67, 163.241.184.49 - [16/Feb/2019:00:00:00 -0500] "GET /customer/xx/yy?xx=www HTTP/1.1" 200 785 "https://www.website.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.96 Safari/537.36"`

`127.0.0.1 2601:191:4103:4271:9aad:c677:1429:c53f, 34.195.252.89, 192.240.174.39 - [16/Feb/2019:00:00:01 -0500] "GET /pub/someimage.png HTTP/1.1" 200 13036 "-" "Amazon CloudFront"`

`127.0.0.1 127.35.49.250, 163.241.184.49 - [16/Feb/2019:00:00:00 -0500] "GET /page.html HTTP/1.1" 200 97978 "-" "Mozilla/5.0 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)"`

`163.241.184.49 47.47.47.47 - [16/Feb/2019:00:00:00 -0500] "POST /checkout HTTP/1.1" 200 16 "https://www.site.com/page-x.html" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3624.96 Safari/507.36"`

What'd you recommend me to put to `log_format`?

Thank you!

**Comment by allinurl** [comment]
@roma-glushko there are some inconcensticnes in your log. For instance, some of the posted lines have commas in between IPs, others don't. Which one is the actual client IP that you want to track?

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
