### ISSUE TITLE
Homebrew with-geoip formulae not up to date

### ISSUE THREAD

**Issue by Glujaz** [allinurl/goaccess#1358]
Hello,

Sorry for bothering, but installing goaccess with geo location via Homebrew is not possible anymore since High Sierra.

Is it possible to update it ?

If not, do you have a precise guide to do so ? In another issue report about this, the links are not valid anymore. Moreover, I've never done this before...

Thanks :)

**Comment by allinurl** [comment]
Sorry for the delay on this. Please feel free to create an issue on the [**hombrew repo**](https://github.com/Homebrew/homebrew-core/blob/master/Formula/goaccess.rb).
