### ISSUE TITLE
Pressing CTRL+C at the startup config window doesn't cause an exit

### ISSUE THREAD

**Issue by tstack** [allinurl/goaccess#1363]
version: goaccess v1.2 (the latest version in OS X brew)
command-line: goaccess /path/to/log

While "Log Format Configuration" is displayed, pressing CTRL+C causes "SIGINT caught!" to be displayed and then "Closing GoAccess...", but nothing actually happens and you're stuck in the screen.  Pressing CTRL+C again just gives the same message.  Pressing 'q' does work (although, I didn't notice that text and did a kill -9 in a separate window).

**Comment by SampsonCrowley** [comment]
Thank you for opening this issue, just ran into this as well

**Comment by allinurl** [comment]
Thanks for reporting this. I'll look into it and post back.
