### ISSUE TITLE
libssl Depends problem in Debian packge

### ISSUE THREAD

**Issue by szepeviktor** [allinurl/goaccess#1365]
> goaccess: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory

Depends says: `libssl1.0.0 | libssl1.0.1 | libssl1.0.2` but the binary is linked to version 1.0.0

```
$ ldd /usr/bin/goaccess|grep ssl
/usr/bin/goaccess: /usr/lib/x86_64-linux-gnu/libssl.so.1.0.0: version `OPENSSL_1.0.0' not found (required by /usr/bin/goaccess)
        libssl.so.1.0.0 => /usr/lib/x86_64-linux-gnu/libssl.so.1.0.0 (0x00007f4551260000)
```

libssl1.0.2 package in Debian stable has only `libssl.so.1.0.2`

Please advise.

**Comment by szepeviktor** [comment]
I'm sorry, I've installed the jessie package in stretch.

**Comment by szepeviktor** [comment]
Packages from deb.goaccess.io for Debian buster are compiled with libssl1.0.2 which is not part of buster.
Please rebuild that packages with libssl1.1

Thank you.

**Comment by allinurl** [comment]
@szepeviktor I'm doing some major updates to the repo server right now, so I'll work on this as well. Thanks for pointing that out.

**Comment by seguri** [comment]
Hi, any update?

```
$ echo "deb https://deb.goaccess.io/ $(lsb_release -cs) main" | sudo tee -a /etc/apt/sources.list.d/goaccess.list
$ wget -O - https://deb.goaccess.io/gnugpg.key | sudo apt-key add -
$ sudo apt-get update
$ sudo apt-get install goaccess
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 goaccess : Depends: libssl1.0.2 (>= 1.0.2) but it is not installable
E: Unable to correct problems, you have held broken packages.
```

**Comment by allinurl** [comment]
@seguri Thanks for reporting this. v1.4 will be out pretty soon, it should be fixed then. Feel free to build from [**development**](https://github.com/allinurl/goaccess#build-from-github-development).

**Comment by allinurl** [comment]
[**v1.4**](https://goaccess.io/download) is out! Available as well in the deb repo for the following distributions: 

```
goaccess |  1:1.4-xenial |  xenial | amd64, i386
goaccess |  1:1.4-bionic |  bionic | amd64
goaccess |    1:1.4-eoan |    eoan | amd64
goaccess |   1:1.4-focal |   focal | amd64
goaccess | 1:1.4-stretch | stretch | amd64, i386
goaccess |  1:1.4-buster |  buster | amd64, i386
```
If you get a `GPG error The following signatures couldn't be verified because the public key is not available.` Please make sure to download the new public key as shown [**here**](https://goaccess.io/download#official-repo) above to correct this.
