### ISSUE TITLE
How do you extend the number of entries that show within a panel for HTML output?

### ISSUE THREAD

**Issue by atc0005** [allinurl/goaccess#1367]
I've tried the following to limit the generated HTML panels list to just the "HOSTS" panel with the hope that it would expand to include more entries, but no such luck:

```shell
grep '29/Jan' other_vhosts_access.log | \
	goaccess \
		--log-format VCOMMON \
		--agent-list \
		--all-static-files \
		--enable-panel="HOSTS" \
		--ignore-panel="REQUESTS" \
		--ignore-panel="REQUESTS_STATIC" \
		--ignore-panel="NOT_FOUND" \
		--ignore-panel="VISITORS" \
		--ignore-panel="OS" \
		--ignore-panel="BROWSERS" \
		--ignore-panel="VISIT_TIMES" \
		--ignore-panel="VIRTUAL_HOSTS" \
		--ignore-panel="REFERRERS" \
		--ignore-panel="REFERRING_SITES" \
		--ignore-panel="KEYPHRASES" \
		--ignore-panel="STATUS_CODES" \
		--ignore-panel="REMOTE_USER" \
		--ignore-panel="GEO_LOCATION" \
		--with-output-resolver \
		-o SYSTEM_NAME_HERE-2019-01-29.html
```

I assume I'm doing something wrong, but the entries in the panel appear to be limited to 7 items.

What I'm really trying to accomplish is either a longer listing of top visitors *or* a grouping of visitors by domain instead of via individual IPs or (in my case) by unique FQDN.

Thanks for your help.

**Comment by allinurl** [comment]
You can set the number of items through the preferences (HTML report) or through your config file, e.g., 

    html-prefs {"autoHideTables":true,"layout":"horizontal","perPage":15,"theme":"darkPurple"}

Please note you may need to reload the report (Ctrl+Shift+r)

**Comment by atc0005** [comment]
omg, I am so blind. Thank you for patiently/kindly pointing that out. :)

**Comment by allinurl** [comment]
Glad to hear you were able to spot it :)
