### ISSUE TITLE
laravel log format doesn't match specifier

### ISSUE THREAD

**Issue by MasoudKaviani** [allinurl/goaccess#1371]
I have a laravel file and i want to run goaccess on it:
Here is my sample log format:

`[2019-02-04 08:27:54] debuge.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Class 'Illuminate\Mail\MailServiceProvider' not found in /home/api/domains/dayacom.ir/public_html/vendor/laravel/lumen-framework/src/Application.php:176
Stack trace:
#0 /home/api/domains/dayacom.ir/public_html/bootstrap/app.php(132): Laravel\Lumen\Application->register('Illuminate\\Mail...')
#1 /home/api/domains/dayacom.ir/public_html/public/index.php(14): require('/home/api/domai...')
#2 {main} {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Class 'Illuminate\\Mail\\MailServiceProvider' not found at /home/api/domains/dayacom.ir/public_html/vendor/laravel/lumen-framework/src/Application.php:176)
[stacktrace]
#0 /home/api/domains/dayacom.ir/public_html/bootstrap/app.php(132): Laravel\\Lumen\\Application->register('Illuminate\\\\Mail...')
#1 /home/api/domains/dayacom.ir/public_html/public/index.php(14): require('/home/api/domai...')
#2 {main}
"} `

but with goaccess it through an error:
`'[2019-02-04' doesn't match specifier '%h'`

i run this goaccess command:
` goaccess lumen.log -o /home/api/public_html/public/monitor.html --log-format=COMBINED --real-time-html`

**Comment by allinurl** [comment]
Unfortunately your log format doesn't appear to be from an access log so goaccess won't be of much help. You will need to try a different tool though.
