### ISSUE TITLE
goaccess 1.3 html no display

### ISSUE THREAD

**Issue by leepoi** [allinurl/goaccess#1377]
Thank you for your excellent software.

But.....  I have a strange HTML display problem , I spent two nights trying to solve this problem, but I had no idea.

I have two Centos 6.9 servers with the same problem .  And I used the same log to experiment

I compiled version 1.3, which works normally under the shell window, but the exported HTML does not display the content, only turns around  and  chrome/IE 11  labels are both scrambled

Then I compiled version 1.2. Both shell and HTML work perfectly.

The compilation steps follow exactly https://goaccess.io/download

I'm a Chinese user. I guess this problem may be related to i18n.

So I want to change the language of HTML.

**Whether**

export LANG="en_US.UTF-8"   
/usr/local/bin/goaccess access.log -a -o report2.html -p /usr/local/etc/goaccess/goaccess.conf

**or**

export LANG="zh_CN.UTF-8"
/usr/local/bin/goaccess access.log -a -o report2.html -p /usr/local/etc/goaccess/goaccess.conf

The generated HTML still contains Chinese, and the Chrome browser cannot parse it.

Here is the generated HTML file. 1.2 is normal and 1.3 is not displayed.

goaccess 1.2   https://ufile.io/ubwp4

goaccess 1.3   https://ufile.io/txfiw
.
I'm sorry to disturb you because of my question.

**Comment by allinurl** [comment]
Thanks for reporting this. Like you said, it's seems related to the locale. Can you please try to set your locale and then build again? e.g.,

```
# export LANG="en_US.UTF-8"
# cd goaccess-1.3/
# ./configure --enable-utf8 --enable-geoip=legacy
# make uninstall
# make
# make install
```

**Comment by allinurl** [comment]
By the way, is the terminal output also broken for your locale? Thanks

**Comment by leepoi** [comment]
1#   I remember trying it before, but it doesn't work. To confirm it again, I just reinstalled it according to your instructions. It's still not normal.

2#   It works perfect in terminal output

**Comment by leepoi** [comment]
haha  I solved it.

The reason is that someone set some strange I18N config  when installing the operating system

when i type  command  "locale"  in terminal
the wrong config is below :

LANG=en_US.UTF-8
LC_CTYPE="zh_CN"
LC_NUMERIC="zh_CN"
LC_TIME="zh_CN"
LC_COLLATE="zh_CN"
LC_MONETARY="zh_CN"
LC_MESSAGES="zh_CN"
LC_PAPER="zh_CN"
LC_NAME="zh_CN"
LC_ADDRESS="zh_CN"
LC_TELEPHONE="zh_CN"
LC_MEASUREMENT="zh_CN"
LC_IDENTIFICATION="zh_CN"
LC_ALL="zh_CN"

I searched for "locale" on the Internet.

I found that Although I set variable LANG , But variable  LC_ALL has the highest priority.

So no matter how I set it up, it's not normal in the end.

Finally, I used the following command

export LC_ALL="en_US.UTF-8"

Then uninstall the software and recompile it. 

Everything is perfect !!!

Thank you !

**Comment by allinurl** [comment]
Glad you got it to work. However, is the Chinese output still broken? If it is, would you be able to send me a few lines from your log that are in fact causing the report to break? Thanks

**Comment by leepoi** [comment]
:-)   Now the Chinese display is perfect, there is no need to modify anything else.
