### ISSUE TITLE
squid logfile: doesn't match specifier '%x'

### ISSUE THREAD

**Issue by ThomasCr** [allinurl/goaccess#1383]
I have also a problem with squid log format:
```
Token '/98' doesn't match specifier '%x'
Token '/clientservices' doesn't match specifier '%x'
Token '/sluk' doesn't match specifier '%x'
Token '/tile-service' doesn't match specifier '%x'
```
I think this are the problematic lines:
```
1550353239.789      0 rd1.domain.lan TCP_DENIED/403 4335 GET http://98.157.215.153/ - HIER_NONE/- text/html
1550374020.692     83 desktop-o1g07qt.domain.lan TCP_REFRESH_UNMODIFIED/200 866 GET http://clientservices.googleapis.com/chrome-variations/seed? - ORIGINAL_DST/172.217.22.99 application/octet-stream
1550295096.846     25 sec30cda763504f.domain.lan TCP_DENIED/403 4367 GET http://sluk.samsungcloudprint.com/scp/v2/svclookup/service? - HIER_NONE/- text/html
1550295228.193     76 desktop-o1g07qt.domain.lan TCP_REFRESH_MODIFIED/200 4645 GET http://tile-service.weather.microsoft.com/de-DE/livetile/preinstall? - ORIGINAL_DST/23.32.125.203 text/xml
```
my logformat in squid is:
`logformat squid      %ts.%03tu %6tr %>A %Ss/%03>Hs %<st %rm %ru %[un %Sh/%<a %mt`

this is the default:
`logformat squid      %ts.%03tu %6tr %>a %Ss/%03>Hs %<st %rm %ru %[un %Sh/%<a %mt`

So I only changed a to A
> >a	Client source IP address
> >A	Client FQDN

Source: http://www.squid-cache.org/Doc/config/logformat/

I use GoAccess - 1.3 from your Ubuntu repository

**Comment by allinurl** [comment]
Could you please post the goaccess log-format that you are currently using? Thanks.

**Comment by ThomasCr** [comment]
I used the predefined squid log format

**Comment by 0bi-w6n-K3nobi** [comment]
Try this, in `goaccess.conf`:

`date-format %s`
`time-format %s`
`log-format %x.%^ %~%L %^ %^/%s %b %m %U %^ %^/%h %^`

or in command-line:
`--date-format='...' --time-format='...' --log-format='...'`

**notes:**
GoAccess have a Bug so `Time Distribution panel` always blank . See at #1810.
Lines without client ip `<a` cannot processed.

**Comment by allinurl** [comment]
Note that you don't have a valid IPv4/6, however, you still could use `--no-ip-validation`

    goaccess squid.log --log-format='%x.%^ %~%L %h %^/%s %b %m %U %^ %^ %M' --date-format=%s --time-format=%s --http-protocol=no --ignore-panel=BROWSERS --ignore-panel=OS --ignore-panel=REFERRING_SITES --no-ip-validation

Closing this. Feel free to reopen it if needed.
