### ISSUE TITLE
didn't enable real-time-html, but comes out: websocket ready to accept new client

### ISSUE THREAD

**Issue by saclin** [allinurl/goaccess#1384]
here is my command:
goaccess api.crm.51zan.production.access.log -a -o test.html
then comes out:
WebSocket server ready to accept new client connections

in the access.conf, I didn't enable real-time too!!!
![image](https://user-images.githubusercontent.com/30526808/53229583-9ea86400-36bf-11e9-8a03-bae913f028e8.png)

**Comment by allinurl** [comment]
Can you please post the output of `goaccess --dcf` and please attach the goaccess.conf here. Thanks.

**Comment by ZenImagine** [comment]
Hi, I have exactly the same problem and your documentation does not seem to be up to date. Here's how I installed GoAccess :

# echo "deb http://deb.goaccess.io/ $(lsb_release -cs) main" | sudo tee -a /etc/apt/sources.list.d/goaccess.list
# wget -O - https://deb.goaccess.io/gnugpg.key | sudo apt-key add -
# sudo apt update
# sudo apt install goaccess
**Configurer GoAccess en décommettant les lignes**
# sudo nano /etc/goaccess.conf
```
time-format %H:%M:%S
date-format %d/%b/%Y
log-format %h %^[%d:%t %^] "%r" %s %b "%R" "%u"
```
**Créer le dossier du site**
# sudo mkdir -p /var/www/analytics-domaine-com/web
**Créer le rapport**
# sudo goaccess /var/log/nginx/access.log -o /var/www/analytics-domaine-com/web/report.html --real-time-html
**Changer le propriétaire et le groupe**
# sudo chown -R www-data:www-data /var/www/analytics-domaine-com
**Créer un virtualhost**
# sudo nano /etc/nginx/sites-available/analytics-s1biose-com
```
server {
    listen 80 http2;
    listen [::]:80 ipv6only=on http2;
    server_name analytics.s1biose.com;
    root /var/www/analytics-s1biose-com/web;
    report.html;
}
```
**Activer les services**
# sudo ln -s /etc/nginx/sites-available/analytics-domaine-com /etc/nginx/sites-enabled/
**Testet la syntaxe**
# sudo nginx -t
**Redémarrer apache**
# sudo systemctl restart nginx

When I run the command :
`WebSocket server ready to accept new client connections`
I have this message, the report is well created but the real time update does not work.
In /etc/goaccess.conf I only uncomment the 3 lines above.

**Comment by allinurl** [comment]
@ZenImagine can you please verify that if there's a config file under: `/etc/goaccess/goacces.conf`? Thanks

**Comment by ZenImagine** [comment]
@allinurl No, there is no configuration file at this location

**Comment by ZenImagine** [comment]
@allinurl There is also a problem with the https.

I activated https with let's encrypt, the page starts to load (a circle runs in the middle of the screen) and the navigator displays:

> Unsecured content blocked.
> This attempts to load scripts from unauthenticated sources.
> "Load script at risk" OK

![capture d ecran de 2019-03-04 18-51-50](https://user-images.githubusercontent.com/29839861/53752565-34f23c00-3eaf-11e9-8633-91acf2e08f86.png)

**Comment by allinurl** [comment]
@ZenImagine Are you in v1.2? or v1.3? Your browser (console) should be able to tell you what content is insecure, then please post it here...

**Comment by ZenImagine** [comment]
@allinurl I am on version 1.3 because your deposit does not work on Ubuntu 18.04

```
ubuntu@www-s1biose-com ~ $ sudo apt update
Hit:1 http://ppa.launchpad.net/certbot/certbot/ubuntu bionic InRelease
Hit:2 http://ppa.launchpad.net/ondrej/php/ubuntu bionic InRelease                                                                          
Hit:3 http://ppa.launchpad.net/webupd8team/java/ubuntu bionic InRelease                                                                    
Hit:4 http://nova.clouds.archive.ubuntu.com/ubuntu bionic InRelease                                                                        
Get:5 http://nova.clouds.archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]                                                      
Hit:6 http://security.ubuntu.com/ubuntu bionic-security InRelease                                                                          
Hit:7 https://deb.nodesource.com/node_8.x bionic InRelease                                                              
Hit:8 http://repo.mysql.com/apt/ubuntu bionic InRelease                                           
Get:9 http://nova.clouds.archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]
Ign:10 http://deb.goaccess.io $ InRelease                                                    
Err:11 http://deb.goaccess.io $ Release            
  404  Not Found [IP: 107.170.196.4 80]
Get:12 http://nova.clouds.archive.ubuntu.com/ubuntu bionic-updates/universe Sources [133 kB]
Get:13 http://nova.clouds.archive.ubuntu.com/ubuntu bionic-updates/main Sources [250 kB]
Get:14 http://nova.clouds.archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages [538 kB]
Get:15 http://nova.clouds.archive.ubuntu.com/ubuntu bionic-updates/main Translation-en [200 kB]
Get:16 http://nova.clouds.archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages [737 kB]
Reading package lists... Done      
E: The repository 'http://deb.goaccess.io $ Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

In screenshot the message of the console.

![capture d ecran du 2019-03-05 18-16-24](https://user-images.githubusercontent.com/29839861/53823928-0b024d80-3f73-11e9-821c-e01b5c58aed2.png)

**Comment by allinurl** [comment]
Are you running this through `wss`?

**Comment by ZenImagine** [comment]
@allinurl I do not understand, what should I do

**Comment by allinurl** [comment]
You need to set the URI scheme using `--ws-url=<[scheme://]url[:port]>` for encrypted connections.  e.g.,

    --ws-url=wss://analytics.s1biose.com

**Comment by ZenImagine** [comment]
@allinurl Here is my current configuration for nginx, but I do not know if it is correct (I start with nginx). I have a question waiting for an answer :

https://serverfault.com/questions/956888/how-to-configure-multiple-servers-on-the-same-ip-address-with-nginx

# sudo nano /etc/nginx/sites-available/analytics-domaine-com
```
server {
    listen 443 ssl http2;
    server_name analytics.domaine.com;
    root /var/www/analytics-domaine-com/web;
    #report.html;

    auth_basic "Protected";
    auth_basic_user_file /var/www/analytics-domaine-com/web/.htpasswd;

    ssl_certificate /etc/letsencrypt/live/analytics.domaine.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/analytics.domaine.com/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
}

server {
    listen 80;
    server_name analytics.domaine.com;
    return 301 https://$server_name$request_uri;
}
```

**Comment by allinurl** [comment]
How are you running goaccess? can you please attach the conf file here as well? Thanks.

**Comment by ZenImagine** [comment]
@allinurl /etc/goaccess.conf

[goaccess.txt](https://github.com/allinurl/goaccess/files/2932706/goaccess.txt)

**Comment by ZenImagine** [comment]
@allinurl Here is the message that is displayed in the chrome console :

> Mixed Content: The page at 'https://analytics.s1biose.com/' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://analytics.example.com:7890/'. This request has been blocked; this endpoint must be available over WSS.

**Comment by ZenImagine** [comment]
@allinurl I followed your tutorial :

```
$ echo "deb http://deb.goaccess.io/ $(lsb_release -cs) main" | sudo tee -a /etc/apt/sources.list.d/goaccess.list
$ wget -O - https://deb.goaccess.io/gnugpg.key | sudo apt-key add -
$ sudo apt-get update
$ sudo apt-get install goaccess
```

When I do :

`$ sudo apt-get update`

I have the following error :

```
Hit:1 http://ppa.launchpad.net/certbot/certbot/ubuntu bionic InRelease
Hit:2 http://nova.clouds.archive.ubuntu.com/ubuntu bionic InRelease                                                                        
Hit:3 http://ppa.launchpad.net/ondrej/php/ubuntu bionic InRelease                                                                          
Get:4 http://nova.clouds.archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]                                                      
Hit:5 http://ppa.launchpad.net/webupd8team/java/ubuntu bionic InRelease                                                                    
Get:6 http://nova.clouds.archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]                                                    
Get:7 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]                                                                
Hit:8 http://repo.mysql.com/apt/ubuntu bionic InRelease                                                                                    
Hit:9 https://deb.nodesource.com/node_8.x bionic InRelease                                                                                 
Ign:10 http://deb.goaccess.io $ InRelease                                                                            
Err:11 http://deb.goaccess.io $ Release
  404  Not Found [IP: 107.170.196.4 80]
Reading package lists... Done
E: The repository 'http://deb.goaccess.io $ Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```
I am currently on Ubuntu 18.04 and GoAccess is in version 1.2 which explains the page of error (I am in HTTPS).

Here is the content of /etc/apt/sources.list.d/goaccess.list

`deb http://deb.goaccess.io/ $ (lsb_release -cs) main
`
How can I install version 1.3 ?

**Comment by allinurl** [comment]
Yep, you need to use `wss`. Take a look at the example I posted before. To install goaccess, please build from source.

**Comment by ZenImagine** [comment]
@allinurl  I will try the sources. Is it normal that the repository does not work and that version 1.3 is not available for ubuntu ?

**Comment by ZenImagine** [comment]
@allinurl Are your instructions correct ?

```
$ echo "deb http://deb.goaccess.io/ $(lsb_release -cs) main" | sudo tee -a /etc/apt/sources.list.d/goaccess.list
$ wget -O - https://deb.goaccess.io/gnugpg.key | sudo apt-key add -
$ sudo apt-get update
$ sudo apt-get install goaccess
```

If I replace HTTP with HTTPS in sources it works :

```
$ echo "deb https://deb.goaccess.io/ $(lsb_release -cs) main" | sudo tee -a /etc/apt/sources.list.d/goaccess.list
$ wget -O - https://deb.goaccess.io/gnugpg.key | sudo apt-key add -
$ sudo apt-get update
$ sudo apt-get install goaccess
```

**Comment by allinurl** [comment]
It should certainly work for Ubuntu 18.04, I need to look what's going on... If you need the binary, let me know and I can post a direct link.

Can you please post a few lines from your access log? You don't have the right log format given that error. Also, please take a look at the documentation on how to enable more panels.

**Comment by ZenImagine** [comment]
@allinurl Here is my log of access :

```
185.228.228.247 - - [02/Mar/2019:06:25:41 +0000] "GET /fr/private_message/ajax_callback/get_new_unread_thread_count?token=GO0HLTZudaDjqwgY5Kj-aRBX58WbnRRpOMGyXdz4yug HTTP/2.0" 200 76 "https://www.s1biose.com/fr/legal/document/politique_de_confidentialite" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:65.0) Gecko/20100101 Firefox/65.0"
185.228.228.247 - - [02/Mar/2019:06:25:56 +0000] "GET /fr/private_message/ajax_callback/get_new_unread_thread_count?token=GO0HLTZudaDjqwgY5Kj-aRBX58WbnRRpOMGyXdz4yug HTTP/2.0" 200 76 "https://www.example.com/fr/legal/document/politique_de_confidentialite" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:65.0) Gecko/20100101 Firefox/65.0"
```

**Comment by ZenImagine** [comment]
@allinurl OK it works, I changed the format. Which code do you use in the demo to display all the links in the menu ?

It works in real time but when I execute the command, the terminal displays:

WebSocket server ready to accept new client connections

If I do CTRL + C it stops the tracking in real time.

**Comment by allinurl** [comment]
Glad that worked. You need to ensure all `ignore-panel` are commented. SIGINT is doing what's supposed to do. You can use `--daemonize` if needed. Please take a look at the documentation for all the options available.

**Comment by ZenImagine** [comment]
@allinurl Thanks, can you share the command you enter in the terminal to create "Live Demo" ?

**Comment by ZenImagine** [comment]
I test the following command but there is no update in real time :

```
ubuntu@www-example-com ~ $ sudo goaccess /var/log/nginx/access.log -o /var/www/analytics-example-com/web/report.html --real-time-html --ssl-cert=/etc/letsencrypt/live/analytics.example.com/fullchain.pem --ssl-key=/etc/letsencrypt/live/analytics.s1biose.com/privkey.pem –ws-url=wss://analytics.example.com –enable-panel=REFERRERS --anonymize-ip --daemonize
Daemonized GoAccess: 10395
```

**Comment by allinurl** [comment]
Please start with the bare minimal.  

    sudo goaccess /var/log/nginx/access.log -o /var/www/analytics-example-com/web/report.html --real-time-html

and work your way up to determine which option is causing the issue. Let me know.

**Comment by ZenImagine** [comment]
@allinurl Sorry it works there is "--" which was automatically replaced by "-" in the word processor.

What is the order for the live demo please?

**Comment by allinurl** [comment]
Not sure I follow, is the live report working?

**Comment by ZenImagine** [comment]
@allinurl Yes now it works in the background. I wanted to know the command for live demo as an example. With all the panels

**Comment by allinurl** [comment]
All in the conf file.

```
config-dialog false
hl-header true
html-prefs {"theme":"darkPurple"}
html-report-title GoAccess Real-Time HTML Report
json-pretty-print false
no-color false
no-column-names false
no-csv-summary false
no-progress false
no-tab-scroll false
with-mouse false
port 9870
real-time-html true
ssl-cert /path/cert.pem
ssl-key /path/privkey.pem
ws-url wss://rt.goaccess.io:9870
agent-list true
with-output-resolver false
http-method yes
http-protocol yes
output-format /path/index.html
no-query-string false
no-term-resolver false
444-as-404 false
4xx-to-unique-count true
all-static-files false
date-spec hr
double-decode false
hour-spec min
ignore-crawlers false
crawlers-only false
real-os true
static-file .css
static-file .js
static-file .jpg
static-file .png
static-file .gif
static-file .ico
static-file .jpeg
static-file .pdf
static-file .txt
static-file .csv
static-file .zip
static-file .mp3
static-file .mp4
static-file .mpeg
static-file .mpg
static-file .exe
static-file .swf
static-file .woff
static-file .woff2
static-file .xls
static-file .xlsx
static-file .doc
static-file .docx
static-file .ppt
static-file .pptx
static-file .iso
static-file .gz
static-file .rar
static-file .svg
static-file .bmp
static-file .tar
static-file .tgz
static-file .tiff
static-file .tif
static-file .ttf
static-file .flv
geoip-database /path/GeoLiteCity.dat
```

**Comment by ZenImagine** [comment]
@allinurl Thank you, if I understood correctly, we can put the parameters directly in the configuration file instead of a command of several lines ?

**Comment by ZenImagine** [comment]
@allinurl There is a panel "VIRTUAL HOSTS" what is it for? It does not appear on my server.

If I specify all the parameters in the config file. How to run Goaccess, what is the command ?

I added the log and html path in the file :

```
log-file /var/log/nginx/access.log
output-format /var/www/analytics-example-com/web/report.html
real-time-html true
daemonize true
```

**Comment by allinurl** [comment]
> @allinurl Thank you, if I understood correctly, we can put the parameters directly in the configuration file instead of a command of several lines ?

Yes you can certainly do that, just remove the `--` from the beginning of the option.

> @allinurl There is a panel "VIRTUAL HOSTS" what is it for? It does not appear on my server.

If you have the `%v` specifier in your log-format, then it will display the virtual host.

Closing this as it appears to be resolved. Feel free to reopen it if needed.

**Comment by darkhan** [comment]
Hello! I have the same problem. Debian Linux, installed from the source with openssl and geoip.
`./configure --enable-utf8 --enable-geoip=legacy  --with-openssl`

`goaccess /home/username/domains/example.com/logs/nginx_access.log -o /home/username/domains/report/html/index.html --ssl-cert=/etc/nginx/ssl/cert.pem --ssl-key=/etc/nginx/ssl/private.key --ws-url=wss://example.com  --real-time-html --config-file=/usr/local/etc/goaccess/goaccess.conf`

in config file I use
`time-format %T`
`date-format %d/%b/%Y`
`log-format %h - %^ [%d:%t %^] "%r" %s %b "%R" "%u" "%^"`

I got these format via nginx2goaccess bash script.
Real-time updates not working. Can you help me with it?

**Comment by allinurl** [comment]
@darkhan are you getting an error message in the browser's console? Could you please run it through `strace` and attach the output here?

**Comment by darkhan** [comment]
No, everything works. But there are no updates. The log file is changed, but the report file is not

**Comment by narayan1599** [comment]
![Screenshot 2020-03-19 at 6 53 38 PM](https://user-images.githubusercontent.com/43582408/77072002-ffb18100-6a12-11ea-8bec-fd35bd9a6323.png)

**Comment by narayan1599** [comment]
what is the solution

**Comment by allinurl** [comment]
@narayan1599 What's the output of your browser's console? are you behind a proxy, or docker?

**Comment by narayan1599** [comment]
> @narayan1599 What's the output of your browser's console? are you behind a proxy, or docker?

it is not taking real time data to my bowser

**Comment by narayan1599** [comment]
are you behind a proxy, or docker?
no

**Comment by allinurl** [comment]
@narayan1599 What's the output of your browser's console?

**Comment by narayan1599** [comment]
![Screenshot 2020-03-19 at 7 05 34 PM](https://user-images.githubusercontent.com/43582408/77073066-a6e2e800-6a14-11ea-982c-8658fe290888.png)

**Comment by allinurl** [comment]
Right, I'm just curious what's the output of your browser's console (Ctrl+shift+j in Chrome).

**Comment by narayan1599** [comment]
> Right, I'm just curious what's the output of your browser's console (Ctrl+shift+j in Chrome).

nothing is happening

**Comment by narayan1599** [comment]
what it command do

**Comment by allinurl** [comment]
Not sure what you mean with your last comment. Are you able to telnet to the machine where goaccess is running on that specific port?

**Comment by narayan1599** [comment]
![Screenshot 2020-03-19 at 9 27 10 PM](https://user-images.githubusercontent.com/43582408/77086953-77d67180-6a28-11ea-92c8-eb6275fbe769.png)

**Comment by narayan1599** [comment]
is this u want to check

**Comment by allinurl** [comment]
Yes, but please clear that out and reload the page and post anything relevant to the report. Thanks

**Comment by narayan1599** [comment]
what is the command to get real time html

**Comment by narayan1599** [comment]
and how to clear it

**Comment by narayan1599** [comment]
?

**Comment by narayan1599** [comment]
thanks

**Comment by narayan1599** [comment]
the error is solved now thanks for your support

**Comment by manwithsteelnerves** [comment]
@allinurl : I see this error in the chrome console
```

WebSocket connection to 'ws://api.domain.com:7890/' failed: Error in connection establishment: net::ERR_CONNECTION_TIMED_OUT
setWebSocket @ report1.html:1780
```


I'm using nginx proxy. Any special setup I need to activate realtime?
