### ISSUE TITLE
goaccess with zabbix

### ISSUE THREAD

**Issue by SlackMaker** [allinurl/goaccess#1389]
Hi, Srs !

I need to implement the goaccess panel inside zabbix, has anyone managed to do this?

**Comment by allinurl** [comment]
Can you post some additional details about this? I'm not familiar with zabbix, however, it would be interesting to know what exactly you are trying to do.

**Comment by ottok** [comment]
How to implement a new panel in Zabbix is completely a Zabbix question and thus I recommend you close this issue as there is nothing in GoAccess to design/implement in this regard.

**Comment by allinurl** [comment]
Closing this. @SlackMaker feel free to post additional details if needed.
