### ISSUE TITLE
Help with log format

### ISSUE THREAD

**Issue by travisnewman** [allinurl/goaccess#1390]
Hi folks, I've tried modifying a few examples I've seen here to no avail. I'm attaching the tail of access.log with some redactions

```
123-123-123-123.cust.isp.net - - [28/Feb/2019:06:25:16 -0500] "GET /images/services/redacted.jpg HTTP/1.1" 200 39019 "https://www.domain.com/" "Mozilla/5.0 (Linux; Android 6.0.1; SM-G930V) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.99 Mobile Safari/537.36"
localhost - - [28/Feb/2019:06:25:16 -0500] "OPTIONS * HTTP/1.0" 200 110 "-" "Apache/2.4.18 (Ubuntu) OpenSSL/1.0.2g (internal dummy connection)"
host.domain.com - - [28/Feb/2019:06:25:17 -0500] "GET /rss/alerts/ HTTP/1.1" 302 418 "app:/application" "Mozilla/5.0 (Windows; U; en-US) AppleWebKit/533.19.4 (KHTML, like Gecko) AdobeAIR/3.8"
host.domain.com - - [28/Feb/2019:06:25:17 -0500] "GET /rss/alerts/ HTTP/1.1" 200 314 "app:/application" "Mozilla/5.0 (Windows; U; en-US) AppleWebKit/533.19.4 (KHTML, like Gecko) AdobeAIR/3.8"
host.domain.com - - [28/Feb/2019:06:25:17 -0500] "GET /rss/sign_messages/ HTTP/1.1" 302 432 "app:/application" "Mozilla/5.0 (Windows; U; en-US) AppleWebKit/533.19.4 (KHTML, like Gecko) AdobeAIR/3.7"
host.domain.com - - [28/Feb/2019:06:25:17 -0500] "GET /rss/sign_messages/ HTTP/1.1" 200 2954 "app:/application" "Mozilla/5.0 (Windows; U; en-US) AppleWebKit/533.19.4 (KHTML, like Gecko) AdobeAIR/3.7"
123-123-123-123.cust.isp.net - - [28/Feb/2019:06:25:17 -0500] "GET /images/news/redacted.jpg HTTP/1.1" 200 362263 "https://www.domain.com/" "Mozilla/5.0 (Linux; Android 6.0.1; SM-G930V) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.99 Mobile Safari/537.36"
123-123-123-123.cust.isp.net - - [28/Feb/2019:06:25:17 -0500] "GET /images/services/redacted.jpg HTTP/1.1" 200 79748 "https://www.domain.com/" "Mozilla/5.0 (Linux; Android 6.0.1; SM-G930V) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.99 Mobile Safari/537.36"
123-123-123-123.cust.isp.net - - [28/Feb/2019:06:25:19 -0500] "GET /images/services/redacted.jpg HTTP/1.1" 200 44435 "https://www.domain.com/" "Mozilla/5.0 (Linux; Android 6.0.1; SM-G930V) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.99 Mobile Safari/537.36"
123-123-123-123.cust.isp.net - - [28/Feb/2019:06:25:20 -0500] "GET /images/services/redacted.jpg HTTP/1.1" 200 37774 "https://www.domain.com/" "Mozilla/5.0 (Linux; Android 6.0.1; SM-G930V) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.99 Mobile Safari/537.36"
```

The ones that are 123-123-123-123.cust.isp.net are outside connections, the host.domain.com are internal and are coming from an app that has also been redacted. 

Any help on the format for this? Thanks!

EDIT:

Actually it seems like if I grep for a single IP and output it to a new file, it works with just the standard log format, so it seems any hostnames as the client source will break this.

A. Is there any way around this?
B. If not, how might I go about telling Apache to only log IP, not name.

**Comment by allinurl** [comment]
Are you resolve the IPs to hostnames? Are you able to change that? goaccess currently requires a valid IP

**Comment by travisnewman** [comment]
I figured that part out. Well, kinda. It wasn't set to resolve but it still was. A reboot fixed it, not sure what exactly was going on there.

I'm curious as to why hostnames won't work, is it just a matter of it being hard to account for all the different ways it could be formatted?

**Comment by allinurl** [comment]
Originally was designed to validate those IPs and resolve them within goaccess, if you build from development, then a recent patch was added that could work in your case, please use the flag `--no-ip-validation` and let me know if that does the job for you.

```
$ git clone https://github.com/allinurl/goaccess.git
$ cd goaccess
$ autoreconf -fiv
$ ./configure --enable-utf8 --enable-geoip=legacy
$ make
# make install
# goaccess access.log --log-format=COMBINED --no-ip-validation
```

**Comment by travisnewman** [comment]
I'm fine without it, I'd prefer they not resolve as the user accesses the server anyway. I was just curious about reasoning. That's good to know, though, in case something changes.

Thanks for the info and the truly amazing program!
