### ISSUE TITLE
TokyoCabinet corruption with lot's of traffic

### ISSUE THREAD

**Issue by Power2All** [allinurl/goaccess#1391]
I try using GoAccess for a while now.
Problem is, that if the TokyoCabinet database is not exited correctly (or closed so to speak), it appears to get corrupted really quickly, and GoAccess won't be able to continue, or crashes, and won't be able to boot it up anymore, unless I remove all the TokyoCabinet files.
I hope that an option to use local or remote influxDB or any other metrics recording database will be able to be used, since TokyoCabinet is just unsafe and unreliable as it is now.

**Comment by allinurl** [comment]
Thanks for reporting this. There're  a few reports on this bug as well. As you mentioned, the plan #1274 is to replace TC. I'm still looking for options in terms of DBs and what would work best. How stable has been for you influxdb?

**Comment by Power2All** [comment]
> Thanks for reporting this. There're a few reports on this bug as well. As you mentioned, the plan #1274 is to replace TC. I'm still looking for options in terms of DBs and what would work best. How stable has been for you influxdb?

Very, the hosting company I worked for (with some high availability companies) uses it for it's monitoring. Tickstack is using InfluxDB, and some other companies use it too. InfluxDB is also pretty simple and easy in use, and would be very nice for this kind of metrics as well. Also, InfluxDB is very fast and it supports clustering to loadbalance. It would be a good option for GoAccess next to TokyoCabinet. Maybe some other metrics databases are nice too, like Cassandra as has been mentioned as well.
Just more options other then TokyoCabinet would be beneficial for anybody that want a choice what database/metrics measuring they like to use, so to speak.

**Comment by allinurl** [comment]
Thanks for suggesting this. I definitely plan to replace TC. I'll look into InfluxDB. Although one of the key features of goaccess is having an embedded db just for simplicity.

**Comment by Power2All** [comment]
> Thanks for suggesting this. I definitely plan to replace TC. I'll look into InfluxDB. Although one of the key features of goaccess is having an embedded db just for simplicity.

I agree, but it should also be a option to use other metrics databases.
There is no harm to keep support of TokyoCabinet in place for people who like to use it, even if it's unstable or insecure when it comes to high traffic usage.
ElasticSearch is also often used for metrics, but InfluxDB is still the best option, it's also free and open source ( see https://github.com/influxdata/influxdb ) and they offer paid support option, which is especially useful for big companies we need 24/7 support.

Thanks for GoAccess, it's a very useful system 👍

**Comment by allinurl** [comment]
The on-disk storage issue has been addressed. It now supports native on-disk persistence storage (no dependencies). New command line options are `--persist`, `--restore`, `--keep-last=<num_days>`. It also adds the ability to re-parse the same log(s) without counting data twice (see #334 or for exact details [**this post**](https://github.com/allinurl/goaccess/issues/334#issuecomment-272317226)).

This will be pushed out in the upcoming release. However, it would be great if you could test this out before deployment by building from [**development**](https://github.com/allinurl/goaccess#build-from-github-development).

Closing this as fixed. Feel free to post back as needed.

**Comment by allinurl** [comment]
Actually [**v1.4**](https://goaccess.io/download) has been released.
