### ISSUE TITLE
Proposal: Unification of coding style by the source code formatter.

### ISSUE THREAD

**Issue by err931** [allinurl/goaccess#1393]
### Hey brother! There are kool product, today!

[ClangFormat](https://clang.llvm.org/docs/ClangFormat.html)

As the name suggests, it formatter for C++ that comes with Clang. Of course you can use "ANSI C".
**(Although it's not already done well)** I'm trying replace to [LevelDB](https://github.com/google/leveldb) from TokyoCabinet.

So I used this tool to check the overall picture.
As a reference, set aside the source code formatting and configuration files. [Sample](https://gist.github.com/err931/91a024367838dcc4a122108004c2b660)

For Debian (and Ubuntu) you can install it with **apt-get**.
`apt install -yq clang-format`

If you want to check roughly, you can do it like this.
`clang-format -i -style=Google src/*.c`

If you put **.clang-format** in your home directory, you can set detailed rules.
`clang-format -i -style=file src/*.c`

I hope this will help.

**Comment by allinurl** [comment]
I do like the code style. Any reason as to why you closed it? I'll give it a shot and let you know.

**Comment by err931** [comment]
**I missed the operation...**
A problem occurred when I tried to edit it into formal sentences. Probably it's due to development tools.

Code style is sensitive problem. If necessary, please start a discussion. :muscle:

I'll leave it in your hands. Reopened this issues or start a new one.
