### ISSUE TITLE
Config file option for --browsers-file

### ISSUE THREAD

**Issue by lahwaacz** [allinurl/goaccess#1396]
The path for `--browsers-file` should be configurable in the config file.

**Comment by allinurl** [comment]
You should be able to set it through the conf file. Are you getting an error message?

**Comment by lahwaacz** [comment]
Sorry, didn't see the option commented in my config file, so I assumed it was missing...

**Comment by allinurl** [comment]
Are you using the latest version? The [**option**](https://github.com/allinurl/goaccess/blob/master/config/goaccess.conf#L433) should be there...

**Comment by lahwaacz** [comment]
Yes, but before https://github.com/allinurl/goaccess/commit/126f61a1e7fe52ae9f7358ec7e2f0232f887bc5c#diff-bb2cd4651768482b99cb1c52d29ceffd, that file was not used by default so I was looking in `/etc/goaccess.conf` which didn't contain the new options.

**Comment by allinurl** [comment]
Thanks for pointing that out. The upcoming version fixes this :)
