### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by luwfls** [allinurl/goaccess#1397]
```tail -f /usr/local/nginx/logs/access.log  | goaccess --log-format=COMBINED -q -a -o /data/visit/status.html --real-time-html```

Output all the time  like "Parsing... [520,438] [1,112/s]"，but no result。

**Comment by allinurl** [comment]
Can you please try adding the extra dash in there,

    tail -f access.log | goaccess - --log-format=COMBINED

**Comment by luwfls** [comment]
tanks,but not helpful

**Comment by allinurl** [comment]
Are you in v1.3?

**Comment by luwfls** [comment]
thanks , I use 1.1.1，its work in 1.3
