### ISSUE TITLE
Unable to use live report due to time format missing

### ISSUE THREAD

**Issue by cosmokid** [allinurl/goaccess#1398]
I run `goaccess -f /var/log/nginx/access.log -a ` and it then shows me `Log Format Configuration` I select the first one. Works fine. 

However, when I use ` goaccess access.log -o /usr/share/nginx/www/rt.goaccess.io/report.html --real-time-html` It doesn't work and gives me  

> GoAccess - version 1.3 - Mar  5 2019 18:40:58
Config file: /usr/local/etc/goaccess.conf

>Fatal error has occurred
Error occurred at: src/parser.c - parse_log - 2764
No time format was found on your conf file.

Also, `/usr/share/nginx/www/rt.goaccess.io/` seems to be missing from my Ubuntu server.

**Comment by allinurl** [comment]
You will need to set your log/date/time-format under `/usr/local/etc/goaccess.conf` or run goaccess as:

    goaccess access.log --log-format=COMBINED -o /usr/share/nginx/www/rt.goaccess.io/report.html --real-time-html

**Comment by cosmokid** [comment]
> /usr/local/etc/goaccess.conf

This is my goaccess.conf file:

# Apache log date format. The following date format works with any of the Apache's log formats below.
#
date-format %d/%b/%Y
# NCSA Combined Log Format with Virtual Host
#
log-format %^:%^ %h %^[%d:%^] "%r" %s %b "%R" "%u"
#
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
"/usr/local/etc/goaccess.conf" 7L, 225C                       1,1           All

This still doesn't work. What am I doing wrong?

**Comment by allinurl** [comment]
How are you running goaccess when it doesn't work?

**Comment by cosmokid** [comment]
> How are you running goaccess when it doesn't work?

I honestly have no idea. What do you mean?

**Comment by allinurl** [comment]
Based on the error you are getting, I'm guessing you didn't specify the `log-file` option in the config file. i.e., `log-file /var/log/apache2/access.log`.

As far as the `--real-time-html` not being live, please take a look at the browser's console and see what error you are getting. By default, GoAccess will use the host name of the generated report. Optionally, you can specify the URL to which the client's browser will connect to using `--ws-url`.

    # goaccess access.log -o report.html --real-time-html --ws-url=goaccess.io

Let me know if that helps.

**Comment by cosmokid** [comment]
> Based on the error you are getting, I'm guessing you didn't specify the `log-file` option in the config file. i.e., `log-file /var/log/apache2/access.log`.
> 
> As far as the `--real-time-html` not being live, please take a look at the browser's console and see what error you are getting. By default, GoAccess will use the host name of the generated report. Optionally, you can specify the URL to which the client's browser will connect to using `--ws-url`.
> 
> ```
> # goaccess access.log -o report.html --real-time-html --ws-url=goaccess.io
> ```
> Let me know if that helps.

[https://i.imgur.com/9gCs58C.png](url) Is this what you wanted me to show you? As far as the console goes, it's just blank: [https://i.imgur.com/anrugQL.png](url)

Running `goaccess access.log -o report.html --real-time-html --ws-url=goaccess.io` returns:

```GoAccess - version 1.3 - Mar  5 2019 18:40:58
Config file: /usr/local/etc/goaccess.conf

Fatal error has occurred
Error occurred at: src/parser.c - parse_log - 2764
No time format was found on your conf file.```

**Comment by cosmokid** [comment]
Any update sir?

**Comment by allinurl** [comment]
The time-format issue is as a result that you haven't specify the `time-format` variable. Please take a look at the default config file. I see there's a console error on the first screenshot you posted, can you please click on it and post what is that about.

**Comment by cosmokid** [comment]
> The time-format issue is as a result that you haven't specify the `time-format` variable. Please take a look at the default config file. I see there's a console error on the first screenshot you posted, can you please click on it and post what is that about.

How do I edit the config file correctly to support this?

**Comment by cosmokid** [comment]
Hello, just a quick update. Managed to get the `report.html` setup. However, it's not in real time, it's only static and only refreshes if I close the connection and re-do the command.

`root@college:/var/www/html# goaccess -f /var/log/nginx/access.log -o /var/www/html/report.html --real-time-html --ws-url=ws://ip:7890
WebSocket server ready to accept new client connections
`

**Comment by allinurl** [comment]
Are you able to telnet to that port?

**Comment by cosmokid** [comment]
> Are you able to telnet to that port?

No, sorry. `telnet: Unable to connect to remote host: Connection refused
`

**Comment by allinurl** [comment]
That's probably the reason. Did you open the port?

**Comment by cosmokid** [comment]
> That's probably the reason. Did you open the port?

Actually, yes. I typed it without typing `goaccess -f /var/log/nginx/access.log -o /var/www/html/report.html --real-time-html --ws-url=ws://ip:7890`

Now, I'm able to Telnet it. What would you like me to try now? It's still static.

**Comment by ZenImagine** [comment]
I test the following command but there is no update in real time :

```
ubuntu@www-example-com ~ $ sudo goaccess /var/log/nginx/access.log -o /var/www/analytics-example-com/web/report.html --real-time-html --ssl-cert=/etc/letsencrypt/live/analytics.example.com/fullchain.pem --ssl-key=/etc/letsencrypt/live/analytics.s1biose.com/privkey.pem –ws-url=wss://analytics.example.com –enable-panel=REFERRERS --anonymize-ip --daemonize
Daemonized GoAccess: 10395
```

**Comment by allinurl** [comment]
Can you please try to establish an HTTP handshake and upgrade the connection to WS via telnet?

**Comment by cosmokid** [comment]
> Can you please try to establish an HTTP handshake and upgrade the connection to WS via telnet?

I've actually managed to fix it! Not sure what I did, just endlessly tried different commands and it finally worked! `goaccess -f /var/log/nginx/access.log -o /var/www/html/report.html --real-time-html --ws-url=ws://ip:7890
`
However, since enabling HTTPs with LetsEncrypt, it stopped loading completely and console shows

`report.html:1 Mixed Content: The page at 'https://website.com/report.html' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://ip:7890/'. This request has been blocked; this endpoint must be available over WSS` 

And 

`Uncaught DOMException: Failed to construct 'WebSocket': An insecure WebSocket connection may not be initiated from a page loaded over HTTPS.
    at Object.setWebSocket (https://website.com/report.html:1:344282)
    at Object.initialize (https://website.com/report.html:1:343494)
    at window.onload (https://website.com/report.html:1:381656)`

**Comment by allinurl** [comment]
Please use `--ws-url=wss://ip:7890` when using HTTPS. This is described in the man page.

**Comment by cosmokid** [comment]
> Please use `--ws-url=wss://ip:7890` when using HTTPS. This is described in the man page.

Didn't work sir.

`goaccess -f /var/log/nginx/access.log -o /var/www/html/report.html --real-time-html --ws-url=wss://ip:7890 --ssl-cert=/etc/letsencrypt/live/www.website/cert.pem -ssl-key=/etc/letsencrypt/live/www.website.com/privekey.cem
goaccess: unrecognized option '--ssl-cert=/etc/letsencrypt/live/www.website.com/cert.pem'`

**Comment by allinurl** [comment]
did you build with [openssl](https://goaccess.io/man#configuration) support?

**Comment by cosmokid** [comment]
> did you build with [openssl](https://goaccess.io/man#configuration) support?

No, I didn't. I didn't have SSL at the time of setup.

**Comment by allinurl** [comment]
Please do so that way the ssl support will be active.

**Comment by allinurl** [comment]
Closing this, feel free to reopen it if needed.

**Comment by yolandabrg** [comment]
there is a problem here. how to solve it? please

goaccess access.log -o /var/www/backendserver2/report.html --log-format=COMBINED --real-time-html

GoAccess - version 1.4.3 - Dec  4 2020 02:15:51
Config file: /etc/goaccess/goaccess.conf

Fatal error has occurred
Error occurred at: src/parser.c - read_log - 3177
Unable to open the specified log file 'access.log'. No such file or directory

**Comment by allinurl** [comment]
@yolandabrg As the error says, access log doesn't exist on your path. Please make sure yo specify the full path to your access log.
