### ISSUE TITLE
About the date display of report. #1310

### ISSUE THREAD

**Issue by err931** [allinurl/goaccess#1400]
I'm troubled. How do you solve this problem.

I suggested before. #1310
I fork and verified the repository to see how this should be resolved. And I found a way to solve this problem.

```
127.0.0.1 - - [07/Mar/2019:01:48:21 +0900] "GET /timelines/62583497 HTTP/1.1" 200 109 "/user/kamino" "Mozilla/5.0 (Windows NT 6.0) AppleWebKit/535.11 (KHTML, like Gecko) Chrome/17.0.963.56 Safari/535.11"
```

This is a part of the log recorded in the **Combined format,** but I was able to confirm that the date and time are in British expression.
Which source code should I change to convert this to RFC3339 format? (I think that the `get_visitors_date` function in` util.c` is doubtful)

-----
Once this issue is resolved, I start to new issue proposing a change from "MIT" to "Apache License 2.0"
The contributors' rights will be clarified, the opportunities used by corporations will increase and the load (to solve problems) will be dispersed.

**Comment by allinurl** [comment]
Just so I understand, are you trying to parse this specific format `[07/Mar/2019:01:48:21 +0900]` or  display  it in different format?

**Comment by err931** [comment]
Parser don't modify. I will convert internal data and make it compliant with RFC3339 format.

**Comment by allinurl** [comment]
To answer your question, yes, you are probably looking at `get_visitors_date` which should take care of the displaying of the parsed dates.

**Comment by err931** [comment]
Thx! If conversion to RFC3339 format is successful, send PR.
