### ISSUE TITLE
GoAccess in Docker env: no real time updates

### ISSUE THREAD

**Issue by okoester** [allinurl/goaccess#1401]
Hi,

I've set up GoAccess in Docker environment following [this](https://hub.docker.com/r/allinurl/goaccess 
)

I created a config file as described:
> log-format VCOMBINED
> log-file /srv/logs/access.log
> output /srv/report/index.html
> real-time-html true
> exclude-ip 172.17.0.1-172.17.0.254

The given log file is processed, but when it is updated by the Apache Webserver, the GoAccess dashboard isn't...

After starting docker container docker logs gave me the following output:

>  WebSocket server ready to accept new client connections

The websocket seems to be open when trying to access with nc (netcat)

Is there any way to "trigger" updates of the page?
Or do I miss some settings in goaccess.conf ?

Regards
Olaf

**Comment by allinurl** [comment]
Can you post your browser's console output? Also, do you see a green green dot icon as in the [**live**](https://rt.goaccess.io/?20181123091935) version active or is grayed out? Thanks.

**Comment by okoester** [comment]
Hi, there is this grey dot close to the settings icon. It popup tess disconnected...

And the console output states that my browser cannot connect to wss://<sitename>:7890

I think it is because of the apache configuration on my host system.
I do not use reverse proxy but link from /var/www/goaccess/index.html to the index.html in the docker environment.
I'd prefer reverse proxy setup but do not know how to set that up with goaccess docker container...

Any help?

**Comment by allinurl** [comment]
Seems you are not specifying any host. Please take a look at the man page for --ws-url
If you are using docker, please take a look at this [instructions](https://github.com/allinurl/goaccess#docker).

**Comment by okoester** [comment]
Thanks, that helped. Statistics seem to be updated in real time now.
I've opened the ws port and had to add the certs to make it work. Accessing the website via https:// requires to access the web service also via wss:// not ws:// ;-)
And now this green dot icon is really green :-D

Thanks for support!
