### ISSUE TITLE
haproxy format string problems

### ISSUE THREAD

**Issue by jrichet** [allinurl/goaccess#1402]
It would be really great if there was a tool to build format strings from an example string provided.

I've gotten goaccess to work on many different log formats, but this one is not working for me...

As it is, my log looks like this:
```
Mar  8 06:25:07 ip-172-31-16-77 haproxy[2168]: 52.15.166.202:42448 [08/Mar/2019:06:25:07.063] http-in cluster_name/api2 0/0/0/1/1 200 1825 - - ---- 2/2/0/0/0 0/0 "GET //api/misc/form HTTP/1.1"
```
the format strings I've tried include but are not limited to the following:
```
%^  %^ %^ %^ %^: %^ [%d:%t.%^] %^ %^ %^ %s %b %^ %^ %^ %^ %^ "%m %q %H"
%^  %^ %^ %^ %^[%^]: %h:%^ [%d:%t] %^ %^ %s %b - - ^% %^ %^ "%m %q %H"
%^  %^ %^ %^ %^[%^]: %h:%^ [%d:%t] %^ %^ %^ %s %b - - ---- %^ %^ "%m %q %H"
%^  %^ %^ %^ %^[%^] %h:%^ [%d:%t%.^] ^% ^% ^% %s %b %^ %^ %^ %^ %^ "%m %r %H"
%^  %^ %^ %^ %^[%^]: %h:%^ [%d:%t%.^] ^% ^% ^% %s %b %^ %^ %^ %^ %^ "%m %r %H"
%^  %^ %^ %^ %^ %h:%^ [$d:%t.%^] %^ %^ %^ %s %b ^% ^% ^% ^% ^% "%m %q %H"
```
And goaccess keeps telling me "nothing valid to process"
I am getting pretty frustrated. can anyone see what's wrong?

**Comment by jrichet** [comment]
bonus points for providing answer on SO as well https://stackoverflow.com/questions/55072107/goaccess-format-for-haproxy

**Comment by allinurl** [comment]
I can certainly take a look. Could you please describe these fields: `0/0/0/1/1 200 1825 - - ---- 2/2/0/0/0 0/0`? Thanks.

**Comment by allinurl** [comment]
Any updates on this?

**Comment by jazzl0ver** [comment]
@jrichet I use this format:
```
log_format %^ %~ %^ %^ %^ [%d:%t.%^] %^ %^ %^/%^/%^/%^/%^/%^/%L ....
```
What actually matters here is the 2nd key **%~**, which skips the extra space when the date number becomes 1 digit. I had hard time figuring it out and bombing @allinurl with false bug reports ;-\

**Comment by allinurl** [comment]
Take a look at https://github.com/stockrt/nginx2goaccess

Closing this, feel free to reopen it if needed.
