### ISSUE TITLE
why cannot show chinese on html by docker?

### ISSUE THREAD

**Issue by pengwenwu** [allinurl/goaccess#1403]
when i run it by docker, get html within english language。How can i solve it，tks。  

![](http://pic.pwwtest.com/20190311175929.png)

**Comment by err931** [comment]
Please pass `-e LANG=zh_CN` option when `docker run`. **Enjoy!**

**Comment by pengwenwu** [comment]
> Please pass `-e LANG=zh_CN` option when `docker run`. **Enjoy!**

thank you, it works.
