### ISSUE TITLE
Proposal: Renew Dockerfile

### ISSUE THREAD

**Issue by err931** [allinurl/goaccess#1404]
I have used the **GoAccess** in business. It has achieved great results and is well received in the company.

However, the size of official Docker image is so large that security audits may not pass.
So I wrote an unofficial Dockerfile and operated it in-house. It has been in operation for about half a year, but it's stable enough.

I will submit `Dockerfile` if you accept it.
Apply **Apache License 2.0** to the license. This does not conflict with the MIT license.

Please kindly consider this matter. :muscle:

# Comparison
- Using a multi-build, we reduced the size of the image.
	- After building in Alpine, it will be saved in the image of BusyBox. By eliminating extra packages, you are more resistant to vulnerabilities.
- Replace OpenSSL to LibreSSL.
	- Normally, you can't use host-side shared libraries in container image. Therefore, I replaced it with a static link.
	- Less susceptible to vulnerabilities from OpenSSL, you can avoid unnecessary build.
- Compatible with `ARM architecture`.
	- This image has been successfully built many times on `Raspberry Pi 3`.
	- So you don't have to worry about `ARM-based CPUs` that will increase in the future.
- Minimum required command.
	- There is no need to insert `tini` to make it **PID 1**. It can be substituted with the `docker run --init` command.
	- Even using the `VOLUME` command, you can't host side and the synchronization.
	- Only `/var/www/goaccess` and 7890 port are open to connect with `nginx` container etc.

**Comment by allinurl** [comment]
Would it work still the same way as it's in the [**docs**](https://github.com/allinurl/goaccess#docker)? I'm all for any improvements and this sounds like it has several of them :)

**Comment by err931** [comment]
Regarding your question, **most of them work.** :+1:
However, I have disabled **GeoIP** and **Tokyo Cabinet**.

Not to mention the latter, but there is a reason for **GeoIP**. Because it must respond to [GDPR](https://ec.europa.eu/info/law/law-topic/data-protection_en).
**GDPR also protects IP addresses**, which must be excluded if a viewer refuses to retrieve data.

However, it's difficult to record that intention in the access log.
The only workaround is to `Anonymize all IP addresses` in which case GeoIP won't work.

Can you tell me what you think is a problem? Answer your questions.

# For example
If you want to output Apache log as HTML report, you can do as follows. There is no need to install directly as it's isolated in the container.
**Note: if you were replaced by the new Dockerfile.**

```
cat access.log | docker run --rm -i -e LANG=$LANG allinurl/goaccess --log-format=VCOMBINED -a -o html - > report.html
```

**This works well in practice.** This is why you need to keep container size as small as possible.
Because the main options plan to change to pass in environment variable.

```
cat access.log | docker run --rm -i -e LANG=$LANG -e LOG_FMT=VCOMBINED -e OUTPUT=json allinurl/goaccess > report.json
```

## Default
- LOG_FMT=COMBINED
- OUTPUT=html

**Comment by err931** [comment]
This is the [Dockerfile](https://github.com/err931/project-corvus/blob/master/Dockerfile) I'm planning to pull request.
Please see the attached.

**Comment by allinurl** [comment]
Looks good to me. Regarding the IP and GDPR, shouldn't this concern be addressed with the `--anonymize-ip` option? Also, I just want to make sure the build [**docs**](https://github.com/allinurl/goaccess#docker) would still apply with this Dockerfile, can you confirm this? Thanks

**Comment by err931** [comment]
> Regarding the IP and GDPR, shouldn't this concern be addressed with the `--anonymize-ip` option?

Yes, I also considered it. But I don't think it makes sense to anonymize IP addresses if GeoIP can identify **Location**.
I'm putting it on hold because I can't say that the accuracy is good and it may cause unexpected complaints.

> Also, I just want to make sure the build docs would still apply with this Dockerfile, can you confirm this?

There was no problem here. `Volume mounts` and `port forwarding` in **Docker options** are not affected by **Dockerfile**.
However, I have the idea that the configuration file should be imported as a custom image prepared separately. Just like this.

```
FROM allinurl/goaccess
COPY goaccess.conf /root/.goaccessrc
RUN tar Jxf tzdata.tar.xz ./Japan && mv -f ./Japan /etc/localtime
CMD ["--no-global-config"]
```

We need more information...

**Comment by allinurl** [comment]
I see. I do like the idea. Please feel free to submit the PR and also please don't forget the update the README.md accordingly.

**Comment by err931** [comment]
Thx! :sunglasses:
Because it's likely to be deployed in a staging or production environment, perform additional testing using possible patterns. That will improve the reliability.

Organize your documents at the same time. It will also add what should be included in the document. (For example, #1403 etc...)
This issue closes. I will send you a pull request as soon as I pass the test and organize the documents.

We appreciate your patience as it might take some time.
Best regards,
