### ISSUE TITLE
Font Awesome missing in HTML Report

### ISSUE THREAD

**Issue by roben** [allinurl/goaccess#1405]
I noticed Icons being broken in the HTML Report using GoAccess 1.2 from Debian testing. Viewing the page source revealed that the font is loaded from files (which do not exist):

`src:url('../fonts/fontawesome-webfont.eot?v=4.7.0')`

Which is in contrast to `https://github.com/allinurl/goaccess/blob/master/resources/css/fa.min.css`. 

Maybe the debian guys changed the inlining to external files due to licensing issues? Or is it just a configuration thing that needs to be changed? I did not find anything related, though.

**Comment by roben** [comment]
I just tested v1.3 using the official repository and can confirm icons working just fine there. So it seems to be an issue with the debian package.

**Comment by allinurl** [comment]
Thanks for reporting this. It looks like some changes were done to the debian package as listed [**here**](https://metadata.ftp-master.debian.org/changelogs/main/g/goaccess/goaccess_1.2-4_changelog). Like you said, it might be a licensing thing. Please feel free to report this to the debian maintainer, or using this [**link**](https://bugs.debian.org/cgi-bin/pkgreport.cgi?pkg=goaccess;dist=unstable).

**Comment by niol** [comment]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=934121 so this can be closed here.
