### ISSUE TITLE
[Solved] Processing logs with goaccess and logrotate  - question.

### ISSUE THREAD

**Issue by AreYouLoco** [allinurl/goaccess#1406]
Hi!

I am using this command to print real-time html output:
goaccess /path/to/access.log --log-format=COMBINED -o /path/to/www/root/report.html --real-time-html --real-os --all-static-files --agent-list --http-protocol=yes --http-method=yes --hl-header

And it shows statistics only from one day (current day). There is also files like access.log.12.gz due to logrotate. How can I use all of the data? Also compressed with logrotate.

Thanks in advance!

**Comment by allinurl** [comment]
Please try using:

    zcat access.log.*.gz | goaccess access.log --log-format=COMBINED - -o /path/to/www/root/report.html

Also note that each active panel has a total of 50 entries in the real-time HTML report instead of the 366 in static mode.  Let me know how that goes.

**Comment by AreYouLoco** [comment]
Yup it works. issue can be closed and marked solved. I switched to static pages and your pipe trick and now I can see all the data which is more than disturbing.
Why people would like to break into my phpmyadmin, why?:D
