### ISSUE TITLE
Meaning of Init. Proc. Time

### ISSUE THREAD

**Issue by linermgn** [allinurl/goaccess#1414]
Please, give description of Init. Proc. Time indicator, what it shows? It is unclear and I have no luck to find it at documentation.

**Comment by allinurl** [comment]
Initial processing time. Essentially how long it took to parse the whole log from scratch. Thanks for bringing this up. I can certainly add some title and description to the docs about this.

**Comment by lovasoa** [comment]
Maybe it could be renamed "log parsing time" ?

I was scared at first, because I thought it was somewhat related to the time taken by the server to serve requests.

**Comment by allinurl** [comment]
@lovasoa I agree. Would you be able to submit a PR with this update? Changing [**this line**](https://github.com/allinurl/goaccess/blob/master/src/labels.h#L64) should do it.

**Comment by lovasoa** [comment]
👍 thanks !
