### ISSUE TITLE
not able to open report.html

### ISSUE THREAD

**Issue by partsauthority** [allinurl/goaccess#1415]
I am able to see interactive screen with all statistics for my access log but not able to load the html from browser. It says loading but never loads. Please help me out with loading the html report generated.

command used:

/usr/local/bin/goaccess /opt/IBMIHS/logs/webqa/access_log.20190321 --log-format='%h %v %U %s [%d:%t %^] %D "%u"' --date-format='%d/%b/%Y' --time-format=%T --enable-panel=REFERRERS --enable-panel=KEYPHRASES

command used for generating report.html:

/usr/local/bin/goaccess /opt/IBMIHS/logs/webqa/access_log.20190321 --log-format='%h %v %U %s [%d:%t %^] %D "%u"' --date-format='%d/%b/%Y' --time-format=%T --enable-panel=REFERRERS --enable-panel=KEYPHRASES -o report.html

**Comment by allinurl** [comment]
Please post a screenshot of your browser's console. Thanks.

**Comment by partsauthority** [comment]
![image](https://user-images.githubusercontent.com/49204615/55420772-aa900d00-552c-11e9-8cf9-b31deb9b2537.png)

**Comment by allinurl** [comment]
Please post the browser's console (second tab).

**Comment by partsauthority** [comment]
![image](https://user-images.githubusercontent.com/49204615/55495634-34ee7480-55f2-11e9-8bac-c8ca6bc0ba5e.png)

its not writing anything in console tab

**Comment by partsauthority** [comment]
[reporthtml.docx](https://github.com/allinurl/goaccess/files/3039740/reporthtml.docx)

**Comment by allinurl** [comment]
Can you please attach this as an html file? Thanks

**Comment by partsauthority** [comment]
html file extension is not supported to upload in here

**Comment by partsauthority** [comment]
[report.zip](https://github.com/allinurl/goaccess/files/3039792/report.zip)

**Comment by partsauthority** [comment]
I zipped the html file and uploaded it. Hope you can see the file

Thanks

**Comment by allinurl** [comment]
I dont see any loading scripts in the dom. How did you build goaccess? Are you able to build from [development](https://github.com/allinurl/goaccess#build-from-github-development) and see if that solves the issue? Thanks

**Comment by partsauthority** [comment]
I followed this steps to install goaccess except for the --enable-geoip=legacy

$ wget https://tar.goaccess.io/goaccess-1.3.tar.gz
$ tar -xzvf goaccess-1.3.tar.gz
$ cd goaccess-1.3/
$ ./configure --enable-utf8 
$ make
# make install

I have not tried it building from development

**Comment by xorock** [comment]
I'm having the same issue. 

```bash
goaccess access_log -a -o report.html --config-file=/etc/goaccess/goaccess.conf --real-os
```

Console has 4 errors

```
SyntaxError: illegal character report.html:1:151139
SyntaxError: illegal character report.html:1:8554
SyntaxError: illegal character report.html:1:39695
SyntaxError: illegal character report.html:1:20420
```

**Comment by allinurl** [comment]
@xorock How did you build goaccess? Are you able to build from [development](https://github.com/allinurl/goaccess#build-from-github-development) and see if that solves the issue? Thanks

**Comment by xorock** [comment]
There must be some package errors. I've compiled 1.3 version and works as expected.
https://build.opensuse.org/package/show/server%3Ahttp/goaccess
Spec file https://build.opensuse.org/package/view_file/server:http/goaccess/goaccess.spec?expand=1 shows, it is basically the same config.

**Comment by allinurl** [comment]
Good to know is a SUSE build issue. I can add it to the docs. What's the command to install it on suse?

**Comment by xorock** [comment]
```bash
zypper addrepo https://download.opensuse.org/repositories/server:/http/[Distro version]/
#for example zypper addrepo https://download.opensuse.org/repositories/server:/http/openSUSE_Leap_15.0/
zypper refresh
zypper install goaccess
```

Or with OneClickInstall https://software.opensuse.org/download.html?project=server%3Ahttp&package=goaccess

**Comment by hennevogel** [comment]
Well `%configure` and `./configure` are not necessarily the same thing. `%configure` expands to many things (setting CFLAGS, adding more options etc.). See the [build log](https://build.opensuse.org/build/server:http/openSUSE_Tumbleweed/x86_64/goaccess/_log) for details. I've tried to build it without those settings, same result.

So it must be something else. Do you depend on a specific locale set during build or something?

**Comment by hennevogel** [comment]
There are ordinal `º` characters (sometimes followed by control characters) in the resulting HTML. If you remove them, the HTML is fine.

**Comment by allinurl** [comment]
@hennevogel did you build from [development](https://github.com/allinurl/goaccess#build-from-github-development)? From the previous post, it seems to be an issue with SUSE build.

**Comment by hennevogel** [comment]
Nope I did not, used 1.3. Trying to narrow down the issue with the SUSE build (I am a SUSE developer).

**Comment by hennevogel** [comment]
Same result with 8af30fc

**Comment by allinurl** [comment]
From your post above, it seems like it may be related to the embedded fontawesome?

**Comment by hennevogel** [comment]
The characters occur in the HTML always at the end of the things you concatenate. Maybe this process adds those characters?

**Comment by allinurl** [comment]
This seems isolated to SUSE as I don't see these chars under arch or debian. I wonder if it has something to do with the compiler. It could be the bin2c. Are you able to reproduce this on a different version of suse?

**Comment by hennevogel** [comment]
Yeah that is my theory now. Probably `fpic` or something is missing when compiling binc as it's not using CFLAGS etc.. 

I was able to reproduce this on many different versions, yes.

**Comment by coolo** [comment]
Please update to https://github.com/gwilymk/bin2c/issues/3

**Comment by hennevogel** [comment]
ARGH, I've looked at that repo, but apparently not too close! Yes this fixes it for me: 

```patch
diff -Nur goaccess-1.3.orig/src/bin2c.c goaccess-1.3/src/bin2c.c
--- goaccess-1.3.orig/src/bin2c.c	2018-11-23 03:00:08.000000000 +0100
+++ goaccess-1.3/src/bin2c.c	2019-08-26 14:18:22.550783529 +0200
@@ -9,10 +9,10 @@
  * I have decided not to change the licence.
  */
 
+#include <assert.h>
 #include <stdio.h>
-#include <string.h>
 #include <stdlib.h>
-#include <assert.h>
+#include <string.h>
 
 #ifdef USE_BZ2
 #include <bzlib.h>
@@ -46,7 +46,6 @@
   fseek (f_input, 0, SEEK_END);
   file_size = ftell (f_input);
   fseek (f_input, 0, SEEK_SET);
-  file_size++;
 
   if ((buf = malloc (file_size)) == NULL) {
     fprintf (stderr, "Unable to malloc bin2c.c buffer\n");
@@ -59,7 +58,7 @@
 
 #ifdef USE_BZ2
   // allocate for bz2.
-  bz2_size = ((file_size) * 1.01) + 600;        // as per the documentation
+  bz2_size = (file_size + file_size / 100 + 1) + 600; // as per the documentation
 
   if ((bz2_buf = malloc (bz2_size)) == NULL) {
     fprintf (stderr, "Unable to malloc bin2c.c buffer\n");

```

**Comment by coolo** [comment]
Spot the glasses on my profile pic? Perhaps it's time dude... :)

**Comment by jubalh** [comment]
@xorock: @hennevogel submitted the bin2c patch to the openSUSE [package](https://build.opensuse.org/package/show/server:http/goaccess). So if you use the package from `server:http` this should be fixed for you now.

> BTW. Could You mention here https://goaccess.io/download#distro there is also Suse build available?

That would be cool. openSUSE has goaccess packaged since 2010 ;-)

**Comment by xorock** [comment]
@jubalh I can confirm that it now works on OpenSuse :) You are great guys.
