### ISSUE TITLE
[ERROR] Invalid filename extension used, must be any of .csv, .json, or .html

### ISSUE THREAD

**Issue by CristyDry** [allinurl/goaccess#1417]
GoAccess - version 1.3 - Apr  3 2019 10:24:48

time-format %T
date-format %d/%b/%Y
log-format %h - %^ [%d:%t %^] requesthost:"%v"; "%r" requesttime:"%T"; %s %b "%R" - %^"%u"

log-file /www/a.log
output /www/report.html
real-time-html true

sudo=> goaccess -config-file=/usr/local/etc/goaccess/goaccess.conf
[ERROR] Invalid filename extension used, must be any of .csv, .json, or .html

sudo=> goaccess -f /www/a.log -c -a>/www/report.html
GoAccess - version 1.3 - Apr  3 2019 10:24:48
Config file: No config file used

Fatal error has occurred
Error occurred at: src/parser.c - parse_log - 2764
No time format was found on your conf file.

**Comment by allinurl** [comment]
Can you please build from [**development**](https://github.com/allinurl/goaccess#build-from-github-development) and see if this issue has already been fixed? Thanks

**Comment by CristyDry** [comment]
Thank you. I'm using yum install 1.2 now. I'll try your advice.
