### ISSUE TITLE
Confusing references to both hide-referer and ignore-referer-report in changelog

### ISSUE THREAD

**Issue by palant** [allinurl/goaccess#1419]
https://github.com/allinurl/goaccess/blob/master/ChangeLog currently has the following entries for GoAccess 1.3:

>   - Added --hide-referer command line option to hide referers from report.
>   - Added --ignore-referer-report command line option to hide referers from
>     output.

This had me confused. Turns out, both entries mean the same feature which was checked in as `ignore-referer-report` initially and renamed into `hide-referer` later in the development cycle. Maybe remove that `ignore-referer-report` line so nobody else has to research this?

**Comment by allinurl** [comment]
Thanks for the heads up on this. Your PR has addressed this issue.
