### ISSUE TITLE
Docker installation error

### ISSUE THREAD

**Issue by gogoqixin** [allinurl/goaccess#1423]
Config file: /srv/data/goaccess.conf
Fatal error has occurred
Error occurred at: src/parser.c - read_log - 2728

**Comment by mbejda** [comment]
This may be helpful. 
<img width="919" alt="Screen Shot 2019-04-10 at 8 19 34 AM" src="https://user-images.githubusercontent.com/5429780/55877989-78ecf680-5b69-11e9-9c63-6254cdf7d5b6.png">

**Comment by gogoqixin** [comment]
Execute goaccess access.log after entering the container
The error was reported as follows:

Fatal error has occurred
Error occurred at: src/parser.c - read_log - 2728
Unable to open the specified log file. No such file or directory


Copy the config/goaccess. Conf
And it's increased
The log - format COMBINED
The log file/SRV/logs/access. Log
The output/SRV/report/index. HTML
True real - time - HTML

**Comment by allinurl** [comment]
@gogoqixin are you still getting this error?
