### ISSUE TITLE
syncing logs from elb - live report

### ISSUE THREAD

**Issue by kenzoawa** [allinurl/goaccess#1424]
Hey guys, i just tried GoAccess and it works like a charm once you get to know it.

It's not a issue but more of a logical question.

I am successful in parsing the s3/elb logs that are stored there with s3cmd sync command to EC2. 
What i am trying to do is having that sync from s3 to GoAccess live - incrementally because sync works that way, only new logs are shipped and i want those new ones added to the report, not all of them.

If i put the command for report.html it parses the whole folder, not just the new ones that were copied. 
Here is the command : 

`find /tmp/s3/ -name "*.log" -exec cat {} \; | goaccess -a --log-format=AWSELB -p /usr/local/etc/goaccess/goaccess.conf -o /var/www/html/report.html --real-time-html`

Is there any possibility for goaccess to only parse the new logs in real time because my bucket is dozens of gigabytes ? I tried something with crontab but unsuccessful. 
Thank you guys.

**Comment by allinurl** [comment]
You could use find and see the latest mod files:

> find . -cmin +<time>
> find . -cmin -<time>
> find . -cmin  <time>

For example, the files with last edition in a maximum of 5 minutes, are given by:

    find  /tmp/s3/ -cmin -5 -name "*.log" -exec cat {} \; | goaccess -a --log-format=AWSELB -p /usr/local/etc/goaccess/goaccess.conf -o /var/www/html/report.html --real-time-html

**Comment by kenzoawa** [comment]
Thank you very much allinurl! 
You are a saver. 

I will try the command and give feedback here.

**Comment by kenzoawa** [comment]
Works like a charm, thanks allinurl!
