### ISSUE TITLE
Token '2019-01-09' doesn't match specifier '%h'

### ISSUE THREAD

**Issue by manues50** [allinurl/goaccess#1427]
I am trying to parse the media server logs but I am getting some error

Parsed 1 linesproducing the following errors:

Token '2019-01-09' doesn't match specifier '%h'

Format Errors - Verify your log/date/time format

I tried with most of the log formations all are getting different errors

**Comment by manues50** [comment]
Following is my log sample

2019-04-16 12:29:11.431 200 0 299 /ClanHD/tracks-v1a1/mono.m3u8 138084009cec21a7bd52b940a550413e6f4483ad 183.83.174.147

**Comment by allinurl** [comment]
Please describe your log format. Thanks

**Comment by manues50** [comment]
These logs are from a media server named flussonic.

Sample logs for one channels.

2019-05-03 09:10:43.878 200 4 935488 /CHANNEL1/tracks-v3a1/2019/05/03/09/10/32-06000.ts 44ecbde929494680a0ba31ef000e704bcdc628d2 76.18.17.234

Here

200 - http code 
4 - backend runtime in ms 
935488 - content size in bytes 
84539db6d480d7d656259cd2fda7977e4a613946  - client session_id

**Comment by allinurl** [comment]
This should do it:

    goaccess access.log --log-format='%d %t.%^ %s %L %b %U %^ %h' --date-format=%Y-%m-%d --time-format=%T --ignore-panel=OS --ignore-panel=BROWSERS --http-method=no --http-protocol=no

**Comment by manues50** [comment]
This information was helpful 
Thank  You

**Comment by allinurl** [comment]
Great. Closing this, feel free to reopen it if needed.

**Comment by Hosting-Server-Team** [comment]
@allinurl - I have below log format in Apache and while executing the goaccess command getting this error.

**Apache Log Format**
LogFormat "%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" combined

**GoAccess Command**
goaccess  /var/log/domain.com_access_log --log-format=combined -a -o /home/domain/report.html

goaccess /var/log/virtualmin/demo.brainvire.com_access_log --log-format='"%h" %^[%d:%t %^] "%r" %s %b "%R" "%u"' --date-format=%d/%b/%Y --time-format=%T --no-global-config -a -o /home/demo/public_html/report.html

**Error**
Parsed 10 lines producing the following errors:
Token '842 63.143.42.243 - - [30/Aug/2019:15:04:33 +0530]' doesn't match specifier '%h'
Token '635 63.143.42.243 - - [30/Aug/2019:15:09:34 +0530]' doesn't match specifier '%h'
Format Errors - Verify your log/date/time format

**Comment by allinurl** [comment]
@Hosting-Server-Team can you please post a few lines from your access log? Thanks

**Comment by SteveSafaron** [comment]
On all presets get error
Have this format access log:
site.ru 172.69.69.53 - - [26/Sep/2019:00:20:53 +0300] "GET /product/test "-" "Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.96 Mobile Safari/537.36 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)" 0

**Comment by pangxudong** [comment]
@allinurl - hi，I have below log format in nginx.

**nginx.conf**
`log_format  main 'v1{|]$remote_addr:$remote_port{|]$http_x_forwarded_for{|]$upstream_addr{|]$time_iso8601{|]$request_method{|]$server_name{|]$uri{|]$args{|]$status{|]$http_referer{|]$body_bytes_sent{|]$request_time{|]$upstream_response_time{|]$http_user_agent{|]$sent_http_location{|]$http_cookie{|]$http_expect';
`

**log sample** 
`v1{|]39.156.69.79:50363{|]-{|]unix:/tmp/php-cgi.sock{|]2019-08-27T10:29:09+08:00{|]GET{|]example.com{|]/index.php{|]-{|]500{|]-{|]5{|]0.000{|]0.000{|]Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36{|]-{|]-{|]-
v1{|]39.156.69.79:50375{|]-{|]unix:/tmp/php-cgi.sock{|]2019-08-27T10:30:23+08:00{|]GET{|]example.com{|]/index.php{|]-{|]500{|]-{|]194869{|]0.095{|]0.094{|]Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36{|]-{|]-{|]-
v1{|]39.156.69.79:50375{|]-{|]-{|]2019-08-27T10:30:23+08:00{|]GET{|]example.com{|]/favicon.ico{|]-{|]200{|]https://example.com/{|]0{|]0.000{|]-{|]Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36{|]-{|]-{|]-
v1{|]39.156.69.79:50375{|]-{|]unix:/tmp/php-cgi.sock{|]2019-08-27T10:30:37+08:00{|]GET{|]example.com{|]/index.php{|]-{|]500{|]-{|]194873{|]0.095{|]0.094{|]Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36{|]-{|]-{|]-
v1{|]39.156.69.79:50375{|]-{|]-{|]2019-08-27T10:30:37+08:00{|]GET{|]example.com{|]/favicon.ico{|]-{|]200{|]https://example.com/{|]0{|]0.000{|]-{|]Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36{|]-{|]-{|]-
v1{|]39.156.69.79:50375{|]-{|]unix:/tmp/php-cgi.sock{|]2019-08-27T10:30:55+08:00{|]GET{|]example.com{|]/index.php{|]-{|]500{|]-{|]194847{|]0.094{|]0.093{|]Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36{|]-{|]-{|]-
v1{|]39.156.69.79:50375{|]-{|]-{|]2019-08-27T10:30:56+08:00{|]GET{|]example.com{|]/favicon.ico{|]-{|]200{|]https://example.com/{|]0{|]0.000{|]-{|]Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36{|]-{|]-{|]-`
