### ISSUE TITLE
How to enable geoip when installing with the package manager?

### ISSUE THREAD

**Issue by nikosvaggalis** [allinurl/goaccess#1428]
I'm on Ubuntu and install with apt-get geoaccess.
how can I enable geoip? I see that all tutorials require to build and configure from source to enable it.Is that so?

**Comment by allinurl** [comment]
If you used the debian repo, yes, you would need to build from source or use the [official](https://github.com/allinurl/goaccess#official-goaccess-debian--ubuntu-repository) deb repo.o.
