### ISSUE TITLE
Custom Log format GoAccess Nginx

### ISSUE THREAD

**Issue by MJC2** [allinurl/goaccess#1429]
Hi 
My name is MJ 

I have problems with the format I add it manually or in the conf file and I do not consider the date or time.

What can you suggest?

    [root@ip~]# /tmp/goaccess-1.3/goaccess -f /tmp/LOGS/LT/error.log-20190411 --log-format=%d %t %^, %^, client: %h, server: %^, request: "%r", host: "%v", referrer: "%R", %^, host "%v"

Parsed 1 linesproducing the following errors:

    Token '2019/04/10 03:40:09 [error] 32450#0: *1731 FastCGI sent in stderr: "PHP message: PHP Warning:  file_get_contents(/srv/www/xxxx/wp-content/json/portadas/portada_link-externo.json): failed to open stream: No such file or directory in /srv/www/xxxx/wp-content/themes/gnuble/functions.php on line 1964' doesn't match specifier '%d'

Format Errors - Verify your log/date/time format

**Comment by allinurl** [comment]
Looks like you are trying to parse an error log instead of an access log. You will need a different tool for that.

**Comment by allinurl** [comment]
Closing this, feel free to reopen it if needed.
