### ISSUE TITLE
real-time-html appeared not to be working but actually was. (pitfall)

### ISSUE THREAD

**Issue by iWoodsman** [allinurl/goaccess#1431]
I spent a lot of time trying to figure out why goaccess was not updating the html page, including all the fixes I found in these Issues. It turned out that the real-time updates HAD been occurring all along, but my site traffic was very low so the incrementing counters were subtle. The main problem was that I kept watching for the "Last Updated" field on the HTML page to change: it does not, yet real-time-updates may be happening. My guess is that the file is written only once, with all further data streaming over the WS. It might be good to de-emphasize or allow the hiding of the "Last Updated" field to avoid confusion. I'm going to have to warn my CTO about this more than once :)

**Comment by allinurl** [comment]
Thanks for reporting this. Glad you got it to work. #1356 will address this issue in the upcoming version. Closing this as it's part of #1356.
