### ISSUE TITLE
HTML report /favicon.ico 404

### ISSUE THREAD

**Issue by dragonandy** [allinurl/goaccess#1432]
You may notice that every time you open up the html report generated by the goaccess in the browser, your browser will request a favicon.ico file from the root uri. 
The [demo site](https://rt.goaccess.io/?20181123091935) also have this issue.  
When the `image/x-icon` is not set in the html file, the browser will try to request a favicon.ico file from "https://rt.goaccess.io/favicon.ico" which may cause a 404.And it takes up time. 
Many of us won't put the favicon.ico in "/", instead it will be put somewhere else, the path will be set by the html file like
```html
<link rel="icon" href="somewhere/favicon.ico" type="image/x-icon" /> 
```
for goaccess maybe a better solution is to base64 the favicon.ico file and embed it into the html report file, the code may looks like this:
```html
<link href="data:image/x-icon;base64,AAABAAEAEBAQAAEABAAoAQAAFgAAACgAAAAQAAAAIAAAAAEABAAAAAAAgAAAAAAAAAAAAAAAEAAA
AAAAAADGxsYAWFhYABwcHABfAP8A/9dfAADXrwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAIiIiIiIiIiIjMlUkQgAiIiIiIiIiIiIiIzJVJEIAAAIiIiIiIiIiIiMyVSRC
AAIiIiIiIiIiIiIRERERERERERERERERERERIiIiIiIiIiIgACVVUiIiIiIiIiIiIiIiIAAlVVIi
IiIiIiIiIiIiIhEREREREREREREREREREREAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" rel="icon" type="image/x-icon" />
```

**Comment by allinurl** [comment]
That's awesome. Thanks for sharing this. Would you be able to submit a PR for this?

**Comment by dragonandy** [comment]
done. the code worked on my mac.
