### ISSUE TITLE
Docker install - Can't read multiple logs

### ISSUE THREAD

**Issue by mattgphoto** [allinurl/goaccess#1433]
Hey there @allinurl I'm just trying to tune up goaccess as much as possible before I tackle trying to deal with websockets in nginx reverse proxy config (certbot container)...

I've come across a few hitches so far when making edits to the config file:

1. In my goaccess.conf, I have this for instance:
```
######################################
# File Options
######################################

# Specify the path to the input log file. If set, it will take
# priority over -f from the command line.
#
log-file /srv/logs/access.log
```
That works fine! However if I do something like this:
`
log-file /srv/logs/access.log /srv/logs/error.log
`
Then I get this in the logs for the container when I restart:
```
Parsing... [0] [0/s]
GoAccess - version 1.3 - Jan 20 2019 11:05:15
Config file: /srv/data/goaccess.conf

Fatal error has occurred
Error occurred at: src/parser.c - read_log - 2728
Unable to open the specified log file. No such file or directory

Parsing... [0] [0/s]
GoAccess - version 1.3 - Jan 20 2019 11:05:15
Config file: /srv/data/goaccess.conf

Fatal error has occurred
Error occurred at: src/parser.c - read_log - 2728
Unable to open the specified log file. No such file or directory
```
I've also tried:
```
log-file /srv/logs/access.log
log-file /srv/logs/error.log
```
With the same results.

~2. When I enable daemonize in the config file:~
```
# Run GoAccess as daemon (if --real-time-html enabled).
#
daemonize true

# The port to which the connection is being attempted to connect.
# By default GoAccess' WebSocket server listens on port 7890
# See man page or http://gwsocket.io for details.
#
port 7900

# Write the PID to a file when used along the daemonize option.
#
pid-file /var/run/goaccess.pid

# Enable real-time HTML output.
#
real-time-html true
```
~I get this in the log:~
```
Closing GoAccess...
Stopping WebSocket server...
Daemonized GoAccess: 7
Daemonized GoAccess: 8
Daemonized GoAccess: 7
Daemonized GoAccess: 7
Daemonized GoAccess: 7
Daemonized GoAccess: 7
Daemonized GoAccess: 7
Daemonized GoAccess: 8
Daemonized GoAccess: 7
```
~And the container never starts. Is this typical?~

Any info would be extremely helpful. :-)

**Comment by mattgphoto** [comment]
Figured out one of the issues. You don't daemonize something that's in a docker container. :-) Might want to add a note in the example config with something along the lines of:
```
# Run GoAccess as daemon (if --real-time-html enabled). If you are using docker, ignore this flag.
#
#daemonize true
```
Still need help with the first issue.

**Comment by mattgphoto** [comment]
Figured it out myself. Now it's just a matter of figuring out multiple log formats within the .conf file.

**Comment by allinurl** [comment]
At the moment it can only parse one log format. #213 will address the ability to have multiple log formats
