### ISSUE TITLE
armv6 support

### ISSUE THREAD

**Issue by Fieel** [allinurl/goaccess#1434]
Hello.

I've been using Goaccess for a while now, I always had problems of some kind but always wanted to properly install it once and for all, on my old raspberrypi2b running an armv6l architecture.

Unfortunately, I had no luck, both browsing this repo issues or with google.

What's the correct, best way to install and run Goaccess on my raspberry pi 2b running an armv6l architecture? I want a real-time html page running on my web server (nginx).

Things i tried:

- download and installed Goaccess-1.2.tar.gz directly from source (worked, couldn't automate it though, script would work half of the times etc.) ([source](https://goaccess.io/download))

This is the script i used to start it:
`sudo goaccess -f /var/log/nginx/access.log -o /var/www/domain.name/goaccess/report.html --real-time-html --log-format=COMBINED --ws-url=wss://domain.name:7890 --ssl-cert=/etc/letsencrypt/live/domain.name-0001/fullchain.pem --ssl-key=/etc/letsencrypt/live/domain.name-0001/privkey.pem --ignore-crawlers`

This is the system service I created to automate it ([source](https://github.com/allinurl/goaccess/issues/684)):
```bash
[Unit]
Description=goaccess
After=network.target

[Service]
Type=simple
Restart=always
WorkingDirectory=/home/fieel/scripts
ExecStart=/home/fieel/scripts/goaccess_start.sh
#ExecStop=/bin/kill -9 ${MAINPID}
#PrivateTmp=false

[Install]
WantedBy=multi-user.target
```

Failed service execution:

```bash
fieel@raspberrypi2b:~ $ systemctl status goaccess.service
● goaccess.service - goaccess
   Loaded: loaded (/etc/systemd/system/goaccess.service; bad; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sun 2019-04-21 22:10:35 CEST; 1 day 14h ago
  Process: 405 ExecStart=/home/fieel/scripts/goaccess_start.sh (code=exited, status=203/EXEC)
 Main PID: 405 (code=exited, status=203/EXEC)
```

When i run the script (or the system runs it as a service, or cronjob executes it) the html page won't show real time data. Sometimes no data at all.

- tried installing docker (so i could maybe containerize Goaccess). Turns out docker has problems with this architecture, but I'd love to NOT use it anyways if possible.

**Comment by allinurl** [comment]
Have you tried running goaccess simply as:

    goaccess -f /var/log/nginx/access.log -o /var/www/domain.name/goaccess/report.html --real-time-html --log-format=COMBINED --ws-url=wss://domain.name:7890 --ssl-cert=/etc/letsencrypt/live/domain.name-0001/fullchain.pem --ssl-key=/etc/letsencrypt/live/domain.name-0001/privkey.pem --ignore-crawlers

without the systemd script? does it work? if it doesn't what output are you getting through the browser's console? Thanks

**Comment by Fieel** [comment]
@allinurl yeah it worked.

2 years ago, when I first tried using goaccess, I had lots of problems and barely managed to make it work. Soon after I opened this issue the installation completed flawlessly and everything works :).
