### ISSUE TITLE
SSL problem

### ISSUE THREAD

**Issue by kenzoawa** [allinurl/goaccess#1435]
Hi guys,

I have installed goaccess but i want to use it with SSL.

So far i have installed with --with-openssl and i have this input line 

`find /home/ubuntu/s3/ -cmin -300 -name "*.log" -exec cat {} \; | goaccess -a - --log-format=AWSELB -p /usr/local/etc/goaccess/goaccess.conf -o /var/www/html/index.html --ssl-cert=/home/ubuntu/s3/server.crt --ssl-key=/home/ubuntu/s3/server.key --ws-url=wss://publicipoftheserver:7890`

Then when i visit my public ip i don't have ssl, even with :7890 and with https:// i only have port 80, and goaccess doesn't show any errors while parsing. Tried to use debug mode but no luck there.
Only working option is without ssl, port 80, is there anything else i need to look for ?
I am using Ubuntu 16.04.

Thanks guys.

**Comment by kenzoawa** [comment]
So basically you are saying that i just insert the SSL certs and keys to the apache that is running local and skip the SSL flags .. etc right ?

**Comment by iWoodsman** [comment]
Correct. The report page it’s self is a plain old static page served by Apache, and if you have configured Apache for SSL, then the report page will be delivered as such. You only need to explicitly tell goaccess about SSL and certificates if you want the real time HTML data that is transferred between the goaccess websocket and the end-user’s browser to be encrypted. That’s when you specify the cert and the key to goaccess, and if necessary the ws server and port. The latter will default to your apache host, and port 7890.
Strangely, I found that using the ws=wss directive to specify the server and port caused the real time HTML to not work, whereas not specifying that and letting the defaults be used did work, even though what I was specifying were in fact the defaults. 


—

**Comment by kenzoawa** [comment]
Hey @iWoodsman thanks for the advice, much appreciated! I was successful.   

I have installed the SSL on the apache and works like a charm if you are not using --real-time-html.

If anyone stumbles across that problem - just use ssl on the apache without real time report.
