### ISSUE TITLE
AWSELB log format doesn't work

### ISSUE THREAD

**Issue by mrchief** [allinurl/goaccess#1436]
goaccess currently has a common name for Amazon ELB logs `AWSELB       | Amazon Elastic Load Balancing`

ELB logs are slightly [different](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-access-logs.html#access-log-entry-format) and this format works:

```
log-format %^ %dT%t.%^ %v %h:%^ %^ %T %^ %^ %s %^ %b %^ "%r" "%u" %^
date-format %Y-%m-%d 
time-format %T
```

Can this be updated please?

**Comment by kenzoawa** [comment]
Hi @mrchief 

AWS ELB logs work fine on my side, which version of goaccess you have ? 

I use `--log-format=AWSELB -p /usr/local/etc/goaccess/goaccess.conf`

**Comment by mrchief** [comment]
I'm on 1.3

![image](https://user-images.githubusercontent.com/781818/56749612-0fb3d880-6750-11e9-8778-1f3114e981c8.png)

The [default](https://github.com/allinurl/goaccess/blob/master/config/goaccess.conf#L88) format doesn't account for `type` it seems and the error message confirms that. Am I missing something here?

**Comment by agutierrezrodriguez** [comment]
Same problem here with the last version.

**Comment by allinurl** [comment]
Awesome, thanks for confirming this. I have [updated](https://github.com/allinurl/goaccess/commit/b1547e5614dcc1784469f51cd5964c95bb78cdc3) the format upstream. Please feel free to build from [**development**](https://github.com/allinurl/goaccess#build-from-github-development) and let me know if that works on your end.

Closing this.
