### ISSUE TITLE
log-format | nginx | doesn't match specifier ..

### ISSUE THREAD

**Issue by apelsinkabl** [allinurl/goaccess#1440]
Could not configure log-format. Can you help me? Please.

    GoAccess - 1.2.

Now I have nginx log like this:

    Apr  5 07:29:28 vh1 nginx: domain.com 123.123.123.1 - - [05/Apr/2019:09:39:14 +0300] "GET / HTTP/1.1" 200 20933 "-" "Mozilla/5.0 (compatible; YandexMetrika/2.0; +http://domain.com/bots dabs01)" "3.80" "-" "127.0.0.1:8081"

What I should do? Cut/sed/awk to make "classic" format and then use some default config or?..

If you have some detailed examples how to create this configuration line, please send me the information.

**Comment by DragonHacker1** [comment]
Might need same help what specificed up, but mine are a bit more customized. 
`[28/Apr/2019:09:16:12 +0000] - 200 200 - GET https web.***.**** "/" [Client 188.13*.***.***] [Length 139] [Gzip 1.23] [Sent-to 1**.2**.4*.*1] "Mozilla/5.0 (X11; Linux x86_64; rv:66.0) Gecko/20100101 Firefox/66.0" "http://a**.**:81/nginx/proxy"`
Is a bit diferent because i using only nginx proxy, logs are modified alot, thank you.

**Comment by allinurl** [comment]
Can  you please both describe the fields on your log format. Thanks.

**Comment by DragonHacker1** [comment]
Mine i used ** because i actually web.** - domain, also client 188.13**.***.*** - ip of user logging the browser, and last http://a**.**:81/nginx/proxy should don't mention because actually where did redirected, like visiting into that domain will automatically redirect other specific, so 
`[28/Apr/2019:09:16:12 +0000] - 200 200 - GET https DOMAIN "/" [Client IP] [Length 139] [Gzip 1.23] [Sent-to SERVERIP] "Mozilla/5.0 (X11; Linux x86_64; rv:66.0) Gecko/20100101 Firefox/66.0" `

DOMAIN - domain where will go (accesed)
IP (client ip, a user/browser did accesed)
SERVERIP - informations sent back into server, if don't understand how, later if need will send you a full access.log in private way.

**Comment by apelsinkabl** [comment]
> Can you please both describe the fields on your log format. Thanks.

I need to process only the default log. 
Can I ignore some columns? What do I need to use? or should format my log to default and use default log-format for goaccess?

**Comment by antongiacomo** [comment]
Same here, thank you for your work

**Comment by allinurl** [comment]
@apelsinkabl This should work:

    goaccess access.log --log-format='%^:%^:%^: %^ %h %^[%d:%t %^] "%r" %s %b "%R" "%u" "%T" %^' --date-format=%d/%b/%Y --time-format=%T

**Comment by antongiacomo** [comment]
Hi,Token '+0000]' doesn't match specifier '%h'

**Comment by antongiacomo** [comment]
Hi,
The error now is:


Token '+0000]' doesn't match specifier '%h'
Token '+0000]' doesn't match specifier '%h'
Token '+0000]' doesn't match specifier '%h'
Token '+0000]' doesn't match specifier '%h'
Token '+0000]' doesn't match specifier '%h'
Token '+0000]' doesn't match specifier '%h'
Token '+0000]' doesn't match specifier '%h'
Token '+0000]' doesn't match specifier '%h'
Token '+0000]' doesn't match specifier '%h'
Token '+0000]' doesn't match specifier '%h'

**Comment by allinurl** [comment]
@antongiacomo Please describe the field from your log.

**Comment by antongiacomo** [comment]
@allinurl 
Exactly the same of @DragonHacker1 ones

**Comment by allinurl** [comment]
@antongiacomo @DragonHacker1 

    goaccess access.log --log-format='[%d:%t %^] %^ %s %^ %^ %m %^ %v "%U" [%^ %h] [%^ %b] %^"%u" "%R"' --date-format=%d/%b/%Y --time-format=%T --http-protocol=no

**Comment by antongiacomo** [comment]
Worked like a charm thanks!

**Comment by DragonHacker1** [comment]
Thank you, is working like a charm :)

**Comment by dodoanji** [comment]
Hi allinurl ,

I am trying following syntax.

goaccess www.xyz.com.access.log.1 --log-format='%^: "%dT%t+%^",%^: "%h",%^: "%e",%^: "%b",%^: "%T",%^: "%s",%: "%r",%^:%^: "%R",%^: "%u",%^' --date-format=%Y-%m-%d --time-format=%T -o /var/www/html/report.html

getting following message for id. 

Token 'GET /abc/what-is-myname-2193443?pfrom=home-topstories HTTP/1.1' doesn't match specifier '%s'
Token 'GET /cricket/view/xyz2193584/site=classic/?device=androidv2&siteid=news&showads=no&mutestart=1&hideads=0 HTTP/1.1' doesn't match specifier '%s'

--
Ashish

**Comment by allinurl** [comment]
@dodoanji Could you please post a few lines from your access log?

**Comment by dodoanji** [comment]
Thanks for the quick response. Please find the below logs.

{ "time": "2020-03-13T06:25:20+00:00", "remote_addr": "2401:4900:33b5:4802:84bb:1d7f:1af7:5557", "body_bytes_sent": "2355", "request_time": "0.281", "status": "200", "request": "GET /video/embed-player/?site=classic&id=529726&autoplay=0&category=embed&cTitle=1&src=gadgets&skipThumbnailCss=1 HTTP/1.1", "request_method": "GET", "http_referrer": "https://abc.ampproject.org/v/s/abc.ndtv.com/mobiles/news/vivo-funtouch-os-10-rollout-roadmap-nex-3-5g-x27-pro-s5-s1-z5-z5i-z5x-x23-z3-2149989?amp=1&akamai-rum=off&amp_js_v=0.1&usqp=mq331AQFKAGwASA%3D", "http_user_agent": "Mozilla/5.0 (Linux; Android 9; vivo 1920 Build/PKQ1.190626.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.84 Mobile Safari/537.36 VivoBrowser/6.2.0.1" };

{ "time": "2020-03-13T06:25:20+00:00", "remote_addr": "150.109.120.120", "body_bytes_sent": "39342", "request_time": "0.821", "status": "200", "request": "GET /video/business/news/bnp-paribas-evaluates-the-impact-of-boj-intervention-on-yen-247560 HTTP/1.1", "request_method": "GET", "http_referrer": "https://www.abc.com/topic/yen", "http_user_agent": "Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.0; Trident/4.0; GTB5; SLCC1; .NET CLR 2.0.50727; Media Center PC 5.0; .NET CLR 3.0.04506; InfoPath.2" };

**Comment by allinurl** [comment]
@dodoanji This should work:

    goaccess access.log --log-format='%^: "%dT%t+%^",%^: "%h",%^: "%b",%^: "%T",%^: "%s",%^: "%r",%^:%^: "%R",%^: "%u",%^' --date-format=%Y-%m-%d --time-format=%T

**Comment by dodoanji** [comment]
Thanks Allinurl, Have one more query. Logs parsing for 5xx,4xx only showing number of hits, is it possible to show corresponding URL. Tried to find URL in Panel Option settings. But its not available. 



# | Hits | Avg. T.S. | Cum. T.S. | Max. T.S. | Data
-- | -- | -- | -- | -- | --
  |   | 1,105,590Max: 1,050,898Min: 1 | 186.91 ms | 2.39 dMax: 2.37 dMin: 0.00 us | 2.39 dMax: 1.00 mMin: 29.00 ms | 9 Total
  | 1 | 1,050,899 (95.05%) | 194.57 ms | 2.37 d | 38.13 s | 2xx Success
  | 2 | 38,190 (3.45%) | 32.95 ms | 20.97 m | 3.75 s | 3xx Redirection
  | 3 | 15,615 (1.41%) | 54.17 ms | 14.10 m | 4.29 s | 4xx Client Error
  | 4 | 886 (0.08%) | 77.32 ms | 1.14 m | 1.00 m | 5xx Server Error

**Comment by dodoanji** [comment]
Hi Allinurl,

waiting for your reply. Thanks.

**Comment by allinurl** [comment]
@dodoanji #117 will address this. For now you have to preprocess the log. e.g., awk, sed, grep. e.g., 

    #  awk '$9~/500/' access.log | goaccess -

Please take a look at the man page for more [**examples**](https://goaccess.io/man#examples).

**Comment by cmmanoj** [comment]
Hello i get below error while parsing my custom log files as below:
======
Parsed 1 lines producing the following errors:

Token '020-06-05 17' doesn't match specifier '%d'

Format Errors - Verify your log/date/time format
======
Log files are as below:
2020-06-05 17:54:34:019  [TID      25532][INFO    ] Default Logger initialized [casAPIPlatform]^M
2020-06-05 17:54:34:019  [TID      25532][INFO    ] ENTER: Config default values [casAPIPlatform]^M
2020-06-05 17:54:34:019  [TID      25532][INFO    ] EXIT: Config default values [casAPIPlatform]^M
2020-06-05 17:54:34:019  [TID      25532][INFO    ] ENTER: LoadSystemControllers [casAPIPlatform]^M
2020-06-05 17:54:34:019  [TID      25532][INFO    ] EXIT: LoadSystemControllers [casAPIPlatform]^M
