### ISSUE TITLE
Token '25' doesn't match specifier '%d'

### ISSUE THREAD

**Issue by markgraf** [allinurl/goaccess#1441]
Running...
<pre>$ goaccess -p /etc/goaccess/goaccess.conf -f peak.log -a > peak.html</pre>
I get the following error

<pre>Parsed 1 linesproducing the following errors:

Token '25' doesn't match specifier '%d'

Format Errors - Verify your log/date/time format</pre>

Which is weird, because "25" is a valid value of %d (day of month).

/etc/goaccess/goaccess.conf contains:
<pre>
time-format %H:%M:%S
date-format %d/%b/%Y
log-format %h %l %u %^[%d/%b/%Y%^:%H%^:%M%^:%S %z%^] \"%r\" %>s %b \"%Referer}i\" \"%{User-Agent}i\" **%T/%D**
</pre>

Version is 1.3 , installed on Debian stretch from the official repo.

Could goaccess be stumbling over the non-standard log-format?

**Comment by allinurl** [comment]
Please post a few sample lines from your access.log. Thanks.

**Comment by markgraf** [comment]
Sorry for the delay :-( Are 20 lines enough?
<pre>
xxx.xxx.xxx.xxx - - [08/May/2019:11:37:52 +0200] "GET /panorama/polizei-sucht-_huehnerkiller_-30880912.html?_XML=AMP HTTP/1.1" 200 15618 "https://www.swp.de/blaulicht/crailsheim/frauenleiche-in-wohnung-gefunden-lebensgefaehrte-verhaftet-30881568.html?_XML=AMP" "Mozilla/5.0 (Linux; Android 9; SM-G950F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.112 Mobile Safari/537.36" **0/169472**
xxx.xxx.xxx.xxx - - [08/May/2019:11:37:52 +0200] "GET /imgs/07/4/2/8/0/5/7/8/3/tok_762e99b98610658d20d4ff875a109b62/w370_h518_x393_y174_dadc02b5df9cea4e.jpeg HTTP/1.1" 304 - "https://www.swp.de/suedwesten/staedte/heidenheim/" "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko" **0/584**
xxx.xxx.xxx.xxx - - [08/May/2019:11:37:52 +0200] "GET /imgs/07/3/2/8/7/0/3/4/0/tok_25c8b878c2e9ea92f396660ebcc84843/w800_h450_x500_y750_gem__se-b78bdc17cd4ad07f.jpeg HTTP/1.1" 200 33690 "https://www.swp.de/suedwesten/staedte/bietigheim-bissingen/" "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko" **0/811**
xxx.xxx.xxx.xxx - - [08/May/2019:11:37:52 +0200] "GET /imgs/07/4/2/8/0/2/7/3/4/tok_006c7419910d418e96f701b6d4f97a19/w400_h225_x558_y259_cecca29521ee10ee.jpeg HTTP/1.1" 304 - "https://www.swp.de/suedwesten/staedte/heidenheim/" "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko" **0/561**
xxx.xxx.xxx.xxx - - [08/May/2019:11:37:52 +0200] "GET /includes/ajax_treenodeid_controller_16257247.php?treenode_id=20295&count=3 HTTP/1.1" 200 5741 "https://www.swp.de/sport/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0" **0/4296**
xxx.xxx.xxx.xxx - - [08/May/2019:11:37:52 +0200] "GET /imgs/07/1/6/3/7/2/8/2/1/tok_e0f0149eba5bcd261ba8df2392a08020/w575_h323_x750_y422_3f2a24a1eb313aac.jpeg HTTP/1.1" 304 - "-" "Googlebot-Image/1.0" **0/773**
xxx.xxx.xxx.xxx - - [08/May/2019:11:37:52 +0200] "GET /imgs/07/3/1/9/4/7/9/3/6/tok_e9e7ecd258792924d309a24e5c1d93b8/w800_h450_x750_y382_boe_ganerbenfest8_mk-6a6be2c4bd45bea4.jpeg HTTP/1.1" 200 213062 "https://www.swp.de/suedwesten/staedte/bietigheim-bissingen/" "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko" **0/1331**
xxx.xxx.xxx.xxx - - [08/May/2019:11:37:52 +0200] "GET /imgs/07/4/2/7/9/5/6/4/4/tok_172bddb378150894a6d7d3808c9ab3fb/w400_h225_x501_y348_f74858cda0f36f56.jpeg HTTP/1.1" 200 14751 "https://www.swp.de/suedwesten/staedte/heidenheim/" "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko" **0/627**
xxx.xxx.xxx.xxx - - [08/May/2019:11:37:52 +0200] "GET /imgs/07/4/2/7/9/9/9/6/0/tok_57a295b2e0280871756e149ca4711266/w400_h225_x292_y150_1243d243fd1a5785.jpeg HTTP/1.1" 304 - "https://www.swp.de/suedwesten/staedte/heidenheim/" "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko" **0/516**
xxx.xxx.xxx.xxx - - [08/May/2019:11:37:52 +0200] "GET /imgs/07/4/2/7/5/1/4/4/0/tok_630bb1d612d16f4fd703107713fc02b5/w400_h225_x323_y247_c30211efd4836a4e.jpeg HTTP/1.1" 304 - "https://www.swp.de/suedwesten/staedte/heidenheim/" "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko" **0/499**
xxx.xxx.xxx.xxx - - [08/May/2019:11:37:52 +0200] "GET /imgs/07/4/2/6/9/6/6/0/6/tok_0af368fc950f435043ec412d718c4fed/w400_h225_x929_y246_eea9d2dcc122ec67.jpeg HTTP/1.1" 304 - "https://www.swp.de/suedwesten/staedte/heidenheim/" "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko" **0/537**
xxx.xxx.xxx.xxx - - [08/May/2019:11:37:52 +0200] "GET /imgs/07/4/2/8/0/4/9/4/0/tok_a84f716343818e18f1f7d6716575681b/w400_h225_x400_y255_c8be00720140a454.jpeg HTTP/1.1" 304 - "https://www.swp.de/suedwesten/staedte/heidenheim/" "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko" **0/478**
xxx.xxx.xxx.xxx - - [08/May/2019:11:37:53 +0200] "GET /imgs/07/3/1/8/2/3/2/1/6/tok_a8f8997e8d371b237fa1523d74042482/w800_h450_x750_y369_lb_roncalli3_mk-78314252c84ef28f.jpeg HTTP/1.1" 200 116681 "https://www.swp.de/suedwesten/staedte/bietigheim-bissingen/" "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko" **0/1113**
xxx.xxx.xxx.xxx - - [08/May/2019:11:37:53 +0200] "GET /imgs/07/4/2/8/0/4/7/9/6/tok_ec19dd612a8e5e4a80be403281ee3a75/w400_h225_x750_y543_81f004dbc6ee7d3b.jpeg HTTP/1.1" 304 - "https://www.swp.de/suedwesten/staedte/heidenheim/" "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko" **0/513**
xxx.xxx.xxx.xxx - - [08/May/2019:11:37:52 +0200] "GET /suedwesten/staedte/ulm/ HTTP/1.1" 200 26042 "https://www.google.com/" "Mozilla/5.0 (Linux; Android 7.0; F3111) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.136 Mobile Safari/537.36" **0/82136**
xxx.xxx.xxx.xxx - - [08/May/2019:11:37:53 +0200] "GET /imgs/07/4/2/7/5/6/5/2/6/tok_de9459c7f2a382a515a7cee03da6c449/w400_h225_x635_y336_cde840ec784f95b0.jpeg HTTP/1.1" 304 - "https://www.swp.de/suedwesten/staedte/heidenheim/" "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko" **0/417**
xxx.xxx.xxx.xxx - - [08/May/2019:11:37:53 +0200] "GET /js/main.min.js?ts=20190415173000 HTTP/1.1" 200 83030 "https://www.swp.de/suedwesten/staedte/bietigheim-bissingen/" "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko" **0/24676**
xxx.xxx.xxx.xxx - - [08/May/2019:11:37:53 +0200] "GET /imgs/07/4/2/8/0/9/0/4/7/tok_bbb29eee4234057e7d0cd9e2a456475a/w400_h225_x400_y220_cc8e75fc0ee07fe8.jpeg HTTP/1.1" 304 - "https://www.swp.de/suedwesten/staedte/heidenheim/" "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko" **0/632**
xxx.xxx.xxx.xxx - - [08/May/2019:11:37:53 +0200] "GET /imgs/07/4/2/8/1/1/5/1/1/tok_33634983b9f5dc907a6a6700ebd07317/w370_h518_x400_y276_0a1ea7061f5fb6e5.jpeg HTTP/1.1" 200 30028 "https://www.swp.de/suedwesten/staedte/heidenheim/" "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko" **0/692**
xxx.xxx.xxx.xxx - - [08/May/2019:11:37:53 +0200] "GET /imgs/07/4/2/8/0/4/9/5/0/tok_c4cae22a7b56ad0344895036855f36e8/w370_h518_x400_y161_a0d1235b049df6e2.jpeg HTTP/1.1" 200 28982 "https://www.swp.de/suedwesten/staedte/heidenheim/" "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko" **0/739**
</pre>

**Comment by allinurl** [comment]
This should do it:

    goaccess access.log --log-format='~h{, } %^[%d:%t %^] "%r" %s %b "%R" "%u" %^/%D**' --date-format=%d/%b/%Y --time-format=%T

**Comment by markgraf** [comment]
That seems to be working until I reach a count of roundabout 1,6 Million lines.
I tried multiple times. the exact numbers changes a little, but the error is always this one:

<pre>
$ goaccess access.log --log-format='~h{, } %^[%d:%t %^] "%r" %s %b "%R" "%u" %^/%D**' --date-format=%d/%b/%Y --time-format=%T -f peak.log -o peak.html
Parsing... [1,611,867] [30,997/s]
GoAccess - version 1.3 - Nov 25 2018 19:47:35
Config file: No config file used

Fatal error has occurred
Error occurred at: src/parser.c - read_log - 2728
Unable to open the specified log file. No such file or directory
</pre>

My logfile is 563M big, is that a problem?

**Comment by allinurl** [comment]
Sounds like a permissions issue on your file. Can you try to isolate this by creating a new file and reading that file with goaccess? e.g., 

    # cat access.log > /home/user/test.log 
    # goaccess test.log

**Comment by markgraf** [comment]
Ah! Sorry, must have missed the notification :-/

The file was on a Windows-Partition and thus mode 777.  Copying to my /home (mode 740) did not change  anything unfortunately.

I get the exact same error.

**Comment by allinurl** [comment]
I'd try running goaccess as root and see how it goes. Else, please feel free to run it through `strace` and attach the output here. Thanks.

**Comment by markgraf** [comment]
**PEBCAS**
Ok, NOW I feel really, really stupid m(   

I kept the copy-pasted "access.log" from the command you gave me and ADDED a "-f mylogfile.log":
`goaccess access.log --log-format='~h{, } %^[%d:%t %^] "%r" %s %b "%R" "%u" %^/%D**' --date-format=%d/%b/%Y --time-format=%T -f peak.log -o peak.html`
The command then choked on the extra logfile.

How did I not see that? Head -> Desk -> repeat...

This did work as expected:
`goaccess --log-format='~h{, } %^[%d:%t %^] "%r" %s %b "%R" "%u" %^/%D**' --date-format=%d/%b/%Y --time-format=%T -f peak.log -o peak.html`

Sorry for that.

 I just  tried what happens if I do:
`goaccess web01.log --log-format='~h{, } %^[%d:%t %^] "%r" %s %b "%R" "%u" %^/%D**' --date-format=%d/%b/%Y --time-format=%T -f web02.log -f web03.log -o test.html`

All files existed this time and it worked. Great! That saves me merging the files prior to the analysis :-)

Thanks for helping me out!

**Comment by allinurl** [comment]
No worries, it happens :) glad it is working now!
