### ISSUE TITLE
Token '"GET' doesn't match specifier '%m'

### ISSUE THREAD

**Issue by fail2010** [allinurl/goaccess#1442]
my config:
```
time-format %H:%M:%S
date-format %d/%m/%Y
log-format [%d:%t %^] "%s" %h - %^ - %^ "%m %q %H" %b "%R" "%u" "%^" rt=%T rl=%L bs=%^
```

my access.log is :

    [30/Apr/2019:06:26:55 +0800] "200" 111.213.101.177 - 111.27.173.6 - -  "GET /aaa/g/get/bbb/123?v=2.2.5&id=dddddd HTTP/1.1"  140  "https://s.taobao.com/search?q=help"  "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36"  "-" rt=0.006 rl=1395 bs=504

do i samething wrong?
and how i setting log-format, this user-agent don't match anything , just display Unknown ?
thanks

**Comment by fail2010** [comment]
if log-format:
log-format [%d:%t %^] "%s" %h - %^ - %^ "%r" %b "%R" "%u" "%^" rt=%T rl=%L bs=%^

that request method and request protocol display  "---"

**Comment by allinurl** [comment]
Please try this, it should work:

    goaccess access.log --log-format='[%d:%t %^] "%s" %h %^"%r"  %b  "%R"  "%u" %^ %^=%T %^' --date-format=%d/%b/%Y --time-format=%T

**Comment by allinurl** [comment]
Closing this, feel free to reopen it if needed.

**Comment by saran2250** [comment]
193.104.175.14<>[07/Oct/2019:09:28:28 +0000]<>www.mysite.co.uk 31<>MISS<>[no-cache]<>0.041<>"GET /w-images/googlenew2017-370x229.jpg HTTP/1.1"<>404<>"-"<>"Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 10.0; Win64; x64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Tablet PC 2.0; wbx 1.0.0; Microsoft Outlook 16.0.10730; Microsoft Outlook 16.0.10730; ms-office; MSOffice 16)"<>"0.041"

I can you suggest format for this.
