### ISSUE TITLE
Haproxy log format help

### ISSUE THREAD

**Issue by bajigithub** [allinurl/goaccess#1444]
Can you please help me to convert the below log format/line to work with goaccess?

log-format = [%pid]\ [%Ts.%ms]\ %ac/%fc/%bc/%bq/%sc/%sq/%rc\ %Tq/%Tw/%Tc/%Tr/%Tt\ %tsc\ %ci:%cp\ %fi:%fp\ %si:%sp\ %ft\ %sslc\ %sslv\ %{+Q}r\ %ST\ %b:%s\ "%CC"\ "%hr"\ "%CS"\ "%hs"\ req_size=%U\ resp_size=%B

Log line:

    Apr 30 08:38:15 usw02-rel-dataservices-ts-timeseries-lb haproxy[849]: [849] [1556613495.891] 1/1/1/0/1/0/0 0/0/0/33/+33 ---- 10.72.131.11:45036 10.72.148.46:80 10.72.148.49:8787 time_series - - "GET /v1/datapoints/latest?tags=default.d15ba919-4d4c-4e26-95ad-fc28ebf31768.OVPN_RX,default.d15ba919-4d4c-4e26-95ad-fc28ebf31768.OVPN_TX HTTP/1.1" 200 time_series_aeondb:10.72.148.49 - {time-series-store-pr||} - {Jetty(9.3.11.v201607||no-cache||} req_size=0 resp_size=+294

**Comment by bajigithub** [comment]
Any pointer to the documentation on how to convert would also help?

**Comment by 0bi-w6n-K3nobi** [comment]
Try this, in `goaccess.conf`:

`date-format %s`
`time-format %s`
`log-format %^ [%x.%^] %^ %^ %^ %h:%^ %^ %^ %^ %^ %^ "%r" %s %^resp_size=+%b`

or in command-line:
`--date-format='...' --time-format='...' --log-format='...'`

**notes:**
Man, really little useful information that can be extracted and used.
GoAccess have a Bug so Time Distribution panel always blank . See at #1810.
If you wish you can use the `HAProxy` `%b` `backend_name` field like a `GoAccess` `vhost` `%v`.
For that, change piece of `log-format`: 
`%s %^resp_size=+%b`  by  `%s %v:%^resp_size=+%b`

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
