### ISSUE TITLE
No Such File or Directory

### ISSUE THREAD

**Issue by daBee** [allinurl/goaccess#1445]
$ goaccess -p /usr/local/etc/goaccess/goaccess.conf mylog.log-20190502 ~/desktop/alpha.html

	GoAccess - version 1.3 - Apr 29 2019 17:12:23
	Config file: /usr/local/etc/goaccess/goaccess.conf

	Fatal error has occurred
	Error occurred at: src/parser.c - read_log - 2728
	Unable to open the specified log file. No such file or directory

	$ ll
	-rwxr-xr-x   1 rich  admin    21K Oct 15  2018 mylog.log-20181003
	-rwxr-xr-x@  1 rich  admin   1.1M May  2 07:59 mylog.log-20190502

For some reason, the log file cannot be opened.  It's there (last line) and it's copied and pasted so I'm not overlooking it.  

Anything I should try?

**Comment by allinurl** [comment]
Please specify the output flag. e.g.,

    $ goaccess -p /usr/local/etc/goaccess/goaccess.conf mylog.log-20190502 -o ~/desktop/alpha.html

**Comment by daBee** [comment]
That was it.  Not sure how I missed that.
