### ISSUE TITLE
Goaccess will no longer parse my logs

### ISSUE THREAD

**Issue by mwarnett** [allinurl/goaccess#1446]
I am running KUbuntu:

No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
Codename:       bionic

I run Goaccess every month on my server logs, it has worked well for me. 

I use the COMBINED log format

This month it refuses to parse my log file:

Parsed 1 linesproducing the following errors:

Token 'node3.virginia.node.siteuptime.com' doesn't match specifier '%h'

Here is the full log line:

    node3.virginia.node.siteuptime.com - - [01/Apr/2019:00:01:21 -0400] "GET /index.php HTTP/1.1" 200 30183 "-" "SiteUptime"

But is has always been able to process these lines. Here is an equivalent from last months log:

    node3.virginia.node.siteuptime.com - - [01/Mar/2019:00:10:48 -0500] "GET /index.php HTTP/1.1" 200 31937 "-" "SiteUptime"

They look the same to me. Last month Goaccess processed the log file with no errors. This month if refuses to parse the log with the same entries.

**Comment by allinurl** [comment]
Please post the exact command and attach the config file that you are running. Thanks

**Comment by allinurl** [comment]
Any updates on this?

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
