### ISSUE TITLE
Please help me with my Apache log

### ISSUE THREAD

**Issue by VIEWSION** [allinurl/goaccess#1450]
Hi,

I just can't get it run with my Apache log I downloaded. Can somebody help me with the right format? This is an example line:

`195.57.112.0 www.mydomain.com - [05/May/2019:11:24:32 +0200] "POST /path/index.php?api-call=test HTTP/2.0" 503 299 "https://www.mydomain.com/path/index.php?page=demo" "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36" 61 299`

**Comment by allinurl** [comment]
Could you please describe what are the last two fields? Thanks.

**Comment by VIEWSION** [comment]
Hey... I asked the hosting provider and he sent me the log file format config:

"%v:#:%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-agent}i\"
%I %O"

I guess this is something with I/O ... and btw this is probably the same string or at least parts to use for goAccess settings, right?

**Comment by VIEWSION** [comment]
I tried the following. But I always get this Token '././.' doesn't match specifier '%d'. I am on Mac/Mojave - any known issues here? I also tried '%d/%b/%Y' (in quotation marks)... same thing.

```
goaccess access.log --log-format='%h %U %^ [%d:%t %^] "$m %q %^" %s %b "%R" "%u" %^ %^' --date-format=%d/%b/%Y --time-format=%T
Parsed 1 linesproducing the following errors:

Token '05/May/2019' doesn't match specifier '%d'

Format Errors - Verify your log/date/time format
```

**Comment by VIEWSION** [comment]
Hey... found it... the local setting (German) was the reason. Entering

export LANG="en_US.UTF-8"

before you call GoAccess does the job. Is there a need to reset it after to the German setting? Or is this just a temporarily set for the current terminal session?

**Comment by allinurl** [comment]
Closing this, feel free to reopen it if needed.
