### ISSUE TITLE
Certificate for deb.goaccess.io expired

### ISSUE THREAD

**Issue by vbrandl** [allinurl/goaccess#1451]
The current certificate for `deb.goaccess.io` (`03:40:33:2C:8B:AC:AF:10:1B:CE:4D:9D:65:81:CF:AB:5F:2F`) expired today (exactly `May 8, 2019, 6:36:27 PM GMT`) and is no longer valid.

**Comment by allinurl** [comment]
Thanks a lot for the heads up on this. It should be back up again.

**Comment by vbrandl** [comment]
Yes. Looks fine from here. Thanks for the fast response.
