### ISSUE TITLE
Wrong date in report.

### ISSUE THREAD

**Issue by magenest-dev** [allinurl/goaccess#1454]
Hi,

I think there's a bug in the report where I have logs from 11,12, 13/May and it's showing 01, 02, 03/May.
I started recording from 08, 09/May everything works fine but starting from 10, it reports back to 01?

date-format %d/%b/%Y
log-format %h %^ &^ [%d:%t %^] "%r" %v %s %b "%R" "%u" %^ %^ %^ %^"%T"

My logs:  ....- - [13/May/2019:01:46:42 +0000] ....

Here is how my report is showing. It's still being updated real time into 03/May today (which is 13th)
![2019-05-13 15:43:40](https://user-images.githubusercontent.com/44190478/57608269-dcb67500-7596-11e9-8e1d-220f348b8c4e.png)

**Comment by allinurl** [comment]
Interesting... Are you running v1.3? can you please run goaccess with `--json-pretty-print` and check the source code of the generated report to see if it's bootstraping the dates correctly or if it's a JS thing. Thanks.

**Comment by allinurl** [comment]
Also, could you please run in via terminal and see if it outputs the same thing? Thanks.

**Comment by magenest-dev** [comment]
Yes, I'm using 1.3.
![image](https://user-images.githubusercontent.com/44190478/57825280-58e3cf00-77c8-11e9-8ec7-eb25782cb1b8.png)

I exported a few lines from the main log to run from terminal
![image](https://user-images.githubusercontent.com/44190478/57825293-68631800-77c8-11e9-810a-6599cf952ccd.png)

I think it's not a js thing.
![image](https://user-images.githubusercontent.com/44190478/57825308-7e70d880-77c8-11e9-9473-9317a9ef23bd.png)

**Comment by magenest-dev** [comment]
Sorry for this. I had a typo in the log-format

"&^"  should have been "%^"

This is what was messing up the date. It works fine now.

**Comment by allinurl** [comment]
Good to hear that. Closing this. Feel free to reopen it if needed.
