### ISSUE TITLE
GoAccess Realtime Not Working

### ISSUE THREAD

**Issue by just4testing1** [allinurl/goaccess#1455]
I'm able to get the `report.html` up and running, however it's still not in realtime despite using those parameters in SSH.

`/goaccess-1.3# goaccess /var/log/apache2/access.log -o /var/www/html/report.html --log-format=COMBINED --real-time-html
Error Opening file /usr/local/share/GeoIP/GeoIP.dat
WebSocket server ready to accept new client connections
`

Have tried installing GeoIP.dat

`:~/goaccess-1.3# apt-get install geoip-database                 Reading package lists... Done
Building dependency tree
Reading state information... Done
geoip-database is already the newest version (20180315-1).
The following packages were automatically installed and are no longer required:
  linux-headers-4.15.0-36 linux-headers-4.15.0-36-generic
  linux-image-4.15.0-36-generic linux-modules-4.15.0-36-generic
Use 'apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 129 not upgraded.
`

Only updates after and when I close the connection and re-enter the command.

**Comment by Bluscream** [comment]
I have a similar problem, I am using

```bash
zcat /var/log/apache2/other_vhosts_access.log.*.gz | ./goaccess /var/log/apache2/access.log /var/log/apache2/other_vhosts_access.log -o /var/www/html/admin/report.html --config-file=/opt/goaccess/config/goaccess.conf --geoip-database /usr/share/GeoIP/GeoLite2-City.mmdb --real-time-html --ws-url=<censored> --port=7890
```

But after GET'ing anything on my site it doesn't refresh even with F5 it just shows same amount.

**Comment by allinurl** [comment]
Could you both please the output of your browser's console. Also, please try with the bare minimal number of options. e.g., 

    goaccess access.log -o report.html --log-format=COMBINED --real-time-html

**Comment by Bluscream** [comment]
Can't use your command, have to pass my config
```bash
blu@minopia:/opt/goaccess$ ./goaccess access.log -o report.html --log-format=COMBINED --real-time-html
GoAccess - version 1.3 - May 15 2019 01:28:27
Config file: No config file used
Parsing... [0] [0/s]
Fatal error has occurred
Error occurred at: src/parser.c - read_log - 2728
Unable to open the specified log file. No such file or directory
```

**Comment by allinurl** [comment]
Looks like an issue reaching the host. Please make sure you have the port opened. Also, try using telnet to see if you can reach that port. e.g., 

    telnet host 7890

**Comment by pcart-grandjean** [comment]
Hello,
I also can't have a live report. Unfortunately I have no error message to work with.

When I create the server with the command
`goaccess /var/log/nginx/access.log --log-format=COMBINED --output=/var/www/goaccess/report.html --real-time-html`
I get the proper response:
`WebSocket server ready to accept new client connections`

When I open the page in my browser (from my laptop), I can see the data up until the moment I started goaccess. But no new data will come, no matter how long I wait and how much my `access.log` will fill up. 

In the development console there is no error. The only thing I am not sure about is that the return code from the websocket call is 101.

I have tried to test the websocket server from my laptop with a very simple little client and it worked just fine. I could see data pouring in. So I do not have a network issue between the laptop and the server.

Please let me know what I could try to narrow down the issue.

Thanks,
Pierre

**Comment by Bluscream** [comment]
@pcart-grandjean have you tried the telnet thingy @allinurl suggested?

**Comment by pcart-grandjean** [comment]
@Bluscream , yes I have and I get the `Connected to` message.

But I tried even better: I connected to the websocket with a client application. And I could see the data coming from the websocket open by goaccess.

**Comment by pcart-grandjean** [comment]
I tried again with a Linux Desktop and it works fine when browsing from the Desktop. It doesn't work when browsing from the outside. I seem to be missing a configuration parameter for that. Any help is welcome.
Thanks.

**Comment by allinurl** [comment]
@Bluscream I see that your connection is done through `wss`, you will need to use a certificate for that and ensure you are going through HTTPS.

**Comment by Bluscream** [comment]
Yes i use cloudflares certificate

**Comment by allinurl** [comment]
Did you specify the certificate and key in goaccess?

**Comment by Bluscream** [comment]
But wouldn't i need another cert if i say `--ws-url=<different>` because cloudflare protection doesnt let other traffic than 80/443 through?

**Comment by allinurl** [comment]
You definitely need a certificate to use with goaccess if you are routing through HTTPS. You are probably right, however, I can't help you with cloudflare as I'm not familiar with their system. You may be able to find similar issues here.

**Comment by Bluscream** [comment]
I wanted to use the original server ip (bypassing cloudflare completely) for the report because it's behind a `Auth: Basic` wall anyway

**Comment by phatjak** [comment]
I am running goaccess 1.1.1 (cygwin64 terminal on Windows 10), and passing the command: 

$ goaccess -f access.log -o report.html --log-format=COMBINED --real-time-html

There seems to be an issue with parsing (real-time) as it stalls at some point and never comes back. 

Nonetheless, I was able to produce static html reports and run goaccess via terminal as well.

**Comment by allinurl** [comment]
Closing this as no updates from OP. Feel free to reopen it if needed.
