### ISSUE TITLE
Always "Temporary failure in name resolution"

### ISSUE THREAD

**Issue by Bluscream** [allinurl/goaccess#1456]
![image](https://user-images.githubusercontent.com/3318223/57771816-1c569b80-7714-11e9-9d78-7b2de714c6e3.png)

**Comment by allinurl** [comment]
If it's happening to all IPs, then it sounds like it's a DNS issue on your end. Try running:

    nslookup IP

Also, you could try temporarily changing your DNS to use Google's nameservers 8.8.8.8, e.g.,

    sudo nano /etc/resolv.conf

**Comment by Bluscream** [comment]
```
blu@server:~$ nslookup 162.158.90.241
Server:         127.0.0.1
Address:        127.0.0.1#53

** server can't find 241.90.158.162.in-addr.arpa: SERVFAIL
```

**Comment by Bluscream** [comment]
I tried adding more now:

```
blu@server:/etc/resolvconf/resolv.conf.d$ nslookup 162.158.90.241
;; reply from unexpected source: 192.168.2.43#53, expected 192.168.2.47#53
;; Got SERVFAIL reply from 192.168.2.43, trying next server
;; Got SERVFAIL reply from 8.8.8.8, trying next server
;; reply from unexpected source: 192.168.2.43#53, expected 192.168.2.47#53
;; reply from unexpected source: 192.168.2.43#53, expected 192.168.2.47#53
;; connection timed out; no servers could be reached
```

```
blu@server:/etc/resolvconf/resolv.conf.d$ sudo cat /etc/resolv.conf
# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
nameserver 192.168.2.47
nameserver 192.168.2.43
nameserver 8.8.8.8
nameserver 127.0.0.1
search fritz.box
```

**Comment by allinurl** [comment]
This appears to be an issue with your DNS and not with goaccess. Essentially goaccess uses the dns resolver configured on your machine. From your nslookup output above, it couldn't resolve the IP and thus the same output in goaccess. I'd recommend posting a question on https://serverfault.com/ to see what might be the issue with your DNS.
