### ISSUE TITLE
Config file: No config file used

### ISSUE THREAD

**Issue by pyataevsv** [allinurl/goaccess#1458]
Hellow

I'm sorry, I'm completely newbie at coding and server administration but I very need to get GoAccess on my website.

I've installed successfully GoAccess on my server but when I'm trying to set up log format with a command

`# goaccess access.log -c`

I got answer

```
GoAccess - version 1.3 - Nov 22 2018 23:57:27
Config file: No config file used

Fatal error has occurred
Error occurred at: src/parser.c - read_log - 2728
Unable to open the specified log file. No such file or directory
```

I've tried to to find anny files accoiciated with "access.log" and "goaccess" via
```
# locate -i access.log
# locate -i goaccess
```
which gave me no files with such names...

What I did wrong?

**Comment by allinurl** [comment]
Which webserver are you using? i.e., apache, nginx, etc You can try running:

    # find / -name access.log

then run goaccess as e.g.,

    # goaccess /var/log/apache2/access.log -c

**Comment by pyataevsv** [comment]
I use  bitnami lamp stack

There is no such file `access.log` on my server.

I've tried 
```
# find / -name access.log
# locate -i access.log
```

Can It be with a different name?
May be it means server configuratin file like `httpd.conf`?

**Comment by pyataevsv** [comment]
I found out my log file as a access_log.
Other problems solved.

Thank you for product.
