### ISSUE TITLE
there is nothing in static html

### ISSUE THREAD

**Issue by rainbowfhb** [allinurl/goaccess#1465]
HI, I use the command "

    goaccess access-2019-05-18.log  --time-format='%T' --date-format='%d/%B/%Y' --log-format="%h %^ %^ [%d:%t %^]  %m %U %H "%s" %^ "%R" %u %^ %^" --geoip-database='GeoLite2-City.mmdb' -o report.html

but when i use browser to open the static html, there is nothing displayed.

if I dont use the parameter '-o report.html', I can see the result in linux screen.

**Comment by rainbowfhb** [comment]
![image](https://user-images.githubusercontent.com/33643321/58401448-71899a00-8090-11e9-99be-69ae0785d157.png)

**Comment by rainbowfhb** [comment]
![image](https://user-images.githubusercontent.com/33643321/58401479-8c5c0e80-8090-11e9-8900-c61ef8c94290.png)

**Comment by allinurl** [comment]
Strange, have you made any updates to the code? Also, can you post a few lines from your access log? Thanks

**Comment by rainbowfhb** [comment]
121.228.250.179 - - [18/May/2019:00:14:27 +0800] "GET /aep_product_management/product?productId=8725 HTTP/1.1" 200 1571 "-" "Apache-HttpClient/4.4.1 (Java/1.7.0_151)" "-" "121.228.250.179"
121.8.136.7 - - [18/May/2019:00:14:27 +0800] "GET /login/index.html?true&returnURL=https%3A%2F%2Fwww.ctwing.cn%2Flogin%3Furl%3D%252F HTTP/1.1" 500 5205 "https://www.ctwing.cn/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0.3 Safari/605.1.15" "-" "121.8.136.7"
180.101.149.101 - - [18/May/2019:00:14:27 +0800] "GET /echo HTTP/1.1" 200 675 "-" "Go-http-client/1.1" "-" "180.101.149.101"

**Comment by rainbowfhb** [comment]
121.228.250.179 - - [18/May/2019:00:14:27 +0800] "GET /aep_product_management/product?productId=8725 HTTP/1.1" 200 1571 "-" "Apache-HttpClient/4.4.1 (Java/1.7.0_151)" "-" "121.228.250.179"
180.101.149.101 - - [18/May/2019:00:14:27 +0800] "GET /echo HTTP/1.1" 200 675 "-" "Go-http-client/1.1" "-" "180.101.149.101"

**Comment by allinurl** [comment]
Please try:

    goaccess access.log --log-format='%h %^[%d:%t %^] "%r" %s %b "%R" "%u" %^' --time-format='%T' --date-format='%d/%B/%Y'

**Comment by allinurl** [comment]
Closing this. v1.4 has been released so feel free to test it out there and post back if needed. Thanks.
