### ISSUE TITLE
`--enable-geoip` option does not work

### ISSUE THREAD

**Issue by alexreg** [allinurl/goaccess#1470]
I get:
```
goaccess: unrecognized option `--enable-geoip'
```
What's going on here?

(Version 1.3.0 on macOS.)

**Comment by allinurl** [comment]
Did you build with geoip? Please take a look at [**this**](https://github.com/allinurl/goaccess#build-from-release).

**Comment by alexreg** [comment]
I used the Homebrew build. Doesn't that enable it?

**Comment by alexreg** [comment]
Ah, my mistake... I misread the docs, sorry. It's a configuration option for the build, not for the actual progoram!

**Comment by alexreg** [comment]
Incidentally, is there a way to view data per city in the HTML report? I only see a per continent/country breakdown.

**Comment by allinurl** [comment]
Currently the city is reported only in the hosts panel (per IP).  #750 will handle this.

**Comment by alexreg** [comment]
Okay, thanks for that notice. I'll go ahead and close this because the original problem is solved.
