### ISSUE TITLE
nginx custom log format

### ISSUE THREAD

**Issue by madawei2699** [allinurl/goaccess#1476]
here is my nginx access log:

`66.249.64.155 - - [10/Jun/2019:01:15:31 +0000] 10.6.96.6:4000 "GET /tag/umzugnaht HTTP/1.1" 429 17 "-" "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"`

how can I config goaccess log format?

thanks!

**Comment by allinurl** [comment]
Please try:

    goaccess access.log --log-format='%h %^[%d:%t %^] %^ "%r" %s %b "%R" "%u"' --date-format=%d/%b/%Y --time-format=%T

**Comment by madawei2699** [comment]
thanks!
