### ISSUE TITLE
Log Format

### ISSUE THREAD

**Issue by Ala321** [allinurl/goaccess#1477]
Hi i want to ask to help with  configure log format. 
My apache config is set to 

    LogFormat "%h %a %l %u [%{%d/%b/%Y:%T}t.%{msec_frac}t %{%z}t] \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\" %T %{cookie}n %I %O (%{ratio}n) %X|%D (%{mpuid}C) (%{resolution}C)" combined

    192.168.10.100 213.94.152.272 - - [10/Jun/2019:11:26:07.242 +0200] "GET /main/art/thumb/115989/120/90.html HTTP/1.1" 302 - "https://www.domain.com/art/list/64585,pain" "Mozilla/5.0 (Linux; Android 8.1.0; HTC U12 life) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.157 Mobile Safari/537.36" 0 - 1073 247 (-) -|38365 (35f9ffe4-8a13-4caa-a821-d26b02424602) (-)

i set up 

```
time-format %H:%M:%S
date-format {%d/%b/%Y:%T}t.%{msec_frac}t
log-format %h %a %l %u [%{%d/%b/%Y:%T}t.%{msec_frac}t %{%z}t]


```but it cant reads 
 Format Errors - Verify your log/date/time format     
 Token '10' doesn't match specifier '%d'

**Comment by allinurl** [comment]
Can you please describe the fields you have in your format? Thanks

**Comment by allinurl** [comment]
Please try:

    goaccess access.log --log-format='%^ %h %^[%d:%t.%^] "%r" %s %b "%R" "%u" %^|%D %^' --date-format=%d/%b/%Y --time-format=%T

**Comment by allinurl** [comment]
Any updates on this?

**Comment by allinurl** [comment]
Closing this, feel free to reopen it if needed.
