### ISSUE TITLE
Automatic build stopped on Docker Hub

### ISSUE THREAD

**Issue by err931** [allinurl/goaccess#1481]
**The automatic image build seems to have stopped because the token has been revoked.**
It will return to normal if you tie it again. Please do the procedure.

**Comment by allinurl** [comment]
Which token would that be?

**Comment by err931** [comment]
> Docker Hub hack exposed data of 190,000 users
> https://zd.net/2V1PxJK

A while ago, an accident occurred inside the Docker Hub.
As a result, all github tokens associated with Docker Hub were revoked.

You need to access Docker Hub and re-associate your github account.

**Comment by allinurl** [comment]
Should be re-linked now. Please take a look and let me know if that's the case for you.

Gerardo

**Comment by allinurl** [comment]
Closing this, feel free to reopen it if needed. Thanks!
