### ISSUE TITLE
crontab execute very slow

### ISSUE THREAD

**Issue by l36t** [allinurl/goaccess#1483]
hi,my goaccess version is 1.3. redhat 6.8  When I execute under commander "/home/software/goaccess/goaccess   -q --no-query-string --hour-spec=min --date-spec=hr -p /root/.goaccessrc  -f /home/software/goaccess/goaccess_log/history/test.log > /home/software/goaccess/goaccess_html/test.html".
It's very fast and the log size is 200M.
However,if I execute from crontab :
39 18 * * * /home/software/goaccess/goaccess   -q --no-query-string --hour-spec=min --date-spec=hr -p /root/.goaccessrc  -f /home/software/goaccess/goaccess_log/history/test.log > /home/software/goaccess/goaccess_html/test.html
goaccess execute very slow,I wait for 20 minutes,then kill the process.
Do you know why,or how to debug to find some reason,Thank you so much

**Comment by allinurl** [comment]
Did you resolve this issue?
