### ISSUE TITLE
Custom log format parsing error

### ISSUE THREAD

**Issue by edisonh** [allinurl/goaccess#1484]
Hi
Thx for great tool.

Using goaccess version 1.3

log sample:
```
- - 1.2.3.4:1234 - - [20/Jun/2019:00:00:00 +0800] "GET http://xxx.com/api/xxx" 200
```

## problem one: date parsing error

command line:
```
goaccess --date-format='%d/%b/%Y' --time-format=%T --log-format='%^ %^ %h:%^ %^[%d:%t %^] "%m http://%v%U" %s' xx.log

```
error:
```
Token '20/Jun/2019' doesn't match specifier '%d'
```

## problem two: server name parsing error
Ignore problem one: set '%^' at '%d' position
commad line:
```
goaccess --date-format='%d/%b/%Y' --time-format=%T --log-format='%^ %^ %h:%^ %^[%^:%t %^] "%m http://%v%U" %s' xx.log
```
error:
```
Token for '%v' specifier is NULL
```

**Comment by allinurl** [comment]
Can you please try this:

    goaccess access.log --log-format='%^ %^ %h: %^[%d:%t %^] "%m %U" %s' --date-format='%d/%b/%Y' --time-format=%T --http-protocol=no

**Comment by allinurl** [comment]
Any updates on this?

**Comment by allinurl** [comment]
Closing this, feel free to reopen it if needed.
