### ISSUE TITLE
Disable Geo Location when using prepackaged binary

### ISSUE THREAD

**Issue by MACscr** [allinurl/goaccess#1485]
I am using the deb.goaccess.io repo for my Debian Jessie systems and it seems to have geolocation enabled by default. I dont see a way to disable it, only to hide the panel. Everytime i start goaccess, i get 'Error Opening file /usr/share/GeoIP/GeoIP.dat'. I dont have it enabled it the config file or at the cli. Am i missing something? Im running 1.3 and it seems to by default been built with legacy geoip enabled.

```
GoAccess - 1.3.
For more details visit: http://goaccess.io
Copyright (C) 2009-2016 by Gerardo Orellana

Build configure arguments:
  --enable-utf8
  --enable-geoip=legacy
  --with-openssl
```

**Comment by allinurl** [comment]
Can you please post the output of `goaccess --dcf`?

Thanks

**Comment by allinurl** [comment]
Closing this, feel free to reopen it if needed.
