### ISSUE TITLE
Issue with custom database path

### ISSUE THREAD

**Issue by waferbaby** [allinurl/goaccess#1486]
I'm trying to keep incremental logs in the btree DB. My initial command was:

```zcat /usr/local/www/usesthis.com/log/access.log.*.gz | goaccess --keep-db-files --db-path=/usr/local/share/stats/usesthis/ --log-format=COMBINED -o /usr/local/www/usesthis.com/public/stats.html -```

Which worked great, I can see a ton of data - I want to start from a solid base of old logs, etc. I want to set up a cronjob that appends the logs from `access.log`/`access.log.1` on a daily basis, so I figured I'm meant to do something like this:

```goaccess --keep-db-files --db-path=/usr/local/shared/stats/usesthis/ /usr/local/www/usesthis.com/log/access.log /usr/local/www/usesthis.com/log/access.log.1 --log-format=COMBINED -o /usr/local/www/usesthis.com/public/stats.html```

However, I get:

```
GoAccess - version 1.2 - Jun 19 2017 12:55:29
Config file: No config file used

Fatal error has occurred
Error occured at: src/tcbtdb.c - tc_db_set_path - 66
Unable to access database path: No such file or directory
```

A) Am I understanding how to even do the incremental data stuff correctly?
B) Why can't it access the database path? Not using a config file, so what you see is all there. I can see all the .tcb files in `/usr/local/share/stats/usesthis`, and trying with or without a trailing slash doesn't seem to make a difference.

What am I doing wrong?

**Comment by waferbaby** [comment]
(Now I'm wondering if this is something to do with using v1.2, not 1.3, which doesn't seem to be available via `apt` directly.)

**Comment by waferbaby** [comment]
Updated to 1.3, and starting from scratch, I now get:

```zcat /usr/local/www/usesthis.com/log/access.log.*.gz | goaccess --keep-db-files --db-path=/usr/local/share/stats/usesthis/ --log-format=COMBINED -o /usr/local/www/usesthis.com/public/stats.html /usr/local/www/usesthis.com/log/access.log /usr/local/www/usesthis.com/log/access.log.1 -o /usr/local/www/usesthis.com/public/stats.html
goaccess: unrecognized option '--keep-db-files'```

**Comment by waferbaby** [comment]
Updated to 1.3 - same issue (different line in the C code):

```
GoAccess - version 1.3 - Nov 22 2018 23:58:39
Config file: No config file used

Fatal error has occurred
Error occurred at: src/tcbtdb.c - tc_db_set_path - 79
Unable to access database path: No such file or directory
```

**Comment by allinurl** [comment]
Can you please try with `--no-global-config`? Thanks

**Comment by waferbaby** [comment]
@allinurl Unfortunately, exact same issue.

```
goaccess --keep-db-files --db-path=/usr/local/shared/stats/usesthis/ /usr/local/www/usesthis.com/log/access.log /usr/local/www/usesthis.com/log/access.log.1 --log-format=COMBINED -o /usr/local/www/usesthis.com/public/stats.html --no-global-config

GoAccess - version 1.3 - Nov 22 2018 23:58:39
Config file: No config file used

Fatal error has occurred
Error occurred at: src/tcbtdb.c - tc_db_set_path - 79
Unable to access database path: No such file or directory
```

**Comment by waferbaby** [comment]
(@allinurl Happy to send you the log files or my .tcb files if that helps.)

**Comment by waferbaby** [comment]
@allinurl Let me know if I can do anything else to help debug, too.

**Comment by allinurl** [comment]
It seems it's failing on the `stat()` [**call**](https://github.com/allinurl/goaccess/blob/master/src/tcbtdb.c#L78). Are you able to run it through strace and post/attach the output here. Thanks

**Comment by waferbaby** [comment]
Here's the breaking bit:

```write(2, "\nFatal error has occurred", 25
Fatal error has occurred) = 25
write(2, "\nError occurred at: src/tcbtdb.c"..., 55
Error occurred at: src/tcbtdb.c - tc_db_set_path - 79
) = 55
openat(AT_FDCWD, "/usr/share/locale/locale.alias", O_RDONLY|O_CLOEXEC) = 4
fstat(4, {st_mode=S_IFREG|0644, st_size=2995, ...}) = 0
read(4, "# Locale name alias data base.\n#"..., 4096) = 2995
read(4, "", 4096)                       = 0
close(4)                                = 0
openat(AT_FDCWD, "/usr/share/locale/en_US.UTF-8/LC_MESSAGES/libc.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/share/locale/en_US.utf8/LC_MESSAGES/libc.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/share/locale/en_US/LC_MESSAGES/libc.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/share/locale/en.UTF-8/LC_MESSAGES/libc.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/share/locale/en.utf8/LC_MESSAGES/libc.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/share/locale/en/LC_MESSAGES/libc.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/share/locale-langpack/en_US.UTF-8/LC_MESSAGES/libc.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/share/locale-langpack/en_US.utf8/LC_MESSAGES/libc.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/share/locale-langpack/en_US/LC_MESSAGES/libc.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/share/locale-langpack/en.UTF-8/LC_MESSAGES/libc.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/share/locale-langpack/en.utf8/LC_MESSAGES/libc.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/share/locale-langpack/en/LC_MESSAGES/libc.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
write(2, "Unable to access database path: "..., 57Unable to access database path: No such file or directory) = 57
write(2, "\n\n", 2

)                     = 2
exit_group(1)                           = ?
+++ exited with 1 +++```

**Comment by allinurl** [comment]
Could you please post a few lines before the Fatal error message? Thanks

**Comment by waferbaby** [comment]
@allinurl https://gist.github.com/waferbaby/0e78effbcda87a18d79464b217aec7c7

**Comment by allinurl** [comment]
Are you running this as root? From that output, it seems like `stat("/usr/local/shared/stats/usesthis/", 0x7ffc4971a700) = -1 ENOENT (No such file or directory)` doesn't exist. Also, just to be sure, please try using v1.3 as there were some fixes that could have affected this. Thanks!

**Comment by waferbaby** [comment]
Oh my god, it was a typo. It was a typo! You can ignore this now.
