### ISSUE TITLE
CUSTOM LOG/DATE FORMAT ERROR

### ISSUE THREAD

**Issue by xzm1274913976** [allinurl/goaccess#1489]
`
 log_format test '$remote_addr - - $time_iso8601 "$request_method $scheme://$host$request_uri $server_protocol" $status $bytes_sent "$http_referer" "$http_user_agent" $upstream_cache_status:TCP $request_length $request_time $upstream_response_time $server_addr';
`

- - - 2019-06-29 21:51:03 "GET https://www.myblogsite.top/report.html?2 HTTP/1.1" 200 96676 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:67.0) Gecko/20100101 Firefox/67.0" -:TCP 674 0.130 - 192.168.1.158
- - - 2019-06-29 21:54:51 "GET https://www.myblogsite.top/report.html?2 HTTP/1.1" 304 213 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:67.0) Gecko/20100101 Firefox/67.0" -:TCP 785 0.000 - 192.168.1.158

 LANG="zh_CN.UTF-8";/usr/local/goaccess/bin/goaccess /usr/local/nginx/logs/django_blog.log -o /usr/local/django-blog-master/templates/report.html --real-time-html  --log-format='????' --date-format=%d/%b/%Y --time-format=%T

--log-format is do? Thanks.

**Comment by allinurl** [comment]
This should work:

    goaccess log --log-format='%d %t "%r" %s %b "%R" "%u" %^ %^ %T %^ %h' --date-format=%Y-%m-%d --time-format=%T

**Comment by xzm1274913976** [comment]
Thanks very much .I use :
`--log-format='- - - %d %t "%r" %s %b "%R" "%u" %^ %^ %T %^ %h' --date-format=%Y-%m-%d --time-format=%T`

GoAccess start working!
