### ISSUE TITLE
Mac OS Server Log Format

### ISSUE THREAD

**Issue by Glujaz** [allinurl/goaccess#1490]
Hello, 

I'm sorry for bothering, but I simply can't find the correct log format to use with Mac OS Server High Sierra's built in Apache Server. (Yes, I know about Mac OS Server... but will still wait 1 extra year before changing)

Even the config file is a bit strange to understand...

`  LogFormat "%a %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" combined
    LogFormat "%v %a %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" combinedvhost
    LogFormat "%a %l %u %t \"%r\" %>s %b" common
    LogFormat "%v %a %l %u %t \"%r\" %>s %b" commonvhost

    <IfModule logio_module>
      # You need to enable mod_logio.c to use %I and %O
      LogFormat "%a %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\" %I %O" combinedio
      LogFormat "%v %a %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\" %I %O" combinediovhost`

And this is how a log looks like :

`host.fr 66.249.75.52 - - [05/Jun/2019:06:00:10 +0200] "GET /robots.txt HTTP/1.1" 200 24 "-" "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"

other.host.fr 127.0.0.1 - user [05/Jun/2019:07:25:53 +0200] "PROPFIND /dav.php/ HTTP/1.1" 207 1010 "-" "ReaddleDAV Documents/6.9.1.622 (redirects)"`

Thanks in advance ! :)

**Comment by allinurl** [comment]
This should do it:

   goaccess access.log --log-format='%v %h %^[%d:%t %^] "%r" %s %b "%R" "%u"' --date-format=%d/%b/%Y --time-format=%T

**Comment by Glujaz** [comment]
Thank you for your help, but it still doesn't work...
I get this error message : 

`Token '' doesn't match specifier '%h'
`

**Comment by allinurl** [comment]
For the lines you posted above, it works for me. Can you please post/attach a good sample from your access log and how you are running goaccess?

**Comment by Glujaz** [comment]
Hello, sorry for the late reply,

here are some other lines. I try to avoid showing up to much, as I don't won't it to be public. Hope you can understand :/

`
files.example.fr 195.25.118.37 - - [02/Jul/2019:15:06:52 +0200] "POST /?module=fileman&section=get&page=tree HTTP/1.1" 200 2 "https://files.example.fr/" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.172 Safari/537.36 Vivaldi/2.5.1525.46"
files.example.fr 195.25.118.37 - - [02/Jul/2019:15:06:50 +0200] "GET /t.php?p=/ROOT/HOME/Documents/Aero/ATR Air asia crah report.pdf&s=14774269&t=1538778780 HTTP/1.1" 200 7916 "https://files.example.fr/" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.172 Safari/537.36 Vivaldi/2.5.1525.46"
default 127.0.0.1 - - [02/Jul/2019:15:07:05 +0200] "OPTIONS * HTTP/1.0" 200 - "-" "Apache/2.4.33 (Unix) LibreSSL/2.2.7 (internal dummy connection)"
default 139.199.38.31 - - [02/Jul/2019:15:12:38 +0200] "GET /TP/public/index.php HTTP/1.1" 302 286 "-" "Mozilla/5.0 (Windows; U; Windows NT 6.0;en-US; rv:1.9.2) Gecko/20100115 Firefox/3.6)"
files.example.fr 195.25.118.37 - - [02/Jul/2019:15:21:57 +0200] "GET /images/icons/ellipsis-v.svg HTTP/1.1" 200 455 "https://files.example.fr/css/ext.php?v=2018.11.11&theme=green" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.172 Safari/537.36 Vivaldi/2.5.1525.46"
example.fr 201.106.4.140 - - [02/Jul/2019:16:28:52 +0200] "GET / HTTP/1.1" 302 261 "-" "-"
example.fr 34.211.228.42 - - [02/Jul/2019:16:34:22 +0200] "GET / HTTP/1.1" 302 261 "-" "Go-http-client/1.1"
default 5.188.210.101 - - [02/Jul/2019:17:20:50 +0200] "GET /echo.php HTTP/1.1" 302 277 "https://www.google.com/" "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36"
default 185.234.218.18 - - [03/Jul/2019:06:58:16 +0200] "GET /.bitcoin/wallet/wallet.dat HTTP/1.1" 302 293 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:67.0) Gecko/20100101 Firefox/67.0"
default 185.234.218.18 - - [03/Jul/2019:06:58:16 +0200] "GET /.bitcoin/wallet/wallet.dat HTTP/1.1" 404 286 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:67.0) Gecko/20100101 Firefox/67.0"
`

**Comment by allinurl** [comment]
This works for me:

    goaccess access.log --log-format='%v %h %^[%d:%t %^] "%r" %s %b "%R" "%u"' --date-format=%d/%b/%Y --time-format=%T --no-global-config

![a](https://user-images.githubusercontent.com/5005367/60615039-d4f39f80-9d93-11e9-93a0-64b76ef6015c.png)

**Comment by Glujaz** [comment]
I still have the same error...
Is it because I have this as my first line ?

> Jun  5 01:30:01 server newsyslog[63679]: logfile turned over due to size>20480K

**Comment by Glujaz** [comment]
Removing the first line gives me this error now : 

> Token '05/Jun/2019' doesn't match specifier '%d'

**Comment by allinurl** [comment]
Could be, you could try passing `--num-tests=0` and see if that's the issue. Let me know!

**Comment by allinurl** [comment]
what's the output of `date` from your terminal?

**Comment by Glujaz** [comment]
This is my output : 

> Mer  3 jul 2019 20:20:45 CEST

By the way, using the argument `--num-tests=0` seems to open everything now
!
Though, it stops at the first of July when my log file starts in June...
[Capture d’écran 2019-07-03 à 20 21 44](https://user-images.githubusercontent.com/44747485/60615788-43565300-9dd0-11e9-9fc4-e2ebdd08a4b0.png)

**Comment by allinurl** [comment]
Please try:

    LANG="en_US.UTF-8" bash -c 'goaccess access.log --log-format='%v %h %^[%d:%t %^] "%r" %s %b "%R" "%u"' --date-format=%d/%b/%Y --time-format=%T --no-global-config'

**Comment by Glujaz** [comment]
Nope, now it's asking for a log format configuration.

Sorry again :(

**Comment by allinurl** [comment]
> By the way, using the argument `--num-tests=0` seems to open everything now!
So did it work?

**Comment by Glujaz** [comment]
Negative, it is not going further then July, when my log file starts on June...

**Comment by allinurl** [comment]
Not sure what you mean with start on June but can't go further than July. Can you attach the access log? what would the output of `head access.log` and `tail access.log` is?

**Comment by Glujaz** [comment]
Is it possible to keep an attached file as private ?

Head access_log (yeah, not proud of it's content, but it isn't available in france...) : 

Jun 5 01:30:01 server newsyslog[63679]: logfile turned over due to size>20480K
files.example.fr 127.0.0.1 - - [05/Jun/2019:01:30:02 +0200] "GET /dav.php/@Home/Downloads/Aria%20Downloads/Chernobyl.S01E04.720p.WEBRip.x264-TBS%5BTGx%5D/chernobyl.s01e04.720p.webrip.x264-tbs.mkv HTTP/1.1" 401 50 "-" "ReaddleDAV Documents/6.9.1.622 (redirects)"
files.example.fr 127.0.0.1 - user [05/Jun/2019:01:30:03 +0200] "GET /dav.php/@Home/Downloads/Aria%20Downloads/Chernobyl.S01E04.720p.WEBRip.x264-TBS%5BTGx%5D/chernobyl.s01e04.720p.webrip.x264-tbs.mkv HTTP/1.1" 206 12304384 "-" "ReaddleDAV Documents/6.9.1.622 (redirects)"
files.example.fr 127.0.0.1 - user [05/Jun/2019:01:30:05 +0200] "GET /dav.php/@Home/Downloads/Aria%20Downloads/Chernobyl.S01E04.720p.WEBRip.x264-TBS%5BTGx%5D/chernobyl.s01e04.720p.webrip.x264-tbs.mkv HTTP/1.1" 206 20971520 "-" "ReaddleDAV Documents/6.9.1.622 (redirects)"
files.example.fr 127.0.0.1 - user [05/Jun/2019:01:30:07 +0200] "GET /dav.php/@Home/Downloads/Aria%20Downloads/Chernobyl.S01E04.720p.WEBRip.x264-TBS%5BTGx%5D/chernobyl.s01e04.720p.webrip.x264-tbs.mkv HTTP/1.1" 206 20971520 "-" "ReaddleDAV Documents/6.9.1.622 (redirects)"
files.example.fr 127.0.0.1 - user [05/Jun/2019:01:30:08 +0200] "GET /dav.php/@Home/Downloads/Aria%20Downloads/Chernobyl.S01E04.720p.WEBRip.x264-TBS%5BTGx%5D/chernobyl.s01e04.720p.webrip.x264-tbs.mkv HTTP/1.1" 206 20971520 "-" "ReaddleDAV Documents/6.9.1.622 (redirects)"
files.example.fr 127.0.0.1 - user [05/Jun/2019:01:30:10 +0200] "GET /dav.php/@Home/Downloads/Aria%20Downloads/Chernobyl.S01E04.720p.WEBRip.x264-TBS%5BTGx%5D/chernobyl.s01e04.720p.webrip.x264-tbs.mkv HTTP/1.1" 206 20971520 "-" "ReaddleDAV Documents/6.9.1.622 (redirects)"
files.example.fr 127.0.0.1 - user [05/Jun/2019:01:30:13 +0200] "GET /dav.php/@Home/Downloads/Aria%20Downloads/Chernobyl.S01E04.720p.WEBRip.x264-TBS%5BTGx%5D/chernobyl.s01e04.720p.webrip.x264-tbs.mkv HTTP/1.1" 206 20971520 "-" "ReaddleDAV Documents/6.9.1.622 (redirects)"
files.example.fr 127.0.0.1 - user [05/Jun/2019:01:30:15 +0200] "GET /dav.php/@Home/Downloads/Aria%20Downloads/Chernobyl.S01E04.720p.WEBRip.x264-TBS%5BTGx%5D/chernobyl.s01e04.720p.webrip.x264-tbs.mkv HTTP/1.1" 206 20971520 "-" "ReaddleDAV Documents/6.9.1.622 (redirects)"
files.example.fr 127.0.0.1 - user [05/Jun/2019:01:30:18 +0200] "GET /dav.php/@Home/Downloads/Aria%20Downloads/Chernobyl.S01E04.720p.WEBRip.x264-TBS%5BTGx%5D/chernobyl.s01e04.720p.webrip.x264-tbs.mkv HTTP/1.1" 206 20971520 "-" "ReaddleDAV Documents/6.9.1.622 (redirects)"


Tail access_log : 

vh1.example.fr 127.0.0.1 - - [03/Jul/2019:20:14:56 +0200] "GET /.well-known/acme-challenge/ HTTP/1.1" 403 304 "-" "curl/7.54.0"
default 127.0.0.1 - - [03/Jul/2019:20:15:01 +0200] "OPTIONS * HTTP/1.0" 200 - "-" "Apache/2.4.33 (Unix) LibreSSL/2.2.7 (internal dummy connection)"
default 127.0.0.1 - - [03/Jul/2019:20:15:06 +0200] "OPTIONS * HTTP/1.0" 200 - "-" "Apache/2.4.33 (Unix) LibreSSL/2.2.7 (internal dummy connection)"
default 127.0.0.1 - - [03/Jul/2019:20:15:07 +0200] "OPTIONS * HTTP/1.0" 200 - "-" "Apache/2.4.33 (Unix) LibreSSL/2.2.7 (internal dummy connection)"
default 127.0.0.1 - - [03/Jul/2019:20:15:12 +0200] "OPTIONS * HTTP/1.0" 200 - "-" "Apache/2.4.33 (Unix) LibreSSL/2.2.7 (internal dummy connection)"
default 127.0.0.1 - - [03/Jul/2019:20:15:13 +0200] "OPTIONS * HTTP/1.0" 200 - "-" "Apache/2.4.33 (Unix) LibreSSL/2.2.7 (internal dummy connection)"
default 137.74.158.99 - - [03/Jul/2019:20:23:14 +0200] "GET /wp-login.php HTTP/1.1" 302 285 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:62.0) Gecko/20100101 Firefox/62.0"
default 137.74.158.99 - - [03/Jul/2019:20:23:15 +0200] "GET /wp-login.php HTTP/1.1" 404 275 "http://vh2.example.fr/wp-login.php" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:62.0) Gecko/20100101 Firefox/62.0"
default 127.0.0.1 - - [03/Jul/2019:20:23:32 +0200] "OPTIONS * HTTP/1.0" 200 - "-" "Apache/2.4.33 (Unix) LibreSSL/2.2.7 (internal dummy connection)"
default 143.255.240.253 - - [03/Jul/2019:20:37:18 +0200] "GET / HTTP/1.1" 302 267 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36"

**Comment by Glujaz** [comment]
And as you can see in a previous message, I attached a screen capture with go access starting only at the 1st of July, whereas the head of access_log clearly start at the 5th of June

**Comment by allinurl** [comment]
Probably not possible to attach a private link. You can always hosted on your site and share the link to me via hello [at] goaccess.io. Are you able to run this on a different machine just to see how it performs?

**Comment by Glujaz** [comment]
Hello,
I sent you a link via email :)

By the way, I had it working with live HTML view for a few month, up until an update of go access remove my script with the command because I stupidly placed it at a wrong place...
And I completely forgot that I had backups of my server old enough to recover these files. So I did it a few minutes ago, and ran it with no success.
Adding --num-test=0 helped a bit, but give the same results as the ones I have up until now (June not included).

Here is the command : 

> goaccess /var/log/apache2/access_log --log-format='%v %h %^[%d:%t %^] "%r" %s %b "%R" "%u"' --date-format=%d/%b/%Y --time-format=%T


Running it with live HTML arguments made it create the file, but the webpage is not being updated, although it says in terminal, web socket is active.

Hope this can help a little bit more ! :)

**Comment by allinurl** [comment]
Any updates on this? If still not working, please feel free to attach the access log so I can run on it on y end.
