### ISSUE TITLE
GoAccess not showing 'Tx.' Amount

### ISSUE THREAD

**Issue by wappguru** [allinurl/goaccess#1493]
Hello everyone,

I've configured goaccess for one of our servers to show data for our individual websites 'apache vhosts'.

Everything works great at first, but the one thing missing is the bandwidth amount 'the reason I installed it'.

Is there anything specific I should check as to why it won't show the bandwidth?

https://imgur.com/a/TUz7Sv3

**Comment by allinurl** [comment]
Probably wrong log-format. Can you post a few lines from your access log and the log-format you are using with goaccess?

**Comment by wappguru** [comment]
`172.24.32.12 - - [10/Jul/2019:08:31:55 -0500] "GET /event_calendar_large.php?pageID=293&month=&day=&year=&calstart=1559288611&filterCat=11&jump=&calcats= HTTP/1.0" 200 29613 "-" "-"
46.229.168.149 - - [10/Jul/2019:08:31:55 -0500] "GET /site.php?calstart=1559288611&filterCat=11&pageID=293 HTTP/1.1" 200 34730 "-" "Mozilla/5.0 (compatible; SemrushBot/3~bl; +http://www.semrush.com/bot.html)"
12.152.126.2 - - [10/Jul/2019:08:31:56 -0500] "-" 408 - "-" "-"
172.24.32.12 - - [10/Jul/2019:08:32:01 -0500] "GET /event_detail.php?pageID=293&eID=5812 HTTP/1.0" 200 1226 "-" "-"
54.36.150.75 - - [10/Jul/2019:08:32:01 -0500] "GET /site.php?pageID=293&eID=5812&backpage=pageID7eq72937an7calstart7eq71530368227 HTTP/1.1" 200 6339 "-" "Mozilla/5.0 (compatible; AhrefsBot/6.1; +http://ahrefs.com/robot/)"
46.229.168.162 - - [10/Jul/`

log-format %v:%^ %h %^[%d:%t %^] "%r" %s %b "%R" "%u"

I copied a few lines from the individual vhost log. Thank you for your assistance I really appreciate it!

**Comment by wappguru** [comment]
Any help would be greatly appreciated. Let me know if there is anything I can do in return.

**Comment by allinurl** [comment]
goaccess log --log-format=COMBINED

**Comment by wappguru** [comment]
That worked! Thank you so much!!
