### ISSUE TITLE
GoAccess fails to install on Debian Buster

### ISSUE THREAD

**Issue by chrisx8** [allinurl/goaccess#1496]
I tried to install Goaccess on Debian Buster (now stable) from the official Debian repo and I ran into some dependency issues. Goaccess depends on `libssl1.0.2`, but Debian Buster only includes `libssl1.1` in their repos.

My OS version: `Debian GNU/Linux 10 (buster)`

Here's my repo config in `/etc/apt/sources.list`:
```
deb http://deb.goaccess.io/ buster main
```

Here's the error I'm encountering:
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 goaccess : Depends: libssl1.0.2 (>= 1.0.2) but it is not installable
E: Unable to correct problems, you have held broken packages.
```

**Comment by chrisx8** [comment]
Already fixed.

**Comment by jotteerr** [comment]
Sorry to ask, how did you fix it? I'm getting the same error …

**Comment by chrisx8** [comment]
Sorry I was incorrect. Debian Buster only has `libssl1.1` in the repos, and `libssl1.0.2` is still not installable.

However, `libssl1.0.2` can be manually installed. To do this, [download the `.deb` package](https://packages.debian.org/stretch/libssl1.0.2) from the Debian Stretch repos and install it with `dpkg`.

**Comment by jotteerr** [comment]
Thanks, @chrisx8, got it installed. Unfortunately, when starting GoAccess with `goaccess /var/log/caddy/access.log --real-time-html -o /var/www/html/report.html -p /etc/goaccess/goaccess.conf`, I get a static file, not real time updates. `report.html` is populated, when I start GoAccess, but then it is never changed. Did you get it working?

**Comment by chrisx8** [comment]
Real-time HTML reports require its own WebSocket server (created by GoAccess when `--real-time-html` is set). Make sure GoAccess remains running and the port (default is 7890) is open.

To change the port, check out [GoAccess's man page](https://goaccess.io/man#options) under **Server Options**.

**Comment by chrisx8** [comment]
Resolved
