### ISSUE TITLE
Unable to parse custom JSON log format

### ISSUE THREAD

**Issue by shiyan0109** [allinurl/goaccess#1500]
I am trying to use goaccess to analyze my nginx log, my log is customized with json,like this

    {"time_date": "2019-07-15T08:22:45+00:00","client": "172.30.148.128", "host": "test.my-9c-clu.xx.xxx", "scheme": "http", "request_method": "GET", "request_uri": "/PingServlet", "request_id": "817c80d5e6791c10bf459b166cb311ad", "status": 200, "upstream_addr": "172.30.78.203:8000", "upstream_status": 200, "request_time": 0.006, "upstream_response_time": 0.004, "upstream_connect_time": 0.000, "upstream_header_time": 0.004}

I tried to use

```
log-format '%^: "%^",%^: "%h", %^: "%U", %^: "%^", %^: "%^", %^: "%U", %^: "%^", %^: %s, %^: "%h:%^", %^: %T, %^: %T, %^: %T, %^: %T, %^: %T'
date-format %Y-%m-%d
time-format %T
```

based on some issues I reference, but still can't parse the log

I got the error like
```
Fatal error has occurred
Error occured at: src/goaccess.c - main - 1033
Nothing valid to process.
```

Could you please help me on what format I should use for log, time and date? Thanks very much

**Comment by allinurl** [comment]
This should do it:

    goaccess access.log --log-format='%^: "%dT%t+%^",%^: "%h",%^: "%v",%^,%^: "%m",%^: "%U",%^,%^: %s,%^,%^,%^: %T,%^' --date-format=%Y-%m-%d --time-format=%T --ignore-panel=BROWSERS --ignore-panel=OS --ignore-panel=REFERRING_SITES --http-protocol=no

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
