### ISSUE TITLE
Need help in parsing this http LogFormat log with goaccess for realtime view

### ISSUE THREAD

**Issue by SuMe1** [allinurl/goaccess#1504]
I am trying to read the below Apache httpd log format using goaccess. But the referrer url, OS, Browsers section, httpd status codes is still coming in as unknown. As far as I can see the order of the log-format is correct, but I could be missing something basic here.

+--------------------------------+
Apache LogFormat ->
`LogFormat "%h %l %u %t \"%r\" %>s %b %D %T \"%{Referer}i\" \"%{User-Agent}i\"" myview`
+--------------------------------+
Sample log file content..
```
172.20.161.242 - devweb [17/Jul/2019:06:34:10 -0400] "GET /pricingmodule/pricing_info.go?productid=60388 HTTP/1.1" 500 2719 562433 0 "-" "Java/1.6.0_30"

10.73.80.150 - - [17/Jul/2019:06:35:14 -0400] "GET /js/client_auto_complete.js HTTP/1.1" 200 43540 1470 0 "http://myserver/customview/customViewTaskController.go?action=getCustomViewTaskList" "Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 10.0; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; wbx 1.0.0; Zoom 3.6.0)"
```

+--------------------------------+
goaccess command line arguments:

`goaccess /home/meuser/httpd/logs/access.log -o /home/meuser/httpd/htdocs/http-load.html --log-format='%h %l %u [%d:%t %^] \"%r\" %>s %b %D %T \"%{Referer}i\" \"%{User-Agent}i\"' --date-format=%d/%b/%Y --time-format=%T --real-time-html`

**Comment by allinurl** [comment]
Please try this, it should work:

    goaccess /home/meuser/httpd/logs/access.log -o /home/meuser/httpd/htdocs/http-load.html --log-format='%h %^[%d:%t %^] "%r" %s %b %D %^ "%R" "%u"' --date-format=%d/%b/%Y --time-format=%T --real-time-html

**Comment by SuMe1** [comment]
thanks Gerardo. thats it. it works now.
