### ISSUE TITLE
CowAxess - GoAccess for Windows

### ISSUE THREAD

**Issue by tevkar** [allinurl/goaccess#1505]
> Please consider to list **CowAxess** as a GoAccess implementation on Windows:

[CowAxess](https://itefix.net/cowaxess) is a _GoAccess_ implementation for Windows systems. It is a packaging of GoAccess, Cygwin and many other related tools to make it a complete and ready-to-use solution for real-time web log analysis, all in a 4 MB package. We have followed standard instructions available at the GoAccess website.

CowAxess is available as a free solution licensed under simplified BSD. Enjoy!

**Comment by allinurl** [comment]
That's awesome, thanks for sharing this and having this implementation. I've added to the [**downloads page**](https://goaccess.io/download#distro). I'll keep this open for a while just as a reference as well.

**Comment by tevkar** [comment]
[CowAxess](https://itefix.net/cowaxess) is now updated to GoAccess 1.4.

**Comment by allinurl** [comment]
Thanks a lot for updating this!

**Comment by saptarshisd** [comment]
Unable to paste longer commands in cowaxess. ctrl+v and right click, both not working.

**Comment by allinurl** [comment]
@saptarshisd Not sure this is an issue with goaccess as I don't recall having a ctrl+v functionality. What was it doing before?

**Comment by saptarshisd** [comment]
I might have framed my question wrong apologies. The correct way to put it would be, Is there a way to paste commands in the cowaxess terminal? I have tried ctrl+v and right click, but none seemed to work. Hence curious

**Comment by tevkar** [comment]
CowAxess  is now updated with GoAccess 1.4.3 and Mintty is introduced as terminal with better cut/paste support . You may give it a try.

**Comment by allinurl** [comment]
@tevkar Thank you again for putting this together!

**Comment by tevkar** [comment]
CowAxess is now updated with GoAccess 1.5.1

**Comment by fbollon** [comment]
Hi,

has anyone ever managed to create a batch to schedule the generation of the static html report on a windows server?

**Comment by allinurl** [comment]
@fbollon create a batch as in running through all the logs?

**Comment by tevkar** [comment]
Hi,

cowAxess is now taken out of our solution offerings. It will not be maintained any longer.

Kind regards
itefix.net

**Comment by allinurl** [comment]
@tevkar Thanks a lot for supporting the Windows version all this time!

**Comment by tevkar** [comment]
Hi folks,

just to let you know cowAxess is made available again at our site [https://itefix.net/cowaxess](url). We can't guarantee timely updates though.

Kind regards,
Itefix team

**Comment by allinurl** [comment]
@tevkar Thanks a lot!

**Comment by tevkar** [comment]
Hi folks, Cowaxess is now provided as a timely-updated solution. You may consider to mention at your listings.

**Comment by allinurl** [comment]
@tevkar thanks veru much, I added this back to the [downloads page](https://goaccess.io/download#distro).

**Comment by frostyyyy1** [comment]
Why did this have to get taken down so that you can not use Cowaxess anymore? @tevkar 
Adleast leave legacy downloads up.

**Comment by frostyyyy1** [comment]
Since legacy downloads are no longer available, I’ve preserved the last public release here for archival and research purposes:
https://github.com/frostyyyy1/cowaxess-legacy

All licensing and copyright remain with the original authors.

**Comment by frostyyyy1** [comment]
@tevkar Thank you :D
