### ISSUE TITLE
All the configurations are ok, but still the Chinese report cannot be generated.

### ISSUE THREAD

**Issue by eryajf** [allinurl/goaccess#1506]
I am always unable to generate reports in Chinese in my own system. I have tried all kinds of schemes on the internet, but it still seems that I can't.

Execute the locale command as follows：

```
LANG=zh_CN.UTF-8
LC_CTYPE="zh_CN.UTF-8"
LC_NUMERIC="zh_CN.UTF-8"
LC_TIME="zh_CN.UTF-8"
LC_COLLATE="zh_CN.UTF-8"
LC_MONETARY="zh_CN.UTF-8"
LC_MESSAGES="zh_CN.UTF-8"
LC_PAPER="zh_CN.UTF-8"
LC_NAME="zh_CN.UTF-8"
LC_ADDRESS="zh_CN.UTF-8"
LC_TELEPHONE="zh_CN.UTF-8"
LC_MEASUREMENT="zh_CN.UTF-8"
LC_IDENTIFICATION="zh_CN.UTF-8"
LC_ALL=zh_CN.UTF-8
```

I also recompiled the project and tried it out `LANG="zh_CN.UTF-8" bash -c "goaccess -p /usr/local/goaccess/etc/goaccess/goaccess.conf /home/logs/blog/access.log -o /home/goaccess/k.html`
In this way, the results generated are all English interfaces. I don't know why

**Comment by allinurl** [comment]
Did you run `make install` as root? it should generate the translated files.

**Comment by eryajf** [comment]
Yes, I did. I don't know what you said about the translation document. I can check it out.

**Comment by allinurl** [comment]
Are you running goaccess as root too? It should install the `.mo` files under:

```
Making install in po
make[2]: Entering directory `/home/user/goaccess/po'
installing fr.gmo as /usr/local/share/locale/fr/LC_MESSAGES/goaccess.mo
installing es.gmo as /usr/local/share/locale/es/LC_MESSAGES/goaccess.mo
installing zh_CN.gmo as /usr/local/share/locale/zh_CN/LC_MESSAGES/goaccess.mo
installing ja.gmo as /usr/local/share/locale/ja/LC_MESSAGES/goaccess.mo
```

**Comment by Hill-98** [comment]
I encountered the same problem and solved it.
I use CentOS 8, which by default has only `en_ *` locale (-a` view by `llocale), the solution is to install all locales:` dnf install glibc-all-langpacks`, you can try.

**Comment by Hill-98** [comment]
@allinurl It proposed to add to the document: If you want to use the corresponding i18n system must support the corresponding language.

**Comment by allinurl** [comment]
@Hill-98 Thanks for reporting this. Are you referring to add this to the man page? 

Closing this as it appears the issue was missing locales on the machine.
