### ISSUE TITLE
I can not activate --real-time-html on Cron

### ISSUE THREAD

**Issue by SergioDG-YCC** [allinurl/goaccess#1508]
I can not make it work --real-time-html on Cron. This is my code:
`/usr/bin/goaccess -f /home/microtvar/web/XXXX/public_html/184/analytics/3633/nginx/access.log > /home/microtvar/web/XXXX/public_html/report3633.html --log-format=COMBINED --real-time-html`
If I remove it --real-time-html works perfectly, but without realtime...

**Comment by allinurl** [comment]
Are you using v1.3?

If so, can you please try this:

    /usr/bin/goaccess - /home/microtvar/web/XXXX/public_html/184/analytics/3633/nginx/access.log -o /home/microtvar/web/XXXX/public_html/report3633.html --log-format=COMBINED --real-time-html

**Comment by SergioDG-YCC** [comment]
Yes! This has worked for me. How often would you say that I should adjust the cron ?. I have noticed that the file remains the same because the GoAccess service is already active. The cron only works to monitor, and start it in case of system restart or some failure. Also, in parallel, I can generate different cron, with the previous code. How much RealTime can I start in parallel? Thank you!!

![Captura](https://user-images.githubusercontent.com/51941365/61647094-f6ed8d00-ac82-11e9-9ac2-d24a45d941be.JPG)

**Comment by allinurl** [comment]
> The cron only works to monitor, and start it in case of system restart or some failure.

Then you can use `@reboot  /path/to/shell.script` in the cron instead of specifying a time.

> How much RealTime can I start in parallel?

Please take a look at this [post](https://github.com/allinurl/goaccess/issues/625#issuecomment-272905761) to see how to run multiple instances of goaccess. 

Closing this, feel free to reopen it if needed.
