### ISSUE TITLE
how to make log format configuration my own log format?

### ISSUE THREAD

**Issue by oiluuurk** [allinurl/goaccess#1509]
We are using below own log format. but I have no idea how to set 00log-format & --date-format && --time-format.
2019/07/22 15:16:23 [info] 43891#43891: *72832 proxy [2001:db8:a01:2101:9::a102]:38302 connected to [2001:db8:a01:2053:4::16]:4430

**Comment by allinurl** [comment]
GoAccess requires the following fields:

> a valid IPv4/6 %h
> a valid date %d
> the request %r

You've got the date and IP but doesn't look like there's a request. Is this an access log?

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
