### ISSUE TITLE
Need help about log format like kind of IP=127.0.0.1

### ISSUE THREAD

**Issue by liuhongyuand** [allinurl/goaccess#1510]
This is my log.

`07-17-2019 00:24:27.984 ip=127.0.0.1  status=200  tenant=- user=- correlationId=-  request="GET /platform-webapp/ HTTP/1.1" userType=- requestInfo=- duration=0 bytes=3505 thread=http-nio-8080-exec-20 service=platform-webapp itemType=N-A itemOperation=READ dataLayer=N-A incomingItemCnt=- outgoingItemCnt=-`

Can you guide me what is the format? Thanks!!

I using like this:
log-format: %d %t ip=%h %^ %^ %^ %^ request=%m %U %^ %^ duration=%D %^ %^ %^ %^ %^ %^ %^ %^
date-format: %b-%d-%Y
time-format: %H:%M:%S

but get the error:
Token '07-17-2019' doesn't match specifier '%d'

**Comment by allinurl** [comment]
Assuming there's a valid IPv4/6, this should work:

    goaccess access.log --log-format='%d %t.%^ %^=%h %^=%s %^ %^=%e %^ %^"%r" %^ %^ %^=%T %^=%b %^=%^v %^' --date-format=%m-%d-%Y --time-format=%T --ignore-panel=OS --ignore-panel=BROWSERS --ignore-panel=REFERRING_SITES
