### ISSUE TITLE
Token '+0900]' doesn't match specifier '%h' 

### ISSUE THREAD

**Issue by kgs921** [allinurl/goaccess#1511]
HI

I can't figure out why goaccess error. What's wrong?

Please Help me

```
$goaccess test --log-format=VCOMMON –o report.html —real-time-html
Parsed 1 linesproducing the following errors:
Token '+0900]' doesn't match specifier '%h'
Format Errors - Verify your log/date/time format

$ goaccess --version
GoAccess - 1.3.

```
LOG sample
```
[24/Jul/2019:00:00:08 +0900] XXX.XXX.XXX.XXX TLSv1.2 ECDHE-RSA-AES256-GCM-SHA384 "GET / HTTP/2.0" 4
[24/Jul/2019:00:00:10 +0900] XXX.XXX.XXX.XXX TLSv1.2 ECDHE-RSA-AES256-GCM-SHA384 "GET /web-inf/component/font-awesome/fonts/fontawesome-webfont.woff2?v=4.7.0 HTTP/2.0" 77160
XXX.XXX.XXX.XXX - - [24/Jul/2019:00:13:13 +0900] "GET / HTTP/1.1" 200 139 "-" "Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36"

```

**Comment by allinurl** [comment]
Do these logs have the same log format? I see the first two have the same format but not the third one. Currently GoAccess has only capability to read one format.

**Comment by kgs921** [comment]
Thank you for answer

I installed apache2 with yum and Logformat is default in httpd.conf
-------------------------------------------------------------------------------
Log_config_module
	  LogFormat "%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" combined
    LogFormat "%h %l %u %t \"%r\" %>s %b" common

    <IfModule logio_module>
      # You need to enable mod_logio.c to use %I and %O
      LogFormat "%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\" %I %O" combinedio
    </IfModule>
-----------------------------------------------------------------------------------
daily_log
[25/Jul/2019:00:08:53 +0900] 123.123.123.123 TLSv1.2 ECDHE-RSA-AES256-GCM-SHA384 "GET /folder/folder2/folder3/file.xx?xx=xx123456 HTTP/2.0" 27370
[25/Jul/2019:00:08:57 +0900] 123.123.123.123 TLSv1.2 ECDHE-RSA-AES256-GCM-SHA384 "GET /folder/folder/folder/file.file?xxxx=xx123456 HTTP/2.0" 137940
123.123.123.123 - - [25/Jul/2019:00:09:43 +0900] "GET / HTTP/1.1" 200 139 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36"
--------------------------------------------------------------------------------------
Daily logs are running in this format

goaccess /logs/daily_log --log-format='[%d:%t %^] %h %r "%b" "%R"' --date-format=%d/%b/%Y --time-format=%T -o /www/report.html --real-time-html --daemonize
------------------------------------------------------------------------------------------------------------
When I ask the first question, I can not run it with the error message.
But now you're ready to run.
A report.html file is also created and can be viewed on the website
But I wonder if the analysis works.

**Comment by allinurl** [comment]
Sorry, I'm not sure I follow your question. Did you get it to parse your access log? Are you able to see the report?

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
