### ISSUE TITLE
slow processing when using db files as the database grow (Database currently around 8GB)

### ISSUE THREAD

**Issue by andresbarcenas** [allinurl/goaccess#1514]
Hello,

I used goaccess to parse the access log from multiple load balanced webservers. I have data from Feb until July of 2019 imported using the following command line but it feels like things are getting slower as the database gets bigger:

```
goaccess LOG_FILE --keep-db-files --load-from-disk --db-path=/home/logs/db/ --log-format=COMBINED -o /var/www/html/report/index.html
```

```
[root@las-elk01 temp]# du -hs /home/logs/db/
8.1G    /home/logs/db/
```

This is a test processing a file with 200 lines of logs

```
[root@las-elk01 temp]# goaccess test.log --keep-db-files --load-from-disk --db-path=/home/logs/db/ --log-format=COMBINED -o /var/www/html/report/test.html
[root@las-elk01 temp]# time goaccess test.log --keep-db-files --load-from-disk --db-path=/home/logs/db/ --log-format=COMBINED -o /var/www/html/report/test.html

real    0m32.128s
user    0m28.479s
sys     0m2.042s
```

Is this performance degradation normal as the db data gets larger? Is there anything I can do to speed the process of new data?

Thanks.

**Comment by allinurl** [comment]
Unfortunately this is one of the shortcoming of the current on-disk db storage. However, I'm currently working on a more robust version of it. Please stay tuned!

You could play with the db values on the config file, though, if you need fast processing and if it fits in memory, then I'd recommend using the default in-memory hash storage.

**Comment by allinurl** [comment]
The on-disk storage issue has been addressed. It now supports native on-disk persistence storage (no dependencies). New command line options are `--persist`, `--restore`, `--keep-last=<num_days>`. It also adds the ability to re-parse the same log(s) without counting data twice (see #334 or for exact details [**this post**](https://github.com/allinurl/goaccess/issues/334#issuecomment-272317226)).

[**v1.4**](https://goaccess.io/download) has been released.
