### ISSUE TITLE
Help with custom log format

### ISSUE THREAD

**Issue by SSalinasC** [allinurl/goaccess#1517]
Hi guys... I'm trying to parse this log format with goaccess (last version):

LogFormat "%{X-Forwarded-For}i,%l,%u,%t,\"%r\",%>s,%b,microsec,%D,WAS,%{WAS}e,jsess,%{JSESSIONID}C"

I must be able to parse log entries like this but no luck until now:

```
127.0.0.1,-,-,[01/Jan/2019:00:00:32 -0300],"POST /preengine/api/pesendapi HTTP/1.1",200,366,microsec,8847,WAS,myhost:8081,jsess,-
-,-,-,[01/Jan/2019:00:00:32 -0300],"GET /server-status?auto HTTP/1.1",200,4255,microsec,556,WAS,-,jsess,-
```

Please can you help me with the right command ?

Thanks in advance.
Regards
Sergio

**Comment by allinurl** [comment]
You would need a valid IP, however, it looks like the second sample line doesn't have one.

    goaccess access.log --log-format='%h,%^[%d:%t %^],"%r",%s,%b,%^,%D,%^,%v,%e,%^' --date-format=%d/%b/%Y --time-format=%T --ignore-panel=BROWSERS --ignore-panel=OS --ignore-panel=REFERRING_SITES

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
