### ISSUE TITLE
Date doesn't match specifier '%d' with NCSA Combined Log Format

### ISSUE THREAD

**Issue by m4ps** [allinurl/goaccess#1519]
Hello! Please, help. 
For me it looks like this should fit NCSA Combined Log Format, but it throws error

Example:

```
59.120.189.2 - - [06/Aug/2019:07:10:22 +0000] "POST / HTTP/1.1" 200 305 "https://127.0.0.1:3015/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36 OPR/62.0.3331.99"
213.21.55.10 - - [06/Aug/2019:07:10:34 +0000] "OPTIONS / HTTP/1.1" 204 0 "http://127.0.0.1:3015/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36"
213.21.55.10 - - [06/Aug/2019:07:10:38 +0000] "OPTIONS / HTTP/1.1" 204 0 "http://127.0.0.1:3015/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36"
```

Error:

```
 Token '06/Aug/2019' doesn't match specifier '%d'
```

Settings from Log Format Configuration.

```Log Format  %h %^[%d:%t %^] "%r" %s %b "%R" "%u"```

```Date Format %d/%b/%Y```
```Time Format -  %H:%M:%S```

**Comment by allinurl** [comment]
what's the output of your locale? e.g.,

    locale -a

**Comment by m4ps** [comment]
Oh thank you very much.
This 
```export LANG='en_US.UTF-8'``` helped

**Comment by allinurl** [comment]
You can always run:

    LANG="en_US.UTF-8" bash -c 'goaccess access.log --log-format=COMBINED'

Glad that worked! Closing this. Feel free to reopen it if needed.
