### ISSUE TITLE
sig11 in docker container

### ISSUE THREAD

**Issue by dmaziuk** [allinurl/goaccess#1523]
It seems in an alpine container build I can ether have TCB support or a static binary, but not both, and my goaccess built without `-static` coredumps with no useful info. Is there a background to this, is it possible to have a containerized version with tokyocabinet support?
thx

**Comment by allinurl** [comment]
This is related to #832. TCB is going away in favor of a more stable on-disk storage.

**Comment by dmaziuk** [comment]
Sorry, my search-fu failed.

I just checked, build without `-static` and without tcb works, so yeah: this is a TCB problem.
