### ISSUE TITLE
Can someone help me with the custom log format ?

### ISSUE THREAD

**Issue by mye770** [allinurl/goaccess#1524]
===========
Can someone help me with the custom log format ?

`- - 113.196.162.134 [09/Aug/2019:03:05:50 +0000] "POST /api/NotLoggedInApi?ApiInterface=indexhot HTTP/1.1" 404 33002 "http://www2.namieamuro.tw:8082/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36`

**Comment by allinurl** [comment]
Please try:

    goaccess access.log --log-format='%^ %^ %h [%d:%t %^] "%r" %s %b "%R" "%u"' --date-format=%d/%b/%Y --time-format=%T

**Comment by mye770** [comment]
Hi Gerardo,

Thank you for your help.

I tried it and start using GoAccess now, thank you.

Austin 祝您 新年快樂


<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
不含病毒。www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Gerardo O. <notifications@github.com> 於 2019年8月13日 週二 下午10:32寫道：
