### ISSUE TITLE
Extend browsers.list to support customized browser group mapping

### ISSUE THREAD

**Issue by favoyang** [allinurl/goaccess#1526]
Purpose: MicroMessenger is the browser name of WeChat, a very popular messaging/social network in China. It would be good to categorize browser MicroMessenger/VERSIONS (i.e. `MicroMessenger/7.0.5(0x17000523`) into a separated group named MicroMessenger (current under Other group).

However it could be argued that MicroMessenger is not actually a browser, but a webview component in iOS and other implementation in Android. So I think we could give user the choice that using the browsers.list to support customized browser group mapping.

```
[BROWSER_NAME]\t[CATEGORY]
MicroMessenger\t\t\t\tBrowsers

# OR 

[BROWSER_NAME]\t[CATEGORY]\t[GROUP]
MicroMessenger\t\t\t\tBrowsers\tMicroMessenger
```

Thought?

**Comment by allinurl** [comment]
Great point. As far as I recall, you should be able do the former, e.g., 

    MicroMessenger > MicroMessenger/7.0.5(0x17000523)

In your `browsers.list` file, you could write it as 

    MicroMessenger\t\tMicroMessenger

I like the idea of having multiple levels or at least another level as you mentioned above, the question is how would it look like in the HTML/CLI output... thoughts?

**Comment by favoyang** [comment]
Thanks. This works perfectly. 
```
MicroMessenger\t\tMicroMessenger
```

Would be good to update the header of browsers.list to include it as example. It feels like the group option is limited to one of `Crawlers`, `Browsers` and `Feeds` currently.

Maybe we don't need another layer, if we could aggregate the BrowserX/[VersionY] format automatically into Other > BrowserX? After all specific version after splash is not very useful.

However if we do want to add another level, some ascii character `└` can help. (I didn't come with a good solution for multiple levels.). Probably not that useful for browser panel, but could be useful for GEO panel to include City as another level (refs #1498 ).

![image](https://user-images.githubusercontent.com/125390/62996510-8b6c9900-be97-11e9-9359-300523793a8f.png)

**Comment by allinurl** [comment]
Awesome. I've added an extra note to the browsers.list file. Let me know what you think. Or feel free also to submit a PR if you think I'm missing something. 

Thanks for the suggestion about the ascii char, I can look into this if we decide to go for the additional level. Closing this, feel free to reopen it if needed.
