### ISSUE TITLE
Token '13/Aug/2019' doesn't match specifier '%d'

### ISSUE THREAD

**Issue by Jason-mor** [allinurl/goaccess#1528]
##### when I run the below command
```
goaccess access.log --log-format='%^\t%h\t%^\t%^\t%^\t%d:%t +0800\t%r\t%b\t%b\t%^\t%s\t%^\t%^\t%u\t%^' --time-format=%H:%M:%S --date-format=%d/%b/%Y
```
##### error
Token '13/Aug/2019' doesn't match specifier '%d'

##### nginx log format
```
'$http_host\t$server_addr\t$hostname\t$remote_addr\t$http_x_forwarded_for\t$time_local\t$request_uri\t$request_length\t$bytes_sent\t$request_time\t$status\t$upstream_addr\t$upstream_response_time\t$http_user_agent\t$scheme';
```
##### access.log
```
hello_test.com	127.0.0.1	test.local	127.0.0.1	-	13/Aug/2019:11:34:38 +0800	/0.js	738	201	0.002	304	127.0.0.1:8081	0.002	Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36	http

```

**Comment by allinurl** [comment]
Please try:

    goaccess access.log --log-format='%v\t%h\t%e\t%^\t%^\t%d:%t %^\t%U\t%^\t%b\t%T\t%s\t%^\t%^\t%u\t' --date-format=%d/%b/%Y --time-format=%T --http-protocol=no --http-method=no

**Comment by Jason-mor** [comment]
I use your command, but it doesn't work.
I also try the below configuration
```
goaccess access.log --log-format='%^\t%^\t%^\t%^\t%^\t%d:%t %^\t%^\t%^\t%^\t%^\t%^\t%^\t%^\t%^\t' --date-format=%d/%b/%Y --time-format=%T --http-protocol=no --http-method=no
```

#### My Environment
macVersion:10.14.5
goaccess:1.13

install by brew install goaccess

Thanks

**Comment by Jason-mor** [comment]
@allinurl  
brew install goaccess -s 
it also does't work.
Help solve it, thank you

**Comment by allinurl** [comment]
The command I posted works fine on v1.3 with the line you posted above. Could you please post/attach several lines? THanks.

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
