### ISSUE TITLE
Q: per year stats? per server?

### ISSUE THREAD

**Issue by dmaziuk** [allinurl/goaccess#1530]
I've a decade+ worth of logs from multiple servers: we have mirror sites as well as local HA clusters. So far I've imported ~300MB into the DB and the slowdown is already noticeable -- but it is to be expected. (And it's nowhere near as bad as elasticsearch on the same logs.)

So here's the wishlist/questions: 

1. Stats per server. E.g. if our mirror site X gets 0.0001% traffic, it's not worth maintaining. 

2. Stats per year. We make annual reports to various Powers That Be(tm) and stats like unique visitors per year and terabytes downloaded per year are always included. As above, separate reports for each year are not the same thing.

**Comment by dmaziuk** [comment]
To answer my own first question: I need to pre-process the logs into `vhost: ...` format, re-parse them and see.

**Comment by allinurl** [comment]
Thanks for the suggestions.

1. I think #117 would solve this. It's a feature I really need as well, so it's definitely on my priority list and probably the next big feature to incorporate.

2. This should be fairly trivial to add, this is a dup of  #1167. I've been working slowly on adding the new on-disk storage to goaccess to replace TC, then I can look into these smaller features. Stay tuned.

Closing this as they're part of existing issues. Feel free to reopen it if needed.
