### ISSUE TITLE
Token 'cable190-248-136-226.une.net.co' doesn't match specifier '%h'

### ISSUE THREAD

**Issue by desarrollocdb** [allinurl/goaccess#1531]
Hi, I have problems reading the log files of my web server

Log apache:

    cable190-248-136-226.une.net.co - - [14/Aug/2019:14:13:03 -0500] "GET /centro_serviciosv2/tiempo_session.php HTTP/1.1" 200 3831 "https://app.ciudaddonbosco.org/centro_serviciosv2/panel/index.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36"

Error:
Token 'cable190-248-136-226.une.net.co' doesn't match specifier '%h'

Format Log:
CustomLog ${APACHE_LOG_DIR}/access_app.log combined

Load goaccess:

    goaccess /var/log/apache2/access_app.log --log-format=COMBINED

**Comment by allinurl** [comment]
GoAccess requires a valid IPv4/6, so you would need to reverse lookup the host or log the IP.

**Comment by desarrollocdb** [comment]
Thanks, how can I make this possible on an Apache server?

**Comment by allinurl** [comment]
You will need to change your apache config to `HostnameLookups Off`

http://httpd.apache.org/docs/2.2/mod/core.html#hostnamelookups

**Comment by desarrollocdb** [comment]
Hi, I have reviewed and the current configuration is off. Should I change it to on?

**Comment by desarrollocdb** [comment]
Thanks, I solved it by changing the setting from off to Double.
