### ISSUE TITLE
How to parse multiple IP Addesses in the  %h (X-Forwaded-For)

### ISSUE THREAD

**Issue by Gecko483** [allinurl/goaccess#1533]
When parsing my IIS logs using the previously recommended format:

```
--log-format='%d %t.%^ "%h" %e %v %^ %m %U %q %s %^ %^ %L "%u" %R %^'
--date-format=%Y-%m-%d 
--time-format=%T
```

I came across another issue that is due to multiple IP Addresses listed in the %h column, in the following format:

    "111.222.333.444, 222.333.111.444"

The problem here is sometimes it has that format and other entries in the same log have the standard entry: "111.222.333.444"

I cannot find a way to parse this data within the same file that has both formats.

I have tried the following identifiers:
```
"%h"
"%h,%^"
```

I am still getting the error message:

    Token '111.222.333.444, 222.333.111.444' doesn't match specifier '%h'

Let me know your thoughts on this.

**Comment by allinurl** [comment]
Please take a look at the `~h` specifier in the [man page](https://goaccess.io/man#custom-log). I'd guess you need to use `~h{,"}`. Feel free to post a few sample lines from your log if that doesn't work.

**Comment by Gecko483** [comment]
Thanks for taking the time to link the page and send me in the right direction. I had read over the man page and originally tried the ~h designation but reverted back tot he %h.

This is also verifying that all of our site logs are the same format as well.

**Comment by allinurl** [comment]
np, feel free to post a few lines from your log and I can try looking into the format.

**Comment by Gecko483** [comment]
It is working quite well i have reporting now to analyze the web logs. the format you posted a reference to works great!

**Comment by allinurl** [comment]
Awesome. Closing this, feel free to reopen it if needed.
