### ISSUE TITLE
Trying to exclude a specific user agent (Web Site Monitor)

### ISSUE THREAD

**Issue by Gecko483** [allinurl/goaccess#1536]
I was reading how you had added the ability to add a list of browsers in a text file, and was trying to use this as a way to omit our uptime requests from the log parsing.

We use NodePing, so i created a file called browsers.txt, using your demo file and added a line to the top:
NodePing                                          Crawler

I was using the following command in bash:

    bash-4.4$ goaccess /cygdrive/e/temp/goaxess/*.log --log-format='%d %t.%^ ~h{," } %e %v %^ %m %U %q %s %^ %^ %L "%u" %R %^' --date-format=%Y-%m-%d --time-format=%T --http-protocol=no -o /cygdrive/e/temp/ws_all_report_20190919.html --real-time-html --browsers-file=/cygdrive/e/temp/browsers.txt --ignore-crawlers

It still has the same mount of requests over all with or without the last two switches in the command line (I think this is intended to show the total number of requests without filtering the browsers file)

I am just looking for confirmation that this is the way to execute this type of result

Let me know what you think

**Comment by allinurl** [comment]
Please try setting it as `Crawlers` instead of `Crawler`. Also make sure it is tab delimited e.g.,

    NodePing\t\tCrawlers

that is, 

    NodePing		Crawlers

**Comment by Gecko483** [comment]
I added the tab delimiter in between the name and the type instead of spaces.

I also see that it removes the top requested file based on the browsers.txt file.

This is what i was looking for 

Thanks!
