### ISSUE TITLE
Real Time w/SSL on macOS "Stopping WebSocket server..."

### ISSUE THREAD

**Issue by cylott** [allinurl/goaccess#1537]
I am having a hell of a time getting goaccess to use my ssh key. Steps:

Install goaccess from macports
Generate ssl keys for the host domain (the domain that serves the goaccess html file)
Configure for log format
Run goaccess without ssl, works fine
Run with ssl, exits with no errors

`goaccess --log-format='%v %h %^[%d:%t %^] "%r" %s %b' --date-format='%d/%b/%Y' --time-format='%H:%M:%S' -o /opt/www/domain.com/go.html --real-time-html --port=XXXX /var/log/apache2/access_log --ssl-cert=/opt/local/etc/letsencrypt/live/www.domain.com/fullchain.pem --ssl-key=/opt/local/etc/letsencrypt/encrypt/live/www.domain.com/privkey.pem`

Stopping WebSocket server...

If I remove the SSL commands, it works fine. I have also tried with many permutations of the ws-url option such as:

`--ws-url=wss://domain.com:XXXX`

Please help!

**Comment by cylott** [comment]
Thank you so much for your help. Yes, this user has write to /tmp

`server:~ user$ touch /tmp/test`

**Comment by allinurl** [comment]
Are you able to run goaccess as root?

**Comment by cylott** [comment]
Strange, I thought I was running as root. This seems to do the trick.
