### ISSUE TITLE
how to parse custom log format that contains a pipe as delimiter

### ISSUE THREAD

**Issue by hxwang1024** [allinurl/goaccess#1541]
my log format as follow:

 **03/Sep/2019:10:04:08 +0800 | 10.10.10.10 | http | 304 | 192.168.2.12 | - | www.hello.com | - | - | GET / HTTP/1.1 | 0 | - | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/547.36 | - | 0.017 | - | - | -**

Please can you help me with the right command ?

Thanks in advance.
Regards

**Comment by allinurl** [comment]
Looking into this. Dup of #1303

**Comment by allinurl** [comment]
This has been fixed. Feel free to build from [**development**](https://github.com/allinurl/goaccess#build-from-github-development) and let me know how it goes. It will be deployed in the upcoming version.
