### ISSUE TITLE
question about Requested Files statistics

### ISSUE THREAD

**Issue by halcyon22** [allinurl/goaccess#1542]
In the "Requested Files" panel, what does the line with Method "---" represent? 

Method "---" has the largest share of requests when running goaccess on my apache logfile, so I'm concerned that I'm missing the actual URL of those requests.

Method "---" is line 26 in "Requested Files" panel of [the real-time demo](https://rt.goaccess.io/).

It also appears as the second line on [the goaccess homepage](https://goaccess.io/):
![goaccess-cli-no-method](https://user-images.githubusercontent.com/2044014/64198300-9b9be680-ce4d-11e9-8334-93eacc0dbaea.png)

**Comment by allinurl** [comment]
It could be time outs, or pretty much anything where there wasn't a proper request. e.g.,

    host.com:80 176.86.241.101 - - [03/Sep/2019:14:39:13 -0500] "-" 408 0 "-" "-" 16

**Comment by halcyon22** [comment]
Thanks for your response!
I've filtered out all lines with no method (`"-"`), so I wonder if something about certain lines - an usual character perhaps - could be causing the method from being parsed correctly.
I'll try to narrow down the problem.

**Comment by allinurl** [comment]
In my case, I see that the majority are bogus bots hitting the server.

**Comment by halcyon22** [comment]
I've narrowed the problem lines down to a representative sample:
```
10.255.0.2 - - [11/Jul/2019:23:59:59 -0500] "GET /" 200 23287 
10.255.0.4 - - [11/Jul/2019:23:59:58 -0500] "GET /" 200 15575 
10.255.0.4 - - [11/Jul/2019:23:59:57 -0500] "GET /" 200 23287 
10.255.0.3 - - [11/Jul/2019:23:59:57 -0500] "GET /" 200 23759 
```
This corresponds to the standard Apache HTTP format of `"%h %l %u %t \"%r\" %>s %b `. I run goaccess on the above with the following command:
```
goaccess -f example.log --time-format="%T" --date-format="%d/%b/%Y" --log-format=COMMON
```
Doing so results in the following:

```
   2 - Requested Files (URLs)                                                                                                                                                                                                     Total: 1/1

 Hits      h% Vis.      v% Tx. Amount Mtd Proto    Data
 ---- ------- ---- ------- ---------- --- -------- ----
    4 100.00%    3 100.00%  83.89 KiB --- ---      -
```
What am I doing wrong?

**Comment by allinurl** [comment]
`\"%r\"` should display the method, request and protocol according to [this](https://httpd.apache.org/docs/2.4/logs.html). Those seems like were invalid lines as they did not pass the protocol. Are all of your requests this way?

**Comment by halcyon22** [comment]
All of the requests to `/` in my log do lack the protocol, which I should have noticed as you did. Thanks very much for your assistance.
