### ISSUE TITLE
What is the log-format for the 'access.log format'

### ISSUE THREAD

**Issue by 123mja** [allinurl/goaccess#1543]
What is the log-format for the 'access.log format'?
Thanks

```
goenhanced.com Z2IMvkhUKRiwMB4gqyuY4A - - [04/Sep/2019:16:27:32 +0000] "GET / HTTP/1.1" 200 595 "-" "Mozilla/5.0 (iPhone; CPU iPhone OS 7_0 like Mac OS X) AppleWebKit/537.51.1 (KHTML, like Gecko) Version/7.0 Mobile/11A465 Safari/9537.53 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)" {393:787,46284}
goenhanced.com yqwlTF0wgYj56u0/h4LxtQ - - [04/Sep/2019:16:27:40 +0000] "GET /robots.txt HTTP/1.1" 404 370 "-" "Mozilla/5.0 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)" {247:569,46527}
goenhanced.com iBplFy9acUuoF8dP4dqwFw - - [04/Sep/2019:16:27:43 +0000] "GET /contact.jpg HTTP/1.1" 200 14135 "-" "Mozilla/5.0 (iPhone; CPU iPhone OS 7_0 like Mac OS X) AppleWebKit/537.51.1 (KHTML, like Gecko) Version/7.0 Mobile/11A465 Safari/9537.53 BingPreview/1.0b" {316:14415,13727}
```

**Comment by allinurl** [comment]
Can you please describe the fields you've got in there? Thanks

**Comment by 123mja** [comment]
Hi Gerardo,

thanks for the assistance. My best guest to describe the fields is:

1 myserver.com %v:
2 kfr3RdqIeZ4VvnDkk3TLjw %^
3 - %^
4 - %^
5 [04/Sep/2019:07:58:02 +0000] [%d:%t %^]
6 "GET / HTTP/1.1" "%r"
7 200 %s
8 595 %b
9 "-" %^
10 "Mozilla/5.0 (compatible; hrankbot/1.0; +https://www.hrank.com/bot)" "%u"
11 {239:732,79529}  %^


So, I do not know the meaning of fields 2,3,4,9,11 therefore I tried with
%^ , but still I got error when parsin
My log-format %v:%^ %^ %^ [%d:%t %^] "%r" %s %b %^ "%u" %^
But I am getting this error

*See output:*

./myserver.com.log

Parsed 10 lines producing the following errors:



Token 'robots.txt HTTP/1.1" 404 370 "-" "Mozilla/5.0 (compatible;
bingbot/2.0; +http' doesn't match specifier '%d'

Token 'HTTP/1.1" 200 595 "-" "Mozilla/5.0 (compatible; bingbot/2.0; +http'
doesn't match specifier '%d'

Token 'robots.txt HTTP/1.1" 404 370 "-" "Mozilla/5.0 (compatible;
bingbot/2.0; +http' doesn't match specifier '%d'

Token 'wp-login.php HTTP/1.1" 404 370 "-" "Mozilla/5.0 (X11; Ubuntu; Linux
x86_64; rv' doesn't match specifier '%d'

Token 'HTTP/1.1" 200 595 "-" "Mozilla/5.0 zgrab/0.x (compatible;
Researchscan/t13rl; +http' doesn't match specifier '%d'

Token 'HTTP/1.1" 200 595 "-" "Mozilla/5.0 (compatible; hrankbot/1.0;
+https' doesn't match specifier '%d'

Token 'HTTP/1.1" 200 595 "-" "Mozilla/5.0 (compatible; hrankbot/1.0;
+https' doesn't match specifier '%d'

Token 'HTTP/1.1" 200 595 "-" "Mozilla/5.0 (X11; Linux x86_64)
AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36
OPR/62.0.3331.99" {536' doesn't match specifier '%d'

Token 'admin/ HTTP/1.1" 404 370 "-" "Mozilla/5.0 (X11; Linux x86_64)
AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36
OPR/62.0.3331.99" {542' doesn't match specifier '%d'

Token 'robots.txt HTTP/1.1" 404 370 "-" "Mozilla/5.0 (compatible;
AhrefsBot/6.1; +http' doesn't match specifier '%d'

Format Errors - Verify your log/date/time format

*See input file*:

myserver.com +iPZ517V58oZvoeK+Dk8BA - - [04/Sep/2019:00:17:42 +0000] "GET
/robots.txt HTTP/1.1" 404 370 "-" "Mozilla/5.0 (compatible; bingbot/2.0; +
http://www.bing.com/bingbot.htm)" {251:569,43717}

myserver.com vZtcOupn4rDNj4BG/GaNTw - - [04/Sep/2019:00:17:47 +0000] "GET /
HTTP/1.1" 200 595 "-" "Mozilla/5.0 (compatible; bingbot/2.0; +
http://www.bing.com/bingbot.htm)" {273:787,39784}

myserver.com fXdZvlIHJVIT6nCSqIoFrw - - [04/Sep/2019:00:17:52 +0000] "GET
/robots.txt HTTP/1.1" 404 370 "-" "Mozilla/5.0 (compatible; bingbot/2.0; +
http://www.bing.com/bingbot.htm)" {251:569,39733}

myserver.com Djp8ZoYIRKxW5SwH0obFBg - - [04/Sep/2019:07:17:29 +0000] "GET
/wp-login.php HTTP/1.1" 404 370 "-" "Mozilla/5.0 (X11; Ubuntu; Linux
x86_64; rv:62.0) Gecko/20100101 Firefox/62.0" {184:533,71901}

myserver.com 69/ll3ojrUEdw890Ch+ldw - - [04/Sep/2019:07:34:11 +0000] "GET /
HTTP/1.1" 200 595 "-" "Mozilla/5.0 zgrab/0.x (compatible;
Researchscan/t13rl; +http://researchscan.comsys.rwth-aachen.de)"
{754:2283,66688}

myserver.com kfr3RdqIeZ4VvnDkk3TLjw - - [04/Sep/2019:07:58:02 +0000] "GET /
HTTP/1.1" 200 595 "-" "Mozilla/5.0 (compatible; hrankbot/1.0; +
https://www.hrank.com/bot)" {239:732,79529}

myserver.com 53Xz9ZgTRSxxTlIZOeKPpg - - [04/Sep/2019:09:35:42 +0000] "GET /
HTTP/1.1" 200 595 "-" "Mozilla/5.0 (compatible; hrankbot/1.0; +
https://www.hrank.com/bot)" {239:732,64154}

myserver.com /IzMewsUilJdu5SEmqco2g - - [04/Sep/2019:11:17:31 +0000] "GET /
HTTP/1.1" 200 595 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36
(KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36 OPR/62.0.3331.99"
{536:787,515224}

myserver.com /IzMewsUilJdu5SEmqco2g - - [04/Sep/2019:11:17:31 +0000] "GET
/admin/ HTTP/1.1" 404 370 "-" "Mozilla/5.0 (X11; Linux x86_64)
AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36
OPR/62.0.3331.99" {542:569,46807}

myserver.com TG0bZih9M7+UJ5JUI2z5tA - - [04/Sep/2019:14:12:40 +0000] "GET
/robots.txt HTTP/1.1" 404 370 "-" "Mozilla/5.0 (compatible; AhrefsBot/6.1; +
http://ahrefs.com/robot/)" {847:2070,65912}

myserver.com Ra6novx+Q27qLg3nfgVq6w - - [04/Sep/2019:14:12:41 +0000] "GET /
HTTP/1.1" 200 595 "-" "Mozilla/5.0 (compatible; AhrefsBot/6.1; +
http://ahrefs.com/robot/)" {837:2288,46175}

myserver.com 9/txbsRVR1cxmfyQSWoNLA - - [04/Sep/2019:15:50:07 +0000] "GET
/wp-login.php HTTP/1.1" 404 370 "-" "Mozilla/5.0 (X11; Ubuntu; Linux
x86_64; rv:62.0) Gecko/20100101 Firefox/62.0" {184:533,74626}

myserver.com IHuhD1+wejlhmLFxE9tXrg - - [04/Sep/2019:16:27:23 +0000] "GET
/robots.txt HTTP/1.1" 404 370 "-" "Mozilla/5.0 (compatible; bingbot/2.0; +
http://www.bing.com/bingbot.htm)" {247:569,59053}

myserver.com Z2IMvkhUKRiwMB4gqyuY4A - - [04/Sep/2019:16:27:32 +0000] "GET /
HTTP/1.1" 200 595 "-" "Mozilla/5.0 (iPhone; CPU iPhone OS 7_0 like Mac OS
X) AppleWebKit/537.51.1 (KHTML, like Gecko) Version/7.0 Mobile/11A465
Safari/9537.53 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)"
{393:787,46284}

myserver.com yqwlTF0wgYj56u0/h4LxtQ - - [04/Sep/2019:16:27:40 +0000] "GET
/robots.txt HTTP/1.1" 404 370 "-" "Mozilla/5.0 (compatible; bingbot/2.0; +
http://www.bing.com/bingbot.htm)" {247:569,46527}
myserver.com iBplFy9acUuoF8dP4dqwFw - - [04/Sep/2019:16:27:43 +0000] "GET
/contact.jpg HTTP/1.1" 200 14135 "-" "Mozilla/5.0 (iPhone; CPU iPhone OS
7_0 like Mac OS X) AppleWebKit/537.51.1 (KHTML, like Gecko) Version/7.0
Mobile/11A465 Safari/9537.53 BingPreview/1.0b" {316:14415,13727}

**Comment by allinurl** [comment]
Seems like you are missing the client IP. GoAccess requires the following fields:

> a valid IPv4/6 %h
> a valid date %d
> the request %r

**Comment by 0bi-w6n-K3nobi** [comment]
Try this, in `goaccess.conf`:

`time-format %H:%M:%S` or in same way `time-format %T`
`date-format %d/%b/%Y`
`log-format %v %^[%d:%t %^] "%r" %s %b "%R" "%u" %^`

**notes:**
GoAccess requires a valid IPv4/6 `%h`.
However ask @allinurl about a alternative version without this obligation.
Already seen this here.

I suposse that have a referer field `%R`, but if you don't care for it then change for `%^`.

All field with double quote must be define with double quote.
This is case of `%R`.

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
