### ISSUE TITLE
GoAccess submitting aggregate data to MySQL

### ISSUE THREAD

**Issue by MarkMessa** [allinurl/goaccess#1544]
Is it possible to make GoAccess count views from Apache log (single server) in real-time and submit the aggregate data to MySQL according some threshold? (ex: each 5 min or 1KB)

**Comment by allinurl** [comment]
It's not possible. Could you please describe a use case for this? Thanks.

**Comment by MarkMessa** [comment]
> Could you please describe a use case for this?

Suppose you wanna count views and update MySQL aggregate table out of the client request cycle.  
It seems that the most common way to achieve that is via ELK stack. Unfortunately, for a single server, ELK stack is to much complicated. Therefore, I'm looking for lighter alternatives.

**Comment by allinurl** [comment]
I'm working on a more robust on-disk storage which more likely will support wither postgres or mysql. This will replace the existing on-disk implementation. Please stay tuned for the upcoming release.

**Comment by MarkMessa** [comment]
@allinurl Mind to give more details?
- Is this gonna be an improvement of GoAccess or it will be a completely new web analytics software?
- Still FOSS?
- Still lightweight?

**Comment by allinurl** [comment]
It's just a change on the current on-disk implementation. Always FOSS, and lightweight too.

**Comment by MarkMessa** [comment]
Any release date forecast?

**Comment by JanUrlaub** [comment]
That would be a really nice to have.
A changeable DSN like mysql://user@pasword:server/database insteat of slite3://path/to/folder
