### ISSUE TITLE
kernel message: goaccess trap divide error

### ISSUE THREAD

**Issue by m33m33** [allinurl/goaccess#1549]
When running goaccess 1.3 daemonized, I ran in this issue today.

The web page with realtime stats was empty, on disk the realtime html and database look good.

In the syslog I see :
traps: goaccess[4010] trap divide error ip:559ca6039673 sp:7fff900f9170 error:0 in goaccess[559ca6020000+97000]
traps: goaccess[4105] trap divide error ip:5578b589e673 sp:7fff666347c0 error:0 in goaccess[5578b5885000+97000]
traps: goaccess[4161] trap divide error ip:56081b72a673 sp:7ffe64b5f5d0 error:0 in goaccess[56081b711000+97000]

Restarting goaccess didn't fix the problem. 

I had to clean the database and realtime html file to start from scratch.

No idea on how to reproduce the issue (keep it running ?)

**Comment by allinurl** [comment]
Does it break when not daemonized? are you able to reproduce this using the in-memory storage? Please run it through `strace` and attach the result here. Thanks.

**Comment by m33m33** [comment]
Can't reproduce it yet. I suspect a corruption of goaccess file storage.

Let's close this ticket, I will reopen it if needed.
