### ISSUE TITLE
Allow %h (or a new format specifier) to accept looked-up hostnames

### ISSUE THREAD

**Issue by zaitseff** [allinurl/goaccess#1552]
First off, thank you for writing GoAccess and releasing it!

Could you please implement the ability to have `%h` (or perhaps a new format specifier like `%H`) accept hostnames that have already been looked up.  In other words, to be able to accept log files where IP addresses are not recorded but the looked-up names are:

```
crawl-66-249-65-222.googlebot.com - - [21/Sep/2019:09:00:06 +1000] "GET /robots.txt HTTP/1.1" 200 571 "-" "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"
```

When I run `goaccess` with such log files, it complains with something like:

```
Parsed 10 lines producing the following errors:

Token 'crawl32.bl.semrush.com' doesn't match specifier '%h'
Token '141-8-143-196.spider.yandex.com' doesn't match specifier '%h'
Token 'msnbot-207-46-13-178.search.msn.com' doesn't match specifier '%h'
Token '141-8-143-196.spider.yandex.com' doesn't match specifier '%h'
Token '141-8-143-196.spider.yandex.com' doesn't match specifier '%h'
Token '141-8-143-196.spider.yandex.com' doesn't match specifier '%h'
Token '141-8-143-196.spider.yandex.com' doesn't match specifier '%h'
Token '141-8-143-196.spider.yandex.com' doesn't match specifier '%h'
Token '141-8-143-196.spider.yandex.com' doesn't match specifier '%h'
Token '141-8-143-196.spider.yandex.com' doesn't match specifier '%h'

Format Errors - Verify your log/date/time format
```

(I tried to search whether someone had already filed this issue, but could not find anything to match).

Thanks!

**Comment by allinurl** [comment]
I can look into this, however, as a workaround, you could try building from [**development**](https://goaccess.io/download#build) and pass `--no-ip-validation`.

**Comment by pepalogik** [comment]
I have just discovered GoAccess and wanted to give it a try, but this issue seems to render it unusable.

**Comment by allinurl** [comment]
Closing this as v1.4 will have the ability to parse these logs through the use of `--no-ip-validation`. 
 Feel free to test it out from [**development**](https://github.com/allinurl/goaccess#build-from-github-development) else will be pushed out in the upcoming release.
