### ISSUE TITLE
k8s nginx real-time log always hang with 4w data

### ISSUE THREAD

**Issue by rayer4u** [allinurl/goaccess#1556]
I'm using goaccess to analysis a small k8s cluster ingress nginx log. It is always hang at 4w data, the server is still  generate log. After stop with control-c, the log report is successful generate with only the 4w data. I have tryed many times, no wrong only hang. 
Is any thing I can do to solve this problem?

```shell
root@master1:~# kubectl -n ingress-nginx logs  -f --tail=0 ingress-nginx-controller-mdxbw | awk '$1~/[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+/' | docker run --rm -i -v ~/tmp:/out allinurl/goaccess --log-format="%^ %^ [%h] %^ %^ [%d:%t %^] \"%r\" %s %b \"%R\" \"%u\" %^ %^ [%v] %^:%^ %^ %T %^ %^" --date-format="%d/%b/%Y" --time-format="%H:%M:%S" -a -real-time-html -o /out/log_report.html -
Parsing... [614] [34/s]
Parsing... [20976] [28/s]
Parsing... [27681] [27/s]
Parsing... [34260] [27/s]
Parsing... [41269] [26/s]
Parsing... [41269] [25/s]
```

**Comment by allinurl** [comment]
Are you using the on-disk storage or in-memory? Anything in the logs? are you able to run it through `strace(1)`?

Thanks

**Comment by rayer4u** [comment]
Sorry, I'm already know the problem is not from goaccess. `kubectl logs` hang but `docker log` is working well. I think `kubectl logs` is not a right tool to continuous generate logs
