### ISSUE TITLE
Podcast-related browser list

### ISSUE THREAD

**Issue by rahra** [allinurl/goaccess#1557]
I run a Wordpress blog where I also host a podcast. The statistics shows more the 50% of unknown browsers. So I collected a browser list which contains most user agents which are podcast related, i.e. podcast apps, media players, and podcast directories/crawlers (Itunes, Stitcher,...). This highly improved to result.
Maybe you want to integrate this into your repository, list is attached.

Best regards,
Bernhard

[podcast.list.txt](https://github.com/allinurl/goaccess/files/3667422/podcast.list.txt)

**Comment by allinurl** [comment]
Thanks for sharing this. Would you be able to submit a PR?

**Comment by rahra** [comment]
Just filed a PR.

**Comment by allinurl** [comment]
Merged. Thank you!
