### ISSUE TITLE
Apt-get update goaccess configured multiple times?

### ISSUE THREAD

**Issue by jockebq** [allinurl/goaccess#1564]
Hi,

When doing apt-get update I get this in the log:

`W: Target Packages (main/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list.d/goaccess.list:1 and /etc/apt/sources.list.d/goaccess.list:2
W: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list.d/goaccess.list:1 and /etc/apt/sources.list.d/goaccess.list:2
W: Target Translations (main/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list.d/goaccess.list:1 and /etc/apt/sources.list.d/goaccess.list:2
W: Target Packages (main/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list.d/goaccess.list:1 and /etc/apt/sources.list.d/goaccess.list:3
W: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list.d/goaccess.list:1 and /etc/apt/sources.list.d/goaccess.list:3
W: Target Translations (main/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list.d/goaccess.list:1 and /etc/apt/sources.list.d/goaccess.list:3
W: Target Packages (main/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list.d/goaccess.list:1 and /etc/apt/sources.list.d/goaccess.list:2
W: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list.d/goaccess.list:1 and /etc/apt/sources.list.d/goaccess.list:2
W: Target Translations (main/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list.d/goaccess.list:1 and /etc/apt/sources.list.d/goaccess.list:2
W: Target Packages (main/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list.d/goaccess.list:1 and /etc/apt/sources.list.d/goaccess.list:3
W: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list.d/goaccess.list:1 and /etc/apt/sources.list.d/goaccess.list:3
W: Target Translations (main/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list.d/goaccess.list:1 and /etc/apt/sources.list.d/goaccess.list:3`

How do I fix this? Mostly it is annoying!

**Comment by allinurl** [comment]
Have you tried any of [these](https://askubuntu.com/a/846162)?

**Comment by XOR-LIFE** [comment]
go to `/etc/apt/sources.list.d/`
and check the duplicate file/line and delete it.

**Comment by allinurl** [comment]
Any updates on this?
