### ISSUE TITLE
Ubuntu: unrecognized option '--ssl-cert' 

### ISSUE THREAD

**Issue by myoriginalusername** [allinurl/goaccess#1568]
Apologies if I'm missing something straightforward here but I'm not able to use the `--ssl-cert` or `--ssl-key` commands.

The error I get is:
````
goaccess: unrecognized option '--ssl-cert'
````
goaccess is installed on an Ubuntu 18.04 LTS box and I made sure to install it from the Official GoAccess Debian & Ubuntu repository (i.e. deb.goaccess.io) as I know the standard Ubuntu repo can be outdated. 

Any ideas?

**Comment by allinurl** [comment]
What's the output of `goaccess -V`?

**Comment by myoriginalusername** [comment]
Nevermind. User error on my part as I had two conflicting installations of goaccess.
