### ISSUE TITLE
Unknown operating system

### ISSUE THREAD

**Issue by szazo** [allinurl/goaccess#1573]
Firstly thank you for your hard work.

I parsed an IIS log file (in W3C format), and in the result, most of the operating system was "Unknown"

In the log file, user agents stored in the following format:
`Mozilla/5.0+(Windows;+U;+Windows+NT+6.0;en-US;+rv:1.9.2)+Gecko/20100115+Firefox/3.6)`

I checked the source and found that however in the code (parser.c line 1226) there is a comment that `+` symbols should be decoded, they are not actually decoded in `decode_url()`:

```
      /* Make sure the user agent is decoded (i.e.: CloudFront)
       * and replace all '+' with ' ' (i.e.: w3c) */
      logitem->agent = decode_url (tkn);
```
If I add the following line after this, then user agents are successfully parsed:
```
      logitem->agent = char_replace (logitem->agent, '+', ' ');
```

**Comment by allinurl** [comment]
Thanks for reporting this. Interesting, are you in the latest version?

**Comment by szazo** [comment]
I am using 1.3 version from release page (GoAccess 1.3 - Friday, November 23, 2018)

Now I checked `parser.c` on master, it also doesn't contain code for decoding `+` into space for the UserAgent

**Comment by humaita-github** [comment]
Hi, I can confirm that this bug is still present in version 1.4, and I can confirm that the suggested change fixes the problem. So it would be great if someone could add it to the next version (its not in master either)

**Comment by allinurl** [comment]
@humaita-github thanks for the heads up on this. I'll push a fix for the upcoming version. I added this to the v1.4.1 milestone.

**Comment by allinurl** [comment]
This has been [fixed](https://github.com/allinurl/goaccess/commit/ae98eb91a9ae403c4910ec5f36bddf2a67461fb4) and will be pushed out in the upcoming release pretty soon. Stay tuned.

@szazo Just a heads up on the fixed you proposed above. It will read from an invalid address since the memory is not allocated, so please use the fixed from upstream.

**Comment by szazo** [comment]
thank you @allinurl :)
