### ISSUE TITLE
Custom Log with delimiter didn't work

### ISSUE THREAD

**Issue by sunardo** [allinurl/goaccess#1574]
Hi,

I have costum log Apache HTTPD:
`LogFormat "%{%Y%m%d,%H%M%S}t,%{msec_frac}t,%h,%D,\"%r\",%B,\"%{Referer}i\",\"%{User-agent}i\",%P,%v,%>s"`

Output: 
`20191018,133018,277,202.51.110.214,1171,"GET / HTTP/1.1",3503,"-","Mozilla/5.0 (redhat-x86_64-linux-gnu) Siege/3.0.8",1127,mediasport.id,200`

I try with this but It didn't work :
```
goaccess -f access.log --log-format='%{%Y%m%d,%H%M%S}t,%{msec_frac}t,%h,%D,\"%r\",%B,\"%{Referer}i\",\"%{User-agent}i
\",%P,%v,%>s'  --date-format='%Y%m%d' --time-format='%H%M%S' -o ~/var/www/html/report/report.html
```

Please help me

Thank you.

**Comment by allinurl** [comment]
Please try:

    goaccess access.log --log-format='%d,%t,%^,%h,%D,"%r",%b,"%R","%u",%^,%v,%s' --date-format=%Y%m%d --time-format=%H%M%S

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
