### ISSUE TITLE
Errors: unexpected token: '!' + AreaChart is not defined

### ISSUE THREAD

**Issue by gawlk** [allinurl/goaccess#1575]
Hi,

I tried to play a little bit with this wonderful analyzer, I must admit that it was a bit a struggle but I got it working. The page loads but sadly it won't show any graphs and print two erros in the console:

- SyntaxError: unexpected token: '!'
- ReferenceError: AreaChart is not defined

Does anyone have any idea how to fix it ?

Thanks,

K

**Comment by allinurl** [comment]
I'm guessing this is related to #1570. Did you build from development/upstream?

**Comment by gawlk** [comment]
Indeed !

**Comment by romanek-adam** [comment]
Same here on sources from master. Reverted back to v1.3 and it's all good.

**Comment by allinurl** [comment]
This should be fixed per #1595.

Closing it, feel free to reopen it if needed.
