### ISSUE TITLE
Format Error

### ISSUE THREAD

**Issue by inisis** [allinurl/goaccess#1583]
Hi,

    goaccess is amazing!
    But I encountered a problem,

    I use this 'goaccess -a -d -f /var/log/nginx/access.log --log-format=%h %^[%d:%t %^] "%r" %s %b "%R" "%u" %D --date-format=%d/%b/%Y --time-format=%T -o /root/report.html --real-time-html' to parse my log, but I get following error.

Token '185.56.159.254 - - [31/Oct/2019:06:35:30 +0800] "GET / HTTP/1.1" 200 11 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36"' doesn't match specifier '%h'

 I am using goaccess 1.2, Can you help me out.

Best wishes

**Comment by allinurl** [comment]
Please enclose the log-format in single quotes:

    goaccess -a -d -f /var/log/nginx/access.log --log-format='%h %^[%d:%t %^] "%r" %s %b "%R" "%u" %D' --date-format=%d/%b/%Y --time-format=%T -o /root/report.html --real-time-html
