### ISSUE TITLE
 Problem with the log format

### ISSUE THREAD

**Issue by fmartineza** [allinurl/goaccess#1585]
Hello
The first thank your help
I have the following error
 Token for '% b' specifier is NULL.

I have the default format after installing ssl (yum install mod_ssl)

**Comment by fmartineza** [comment]
I use
CustomLog logs/ssl_request_log \
          "%t %h %{SSL_PROTOCOL}x %{SSL_CIPHER}x \"%r\" %b"

**Comment by allinurl** [comment]
Can you please post a few lines from your access log? Thanks

**Comment by allinurl** [comment]
For `%{SSL_PROTOCOL}x` `%{SSL_CIPHER}x` you can use `%K` and `%k`. e.g., 

    --log-format='%h %^[%d:%t %^] "%r" %s %b "%R" "%u" %K %k'

Closing this.
