### ISSUE TITLE
Problem with Geo Location (Unknown)

### ISSUE THREAD

**Issue by giopas** [allinurl/goaccess#1590]
I am running GoAccess to gather some stats on several reverse proxies handled by Caddy.

To launch GoAccess I have customized a startup script:

```
#!/bin/sh
### Get GeoIP db
cd /share/Public/goaccess/GeoIP
wget -N http://geolite.maxmind.com/download/geoip/database/GeoLite2-City.mmdb.gz
gunzip -f GeoLite2-City.mmdb.gz
### Launch goaccess
goaccess --no-global-config -o /share/Web/goaccess/index.html --real-time-html --config-file=/share/Public/goaccess/goaccess.conf --geoip-database /share/Public/goaccess/GeoIP/GeoLite2-City.mmdb
```
goaccess.conf is the following:
```
port 7890
daemonize true
log-format COMMON
real-time-html true
output /share/Web/goaccess/index.html
log-file /share/Public/caddy/accesslogs/goaccess.log
agent-list true
no-query-string true
```
If I go on goaccess.log, I have the following type of entries:
```
146.0.177.5 - goaccess [04/Nov/2019:10:44:04 +0100] "GET / HTTP/2.0" 200 116439
192.168.1.1 -  [03/Nov/2019:19:27:10 +0100] "GET / HTTP/2.0" 401 17
212.66.75.12 - goaccess [04/Nov/2019:22:59:46 +0100] "GET /favicon.ico HTTP/2.0" 404 236
```
Does anyone understand why I only get "Unknown" in the Geo Location tab?

Thanks

**Comment by giopas** [comment]
Hi @allinurl ,

Do you have any hint on where to look at or if I need to provide a better explanation on it?

Here is a screenshot:

![Screenshot_20191115-071038__01](https://user-images.githubusercontent.com/15943762/68920922-2f0b6500-0777-11ea-9696-4369a14e2b6a.jpg)

Thanks

**Comment by allinurl** [comment]
Let me look at this from my end and I'll post back.

**Comment by giopas** [comment]
Hi @allinurl,

Did you manage to have a look at it?

Thank you a bunch!

**Comment by allinurl** [comment]
You will need to build with `mmdb` support. 

    --enable-geoip=mmdb

Here's what I get:

![2019-11-18-215521_410x162_scrot](https://user-images.githubusercontent.com/5005367/69115389-f78a0a80-0a4d-11ea-8137-c9c6e168b550.png)

**Comment by giopas** [comment]
Thanks, I will check if this was done it!

**Comment by giopas** [comment]
That was indeed the issue, now it is solved, thanks!!

**Comment by giopas** [comment]
Issue solved
