### ISSUE TITLE
Log format of full URL

### ISSUE THREAD

**Issue by lepture** [allinurl/goaccess#1591]
Here is an example of my access log:

```
200.200.200.200 - [06/Nov/2019:01:14:46 +0000] "GET https://lepture.com/feed.xml HTTP/1.1" 200 35538 "-" "Tiny Tiny RSS/19.8 (http://tt-rss.org/)" "0.003"
```

So I tried with `%v`

```
%h - [%d:%t %^] "%m %^://%v%U %H" %s %b "%R" "%u" "%T"
```

But goaccess told me that `%v` is NULL.

**Comment by allinurl** [comment]
Closest you could get due to the parser needing a delimiter between specifiers would be 

    goaccess log --log-format='%h - [%d:%t %^] "%m %^://%v/%U %H" %s %b "%R" "%u" "%T"' --date-format='%d/%b/%Y' --time-format=%T

**Comment by lepture** [comment]
Thanks, that's what I'm doing now.

**Comment by allinurl** [comment]
Glad that solved the issue. Closing this. feel free to reopen it if needed.

**Comment by lepture** [comment]
Thanks.
