### ISSUE TITLE
No charts on HTML output

### ISSUE THREAD

**Issue by ahelito** [allinurl/goaccess#1595]
Hi
I run goaccess like:
`cat access_log.* | goaccess --log-format=COMBINED -a -o stats.log.html`
But i can't see any chart on the browser, I get only tables.
goaccess shows no error while parsing

My log lines are like follows:
```
18.237.44.188 - - [07/Nov/2019:01:16:58 +0100] "GET / HTTP/1.1" 404 466 "-" "Go-http-client/1.1" "-"
54.188.179.41 - - [07/Nov/2019:01:49:37 +0100] "GET / HTTP/1.1" 404 523 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64)AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36" "-"
81.203.146.107 - - [07/Nov/2019:07:50:14 +0100] "GET /nueva_web HTTP/1.1" 301 500 "-" "Mozilla/5.0 (iPad; CPU OS 9_3_5 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13G36 Safari/601.1" "-"
81.203.146.107 - - [07/Nov/2019:07:50:14 +0100] "GET /nueva_web/ HTTP/1.1" 200 5696 "-" "Mozilla/5.0 (iPad; CPU OS 9_3_5 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13G36 Safari/601.1" "-"
```

**Comment by ahelito** [comment]
Just saw Issue #1570 [https://github.com/allinurl/goaccess/issues/1570](url)
And revovig the extra "j!" fixes the problem

**Comment by allinurl** [comment]
Did you build from development to fix this issue?

**Comment by ahelito** [comment]
No, I got it installed from the SuSE Leap 15.0 repo (v1.3)
What fixed the issue was to manually edit the html output and remove the "j!"

**Comment by allinurl** [comment]
Would you be able to build from [**development**](https://github.com/allinurl/goaccess#build-from-github-development) and confirm that it fixes the issue? Thanks.

**Comment by ahelito** [comment]
```
$ git clone https://github.com/allinurl/goaccess.git
$ cd goaccess
$ autoreconf -fiv
$ ./configure --enable-utf8 --enable-geoip=legacy
$ make
# make install
```
gives error to me:

```
checking for GeoIP_new in -lGeoIP... no
configure: error: 
    *** Missing development files for the GeoIP library
```

I tried 
```
$ git clone https://github.com/allinurl/goaccess.git
$ cd goaccess
$ autoreconf -fi
$ ./configure --enable-geoip --enable-utf8
$ make
# make install
```
and I could build, but html output is still broken (needs to be fixed manually)

**Comment by vitaocode** [comment]
@allinurl 
eu compilei from development sem erros hoje e nao exibiu graficos, notei a presença do "!J" como no print abaixo:
![image](https://user-images.githubusercontent.com/31347646/68918235-1cc80180-074c-11ea-845e-a8b6cc20aca4.png)
@ahelito 

how did you do to revovig the extra "j!"?

**Comment by ahelito** [comment]
I edit the html output each time i generate output. I use sed:
`sed -i -e 's/j!<\/script>/<\/script>/g' log.html`

**Comment by vitaocode** [comment]
I compiled it through the stable version and it worked well.

**Comment by allinurl** [comment]
@ahelito @vitaocode can I ask you to please build again from [**development**](https://github.com/allinurl/goaccess#build-from-github-development) as we just pushed some new commits and see if that solves the issue. Thanks.

**Comment by gpailler** [comment]
I just built GoAccess from the latest sources and I can confirm the charts are back. Thanks!

**Comment by vitaocode** [comment]
@allinurl i build from development and works fine! the charts are back. :)
![image](https://user-images.githubusercontent.com/31347646/68989330-ba423480-0823-11ea-8338-9e4a290ef573.png)

**Comment by allinurl** [comment]
Great to hear that. Thank you guys for the update! Stay tuned for the upcoming updates :)
