### ISSUE TITLE
group requested files (URLS)

### ISSUE THREAD

**Issue by vitaocode** [allinurl/goaccess#1598]
good afternoon
I have two portals on the same server on a single vhost.

The difference between the two is in the image below:
![image](https://user-images.githubusercontent.com/31347646/68491458-a8f89700-0229-11ea-8618-ca8328ab139e.png)

both begin with the letter P but one ends with the letter O and the other with the letter T.
so we call p1p0 and p2pt.

would like to group REQUESTED FILES (URLS) panel records
so you can measure which portal has the most access.

You can see that there are differences between p1p0 as with bar and without bar and I count in the calculator the number of hits of each.

if there is a way to group this data together to make it more understandable.

from apache settings to advanced grep something like that.

Thanks in advance

**Comment by allinurl** [comment]
Have you checked this section of [**README**](https://github.com/allinurl/goaccess#virtual-hosts)?

**Comment by vitaocode** [comment]
Yes, i read Full readme before any questions, but i not understand How to group...Sorry man.
You can Help?

**Comment by vitaocode** [comment]
Good Morning,
I was able to test the recommendation. like:
tail -f -n +1 /var/log/apache2/other_vhosts_access.log | stdbuf -o0 awk '$8=$1$8'

however what happens is:
the domain is one!
What changes are the folders that will be accessed.

for example.


domain / folder1
domain / folder2
domain / folder1 /
domain / folder2 /
I want to group domain / folder1 with domain / folder1 /
and
domain / folder2 with domain / folder2 /

**Comment by allinurl** [comment]
This sounds very similar to [**this**](https://github.com/allinurl/goaccess/issues/673#issuecomment-283457620). Essentially you would need to prepend your domain/folder name to the request via awk and pass it to goaccess.

**Comment by vitaocode** [comment]
works fine... thanks in advanced

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
