### ISSUE TITLE
How to edit html

### ISSUE THREAD

**Issue by vitaocode** [allinurl/goaccess#1602]
Hi,
I want to edit HTML to translate the language to pt-br.
Wich files do i have to change to recompile

**Comment by vitaocode** [comment]
It's labels.h?

**Comment by allinurl** [comment]
Here are the steps for Spanish. Please take a look at [**this**](https://github.com/allinurl/goaccess/issues/858#issuecomment-320257517) post. Thanks

**Comment by allinurl** [comment]
BTW, seems like pt-br is already [**there**](https://github.com/allinurl/goaccess/blob/master/po/pt_BR.po).

**Comment by vitaocode** [comment]
Very good,
How do I add this file?
because I'm looking file by file and the folder "po" has no pt-br

**Comment by allinurl** [comment]
Please build from development.

**Comment by vitaocode** [comment]
following the compilation steps, I get this error named "autoreconf -fiv"
What can it be?

![image](https://user-images.githubusercontent.com/31347646/68880634-6122b580-06ea-11ea-9e3c-577c4821bf6a.png)

**Comment by allinurl** [comment]
apt-get install autopoint

**Comment by vitaocode** [comment]
it worked apt-get install autopoint
Now I can't export the variable LC_ALL
any more suspicions?

![image](https://user-images.githubusercontent.com/31347646/68881638-43565000-06ec-11ea-826e-42620112799f.png)

**Comment by allinurl** [comment]
Can you please run it through gdb?

```
$ gdb --args ./goaccess access.log
(gdb) r <enter>
(gdb) bt full <enter>
```

**Comment by vitaocode** [comment]
this?

![image](https://user-images.githubusercontent.com/31347646/68886648-5a9a3b00-06f6-11ea-9c2d-e1e086c87c46.png)

**Comment by vitaocode** [comment]
i reinstalled linux ubuntu 16.04.5 lts, ​​i will try again.

**Comment by vitaocode** [comment]
I was able to translate by downloading the stable goaccess package and added the ptbr language files manually.
it worked ok.
Thanks a lot

**Comment by allinurl** [comment]
Glad that worked :)
