### ISSUE TITLE
goaccess docker generated json or html file geolocation is empty

### ISSUE THREAD

**Issue by jevy-wangfei** [allinurl/goaccess#1604]
Use docker: 
```bash
cat log |  docker run --rm -i allinurl/goaccess -a -o json --log-format  COMBINED -> test.json
```
geolocation section: 
```json
    "geolocation": {
        "metadata": {
            "bytes": {
                "count": 0,
                "max": 0,
                "min": 0
            },
            "visitors": {
                "count": 0,
                "max": 0,
                "min": 0
            },
            "hits": {
                "count": 0,
                "max": 0,
                "min": 0
            },
            "data": {
                "unique": 0
            }
        },
        "data": []
    }
```

Use Ubuntu installed goaccess to process the same log, everyting is OK:
```json

"geolocation": {
    "metadata": {
        "bytes": {
            "count": 137656274,
            "max": 43982538,
            "min": 463
        },
        "visitors": {
            "count": 831,
            "max": 596,
            "min": 1
        },
        "hits": {
            "count": 9994,
            "max": 4571,
            "min": 1
        },
        "data": {
            "unique": 31
        }
    },
    "data": [{
        "hits": {
            "count": 4705,
            "percent": "47.08"
        },
        "visitors": {
            "count": 29,
            "percent": "3.49"
        },
        "bytes": {
            "count": 83459309,
            "percent": "60.63"
        },
        "data": "OC Oceania",
        "items": [{
            "hits": {
                "count": 4571,
                "percent": "45.74"
            },
            "visitors": {
                "count": 28,
                "percent": "3.37"
            },
            "bytes": {
                "count": 39476771,
                "percent": "28.68"
            },
            "data": "AU Australia"
        }, {
```

**Comment by allinurl** [comment]
Thanks for reporting this. Is this the only panel displaying these numbers?

**Comment by noszone** [comment]
Used command:
goaccess /var/log/apache2/access.log -o /var/www/html/report.html --log-format=COMBINED

and got an empty html file. Tried other options, pls help.

**Comment by jevy-wangfei** [comment]
> Thanks for reporting this. Is this the only panel displaying these numbers?

Yes, only the geolocation panel has zero metadata and empty data. 

Also notice that goaccess docker will generage the hosts panel  with item field at data attribute, but generage items field at Goaccess on linux. 

The GoAccesss version on my WSL:   

```
root@EVANSTON-BM:~# goaccess --version
GoAccess - 1.3.
For more details visit: http://goaccess.io
Copyright (C) 2009-2016 by Gerardo Orellana
```

**Comment by allinurl** [comment]
You will need to download and specify the db file. e.g., 

    --geoip-database=GeoLite2-City.mmdb

```
# For GeoIP2 City database:
# wget -N http://geolite.maxmind.com/download/geoip/database/GeoLite2-City.mmdb.gz
# gunzip GeoLite2-City.mmdb.gz
#
# For GeoIP2 Country database:
# wget -N http://geolite.maxmind.com/download/geoip/database/GeoLite2-Country.mmdb.gz
# gunzip GeoLite2-Country.mmdb.gz
```

**Comment by Stephan972** [comment]
> You will need to download and specify the db file. e.g.,
> 
> ```
> --geoip-database=GeoLite2-City.mmdb
>(...)
> # For GeoIP2 Country database:
> # wget -N http://geolite.maxmind.com/download/geoip/database/GeoLite2-Country.mmdb.gz
> # gunzip GeoLite2-Country.mmdb.gz

Since December 30, 2019, downloads are no longer served from MaxMind public GeoLite2 page, from geolite.maxmind.com/download/geoip/database/*, or from any other public URL.

A free license key is now required to download the MaxMind data.
Source: https://blog.maxmind.com/2019/12/18/significant-changes-to-accessing-and-using-geolite2-databases/

**Comment by allinurl** [comment]
That's right. You need to download the right files when using mmdb, which docker uses. Take a look at the [**config file**](https://github.com/allinurl/goaccess/blob/master/config/goaccess.conf#L661) for instructions. 

```
> # === GeoIP2
> # For GeoIP2 databases, you can use DB-IP Lite databases.
> # DB-IP is licensed under a Creative Commons Attribution 4.0 International License.
> # https://db-ip.com/db/lite.php
> # Download the GeoLite2-Country.mmdb.gz
> # gunzip GeoLite2-Country.mmdb.gz
> 
> use as: goaccess access.log --geoip-database=GeoLite2-Country.mmdb
```
