### ISSUE TITLE
geoip-city-data flag

### ISSUE THREAD

**Issue by cgzones** [allinurl/goaccess#1606]
`geoip-city-data` is an alias for `geoip-database`, but only if compiled with GeoIP Legacy (not GeoIP2).

Please either deprecate (and document so) `geoip-city-data` or enable it for GeoIP2 as well.

**Comment by vitaocode** [comment]
I got geoip2 with city database with this steps.
first:
i am using ubuntu 16.04 - apt install geoip-database
second compile with "mmdb":
./configure --enable-utf8 --enable-geoip=mmdb --with-getline --with-openssl
#mmb = geoip2

third:
download geoip2-database and extract
# wget -N http://geolite.maxmind.com/download/geoip/database/GeoLite2-Country.mmdb.gz
# gunzip GeoLite2-Country.mmdb.gz

four:
add to goaccess.conf path to the geoip2 database you downloaded.
I suggest leaving it in the default path of the document.
as below:
geoip-database /usr/local/share/GeoIP/GeoLite2-City.mmdb

this steps work for me

**Comment by allinurl** [comment]
Deprecated option `--geoip-city-data` in favor of `--geoip-database`. This will be pushed out in the upcoming release.
