### ISSUE TITLE
Filter out some IP addresses?

### ISSUE THREAD

**Issue by halloleo** [allinurl/goaccess#1609]
I'd like to filter out some IP addresses, so that tehy do not show up in the report - can GoAccess do this natively or should I pre-process the logs for this?

**Comment by allinurl** [comment]
You can do this natively. Please take a look at the [**man page**](https://goaccess.io/man#options) under parse options:

    -e --exclude-ip <IP|IP-range>

**Comment by halloleo** [comment]
Thanks @allinurl. Makes sense.

**Comment by attikov** [comment]
How can you ignore 2 IP's?
Using the -e multiple times ignores only the last one, using a delimiter doesn't work either

**Comment by allinurl** [comment]
@attikov Exclude an IPv4 or IPv6 from being counted. Ranges can be included as well using a dash in between the IPs (start-end).


```console

exclude-ip 127.0.0.1
exclude-ip 192.168.0.1-192.168.0.100
exclude-ip ::1
exclude-ip 0:0:0:0:0:ffff:808:804-0:0:0:0:0:ffff:808:808
```

**Comment by attikov** [comment]
Yes, it's not obvious that these are consecutive options because they are on new lines. Normally, one option is taken only once. It should be mentioned in the documentation that this option can be added multiple times. If it's still not clear what I'm talking about, then just ignore it.

**Comment by allinurl** [comment]
Certainly, you can pass multiple `-e` flags to accommodate your requirements

**Comment by attikov** [comment]
just forget it
