### ISSUE TITLE
Custom log with php execution time

### ISSUE THREAD

**Issue by ufo56** [allinurl/goaccess#1616]
Hi

My apache2 logs also time that takes to execute php request.

`domain xx.xx.xxx.xxx - - [25/Nov/2019:00:00:00 +0200] "GET /link/calculator/calculate?amount=1139.00 HTTP/2.0" 200 119 "https://domain/link/link/" "Mozilla/5.0 (Linux; Android 9; EML-L29) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Mobile Safari/537.36" (60642713-6.779)`

At moment i use ` --log-format='%v %h %^ %^ [%d:%t %^] "%r" %s %b "%R" "%u" "%^"%^ %^'`
Last number on line is time that takes to execute this php script. (6.779) Before that is just process id.

Is it possible to log that time into goaccess ? I see that there is options to log that time but i can't figure out correct log-format 

%DThe time taken to serve the request, in microseconds.
%TThe time taken to serve the request, in seconds with milliseconds resolution.
%L The time taken to serve the request, in milliseconds as a decimal number.

EDIT: Asked to soon help here. `--log-format='%v %h %^ %^ [%d:%t %^] "%r" %s %b "%R" "%u" "(%^-%T)"'` Seems to be correct answer :)

**Comment by allinurl** [comment]
This should do it:

    goaccess access.log --log-format='%v %h %^ %^ [%d:%t %^] "%r" %s %b "%R" "%u" %^-%T)' --date-format=%d/%b/%Y --time-format=%T

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
