### ISSUE TITLE
Help on custom log

### ISSUE THREAD

**Issue by giopas** [allinurl/goaccess#1626]
Hello,

I am trying to configure (in the config file) this type of log:

```
2019/12/06 08:16:01 my.domain.com 192.168.1.1 - - [06/Dec/2019:08:16:01 +0100] "GET /redirect.html?count=0.7408056120261262 HTTP/2.0" 200 548 "https://my.domain.com/" "Mozilla/5.0 (Linux; Android 9; ONEPLUS A5000) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Mobile Safari/537.36" 3
2019/12/06 08:24:42 my.domain.com 218.66.77.11 - - [06/Dec/2019:08:24:42 +0100] "GET /redirect.html?count=0.22918624993826597 HTTP/2.0" 200 548 "-" "Mozilla/5.0 (Linux; Android 9; ONEPLUS A5000) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Mobile Safari/537.36" 2
2019/12/06 17:36:54 my.domain.com 226.238.137.251 - - [06/Dec/2019:17:36:54 +0100] "GET /cgi-bin/login.html?1575650214 HTTP/1.1" 200 2653 "https://my.domain.com/redirect.html?count=0.282681040591797" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36" 3
```

On Caddy the log is set to "{hostonly} {combined} {latency_ms}", but I do not know how to translate it to make it readable to goaccess.

 How should I set it to work on goaccess.conf?

Thanks!

**Comment by giopas** [comment]
I arrived ti do so, but it still does not work:
`%d %t %v %h %^[%d:%t %^] "%r" %s %b "%R" "%u"`
Any help is really appreciated!!

**Comment by allinurl** [comment]
Can you please describe what's the last field? Thanks

**Comment by giopas** [comment]
Thanks @allinurl , I think it is {latency_ms}, but I don't know if it is really necessary to keep it.

Reading here[1], it seems to correspond to `%L`. Correct?

[1] https://lemanchet.fr/articles/optimizing-caddy-logs-for-goaccess.html

**Comment by giopas** [comment]
Hi @allinurl can you  please have a look at the above? 1000 kudos!

**Comment by giopas** [comment]
Hi @allinurl , I apologise for chasing you, but am I on a bad track? Could you please help me out? Thanks a bunch!

**Comment by allinurl** [comment]
This should work: 

    goaccess log --log-format='%d %t %v %h %^[%^] "%r" %s %b "%R" "%u" %L' --date-format=%Y/%m/%d --time-format=%T

**Comment by giopas** [comment]
Indeed it works, thanks!

I only see the "keyphrases from Google's search" tab empty, but I think it is because the info is not available in the log.
