### ISSUE TITLE
Unable to connect to WebSocket realtime HTML

### ISSUE THREAD

**Issue by Murkur** [allinurl/goaccess#1627]
ive been attempting to connect to the Real time HTML but I believe im doing it completely wrong
im starting the server over SSH under Super User using 
```
goaccess /var/log/apache2/access.log -o /var/www/html/ProjectModal/CDN/Models/Myrkur/report.html --log-format=COMBINED --real-time-html --ws-url=https://argonopenreach.ddns.net:7890 --ssl-cert=/etc/letsencrypt/live/argonopenreach.ddns.net/fullchain.pem --ssl-key=/etc/letsencrypt/live/argonopenreach.ddns.net/privkey.pem
```

I have built using openSSL so thats not the issue the issue is me trying to actually connect to the websocket at https://argonopenreach.ddns.net:7890/
does it not support using a ddns? or am I configuring wrong
console reads
```
WebSocket server ready to accept new client connections
```
I plan to use --daemonize it later when I get it Realtime working

im running a headless install of Ubuntu 18.04 bionic beaver with an install of webmin using apache2 webserver which i am using as basic public file storage for me aswell as video storage

ive opened the port on https://argonopenreach.ddns.net:7890/ to make it easier to test but all i get is a HTTP error 400 ive even tried using the servers local ip as its hosted on the same network

Edit
ran telnet to try to connect to the port using 
`telnet https://argonopenreach.ddns.net 7890`
and I get "Name or service not known" but connects fine without https:// ive tried going to argonopenreach.ddns.net:7890 and that provides an empty response
so still have no idea

**Comment by Murkur** [comment]
I did nothing and it works all of the sudden time wasted great software

**Comment by allinurl** [comment]
Just adding to the notes, it should be `--ws-url=wss://argonopenreach.ddns.net:7890` no https but wss.
