### ISSUE TITLE
doesn't work two parameters together

### ISSUE THREAD

**Issue by almirus** [allinurl/goaccess#1634]
goaccess /var/tmp/access.log-20191201 /var/tmp/access.log-20191208 -a **-o report.html**  **--config-dialog**

**Comment by allinurl** [comment]
When outputting to a file, you can't prompt the config dialog as ncurses is disabled. You will need to specify the log either in your config file or using a CLI option.

**Comment by almirus** [comment]
I tried using config file, but can't add leading space #1639 
#log-format [space]%h %^[%d:%t %^] "%r" %s %b "%R" "%u"

**Comment by allinurl** [comment]
Please try using single quotes. e.g., 

    goaccess access.log --log-format=' %h %^[%d:%t %^] "%r" %s %b "%R" "%u"' --date-format=%d/%b/%Y --time-format=%T
