### ISSUE TITLE
goaccess.conf not found in homebrew MacOS install

### ISSUE THREAD

**Issue by carolyn-shannon** [allinurl/goaccess#1640]
In homebrew MacOS 10.14 install, `goaccess.conf` is not found when running `goaccess`, including `goaccess -dcf`. 

Cause appears to be that `goaccess.conf` is created in 
`\Cellar\goaccess\1.3_1\conf\etc\goaccess`, but the binary looks for it in `\Cellar\goaccess\1.3_1\conf\etc`. 

Moving `goaccess.conf` into `\Cellar\goaccess\1.3_1\conf\etc` resolves the issue.

**Comment by allinurl** [comment]
Thanks for reporting this. I believe this has been fixed upstream per [this commit](https://github.com/allinurl/goaccess/commit/6efcac6179859a504d60a7b96e2549e6da853c95). It will be pushed out in the upcoming version, though you may be able to get the latest changes via brew and passing `--HEAD` to the command.

**Comment by CFin86** [comment]
I didn't see the troubleshooting section on this doc when trying to install GoAccess. I ran into this issue and was able to resolve it by creating `~/.goaccesrc` and copying the contents of goaccess.conf

**Comment by allinurl** [comment]
Closing this. This was fixed in v1.4.

Feel free to reopen it if needed.
