### ISSUE TITLE
Run Goaccess from local machine to monitor apache log in remote server.

### ISSUE THREAD

**Issue by vandat07** [allinurl/goaccess#1641]
Hello,

I have tried Goaccess to monitor the Apache log file in my local machine (windows 10). Now I am trying to run Goaccess in realtime to monitor the log file in remote server (windows server 2016), but I am unable to do it.

Could you please tell me if there is any ways to do this. 

Thanks a lot.
Van Dat

**Comment by allinurl** [comment]
To be honest I'm not familiar with Windows Server. Are you able to somehow ssh into the remote server? or can you mount the remote log e.g., sshfs into your local machine?

**Comment by tomaytotomato** [comment]
This might be of use to you. 

I have a small VPS instance which is not powerful enough to run goaccess, so what I do is use `scp` to pull down my latest access log file to a temporary location. Then I run goaccess on that local file.

So for you the best would be to setup SFTP and a user that has read only access to the directory of your access logs.
Then from your local server using cygwin pull down the access log file to a folder you want the file in.

**Comment by narayan1599** [comment]
I have server 1:-go access server 2:-webserver 
if need to pull data from my webserver to go access server 
but the data should display on go access server

**Comment by allinurl** [comment]
@narayan1599 try `sshfs`

**Comment by narayan1599** [comment]
can u please give an example
or any ref doc

**Comment by allinurl** [comment]
```
# mkdir /home/user/logs
# sshfs user@remoteserver.com:/var/log/apache2/ /home/user/logs/
# goaccess /home/user/logs/access.log --log-format=COMBINED
```

**Comment by narayan1599** [comment]
this work thanks

**Comment by allinurl** [comment]
Awesome. Closing this.
