### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by ripperdoc** [allinurl/goaccess#1643]
Not sure if this is a bug but I am seeking some clarification. I'm trying to run goaccess on a 5GB large log file (1 year of traffic on a smallish site, approximately 23M hits, most of it crawlers of course). I struggle with performance.
On my local (old) MacBook Pro it's using one core fully and starts at 12000 lines/s but after a minute starts falling down to 3000. This is in-memory (when I ran using disk and left it over night and checked in the morning, it was down at 400 lines/s and still not finished). Command is:
`goaccess -d -o report.html`
On my server I tried running it in Docker, it did not fall down but instead Docker socket disconnects after a while:
`read unix @->/var/run/docker.sock: read: connection reset by peer`

Any clues or tricks I should think of? Can goaccess use more than one core? Is the slowdown I see normal? Have the docker issues been seen before?

**Comment by allinurl** [comment]
I'm guessing the culprit is `-d`. Please try without resolving the IPs and let me know how it goes. For 23M hits, I'd still use the in-memory store. 

BTW, what processor do you have and ram? Thanks

**Comment by ripperdoc** [comment]
I tested running it without -d. It has the same performance, starting at 12k slowing down to 2.5k/s. I have 2,6 GHz Intel Core i7 Macbook Pro.

**Comment by allinurl** [comment]
To address your first question, currently there's no way to use more than one core. #377 will address this. 

Are you able to test this out on a different Mac? I just want to know if this might be an isolated issue. Also, you could try [building](https://github.com/allinurl/goaccess/blob/master/Makefile.am#L198) goaccess with `-O3` and see if that helps, or even using `./configure --enable-debug` to see if optimizations are not helping. Thanks!

**Comment by allinurl** [comment]
Closing this. v1.4 has been released so feel free to test it out there and post back if needed. Thanks.
