### ISSUE TITLE
 Token '...' doesn't match specifier '%h' - log without IP v4/6

### ISSUE THREAD

**Issue by mipon** [allinurl/goaccess#1644]
Hi,

Spent several hours trying to figure this out. I get an error.

Could you help? Thank you.

**access_log**
```
mydomain.net dynamic-ip-adsl.something.com - - [30/Dec/2019:00:00:11 +0900] "GET /some/direcotry/page HTTP/1.1" 404 47098 "-" "Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; WOW64; Trident/5.0; SLCC2; Media Center PC 6.0; InfoPath.3; MS-RTC LM 8; Zune 4.7)"
```

**Command**
```
bash-4.4$ goaccess "access_log" --log-format=COMBINED
Parsed 1 linesproducing the following errors:

Token 'mydomain.net' doesn't match specifier '%h'
```

I tried.
```
$ goaccess "access_log" --log-format='%h %^[%d:%t %^] "%r" %s %b "%R" "%u"' --date-fo
rmat=%d/%b/%Y --time-format=%T

Token 'mydomain.net' doesn't match specifier '%h'
```

Also tried many other variations but they don't work.

**Version**
```
$ goaccess -V
GoAccess - 1.3.
For more details visit: http://goaccess.io
Copyright (C) 2009-2016 by Gerardo Orellana

Build configure arguments:
  --enable-utf8
  --enable-geoip=legacy
```

**Comment by vitaocode** [comment]
not sure but try:
goaccess "access_log" --log-format=VCOMBINED

**Comment by allinurl** [comment]
> GoAccess requires the following fields:
> 
> **a valid IPv4/6 %h**
> a valid date %d
> the request %r

**Comment by mipon** [comment]
I see.

It seems the second field is mixed with a client host name and an IP address. Some items have a normal IP address. It is Apache2 log that the shared host gives and they prohibit the users from accessing http.conf. So I have no ways to change the format. 

Seems like there is no workarounds at the moment. 

What about implementing an ability to auto-detect of mixed usage of IP addresses and host names in a future release? 

Thank you for your consideration.

**Comment by allinurl** [comment]
@mipon If you build from [development](https://github.com/allinurl/goaccess#build-from-github-development), please try using `--no-ip-validation` as noted [here](https://github.com/allinurl/goaccess/blob/f331860b37525c276add9a3dd2a842ffbed25a31/config/goaccess.conf#L528).

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
