### ISSUE TITLE
Parsing Error on Log Turn-Over Message

### ISSUE THREAD

**Issue by sarcanon** [allinurl/goaccess#1646]
OpenBSD 6.6-current
Nginx 1.16.1
GoAccess 1.3

Hello. I am getting the following error when attempting to parse a Combined Log File format log:

```
vergil# goaccess /var/www/logs/rib_access.log -a -o /var/www/htdocs/rib/rpts/report.html
/var/www/logs/rib_access.log
Parsed 1 linesproducing the following errors:

Token 'vergil' doesn't match specifier '%h'

Format Errors - Verify your log/date/time format
```

The first line of the log being parsed is:

`2019-12-30T05:00:01.564Z vergil newsyslog[20784]: logfile turned over`

In the configuration file, relevant formats are set as:

```
time-format %H:%M:%S
date-format %d/%b/%Y
log-format %v:%^ %h %^[%d:%t %^] "%r" %s %b "%R" "%u"
```

Just speculating here, but perhaps the time format in the newsyslog message is confusing the parser? In any event, I see no way to configure goaccess to ignore the newsyslog message, and I can't see anything else in the man page that is irrelevant.

Any suggestions would be greatly appreciated.

Thank you.

**Comment by allinurl** [comment]
Are you parsing a web access log?

> GoAccess requires the following fields:
> 
> a valid IPv4/6 `%h`
> a valid date `%d`
> the request `%r`

**Comment by kobajagi** [comment]
Same issue here. OpenBSD writes that line when rotating access log and it's in different format then the rest of the logs. Skipping the first line will make goaccess process log just fine.

**Comment by allinurl** [comment]
@kobajagi Can you please try running goaccess with `--num-tests=1` and see if that does the trick? Thanks.

**Comment by sarcanon** [comment]
@allinurl I have tried with the `--num-tests` flag and get the exact same error:

```
# goaccess /var/www/logs/rib_access.log --num-tests=1 -a -o /var/www/htdocs/rib/rpts/report.html
/var/www/logs/rib_access.log
Parsed 1 linesproducing the following errors:

Token 'vergil' doesn't match specifier '%h'

Format Errors - Verify your log/date/time format

```
To reiterate, first line of log file is the rotate message, all subsequent lines are properly formatted log entries that can be parsed but for the first line that goaccess is choking on.

Thank you.

**Comment by allinurl** [comment]
Sorry, please try `--num-tests=2` or `--num-tests=10`

**Comment by sarcanon** [comment]
Unfortunately, same results:

```
# goaccess /var/www/logs/rib_access.log --num-tests=2 -a -o /var/www/htdocs/rib/rpts/report.html
/var/www/logs/rib_access.log
Parsed 1 linesproducing the following errors:

Token 'vergil' doesn't match specifier '%h'

Format Errors - Verify your log/date/time format
# goaccess /var/www/logs/rib_access.log --num-tests=10 -a -o /var/www/htdocs/rib/rpts/report.html
/var/www/logs/rib_access.log
Parsed 1 linesproducing the following errors:

Token 'vergil' doesn't match specifier '%h'

Format Errors - Verify your log/date/time format
#

```

**Comment by allinurl** [comment]
@sarcanon Could you please post the first 10 lines of that log? Thanks.

**Comment by sarcanon** [comment]
```
# goaccess /var/www/logs/access.log --num-tests=10 -a -o /var/www/htdocs/rib/rpts/report.html
/var/www/logs/access.log
Parsed 1 linesproducing the following errors:

Token 'vergil' doesn't match specifier '%h'

Format Errors - Verify your log/date/time format
# head -10 access.log
2020-02-10T05:00:01.870Z vergil newsyslog[13044]: logfile turned over
60.191.38.77 - - [09/Feb/2020:21:53:33 -0800] "GET / HTTP/1.1" 200 25128 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:47.0) Gecko/20100101 Firefox/47.0"
60.191.38.77 - - [09/Feb/2020:21:53:35 -0800] "GET / HTTP/1.1" 200 25128 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:47.0) Gecko/20100101 Firefox/47.0"
162.243.128.230 - - [09/Feb/2020:21:54:15 -0800] "GET /manager/text/list HTTP/1.1" 400 248 "-" "Mozilla/5.0 zgrab/0.x"
169.197.108.42 - - [09/Feb/2020:23:36:05 -0800] "GET / HTTP/1.1" 200 6205 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36"
216.244.66.230 - - [10/Feb/2020:04:00:07 -0800] "GET /sites/malton HTTP/1.1" 200 22067 "-" "Mozilla/5.0 (compatible; DotBot/1.1; http://www.opensiteexplorer.org/dotbot, help@moz.com)"
185.143.221.85 - - [10/Feb/2020:04:08:53 -0800] "\x03\x00\x00,'\xE0\x00\x00\x00\x00\x00Cookie: mstshash=eltons" 400 150 "-" "-"
159.203.10.6 - - [10/Feb/2020:04:24:46 -0800] "GET /api/v1/pod HTTP/1.1" 404 3863 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36"
198.108.66.144 - - [10/Feb/2020:05:53:53 -0800] "GET / HTTP/1.1" 200 6205 "-" "Mozilla/5.0 zgrab/0.x"
216.244.66.200 - - [10/Feb/2020:06:21:40 -0800] "GET /sites/castlesteads HTTP/1.1" 200 34438 "-" "Mozilla/5.0 (compatible; DotBot/1.1; http://www.opensiteexplorer.org/dotbot, help@moz.com)"
#

```

**Comment by herrbischoff** [comment]
I have the same issue on a FreeBSD system which also uses `newsyslog` and inserts rotate messages at the top and bottom. Which is useful to know a log has not been truncated. Unless I'm missing something major, the obvious solution would appear be to make goaccess ignore the first line of a log file by supplying a flag like

```
--ignore-first-line
```

or

```
--ignore-leading-lines=2
```

**Comment by herrbischoff** [comment]
Since there has been no reaction in over a months from the developers, I just wanted to share an intermediate solution. You can turn off the `newsyslog` "logfile turned over" message by adding the `B` flag:

```
B       indicates that the log file is a binary file, or has some
        special format.  Usually newsyslog(8) inserts an ASCII
        message into a log file during rotation.  This message is
        used to indicate when, and sometimes why the log file was
        rotated.  If B is specified, then that informational
        message will not be inserted into the log file.
```

Source: `newsyslog.conf` man page

**Comment by allinurl** [comment]
@herrbischoff Thanks for posting this. I'm working on a minor release so I can add this request to v1.4.1.

**Comment by herrbischoff** [comment]
@allinurl That'd be great, thanks! Feel free to ping me if you need testing.

**Comment by allinurl** [comment]
This should be fixed per [**this**](https://github.com/allinurl/goaccess/commit/4689e7a18aa1f11e136445d1bcd189387a7594d8) commit. Please feel free to test it out and let me know how it goes on your end. I will be pushing it out in the upcoming release pretty soon.

Thanks again for reporting it!
