### ISSUE TITLE
No real-time output when running goaccess locally from a remote access log

### ISSUE THREAD

**Issue by RobDelafontaine** [allinurl/goaccess#1647]
Sorry to bother you. I do appreciate the tremendous amount of work and talent you're putting into this. I have the following problem.

I have installed GoAccess on a local machine. I'm trying to monitor the logs on a remote shared server over ssh. I'm doing this:

    ssh user@ssh.example.com cat '/remoteserver/logs/access.log' | goaccess -p /usr/local/etc/goaccess.conf -o /localserver/Documents/report.html --real-time.html

This produces a full html output, however, it doesn't refresh.
Lsof -i tells me goacces listens to port 7890.
I have disabled the firewall on my router.
There are no errors in the browser console.

I know there have been many questions about realtime reporting, and I have read them all, but I can't get this to work. Once again, sorry to bother you.

**Comment by allinurl** [comment]
Great question. `cat` will only pull the file once. So you can try using `tail -f`, however, please note that there are reports #1282 of goaccess getting stuck while processing. I still need to look into this, though you can try:

    ssh -t username@server 'tail -f -n +1 /var/log/nginx/access.log' | goaccess -o /path/to/report.html --real-time-html -

Alternatively you could use `sshfs` and mount the access log locally. I've tested this and works fine.

**Comment by RobDelafontaine** [comment]
Thanks for your reply.
I tried using 'tail -f', but I'm sorry to say with no luck.
The report loads perfectly, but won't update.
I'll look into sshfs now.

**Comment by RobDelafontaine** [comment]
Okay. Don't laugh at me. I was checking the "Last Updated: ..." sign in the right top corner. Contents of that sign don't update, but the various panels do. Which means this problem has been solved.

**Comment by allinurl** [comment]
@RobDelafontaine yes, that bug of 'last updated' has been fixed upstream. It will be pushed out in the upcoming release.
