### ISSUE TITLE
Time Served columns are missing when piping messages from Java

### ISSUE THREAD

**Issue by MosheElisha** [allinurl/goaccess#1648]
Hi,

I have a Java process that reads messages from Elasticsearch and pipes them to goaccess.

If I use the  `--real-time-html` option when I start goaccess process from within Java, the Time Served columns (Avg, Max, Cum) are missing (attached real-time-report-without-ts). 

This is the command I use from within Java:

```
/usr/local/bin/goaccess --output /opt/aua/goaccess/index.html --time-format '%T' --date-format '%d/%b/%Y' --log-format '%h - %^ [%d:%t %^] "%r" %s %b "%R" "%u" "%^" %T %^ %^ %^' --real-time-html --fifo-in /tmp/goaccess.in --fifo-out /tmp/goaccess.out --invalid-requests /tmp/goaccess.invalid
```

If I don't use the `--real-time-html` option when starting `goaccess`, the T.S. columns are generated as expected (attached static-report-with-ts).

```
/usr/local/bin/goaccess --output /opt/aua/goaccess/index.html --time-format '%T' --date-format '%d/%b/%Y' --log-format '%h - %^ [%d:%t %^] "%r" %s %b "%R" "%u" "%^" %T %^ %^ %^'
```

If I change my Java program to write the messages into a FileOutputStream instead of the Process.getOutputStream() and than use the file generated with `--real-time-html` everything works as expected (attached real-time-report-with-ts):

```
tail -F /tmp/messages.log | /usr/local/bin/goaccess --output /var/www/html/report.html --time-format '%T' --date-format '%d/%b/%Y' --log-format '%h - %^ [%d:%t %^] "%r" %s %b "%R" "%u" "%^" %T %^ %^ %^' --real-time-html --fifo-in /tmp/goaccess.in --fifo-out /tmp/goaccess.out --invalid-requests /tmp/goaccess.invalid
```

I feel this is some buffering issue (something like `grep --line-buffered`) but I'm not sure what exactly. In my code I do the following for every log message:

```
byte[] messageBytes = (msgStr + System.lineSeparator()).getBytes();
processOutputStream.write(messageBytes);
processOutputStream.flush();
```

I configured goaccess with `--with-getline` thinking maybe it will make a difference but it didn't.
I also tried to configure with `--enable-debug` and run goaccess with `--debug-file` - the debug log file was created but it was empty.

BTW the https://goaccess.io/man mentions the option "--log-debug" but seems that the actual option is "--debug-file".

[goaccess-reports.zip](https://github.com/allinurl/goaccess/files/4050557/goaccess-reports.zip)

Can you please suggest what I should check?

My setup:
```
$ goaccess --version
GoAccess - 1.3.
For more details visit: http://goaccess.io
Copyright (C) 2009-2016 by Gerardo Orellana

Build configure arguments:
  --enable-debug
  --enable-utf8
  --with-openssl
$ cat /etc/centos-release
CentOS Linux release 7.7.1908 (Core)
```

Thanks.

**Comment by allinurl** [comment]
Thanks for pointing out the `--log-debug`, I'll have this fixed.

Are you able to run your code through gdb? or perhaps strace just to see if TS is actually being logged and how goaccess is reading it. let me know. e.g.,

**Comment by MosheElisha** [comment]
Thanks for replying.

I ran the following strace command:

```
$ ps -ef | grep goaccess
cbnd     14819 14678 68 10:30 pts/1    00:00:12 /usr/local/bin/goaccess --output /opt/aua/goaccess/index.html --time-format %T --date-format %d/%b/%Y --log-format %h - %^ [%d:%t %^] "%r" %s %b "%R" "%u" "%^" %T %^ %^ %^ --real-time-html --fifo-in /tmp/goaccess.in --fifo-out /tmp/goaccess.out --invalid-requests /tmp/goaccess.invalid
cbnd     15036 15441  0 10:30 pts/0    00:00:00 grep --color=auto goaccess
$ strace -s 300 -p 14819 > /tmp/strace.log 2>&1
```

The strace.log is attached - [strace.zip](https://github.com/allinurl/goaccess/files/4113351/strace.zip)

**Comment by allinurl** [comment]
I pushed a commit that fixes this. Please feel free to test it out by building from [**development**](https://github.com/allinurl/goaccess#build-from-github-development) and let me know if that solves the issue on your end. I'll push it out in the upcoming minor release. 

Thanks for reporting it!
