### ISSUE TITLE
Doc: static requests are not requests

### ISSUE THREAD

**Issue by uschwarz** [allinurl/goaccess#1650]
It seems that requests handled as static are not counted towards ordinary requests. That's fine by me, since it's easy to set the list of static extensions to `.thiscanthappen` only to count everything, but I don't think you can tell that behaviour from the docs. 
Saying "This panel displays the most highly requested **(non-static)** files" in the description of the requests panel would make this clearer.

**Comment by allinurl** [comment]
Thanks for pointing that out. I've updated this.

Closing this. Feel free to reopen it if needed.
