### ISSUE TITLE
Goaccess gives 'IPv4/6 is required.' even if I do not have a domain parser field

### ISSUE THREAD

**Issue by ali-bugdayci** [allinurl/goaccess#1652]
1. Can not parse the following with go access:

```
- - - [15/Jan/2020:06:27:31 +0100] "example.com" "GET / HTTP/1.1" 200 2275 "-" "FreshpingBot/1.0 (+https://freshping.io/)" 0.012
```

My parser is:

```
goaccess demo --log-format='%^ %^[%d:%t %^] %v "%m %U %H" %s %b "%^" "%u" %T' --date-format=%d/%b/%Y --time-format=%T  --http-protocol=no
```

it gives 
```
goaccess demo --log-format='%^ %^[%d:%t %^] %v "%m %U %H" %s %b "%^" "%u" %T' --date-format=%d/%b/%Y --time-format=%T  --http-protocol=no
Parsed 1 lines producing the following errors:

IPv4/6 is required.

```

2. The only domain field I have is virtual host %v

go access still gives me the error without it:

```
goaccess demo --log-format='%^ %^[%d:%t %^] %^ "%m %U %H" %s %b "%^" "%u" %T' --date-format=%d/%b/%Y --time-format=%T  --http-protocol=no
Parsed 1 lines producing the following errors:

IPv4/6 is required.
```

3. Could not find a verbose option. Is there a way where we can give smthg like "--verbose"

**Comment by allinurl** [comment]
As it says the message, goaccess requires a valid IP. You may be able to get around this by using `--no-ip-validation`, you will need to build from [**development**](https://github.com/allinurl/goaccess#build-from-github-development) for this option though.

**Comment by ali-bugdayci** [comment]
I do not fetch any IP related fields

The following format does not have an IP parse field, but it still gives the error:

goaccess demo --log-format='%^ %^[%d:%t %^] %^ "%m %U %H" %s %b "%^" "%u" %T' --date-format=%d/%b/%Y --time-format=%T  --http-protocol=no

**Comment by ali-bugdayci** [comment]
Also if I try the "virtual host" field, example.com is a valid domain:

- - - [15/Jan/2020:06:27:31 +0100] "example.com" "GET / HTTP/1.1" 200 2275 "-" "FreshpingBot/1.0 (+https://freshping.io/)" 0.012

**Comment by allinurl** [comment]
Like I said, in order for goaccess to parse your access log, it needs an IP within your log request. e.g., 

    192.168.0.1 - - [15/Jan/2020:06:27:31 +0100] "example.com" "GET / HTTP/1.1" 200 2275 "-" "FreshpingBot/1.0 (+https://freshping.io/)" 0.012

**Comment by ali-bugdayci** [comment]
By the way I am using nginx default log-format. MEaning that I do not have a custom log format. 

Do you have any clues why it is not writing request IP to logs ?

**Comment by allinurl** [comment]
The closest you can do is to use `--no-ip-validation` as I posted above. 

Please post your nginx access log format.

**Comment by ali-bugdayci** [comment]
I do not have an access log format.

I am using the default

nginx version: nginx/1.11.4

**Comment by ali-bugdayci** [comment]
building goaccess 1.3 from source codes

$ ./configure --no-ip-validation
configure: error: unrecognized option: `--no-ip-validation'
Try `./configure --help' for more information

**Comment by allinurl** [comment]
nginx has a log format, please look into and post it otherwise I can't help you. 

Also, please look at my first post for instructions on how to use that flag.

**Comment by ali-bugdayci** [comment]
Did not find it on your post.

Would it work if I appended it to : 

```config/goaccess.conf
no-ip-validation true
```

**Comment by allinurl** [comment]
You will need to build from [**development**](https://github.com/allinurl/goaccess#build-from-github-development) for `no-ip-validation` to work.

**Comment by ali-bugdayci** [comment]
Sorry, I was using package manager to install, So when I see development, tohught building from source :)

**Comment by rothkj1022** [comment]
I attempted to build from development with the --no-ip-validation option, and was met with the same error message:
configure: error: unrecognized option: --no-ip-validation' Try ./configure --help' for more information

**Comment by allinurl** [comment]
@rothkj1022 `--no-ip-validation` should be used when you run goaccess not to build goaccess. e.g.,

    goaccess access.log --log-format=COMBINED --no-ip-validation

**Comment by KaneTW** [comment]
Encountering this as well. Very frustrating. --no-ip-validation doesn't help.

**Comment by allinurl** [comment]
@KaneTW please post a few lines from your access log and the log format you are using.

**Comment by KaneTW** [comment]
```
- - - [07/Apr/2021:06:24:27 +0200] "GET https://seafile.kane.cx/seafhttp/repo/d336eecd-7dee-4ae8-90a6-8585f4bd3803/commit/HEAD HTTP/1.1" 200 81 "-" "Seafile/7.0.9 (Windows NT)" 0.004
- - - [07/Apr/2021:06:24:58 +0200] "GET https://seafile.kane.cx/seafhttp/repo/d336eecd-7dee-4ae8-90a6-8585f4bd3803/commit/HEAD HTTP/1.1" 200 81 "-" "Seafile/7.0.9 (Windows NT)" 0.003
```

```
goaccess --log-format='%^ %^ %^ [%d:%t %^] "%m %U %H" %s %b "%R" "%u" %T' --date-format=%d/%b/%Y --time-format=%T access.log --no-ip-validation
```

**Comment by allinurl** [comment]
You still have to specify `%h`, e.g.,

    goaccess --log-format='%h %^ %^ [%d:%t %^] "%m %U %H" %s %b "%R" "%u" %T' --date-format=%d/%b/%Y --time-format=%T access.log --no-ip-validation

**Comment by KaneTW** [comment]
Cheers, thanks
