### ISSUE TITLE
Unknown browser behind apache reverse proxy

### ISSUE THREAD

**Issue by x4nd1-2** [allinurl/goaccess#1655]
Hi,

my webserver is behind an apache reverse proxy. Therefore my apache LogFormat looks like this:
`LogFormat "%a %l %u %t \"%r\" %>s %O \"%{Referer}i\" \"%{User-Agent}i\"" proxy`

Output:
`192.168.99.1 - - [18/Jan/2020:13:37:36 +0100] "GET /favicon.ico HTTP/1.1" 301 232 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:72.0) Gecko/20100101 Firefox/72.0"`

If i choose the "Common Log Format (CLF)" in goaccesss.conf, it does work, but shows 100% unknown browsers.
I tried a few other strings without success.

What would be the correct logformat in goaccess.conf?

**Comment by allinurl** [comment]
Looks like the COMBINED format. Please try passing

    goaccess access.log --log-format=COMBINED

Otherwise, feel free to post a few lines from your access log and I can take a look. Thanks

**Comment by x4nd1-2** [comment]
Thank you, that works!
