### ISSUE TITLE
Another custom log format request

### ISSUE THREAD

**Issue by NHOrus** [allinurl/goaccess#1657]
Hello!
My log format line in apache is 
```
%t\t%h\t%v\t%D\t%l\t%u\t\"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"
```
It produces lines looking like (edited):
```
[21/Jan/2020:03:00:00 +0300]    10.0.0.47     virtualhost     0       -       -       "POST /REDACTED HTTP/1.1" 200 - "https://virtualhost/redacted" "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.117 Safari/537.36"
```
Goaccess refuses to parse with following:
```
Token '[21/Jan/2020:03:00:00 +0300]' doesn't match specifier '%t'
```

time-format %H:%M:%S
date-format %d/%b/%Y

and log-format from above. Help, please?

**Comment by allinurl** [comment]
Sorry for the delay on this, this should work:

    goaccess access.log --log-format='[%d:%t %^]\t%h\t%v\t%D\t%^"%r" %s %b "%R" "%u"' --date-format=%d/%b/%Y --time-format=%T

**Comment by narayan1599** [comment]
can go access read my mail logs

**Comment by allinurl** [comment]
@narayan1599 you can't. access logs only

**Comment by narayan1599** [comment]
thanks for your support 
it help's me

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it as needed.
