### ISSUE TITLE
AWS Beanstalk Custom Access Log Format

### ISSUE THREAD

**Issue by colender** [allinurl/goaccess#1664]
Im trying to figure out how to set the custom access log for Beanstalk

The example 

> 172.31.13.163 (45.56.150.80, 172.31.13.163) - - [15/Jan/2020:20:02:40 +0000] "GET /test?station=25&playtime=cool/playlist.m3u8 HTTP/1.1" 200 975 "-" "Mozilla/5.0 (Linux; Android 7.1.2; AFTMM Build/NS6268; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/70.0.3538.110 Mobile Safari/537.36"

I hope this helps

**Comment by allinurl** [comment]
Please try:

    goaccess access.log --log-format=COMBINED

**Comment by colender** [comment]
It worked thank you!!

**Comment by colender** [comment]
How would I be able to get the X-FORWARDED ip the part (45.56.150.80, 172.31.13.163) with COMBINED it doesn't get the ip from the user Im just getting the ip from the server. I have tried to use. 
`--log-format= %h (~h{,}) -- [%d:%t %^] "%m %U %H" %s %b "%R" "%u" --date-format=%d/%b/%Y --time-format=%T`
 I tried that but I get a %h has been specified error

**Comment by allinurl** [comment]
Close, this should work:

    goaccess access.log --log-format='%^ (~h{, }) %^[%d:%t %^] "%r" %s %b "%R" "%u"' --date-format=%d/%b/%Y --time-format=%T

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
