### ISSUE TITLE
Exposing port 7890

### ISSUE THREAD

**Issue by radoslav-stefanov** [allinurl/goaccess#1665]
Hi guys,

I have a running real time goaccess setup that is exposing websockets port to the web (goaccess is running from a Docker container). What are the security implication of this and how bad of an idea is to leave it open for everyone?

The web interface for viewing reports is protected by SSO authentication.

Thanks!

**Comment by allinurl** [comment]
Great question. Please take a look at [**this**](https://security.stackexchange.com/a/78811) for the implication of having a port opened. There are no known or outstanding security issues with goaccess, however, this does not mean it's 100% free of potential issues.

**Comment by radoslav-stefanov** [comment]
@allinurl Good to know that there are no known security issues. I plan to use goaccess for one of my next projects.

Thanks for the reply! I am closing the issue.
