### ISSUE TITLE
Parsing access log date and time in a single variable tab delimited

### ISSUE THREAD

**Issue by egar1m** [allinurl/goaccess#1668]
Hi all, I'm new to goaccess and I'm trying to my web access log to be inspect:

this is my apache log format: 

`LogFormat "%V\t%h\t%{SSL_PROTOCOL}x\t%{SSL_CIPHER}x\t%{SSL_CLIENT_S_DN_CN}x\t%u\t%{%d/%m/%Y %T %Z}t\t%{UNIQUE_ID}e\t%{JSESSIONID}C\t%H\t%m\t%U\t\"%q\"\t%>s\t%b\t\"%{Referer}i\"\t\"%{User-Agent}i\"\t%D\t%X\t%I\t%O" mycustumlog
`

example output:

    www.test.it   192.168.253.176                 -       -       20/01/2020 01:00:47 CET XiTtr38AAAEAAAzn8PkAAABX        7E7E5A44F91C8095E2E6EC57EBD0221E        HTTP/1.1        GET     0       /cms/   ""      200     143296  "-"     "Zabbix"        309722  +       477     147885

`
I try with:

`goaccess access.log -o report.html  -p /etc/goaccess/goaccess.conf  --time-format='%H:%M:%S %Z' --date-format='%d/%m/%Y' --log-format='%v\t%h\t-\t-\t-\t%d\t'`

but I get:

```
Parsed 1 linesproducing the following errors:

Token '20/01/2020 01:00:47 CET' doesn't match specifier '%d'

Format Errors - Verify your log/date/time format

```
Could anyone help?

**Comment by allinurl** [comment]
For this log:

```
www.test.it	192.168.253.176	-	-	20/01/2020 01:00:47 CET	XiTtr38AAAEAAAzn8PkAAABX	7E7E5A44F91C8095E2E6EC57EBD0221E	HTTP/1.1	GET	0	/cms/	""	200	143296	"-"	"Zabbix"	309722	+	477	147885
```

This should work:

    goaccess access.log --log-format='%v\t%h\t%^\t%^\t%d %t %^\t%^\t%^\t%H\t%m\t%^\t%U\t"%q"\t%%s\t%b\t^"%R"\r"%u"\t%D\t%^' --date-format=%d/%m/%Y --time-format=%T

**Comment by egar1m** [comment]
thank you so much! I add some extra %^ to parse "-" chars and now the magic string:
 goaccess access.log --log-format='%v\t%h\t%^\t%^\t%^\t%^\t%d %t %^\t%^\t%^\t%H\t%m\t%^\t%U\t"%q"\t%%s\t%b\t^"%R"\r"%u"\t%D\t%^' --date-format=%d/%m/%Y --time-format=%T

thanks for help! Great software!!!

**Comment by allinurl** [comment]
Glad that did the job :)
