### ISSUE TITLE
Tomcat 8.5.47 COMBINED

### ISSUE THREAD

**Issue by majkelo** [allinurl/goaccess#1669]
Hi, I use lastest release:
```
$ goaccess --version
GoAccess - 1.3.
```

I have set up server.xml as

```
<Valve className="org.apache.catalina.valves.AccessLogValve" directory="logs"
          prefix="api-example_access_log" suffix=".txt"
          pattern="combined" />
```

than after restart new file generated logs like:

> 127.0.0.1 - - [13/Feb/2020:23:29:49 +0100] "GET / HTTP/1.1" 302 - "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0"
> 127.0.0.1 - - [13/Feb/2020:23:29:50 +0100] "GET /login/auth HTTP/1.1" 200 2283 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0"
> 127.0.0.1 - - [13/Feb/2020:23:29:50 +0100] "GET /favicon.ico HTTP/1.1" 404 46 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0"
> 

### COMBINED 
 after running
`$ goaccess ./logs/api-example_access_log.2020-02-13.txt --log-format=COMBINED`

I received:

>  Parsing... [0] [0/s]                                                                                                                                             /./logs/api-example_access_log.2020-02-13.txt
> Parsed 1 linesproducing the following errors:
> 
> Token '13/Feb/2020' doesn't match specifier '%d'
> 
> Format Errors - Verify your log/date/time format

same error pops up if I start goaccess without `--log-format` param and choose `NCSA Combined Log Format `

same issue if I run 
`$ LANG="en_US.UTF-8" bash -c 'goaccess ./logs/api-example_access_log.2020-02-13.txt --log-format=COMBINED'`

###  VCOMBINED

 after running
`$ goaccess ./logs/api-example_access_log.2020-02-13.txt --log-format=VCOMBINED`

I received:

>  Parsing... [0] [0/s]                                                                                                                                             /./logs/api-example_access_log.2020-02-13.txt
> Parsed 1 linesproducing the following errors:
> 
> Token '+0100]' doesn't match specifier '%h'
> 
> Format Errors - Verify your log/date/time format

sam eissue if I run 
`LANG="en_US.UTF-8" bash -c 'goaccess ./logs/api-example_access_log.2020-02-13.txt --log-format=VCOMBINED'`

```
$ uname -a
FreeBSD example.com 11.3-RELEASE-p3 FreeBSD 11.3-RELEASE-p3 #1: Tue Oct 15 01:53:29 CEST 2019
```

Any help will be appreciated

**Comment by majkelo** [comment]
### Solution

`LC_ALL="en_US.UTF-8" bash -c 'goaccess ./logs/api-example_access_log.2020-02-13.txt --log-format=COMBINED'`

### Explanation

my system has different locale:

```
$ locale
LANG=
LC_CTYPE=pl_PL.UTF-8
LC_COLLATE=pl_PL.UTF-8
LC_TIME=pl_PL.UTF-8
LC_NUMERIC=pl_PL.UTF-8
LC_MONETARY=pl_PL.UTF-8
LC_MESSAGES=pl_PL.UTF-8
LC_ALL=
```
I had to explicitly enforce US locale (for alphabetic name of the month)

**Comment by allinurl** [comment]
Good call on that. Probably a better error message should be displayed on those cases.
