### ISSUE TITLE
Docker image and Tokyocabinet - build with Debian instead?

### ISSUE THREAD

**Issue by dschaper** [allinurl/goaccess#1674]
The current docker image is a multistage build using Alpine as the builder. Alpine doesn't have a native package for tokyocabinet so complexity increases with compiling from source and pathing the libraries. 

Instead of using Alpine for the build stage, is there interest in using an image with tokyocabinet as a native package? The build artifacts would still be copied to the actual busybox runtime image so the build OS doesn't seem to need to be Alpine. Busybox may not be `musl`, but busybox has `glibc` | `uclibc` images as well.

**Comment by allinurl** [comment]
Great question. I'm 2/3 the way into replacing tokyocabinet as the on-disk storage, I'm shooting to have this out before or by the end of March. Though, I do appreciate you bringing this up.

**Comment by dschaper** [comment]
Great news! The concept is something to keep in mind then, since multistage decouples the build and deployment images. No longer a need to have a stripped down building stage just to keep the deployment lightweight.

**Comment by allinurl** [comment]
The on-disk storage issue has been addressed. It now supports native on-disk persistence storage (no dependencies). New command line options are `--persist`, `--restore`, `--keep-last=<num_days>`. It also adds the ability to re-parse the same log(s) without counting data twice (see #334 or for exact details [**this post**](https://github.com/allinurl/goaccess/issues/334#issuecomment-272317226)).

This will be pushed out in the upcoming release. However, it would be great if you could test this out before deployment by building from [**development**](https://github.com/allinurl/goaccess#build-from-github-development).

Closing this as fixed. Feel free to post back as needed.
