### ISSUE TITLE
How the bandwith are calculated ?

### ISSUE THREAD

**Issue by MyTheValentinus** [allinurl/goaccess#1680]
Hello,
This is a question about the bandwith statistics, how goacces get this info. ?
In my log format i don't have this information

Thanks

**Comment by allinurl** [comment]
If it's not as part of your log, then it won't be able to calculate it.

**Comment by MyTheValentinus** [comment]
Hello, what’s is TX and RX in the report ?

**Comment by allinurl** [comment]
There's only T.X. It's the accumulated "bandwidth" from the access log.

**Comment by MyTheValentinus** [comment]
Yeah, but in my access log i not have bandwith

**Comment by allinurl** [comment]
It would need to be in the log, otherwise there's no way to report it out.

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
