### ISSUE TITLE
no-ip-validation not work

### ISSUE THREAD

**Issue by lerit** [allinurl/goaccess#1688]
config goaccess.conf:
no-ip-validation true
throw:
unrecognized option: no-ip-validation

goaccess -V:1.3

**Comment by lerit** [comment]
deploy my app in different environment,access direct or behind slb.
so xff not set if access directly.
```
log-format %^ %^ %^ %^[%d:%t %^] "%r" %s %b "%R" "%u" %^ %T ~h{", }
```
this is my log:
```
10.42.0.0 - - [29/Feb/2020:08:08:02 +0000] "GET /overhaul/work-order-to-check-node/check-statistics?accessKeyId=L77gQNbmh2BiEI5J&signatureNonce=0.4747935343448557&timestamp=2020-02-29T08:08:00.106Z&categoryID=001&activeTypeID=3 HTTP/1.1" 200 524 "http://192.168.5.9:4910/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.81 Safari/537.36" 1.080 1.080 "-"
```
does no-ip-validation  resolve this?

**Comment by allinurl** [comment]
You could use that flag (build from development as it hasn't been deployed) as long as the format is the same.

**Comment by lerit** [comment]
thanks!

**Comment by lerit** [comment]
@allinurl
i build goaccess with development,now goaccess start without error.
but  has no data in html page.
network info:{total_requests:10,valid_requests:0,failed_requests:10}
does this options resolve xxf  with '-'?
if xxf address is valid,goaccess work well

**Comment by allinurl** [comment]
Sounds like the wrong format. Please take a look at the other issue you opened.

**Comment by letwang** [comment]
> Sounds like the wrong format. Please take a look at the other issue you opened.

https://github.com/allinurl/goaccess/issues/1692

**Comment by letwang** [comment]
> @allinurl
> i build goaccess with development,now goaccess start without error.
> but has no data in html page.
> network info:{total_requests:10,valid_requests:0,failed_requests:10}
> does this options resolve xff with '-'?
> if xxf address is valid,goaccess work well

为什么我编译 报错？
https://github.com/allinurl/goaccess/issues/1692

**Comment by allinurl** [comment]
@lerit any updates?

**Comment by lerit** [comment]
@allinurl 
nothing update.you tell me [this](https://github.com/allinurl/goaccess/issues/1688#issuecomment-593094435) relate to #1689 

would you please help me  resolve that issue

**Comment by allinurl** [comment]
I'm looking at the other issue, I'll close this then.
