### ISSUE TITLE
only less table colums display in my html page

### ISSUE THREAD

**Issue by lerit** [allinurl/goaccess#1689]
my html page show less table column different with offical demo:
**offical demo:https://rt.goaccess.io/?20200209201008**
![image](https://user-images.githubusercontent.com/4743467/75607654-5d4d5e80-5b34-11ea-93e9-6ab0faa69566.png)

**my html:**
![image](https://user-images.githubusercontent.com/4743467/75607666-7bb35a00-5b34-11ea-96fa-144fb433f124.png)

**Comment by lerit** [comment]
i can see the data in browser network:
```
avgts: {avg: 60362}
bytes: {count: 282843, max: 89737, min: 55}
cumts: {count: 19316000, max: 1240000, min: 8000}
data: {unique: 107}
hits: {count: 320, max: 14, min: 1}
maxts: {count: 19316000, max: 596000, min: 8000}
visitors: {count: 160, max: 3, min: 1}
```

**Comment by allinurl** [comment]
Are you logging that data in your access log? Can you please post a few lines from your access log? Thanks

**Comment by lerit** [comment]
@allinurl 
**my goaccess.conf:**
```
log-format %^ %^ %^ %^[%d:%t %^] "%r" %s %b "%R" "%u" %^ %T ~h{", }
```
**my nginx format:**
```
    log_format main '$remote_addr - $remote_user [$time_local] "$request" '
    '$status $body_bytes_sent "$http_referer" '
    '"$http_user_agent" $request_time '
    '$upstream_response_time "$http_x_forwarded_for"';
```
**my nginx log:**
```
172.17.137.24 - - [29/Feb/2020:15:51:58 +0000] "GET /file-manager/index/get-folder HTTP/1.1" 200 473 "http://yyy.test.xxxx.com.cn/" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3314.0 Safari/537.36 SE 2.X MetaSr 1.0" 0.108 0.108 "123.72.62.143"
172.17.137.24 - - [29/Feb/2020:15:51:58 +0000] "GET /file-manager/index/preview-image HTTP/1.1" 200 1312 "http://yyy.test.xxx.com.cn/" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3314.0 Safari/537.36 SE 2.X MetaSr 1.0" 0.022 0.024 "123.72.62.143"
172.17.137.24 - - [29/Feb/2020:15:51:59 +0000] "GET /file-manager/index/preview-image HTTP/1.1" 200 5325 "http://yyy.test.xxx.com.cn/" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3314.0 Safari/537.36 SE 2.X MetaSr 1.0" 0.013 0.012 "123.72.62.143"
```

**Comment by allinurl** [comment]
The following format works for me, v.1.3

    goaccess access.log --log-format='%^[%d:%t %^] "%r" %s %b "%R" "%u" %^ %T ~h{", }' --date-format=%d/%b/%Y --time-format=%T -o a.html

Producing:

![2020-03-01-201519_1319x831_scrot](https://user-images.githubusercontent.com/5005367/75640117-75d37c80-5bf9-11ea-859f-cca1b5ce5a63.png)

**Comment by lerit** [comment]
@allinurl 
thank you. i try ,but nothing different.
i fact,shell work fine:
![2020-03-02 11-56-07屏幕截图](https://user-images.githubusercontent.com/4743467/75644340-fc7d6d80-5c7c-11ea-838c-eb1cf0b14879.png)
html not work:
![2020-03-02 11-56-36屏幕截图](https://user-images.githubusercontent.com/4743467/75644345-fedfc780-5c7c-11ea-93e4-1f5600ed48b8.png)

**Comment by allinurl** [comment]
Are you piping data in or reading directly from the log? This seems related or a dup of #1501

**Comment by allinurl** [comment]
Also, please attach your HTML report file here. Thanks

**Comment by lerit** [comment]
generate html:
[index.zip](https://github.com/allinurl/goaccess/files/4273407/index.zip)
I don't know what's mean piping data.i use a docker conatainer to generate the html page

**Comment by lerit** [comment]
i use a custom [docker](https://github.com/GregYankovoy/docker-goaccess),with nginx to serve the html page

**Comment by lerit** [comment]
@allinurl 
more info: in browser  console
**window.user_interface.visitors.items**
**demo html,with seven column:**
![work](https://user-images.githubusercontent.com/4743467/76413758-f4d26d00-63d0-11ea-807f-cee167017630.png)
**my html,only three column:**
![not-work](https://user-images.githubusercontent.com/4743467/76413769-fdc33e80-63d0-11ea-9e47-512302a6f95b.png)

are the column generate base on my data?
how can i debug this problem

**Comment by allinurl** [comment]
@lerit They're generated based on the data available. Are you loading from disk? or using the on-disk storage?

**Comment by lerit** [comment]
@allinurl 
not from disk,full command:
```
goaccess --no-global-config --config-file=/config/goaccess.conf
```
this is my config:
[goaccess.zip](https://github.com/allinurl/goaccess/files/4346827/goaccess.zip)

generate html and access from nginx;

**Comment by lerit** [comment]
@allinurl
i do not  know if the data result the issue?
nginx config:
```
    log_format main '$remote_addr - $remote_user [$time_local] "$request" '
    '$status $body_bytes_sent "$http_referer" '
    '"$http_user_agent" $request_time '
    '$upstream_response_time "$http_x_forwarded_for"';
```
goaccess config:
```
log-format %^[%d:%t %^] "%r" %s %b "%R" "%u" %^ %T ~h{", }
```

**Comment by lerit** [comment]
@allinurl  sorry to trouble you.
i find the html  json with all column data:(same as you online demo)
so i think it is not a problem with data.
it just didn't show it in html
```
	"visitors": {
		"metadata": {
			"avgts": {
				"avg": 38769
			},
			"cumts": {
				"count": 69669000,
				"max": 68873000,
				"min": 796000
			},
			"maxts": {
				"count": 69669000,
				"max": 428000,
				"min": 140000
			},
			"bytes": {
				"count": 18909695,
				"max": 18906233,
				"min": 3462
			},
			"visitors": {
				"count": 18,
				"max": 17,
				"min": 1
			},
			"hits": {
				"count": 1797,
				"max": 1785,
				"min": 12
			},
			"data": {
				"unique": 2
			}
		},
		"data": [{
			"hits": {
				"count": 12,
				"percent": "0.67"
			},
			"visitors": {
				"count": 1,
				"percent": "5.56"
			},
			"bytes": {
				"count": 3462,
				"percent": "0.02"
			},
			"avgts": 66333,
			"cumts": 796000,
			"maxts": 140000,
			"data": "20200322"
		}, {
			"hits": {
				"count": 1785,
				"percent": "99.33"
			},
			"visitors": {
				"count": 17,
				"percent": "94.44"
			},
			"bytes": {
				"count": 18906233,
				"percent": "99.98"
			},
			"avgts": 38584,
			"cumts": 68873000,
			"maxts": 428000,
			"data": "20200321"
		}]
	},
```

**Comment by lerit** [comment]
> Are you piping data in or reading directly from the log? This seems related or a dup of #1501

I can confirm this. Since it's a dup of #1501, I'll close this. 
@allinurl
