### ISSUE TITLE
How to analyze zipped log files on a remote webserver?

### ISSUE THREAD

**Issue by JoshDebris** [allinurl/goaccess#1693]
I want to set up goaccess on my local RaspberryPi and after that I want to analyze logfiles from a few remote server of the same provider. This provider stores all the logfiles in /logs

So far so good...

But... all these logfiles are zipped like: access_log_2020-03-03.gz
Is it somehow possible to read these zipped logfiles with goaccess?

Thanks in advance... :)

**Comment by allinurl** [comment]
Great question. I'd use `sshfs` and mount that directory on your RaspberryPi.

**Comment by JoshDebris** [comment]
Thank you for that tip.

I'm totaly overwhelmed wth the whole Linux stuff.... but I will read the documentaion about sshfs.
Hopefully I can get goaccess running at all? ;-)

**Comment by allinurl** [comment]
You should be able to run it as (assuming debian on the RaspberryPi):

```
  # apt-get install sshfs
  # mkdir /home/your_user/logs
  # sshfs remote_user@remote_server.com:/var/log/apache2/ /home/your_user/logs
  # zcat -f /home/your_user/logs/access.log* | goaccess - --log-format=COMBINED
```

**Comment by 0bi-w6n-K3nobi** [comment]
I use `socat` for transfer and analysis in real-time.
However, you will need to have a permanent link and some mechanism/trick to deal with any failure.

**Comment by allinurl** [comment]
You could try:

    # ssh -n root@server 'zcat -f /var/log/apache2/access_log*' | goaccess -

**Note**: SSH requires `-n` so GoAccess can read from stdin. Also, make sure to use SSH keys for authentication as it won't work if a passphrase is required.
