### ISSUE TITLE
Purple display issues in terminal

### ISSUE THREAD

**Issue by jamieburchell** [allinurl/goaccess#1695]
When starting goaccess I always have display issues as can be seen in the images below. I'm not sure if this is a bug in goaccess or the terminal or terminal configuration:

![Capture](https://user-images.githubusercontent.com/3270426/75980084-bb35c980-5ed9-11ea-9762-9ef836189de8.PNG)
![Capture2](https://user-images.githubusercontent.com/3270426/75980089-bd982380-5ed9-11ea-9f51-f460bfb74bb1.PNG)

GoAccess 1.2
CentOS 7
ConEmu 190310 [64]

**Comment by MrSorcus** [comment]
Did you try other terminals?

**Comment by jamieburchell** [comment]
You are right; it works fine in the terminal provided by Windows. Looks like I should ditch ConEmu.

**Comment by MrSorcus** [comment]
> You are right; it works fine in the terminal provided by Windows. Looks like I should ditch ConEmu.

You can create issue here https://github.com/Maximus5/ConEmu
Maybe they fix it if bug is the affected to their terminal.

**Comment by allinurl** [comment]
Closing this.
