### ISSUE TITLE
Do not overwrite config file when update using package manager

### ISSUE THREAD

**Issue by xupefei** [allinurl/goaccess#170]
Every time when GoAccess has updated by using `apt-get upgrade` command, the config file /etc/goaccess.conf file will be overwritten by a sample config file and the old one has no backup. Could you add a backup operation to this file before updating? Thanks :)

**Comment by allinurl** [comment]
I must have missed something in v0.9. For some reason, it seems like `fpm --config-files` is not properly using `conffiles` upon the creation of the `deb` file. I'll look further into this. Sorry about that.

**Comment by allinurl** [comment]
This has been fixed. Thanks!
