### ISSUE TITLE
Help with custom log format 

### ISSUE THREAD

**Issue by drolean** [allinurl/goaccess#1702]
my custom log nginx 
`'$remote_addr - $remote_user [$time_local] "$host" $request "$status" $body_bytes_sent "$http_referer" "$http_user_agent" "$http_x_forwarded_for" "$gzip_ratio" "$connection" "$connection_requests" "$request_time"'`

tried this:
`--log-format='%h - %^ [%d:%t %^] "%v" %r "%s" %b "%R" "%u" "%^" "%^" "%^" "%^" "%T"' --date-format=%d/%b/%Y --time-format=%T`

error: 
```
Token 'painel/ HTTP/1.1' doesn't match specifier '%s'
Token 'api/heat HTTP/1.1' doesn't match specifier '%s'
Token 'HTTP/1.1' doesn't match specifier '%s'
```

log:
```
186.193.186.243 - - [14/Mar/2020:10:52:43 -0300] "rec.2fin.com" POST /dc659162/validate HTTP/1.1 "422" 333 "https://rec.2fin.com/dc659162/login" "Mozilla/5.0 (iPhone; CPU iPhone OS 13_3_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.5 Mobile/15E148 Safari/604.1" "186.193.186.243" "-" "709467" "1" "3.119"
170.83.16.9 - detebibi [14/Mar/2020:10:52:43 -0300] "painel.2fin.com" GET /painel/ HTTP/1.1 "200" 24429 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36" "170.83.16.9" "19.00" "709391" "3" "0.625"
```

**Comment by allinurl** [comment]
This should do it:

    goaccess access.log --log-format='%h %^[%d:%t %^] "%v" %m %U %H "%s" %b "%R" "%u" %^ %^ %^ %^ "%T"' --date-format=%d/%b/%Y --time-format=%T

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
