### ISSUE TITLE
Display error requests

### ISSUE THREAD

**Issue by SoftCreatR** [allinurl/goaccess#1703]
Dunno, if this is already possible and i just missed it, but it would be nice if we could get a list of error requests (400+500) alongside the HTTP Status Codes list.

**Comment by 0bi-w6n-K3nobi** [comment]
The possivel and now workaround is, for log lines:

    Change 404 status [%s field specifier] for 204 or 304 or 504 [or just keep].
    Change 50x status for 404 and uri like a /uri to 50x@/uri;

Thus do you have a 404s panel with your 50x errors

**Comment by bgehman** [comment]
I feel the pain.  It is not useful to get very detailed avg/max response timings for calls that are 500'ing, but not able to see which URI's are responding with the 500's...

And likewise, a lot of 4xx/5xx skewing the response time averages for your 2xx's -- making you think everything is responding fast when the place is on fire.

I find it good to do some pre-filtering (with `grep`) to generate different reports, depending on the situation.

basic example (to pipe anything that looks like a 5xx to goaccess):
```
$ grep " 5[0-9][0-9] " *serverlogs* | goaccess ...... -o server_errros.html
```

A proper monitoring solution would be best though.

**Comment by allinurl** [comment]
#117 should address this.
