### ISSUE TITLE
Real time remote log updates 

### ISSUE THREAD

**Issue by javadan** [allinurl/goaccess#1706]
Hi,  thanks for this open source project.  It looks great so far.

I've managed to run GoAccess in a docker-compose, on IIS files that I copied over manually from a Windows machine.

From the looks of it, the file numbers increase u_ex200224.log, u_ex200225.log, u_ex200226.log, etc.

I have read the docs and some [related issue](https://github.com/allinurl/goaccess/issues/1647#issuecomment-570603668), but I'm still not sure what the best option would be.  

Real time updates would be best, but generating a static report with the day's logs is also an option.

Would you recommend I make a script like below that increments the file name when a new one is available?

`ssh -t username@server 'tail -f -n +1 /var/log/nginx/access.log' | goaccess -o /path/to/report.html --real-time-html -`  ?

**Comment by allinurl** [comment]
Yeah that would work, however, for real-time data, you could always try using something like `sshfs` to mount the remote logs locally and parse from there.

**Comment by narayan1599** [comment]
> Hi, thanks for this open source project. It looks great so far.
> 
> I've managed to run GoAccess in a docker-compose, on IIS files that I copied over manually from a Windows machine.
> 
> From the looks of it, the file numbers increase u_ex200224.log, u_ex200225.log, u_ex200226.log, etc.
> 
> I have read the docs and some [related issue](https://github.com/allinurl/goaccess/issues/1647#issuecomment-570603668), but I'm still not sure what the best option would be.
> 
> Real time updates would be best, but generating a static report with the day's logs is also an option.
> 
> Would you recommend I make a script like below that increments the file name when a new one is available?
> 
> `ssh -t username@server 'tail -f -n +1 /var/log/nginx/access.log' | goaccess -o /path/to/report.html --real-time-html -` ?

sshfs -o nonempty /home/mount user@ip:/usr/local/apache/logs/
this my help u

**Comment by allinurl** [comment]
Any updates on this?

**Comment by javadan** [comment]
Ended up using scp on a cron job, to copy the files over daily.  .
