### ISSUE TITLE
piping log into goaccess does not work correctly anymore

### ISSUE THREAD

**Issue by kochtopf** [allinurl/goaccess#1708]
just upgraded from Mar 12 -> Mar 21 and found the following...
cat test.log|goaccess -p go.cnf equals in Total requests count is higher than Valid requests
doing goaccess -f test.log -p go.cnf is still working OK (Total request = Valid requests). Looks like pipping stuff into goaccess does "eat" up / ignores  some Valid requests.

BTW. The default config file also got removed somehow.
goaccess --dcf
No default config file found.
You may specify one with `-p /path/goaccess.conf`

**Comment by allinurl** [comment]
Thanks for reporting this. Could you rebase and test it again? It was by default loading all data from disk. 

Also, can you post the output of `/usr/local/etc/goaccess`?

**Comment by kochtopf** [comment]
diff goaccess.conf_OK goaccess.conf	# this is what I'm using in ADDITION/OVERRIDE to the default goaccess.conf option file from make install
701,716d700
< 
< time-format %T
< date-format %d/%b/%Y
< log-format '%^ %~%^ %^ %^ %^ %h %v %e [%d:%t %^] "%r" %s %b "%R" "%u" "%^" "%^" "%T" "%C"'
< sort-panel VISIT_TIMES,BY_DATA,DESC
< geoip-database /usr/local/etc/goaccess/GeoLite2-City.mmdb
< ignore-panel REMOTE_USER

to process like
Mar 25 18:55:06 srv3 nginx: xxx.xxx.xxx.xxx www.sample.me - [25/Mar/2020:18:55:06 +0100] "GET /url HTTP/1.1" 200 18934 "https://www.google.com/" "xxx" "XX" "0.000" "HIT"

cat test.log|goaccess -p /usr/local/etc/goaccess/goaccess.conf
  Total Requests  22642 Unique Visitors  5779 Requested Files 9226 Referrers  0
  Valid Requests  17114 Init. Proc. Time 2s   Static Files    17   Log Size   0.0   B
  Failed Requests 0     Excl. IP Hits    389  Not Found       28   Tx. Amount 244.16 MiB
  Log Source      STDIN
                                   
goaccess -f test.log -p /usr/local/etc/goaccess/goaccess.conf	# this matches to build 186070cfe03e3001743176d71db3f2930a88098e
  Total Requests  22642 Unique Visitors  6201 Requested Files 11429 Referrers  0
  Valid Requests  22077 Init. Proc. Time 3s   Static Files    20    Log Size   11.23 MiB
  Failed Requests 0     Excl. IP Hits    565  Not Found       37    Tx. Amount 334.51 MiB
  Log Source      test.log
                             
---

# done with af874a29e88fde44e7180a29ddb9f6d130c9f20a
goaccess --dcf
No default config file found.
You may specify one with `-p /path/goaccess.conf`

# done with 186070cfe03e3001743176d71db3f2930a88098e
goaccess_OLDOK --dcf
/usr/local/etc/goaccess/goaccess.conf

PS: I do FLAGS="-O3" ./configure --enable-utf8 --enable-geoip=mmdb --with-getline
Looks like piping the SAME file gives different Valid Requests by a very large margin.
Thank you very much for reading.

**Comment by billhemsley** [comment]
Hi, 

I'm not sure if this is the same issue, but I'm trying to do the same thing so it might be at least related.

I'm piping in log files as per the instructions in the Multiple Log Files section of the man page. I'm on Mac OS X and am using:

```
gunzip -c access.log.*.gz | goaccess access.log -
```

This returns the error:

```
GoAccess - version 1.3 - Jun 17 2019 02:48:47
Config file: No config file used

Fatal error has occurred
Error occurred at: src/goaccess.c - set_curses - 1449
No time format was found on your conf file.
```
Using `goaccess access.log` on its own works fine, and `gunzip -c access.log.*.gz` returns the contents of the log files as expected. Thus is seems that the piping in the log file is causing the problem. Or perhaps it's simply me making an error.

Thanks!

**Comment by kochtopf** [comment]
Not my issue. I just tried your command 'gunzip -c access.log.*.gz | goaccess_OLDOK goaccess.log.1 -' and it works OK. But with a much more recent version (March 12 2020 - yours is from Jun 17 2019). RGDS

**Comment by billhemsley** [comment]
Thanks, @kochtopf .

The Jun 2019 version is the one on Homebrew. It'd be good if this was updated.

In case anyone else comes across this, note that there are instructions for installing on Mac without Homebrew on the FAQ page, although this involves having Xcode installed (around 8GB).

**Comment by allinurl** [comment]
@kochtopf I'll be checking at your report soon, I'm working on the storage right now and I want to push some commits before I take a look at it. I'll post back soon.

@billhemsley Does it work if you specify the log-format? e.g., 

    gunzip -c access.log.*.gz | goaccess access.log - --log-format=COMBINED

**Comment by billhemsley** [comment]
Many thanks @allinurl. That makes it work fine.

**Comment by majorboob** [comment]
goaccess development fresh install

/usr/local/bin/goaccess --dcf
No default config file found.
You may specify one with `-p /path/goaccess.conf`

**Comment by BobbyWibowo** [comment]
Any update to this? I'm getting the same issue with commit https://github.com/allinurl/goaccess/commit/c41bf05f194ec98a1074173457b8b8cea74b1b30.
```
zcat -f file.log | goaccess -p my.conf -
```
I initially noticed the issue while I was attempting to pipe multiple log files using wildcard glob, but I've also tried piping exactly one file, yet still the same issue anyway.

A few things I noticed:
- Piping was always over twice as fast as compared to specifying the log files directly as goaccess parameter (`zcat file.log | goaccess -` vs `goaccess file.log`).
On my old rack, piping were ~12k lines/s in average, while param were only ~4k lines/s in average.
- When I enabled `invalid-requests` config, every once in a while I'd see only *a few* lines getting logged as invalid. I re-iterate, *only a few*.
For example, with a ~400k lines log file, with which piping would result in only ~80k valid lines, it would at most log 5 invalid lines, but most of the times, **none at all** (each attempt was using the same log file, unmodified between attempts).
- Can confirm @kochtopf's claim:
  > Looks like piping the SAME file gives different Valid Requests by a very large margin.
- The logged invalid lines were fragmented and unique.
Sometimes only the first few characters were missing, but sometimes the whole first half of the whole line was missing.
Ignoring the attempts in which the invalid log wasn't populated, all of the logged invalid lines were always of different lines. So not only were the missing parts random, the lines that would get logged were also random.

And I've already tried the same log file directly as goaccess parameter, and as expected the valid lines were about 99.9%.

---

For my next attempt I guess I'll try building https://github.com/allinurl/goaccess/commit/f62848c17a80443cf8dbed9d9c5604120ea11146 (last commit OP implied to be working).

**Comment by BobbyWibowo** [comment]
> Never mind. I'll just feed all logs, active and historical, as goaccess params. I actually didn't know wildcards would also work there...

Nu uh. That breaks with over 20 log files. My logs are rotated daily, and I have 7 vhosts, and it started breaking on the 4th day).
From 1.4M requests in total, GoAccess would only capture ~140k in total, with ~80k said to be failed.
In the end I had to tweak my starter script to zcat all historical logs to a single temporary file and instead pass that along with the other 7 active logs, bringing them to only 8 log files.

**Comment by allinurl** [comment]
Thanks again for reporting this. This should be fixed as of [**3eccf58**](https://github.com/allinurl/goaccess/commit/3eccf58619d9c89918231f55e147db0ee8ef8bf0), counters should be back to normal. 

Please note that this was due to a recently added mechanism to avoid counting twice a persisted dataset (from issue #334). Note that if in fact you are restoring data and piping a log to goaccess, there's still a chance that this could occur. For details on why, please take a look at [**these posts**](https://github.com/allinurl/goaccess/issues/334#issuecomment-272317226).

@BobbyWibowo Good catch there. I've been working on a few different machines to commit the code so my best guess is one of them has the wrong system date/time.

Please rebase and let me know how it goes as I v1.4 is coming out soon! Thanks again for reporting it!

**Comment by kochtopf** [comment]
Counters measuring up again. Great fix. Thank you very much.
PS: Maybe just for cosmetic... goaccess --dcf still has:
No default config file found.
Maybe give'em back the default /usr/local/etc/goaccess/goaccess.conf

**Comment by allinurl** [comment]
@kochtopf Thanks for pointing that out, I'll look into the config file next.

**Comment by allinurl** [comment]
@kochtopf --dcf and finding out which config file should be fixed. Feel free to rebase again. Thanks again for reporting it!
