### ISSUE TITLE
generated report is not real-time

### ISSUE THREAD

**Issue by moeinrahimi** [allinurl/goaccess#1709]
I'm using provided command in getting started guide to get my nginx logs in real-time, but it's not real-time.
```
goaccess /var/log/nginx/access.log -o /var/www/html/report.html --log-format=COMBINED --real-time-html
```
I need manually to reload report page to get new stats

**Comment by allinurl** [comment]
Please post the contents of your browser's console. e.g., CTRL+Shift+j

**Comment by moeinrahimi** [comment]
there is not much info i guess.
```
DevTools failed to parse SourceMap: chrome-extension://ghkdafjlppmjciggpilgmnkjlcbpdifb/all.js.map
DevTools failed to parse SourceMap: chrome-extension://hdokiejnpimakedhajhdlcegeplioahd/sourcemaps/onloadwff.js.map
report.html:1 [Violation] 'load' handler took 589ms
[Violation] Forced reflow while executing JavaScript took 163ms
[Violation] Forced reflow while executing JavaScript took 30ms
```

**Comment by allinurl** [comment]
Can you share the URL? are you behind a proxy, docker? did you open the default port? are you able to telnet to that machine where goaccess is running? Thanks

**Comment by moeinrahimi** [comment]
I use nginx to serve the html file, I installed goaccess using using apt package manager on a ubuntu machine.
```
server {
server_name serverName;
listen 8989;
root /var/www/html;
}
```

**Comment by allinurl** [comment]
did you open port 7890? port 8989 seems to be the one used to serve the HTML report by nginx. You still need to open the websocket port 7890.

**Comment by moeinrahimi** [comment]
that's what I missed, should I restart goaccess somehow after opening port ? I'm running it in daemonize mode, because I used the below command and still no changes.
ufw allow 7890/tcp

**Comment by allinurl** [comment]
I'd restart it just in case. When you mouseover the dot next to the hamburger menu on the report, what address are you seeing there and are you able to telnet to it?

    # telnet address 7890

**Comment by moeinrahimi** [comment]
oh shoot something odd happened, my vps storage ran out and i cant ssh anymore, so goaccess generate file can be that big? I just installed it today.
I guess the 7890 port issue is solved.

**Comment by allinurl** [comment]
report is small, a couple of MBs

**Comment by moeinrahimi** [comment]
my issue is solved thank you for guidance

**Comment by moeinrahimi** [comment]
I know this is off topic but I want to mention when you do 'ufw enable', it basically closes all ports so you need to run 'ufw allow ssh' to keep ssh port open or you will get into trouble like me.
