### ISSUE TITLE
How to enable on-disk support from development version?

### ISSUE THREAD

**Issue by arischow** [allinurl/goaccess#1711]
When I try to run:
`./configure --enable-utf8 --enable-tcb=btree --with-openssl`

And in the final of the output there is a line `configure: WARNING: unrecognized options: --enable-tcb`

If I build the source code without appending `--enable-tcb=btree`, when I try to run:
`goaccess history.log --keep-db-files`

It just shows:
`goaccess: unrecognized option '--keep-db-files'`

BTW I'm using Ubuntu 18.04

**Comment by arischow** [comment]
OK I checked the git log and I found there's new option named `--keep-last=<NUM>`

But I can't find where the data will save to.

**Comment by allinurl** [comment]
There are three options. `--persist` `--restore` `--db-path=<dir>` by default it saves all data to /tmp

**Comment by allinurl** [comment]
BTW, `--keep-last` it's used to only show the last x number of days. e.g., show last 5 days and regardless of how many days it parsed. It does clean up the data that's not within those X days if new data is appended.

**Comment by arischow** [comment]
Thanks for your reply. I think it will be better to make a documentation for dev version 😄

**Comment by allinurl** [comment]
It will before v1.4 is released. Thanks for the heads up
