### ISSUE TITLE
Issue in Custom Log Format

### ISSUE THREAD

**Issue by prakashk22** [allinurl/goaccess#1714]
Hi Everyone,
  I am new to goaccess. My Custom Log format in apache is:- 
LogFormat "%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-agent}i\" %A %D %H %p %P %q %T %U" combined

How do i permanently set it in my goaccees.  i tried but getting errors. the specifiers are different in goaccess. Can any one help me out with this

**Comment by allinurl** [comment]
Please post a few lines from your log and I can take a look at it.

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
