### ISSUE TITLE
known problem with 2020/02/29?

### ISSUE THREAD

**Issue by reinweiss** [allinurl/goaccess#1716]
I have installed goaccess under MacOS for the first time and everything works fine. Unfortunately all reports end on 29.2.2020:

"Last Updated: 2020-03-26 12:38:52 +0100
Dashboard
OVERALL ANALYZED REQUESTS07/FEB/2019 — 29/FEB/2020"

**Comment by allinurl** [comment]
No known issues. Is this a static report or real-time?

**Comment by reinweiss** [comment]
It is a static report.

**Comment by reinweiss** [comment]
0.0.0.0 - - [29/Feb/2020:18:51:58 +0100] "GET /inhaltsverzeichnis.html HTTP/1.1" 200 1702 "https://test.test/test.html" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36 OPR/66.0.3515.72" "Traffic IN:1309 OUT:5570" "ReqTime:0 sec"
0.0.0.0 - - [01/Mar/2020:18:51:58 +0100] "GET /inhaltsverzeichnis.html HTTP/1.1" 200 1702 "https://test.test/test2.html" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36 OPR/66.0.3515.72" "Traffic IN:1309 OUT:5570" "ReqTime:0 sec"

This test-log shows only 1 hit on 29/Feb/2020, the entry on 01/Mar/2020 is ignored.

**Comment by reinweiss** [comment]
Problem solved:
Logfiles in English, Mac to analyze German. The specification locale, see above was wrong. I do not know why :(

locale
locale
LANG="de_DE.UTF-8"
LC_COLLATE="de_DE.UTF-8"
LC_CTYPE="de_DE.UTF-8"
LC_MESSAGES="de_DE.UTF-8"
LC_MONETARY="de_DE.UTF-8"
LC_NUMERIC="de_DE.UTF-8"
LC_TIME="de_DE.UTF-8"

Start goaccess:
LANG="en_US.UTF-8" bash -c 'goaccess ~/logfiles/test/access_log_test --log-format=COMBINED'

Result:
All is well.
