### ISSUE TITLE
Log format config help !

### ISSUE THREAD

**Issue by stephsabb** [allinurl/goaccess#1717]
Hello, 
My Apache log : 

> ecoledigital.net 2a01:cb08:8afd:1c00:c4d9:d987:5070:3311 - - [02/May/2019:13:14:11 +0000] (0 s) "GET /css/framework7.bundle.css HTTP/1.1" 200 70491 "http://ecoledigital.net/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1 Safari/605.1.15"

I try : 

> goaccess access.log --log-format='%v %h %^[%d:%t %^] %^ %^ "%r" %s %b "%R" "%u"' --date-format=%d/%b/%Y --time-format=%T

But error : 

> Token '02/May/2019' doesn't match specifier '%d'

?? date format is good no ?

Thanks

**Comment by allinurl** [comment]
This should do it:

    goaccess access.log --log-format='%v %h %^[%d:%t %^] %^"%r" %s %b "%R" "%u"' --date-format=%d/%b/%Y --time-format=%T

**Comment by stephsabb** [comment]
Thanks, 
This is a language issue on my computer,
cmd : LANG="en_US.UTF-8" correct this

**Comment by phanumax** [comment]
Dear,
Here is my nginx log.
`2020-03-22T04:27:07+07:00 10.1.71.26 "GET /intranet/intranet.php HTTP/1.1" - 301 0.000 520 162 "-" "Mozilla/5.0 (Linux; Android 6.0.1; SM-N910C) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Mobile Safari/537.36" "-"`

and this is nginx config.
`'$time_iso8601 $remote_addr "$request" '
      '$upstream_cache_status $status $request_time $bytes_sent $body_bytes_sent '
      '"$http_referer" "$http_user_agent" "$http_x_forwarded_for" '`

Please help me create log-format.

Thanks
