### ISSUE TITLE
VIRTUAL HOSTS Issue in realtime html

### ISSUE THREAD

**Issue by prakashk22** [allinurl/goaccess#1720]
I have multiple sites on apache server. so in real time html, in NOT FOUND URLS i want to also display virtual host name.
So i can decide which host is having 404 issue.
i tried below command:-

    $ awk '$8=$1$8' access.log | goaccess -a   -

But gives error .
Then tried it with date time:-

    $ sudo awk '$8=$1$8' /var/log/apache2/access.log | goaccess -a - --log-format='%v %h %^[%d:%t %^] "%r" %s %b "%R" "%u"' --date-format='%d/%b/%Y' --time-format=%T

But output is blank.

So how do i achieve this in realtime and both on terminal  #also.

**Comment by allinurl** [comment]
Did you check if `$8` is the request and `$1` is your actual vhost? Feel free to post a few sample lines from your access log.

**Comment by allinurl** [comment]
Closing this.
