### ISSUE TITLE
Mar, May and Dec missing in report

### ISSUE THREAD

**Issue by reinweiss** [allinurl/goaccess#1721]
The log:
----------

```
0.0.0.0 - - [01/Jan/2019:18:51:58 +0100] "GET /test.html HTTP/1.1" 200 1702 "https://test.test/test.html" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36 OPR/66.0.3515.72" "Traffic IN:1309 OUT:5570" "ReqTime:0 sec"
0.0.0.0 - - [01/Feb/2019:18:51:58 +0100] "GET /test.html HTTP/1.1" 200 1702 "https://test.test/test.html" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36 OPR/66.0.3515.72" "Traffic IN:1309 OUT:5570" "ReqTime:0 sec"
0.0.0.0 - - [01/Mar/2019:18:51:58 +0100] "GET /test.html HTTP/1.1" 200 1702 "https://test.test/test.html" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36 OPR/66.0.3515.72" "Traffic IN:1309 OUT:5570" "ReqTime:0 sec"
0.0.0.0 - - [01/Apr/2019:18:51:58 +0100] "GET /test.html HTTP/1.1" 200 1702 "https://test.test/test.html" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36 OPR/66.0.3515.72" "Traffic IN:1309 OUT:5570" "ReqTime:0 sec"
0.0.0.0 - - [01/May/2019:18:51:58 +0100] "GET /test.html HTTP/1.1" 200 1702 "https://test.test/test.html" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36 OPR/66.0.3515.72" "Traffic IN:1309 OUT:5570" "ReqTime:0 sec"
0.0.0.0 - - [01/Jun/2019:18:51:58 +0100] "GET /test.html HTTP/1.1" 200 1702 "https://test.test/test.html" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36 OPR/66.0.3515.72" "Traffic IN:1309 OUT:5570" "ReqTime:0 sec"
0.0.0.0 - - [01/Jul/2019:18:51:58 +0100] "GET /test.html HTTP/1.1" 200 1702 "https://test.test/test.html" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36 OPR/66.0.3515.72" "Traffic IN:1309 OUT:5570" "ReqTime:0 sec"
0.0.0.0 - - [01/Aug/2019:18:51:58 +0100] "GET /test.html HTTP/1.1" 200 1702 "https://test.test/test.html" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36 OPR/66.0.3515.72" "Traffic IN:1309 OUT:5570" "ReqTime:0 sec"
0.0.0.0 - - [01/Sep/2019:18:51:58 +0100] "GET /test.html HTTP/1.1" 200 1702 "https://test.test/test.html" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36 OPR/66.0.3515.72" "Traffic IN:1309 OUT:5570" "ReqTime:0 sec"
0.0.0.0 - - [01/Okt/2019:18:51:58 +0100] "GET /test.html HTTP/1.1" 200 1702 "https://test.test/test.html" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36 OPR/66.0.3515.72" "Traffic IN:1309 OUT:5570" "ReqTime:0 sec"
0.0.0.0 - - [01/Nov/2019:18:51:58 +0100] "GET /test.html HTTP/1.1" 200 1702 "https://test.test/test.html" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36 OPR/66.0.3515.72" "Traffic IN:1309 OUT:5570" "ReqTime:0 sec"
0.0.0.0 - - [01/Dec/2019:18:51:58 +0100] "GET /test.html HTTP/1.1" 200 1702 "https://test.test/test.html" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36 OPR/66.0.3515.72" "Traffic IN:1309 OUT:5570" "ReqTime:0 sec"

```
----------

locale
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL=

The static-report: 
9 valid Requests, 3 failed Requests. Mar, May and Dec missing.

**Comment by allinurl** [comment]
This is what I get for the log you posted above in v1.3.

![2020-03-30-185015_773x342_scrot](https://user-images.githubusercontent.com/5005367/77972525-504c9800-72b7-11ea-9f91-f4b15d310fa6.png)

Oct is missing since your log has Ock instead of Oct.

**Comment by reinweiss** [comment]
0.0.0.0 - - [01/Jan/2019:18:51:58 +0100] "GET /test.html HTTP/1.1" 200 1702 "https://test.test/test.html" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36 OPR/66.0.3515.72" "Traffic IN:1309 OUT:5570" "ReqTime:0 sec"
0.0.0.0 - - [01/Feb/2019:18:51:58 +0100] "GET /test.html HTTP/1.1" 200 1702 "https://test.test/test.html" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36 OPR/66.0.3515.72" "Traffic IN:1309 OUT:5570" "ReqTime:0 sec"
0.0.0.0 - - [01/Mar/2019:18:51:58 +0100] "GET /test.html HTTP/1.1" 200 1702 "https://test.test/test.html" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36 OPR/66.0.3515.72" "Traffic IN:1309 OUT:5570" "ReqTime:0 sec"
0.0.0.0 - - [01/Apr/2019:18:51:58 +0100] "GET /test.html HTTP/1.1" 200 1702 "https://test.test/test.html" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36 OPR/66.0.3515.72" "Traffic IN:1309 OUT:5570" "ReqTime:0 sec"
0.0.0.0 - - [01/May/2019:18:51:58 +0100] "GET /test.html HTTP/1.1" 200 1702 "https://test.test/test.html" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36 OPR/66.0.3515.72" "Traffic IN:1309 OUT:5570" "ReqTime:0 sec"
0.0.0.0 - - [01/Jun/2019:18:51:58 +0100] "GET /test.html HTTP/1.1" 200 1702 "https://test.test/test.html" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36 OPR/66.0.3515.72" "Traffic IN:1309 OUT:5570" "ReqTime:0 sec"
0.0.0.0 - - [01/Jul/2019:18:51:58 +0100] "GET /test.html HTTP/1.1" 200 1702 "https://test.test/test.html" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36 OPR/66.0.3515.72" "Traffic IN:1309 OUT:5570" "ReqTime:0 sec"
0.0.0.0 - - [01/Aug/2019:18:51:58 +0100] "GET /test.html HTTP/1.1" 200 1702 "https://test.test/test.html" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36 OPR/66.0.3515.72" "Traffic IN:1309 OUT:5570" "ReqTime:0 sec"
0.0.0.0 - - [01/Sep/2019:18:51:58 +0100] "GET /test.html HTTP/1.1" 200 1702 "https://test.test/test.html" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36 OPR/66.0.3515.72" "Traffic IN:1309 OUT:5570" "ReqTime:0 sec"
0.0.0.0 - - [01/Oct/2019:18:51:58 +0100] "GET /test.html HTTP/1.1" 200 1702 "https://test.test/test.html" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36 OPR/66.0.3515.72" "Traffic IN:1309 OUT:5570" "ReqTime:0 sec"
0.0.0.0 - - [01/Nov/2019:18:51:58 +0100] "GET /test.html HTTP/1.1" 200 1702 "https://test.test/test.html" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36 OPR/66.0.3515.72" "Traffic IN:1309 OUT:5570" "ReqTime:0 sec"
0.0.0.0 - - [01/Dec/2019:18:51:58 +0100] "GET /test.html HTTP/1.1" 200 1702 "https://test.test/test.html" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36 OPR/66.0.3515.72" "Traffic IN:1309 OUT:5570" "ReqTime:0 sec"

$ goaccess ~/goaccess/test/access_log_test --log-format=COMBINED

The result:
<img width="933" alt="Bildschirmfoto 2020-03-31 um 09 35 41" src="https://user-images.githubusercontent.com/13784173/77999474-03a6a280-7333-11ea-82b3-ccc7882aa29a.png">

**Comment by reinweiss** [comment]
Problem solved:
Logfiles in English, Mac to analyze German. The specification locale, see above was wrong. I do not know why :(

locale
LANG="en_EN.UTF-8"
LC_COLLATE="en_EN.UTF-8"
LC_CTYPE="en_EN.UTF-8"
LC_MESSAGES="en_EN.UTF-8"
LC_MONETARY="en_EN.UTF-8"
LC_NUMERIC="en_EN.UTF-8"
LC_TIME="en_EN.UTF-8"

Start goaccess:
LANG="en_US.UTF-8" bash -c 'goaccess ~/logfiles/test/access_log_test --log-format=COMBINED'

Result:
All is well.


Translated with www.DeepL.com/Translator (free version)
