### ISSUE TITLE
GoAccess 1.3 crashed by Sig 11

### ISSUE THREAD

**Issue by javadan** [allinurl/goaccess#1722]
Hi

So I made a directory watcher program that's picking up filenames of any log files created under a directory, and I pass it the source path and file name in $1 and $2.

```
#!/bin/bash

cd /opt/goaccess/
cat $1 | docker run --rm -i allinurl/goaccess -a -o html --no-global-config --log-format '%d %t %^ %^ %^ %m %U %^ %^ %^ %h %H %u %R %^ %s %^ %^ %b %^ %L' -> /opt/$2.html

```

When it runs, I get 

> 
> ==1== GoAccess 1.3 crashed by Sig 11
> ==1==
> ==1==
> ==1== Please report it by opening an issue on GitHub:
> ==1== https://github.com/allinurl/goaccess/issues
> 
> read unix @->/var/run/docker.sock: read: connection reset by peer
> 

Any idea?  Sorry, I wasn't able to work out an answer from the previous bug with this name

**Comment by allinurl** [comment]
Are you using the on-disk storage?

**Comment by javadan** [comment]
Ah, no, just piping and redirecting, using the docker command above.

**Comment by allinurl** [comment]
Does it work if you pass an existing filename?

    cat access.log | docker run --rm -i allinurl/goaccess -a -o html --no-global-config --log-format '%d %t %^ %^ %^ %m %U %^ %^ %^ %h %H %u %R %^ %s %^ %^ %b %^ %L' -> /opt/output.html

**Comment by javadan** [comment]
Thanks will try that. I shut down the computer for today, so will let you know next time

**Comment by javadan** [comment]
Looks like --no-global-config is the likely suspect.

**Comment by javadan** [comment]
Ok so I have this producing a report:

`docker run -v /goaccess:/goaccess -i allinurl/goaccess -a -o html --log-format '%d %t %^ %^ %^ %m %U %^ %^ %^ %h %H %u %R %^ %s %^ %^ %b %^ %L' --output=/goaccess/index.html --log-file=/goaccess/access.log --config-file=/goaccess/goaccess.conf`

I can also get this saving to disk:

`cat access.log | docker run -v /goaccess:/goaccess -i allinurl/goaccess -a -o html --log-format '%d %t %^ %^ %^ %m %U %^ %^ %^ %h %H %u %R %^ %s %^ %^ %b %^ %L' --output=/goaccess/index.html --config-file=/goaccess/goaccess.conf - > /goaccess/test.html
`

though I need to CTRL+C because the web socket stays open.

If I can get a websocket client working, that would be fine too.

But yes, I seem to be stuck now, trying to get more than one file piped in.

`cat access1.log access2.log | `

only seems to send one file through

But I haven't managed to get two

**Comment by javadan** [comment]
Ok never mind, it is sending both.  Looks like it's working.  I just need to stop the websocket server from staying active.  

Is there a way to disable the websocket server?  (Just have it parse the logs to html and quit)?

**Comment by javadan** [comment]
Ah I found the problem.  real-time-html was true in the config.  Working now.  Thanks
