### ISSUE TITLE
how to change Amazon Elastic Load format in goaccess 

### ISSUE THREAD

**Issue by narayan1599** [allinurl/goaccess#1724]
#1436  as this issue i have try it is working 
but how can i change in my conf file

**Comment by allinurl** [comment]
Simply add it to the config file. From https://goaccess.io/faq#configuration

> **Where is the configuration file located?**
> The configuration file is located under `~/.goaccessrc` or `%sysconfdir%/goaccess.conf` where `%sysconfdir%` is either `/etc/`, `/usr/etc/` or `/usr/local/etc/`. You can find the default configuration file here.

**Comment by narayan1599** [comment]
I have followed this and add in my conf file still it not changing

**Comment by narayan1599** [comment]
![Screenshot 2020-04-02 at 3 34 08 PM](https://user-images.githubusercontent.com/43582408/78236313-6c3e7c80-74f7-11ea-9fa2-6cc28462c709.png)

**Comment by narayan1599** [comment]
![Screenshot 2020-04-02 at 3 37 24 PM](https://user-images.githubusercontent.com/43582408/78236636-e40ca700-74f7-11ea-9495-0dcca06ba70b.png)

**Comment by narayan1599** [comment]
?

**Comment by allinurl** [comment]
Those are hard-coded, you will need to update https://github.com/allinurl/goaccess/blob/master/src/settings.c#L64

**Comment by narayan1599** [comment]
> Those are hard-coded, you will need to update https://github.com/allinurl/goaccess/blob/master/src/settings.c#L64

in my server were should i get this path?

**Comment by narayan1599** [comment]
?

**Comment by allinurl** [comment]
src/settings.c#L64

**Comment by narayan1599** [comment]
which part of code is responsible for generating HTML page

**Comment by allinurl** [comment]
@narayan1599 output.c

**Comment by allinurl** [comment]
Closing this. Feel free to reopen if needed.
