### ISSUE TITLE
how to make s3 realtime real-time web page

### ISSUE THREAD

**Issue by narayan1599** [allinurl/goaccess#1730]
I have tried to connect my AWS s3 logs the logs are coming to my goaccess server but aws is  creating more the one logs file

**Comment by narayan1599** [comment]
?

**Comment by allinurl** [comment]
Not sure exactly what is the question. To make it real-time just pass that flag: `--real-time-html`. More instructions on the [FAQ](https://goaccess.io/faq#html-report).
