### ISSUE TITLE
Max t.s. seems not calculated correctly

### ISSUE THREAD

**Issue by abregar** [allinurl/goaccess#1732]
Just noticed during some observation that there's a mismatch between max T.S. in a header row and ones presented in separate lines:
![wrong_ts](https://user-images.githubusercontent.com/1748792/78793488-c5545780-79b2-11ea-8a86-4e276d94fa58.jpg)
There is 1.24m in head and subsequent lines hold much higher values i.e. 7.82m. I have verified the access log manually and there should be 72.874sec. 

May I ask you to point me to the section in code where this is calculated and I may take a look?
Or if there is any other hint on this topic?

Thank you in advance and keep up the good work!

**Comment by allinurl** [comment]
Did you build from development? or is this v1.3? Thanks

**Comment by abregar** [comment]
Development fork, pretty recent. https://github.com/abregar/goaccess/

**Comment by allinurl** [comment]
Thanks for reporting this. I need to add back [these](https://github.com/abregar/goaccess/blob/master/src/parser.c#L1830) calls. However, I'm refactoring how it stores the data, thus they were not uncommented. I expect to push the changes in the upcoming days.

**Comment by abregar** [comment]
Excellent! Eagerly waiting.

**Comment by allinurl** [comment]
[**v1.4**](https://goaccess.io/download) has been released. Should address this.
