### ISSUE TITLE
AM_INIT_AUTOMAKE: command not found

### ISSUE THREAD

**Issue by javadan** [allinurl/goaccess#1733]
I'm on Centos 7
I'm trying to compile for on-disk:
```

# ./configure --enable-utf8 --enable-tcb=btree
./configure: line 2319: AM_INIT_AUTOMAKE: command not found
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
./configure: line 3120: AM_PROG_CC_C_O: command not found
./configure: line 3122: syntax error near unexpected token `external'
./configure: line 3122: `AM_GNU_GETTEXT(external)'

```

I installed tokyo cabinet
but am getting the above.  Do you know what is wrong? OS thing?

**Comment by allinurl** [comment]
You probably need to install "Development Tools" and  gettext-devel

**Comment by javadan** [comment]
I ran 
yum groupinstall "Development tools"
yum install gettext-devel

Same error as before

**Comment by allinurl** [comment]
I don't have a CentOS machine to test this out but based on the errors you are getting, it looks like you are missing some development tools such as automake autoconf, gettext. Did  you build from development or did you download v1.3?

**Comment by javadan** [comment]
v1.3

It seems I don't need the on-disk though, so I'll close this issue.
