### ISSUE TITLE
Cannot start as non-root

### ISSUE THREAD

**Issue by quinnjones** [allinurl/goaccess#1735]
I've just installed goaccess on a new, bare-bones machine.  I can't start it as a regular user:

    $ goaccess /var/log/apache2/access_log -c
    
    GoAccess - version 1.3 - Apr 12 2020 08:41:51
    Config file: No config file used
    
    Fatal error has occurred
    Error occurred at: src/settings.c - parse_conf_file - 282
    Malformed config key at line: 1

Even a simple `-h` results in the same error.

I can start the program if I run as root, but that isn't ideal.

I don't believe that this is a permissions issue with the configuration files, as they're world-readable:

    $ ls -alh /etc/goaccess
    total 52K
    drwxr-xr-x  2 root root   48 Apr 12 08:42 .
    drwxr-xr-x 75 root root  16K Apr 12 08:43 ..
    -rw-r--r--  1 root root 2.8K Apr 12 08:42 browsers.list
    -rw-r--r--  1 root root  21K Apr 12 08:42 goaccess.conf

Additional details:

Distro: Gentoo Linux
goaccess: v1.3
Apache: 2.4.41
First time using goaccess

**Comment by allinurl** [comment]
Does it make a difference if you pass `--no-global-config`? can you also please try making a copy of your /etc/goaccess/goaccess.conf into ~user/.goaccessrc and see how it goes. And finally please attach your config file. Thanks

**Comment by quinnjones** [comment]
Thanks for the quick response!
Copying /etc/goaccess/goaccess.conf to ~/.goaccessrc seemed to solve the problem.
Even though I consider this issue resolved, I've attached /etc/goaccess/goaccess.conf anyway, in case you still want to see what's in it.  It's still unchanged from the installation default.
[goaccess.conf.txt](https://github.com/allinurl/goaccess/files/4472512/goaccess.conf.txt)

Thank you!

**Comment by allinurl** [comment]
Thanks for reporting it! This has been fixed upstream. Please rebase from upstream or build from [**development**](https://github.com/allinurl/goaccess#build-from-github-development) to test it out.
