### ISSUE TITLE
Counts hits etc multiple times if log configured in .conf & command line

### ISSUE THREAD

**Issue by Admiral-Noisy-Bottom** [allinurl/goaccess#1736]
I've only been using Goaccess for a few days and love it but was surprised to see my web traffic almost doubled over a period of one hour.

I'm using version 1.3 on  Centos 7.

I checked the stats in the usual way and then closed it. Came back an hour later and reloaded it and found web traffic had doubled. The difference being that I had configured the goaccess.conf and included the log file to read and then loaded from the command line using "sudo goaccess /var/log/nginx/access.log"

It would seem goaccess read /var/log/nginx/access.log from the config file and then again from the command line and processed it twice.

Is it possible to add an internal check to see if the log file has been re-specified? I'm likely to do it again and be just as confused as I was earlier.

**Comment by allinurl** [comment]
I'm guessing you are using the on-disk storage? If that's the case, the soon-to-be-release version will have this protection. #334

**Comment by Admiral-Noisy-Bottom** [comment]
Brilliant, thanks. It isn't a real issue but it was confusing until I realized my mistake.

Thanks again.
