### ISSUE TITLE
Processing numbers inside report.html when using cron

### ISSUE THREAD

**Issue by majorboob** [allinurl/goaccess#1738]
Hi
In my HTML report, I got a lot of log processing numbers
https://i.imgur.com/BgNeLxy.jpg
This also broke some css styles 

cron cmd: `/usr/local/bin/goaccess -p /usr/local/etc/goaccess/goaccess.conf -a -f /home/users/USERNAME/logs/access.log > /home/users/USERNAME/www/mysite.com/access.html`

when I use this command through the terminal, everything works great.

p.s I use -p because of bug in dev version
https://github.com/allinurl/goaccess/issues/1532

**Comment by allinurl** [comment]
Please use the single dash `-` as indicated in the docs.

    /usr/local/bin/goaccess -p /usr/local/etc/goaccess/goaccess.conf -a - /home/users/USERNAME/logs/access.log -o  /home/users/USERNAME/www/mysite.com/access.html

**Comment by majorboob** [comment]
Thanks, it helped!

closed
