### ISSUE TITLE
MAX_LINE_CONF 512 is too short for my logformat

### ISSUE THREAD

**Issue by tykling** [allinurl/goaccess#1744]
Hello,

Can this be raised to maybe 1024 or more? https://github.com/allinurl/goaccess/blob/afc427cc27dbe97ce8b3db7e67f63eb00ab539a9/src/settings.h#L36

The current limit of 512 makes goaccess break up my json logformat, which means it tries to interpret something in the middle of the log-format as a goaccess config element, breaking config parsing :(

Thanks! :)

**Comment by tykling** [comment]
To add to the confusion this also applies to comments, so if you comment out a line while troubleshooting, goaccess still errors out the same way, trying to parse something 512 bytes into the commented line

**Comment by allinurl** [comment]
Thanks. I've pushed a commit for this (increased to 4096). Feel free to test it out from [development](https://github.com/allinurl/goaccess#build-from-github-development), otherwise it will be pushed out in the upcoming release.
