### ISSUE TITLE
Following recent update on Centos 7, config file not being found

### ISSUE THREAD

**Issue by RPCarter53** [allinurl/goaccess#1745]
Following a recent update on a number of CentoS 7 machines, goaccess stopped working. It would appear it is unable to find the config file correctly. The config file appears to be at /etc/goaccess/goaccess.conf. In the root of /etc I see goaccess.conf.rpmnew and goaccess.conf.rpmsave, there is no goaccess.conf file in the /etc itself.

**Comment by allinurl** [comment]
Thanks for reporting it! This has been fixed upstream. Please rebase from upstream or build from [**development**](https://github.com/allinurl/goaccess#build-from-github-development) to test it out.
