### ISSUE TITLE
Error message: Parsed 1 linesproducing the following errors:  Token 'XXXX' doesn't match specifier '%h'

### ISSUE THREAD

**Issue by cronforce** [allinurl/goaccess#1746]
Hi there,
I need some help with log file syntax. FYI: Running goacces on Ubuntu as Subsystem on Windows.

Ran this command:  
`goaccess /mnt/c/Users/XXX/httpd/prod.rtv.de_access.log -o ../stats.html --log-format=COMBINED`

Resulted in this message:

> Parsed 1 linesproducing the following errors:
> 
> Token 'crawl7.bl.semrush.com' doesn't match specifier '%h'
> 
> Format Errors - Verify your log/date/time format

Here are two lines of my logfile:
```
crawl7.bl.semrush.com - - [26/Apr/2020:03:12:05 +0200] "GET /amazon/neu-highlights-november/ HTTP/1.1" 301 - "-" "Mozilla/5.0 (compatible; SemrushBot/6~bl; +http://www.semrush.com/bot.html)"
crawl-66-249-79-130.googlebot.com - - [26/Apr/2020:03:12:05 +0200] "GET /index.cfm?spID=suche_erg&katID=120 HTTP/1.1" 404 530849 "-" "Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.96 Mobile Safari/537.36 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"
```

Thank you for your help!

**Comment by cronforce** [comment]
@allinurl: can you help please?

**Comment by allinurl** [comment]
Sorry about the delay on this. 

v1.3 requires a valid IPv4/6. The upcoming version will have the option to skip IP validation. If you want to build from [**development**](https://github.com/allinurl/goaccess#build-from-github-development) you can test this out by using --log-format=COMBINED along `--no-ip-validation`. Let me know how it goes.

**Comment by allinurl** [comment]
[v1.4](https://goaccess.io/download) has been deployed. You should be able to parse this log.
