### ISSUE TITLE
Get only general into my json

### ISSUE THREAD

**Issue by LoanDEV** [allinurl/goaccess#1748]
Hi, i need to get only general stats on my json output, is it possible ?

**Comment by allinurl** [comment]
Have you try disabling all [panels](https://github.com/allinurl/goaccess/blob/master/config/goaccess.conf#L498)?

**Comment by LoanDEV** [comment]
Owh sorry ! my bad !!! it's perfect thanks !!

**Comment by allinurl** [comment]
No worries, glad that worked :)
