### ISSUE TITLE
Noob infos setting up GoAccess with Jekyll website

### ISSUE THREAD

**Issue by xplosionmind** [allinurl/goaccess#1749]
Hi everybody, I'm a newbie who just configured and deployed its test website with Netlify. You can view it [here](https://xplosionmind.netlify.app) (still a WIP, though). How should I configure goaccess?

Another stupid question: goaccess displays only real-time data or stores also navigation data of the past which can be viewed in a dashboard? Since it's just a personal website, it's pretty useless to ma to have real-time data.

Thanks a lot!

**Comment by allinurl** [comment]
Do you know if netlify gives you access to the access logs?

You can see data in real-time or previously stored data.

**Comment by xplosionmind** [comment]
I'll check. Thanks! What about deployment?

-------- Original Message --------

**Comment by allinurl** [comment]
To be honest, I'm not familiar with netlify so I can't really answer if goaccess can be deployed on their platform. If you have access to their server and access logs, then you should be able to run goacceess, if you don't have access to the server where your site is hosted, but you have access to their access logs, then you could run goaccess in your local machine and just pull those logs locally (e.g., ssh, or sshfs).

**Comment by joeydi** [comment]
@xplosionmind 

> Do you know if netlify gives you access to the access logs?

They don't, and it sounds like that's not something they will ever offer, according to their head of support: https://community.netlify.com/t/download-raw-server-access-logs/6586/2 - They have their own analytics product which I imagine has something to do with that decision.

> What about deployment?

Netlify only supports hosting static files, so you wouldn't be able to run GoAccess on their servers. Theoretically you could run GoAccess locally, and host the HTML report output with them.

**Comment by xplosionmind** [comment]
Thank you so much! I was trying to figure it out myself but, as I wrote, I'm still at the beginning and I don't really know where to look and what to check.

What simple and easy CDN / server which I can link to both Goaccess and the GitHub repo of the website would you suggest me, then?

Actually I have a Linode VPS, but I don't know if I can directly link files which are stored there with the GitHub repo of the website.

Thanks a lot for your help!
Best,

Tommi

-------- Original Message --------

**Comment by xplosionmind** [comment]
> Netlify only supports hosting static files, so you wouldn't be able to run GoAccess on their servers. Theoretically you could run GoAccess locally, and host the HTML report output with them.

Thanks @joeydi, your reply is really useful. So is there a way I can install GoAccess on my server and use it to track my website hosted on Netlify? For example by adding in my website HTML some code to link my server instance to the website, thus tracking data...

Thanks a lot!

**Comment by joeydi** [comment]
No, I don’t think so. GoAccess runs on server logs, and Netlify doesn’t give you access to the server logs.

**Comment by xplosionmind** [comment]
That’s it. Thanks a lot to both of you! @allinurl @joeydi
