### ISSUE TITLE
Please note that HTTP requests containing the **same IP**, the **same date**, and the **same user agent** are considered a unique visitor. In your case, I'm assuming you are only taking unique IPs.

### ISSUE THREAD

**Issue by siteparc** [allinurl/goaccess#1750]
Please note that HTTP requests containing the **same IP**, the **same date**, and the **same user agent** are considered a unique visitor. In your case, I'm assuming you are only taking unique IPs. 

The unique IPs count should be displayed right above the data column in the Visitors Panel.

_Originally posted by @allinurl in https://github.com/allinurl/goaccess/issues/1205#issuecomment-414336124_

**Comment by siteparc** [comment]
Hello,
I'm using GoAccess - 1.3 on Ubuntu 16.04 to parse Nginx logfile.
Goaccess returns "406" for "unique visitors"... and "42 063" in data for IP...
the command in shell :
cat /var/log/nginx/access.log | awk '{print $1}' | sort | uniq | wc -l 
returns also :  "42 063"

I don't understand how you determine the unique key for the visitor in https://github.com/allinurl/goaccess/blob/master/src/parser.c
Thanks in advance

**Comment by allinurl** [comment]
The code that keeps track of the unique visitors panel is [here](https://github.com/allinurl/goaccess/blob/master/src/parser.c#L1855). Let me know if that answers your question.

**Comment by njrl** [comment]
i'm not shure if its the same problem but in my case the uniqe visitors are counted twice.
in a test setup uniqe vis. shows: 4
VISITOR HOSTNAMES AND IPS is listing two ips
cat /var/log/nginx/access.log | awk '{print $3}' | sort | uniq | wc -l  -> 2

(my log_format [%v] %T %h %^ %e [%d:%t %^] %s "%r" %b "%R" "%u" %^)

**Comment by allinurl** [comment]
@njrl Please post the lines from your access log that are being counted twice so I can reproduce this on my end. also, are you using the on-disk storage, if yes, did you persist and restore the data?

**Comment by njrl** [comment]
the log file https://pastebin.com/JRPUEifp
its a simple on-disk log ... blank started

**Comment by allinurl** [comment]
I get 2 unique visitors for the sample log you posted.

![2020-05-06-191008_558x197_scrot](https://user-images.githubusercontent.com/5005367/81240522-39dbdf80-8fcd-11ea-90c7-05efff54368a.png)

**Comment by njrl** [comment]
thats strange 
with:` goaccess --log-format='[%v] %T %h %^ %e [%d:%t %^] %s "%r" %b "%R" "%u" %^' --date-format='%d/%b/%Y' --time-format='%H:%M:%S'  -f /var/log/nginx/test.log` i get 
(https://user-images.githubusercontent.com/10773007/81261304-20be4780-903c-11ea-9b2e-785867402d94.png)
`goaccess -V
GoAccess - 1.3.`

**Comment by njrl** [comment]
found MY fault.. got an extra scace in my logs
`[%v] %T %h %^ %e [%d:%t %^] %s "%r" %b "%R" "%u" %^` --> counts 4 u.visitors
`[%v] %T %h %^ %e [%d:%t %^] %s "%r"  %b "%R" "%u" %^` --> counts 2 u.visitors
sorry for bothering

**Comment by allinurl** [comment]
Glad you figured out. Closing this, feel free to reopen it as needed.
