### ISSUE TITLE
Apache Milliseconds

### ISSUE THREAD

**Issue by amr-khaled-helmy** [allinurl/goaccess#1752]
How GoAccess can parse this format, I want to calculate average response time, 
"%h %l %u %t \"%r\" %>s %b %{ms}T"
response time is logged in a millisecond 

Example: 
172.16.10.1 - - [03/May/2020:03:00:01 +0300] "GET /mobile/service/lastTransactions HTTP/1.1" 200 778 1736

I already tried %L but didn't work correctly

**Comment by allinurl** [comment]
This is what I get on my end

![2020-05-03-152237_708x324_scrot](https://user-images.githubusercontent.com/5005367/80924956-d85c0c80-8d51-11ea-8b19-7529b4b76cf6.png)

 Are you getting a different result?

**Comment by amr-khaled-helmy** [comment]
Yes, I am getting zeros, 
this is the command I use,
goaccess --log-format="%h %l %u %^[%d:%t %^] \"%r\" %>s %b %L" access_log.2020-05-03 -o access_log.2020-05-03.html --time-format=%T --date-format='%d/%b/%Y' --no-global-config

**Comment by allinurl** [comment]
goaccess access.log --log-format='%h %^[%d:%t %^] "%r" %s %b %L' --date-format=%d/%b/%Y --time-format=%T
