### ISSUE TITLE
Charts and tables not loading unless "manually triggered"?

### ISSUE THREAD

**Issue by BobbyWibowo** [allinurl/goaccess#1753]
Basically on first page load it'd always look like this:
![Screenshot](https://i.fiery.me/SdVio.png)

But I can "manually trigger" them to appear by clicking on the right arrow buttons on each panel (the one at the very bottom, for tables), for example.
But that method would only load the tables.
For the charts, I'd have to untick Chart from Panel Options then re-tick it.
And then it'd only work for that specific panel.
Sometimes other panel would load by itself too in the middle of doing that, but I'm not too clear on the specifics.

As for Chart of the first panel, it'd always appear like that on first load, but with empty data basically.
I can only 'fix' this by manually changing the type to Area Spline. For some reason Bar would never work.

I also do NOT have Auto-hide on Small Devices enabled.

I'm on dev commit https://github.com/allinurl/goaccess/commit/36b542ab0370e0e3e6b050d11e33c6a368f8039a.
Running on CentOS 7, using multiple Nginx logs (gzip-archived ones piped through zcat, today's uncompressed ones specified straight with goaccess parameters), and with store to disk enabled.
Please let me know what other details are required to debug the issue.

**Comment by BobbyWibowo** [comment]
I also noticed this being logged in my browser's console:
```
TypeError: str is undefined goaccess:8:3683
    formatDate https://my.domain/goaccess/:8
    fmtValue https://my.domain/goaccess/:8
    xAxis https://my.domain/goaccess/:8
    text https://my.domain/goaccess/:8
    each https://my.domain/goaccess/:8
    Y https://my.domain/goaccess/:8
    each https://my.domain/goaccess/:8
    text https://my.domain/goaccess/:8
    n https://my.domain/goaccess/:8
    each https://my.domain/goaccess/:8
    Y https://my.domain/goaccess/:8
    each https://my.domain/goaccess/:8
    n https://my.domain/goaccess/:8
    call https://my.domain/goaccess/:8
    addAxis https://my.domain/goaccess/:8
    chart https://my.domain/goaccess/:8
    each https://my.domain/goaccess/:8
    Y https://my.domain/goaccess/:8
    each https://my.domain/goaccess/:8
    chart https://my.domain/goaccess/:8
    call https://my.domain/goaccess/:8
    renderChart https://my.domain/goaccess/:8
    addChart https://my.domain/goaccess/:8
    renderCharts https://my.domain/goaccess/:8
    initialize https://my.domain/goaccess/:8
    initialize https://my.domain/goaccess/:8
    onload https://my.domain/goaccess/:8
```

**Comment by BobbyWibowo** [comment]
On PC I notice chart of first panel would load properly.
Table of the first 4 panels would also load properly (but the others would still require doing the steps I mentioned on the first post).
But charts, aside from the first panel, wouldn't load properly unless I did the steps I mentioned on the first post either.

**Comment by BobbyWibowo** [comment]
Update. It might have been a mistake in my implementation of using Nginx to proxy the WebSocket. Tables would load properly all the time now, and it will indeed be real time (I can see it updating every second).
Unfortunately charts still wouldn't work properly unless manually triggered, aside from the first panel.

**Comment by BobbyWibowo** [comment]
Ok, figured it all out.
It seems charts would fail if the panel has too many vectors? (idk the term).
Panel such as referrals is one example as there'd surely be countless different referrals, for example.
But other things such as operating systems, browsers, etc. are working since there are typically less than 10. In fact time distribution also works.
But I have to disable charts of the problematic panels, otherwise the rest won't load on first page load (as if it all goes in a for-loop that immediately exits on the first error).

Oh yeah, I also enabled GeoLite2 City, but for some reason my panel only showed continents? Not even country, just continents.

**Comment by BobbyWibowo** [comment]
> Oh yeah, I also enabled GeoLite2 City, but for some reason my panel only showed continents? Not even country, just continents.
Frick, I'm dumb. There's an expand button to see countries within the continent and all that jazz.

Anyway, with that out of the way, everything seems to be solved 😅

**Comment by allinurl** [comment]
Interesting and thanks for pointing the issue with the charts. So I see you built from development. Are you able to reproduce this from v1.3? It would be great if you could help me test that out so I can look into it if this was an issue introduced in dev. Thanks.

Also, please feel free to attach your config file.
