### ISSUE TITLE
Log file without IP addresses?

### ISSUE THREAD

**Issue by ppelleti** [allinurl/goaccess#1754]
My hosting provider has changed my log file format from:

    Stamp,HostName,Page,IpAddress,Referer,UserAgent

to just:

    Stamp,HostName,Page,Referer,UserAgent

I had previously been using:

    goaccess access.log --log-format='"%d %t",%v,%U,%h,%R,"%u"' --date-format=%Y-%m-%d --time-format=%T --http-method=no --http-protocol=no --ignore-panel=REFERRING_SITES --ignore-panel=STATUS_CODES

so now I tried removing the `%h` field:

    goaccess access.log --log-format='"%d %t",%v,%U,%R,"%u"' --date-format=%Y-%m-%d --time-format=%T --http-method=no --http-protocol=no --ignore-panel=REFERRING_SITES --ignore-panel=STATUS_CODES

but I get the error:

```
Parsed 1 linesproducing the following errors:

IPv4/6 is required.

Format Errors - Verify your log/date/time format
```

Is there any way to parse the new log file format, or is goaccess just not designed to parse such a minimal log file?

**Comment by allinurl** [comment]
The upcoming version will have the option for `--no-ip-validation`. You can build from [development](https://github.com/allinurl/goaccess#build-from-github-development) to test this out.

**Comment by ppelleti** [comment]
I tried building from development, but when I did:

    ./configure --enable-geoip --enable-utf8

I got:

    configure: error: *** Invalid argument for GeoIP: yes

Have the configure options changed since the instructions were written?

**Comment by ppelleti** [comment]
I tried leaving off the `--enable-geoip` (since without IPs, I assume it wouldn't do me any good anyway?) and just did:

    ./configure --enable-utf8

And that worked.  But then, when I did `make`, I got:

```
src/parser.c:57:10: fatal error: 'malloc.h' file not found
#include <malloc.h>
         ^
1 error generated.
```

I'm on Mac OS X 10.9.5.  Is my Mac OS too old an no longer supported by goaccess?

**Comment by ppelleti** [comment]
I got it to build by just commenting out the `#include <malloc.h>` in `parser.c`.

However, when I run

    goaccess access.log --log-format='"%d %t",%v,%U,%R,"%u"' --date-format=%Y-%m-%d --time-format=%T --http-method=no --http-protocol=no --ignore-panel=REFERRING_SITES --ignore-panel=STATUS_CODES --no-ip-validation

I still get:

```
Parsed 1 lines producing the following errors:

IPv4/6 is required.

Format Errors - Verify your log/date/time format
```

(The only change seems to be that now there is a space between "lines" and "producing".)

**Comment by allinurl** [comment]
You would still need a HostName and use `%h`, however it won't validate %h as an IP if you pass --no-ip-validation.

**Comment by ppelleti** [comment]
OK, thanks!  That seems to have worked.
