### ISSUE TITLE
Add ability to report time in milliseconds

### ISSUE THREAD

**Issue by myusoof** [allinurl/goaccess#176]
Hi

It would be great if you could add a config option to view the time in milliseconds, rather than microseconds. The tomcat log files we have don't have microsecond precision.

Regards
Brian

**Comment by NeoCN** [comment]
`%T` is for seconds, use this will lead to wrong time result, support for milliseconds is appreciate! @allinurl

**Comment by allinurl** [comment]
`%T` parses the time in seconds with a milliseconds precision, e.g., `0.499`. What does your server output?

**Comment by allinurl** [comment]
This has been implemented. The specifier is `%L` - milliseconds as a decimal number [000, 999].
