### ISSUE TITLE
geoip-database

### ISSUE THREAD

**Issue by q5451227** [allinurl/goaccess#1761]
configure :
./configure --prefix=$GOACCESS --enable-utf8 --with-getline --with-openssl --enable-geoip=../goaccess/lib/GeoLite2-City.mmdb
sudo make && make install
goaccess.conf:
log-format COMBINED
with-mouse false
real-time-html true
log-file /www/wwwlogs/192.168.0.172.log
log-file /www/wwwlogs/access.log
http-method yes
http-protocol yes
output /www/wwwroot/app/public/1.html
real-os true
geoip-database ../../lib/GeoLite2-City.mmdb
static-file .css
......
startrun:

unrecognized option '--geoip-database'

**Comment by ajayramaswamy** [comment]
no the correct way is
./configure --enable-debug --enable-geoip=mmdb --enable-utf8 --with-getline --with-openssl

and then later in the config file /etc/goaccess/goacces.conf
add

db-path /var/cache/goaccess/
persist true
restore true
geoip-database /usr/share/GeoIP/GeoLite2-City.mmdb

**Comment by q5451227** [comment]
Thank you
Excuse me:If the terminal is closed, the program can still output logs(not shutdown)

**Comment by allinurl** [comment]
@q5451227 Yes, please run goaccess with the option `--daemonize`
