### ISSUE TITLE
Custom logs format

### ISSUE THREAD

**Issue by jcor29** [allinurl/goaccess#1762]
Hi,
There's seem to have lots of examples with access.log
I'm trying to figure out the log format for the following type of log file 

May  6 09:08:31 lxcent glx: Apache install for CentOS complete
..
So far no luck
goaccess glx.log
--time-format='%H:%M:%S' \
--date-format='%d' \
--log-format='%b  %d %t %~ %~ %~ %~'

Parsed 2 lines producing the following errors:

IPv4/6 is required.
IPv4/6 is required.

Could you help me out ?

Best Regards
J

**Comment by allinurl** [comment]
Please post a few lines from you access log. Thanks.

**Comment by allinurl** [comment]
Also, as it says on that message, an IPv4/6 is required in your log.

**Comment by MasterGroosha** [comment]
It it possible to log without IP address? I'm going to log event in my Python app. Of course, I can make a stub like 0.0.0.0, but that's just useless

**Comment by allinurl** [comment]
The upcoming v1.4 supports `--no-ip-validation`, though you still need a host, e.g., resolved ip

**Comment by allinurl** [comment]
@jcor29 any updates on this?

**Comment by jcor29** [comment]
Thanks for your reply
Still i think its would be nice for newbe like me
to have somewhere writen that gaccess needs an ip address, instead of
laconic message
Regards
Jacques

**Comment by allinurl** [comment]
Jacques, I'll see if I can move it to the FAQ, right now it is displayed in the docs under [**Custom Log Format**.](https://goaccess.io/man#custom-log). BTW, [**v1.4**](https://goaccess.io/download) is out if you want to give it a shot.
