### ISSUE TITLE
Config ignored?

### ISSUE THREAD

**Issue by Pi-George** [allinurl/goaccess#1764]
I've edited the goaccess.conf file so it has my log-format, date-format and time-format uncommented, however when I try to pipe stdin to goaccess it still complains "No time format was found on your conf file".

My conf file is located under /usr/local/etc/goaccess/ and the goaccess executable is under /usr/local/bin/

**Comment by allinurl** [comment]
Thanks for reporting this. I believe is trying to open `/usr/local/etc/goaccess.conf`. This should be fixed upstream. Feel free to build from [**development**](https://github.com/allinurl/goaccess#build-from-github-development) and let me know how it goes. Thanks.

**Comment by Pi-George** [comment]
Yeah moving the conf file up to the path you suggested fixed the issue. I'll close this since it's a duplicate
