### ISSUE TITLE
Parser breaks when using config file

### ISSUE THREAD

**Issue by MasterGroosha** [allinurl/goaccess#1767]
Hello. I'm having a strange issue with goaccess. It was installed on Manjaro via official repos using pacman.

`goaccess --version` output:
```
GoAccess - 1.3.
For more details visit: http://goaccess.io
Copyright (C) 2009-2016 by Gerardo Orellana

Build configure arguments:
  --enable-geoip=mmdb
  --with-openssl
```

So here's the problem. I have a file which is produced by Python script:
```
0.0.0.0 2020-05-13 02:08:42 - mystring - myvalue
1.2.3.4 2020-05-13 02:08:40 - mystring - myvalue
```

When launching goaccess with command-line arguments as `goaccess ~/path/to/log.log --time-format='%H:%M:%S' --date-format='%Y-%m-%d' --log-format='%h %d %t - %v - %r'` everything works fine and a terminal app opens with parsed data.

However, if I create `goaccess.conf` file with the same parameters:
```
time-format "%H:%M:%S"
date-format "%Y-%m-%d"
log-format "%h %d %t - %v - %r"
```
And then run it as `goaccess -p goaccess.conf ~/path/to/log.log`, then the following error message is displayed:
```
Parsed 1 linesproducing the following errors:

Token '.0.0.0' doesn't match specifier '%h'

Format Errors - Verify your log/date/time format
```
(the "linesproducing" word is a typo in program output, I just copied it here). 
If I change the IP in the first line from 0.0.0.0 to 1.2.3.4, it will say "Token '.2.3.4'...", so when running the app with config file, it cuts the first symbol in log and then fails to parse IP address.

If I change the first IP to 00.0.0.0 (to bypass this bug), it will say `Token '2020-05-13' doesn't match specifier '%d'`

I guess there is some bug when using goaccess with custom config file passed as argument. Or I'm missing something. Again, launching goaccess with app parameters passed as arguments works fine.

**Comment by MasterGroosha** [comment]
Also I've just compiled the app from source and the problem does persist for me.

**Comment by MasterGroosha** [comment]
After reading [the example file](https://raw.githubusercontent.com/allinurl/goaccess/master/config/goaccess.conf) I decided to get rid of all quotes:
```
time-format %H:%M:%S
date-format %Y-%m-%d
log-format %h %d %t - %v - %r
```

And the problem was solved.

**Comment by allinurl** [comment]
Glad that worked. Yes, in the config file there's no need for quotes as it grabs the whole string as is.
