### ISSUE TITLE
Support structured log formats such as JSON

### ISSUE THREAD

**Issue by mholt** [allinurl/goaccess#1768]
If I understand correctly, GoAccess needs to extract certain fields from mostly-arbitrary lines of data, in order to do its job.

Structured logs make this very easy by using a formally-structured encoding such as JSON or logfmt to key fields to values. [Caddy adopts this approach](https://caddyserver.com/docs/logging#structured-logs) since it is extremely useful for log aggregation and processing. In fact, Common Log Format and Combined and other antiquated standard formats don't provide enough information to be useful in advanced server applications.

An example access log from Caddy contains much more information than most traditional log formats such as CLF or Combined:

```json
{
	"level": "info",
	"ts": 1585597114.7687502,
	"logger": "http.log.access",
	"msg": "handled request",
	"request": {
		"method": "GET",
		"uri": "/",
		"proto": "HTTP/2.0",
		"remote_addr": "127.0.0.1:50876",
		"host": "example.com",
		"headers": {
			"User-Agent": [
				"curl/7.64.1"
			],
			"Accept": [
				"*/*"
			]
		},
		"tls": {
			"resumed": false,
			"version": 771,
			"ciphersuite": 49196,
			"proto": "h2",
			"proto_mutual": true,
			"server_name": "example.com"
		}
	},
	"latency": 0.000014711,
	"size": 2326,
	"status": 200,
	"resp_headers": {
		"Server": [
			"Caddy"
		],
		"Content-Type": ["text/html"]
	}
}
```

(In reality, log entries do not have newlines; I have formatted this one for readability.)

Logs that are emitted in this manner (instead of a custom format) also benefit from performance improvements; these logs require no allocations.

Unfortunately, it seems a bit tedious (impossible?) to get GoAccess to work with structured logs. For example, I do not think there is a way to skip until a next substring -- and even that only works if we know the order of the fields. (In Caddy's case, the field order is fairly deterministic since the JSON encoder is append-only, but JSON objects in general are not necessarily ordered.)

As you can see, all the required information (and much more!) is available in that log emission, but I don't know how to make GoAccess work with it: header fields vary, TLS may or may not be used, etc. The formats of durations and timestamps can even be customized, so that shouldn't be a problem for compatibility.

The main problem is that there doesn't seem to be a way to parse a structured format such as JSON and then specify fields from which to extract the needed information.

For example:

```
%x: ts
%v: request>host
%h: request>remote_addr
%U: request>uri
%H: request>proto
%T: latency
%R: request>headers>Referer
%s: status
%b: size
...
```

Does that make sense?

I am new to this project, and was about to jump in and contribute JSON support, but then realized that GoAccess is not written in Go 😅 .

**Comment by allinurl** [comment]
Matt, thanks for pointing this out. I do agree that having structured logs seems pretty useful, especially for debugging purposes. I think having an easier way to parse such logs in goaccess would be awesome and I can certainly start looking into this. 

I guess a quick way of having this implemented would be to use a JSON parser but I'm positive that would impact the performance of the current parser. One of the main goals of goaccess is the ability to parse a log as possible while being flexible enough to process virtually any log format. To accomplish this it performs a lot of pointer arithmetic while sacrificing the easiness of writing a custom format. Nonetheless, I certainly believe that there's room for improvement in this area and I plan to work on it.

As far as JSON objects not necessarily being ordered, is there a case where Caddy would log requests in different formats in the same access log? For instance, you mentioned that header fields vary, TLS may or may not be used, etc. Does that mean that the same access log may or may not contain certain fields and will depend on the request? I ask because that would certainly make things a bit more tricky for the current parser. If that is the case, feel free to post a few lines straight from your access log and I **may** be able to find a pattern on it.

For what is worth, the following format should work for the sample line you posted above (assumes there's a space between the key and the value on most cases, `"key": "val"`),

    { "level": "info", "ts": 1585597114.7687502, "logger": "http.log.access", "msg": "handled request", "request": { "method": "GET", "uri": "/", "proto": "HTTP/2.0", "remote_addr": "127.0.0.1:50876", "host": "example.com", "headers": { "User-Agent": [ "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36 Edg/81.0.416.72" ], "Accept": [ "*/*" ] }, "tls": { "resumed": false, "version": 771, "ciphersuite": 49196, "proto": "h2", "proto_mutual": true, "server_name": "example.com" } }, "latency": 0.000014711, "size": 2326, "status": 200, "resp_headers": { "Server": [ "Caddy" ], "Content-Type": ["text/html"] } }

---

    goaccess access.log --log-format='%^:%^: %x.%^ %^{%^: "%m"%^: "%U"%^: "%H"%^: "%h:%^"%^: "%v"%^[ "%u"%^]%^}%^}%^}%^: %T,%^: %b,%^: %s, %^' --date-format=%s --time-format=%s

About the name, the go comes from my initials :blush:  —  I do appreciate the intent to contribute though.

**Comment by flozano** [comment]
Another user of structured logs here - in my case it's LTSV, not JSON. 

> As far as JSON objects not necessarily being ordered, is there a case where Caddy would log requests in different formats in the same access log? For instance, you mentioned that header fields vary, TLS may or may not be used, etc. Does that mean that the same access log may or may not contain certain fields and will depend on the request? I ask because that would certainly make things a bit more tricky for the current parser. If that is the case, feel free to post a few lines straight from your access log and I may be able to find a pattern on it.

We log some (request/response) headers only if they are present. If they are not, the corresponding field will not appear in the logs, so a parser that expects a fixed format will not work. Moreover, there's no guarantee that the fields are always positioned the same way.

**Comment by mholt** [comment]
@allinurl Thank you for the thoughful consideration! And thank you for chiming in @flozano , it's good to have another perspective too; I hadn't heard of LTSV.

> I guess a quick way of having this implemented would be to use a JSON parser but I'm positive that would impact the performance of the current parser. One of the main goals of goaccess is the ability to parse a log as fast as possible while being flexible enough to process virtually any log format.

Yep, JSON parsing will always be slower than pointer arithmetic. However, I know there are several libraries written in Go that deliver extremely high performance JSON parsing -- and that's with a (highly tuned) garbage collector! I also know of several companies that use Go on their edge to do log aggregation which can handle JSON logs at scale, without a problem. If Go can do it, I am certain that there are very performant JSON libraries in C. And since GoAccess already has peak performance for those who need it, now here's an opportunity to make GoAccess usable by a larger audience.

So, if I may suggest: you don't need to make ultimate performance the enemy of JSON support, especially at a first pass. Performance can always be optimized (especially in C) later on. We can probably safely assume that 99%+ of GoAccess users aren't emitting _so many logs_ that GoAccess would choke on JSON. Those who need higher performance can use faster encodings until the JSON is optimized.

Also, how many users with _extremely busy servers_ run GoAccess on the same machine (thus taking CPU time away from the main application) in production? I wouldn't know -- but I'm guessing if their servers are already pegged with their main web app, that they wouldn't also be doing log aggregation on the same one. So, it's probably safe to assume that GoAccess doesn't need to be optimally performing for JSON logs in most cases.

Anyway, I can understand wanting top performance (I write web servers, after all) -- but I hope it won't stand in the way of a very useful feature! I've been wanting to try GoAccess for years and now I have an opportunity -- I'd rather be able to use GoAccess than have to find something else just because of performance worries.

> As far as JSON objects not necessarily being ordered, is there a case where Caddy would log requests in different formats in the same access log?

Possibly, yeah. Structured logs can all be different (they're just JSON messages) but in Caddy, at least, each log has a field called "logger" that says the name of the logger. In Caddy, each logger emits the same kind of logs. So, all access logs will begin with "http.log.access" -- but again, that's a Caddy-ism.

> For instance, you mentioned that header fields vary, TLS may or may not be used, etc. Does that mean that the same access log may or may not contain certain fields and will depend on the request?

Correct - since server configurations vary widely (and I mean, _really_ widely) I can't make any guarantees as to the uniformity of the logs. Francisco is right -- you can't be sure of the order of the fields, or the existence of any fields.

My suggestion for handling this is simple: if the required fields are missing, skip the log entry.

(PS. Thank you for making a format string! I'll try it out when I have a second this week.)

So, if we are okay with not worrying about super-optimal-performance for this one feature, then in theory the functionality is as simple as parsing the JSON line (probably 1 line of code if using a library), get the required fields, and if they don't exist, skip it.

Also -- there are Go libraries for traversing into JSON objects fairly efficiently without parsing the whole thing. So for example, the input is a path (like above, `request>uri` or something like that) and the library will use a very simple state machine to look inside the JSON structure and quickly find that field, without parsing the whole thing. An equivalent in C may be very useful for this.

**Comment by allinurl** [comment]
Thanks Matt and Francisco for your input and suggestions here. Like you said, it doesn't need to be  super-optimal-performance for this one feature so what I can see implementing is an additional parser that takes care of structured logs. 

I'd need to get a bit more familiar with LTSV and see how it can be implemented as part of this enhancement. Aside from JSON and LTSV, do you know what other popular structured logs are there?

**Comment by francislavoie** [comment]
There's [logfmt](https://brandur.org/logfmt) as well 👍

**Comment by ArpitKotecha** [comment]
> There's [logfmt](https://brandur.org/logfmt) as well 👍 

@allinurl Hi just wanted to know does logfmt or caddyjson support is going to be added?

**Comment by allinurl** [comment]
@ArpitKotecha It's certainly in the pipeline. Stay tuned!

**Comment by DWiskow** [comment]
As an interim work around whilst this works its way along the pipeline, i have created a python script that will allow Caddy JSON data logs to be streamed to GoAccess in real-time. Details and the code can be found on my github site [CaddyGoAccessDataLoggerConverter](https://github.com/DWiskow/CaddyGoAccessDataLoggerConverter).

It may be that this approach can be adapted for other providers of structured logs too.

**Comment by allinurl** [comment]
@DWiskow This is great! Thanks for sharing this, Dorian!

**Comment by DWiskow** [comment]
@allinurl no problem, I really like GoAccess and wanted to use it with Caddy, as I am sure others also do.

If you look at the code, you will see that the actual conversion from the JSON Input is a very simple (function convertJSONtoGoAccess at line 215-245 in the github code).

Given that GoAccess already reads and parses an input log file, it would be very simple to add this logic with the JSON keys specified as suggested by Matt Holt above. If there is anything I can do to help With this, just let me know.

**Comment by mholt** [comment]
One other thing to consider: sometimes the structure of structured logs changes depending on the part of the code it is emitted from. For example, an HTTP request has one structure while a TLS handshake has a different one.

So you will want to be sure to make it possible to define multiple paths to a particular metric (and use the first one that is valid in any given log) OR make the paths conditional on the structure or logger name or something. In my example in the OP above, the `"logger"` field is the logger name. (But it might be simpler to just allow the user to configure multiple paths to a metric, and then use the first one that exists.)

**Comment by AtjonTV** [comment]
I love GoAccess and I love Caddy 2. But as GoAccess doesnt yet support the JSON structure I have hacked together a little Python script that transforms the Caddy JSON files into a NCSA vHost file for consumption by GoAccess.

I know that Caddy 2 can output CLF, but it neither has vhosts, referers nor user-agents. So my tool has that with the NCSA vHost format.

Upstream Gitlab: https://gitlab.atvg-studios.com/atjontv/caddy2ncsa
Mirror Github: https://github.com/AtjonTV/Caddy2NCSA

I have added stuff like GZIP support just now so that it can consume the gz files from Caddys log rolling.

Its not a permanent solution but a nice start for everyone who needs this functionality right now.

(Please excuse my bad Python code, I am a Kotlin Programmer)

Bonus: If I input 66MB of Caddy JSON, I get 5.4MB of NCSA vHost log, GoAccess has a 6 second processing time (with `-a -g -e <ip> --anonymize-ip` arguments)

**Comment by rumpelsepp** [comment]
> Anyway, don't worry about finding a log format that works for JSON logs -- instead, let's work on adding first-class support for structured logs +1

For the time being the json logs could be transformed into something parseable by goaccess via `jq`, couldn't it?

**Comment by allinurl** [comment]
@rumpelsepp You certainly can, I saw this post https://alexmv12.xyz/blog/goaccess_caddy/, so you could derive a one-liner:

> example.com:X 127.0.0.1 [30/Mar/2020:19:38:34 CST] "GET / HTTP/2.0" 200 2326 "http://example.com/bot.html" "curl/7.64.1" 1.4711e-05

    jq -j '.ts |= strftime("%d/%b/%Y:%H:%M:%S %Z") | .request.remote_addr |= .[:-6]  | .request.host, ":X ", .request.remote_addr, " [", .ts ,"]", " \"", .request.method, " ", .request.uri, " ", .request.proto, "\" ", .status, " ", .size, " \"", .request.headers.Referer[0] // "-","\"", " \"", .request.headers."User-Agent"[0] // "-","\"", " ", .latency, "\n"' access.log | goaccess - --log-format=VCOMBINED

or to capture the latency:

    jq -j '.ts |= strftime("%d/%b/%Y:%H:%M:%S %Z") | .request.remote_addr |= .[:-6]  | .request.host, ":X ", .request.remote_addr, " [", .ts ,"]", " \"", .request.method, " ", .request.uri, " ", .request.proto, "\" ", .status, " ", .size, " \"", .request.headers.Referer[0] // "-","\"", " \"", .request.headers."User-Agent"[0] // "-","\"", " ", .latency, "\n"' ../logs/caddy.log | ./goaccess - --log-format='%v:%^ %h %^[%d:%t %^] "%r" %s %b "%R" "%u" %T' --date-format=%d/%b/%Y --time-format=%T

I'm getting closer to the point where I can implement this natively.

**Comment by allinurl** [comment]
@mholt I'm working on adding JSON support to goaccess. Though, I do have a couple of questions for you regarding Caddy's JSON log format that maybe you can help me with. 

1. I'm trying to understand why some of the fields are presented as an array, e.g., `"User-Agent": ["curl/7.64.1"]`,`"Content-Type": ["text/html; charset=utf-8"]` could these fields somehow hold more than one value under Caddy?
2. Are Caddy users able to log the actual cipher suite name as opposed to their id, e.g., `TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384` vs  `49196`. And do you know how Caddy is generating that id?
 
Thank you for any info you can provide!

**Comment by francislavoie** [comment]
> I'm trying to understand why some of the fields are presented as an array, e.g., "User-Agent": ["curl/7.64.1"],"Content-Type": ["text/html; charset=utf-8"] could these fields somehow hold more than one value under Caddy?

Yes, HTTP headers can have more than one value if they are repeated. For example:
```
Foo: Bar
Foo: Baz
```

You'll see this in the JSON: `"Foo": ["Bar", "Baz"]`.

> Are Caddy users able to log the actual cipher suite name as opposed to their id, e.g., TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384 vs 49196. And do you know how Caddy is generating that id?

The values are here: https://pkg.go.dev/crypto/tls#pkg-constants, Caddy just uses the consts from stdlib. I think those are well-known constants as per the TLS spec https://tools.ietf.org/html/rfc5246#appendix-A.5

**Comment by allinurl** [comment]
@francislavoie Thanks for the response. I'm a bit confused, so for the response, e.g., `Content-Type` shouldn't be only one type based on the requester's Accept? https://greenbytes.de/tech/webdav/rfc2616.html#rfc.section.14.17. For me it seems like it is: a single type/subtype + params? I can't find any reference where you can return multiple content types on the response header, but maybe I'm missing something?

**Comment by francislavoie** [comment]
The `Content-Type` header will generally not have multiple values, but _in general_, headers _can_. Caddy will always wrap them in an array regardless, to keep the type consistent.

**Comment by allinurl** [comment]
Got it. I think makes sense for some of the fields. Certainly confusing for others :) I'll take that into account on my end. Thanks again for the prompt response!

**Comment by mholt** [comment]
Yep, more crucially, the array can expose bugs in web applications or clients that are setting multiple values for a header field that should only have one value.

**Comment by allinurl** [comment]
Native JSON support has been added. Feel free to build from development to test this out. It will be pushed out in the upcoming release (v1.4.4). In addition, I added a quick pre-defined format for Caddy, e.g.,

    # goaccess accesss.log --log-format=CADDY -o report.html

or from a remote server:

    # ssh -n root@server 'tail -f access.log' | goaccess - --log-format=CADDY -o report.html --real-time-html

**Note**: SSH requires `-n` so GoAccess can read from stdin. Also, make sure to use SSH keys for authentication as it won't work if a passphrase is required.

The `CADDY` format is composed of these fields:

```
{
    "ts": "%x.%^",
    "request": {
        "remote_addr": "%h:%^",
        "proto": "%H",
        "method": "%m",
        "host": "%v",
        "uri": "%U",
        "headers": {
            "User-Agent": ["%u"]
        },
        "tls": {
            "cipher_suite": "%k",
            "proto": "%K"
        }
    },
    "duration": "%T",
    "size": "%b",
    "status": "%s",
    "resp_headers": {
        "Content-Type": ["%M"]
    }
}
```

Thanks again for the all the info provided.

Closing this, feel free to reopen it if needed.

**Comment by mholt** [comment]
Just tried it out real quick. Very nice -- seems to work! Thanks so much! Great job with GoAccess.

**Comment by allinurl** [comment]
Glad to hear it worked for you :) I still got a few more things to do before I can push this version out but I expect it will be soon. Thanks a lot for suggesting this!

One thing I forgot to mention and mostly as a future note for folks building from source, please make sure to build with libssl e.g., `./configure --with-openssl` so that it can output the cipher and tls version out in the report.

**Comment by alexpovel** [comment]
This looks promising! For now however, I can't get it to work. Please help me understand why we specify `%x` for the `ts` field. Shouldn't it be `%s`, seconds since epoch?

I'm getting an error related to this. I'm running the latest version that should have the `CADDY` format:

```bash
$ docker run --rm allinurl/goaccess --version
GoAccess - 1.4.5.
For more details visit: https://goaccess.io/
Copyright (C) 2009-2020 by Gerardo Orellana

Build configure arguments:
  --enable-geoip=mmdb
  --with-openssl
```

I prepared a line from the relevant logs as an example. The following is written to `test.json` in the current working directory:

```json
{ "level": "info", "ts": 1611931913.2766495, "logger": "http.log.access", "msg": "handled request", "request": { "remote_addr": "1.2.3.4:1337", "proto": "HTTP/1.1", "method": "POST", "host": "domain.com", "uri": "/api/v4/jobs/request", "headers": { "User-Agent": [ "someone" ], "Content-Length": [ "665" ], "Accept": [ "application/json" ], "Content-Type": [ "application/json" ], "Accept-Encoding": [ "gzip" ] }, "tls": { "resumed": false, "version": 772, "cipher_suite": 4865, "proto": "", "proto_mutual": true, "server_name": "domain.com" } }, "common_log": "1.2.3.4 - - [29/Jan/2021:14:51:53 +0000] \"POST /api/v4/jobs/request HTTP/1.1\" 204 0", "duration": 0.004342909, "size": 0, "status": 204, "resp_headers": { "Date": [ "Fri, 29 Jan 2021 14:51:53 GMT" ] } }
```

(For readability:)

```json
{
    "level": "info",
    "ts": 1611931913.2766495,
    "logger": "http.log.access",
    "msg": "handled request",
    "request": {
        "remote_addr": "1.2.3.4:1337",
        "proto": "HTTP/1.1",
        "method": "POST",
        "host": "domain.com",
        "uri": "/api/v4/jobs/request",
        "headers": {
            "User-Agent": [
                "someone"
            ],
            "Content-Length": [
                "665"
            ],
            "Accept": [
                "application/json"
            ],
            "Content-Type": [
                "application/json"
            ],
            "Accept-Encoding": [
                "gzip"
            ]
        },
        "tls": {
            "resumed": false,
            "version": 772,
            "cipher_suite": 4865,
            "proto": "",
            "proto_mutual": true,
            "server_name": "domain.com"
        }
    },
    "common_log": "1.2.3.4 - - [29/Jan/2021:14:51:53 +0000] \"POST /api/v4/jobs/request HTTP/1.1\" 204 0",
    "duration": 0.004342909,
    "size": 0,
    "status": 204,
    "resp_headers": {
        "Date": [
            "Fri, 29 Jan 2021 14:51:53 GMT"
        ]
    }
}
```

As far as I can see, we discard the decimal stuff with `.%^` and fetch the whole seconds with `%x`. Now, running `goaccess` on the above, single-line Caddy-emitted JSON line returns:

```bash
$ docker run --rm -v $(pwd):/log allinurl/goaccess --log-format=CADDY /log/test.json
 [SETTING UP STORAGE /log/test.json] {0} @ {0/s}
==1== GoAccess - Copyright (C) 2009-2020 by Gerardo Orellana
==1== https://goaccess.io - <hello@goaccess.io>
==1== Released under the MIT License.
==1==
==1== FILE: /log/test.json
==1== Parsed 1 lines producing the following errors:
==1==
==1== Token '1611931913' doesn't match specifier '%x'
==1==
==1== Format Errors - Verify your log/date/time format
```

This is out-of-the-box behaviour with no modifications. I wonder how this simple setup is different to those where people say it worked?

Taking your prepared formatting string and replacing `%x` with `%s` should work, I thought, since then the `'1611931913'` token should actually match `%s`, because that's what it is. For readability, I put this into a `goaccess.conf` file into the current working directory as well:

```conf
log-format {"ts": "%s.%^","request": {"remote_addr": "%h:%^","proto": "%H","method": "%m","host": "%v","uri": "%U","headers": {"User-Agent": ["%u"]},"tls": {"cipher_suite": "%k","proto": "%K"}},"duration": "%T","size": "%b","status": "%s","resp_headers": {"Content-Type": ["%M"]}}
time-format CADDY
date-format CADDY
```

(It won't run without specifying `time-format` and `date-format`; I don't understand that behaviour, maybe I made a mistake here.)

Now, the returned error is a bit bizzare:

```bash
$ docker run --rm -v $(pwd):/log allinurl/goaccess --config-file=/log/goaccess.conf /log/test.json
 [SETTING UP STORAGE /log/test.json] {0} @ {0/s}
==1== GoAccess - Copyright (C) 2009-2020 by Gerardo Orellana
==1== https://goaccess.io - <hello@goaccess.io>
==1== Released under the MIT License.
==1==
==1== FILE: /log/test.json
==1== Parsed 1 lines producing the following errors:
==1==
==1== Token '1611931913' doesn't match specifier '%s'
==1==
==1== Format Errors - Verify your log/date/time format
```

`1611931913` are our seconds since epoch and should therefore now definitely match `%s`, shouldn't it?

**Comment by allinurl** [comment]
@alexpovel Thanks for reporting this. Interesting, it looks like Alpine Linux, [musl `strptime(3)`](https://git.musl-libc.org/cgit/musl/tree/src/time/strptime.c) which is used to build the Docker image doesn't have support for `%s` (which goaccess uses as `time-format` and `date-format`) and thus you get that message. If you run it outside of Docker it should work fine and output the following. However, let me find a workaround for the Docker image and I'll post back.

![2021-01-29-143529_660x320_scrot](https://user-images.githubusercontent.com/5005367/106347166-05f2c980-6282-11eb-8d0e-804ff81861fd.png)

**Comment by allinurl** [comment]
Alright, the issue should be fixed. You will need to remove your current Docker image and run it again, e.g.,

    $ sudo docker rmi ea43ef7696fb
    $ cat caddy.log | sudo docker run --rm -i -e LANG=$LANG allinurl/goaccess -a -o html --log-format CADDY - > report.html

Let me know how it goes for you. Thanks!

**Comment by alexpovel** [comment]
Up and running now, thanks a lot for the super quick help and fix!

**Comment by allinurl** [comment]
@alexpovel That's great to hear, thanks for letting me know!
