### ISSUE TITLE
Error occured at: goaccess.c - main - 832

### ISSUE THREAD

**Issue by xhhan** [allinurl/goaccess#1769]
when I try to run "goaccess -f  access.log -a",it return some err like:
GoAccess - version 0.8.5 - Dec  5 2014 06:36:01

Fatal error has occurred
Error occured at: goaccess.c - main - 832
Nothing valid to process.

config:
date-format %d/%b/%Y
log-format "%h""\t%d:%t +0800""\t%m %U %H""\t%D""\t%s""\t%b""\t%R""\t%^""\t%^""\t%^""\t%^""\t%^""\t%^""\t%^""\t%^""\t%^""\t%^""\t%^""\t%^""\t%^""\t%^""\t%^""\t%^""\t%^""\t%^"

nginx log format:
```
log_format access "$remote_addr"
                      "\t$time_local"
                      "\t$request"
                      "\t$request_time"
                      "\t$status"
                      "\t$body_bytes_sent"
                      "\t$http_referer"
                      "\t$http_user_agent"
                      "\t$http_x_forwarded_for"
                      "\t$host"
                      "\t$hostname"
                      "\t$scheme"
                      "\t$server_name"
                      "\t$ssl_protocol"
                      "\t$ssl_server_name"
                      "\t$server_protocol"
                      "\t$ssl_cipher"
                      "\t$ssl_session_reused"
                      "\t$pipe"
                      "\t$tcpinfo_rtt"
                      "\t$upstream_addr"
                      "\t$upstream_connect_time"
                      "\t$upstream_response_time"
                      "\t$msec"
                      "\t$upstream_status";
```

log:

    127.0.0.1       14/May/2020:17:05:47 +0800      GET HTTP://test.vip.com/123 HTTP/1.1  0.115   200     2       -curl/7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.21.7 OpenSSL/1.0.0r zlib/1.2.3   -       ydtest.vip.com  xxx.com http    test.vip.com  -       -       HTTP/1.1        -       -       .       1000    10.198.189.46:80  0.057   0.115   1589447147.239  200

what's wrong??

**Comment by allinurl** [comment]
You won't be able to fully parse it as it's not delimited. For instance there's no delimiter between the user agent. Closest would be:

    goaccess access.log --log-format='%h %d:%t %^ %m %U %H %T %s %b %u %^' --date-format=%d/%b/%Y --time-format=%T

I'd set delimiters in that log format.

**Comment by allinurl** [comment]
Closing this.
