### ISSUE TITLE
[Visual] Dropdown menu overlaps text in Widescreen view

### ISSUE THREAD

**Issue by MasterGroosha** [allinurl/goaccess#1772]
GoAccess is built after commit dfbbe8b66f22dbda9ceddc5005d0114529d7d582
![изображение](https://user-images.githubusercontent.com/2780044/82098150-09065380-970d-11ea-8345-2ef133755da1.png)

**Comment by allinurl** [comment]
Good point. The widescreen was added mostly for 4K dashboards so I'm not sure it's worth moving the dropdowns. 

I'll close this and if it becomes a bigger issue I can look into possible solutions. Thanks though.
