### ISSUE TITLE
404 Issues with the debian jessie repo

### ISSUE THREAD

**Issue by Thaillie** [allinurl/goaccess#1778]
Heya, since yesterday we see issues with the debian jessie repo.
We are getting 404 when retrieving the Packages.

I saw in issues #1775 that there where some disk issues with the repo.
So I guess this issue can be related to that?
```
Ign http://deb.goaccess.io jessie/main Translation-en
Err http://deb.goaccess.io jessie/main amd64 Packages
  404  Not Found
Fetched 927 B in 9s (102 B/s)
STDERR: W: Failed to fetch http://deb.goaccess.io/dists/jessie/main/binary-amd64/Packages  404  Not Found
```

**Comment by allinurl** [comment]
Originally I didn't think about Jessie as it's going away soon. However, I just created the package so now it should be available for amd64. Let me know how it goes.

```
goaccess |  1:1.4-xenial |  xenial | amd64, i386
goaccess |  1:1.4-bionic |  bionic | amd64
goaccess |    1:1.4-eoan |    eoan | amd64
goaccess |   1:1.4-focal |   focal | amd64
goaccess |  1:1.4-jessie |  jessie | amd64
goaccess | 1:1.4-stretch | stretch | amd64, i386
goaccess |  1:1.4-buster |  buster | amd64, i386
```

**Comment by Thaillie** [comment]
Thank you for adding it to the repo again ^^
Everything is in working order now 👍
