### ISSUE TITLE
v1.4 fails to compile on macOS due to <malloc.h>

### ISSUE THREAD

**Issue by EricFromCanada** [allinurl/goaccess#1779]
In `src/parser.c` there's currently a reference to `#include <malloc.h>`. For macOS this should be changed to something like:
```
#if defined(__APPLE__)
#  include <malloc/malloc.h>
#else
#  include <malloc.h>
#endif
```

**Comment by allinurl** [comment]
Thanks for reporting it! I think it's safe to remove that include. Could you please try removing it and see if that works for you? If it works on your end, I can push a fix for this. Thanks.

**Comment by EricFromCanada** [comment]
Seems to work. Homebrew formula bump is in Homebrew/homebrew-core#54980.

**Comment by allinurl** [comment]
This has been fixed upstream. Thanks again!

**Comment by allinurl** [comment]
Just a quick note on the formula. `tokyo-cabinet` is no longer a dependency so no need for `--enable-tcb=btree`.

Thank you for submitting those changes!
