### ISSUE TITLE
No time format was found on your conf file. Error occurred at: src/parser.c - parse_log - 2777

### ISSUE THREAD

**Issue by elit3ge** [allinurl/goaccess#1782]
Having some issue deploying in Docker.

Have tried setting it in the config and out no luck.

```
Command
goaccess --time-format=%H:%M:%S --date-format=%d/%b/%Y --log-format=COMBINED --log-file=/tmp/access.log --no-global-config --config-file=/goaccess/goaccess.conf --output=/goaccess/index.html
```

```
GoAccess - version 1.4 - May 18 2020 04:06:39,
Config file: /etc/goaccess/goaccess.conf,
Fatal error has occurred,
Error occurred at: src/parser.c - parse_log - 2777,
No time format was found on your conf file.
```

**Comment by florenthemmi** [comment]
Same issue here, the config file is not backward compatible with GoAccess 1.3

**Comment by allinurl** [comment]
Are you sure you don't have any other config file under `~/.goaccessrc` or previously in 1.3 was `/usr/local/etc/goaccess.conf`. You could try specifying it with `-p /usr/local/etc/goaccess/goaccess.conf` to make sure you are setting the right path.

**Comment by elit3ge** [comment]
> Are you sure you don't have any other config file under `~/.goaccessrc` or previously in 1.3 was `/usr/local/etc/goaccess.conf`. You could try specifying it with `-p /usr/local/etc/goaccess/goaccess.conf` to make sure you are setting the right path.

Nope, it was a brand new docker installation.

**Comment by johnpilbeam** [comment]
I had this issue on macOS/Homebrew. The solution was to edit the config file:
`/opt/homebrew/Cellar/goaccess/1.5.1/etc/goaccess/goaccess.conf`
Uncomment lines 13 and 36:
`time-format %H:%M:%S
date-format %d/%b/%Y
`
Save the file and run the command again.

**Comment by florenthemmi** [comment]
Thanks @johnpilbeam for you feedback.
It is already done in my previous comment https://github.com/allinurl/goaccess/issues/1782#issuecomment-633125643.

**Comment by allinurl** [comment]
@florenthemmi are you still having issues with this? Are you running it through Docker?

**Comment by florenthemmi** [comment]
Hello @allinurl

Same config with latest version.

```
> /usr/local/bin/goaccess -f /logs/access.log -a -o /var/www/html/index.html

 [SETTING UP STORAGE /logs/access.log] {0} @ {0/s}
GoAccess - version 1.5.1 - Jul  7 2021 13:29:55
Config file: /usr/local/etc/goaccess/goaccess.conf

Fatal error has occurred
Error occurred at: src/parser.c - parse_log - 2043
No time format was found on your conf file.
```

**Comment by allinurl** [comment]
@florenthemmi Have you tried running it as specified [here](https://github.com/allinurl/goaccess#docker)? Please let me know if that works on your end.

**Comment by florenthemmi** [comment]
So it works as expected. Thanks @allinurl!

My config was not used in my last try (my bad).
Instead the default one was used, which is not working with Nginx (need to uncomment lines 13 and 36).

I suggest to close this issue (v1.4). Looks like it is fixed in v1.5.

**Comment by allinurl** [comment]
@florenthemmi Glad that worked. Feel free to reopen it if needed.

**Comment by dogukankurnaz** [comment]
If you do the above and still get errors:

My solution= sudo nano /etc/goaccess/goaccess.conf

######################################
 Log Format Options (required)
######################################


 NCSA Combined Log Format
log-format %h %^[%d:%t %^] "%r" %s %b "%R" "%u"

remove the comment line.

Note: First of all, after testing the application as goaccess xxxx.log and finding the most suitable and working order, revise and edit the goaccess.conf file (worked fine for my access.log file)   :)

Thank you.

**Comment by allinurl** [comment]
@dogukankurnaz Thanks for posting those additional details.

**Comment by pixelpadre** [comment]
I changed the log file from NCAS to common in the goaccess.conf file.  That worked for my apache centos 7 server.
