### ISSUE TITLE
Token '92.118.161.13.netsystemsresearch.com' doesn't match specifier '%h' in v1.4

### ISSUE THREAD

**Issue by cvmiller** [allinurl/goaccess#1784]
Using Apache  common log format. When running goaccess (v1.4):
/usr/local/bin/goaccess - -o /home/cvmiller/my_report.html --log-format=COMBINED

I get the error:
```
Parsed 1 lines producing the following errors:

Token '92.118.161.13.netsystemsresearch.com' doesn't match specifier '%h'

Format Errors - Verify your log/date/time format
```

It seems like the parser is confused by the fact that the hostname begins like an IPv4 address, but is in fact part of a larger hostname. Other hosts which fail with this error are:
```
187.114.156.0.static.host.gvt.net.br
ec2-34-223-93-168.us-west-2.compute.amazonaws.com
```
Also saw this issue  in version 1.3. Built goaccess with the following:
```
 ./configure --enable-utf8 --without-libintl-prefix
make
sudo make install
```

**Comment by allinurl** [comment]
You can try using `--no-ip-validation`.

**Comment by cvmiller** [comment]
Thanks! That solves the problem.

Perhaps this is a documentation issue, as I don't see `--no-ip-validation` in the `--help`

**Comment by allinurl** [comment]
Thanks for reporting that. I did add it to the man page but completely forgot adding it to the `--help`. I just pushed an update upstream.

Closing this, feel free to reopen it if needed.
