### ISSUE TITLE
https://goaccess.io/ cert expired

### ISSUE THREAD

**Issue by clintnetwork** [allinurl/goaccess#1785]
Hey,

Please check!

Kind regards

**Comment by allinurl** [comment]
> Expires On	Thursday, August 20, 2020 at 12:23:32 PM

Are you getting an error message? Could you please try doing a hard-refresh? Thanks

**Comment by iamdoubz** [comment]
I did get this from my mobile device, but it appears to have gone away now. It was weird though.

**Comment by allinurl** [comment]
I was working on a couple of servers over the weekend so it could've that the failover server kicked in with a bad certificate. I'll check. Thanks for reporting it though!

Feel free to reopen it if needed.
