### ISSUE TITLE
Historic reports with bandwidth/size showing 0 bytes

### ISSUE THREAD

**Issue by armandelli** [allinurl/goaccess#1786]
Hey there!

First of all, GREAT tool here! Congratulations and thanks a lot for developing it! :)

I am generating 7 days and 30 days reports on a daily basis with cron and serving them on my NGINX webserver. However, these historic reports are showing the request sizes and calculated total bandwidth as 0 bytes, as per prints below.

![print2](https://user-images.githubusercontent.com/33656020/82902696-3ab1c280-9f36-11ea-807f-caad54617a0f.PNG)
![print1](https://user-images.githubusercontent.com/33656020/82902699-3c7b8600-9f36-11ea-874a-6dbba51573cb.PNG)

However when I run the perl command(which I got from another issue posted) manually, it returns the size normally:

 _find /var/log/nginx/logs-historico/ -name 'dashboards-gti*' -mtime -7 -type f -exec zcat '{}' + |perl -e 'my $sum=0; while(<>) { my ($traffic) = m/\[.+\] ".+" \d+ (\d+)/; $sum += $traffic}; print "$sum\n"'
1960979562_

One other thing: Real time works fine!

Any ideas as to what is happening?

Thanks a lot!
Andre.

**Comment by allinurl** [comment]
Looks like the log-format may be wrong. Could you please post the log-format you are using and a few lines from your access log? Thanks

**Comment by armandelli** [comment]
Here is the full command:

_goaccess /var/log/nginx/dashboards-gti.access.log --log-format=COMBINED -o /var/www/$servername/proxyreverso/dashboards-gti-realtime.html --real-time-html --port=17903 --fifo-in=/tmp/dashboards-gti.in --fifo-out=/tmp/dashboards-gti.out --daemon_

Log format is COMBINED

And here is the log line(please note that I replaced the full actual address with their variables, just for confidenciality):

_10.0.11.153 - - [26/May/2020:00:00:25 -0300] "GET /api/org/users/lookup HTTP/1.1" 200 253 "$protocol$servername/?orgId=1" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36"_

The log format on NGINX is:
_log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';_

I am guessing  the issue is something stupid from my part, but if it were a format issue, wouldn't it be happening to the realtime report as well?

Thanks!

**Comment by allinurl** [comment]
Seems like you got an extra field in there for the `http_x_forwarded_for`. So I'd run it like (assuming you are ignoring that field for some reason):

    goaccess access.log --log-format='%h %^[%d:%t %^] "%r" %s %b "%R" "%u"%^' --date-format=%d/%b/%Y --time-format=%T

**Comment by armandelli** [comment]
@allinurl the problem was, as predicted, much simpler!

Thanks to your correction, as I was about to apply it, I noticed that the commands in my script which was generating the historical reports were missing a "-" (as in "-log-format=..." instead of "--log-format=...")

Thanks a lot for your quick replies and sorry to take your time!
Cheers!

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
