### ISSUE TITLE
Apache2 Log Config Help

### ISSUE THREAD

**Issue by iamdoubz** [allinurl/goaccess#1787]
First off, this project looks _super awesome_ and cannot wait to start using it! I heard about GoAccess through an acquaintance on diaspora. Now, to the actual problem I am having.

It pains me to ask for help, but I am at my wits end with configuring the log file format.

## My set up

- Ubuntu 18.04
- Compiled from source (utf8, mmdb, openssl config options)
- Apache2 version 2.4.29
- Stock access files (nothing custom to my knowledge)
- I have at least 15 websites
- All logs match the below format

```
8.8.8.8 - - [26/May/2020:11:21:59 -0500] "GET / HTTP/2.0" 200 3844 "https://www.dou.bet/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36 Edg/83.0.478.37"
```

What I have in my `/usr/local/etc/goaccess/goaccess.conf` file right now:

```
time-format %T %z
date-format %d/%b/%y
log-format VCOMBINED
color-scheme 3
config-dialog false
hl-header true
html-prefs {"theme":"bright","perPage":5,"layout":"horizontal","showTables":true,"visitors":{"plot":{"chartType":"bar"}}}
html-report-title Server Live Stats
json-pretty-print true
no-color false
no-column-names false
no-csv-summary false
no-progress false
no-tab-scroll false
with-mouse false
agent-list false
with-output-resolver false
http-method yes
http-protocol yes
no-query-string false
no-term-resolver false
444-as-404 false
4xx-to-unique-count false
all-static-files false
double-decode false
ignore-crawlers false
crawlers-only false
ignore-panel REFERRERS
ignore-panel KEYPHRASES
real-os true
static-file .css
static-file .js
...
```

Any guidance is greatly appreciated. Even if it is "look here to find the variables" manual or something. Thanks in advanced.

**Comment by allinurl** [comment]
Glad you found it useful :) To keep it simple, I'd run goaccess as

    goaccess access.log --log-format=COMBINED -o report.html

Or

I'd replace the config file as:

```
log-format COMBINED
html-prefs {"theme":"bright","perPage":5,"layout":"horizontal","showTables":true,"visitors":{"plot":{"chartType":"bar"}}}
html-report-title Server Live Stats
agent-list true
```

**Comment by iamdoubz** [comment]
-sigh- I tried that, but didn't pay attention to _what_ log file I was choosing. I was lazy and did `*.log`, which is just awful. Once I change it to `*.access.log` wouldn't you know it, it works :-/

Can't wait to setup another subsite for this :)

Thanks for your help.
