### ISSUE TITLE
Add cumulative time served column

### ISSUE THREAD

**Issue by ottok** [allinurl/goaccess#179]
In the example report at http://goaccess.io/goaccess_html_report.html?1410179475#requests the table for requested files (actually the title should be simply "Most frequent requests" as each line in the access.log is per request and not always per a file) each row contains the following columns:
- path of the URL
- cumulative hits for the URL
- cumulative URL hits precentage of all hits
- cumulative bandwith
- time served

The "Time served" column seems problematic. How can the values be so slow? If the bandwith is about 35 MB or "GET /", how come the time was only 137 milliseconds? I suspect the request time field is just for one request. Is it the time for the first or last request? Is it the mean time for all requests of that URL?

I think the most logical value would be to show the cumulative time for each request, just as the cumulative bandwith is shown. That way admins can see what are the URLs that hog the biggest slices of bandwith and server resources (the more cumulative time is spend per resource, the more strain it probably puts on the server).

**Comment by allinurl** [comment]
@ottok I've added the cumulative and max time served columns and named them accordingly.

Feel free to build/test it from [development](http://goaccess.io/download#build), otherwise, it will be out in the upcoming version.

**Comment by ottok** [comment]
Thanks!

If you would provide nightly builds or a PPA on Launchpad it would be easy to test our development versions.

**Comment by ottok** [comment]
I've build from github master and I confirm this works nicely. Now if only the columns were sortable so that clicking on "Cum T.S." would result in a list of sites that cumulatively consume most time, then I'd know to focus optimization on those URLs...

Something like http://tablesorter.com/docs/ would be easy to implement if you are willing to bloat the html reports with jQuery

**Comment by allinurl** [comment]
Glad that worked!

I've been working on some major changes to the HTML UI, so I'll take a look at the sort capability. Right now sorting some of the tables does not work well due to the nesting of some table rows. i.e., browsers, hosts.

**Comment by allinurl** [comment]
BTW, not exactly the same, but just for the record, you could sort them right now upon parsing the log with `--sort-panel=PANEL,METRIC,ORDER` see `man goaccess` for available metrics, order and panels.

**Comment by ottok** [comment]
If I run goaccess in interactive mode and press S to set sort options it works, but neither of the command line commands seem to do the trick:
```
goaccess -f total-access.log --sort-panel=REQUESTS,BY_CUMTS,DESC
goaccess -f total-access.log --sort-panel=REQUESTS,BY_CUMTS,DESC > test.html
```

**Comment by allinurl** [comment]
Found the [issue](https://github.com/allinurl/goaccess/blob/master/src/sort.c#L383), I'll have a fix soon!

**Comment by allinurl** [comment]
@ottok This has been fixed. Please feel free to rebase.

**Comment by ottok** [comment]
Re-built binary at commit 1218d1b8aa70fdd65ca42e449f6a15fbe4a2e28e and I confirm that the sorting of CUMTS now also works!
