### ISSUE TITLE
Help with custom log format with tabs

### ISSUE THREAD

**Issue by p01acos** [allinurl/goaccess#1791]
Hi, I have a custom log that separates data by tab (TSV log format).
Log is a DNS query.

This is a snipped of the log
[2020-05-27 14:47:47]	10.10.1.1	badexample.com	A	FORWARD	24ms	10.10.1.1:53

This is my goaccess.conf 
time-format %H:%M:%S
date-format %Y-%m-%d
log-format [%d %t] %h %v %U %^ %^ %^ %^

It works fine when I manually change tab to space, but can't figure out how to get the tab read by goaccess so interprets the log file.

This is what I keep getting when trying to run goaccess

Parsed 1 lines producing the following errors:
Token for '%h' specifier is NULL.
Format Errors - Verify your log/date/time format

Thanks in advance

**Comment by allinurl** [comment]
You can always use `\t` as delimiter. e.g., 

    log-format [%d %t]\t%h\t%v\t%U\t%^

**Comment by p01acos** [comment]
> log-format [%d %t]\t%h\t%v\t%U\t%^

so simple yet so far :|
bloody legend mate, cheers
