### ISSUE TITLE
How can I parse json?

### ISSUE THREAD

**Issue by mrbinary71** [allinurl/goaccess#1792]
Custom Json:

May 28 03:46:43 83.105.130.100  2020-05-28T03:46:43Z logserver-1 testcdn[1]: {"method":"GET","scheme":"https","domain":"example.com","uri":"/services/Data@1.0.0/history","query_string":"market=stock\u0026symbolId=26014913469567886\u0026rangeKey=oneMonth\u0026property=%5B%22priceVolume%22%2C%20%22name%22%5D","ip":"6.79.34.106","ua":"okhttp/3.12.2","country":"US","asn":16322,"content_type":"application/json","status":200,"server_port":443,"bytes_sent":1105,"bytes_received":2053,"upstream_time":0.052,"cache":"MISS","request_id":"e71d502e1734a5491565222134342192"}

**Comment by viktomas** [comment]
This should help you https://github.com/allinurl/goaccess/issues/634
