### ISSUE TITLE
Can i use GoAccess with iptables.log ?

### ISSUE THREAD

**Issue by ZerooCool** [allinurl/goaccess#1793]
Hello, i search a tool for visualized my file iptables.log.

Can i use GoAccess with iptables.log ?

**Comment by allinurl** [comment]
You may. Though the fields won't necessarily match the context of goaccess' report. e.g., request, browser, etc...

**Comment by ZerooCool** [comment]
Ok, in my case, I don't want to have to adapt fields, so I consider that, initially, it is not adapted.

Thank you for your reply.
If, despite everything, someone has used GoAcces with Iptables logs, tutorials are welcome.

**Comment by allinurl** [comment]
Closing this. However, feel free to reopen it if needed.
