### ISSUE TITLE
icons not rendering

### ISSUE THREAD

**Issue by improvethings** [allinurl/goaccess#1795]
![goaccess-icons](https://user-images.githubusercontent.com/16601027/83439530-33882a00-a3f8-11ea-9dbe-21d03b115cab.png)

$ dpkg -l | grep goaccess
ii  goaccess                                 1:1.2-4+b10                                  amd64        log analyzer and interactive viewer for the Apache Webserver

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 10 (buster)
Release:	10
Codename:	buster

$ uname -srm
Linux 4.19.0-9-amd64 x86_64

**Comment by allinurl** [comment]
Could you please try building from source or using the latest deb package from the [**official deb repo**](https://goaccess.io/download#official-repo)? Please let me know if that fixes the issue. Thanks

**Comment by improvethings** [comment]
They display fine when pulling from the official depo!
