### ISSUE TITLE
Missing HTTP status code 308 support

### ISSUE THREAD

**Issue by petrkutalek** [allinurl/goaccess#1796]
Please, add also support for HTTP status code [308 Permanent Redirect](https://tools.ietf.org/html/rfc7538#section-3).

It is complementary to already supported 307 (Temporary Redirect). You know, it is the same as 301 – 302 pair.

```
goaccess-master/src/util.c
goaccess-master/src/labels.h
goaccess-master/po/…
```

**Comment by allinurl** [comment]
Thanks for pointing this out. It has been added and will be pushed out in the upcoming release.
