### ISSUE TITLE
Pane: 8 - Time Distribution always blank with default Squid access log format

### ISSUE THREAD

**Issue by Kevin-NZ** [allinurl/goaccess#1810]
There is an issue when parsing the decimal dates found within the standard Squid access logs.  It was working in GoAccess v1.2 but broke in v1.3 and is still broken in v1.4.

To reproduce this you can create a small log file called squid.log containing the following three lines:
`1591919639.503    271 123.0.0.1 TCP_TUNNEL/200 3951 CONNECT outlook.office.com:443 - HIER_DIRECT/123.0.0.1 -`
`1591919643.857   3578 123.0.0.1 TCP_TUNNEL/200 24531 CONNECT outlook.office.com:443 - HIER_DIRECT/123.0.0.1 -`
`1591919648.857   4211 123.0.0.1 TCP_TUNNEL/200 13631 CONNECT outlook.office.com:443 - HIER_DIRECT/123.0.0.1 -`

One this file has been created you can duplicate the issue using the following command (with either v1.3 or v1.4):
`goaccess --no-global-config --log-format='%x.%^ %~ %L %h %^/%s %b %m %U %^' --date-format=%s --time-format=%s squid.log`

You will find that the "Time Distribution" pane is empty, when it should have three hits.

I've not got time to look into the root cause, however I was able to workaround the issue for this use-case by adding “`logitem->time=tkn;`” just before the “`break;`” within the “`case 'x':`” clause located in the “`parse_specifier`” function found at line 1063 in the “`src/parser.c`” code.

Obviously this is a hack as the parser library was refactored during the v1.3 release, but it did resolve the issue I was seeing.  Somebody with more knowledge of the libraries might be able to come up with a more legitimate fix.

The bottom of the clause now reads as follows:

`1060:    set_numeric_date (&logitem->numdate, logitem->date);`
`1061:    set_tm_dt_logitem (logitem, tm);`
`1062:    set_tm_tm_logitem (logitem, tm);`
**`1063:    logitem->time=tkn;`**
`1064:    break;`

**Comment by allinurl** [comment]
Thanks @Kevin-NZ for reporting this. It has been fixed upstream. Feel free to test it by building from [**development**](https://github.com/allinurl/goaccess#build-from-github-development) and let me know if that fixes the issue on your end. Otherwise it will be pushed out in the upcoming version.
