### ISSUE TITLE
NGINX revers proxy + goaccess

### ISSUE THREAD

**Issue by karkaaa** [allinurl/goaccess#1811]
Hello,

How i can run goaccess over nginx revers proxy (linuxserver.io letsencrypt)?

I take goaccess.conf from https://github.com/allinurl/goaccess/issues/1789

Thank you.

**Comment by allinurl** [comment]
Maybe any of [these](https://github.com/allinurl/goaccess/search?q=reverse+proxy&type=Issues) can help?

**Comment by karkaaa** [comment]
I try, but it doesn't work and I don't know how him run goaccess. I asked how his run goaccess.

**Comment by karkaaa** [comment]
i found problem

need change from addr 127.0.0.1 to this 0.0.0.0

goaccess run:
goaccess  /var/log/nginx/access.log -o  /var/www/real-time.html

and my nginx revers config is:
```
upstream goaccess {
    server IPaddress:7890;
    keepalive 60;
}

server {

    listen 443 ssl; 

    server_name goaccess.*;

    include /config/nginx/ssl.conf;

    root /config/www;
    index real-time.html;

    client_max_body_size 0;

    location / {
	    include /config/nginx/proxy.conf;
            try_files $uri  $uri/ @goaccess;
            index  real-time.html;
            proxy_set_header Upgrade $http_upgrade;
            proxy_buffering on;            
            proxy_set_header Connection "Upgrade";
    }

    location @goaccess{
            proxy_pass http://goaccess;
    }
}

```
