### ISSUE TITLE
No time format was found on your conf file

### ISSUE THREAD

**Issue by hawk291** [allinurl/goaccess#1814]
Hello, 

Version used  1.3 on CentOS 7.

When executing this, like stated on this page https://goaccess.io/man#configuration
`
awk '$9~/408/' nginx_access.log | goaccess -
`
Having this error
`GoAccess - version 1.3 - Mar 29 2020 22:32:54
Config file: No config file used
Fatal error has occurred
Error occurred at: src/goaccess.c - set_curses - 1449
No time format was found on your conf file.`

/etc/goaccess/goaccess.conf has these fields set as follows (default):
`date-format %d/%b/%Y
log-format %h %^[%d:%t %^] "%r" %s %b "%R" "%u"
time-format %H:%M:%S
`

However this 
`goaccess nginx_access.log` 
works OK, I see all the stats.

**Comment by allinurl** [comment]
Could you please try v1.4 as the config issue was fixed in there. Let me know if that works.

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
