### ISSUE TITLE
Possible issue with incremental logic

### ISSUE THREAD

**Issue by udf2457** [allinurl/goaccess#1815]
I'm planning to move from Matomo to goaccess, and as part of that I was reading the goaccess docs.

It occured to me that your incremental processing logic (`inode:29627417|line:20012|ts:20171231235059`) may possibly cause you a problem in scenarios where truncation is occuring.

For example the popular `logrotate` tool has an option called `copytruncate` whereby it copies a file and truncates the existing one in place.

This leaves you in a situation with an unchanged inode:
```
$ echo 'test' > test
$ ls -i test
67109680 test
$ truncate -s0 test
$ ls -i test
67109680 test
$ cat test 
$
```
So, according to your logic :

> If the inode does not match the current file, it parses all lines. If the current file matches the inode, it then reads the remaining lines and updates the count of lines parsed and the timestamp. As an extra precaution, it won't parse log lines with a timestamp ≤ than the one stored.

Therefore, in a `copytruncate` scenario, the inode matches. So goaccess would go looking for the "remaining lines", but these no longer exist because the file has been truncated ?

**Comment by allinurl** [comment]
Thanks for bring that up. That's a totally valid point. I'd need to think further about this, do you have any input on how it should be handled?

**Comment by udf2457** [comment]
The simplest answer might be just to check file size has not decreased.  But I'm not sure if that's too naïve a method ?  I'll try to have a think.

**Comment by allinurl** [comment]
I agree, I can't think right now of a better way than what you are suggesting. I think that would be the safest bet for now. I'll work on a fix and release a new version asap. If for some reason, you have some additional ideas, please let me know. Thanks again!

**Comment by udf2457** [comment]
Thanks @allinurl 

I don't speak C but I had a quick search of the source for `logrotate`, it looks like they just call `ftruncate(fdcurr, 0)` (https://github.com/logrotate/logrotate/blob/85d0c9086ca541966f19137aabfe31f91f7170a6/logrotate.c#L1212).

So, at least for the `logrotate` scenario, it should be a very safe bet indeed to rely on a simple file size check.

I have not thought of any other ideas at the moment, apart from maybe it might be possible to do something clever with crypto hashes (e.g. hash a selection of lines at random points in the file, then re-hash on the next run .... non-matching hashes would mean "something has changed", so re-process from the beginning).

**Comment by udf2457** [comment]
@allinurl 

It occured to me, its not only with `copytruncate` where you could have problems relying on `inode`, it could also occur in pure file rotation scenarios.

If a file is removed from disk and a new one is created immediately afterwards, there is a real possibility that the new file could have the same `inode` as the old file (because Linux can and does reuse `inode` numbers).

**Comment by 0bi-w6n-K3nobi** [comment]
Hi, everyone.
Maybe so complex to implement, but exits [inotify(7)](https://man7.org/linux/man-pages/man7/inotify.7.html).

**Comment by allinurl** [comment]
@0bi-w6n-K3nobi inotify is a Linux kernel feature so wouldn't work on a bsd system and others.

**Comment by allinurl** [comment]
This has been fixed from [**this commit**](https://github.com/allinurl/goaccess/commit/2e14dc306f509f124e0fea88bfe4571cfbf6b86f). Please give it a shot and let me know how it goes.

Note that it doesn't cover every possible scenario but should address the common ones and the ones hopefully mentioned in here. Thanks again for reporting it!

**Comment by 0bi-w6n-K3nobi** [comment]
Great! I believe that double condition will be good enough.

I thinking about this, and already worked with same scenario.
If I have some new idea will share here.
