### ISSUE TITLE
GoAccess 1.4 crashed by Sig 11

### ISSUE THREAD

**Issue by droM4X** [allinurl/goaccess#1818]
Hey there,

I got this error on Debian 10 (from goaccess repo) when I set _with-mouse to true_ in config file and tried to click/expand referring sites, or status codes (everything after 8 - Time Distribution section). Log file is a default nginx access log.
If with-mouse is false its working fine.

```
==28275== GoAccess 1.4 crashed by Sig 11
==28275==
==28275== VALUES AT CRASH POINT
==28275==
==28275== Line number: 899
==28275== Offset: 899
==28275== Invalid data: 0
==28275== Piping: 0
==28275==
==28275== STACK TRACE:
==28275==
==28275== 0 goaccess(sigsegv_handler+0x138) [0x558a2c44bbf8]
==28275== 1 /lib/x86_64-linux-gnu/libpthread.so.0(+0x12730) [0x7ff335f22730]
==28275== 2 goaccess(+0x11c80) [0x558a2c446c80]
==28275== 3 goaccess(+0x27ce8) [0x558a2c45cce8]
==28275== 4 goaccess(main+0xb78) [0x558a2c447818]
==28275== 5 /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xeb) [0x7ff335d7309b]
==28275== 6 goaccess(_start+0x2a) [0x558a2c4488ca]
==28275==
==28275== Please report it by opening an issue on GitHub:
==28275== https://github.com/allinurl/goaccess/issues
```

Any advice, maybe log problem.
Thanks in advance.

**Comment by allinurl** [comment]
Thanks for reporting this!

Would you be able to run it through gdb?

```
$ curl tar.goaccess.io/goaccess-1.4.tar.gz | tar xvz
$ cd goaccess-1.4/
$ ./configure --enable-debug --enable-utf8
$ make
$ gdb --args ./goaccess access.log --with-mouse
(gdb) r <enter>
... attempt to crash
(gdb) bt full <enter>
```

**Comment by droM4X** [comment]
Sure.

If build goaccess from source and run again, I got this error:

```
==1316== GoAccess 1.4 crashed by Sig 11
==1316==
==1316== VALUES AT CRASH POINT
==1316==
==1316== Line number: 970
==1316== Offset: 970
==1316== Invalid data: 0
==1316== Piping: 0
==1316==
==1316== STACK TRACE:
==1316==
==1316== 0 ./goaccess(sigsegv_handler+0xa0) [0x556902fd5e28]
==1316== 1 /lib/x86_64-linux-gnu/libpthread.so.0(+0x12730) [0x7fe920e76730]
==1316== 2 ./goaccess(parse_raw_data+0x61) [0x556902fe95f7]
==1316== 3 ./goaccess(+0x2a81d) [0x556902fea81d]
==1316== 4 ./goaccess(+0x2b2f0) [0x556902feb2f0]
==1316== 5 ./goaccess(+0x2b340) [0x556902feb340]
==1316== 6 ./goaccess(+0x2c677) [0x556902fec677]
==1316== 7 ./goaccess(+0x2c9b1) [0x556902fec9b1]
==1316== 8 ./goaccess(main+0x12d) [0x556902fed66a]
==1316== 9 /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xeb) [0x7fe920cc709b]
==1316== 10 ./goaccess(_start+0x2a) [0x556902fd1b6a]
==1316==
==1316== Please report it by opening an issue on GitHub:
==1316== https://github.com/allinurl/goaccess/issues
```

I tried to use with gdb but I got an error at the bottom of the screen: [Thread 0x7ffff7a84700 (LWP 1599) exited] and I couldnt go down with the arrow keys / click anywhere. I saw ^[[M... and similar in bottom of the screen when I type/scrolling. I cant copy it, because after I quit from gdb, my terminal is still stucked so I need to reset and its clear the screen.

![screenshot](https://user-images.githubusercontent.com/10895544/85148533-8ebb7880-b250-11ea-8458-27bf6d1f9e01.png)

Hope it helps.
Thanks.

**Comment by allinurl** [comment]
Per #1823, this should be fixed. Could you please try building from [**development**](https://github.com/allinurl/goaccess#build-from-github-development) and let me know if that solves the issue on your end.
