### ISSUE TITLE
Token '06' doesn't match specifier '%m' 

### ISSUE THREAD

**Issue by pranalipagariya-1990** [allinurl/goaccess#1829]
Hi,
Very new to this tool, please pardon my obivious mistake if any :)
Below is my Log format from weblogic server

2020-06-25      1x.1xx.1xx.6

x   15:03:02        0.0     getWebUserStatus        200     317
I have set logformat, dateformat and time format in conf file and then running a command to get data

                                                     |Log Format - [c] to add/edit format                       |
                                                     | %y-%m-%d\t%h\t%H:%M:%S\t%T\t%U\t%s\t%b                    |

                                                     | Date Format - [d] to add/edit format                      |
                                                     | %Y-%m-%d                                                  |

                                                     | Time Format - [t] to add/edit format                      |
                                                     | %H:%M:%S          

Can you please help me to  understand what is wrong with my config.

![image](https://user-images.githubusercontent.com/62091920/85817904-a051d280-b7b2-11ea-947a-13ad7e491ee0.png)
![image](https://user-images.githubusercontent.com/62091920/85817917-a9db3a80-b7b2-11ea-9058-e674ae1ada15.png)
![image](https://user-images.githubusercontent.com/62091920/85818066-0a6a7780-b7b3-11ea-86e9-c84d96525ee9.png)

**Comment by pranalipagariya-1990** [comment]
I chnaged 06 to Jun using, so it passed that filedn now getting below
goaccess idm1_bcc_cid.log -c --date-format=%Y-%b-%d --time-format=%H:%M:%S --log-format='%Y-%b-%d %h %H:%M:%S %T %U %s %b'

2020-Jun-26 1x.1xx.1xx.6x 10:30:39 0.016 getUserProfile 200 774$$
2020-Jun-26 1x.1xx.1xx.6x 10:30:39 0.031 verifyPin 200 311$$
2020-Jun-26 1x.1xx.1xx.6x 10:30:39 0.141 getMigrationStatus 200 1637$$

![image](https://user-images.githubusercontent.com/62091920/85819701-dcd3fd00-b7b7-11ea-8fcf-5a32f6b5b372.png)

![image](https://user-images.githubusercontent.com/62091920/85819695-d3e32b80-b7b7-11ea-959e-1ed6c7b6b641.png)

**Comment by allinurl** [comment]
Can you please attach a few lines from your access log (the exact way they are)? Thanks

**Comment by pranalipagariya-1990** [comment]
I made it work using below
 goaccess idm1_bcc_cid.log -c --date-format='%d-%b-%Y' --time-format='%H:%M:%S' --log-format='%d %h %t %T %U %s %b' -o report.html

Thanks
