### ISSUE TITLE
Get month json/html report from year database

### ISSUE THREAD

**Issue by jabiertxof** [allinurl/goaccess#1831]
I want to get HTML/JSON moth report from a persistent year database without storing month database, is posible?
Thanks in advance.

**Comment by allinurl** [comment]
Are you looking to have a panel like [**this**](https://rt.goaccess.io/?20200708153904#visit_time) but for each month?

**Comment by allinurl** [comment]
BTW, would this be a dup of this #1167?

**Comment by jabiertxof** [comment]
Yes is it, currently Im doing 2 databases one year and one montly but by mistake I remove the montly one and want to resore the month html with yhe year database. Porbably yes is a duple. Thanks for reply!

**Comment by allinurl** [comment]
Thanks for the remainder.  I will be working on this.

**Comment by jabiertxof** [comment]
you are welcome!
