### ISSUE TITLE
how do i process aws elb json formatted logs

### ISSUE THREAD

**Issue by rdukic** [allinurl/goaccess#1832]
Hello,

I have logs from aws in json format and would like to process with goaccess. any assistance would be great

they look like this:

    {"timestamp":1591837307445 | formatVersion:1 | webaclId:"444627c1-c429-4a6f-b7e5-82cf73d05a9c" | terminatingRuleId:"Default_Action" | terminatingRuleType:"REGULAR" | action:"ALLOW" | terminatingRuleMatchDetails:[] | httpSourceName:"ALB" | httpSourceId:"248494895611-app/elb-application-handbook/e23009b618875bd1" | ruleGroupList:[] | rateBasedRuleList:[{"rateBasedRuleId":"588ecc19-8dec-47d2-80ad-fdc6bb648a76" | limitKey:"IP" | maxRateAllowed:250 | limitValue:null}] | nonTerminatingMatchingRules:[] | httpRequest:{"clientIp":"121.211.234.183" | country:"AU" | headers:[{"name":"Host" | value:"www.handbook.unsw.edu.au"} | {"name":"Content-Length" | value:"0"} | {"name":"user-agent" | value:"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML | like Gecko) Chrome/83.0.4103.97 Safari/537.36"} | {"name":"accept" | value:"text/css | */*;q=0.1"} | {"name":"sec-fetch-site" | value:"same-origin"} | {"name":"sec-fetch-mode" | value:"no-cors"} | {"name":"sec-fetch-dest" | value:"style"} | {"name":"referer" | value:"https://www.blah.blah.bla.com/search?study_level=ugrd&year=2020&appliedFilters=eyJwYXJhbXMiOnsiY3QiOiJzdWJqZWN0IiwicngiOiIuKiIsImZhY3VsdHkiOiI1N2E1NmNlYjRmMDA5MzAwNGFhNmViNGYwMzEwYzdhZSJ9LCAiZGVzY3JpcHRpb24iOiAiYW55IGNvdXJzZSBvZmZlcmVkIGJ5IEZhY3VsdHkgb2YgU2NpZW5jZSJ9"} | {"name":"accept-encoding" | value:"gzip | deflate | br"} | {"name":"accept-language" | value:"en-GB | en-US;q=0.9 | en;q=0.8"} | {"name":"cookie" | value:"opvc=875b85cb-3a88-408f-98c7-63f9f832c04f; sitevisitscookie=1; dmid=84a88f85-fb32-4eb7-a6c6-4c0c548c147b; _gcl_au=1.1.1217065428.1587943498; _ga=GA1.3.765197479.1587943498; _ga=GA1.4.765197479.1587943498; structure_refactor=false; _fbp=fb.2.1588662108760.2001049527; check=true; fonce_current_user=0; fonce_current_user_MOM=0; AMCVS_8A5564D65437E5950A4C98A2%40AdobeOrg=1; s_ecid=MCMID%7C64778291457499819111266018821198764387; s_mcid=64778291457499819111266018821198764387; fonce_current_day=0 | 2020-06-02; _hjid=4d7c6b7c-7fcb-48d7-a87c-e7f2ab9b76ee; _gid=GA1.3.678530658.1591834427; _gid=GA1.4.678530658.1591834427; AMCV_8A5564D65437E5950A4C98A2%40AdobeOrg=-1712354808%7CMCIDTS%7C18425%7CMCMID%7C64778291457499819111266018821198764387%7CMCAAMLH-1592440007%7C8%7CMCAAMB-1592440007%7CRKhpRz8krg2tLO6pguXWp5olkAcUniQYPHaMWWgdJ3xzPWQmdj0y%7CMCOPTOUT-1591842407s%7CNONE%7CMCAID%7CNONE%7CvVersion%7C4.3.0; aam_uuid=59006119085071592641844010075972770132; utag_main=v_id:017258f5974f004c7aedbada9ba003079003c07100fb8$_sn:2$_se:2$_ss:0$_st:1591837013368$vapi_domain:domain.com$ses_id:1591835206923%3Bexp-session$_pn:2%3Bexp-session; mbox=PC#20f504ab1104409c8d06475800f5c0f3.36_0#1655080008\|session#34eac1a6f81240029d9aeffe41f6cc7f#1591837095; _gat_UA-69401229-1=1; AWSALBTG=RX76gpompVITB1MuKRGuGjO9aF0YTQJVHs4ZzBZVPRtoAtazZu+4km1jbAVTcWaJQNCo47j1XZqGFskVh1NbINdm7Qf4wuaVqAPxqNnWU9hXzqaqYj3c/HrEonlXze8ZSldzlpZCBxWwX3nmwHq0rMgpbBrW/SvPjxtHk3rIz/i8; AWSALBTGCORS=RX76gpompVITB1MuKRGuGjO9aF0YTQJVHs4ZzBZVPRtoAtazZu+4km1jbAVTcWaJQNCo47j1XZqGFskVh1NbINdm7Qf4wuaVqAPxqNnWU9hXzqaqYj3c/HrEonlXze8ZSldzlpZCBxWwX3nmwHq0rMgpbBrW/SvPjxtHk3rIz/i8; AWSALB=5ZIm3Fdsv1IMw+hbl0v5pRT7NuuyGkFH7JbmT2gIrNutLPnujIxLuNnABzN9o7RxjnMm9a3GOPEagx55S7lVSejGchcXRy/NIeYoXsfmdx/OsMITR73CrIjTti6S; AWSALBCORS=5ZIm3Fdsv1IMw+hbl0v5pRT7NuuyGkFH7JbmT2gIrNutLPnujIxLuNnABzN9o7RxjnMm9a3GOPEagx55S7lVSejGchcXRy/NIeYoXsfmdx/OsMITR73CrIjTti6S; JSESSIONID=2FF6B563D03B4A29616490C897158515"}] | uri:"/application/themes/search/css/skeleton.css" | args:"" | httpVersion:"HTTP/2.0" | httpMethod:"GET" | requestId:null

**Comment by allinurl** [comment]
Can you please **attach** a few sample lines directly from your access log?  The one you posted malformed or incomplete. Also please describe the fields.

Thanks.

**Comment by rdukic** [comment]
[sample log.txt](https://github.com/allinurl/goaccess/files/4893566/sample.log.txt)

Here's a sample. 

i think this is the field mapping from AWS.

https://docs.aws.amazon.com/athena/latest/ug/application-load-balancer-logs.html

**Comment by 0bi-w6n-K3nobi** [comment]
Wouldn't it be easier for you to transform it into a flat log?
Including removing unnecessary fields ...

**Comment by allinurl** [comment]
JSON support was added in v1.4.4. Even though you don't have a valid json string in there (due to the pipes delimiting the fields) I think it *could* be fairly easy to parse by pre-processing the log and replacing the pipes with comas and then using the JSON parser. One issue I see is that there are a lot of repeat keys/values, so not 100% it will work. Take a look at [**this post**](https://github.com/allinurl/goaccess/issues/1768#issuecomment-755792463) and [**this**](https://github.com/allinurl/goaccess/issues/2022#issuecomment-774688174) for a sample log-format. 

Otherwise, using the regular parser may do it (as long as all the fields are consistent across multiple lines) but it looks like it will take sometime to map all the fields.

Closing this, feel free to reopen it if needed.
