### ISSUE TITLE
Error occured at src/parser.c - read_log. But only when run from cron. And yes, I'm using absolute paths.

### ISSUE THREAD

**Issue by SoptikHa2** [allinurl/goaccess#1836]
Hi,
I know this looks like the 50 identical issues I've googled so far, but I have no idea why this doesn't work. The point is, it works when invoked in shell, but doesn't when run from cron. The cron is root-owned, so there should be no permission issues. I use absolute paths, so ENV variables shouldn't be an issue either.

This is the problematic line:
```
zcat /var/log/nginx/access.log.*.gz | goaccess /var/log/nginx/access.log{,.1} - -q --log-format=COMBINED -o /var/www/html/foo/bar/report.html >/dev/null
```

It works in shell, but not in cron.

```
Parsing... [0] [0/s]
GoAccess - version 1.2 - Jun 19 2017 12:55:29
Config file: /etc/goaccess.conf

Fatal error has occurred
Error occured at: src/parser.c - read_log - 2669
Unable to open the specified log file. No such file or directory
```

This looks like I misspecified the log paths, but when I paste the command into shell, everything works. I thought it was going to be `$PATH` issue, but I specify absolute paths everywhere. And both `zcat` and `goaccess` are in cron `$PATH` already.

Any ideas?

**Comment by allinurl** [comment]
Can you please try without expanding multiple logs?

    zcat /var/log/nginx/access.log.*.gz | goaccess /var/log/nginx/access.log - -q --log-format=COMBINED -o /var/www/html/foo/bar/report.html

and  

     goaccess /var/log/nginx/access.log - -q --log-format=COMBINED -o /var/www/html/foo/bar/report.html

**Comment by SoptikHa2** [comment]
Thanks a lot, the issue disappears when I remove the shell expand. I guess it's some shell opt-in feature.

Sorry for inconvenience!

**Comment by allinurl** [comment]
Glad that solved the issue. Yeah my best guess is that the cron doesn't expand it due to a tty. You can probably run a scripts instead of running goaccess directly.

Closing this. Feel free to reopen it if needed.
