### ISSUE TITLE
Repo signature for debian stretch

### ISSUE THREAD

**Issue by bugeaud** [allinurl/goaccess#1837]
Hello,

Trying to upgrade under debian stretch I now get the following :

Err:5 http://deb.goaccess.io stretch InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 97BD1A0133449C3D
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://deb.goaccess.io stretch InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 97BD1A0133449C3D
W: Failed to fetch http://deb.goaccess.io/dists/stretch/InRelease  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 97BD1A0133449C3D

Some repo issue ?

Rgs,
JB

**Comment by allinurl** [comment]
Please take a look at [**this note post**](https://goaccess.io/download#official-repo). Let me know if that solves the issue on your end.

**Comment by Stephan972** [comment]
> Please take a look at [**this note post**](https://goaccess.io/download#official-repo). Let me know if that solves the issue on your end.

I did have a similar issue. Applying the instructions in the note post solved the issue.
Thanks.

**Comment by allinurl** [comment]
Closing this.
