### ISSUE TITLE
Make log-format case insensitive?

### ISSUE THREAD

**Issue by elboulangero** [allinurl/goaccess#1838]
Just a quick comment, as I was running `goaccess --log-format combined`, which failed, until I realized that the option is actually case-sensitive, and I had to run `goaccess --log-format COMBINED`.

Wondering if it would make sense for you to make it case-insensitive instead, so that it doesn't bite me and others :)

I can submit a patch (though it seems trivial, just replace a few `strcmp` with `strcasecmp` in `settings.c` apparently)

Thanks!

**Comment by allinurl** [comment]
Yeah, please feel free to submit a PR. Happy to merge it!

**Comment by elboulangero** [comment]
Created PR 1844, tested, works for me
