### ISSUE TITLE
Display the x slowest running requests

### ISSUE THREAD

**Issue by gurrie** [allinurl/goaccess#184]
Firstly thanks for a great tool, I was wondering whether you have any plans to add an extra module to show the slowest running requests? The current 'Requested Files' module presents the mean time for the total number of requests for that url, which can hide the fact that for certain periods that request is actually very slow.

Regards
Brian

**Comment by gurrie** [comment]
Hi, just wondering if you have managed to make any progress on this issue?

**Comment by allinurl** [comment]
I did refactor the way panels and metrics are parsed, which gives more flexibility when it comes to adding new modules. I'm close to release 0.9.1. So I can have this feature added on 0.9.2. Thanks for the reminder though.

**Comment by gurrie** [comment]
Thank you for the awesome product! That would be much appreciated.

**Comment by gurrie** [comment]
Hi, just wondering if you managed to get this in for 0.9.2?

**Comment by allinurl** [comment]
@gurrie sorry, I completely overlooked my last post. I'll work on this and post back as soon as I have it implemented.

**Comment by allinurl** [comment]
The new metric, slowest running requests or max time served has been added. 

It will be pushed out in the upcoming version, otherwise, feel free to build from [master](http://goaccess.io/download#build).

**Comment by gurrie** [comment]
Thank you! I really appreciate the effort.
