### ISSUE TITLE
Help with Log Format

### ISSUE THREAD

**Issue by hougholi** [allinurl/goaccess#1842]
Struggling to create a `--log-format` flag for GoAccess, my Apache conf is using the following format:
```
LogFormat "{ \"time\":\"%{%Y-%m-%d}tT%{%T}t.%{msec_frac}tZ\", \"process\":\"%D\", \"filename\":\"%f\", \"remoteIP\":\"%{X-Forwarded-For}i\", \"host\":\"%V\", \"request\":\"%U\", \"query\":\"%q\",\"method\":\"%m\", \"status\":%>s, \"userAgent\":\"%{User-agent}i\",\"referer\":\"%{Referer}i\"}" combined
```
Any help would be appreciated!

**Comment by allinurl** [comment]
Please post a few lines from your access log. Thanks!

**Comment by hougholi** [comment]
Here you go

`{ "time":"2020-07-15T10:04:57.957Z", "process":"10903", "filename":"/filename.html", "remoteIP":"1.2.3.4", "host":"example.com", "request":"/index/html", "query":"","method":"GET", "status":302, "userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36","referer":"https://example2.com"}`

`{ "time":"2020-07-15T10:05:02.944Z", "process":"1108701", "filename":"/filename.html", "remoteIP":"5.6.7.8", "host":"example.com", "request":"/index.html", "query":"?a=1594807502838","method":"GET", "status":200, "userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36","referer":"https://example2.com"}`

`{ "time":"2020-07-15T10:06:17.944Z", "process":"9212", "filename":"/filename.html", "remoteIP":"9.10.11.12", "host":"example.com", "request":"/index.php", "query":"","method":"GET", "status":302, "userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36","referer":"https://example2.com"}`

**Comment by sivasankarsani737** [comment]
for me also getting the log-format.

log-format 

34.200.214.52 - - [16/Jul/2020:07:27:20 +0200] "GET <requested-api> HTTP/1.1" 200 1076 "-" "rest-client/2.1.0 (linux-gnu x86_64) ruby/2.5.7p206" 0.025 0.024 "example.com" -

please help me @allinurl

**Comment by hougholi** [comment]
@allinurl Just so you know I got this working with:

`'%^: "%dT%t.%^", %^: "%D", %^: "%f", %^: "%h", %^: "%V", %^: "%U", %^: %^, %^: %^, %^: "%>s", %^: "%{User-agent}i", %^: "%{Referer}i"' --date-format=%Y-%m-%d --time-format=%T`

Thanks

**Comment by allinurl** [comment]
@hougholi sorry for the delay on this, this should do it:

    goaccess access.log --log-format='%^:"%dT%t.%^",%^,%^,%^:"%h",%^:"%v",%^:"%U",%^:"%q",%^:"%m",%^:%s,%^:"%u",%^:"%R"' --date-format=%Y-%m-%d --time-format=%T --http-protocol=no
