### ISSUE TITLE
Yet another log format issue

### ISSUE THREAD

**Issue by Titaniumtown** [allinurl/goaccess#1843]
So i run apache web server, with the logformat: "%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-agent}i\"" combined

xxx.xxx.xxx.xxx - - [14/Jul/2020:21:31:05 -0400] "GET /log.html HTTP/1.1" 304 - "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36"

one example: ``` goaccess /mnt/tb_hdd/logs/access_log_apache.txt --date-format='%d/%b/%Y' --time-format=%H:%M:%S  -o /mnt/hdd/http_share/log.html ```
outputs: 
```
Parsed 1 lines producing the following errors:

Token 'xx.xxx.xxx.xxx' doesn't match specifier '%h'
```
note the ip address blocked out above seems to have the first character cut off.

what log-format do i use? I tried log-format "%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-agent}i\"" and a bunch of other stuff. it just doesnt seem to work! Please help! I would love to use this tool!

**Comment by allinurl** [comment]
Can you please try:

    goaccess /mnt/tb_hdd/logs/access_log_apache.txt --log-format=COMBINED -o /mnt/hdd/http_share/log.html

Let me know if that solves the issue.

![2020-07-14-211138_670x1057_scrot](https://user-images.githubusercontent.com/5005367/87495157-4ce6dd80-c616-11ea-9f62-e1d2cf8dd61c.png)

**Comment by Titaniumtown** [comment]
```
Parsed 1 lines producing the following errors:

Token for '%b' specifier is NULL.
```

**Comment by allinurl** [comment]
Are you using v1.4? Can you please add `--no-global-config`?

**Comment by Titaniumtown** [comment]
I am using 1.4 (i'm on arch linux) the build date is May 18th, I will test that.

**Comment by Titaniumtown** [comment]
Issue persists

**Comment by allinurl** [comment]
Can you please attach a few lines straight from your access log? Given the line you posted above, in v1.4, I got the output as shown on the screenshot above.

**Comment by Titaniumtown** [comment]
xxx.xxx.xxx.xxx - - [14/Jul/2020:22:07:51 -0400] "GET /my_repo/aarch64/linux-raspberrypi4-5.4.y-5.4.51.r880956.g7d9a391c64cb-1-aarch64.pkg.tar.xz HTTP/1.1" 200 19667640 "-" "pacman/5.2.2 (Linux aarch64) libalpm/12.0.2"

xxx.xxx.xxx.xxx - - [14/Jul/2020:22:07:53 -0400] "GET /my_repo/aarch64/linux-raspberrypi4-5.4.y-headers-5.4.51.r880956.g7d9a391c64cb-1-aarch64.pkg.tar.xz HTTP/1.1" 200 8742660 "-" "pacman/5.2.2 (Linux aarch64) libalpm/12.0.2"

**Comment by allinurl** [comment]
Can you please run 

    # tail -20 /mnt/tb_hdd/logs/access_log_apache.txt > sample.log

and post the sample.log as an attachment to this post? I just want to make sure I'm testing the right log (ideally without mods). If needed, feel free to replace those IPs with 127.0.0.1. Also, feel free to test your goaccess instance against that log and see how it goes.

**Comment by Titaniumtown** [comment]
[sample.log](https://github.com/allinurl/goaccess/files/4922589/sample.log)

**Comment by Titaniumtown** [comment]
oh. it seems it works?

**Comment by Titaniumtown** [comment]
but my actual log files fails. let me do some digging

**Comment by Titaniumtown** [comment]
found the issue: I have these strange entries in my log file:
```
::1 - - [08/Jul/2020:04:57:41 -0400] "OPTIONS * HTTP/1.0" 200 -
```

**Comment by Titaniumtown** [comment]
also: 
```
::1 - - [09/Jul/2020:12:19:17 -0400] "OPTIONS * HTTP/1.0" 200 - "-" "Apache/2.4.43 (Unix) PHP/7.4.8 (internal dummy connection)"
```

**Comment by Titaniumtown** [comment]
Do you have any idea what those entries could be?

**Comment by allinurl** [comment]
It's Apache's way to wake up processes.

Seems like you got some mixed formats in there, e.g., COMBINED vs COMMON. You can try passing `--num-test=0`

**Comment by Titaniumtown** [comment]
It works find w/o those ::1 lines

**Comment by Titaniumtown** [comment]
wait, i was wrong. it doesnt work

**Comment by Titaniumtown** [comment]
your argument works. What does it do?

**Comment by Titaniumtown** [comment]
It works perfectly now!

**Comment by allinurl** [comment]
Glad that worked :) Since you got some mixed log formats, then goaccess tries to parse the first few lines as COMBINED, however, it fails on the COMMON line. `--num-test=0` just lets goaccess know to skip validation and attempt to parse all lines.

Closing this, feel free to reopen it if needed.

**Comment by Titaniumtown** [comment]
Thanks so much! Your project is so useful! I had a basic little python script doing some of the work!

**Comment by allinurl** [comment]
Thanks for the feedback. Happy to hear you found it useful. Stay tuned for the upcoming releases :)
