### ISSUE TITLE
Transitioned to apache webserver from darkhttpd, can I still include my darkhttpd log files?

### ISSUE THREAD

**Issue by Titaniumtown** [allinurl/goaccess#1845]
So, as the title says, I now use apache webserver instead of darkhttpd. But I still want goaccess to parse through that info, is that possible?

**Comment by allinurl** [comment]
You probably can as long as they both have the same log/date/time format. Otherwise you will need to run two separate [**instances**](https://github.com/allinurl/goaccess/issues/625#issuecomment-272905761).

#213 will address the issue where different log formats are parsed at once.

**Comment by Titaniumtown** [comment]
Thanks again for the timely response!

**Comment by Titaniumtown** [comment]
for dark httpd it does:
```
1594183805 xxx.xxx.xxx.xxx "GET /" 200 3775 "" "Mozilla/5.0 (X11; Linux x86_64; rv:79.0) Gecko/20100101 Firefox/79.0"
```
where the first number is unix time

**Comment by allinurl** [comment]
This should do it:

    goaccess sample.log --log-format='%x %h "%m %U" %s %b "%R" "%u"' --date-format=%s --time-format=%s --http-protocol=no

**Comment by Titaniumtown** [comment]
how would i then use that info and the apache logs too?

**Comment by allinurl** [comment]
So far you won't be able to parse both at the same time. Are you able to change the log/date/time format in darkhttpd to the COMBINED format?

**Comment by Titaniumtown** [comment]
It's a pre-existing log. I no longer use darkhttpd. I don't know how i would change the format in a previous log.

**Comment by allinurl** [comment]
I'd parse them separately. Otherwise, you could go the pre-processing route and use a tool such as awk, sed to change the format and pipe that data to goaccess. e.g.,

    awk ... darkhttpd.access.log | goaccess - apache.access.log --log-format=COMBINED

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
