### ISSUE TITLE
Log Format Help - Syslog

### ISSUE THREAD

**Issue by nabeelaejaz** [allinurl/goaccess#1848]
I had tried all the methods mentioned here in the issues, but none helped. Kindly help me parse auth.log file. Below are few data:

Jul 15 18:53:21 ip-172-26-15-120 sshd[2761]: Connection closed by 195.158.80.60 port 37508 [preauth]
Jul 15 18:53:23 ip-172-26-15-120 sshd[2763]: Connection closed by 195.158.80.60 port 39200 [preauth]
Jul 15 18:53:24 ip-172-26-15-120 sshd[2765]: Connection closed by 195.158.80.60 port 40936 [preauth]
Jul 15 18:53:26 ip-172-26-15-120 sshd[2767]: Connection closed by 195.158.80.60 port 42776 [preauth]
Jul 15 18:53:28 ip-172-26-15-120 sshd[2769]: Connection closed by 195.158.80.60 port 44510 [preauth]
Jul 15 18:53:30 ip-172-26-15-120 sshd[2771]: Connection closed by 195.158.80.60 port 46188 [preauth]
Jul 15 18:53:32 ip-172-26-15-120 sshd[2773]: Connection closed by 195.158.80.60 port 47890 [preauth]
Jul 15 18:53:33 ip-172-26-15-120 sshd[2775]: Connection closed by 195.158.80.60 port 49658 [preauth]
Jul 15 18:53:35 ip-172-26-15-120 sshd[2777]: Connection closed by 195.158.80.60 port 51380 [preauth]

**Comment by allinurl** [comment]
goaccess analyses web access logs, you probably need to use a different tool.
