### ISSUE TITLE
src/tpl.c:61:10: fatal error: win/mman.h: No such file or directory | Cygwin64

### ISSUE THREAD

**Issue by mongoose00318** [allinurl/goaccess#1851]
When trying to install goaccess.io I get this error and the compile fails.

src/tpl.c:61:10: fatal error: win/mman.h: No such file or directory

I'm new to using Cygwin and not sure what I am doing wrong. But, I installed all of the packages that it said were required (ncurses, wget, etc)

I also tried using cowaxess but I couldn't get that to work either?

**Comment by allinurl** [comment]
Thanks for reporting this. The fix will be pushed out in the upcoming release.

**Comment by allinurl** [comment]
Commit e4b419c fixes this. Thanks again for reporting it. It will be release in the upcoming version soon. Stay tuned,
