### ISSUE TITLE
Setup goaccess as a systemd service

### ISSUE THREAD

**Issue by Titaniumtown** [allinurl/goaccess#1852]
Is there a way to generate a log.html file every hour or so? So I don't have to run the command manually?

**Comment by allinurl** [comment]
Could you run it through the cron? 

    cron -e

then add:

    0 * * * *

**Comment by Titaniumtown** [comment]
Wait, before i do that, how to i make it so the command: ``` goaccess /mnt/tb_hdd/logs/access_log_apache.txt --log-format=COMBINED --num-test=0 --real-time-html -o /mnt/hdd/http_share/log.html ``` only saves the html file, and not resulting in: ``` WebSocket server ready to accept new client connections ```

**Comment by Titaniumtown** [comment]
Sorry, I was just an idiot. about the above comment ^^^^^^^^^^^^^ I had real-time-html set in the args. lmao

**Comment by allinurl** [comment]
So is this resolved?
