### ISSUE TITLE
error processing custom format.

### ISSUE THREAD

**Issue by nikhil-kartha** [allinurl/goaccess#1854]
Can't figure out the error thrown when using the custom format.
```
$ echo "[GIN] 2020/07/25 - 03:01:04 | 200 |      67.081µs |   10.114.21.249 | GET      /" | goaccess --log-format='%^ %d %^ %t |  %s | %D.%^ | %~%h | %~%m %U' --date-format=%Y/%m/%d --time-format=%T
Parsed 1 lines producing the following errors:

Missing braces '{}' and ignore chars for specifier '%h'

Format Errors - Verify your log/date/time format
```

Version:
```
$ goaccess -V
GoAccess - 1.2.
For more details visit: http://goaccess.io
Copyright (C) 2009-2016 by Gerardo Orellana
```

**Comment by allinurl** [comment]
Please attach a file with a few lines from your access log. Thanks

**Comment by nikhil-kartha** [comment]
[sample.txt](https://github.com/allinurl/goaccess/files/4992151/sample.txt)

Attached a file with few lines from the log.
- Thanks,
Nikhil.

**Comment by allinurl** [comment]
Interesting format, but this should do it in v1.4:

    goaccess sample.txt --log-format='[%v] %d - %t %^ %s |%~%D.%^ |%~%h %^ %m %~%U' --date-format=%Y/%m/%d --time-format=%T

**Comment by nikhil-kartha** [comment]
I switched to using goaccess 1.4, but cant get it to work with the sample text.

When i run the command mentioned above, i get a "Log Format Configuration" screen.
Tried selecting every log format, but get an error:
"Token '[GIN]' doesn't match specifier '<<specifier>>'
where, the <specifier> changes with the selected log format.

**Comment by allinurl** [comment]
@nikhil-kartha could you please post a few lines from your access log and the command you are running? Thanks

**Comment by nikhil-kartha** [comment]
Sorry, it's working fine today. Not sure what the issue was yesterday.
I used the command you provided:
```
goaccess sample.txt --log-format='[%v] %d - %t %^ %s |%~%D.%^ |%~%h %^ %m %~%U' --date-format=%Y/%m/%d --time-format=%T
```


![image](https://user-images.githubusercontent.com/10873406/89972516-e653e000-dc12-11ea-9e19-23124481ce74.png)

**Comment by nikhil-kartha** [comment]
I tried it with a bigger sample data, few mb's, it works great!
