### ISSUE TITLE
Sed Errors with Relative Date

### ISSUE THREAD

**Issue by lwarrent** [allinurl/goaccess#1857]
I am trying to create an html report with a relative date on Mac OS. I am able to generate the report fine with a selected start date, but not with the relative date command. Here's the command I am using and the errors it gives me:

```
sed -n '/'$(date '+%d/%b/%Y' -d 'yesterday')'/,$ p' /private/var/log/apache2/access_log | goaccess -o /Users/username/Documents/report.html
date: illegal time format
usage: date [-jnRu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ... 
            [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]
sed: first RE may not be empty
```
Appreciate any help you can offer.

**Comment by allinurl** [comment]
Seems like you are not escaping the date slashes. Please try something like e.g.,

    sed -n '/'$(date '+%d\/%b\/%Y' -d '1 week ago')'/,$ p' access.log

**Comment by lwarrent** [comment]
I actually pasted the wrong line in the original post. I have also tried what you suggest with the same results.

```
sed -n '/'$(date '+%d\/%b\/%Y' -d '1 week ago')'/,$ p' /private/var/log/apache2/access_log | goaccess -o /Users/username/Documents/report.html --real-time-html
date: illegal time format
usage: date [-jnRu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ... 
            [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]
sed: first RE may not be empty
```

**Comment by allinurl** [comment]
Are you able to use those date specifier in in Mac OS?  e.g.,

    date '+%d\/%b\/%Y' -d '1 week ago'

I don't have a Mac on hand to test this out, but you could try running `man date` or `man strptime`. Let me know.

**Comment by lwarrent** [comment]
`date '+%d\/%b\/%Y' -d '1 week ago'` gives the same illegal time format error.

`man date` gives this page: https://www.unix.com/man-page/osx/1/date/ (mostly the same, but this one is older. Can copy past the one from my terminal if you like but thought better not to add the clutter.)

**Comment by lwarrent** [comment]
Rearranging the date to `date -d "1 week ago 00:00" '+%Y-%m-%d'` gets rid of the `date: illegal time format` error. But still getting the others:

```
usage: date [-jnRu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ... 
            [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]
sed: first RE may not be empty
```

**Comment by allinurl** [comment]
You may want to look at how the date command works on Mac OS. I can't help you much with that. However, [**this**](https://stackoverflow.com/questions/498358/how-do-i-do-date-math-in-a-bash-script-on-os-x-leopard) may help,

Closing this as it appears not to be an issue directly with goaccess. Feel free to reopen it if needed.
