### ISSUE TITLE
Error Official GoAccess' Debian/Ubuntu Repository

### ISSUE THREAD

**Issue by desarrollocdb** [allinurl/goaccess#1858]
![image](https://user-images.githubusercontent.com/26174637/88570014-f360b480-d000-11ea-8fc1-f2fc42fb9c6b.png)

![image](https://user-images.githubusercontent.com/26174637/88570046-01163a00-d001-11ea-8ff6-3a093df6b412.png)

http://deb.goaccess.io/

**Comment by allinurl** [comment]
I don't see any issues from my end. Is it apt-get timing out on you? 

The 403 is because I don't list the content of the directory.

**Comment by desarrollocdb** [comment]
I can't update via apt-update, I always have the same error

![image](https://user-images.githubusercontent.com/26174637/88608369-35144e00-d047-11ea-99a0-ef3bdfa18bb5.png)

**Comment by allinurl** [comment]
Interesting, are you able to ping to that IP? also, feel free to send me an email (hello [at] goaccess.io) with the IP of the machine trying to fetch the deb repo and I can see if it's banned for some reason. Thanks

**Comment by desarrollocdb** [comment]
Hello, everything is normal now. Thank you

**Comment by allinurl** [comment]
Glad to hear that. BTW, did something change on your end?
