### ISSUE TITLE
Local setup + SSH pipe + NFS

### ISSUE THREAD

**Issue by acondura** [allinurl/goaccess#1859]
Hi,

I'm basically using this:

ssh USER@HOST "tail -f LOG_LOCATION/access.log" | goaccess --log-format=COMBINED -o /data/goaccess/goaccess.html --real-time-html -

That /data/goaccess/goaccess.html is exported using NFS to another server in the same network. The destination goaccess.html file gets written ok but subsequent updates don't get written and the html report does not get updated with new data.

If I use the same command but displaying the data in CLI, I see the data updating every second.

Am I missing something? Do you know of any issues with NFS?

**Comment by acondura** [comment]
The server that runs the goaccess command and thus, creates the html report, does not have a public IP, only a local one.
The server that has a public IP now has an NFS share with dest folder to /data/goaccess/goaccess.html on the private goaccess server above.
So, the goaccess server writes the html report to the NFS share and I'm access the goaccess.html on the public server through a web url. 
This should work, right?

**Comment by acondura** [comment]
The front facing, public website is reporting:

WebSocket connection to 'wss://DOMAIN:7890/' failed: Error in connection establishment: net::ERR_CONNECTION_RESET

**Comment by acondura** [comment]
I've opened port 7890 like it says here https://github.com/allinurl/goaccess/issues/1100 but still nothing.

**Comment by acondura** [comment]
hm... from reading other issues in this queue, I see I need to supply SSL keys.

**Comment by acondura** [comment]
I had no idea making goaccess work with SSL and behind a Varnish cache would be so hard!

**Comment by acondura** [comment]
Still struggling with WebSocket connection to 'wss://DOMAIN:7890/' failed: Error in connection establishment: net::ERR_CONNECTION_RESET.

I now have goaccess on the same domain as the frontend, I feed it the SSL key and cert and still nothing.
Initial changes in Varnish for websocket don't seem to work.

**Comment by acondura** [comment]
I ended up using Goaccess on a standalone server with Apache. I now get this error:

goaccess: unrecognized option '--ssl-key

although I installed libssl-dev on Ubuntu and configured '--with-openssl'.

Funny thing is when I run the command directly in the CLI it works but if I set it as a service in /etc/systemd/system it throws the above error.

**Comment by acondura** [comment]
It seems there is a lingering goaccess v1.0.2 somewhere. That's the version being called from systemd, although I installed 1.4, confirmed by goaccess -V.
I can't find where it comes from.

**Comment by allinurl** [comment]
How did you find out that it's running v1.0.2?

**Comment by acondura** [comment]
From /var/log/syslog

<img width="855" alt="Screen Shot 2020-08-04 at 1 19 51 PM" src="https://user-images.githubusercontent.com/1694890/89283114-436cf600-d655-11ea-982a-36dc080cbdd6.png">

**Comment by acondura** [comment]
When I run the following command from CLI, everything works and I can access the URL with the realtime report:

ssh USER@HOST "tail -f /var/log/sites/joccom/logs/web-2917/access.log" | /usr/local/bin/goaccess --log-format=COMBINED --ssl-cert /SSLPATH/cert.pem --ssl-key /SSLPATH/privkey.pem -o /var/www/html/goaccess.html --keep-last=90 --with-output-resolver --geoip-database=/root/geolite2-city/GeoLite2-City.mmdb --real-time-html -

When I use the exact same command in goaccess.service in ExecStart, it says:

/etc/systemd/system/goaccess.service:11: Executable path is not absolute: ssh...

I go in and fix that by changing 'ssh' to '/usr/bin/ssh' and now it complains about SSL:

goaccess: unrecognized option '--ssl-cert'

**Comment by acondura** [comment]
How on earth can '--ssl-cert' be unrecognized?

**Comment by acondura** [comment]
I finally used sshfs and all works now!

**Comment by allinurl** [comment]
This should be fixed. Please update to v1.4.2. Should work with:

    ssh -n root@server 'tail -f /var/log/apache2/access.log' | goaccess - --log-format=COMBINED

**Note**, SSH requires `-n` so GoAccess can read from stdin.

Closing this. Feel free to reopen it if needed.
