### ISSUE TITLE
meet this problem ！！

### ISSUE THREAD

**Issue by llnbe** [allinurl/goaccess#1860]
8.8.8.8 - 50099 - - [29/Jul/2020:09:59:00 +0800] "www.google.com"  "POST /newEdition/getSingleWeiboAnalysisReportList.action HTTP/1.1" 200 1109 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36" "-"

![图片](https://user-images.githubusercontent.com/32897413/88913938-6cc40580-d294-11ea-971c-60cfec840228.png)

time-format %H:%M:%S
date-format %d/%b/%Y
log-format %h %^ %^ %^[%d:%t +0000] "%v" "%r" %s  %b "%R" "%u" "%^"

**Comment by 0bi-w6n-K3nobi** [comment]
It is running here!
But is best in the way:

`log-format %h %^[%d:%t ^%] "%v" "%r" %s %b "%R" "%u" "%^"`

**Comment by Titaniumtown** [comment]
> meet this problem ！！

I've met it now.

**Comment by llnbe** [comment]
![图片](https://user-images.githubusercontent.com/32897413/93840175-07075f00-fcc2-11ea-98fb-6eb0e389b293.png)
time-format %H:%M:%S
date-format %d/%b/%Y
log-format %h %^[%d:%t ^%] "%v" "%r" %s %b "%R" "%u" "%^"

**Comment by 0bi-w6n-K3nobi** [comment]
It looks so weird. Works perfectly with the example line above.
You also tried with:
`LANG = en_US.UTF-8 goaccess` ...

Can you attach some log lines here?

**Comment by 0bi-w6n-K3nobi** [comment]
PS: What is your version?  `goaccess --version`

**Comment by allinurl** [comment]
I agree, it may be an old version or locale. Closing this. Feel free to reopen it if needed.
