### ISSUE TITLE
nginx combined format needs tweaking

### ISSUE THREAD

**Issue by udf2457** [allinurl/goaccess#1864]
Hi,

I'm not sure when it changed in the NGINX codebase, but the default install of NGINX from the NGINX repo now has the following defintion for log_format:

```
log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';
access_log  /var/log/nginx/access.log  main;
```

I'm no expert, but this appears to be 99.9% similar to the "old" combined format, except for `http_x_forwarded_for` tagged on the end.  

You might want to tweak your code accordingly ?

**Comment by FranklinYu** [comment]
Setting `LANG=en_US.UTF-8` helped:

```sh
LANG=en_US.UTF-8 goaccess access.log --log-format=COMBINED
```

It has been repeatedly reported by many users: #121, #1475, #1571, #1651. I think it may help to note this in [FAQ#Configuration](https://goaccess.io/faq#configuration). Would like the opinion from maintainer.

**Comment by allinurl** [comment]
Thanks @FranklinYu - This has been added to the FAQ and man page.
