### ISSUE TITLE
GoAccess tutorial

### ISSUE THREAD

**Issue by elboulangero** [allinurl/goaccess#1866]
Hi,

I just finished a lengthy tutorial for GoAccess, that I'll publish on my blog in a few days. If you're interested, don't hesitate to give a look at it, and submit corrections, rewording or anything, if you feel what I say is not correct.

The draft is at: https://gitlab.com/elboulangero/arnaudr.io/-/blob/master/content/2020-08-goaccess.md

I'll follow-up with the final URL once it's published. Thanks!

**Comment by allinurl** [comment]
This is perfect. Thanks so much for writing this. Let me know when you publish it and I can probably link it in the getting started page.

**Comment by elboulangero** [comment]
> Let me know when you publish it and I can probably link it in the getting started page.

Sounds great! The tutorital is now published at this URL:

http://arnaudr.io/2020/08/03/goaccess-14-a-detailed-tutorial/

**Comment by elboulangero** [comment]
@allinurl Hey just bumping this one up in case. I'd be super proud to see a link to this tutorial in the "Get Started" section of goaccess.io or something, but it's up to you really :)

**Comment by allinurl** [comment]
@elboulangero Sorry for the delay on this. Completely missed it.

I've added it to the Getting Started under [**Troubleshooting**](http://goaccess.io/get-started). Once again, thanks a lot for this pretty good tutorial!

**Comment by elboulangero** [comment]
\o/ Thanks!
