### ISSUE TITLE
XSS on real-time HTML report

### ISSUE THREAD

**Issue by guragainroshan0** [allinurl/goaccess#1867]
I'm using goaccess version 1.2 installed using apt-get. I found XSS on the HTML report with payload 
`/<img%20src=x%20onerror=alert(1)> `
![image](https://user-images.githubusercontent.com/24434116/89212020-79bd5d80-d5e2-11ea-9bf7-026f47943221.png)

**Comment by allinurl** [comment]
Thanks for reporting this. Could you please test this out in the latest verson? v1.4. Let me know if that solves the issue.

**Comment by guragainroshan0** [comment]
Tested on version v1.4 but the same bug appears there as well.

**Comment by allinurl** [comment]
Can you please post the offending lines directly from your access log so I can take a look at it? Thanks

**Comment by guragainroshan0** [comment]
[03/Aug/2020:23:34:08 +0545] "GET /?%3Cimg%20src=x%20onerror=alert(1)%3E HTTP/1.1" 200 409 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.117 Safari/537.36"

**Comment by allinurl** [comment]
Could you please re-test this on v1.4? I don't get any issues with the line you posted. Thanks

![2020-09-16-180648_1304x765_scrot](https://user-images.githubusercontent.com/5005367/93401283-7525cf00-f847-11ea-9b50-8a7210d74523.png)

**Comment by guragainroshan0** [comment]
![image](https://user-images.githubusercontent.com/24434116/93432225-f1222480-f8e4-11ea-8d28-24d6b2ec5431.png)

Request: http://localhost/?data=%3Cimg%20src=x%20onerror=alert(1)%3E

Go access : ./goaccess /var/log/apache2/access.log -o ~/Documents/php/www/report.html --real-time-html

Version: 1.4 
Downloaded : https://tar.goaccess.io/goaccess-1.4.tar.gz

**Comment by allinurl** [comment]
Thank you again for reporting this. I've pushed a fix that should address the issue. Please test it out by building from [**development**](https://github.com/allinurl/goaccess#build-from-github-development) and let me know if that fixes the issue on your end.

**Comment by guragainroshan0** [comment]
It is fixed on the development version. Thank you.
