### ISSUE TITLE
Issue with --real-time-html option

### ISSUE THREAD

**Issue by dervan** [allinurl/goaccess#1878]
Hello,

I'm trying to use your great tool to monitor my nginx logs. Unfortunately, I cannot launch a properly real-time version of goaccess and I would be honored if you can share your thoughts on my setup.

I have a log file _/var/log/nginx/access.log_ I'm running a goaccess with:
`goaccess /var/log/nginx/access.log -o /var/www/html/report.html --real-time-html `
A report file appears and is up-to-date. Then I'm making a few requests and observing a log with `tail -f /var/log/nginx/access.log`. A log is updated, but a report is not. What I could missed in this scenario to run it properly?

**Comment by allinurl** [comment]
Could you please take a look at the browser's console after opening the report and see what may be the issue reported in there. Thanks.

**Comment by dervan** [comment]
There is a log indeed! I see that the file doesn't change until goaccess gets a request through websocket, but websocket was cut out by a firewall (so the file was old and that misled me). After unlocking on the firewall everything works. Thanks for your help and sorry for my silly oversight!
