### ISSUE TITLE
Error with Dreamhost Apache log

### ISSUE THREAD

**Issue by jeremycherfas** [allinurl/goaccess#1879]
I get an error of `Token '09/Aug/2020' doesn't match specifier '%d'` when trying to read my logfile with NCSA combined log format.

Date Format is `%d/%b/%Y` and Time Format is `%H:%M:%S` which I believe are correct.

Sample lines from logfile:

````
157.55.39.91 - - [09/Aug/2020:02:06:31 -0700] "GET /stream/2019-9-4 HTTP/1.1" 301 4177 "-" "Mozilla/5.0 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)" 
66.249.66.48 - - [09/Aug/2020:02:51:18 -0700] "GET /robots.txt HTTP/1.1" 301 4167 "-" "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)" 
66.249.66.52 - - [09/Aug/2020:02:51:19 -0700] "GET /ads.txt HTTP/1.1" 301 4161 "-" "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)" 
88.105.222.64 - - [09/Aug/2020:02:56:25 -0700] "GET / HTTP/1.1" 301 4202 "-" "-" 
131.220.6.152 - - [09/Aug/2020:03:23:28 -0700] "GET / HTTP/1.1" 301 3547 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.79 Safari/537.36" 
````

Any help appreciated.

**Comment by allinurl** [comment]
Could you please try your format as:

    LANG="en_US.UTF-8" bash -c 'goaccess access.log'

**Comment by jeremycherfas** [comment]
That works, so many thanks.

Would you mind explaining why? Obviously I would like to put this in my own custom configuration, but I would like to understand better.

Jeremy

On Wed, 12 Aug 2020, at 4:36 AM, Gerardo O. wrote:
> 

> Could you please try your format as:

> `LANG="en_US.UTF-8" bash -c 'goaccess access.log'
`

**Comment by allinurl** [comment]
Sorry for the delay on my response.

Sure, it seems like your machine has a different locale than your access log date format. So it may not match Aug with the month in your locale. Hope that helps :)

Closing  this, feel free to reopen it if needed.

**Comment by marcelstoer** [comment]
Ran into the exact same issue today.

On the webhost:
```
$ echo $LANG
en_US.UTF-8
```

On the log analyzer machine (macOS Big Sur)
```
$ echo $LANG

```
-> no`LANG` set explicitly

Setting it for the session and then running goaccess won't work. You really seem to have to set the variable and then invoke bash in one go.

```
$ LANG="en_US.UTF-8"                                                      
$ goaccess access.log  -a -o report.html

 [SETTING UP STORAGE access.log] {0} @ {0/s}
GoAccess - version 1.4.3 - Dec  4 2020 04:26:19
Config file: /usr/local/Cellar/goaccess/1.4.3/etc/goaccess/goaccess.conf

Fatal error has occurred
Error occurred at: src/parser.c - parse_log - 3222
No time format was found on your conf file.
```

**Comment by allinurl** [comment]
@marcelstoer did you set your log/date/time variables in your config file? or you could try something like:

    goaccess access.log  -a -o report.html --log-format=COMBINED

**Comment by marcelstoer** [comment]
Yeah, sorry. I got lost in the jungle of variations I tried. It's the `--log-format=COMBINED` I used at some point and later omitted.

**Comment by allinurl** [comment]
@marcelstoer Got it. Thanks for posting those notes!

**Comment by marcelstoer** [comment]
Btw, I did check https://goaccess.io/faq and the man page before I resorted to this issues list. This locale/`LANG` thing would be a useful addition to those pages IMO.

Thank you so much for this great tool! Heard of it for the first time today and I'm already lovin' it.

**Comment by allinurl** [comment]
@marcelstoer Thanks for the suggestion. I've added this to the [**man page**](https://goaccess.io/man#options) under `--date-format`.
