### ISSUE TITLE
Can goaccess support the second ip address?

### ISSUE THREAD

**Issue by smiliang** [allinurl/goaccess#1882]
Hello, my server is behind a proxy server.

My nginx log looks like this:
a.a.a.a (remote_addr)-[12 /Aug/ 2020: 20: 50: 02 +0000] "GET /" 302 5 "-"" Mozilla / 5.0" "b.b.b.b" (XFF)

I use "~h" to get the user's ip from the X-Forwarded-For (XFF) field, but sometimes some crawlers may scan my server directly through the ip address. In this case, XFF is "-", which may cause goaccess to throw a "Token for '%h' specifier is NULL" error.

I tried the "--no-ip-validation" option, but when the XFF of the first line of the log file is "-", the option does not work.
I prefer to set remote_addr (a.a.a.a) as the second host. When the first host is "-", goaccess can use the second host.

Can you support a second IP address?

Best wishes

**Comment by allinurl** [comment]
Sounds doable. So should it give priority to XFF and if not found, then use `%h`? Thanks

**Comment by 0bi-w6n-K3nobi** [comment]
For `NGinX`, use `real-ip` module for resolve it and just will use `%h` field.
See [here](http://nginx.org/en/docs/http/ngx_http_realip_module.html) and [there](https://docs.nginx.com/nginx/admin-guide/load-balancer/using-proxy-protocol/).

**Comment by smiliang** [comment]
> Sounds doable. So should it give priority to XFF and if not found, then use `%h`? Thanks

Yes, it is a good solution.

**Comment by smiliang** [comment]
> For `NGinX`, use `real-ip` module for resolve it and just will use `%h` field.
> See [here](http://nginx.org/en/docs/http/ngx_http_realip_module.html) and [there](https://docs.nginx.com/nginx/admin-guide/load-balancer/using-proxy-protocol/).

For nginx, this is a feasible solution. Thanks.

**Comment by allinurl** [comment]
I'm guess @0bi-w6n-K3nobi solved the issue. Thanks for posting that solution!
