### ISSUE TITLE
goaccess conf for fail2ban logs ?

### ISSUE THREAD

**Issue by securixhk** [allinurl/goaccess#1883]
Hello everyone,

I'm a bit stuck on the way to **configure goaccess to read the fail2ban logs** that have this format/syntax : 

`2020-08-13 18:57:11,326 fail2ban.actions        [10357]: NOTICE  [firewall] Ban ww.xx.yy.zz`

Can't figure out the log-format (tried various combinations related to `%d %t %^ %^ %^ %^ %^ %h` syntax).

Could you help :) ? 

Thanks in advance.

Sincerely,

**Comment by securixhk** [comment]
The solution is to carefully respect the `spaces` quantity :) besides some tricks as : 

18:57:11,326 -> **%t,%^**

Thanks

**Comment by allinurl** [comment]
You can try:
 
    goaccess fail2ban.log --log-format='%d %t,%^ %U %^ %^ %^ %v %h' --date-format=%Y-%m-%d --time-format=%T --http-protocol=no --http-method=no --ignore-panel=OS --ignore-panel=BROWSERS

**Comment by allinurl** [comment]
Closing this, feel free to reopen it if needed.
