### ISSUE TITLE
Token for '%m' specifier is NULL.

### ISSUE THREAD

**Issue by Dmytro4** [allinurl/goaccess#1885]
Log example:
`35.182.15.104 - - 2020-08-14 17:22:15 "GET /images/weapons/xxx.png HTTP/1.1" 200 65127 "https://xxx/weapons" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.125 Safari/537.36 X-Middleton/1"
`
Query:
```
bash-4.4$ <- goaccess C:/Work/Apache24/logs/access.log -o C:/Work/www/xxx/log/report.html --log-format='%h %l %u %{%Y-%m-%d %H:%M:%S}t "%r" %>s %b "%{Referer}i" "%{User-Agent}i"' --time-format='%H:%M:%S' --date-format='%Y-%m-%d' --real-time-html

Parsed 1 lines producing the following errors:

Token for '%m' specifier is NULL.

Format Errors - Verify your log/date/time format
```
Apache log settings:
`LogFormat "%h %l %u %{%Y-%m-%d %H:%M:%S}t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" new_format`

**Comment by allinurl** [comment]
Sorry for the delay on my response. This should do it:

    goaccess access.log --log-format='%h %^ %^ %d %t "%r" %s %b "%R" "%u"' --date-format=%Y-%m-%d --time-format=%T

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
