### ISSUE TITLE
 Windows: xterm-256color

### ISSUE THREAD

**Issue by Dmytro4** [allinurl/goaccess#1886]
![image](https://user-images.githubusercontent.com/22562710/90270831-830cbc80-de63-11ea-9297-748ab10d1f73.png)

**Comment by allinurl** [comment]
Which version of goaccess are you running and how did you build it?

**Comment by Dmytro4** [comment]
> Which version of goaccess are you running and how did you build it?

cowaxess_1.1.0
Installed it through .exe 
"A Bash terminal environment can be started via the cowaxess shortcut in the root of the installation directory."

**Comment by allinurl** [comment]
Please try the latest version of cowaccess, there have been multiple changes upstream that may address this. 

Closing this, however, feel free to reopen it if needed.
