### ISSUE TITLE
src/tpl.c:61:10: fatal error: win/mman.h: No such file or directory

### ISSUE THREAD

**Issue by msitprof** [allinurl/goaccess#1893]
we are trying to install goaccess on cygwin on window 10 machine and get the following error 
src/tpl.c:61:10: fatal error: win/mman.h: No such file or directory

i have install all the package but still no luck, can you please help me in this regards,

**Comment by allinurl** [comment]
Thanks for reporting this. The fix will be pushed out in the upcoming release.

Closing this as is a dup of #1851
