### ISSUE TITLE
I can't see VIRTUAL HOSTS report

### ISSUE THREAD

**Issue by hurano** [allinurl/goaccess#1895]
<img width="597" alt="Screen Shot 2020-08-20 at 4 28 28 PM" src="https://user-images.githubusercontent.com/3528876/90835801-5b55a280-e302-11ea-804e-b0af96d163bc.png">

How can I output the virtual hosts report?

Thank you.

**Comment by allinurl** [comment]
Did you use the `%v` specifier?

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
