### ISSUE TITLE
[Future] Migrate the Docker image build to GitHub Actions.

### ISSUE THREAD

**Issue by err931** [allinurl/goaccess#1896]
Resolves: #1877

Recently, there have been a number of glitches in the automated build system within Docker Hub.

I wrote a case of publishing an image to Docker Hub using __GitHub Actions__ to try it out, and it worked very well.

There are a few issues, such as the __Docker Hub side description not being automatically updated,__ but there are many advantages, such as the generation of a versioned image when a new tag is hit.

If you want to migrate, you can create a pull request in the workflow I created.

-----

__Note:__ It conflicts with the CI on the Docker Hub side, so you may need to remove the Docker Hub package once and configure it anew.

**Comment by allinurl** [comment]
I can look into this. Are you able to share the detailed steps and just so we have a record, exactly what it is going to affect. Thanks, @err931

**Comment by err931** [comment]
I've prepared a workflow that actually works.
This is a slightly modified version of the official __GitHub Actions__ sample.

Original: https://git.io/docker-publish

# Process
1. Get `Docker Hub` access tokens. [Docs](https://docs.docker.com/docker-hub/access-tokens/)
1. Set up an access token in the GitHub repository with the key name `DOCKERHUB_TOKEN`. [Docs](https://docs.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets)
1. Create a new commit and push.
1. The CI starts, and everything from build tests to pushing to Docker Hub is done.
1. Yay. :muscle:

=====

For reference, add it to your pull request.

**Comment by err931** [comment]
__This remains in does not work.__

Please refer to [this page](https://docs.docker.com/docker-hub/access-tokens/) to get an access token.

The access token is stored in secret as `DOCKERHUB_TOKEN`.

I'll delete it later. NRN.

![](https://user-images.githubusercontent.com/67395018/91793459-342c9880-ec53-11ea-9212-bb0ba756672b.png)

**Comment by allinurl** [comment]
@err931 Thanks for the sending those details. It should be there now, let me know if I missed something on my end.
