### ISSUE TITLE
Running as systemd service

### ISSUE THREAD

**Issue by hennedo** [allinurl/goaccess#1898]
Hey!
I'm trying to get goaccess 1.4 to run as a systemd service. I have changed the config file /etc/goaccess/goaccess.conf to my needs, including persistent and restoring storage in /opt/goaccess. Everything belongs to root at this time and everything is running as root, I know, very unsafe, but I'll get to that once everything is running.

The following is my systemd service.
```
[Unit]
Description=GoAccess Live Log Analyzer

[Service]
Type=simple
ExecStart=/usr/bin/goaccess -p /etc/goaccess/goaccess.conf
ExecStop=/bin/kill -9 ${MAINPID}
PrivateTmp=false
RestartSec=1800
User=root
Group=root
Restart=always

[Install]
WantedBy=multi-user.target
```

It starts properly, it produces the correct html output and seems to be working well, except for the persisting database.
When run as systemd service, goaccess does not seem to write anything to the db-path /opt/goaccess. It's just empty. 

On the other hand, when I manually run `sudo goaccess -p /etc/goaccess/goaccess.conf` it does produces db files in the db-path and also restores the previous data correctly. 
When I now start the systemd service, it reads from the persisted data, but does not write to it.
What am I missing here?

Here is an excerpt of my config file (I removed static files stuff..)

```
time-format %H:%M:%S
date-format %d/%b/%Y
log-format %h %^[%d:%t %^] "%r" %s %b "%R" "%u"

## UI Settings

config-dialog false
hl-header true
json-pretty-print false
no-color false
no-column-names false
no-csv-summary false
no-progress false
no-tab-scroll false
with-mouse false

## Server options

daemonize false
pid-file /var/run/goaccess.pid
real-time-html true
ws-url wss://example.com
log-file /var/log/nginx/example.com.log
ssl-cert /etc/letsencrypt/live/example.com/fullchain.pem
ssl-key /etc/letsencrypt/live/example.com/privkey.pem

## Parse options

agent-list false
with-output-resolver false
http-method yes
http-protocol yes
output /var/www/report_example.com.html
no-query-string false
no-term-resolver false
444-as-404 false
4xx-to-unique-count false
all-static-files false
double-decode false
ignore-crawlers false
crawlers-only false
ignore-panel REFERRERS
ignore-panel KEYPHRASES
real-os true

## Static Files
static-file .xxx
static-file .xxx

## Persistence Options
db-path /opt/goaccess
persist true
restore true
```

```
ls -lha /opt/goaccess
total 16K
drwxrwxrwx 2 root root  12K Aug 23 15:21 .
drwxr-xr-x 6 root root 4.0K Aug 17 12:56 ..
```

UPDATE
I changed the rights of the databasefiles to ugo+rw, so everyone can write to it, so it seems, it's not a rights problem.
```
ls -lha /opt/goaccess/
total 748K
drwxrwxrwx 2 root root  12K Aug 25 23:12 .
drwxr-xr-x 5 root root 4.0K Aug 25 23:12 ..
-rw-rw-rw- 1 root root  166 Aug 27 14:58 IGSL_BROWSERS_MTRC_AGENTS.db
-rw-rw-rw- 1 root root  166 Aug 27 14:58 IGSL_HOSTS_MTRC_AGENTS.db
-rw-rw-rw- 1 root root  166 Aug 27 14:58 IGSL_NOT_FOUND_MTRC_AGENTS.db
-rw-rw-rw- 1 root root  166 Aug 27 14:58 IGSL_OS_MTRC_AGENTS.db
-rw-rw-rw- 1 root root  166 Aug 27 14:58 IGSL_REFERRING_SITES_MTRC_AGENTS.db
-rw-rw-rw- 1 root root  166 Aug 27 14:58 IGSL_REQUESTS_MTRC_AGENTS.db
-rw-rw-rw- 1 root root  166 Aug 27 14:58 IGSL_REQUESTS_STATIC_MTRC_AGENTS.db
-rw-rw-rw- 1 root root  166 Aug 27 14:58 IGSL_STATUS_CODES_MTRC_AGENTS.db
[..]
```
Still no writing to the database after logrotate moves the file and restarts goaccess. The previous log-day is just not in the graph and therefore not in the database.
If I then do
```
sudo service goaccess stop
sudo goaccess -p /etc/goaccess/goaccess.conf -f /var/log/nginx/example.com.log.1
[ctrl+c]
sudo service goaccess start
```
The previous log shows in the data.

**Comment by hennedo** [comment]
I got it resolved! Scrolled through the code and found that goaccess saves it's database when goaccess is closed. So stupid me with copy&paste systemd service files used "kill -9 ${MAINPID}" for the stop command, -9 kills it and it never gets to the point where it can write to the database.

For anyone interested in a working systemd file:

```
[Unit]
Description=GoAccess Live Log Analyzer

[Service]
Type=simple
ExecStart=/usr/bin/goaccess -p /etc/goaccess/goaccess.conf
ExecStop=/bin/kill ${MAINPID}
PrivateTmp=false
RestartSec=1800
User=root
Group=root
Restart=always

[Install]
WantedBy=multi-user.target
```

Sidenote: If I understand correctly, if logrotate is used, logrotate needs to restart the service because of #1906 which is resolved in 1.4.1

**Comment by allinurl** [comment]
Thanks for sharing these findings. v1.4.1 should address #1906 as you noted above. Stay tuned!

**Comment by bugbounce** [comment]
In the interest of being explicit, the following could be added to the [Service] section:
```
ExecStop=/bin/kill -0 ${MAINPID}
KillSignal=SIGINT
RestartKillSignal=SIGINT
```
