### ISSUE TITLE
Enable GeoIP type is missing from building-from-source example

### ISSUE THREAD

**Issue by pla1** [allinurl/goaccess#1901]
I think the [example for building from source](https://goaccess.io/download#build) should be 
`./configure --enable-geoip=legacy --enable-utf8`
or 
`./configure --enable-geoip=mmdb --enable-utf8`
instead of 
`./configure --enable-geoip --enable-utf8`

Thanks! ☮

**Comment by allinurl** [comment]
Sorry for the delay. This has been fixed. Thanks for reporting it!
