### ISSUE TITLE
What should I do?

### ISSUE THREAD

**Issue by TheEarlSun** [allinurl/goaccess#1902]
I cann't install GoAccess-1.4 on CowAxess. 
<img width="455" alt="Capture" src="https://user-images.githubusercontent.com/30995450/91199451-1bd6ee00-e728-11ea-9d13-60aa25569fb6.PNG">

**Comment by allinurl** [comment]
Thanks for reporting this. The fix will be pushed out in the upcoming release.

Closing this as is a dup of #1851
