### ISSUE TITLE
Format Errors - Verify your log/date/time format

### ISSUE THREAD

**Issue by picc8** [allinurl/goaccess#1903]
I want extract data from my log, but I can't understand the right *format :(

Here one sample segment from my log:

```
Aug 26 09:20:39 host remote_addr: [0.000 - .] - testdomain.com - 10.00.123.123, 69.22.1.34 - - [26/Aug/2020:09:20:39 +0200]  "GET /media/image.jpg HTTP/1.1" 304 0 "https://testdomain.com/test.html" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36"
```

nginx conf:

```
log_format main '[$request_time $upstream_response_time $pipe] - $host - $remote_addr - $remote_user [$time_local]  '
'"$request" $status $body_bytes_sent '
'"$http_referer" "$http_user_agent"';
```

**Comment by 0bi-w6n-K3nobi** [comment]
Try this, in `goaccess.conf`:

`date-format %d/%b/%Y`
`time-format %H:%M:%S`
`log-format %^[%T %^ %^ %^] %^ %v %^ ~h %^ %e %^[%d:%t %^] "%r" %C %b "%R" "%u"`

or in command-line:
`--date-format='...' --time-format='...' --log-format='...'`

**Comment by picc8** [comment]
> Try this, in `goaccess.conf`:
> 
> `date-format %d/%b/%Y`
> `time-format %H:%M:%S` or `time-format %T`
> `log-format [%T %^ %^] - %v - ~h{, } - %e [%d:%t %^] "%r" %s %b "%R" "%u"`
> `. . . . . . . . . . . . . . . . . . . . . . . . -- ^^ 2 spaces here --` like in your `NGinX Conf`
> 
> or in command-line:
> `--date-format='...' --time-format='...' --log-format='...'`
> 
> **Notes:**
> 
>     * For complex field like this, X-Forwarded-For (XFF) field, is more easy use a double quote "".
>       i.e. like `... testdomain.com - "10.0.123.123, 69.22.1.34" - ...`
> 
>     * The ipv4 10.**0**0.123.123 is not valid. GoAccess need 1 valid `IP` by line record that will be process.
> 
>     * See [Man Page](https://goaccess.io/man) section `SPECIFIERS` for more details.

**Comment by picc8** [comment]
> Try this, in `goaccess.conf`:
> 
> `date-format %d/%b/%Y`
> `time-format %H:%M:%S` or `time-format %T`
> `log-format [%T %^ %^] - %v - ~h{, } - %e [%d:%t %^] "%r" %s %b "%R" "%u"`
> `. . . . . . . . . . . . . . . . . . . . . . . . -- ^^ 2 spaces here --` like in your `NGinX Conf`
> 
> or in command-line:
> `--date-format='...' --time-format='...' --log-format='...'`
> 
> **Notes:**
> 
>     * For complex field like this, X-Forwarded-For (XFF) field, is more easy use a double quote "".
>       i.e. like `... testdomain.com - "10.0.123.123, 69.22.1.34" - ...`
> 
>     * The ipv4 10.**0**0.123.123 is not valid. GoAccess need 1 valid `IP` by line record that will be process.
> 
>     * See [Man Page](https://goaccess.io/man) section `SPECIFIERS` for more details.

it works!
Thank you for your precious help and clarification.
