### ISSUE TITLE
Real time follow rotated log file

### ISSUE THREAD

**Issue by stephenwade** [allinurl/goaccess#1906]
Should GoAccess keep following a log file that is replaced by `logrotate`? I see a reference in `goaccess.c` to rotated/truncated files so I thought it would work with `logrotate`, but still GoAccess stops working after logrotate runs. The green dot stays running and I don't see any errors in the terminal running the service, but new requests stop showing up on the dashboard.

https://github.com/allinurl/goaccess/blob/4bc8423b9835734e230fcc1355edc08ca86d867e/src/goaccess.c#L785-L786

My terminal this morning still just shows the text that it showed when I started GoAccess yesterday:

```
Parsing... [16] [0/s]
WebSocket server ready to accept new client connections
```

Full command:

```
/usr/bin/goaccess /var/log/apache2/stephenwade.me_access.log \
    -o /var/www/stephenwade.me/goaccess/index.html \
    --log-format=COMBINED --real-time-html --port=8625 \
    --ssl-cert=/etc/letsencrypt/live/stephenwade.me/fullchain.pem \
    --ssl-key=/etc/letsencrypt/live/stephenwade.me/privkey.pem \
    --html-report-title='stephenwade.me Server Statistics' --html-prefs='{"theme": "darkBlue"}'
```

**Comment by allinurl** [comment]
Thanks for reporting this. It should be fixed upstream as this was a regression. Could you please build from [**development**](https://github.com/allinurl/goaccess#build-from-github-development) and verify that it's working for you? Thanks!

**Comment by stephenwade** [comment]
I've built from source and started GoAccess. I will report tomorrow whether GoAccess kept running overnight.

**Comment by stephenwade** [comment]
Success! It works as expected now.

What is the ETA for 1.4.1?
