### ISSUE TITLE
Installation on 20.04

### ISSUE THREAD

**Issue by ijf8090** [allinurl/goaccess#1907]
Despite what the instructions say, installation on Ubuntu 20.04 is not straightforward

"Installing GoAccess is pretty easy. Just download, extract and compile it with:
					$ ./configure --enable-utf8 --enable-geoip=legacy
					$ make
					# make install
"

Yeah, not so much - this is what worked for me 
  350  sudo apt-get install libncurses5-dev libncursesw5-dev
  352  ./configure --enable-utf8 --disable-dependency-tracking
  354  sudo apt install make
  355  make install
  356  sudo make
I'm pretty sure I had to install gcc also

**Comment by allinurl** [comment]
Thanks for posting that. I may need to add the note at the top of the page, but you can find it under [**distribution packages**](https://goaccess.io/download#build).

> **Note**: You may need to install build tools like `gcc`, `autoconf`, `gettext`, `autopoint` etc for compiling/building software from source. e.g., base-devel, build-essential, "Development Tools".

**Comment by ijf8090** [comment]
Very impressed by your quick response!
 I agree that adding the note re: build tools at the top  of the page would be very helpful. 

 I think it would also be helpful to move this note to the top of the page"
"It is easiest to install GoAccess on Linux using the preferred package manager of your Linux distribution. Please note that not all distributions will have the lastest version of GoAccess available "

BTW - there is a typo in that note,  "lastest" should be "latest" :)

Best regards
Ian

**Comment by allinurl** [comment]
Website updated. Thanks again for the suggestions.
