### ISSUE TITLE
how to use  date/time format

### ISSUE THREAD

**Issue by hope1234567hope** [allinurl/goaccess#1908]
my  tst.log is:
11.66.227.216 - - [2020-08-10T14:46:04+08:00] "GET /ngiam-rst/1.1" 200 44 "https://tam.i.pc/qrcode.html?/defatult.aspx" "Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.14)" "-"

use nginx2goaccess.sh 
./nginx2goaccess.sh '$remote_addr - $remote_user [$time_iso8601] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent" "$http_x_forwarded_for"'

time-format %T
date-format %d/%b/%Y
log_format %h - %^ [%^8601] "%r" %s %b "%R" "%u" "%^"

[root@forp tmp]# goaccess tst.log         
Parsed 1 lines producing the following errors:
Token 'ET' doesn't match specifier '%s'
Format Errors - Verify your log/date/time format

 How to solve it，thanks

**Comment by 0bi-w6n-K3nobi** [comment]
Try this:

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
