### ISSUE TITLE
date format using Russian localization crash

### ISSUE THREAD

**Issue by partnumber** [allinurl/goaccess#1912]
Hello All!
I use your wonderful analyzer, I like it very much.
Everything works fine in the default locale (English). One has only to change the locale to Russian (I love Russian, I'm from Russia), the demon stops running. I am using the default config file. My operating FreeBSD hostname 12.1-RELEASE-p9 FreeBSD 12.1-RELEASE-p9 GENERIC amd64.
Usually I switch the login class with the command pw user mod user -L russian.
My goaccess.conf
###
time-format% H:% M:% S
date-format% d /% b /% Y
log-format% v:% ^% h% ^ [% d:% t% ^] "% r"% s% b "% R" "% u"
log-format COMBINED
config-dialog false
hl-header true
html-report-title
json-pretty-print false
no-color false
no-column-names false
no-csv-summary false
no-progress false
no-tab-scroll false
with-mouse false
log-file /var/log/nginx/access.log
agent-list false
with-output-resolver false
http-method yes
http-protocol yes
output /usr/local/www/index.html
no-query-string false
no-term-resolver false
444-as-404 false
4xx-to-unique-count false
all-static-files false
double-decode false
ignore-crawlers false
crawlers-only false
ignore-panel REFERRERS
ignore-panel KEYPHRASES
real-os true
static-file .css
static-file .js
static-file .jpg
static-file .png
static-file .gif
static-file .ico
static-file .jpeg
static-file .pdf
static-file .csv
static-file .mpeg
static-file .mpg
static-file .swf
static-file .woff
static-file .woff2
static-file .xls
static-file .xlsx
static-file .doc
static-file .docx
static-file .ppt
static-file .pptx
static-file .txt
static-file .zip
static-file .ogg
static-file .mp3
static-file .mp4
static-file .exe
static-file .iso
static-file .gz
static-file .rar
static-file .svg
static-file .bmp
static-file .tar
static-file .tgz
static-file .tiff
static-file .tif
static-file .ttf
static-file .flv
geoip-database /usr/local/share/GeoIP/GeoLiteCity.dat
###
pw user mod root -L default
/ usr / local / bin / goaccess -p /usr/local/etc/goaccess/goaccess.conf --no-progress
/var/log/nginx/access.log
Everything is OK
If I change the class pw user mod root -L russian
 / usr / local / bin / goaccess -p /usr/local/etc/goaccess/goaccess.conf --no-progress
/var/log/nginx/access.log
Parsed 1 lines producing the following errors:
Token '01 / Sep / 2020 'doesn't match specifier'% d '
Format Errors - Verify your log / date / time format

**Comment by allinurl** [comment]
It sounds like you are changing the date/time format upon setting it to Russian. I'd make sure not to change the date/time locale. You could always try checking the output of `date` in your terminal after switching to Russian. Feel free to post the output.

**Comment by partnumber** [comment]
Thank you for quick answer.
It helped me env LC_TIME = "en_US.UTF-8" / usr / local / bin / goaccess -p /usr/local/etc/goaccess/goaccess.conf --no-progress.
Good luck.
