### ISSUE TITLE
Chinese I18N seems doesn't works well?

### ISSUE THREAD

**Issue by kannad** [allinurl/goaccess#1914]
trying:
- $ LANG="zh_CN.UTF-8" bash -c 'goaccess .......'
- $ LANG="zh_CN.UTF8" bash -c 'goaccess .......'
- $ LANG="zh_CN" bash -c 'goaccess .......'

my env:

$ locale -a | grep zh_CN
zh_CN
zh_CN.gb18030
zh_CN.gb2312
zh_CN.gbk
zh_CN.utf8

$ echo $LANG
zh_CN

$ cat /etc/redhat-release 
CentOS Linux release 7.7.1908 (Core)

my english is so bad that some words might be wrong :( sorry about that

![image](https://user-images.githubusercontent.com/17513790/93214964-6af8c780-f798-11ea-9fde-50788261b6d0.png)

**Comment by allinurl** [comment]
Could you please give elaborate about this issue? Thanks

**Comment by kannad** [comment]
> Could you please give elaborate about this issue? Thanks

i just supply :)

**Comment by allinurl** [comment]
Please take a look at issue #1506, that seems to be the issue. May need to  install 

    dnf install glibc-all-langpacks

**Comment by kannad** [comment]
> Please take a look at issue #1506, that seems to be the issue. May need to install
> 
> ```
> dnf install glibc-all-langpacks
> ```

centos 7 seems no rpm could be found.
i trying 

- yum update -y glibc-common
- yum install glibc-common glibc.i686 glibc.x86_64

This doesn't seem to work

**Comment by ms217** [comment]
On El7 glibc-common provides the locales. The package glibc-all-langpacks only exists on EL8.
@kannad Which GoAccess version do you use?

GoAccess 1.4 (release tag) on EL7 generates the statistics just fine here on my system.

**Comment by kannad** [comment]
> On El7 glibc-common provides the locales. The package glibc-all-langpacks only exists on EL8.
> @kannad Which GoAccess version do you use?
> 
> GoAccess 1.4 (release tag) on EL7 generates the statistics in chinese just fine here on my system.

It also worked for me, tks ever so, I used the old version in the past
