### ISSUE TITLE
Packaged version won't work with debian GeoIP database

### ISSUE THREAD

**Issue by fancsali** [allinurl/goaccess#1918]
Installed debian maintained version `1.2`, from the main `buster` repo, along with the `geoip-database` and `geoip-database-extra` packages. The result is, that the GeoIP features work as expected.

Added the project's own APT repository, and installed version `1.4` this way. The result is an error when trying to use the same data files:
```
# sudo -u www-data -g adm goaccess /var/log/apache2/access.log.1 /var/log/apache2/access.log --real-time-html --keep-last=7 -o /var/cache/goaccess/index.html
GoAccess - version 1.4 - May 18 2020 01:45:26
Config file: /etc/goaccess/goaccess.conf

Fatal error has occurred
Error occurred at: src/geoip2.c - init_geoip - 89
Unable to open GeoIP2 database: /usr/share/GeoIP/GeoIP.dat
```

Despite, both seemingly being built with  `--enable-geoip=mmdb`...

https://salsa.debian.org/debian/goaccess/-/blob/master/debian/rules:
```
...
override_dh_auto_configure:
	dh_auto_configure -- --enable-geoip=mmdb --enable-utf8 --with-openssl
```

Project's version:
```
# goaccess -V
GoAccess - 1.4.
For more details visit: http://goaccess.io
Copyright (C) 2009-2020 by Gerardo Orellana

Build configure arguments:
  --enable-utf8
  --enable-geoip=mmdb
  --with-openssl
```

**Comment by fancsali** [comment]
Had another look, and it seems, that the Debian maintained version of 1.2 is built with `--enable-geoip=mmdb`, whereas both this version and the Debian maintained version 1.4 (from bullseye) has in fact been build with `--enable-geoip=mmdb`.

**Comment by fancsali** [comment]
Furthermore it seems to me, that all versions (buster, bullseye, buster-backports) of the geoip-database and geoip-database-extra packages in Debian are using the legacy format.

**Comment by fancsali** [comment]
Confirmed.

Built as per instructions from source, using `--enable-utf8 --enable-geoip=legacy --with-opessl` and works sort of fine. (Except only as root, similarly to #868 and #1091)

**Comment by allinurl** [comment]
Thanks for reporting this. GeoIP.dat is in fact the legacy db. For mmdb, you can use DB-IP Lite databases. Please take a look at these [**comments**](https://github.com/allinurl/goaccess/blob/master/config/goaccess.conf#L665) for more info and let me know how it goes. Thanks

**Comment by fancsali** [comment]
Indeed, I did. What I am sort of suggesting here, I guess, is that the package built for buster specifically should be working with the default Debian GeoIP database included with buster.

At least that's what I would have expected - especially, that other packages on my system already use those databases.

I appreciate, this is a compile time option, so it's an either-or. Otherwise it would mean two packages to both align with the Debian defaults and have the freedom of using the MMDB format too - it would still make sense to me, nevertheless.

Would love to hear the views of others, though.

**Comment by fancsali** [comment]
Happy to contribute, btw, if you'd be so kind to point me towards the source/build files for the `.deb` package.

**Comment by allinurl** [comment]
@fancsali sorry for the late reply. I just noticed this message. The source can be found here (for buster):

    https://deb.goaccess.io/amd64/goaccess_1:1.4-buster_amd64.deb

**Comment by allinurl** [comment]
By the way, just to be clear, you are saying that goaccess ( buster ) should be build against `libgeoip-dev` instead of  `libmmdb2-0`?

**Comment by fancsali** [comment]
Well, by source, I meant the scripts/makefiles used when building those `.deb` packages.

Well, yes, I meant that the source in the `buster` package shall use `--enable-geoip=legacy`, essentially; I reckon, that'd mean `libgeiop-dev` instead of `libmmdb2-0`.

**Comment by allinurl** [comment]
v1.4.2 was built with mmdb per #1965. Here are the available packages.

```
goaccess |  1:1.4.2-xenial |  xenial | amd64, i386
goaccess |  1:1.4.2-bionic |  bionic | amd64
goaccess |    1:1.4.2-eoan |    eoan | amd64
goaccess |   1:1.4.2-focal |   focal | amd64
goaccess | 1:1.4.2-stretch | stretch | amd64, i386
goaccess |  2:1.4.2-buster |  buster | amd64, i386
```
