### ISSUE TITLE
Format for SHOUTcast V2 Log Files?

### ISSUE THREAD

**Issue by XfactorDO** [allinurl/goaccess#1919]
I tried a little bit but dont get it working with shoutcast v2 log files.

**Example**
```
#Software: SHOUTcast
#Version: 2.6.0.750
#Fields: c-ip c-dns date time cs-uri-stem c-status cs(User-Agent) sc-bytes x-duration avgbandwidth
217.232.69.000 217.232.69.000 2020-09-19 11:12:00 /stream?title=Little%20Eva%20-%20Some%20Kind-A%20Wonderful%20%5B8e5%5D 200 WinampMPEG%2F5.50 2423327 152 127543
88.99.58.000 88.99.58.000 2020-09-19 11:12:00 /stream?title=Little%20Eva%20-%20Some%20Kind-A%20Wonderful%20%5B8e5%5D 200 WinampMPEG%2F5.50 2432105 152 128005
85.220.185.00 85.220.185.00 2020-09-19 11:12:00 /stream?title=Little%20Eva%20-%20Some%20Kind-A%20Wonderful%20%5B8e5%5D 200 WinampMPEG%2F5.50 2433776 152 128093
87.162.74.00 87.162.74.00 2020-09-19 11:12:00 /stream?title=Little%20Eva%20-%20Some%20Kind-A%20Wonderful%20%5B8e5%5D 200  2432522 152 128027
95.217.164.000 95.217.164.000 2020-09-19 11:12:09 /stream?title=Little%20Eva%20-%20Some%20Kind-A%20Wonderful%20%5B8e5%5D 200  16384 0 0
85.220.185.00 85.220.185.00 2020-09-19 11:14:07 /stream?title=The%20Kinks%20-%20Dandy%20%5B2d9%5D 200 WinampMPEG%2F5.50 2023340 127 127454
217.232.69.000 217.232.69.000 2020-09-19 11:14:07 /stream?title=The%20Kinks%20-%20Dandy%20%5B2d9%5D 200 WinampMPEG%2F5.50 2031282 127 127954
88.99.58.000 88.99.58.000 2020-09-19 11:14:07 /stream?title=The%20Kinks%20-%20Dandy%20%5B2d9%5D 200 WinampMPEG%2F5.50 2024594 127 127533
87.162.74.00 87.162.74.00 2020-09-19 11:14:07 /stream?title=The%20Kinks%20-%20Dandy%20%5B2d9%5D 200  2023759 127 127480
```

Could someone help please with the right format?

**Comment by scysys** [comment]
`--log-format='%h %v %d %t %U %s %u %b %T %^'`

Should help

**Comment by 0bi-w6n-K3nobi** [comment]
Try this, in `goaccess.conf`:

`time-format %H:%M:%S` or in same way `time-format %T`
`date-format %Y-%m-%d` or in same way `date-format %F`
`log-format %h %^ %d %t %U %s %u %b %L %^`

or in command-line
`--time-format='...' --date-format='...' --log-format='...'`

**notes:**
I believe that `.00` and `.000` in the `IPs` are just examples. These values are not valid.
There is no field for the `http method`, so use `--http-method=no`.

It will be difficult to process this `LOG`. 
It sometimes introduces the `user-agent`, others not.
You will have to separate these lines into 2 distinct files.
Or ignore all fields just after status `%s`, using `%^`. i.e. : 

`log-format %h %^ %d %t %U %s %^`

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
