### ISSUE TITLE
Please add a javascript table sort

### ISSUE THREAD

**Issue by pjsg** [allinurl/goaccess#192]
Using something like jquery tablesorter would allow the various tables to be sorted by the user clicking in the browser.

Thanks

**Comment by 2vek** [comment]
:+1: Would be nice to have.
Since, we already have expanding tables, first thing I tried to do was sorting table by clicking table header.

**Comment by allinurl** [comment]
@2vek I'll look into it now that I'm working on the Bootstrapify output #223. Thanks for the reminder!

**Comment by allinurl** [comment]
This has been implemented and deployed in [version 1.0](https://goaccess.io/). Thanks.
