### ISSUE TITLE
Multiple sites url informations 

### ISSUE THREAD

**Issue by N445** [allinurl/goaccess#1921]
Hello
I have several log files for the accesses to my sites. I have a problem because in the interface only the name of the links are shown (Requested Files (URLs) or Not Found URLs (404s) for exemple), but without any indication of which website the information comes from.

How to display the website information ?

**Comment by 0bi-w6n-K3nobi** [comment]
To do this, apply a simple filter. Change `/uri` by `domain-site/uri`. 
Use a command like:

`awk '$8=$1$8' access.log | goaccess -a -`

See more on the [main page](https://goaccess.io/man), in the section `VIRTUAL HOSTS`.

**Comment by N445** [comment]
Okay I see but it's seam it doesn't look like a format for nginx ?
I'm sorry I forgot to speficy that I'm using nginx and the log format is that

`172.19.0.1 - - [23/Sep/2020:17:23:48 +0000] "GET /myroute" 200 21130 "http://myhost.local/" "Mozilla/5.0 (X11; Linux; rv:40) Gecko/20 Firefox/80.0"`

**Comment by 0bi-w6n-K3nobi** [comment]
I **see** that you **don't have** `vhost` `%s` [`domain-site`] in the `LOG`.
Would it be a separate `LOG` for each `domain-site`?
If yes, you can make it fixed for each `domain-site` for each `LOG`.
Ex.:

`awk '$7="site1"$7' access1.log | goaccess -a -`
`awk '$7="site2"$7' access2.log | goaccess -a -`
...

**Comment by allinurl** [comment]
Closing this due to the lack of info. Feel free to reopen it if needed.
