### ISSUE TITLE
Real-time HTML doesn't show request times while a static one does

### ISSUE THREAD

**Issue by andreychirikba** [allinurl/goaccess#1930]
I run two almost identical commands:
`grep '05/Oct/2020' access_log | LANG=en_US goaccess --log-format '[%d:%t +0200] %h %e "%r" %s %b "%R" "%u" **%^/%D**' --date-format '%d/%b/%Y' --time-format '%H:%M:%S' - -o 2020-10-05-report.htm`
and
`ssh user@server 'tail -f /var/log/httpd/access_log' | LANG=en_US goaccess --log-format '[%d:%t +0200] %h %e "%r" %s %b "%R" "%u" **%^/%D**' --date-format'%d/%b/%Y' --time-format '%H:%M:%S' --real-time-html -o report.html --ws-url localhost`
The first one reads grep output from stdin and writes it to a report file, the second one reads tail output from an ssh session for real-time reporting. The difference is, whichever remote command I try with an ssh session (cat, grep etc.), the following columns are missing on every panel of GoAccess dashboard: 
`Tx. Amount | Avg. T.S. | Cum. T.S. | Max. T.S.`
While they are always present when I source the input locally. Is it some kind of shell or cr/ln mismatch? Or does it somehow misdetect whatever is on the first line and determines the structure of the rest of the file? A typical log line is:
`[04/Oct/2020:04:30:34 +0200] 104.131.105.130 - "HEAD /icons/apache_pb.gif HTTP/1.0" 301 - "-" "Mozilla/5.0 (compatible; NetcraftSurveyAgent/1.0; +info@netcraft.com)" **0/182**`

Both the referrer and the user agent get detected correctly.

**Comment by andreychirikba** [comment]
any thought on this? This means I can't really use Goaccess for realtime stats, because the most important metric is how long requests take.

**Comment by allinurl** [comment]
I pushed a commit that fixes this. Please feel free to test it out by building from [**development**](https://github.com/allinurl/goaccess#build-from-github-development) and let me know if that solves the issue on your end. I'll push it out in the upcoming minor release. 

Thanks for reporting it!

**Comment by andreychirikba** [comment]
Yes, I can confirm it works, thanks for that!
