### ISSUE TITLE
Change base image back to busybox

### ISSUE THREAD

**Issue by jjlin** [allinurl/goaccess#1932]
After updating to the latest Docker image today, I found that my setup broke because the base image is now `scratch`. Considering `busybox` is a pretty lightweight image already, this seems to have minimal benefit, while making troubleshooting and other use cases needlessly difficult.

For example, my entrypoint is of the form `/bin/sh -c "tail -F /goaccess/logs/access_log | goaccess ...` since `goaccess` isn't natively able to follow log files across renames/rotations.

**Comment by allinurl** [comment]
Thank you for reporting this. It should be fixed. Please let me know how it goes on your end.
