### ISSUE TITLE
Running persist and restore consecutives always lost next record

### ISSUE THREAD

**Issue by 0bi-w6n-K3nobi** [allinurl/goaccess#1933]
Hello @allinurl, I'm here again.

After `BUG`/mismatch at #1929 yet I cannot run persist and restore satisfactorily.
I will explain the problem through a practical example.

Consider the simple `LOGFILE` below:
```
1.2.3.4 2020-10-07 01:02:03 "GET /a.html HTTP/1.1" 200 1 "(Windows NT 10.0; Win64; x64) Chrome/85.0.4183.101" a.com HIT
2.3.4.5 2020-10-07 02:03:04 "GET /b.html HTTP/2.0" 304 2 "(X11; Linux x86_64) Firefox/80.0" b.com MISS
3.4.5.6 2020-10-07 03:04:05 "GET /c.html HTTP/1.0" 302 3 "(Linux; Android 6.0.1; None) Safari/604.1" c.com EXPIRED
```
and `GoAccess` with appropriated parameters:

`goaccess --no-global-config --date-spec='hr' --hour-spec='min'`
` --date-format='%Y-%m-%d' --time-format='%H:%M:%S'`
`  --log-format='%h %d %t "%r" %s %b "%u" %v %C' --output=./a.html -`

For running bellow, will be generate perfect output:

`cat LOGFILE | goaccess ...`

But, if I run in 2 steps like:

`mkdir db`
`head -1 LOGFILE | goaccess ... --db-path=./db --persist`
`tail -n +2 LOGFILE | head -1 | goaccess ... --db-path=./db --restore --persist`

and Oops... In all `PANELs` will be show 2 HITS, and `SUM` of bytes will be correct, 
but **2nd record** of data will be simply "**swallowed**".

In the other way, I can run too:

`mkdir db`
`head -1 LOGFILE | goaccess ... --db-path=./db --persist`
`tail -n +2 LOGFILE | goaccess ... --db-path=./db --restore --persist`

In this case, again, the 2nd record will be disappear but _3rd will be OK_.

Try yourself this below, and you will see that it gets **even worse**, mixing things up if:

`mkdir db`
`head -1 LOGFILE | goaccess ... --db-path=./db --persist`
`tail -n +2 LOGFILE | head -1 | goaccess ... --db-path=./db --restore --persist`
`tail -n +3 LOGFILE | head -1 | goaccess ... --db-path=./db --restore --persist`

But the follow is ok:

`mkdir db`
`head -1 LOGFILE | goaccess ... --db-path=./db --persist`
`echo -n '' | goaccess ... --db-path=./db --restore --persist`

All rigth.
I tried debug and found than `GoAccess` looks rigth to write [ persist ] the `HASH` table. 
I maked hexdump for `SI32_UNIQUE_KEYS.db` file, just after 1st record processing 
and write them, and _uniq visitor key_ was there.

The problem appears after load. The `hash` table looks diferent when **load** and 
when `GOACCESS` **run direct**, comparing soon just after 1st record be processed.

That's all for now folks.
Feel free if you have any questions.
See you soon.

**Comment by 0bi-w6n-K3nobi** [comment]
I got the last version of github. For this test above looks ok.
Great! I will be some more tests and close this issue.

**Comment by 0bi-w6n-K3nobi** [comment]
Alright. I believe the patch a6e1825 solved all.
Thanks.

**Comment by allinurl** [comment]
Awesome, thanks for testing it out!
