### ISSUE TITLE
separate browser list

### ISSUE THREAD

**Issue by simon1tan** [allinurl/goaccess#1936]
Would it be better to separate out the browser list so users can add their own? It seems more like a configuration than something compiled in the executable. I was looking to add smart speakers into the list.  Also that browsers.list shown in the sample config file seems more like a crawlers.list.

**Comment by allinurl** [comment]
You should be able to add your own to the [**browsers.list**](https://github.com/allinurl/goaccess/blob/master/config/browsers.list). Are you getting an error message?

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
