### ISSUE TITLE
Token '06/Oct/2020:12:39:16' doesn't match specifier '%h'

### ISSUE THREAD

**Issue by DWFLZXJ** [allinurl/goaccess#1937]
just dont know how to fix it 
**command**
LANG="en_US.UTF-8" LC_TIME="en_US.UTF-8" bash -c 'goaccess /opt/access.log -o /usr/local/tomcat/webapps/report.html  --time-format='%H:%M:%S' --date-format='%d/%b/%Y'  --log-format=COMBINED'

**LOGS**
/opt/access.log[0/s]
Parsed 1 linesproducing the following errors:

Token '06/Oct/2020:12:39:16' doesn't match specifier '%h'

Format Errors - Verify your log/date/time format

**Comment by DWFLZXJ** [comment]
done

10/Oct/2020:10:57:41 +0800  ip:port  POST  1.html  2.html  0.036  200  616  0.015  3.html  ip:port  Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; WOW64; Trident/5.0)  -  1550  China  Jiangsu  Nanjing

%d:%^:%^:%^ %^  %h:%^  %m  %r  %^  %T  %s  %^  %T  %R  %^:%^  %u  %^  %^  %^  %^  %^

**Comment by 0bi-w6n-K3nobi** [comment]
My bet:

`%d:%t %^ %h:%^ %m %r %^ %T %s %b %^ %R %^:%^ %u %^`

**notes**
* User-agent will not full parse.
* For complex multi-word field, use double quotes like a
 `.. ip:port  "Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; WOW64; Trident/5.0)" -  ...`
 see more details in manual, section `SPECIFIERS` [here](https://goaccess.io/man).
