### ISSUE TITLE
exclude ip with dynamic ip address

### ISSUE THREAD

**Issue by tellustheguru** [allinurl/goaccess#1941]
I´m using a dynamic ip address on my server with a ddns host address, how do I make it to work with exclude ip?

**Comment by allinurl** [comment]
You can probably use the ip range?

**Comment by tellustheguru** [comment]
No, I will then exclude other guests on that provider, not just me.

**Comment by allinurl** [comment]
I can't think right of another way than the ip range. You could write a script that captures those IPs and keep some sort of db that can be used with goaccess exclude param. I don't think it should be goaccess that keeps track of this, though. 

If you have any ideas, feel free to post them, For now I'm closing this.
