### ISSUE TITLE
Custom log format

### ISSUE THREAD

**Issue by route-print** [allinurl/goaccess#1942]
We use a custom log format that I've been having the hardest time configuring GoAccess to parse. Any help/input would be appreciated.

httpd.conf log format;

LogFormat "\"%{X-Forwarded-For}i\" %v %h %l %u %t \"%r\" %>s %b %D \"%{Referer}i\" \"%{User-Agent}i\"" custom

log output example;

"70.X.X.X, 90.X.X.X" test.host.com 172.X.X.X - - [11/Oct/2020:03:12:03 +0000] "POST /api/rest.php HTTP/1.1" 200 745 229390 "-" "Amazon CloudFront"

**Comment by allinurl** [comment]
This should do it:

    goaccess access.log --log-format='~h{", } %v %^ %^[%d:%t %^] "%r" %s %b %D "%R" "%u"' --date-format=%d/%b/%Y --time-format=%T

**Comment by route-print** [comment]
Thanks!, that did the trick.
