### ISSUE TITLE
Problem with  Apache Custom Log in GoAccess

### ISSUE THREAD

**Issue by Houssem99** [allinurl/goaccess#1943]
Good morning all

I encountered problems with my apache log file on goaccess can you help me please

Format Log :

    Oct 8 11:55:59 server2 server2-access 92.184.124.86 - - [08/Oct/2020:00:00:12 +0200] "GET /wikiTekfor/info/tests.php" 200 6953 "https://wikiTekfor.com" "Mozilla/5.0 (iPhone; CPU iPhone OS 11_2_5 like Mac OS X) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0 Mobile/15D60 Safari/604.1"

Thank you

**Comment by 0bi-w6n-K3nobi** [comment]
My bet:

`--time-format='%H:%M:%S'`
`--date-format='%d/%b/%Y'`
`--log-format='%^ %^ %^ %^ %^ %h %^[%d:%t %^] "%m %U" %s %b  "%R" "%u"'`

into command-line, or in `goaccess.conf`:

`time-format %H:%M:%S`
`date-format %d/%b/%Y`
`log-format %^ %^ %^ %^ %^ %h %^[%d:%t %^] "%m %U" %s %b  "%R" "%u"`

**Comment by allinurl** [comment]
@0bi-w6n-K3nobi should work. You could also try:

    goaccess access.log --log-format='%^:%^ %^ %v %h %^[%d:%t %^] "%m %U" %s %b "%R" "%u"' --date-format=%d/%b/%Y --time-format=%T --http-protocol=no

**Comment by Houssem99** [comment]
Good morning all

Thank you very much, it works 

Thank-you for your prompt response

**Comment by allinurl** [comment]
Glad that worked!
