### ISSUE TITLE
GoAccess hangs with multiple logs

### ISSUE THREAD

**Issue by mimosvk** [allinurl/goaccess#1944]
Hey there! I have multiple logs and I want to create report "merged" and "per file". 
```
### number of lines
# for i in $(ls); do echo "${i} = $(wc -l ${i})"; done
other_vhosts_access.log.1.tmp = 323830
other_vhosts_access.log.1.tmp = 540065
other_vhosts_access.log.1.tmp = 503294
other_vhosts_access.log.1.tmp = 541169
other_vhosts_access.log.1.tmp = 544611
other_vhosts_access.log.1.tmp = 333222
other_vhosts_access.log.1.tmp = 544712
other_vhosts_access.log.1.tmp = 504067
other_vhosts_access.log.1.tmp = 528368
other_vhosts_access.log.1.tmp = 557275
other_vhosts_access.log.1.tmp = 325226
other_vhosts_access.log.1.tmp = 544302
other_vhosts_access.log.1.tmp = 546292
other_vhosts_access.log.1.tmp = 556916
other_vhosts_access.log.1.tmp = 549433
other_vhosts_access.log.1.tmp = 318966
other_vhosts_access.log.1.tmp = 559594
other_vhosts_access.log.1.tmp = 539018
other_vhosts_access.log.1.tmp = 549810
other_vhosts_access.log.1.tmp = 11100
```
Every log is parsed in loop in 10-15 seconds per log with. Without any problem.
```
#!/bin/bash
LOG_LIST="$(find "${APACHE_ACCESS_LOG_BASE_DIR}" -type f | grep '\.tmp$' | sort)"
while IFS= read -r line; do
    LOG_PATH="${line}"
    cat "${LOG_PATH}" | goaccess - -p "${GOACCESS_CONF}" -o "${GOACCESS_LAST_DIR}/${LOG_NAME}.html" -o "${GOACCESS_LAST_DIR}/${LOG_NAME}.csv" -o "${GOACCESS_LAST_DIR}/${LOG_NAME}.json"
done <<< "${LOG_LIST}"
```
But when I want to create one report with all logs I'am not able to.
```
#!/bin/bash
cat ./*.tmp | goaccess - -p "${GOACCESS_CONF}" -o "${GOACCESS_LAST_DIR}/${LOG_NAME}.html" -o "${GOACCESS_LAST_DIR}/${LOG_NAME}.csv" -o "${GOACCESS_LAST_DIR}/${LOG_NAME}.json"
```
I tried merge these files before process ( not working )
```
#!/bin/bash
cat /dev/null > "${LOG_NAME}.log"
for TMP_LOG in $(find ./ -type f -name '*.tmp'); do
     test -f "${TMP_LOG}" && cat "${TMP_LOG}" >> "${LOG_NAME}.log"
done
cat "${LOG_NAME}.log" | goaccess - -p "${GOACCESS_CONF}" -o "${GOACCESS_LAST_DIR}/${LOG_NAME}.html" -o "${GOACCESS_LAST_DIR}/${LOG_NAME}.csv" -o "${GOACCESS_LAST_DIR}/${LOG_NAME}.json"
```
I tried specify by `-f` parameter
```
#!/bin/bash
goaccess -p "${GOACCESS_CONF}" -f (find ./ -type f -name '*.tmp' | tr '\n' ' ') -o "${GOACCESS_LAST_DIR}/${LOG_NAME}.html" -o "${GOACCESS_LAST_DIR}/${LOG_NAME}.csv" -o "${GOACCESS_LAST_DIR}/${LOG_NAME}.json"
```
Nothing works. 
Using GoAccess 1.4 fron Debian / Ubuntu repo.
Thanks for help.

**Comment by 0bi-w6n-K3nobi** [comment]
My bet, in last:

`#!/bin/bash`
`goaccess -p "${GOACCESS_CONF}"  -o "${GOACCESS_LAST_DIR}/${LOG_NAME}.html" -o "${GOACCESS_LAST_DIR}/${LOG_NAME}.csv" -o "${GOACCESS_LAST_DIR}/${LOG_NAME}.json" $(find ./ -type f -name '*.tmp' | tr '\n' ' ')`

You didn't need specify `-f` for several `LOGFILEs` in command-line.

**Comment by 0bi-w6n-K3nobi** [comment]
My 2nd bet:

`#!/bin/bash`
`for LOG_PATH in $(find "${APACHE_ACCESS_LOG_BASE_DIR}" -type f | grep '\.tmp$' | sort)`
`do`
` ` ` ` `cat "${LOG_PATH}"`
`done |  \`
`goaccess - -p "${GOACCESS_CONF}" -o "${GOACCESS_LAST_DIR}/${LOG_NAME}.html" -o ${GOACCESS_LAST_DIR}/${LOG_NAME}.csv" -o "${GOACCESS_LAST_DIR}/${LOG_NAME}.json"`

**Comment by mimosvk** [comment]
I tried with -f in command. No luck. 

--
Best regards
Miroslav KUHAJDA

**Comment by mimosvk** [comment]
Is there any difference between “cat in for loop and pipe to GA” and “merge multiple files to one log and parse that merged log with GA” and “cat ./*.tmp pipe to GA” ?

I have much bigger Nginx logs ( 4M lines ) and have no problem ( parse time 5-10min ). These merged Apache logs ( 2-3M lines in final ) GA parse for 8 hours without any output. Not even in debug log. Only log is “Bye” after Crtl+c. 

I’m stuck for 2 days 😢 .

Thanks. 

--
Best regards
Miroslav KUHAJDA

**Comment by 0bi-w6n-K3nobi** [comment]
No, no difference. Only just alternative to, because no need `concat` for processing.

Ok. `GOACCESS` will be slow downing with increase records' number.
I did say that you **don't have use** `-f`... just put `LOGFILEs` in front, in command-line.

For acelerate, try to:
* disable some `PANELs` with `--ignore-panel=...`;
* use option `-q` | `--no-query-string`;
* use option `--all-static-files`;
* use option `--keep-last=0` to avoid any filter and waiting.

If it still gets slow, try to `concat` a few lines from each file, such as` head -1000 logfile ... `.

**Comment by 0bi-w6n-K3nobi** [comment]
Ok... Can be your `--log-format`...

Do you can put some lines here? And too `--log-format`?

**Comment by mimosvk** [comment]
log example ( classic VHOST Apache2 ) 
```
www.site.com:80 10.133.96.84 - - [13/Oct/2020:00:00:11 +0200] "GET /index.php HTTP/1.1" 200 87911 "-" "monitoring"
www.site.com:80 10.133.96.84 - - [13/Oct/2020:23:59:06 +0200] "GET /site.php HTTP/1.1" 200 2429 "-" "monitoring plugins"
```
config
```
# cat /etc/goaccess/goaccess.apache.conf | egrep '(^log-format|^time-format|^date-format)'
time-format %T
date-format %d/%b/%Y
log-format %v:%^ %h %^[%d:%t %^] "%r" %s %b "%R" "%u"
```
in logs there are local IP 's because these servers are behind Nginx loadbalancer, so this is also in config
```
# enable-panel GEO_LOCATION
ignore-panel GEO_LOCATION
```

**Comment by 0bi-w6n-K3nobi** [comment]
It seems to me that everything is correct.
If its `user-agent` are ever those, therefore add `--ignore-panel=OS` and `--ignore-panel=BROWSERS`.

Ok... Test again with `--keep-last=0` and concat only some lines of each `LOGFILE`. Try something like `head -1000 ...`.

For NGinX with local IP's or LoadBalancer, use real-ip module for resolve it and just will use `%h` field.
See more [here](http://nginx.org/en/docs/http/ngx_http_realip_module.html) and [there](https://docs.nginx.com/nginx/admin-guide/load-balancer/using-proxy-protocol/).

**Comment by allinurl** [comment]
@mimosvk I just ran a test using v1.4 with 5 logs, 1 line each and I was able to output those three reports (json,html,csv). Could you please test this with the minimal conf. e.g.,

    cat *.log | goaccess - --log-format=VCOMBINED -o a.html -o a.json -o a.csv --no-global-config

Please post what output you are getting, a screenshot help too :) 

Feel free to test it out against these 5 attached files.

[2.log](https://github.com/allinurl/goaccess/files/5381796/2.log)
[4.log](https://github.com/allinurl/goaccess/files/5381797/4.log)
[5.log](https://github.com/allinurl/goaccess/files/5381798/5.log)
[3.log](https://github.com/allinurl/goaccess/files/5381799/3.log)
[1.log](https://github.com/allinurl/goaccess/files/5381800/1.log)

**Comment by mimosvk** [comment]
hmmm @allinurl. This works, no config - only command line parameters. Is this better usage ? No config, only command line parameters ?

**Comment by allinurl** [comment]
Can you attach your config file and feel free to post a few lines from your access logs so I can try to replicate what you have there. Thanks.

**Comment by mimosvk** [comment]
config
```
time-format %T
date-format %d/%b/%Y
log-format %v:%^ %h %^[%d:%t %^] "%r" %s %b "%R" "%u"
hl-header true
html-prefs {"theme":"bright","perPage":10,"layout":"vertical","showTables":true}
html-report-title Logs Stats
json-pretty-print true
no-color false
no-column-names false
no-csv-summary false
no-progress true
no-tab-scroll false
with-mouse false
debug-file /var/log/goaccess-debug.log
agent-list true
with-output-resolver false
exclude-ip 188.167.0.1
exclude-ip 207.154.0.1
http-method yes
http-protocol yes
no-query-string false
no-term-resolver false
444-as-404 false
4xx-to-unique-count false
all-static-files false
double-decode false
enable-panel VISITORS
enable-panel REQUESTS
enable-panel REQUESTS_STATIC
enable-panel NOT_FOUND
enable-panel HOSTS
enable-panel OS
enable-panel BROWSERS
enable-panel VISIT_TIMES
enable-panel VIRTUAL_HOSTS
enable-panel REFERRERS
enable-panel REFERRING_SITES
enable-panel KEYPHRASES
enable-panel STATUS_CODES
enable-panel REMOTE_USER
enable-panel CACHE_STATUS
ignore-crawlers false
crawlers-only false
ignore-panel GEO_LOCATION
real-os true
static-file .css
static-file .js
static-file .jpg
static-file .png
static-file .gif
static-file .ico
static-file .jpeg
static-file .pdf
static-file .txt
static-file .csv
static-file .zip
static-file .mp3
static-file .mp4
static-file .mpeg
static-file .mpg
static-file .exe
static-file .swf
static-file .woff
static-file .woff2
static-file .xls
static-file .xlsx
static-file .doc
static-file .docx
static-file .ppt
static-file .pptx
static-file .iso
static-file .gz
static-file .rar
static-file .svg
static-file .bmp
static-file .tar
static-file .tgz
static-file .tiff
static-file .tif
static-file .ttf
static-file .flv
static-file .less
static-file .ac3
static-file .avi
static-file .bz2
static-file .class
static-file .cue
static-file .dae
static-file .dat
static-file .dts
static-file .ejs
static-file .eot
static-file .eps
static-file .img
static-file .jar
static-file .map
static-file .mid
static-file .midi
static-file .mkv
static-file .odp
static-file .ods
static-file .odt
static-file .ogg
static-file .otf
static-file .pict
static-file .pls
static-file .ps
static-file .qt
static-file .rm
static-file .svgz
static-file .wav
static-file .webp
```
I send logs before ... I can't send more logs - I'm not able to anonymize them
```
www.site.com:80 10.133.96.84 - - [13/Oct/2020:00:00:11 +0200] "GET /index.php HTTP/1.1" 200 87911 "-" "monitoring"
www.site.com:80 10.133.96.84 - - [13/Oct/2020:23:59:06 +0200] "GET /site.php HTTP/1.1" 200 2429 "-" "monitoring plugins"
```

**Comment by allinurl** [comment]
Still with your conf works on my end.  

    cat *.log | goaccess - -o a.html -o a.json -o a.csv --no-global-config -p test.conf 

I'm attaching the testing log files. Does that work on your end?
[1.log](https://github.com/allinurl/goaccess/files/5405315/1.log)
[3.log](https://github.com/allinurl/goaccess/files/5405316/3.log)
[4.log](https://github.com/allinurl/goaccess/files/5405317/4.log)
[2.log](https://github.com/allinurl/goaccess/files/5405318/2.log)
[5.log](https://github.com/allinurl/goaccess/files/5405319/5.log)

**Comment by mimosvk** [comment]
It works with my config also, but only with 1/2 or 1/4 of data. I don’t know why. 

With command args everything works. So you may close this issue as “cannot reproduce” or something like that. 

Thanks a lot for help. 

--
Best regards

**Comment by allinurl** [comment]
There may be some lines not matching the format. You could try `--num-tests=0` or you could try specifying VCOMBINED as your log-format in your config file and getting rid of the date & time format variables. e.g.,

```
log-format VCOMBINED
hl-header true
html-prefs {"theme":"bright","perPage":10,"layout":"vertical","showTables":true}
...
```

Closing this. Feel free to reopen it as needed though.
