### ISSUE TITLE
Goaccess Error occurred at: src/parser.c - read_log - 2730

### ISSUE THREAD

**Issue by andrgayday** [allinurl/goaccess#1948]
Good day!
I am getting an error when executing the command:

$ zcat /var/log/nginx/access.log.*.gz | goaccess /var/log/nginx/access.log --log-format=COMBINED

GoAccess - version 1.4 - Oct 19 2020 14:08:20
Config file: /usr/local/etc/goaccess/goaccess.conf

Fatal error has occurred
Error occurred at: src/parser.c - read_log - 2730
Unable to open the specified log file. Permission denied

I work with DJANGO and I have failed to implement real-time statistics export.
Therefore, I implemented the export of the report through a script, but when the script is executed, the statistics are displayed for one day.  And I need to display statistics since the start of the web server.

**Comment by 0bi-w6n-K3nobi** [comment]
Hi.
I hope that message is clear. Or not? **`"...  Permission denied"`**
Your user need permission for read the `LOG`.

I should too add character **`-`** for read from `PIPE`. I.E:

 `zcat /var/log/nginx/access.log.*.gz | goaccess`**`-`**`/var/log/nginx/access.log --log-format=COMBINED`

**Comment by andrgayday** [comment]
Problem solved! I changed the permissions on the log file.
Many thanks!
