### ISSUE TITLE
Detailed export ? HTML / CSV / JSON

### ISSUE THREAD

**Issue by googleanalyticsresoneo** [allinurl/goaccess#195]
Hi

I can't figure out how to export _all the rows from each detailed reports_, which are available in the interactive GUI, into HTML reports (it stays limited to the top10 rowson each report)
Do CSV and JSON reports behave the same ?

Is there an option for that ?
Or is just unavailable ?

Thanks for your attention

**Comment by dawapaljor** [comment]
@allinurl  I can see json export from the html output panel. But I can't find the CSV export options.. Please how can we do that. Thanks @

**Comment by mark-chief** [comment]
> @allinurl I can see json export from the html output panel. But I can't find the CSV export options.. Please how can we do that. Thanks @

Me too.. any idea?
