### ISSUE TITLE
How are visitors calculated?

### ISSUE THREAD

**Issue by JeffJefferson-dot** [allinurl/goaccess#1954]
Hello,

Title says it all really, under the `Visitor Hostnames and IPs` tab within the WebUI, how are "Visitors" calculated?
The image below sort of sums up my issue. The top request is illegitimate, and the other two are legitimate users.
![image](https://user-images.githubusercontent.com/74031345/98317402-597faf00-1fd4-11eb-9294-fb71ea4b29cb.png)

I'm attempting to isolate how visitors are calculated so that I can set up some sort of Nginx rule to block IP addresses that have more than say, 10 visitors.

Thanks for the help!

**Comment by allinurl** [comment]
Currently the way the visitors count works is by generating a unique key composed of `IP/date/UA` done by the `get_uniq_visitor_key()` function. Then each panel creates its own unique key based on at least one metric (the data field).

For instance, the visitors panel uses `gen_visitor_key()`. This key is then appended to the IP/date/UA key which produces the unique count per unique data metric.

**Comment by allinurl** [comment]
Can I ask how many days span the dataset?  For instance, if your dataset/log spans only one date, then I would say that the single IP with the count of 1728 visitors used different user agents. Let me know if that helps.

**Comment by JeffJefferson-dot** [comment]
Logs are rotated every 24 hours, so Goaccess is only analyzing 24 hours worth of access logs.

**Comment by JeffJefferson-dot** [comment]
I suppose there is no way for me to block requests from IP addresses that switch UA frequently? (I know this is somewhat off topic, thanks for the clarification though)

**Comment by allinurl** [comment]
I see. So yeah, I'd say the IP is using multiple agents in that one day. You can take a look at the agents by passing `-a`. It will show the first 10 agents (HTML report), and a lot more on the terminal output (by pressing enter on top of IP). 

Depending on the type of traffic, you could make the assumption that if an IP has a lot visitors (reaches some threshold) and your log rotates daily, then mark it as suspicious and block it. However, I'd be cautions just because a valid IP could be NAT'd where a lot of clients are going out with the same IP, but again, this will depend on your traffic/clients.

**Comment by JeffJefferson-dot** [comment]
That sounds about right, I would probably have to do this all manually, as I'm not aware of any tools that can analyze my access logs that deeply AND take some kind of action based on thresholds.

**Comment by allinurl** [comment]
I don't recall if somebody opened a request to execute commands on an IP but feel free to open a new issue so I can take a look at it, I think it would be pretty nifty and convenient.

For now, you could do it manually or even better, you could output a JSON report (along the HTML) and parse that specific panel's data. I think a bash script with some tools like `jq` shouldn't be too bad to implement.

**Comment by JeffJefferson-dot** [comment]
Thanks for that, I appreciate the insights and ideas, I'll take a look at opening an issue now.

**Comment by JeffJefferson-dot** [comment]
Oops, I meant to ask what info you'd need from me for that new issue?

**Comment by allinurl** [comment]
I think #1175 may be the one I'm thinking. If you could please add to that issue that along the alert, trigger/take some kind of action based on thresholds would be great, just so I don't forget :)
