### ISSUE TITLE
Issue processing multiple logs in real-time in version 1.4.1

### ISSUE THREAD

**Issue by 0bi-w6n-K3nobi** [allinurl/goaccess#1958]
Hi @allinurl .

I have deployed the new version **1.4.1** on my servers.
Just **yesterday**, I had to do some statistics for a new partner. And everything was ok, for statistical `LOGs`.

_The good, the bad and the ugly_

However, this morning I checked the statistics for my sites in real-time.
In all instances, I was **overloaded** to run GoAccess. 
What used to be only **40%** of  `CPU` processing in previous version, today is around **100%**.
The only **exception** was the WordPress instance, which has **only 1** `LOG`.

So, I found the **prank**, in the code below:
```
static void
perform_tail_follow (uint64_t * size1, const char *fn) {
...
  len = MIN (glog->snippetlen, size2);
  if ((fread (buf, len, 1, fp)) != 1 && ferror (fp))
    FATAL ("Unable to fread the specified log file '%s'", fn);

  if (glog->snippet[0] != '\0' && buf[0] != '\0' && memcmp (glog->snippet, buf, len) != 0)
    *size1 = glog->bytes = 0;
```
The code looks ok. But, wait...
There is only **one** variable/value `glog-> snippet` and I have **4** `LOGs` for real-time processing.

Therefore, GoAccess will **continue** processing the **last** `LOG`.
But for the **other 3** `LOGs` it will always reprocess **from** the **beginning**.
As I write here, my sites are registering more than **600 million** requests for each. My Gosh.

The problem does **not occur** for the processing of the `LOGs` in non-real-time, because the `read_log` routine calls `set_initial_persisted_data` ~~after each record~~ for each `LOG`, before process them.
The same does not happen in `perform_tail_follow` and therefore `glog-> snippet` has the value of only the last `LOG`.
And so, the behaviour will be **ok** if you have **only 1** LOG.

I hope I was clear. :)

**Comment by allinurl** [comment]
Hello @0bi-w6n-K3nobi I completely missed that on my test. Thanks a lot for looking into this. I'll work on a fix and post back asap.

**Comment by 0bi-w6n-K3nobi** [comment]
Hi @allinurl .

Perhaps it is time to think about individualized flags, by `LOG`, even in `HASH` like in the `ht_insert_last_parse` function.
Something similar, like the `glob->filesizes` variable
These **would be**: # of line, size, snippet, inode.

This may also make it **easier** to convert GoAccess to **multi-thread**.

**Comment by 0bi-w6n-K3nobi** [comment]
PS:

**Comment by 0bi-w6n-K3nobi** [comment]
Good afternoon, @allinurl .

It seems to me that the `fgets` function will **never** fail or return `EOF`, if you use `PIPE` as an input.
We are **assuming** that the input is via an **active** `LOG`, using the `tail -F` command, which it will **never end**.
So, the processing of requests had **never left the loop** in the `read_log` function. This is the problem in the case of real-time.

**Comment by allinurl** [comment]
Hello @0bi-w6n-K3nobi I'm not sure I follow, I see the point you made regarding the snippet on multiple files. Are you now seeing some issues with data coming from stdin? How are you running goaccess so I can try to reproduce this. Thanks

**Comment by 0bi-w6n-K3nobi** [comment]
Hello @allinurl 

Firstly, I was running with 4 LOGs, like as:

`goaccess LOG-a LOG-b LOG-c LOG-d`.

Then, I found the problem with snippet. 
So, I tried fix using `TAIL` and `PIPE` input.
And I found 2nd problem, comming with `stdin`/`PIPE` like I describe above.

So sorry, man.... :)

**Comment by allinurl** [comment]
so just to be sure, e.g.,

    tail -f access.log -f access.1.log | goaccess - --real-time-html -o report.html

**Comment by 0bi-w6n-K3nobi** [comment]
Yeah... 
With 1, 2 or more LOGs.... The problem is same.

**Comment by allinurl** [comment]
Are you able to reproduce this in v1.4? I don't think that code changed.

**Comment by allinurl** [comment]
Specifically tailing from pipe/stdin.

**Comment by 0bi-w6n-K3nobi** [comment]
Yeah... So weird.

My server is CentOS8. Here, in my home is Fedora31.
In Server is problem. Here maybe ok.

**Comment by 0bi-w6n-K3nobi** [comment]
Yeah... 

In CentOS8 is the problem.

**Comment by 0bi-w6n-K3nobi** [comment]
Hello @allinurl .

The difference is behaviour of `fgets`, reading from `STDIN`:

`Fedora31`: return `NULL`, and set errno == `EAGAIN` == [11]
`CentOS8`: block wait to read and not return

That it.

**Comment by allinurl** [comment]
Interesting... Thanks for checking that out. Do you get the same behavior if you build with `--with-getline`?

**Comment by 0bi-w6n-K3nobi** [comment]
Man, so hard here.

Yeah, It's default for Fedora/CentOS package is with `--with-getline`.

I found!!!
The problem was I ever running into `SCREEN` section.
I ever create a new window/term and then change to `root` and after to `goaccess` user.

In normal case, I ever running GoAccess in `Service` at `SystemD`.
But, today I used the terminal. And it owner is my user, and not `goaccess` user.
Debugging here, I found than `open (term, O_RDONLY)` failed into `open_term`, because of user permission.
So, code into `set_pipe_stdin` wasn't running and not add `O_NONBLOCK` flag to `STDIN`.

... my Gosh ...
Well, sorry... It was my fault.
But, stay here the note: user **must** be open **term permission**.

See later.

**Comment by allinurl** [comment]
@0bi-w6n-K3nobi Could you please try building from upstream? It should address this issue. Also, it should align the code better to multithread multiple logs. Let me know. Thanks

**Comment by allinurl** [comment]
By the way, the latest changes should fix as well some issues when trying to read from stdin without using the `-`.

**Comment by 0bi-w6n-K3nobi** [comment]
Hi @allinurl 

I so busy because elections . But I will soon as possible.

Thanks :)

**Comment by 0bi-w6n-K3nobi** [comment]
Great. 
It seems to me that you made good/great changes.

Yeah. I believe you are one step away from multi-thread.
I'm busy now, but I will test the code as soon as possible.

**Comment by 0bi-w6n-K3nobi** [comment]
Yeah.
It seems to me that you deploy very good changes here.

I did see very strange code ... at least I did think with my self :
```
Logs *
init_logs (int size) {
...
  for (i = 0; i < size; ++i) {
...
    logs->processed = &(glog[i].processed);
    logs->filename = glog[i].filename;
```
I didn't believe that you can be made very simple mistake...
And so I did see the code at `set_log_processing`... and I breathed a sigh of relief.

I believe that you found a very nice solution. I would take longer for think the same.

**Comment by allinurl** [comment]
Awesome, thank you sir! I pushed out a few more changes. I'll be releasing v1.4.2 this week. I appreciate your help!

**Comment by 0bi-w6n-K3nobi** [comment]
I know that behaviour is almost the same... 
But you changed intensely internal structs... 
So... Do you sure than be 1.4.2 and not 1.5?

**Comment by allinurl** [comment]
Great point! I'm making it 1.4.2 just so we enter 1.5 with a stable release.

**Comment by 0bi-w6n-K3nobi** [comment]
Hi @allinurl ... Good morning.
First test, all right.

I used my `LOGs` of the old problem with `PIPE` entry.
First, in order with `--persist` and `--restore`. So I ran again changing the order of the `LOGs`.
I did it several times, each in a different order. All right.
That was the idea: save `HASH` with the line counter **individually** for each `LOG`.

I noticed that you have modified/improved the processing information. Nice! 
I also noticed that the processing time accumulates. Good job.

See you!

**Comment by 0bi-w6n-K3nobi** [comment]
Second test -- `PIPE` input.

Everything ok here, too.
Only 2 reservations:
* the number of unique visitors differs slightly -- 104,588 vs 104,603 - I had already noted in the previous version.
* if the entry is like `cat log-a log-b log-c ...`, the last log **must** have the **greatest** timestamp in the **last** record.

The latter case is comparable to having an unordered `LOG`.
If this occurs, and if you reprocess the input then run the risk of reprocessing some requests -- **where** the timestamp is **greater** than the timestamp of the last record.
We return here to the subject about the `--ordered-timestamp` flag.

A workaround/**solution** for this would be to **find** the **largest** timestamp of all requests and **set** this value in `HASH`, when **saving** to disk.

**Comment by 0bi-w6n-K3nobi** [comment]
**PS:**
I think it would be possible to adjust the `LOG Size` field, creating a function for this - in the case of the `PIPE` input.

**Comment by 0bi-w6n-K3nobi** [comment]
Third test -- real-time.

Everything seems ok here.
I also tested the `MIME` panel. I will use it in the future as it is important to count requests by type.

**Comment by 0bi-w6n-K3nobi** [comment]
Fourth test -- `--persit` and `--restore` with CLang Address Sanitizer.

I did the test by loading and saving, and processing each log at a time.
Then, all the `LOGs` in different orders.
Everything ok, so far -- no leaks and correct count of requests.

However I found some minor problems, which do not affect the result:
* The `LOG Size` field does not accumulate the values -- it only shows the size of the last one processed -- I believe that the sum would be correct, like a `Init. Proc. Time` field -- maybe not count the ignored records;
* Again, # of unique visitors differs slightly;

I believe that below is a problem, only that it does not affect the result:

The `SETTING UP STORAGE` message time increases with the size of the `LOG` after processed that.
After processing a large `LOG` -- about 1 million of requests -- the time goes up to 35 seconds, for each new restore.
I made sure it is not an `I/O` problem by changing `--db-path` to a directory on top of `/dev/shm`, i.e. everything in memory.
Rebuilding GoAccess with the normal options, i.e. gcc compiler, that time is around 9 seconds.

In summary, we have the table below -- with 34 differents `LOGs`:
```
time        processed LOG(s)   restore+save   Compiler
----        ----------------   ------------   ------
00:01:42    all at once            ---        Gcc normal options
00:07:03    one by one            ~  9s
00:07:36    all at once            ---        CLang with Address Sanitizer
00:32:05    one by one            ~ 43s
```
The `LOGs` were processed from the largest to the smallest.
If we invert and process from the smallest to the largest, we have:
```
time        processed LOG(s)   Compiler
----        ----------------   ------
00:01:46    one by one         Gcc normal options
00:07:39    one by one         CLang with Address Sanitizer
```
I may be mistaken, and it may just be a lack of optimization.
The time taken to save is always small, so the restore time increases.

In the next test, I will check if there are any leaks in real-time processing.

See you later!

**Comment by allinurl** [comment]
@0bi-w6n-K3nobi Thanks for these testings. Like you said, for unordered logs, having a flag like `--ordered-timestamp` should help the user. Just to be clear, this flag would only compare to the largest timestamp we have parsed, and without it would not take the timestamp into account upon restoring, correct?

Regarding the restore time,  the `SETTING UP STORAGE` essentially indicates that it's loading data from disk so my assumption is that the larger the log, the longer it will take, but I feel like I'm misinterpreting your message. Please let me know if that's not what you meant.

**Comment by 0bi-w6n-K3nobi** [comment]
Hi @allinurl 

I don't know if I expressed myself well.

The `--ordered-timestamp` flag is that, but it has an additional, when we use the `--persist` option.
Beyond to the comparison, we would have to retain and save the **largest** timestamp of the **processed** `LOG` to HASH on the **disk**.
We already mentioned it extensively in question #1945.

The solution I see/tell here, for the `PIPE` input, is **also** to save this timestamp.
Certainly when the user uses the `PIPE` input, he will use more than one file, and then we will have the problem that I mentioned above -- the **last** `LOG` may **not have** in its last line the **biggest** timestamp of **all** the processed `LOGs`.
If we **reprocess**, i.e. run with same `LOGs`, then we can run the **risk of** reprocessing some requets.

The second part, when you say "it's loading data from disk", I understand that you meant:
it **already** loaded the disk -- yeah, I'm using `/dev/shm` -- and GoAccess is decompressing and **making it useful** information to be able to use it.

Here, I would like to be as optimistic as you are.
The program uses only 4096 bytes as a snipplet size. Only 1 of my LOGs is less than that.
So, **whether** the `LOG` is large or small, the `HASH` load time **should be** practically the same.
Therefore, there should be no difference between processing the `LOGs` from the smallest to the largest, and the opposite.
And the values ​​9s and 43s? Aren't they huge for you? Just for unzip and load `HASH` into memory ...

**PS:**
I meant in:
```
all at once    goacess --persist --restore LOG-01 LOG-02 .. LOG-34

one by one     goaccess --persist --restore LOG-01
               goaccess --persist --restore LOG-02
                        ....           ...
               goaccess --persist --restore LOG-34
```

I hope I spoke more simply...  I see you later!

**Comment by 0bi-w6n-K3nobi** [comment]
My fault... 
I forget the data from each `LOG` that `GOACCESS` saves beyond the `HASH`.

My Gosh.
A thousand pardons for that.
