### ISSUE TITLE
Alpine (not alpine docker) package configured with Geoip Legacy

### ISSUE THREAD

**Issue by rhanka** [allinurl/goaccess#1960]
Would it be possible to enable mmdb support by default in the alpine package ?

https://build.alpinelinux.org/buildlogs/build-edge-x86/main/goaccess/goaccess-1.4.1-r0.log

It seems now to be the easier to get a mmdb up to date format, isn't it ?

**Comment by allinurl** [comment]
Great question. I think you will need to submit a request in the alpine ports [**repo**](https://github.com/alpinelinux/aports/blob/2b71a295e3a0b9653bce5e9006fac92cbef1513f/main/goaccess/APKBUILD). Let me know how it goes.
