### ISSUE TITLE
Error in Parsing GeoIP2 Databases After Upgrade

### ISSUE THREAD

**Issue by bnkas** [allinurl/goaccess#1965]
Hello,

I am running Debian 10 server with GoAccess installed via the official Debian/Ubuntu Repository (deb.goaccess.io).

GoAccess was installed and running well for months. I very recently did an upgrade to version 1.4.1 and I immediately noticed this error when parsing log files:

`Error Traversing Database for ipnum = <num> - Perhaps database is corrupt?`

I have been using GeoIP2 dbip-city-lite.mmdb for months without issues. I pulled the most recent version of the database and replaced the old one, but I still encounter the same error. I also re-installed GoAccess and used the most recent config file template, but that made no difference. 

Any idea on what might have happened? Or how I can troubleshoot the issue further?

Thanks.

**Comment by allinurl** [comment]
Thanks for reporting this. My bad. I think this is a regression introduced in #1918 - essentially was to package goaccess with legacy geoip on buster — v1.4.2 is going out this week. For now, you could try using one of the db files from https://github.com/allinurl/goaccess/blob/master/config/goaccess.conf#L668.

@fancsali, before I revert this and build v1.4.2 with mmdb, could you please explain the reason behind using legacy on debian 10? Thanks.

**Comment by bnkas** [comment]
@allinurl Excellent and thank you for the speedy reply. I will hold out for the upgraded version to fix the issue as IP location is not critical for my needs at this point. Thanks again.

**Comment by allinurl** [comment]
v1.4.2 was built with mmdb per #1965. Here are the available packages.

```
goaccess |  1:1.4.2-xenial |  xenial | amd64, i386
goaccess |  1:1.4.2-bionic |  bionic | amd64
goaccess |    1:1.4.2-eoan |    eoan | amd64
goaccess |   1:1.4.2-focal |   focal | amd64
goaccess | 1:1.4.2-stretch | stretch | amd64, i386
goaccess |  2:1.4.2-buster |  buster | amd64, i386
```
