### ISSUE TITLE
bug in TLS parsing

### ISSUE THREAD

**Issue by petrkutalek** [allinurl/goaccess#1967]
https://github.com/allinurl/goaccess/blob/9e4b7cf14e92f808b816c8c300331f2ae132b22f/src/parser.c#L1418

Should be probably
```C
    if (!(tkn = parse_string (&(*str), end, 1)))
```

Current implementation creates 
![screenshot_20201116_184618_cutout](https://user-images.githubusercontent.com/42769564/99288769-65713980-283c-11eb-80c8-90855c419218.png)

**Comment by allinurl** [comment]
Good point there. Are you saying because the specifiers could be in two separate positions and not necessarily next to each other?

**Comment by petrkutalek** [comment]
Would not be better to use a format with slash `TLSv1.2/ECDHE-ECDSA-AES128-GCM-SHA256` instead of two strings `"TLSv1.2 ECDHE-ECDSA-AES128-GCM-SHA256"`? Alternatively you could define two keys for both the TLS protocol and the cipher to parse any format customers would like to use.

**Comment by allinurl** [comment]
Pushed a commit to address this. Note that this changes a bit how it parses the TLS version and the Cypher so it gives more flexibility in case the fields are not next to each other. 

You will need to specify now `%K` for the TLS version and `%k` for the cypher. Feel free to test it out by building from [**development**](https://github.com/allinurl/goaccess#build-from-github-development). It will be pushed out in v1.4.3.

**Comment by allinurl** [comment]
By the way, thanks for reporting it!
