### ISSUE TITLE
How to parse custom user-agent ?

### ISSUE THREAD

**Issue by Theadri1900** [allinurl/goaccess#1968]
Hi,
sorry in advance if I don't ask my question in the right place. Google was unable to answer my question.
I wanted to know how I could integrate new custom user-agent into the current browser list.
Indeed, for my projects (mobile application), the user-agent used is specific to the application. So I would like to be able to know the proportion of people who use my application as a browser.

Sincerely,

**Comment by allinurl** [comment]
Great question. You can add your user agent to [**this list**](https://github.com/allinurl/goaccess/blob/master/config/browsers.list). Usually this is located under `%sysconfdir%` where `%sysconfdir%` is either `/etc/`, `/usr/etc/` or `/usr/local/etc/`

Or you could specify one with `--browsers-file=/path/browsers.list`.

Let me know if that helps.

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.

**Comment by madusehat** [comment]
bisa kunjungi [agen8](https://heylink.me/agent8slot)
