### ISSUE TITLE
Goaccess live-html-report returns JSON only

### ISSUE THREAD

**Issue by hadran9** [allinurl/goaccess#1969]
Hello everyone, so I'm new to goaccess, And now I'm using it with html-report and I'm loving it, so now what I want is to use `live-html-report` but I don't get the idea why I'm receiving only JSON data on the websocket or Is that how's the server is supposed to work ?

so my command is : `goaccess -f access.log --log-format=COMBINED --time-format=%T --date-format=%d/%b/%Y --live-html-report --port=9870`

And my HTML client code that receives data from the websocket is : 

`<!DOCTYPE html>`
`<html lang="en">`
`<script>`
`window.onload = function() {`
`    function $(selector) {`
`        return document.querySelector(selector);`
`    }`
`    var socket = new WebSocket('ws://localhost:9870');`
`    socket.onopen = function(event) {`
`        $('#messages').innerHTML = 'Connected<br>';`
`    };`
`    socket.onmessage = function(event) {`
`        $('#messages').innerHTML += event.data + '<br>';`
`    };`
`    socket.onclose = function(event) {`
`        $('#messages').innerHTML = 'Disconnected ' + event.reason;`
`    };`
`};`
`</script>`

`<div id="page-wrapper">`
`    <pre id="messages">Connecting...</pre>`
`</div>`

**So once I'm connected with the websocket, the data that I receive is only JSON and the output is like this :** 

`{`
`	"general": {`
`		"start_date": "14/Jun/2020",`
`		"end_date": "20/Nov/2020",`
`		"date_time": "2020-11-21 11:09:42 +0100",`
`		"total_requests": 23614,`
`		"valid_requests": 23614,`
`		"failed_requests": 0,`
`		"generation_time": 3,`
`		"unique_visitors": 519,`
`		"unique_files": 1830,`
`		"excluded_hits": 0,`
`		"unique_referrers": 2089,`
`		"unique_not_found": 20,`
`		"unique_static_files": 323,`
`		"log_size": 5320508,`
`		"bandwidth": 1649885575,`
`		"log_path": [`
`			*************`
`		]`
`	},`
`	"visitors": {`
`		"metadata": {`
`			"bytes": {`
`				"total": {`
`					"value": 1649885575`
`				},`
`				"avg": {`
`					"value": 36664124,`
`					"percent": "2.22"`
`				},`
`				"max": {`
`					"value": 1472808017,`
`					"percent": "89.27"`
`				},`
`				"min": {`
`					"value": 10906,`
`					"percent": "0.00"`
`				}`
`			},`
`.....`

And What I want is, Instead of sending only the parsed data as JSON over the websocket, I want to send the full HTML report (with it's HTML, CSS And Java Script) like when I'm generating a static one using the command `goaccess access.log -a > report.html`.

**So my question is, is there's any way to send the full HTML report over the websocket ?**

Also if there's any enhancement on the HTML client code that accepts data from the websocket I would also love it.

**Comment by allinurl** [comment]
Hello, it should be `--real-time-html` and the output file. e.g.,

    goaccess access.log --real-time-html -o report.html --log-format=COMBINED --port=9870

**Comment by hadran9** [comment]
Thanks for your answer, even with this method it's still sends me data as **JSON**. And FYI, I have a configuration file that I'm using when I'm outputting a static HTML report which contains the following:

```
date-format %d/%b/%Y 
time-format %T
log-format COMBINED
log-file access.log
geoip-database GeoLite2-City.mmdb
color-scheme 3
config-dialog false
hl-header true
html-prefs {"theme":"bright","perPage":20,"layout":"horizontal","showTables":true,"visitors":{"plot":{"chartType":"bar"}}}
html-report-title Statistics
real-os true
agent-list true
output output\report.html
```


And I even tried to use this configuration file with `--real-time-html` but still no luck.

**Comment by allinurl** [comment]
Could you please post a screenshot of what you are getting when opening the report.html file?

**Comment by hadran9** [comment]
Yeah Yeah of course, sorry for not posting one from the start.

Here's my configuration file and when I'm starting **goaccess** with the conf file:

![Capture-101](https://user-images.githubusercontent.com/65096377/99942183-802d3c00-2d6f-11eb-8092-e37137f0f4fe.jpg)

And here is when I'm starting **goaccess** with in-line parameters : 

![Capture-102](https://user-images.githubusercontent.com/65096377/99943433-96d49280-2d71-11eb-989a-c77d935ee1d1.jpg)

Either ways I'm using to start **goaccess**  with `--real-time-html` I'm getting the same output on the browser, but tbh sometimes when I'm starting it with the conf file( the same conf file in the picture above ) I get disconnected directly once I get connected.

And here's my output on the browser when it's working:

![Capture-103](https://user-images.githubusercontent.com/65096377/99942173-7c99b500-2d6f-11eb-91c2-bf3f2cb54ade.jpg)

A closer look:

![Capture-104](https://user-images.githubusercontent.com/65096377/99942165-7a375b00-2d6f-11eb-916a-20437980e5f7.jpg)

And here's my source code : 

![Capture-105](https://user-images.githubusercontent.com/65096377/99942138-71df2000-2d6f-11eb-95d6-daaa4ce861d0.jpg)

I even tried to change the line 8 on the HTML file which contains the following Javascript instruction : `    var socket = new WebSocket('ws://localhost:9870/report.html');`  and tried to remove the **report.html** from the websocket address and I'll have the following :  `    var socket = new WebSocket('ws://localhost:9870');`  but still no luck.

But after you've said : 
> Could you please post a screenshot of what you are getting when opening the report.html file?

I did take a look on the `report.html` directly from the hard-drive and when I refresh the page, the file actually does change (Take a look at the **last time updated** in both pictures): 

![Capture-106](https://user-images.githubusercontent.com/65096377/99946199-43187800-2d76-11eb-907f-c48cbfe03d93.jpg)

![Capture-107](https://user-images.githubusercontent.com/65096377/99946193-3f84f100-2d76-11eb-83ad-2a42101f87fc.jpg)

And last but not least, I even tried with **gwsocket** and I always get data in JSON format. 

**So my question is, is there's any way to send the full `report.html` over the websocket.**

FYI, I'm working at the moment with **Windows 10** And **MSYS** And I've compiled all the sources, which means I didn't download any pre-built binary release, And **gwsocket** is working normally without any errors and it's working like a charm when I'm outputting a static HTML report.

And finally thank you so much for your time and efforts.

**Comment by allinurl** [comment]
Sorry, I misread your question. Yes, the websocket server in goaccess will only output JSON data. You can't get HTML. Is there any particular reason why you want to get HTML code? JSON should give you a lot more flexibility to build whatever you are looking for with the data.

**Comment by hadran9** [comment]
> JSON should give you a lot more flexibility to build whatever you are looking for with the data.

Yes exactly, Thanks a lot for your time.
