### ISSUE TITLE
logfile format

### ISSUE THREAD

**Issue by altneuland** [allinurl/goaccess#1973]
would you be so kind to convert this logfile format into your code? Thank you very much! 

178.115.129.47.wireless.dyn.drei.com - - [29/Nov/2020:12:59:39 +0100] "GET /wp-includes/images/w-logo-blue-white-bg.png HTTP/1.1" 200 4119 "http://www.bauer.at/?fbclid=IwAR1UJ4YXbY337I7xZs3yxbSE4_0P9Ltmr88E6qcG4lv9M1ahz1GkqZqAtmQ" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36"
84-113-182-27.cable.dynamic.surfer.at - - [29/Nov/2020:12:59:39 +0100] "GET /wp-includes/js/wp-emoji-release.min.js?ver=5.5.3 HTTP/1.1" 200 4721 "http://www.bauer.at/" "Mozilla/5.0 (Linux; Android 6.0.1; SM-G389F Build/MMB29K; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/86.0.4240.185 Mobile Safari/537.36 [FB_IAB/FB4A;FBAV/295.0.0.36.119;]"
194-166-199-225.adsl.highway.telekom.at - - [29/Nov/2020:12:59:38 +0100] "GET /wp-content/uploads/2020/11/4dc4324a-abde-4db8-9da2-24941326030e-768x576.jpg HTTP/1.1" 200 111694 "http://www.bauer.at/seine-liebe-die-alm/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:83.0) Gecko/20100101 Firefox/83.0"
217-149-174-41.nat.highway.telekom.at - - [29/Nov/2020:12:59:34 +0100] "GET /?fbclid=IwAR3ehhesaXSfMLxMMk27mpOV1JhhPF7SkPxcI14GUE1AlTDwvJNtyz1GX3Y HTTP/1.1" 200 36527 "-" "Mozilla/5.0 (Android 10; Mobile; rv:83.0) Gecko/83.0 Firefox/83.0"
089144197042.atnat0006.highway.a1.net - - [29/Nov/2020:12:59:20 +0100] "GET / HTTP/1.1" 301 - "https://t.co/BsPICk9EdR?amp=1" "Mozilla/5.0 (iPhone; CPU iPhone OS 14_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.1 Mobile/15E148 Safari/604.1"

**Comment by 0bi-w6n-K3nobi** [comment]
Hi @altneuland 

on the manual page you find the quote:

**Comment by altneuland** [comment]
thanks for the quick reaction but what quote? I followed this advice:
If you are unsure, please feel free to open a new issue on Github and post a few sample lines from your access log.

**Comment by 0bi-w6n-K3nobi** [comment]
My fault.
Read again the post. I change it.

**Comment by altneuland** [comment]
Big thanks, will try it right away.
