### ISSUE TITLE
Real-time report shows way too many hits

### ISSUE THREAD

**Issue by stephenwade** [allinurl/goaccess#1974]
When GoAccess is first started, the real-time report behaves correctly. However, after a day or two (I assume the issue is triggered by logrotate), each hit starts counting as multiple hits. For example, right now every time I `curl` my home page, the "hits" count on the real-time report increases by 26.

![A GIF demonstrating the issue](https://user-images.githubusercontent.com/4148577/100684495-721b8480-3348-11eb-83af-a6df82b07f50.gif)

GoAccess version: 1.4.2

<details>
<summary>SystemD unit file</summary>

```
[Unit]
Description=GoAccess stephenwade.me
Requires=network-online.target apache2.service
After=network-online.target apache2.service

[Service]
Type=simple
Restart=always

ExecStart=/usr/local/bin/goaccess-stephenwade.me.sh
ExecStop=/bin/kill -INT $MAINPID

[Install]
WantedBy=multi-user.target
```
</details>

<details>
<summary>goaccess-stephenwade.me.sh</summary>

```bash
#!/bin/bash
/usr/bin/goaccess \
    /var/log/apache2/stephenwade.me_access.log \
    -o /var/www/stephenwade.me/goaccess/index.html \
    --log-format=COMBINED --real-time-html --port=8625 \
    --ssl-cert=/etc/letsencrypt/live/stephenwade.me/fullchain.pem \
    --ssl-key=/etc/letsencrypt/live/stephenwade.me/privkey.pem \
    --html-report-title='stephenwade.me Server Statistics' --html-prefs='{"theme": "darkBlue"}'
```
</details>

**Comment by allinurl** [comment]
Thank you for reporting this. I just noticed this as well. Like you said, it seems related to log rotation. I'll work on reproducing this on my end and submit a fix asap.

**Comment by allinurl** [comment]
BTW, it seems like restarting goaccess solves the issue. Is that the case on your end?

**Comment by stephenwade** [comment]
Yes, that's correct. Restarting fixes the issue for me.

**Comment by allinurl** [comment]
I pushed a fix for this. I'll deploy pretty soon a minor release. Feel free to test it out by building from [**development**](https://github.com/allinurl/goaccess#build-from-github-development).

Again, thank a lot for reporting it!
