### ISSUE TITLE
How to determine response time from Apache logs.

### ISSUE THREAD

**Issue by erikfrangez** [allinurl/goaccess#1977]
Hello.

Our logs from apache are next:

```
109.182.228.221 - - [10/Dec/2020:06:25:24 +0100] "GET /notes/index.php?filtertype=course&filterselect=12628 HTTP/1.1" 200 25079 "https://estudij.um.si/user/view.php?id=6754&course=12628" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36 Edg/87.0.664.57"
109.182.228.221 - - [10/Dec/2020:06:25:26 +0100] "POST /lib/ajax/service.php?sesskey=J6YCq4zv9R&info=core_fetch_notifications HTTP/1.1" 200 376 "https://estudij.um.si/notes/index.php?filtertype=course&filterselect=12628" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36 Edg/87.0.664.57"
109.182.228.221 - - [10/Dec/2020:06:25:32 +0100] "POST /lib/ajax/service.php?sesskey=J6YCq4zv9R&info=core_fetch_notifications HTTP/1.1" 200 7187 "https://estudij.um.si/user/view.php?id=6754&course=12628" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36 Edg/87.0.664.57"
109.182.228.221 - - [10/Dec/2020:06:25:37 +0100] "GET /user/index.php?id=12628 HTTP/1.1" 200 34901 "https://estudij.um.si/user/view.php?id=6754&course=12628" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36 Edg/87.0.664.57"
109.182.228.221 - - [10/Dec/2020:06:25:38 +0100] "POST /lib/ajax/service.php?sesskey=J6YCq4zv9R&info=core_fetch_notifications HTTP/1.1" 200 376 "https://estudij.um.si/user/index.php?id=12628" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36 Edg/87.0.664.57"
```

We would like to extend data in goaccess and log more data, including response time of Apache. Can you please help us? 

Thank you!

Best

**Comment by allinurl** [comment]
You will need to modify your apache2.conf, usually located under /etc/apache2/apache2.conf and add `%D` to your current format. e.g.,

    LogFormat "%h %l %u %t \"%r\" %>s %O \"%{Referer}i\" \"%{User-Agent}i\" %D" combined

then restart apache, e.g.,

    # systemctl restart apache2

Then use this in goaccess

    goaccess access.log --log-format='%h %^[%d:%t %^] "%r" %s %b "%R" "%u" %D' --date-format=%d/%b/%Y --time-format=%T

**Comment by erikfrangez** [comment]
Thank you!

Apache conf: 
LogFormat "%h %l %u %t \"%r\" %>s %O \"%{Referer}i\" \"%{User-Agent}i\" %D %T" combined

goaccess command: 
goaccess /var/log/goAccess/ssl_access.log -o /var/www/html/index.html --log-format="%h %^[%d:%t %^] \"%r\" %s %b "%R" "%u" %D %T" --date-format=%d/%b/%Y --time-format=%T

But still I don't see some data in graphs, example:
![image](https://user-images.githubusercontent.com/8123421/101786784-a0deeb00-3afe-11eb-9ecb-ed853b7a8020.png)

**Comment by allinurl** [comment]
Please only use %D and not %T. 

    goaccess /var/log/goAccess/ssl_access.log -o /var/www/html/index.html --log-format="%h %^[%d:%t %^] "%r" %s %b "%R" "%u" %D %^" --date-format=%d/%b/%Y --time-format=%T

Let me know if that works

**Comment by erikfrangez** [comment]
No, still same :( 

![image](https://user-images.githubusercontent.com/8123421/101805369-f6bd8e00-3b12-11eb-9b63-f6c4154be4b9.png)

**Comment by allinurl** [comment]
Sorry, I'm not sure what issue you are experiencing. Can you please elaborate this?

**Comment by erikfrangez** [comment]
Hi, yes sure, I could try to explain.

So, date in column Avg. T. S. is not in ms, there is just us unit. I belive that my avg response times are higher that us. 

Maybe I don't know exactly how this software works 👍 

So, what I need is graph for response_time of apache web server for specifics website. 

Can we archive this here?

Thank you for help and support!

Regards, Erik

**Comment by allinurl** [comment]
My guess is that since you recently added `%D` to your log, it's taking a lot of those 0s into account and thus averaging in microsecs. Just to be sure, you can take a sample set of the last 10 requests and see if the avg.ts number makes sense. e..g,

    tail -10 access.log | goaccess - -o /var/www/html/index.html --log-format="%h %^[%d:%t %^] "%r" %s %b "%R" "%u" %D %^" --date-format=%d/%b/%Y --time-format=%T

Right now you can plot either visitors/hits/tx, there's no chart right now for avg.ts. Though, I should be able to add that. If that's the chart you are looking to have, please feel free to create a new issue so I don't forget.

**Comment by erikfrangez** [comment]
Hi,

I have try with last 10 rows from logs... situation is the same:

![image](https://user-images.githubusercontent.com/8123421/101819535-b0bdf580-3b25-11eb-9fae-4828fab46f09.png)

**Comment by allinurl** [comment]
Can you please post those 10 lines here? and the exact command you are running? Thanks!

**Comment by erikfrangez** [comment]
last 10 rows:

92.37.20.140 - - [10/Dec/2020:20:25:03 +0100] "GET /mod/lesson/view.php?id=160598&pageid=6923&startlastseen=yes HTTP/1.1" 303 992 "https://estudij.um.si/mod/lesson/view.php?id=160598" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36" 34209 0
92.37.20.140 - - [10/Dec/2020:20:25:03 +0100] "GET /mod/lesson/view.php?id=160598&pageid=6927 HTTP/1.1" 200 26692 "https://estudij.um.si/mod/lesson/view.php?id=160598" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36" 131690 0
92.37.20.140 - - [10/Dec/2020:20:25:03 +0100] "POST /lib/ajax/service.php?sesskey=XIN663OnZL&info=core_fetch_notifications HTTP/1.1" 200 376 "https://estudij.um.si/mod/lesson/view.php?id=160598&pageid=6927" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36" 17544 0
213.143.73.153 - - [10/Dec/2020:20:25:03 +0100] "POST /lib/ajax/service.php?sesskey=qcPFsvUTk2&info=core_message_get_conversation_counts,core_message_get_unread_conversation_counts HTTP/1.1" 200 640 "https://estudij.um.si/course/view.php?id=17289" "Mozilla/5.0 (Linux; Android 10; ELE-L29) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.101 Mobile Safari/537.36" 22682 0
213.143.73.153 - - [10/Dec/2020:20:25:03 +0100] "POST /lib/ajax/service.php?sesskey=qcPFsvUTk2&info=core_message_get_conversations HTTP/1.1" 200 1105 "https://estudij.um.si/course/view.php?id=17289" "Mozilla/5.0 (Linux; Android 10; ELE-L29) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.101 Mobile Safari/537.36" 18551 0
213.143.73.153 - - [10/Dec/2020:20:25:03 +0100] "GET /lib/ajax/service-nologin.php?info=core_get_string&cachekey=1607600876&args=%5B%7B%22index%22%3A0%2C%22methodname%22%3A%22core_get_string%22%2C%22args%22%3A%7B%22stringid%22%3A%22totalconversations%22%2C%22stringparams%22%3A%5B%5D%2C%22component%22%3A%22core_message%22%2C%22lang%22%3A%22sl%22%7D%7D%5D HTTP/1.1" 200 558 "https://estudij.um.si/course/view.php?id=17289" "Mozilla/5.0 (Linux; Android 10; ELE-L29) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.101 Mobile Safari/537.36" 6202 0
213.143.73.153 - - [10/Dec/2020:20:25:03 +0100] "GET /lib/ajax/service-nologin.php?info=core_get_string&cachekey=1607600876&args=%5B%7B%22index%22%3A0%2C%22methodname%22%3A%22core_get_string%22%2C%22args%22%3A%7B%22stringid%22%3A%22unreadconversations%22%2C%22stringparams%22%3A%5B%5D%2C%22component%22%3A%22core_message%22%2C%22lang%22%3A%22sl%22%7D%7D%5D HTTP/1.1" 200 420 "https://estudij.um.si/course/view.php?id=17289" "Mozilla/5.0 (Linux; Android 10; ELE-L29) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.101 Mobile Safari/537.36" 5515 0
213.143.73.153 - - [10/Dec/2020:20:25:03 +0100] "GET /lib/ajax/service-nologin.php?info=core_output_load_template_with_dependencies&cachekey=1607571348&args=%5B%7B%22index%22%3A0%2C%22methodname%22%3A%22core_output_load_template_with_dependencies%22%2C%22args%22%3A%7B%22component%22%3A%22core_message%22%2C%22template%22%3A%22message_drawer_conversations_list_items_placeholder%22%2C%22themename%22%3A%22classic%22%2C%22lang%22%3A%22sl%22%7D%7D%5D HTTP/1.1" 200 1472 "https://estudij.um.si/course/view.php?id=17289" "Mozilla/5.0 (Linux; Android 10; ELE-L29) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.101 Mobile Safari/537.36" 8153 0
213.143.73.153 - - [10/Dec/2020:20:25:03 +0100] "GET /lib/ajax/service-nologin.php?info=core_output_load_template_with_dependencies&cachekey=1607571348&args=%5B%7B%22index%22%3A0%2C%22methodname%22%3A%22core_output_load_template_with_dependencies%22%2C%22args%22%3A%7B%22component%22%3A%22core_message%22%2C%22template%22%3A%22message_drawer_conversations_list%22%2C%22themename%22%3A%22classic%22%2C%22lang%22%3A%22sl%22%7D%7D%5D HTTP/1.1" 200 4668 "https://estudij.um.si/course/view.php?id=17289" "Mozilla/5.0 (Linux; Android 10; ELE-L29) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.101 Mobile Safari/537.36" 9465 0
213.143.73.153 - - [10/Dec/2020:20:25:04 +0100] "GET /theme/image.php/classic/core/1607571348/u/f1 HTTP/1.1" 200 1627 "https://estudij.um.si/course/view.php?id=17289" "Mozilla/5.0 (Linux; Android 10; ELE-L29) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.101 Mobile Safari/537.36" 1184 0

command:
goaccess /var/log/goAccess/ssl_access.log -o /var/www/html/index.html --log-format="%h %^[%d:%t %^] \"%r\" %s %b "%R" "%u" %D %^" --date-format=%d/%b/%Y --time-format=%T


Best,

**Comment by allinurl** [comment]
goaccess /var/log/goAccess/ssl_access.log -o /var/www/html/index.html --log-format='%h %^[%d:%t %^] "%r" %s %b "%R" "%u" %D %^' --date-format=%d/%b/%Y --time-format=%T

**Comment by erikfrangez** [comment]
Awesome, it is working now! Really thank you! 

Now we need just graph for response_time, I will open new issue.

Really thank you!!!

Best,

**Comment by allinurl** [comment]
That's great to hear. Closing this, feel free to reopen it if needed.
