### ISSUE TITLE
File not found if using config file

### ISSUE THREAD

**Issue by poblabs** [allinurl/goaccess#198]
Hi there, I've installed goaccess using yum on CentOS 6.6. 

I've defined a custom log format and log file using /etc/goaccess.conf. I get the error below when I just run `goaccess`. Here's my config:

/etc/goaccess.conf

```
date-format %d/%b/%Y
log-format %v %h %^[%d:%^] "%r" %s %b
log-file /var/log/httpd/all_sites-access_log
```

I get this error:

```
GoAccess - version 0.8.2 - Jul 25 2014 01:55:08

Fatal error has occurred
Error occured at: parser.c - parse_log - 1071
No such file or directory
```

The log file does exist. If I run `goaccess -f /var/log/httpd/all_sites-access_log` it works right away.

Any thoughts?

I also have a 2nd question on if it's possible to view which site is being accessed in real time based off the %v VirtualHost? Right now I see a lot of stats, which is great, but it's not displaying the %v VirtualHost anywhere, so it's a little tough to follow 

Thanks!

**Comment by antonioreyna** [comment]
i have the same problem on mac

**Comment by allinurl** [comment]
@antonioreyna this should work fine on the latest release.

**Comment by Jason-mor** [comment]
the version 1.3_1, i have the same problem on mac.

**Comment by allinurl** [comment]
@Jason-mor Can you please attach your config file and would you be able to run it through `strace` and attach the output as well? Thanks.
