### ISSUE TITLE
Cannot access real-time HTML Output 

### ISSUE THREAD

**Issue by zarar-shah** [allinurl/goaccess#1980]
Hello guys, as I am new to this technology and also linux. I want to create a secure SSH connection to my webserver and use GoAccess to monitor real-time logs. But I can't connect my cowAxess with the web server please guide me. 

Thanks all!

**Comment by allinurl** [comment]
You can install goaccess in your local computer and access your server logs as:

     ssh -n root@server 'tail -f /var/log/apache2/access.log' | goaccess - --log-format=COMBINED

**Note**: SSH requires `-n` so GoAccess can read from stdin. Also, make sure to use **[SSH keys](https://www.digitalocean.com/community/tutorials/how-to-set-up-ssh-keys-2)** for authentication as it won't work if a passphrase is required.

**Comment by zarar-shah** [comment]
Appreciate your response, but I've to ask that can I use this on windows 10 ssh ? or will need PuTTy? It will be much appreciated if you can tell me all the steps as it is my first experience to use GoAccess for real-time logs monitoring for my website.

**Comment by allinurl** [comment]
If you're in Win 10, I think you can use ssh over powershell. Take a look at https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_keymanagement 

Let me know if that helps.

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
