### ISSUE TITLE
How to make "Encryption Settings" panel work？

### ISSUE THREAD

**Issue by i553041** [allinurl/goaccess#1981]
In goaccess manual page, there have an "Encryption Settings" panel, it said: this panel shows the SSL/TLS protocol used along the Cipher Suites. This panel is not enabled unless %K is given within the log-format variable.

but I don't know how to add %K，please help, I want to check TLS & ciphers (%K & %k)

I'm using ubuntu 20.10, goaccess 1.4.3, nginx 1.19.5

I make goaccess as service, and use real-time-html, everything is work

```
root@ubuntu:/etc/nginx# service goaccess status
● goaccess.service - Goaccess Web log report.
     Loaded: loaded (/etc/systemd/system/goaccess.service; enabled; vendor preset: enabled)
     Active: active (running) since Sat 2020-12-19 23:20:32 HKT; 14min ago
   Main PID: 302423 (goaccessreport)
      Tasks: 4 (limit: 971)
     CGroup: /system.slice/goaccess.service
             ├─302423 /bin/bash /usr/local/bin/goaccessreport
             └─302425 /usr/local/bin/goaccess /var/log/nginx/access.log - -o /var/www/html/index.html --ws-url=wss://xxx.xxx.com --ssl-cert=/etc/cert>

Dec 19 23:20:32 ubuntu systemd[1]: Started Goaccess Web log report..
```

 I just want to add %K & %k, make "Encryption Settings" panel work, here is the goaccess.service

```
[Unit]
Description=Goaccess Web log report.
After=network.target
StartLimitIntervalSec=0

[Service]
Type=simple
User=root
Group=root
Restart=always
RestartSec=1800
ExecStart=/usr/local/bin/goaccessreport
StandardInput=tty
StandardOutput=tty
StandardError=tty
TTYPath=/dev/tty7

[Install]
WantedBy=multi-user.target
```

/usr/local/bin/goaccessreport :

```
#!/bin/bash
zcat -f /var/log/nginx/*access.log.* | /usr/local/bin/goaccess /var/log/nginx/*access.log - -o /var/www/html/index.html --ws-url=wss://xxx.xxx.com --ssl-cert=/etc/cert/ecc384.crt --ssl-key=/etc/cert/ecc384.key --log-format=COMBINED --real-time-html
```

here is my nginx.conf log setting:

```
log_format proxy '$proxy_protocol_addr - $remote_user [$time_local] '
                     '$ssl_protocol/$ssl_cipher '
                     '"$request" $status $body_bytes_sent '
                     '"$http_referer" "$http_user_agent"';
```

and here is the real log in /var/log/nginx/access.log

```
111.224.7.4 - - [19/Dec/2020:23:10:18 +0800] TLSv1.2/ECDHE-ECDSA-AES128-GCM-SHA256 "GET /1 HTTP/1.1" 404 188 "-" "Mozilla/4.054101423 Mozilla/4.0 (compatible; MSIE 9.0; Windows NT 6.1)"
```

In my case, how to make "Encryption settings" panel work?

Sorry, I'm stupid, I really don't understand the manual page "CUSTOM LOG/DATE FORMAT" section.

thanks for help first.

**Comment by allinurl** [comment]
This should do it:

    goaccess access.log --log-format='%h %^[%d:%t %^] %K/%k "%r" %s %b "%R" "%u"' --date-format=%d/%b/%Y --time-format=%T

**Comment by i553041** [comment]
> This should do it:
> 
> ```
> goaccess access.log --log-format='%h %^[%d:%t %^] %K/%k "%r" %s %b "%R" "%u"' --date-format=%d/%b/%Y --time-format=%T
> ```

Thank you very much for your quick reply, it works.
