### ISSUE TITLE
Example browsers.list partially broken

### ISSUE THREAD

**Issue by uschwarz** [allinurl/goaccess#1982]
Starting from https://github.com/allinurl/goaccess/blame/master/config/browsers.list#L96 there's spaces instead of tabs until the end of the "browsers" block.

**Comment by allinurl** [comment]
Thanks for reporting it!. I pushed a [commit](https://github.com/allinurl/goaccess/commit/bb97ebb4ae4190922072e3f2bb01a9f920af8045) to address it.
