### ISSUE TITLE
timestamp in milliseconds

### ISSUE THREAD

**Issue by backface** [allinurl/goaccess#1983]
I got a log from a CDN provider with a timestamp in milliseconds! 
I see there is a time format specifier  %s -  for UNIX timestamp in seconds - and %f  - for timestamps in microseconds - but none for timestamps in milliseconds or did I overlook something? 
Otherwise, this can be seen as a feature request, it would be great being able to read it in without further processing.

**Comment by allinurl** [comment]
Thanks for pointing that out. I can look into adding this. Could you please post a few lines from your access log so I can run some tests before pushing it out? Thanks again.

**Comment by backface** [comment]
sure:

MISS|200|1609009529084|623|225654|68.6.149.0|https://www.example.at/|https://play.example.live/hls/live_480p/index.m3u8|LA|Mozilla/5.0 (X11; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0|0be23d8b5fc077f099e072a1977162b9|US
MISS|200|1609009527013|935438|225654|68.6.149.0|https://www.example.at/|https://play.example.live/hls/live_480p/1609009507638.ts|LA|Mozilla/5.0 (X11; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0|c4f63d5e107a553ec6692552130606ec|US
MISS|200|1609009523952|929636|225654|68.6.149.0|https://www.example.at/|https://play.example.live/hls/live_480p/1609009501623.ts|LA|Mozilla/5.0 (X11; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0|ab98fda63a4bd801e9457c32ce7157ff|US
MISS|200|1609009522342|622|225654|68.6.149.0|https://www.example.at/|https://play.example.live/hls/live_480p/index.m3u8|LA|Mozilla/5.0 (X11; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0|bc17f26710297c8bd40c1ed9c6ddc8f4|US
MISS|200|1609009520755|937837|225654|68.6.149.0|https://www.example.at/|https://play.example.live/hls/live_480p/1609009495624.ts|LA|Mozilla/5.0 (X11; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0|a6d3088966a03bba4aa54745935c32f3|US
MISS|301|1608999297225|511|225654|209.17.96.0|-|http://play.example.live/|LA|Mozilla/5.0 (compatible; Nimbostratus-Bot/v1.3.2; http://cloudsystemnetworks.com)|7f14addbcf2d33b2dd927fd0b5107abd|US
HIT|200|1608977032585|2463|225654|209.17.96.0|-|https://play.example.live/|LA|Mozilla/5.0 (compatible; Nimbostratus-Bot/v1.3.2; http://cloudsystemnetworks.com)|14210011ea3796cdc6d97646e7eb0080|US
HIT|200|1608970190494|2463|225654|209.17.96.0|-|https://play.example.live/|LA|Mozilla/5.0 (compatible; Nimbostratus-Bot/v1.3.2; http://cloudsystemnetworks.com)|1df6e1732651f86848d052d593cd7326|US

**Comment by allinurl** [comment]
This has been added upstream. Feel free to build from [**development**](https://github.com/allinurl/goaccess#build-from-github-development) to test it out. It will be pushed out in the upcoming release. Thanks again.

**Comment by allinurl** [comment]
By the way, It uses `%*` as `--date-format` & `--time-format`. e.g.,

```
google.com:80 90.175.232.26 - - [1609009529084] "GET /images/pics.jpg HTTP/1.1" 200 93854 "http://www.google.com/test/" "Mozilla/5.0 (iPad; CPU OS 9_3_2 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13F69 Safari/601.1" 459814
google.com:80 90.106.194.195 - - [1610481852572] "GET /rural.html HTTP/1.0" 200 30927 "https://www.google.com/" "Mozilla/5.0 (Linux; Android 6.0; XT1063 Build/MPB24.65-34) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.94 Mobile Safari/537.36" 12801
```



    goaccess access.log --log-format '%v:%^ %h %^[%x] "%r" %s %b %T "%u" %D' --date-format=%* --time-format=%*
