### ISSUE TITLE
goaccess sends data via socket each second when managed by systemd

### ISSUE THREAD

**Issue by dp92987** [allinurl/goaccess#1984]
When I run GoAccess using `/usr/local/bin/goaccess /var/log/nginx/access.log --output=/var/www/html/goaccess.html --real-time-html --ws-url=wss://myhost:443/goaccess --addr=127.0.0.1 --port=7890` (w/ or w/o --daemonize) everything is working as expected - in particular goaccess sends data via socket only when log is updated:

![https://deltapapa.io/~daniil/Screenshot%202020-12-24%20at%2019.55.23.png](https://deltapapa.io/~daniil/Screenshot%202020-12-24%20at%2019.55.23.png)

But when the same is managed by systemd goaccess starts sending data each second regardless of log updates.

![https://deltapapa.io/~daniil/Screenshot%202020-12-24%20at%2019.59.45.png](https://deltapapa.io/~daniil/Screenshot%202020-12-24%20at%2019.59.45.png)

systemd unit:
```
[Unit]
Description=GoAccess
After=multi-user.target

[Service]
User=ubuntu
Group=ubuntu
Restart=always
RestartSec=1800
ExecStart=/usr/local/bin/goaccess /var/log/nginx/access.log --output=/var/www/html/goaccess.html --real-time-html --ws-url=wss://myhost:443/goaccess --addr=127.0.0.1 --port=7890

[Install]
WantedBy=default.target
```

**Comment by jonathonf** [comment]
I'm seeing the same thing, with the symptom of a constant stream of 100KB/s data when the GoAccess stats page is loaded.

This seems to have started with 1.4.3 - I didn't see this with any earlier version.

**Comment by allinurl** [comment]
Thanks for reporting this. Can I ask, does it make any difference if you add a dash to the command?. e.g.,

    ExecStart=/usr/local/bin/goaccess /var/log/nginx/access.log - --output=/var/www/html/goaccess.html --real-time-html --ws-url=wss://myhost:443/goaccess --addr=127.0.0.1 --port=7890

**Comment by jonathonf** [comment]
No change to the network activity if a dash is added after the log filename.

**Comment by allinurl** [comment]
This has been fixed. Please feel free to test it out by building from [**development**](https://github.com/allinurl/goaccess#build-from-github-development) and let me know how it goes. It will be pushed out in the upcoming version.

Feel free to reopen it if needed.

**Comment by jonathonf** [comment]
Looks to have done the job - I've applied the above patch against 1.4.3 and I'm not seeing the issue any more.
