### ISSUE TITLE
Geo location shown as Unknown

### ISSUE THREAD

**Issue by HB9VQQ** [allinurl/goaccess#1986]
I compiled goaccess from source
./configure --enable-utf8 --enable-geoip=mmdb

configured goacess.conf with
geoip-database /usr/local/etc/goaccess/GeoLite2-ASN.mmdb

Dowloaded Geo DB 
![image](https://user-images.githubusercontent.com/75934980/103175637-b9bffe00-486b-11eb-95cf-01afbd649b03.png)

and copied Geo file to
![image](https://user-images.githubusercontent.com/75934980/103175664-f25fd780-486b-11eb-96a9-533b76749f9e.png)

starting goaccess
/usr/local/bin/goaccess -f /var/log/nginx/access.log -o /var/www/html/report.html --log-format=COMBINED --real-time-html

If I look at the html file it still shows Unknown
![image](https://user-images.githubusercontent.com/75934980/103175685-0e637900-486c-11eb-9ecd-827ea2b7e8c1.png)

Whats wrong with my setup ?

**Comment by allinurl** [comment]
Is `GeoLite2-ASN.mmdb` the file provided by MaxMind when you click on the GeoLite 2 City download? Seems like the first option though, which I think is not supported.

**Comment by allinurl** [comment]
By the way, you could ways try with the city/country dbs from https://db-ip.com/db/lite.php to test things out.

**Comment by HB9VQQ** [comment]
I must have clicked on the wrong link although I could swear I got the right zip file.... Now all is working as expected. Sorry for the confusion and thanks for your help !

**Comment by allinurl** [comment]
No problem :) Glad that solved the issue. 

Feel free to reopen it if needed.

**Comment by 47Balboa** [comment]
I get the same issue when running goaccess in docker compose with the allinurl/goaccess:1.7 image. I am using the GeoLite2-City.mmdb file from https://dev.maxmind.com/geoip/geolite2-free-geolocation-data but in the dashboard it shows as Unknown.

**Comment by prologic** [comment]
To be clear; the docs say to use the City or Country db. Which is it?

```
proxy-1:~# ls -1 /etc/caddy/*.mmdb
/etc/caddy/GeoLite2-ASN.mmdb
/etc/caddy/GeoLite2-City.mmdb
/etc/caddy/GeoLite2-Country.mmdb
```

I'm also getting "Unknown" for the ASN panel, but other Geo panels are just working fine. Which database which we be using here? Perhaps the docs / man page needs some updating?

**Comment by allinurl** [comment]
@prologic The country database provides only country-level data, while the city database includes both country and city data. I’d recommend configuring it like this:

```
geoip-database /mmdb/dbip-asn-lite-2024-04.mmdb
geoip-database /mmdb/dbip-city-lite-2024-01.mmdb
```

These options should fall under the GEOLOCATION OPTIONS section in the man page. Let me know if anything seems to be missing!

**Comment by prologic** [comment]
So you mean to say the flags / options can be passed twice? Do the docs day this?
