### ISSUE TITLE
FreeBSD / No real time HTML

### ISSUE THREAD

**Issue by pousterlus** [allinurl/goaccess#1992]
Hey there,

I didn't succeed to fix my problem alone with reading everything related to real time HTML issues.
I have a FreeBSD server hosting several small websites. I've tweaked GoAccess to be able to parse my custom Apache logfiles. Everything works smoothly.. except realtime HTML.

If I restart the daemon, the report.html file is correctly updated but WebSocket server seems to be down.
My goaccess.conf relevant informations (I've obfuscated/faked some for security purposes) : 
```
addr 87.xxx.89.xxx
daemonize true
origin http://www.domain.net
port 7890
real-time-html true
ws-url vendome (result of "hostname" command in terminal)
```

When the daemon is started, I visit http://www.domain.net/report.html : I can see the report well (timestamped from the time the daemon started).
But if I try to access http://www.domain.net:7890 it fails.

I have an Apache24 WebServer and VirtualHost configurations.

There is obviously something I miss there, but I can't find it.
If someone could give me a hint on what I could check to fix it ?

Thanks :)

-- 
Léo.

**Comment by allinurl** [comment]
When you open `http://www.domain.net/report.html`, can you post the output of your browser's console? I'd try running it without `daemonize` and without `addr` & `origin` to test it out.

**Comment by pousterlus** [comment]
Hey allinurl :)

Thanks for your answer, and by extension for your dedication and work for the community.
I didn't think about checking the browser's console.

It says : 
`Firefox can't establish a connection with server wss://vendome:7890/.`
So I tried to modify the `ws-url` parameter with `www.domain.net` (to make it similar and maybe accessible) but I ended up with the same error : `Firefox can't establish a connection with server wss://www.domain.net:7890/.`

I followed your advice to comment out `daemonize` / `addr` and `origin`, it leaves us with `real-time-html` and `port` parameters set respectively to `true` and `7890`.

Then : 

```
goaccess --real-time-html -p /usr/local/etc/goaccess/goaccess.conf -o /usr/local/www/apache24/data/report.html
 [PARSING /var/log/httpd-access.log] {61638} @ {12327/s}/s}
WebSocket server ready to accept new client connections
Accepted: 12 51.159.xx.68 (my ip)
Active: 0
```

Then I went to Firefox, refreshed the page, the report's still there, but same error.

I'm not familiar (at all) with WebSocket, so I have to ask : is there anything to configure in Apache side or server side in order to make it work ?

Thanks,

-- 
Léo.

**Comment by pousterlus** [comment]
In addition, I tried the live terminal output and everything is refreshed "real-time".
```
Total Requests  62058
...
Total Requests  62075
...
Total Requests  62087
```

-- 
Léo.

**Comment by allinurl** [comment]
Sounds like it can reach the server. Did you open port 7890? Are you able to telnet from your local machine/laptop to the server via port 7890? e.g.,

    $ telnet domain.com 7890

Let me know what output you get.

**Comment by pousterlus** [comment]
Errr that's exactly what I was afraid about : I've just installed GoAccess with the FreeBSD package manager. I didn't notice that there was additional steps to make real time HTML. The WebSocket server need to be installed separately ?

Looking at the "Get Started" section of GoAccess website, I see a link to `https://gwsocket.io/` : is that the tool I need to install additionally ?

**Comment by allinurl** [comment]
There are no additional packages to install. You just need to make sure you have port 7890 opened. I said use telnet to check if you have access to the server.

**Comment by pousterlus** [comment]
Okay, so with host : 
```
telnet www.domain.net 7890
Trying 87.xxx.89.xxx...
telnet: connect to address 87.xxx.89.xxx: Connection refused
telnet: Unable to connect to remote host

```

And with localhost : 
```
telnet localhost 7890
Trying 127.0.0.1...
telnet: connect to address 127.0.0.1: Connection refused
Trying ::1...
telnet: connect to address ::1: Connection refused
telnet: Unable to connect to remote host
```

-- 
Léo.

**Comment by pousterlus** [comment]
Sorry I'm quite comfortable with many things but WebSocket is a whole new world for me :)

Okay, so I've run the service : `/usr/local/etc/rc.d/goaccess start`
With `ps aux | grep goaccess` I get : `/usr/local/bin/goaccess --daemonize --real-time-html --pid-file=/var/run/goaccess.pid -p /usr/local/etc/goaccess/goaccess.conf -o /usr/local/www/apache24/data/report.html`

In `goaccess.conf` section "Server Options" everything is commented out except ws-url parameter set to `www.domain.net`.

In this situation, when I `telnet www.domain.net 7890`
I get : 
```
Trying 87.xxx.89.xxx...
Connected to vendome.domain.net.
Escape character is '^]'.
```

So the port seems to be correctly opened.

In Firefox when I access `https://www.domain.net/report.html` it says :
`Firefox can't establish a connection with server wss://www.hyod.net:7890/.`

**Comment by allinurl** [comment]
You appear to be using wss, so you need to use a certificate and key. Please take a look at `--ssl-cert=<path/cert.crt>` & `--ssl-key=<path/priv.key>`. Also, you will need to connect in your browser via an https address as well. e.g., https://mydomain.com

**Comment by pousterlus** [comment]
Hi,

Thanks for your help.
I didn't specify GoAccess to use wss, maybe that's a default behavior induced by my Apache configuration ?

Anyway, I filled the crt and key SSL files inside goaccess.conf and magic happened :)
Thanks for all your work and your continuous dedication about resolving community issues.

Cheers from Paris, France.

-- 
Léo.

**Comment by allinurl** [comment]
No problem. Glad to hear you got it solved :)

Feel free to reopen it if needed.
