### ISSUE TITLE
REQUESTED FILES (URLS): Max T.S. is wrong (in html report)

### ISSUE THREAD

**Issue by cdaller** [allinurl/goaccess#1995]
When processing a list of urls the value of Max T.S. in REQUESTED FILES (URLS) is wrong.

![image](https://user-images.githubusercontent.com/1531978/103902029-3b304f80-50fa-11eb-9508-ad5f22b150f4.png)

This is easily seen as the Max value is less than the average value (see screenshot).

Attached is an anonymized nginx log. The command line to read the log and create the report was:
```
cat anonymized.log \
 goaccess \
  --log-format '%v %h %^ %^ [%d:%t %^] "%r" %s %b %T "%u" "%^"' \
  --date-format %d/%b/%Y \
  --time-format %H:%M:%S \
  -o report_anonymized.html
```

[anonymized.log](https://github.com/allinurl/goaccess/files/5782073/anonymized.log)

as a test you can extract the seconds from above log file using
```
cut -d' ' -f 12 anonymized.log | sed -e 's/\./,/g'  > anonymized.csv
```

and calculate the values in excel:
sum and avg are correct, but max should be 4,491s instead of 59ms

**Comment by allinurl** [comment]
Thanks for reporting this. I believe this was fixed on a previous release. Here's what I get on the latest version (30,071 requests). Could you please upgrade and let me know if that solves the issue on your end? Thanks

![2021-01-12-114553_893x449_scrot](https://user-images.githubusercontent.com/5005367/104352140-e6128600-54cb-11eb-9b2e-7b443190baea.png)

**Comment by cdaller** [comment]
yes, version 1.4.3 (latest) at least does not have this issue - thanks for response and for the great tool!
