### ISSUE TITLE
Merge protocols for the same page

### ISSUE THREAD

**Issue by pozitron57** [allinurl/goaccess#1996]
Goaccess shows that the pages were accessed via HTTP/1.0 or HTTP/1.1 protocols. As a result, there are two lines for the same page in the tables (I generate static html files).

How can I have a single line for a single page, where are visits and hits for both protocols are counted?

**Comment by 0bi-w6n-K3nobi** [comment]
Hi @pozitron57 

You can be this with a option `-H no` or `--http-protocol=no` in command-line
or add option into `goaccess.conf`.

You can see more details into manual [here](https://goaccess.io/man).

**Comment by pozitron57** [comment]
@0bi-w6n-K3nobi oh, i missed it in the manual. Thanks!
