### ISSUE TITLE
Another log format question

### ISSUE THREAD

**Issue by hpapagaj** [allinurl/goaccess#1997]
I feel so stupid to open an issue because of this, but I would like to ask for a help to determine my log format. 🙏

Access.log:
`xy.com 78.99.221.133 - - [08/Jan/2021:19:00:39 +0100] "GET /image/321100-16.JPG HTTP/1.1" 200 489481 "https://xy.com/axon" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36" 5995 790 490698`

apache2 config:

```
LogFormat "%v:%p %a %l %u %t \"%r\" %>s %O \"%{Referer}i\" \"%{User-Agent}i\"" vhost_combined
LogFormat "%V %a %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\" %P %I %O" combined
LogFormat "%a %l %u %t \"%r\" %>s %O" common
LogFormat "%{Referer}i -> %U" referer
LogFormat "%{User-agent}i" agent
```

**Comment by hpapagaj** [comment]
I figured it out.

```
log-format %v %h %^[%d:%t %^] "%r" %s %b "%R" "%u" %P %I %O
date-format %d/%b/%Y
time-format %H:%M:%S
```

**Comment by hpapagaj** [comment]
@allinurl I hope you read closed issues and take a look on my question. 

I would like to store 30day of data, I am calling goaccess from logrotate config:

```
/var/log/apache2/*.log {
        daily
        missingok
        rotate 52
        compress
        postrotate
                /etc/init.d/apache2 reload > /dev/null
                goaccess \
                /var/log/apache2/access.log.1 \
                --db-path /var/log/goaccessdb \
                --restore \
                --persist \
                --keep-last=30 \
                --process-and-exit \
        endscript
}
```
 
I am I using correctly the restore & persist commands here?

I found out that I cannot use "-o /home/html/user/public_html/goaccess/report.html" command here, so I plan to generate later from crontab:

```
goaccess \
  --db-path /var/log/goaccessdb \
  --restore \
  -o /home/html/user/public_html/goaccess/report.html
```

**Comment by allinurl** [comment]
@hpapagaj looks right to me. Are you getting the output you need so far?
