### ISSUE TITLE
nginx log format

### ISSUE THREAD

**Issue by introfini** [allinurl/goaccess#20]
Hello!

I have tried everything but can't make it work with this nginx log format:

$remote_addr - $remote_user [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent" "$http_x_forwarded_for"

Example:
127.0.0.1 - - [23/Aug/2013:14:01:26 +0100] "GET /sites/xxx.pt/files/imagecache/64x64/avatar/picture-156409.jpg HTTP/1.1" 200 1768 "http://xxx.pt/forum/pr-saldos-80" "Mozilla/5.0 (Windows NT 5.1; rv:22.0; Avant TriCore) Gecko/20130630 Firefox/22.0" "213.58.193.194, 213.58.193.194"

I'm using version 0.6. I need the %h to be the http_x_forwarded_for

Thanks!

**Comment by gxhllj** [comment]
Have you solved this problem ? I have the same problem.
@introfini

**Comment by allinurl** [comment]
@gxhllj are you having issues with the log format?

**Comment by gxhllj** [comment]
yes, and i have replied you in another issues.
maybe i need email you.
@allinurl
