### ISSUE TITLE
Default value of keep-last

### ISSUE THREAD

**Issue by danilort** [allinurl/goaccess#2000]
Hello, 
what is the default value of the **keep-last** parameter, 
used in conjunction with **persist = true**?
7 days?
infinite?

Thank's for your job!

**Comment by 0bi-w6n-K3nobi** [comment]
Hi @danilort 

Just see into your conf `/etc/goaccess/goaccess.conf`.
If it is commented then it is `zero` == `infinite`, i.e. without any limitation.
Do a simple test, with a few requests for each day, and you will be sure of it.
And this parameter is independent of the flag `persit`.

I hope I've helped.

**Comment by danilort** [comment]
Great. 
Thanks

**Comment by allinurl** [comment]
As @0bi-w6n-K3nobi zero is default which is equal to infinity regardless of persist. 

If you have any other questions, feel free to reopen it if needed.
