### ISSUE TITLE
AWstats compatible "Visit" metrics

### ISSUE THREAD

**Issue by fanfani** [allinurl/goaccess#2001]
awstats provides a metric for "**Number of Visits**", defined as follows:

> Vists refer to the number of times folks have visited your site. For example, if I visit your site and view 18 different pages, that counts as one visit.
> 
> AWStats groups page views into a single visit if those page views occur within one hour. For example, if I visit your site, then come back two hours later, that’s two visit.
> 
> If I visit your site, and then come back 20 minutes later, that’s one visit.
> 

is that measured in goaccess? 

thank you!

**Comment by allinurl** [comment]
Similar, however, in goaccess if I visit your site, and then come back 2 hours later, that’s still one visit. In fact, whole day is one visit.

**Comment by fanfani** [comment]
two questions: 
- how is this called in goaccess? (and/or what is the label in json output)
- is the time period (1 day) customizable?

**Comment by allinurl** [comment]
Visitors.

Closest is to pass `--date-spec=hr`, it will show it like this https://rt.goaccess.io/?20201108215118

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
