### ISSUE TITLE
How to tail a remote log and have goaccess parse it locally in real-time

### ISSUE THREAD

**Issue by sudolawyer** [allinurl/goaccess#2010]
I have read all the issues about loading the dashboard from a remote server's access.log file but I have not been able to get it to work. I can get a static report.html page but it will not load live time.

This is what I've used to set-up the pipe, which does successfully pull the access.log from the remote server. In my console, I do see the line number increases in live time as I reload the target server webpage but that change is not reflected in the report.html dashboard.

`ssh -t user@remote-server 'tail -f -n +1 /var/log/apache2/access.log' | goaccess -o /var/www/html/report.html --log-format=COMBINED --real-time-html -`

I've tried a bunch of stuff but have not been able to get this to work. Any ideas/updates/tips?

**Comment by allinurl** [comment]
Please take a look at the [**examples**](https://goaccess.io/man#examples) in the man page (server section). I think I posted [this](https://twitter.com/goaccess/status/1331628718704431104) not long ago in twitter.

    # ssh -n root@server 'tail -f /var/log/apache2/access.log' | goaccess -

**Note**: SSH requires `-n` so GoAccess can read from `stdin`. Also, make sure to **use SSH keys** for authentication as it won't work if a passphrase is required.

**Comment by sudolawyer** [comment]
tried your command above but now the report.html is not created in the /var/www/html/ directory.

I am using an ssh alias from config, for example: 

`ssh -n alias 'tail -f /var/log/apache2/access.log' | goaccess - -o /var/www/html/report.html --log-format=COMBINED --real-time-html`

report.html isn't being created

**Comment by sudolawyer** [comment]
I played around with this some more I can get Server A dashboard to display Server A's access.log in real time. I had to first generate a static report.html, then re-run the command with the --real-time-html operand.

But I still cannot get Server A dashboard to display Server B's access.log. I confirm the following:

1. I can ssh from Server A to Server B using only keys
2. I can output Server B's access.log file on Server A's standard out

I cannot:

1. create a static report on Server A using pipe from Server B (i.e., I cannot `ssh -n ServerB_alias  'tail -f /var/log/apache2/access.log' | goaccess - -o /var/www/html/report.html --log-format=COMBINED`
2. When I try to do this, I do not get an error, but nothing is created in Server A's /var/www/html directory
3. I also cannot `ssh -n ServerB_alias 'tail -f /var/log/apache2/access.log' | goaccess - -o /var/www/html/report.html --log-format=COMBINED --real-time-html`

**Comment by allinurl** [comment]
Sounds like a permissions issue maybe? I'd start with the basics:

Try to see if the data comes as it should and with the right log format. e.g., should output a stream of COMBINED log-format data without requiring credentials

     # ssh -n root@server 'tail -f /var/log/apache2/access.log'

Try outputting to the terminal to see if that works fine:

     # ssh -n root@server 'tail -f /var/log/apache2/access.log' | goaccess - --log-format=COMBINED

I'd try to output to your home dir

     # ssh -n root@server 'tail -f /var/log/apache2/access.log' | goaccess - --log-format=COMBINED -o /home/user/report.html --real-time-html

Let me know what how it goes.

**Comment by sudolawyer** [comment]
> Sounds like a permissions issue maybe? I'd start with the basics:
> 
> Try to see if the data comes as it should and with the right log format. e.g., should output a stream of COMBINED log-format data without requiring credentials
> 
> ```
>  # ssh -n root@server 'tail -f /var/log/apache2/access.log'
> ```
> **Confirmed. I am able to successfully output remote server's access.log file.**

> Try outputting to the terminal to see if that works fine:
> 
> ```
>  # ssh -n root@server 'tail -f /var/log/apache2/access.log' | goaccess - --log-format=COMBINED
> ```
> **This works but with a weird behavior. I am able to get output to terminal but it remains static until I resize by terminal window (I'm on OSX). If I resize the terminal window in OSX, I get an updated dashboard. If I leave as is, it is static, despite repeated refreshes/requests made to the remote (i.e., target) web server.**

> I'd try to output to your home dir
> 
> ```
>  # ssh -n root@server 'tail -f /var/log/apache2/access.log' | goaccess - --log-format=COMBINED -o /home/user/report.html --real-time-html
> ```
> **Ok, this worked but I had to run as sudo. I am running as user$, who is sudo. /var/www/html is owned by $user, so it weird that it wouldn't create.** I had to 
```
ssh -n root@server 'tail -f /var/log/apache2/access.log' | **sudo** goaccess . . . .
```

> Let me know what how it goes.

**Comment by allinurl** [comment]
Quick question, are you in v1.4.5? Also, are you able to test this out on a linux machine, I'm curious if this is isolated to OSX... you mentioned sudo, I wonder if #2009 could help in your case.

**Comment by sudolawyer** [comment]
> Quick question, are you in v1.4.5? Also, are you able to test this out on a linux machine, I'm curious if this is isolated to OSX... you mentioned sudo, I wonder if #2009 could help in your case.

Im running it on Ubuntu -- i just ssh into the box from my osx laptop. 

Im running v1.2

**Comment by allinurl** [comment]
Would you be able to build from [**development**](https://github.com/allinurl/goaccess#build-from-github-development)? There have been several changes since v1.2 - I just pushed #2009 which may address the sudo issue. If you are on OSX, you probably can run:

    brew install --HEAD goaccess

**Comment by sudolawyer** [comment]
let me see if I can. My envir is on Ubuntu, I'm only using OSX's terminal to ssh into my box.

**Comment by sudolawyer** [comment]
I updated to 1.4

**Comment by allinurl** [comment]
Glad to hear it got resolved. 

Closing this. Feel free to reopen it if needed.

**Comment by sudolawyer** [comment]
> Glad to hear it got resolved.
> 
> Closing this. Feel free to reopen it if needed.

Thank you! And thanks for your help!
