### ISSUE TITLE
Does not show swedish translation after upgrading to 1.4.5

### ISSUE THREAD

**Issue by tellustheguru** [allinurl/goaccess#2013]
After I upgraded GoAccess from 1.4.3 to 1.4.5, it shows GoAccess in english not swedish.

**Comment by tellustheguru** [comment]
I fixed it my self, I am running goacces as a service in debian. Just adding "export LANG=sv_SE.UTF-8" in the service script.

**Comment by allinurl** [comment]
Thanks for pointing that out. Feel free to reopen it if needed.
