### ISSUE TITLE
Token '' doesn't match specifier '%h'

### ISSUE THREAD

**Issue by gopwcd** [allinurl/goaccess#2015]
So, I am having this issue when trying out goaccess. I am trying to read the standard linux .log files.

Token '' doesn't match specifier '%h'

Logs are like this one:

Jan 25 23:06:39 gopwcd kernel: [    0.000000] KERNEL supported cpus:

**Comment by allinurl** [comment]
Hello - goaccess works very well with access logs. You will need a consistent pattern to parse other logs.
