### ISSUE TITLE
Serve goaccess html page from nginx subdirectory

### ISSUE THREAD

**Issue by Eliesemoule** [allinurl/goaccess#2017]
I try to access to goaccess html page from Nginx subdirectory. Nginx says `404 Not found` I don't know if it's possible. Below my setup :

I use goaccess 1.4.5 compiled with this option : `--enable-debug --enable-geoip=mmdb --enable-utf8 --sysconfdir=/etc/ --with-openssl`

goaccess.conf file
`log-format COMBINED`
`log-file /var/log/nginx/oaccess.log`
`config-dialog true`
`html-report-title GoAccess WebSite`
`pid-file /var/run/goaccess.pid`
`real-time-html true`
`ws-url ws://goaccess.mydomain.com/goaccess/ws:80`
`output /var/www/html/goaccess/index.html`
`keep-last 365`
`real-os true`
`db-path /opt/goaccess/`
`persist true`
`restore true`

Nginx vhost conf file :
`server {`
`    listen 80;`
`    server_name goaccess.mydomain.com;`
`    location /goaccess {`
`        root /var/www/html/goaccess/;`
`    }`
`    location /goaccess/ws {`
`        proxy_pass http://127.0.0.1:7890/goaccess/ws;`
`        proxy_http_version 1.1;`
`        proxy_set_header Upgrade $http_upgrade;`
`        proxy_set_header Connection "Upgrade";`
`        proxy_set_header Connection "keep-alive";`
`        proxy_pass_request_headers on;`
`    }`

What I'm doing wrong ?? Could you please someone help me ?

**Comment by 0bi-w6n-K3nobi** [comment]
Hi, @Eliesemoule.

Your mistake is simple.
You can see it into `error.log` from NGinX.

You can't add `/goaccess` into variable `root`.
You maybe use:
`root /var/www/html/;`

Otherwise when you access into browser to `/goaccess/index.html` will be
access to `/var/www/html/goaccesss/goaccess/index.html` into NGinX.

As I said earlier, You can see this into `error.log`.

I hope I have helped.

**Comment by Eliesemoule** [comment]
Hello @0bi-w6n-K3nobi 

I'm really confuse about this stupid mistake. It's work fine after remove `goaccess` from root variable.

Thanks a lot for your help

**Comment by 0bi-w6n-K3nobi** [comment]
Hi, @Eliesemoule.

You don't have to feel that way.
This is a common mistake.
Especially if you work with Apache and Alias.
Usually Apache removes `/something` from the `URL`, in which case it would work with you thought.

You Wellcome!
