### ISSUE TITLE
Custom log parsing JSON in GoAccess

### ISSUE THREAD

**Issue by vishal2232** [allinurl/goaccess#2022]
doesn't match specifier '%d'
==24522== Parsed 10 lines producing the following errors:
==24522==
==24522== Token '"05/Feb/2021' doesn't match specifier '%d'
==24522== Token '"05/Feb/2021' doesn't match specifier '%d'
==24522== Token '"05/Feb/2021' doesn't match specifier '%d'
==24522== Token '"05/Feb/2021' doesn't match specifier '%d'
==24522== Token '"05/Feb/2021' doesn't match specifier '%d'

sample logs

    { "time_kcs": "06/Feb/2021:17:53:24 +0000", "remote_addr_kcs": "X.X.X.X", "remote_user_kcs": "-", "body_bytes_sent_kcs": "0", "request_time_kcs": "0.003", "host_called_kcs": "www.example.com", "status_kcs": "200", "request_uri_kcs": "/", "request_method_kcs": "HEAD", "http_referrer_kcs": "-", "http_user_agent_kcs": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3579.0 Safari/537.36" }

using below log format

    --log-format='%^:"%d:%t"%^:"%h"%^:%^:"%R"%^:"%b"%^:"%T"%^:"%v"%^:"%s"%^:"%U"%^:"%m"%^:"%R"%^:"%u"%^' --date-format='%d/%b/%Y' --time-format='%T' -H no

**Comment by allinurl** [comment]
Please make sure to take into account the spaces in between. e.g., `"time_kcs": "06/Feb/2021:17:53:24 +0000"` should be `%^: "%d:%t %^"` etc.

Or you can use the JSON parser, probably easier. Here an [**example**](https://github.com/allinurl/goaccess/issues/1768#issuecomment-755792463) of how it works.

**Comment by vishal2232** [comment]
@allinurl  i'm still facing after --log-format=CADDY

==31660== Parsed 10 lines producing the following errors:
==31660==
==31660== IPv4/6 is required.
==31660== IPv4/6 is required.
==31660== IPv4/6 is required.
==31660== IPv4/6 is required.
==31660== IPv4/6 is required.
==31660== IPv4/6 is required.
==31660== IPv4/6 is required.
==31660== IPv4/6 is required.
==31660== IPv4/6 is required.
==31660== IPv4/6 is required.
==31660==
==31660== Format Errors - Verify your log/date/time format

Can you please help me to get the required format.

**Comment by allinurl** [comment]
Since your format does not look like a Caddy format, then you have to specify it as a JSON format. Assuming you have the latest version, this should  do it;

    goaccess access.log --log-format='{ "time_kcs": "%d:%t %^", "remote_addr_kcs": "%h", "remote_user_kcs": "%e", "body_bytes_sent_kcs": "%b", "request_time_kcs": "%T", "host_called_kcs": "%v", "status_kcs": "%s", "request_uri_kcs": "%U", "request_method_kcs": "%m", "http_referrer_kcs": "%R", "http_user_agent_kcs": "%u" }' --date-format=%d/%b/%Y --time-format=%T


![2021-02-07-085726_663x165_scrot](https://user-images.githubusercontent.com/5005367/107150245-85d40000-6922-11eb-88b6-a72cc4346dc2.png)

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
