### ISSUE TITLE
Unable to see username using combined log format

### ISSUE THREAD

**Issue by vvvchi** [allinurl/goaccess#2026]
Hi,
I'm running latest goaccess-1.4.5 and kicked off a real time report.
`goaccess /var/log/httpd/ssl_access_log* -o /var/www/html/report.html --log-format=COMBINED --real-time-html`

Everything looks great except I can't see the usernames.  All it shows is unique visitors.  I can confirm the ssl_access_log has my username, and the conf is using the combined format.

`LogFormat "%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" combined`

log snippet (replaced data with fake names for demonstration)

`10.10.10.10 - vchi [10/Feb/2021:08:46:58 +0000] "GET /mydir/dir1/ HTTP/1.1" 200 6 "https://webserver.domain.com/secure/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0"`

Any help would be great.
Thanks

**Comment by allinurl** [comment]
You will need to use the format as:

    goaccess /var/log/httpd/ssl_access_log* -o /var/www/html/report.html --real-time-html --log-format='%h %^ %e [%d:%t %^] "%r" %s %b "%R" "%u"' --date-format=%d/%b/%Y --time-format=%T

**Comment by vvvchi** [comment]
Perfect!  Thanks for the quick response as well.
