### ISSUE TITLE
Error:A request is required

### ISSUE THREAD

**Issue by pranalipagariya-1990** [allinurl/goaccess#2028]
I'm getting below error
```
==543== GoAccess - Copyright (C) 2009-2020 by Gerardo Orellana

==543== https://goaccess.io - <hello@goaccess.io>
==543== Released under the MIT License.
==543==
==543== FILE: access.log
==543== Parsed 4 lines producing the following errors:
==543==
==543== A request is required.
==543== A request is required.
==543== A request is required.
==543== A request is required.
==543==
==543== Format Errors - Verify your log/date/time format

```

my log file has

```
23.1.17.201 - - [12/Feb/2021:11:15:56 +1100] 0 "GET /health.txt HTTP/1.1" 200 26 "-" "-" "-"
23.1.17.2 - - [12/Feb/2021:11:15:56 +1100] 0 "GET /images HTTP/1.1" 200 26 "-" "SPS 12.5 0 0" "-"
23.1.17.2 - - [12/Feb/2021:11:15:59 +1100] 0 "GET /scripts HTTP/1.1" 200 26 "-" "SPS 12.5 0 0" "-"
23.1.17.202 - - [12/Feb/2021:11:15:59 +1100] 0 "GET /health.txt HTTP/1.1" 200 26 "-" "-" "-"
```

I'm using 
`goaccess.exe access.log -o report.html --log-format '%h %^ %^ [%d:%t %^] %T "%^" %s %b "%^" "%^" "%^"'  --time-format='%H:%M:%S'  --date-format='%d/%b/%Y'`

Not sure what request its looking for.
someone please assist.

**Comment by allinurl** [comment]
This should do it:

    goaccess access.log --log-format='%h %^[%d:%t %^] %T "%r" %s %b %^' --date-format=%d/%b/%Y --time-format=%T --ignore-panel=OS --ignore-panel=BROWSERS --ignore-panel=REFERRING_SITES -o report.html

**Comment by pranalipagariya-1990** [comment]
thanks, worked fine. can you please explain the fix?

**Comment by allinurl** [comment]
It seems like you missed adding `"%r"` for the request as you can see on my response.
