### ISSUE TITLE
Question about Dashboard and search

### ISSUE THREAD

**Issue by matheusvs1** [allinurl/goaccess#2032]
First i have to say, thank for the program i really enjoying study it  :smile:

Now the question, based on this image:

![novo_titulo](https://user-images.githubusercontent.com/65990907/108209380-fe984080-7108-11eb-815c-a9065142392d.png)

For exemplo this PW00125, is possible to have another  search to look all the 1751 Hits and make the same analiys? in another words, istead of put all PW00125 in one group and create a line, put the single hit in a line, create a serch of 1751 line for each hits of PW00125?

I hope you undertands what i'm try to say :sweat_smile:

**Comment by allinurl** [comment]
Sorry I'm not sure I follow. 1751 is the number of hits for that /consultar page. You can always pre-process the log, please take a look at the examples under the [**man page**.](https://goaccess.io/man#examples) e.g.,

    grep 'PW00125/consultar' access.log | goaccess - --log-format='%h [%d:%t %^] "%r" %s %L %^"%u"' --date-format=%d/%b/%Y --time-format=%T

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
