### ISSUE TITLE
How to view the HTML dashboard

### ISSUE THREAD

**Issue by cynyap** [allinurl/goaccess#2033]
Good evening,

Would like to inquire how to create the HTML Dashboard. I am using an EC2 instance with nginx and SSH into it on ubuntu. I am able to get the terminal output through goaccess /var/log/nginx/access.log but I'm not sure how to get the HTML version to run on my google chrome browser with my ipv4 address. I used this goaccess /var/log/nginx/access.log -a -o report.html but simply typing my ip4 addresds/report.html on my browser gives me 404 not found

![Capture](https://user-images.githubusercontent.com/79317896/108516472-3c5fb980-7301-11eb-8547-52475338a942.JPG)

**Comment by allinurl** [comment]
You will need to place your `report.html` in your document root of your web server such as nginx. For instance, /var/www/mywebsite/report.html

    goaccess /var/log/nginx/access.log -o /var/www/mywebsite/report.html 

Then you can open the report by navigating to mywebsite.com/report.html

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
