### ISSUE TITLE
Parsing custom log without IP with backslashes in log format

### ISSUE THREAD

**Issue by lunous01** [allinurl/goaccess#2041]
Hi, I'm trying to parse a custom nginx log 
but can't get it to work to skip one letter -> "\"
seems like it's getting stuck on somewhere
`[23/Feb/2021:23:59:59 +0900] 1614092399.744 \"GET /service/info`

my log-format 
`%^[%d:%t %^] %T %^\ %m %q`

Keeps on skiping `\"G`
so I get Error like this

`Token 'ET /service/info' doesn't match specifier '%m'`

*Can't use %r for special purpose.
Thank in advance for your help

**Comment by allinurl** [comment]
You need a valid IPv4/6, if you have, this would work:

```
goaccess access.log --log-format='[%d:%t %^] %T %^"%m %U' --date-format=%d/%b/%Y --time-format=%T
==3576154== GoAccess - Copyright (C) 2009-2020 by Gerardo Orellana
==3576154== https://goaccess.io - <hello@goaccess.io>
==3576154== Released under the MIT License.
==3576154==
==3576154== FILE: log
==3576154== Parsed 1 lines producing the following errors:
==3576154==
==3576154== IPv4/6 is required.
```

If you really want to make it work, you could try substituting the TZ as a bogus IP and use `--no-ip-validation`:

    goaccess access.log --log-format='[%d:%t %h] %T %^"%m %U' --date-format=%d/%b/%Y --time-format=%T --no-ip-validation

**Comment by lunous01** [comment]
Oh. Couldn't think of that,
I just went on and ignored some fussing letters.

log-format :
`date-format %d/%b/%Y log-format %^ %^ %^ %f %^ %^ %h - %^ [%d:%t %^] %^ %^\\" %m %w %H %s %b %U "%R" "%u" "%^"`


Sample Log :
`Feb 23 23:59:59 1614092399.745044 k014 nginx: 14.52.252.178 - - [23/Feb/2021:23:59:59 +0900] 1614092399.744 \"GET /webmail/lists/ajax?&s_fnum=1&s_mread=&mdl=lists HTTP/2.0\" 200 34368 \"https://mail.eia-is.com/mail/lists\" \"Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; rv:11.0) like Gecko\" \"-\" - 0.141","fields":{"topic":"sv01-nginx-access-topic"}}`

Still seems like it's missing some data though. And some funny numbers on t.s.
(What does t.s. stand for?)
![TS_ERROR02](https://user-images.githubusercontent.com/68853239/109089663-f4072800-7754-11eb-98e8-67817a2fd1e8.PNG)

**Comment by mahesh-kore** [comment]
Can someone please help to parse below custom JSON log

Nginx Logformat

log_format logjson '{ "@timestamp": "$time_iso8601", '
'"msec": $msec, '
'"remote_addr": "$remote_addr", '
'"x_forwarded_for": "$proxy_add_x_forwarded_for", '
'"remote_port": "$remote_port", '
'"pipelined": "$pipe", '
'"body_bytes_sent": "$body_bytes_sent", '
'"bytes_sent": $bytes_sent, '
'"request_time": $request_time, '
'"upstream_response_time": "$upstream_response_time", '
'"upstream_response_length": "$upstream_response_length", '
'"upstream_status": "$upstream_status", '
'"kore_route": "$upstream_http_x_route", '
'"koreserver": "$upstream_http_server", '
'"host": "$host", '
'"hostname": "$hostname", '
'"server_name": "$server_name", '
'"request_completion": "$request_completion", '
'"status": $status, '
'"connection_requests": $connection_requests, '
'"request_uri": "$request_uri", '
'"request_method": "$request_method", '
'"request_content_type": "$content_type", '
'"request_content_length": "$content_length", '
'"request_total_length": $request_length, '
'"args": "$args",'
'"is_args": "$is_args", '
'"x-traceid":"$upstream_http_x_traceid", '
'"http_user_agent": "$http_user_agent" }';

Sample Loglines:

{ "@timestamp": "2021-02-23T08:27:47+00:00", "msec": 1614068867.506, "remote_addr": "172.1.0.32", "x_forwarded_for": "172.1.0.32", "remote_port": "2431", "pipelined": ".", "body_bytes_sent": "46", "bytes_sent": 710, "request_time": 0.010, "upstream_response_time": "0.012", "upstream_response_length": "46", "upstream_status": "401", "kore_route": "-", "koreserver": "KoreServer/", "host": "wb-bots.korebots.com", "hostname": "app-57c5bc4bb7-4m2r2", "server_name": "_", "request_completion": "OK", "status": 401, "connection_requests": 2, "request_uri": "/api/1.1/rtm/start", "request_method": "POST", "request_content_type": "application/json", "request_content_length": "122", "request_total_length": 729, "args": "-","is_args": "", "x-traceid":"-", "http_user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36" }

{ "@timestamp": "2021-02-23T08:27:47+00:00", "msec": 1614068867.926, "remote_addr": "172.1.0.32", "x_forwarded_for": "172.1.0.32", "remote_port": "2431", "pipelined": ".", "body_bytes_sent": "53", "bytes_sent": 698, "request_time": 0.008, "upstream_response_time": "0.008", "upstream_response_length": "53", "upstream_status": "401", "kore_route": "-", "koreserver": "KoreServer/", "host": "wb-bots.korebots.com", "hostname": "app-57c5bc4bb7-4m2r2", "server_name": "_", "request_completion": "OK", "status": 401, "connection_requests": 3, "request_uri": "/api/1.1/users/sts?rnd=wb729", "request_method": "POST", "request_content_type": "application/json;charset=UTF-8", "request_content_length": "2", "request_total_length": 861, "args": "rnd=wb729","is_args": "?", "x-traceid":"-", "http_user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36" }

**Comment by 0bi-w6n-K3nobi** [comment]
Hi @lunous01.

I believe that strange behavior is due to field `%f`. 
You maybe be confused, but this field is `TIMESTAMP` -- i.e. date-time that corresponds to field `%x`.

Then, You can try this into `goaccess.conf`:
`log-format` `%^ %^ %^ %^ %^ %^ %h - %^[%d:%t %^] %^"%r\\%^ %s %b  %^"%R\\%^ %^"%u\\%^ %^ %^ %T"`

Yeap. I believe that value `0.141` be what you look for, that corresponds to field `%T`.

**note:**
@allinurl ... I had difficulties to parse fields like `\\"value\\"`...
I understand this for field `%r`... but I had problems too parse `%R` and `%u`.
The workaround that I found was to use `%^"%R\\%^ `, without prejudice to the next field.
I used version `1.4.4`.

I hope I've helped.

**Comment by allinurl** [comment]
@0bi-w6n-K3nobi Thanks for chiming in. You are right, there's an escaping issue that makes it more difficult to parse @lunous01 post. I was looking at it and see how I can resolve it. I'll post back as soon as I have some news on this.

**Comment by allinurl** [comment]
@lunous01 This should be fixed upstream. Please feel free to build from [development](https://github.com/allinurl/goaccess#build-from-github-development) to test it out. It will be pushed on in v1.4.6 soon. Format should be: 

    goaccess access.log --log-format='%^.%^ %v %^: %h %^[%d:%t %^] %^ \\"%r\\" %s %b \\"%R\\" \\"%u\\" %^ %^ %T"%^' --date-format=%d/%b/%Y --time-format=%T -o report.html
