### ISSUE TITLE
report not generated

### ISSUE THREAD

**Issue by GrepZen** [allinurl/goaccess#2043]
'lo All,
I've installed GoAccess on my  Debian/Apache2 webserver and am having some trouble getting GoAccess to generate output.

--TheCommand:
goaccess /var/log/apache2/other_vhost_access.log -o /f1/websites/80_home/html/goaccess/index.html --log-format=VCOMBINED --real-time-html
--TheOutput:
Daemonized GoAccess: 3438

...Yet the file:[/f1/websites/80_home/html/goaccess/index.html]  is never created.
There is no error text.
there is no existing ~index.html file

and ps aux | 3438 yields no output either.

--TheRequest:
Can any of you lend some insight on how to troubleshoot/resolve this?

**Comment by allinurl** [comment]
Please don't daemonize the process and check for any errors you may be getting. Also make sure you can write to that path.

**Comment by allinurl** [comment]
Any updates on this?

**Comment by GrepZen** [comment]
Allinurl  .. two things
1st ... Thank you so much for the follow up on this.  Time had gotten away from me and this reminder helped me close a task. --Thank You!
2nd ... I ran w/o daemonizing and was able to see errors (log file path) that readily lead to solution.  GoAccess is now performing well and displaying beautifully.  Thank you again!
