### ISSUE TITLE
Look for a Maintainer

### ISSUE THREAD

**Issue by szepeviktor** [allinurl/goaccess#2048]
@allinurl Please look for a maintainer.
There are **six years** old open issues.

**Comment by allinurl** [comment]
Viktor, rest assured the project is actively maintained  - nonetheless, I do appreciate your concern about taking care of old issues but as you know, there are priority issues that have and need to be addressed before any other. If there are issues that you would like to help or if you know of someone who would like to speed up some requests, by all means, feel free to submit a PR.

Closing this as I don't think there is need for a maintainer.

**Comment by szepeviktor** [comment]
Okay.
