### ISSUE TITLE
3xx shouldn't count as failed visitors

### ISSUE THREAD

**Issue by overnine** [allinurl/goaccess#205]
In the following JSON example output I fail to understand why 304 corresponds to a failed request:

https://gist.github.com/overnine/efcdba67409fe054f6dc

It should be clear that the client did not recieve a unwanted response, but instead already had the correct response in cache?

Would you consider changing this sometime or alternatively enlighten me as to what I'm missing?

**Comment by allinurl** [comment]
Could you please post the original JSON output? or if you have the 8 requests from your access log, that would work too. Thanks.

**Comment by overnine** [comment]
This is the original, simply with some names replaces as i would like those to be confidential ;)The u's are just unicode labels from python!

You can try these logs, those should be able to recreate the behaivour: https://gist.github.com/overnine/50cfc2c398511c063d4d

**Comment by allinurl** [comment]
From your sample log, I get only 1 failed request which is the blank line. https://gist.github.com/allinurl/c21e38db39eaeb1c0839

Do you get the same output?

**Comment by overnine** [comment]
Hmm, okay wow, I guess i wasn't expecting goaccess to handle those as failed requests, you're right that this is the cause. I guess you consider that an error from my programming then?

**Comment by allinurl** [comment]
It seems like the number of failed requests are not being mapped correctly during the post-processing that you are doing to the JSON file. Feel free to compare the original JSON report to yours to identify the issue.

**Comment by allinurl** [comment]
Closing this since it doesn't seem to be an error on the JSON report. Feel free to reopen it if needed.
