### ISSUE TITLE
goaccess demands gettext

### ISSUE THREAD

**Issue by hdatma** [allinurl/goaccess#2050]
```
Only one dependency
GoAccess is written in C. To run it, you only need ncurses as a dependency. That's it. It even features its own Web Socket server — http://gwsocket.io/.
```

This is not true. The configuration fails when libintl (gettext) is not installed. The option "--disable-nls" is ignored.

**Comment by allinurl** [comment]
There's a note on the [download page](
https://goaccess.io/download#installation):

> Note: You may need to install build tools like gcc, autoconf, gettext, autopoint etc for compiling/building software from source. e.g., base-devel, build-essential, "Development Tools".

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
