### ISSUE TITLE
Token '134>Feb  8 11' doesn't match specifier '%d'

### ISSUE THREAD

**Issue by Lsytnyk** [allinurl/goaccess#2051]
Hello. Please help me parse log.
Format: 
<134>Feb  8 11:44:00 haproxy[888]: 192.168.103.203:37776 [08/Feb/2021:11:44:00.092] in-75-m-local -mobile/app 1/0/0/4/5 200 268 - - ---- 2128/102/41/5/0 0/0 "GET /service/api/oauth/verify HTTP/1.1"

I tried 

 goaccess accesslog --log-format='[%d:%t %^] %^=%h %^="%r" %s %^=%b %
^' --date-format='%d/%b/%Y' --time-format=%T
Parsed 1 linesproducing the following errors:

Token '134>Feb  8 11' doesn't match specifier '%d'

and many otger queries. But still have errors

**Comment by allinurl** [comment]
Hello. Could you please describe all the fields in your log format? e.g., 2128/102/41/5/0, etc

**Comment by 0bi-w6n-K3nobi** [comment]
Hi @Lsytnyk .

Can You show `HAProxy` logformat for this?

thanks.

**Comment by allinurl** [comment]
Closing this. Feel free to share those fields/reopen it if needed.
