### ISSUE TITLE
Got this error while trying to parse an access.log in v1.4.5

### ISSUE THREAD

**Issue by maetthew** [allinurl/goaccess#2055]
Hi,

I tried to parse an access.log with `goaccess access.log --log-format=CLOUDSTORAGE` and something wonky happened, not sure what, but the message told me to post here so here goes:

```
==131853== STACK TRACE:
==131853==
==131853== 0 goaccess(sigsegv_handler+0x1ae) [0x55ecda3842be]
==131853== 1 /lib64/libpthread.so.0(+0x141e0) [0x7ff034a141e0]
==131853== 2 /lib64/libc.so.6(+0x162605) [0x7ff034995605]
==131853== 3 goaccess(ht_insert_json_logfmt+0x51) [0x55ecda3946b1]
==131853== 4 goaccess(parse_json_string+0x1e5) [0x55ecda3a57a5]
==131853== 5 goaccess(+0x3b67d) [0x55ecda3a867d]
==131853== 6 goaccess(main+0x289) [0x55ecda381e49]
==131853== 7 /lib64/libc.so.6(__libc_start_main+0xf2) [0x7ff03485b1e2]
==131853== 8 goaccess(_start+0x2e) [0x55ecda383cbe]
==131853==
==131853== Please report it by opening an issue on GitHub:
==131853== https://github.com/allinurl/goaccess/issues
 
Segmentation fault (core dumped)

```

**Comment by allinurl** [comment]
Thanks for reporting this. Can I ask, what version are you running?

**Comment by maetthew** [comment]
> Thanks for reporting this. Can I ask, what version are you running?

1.4.5

Installed through dnf on Fedora 33

**Comment by allinurl** [comment]
I see. Yeah sounds like that particular issue was fixed in v1.4.6 in addition to other JSON stuff. Would you be able to upgrade to [**v1.4.6**](https://github.com/allinurl/goaccess#build-from-release) and let me know if that solves the issue on your end? Thanks

**Comment by marclr** [comment]
I had the same issue with Fedora 33 and goaccess 1.4.5. After updating to 1.4.6 everything is working fine.

**Comment by allinurl** [comment]
Closing this as it should be fixed in the latest version. Feel free to reopen it if needed.
