### ISSUE TITLE
images on html report behind apache vhost

### ISSUE THREAD

**Issue by seem8** [allinurl/goaccess#2057]
Hi.

Thank You for a great piece of software. It saves me again and again.

I have trouble with displaying a static html report behind apache vhost. Page works normally with styles and javascipt, except the are no images. Instead of them the are werid rectangles with F0B0, F0C0, FI5B, etc... 

I generate page every hour with a script:

#!/usr/bin/bash

cd /var/www/stat.somepage.pl
cat /var/www/somepage.pl/log/access.log /var/www/somepage.pl/log/errors.log > log1
sed 's/\"//g' log1 > log2

goaccess --log-file=log2 --log-format "%h %^ %^ [%d:%t %^] %m %U %H %s %b - %u" --date-format="%d/%b/%Y" --time-format="%H:%M:%S" --html-prefs='{"theme":"bright","perPage":20,"layout":"vertical","showTables":true}' -a -o public_html/index.html

chown root:stat.somepage.pl public_html/index.html
chmod 640 public_html/index.html

-------------------------------------------------------------------------------------------------------

Here is the host. I tried to disable htpassword, but it didn't help.

<VirtualHost *:80>
  ServerName stat.somepage.pl
  Redirect permanent / https://stat.somepage.pl/
< / VirtualHost>

<VirtualHost *:443>
  ServerName stat.somepage.pl
  DocumentRoot /var/www/stat.somepage.pl/public_html
  AssignUserID stat.somepage.pl stat.somepage.pl

  <Directory "/var/www/stat.somepage.pl">
    AuthType Basic
    AuthName "restricted"
    AuthUserFile /etc/apache2/htpasswd_stat
    Require valid-user
    AllowOverride All
    Options +FollowSymLinks -Indexes
  < / Directory>
  
  Include /etc/letsencrypt/options-ssl-apache.conf
  SSLCertificateFile /etc/letsencrypt/live/stat.somepage.pl/fullchain.pem
  SSLCertificateKeyFile /etc/letsencrypt/live/stat.somepage.pl/privkey.pem

< / VirtualHost>

**Comment by allinurl** [comment]
Glad to hear you found it useful :)

Can I ask what version of goaccess are you running? If not the latest (v1.4.6), please upgrade to the latest. 

Also, are you able to download the report to your local machine and open the report directly in the browser (Ctrl+o) to see if that solves the issue? and last, are you getting any errors in the browser's console?

Thanks

**Comment by seem8** [comment]
Thank You. It's a Debian, so goaccess bersion was a little behind. I pulled newest version from unstable repository and the problem is fixed.

Sorry for bringing something that trivial. :)

Take care.

**Comment by allinurl** [comment]
No worries. Glad that fixed it.
