### ISSUE TITLE
ignore-referer does not seem to work

### ISSUE THREAD

**Issue by dertuxmalwieder** [allinurl/goaccess#2059]
I use the `ignore-referer=mydomain.tld` parameter with GoAccess:

```bash
#!/bin/bash
goaccess --log-file=$HOME/logs/webserver/access_log --log-format=COMBINED --persist --restore --agent-list --real-os --db-path=$HOME/goaccess.db/ --ignore-referer=mydomain.tld --ignore-referer=*.mydomain.tld --output=$HOME/html/stats/index.html
```

Yet, `mydomain.tld` is the most common referrer in the HTML file. What am I missing?

Version information:

```
goaccess 1.4.6
--enable-utf8
--enable-geoip=legacy
--with-openssl
```

*edit:* `--hide-referer` works - but what does `ignore-referer` even **do** then?

**Comment by JulianGro** [comment]
Just to make sure: It is spelled "referrer" not "referer".
At the very least that is how it is spelled in the documentation and how it (somewhat) works for me.
I saw "somewhat" because the wildcards don't work properly for me.

**Comment by allinurl** [comment]
Closing this. `--ignore-referer` works as expected in v1.7.2

![2023-04-24 13-57](https://user-images.githubusercontent.com/5005367/234090502-3c3911ed-70ca-4cbd-aa82-3989130246b6.gif)
