### ISSUE TITLE
Support for GeoIP Country IPv6 and GeoIP City IPv6

### ISSUE THREAD

**Issue by crepererum** [allinurl/goaccess#206]
Currently, only IPv4 databases are supported. When trying to use a IPv6 database, I get `Invalid database type GeoIP City Edition V6, Rev 1, expected GeoIP City Edition, Rev 1`. Free versions of the databases can be downloaded here: https://www.maxmind.com/en/ipv6

**Comment by allinurl** [comment]
Thanks for reporting this, I'll look into this and post back.

**Comment by allinurl** [comment]
Support for GeoIP Country IPv6 and GeoIP City IPv6 has been implemented. Using `--geoip-database` will allow you to set the database file. 

Feel free to build from development, or else it will be pushed out in the upcoming version. Thanks!

**Comment by aharoy1** [comment]
I'm working with C++ code. How do I use the --geoip-database flag?
On which version it is supported?

**Comment by allinurl** [comment]
@aharoy1 You need to download the GeoIP database file and run goaccess as:

 # goaccess -f access.log --geoip-database=GeoLiteCity.dat

Please take a look at the [config file](https://github.com/allinurl/goaccess/blob/master/config/goaccess.conf#L445) for more details

**Comment by aharoy1** [comment]
I'm getting:
GoAccess - version 0.8 - May 21 2014 02:43:56

An error has occurred
Error occured at: geolocation.c - geoip_open_db - 68
Message: Unable to open GeoIP City database.

**Comment by allinurl** [comment]
@aharoy1 Please make sure you are using the latest version of goaccess and that you have the right permissions to access the file.

**Comment by evgenij8585** [comment]
without downloading the database, you can connect to IpV6 here [https://location.ekolesnyk.com/api/](https://location.ekolesnyk.com/api/)
