### ISSUE TITLE
Hostname doesn't match specifier %h

### ISSUE THREAD

**Issue by Alex-C96** [allinurl/goaccess#2060]
ppp-mia-30.shadow.net - - [01/Jul/1995:00:00:41 -0400] "GET /images/NASA-logosmall.gif HTTP/1.0" 200 786

Token 'ppp-mia-30.shadow.net' doesn't match specifier '%h'

Is it possible to read the hostname without it being ipv4 or ipv6?

**Comment by allinurl** [comment]
Please try using `--no-ip-validation`.

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.

**Comment by Alex-C96** [comment]
Thank you!
