### ISSUE TITLE
FreeBSD recognized as Linux

### ISSUE THREAD

**Issue by fekir** [allinurl/goaccess#2062]
````
echo '192.168.1.1 - - [23/Mar/2021:04:01:15 +0100] "GET example.com HTTP/2.0" 200 3606 "https://duckduckgo.com/" "Mozilla/5.0 (X11; FreeBSD amd64; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36"' | goaccess --log-format='COMBINED'
````

navigate to `6 - Operating Systems`, it shows `Linux`, the expected value would have been `FreeBSD`

**Comment by allinurl** [comment]
Thanks for reporting this. Can I ask, do you know why it shows Linux?

**Comment by allinurl** [comment]
This should be fixed upstream and will be deployed in the upcoming version. Thanks again!
