### ISSUE TITLE
Inaccurate number of requested files

### ISSUE THREAD

**Issue by chenss115472** [allinurl/goaccess#2063]
Hello, after many times of analysis and comparison, I found that the number of request files analyzed by goaccess is incorrect, I don't know how to proofread!
![20210325093029](https://user-images.githubusercontent.com/80434236/112405552-77646b00-8d4d-11eb-802e-0d3084497c2a.jpg)
![20210325093034](https://user-images.githubusercontent.com/80434236/112405556-78959800-8d4d-11eb-87e1-ac352b20b2c6.jpg)

**Comment by 0bi-w6n-K3nobi** [comment]
Hi @chenss115472 .

You can see that `Static Files` are not part of `Requested Files (URLs)` .
So... You  must subtract it before accounting.

I hope it helped you.

**Comment by allinurl** [comment]
@0bi-w6n-K3nobi is right, you need to add up 404s and static files.

**Comment by chenss115472** [comment]
@allinurl @0bi-w6n-K3nobi Thank you for your reply, according to your request file + 404s and static files, but I found that this is better than using awk '{print $7}' access.log |The total number of sort | uniq - C | sort - N - K 1 - R | WC - L statistics is more than ten.

Sorry, I found another problem on my side. When analyzing uncompressed logs and tar compressed logs, zcat - F access.log.tar .gz | goaccess -o /opt/access-tar-05.html -p /usr/local/etc/goaccess/ goaccess.conf All requests will be one less and the number of failed requests will be one more.
![捕获](https://user-images.githubusercontent.com/80434236/112779377-346e0480-9079-11eb-8c81-2e62c33662c5.JPG)
![捕获1](https://user-images.githubusercontent.com/80434236/112779391-3932b880-9079-11eb-8619-7049263f377a.JPG)

**Comment by 0bi-w6n-K3nobi** [comment]
Hi @chenss115472.

For 2nd issue: Did you unzip and test it with the final file? 
Which seems to me that you missed one request and broked/corrupted another.

For 1st issue: Interesting...  the difference was 24 more in the sum of the panel.
Did you check if any requests returned 404 at first and then after 200? That would explain the difference.

I hope it helped you.

**Comment by chenss115472** [comment]
Hi  @allinurl @0bi-w6n-K3nobi .
The second problem: the compressed log has been analyzed and tested, and the test result is normal, which is the same as that of the uncompressed log.

The first question: after searching the number of request files, 404s files and static files in the test, it is found that the total number of requests in each module is correct, but the total number of files is not right. I don't know what other methods can find the correct answer.
thank!
![1](https://user-images.githubusercontent.com/80434236/113086355-0a9d1500-9214-11eb-8baf-6acdc3f7d8e0.JPG)
![2](https://user-images.githubusercontent.com/80434236/113086365-0d980580-9214-11eb-8ca0-af6680f317b4.JPG)

**Comment by chenss115472** [comment]
Hi @allinurl  @0bi-w6n-K3nobi .
I don't know if there are other ways to use goaccess to count all the requested files, including static files and 404s files..

**Comment by allinurl** [comment]
Do you mind sharing that specific access log so I can take a look? If you prefer not to attach it here, you can send it to hello [at] goaccess.io. Thanks!

**Comment by 0bi-w6n-K3nobi** [comment]
Hi @chenss115472 .

Well... See if I understand you correctly. 
Do you want count requests that be different/unique?
Regardless of whether they are `files`, `statics` or `not found`.

**Comment by allinurl** [comment]
@chenss115472 wanted to follow up and mak sure it is working now for you. Please let me know.

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
