### ISSUE TITLE
Feed readers on macOS are incorrectly shown as Darwin

### ISSUE THREAD

**Issue by dertuxmalwieder** [allinurl/goaccess#2068]
From my current website statistics:

<img width="535" alt="Bildschirmfoto 2021-03-28 um 19 59 39" src="https://user-images.githubusercontent.com/125629/112762495-38117500-9000-11eb-9a8b-7d0510dbf369.png">

That looks wrong to me. (Especially the Safaris.)

**Comment by allinurl** [comment]
Thanks for reporting this. Could you post the whole request for some of these so I can take a look at where exactly the issue is? Thanks!

**Comment by dertuxmalwieder** [comment]
The latest three request from both Safari and Reeder:

```
access_log.4:80.108.0.0 - - [25/Mar/2021:23:19:53 +0100] "HEAD /apple-touch-icon-precomposed.png HTTP/2.0" 404 0 "-" "Reeder/4020.89.01 CFNetwork/1237 Darwin/20.4.0"
access_log.4:37.201.0.0 - - [26/Mar/2021:01:46:48 +0100] "GET /blog/feed/ HTTP/2.0" 200 29977 "-" "Reeder/4020.89.01 CFNetwork/1220.1 Darwin/20.3.0"
access_log.4:37.201.0.0 - - [26/Mar/2021:02:04:58 +0100] "GET /blog/feed/ HTTP/2.0" 304 0 "-" "Reeder/4020.89.01 CFNetwork/1220.1 Darwin/20.3.0"
access_log.4:2003:c9:: - - [25/Mar/2021:12:49:31 +0100] "GET /blog/wp-content/uploads/2017/05/cropped-penrose-180x180.png HTTP/2.0" 200 12504 "-" "Safari/14610.4.3.1.7 CFNetwork/978.5 Darwin/18.7.0 (x86_64)"
access_log.4:2003:c9:: - - [25/Mar/2021:18:46:18 +0100] "GET /blog/wp-content/uploads/2017/05/cropped-penrose-180x180.png HTTP/2.0" 200 12504 "-" "Safari/14610.4.3.1.7 CFNetwork/978.5 Darwin/18.7.0 (x86_64)"
access_log.6:2003:c9:: - - [24/Mar/2021:00:13:31 +0100] "GET /blog/wp-content/uploads/2017/05/cropped-penrose-180x180.png HTTP/2.0" 200 12504 "-" "Safari/14610.4.3.1.7 CFNetwork/978.5 Darwin/18.7.0 (x86_64)"
```

It seems that they indeed report to run on Darwin. Makes no sense to me.

**Comment by allinurl** [comment]
I've updated this categorization ([per this commit](https://github.com/allinurl/goaccess/commit/b017769dce988267d1cfdfb6ebd60328e7124df7)) as you mentioned. Please feel free to build from [**development**](https://github.com/allinurl/goaccess#build-from-github-development) and let me know if that solves the issue on your end. Thanks!

![2021-03-30-190656_666x136_scrot](https://user-images.githubusercontent.com/5005367/113071798-1d1f3c00-918b-11eb-80f6-b7dd6b39bfd0.png)

**Comment by dertuxmalwieder** [comment]
Looks good on the first sight. As I configured GoAccess to rotate every two weeks, a long-term statistics would be interesting though. Would you mind to leave this issue open until further research?

**Comment by dertuxmalwieder** [comment]
The issue looks solved to me.
