### ISSUE TITLE
Goaccess 0.8.5 - Fatal Error with nginx default log

### ISSUE THREAD

**Issue by radar155** [allinurl/goaccess#207]
if i type 
 zcat -f /var/log/nginx/-access.log* | goaccess 

got this error:

**GoAccess - version 0.8.5 - Jan 16 2015 17:05:32**

**Fatal error has occurred
Error occured at: goaccess.c - main - 832
Nothing valid to process.**

i'm sure i'm editing the right config file:

**date_format %d/%b/%Y:%T %z
log_format %h %^[%d:%^] "%r" %s %b "%R" "%u"**

log sample:

**22.22.22.22 - - [16/Jan/2015:16:53:54 +0100] "GET / HTTP/1.1" 200 3740 "http://example.com/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.99 Safari/537.36"**

**Comment by allinurl** [comment]
Since goaccess does not use time specifiers at the moment, you can
remove them from the date_format.

date_format %d/%b/%Y

That should do it.

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
