### ISSUE TITLE
GNU+Linux incorrectly referred to as "Linux"

### ISSUE THREAD

**Issue by throwaway1037** [allinurl/goaccess#2071]
GoAccess incorrectly refers to the GNU+Linux operating system as "Linux" in its user interfaces and source code.

GNU is an OS started in 1983 and Linux is a kernel started in 1991. The combination of these two components today forms the GNU+Linux operating system.

See also:
https://www.gnu.org/gnu/linux-and-gnu.html
https://www.gnu.org/gnu/gnu-linux-faq.html
https://www.gnu.org/gnu/why-gnu-linux.html

**Comment by allinurl** [comment]
Please feel free to submit a PR with the relevant changes. Thanks

**Comment by allinurl** [comment]
Merged. Thanks!

**Comment by throwaway1037** [comment]
:)
