### ISSUE TITLE
Log format config help

### ISSUE THREAD

**Issue by bwainstock** [allinurl/goaccess#208]
I'm just playing with goaccess for a simple home server that I have, but I can't seem to get the log format configuration to recognize my log.  I'm using gunicorn behind an nginx proxy, which forwards the real IP ahead.  A sample entry in my log (the first IP is always 127.0.0.1 as that is nginx forwarding the request to gunicorn):

gunicorn log format: 
```
%(h)s %(l)s %(u)s %(t)s “%(r)s” %(s)s %(b)s “%(f)s” “%(a)s” "%({X-Real-IP}i)s"
```
```
127.0.0.1 - - [16/Jan/2015:14:30:15 -0800] "GET /bars/ HTTP/1.0" 200 2660 "-" "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.99 Safari/537.36" "192.168.1.100"
```
> %^ %^ %^ [%d:%^] "%r" %s %b %^ "%u" "%h"

That is the formatting I came up with, but it goaccess can't find any entries.  Any ideas?

**Comment by allinurl** [comment]
Barry, the following should do it:

    log-format %^[%d:%^] "%r" %s %b "%R" "%u" "%h"
    date-format %d/%b/%Y

Let me know how that goes. Thanks

**Comment by bwainstock** [comment]
```
No valid hits.
```

**Comment by allinurl** [comment]
It does parse the sample log you posted above. Are you using v0.8.5? This is how I ran it:

    goaccess -f log --log-format='%^[%d:%^] "%r" %s %b "%R" "%u" "%h"' --date-format='%d/%b/%Y'

**Comment by bwainstock** [comment]
Damn!  There were a few lines at the beginning of my log that didn't fit the format.  Taking them out of the file fixed the "No valid hits" issue.  Everything works now.  Thanks.
