### ISSUE TITLE
Formatting help with custom JSON log

### ISSUE THREAD

**Issue by seanlanglands** [allinurl/goaccess#2083]
GoAccess version: 1.4.6

Hello!

I'm a bit stuck on getting the formatting right on our custom JSON logs. I would really appreciate some help or guidance on where I'm falling short here.

Example log data:
```
{
  "body_bytes_sent": "104",
  "client_site_id": "34234",
  "content_type": "application/json; charset=UTF-8",
  "http_accept_language": "en-US,en;q=0.5",
  "http_host": "example.com",
  "http_referer": "https://example.com/dsfgsdfg",
  "http_user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:86.0) Gecko/20100101 Firefox/86.0",
  "http_version": "HTTP/2.0",
  "http_x_forwarded_for": "",
  "private_file": "",
  "remote_addr": "xxx.xx.xx.xx",
  "remote_user": "",
  "request_time": "0.445",
  "request_type": "POST",
  "request_url": "/sfdgdsfg",
  "scheme": "https",
  "sent_cache_control": "no-cache, must-revalidate, max-age=0",
  "sent_vary": "",
  "sent_x_cache": "pass",
  "ssl_client_verify": "NONE",
  "status": "200",
  "timestamp": "15/Mar/2021:21:57:38 +0000",
  "timestamp_iso8601": "2021-03-15T21:57:38+00:00",
  "tls_version": "TLSv1.3",
  "true_client_ip": "",
  "upstream_country_code": "US",
  "wplogin": "bob"
}
```

I've tried to break down the specifiers like so:

```
{
  "body_bytes_sent": "%b",
  "client_site_id": "%^",
  "content_type": "%M",
  "http_accept_language": "%^",
  "http_host": "%v",
  "http_referer": "%R",
  "http_user_agent": "%^",
  "http_version": "%^",
  "http_x_forwarded_for": "%^",
  "private_file": "%^",
  "remote_addr": "%h:%^",
  "remote_user": "%^",
  "request_time": "%T",
  "request_type": "%m",
  "request_url": "%U",
  "scheme": "%^",
  "sent_cache_control": "%^",
  "sent_vary": "%^",
  "sent_x_cache": "%C",
  "ssl_client_verify": "%^",
  "status": "%s",
  "timestamp": "%^",
  "timestamp_iso8601": "%^",
  "tls_version": "%K",
  "true_client_ip": "%^",
  "upstream_country_code": "%^",
  "wplogin": "%^"
}
```

Here's the formating that I thought should work:

time-format %H:%M:%S

date-format %Y-%m-%e

log-format %^:"%b"%^:"%^"%^:"%M"%^:"%^"%^:"%v"%^:"%R"%^:"%^"%^:"%^"%^:"%^"%^:"%^"%^:"%h"%^:"%^"%^:"%T"%^:"%m"%^:"%U"%^:"%^"%^:"%^"%^:"%^"%^:"%C"%^:"%^"%^:"%s"%^:"%^"%^:"%^"%^:"%K"%^:"%^"%^:"%^"%^:"%^"

**Comment by allinurl** [comment]
This should work:

    goaccess access.log --log-format='{ "body_bytes_sent": "%b", "content_type": "%M", "http_host": "%v", "http_referer": "%R", "http_user_agent": "%u", "http_version": "%H", "remote_addr": "%h", "remote_user": "%e", "request_time": "%T", "request_type": "%m", "request_url": "%U", "sent_x_cache": "%C", "status": "%s", "timestamp": "%d:%t %^", "tls_version": "%K", "wplogin": "%e" }' --date-format=%d/%b/%Y --time-format=%T

**Comment by seanlanglands** [comment]
Thank you! I appreciate the simplicity of that log format solution. However, I'm running into `IPv4/6 is required.` even when using the `--no-ip-validation` flag.

**Comment by allinurl** [comment]
Are the xxx in `"remote_addr": "xxx.xx.xx.xx",` substituted by you? or is that the way you have them in your log? I placed a valid IP in your posted example and the format I posted works fine for me.

**Comment by seanlanglands** [comment]
The above wasn't the case, but I tried on another set of logs and it worked perfectly. Thank you!
