### ISSUE TITLE
Timestamp format issue 

### ISSUE THREAD

**Issue by ErikSlevin** [allinurl/goaccess#2088]
Hello,

sry for my bad englisch...

i cant´t parse my RemoteLogs from my Unifi Devices.
> `2021-04-14T12:55:48+02:00 SecurityGateway kernel: [LAN_LOCAL-default-A]IN=eth1 OUT= MAC=ff:ff:ff:ff:ff:ff:XX:XX:XX:7b:8b:91:08:00 SRC=10.X.X.XXX DST=255.255.255.255 LEN=32 TOS=0x00 PREC=0x00 TTL=64 ID=18017 DF PROTO=UDP SPT=54688 DPT=10001 LEN=12`

has anyone the correct date/time/log format for this?

**Comment by Sergerant** [comment]
GoAccess is a web log analyzer. To analyze log files that a web server produces, when someone visits the website. 'RemoteLogs from Unifi Devices' are no web server access log. So GoAccess won't be suitable for your needs, as far as I can tell.

**Comment by allinurl** [comment]
There is a request to have goaccess parse non-access logs (and/or custom panels), it's still for review though. So far, you can probably parse the log you posted using goaccess but you would end up with no much useful data. Like @Sergerant said, you probably need to use a different tool for now.

Closing this. Feel free to reopen if needed.
