### ISSUE TITLE
set default MAX_CHOICES to 400?

### ISSUE THREAD

**Issue by DavidSewell** [allinurl/goaccess#209]
ui.h has
  #define MAX_CHOICES       300
which controls the maximum number of rows displayed in a report window. This means that if you're parsing a logfile for an entire year, the report on daily visits is truncated sometime in March. I would suggest changing that value to 400 (or at least 366) so that it's not necessary to patch the code to get a full yearly report. 
And eventually that should be a configurable value, per goaccess.1

**Comment by allinurl** [comment]
I have set it to 366 for now. 

I'm working on some major changes on the parsing module, I'll do some profiling before increasing it to 400. Like you said, the plan is to make it a configurable value. Thanks!
