### ISSUE TITLE
Time Distribution panel only works for a day in realtime mode?

### ISSUE THREAD

**Issue by globalistas** [allinurl/goaccess#2096]
I am "goaccessing" my Nginx log and all is working fine. However, after midnight, when a new nginx log is always created and the old one rotates out, the Time Distribution panel just stops working/refreshing. I have observed this behavior for several days now, in fact it has behaved the same ever since I started using Goaccess.

This is a screenshot of it I took this morning:
![image](https://user-images.githubusercontent.com/64347618/116504937-dae83800-a8b9-11eb-893e-012582debe7e.png)

The rest of the panels keep working fine even with the rotated log.

I am running goaccess as follows:

`goaccess /var/log/nginx/access.log -o /var/www/html/report.html --log-format=COMBINED --real-time-html --geoip-database=/home/<myuser>/city.mmdb --ignore-crawlers --ignore-panel=REQUESTS_STATIC --ignore-panel=STATUS_CODES --ignore-panel=NOT_FOUND --ignore-panel=GEO_LOCATION --origin=https://my.domain --ws-url=wss://my.domain/wss/ --addr=127.0.0.1 --daemonize` 

Any ideas? Thank you.

**Comment by 0bi-w6n-K3nobi** [comment]
Hi @globalistas 

Yeah...  a pleasure to see you again.

Look more closely ... that I knew, in fact, this panel will accumulate the values day after day.
The only parameter that can change this is `--keep-last`. Setting it to 1 will keep the data for just 1 day.
The default [no set] is `zero` == `infinite`.

You can confirm what that I'm saying by running offline.
I.E. running over more than one `LOGFILE` from previous days.

**Comment by globalistas** [comment]
Ah OK, so it' sactually accumulating the values. Good to know, as I thought it was just stuck.

Thanks, I will possibly use the '--keep-last=1' setting, although it sounds like it affects all panels, not just the TD one.

**Comment by 0bi-w6n-K3nobi** [comment]
Yeah... All panels.
After midnight, it will clear data panels. Or better, after first new day data.
Do see if it is exactly that you want.
Remember too that GoAccess accumulate data in memory, and `--keep-day` adjust how many time will be it.

**Comment by 0bi-w6n-K3nobi** [comment]
Well.... I programming to restart every day after midnight.
And it lead a good and smart behaviour for server [GoAccess] and client [browser].
Firstly, it will release memory from GoAccess.
Second, the browser will be show exactly shot before GoAccess stop -- I.E. before midnigth.
And this way a have, in next morning, a summary of all day back.

Of course, for continue monitoring I need refresh the page.

**Comment by 0bi-w6n-K3nobi** [comment]
other way of made same:

Running GoAccess in offline mode, processing the day back and create a static html report.

**Comment by 0bi-w6n-K3nobi** [comment]
Tip:

Take a look in option `--html-refresh`.
It will reduce CPU load and stretches interval between update into browser.

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
