### ISSUE TITLE
Monthly report from cron is generating empty file

### ISSUE THREAD

**Issue by kabeza** [allinurl/goaccess#2099]
Hi
I've an Ubuntu 18.04 box where I run

`sudo crontab -e`

`0 0 1 * * goaccess -f /var/log/apache2/access.log --log-format COMMON -a -d > "/var/www/html/stats/reporte_$(date +\%d\%m\%Y).html"`

When I check the folder, file is 0bytes. Any clues?

If I execute the same command manually from shell: 

`sudo goaccess -f /var/log/apache2/access.log --log-format COMMON -a -d > "/var/www/html/stats/reporte_$(date +\%d\%m\%Y).html"`

It works great

**Comment by allinurl** [comment]
Hello - Can I ask what version of goaccess are you running?

**Comment by kabeza** [comment]
GoAccess - 1.2.
For more details visit: http://goaccess.io
Copyright (C) 2009-2016 by Gerardo Orellana

**Comment by allinurl** [comment]
Could you please upgrade to the latest version? This issue may have been fixed already.  Let me know. Thanks

**Comment by kabeza** [comment]
> Could you please upgrade to the latest version? This issue may have been fixed already. Let me know. Thanks

don't know why it didn't upgrade all this time, now i notice 1.2 is from 2017 🤦‍♂️

**Comment by allinurl** [comment]
Feel free to use the [**official deb repo**](https://goaccess.io/download#official-repo), usually debian/ubuntu take time to upgrade packages.

**Comment by kabeza** [comment]
> Feel free to use the [**official deb repo**](https://goaccess.io/download#official-repo), usually debian/ubuntu take time to upgrade packages.

Yea, I did that. It looks like I had installed manually 1.2, now removed it, reinstalled through repo and changed cron to daily to see how it goes. Will update. Thanks

**Comment by kabeza** [comment]
Checked output. Cron worked perfectly now
It just needed an upgrade
Thanks
