### ISSUE TITLE
Error occured at: goaccess.c - main - 832

### ISSUE THREAD

**Issue by amrifirdaus** [allinurl/goaccess#210]
Hi..
I'm trying to use goaccess on CentOS 6.5 for analyze haproxy log and using a custom log format in my goaccess.conf.
here's my goaccess.conf file:
date-format %d/%b/%Y
log-format %h %^[%d:%^] %^ "%r" %s %b "%R" "%u"

Here's the error I get when I run goaccess -f /var/log/haproxy.log 
GoAccess - version 0.8.5 - Jan 23 2015 17:17:28

Fatal error has occurred
Error occured at: goaccess.c - main - 832
Nothing valid to process.

Here's sample haproxy log:
123.456.145.12 - - [26/Jan/2015:10:01:04 +0000] "GET /bbi/offer.json HTTP/1.1" 404 687 "" "" 52700 687 "my_wa_wa" "bla" "wawa" 2545 0 0 2 2547 ---- 1 1 0 1 0 0 0 "" ""

**Comment by allinurl** [comment]
The regular `NCSA Combined Log Format` works. However, you have an invalid IP in there. I tested your sample log with:

    goaccess -f log --log-format='%h %^[%d:%^] "%r" %s %b "%R" "%u"' --date-format='%d/%b/%Y'

and it does work.

**Comment by allinurl** [comment]
Closing this. Feel free to re open it if needed.

**Comment by d3fm0nk** [comment]
Hi. I have the same error trying to use goaccess for squid log. It does not work even after I tried with  _goaccess -f <log> --log-format='%h %^[%d:%^] "%r" %s %b "%R" "%u"' --date-format='%d/%b/%Y'_

I have version0.8.5 running on fedora 21.

Thanks

**Comment by allinurl** [comment]
@d3fm0nk Squid usually has a different format. Please post a few lines from your access log, description of each field and how they're currently delimited and I can take a look. Also, please feel free to upgrade to the [**latest**](https://goaccess.io/download) version.

**Comment by d3fm0nk** [comment]
Thank you for the swift response! sample log content is attached below, tab delimited. I redacted internal IP addresses and urls.

Cheers
[SQUID_LOG_FORMAT.txt](https://github.com/allinurl/goaccess/files/1293191/SQUID_LOG_FORMAT.txt)

**Comment by allinurl** [comment]
@d3fm0nk The following should work. However, you will need to build from [**development**](https://github.com/allinurl/goaccess#build-from-github-development) in order to get goaccess to parse your log.

    goaccess squid.log --log-format='%d:%t %^ %~%D %h %^/%s %b %m %U %^' --date-format=%d/%b/%Y --time-format=%T --http-protocol=no

**Comment by d3fm0nk** [comment]
Hi,

I installed the latest version but when I run now I get the message below

"GoAccess - version 1.2 - Sep 14 2017 19:06:15
Config file: /usr/local/etc/goaccess.conf

Fatal error has occurred
Error occured at: src/parser.c - read_log - 2669
Unable to open the specified log file. Device or resource busy"


What am I doing wrongly?

Thanks for your time.

**Comment by allinurl** [comment]
Sounds like other process is using the same access log, please make sure no other processing is holding it. You can use `lsof` or `fuser` to identify who is using this file, something like this:

    # lsof +D /path/log/

**Comment by d3fm0nk** [comment]
I actually moved the access.log file to the same directory as the go access installation but it's the same error.

**Comment by d3fm0nk** [comment]
I lsofd and there was nothing/no one using the file.

**Comment by allinurl** [comment]
Is this a mounted partition? Are you running as root? Make a copy of it and try parsing that file. Otherwise, try rebooting your machine and see if that solves the issue. The message you posted above is related the actual file you are trying to parse.

**Comment by d3fm0nk** [comment]
Hello,

I was going to mention that I see it's something with parsing. I rebooted, changed ownership of file but its same. I even created a custom file by extracting content from the original file while maintaining structure but problem remains. I'll update you if anything changes

**Comment by allinurl** [comment]
@d3fm0nk Feel free to open a new issue if the problem persists. The `Device or resource busy (EBUSY)`  error message comes directly from the system, it's not a message from goaccess. You can Google this message and you may be able to get some hints.

**Comment by d3fm0nk** [comment]
I set up on OS X and I get the error in the screenshot. The log is the same I shared previously. Any ideas about how I can fix it?

![screen shot 2017-09-17 at 6 09 25 pm](https://user-images.githubusercontent.com/5058739/30523181-c6161f28-9bd4-11e7-8912-61949dd87384.png)

**Comment by allinurl** [comment]
@d3fm0nk as I mentioned before, did you build from development? You need to build from development in order to parse the squid log you posted above.

**Comment by d3fm0nk** [comment]
@allinurl Sorry to bother you. Yes, I built from development. The error about device or resource busy was as a result of specifying a wrong path for the log (my error). The problem I have is still about parsing log file, it says "Format Errors - Verify your log/date/time format".

**Comment by allinurl** [comment]
@d3fm0nk Here are the exact steps I followed and it parsed your sample log well:

```
$ wget -O log https://github.com/allinurl/goaccess/files/1314242/sample_squid_log.txt
$ git clone https://github.com/allinurl/goaccess.git goaccess && cd $_
$ autoreconf -fiv
$ ./configure --enable-utf8 --enable-geoip=legacy
$ make
$ ./goaccess ../log --log-format='%d:%t %^ %~%D %h %^/%s %b %m %U %^' --date-format=%d/%b/%Y --time-format=%T --http-protocol=no
```

Here's the output:

![2017-09-19-085803_582x514_scrot](https://user-images.githubusercontent.com/5005367/30596004-7e2ac606-9d18-11e7-80ad-c5130450fded.png)

**Comment by d3fm0nk** [comment]
You are a genius. It was typo from me. Thank you for your time.
