### ISSUE TITLE
The d3 library is old and could need an update

### ISSUE THREAD

**Issue by dertuxmalwieder** [allinurl/goaccess#2103]
As far as I can see, GoAccess uses version 3 of `d3.js` (the current version is [6.7.0](https://github.com/d3/d3/releases)). While this does not automatically make it a bad choice, it is probably a good idea to check whether an update (admittedly, involving a migration 3 -> 4 -> 5 -> 6, due to the API changes) could bring any advantages.

`d3.v6.min.js` weighs 264 Kb, while `d3.v3.min.js` weighs "only" 148 Kb, which is the only obvious disadvantage to me; but then again, I have not evaluated GoAccess's usage of the graphing libraries well enough to understand what else could be a problem here. I'll just leave this here as a suggestion.

**Comment by allinurl** [comment]
I agree. I've been thinking to upgrade as well. Though, last time I checked, it would require some changes under [charts.js](https://github.com/allinurl/goaccess/blob/master/resources/js/charts.js). It'd be nice if we could make the charts.js code smaller if v6.7.0 helps to do that, it'd make up for the larger size of d3.

**Comment by dertuxmalwieder** [comment]
I would guess that the migration guides would cover the required changes?

**Comment by allinurl** [comment]
I think so, I'd have to look into it again. By the way, are you familiar with d3?

**Comment by dertuxmalwieder** [comment]
Not at all, I’m afraid. There are things even I cannot understand yet.

**Comment by allinurl** [comment]
As of this post, D3 was updated to v7 (latest).
