### ISSUE TITLE
GitHub API for releases produces empty output

### ISSUE THREAD

**Issue by tevkar** [allinurl/goaccess#2104]
Hi,

I use Github API to monitor release changes and using the following URL:

**https://api.github.com/repos/allinurl/goaccess/releases**

and it produces an empty array even if you have releases registered.

It would be also very nice if the latest works:
**https://api.github.com/repos/allinurl/goaccess/releases/latest**

PS! This is not a problem for the other packages I monitor.

Kind regards
Itefix

**Comment by allinurl** [comment]
Please use:

https://api.github.com/repos/allinurl/goaccess/tags

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
