### ISSUE TITLE
A possible divide by zero bug

### ISSUE THREAD

**Issue by yiyuaner** [allinurl/goaccess#2106]
In src/gholder.c, the function `set_root_metrics` has the following [code](https://github.com/allinurl/goaccess/blob/0abddd5f09ea6385b8bc2b6b1e0d13e438c1697c/src/gholder.c#L550-#L561):

```
static int
set_root_metrics (GRawDataItem item, GModule module, datatype type, GMetrics ** nmetrics) {
    ...
    uint32_t hits = 0;
    if (map_data (module, item, type, &data, &hits) == 1)
        return 1;
    ...
    metrics->avgts.nts = cumts / hits;
```
On successful return, the function `map_data` may set `hits` to `item.hits`, and if `item.hits` is `0`, then there is a divide by zero problem. I think this case maybe possible. For example, function [`parse_raw_data`](https://github.com/allinurl/goaccess/blob/0abddd5f09ea6385b8bc2b6b1e0d13e438c1697c/src/gkhash.c#L3546) seems to leave the field `hits` in `GRawDataItem` as `0`.

**Comment by allinurl** [comment]
Thanks a lot for pointing that out. It makes sense, I think there's a change to get a division by zero. Would you be able to submit a PR to address this issue?

**Comment by yiyuaner** [comment]
> Thanks a lot for pointing that out. It makes sense, I think there's a change to get a division by zero. Would you be able to submit a PR to address this issue?

Ok, please see if the PR is reasonable.

BTW, it can also resolve another similar divide by zero issue in gholder.c, for example:
```
static void
add_data_to_holder (GRawDataItem item, GHolder * h, datatype type, const GPanel * panel) {
  char *data = NULL;
  uint32_t hits = 0;

  if (map_data (h->module, item, type, &data, &hits) == 1)
    return;

  set_single_metrics (item, h, data, hits); // set_single_metrics  use hits as a divisor. if hits is 0,  there is a divide by zero problem.
```

**Comment by allinurl** [comment]
Agreed. The PR should resolve this. Thanks again.

Closing this. Feel free to reopen it if needed, though.
