### ISSUE TITLE
Array overflows when exceeding MAX_* limites

### ISSUE THREAD

**Issue by denschub** [allinurl/goaccess#211]
When exceeding

```c
#define MAX_EXTENSIONS 64
#define MAX_IGNORE_IPS 64
#define MAX_IGNORE_REF 64
```

the arrays allocated in `settings.h` will try to exceed their limits, resulting in nasty segfaults. No length checks are implemented in `read_option_args()` in `options.c` and the index values will get increased without any boundaries.

**Comment by allinurl** [comment]
Thanks for pointing this out! It has been fixed. Feel free to rebase, otherwise, it will be pushed out in the upcoming version.

**Comment by denschub** [comment]
Now that was a fast one. Thanks very much!
