### ISSUE TITLE
Token '23/Oct/2020' doesn't match specifier '%d'

### ISSUE THREAD

**Issue by powertashton** [allinurl/goaccess#2112]
Hiya, getting the error "Token '23/Oct/2020' doesn't match specifier '%d'" when trying to use goaccess to analyse our httpd apache access logs, our log format and relevant config lines are as below, any idea what's going on here?
```127.0.0.1 - - [23/Oct/2020:13:27:34 +0800] "GET / HTTP/1.1" 200 203
127.0.0.1 - - [23/Oct/2020:13:27:34 +0800] "GET /favicon.ico HTTP/1.1" 404 196
127.0.0.1 - - [23/Oct/2020:13:44:14 +0800] "GET / HTTP/1.1" 200 203
127.0.0.1 - - [23/Oct/2020:13:44:21 +0800] "GET / HTTP/1.1" 200 203
127.0.0.1 - - [23/Oct/2020:13:44:21 +0800] "GET /favicon.ico HTTP/1.1" 404 196
127.0.0.1 - - [23/Oct/2020:13:45:38 +0800] "GET /test.php HTTP/1.1" 200 103941

time-format %H:%M:%S +%z
date-format %d/%b/%Y
log-format %h %^[%d:%t %^] "%r" %s %b

**Comment by powertashton** [comment]
Figured out that it's my locale not being set... think I have it working now

**Comment by 0bi-w6n-K3nobi** [comment]
Hi @powertashton 

If you yet have problem, try remove **`+%z`** from time format.

**Comment by allinurl** [comment]
Also, If your access log contains English months such as 12/Jan/2021 but your machine locale is not set to English, then you need to set your LC_TIME.

    # LC_TIME="en_US.UTF-8" bash -c 'goaccess access.log --log-format=COMBINED'
