### ISSUE TITLE
error log 

### ISSUE THREAD

**Issue by mathoyus** [allinurl/goaccess#2113]
root@ubuntu:~# goaccess /var/log/apache2/error.log --log-format=COMBINED -a -o /var/www/html/er.html     
==1894== GoAccess - Copyright (C) 2009-2020 by Gerardo Orellana
==1894== https://goaccess.io - <hello@goaccess.io>
==1894== Released under the MIT License.
==1894==
==1894== FILE: /var/log/apache2/error.log
==1894== Parsed 10 lines producing the following errors:
==1894==
==1894== Token '2021/05/18' doesn't match specifier '%h'
==1894== Token '2021/05/18' doesn't match specifier '%h'
==1894== Token '2021/05/18' doesn't match specifier '%h'
==1894== Token '2021/05/18' doesn't match specifier '%h'
==1894== Token '2021/05/18' doesn't match specifier '%h'
==1894== Token '2021/05/18' doesn't match specifier '%h'
==1894== Token '2021/05/18' doesn't match specifier '%h'
==1894== Token '2021/05/18' doesn't match specifier '%h'
==1894== Token '2021/05/18' doesn't match specifier '%h'
==1894== Token '2021/05/18' doesn't match specifier '%h'
==1894==
==1894== Format Errors - Verify your log/date/time format
root@ubuntu:~# 

2021/05/18 18:09:02 [error] 95789#95789: *3128659 upstream timed out (110: Connection timed out) while connecting to upstream, client: 10.194.204.214, server: www.gzinternetcourt.gov.cn, request: "POST /open/document/getOpenDocumentsInfo HTTP/1.1", upstream: "http://59.42.214.250:4007/open/document/getOpenDocumentsInfo", host: "10.194.204.82"
2021/05/18 18:10:02 [error] 95788#95788: *3128982 upstream timed out (110: Connection timed out) while connecting to upstream, client: 10.194.204.214, server: www.gzinternetcourt.gov.cn, request: "POST /open/document/getOpenDocumentsInfo HTTP/1.1", upstream: "http://59.42.214.250:4007/open/document/getOpenDocumentsInfo", host: "10.194.204.82"
[Wed May 19 09:26:17.360089 2021] [mpm_event:notice] [pid 1181:tid 140564546893696] AH00489: Apache/2.4.7 (Ubuntu) configured -- resuming normal operations
[Wed May 19 09:26:17.362400 2021] [core:notice] [pid 1181:tid 140564546893696] AH00094: Command line: '/usr/sbin/apache2'

**Comment by mathoyus** [comment]
how do i fix this,

**Comment by allinurl** [comment]
Looks like an error log. You need consistent fields in that log.

**Comment by 63070016** [comment]
how to fix it
