### ISSUE TITLE
json log error . tks

### ISSUE THREAD

**Issue by mathoyus** [allinurl/goaccess#2114]
root@ubuntu:/etc/goaccess-1.4.6# goaccess /etc/goaccess-1.4.6/1.log 2.log 3.log 4.log 5.log 6.log 7.log 8.log --log-format=COMBINED -a -o /var/www/html/gd.html

==2134== GoAccess - Copyright (C) 2009-2020 by Gerardo Orellana
==2134== https://goaccess.io - <hello@goaccess.io>
==2134== Released under the MIT License.
==2134==
==2134== FILE: /etc/goaccess-1.4.6/1.log
==2134== Parsed 10 lines producing the following errors:
==2134==
==2134== Token '{"request_id":"c13973ab0b90b653a27ab86e2a8c7514","time_iso8601":"2021-05-18T22:32:47+08:00","time_local":"18/May/2021:22:32:47' doesn't match specifier '%h'
==2134== Token '{"request_id":"3772620ab3d57ff7c5a6e1d6c6cf761b","time_iso8601":"2021-05-18T22:32:47+08:00","time_local":"18/May/2021:22:32:47' doesn't match specifier '%h'
==2134== Token '{"request_id":"fdd21e182b3b127802782505b0b44036","time_iso8601":"2021-05-18T22:32:47+08:00","time_local":"18/May/2021:22:32:47' doesn't match specifier '%h'
==2134== Token '{"request_id":"1f30d3e882bda331a46d4cec22a52798","time_iso8601":"2021-05-18T22:32:49+08:00","time_local":"18/May/2021:22:32:49' doesn't match specifier '%h'
==2134== Token '{"request_id":"c4a6e92bb2eb0ee56a231bbb49bf63b5","time_iso8601":"2021-05-18T22:32:49+08:00","time_local":"18/May/2021:22:32:49' doesn't match specifier '%h'
==2134== Token '{"request_id":"7dadca31f08a2da5a7e89212587c0fa6","time_iso8601":"2021-05-18T22:32:49+08:00","time_local":"18/May/2021:22:32:49' doesn't match specifier '%h'
==2134== Token '{"request_id":"277669c744ebf55ecafbb6ff09563bdf","time_iso8601":"2021-05-18T22:32:49+08:00","time_local":"18/May/2021:22:32:49' doesn't match specifier '%h'
==2134== Token '{"request_id":"cf9f1d57ad907fdb55b99db3734805a7","time_iso8601":"2021-05-18T22:32:50+08:00","time_local":"18/May/2021:22:32:50' doesn't match specifier '%h'
==2134== Token '{"request_id":"da1eb10adc7dded7c27e7fd7a98d2757","time_iso8601":"2021-05-18T22:32:50+08:00","time_local":"18/May/2021:22:32:50' doesn't match specifier '%h'
==2134== Token '{"request_id":"d747ff1c6cf7407679406d252cdc4cd8","time_iso8601":"2021-05-18T22:32:50+08:00","time_local":"18/May/2021:22:32:50' doesn't match specifier '%h'
==2134==
==2134== Format Errors - Verify your log/date/time format
root@ubuntu:/etc/goaccess-1.4.6# goaccess -f log --log-format='%^:"[%d:%t %^]"%^:"%h"%^:%^:"%U"%^:"%q"%^:"%m"%^:"%s"%^:"%u"%^:"%R"%^' --date-format='%d/%b/%Y' --time-format='%T'

GoAccess - version 1.4.6 - May 16 2021 20:27:14
Config file: No config file used

Fatal error has occurred
Error occurred at: src/parser.c - read_log - 3297
Unable to open the specified log file 'log'. Device or resource busy

root@ubuntu:/etc/goaccess-1.4.6# goaccess -f 1.log --log-format='%^:"[%d:%t %^]"%^:"%h"%^:%^:"%U"%^:"%q"%^:"%m"%^:"%s"%^:"%u"%^:"%R"%^' --date-format='%d/%b/%Y' --time-format='%T'
==2143== GoAccess - Copyright (C) 2009-2020 by Gerardo Orellana
==2143== https://goaccess.io - <hello@goaccess.io>
==2143== Released under the MIT License.
==2143==
==2143== FILE: 1.log
==2143== Parsed 10 lines producing the following errors:
==2143==
==2143== Token '13973ab0b90b653a27ab86e2a8c7514","time_iso8601"' doesn't match specifier '%d'
==2143== Token '772620ab3d57ff7c5a6e1d6c6cf761b","time_iso8601"' doesn't match specifier '%d'
==2143== Token 'dd21e182b3b127802782505b0b44036","time_iso8601"' doesn't match specifier '%d'
==2143== Token 'f30d3e882bda331a46d4cec22a52798","time_iso8601"' doesn't match specifier '%d'
==2143== Token '4a6e92bb2eb0ee56a231bbb49bf63b5","time_iso8601"' doesn't match specifier '%d'
==2143== Token 'dadca31f08a2da5a7e89212587c0fa6","time_iso8601"' doesn't match specifier '%d'
==2143== Token '77669c744ebf55ecafbb6ff09563bdf","time_iso8601"' doesn't match specifier '%d'
==2143== Token 'f9f1d57ad907fdb55b99db3734805a7","time_iso8601"' doesn't match specifier '%d'
==2143== Token 'a1eb10adc7dded7c27e7fd7a98d2757","time_iso8601"' doesn't match specifier '%d'
==2143== Token '747ff1c6cf7407679406d252cdc4cd8","time_iso8601"' doesn't match specifier '%d'
==2143==
==2143== Format Errors - Verify your log/date/time format
root@ubuntu:/etc/goaccess-1.4.6# sed -n '/5\/Nov\/2010/,/5\/Dec\/2010/ p' 1.log | goaccess -a      

GoAccess - version 1.4.6 - May 16 2021 20:27:13
Config file: No config file used

Fatal error has occurred
Error occurred at: src/goaccess.c - set_curses - 1490
No time format was found on your conf file.

root@ubuntu:/etc/goaccess-1.4.6# goaccess 1.log --log-format='%^:"%dT%t+%^",%^,%^:%b,%^:%T,%^,%^,%^:"%v",%^:"%U",%^,%^:"%m",%^,%^,%^:"%R",%^:"%u",%^,%^:"%h",%^:"%s"%^' --date-format=%Y-%m-%d --time-format=%T -H no
==2149== GoAccess - Copyright (C) 2009-2020 by Gerardo Orellana
==2149== https://goaccess.io - <hello@goaccess.io>
==2149== Released under the MIT License.
==2149==
==2149== FILE: 1.log
==2149== Parsed 10 lines producing the following errors:
==2149==
==2149== Token 'c13973ab0b90b653a27ab86e2a8c7514","time_iso8601":"2021-05-18' doesn't match specifier '%d'
==2149== Token '3772620ab3d57ff7c5a6e1d6c6cf761b","time_iso8601":"2021-05-18' doesn't match specifier '%d'
==2149== Token 'fdd21e182b3b127802782505b0b44036","time_iso8601":"2021-05-18' doesn't match specifier '%d'
==2149== Token '1f30d3e882bda331a46d4cec22a52798","time_iso8601":"2021-05-18' doesn't match specifier '%d'
==2149== Token 'c4a6e92bb2eb0ee56a231bbb49bf63b5","time_iso8601":"2021-05-18' doesn't match specifier '%d'
==2149== Token '7dadca31f08a2da5a7e89212587c0fa6","time_iso8601":"2021-05-18' doesn't match specifier '%d'
==2149== Token '277669c744ebf55ecafbb6ff09563bdf","time_iso8601":"2021-05-18' doesn't match specifier '%d'
==2149== Token 'cf9f1d57ad907fdb55b99db3734805a7","time_iso8601":"2021-05-18' doesn't match specifier '%d'
==2149== Token 'da1eb10adc7dded7c27e7fd7a98d2757","time_iso8601":"2021-05-18' doesn't match specifier '%d'
==2149== Token 'd747ff1c6cf7407679406d252cdc4cd8","time_iso8601":"2021-05-18' doesn't match specifier '%d'
==2149==
==2149== Format Errors - Verify your log/date/time format
root@ubuntu:/etc/goaccess-1.4.6#

**Comment by mathoyus** [comment]
{"request_id":"8c5c60b27ec770223025f5d872f4a053","time_iso8601":"2021-05-18T22:32:50+08:00","time_local":"18/May/2021:22:32:50 +0800","http_x_forwarded_for":"39.171.2.101, 120.27.173.48","remote_
addr":"10.0.12.33","remote_user":"","request":"GET /api/lassen/prosecute/prosecuteRpc/getProsecuteNoticeWithConfig.json HTTP/1.1","status":"200","request_length":"2225","body_bytes_sent":"1247","
bytes_sent":"1549","request_time":"0.460","upstream_connect_time":"0.001","upstream_response_time":"0.459","upstream_addr":"10.4.125.202:8080","upstream_status":"200","request_method":"GET","host
":"ols.gzinternetcourt.gov.cn","server_port":"80","uri":"/api/lassen/prosecute/prosecuteRpc/getProsecuteNoticeWithConfig.json","args":"","server_protocol":"HTTP/1.1","http_referer":"https://ols.g
zinternetcourt.gov.cn/lassen/party/app/suit/prosecute/prosecute-guide","http_user_agent":"Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.25 Safari/537
.36 Core/1.70.3868.400 QQBrowser/10.8.4394.400"}

**Comment by mathoyus** [comment]
how can i define this log type

**Comment by allinurl** [comment]
Closing this as it is a dup. Please don't open multiple issues for the same thing. Thanks

**Comment by allinurl** [comment]
dup of #2115
