### ISSUE TITLE
How to parse a custom JSON log format with goaccess

### ISSUE THREAD

**Issue by mathoyus** [allinurl/goaccess#2115]
hi allinurl
i try to fix this log format isue for days ,please help ,tks!!!!!!!!!!!!
```
{"request_id":"8c5c60b27ec770223025f5d872f4a053","time_iso8601":"2021-05-18T22:32:50+08:00","time_local":"18/May/2021:22:32:50 +0800","http_x_forwarded_for":"39.171.2.101, 120.27.173.48","remote_
addr":"10.0.12.33","remote_user":"","request":"GET /api/lassen/prosecute/prosecuteRpc/getProsecuteNoticeWithConfig.json HTTP/1.1","status":"200","request_length":"2225","body_bytes_sent":"1247","
bytes_sent":"1549","request_time":"0.460","upstream_connect_time":"0.001","upstream_response_time":"0.459","upstream_addr":"10.4.125.202:8080","upstream_status":"200","request_method":"GET","host
":"ols.gzinternetcourt.gov.cn","server_port":"80","uri":"/api/lassen/prosecute/prosecuteRpc/getProsecuteNoticeWithConfig.json","args":"","server_protocol":"HTTP/1.1","http_referer":"https://ols.g
zinternetcourt.gov.cn/lassen/party/app/suit/prosecute/prosecute-guide","http_user_agent":"Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.25 Safari/537
.36 Core/1.70.3868.400 QQBrowser/10.8.4394.400"}
{"request_id":"004225f370b966e51bf1c106fd04cdef","time_iso8601":"2021-05-18T22:32:52+08:00","time_local":"18/May/2021:22:32:52 +0800","http_x_forwarded_for":"117.136.32.84, 118.178.15.96","remote
_addr":"10.0.8.115","remote_user":"","request":"GET /fileOperation/download.json?fileIdStr=BpNJL7CP7MVhUB_lDozT3w HTTP/1.1","status":"200","request_length":"1100","body_bytes_sent":"8865","bytes_
sent":"9135","request_time":"0.025","upstream_connect_time":"0.001","upstream_response_time":"0.024","upstream_addr":"10.4.125.202:8080","upstream_status":"200","request_method":"GET","host":"ols
.gzinternetcourt.gov.cn","server_port":"80","uri":"/fileOperation/download.json","args":"fileIdStr=BpNJL7CP7MVhUB_lDozT3w","server_protocol":"HTTP/1.1","http_referer":"https://ols.gzinternetcourt
```
```

root@ubuntu:/etc/goaccess-1.4.6# vi goaccess.conf
root@ubuntu:/etc/goaccess-1.4.6# goaccess 1.log --log-format=json /var/www/1.html
root@ubuntu:/etc/goaccess-1.4.6# vi goaccess.conf                                
root@ubuntu:/etc/goaccess-1.4.6# goaccess 1.log --log-format=json /var/www/1.html
root@ubuntu:/etc/goaccess-1.4.6# goaccess 1.log --log-format=log-format %^: "%dT%t+%^"%^: "%s"%^: "%b"%^: "%v"%^: "%T"%^: "~h{", }%^:%^:%^:%^:%^:%^: "%m"%^:%^:%^: "%U"%^: "%q"%^: "%H"%^:%^:%^: "%R"%^: "%u"%^
root@ubuntu:/etc/goaccess-1.4.6# goaccess 1.log --log-format=log-format %^: "%dT%t+%^"%^: "%s"%^: "%b"%^: "%v"%^: "%T"%^: "~h{", }%^:%^:%^:%^:%^:%^: "%m"%^:%^:%^: "%U"%^: "%q"%^: "%H"%^:%^:%^: "%R"%^: "%u"%^ --date-format %Y-%m-%d --time-format=%T
==3304== GoAccess - Copyright (C) 2009-2020 by Gerardo Orellana
==3304== https://goaccess.io - <hello@goaccess.io>
==3304== Released under the MIT License.
==3304==
==3304== FILE: 1.log
==3304== Parsed 10 lines producing the following errors:
==3304==
==3304== IPv4/6 is required.
==3304== IPv4/6 is required.
==3304== IPv4/6 is required.
==3304== IPv4/6 is required.
==3304== IPv4/6 is required.
==3304== IPv4/6 is required.
==3304== IPv4/6 is required.
==3304== IPv4/6 is required.
==3304== IPv4/6 is required.
==3304== IPv4/6 is required.
==3304==
==3304== Format Errors - Verify your log/date/time format
```

**Comment by allinurl** [comment]
This should do it:

    goaccess access.log --log-format='{"time_local": "%d:%t %^", "http_x_forwarded_for": "%h,%^", "remote_user": "%e", "request": "%r", "status": "%s", "request_length": "%b", "request_time": "%T", "host": "%v", "http_referer": "%R", "http_user_agent": "%u"}' --date-format=%d/%b/%Y --time-format=%T

More details on JSON format, [**here**](https://github.com/allinurl/goaccess/issues/1768#issuecomment-755792463)

**Comment by mathoyus** [comment]
@allinurl how Extract source IP output report?

**Comment by mathoyus** [comment]
@allinurl 



# | HITS | VISITORS | TX. AMOUNT | AVG. T.S. | CUM. T.S. | MAX. T.S. | COUNTRY | DATA
-- | -- | -- | -- | -- | -- | -- | -- | --



&nbsp; | 1 | 1,075&nbsp;(0.26%) | 2&nbsp;(0.01%) | 1.27 GiB&nbsp;(21.82%) | 1.02 s | 18.36 m | 1.29 m | CN China

**Comment by mathoyus** [comment]
tks,i think i know how to do rest json log,again thank you very muck.
my english not very good,

**Comment by mathoyus** [comment]
{"@timestamp":"2021-01-27T14:28:39+08:00","remote_addr":"10.194.204.141","remote_user":"-","request_time":"0.000","upstream_response_time":"-","status":200,"request":"GET /group1/M00/00/00/CsLMjW
ARB-SAatwDAAAIP9q_kUg36.html HTTP/1.1","type":"http","request_method":"GET","http_referrer":"-","body_bytes_sent":2111,"request_body":"-","response_body":"<!DOCTYPE html><html lang=en><head><meta
 charset=utf-8><meta http-equiv=X-UA-Compatible content=\x22IE=edge\x22><meta name=viewport content=\x22width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no\x22><link rel=icon href
=//...ico><title>\xE6\xB3\xB0\xE5\xB2\xB35G\xE6\xB6\x88\xE6\x81\xAF\xE4\xBA\x91\xE5\xB9\xB3\xE5\x8F\xB0</title><link href=/css/app.394085fb.css rel=preload as=style><link href=/css/chunk-libs.ddd
04e9f.css rel=preload as=style><link href=/js/app.1f948213.js rel=preload as=script><link href=/js/chunk-elementUI.8ecf210b.js rel=preload as=script><link href=/js/chunk-libs.30dee9b8.js rel=prel
oad as=script><link href=/css/chunk-libs.ddd04e9f.css rel=stylesheet><link href=/css/app.394085fb.css rel=stylesheet></head><style>@media (min-width: 1024px){\x0A      html{font-size: 18px}\x0A  
  } /*>=1024\xE7\x9A\x84\xE8\xAE\xBE\xE5\xA4\x87*/\x0A\x0A    @media (min-width: 1100px) {\x0A      html{font-size: 20px}\x0A    } /*>=1024\xE7\x9A\x84\xE8\xAE\xBE\xE5\xA4\x87*/\x0A\x0A    @media
 (min-width: 1280px) {\x0A      html{font-size: 22px;}\x0A    }\x0A\x0A    @media (min-width: 1366px) {\x0A      html{font-size: 24px;}\x0A    }\x0A\x0A    @media","http_x_forwarded_for":"-","htt
p_user_agent":"curl/7.29.0"}

root@ubuntu:/etc/goaccess-1.4.6# goaccess access.log --log-format='{"time_local": "%d:%t %^", "remote_addr": "%h", "remote_user": "%e", "request_time": "%T", "upstream_response_time":"%e", "status": "%s", "request": "%r","type":"^","request_method":"m","http_referrer":"R","body_bytes_sent":"b","request_body":"e","response_body":"^", "http_x_forwarded_for": "%h,%^", "http_user_agent": "%u"}'  -a -o /var/www/html/yidong.html

GoAccess - version 1.4.6 - May 16 2021 20:27:14
Config file: No config file used

Fatal error has occurred
Error occurred at: src/parser.c - parse_log - 3342
No time format was found on your conf file.

root@ubuntu:/etc/goaccess-1.4.6# 

@allinurl how can i still not working, i get another json log,i try to define log-format,but fail ,please help.

**Comment by allinurl** [comment]
Glad that worked. Closing this. Feel free to reopen it if needed.

**Comment by eeraser710** [comment]
> 
> 
> tks,i think i know how to do rest json log,again thank you very muck.
> my english not very good,

@mathoyus  - seems your issue is resolved , i am too facing same issue . kinldy help out . kindly refer for https://github.com/allinurl/goaccess/issues/2127 for details
