### ISSUE TITLE
Missing reset after access to disabled panel

### ISSUE THREAD

**Issue by cgzones** [allinurl/goaccess#2121]
When the virtual hosts panel is disabled and it gets requested, by pressing `9`, the footer looks like:

![pre](https://user-images.githubusercontent.com/6131885/119547392-5a700680-bd95-11eb-84b3-2181b01c8d03.jpg)

On selecting a different panel, e.g. by pressing `6`, the background of the footer does not get completely reset:

![post](https://user-images.githubusercontent.com/6131885/119547474-72478a80-bd95-11eb-9230-ca69e3b29ea7.jpg)

**Comment by allinurl** [comment]
Thanks for reporting this. Did you test this on v1.4.6 or from development?

**Comment by cgzones** [comment]
git master branch.

**Comment by allinurl** [comment]
Should be fixed, please give it a shot! Thanks again.
