### ISSUE TITLE
CPU hogging?

### ISSUE THREAD

**Issue by selfagency** [allinurl/goaccess#2123]
I've been noticing that the GoAccess process is eating up about 25% of my web server's CPU power full-time. The moment I start it, it just grabs like a whole processer core for itself. How can I reduce its load?

**Comment by selfagency** [comment]
Never mind I found my problem

**Comment by allinurl** [comment]
Glad you found the issue. Do you mind sharing what was it? Thanks

**Comment by selfagency** [comment]
It was caught in a restart loop because it was choking on some bad formatting in one of the log files.
