### ISSUE TITLE
Apt Repo cert issue

### ISSUE THREAD

**Issue by stephenreay** [allinurl/goaccess#2124]
I'm getting intermittent TLS certificate errors (I can't confirm all are the same but the last one at least was claiming the cert had expired) trying to access the repo. I can't reliably reproduce the issue yet but it's happened several times in the last couple of hours.

**Comment by Chi-Yu** [comment]
The same happens for the website. Sometimes it says the certificate expired on May 27th but force reloading will usually fix it.

**Comment by allinurl** [comment]
Thanks for bringing this up. I'm checking on this and will post back asap.

**Comment by stephenreay** [comment]
Yep this is very odd.

I came across it during a vagrant box build (i.e. vm image build, using packer) - the initial attempt to fetch the .deb during the automated setup failed at least half a dozen times - but even pausing the setup, connecting to the console of the in-process VM and trying to reproduce it, I always got a valid response.

Happy to help if you need more info/tests/whatever.

**Comment by allinurl** [comment]
Please give it a shot, I think the webserver had some orphaned processes with old versions of the certificate. Not sure yet why it didn't kill those processes so hopefully the webserver won't keep triggering this issue. Otherwise I may need to look further into this.

**Comment by stephenreay** [comment]
I've made several builds in the last couple of days and none hit this error.

**Comment by allinurl** [comment]
Awesome, thanks for reporting back! Closing this for now.
