### ISSUE TITLE
--ignore-referer is now --ignore-referrer ???

### ISSUE THREAD

**Issue by stephenreay** [allinurl/goaccess#2130]
Please tell me this was an unfortunate case of an editor/IDE auto-correcting a string, and not someone thinking it's OK to just change the name of an option like that???

```
goaccess[22164]: /usr/bin/goaccess: unrecognized option '--ignore-referer=example.com'
```

From man:

```
       --ignore-referrer=<referrer>
              Ignore referers from being counted. Wildcards allowed. e.g., *.domain.com ww?.domain.*

```

**Comment by allinurl** [comment]
Sorry about this. Unfortunately the option was deprecated under #2102. I should have kept the previous option for backwards compatibility. I'll be more cautious next time ;)
