### ISSUE TITLE
Error installing via PPA

### ISSUE THREAD

**Issue by snowweb** [allinurl/goaccess#2131]
OS: Ubuntu 20.04 LTS (clean install and fully updated)
uname -a: Linux s2.snowweb.info 5.4.0-74-generic #83-Ubuntu SMP Sat May 8 02:35:39 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

See below output when installing GoAccess key, source and then updating APT:

`root@s2:~# wget -O - https://deb.goaccess.io/gnugpg.key | gpg --dearmor | sudo tee /usr/share/keyrings/goaccess.gpg >/dev/null
--2021-06-07 16:49:08--  https://deb.goaccess.io/gnugpg.key
Resolving deb.goaccess.io (deb.goaccess.io)... 67.205.130.138
Connecting to deb.goaccess.io (deb.goaccess.io)|67.205.130.138|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2468 (2.4K) [application/pgp-keys]
Saving to: ‘STDOUT’

-                      100%[===========================>]   2.41K  --.-KB/s    in 0s

2021-06-07 16:49:11 (214 MB/s) - written to stdout [2468/2468]

root@s2:~# echo "deb [signed-by=/usr/share/keyrings/goaccess.gpg] https://deb.goaccess.io/ $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/goaccess.list
deb [signed-by=/usr/share/keyrings/goaccess.gpg] https://deb.goaccess.io/ focal main
root@s2:~# apt-get update
Hit:1 http://asi-fs-d.contabo.net/ubuntu focal InRelease
Hit:2 http://asi-fs-d.contabo.net/ubuntu focal-updates InRelease
Hit:3 http://asi-fs-d.contabo.net/ubuntu focal-backports InRelease
Get:4 http://security.ubuntu.com/ubuntu focal-security InRelease [114 kB]
Hit:5 https://deb.goaccess.io focal InRelease
Fetched 114 kB in 1s (165 kB/s)
Reading package lists... Done
N: Skipping acquire of configured file 'main/binary-i386/Packages' as repository 'https://deb.goaccess.io focal InRelease' doesn't support architecture 'i386'
`
(Strike-through was added by the embedded github editor, not by me, even though I put the output in a code block)

**Comment by allinurl** [comment]
You seem to be using a x86_64. I don't believe there's an i386 version of Ubuntu 20.04. https://releases.ubuntu.com/20.04/
