### ISSUE TITLE
how to display user name and activity in cowaxess output

### ISSUE THREAD

**Issue by babyhughey** [allinurl/goaccess#2134]
my ssl_access_log notes date, time, user and activity (below, downloading a pdf)

(IP ADDRESS) - user@user.com [11/May/2021:08:30:22 -0400] "GET /pdf/my.pdf HTTP/1.1" 401 -

how can I tweak my command so my cowaxess report.html file displays this level of information?

**Comment by allinurl** [comment]
Please try this, it should work:

    goaccess access.log --log-format='%h %^ %e [%d:%t %^] "%r" %s %b' --date-format=%d/%b/%Y --time-format=%T

**Comment by allinurl** [comment]
or HTML output

    goaccess access.log --log-format='%h %^ %e [%d:%t %^] "%r" %s %b' --date-format=%d/%b/%Y --time-format=%T -o report.html

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.

**Comment by babyhughey** [comment]
Thanks for your help on this.

I think the issue is that my log file lists the user’s IP address first and user name second:

xxx.xxx.xxx.xxx - username [09/Jun/2021:10:51:06 -0400] "GET /favicon.ico HTTP/1.1" 404 306

When I run the report per your instructions, it lists user by IP, not user name

**Comment by allinurl** [comment]
Are you able to see what's the last panel on the report? Here's what I see from my end:

![2021-06-22-143017_470x261_scrot](https://user-images.githubusercontent.com/5005367/122987594-633d0380-d366-11eb-8f54-5be00745ced1.png)

**Comment by babyhughey** [comment]
I do get this:

***@***.***D7677E.1957BE80]

Frankly, there’s TOO much and not enough information in this report.

I’d prefer something simple that I can show my managers that notes that x user downloaded y pdf file on z date ... perhaps reversible to show that y pdf was downloaded x number of times in this period by this many users.

**Comment by allinurl** [comment]
It's possible cowaxess is doing something else to display that. I'm not the one maintaining that repo so I can tell. However, you could always try running it via cygwin or generating the reports through a Linux box. Sorry about that.

Soon goaccess will be supporting probably one of the nicest features "search/filtering" which will address very easily the report you are after. Stay tuned :)
