### ISSUE TITLE
PPA not working for Xenial

### ISSUE THREAD

**Issue by mlaurense** [allinurl/goaccess#2135]
It appears the PPA is not working anymore for Xenial?

```
W: The repository 'https://deb.goaccess.io xenial Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch https://deb.goaccess.io/dists/xenial/main/binary-amd64/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.
```
Is Xenial no longer supported?

`wget https://deb.goaccess.io/dists/xenial/main/binary-amd64/Packages` also gives a 404, whereas `wget https://deb.goaccess.io/dists/focal/main/binary-amd64/Packages` does seem to work.

**Comment by allinurl** [comment]
Great question, Xenial is no longer supported, I believe Ubuntu stopped supporting this release on 2021-04. Sorry about that.

**Comment by allinurl** [comment]
Forgot to post the reason behind goaccess not supporting it. Basically I go through an automated building process where it fires a bunch of vagrant boxes that install the build packages such as gcc, make, etc. If the machine fails because it couldn't run `apt update/upgrade` then I can't build goaccess on it.

**Comment by mlaurense** [comment]
Thanks for your swift response. I've put our 16.04 servers on the list to upgrade asap.

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
