### ISSUE TITLE
How do you delete stored goaccess data tables / logs

### ISSUE THREAD

**Issue by BobaPearl** [allinurl/goaccess#2137]
I'm using GoAccess for a weird edge case, I use this to track how many times images on my webpage get static requests, this is because I have a webcomic, and I host it on my site, and then hotlink the images themselves on multiple forum boards. I want to see how many people are viewing the image across sites. I know I can't filter out bots and spiders, but it's the best I got right now.

I delete everything in the log, and start over from the new update, so I can see how many went back and read based on the new stuff, and how many requests are being done per update.

The problem I'm having is that GoAccess keeps internal records of those logs, and adds the new log information to the report. How do I stop it from doing that?

**Comment by 0bi-w6n-K3nobi** [comment]
Hi @BobaPearl

GoAccess use memory for storage of records.
I think do you need restart [i.e. `stop` and `start`] for clear previous info.

**Comment by allinurl** [comment]
Also, are you using --persist and --restore. If you are, then please don't use them as they would keep restoring from disk whatever data was last parsed.

**Comment by allinurl** [comment]
Any update on this? Thanks

**Comment by BobaPearl** [comment]
I can't start and stop my server, as I'm using shared hosting to host my website, or at least the commands have been changed. I ended up purchasing a different access.log visualization program, which has less features, but was able to do what I wanted through some heavy use of filtering.
