### ISSUE TITLE
lengthy static-file configuration value will cause unexpected results

### ISSUE THREAD

**Issue by domolicious** [allinurl/goaccess#2139]
This one got me wondering. It appears that if you add a long file extension to the `static-file` configuration it kind of erases the previous set values. My very long file extension is `.webmanifest`.

Consider this minimal example

```
$ goaccess --version
GoAccess - 1.5.1.
For more details visit: https://goaccess.io/
Copyright (C) 2009-2020 by Gerardo Orellana

Build configure arguments:
  --enable-utf8
  --enable-geoip=mmdb
  --with-getline
  --with-openssl
```

access.log
```
192.168.0.1 - - [30/Jun/2021:11:11:38 +0000] "GET /robots.txt HTTP/1.1" 200 5066 "-" "curl/7.68.0"
192.168.0.1 - - [30/Jun/2021:11:39:58 +0000] "GET /site.webmanifest HTTP/1.1" 200 5030 "-" "curl/7.68.0"
```

.goaccessrc
```
log-format COMBINED
static-file .txt
static-file .webmanifest
```

And I run: `$ goaccess access.log`

### Results

`site.webmanifest` end up being a static request, but `robots.txt` does not.

![goaccess](https://user-images.githubusercontent.com/250664/123960618-cc98c400-d9af-11eb-9c24-38eabd632d19.png)

### Expected results

I am expecting both files to count as static requests.

In my specific case I simply renamed the file extension to `.manifest` along with changing the file name and log entries, and that works just fine.

**Comment by allinurl** [comment]
Sorry for the delay on this and thanks for reporting this. This has been fixed and will be pushed out in the upcoming release to be out soon. You can always test it out by building from [**development**](https://github.com/allinurl/goaccess#build-from-github-development) and let me know how it goes on your end.

Closing this. Feel free to reopen it if needed.
