### ISSUE TITLE
Getting fatal error when parsing nginx log

### ISSUE THREAD

**Issue by Mas73r** [allinurl/goaccess#214]
Using goaccess 0.8.5

    cat /root/access.log | goaccess --no-global-config --agent-list --color-scheme 2 --real-os --date-format '%d/%b/%Y:%T %z' --log-format '"%h" %^ "%^" "[%d]" "%r" "%s" "%b" "%R" "%u" %^ %^ %^ %^ %^' --http-protocol --http-method -c

    GoAccess - version 0.8.5 - Sep 14 2014 08:08:07

    Fatal error has occurred
    Error occured at: goaccess.c - main - 832
    Nothing valid to process.

Sample log

    "33.33.33.3" - "-" "[04/Feb/2015:06:29:05 -0500]" "POST /api/internal/systems/ HTTP/1.0" "200" "71" "-" "Zend_Http_Client" "-" "0.025" "127.0.0.1:9000" "0.025" "foo.com"

**Comment by allinurl** [comment]
The following should do it:

    cat log | goaccess --no-global-config --agent-list --color-scheme 2 --real-os --date-format='%d/%b/%Y' --log-format='"%h" %^[%d:%^]" "%r" "%s" "%b" "%R" "%u"' --http-protocol --http-method

Let me know how it goes.

**Comment by allinurl** [comment]
Closing this, feel free to reopen it if needed.

**Comment by Mas73r** [comment]
Thank you!
