### ISSUE TITLE
Token '0700] "GET http' doesn't match specifier '%d'

### ISSUE THREAD

**Issue by tchnlgst** [allinurl/goaccess#2146]
Hello,

I appreciate your work on GoAccess.

I'm having trouble analyzing a log file and I can't tell what I may be doing wrong. I'd appreciate some assistance.

`55.66.222.333 [5T5DVa5NR2cKpek] jdoe [17/Aug/2020:12:05:14 -0700] "GET http://urlhere.com:80/login?qurl=https%3A%2F%2Flearn.anotherurl.com%2Feos HTTP/1.1" 599 0 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.125 Safari/537.36"
`

GoAccess command is as follows:

`goaccess test.txt --log-format='%h [%{program-session}i] %u %^[%d:%t %^] "%r" %s %b "%{user-agent}i"' --date-format=%d/%b/%Y --time-format=%T`

Error thrown is as follows

`==13133== Token '0700] "GET http' doesn't match specifier '%d'`

`==13133== Format Errors - Verify your log/date/time format`

I'd appreciate any assistance.

**Comment by 0bi-w6n-K3nobi** [comment]
Hi @tchnlgst 
Almost fields is correct in your line declaration with some exceptions:

**Comment by allinurl** [comment]
@0bi-w6n-K3nobi was right on spot, thanks for posting that!

    goaccess access.log --log-format='%h [%v] %e [%d:%t %^] "%r" %s %b "%u"' --date-format=%d/%b/%Y --time-format=%T

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
