### ISSUE TITLE
Issue with %h specifier with custom log

### ISSUE THREAD

**Issue by Jirubizu** [allinurl/goaccess#2149]
I have the following log
`[16/Jul/2021:06:58:18 +0000] - 200 200 - GET https api.jirubizu.cc "/docs" [Client 141.101.99.151] [Length 504] [Gzip 1.98] [Sent-to 192.168.1.153] "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:90.0) Gecko/20100101 Firefox/90.0" "-"
`
And this is my log format
`log_format [%d:%t %^] - %s %^ - %m  %v "%U" [Client %h] [Length %b] [Gzip %^] "%u" "%R"
time-format %T
date-format %d/%b/%Y
`

However I keep getting this error
`Token 'lient 141.101.99.151' doesn't match specifier '%h'`

**Comment by 0bi-w6n-K3nobi** [comment]
Hi @Jirubizu 

Almost is OK here! But you did forgot to ignore `https` word.
Try this:

**Comment by allinurl** [comment]
This should do it:

    goaccess log --log-format='[%d:%t %^] - %s %^ - %m %^ %v "%U" [Client %h] [Length %b] %^"%u" "%R"' --date-format=%d/%b/%Y --time-format=%T

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
