### ISSUE TITLE
Can't get HTTP request time with goaccess from nginx log

### ISSUE THREAD

**Issue by edikmkoyan** [allinurl/goaccess#215]
down vote favorite
	

I've we websites hosted on nginx web server. I've added HTTP request duration to nginx logs, and nginx logs that data. http://nginx.org/en/docs/http/ngx_http_log_module.html

I also have goaccess log analyzer and it works just fine with one nasty exception. I can't get the HTTP request time parameter although in documentation they say it is possible "%DThe time taken to serve the request, in microseconds." Here is the url, please help. http://goaccess.io/man#custom-log

Thanks!!!

http://superuser.com/questions/874064/cant-get-http-request-time-with-goaccess-from-nginx-log

**Comment by allinurl** [comment]
Could you post a sample log line from your current nginx so I can take a look?

**Comment by Babken** [comment]
The last number is request duration
192.168.17.1 - - [05/Feb/2015:22:24:29 +0400] "POST / HTTP/1.1" 200 12015 "http://www.watch-sell.com/" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.94 Safari/537.36" "-" 20.178

Log Format in goaccess.conf

log-format %h %^ %^ [%d:%^] "%r" %s %b "%R" "%^" %T

**Comment by allinurl** [comment]
20.178 is the time in seconds with milliseconds after the dot. GoAccess will output `20.18  s`. Here's the format I used:

    %h %^[%d:%^] "%r" %s %b "%R" "%u" %^ %T

**Comment by edikmkoyan** [comment]
How do you view this data?

**Comment by allinurl** [comment]
goaccess -M -H -f log --log-format='%h %^[%d:%^] "%r" %s %b "%R" "%u" %^ %T' --date-format='%d/%b/%Y'

**Comment by edikmkoyan** [comment]
It worked, thanks!

**Comment by allinurl** [comment]
Great! Closing...
