### ISSUE TITLE
downloadable font: download failed (font-family: "FontAwesome"...)

### ISSUE THREAD

**Issue by KarelWintersky** [allinurl/goaccess#2152]
Goaccess started as daemonized, like this:

```
sudo goaccess /var/log/nginx/47news-ssl-access.log -o /var/www/47news.status/main.html --log-format=COMBINED --real-time-html --daemonize --port=7890 --fifo-in=/tmp/site.in --fifo-out=/tmp/site.out
```

At browser console: 
```
downloadable font: download failed (font-family: "FontAwesome" style:normal weight:400 stretch:100 src index:1): status=2147746065 source: http://status.47news.ru/fonts/fontawesome-webfont.woff2?v=4.7.0

GET http://status.47news.ru/fonts/fontawesome-webfont.woff?v=4.7.0 
404
GET http://status.47news.ru/favicon.ico
404
```

No icons :(

**Comment by KarelWintersky** [comment]
Closed: used old version from stable default debian repo.

**Comment by allinurl** [comment]
Thanks for pointing that out. Yes, someone reported this a while back, I assume the debian repo hasn't upgraded the build.

Please feel free to use the [**official deb repo**](https://github.com/allinurl/goaccess#official-goaccess-debian--ubuntu-repository) to keep up with the latest changes.
