### ISSUE TITLE
Make the web interface real-time

### ISSUE THREAD

**Issue by allinurl** [allinurl/goaccess#216]
Although the real-time capability is already implemented through the terminal interface, making the web interface real-time would be nice.

**Comment by FabianGabor** [comment]
+1

**Comment by Dannii** [comment]
+1

**Comment by yodog** [comment]
could be very simple, like sarg-realtime does for squid

**Comment by allinurl** [comment]
Thanks. I'll look into sarg. So far [websocketd](https://github.com/joewalnes/websocketd) is the candidate for this since goaccess already writes to `STDOUT`.

**Comment by allinurl** [comment]
An update on this. 

I finish writing the real-time layer through WebSockets. Soon I will be implementing it to the actual report. It will use [**gwsocket.io**](http://gwsocket.io/).

Very excited about the upcoming version :)

**Comment by allinurl** [comment]
version 1.0 is out!  Features a complete real-time HTML bootstrap dashboard with a lot of updates to it. https://goaccess.io
