### ISSUE TITLE
PRI * Requests

### ISSUE THREAD

**Issue by finnito** [allinurl/goaccess#2163]
Kia ora, first-up: thanks for the awesome software!

I'm running a `lighttpd/1.4.59 (ssl)` webserver on `Ubuntu 21.04` with `GoAccess - 1.4` and have everything working quite well. The only small thing I've noticed is that I get a bunch of `PRI`requests like this and they are cluttering up my stats:

```
118.149.74.42 www.putaiao.nz - [14/Aug/2021:13:24:12 +1200] "PRI * HTTP/2.0" 100 38 "-" "-"
```

<img width="805" alt="goaccess-pri" src="https://user-images.githubusercontent.com/6530078/129430510-67d57c94-9cd1-4961-8fcf-ac8ca7ef33ab.png">

My `log-format` as defined in my `goaccess.conf` is this:
```
log-format %h %V - [%d:%t] \"%r\" %s %b \"%R\" \"%u\"
```

How can I go about improving this?

Thanks :)

**Comment by allinurl** [comment]
Could you please post a few more lines from your access log? it looks like you are using a different format as I don't see the requested time but I do see the data in the report.

**Comment by finnito** [comment]
Hi, thanks for helping out! Here's a paste from just now:

```
208.115.199.19 sisscc.lesueur.nz - [16/Aug/2021:09:52:40 +1200] "HEAD / HTTP/1.1" 301 0 "https://sisscc.lesueur.nz" "Mozilla/5.0+(compatible; UptimeRobot/2.0; http://www.uptimerobot.com/)"
208.115.199.19 www.sisscc.lesueur.nz - [16/Aug/2021:09:52:41 +1200] "HEAD /?_url=%2F HTTP/1.1" 200 0 "https://sisscc.lesueur.nz" "Mozilla/5.0+(compatible; UptimeRobot/2.0; http://www.uptimerobot.com/)"
108.162.249.17 www.lesueur.nz - [16/Aug/2021:09:54:37 +1200] "PRI * HTTP/2.0" 100 - "-" "-"
108.162.250.162 putaiao.lesueur.nz - [16/Aug/2021:09:55:12 +1200] "GET /te-reo/ HTTP/2.0" 301 0 "-" "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"
108.162.250.162 putaiao.lesueur.nz - [16/Aug/2021:09:55:18 +1200] "PRI * HTTP/2.0" 100 133 "-" "-"
66.249.68.6 putaiao.nz - [16/Aug/2021:09:57:32 +1200] "GET /ads.txt HTTP/1.1" 301 0 "-" "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"
66.249.68.24 putaiao.nz - [16/Aug/2021:09:57:33 +1200] "GET /ads.txt HTTP/1.1" 404 341 "-" "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"
108.162.249.41 science.lesueur.nz - [16/Aug/2021:09:58:15 +1200] "GET /12ess/as91191/new-zealand-plate-tectonics/ HTTP/2.0" 301 0 "-" "Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.119 Mobile Safari/537.36 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"
108.162.249.41 science.lesueur.nz - [16/Aug/2021:09:58:21 +1200] "PRI * HTTP/2.0" 100 157 "-" "-"
66.249.68.24 putaiao.nz - [16/Aug/2021:09:58:35 +1200] "GET /favicon.ico HTTP/1.1" 404 341 "-" "Googlebot-Image/1.0"
207.46.13.2 putaiao.nz - [16/Aug/2021:10:00:03 +1200] "GET / HTTP/1.1" 301 0 "-" "Mozilla/5.0 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)"
66.249.79.25 adventurelog.nz - [16/Aug/2021:10:00:21 +1200] "GET /places/mount-thomas-forest-conservation-area HTTP/1.1" 200 20874 "-" "Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.119 Mobile Safari/537.36 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"
Waiting for data... (interrupt to abort)
```

**Comment by allinurl** [comment]
I'd run it as:

    grep -v 'PRI * ' access.log | goaccess - --log-format='%h %v %^[%d:%t %^] "%r" %s %b "%R" "%u"' --date-format=%d/%b/%Y --time-format=%T

or real-time as

    tail -F access.log | grep -v --line-buffered 'PRI * ' |  goaccess - --log-format='%h %v %^[%d:%t %^] "%r" %s %b "%R" "%u"' --date-format=%d/%b/%Y --time-format=%T

**Comment by finnito** [comment]
Sweet, got it. I'm running it as an every 30mins cronjob so got this:

```
grep -v "PRI * " /var/log/lighttpd/access.log | goaccess
```

Appreciate the help! Is there some way I can purge those requests from my persisted DB files?

**Comment by allinurl** [comment]
You will need to run it again. 

Also, don't forget to pass `-` to goaccess so it knows to read from the pipe.

#117 should make things easier. Working on it as we speak :) Stay tuned!
