### ISSUE TITLE
Trying to get in touch regarding a security issue

### ISSUE THREAD

**Issue by zidingz** [allinurl/goaccess#2164]
Hey there!

I'd like to report a security issue but cannot find contact instructions on your repository.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by allinurl** [comment]
Thanks so much for reporting this. I went ahead and added the [SECURITY.md](https://github.com/allinurl/goaccess/blob/master/SECURITY.md) policy. Please take a look at it and let me know if you have any questions.

**Comment by allinurl** [comment]
It looks like this was an issue on the goaccess website and not in the project. However, I do appreciate you taking the time to report any issues.

Feel free to reopen it or report any other issues as needed. Thanks!

**Comment by zidingz** [comment]
Thanks for taking the time to review!
