### ISSUE TITLE
Error Config file: No config file used

### ISSUE THREAD

**Issue by NicoCaldo** [allinurl/goaccess#2167]
I'm unable to set my config file for GoAccess permanently.

If I run `goaccess access.log -c` and chose the first option everything goes smoothly and I can access the log. If I want to create a real-time webpage, I got the error on the title.

My GoAccess conf file is in _/etc/goaccess/goaccess.conf_ and my log is in _/var/log/apache2/access.log_

Ho can I create the dynamic page in my public HTML folder _/var/www/html/report.html_ ?

**Comment by allinurl** [comment]
Please try setting your config file under `~/.goaccessrc` and setting your options in there (no equal sign within the config file).

Then you should be able to run it as:

    # goaccess /var/log/apache2/access.log -o /var/www/html/report.html

or 

    # goaccess /var/log/apache2/access.log -p ~/.goaccessrc -o /var/www/html/report.html

**Comment by NicoCaldo** [comment]
It seems that this command worked

`goaccess /var/log/apache2/access.log -p /etc/goaccess/goaccess.conf -o /var/www/html/report.html --real-time-html`
