### ISSUE TITLE
Problem with Goaccess and uncorrect number of visitors 

### ISSUE THREAD

**Issue by xXEusXx** [allinurl/goaccess#2168]
Hi, I am new to goaccess and I have found a problem with my nginx log files. Goaccess extracts all the data correctly but sometimes, like in Not Found URLs (404s) table, it ends up having a 0 in visitors field whereas the number of hits is different from 0 for a given URL. On the other hand if I extract that given url directly from the file without using Goaccess (using grep...) I have the same number of hits observed with Goaccess, but the number of visitors is different. I don't understand why it happens and if it is correct to have 0 visitors. I am currently using the version 1.5.1, also I have configured the log-format to %h %^[%d:%t %^] "%r" %s %b "%R" "%u"

**Comment by allinurl** [comment]
Thanks for posting. It could be a log format issue. Are you able to replicate this with a smaller dataset and share those access lines here? Or feel free to email me the sample logs I can replicate the issue. Thanks!

**Comment by xXEusXx** [comment]
Yes I'm going to share a few access lines with you:


209.141.41.98 - - [20/Aug/2021:04:06:03 +0200] "POST /boaform/admin/formLogin HTTP/1.1" 501 4 "http://130.192.167.247:8080/admin/login.asp" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:71.0) Gecko/20100101 Firefox/71.0"
175.111.131.50 - - [20/Aug/2021:04:52:23 +0200] "GET / HTTP/1.1" 501 4 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/601.7.7 (KHTML, like Gecko) Version/9.1.2 Safari/601.7.7"
205.185.115.135 - - [20/Aug/2021:05:08:16 +0200] "POST /boaform/admin/formLogin HTTP/1.1" 404 337 "http://130.192.167.247:80/admin/login.asp" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:71.0) Gecko/20100101 Firefox/71.0"
109.121.163.185 - - [20/Aug/2021:05:21:33 +0200] "GET / HTTP/1.1" 200 2102 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/601.7.7 (KHTML, like Gecko) Version/9.1.2 Safari/601.7.7"
5.89.58.145 - - [20/Aug/2021:05:21:54 +0200] "GET / HTTP/1.1" 400 150 "-" "-"
192.241.201.68 - - [20/Aug/2021:05:34:03 +0200] "GET / HTTP/1.1" 200 1016 "-" "Mozilla/5.0 zgrab/0.x"
209.141.47.134 - - [20/Aug/2021:05:36:48 +0200] "POST /boaform/admin/formLogin HTTP/1.1" 404 337 "http://130.192.167.247:80/admin/login.asp" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:71.0) Gecko/20100101 Firefox/71.0"
190.94.136.207 - - [20/Aug/2021:05:43:55 +0200] "GET / HTTP/1.1" 200 2102 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36"
186.33.111.206 - - [20/Aug/2021:05:54:05 +0200] "GET / HTTP/1.1" 200 2102 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36"
88.9.119.217 - - [20/Aug/2021:06:14:37 +0200] "GET / HTTP/1.1" 200 1016 "-" "Mozilla/5.0 zgrab/0.x"
45.146.164.110 - - [20/Aug/2021:06:40:15 +0200] "POST /api/jsonws/invoke HTTP/1.1" 200 72 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36"
45.146.164.110 - - [20/Aug/2021:06:40:16 +0200] "GET /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php HTTP/1.1" 404 337 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36"
45.146.164.110 - - [20/Aug/2021:06:40:16 +0200] "GET /solr/admin/info/system?wt=json HTTP/1.1" 404 337 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36"
45.146.164.110 - - [20/Aug/2021:06:40:17 +0200] "GET /index.php?s=/Index/\x5Cthink\x5Capp/invokefunction&function=call_user_func_array&vars[0]=md5&vars[1][]=HelloThinkPHP21 HTTP/1.1" 404 337 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36"
45.146.164.110 - - [20/Aug/2021:06:40:17 +0200] "GET /?a=fetch&content=<php>die(@md5(HelloThinkCMF))</php> HTTP/1.1" 200 1016 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36"
45.146.164.110 - - [20/Aug/2021:06:40:17 +0200] "POST /vendor/phpunit/phpunit/src/Util/PHP/eval-stdin.php HTTP/1.1" 404 337 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36"
45.146.164.110 - - [20/Aug/2021:06:40:17 +0200] "GET /?XDEBUG_SESSION_START=phpstorm HTTP/1.1" 200 1016 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36"
45.146.164.110 - - [20/Aug/2021:06:40:17 +0200] "GET /wp-content/plugins/wp-file-manager/readme.txt HTTP/1.1" 404 337 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36"
45.146.164.110 - - [20/Aug/2021:06:40:18 +0200] "GET /console/ HTTP/1.1" 404 337 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36"
45.146.164.110 - - [20/Aug/2021:06:40:18 +0200] "POST /Autodiscover/Autodiscover.xml HTTP/1.1" 404 337 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36"
45.146.164.110 - - [20/Aug/2021:06:40:18 +0200] "GET /_ignition/execute-solution HTTP/1.1" 404 337 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36"

Also a screenshot I have obtained:
![Screenshot from 2021-08-23 15-04-18](https://user-images.githubusercontent.com/10198289/130472726-41a90976-46e7-4f67-819a-68e45f4a3113.png)


I have considered  POST /boaform/admin/formLogin which corresponds to the first row of the table in the screenshot

**Comment by allinurl** [comment]
I get the same numbers for `boaform/admin/formLogin`. Are you getting different numbers? As far as 0 visitors for 4xxs, please use `--4xx-to-unique-count` if needed.

![2021-08-23-183949_661x784_scrot](https://user-images.githubusercontent.com/5005367/130533007-33012303-acc0-4b57-b2d5-1576b020c6c6.png)

vs

![2021-08-23-183957_660x762_scrot](https://user-images.githubusercontent.com/5005367/130533017-802770d8-efd7-493d-86f8-df17194b8103.png)

**Comment by xXEusXx** [comment]
Ok I have the same numbers. I have also solved the issue of 0 visitor using `--4xx-to-unique-count`. Thank you!

**Comment by allinurl** [comment]
Glad that's working.

Closing this, feel free to reopen it if needed.
