### ISSUE TITLE
nginx log format question

### ISSUE THREAD

**Issue by candywind** [allinurl/goaccess#2173]
Hi, I got some problems when analysis nginx log with v1.15.1,  data with response time and tx amount can't displayed in detail info as below. 

![20210902145239](https://user-images.githubusercontent.com/5849061/131797489-c00232b4-5dd4-4df8-9aa1-b32502200254.png)

 but the same conf file displayed well when output result into a file.  pls tell me what can I do to make data well displayed in each panel ? is there any differences  between  command line and file? thanks.

goaccess -f access.log -p gonginx.conf
goaccess -o report.html -f access.log -p gonginx.conf

![20210902151515](https://user-images.githubusercontent.com/5849061/131799449-cc82cc5c-cd59-4453-871b-a93c06733c7f.png)

My nginx log format:
$remote_addr - $remote_user [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent" "$http_x_forwarded_for" $request_time "$host"

example data：
111.11.11.11 - - [30/Aug/2021:15:59:15 +0800] "POST /a/b/c HTTP/1.1" 200 1280 "http://222.222.222.222/index.html" "Mozilla/5.0 (Linux; U; Android 10; zh-CN; M2007J17C Build/QKQ1.200628.002) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/69.0.3497.100 UWS/3.22.2.1 Mobile Safari/537.36 UCBS/3.22.2.1_210128135735 ChannelId(2) NebulaSDK/1.8.100112 Nebula TaurusApp(saas/2.4.0) TaurusLanguage/zh_CN TaurusFontSizeType/1 mPaaSClient" "-" 0.034 "223.3.3.3"

My goaccess config file format：
time-format %T
date-format %d/%b/%Y
log_format %h - %^ [%d:%t %^] "%r" %s %b "%R" "%u" "%^" %T "%^"

**Comment by allinurl** [comment]
Sorry about the delay on this. It looks like it's related to the bold font on your terminal and how you have it configured. You can select the text with your mouse over those "empty" columns and you will probably see the data. Two fixes, either you change your terminal bold colors or you can configure your goaccess theme. Please take a look at the [config file colors](https://github.com/allinurl/goaccess/blob/master/config/goaccess.conf#L218).

Closing this. Feel free to reopen it if needed.
