### ISSUE TITLE
Failed Requests counter not working

### ISSUE THREAD

**Issue by IskeFCRS** [allinurl/goaccess#2174]
Hi,

I have recently started using GoAccess. Everything is working great, except for one thing.

Failed Requests counter always shows 0, but in status codes, I can see that there are many failed requests by status code. 

![Screenshot 2021-09-02 at 08 15 15](https://user-images.githubusercontent.com/9365780/131850729-ca2d333e-6c1d-4d12-93ee-f0509f222a20.png)

![Screenshot 2021-09-02 at 08 15 33](https://user-images.githubusercontent.com/9365780/131850721-31708c87-3163-43d6-b2a9-c9126c85bd56.png)

I tried to find some config related to this but with no luck. The version used is 1.5.1. Please advice...

**Comment by allinurl** [comment]
@0bi-w6n-K3nobi is 100% right. Closing this. Feel free to reopen it if needed.
