### ISSUE TITLE
Need help to rotate logs

### ISSUE THREAD

**Issue by jorgerampinini** [allinurl/goaccess#2175]
Hi,
This is no related strictly to goaccess functionality, but to how to use it in a particular scenario.
I am getting some gziped log files within a year/month/day folder structure. Inside each day folder, there are several gz files for every 5 minutes interval.
I wrote a script that goes into current date folder, and gunzip all files appending them to a day-named log file in another folder, and moves the original files to a third folder for debugging and archiving. That works fine, from command line and also using cron.

Script:
BASEDIR='/mnt/viplogs/log/production'
cd $BASEDIR/"$(date -u +"%Y/%m/%d")"
for f in *.gz ; do
echo "$f";
gunzip -c "$f" >> /home/test/"$(date -u +"%Y%m%d")".log ;
mv "$f" $BASEDIR/"$(date -u +"%Y/%m/%d")"/proc/
done

Cron:
*/5 * * * * /home/pruebas/generalog.sh

Then, I am running goaccess from the directory where the daily log is, and serving it as a real time html:

 goaccess "$(date -u +"%Y%m%d")".log -o /var/www/html/viplogs.rn/index.html --real-time-html

This is working fine during the day, but then fails when day changes.

I tried this other script (using cron, running it daily some 12 minutes after the change of the day):

#kill the running goaccess
pkill -9 goaccess 
# rename the old index.html to yyyymmdd.log
mv /var/www/html/viplogs.rn/index.html /var/www.html/viplogs.rn/"$(date -u +"%Y%m%d")".html
#start a new goaccess instance, using current date as parameter for input file name
goaccess "$(date -u +"%Y%m%d")".log -o /var/www/html/viplogs.rn/index.html --real-time-html

This runs until it kills the running goaccess, and renames the index.html, but never starts the new goaccess instance.

I am sure that there is a better way of doing this, but I don't know it!
Perhaps someone here faced a similar situation and can give me some hints,.

Thanks in advance,
Jorge

**Comment by 0bi-w6n-K3nobi** [comment]
Hi @jorgerampinini 

For real-time I can give you several tricks and hits.

For begin, maybe do you need wait a little bit more to `KILL`  command stop `GoAccess`.
The `GoAccess` need dealloc memory and close ports until finish. In real-time condition time for finish can be litte bigger.
Alternatily, You can use `kill -INT` for simulate Control-C.
Make some test youself for check time for that.

Well, now I can give some alternatives...

**First**
You not need stop `GoAccess`... and if you specify `LOG` filename without date.
`GoAcess` ever time close and reopen file to process request lines.
At change of day, if you keep same name, do you need rename old `LOG` and put new `LOG` in same directory.
Thus `GoAccess` will be see that `LOG` is new and start begin to process them.
Notes here:
*  You need, of course,  to be sure that `GoAccess` finished processing `OLD LOG`;
* If GoAccess have problem to identify the exchange of `LOG`,  then you can trunc `LOG` [zero], wait a little bit, and put new `LOG`;
* for release old data (day ago) you can specify [--keep-last=1](https://goaccess.io/man#options);

**Second**
If you want restart `GoAccess` at midnight, than you can use `timeout` command.
I use in my servers:
`timeout`**`$(( 24*60 - ($(date +%H)*60 + $(date +%M)) ))m`**`goaccess ...`

and it will graceful finish the process.
Again... `timeout` allow choice `kill` signal value.

The advantage for that [stop `GoAcccess`] is, if that your browser connected at  `GoAccess`, you will see exactly values at stop moment, i.e. midnight.
So, you need refresh page for continue real-time monitoring.

**Third**
You do not need concat or move your `LOGs`.
For, you can use a little trick -- `FIFO` file:

`mkfifo pipefile`
`while [ 1 ]; do cat pipefile; done | goaccess -f - --real-time  ...`

and at your cron/script:

`gunzip -c * >> pipefile`

Remembering that `GoAccess` will never stop here.
And do you need use `kill` or `timeout` for that.

**Fourth**
You can use `SSHFS` or `NFS` for access remote server `LOGs`.

I hope that helped you.

**Comment by jorgerampinini** [comment]
Hi @0bi-w6n-K3nobi 
Thank you for all your tricks, I will give them a try, and tell you how it was.
 Regarding the fourth one, use of SSHFS or NFS, the remote logs are stored in an S3 bucket, so I am using s3fs.
Thanks again, and may the Force be with you! :)

**Comment by allinurl** [comment]
@0bi-w6n-K3nobi Thanks for sharing all that, really good info! 

Closing this, feel free to reopen it if needed.
