### ISSUE TITLE
Multiple Files - crashed by Sig 11

### ISSUE THREAD

**Issue by samcro1967** [allinurl/goaccess#2178]
Having a problem trying to parse multiple log files.

**Command used to run goaccess**
```
zcat --force /home/user/Documents/Docker/caddy2/data/*.log* | docker run -v /home/user/Documents/Docker/goaccess/GeoLite2-City.mmdb:/GeoLite2-City.mmdb --rm -i -e LANG=$LANG allinurl/goaccess -a -o html --geoip-database GeoLite2-City.mmdb --log-format CADDY - > /home/user/Documents/Docker/goaccess/index.html
```

**Error message**
```
[PARSING -] {116348} @ {19391/s}s}
==1== GoAccess 1.5.2 crashed by Sig 11
==1==
==1== VALUES AT CRASH POINT
==1==
==1== FILE: -
==1== Line number: 116624
==1== Invalid data: 48245
==1== Piping: 1
==1==
==1==
==1== Please report it by opening an issue on GitHub:
==1== https://github.com/allinurl/goaccess/issues
```

**Comment by allinurl** [comment]
Thanks for reporting this. Do you know if this was running fine before? I ask cause I recently pushed some changes so I wonder if it was working fine for you a few days ago?

**Comment by samcro1967** [comment]
Today was the first time I noticed the issue and the first time I tried passing multiple log files.

**Comment by allinurl** [comment]
I was trying to reproduce this on my end but I was unable to. Are you able to run it against only one log? and with minimal cmd options? e.g.,

    cat /home/user/Documents/Docker/caddy2/data/access.log | docker run -v /home/user/Documents/Docker/goaccess/GeoLite2-City.mmdb:/GeoLite2-City.mmdb --rm -i -e LANG=$LANG allinurl/goaccess -a -o html --geoip-database GeoLite2-City.mmdb --log-format CADDY - > /home/user/Documents/Docker/goaccess/index.html


and

    zcat --force /home/user/Documents/Docker/caddy2/data/*.log* | docker run --rm -i -e LANG=$LANG allinurl/goaccess -a -o html --log-format CADDY - > /home/user/Documents/Docker/goaccess/index.html

I'm thinking this could be an issue with the JSON parser and not necessarily an issue with multiple logs.

Thank you!

**Comment by samcro1967** [comment]
The cat command worked as expected.  The zcat command failed as before.  Is there someway I can privately share the log files with you to see if it is an issue on my end or something else?

This is not a big deal for me, but happy to help if you want to troubleshoot further.

**Comment by allinurl** [comment]
Thanks for getting back to me. 

That would be great, are they fairly big >25MB? otherwise you can send them my way via hello [[at]] goaccess . io or do you have a google drive where you can share the URL via email? Thanks again!

**Comment by samcro1967** [comment]
Well, I realized my mistake as I was grabbing the logs to send to you.  I have the access and caddy logs in the same directory.  *.log* was grabbing both.  Changing it to access*.log* works as it only grabs the access logs.  Working as expected now.

**Comment by allinurl** [comment]
Good to know. Question, would you still be able to share your logs? I want to make sure this gets fixed as it shouldn't be segfaulting. If you prefer not share those logs, would you be able to run it through gdb to see where exactly is crashing? Thanks again.

**Comment by samcro1967** [comment]
See if you can grab them from here.  Let me know so I can remove them after you have them.  It is both the access and caddy logs that I was processing. 
[Link](https://drive.google.com/file/d/1whHJZfLJsI41yzWtWa7N386kGsoZoQje/view?usp=sharing)

**Comment by allinurl** [comment]
Got them. Thanks, I'll post back.

**Comment by allinurl** [comment]
The issue has been fixed upstream. Thanks a lot for sharing that and letting me know. It will be pushed out pretty soon as v1.5.2.

**Comment by samcro1967** [comment]
Glad I could help.  Should I be processing both the access logs and the system logs?  I guess my thought is everything on the dashboard seems to be access related so there is no need to process the caddy system logs.

**Comment by allinurl** [comment]
You could, but it would just ignore those lines and mark them as invalid since they won't match the log-format. For faster processing, I'd just target the access logs.
