### ISSUE TITLE
cannot set different ws port for client connection via 'ws-url'

### ISSUE THREAD

**Issue by bekcpear** [allinurl/goaccess#2179]
refer to issue https://github.com/allinurl/goaccess/issues/447

The above issue said, `ws-url example.domain:9999` config will set a different port for frontend to connect to the a GoAccess instance which behind a proxy. The comment in goaccess.conf https://github.com/allinurl/goaccess/blob/0abddd5f09ea6385b8bc2b6b1e0d13e438c1697c/config/goaccess.conf#L308-L311 also says.

However it's invalid now, only the 'port' config be considered.

https://github.com/allinurl/goaccess/blob/1ce51ed8682c9269ae8a05367fbc95447a1cab38/src/output.c#L508-L509

I think it's a very useful feature, so can it be added?

**Comment by bekcpear** [comment]
Sorry, it's my fault. I set a wrong url format. And it has nothing to do with output.c file. The correct format to specify a different port with a specified path is

```
[protocol://]example.domain:<port>[/<remaining-path>]
```

**Comment by allinurl** [comment]
Glad you got it sorted out. Feel free to reopen it if needed.
