### ISSUE TITLE
avif (and probably jxl) are treated as "requested files (URLs)"

### ISSUE THREAD

**Issue by G2G2G2G** [allinurl/goaccess#2183]
These should be in the STATIC requests section, however they're currently in the URLs section

Looks like avif and jxl would just go here:
https://github.com/allinurl/goaccess/blob/master/src/settings.c#L169-L205

**Comment by allinurl** [comment]
Thanks for bringing this up. I've added this upstream to be taken into account by default. You can always enable this in the config file or passing  `--static-file=.avi`.

Closing this. Stay tuned for the upcoming release.
