### ISSUE TITLE
Issue with date/time/log format for custom logs

### ISSUE THREAD

**Issue by mgrapiniak** [allinurl/goaccess#2184]
Hi!

I do have a custom log file with the following:
`1.23.81.34 - - [Wed, 15 Sep 2021 09:59:09 GMT] "GET /some/url/home.html HTTP/1.1" 200 70749 "-" "Amazon CloudFront"`

Having difficulties to set appropriate parameters in date/time/log format.
Changed combined  date format to following:

`%a, %d %b %Y`

But still unable to parse.
Any hints on this one?

**Comment by allinurl** [comment]
This should work:

    goaccess access.log --log-format='%h %^[%d %t %^] "%r" %s %b "%R" "%u"' --date-format='%a, %d %b %Y' --time-format=%T
