### ISSUE TITLE
[Help] Need real-time-html report

### ISSUE THREAD

**Issue by JoelDivekar** [allinurl/goaccess#2186]
Recently started using goaccess for our apache base website. We are able to get console running and even was able to generate static HTML page. But again whenever I try to generate report in HTML either static or relatime it shows Websocket interface. Wereas would like to automate a process to generate real-time-html report which runs in background as a daemon or system service. Please can you guide. If this is answered already then please excuse me and share the link for me to refer.

**Comment by allinurl** [comment]
I'm not sure I follow, but if you are interested in running goaccess in the background, you could run it as:

    goaccess access.log --log-format=COMBINED --daemonize

Or you could do it through systemd, e.g., #1898 

Let me know if that helps.

**Comment by JoelDivekar** [comment]
Yes, I did that exactly and it is working fine. But I may have to set it up as a service which will auto start with system reboot. Thanks a lot @allinurl

**Comment by allinurl** [comment]
Glad to hear you got it to work :)

Feel free to reopen it if needed.
