### ISSUE TITLE
v1.52 regression- piping logs not working (it did work for v1.4)

### ISSUE THREAD

**Issue by gps3dx** [allinurl/goaccess#2189]
Hi @allinurl
As I mentioned [here](https://github.com/allinurl/goaccess/issues/1781#issuecomment-925922045) I managed to compile GoAccess v1.52 being partially static.

Then I tested the result:
```
>>cat access_log/localhost_access_log..2020-09-2* | /tmp/goaccess -p /tmp/goaccess.conf > /tmp/goaccess_report.html
GoAccess - version 1.5.2 - Sep 23 2021 11:11:23
Config file: /tmp/goaccess.conf
Fatal error has occurred
Error occurred at: src/goaccess.c - initializer - 1459
No input data was provided nor there's data to restore.
```
As can be seen - I'm not able to pipe the logs to goaccess - while I could do so using GoAccess v1.4 that I compiled in the past.
Nonetheless, using the same compiled binary - I can successfully use GoAccess when I use the '-f' flag to point to the log/s.
```
>>/tmp/goaccess -p /tmp/goaccess.conf -f access_log/localhost_access_log..2020-09-2* > /tmp/goaccess_report.html                        
 [PARSING access_log/localhost_access_log..2020-09-25.log] {7,553} @ {0/s}@ {0/s}
```

**Therefore I wonder what is the root cause I cannot pipe logs to GoAccess v1.52 ?**

- is it the ["#define _BSD_SOURCE" fix](https://github.com/allinurl/goaccess/issues/1781#issuecomment-925922045) I embedded in 'src/parse.c' ?
- is it because I static compile '-lnsl' library that I didn't the last time ?
- or is it something else not related that happened/added to GoAccess code in newer versions since v1.4.2 ahead ?

**Comment by allinurl** [comment]
Are you able to test this out by passing a dash to goaccess. e.g.,

    cat access_log/localhost_access_log..2020-09-2* | /tmp/goaccess - -p /tmp/goaccess.conf > /tmp/goaccess_report.html

Also, feel free to share your config file. Thanks

**Comment by gps3dx** [comment]
@allinurl - thank you very much for the reply.
Piping using the syntax you offered does work as expected :-)
Thanks !

I guess this "regression" issue can be closed - unless you expect piping to GoAccess to work w/o added "-" switch to be backward compatible (i.e. w/o regression).

**Comment by allinurl** [comment]
Closing this, feel free to reopen it if needed.
