### ISSUE TITLE
I can't parse the log file

### ISSUE THREAD

**Issue by Ermin34** [allinurl/goaccess#2198]
`"85.105.155.40 - - [30/Sep/2021:09:27:17 +0000] "GET /wp-content/uploads/2021/07/tuba-ablaya-sor-favicon.png HTTP/1.1" 200 937 "https://www.tubaablayasor.com/dunyanin-en-yuksek-faiz-uygulayan-ulkeleri/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.61 Safari/537.36""
"5.255.253.152 - - [30/Sep/2021:09:27:25 +0000] "GET /dunyanin-en-yuksek-faiz-uygulayan-ulkeleri/ HTTP/1.1" 200 31609 "-" "Mozilla/5.0 (compatible; YandexBot/3.0; +http://yandex.com/bots)""
"178.250.2.34 - - [30/Sep/2021:09:27:28 +0000] "GET /dunyanin-en-yuksek-faiz-uygulayan-ulkeleri/ HTTP/1.1" 200 31609 "-" "CriteoBot/0.1 (+https://www.criteo.com/criteo-crawler/)""
`
Here are the lines in my log file. And this is the structure I use to parse

`goaccess /home/xxxx/logs/xxxx.log --log-format='%h %^[%d:%t %^] %m %^ %H %^ %U %s %b "%R" "%u"' --date-format=%d/%b/%Y --time-format=%T
`
this is the error i got :
`Parsed 1 linesproducing the following errors:

Token '"85.105.155.40' doesn't match specifier '%h'
`
how can i solve this problem?

**Comment by 0bi-w6n-K3nobi** [comment]
Hi @Ermin34 

Do you really have quotes starting the line, and ending?
And before `"178.250.2.34` there is no line break? 
If `YES` then you maybe try:

`--log-format='"%h %^[%d:%t %^] "%r" %s %b "%R" "%u""'`

I hope that I could help You.

**Comment by Ermin34** [comment]
> Merhaba @Ermin34
> 
> Satırı _başlatan_ ve _biten_ gerçekten **alıntılarınız** var mı? Ve herhangi bir satır sonu olmadan önce ? Eğer o zaman belki denemek:____`"178.250.2.34``YES`
> 
> `--log-format='"%h %^[%d:%t %^] "%r" %s %b "%R" "%u""'`
> 
> Umarım Size yardımcı olabilmişimdir.

thanks
your suggestion worked very well..
I used it like this and I was able to get a report
`--log-format='"%h %^ %^ [%d:%t %^] "%v %r" %s %b "%R" "%u""'   --date-format=%d/%b/%Y --time-format=%T --real-time-html `

**Comment by 0bi-w6n-K3nobi** [comment]
Ho @Ermin34

Yeah.  The formats are equivalent  -- `%h %^ %^ [` and `%h %^[`.
The second field in `LOGFILE` is ever `-` and third is the _authenticated user_.
But, I can't see the filed `%v` next to `%r`. Are you sure about this?

**Comment by allinurl** [comment]
Thanks @0bi-w6n-K3nobi. Closing this, feel free to reopen it if needed.
