### ISSUE TITLE
Ask for help for parsing Weblogic log 

### ISSUE THREAD

**Issue by Fatsi321** [allinurl/goaccess#2201]
Hi, i want to try to use GoAccess to parse Weblogic log with the following format:

2021-09-30	11:07:21	GET	/foo/bar/test.jsp	200	xx.xx.xx.xx	-	-
2021-09-30	11:07:22	GET	/foo/bar/	200	xx.xx.xx.xx	"yy.yy.yy.yy"	"Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; rv:11.0) like Gecko"

It is tab separated, xx.xx.xx.xx is the proxy ip and "yy.yy.yy.yy" is the client ip. 
For "VISITOR HOSTNAMES AND IPS", if "yy.yy.yy.yy" is -, use xx.xx.xx.xx, if "yy.yy.yy.yy" has value, use yy.yy.yy.yy.

When I try to use:
goaccess test.log* --log-format='%d\t%t\t%m\t%U\t%s\t%h\t~h{"\t}\t"%u"' --date-format='%Y-%m-%d' --time-format='%H:%M:%S'

It will return error:

Parsed 1 linesproducing the following errors:
Token already set for '%h' specifier.
Format Errors - Verify your log/date/time format

Would you please help? Thank you.

**Comment by 0bi-w6n-K3nobi** [comment]
Hi @Fatsi321

First , I have two questions:
* Maybe the first line have quotation marks in the last fields? i.e `... xx.xx.xx.xx` **`"-"` `"-"`**
   A pattern is needed on all lines/requests.
* Is there really `TABS` between the fields? Wouldn't it be simple `SPACE`?

**Comment by 0bi-w6n-K3nobi** [comment]
Hi @allinurl

I'm having a little trouble doing this parse...
I am not able to adjust the `~h` field correctly and so it is swallowing the others as `%u`.

**Comment by geof77** [comment]
I think using %h and ~h in the same filter is not supported. I would replace %h with %^ (ignore field).

**Comment by allinurl** [comment]
Sorry for the late reply. Can you please attach a file with actual access log lines (a few lines is fine)? It's hard to determine the spacing without an actual file to work with. Thanks

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
