### ISSUE TITLE
Real time web log not work after update to 1.5.2 SSL

### ISSUE THREAD

**Issue by cwyin7788** [allinurl/goaccess#2202]
Hi developer,I have this problem, please help.

I have two servers, before I upgrade, everything is alright, after both servers upgrade to 1.5.2, the websocket real-time web log not work anymore, I didn't touch anything, just upgrade the version, the page left corner green light turns off, 

<img width="63" alt="螢幕截圖 2021-10-05 上午8 23 00" src="https://user-images.githubusercontent.com/53026952/135941669-be4f1a0f-67af-4aa9-85d5-e9691b167a18.png">

and the page become to static page,I need to reload the page update the data. let me describe the settings in details.

**I use this option to compile 1.5.2**

./configure --enable-utf8 --enable-geoip=mmdb --enable-debug --with-getline --with-openssl

two servers os also use ubuntu 21.04

**I make goaccess as systemd service run in background：**

```
root@ubuntu:/etc/nginx# cat /etc/systemd/system/goaccess.service
[Unit]
Description=Goaccess Web log report.
After=network.target
StartLimitIntervalSec=0

[Service]
Type=simple
User=root
Group=root
Restart=always
RestartSec=1800
ExecStart=/usr/local/bin/goaccessreport
StandardInput=tty
StandardOutput=tty
StandardError=tty
TTYPath=/dev/tty7

[Install]
WantedBy=multi-user.target
```

here is the /usr/local/bin/goaccessreport

```
#!/bin/bash
zcat -f /var/log/nginx/*access.log.* | /usr/local/bin/goaccess /var/log/nginx/*access.log - -o /var/www/goaccess.mysite.com/index.html --ws-url=wss://goaccess.mysite.com --ssl-cert=/root/cert/ecc384.crt --ssl-key=/root/cert/ecc384.key --log-format='%h %^[%d:%t %^] %K/%k "%r" %s %b "%R" "%u"' --date-format=%d/%b/%Y --time-format=%T --real-time-html
```

**nginx.conf log settings：**

```
         log_format proxy '$proxy_protocol_addr - $remote_user [$time_local] '
                     '$ssl_protocol/$ssl_cipher '
                     '"$request" $status $body_bytes_sent '
                     '"$http_referer" "$http_user_agent"';

        access_log /var/log/nginx/access.log proxy;
        error_log /var/log/nginx/error.log;
```

**goaccess service can run without error, and it also LISTEN 7890**

<img width="1566" alt="螢幕截圖 2021-10-05 上午8 35 33" src="https://user-images.githubusercontent.com/53026952/135942540-2edc56c0-9f44-407f-8fd3-adec8f8dc356.png">

<img width="960" alt="螢幕截圖 2021-10-05 上午8 33 51" src="https://user-images.githubusercontent.com/53026952/135942552-bd9d9add-9ec5-45fa-8bb0-5d78262ab2c6.png">

**When I stop the goaccess service, run it in command:**

```
root@ubuntu:/usr/local/bin# ./goaccessreport
==Using TLS/SSL==
 [PARSING -] {43650} @ {3357/s}.log] {5320} @ {5320/s}
WebSocket server ready to accept new client connections
```

**after I access my sites, and check back the goaccess status, it show the following errors**

```
root@ubuntu:/usr/local/bin# ./goaccessreport
==Using TLS/SSL==
 [PARSING -] {43650} @ {3357/s}.log] {5320} @ {5320/s}
WebSocket server ready to accept new client connections
Accepted: 14 8.21.11.38
SSL: SSL_accept -> SSL_ERROR_WANT_READ
SSL: incomplete, data available for reading
SSL: SSL_accept -> failed fatal error code: 1
SSL: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
SSL: SSL_read -> SSL_ERROR_ZERO_RETURN
SSL: TLS/SSL connection has been closed
SSL: SSL_write -> SSL_ERROR_ZERO_RETURN
SSL: TLS/SSL connection has been closed
SSL: SSL_write -> SSL_ERROR_ZERO_RETURN
SSL: TLS/SSL connection has been closed
SSL: SSL_shutdown -> failed fatal error code: 1
SSL: error:140E0197:SSL routines:SSL_shutdown:shutdown while in init
Active: 0
```

**SSL Error？so I check my certificate, ecc384.crt / ecc384.key, It don't have any problem**

<img width="1488" alt="螢幕截圖 2021-10-05 上午8 50 30" src="https://user-images.githubusercontent.com/53026952/135943552-140b303a-17c8-4d73-bd5a-cc9486a6551f.png">

I don’t know why this happened. There was no problem before the update, but the problem appeared after the update.

Thanks for help first.

**Comment by allinurl** [comment]
Thanks for reporting this. If you are using Lets Encrypt, then it may be relayed to the September 30 issue. You will need to update the certificate chain. Let me know if that helps.

**Comment by cwyin7788** [comment]
> Thanks for reporting this. If you are using Lets Encrypt, then it may be relayed to the September 30 issue. You will need to update the certificate chain. Let me know if that helps.

thanks for your quick reply, I just updated the certificate, actually I really use letsencrypt cert.

<img width="1646" alt="螢幕截圖 2021-10-05 下午12 06 24" src="https://user-images.githubusercontent.com/53026952/135958923-dce4d2d7-a7d2-4b11-a863-3398b2df80aa.png">

and then, restart goaccess and nginx

service goaccess restart
service nginx restart

but the problem still here.

I've tried to remove nginx log and restart nginx, it also not work.

when I use command line to run goaccess

it show the same error:

<img width="876" alt="螢幕截圖 2021-10-05 下午12 16 36" src="https://user-images.githubusercontent.com/53026952/135959353-d24c924f-5945-4040-9574-fba1fc8e925b.png">

**Comment by 0bi-w6n-K3nobi** [comment]
Hi @cwyin7788

Maybe it's a stupid question, but...
Have you updated CA-Certificates' Server?

**Comment by cwyin7788** [comment]
> Hi @cwyin7788
> 
> Maybe it's a stupid question, but... Have you updated CA-Certificates' Server?

Excuse me, I don’t know how to update CA certificate,when I search google, I found that use this command apt update-ca-certificates ?

It didn’t update any certifcate

![AB1A7811-AC15-4FB6-8437-052D300373B6](https://user-images.githubusercontent.com/53026952/136035185-d4da9e92-9a21-4729-9de9-6d3e791d0697.png)

If I use wrong command, can you tell me how to update？

**Comment by cwyin7788** [comment]
> It only updates when I kill goaccess and start it again and refresh the report page... 

I have the same problem

**Comment by 0bi-w6n-K3nobi** [comment]
Hi @cwyin7788 

Do you check `LANG` variable enviroment? -- i.e. `echo $LANG`
Maybe you can set it. --  i.e. `export LANG en_US.UTF-8`
You must be set encoding to `UTF-8`, but the language is your choice.

**Comment by allinurl** [comment]
One more thing, note that when you run it via ask, you need to make sure you are using an https connection through the browser and your web socket should be wss instead of ws.

**Comment by markthompson1** [comment]
I Have the same or similar problem when trying to use a secure connection.

![image](https://user-images.githubusercontent.com/25227361/141518531-95946600-11d6-4972-853a-fed5669bfb45.png)

This is a new install and so unlike the OP, it has not worked for me previously

![image](https://user-images.githubusercontent.com/25227361/141518680-a83ed691-64b4-4f40-b3dc-873db755390e.png)

![image](https://user-images.githubusercontent.com/25227361/141518710-9c9964f8-a77a-440b-8d31-8d0e12436f24.png)

![image](https://user-images.githubusercontent.com/25227361/141518728-b314d6bd-3b1d-4e03-a4be-b38ad53dbbea.png)

I too have to stop and restart the goaccess process to update the static report.

**Comment by allinurl** [comment]
@markthompson1 are you able to telnet to that specific endpoint e.g., 209.... using port 7890? please make sure you are accessing the report via https://your_server.com/report.html. 

also, does the connection work without wss/ssl? and last, I assume you are only specifying a valid ipv4 address under ws-url... Thanks

**Comment by markthompson1** [comment]
Hi @allinurl ,

Yes, the port is open...

![image](https://user-images.githubusercontent.com/25227361/141647841-0dd7767e-2d56-4b5c-8e58-31b91d6f1b49.png)

And it works for when I disable https and use http only.

![image](https://user-images.githubusercontent.com/25227361/141647880-da5d57df-62f6-4586-aed1-9127c89e24c4.png)

**Comment by allinurl** [comment]
I'm trying to reproduce this, not sure yet exactly what's trigerring it, rt.goaccess.io is running v1.5.2 and seems to work fine using a Let's Encrypt certificate. A few questions for everyone:

1. Can anyone confirm if this was working fine on a previous version, e.g., v1.5 (please build from [**source**](https://github.com/allinurl/goaccess#build-from-github-development))?
2. If using Let's Encrypt, can I ask you to please try renewing the certificate with `--preferred-chain "ISRG Root X1"` to exclude expired root from the trust chains.
3. Please try if the following works (If you see a similar issue then it is Let's Encrypt related and you need to remove expired Root CA)
```
     $ curl https://curl.se
```
4. Please take a look at [this post](https://github.com/allinurl/goaccess/issues/2190#issuecomment-951067683) and let me know if that helps solve the issue.

 Thanks everyone!

**Comment by cwyin7788** [comment]
> I'm trying to reproduce this, not sure yet exactly what's triggering it, rt.goaccess.io is running v1.5.2 and seems to work fine using a Let's Encrypt certificate. A few questions for everyone:
> 
> 1. Can anyone confirm if this was working fine on a previous version, e.g., v1.5 (please build from [**source**](https://github.com/allinurl/goaccess#build-from-github-development))?
> 2. If using Let's Encrypt, can I ask you to please try renewing the certificate with `--preferred-chain "ISRG Root X1"` to exclude expired root from the trust chains.
> 3. Please try if the following works (If you see a similar issue then it is Let's Encrypt related and you need to remove expired Root CA)
> 
> ```
>      $ curl https://curl.se
> ```
> 
> 1. Please take a look at [this post](https://github.com/allinurl/goaccess/issues/2190#issuecomment-951067683) and let me know if that helps solve the issue.
> 
> Thanks everyone!

Hi Developer,

We also need to say thank you, thanks for your patiently help,

> 1. Can anyone confirm if this was working fine on a previous version, e.g., v1.5 (please build from [**source**](https://github.com/allinurl/goaccess#build-from-github-development))?

I've tried downgrade to 1.5, it's working fine, please see the screen capture.

<img width="1920" alt="螢幕截圖 2021-11-18 下午10 14 12" src="https://user-images.githubusercontent.com/53026952/142433237-fea21132-ea8e-4011-bd61-b7a5f75832a1.png">
 
===============================

Very strange, I just tried to test your suggestion 1.), after I finished the test, I upgrade to 1.5.2 again, and restart the service, It unexpectedly works again (the screen capture below is 1.5.2 and the green light on again)

<img width="1704" alt="螢幕截圖 2021-11-18 下午10 26 49" src="https://user-images.githubusercontent.com/53026952/142434596-af3ed543-47a2-4536-affa-2a05796d5686.png">

Here is what I did:

1.)delete /usr/local/bin/goaccess, (1.5.2)，and download 1.5 from source and compile it

2.)restart  goaccess

3.)visit my goaccess site and take a screen capture

4.)delete /usr/local/bin/goaccess, (1.5) and download 1.5.2 from source and re-compile it

5.)restart goaccess

1.5.2 real time web log work again 😳

I don't know why, I didn't touch any certificate stuff.

I will continue to pay attention to see the problem is really gone or not.

I didn't test 2, 3, 4 because it seems solved my problem.

**Comment by allinurl** [comment]
@markthompson1 are you still seeing this issue on your end? If yes, please let me know if following the steps on my previous post help. Thanks!

**Comment by allinurl** [comment]
@cwyin7788 Thanks for the update. Glad it's working for you.

**Comment by markthompson1** [comment]
I followed the, downgrade/upgrade steps that worked for the other poster, this didn’t work for me. I’ll try your additional steps about renewing and revoking the “lets encrypt” old certs and report back when I get chance.

 

Thanks for your support.

 

Mark 

 

From: "Gerardo O." ***@***.***>
Reply to: allinurl/goaccess ***@***.***>
Date: Tuesday, 23 November 2021 at 00:13
To: allinurl/goaccess ***@***.***>
Cc: Mark Thompson ***@***.***>, Mention ***@***.***>
Subject: Re: [allinurl/goaccess] Real time web log not work after update to 1.5.2 SSL (#2202)

 

@markthompson1 are you still seeing this issue on your end? If yes, please let me know if following the steps on my previous post help. Thanks!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by tmlnv** [comment]
> Also no livew update here....on two fresh Debian 11.1 installs with Apache2....
> 
> `goaccess example.net/logs/access.log -o example.net/html_public/report.html --log-format=COMBINED --real-time-html --ssl-cert=/etc/letsencrypt/archive/example.net/cert1.pem --ssl-key=/etc/letsencrypt/archive/example.net/privkey1.pem`
> 
> No warning/errors reported when starting goaccess...
> 
> It only updates when I kill goaccess and start it again and refresh the report page... WS in Chromes inspector jsut shows "pending" as status....

Confirm having the same issue

**Comment by allinurl** [comment]
@tmlnv, which version of GoAccess are you currently running?

**Comment by tmlnv** [comment]
@allinurl, 1.8.1
I am on Ubuntu 20 and I've tried a few options:
1) apt-get install goaccess
Generating report, the report is served via nginx, it is accessible, but not updating.
2) Official Debian/Ubuntu repo stated [here](https://goaccess.io/download#official-repo)
Same result as 1
3) Building with `./configure --enable-utf8 --enable-geoip=mmdb --with-openssl`
Got this config and the same result
```
Your build configuration:

  Prefix         : /usr/local
  Package        : goaccess
  Version        : 1.8.1
  Compiler flags :  -pthread
  Linker flags   : -lnsl -lncursesw -lmaxminddb -lcrypto -lssl -lpthread
  UTF-8 support  : yes
  Dynamic buffer : no
  Geolocation    : GeoIP2
  Storage method : In-Memory with On-Disk Persistent Storage
  TLS/SSL        : yes
  Bugs           : hello@goaccess.io
```

To run used
```
./goaccess /var/log/nginx/access.log -o /var/www/my_web/report.html --log-format=COMBINED --real-time-html --ssl-cert=/etc/ssl/my_cert.crt --ssl-key=/etc/ssl/my_private_key.txt
```
or
```
goaccess /var/log/nginx/access.log -o /var/www/my_web/report.html --log-format=COMBINED --real-time-html --ssl-cert=/etc/ssl/my_cert.crt --ssl-key=/etc/ssl/my_private_key.txt
```
No green light ever appeared on the dashboard near the gear.

**Comment by allinurl** [comment]
@tmlnv, I'm curious, can you run it without SSL and access the report using a non-HTTPS URL?

    # goaccess /var/log/nginx/access.log -o /var/www/my_web/report.html --log-format=COMBINED --real-time-html

**Comment by tmlnv** [comment]
@allinurl Yes, I can.
I get:
```bash
WebSocket server ready to accept new client connections
```
However, the report stays static and does not update.

**P.S.**
I have set up a cron job to execute a script for the creation of static reports from both .log and .gz log files regularly. This configuration fulfills all my needs. Therefore, no additional support is needed.

Thank you for your efforts and responses!

**Comment by allinurl** [comment]
It seems that this issue maybe isolated to your environment. My guess is it could be the network or some missing configuration. Either way, thanks for giving me the heads up, and good to know you found a workaround. Feel free to reopen it if you need to.
