### ISSUE TITLE
Apache custom log format question

### ISSUE THREAD

**Issue by ricott** [allinurl/goaccess#2203]
Hi,

sorry for yet another custom log format question, but I can't see what is wrong here

**Sample log lines**
```
xyz.se 81.170.206.86 - - [06/Oct/2021:10:44:30 +0200] "GET /index HTTP/1.1" 200 51 "https://xyz.se/chat" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.71 Safari/537.36 Edg/94.0.992.38"
xyz.se 81.170.206.86 - - [06/Oct/2021:10:44:30 +0200] "POST /chat HTTP/1.1" 200 22 "https://xyz.se/chat" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.71 Safari/537.36 Edg/94.0.992.38"
xyz.se 212.170.59.60 - - [06/Oct/2021:10:44:30 +0200] "GET /uz_selection HTTP/1.1" 200 1103 "https://xyz.se/uz_selection" "Mozilla/5.0 (Linux; Android 11; SAMSUNG SM-G991B) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/15.0 Chrome/90.0.4430.210 Mobile Safari/537.36"
xyz.se 83.233.62.2 - - [06/Oct/2021:10:44:30 +0200] "GET /project HTTP/1.1" 200 13662 "https://xyz.se/project" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.61 Safari/537.36"
```

**Custom Apache log format**
`%V %h %l %u %t "%r" %>s %b "%{Referer}i" "%{User-Agent}i"`

Trying to run the following command
`goaccess access.2021-10-06-09_23_08.log -o report.html --log-format='%v %h %^ %^ [%d:%t %^] "%r" %s %b "%R" "%u"' --date-format='%d/%b/%Y' --time-format='%H:%M:%S'`

I get the following error
```
==66718== Token '06/Oct/2021' doesn't match specifier '%d'
==66718==
==66718== Format Errors - Verify your log/date/time format
```

Running on MacOS (M1), installed goaccess today using brew.

**Comment by 0bi-w6n-K3nobi** [comment]
Hi @ricott 

It's OK for me.

What version are your running?
Check with: `goaccess --version`

Do You know about enviroment LANG?
Try this: `LANG=en_US.utf8 goaccess ...`

I hope that I could helped You.

**Comment by ricott** [comment]
Version: GoAccess - 1.5.2.

and yes, setting LANG did the trick 👍

Thanks!
