### ISSUE TITLE
Logarithmic scale

### ISSUE THREAD

**Issue by alfredneu** [allinurl/goaccess#2205]
My web site has strongly fluctuating number of visitors. In the charts I currently see a few spikes and otherwise a flat line at zero because regular traffic is so much lower than the spikes. I would love an option to set **logarithmic scale on the y-axis** so I can see both the high and the low counts. Added goodie: growth is much easier to estimate on a logarithmic scale.

**Comment by mario-donnarumma** [comment]
This has already been discussed and is currently in the [GoAccess 2.0 Milestone](https://github.com/allinurl/goaccess/milestone/7) (you can refer to #933)

**Comment by alfredneu** [comment]
Great, thank you! And sorry for the duplicate.
