### ISSUE TITLE
Trying to run goaccess

### ISSUE THREAD

**Issue by Ziiweb** [allinurl/goaccess#221]
Hi,

Im getting this after installing goaccess:
```
# goaccess -f /var/log/apache2/access.log -a

GoAccess - version 0.8.5 - Feb 26 2015 17:59:02

Fatal error has occurred
Error occured at: goaccess.c - main - 832
Nothing valid to process.```

**Comment by allinurl** [comment]
Hello, Could you post a couple of lines from your access.log? Thanks.

**Comment by Ziiweb** [comment]
mmm.. access.log is empty.. At this moment Im only getting the access log information at `other_vhosts_access.log`. At this latter file there are lines like these:
```
www.mytravelbanners.com:80 66.249.64.29 - - [18/Mar/2015:21:23:55 +0100] "GET /anuncio/www.falcaodetetie.es.tl HTTP/1.1" 200 1771 "-" "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"
www.mytravelbanners.com:80 66.249.64.29 - - [18/Mar/2015:21:24:28 +0100] "GET /otros.php HTTP/1.1" 500 813 "-" "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"
www.estebancortijo.com:80 187.161.176.188 - - [18/Mar/2015:21:24:37 +0100] "GET /img/carpinteria-aluminio-carpintero-puerta-de-aluminio-comunidad-vecinos-portal-guadalajara.jpg HTTP/1.1" 200 154212 "https://www.google.com.mx/" "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.125 Chrome/36.0.1985.125 BoBrowser/36.0.1985.133 Safari/537.36"
www.mytravelbanners.com:80 66.249.64.29 - - [18/Mar/2015:21:25:02 +0100] "GET /media/cache/resolve/anuncio_cuadrado_gratis_show/rc/ObShcLx5/images/db22ec9fbf6877377a745d7d369a8ccfe2d46001?filters%5Bcrop%5D%5Bstart%5D%5B0%5D=431.51515151515&filters%5Bcrop%5D%5Bstart%5D%5B1%5D=213.33333333333&filters%5Bcrop%5D%5Bsize%5D%5B0%5D=0&filters%5Bcrop%5D%5Bsize%5D%5B1%5D=0 HTTP/1.1" 500 813 "-" "Googlebot-Image/1.0"
```
These are my access.log permissions:
`-rw-r-----  1 root adm         0 mar  4  2014 access.log`
and this is the path:
`/var/log/apache2/access.log`

**Comment by allinurl** [comment]
If your access log is empty, then you will get that error. If you want to parse the `other_vhosts_access.log` file, then you could set the following `log-format` and `date-format` under config file:

    date-format %d/%b/%Y
    log-format %^:%^ %h %^[%d:%^] "%r" %s %b "%R" "%u"

or you could run it as:

   goaccess -f /var/log/apache2/other_vhosts_access.log --date-format='%d/%b/%Y' --log-format='%^:%^ %h %^[%d:%^] "%r" %s %b "%R" "%u"'

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
