### ISSUE TITLE
Planned change to Caddy's access logging

### ISSUE THREAD

**Issue by francislavoie** [allinurl/goaccess#2220]
This is part question, part "notice".

In https://github.com/caddyserver/caddy/pull/4403, we're planning on splitting up `remote_addr` into two fields, `remote_ip` and `remote_port`. The change is still pending, and the field names may change before merging.

I wanted to ask if it's possible/easy to support both `remote_addr` and `remote_ip` at the same time in GoAccess, so that it wouldn't be dependent on the version of Caddy?

**Comment by allinurl** [comment]
Thanks for checking on this. Just so I understand a bit better, there would be a `remote_addr` property and a `remote_port` property instead of having both on the same field? e.g., 

from 

    {"level":"info","ts":1609440464.1045835,"logger":"http.log.access.log0","request":{"remote_addr":"10.0.2.2:59722" ...}

to 

    {"level":"info","ts":1609440464.1045835,"logger":"http.log.access.log0","request":{"remote_addr":"10.0.2.2", "remote_port": 59722 ...}

**Comment by francislavoie** [comment]
Likely `remote_addr` will go away, and be replaced with `remote_ip` and `remote_port`. Still TBD on the field names. The port will be a string (quoted).

**Comment by allinurl** [comment]
I see. There shouldn't be a problem and actually as pointed on [4403](https://github.com/caddyserver/caddy/pull/4403), handling IPv6 without the port on it, would be much easier for goaccess too.

**Comment by francislavoie** [comment]
FYI these changes have been release in https://github.com/caddyserver/caddy/releases/tag/v2.5.0-beta.1

**Comment by allinurl** [comment]
Thanks for sharing this. Do you have an ETA for the production release? I'm thinking it may be best to do the switch on goaccess' format when Caddy reaches the stable release.

**Comment by francislavoie** [comment]
We don't really have a schedule, we usually just cut the release when it "feels good". If we don't get much feedback, we might just make the stable release.

Maybe you could set up a PR in the meantime so you just need to click merge when the time comes? :man_shrugging: 

But yeah, I'll let you know when stable is released. Or if you like, you can subscribe to releases on the Caddy repo in github (Watch button etc).

**Comment by allinurl** [comment]
Got it. I just subscribed to Caddy's releases. Yes, please feel free to let me know in case I miss it. [**PR**](https://github.com/allinurl/goaccess/pull/2293) is ready. Thanks again, Francis!

**Comment by mholt** [comment]
Thanks so much for your ongoing maintenance, @allinurl ! We appreciate it!
