### ISSUE TITLE
Token '-' dosen't match specifier '%h'

### ISSUE THREAD

**Issue by iranbingo** [allinurl/goaccess#2226]
Hi,

My Apache Log File looks like this at the beginning :

```

- - - [01/Mar/2021:00:00:06 +0100] "GET /" 200 2279 "-" "-" 10.127.27.11 
- - - [01/Mar/2021:00:00:06 +0100] "GET / HTTP/1.1" 400 924 "-" "-" 10.127.27.10
- - - [01/Mar/2021:00:00:07 +0100] "GET /" 200 2279 "-" "-" 10.127.27.10
- - - [01/Mar/2021:00:00:11 +0100] "GET /" 200 2279 "-" "-" 10.127.27.11
- - - [01/Mar/2021:00:00:11 +0100] "GET /" 200 2279 "-" "-" 10.127.27.10
- - - [01/Mar/2021:00:00:16 +0100] "GET /" 200 2279 "-" "-" 10.127.27.11
- - - [01/Mar/2021:00:00:17 +0100] "GET /" 200 2279 "-" "-" 10.127.27.10
- - - [01/Mar/2021:00:00:21 +0100] "GET /" 200 2279 "-" "-" 10.127.27.11
- - - [01/Mar/2021:00:00:22 +0100] "GET /" 200 2279 "-" "-" 10.127.27.10
- - - [01/Mar/2021:00:00:24 +0100] "GET / HTTP/1.1" 400 924 "-" "-" 10.127.27.11
- - - [01/Mar/2021:00:00:26 +0100] "GET /" 200 2279 "-" "-" 10.127.27.11
- - - [01/Mar/2021:00:00:27 +0100] "GET /" 200 2279 "-" "-" 10.127.27.10
- - - [01/Mar/2021:00:00:31 +0100] "GET /" 200 2279 "-" "-" 10.127.27.11
- - - [01/Mar/2021:00:00:31 +0100] "GET /" 200 2279 "-" "-" 10.127.27.10 
```

goaccess  shows this error:

Token '-' dosen't match specifier '%h'

I tested all format like Common Combined etc.
Which log format should I use?

Thanks

**Comment by 0bi-w6n-K3nobi** [comment]
Hi @iranbingo 
You need a custom LogFormat...
Maybe you can try this, at `goaccess.conf`:

`date-format %d/%b/%Y`
`time-format %H:%M:%S`
`log-format %^[%d:%t %^] "%m %U" %s %b "%^" "%^" %h`

A unique problem will be parse correct `URL` because you have 2 distinct case -- i.e. with `HTTP/1.1` and without protocol.
Do you have some solution for that, @allinurl ?

**Note:**
You can disable Panel/Chart that `LOGFILE` not have any info.
In this `LOG`, add or uncomment the follow options:

`ignore-panel OS`
`ignore-panel BROWSERS`
`ignore-panel REFERRERS`
`ignore-panel REFERRING_SITES`
`ignore-panel KEYPHRASES`

**Comment by iranbingo** [comment]
Hi,

I used -no-ip-validation with File Format Combined and it worked.

Thanks,

**Comment by 0bi-w6n-K3nobi** [comment]
Hi @iranbingo 

But, It is not be process `LOGFILE` correctly.
See output `HTML` in your browser and will be confirm this.

**Comment by allinurl** [comment]
@0bi-w6n-K3nobi thanks for answering that. You raised a good point, you have two log formats in there. Right now there's no way to parse both of them. I believe we have that in the to-do list. A workaround will be to pre-process the log and either strip that with awk/sed or artificially add it to each line if it doesn't exist. If it's not important to you @iranbingo, I'd personally leave it off.

**Comment by iranbingo** [comment]
Hi @allinurl

Thanks for the answer. Yes, I also wish that my log files are analyzed correctly. How can I determine whether the analysis went correctly or incorrectly?

 since goaccess shows no errors and analyzes logs quickly and easily with --no-ip-validation.

![Bildschirmfoto vom 2021-11-18 09-43-18](https://user-images.githubusercontent.com/68154547/142382404-758d6673-1525-4e4e-a807-497f55ef7f51.png)

**Comment by 0bi-w6n-K3nobi** [comment]
Hi @iranbingo 

Maybe you can look the Chart/Data called `Visitor Hostnames and IPs`.
And you concluded that parse had been wrong, or partially wrong.

Maybe here be off-topic @allinurl , but ... Did you think about a "optional" field, like a regular-expression?
Possibility, it will be resolve several problems include strange date formats.
