### ISSUE TITLE
Bootstrapify the HTML output

### ISSUE THREAD

**Issue by allinurl** [allinurl/goaccess#223]
This should help reduce the amount of custom styling.

**Comment by bdheeman** [comment]
Yeah, agreed.

This will definitely help expose the sidebar menu on hand-held devices, too.

**Comment by d3f3kt** [comment]
Are you still working on this feature? 
Push your progress in an own branch so I can start helping you.

**Comment by allinurl** [comment]
@d3f3kt Thanks, I've been working on this, which will be part of v1.0. There's still work to do, however, a lot of the plumbing is done. The JavaScript side needs some fixes as well. I'm trying to squeeze #216 in this version. 

Let me know if you have any questions/feedback about this branch.

**Comment by d3f3kt** [comment]
@allinurl Very nice that you've pushed your work. 
And btw I really like the new mechanics to handle the HTML output with JavaScript templates. 

So well which part should I take to help you?

**Comment by allinurl** [comment]
@d3f3kt Any help on the JS side would be great! Some of the stuff that still need some work:

- Graph's tooltips need formatting. e.g., bandwidth is displayed in bytes
- Table sort. Ideally have a basic native implementation so we don't have to add a new dependency. One thing to note is that some tables have child rows. e.g., OS panel. Not sure yet how this would play out when sorting a column.
- Expanding child rows and paging through it.

Thanks!

**Comment by allinurl** [comment]
version 1.0 is out! 

Features a complete real-time HTML bootstrap dashboard with a lot of updates to it. https://goaccess.io
