### ISSUE TITLE
Token for '%v' specifier is NULL.

### ISSUE THREAD

**Issue by SoftCreatR** [allinurl/goaccess#2232]
This is my current log format:

```
$remote_addr - $remote_user [$time_local] "$request_method $scheme://$host$request_uri $server_protocol" "$http_referer" "$http_user_agent"
```

Example log entries:

```
127.0.0.1 - - [25/Nov/2021:09:25:49 +0100] "GET https://sub.foo.bar/file.baz HTTP/2.0" "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) 
AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36 Edg/96.0.1054.29"
127.0.0.1 - - [25/Nov/2021:09:26:13 +0100] "GET https://foo.bar/anotherfile.baz HTTP/2.0" "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36 Edg/96.0.1054.29"
```

So I start goaccess via:

```bash
goaccess /var/log/nginx/access.log --log-format='%h - %e [%d:%t %^] "%m %^://%v%U %H" "%R" "%u"' --date-format='%d/%b/%Y' --time-format='%T'
```

But this fails, because `Token for '%v' specifier is NULL.`.

I tried replacing `%v` with `%^` which seems to work, but I'm not sure, if this provides the correct results at the end.

**Comment by allinurl** [comment]
Looks like a COMBINED log format, can you please try:

    goaccess /var/log/nginx/access.log --log-format=COMBINED

Let me know if that works for you.

**Comment by SoftCreatR** [comment]
Nope:

> Token '"-"' doesn't match specifier '%s'

The log format above also differs from nginx' default `combined` format, which is:

```
$remote_addr - $remote_user [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent"
```

**Comment by allinurl** [comment]
My bad. This should do it:

    goaccess /var/log/nginx/access.log --log-format='%h %^[%d:%t %^] "%r" "%R" "%u"' --date-format=%d/%b/%Y --time-format=%T

**Comment by SoftCreatR** [comment]
That looks good to me. Thank you ver much :)

**Comment by ffabreti** [comment]
Excuse me by bringing this up again, but I'm not sure the OP question is answered. He wants the virtualhosts table but the nginx logs only have the virtualhost inside the request. <br>
I am not sure why the answer satisfied the OP, since the title specified the `%v` .

My question, if you should accept to answer :)  ,  is **how can I have the virtualhost table with a log entry like** the below:

```
NGINX: log_format main 
$remote_addr - $remote_user [$time_local] "$request_method $scheme://$host$request_uri $server_protocol"
$status $body_bytes_sent $http_referer $http_user_agent $request_time $request_length

NGINX example:
192.168.24.7 - - [21/Jun/2023:14:13:31 +0000] "GET https://virtualhost01.com.br/the_status HTTP/1.1" 
200 117 "-" "Go-http-client/1.1" 0.000 107
```

my best effort was:
```
cat /srv/nginx/log/access2.log |                                   \
docker run --rm -i -e LANG=$LANG allinurl/goaccess  -o html        \
--date-format='%d/%b/%Y' --time-format='%H:%M:%S'                  \
--log-format='%h - %e [%d:%t %^] "%r" %s %b "%R" "%u" %T %b'       \
- > report3.html
```
but I could no find a way to turn `%r` into something that includes `%v`  for `$scheme://$host$request_uri`

**Comment by ffabreti** [comment]
I have tried:

`--log-format='%h - %e [%d:%t %^] "%m %^://%v/%U" %s %b "%R" "%u" %T %b'`

and it works, **but** tables `NOT FOUND URLS` and `REQUESTED FILES (URLS)` don't show the full URL like before (starting at https://)

**Comment by allinurl** [comment]
@ffabreti Please take a look at the man page [virtual hosts example](https://goaccess.io/man#examples), it should do what you are looking for. Let me know if that helps!
