### ISSUE TITLE
IPv6 address on deb.goaccess.io

### ISSUE THREAD

**Issue by dennisdegreef** [allinurl/goaccess#2243]
Hi,

I am trying use `deb.goaccess.io` on a machine that only has IPv6.

Would it be possible to add AAAA records for this service to your DNS?

Thanks in advanced!

**Comment by allinurl** [comment]
Thanks for bringing this out. Let me take a look at it, I don't think the server has a dual-stack set up.

**Comment by miyurusankalpa** [comment]
any update on this? I ran into the same issue today.

**Comment by allinurl** [comment]
Sorry for the delay on this. Missed it. 

Added the AAAA record. Could you please give it a shot and let me know if that works on your end. Thanks.

**Comment by miyurusankalpa** [comment]
@allinurl thanks.

I can see the DNS record, but it gets timed out. Seems like something is blocking it.

```
#  wget https://deb.goaccess.io -6
--2022-11-22 11:30:05--  https://deb.goaccess.io/
Resolving deb.goaccess.io (deb.goaccess.io)... 2604:a880:1:20::8:9001
Connecting to deb.goaccess.io (deb.goaccess.io)|2604:a880:1:20::8:9001|:443... 
```

**Comment by allinurl** [comment]
Please try again. Let me know if this time works.

**Comment by miyurus-xino** [comment]
works now, thanks.

```
Connecting to deb.goaccess.io (deb.goaccess.io)|2604:a880:400:d0::213c:1|:443... connected.
HTTP request sent, awaiting response... 200 OK
```

**Comment by miyurusankalpa** [comment]
works now, thanks.

```
Connecting to deb.goaccess.io (deb.goaccess.io)|2604:a880:400:d0::213c:1|:443... connected.
HTTP request sent, awaiting response... 200 OK
```

sorry for the double post, used the work account by mistake :D

**Comment by allinurl** [comment]
Glad that worked. Thanks for letting me know.
