### ISSUE TITLE
{BALANCER_WORKER_NAME}e   specifiers 

### ISSUE THREAD

**Issue by zhouzhenhua** [allinurl/goaccess#2249]
LogFormat "%t %a %{SSL_PROTOCOL}x %{SSL_CIPHER}x \"%r\" %>s %b %v \"%{User-Agent}i\" %D %{BALANCER_WORKER_NAME}e" 
===> 
How about specifiers for logging   load balancing back-end IP ports    [{BALANCER_WORKER_NAME}e]

**Comment by allinurl** [comment]
Feel free to reopen it if needed and please post a few lines from your access.log. Thanks
