### ISSUE TITLE
Timeformat in config file broken in version 0.9 on OSX

### ISSUE THREAD

**Issue by overnine** [allinurl/goaccess#225]
Hello, I was attempting to configure a new setup on OSX using the one I have in production. The production system uses v0.8.5.

If you look at the config + output seen here I get a somewhat wired error:
https://gist.github.com/overnine/c39ffdd6185e79f395a2

As you can see the date is correctly formatted according to `man strftime`

**Comment by allinurl** [comment]
Hello, v0.9 introduced the `time_format` variable. Please take a look at it in the [config file](https://github.com/allinurl/goaccess/blob/master/config/goaccess.conf). It also need %t within your `log_format`

**Comment by overnine** [comment]
Seems it works if I add both date-format and time-format, thanks!

This kind of changes should be in the changelog, along with other API changes such as the change in the visitors array where the date key changed to the data key etc.

Thanks for the great work tho.
