### ISSUE TITLE
Add AWS ALB to the predefined logs format

### ISSUE THREAD

**Issue by air3ijai** [allinurl/goaccess#2254]
Hello,

We are considering to parse AWS ALB - [Application Load Balancer](https://aws.amazon.com/elasticloadbalancing/application-load-balancer/) logs. It's log format is described in the documentation - [Access logs for your Application Load Balancer](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-access-logs.html#access-log-entry-syntax).

It was already discussed recently
1. [Log format for Amazon LoadBalancer #793](793)
2. [Amazon Application Load Balancer (alb) access log format #797](797)
3. [Trouble parsing AWS ALB logs #1216](1216)
4. [how do i process aws elb json formatted logs #1832](1832)

But, looks like it is not defined yet in the list of the [predefined logs format](https://goaccess.io/man#options).

We are mostly using ALB instead of the ELB. It can be usefully to have such an option to simplify parsing like we do it now for CloudFront
```
--log-format CLOUDFRONT
--log-format AWSALB
```

An example of the ALB log:
```
h2 2021-12-19T11:22:20.356787Z app/staging/cb87d24460bf11ec 1.1.1.1:62611 172.16.1.1:443 0.006 0.008 0.000 200 200 498 1485 "GET https://service.staging.domain.tld:443/ HTTP/2.0" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36 Edge/12.246" ECDHE-RSA-AES128-GCM-SHA256 TLSv1.2 arn:aws:elasticloadbalancing:us-east-1:123456789012:targetgroup/service-staging/946e110660bf11ec "Root=1-30c170ac-60c011ec86070242ac130002" "service.staging.domain.tld" "arn:aws:acm:us-east-1:123456789012:certificate/8194baa8-60bf-11ec-8607-0242ac130002" 290 2021-12-19T11:22:20.342000Z "forward" "-" "-" "172.16.1.1:443" "200" "-" "-"
```
And `log-format`,  `date-format` and `time-format` we used from [your comment](https://github.com/allinurl/goaccess/issues/1216#issuecomment-416411366):
```bash
zcat *.gz \
| docker run \
    --interactive \
    --rm \
    --env LANG=$LANG \
    allinurl/goaccess \
    --date-spec=hr \
    --real-os \
    --agent-list \
    --output html \
    --log-format='%^ %dT%t.%^ %v %h:%^ %^ %^ %T %^ %s %^ %^ %b "%r" "%u" %^' \
    --date-format=%Y-%m-%d \
    --time-format=%T \
    - > report.html
```
Looks like it works as expected.

Thank you!

**Comment by allinurl** [comment]
Thanks for sharing that. I've added the format as `--log-format=AWSALB` . Also added %k %K to cover the TLS fields. e.g.,

    goaccess access.log --log-format='%^ %dT%t.%^ %v %h:%^ %^ %^ %T %^ %s %^ %^ %b "%r" "%u" %k %K %^' --date-format=%Y-%m-%d --time-format=%T

Closing this. Feel free to reopen it if needed.
