### ISSUE TITLE
Unable to gain HTML reports on GoAccess

### ISSUE THREAD

**Issue by traveltek-jnewall** [allinurl/goaccess#2257]
Hello, i am very new to using GoAccess and have run into a little bit of an issue. I cant seem to get the logs to display on a test server and show the HTML output of the logs. I am getting errors such as below:

```
root:~# goaccess /web/serverlogs/access_log.txt.1 --log-format=CLF -a -o /var/www/html/report.html [PARSING /web/serverlogs/access_log.txt.1] {0} @ {0/s}
==5557== GoAccess - Copyright (C) 2009-2020 by Gerardo Orellana
==5557== https://goaccess.io - <hello@goaccess.io>
==5557== Released under the MIT License.
==5557==
==5557== FILE: /web/serverlogs/access_log.txt.1
==5557== Parsed 10 lines producing the following errors:
==5557==
==5557== IPv4/6 is required.
==5557== IPv4/6 is required.
==5557== IPv4/6 is required.
==5557== IPv4/6 is required.
==5557== IPv4/6 is required.
==5557== IPv4/6 is required.
==5557== IPv4/6 is required.
==5557== IPv4/6 is required.
==5557== IPv4/6 is required.
==5557== IPv4/6 is required.
==5557==
==5557== Format Errors - Verify your log/date/time format
```

As stated above in the error, it seems to be an issue regarding the formats of the logs and the time and date. 

This is the apache config file and showing snippets from the log format, i am wondering if there is something that needs to match between the  apache config and the GoAccess config file.

```
#
# The following directives define some format nicknames for use with
# a CustomLog directive.
#
# These deviate from the Common Log Format definitions in that they use %O
# (the actual bytes sent including headers) instead of %b (the size of the
# requested file), because the latter makes it impossible to detect partial
# requests.
#
# Note that the use of %{X-Forwarded-For}i instead of %h is not recommended.
# Use mod_remoteip instead.
#
LogFormat "%v:%p %h %l %u %t \"%r\" %>s %O \"%{Referer}i\" \"%{User-Agent}i\"" vhost_combined
LogFormat "%h %l %u %t \"%r\" %>s %O \"%{Referer}i\" \"%{User-Agent}i\"" combined
LogFormat "%h %l %u %t \"%r\" %>s %O" common
LogFormat "%{Referer}i -> %U" referer
LogFormat "%{User-agent}i" agent

# Include of directories ignores editors' and dpkg's backup files,
# see README.Debian for details.

# Include generic snippets of statements
IncludeOptional conf-enabled/*.conf

# Include the virtual host configurations:
IncludeOptional sites-enabled/*.conf

# vim: syntax=apache ts=4 sw=4 sts=4 sr noet

```

**Comment by traveltek-tmalek** [comment]
Just to add a little bit more information to what John has mentioned, here's a sample excerpt of our log file that we're trying to parse:

`10.10.210.164 - - [20/Dec/2021:06:54:54 +0000] "GET /extranet/index.pl HTTP/1.1" 200 29009
10.10.210.164 - - [20/Dec/2021:06:54:55 +0000] "GET /extranet/index.pl?fromajax=1&action=getcallbackscnt HTTP/1.1" 200 50
10.10.6.216 - - [20/Dec/2021:06:54:57 +0000] "OPTIONS /healthcheck.txt HTTP/1.0" 200 -
10.10.6.216 - - [20/Dec/2021:06:54:57 +0000] "OPTIONS /healthcheck.txt HTTP/1.0" 200 -
10.10.6.216 - - [20/Dec/2021:06:54:57 +0000] "OPTIONS /healthcheck.txt HTTP/1.0" 200 -
10.10.6.216 - - [20/Dec/2021:06:54:57 +0000] "OPTIONS /healthcheck.txt HTTP/1.0" 200 -
10.10.210.164 - - [20/Dec/2021:06:54:57 +0000] "OPTIONS /healthcheck.txt HTTP/1.0" 200 -
10.10.210.164 - - [20/Dec/2021:06:54:57 +0000] "OPTIONS /healthcheck.txt HTTP/1.0" 200 -
10.10.210.164 - - [20/Dec/2021:06:54:57 +0000] "OPTIONS /healthcheck.txt HTTP/1.0" 200 -
10.10.210.164 - - [20/Dec/2021:06:54:57 +0000] "OPTIONS /healthcheck.txt HTTP/1.0" 200 -
10.10.1.144 - - [20/Dec/2021:06:54:57 +0000] "OPTIONS /healthcheck.txt HTTP/1.0" 200 -
10.10.1.144 - - [20/Dec/2021:06:54:57 +0000] "OPTIONS /healthcheck.txt HTTP/1.0" 200 -
10.10.1.144 - - [20/Dec/2021:06:54:57 +0000] "OPTIONS /healthcheck.txt HTTP/1.0" 200 -
10.10.1.144 - - [20/Dec/2021:06:54:57 +0000] "OPTIONS /healthcheck.txt HTTP/1.0" 200 -
10.10.1.144 - - [20/Dec/2021:06:54:56 +0000] "GET /extranet/index.pl?fromajax=1&action=getcallbackscnt HTTP/1.1" 302 232`

interestingly enough, we can get the display working fine with:

then picking the CLF format.

**Comment by traveltek-tmalek** [comment]
![image](https://user-images.githubusercontent.com/72391257/147276426-afff7539-abf5-439a-8dbd-0c1cecad7a44.png)

Sorry I'll provide a screenshot as it seems a bit more user friendly to view than the copy and paste.

**Comment by allinurl** [comment]
Have you tried using the COMMON log format? e.g.,

    # goaccess access.log --log-format=COMMON -o report.html

Let me know if that works.

**Comment by traveltek-tmalek** [comment]
Thanks that has worked =)

**Comment by allinurl** [comment]
Glad that did the job. Feel free to reopen it if needed.
