### ISSUE TITLE
ignore specific folders in URL

### ISSUE THREAD

**Issue by sderrick** [allinurl/goaccess#2258]
Is there a way to ignore specific folders in a URL request?

If the request is for https://my-domain/admin/...   ignore it

thanks,

Scott

**Comment by allinurl** [comment]
You could do some pre-processing on the log, e.g.,

    grep -v "`cat exclude_url_list_file`" access.log | goaccess - --log-format=COMBINED -o report.html

Let me know if that's what you are looking for.

**Comment by sderrick** [comment]
Actually I was hoping for a PARSE OPTION like ignore-referrer or ignore-status.  Could be ignore-path??

I will think about pre-processing.....

Scott

**Comment by sderrick** [comment]
allinurl,

I set up a pre-processor and it is working fine,

   grep -v  '/monitor\|/admin\|/hg\|/editor\|/php' $file > ga-$file;

thanks,

Scott

**Comment by allinurl** [comment]
Glad that worked. There's parse option right now but I'm expecting this will be part of #117. I'm working on this as we speak. Stay tuned.

Closing this, feel free to reopen it if needed.
