### ISSUE TITLE
What is this log format?

### ISSUE THREAD

**Issue by rdhar-tc** [allinurl/goaccess#2259]
I think it's Common Log Format with Virtual Host, but the prefix is throwing me off. Log is rendered like so:

```log
Dec 16 00:00:00 prod.site.com auth-apache-access: 99.99.99.999 9999 - [16/Dec/2021:00:00:00 +0000] "POST /api/user/ HTTP/1.1" 200 471 "-" "Python-urllib/3.7"
```

How do I take this into account for the custom format?

Thanks for your time.

**Comment by 0bi-w6n-K3nobi** [comment]
Hi @rdhar-tc 

It is seems more NCSA Combined with Virtual Host (VCOMBINED).
Maybe you can try this, at `goaccess.conf`:

`time-format %H:%M:%S`
`date-format %d/%b/%Y`
`log-format %^ %^ %^ %v %^ %h %^[%d:%t %^] "%r" %s %b "%R" "%u"`

or `--time-format="..." ` --date-format="..."`  `--log-format="..."`, at command-line.

**Comment by rdhar-tc** [comment]
Thank you, @0bi-w6n-K3nobi, I really appreciate your response. That works a treat!

As an added (low-fi) workaround, I also had success with `cut -c17- access.log` to trim the fixed length prefix before piping the output as `--log-format=VCOMMON`.

Thanks once again for your time.
