### ISSUE TITLE
~/.goaccessrc not read in default

### ISSUE THREAD

**Issue by sangyye** [allinurl/goaccess#226]
Hey there,
I'm using archlinux with the new goaccess 0.9. I found something strange. I have add a ~/.goaccessrc for my default format but after running `zcat -f logs/access_log* | goaccess -a` I get:

    GoAccess - version 0.9 - Mar 19 2015 14:06:35
    
    Fatal error has occurred
    Error occured at: src/parser.c - parse_log - 1650
    No time format was found on your conf file.

But if I run this `zcat -f logs/access_log* | goaccess -a -p ~/.goaccessrc` It work without a problem. But it should detect the config file automatically, or not?

**Comment by allinurl** [comment]
By default goaccess will attempt to open the user's config file if given, otherwise, it will try to open the global config file `/etc/goaccess.conf`. I assume your global config file does not have the `time_format` variable set. You should also be able to run it as:

    zcat -f logs/access_log* | goaccess -a --no-global-config

**Comment by allinurl** [comment]
Closing this.
