### ISSUE TITLE
prevent negative values in graphs

### ISSUE THREAD

**Issue by infrastation** [allinurl/goaccess#2265]
Thank you for developing goaccess, it is very helpful in my sysadmin work. Let me make a suggestion for a simple improvement. When a metric is zero for a while and then it sharply takes off, the interpolated curve has a bend into the negative space (see the attached image). As far as I understand, all values graphed by goaccess are non-negative, so this is misleading. The simplest potential solution could be to clip the resulting curve using `max(0, value)`, or maybe you could come up with a more sophisticated method.

![Screenshot_2022-01-01_20-28-58](https://user-images.githubusercontent.com/900115/150215482-eedb5baf-918b-404e-bf80-f5515cf2e0d6.png)

**Comment by allinurl** [comment]
Thanks for reporting this. I've updated the interpolation on those area charts. Please feel free to test it out by building from [development](https://github.com/allinurl/goaccess#build-from-github-development) and let me know how it goes. It will be deployed on the next release this month.

**Comment by infrastation** [comment]
Thank you. I have just tried the current master branch, the issue is resolved and the peaks also look more realistic.

**Comment by allinurl** [comment]
Glad that did the job. Thanks again and happy to hear you found the tool useful. Stay tuned for some new features on the upcoming releases!
