### ISSUE TITLE
==4357== Token '+0100]' doesn't match specifier '%h'

### ISSUE THREAD

**Issue by Nemesis77swe** [allinurl/goaccess#2271]
Hi, sorry to bother you, but I'm pretty new, and I'm getting the error `==4357== Token '+0100]' doesn't match specifier '%h'`

I'm using the default apache2 configuration, and the default goaccess configuration, so I can't really understand why it's not working.

apparently does my apache add +0100 into the date.
is there anyway to fix/remove the information?

attaching a line from my log;

`123.456.78.9 - - [06/Feb/2022:10:20:48 +0100] "GET /images/43787452.png HTTP/1.1" 304 352 "https://mysite.org/" "Mozilla/5.0 (X11; Linux x86_64; rv:96.0) Gecko/20100101 Firefox/96.0"`

and this is what's specified in apache2.conf:

```
LogFormat "%v:%p %h %l %u %t \"%r\" %>s %O \"%{Referer}i\" \"%{User-Agent}i\"" vhost_combined
LogFormat "%h %l %u %t \"%r\" %>s %O \"%{Referer}i\" \"%{User-Agent}i\"" combined
LogFormat "%h %l %u %t \"%r\" %>s %O" common
LogFormat "%{Referer}i -> %U" referer
LogFormat "%{User-agent}i" agent

```
and this is added to each virtual host;

    ```
ErrorLog ${APACHE_LOG_DIR}/catchall.error.log
        CustomLog ${APACHE_LOG_DIR}/catchall.access.log combined
```

**Comment by allinurl** [comment]
Please try:

    # goaccess access.log --log-format=COMBINED

**Comment by Nemesis77swe** [comment]
ahh, that solved it, thx a lot!
