### ISSUE TITLE
Request help with custom log format

### ISSUE THREAD

**Issue by drewlearns** [allinurl/goaccess#2272]
I am able to get a --log-format=COMBINED log parse to run but it's output is always the top 5 IPs that are internal IPs (undesired). I've tried the standard log formats but haven't found one that works for our custom log format. Can you assist me with creating a format that will work?

The first IP below is the internal IP and the end of the log is the source IP (the one I need) followed by the cloudfront IP (unnecessary.

Sample:
`10.x.x.x - - [07/Feb/2022:21:59:41 +0000] "GET /media/email/social-pinterest.png HTTP/1.1" 304 0 "-" "Amazon CloudFront" "172.225.xxx.xxx, 64.252.xxx.xxx"`

In /etc/nginx/nginx.conf:

log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

**Comment by 0bi-w6n-K3nobi** [comment]
HI @drewlearns 

The problem with `COMBINED` format that it no will going expand proxied `IP`s,  seen ate last field into your `LOG`.
i.e. the `$http_x_forwarded_for` field at NGinX `CONF`.

For that, maybe you can try this, at `goaccess.conf`:

`time-format %H:%M:%S`
`date-format %d/%b/%Y`
`log-format %^[%d:%t %^] "%r" %s %b "%R" "%u" ~h{," }`

or at command-line:
`goacces --time-format='...' --date-format='...' --log-format='...'  ...`

Note: It is necessary ever have last field **filled**, with proxied `IP`s.

I hope that could helped you.

**Comment by 0bi-w6n-K3nobi** [comment]
Well... What IP do you need process? `172.225.xxx.xxx`? Or the last one, `64.252.xxx.xxx`?

**Comment by drewlearns** [comment]
I need the 172.225.x.x

**Comment by drewlearns** [comment]
$ goaccess /var/log/nginx/access.log*20220127 --time-format='%H:%M:%S' --date-format='%d/%b/%Y' --log-format='%^[%d:%t %^] "%r" %s %b "%R" "%u" ~h{," }'
Parsed 1 linesproducing the following errors:

Token for '%h' specifier is NULL.

Format Errors - Verify your log/date/time format

**Comment by 0bi-w6n-K3nobi** [comment]
humm... I did try with `LOG` line above and worked for me.

What version are you running? Use `goaccess --version` for that.

**Comment by drewlearns** [comment]
$ LANG=en_US.UTF-8 goaccess /var/log/nginx/access.log*20220127 --time-format='%H:%M:%S' --date-format='%d/%b/%Y' --log-format='%^[%d:%t %^] "%r" %s %b "%R" "%u" ~h{," }'
Parsed 1 linesproducing the following errors:

Token for '%h' specifier is NULL.

Format Errors - Verify your log/date/time format
$ goaccess --version
GoAccess - 1.3.
For more details visit: http://goaccess.io
Copyright (C) 2009-2016 by Gerardo Orellana

Build configure arguments:
  --enable-debug
  --enable-utf8
  --enable-geoip=legacy
  --enable-tcb=memhash
  --with-getline
  --with-openssl

**Comment by 0bi-w6n-K3nobi** [comment]
I believe that you need make a update.
The new one do not have this problem. What are your Linux Flavour/Distro?

**Comment by drewlearns** [comment]
I'm using yum installer from aws linux 2

**Comment by drewlearns** [comment]
`goaccess-1.5.5]# goaccess /var/log/nginx/access.log*20220127 --time-format='%H:%M:%S' --date-format='%d/%b/%Y' --log-format='%^[%d:%t %^] "%r" %s %b "%R" "%u" ~h{," }'
Cleaning up resources...
==9737== GoAccess - Copyright (C) 2009-2020 by Gerardo Orellana
==9737== https://goaccess.io - <hello@goaccess.io>
==9737== Released under the MIT License.
==9737==
==9737== FILE: /var/log/nginx/access.log-20220127
==9737== Parsed 10 lines producing the following errors:
==9737==
==9737== Token for '%h' specifier is NULL.
==9737== Token for '%h' specifier is NULL.
==9737== Token for '%h' specifier is NULL.
==9737== Token for '%h' specifier is NULL.
==9737== Token for '%h' specifier is NULL.
==9737== Token for '%h' specifier is NULL.
==9737== Token for '%h' specifier is NULL.
==9737== Token for '%h' specifier is NULL.
==9737== Token for '%h' specifier is NULL.
==9737== Token for '%h' specifier is NULL.
==9737==
==9737== Format Errors - Verify your log/date/time format`

So maybe I need to provide more examples of the output?


`127.x.x.x - - [08/Feb/2022:15:07:35 +0000] "POST /thing_thing_1/document/_search HTTP/1.1" 200 335 "-" "elasticsearch-php/6.7.1 (Linux 4.x.x.x.amzn2.x86_64, PHP 7.2.24)" "-"
127.x.x.x - - [08/Feb/2022:15:07:35 +0000] "POST /thing_thing_1/document/_search HTTP/1.1" 200 335 "-" "elasticsearch-php/6.7.1 (Linux 4.x.x.x.484.amzn2.x86_64, PHP 7.2.24)" "-"
10.x.x.x - - [08/Feb/2022:15:07:35 +0000] "GET /shop-all/weather-instruments/thermometers-and-hygrometers/programmable_alerts-wifi_for_weather_underground-dark_theme-backlight_dimming_option-battery_backup-compatible_with_lightning_detector-displays_daily_rain_total-displays_moon_phase-compatible_with_weather_underground_when_paired_with_thing_access.html HTTP/1.1" 200 38678 "-" "Mozilla/5.0 (Linux; Android 7.0;) AppleWebKit/537.36 (KHTML, like Gecko) Mobile Safari/537.36 (compatible; PetalBot;+https://webmaster.petalsearch.com/site/petalbot)" "114.x.x.x, 64.x.x.x"
10.x.x.x - - [08/Feb/2022:15:07:36 +0000] "GET /shop-all/weather-instruments/weather-sensors-and-parts/sensors/indoor-temperature-sensor-and-humidity-gauge.html HTTP/1.1" 200 38618 "https://www.thing.com/shop-all/weather-instruments/weather-sensors-and-parts/accessories/wireless-signal-extender-for-thing-sensors.html" "Mozilla/5.0 (Windows NT 6.1; rv:96.0) Gecko/20100101 Firefox/96.0" "47.x.x.x, 64.x.x.x"
10.x.x.x - - [08/Feb/2022:15:07:36 +0000] "GET /static/version1637195340/frontend/Mgs/thing/en_US/fonts/fontawesome-webfont.woff2?v=4.7.0 HTTP/1.1" 200 77160 "https://www.thing.com/shop-all/weather-instruments/weather-sensors-and-parts/sensors/indoor-temperature-sensor-and-humidity-gauge.html" "Mozilla/5.0 (Windows NT 6.1; rv:96.0) Gecko/20100101 Firefox/96.0" "47.x.x.x, 64.x.x.x"
10.x.x.x - - [08/Feb/2022:15:07:36 +0000] "GET /static/version1637195340/frontend/Mgs/thing/en_US/fonts/Pe-icon-7-stroke.woff HTTP/1.1" 200 58556 "https://www.thing.com/shop-all/weather-instruments/weather-sensors-and-parts/sensors/indoor-temperature-sensor-and-humidity-gauge.html" "Mozilla/5.0 (Windows NT 6.1; rv:96.0) Gecko/20100101 Firefox/96.0" "47.x.x.x, 64.x.x.x"
10.x.x.x - - [08/Feb/2022:15:07:36 +0000] "GET /static/version1637195340/_cache/merged/eae680730717479ce11027d7b55a073b.min.css HTTP/1.1" 200 197825 "https://www.thing.com/shop-all/weather-instruments/weather-sensors-and-parts/sensors/indoor-temperature-sensor-and-humidity-gauge.html" "Mozilla/5.0 (Windows NT 6.1; rv:96.0) Gecko/20100101 Firefox/96.0" "47.x.x.x, 64.x.x.x"
10.x.x.x - - [08/Feb/2022:15:07:36 +0000] "GET /media/catalog/thing/cache/19881b0b96ef533dd9941f9c99ec36bf/0/6/06044-800x800.jpg HTTP/1.1" 304 0 "-" "Amazon CloudFront" "47.x.x.x, 64.x.x.x"
10.x.x.x - - [08/Feb/2022:15:07:36 +0000] "GET /media/catalog/thing/cache/19881b0b96ef533dd9941f9c99ec36bf/0/6/06044-angle-800x800.jpg HTTP/1.1" 304 0 "-" "Amazon CloudFront" "47.x.x.x, 64.x.x.x"
10.x.x.x - - [08/Feb/2022:15:07:36 +0000] "GET /media/catalog/thing/cache/52aef2ab34f91f508fe37440e98e3131/0/6/06044-alt1-800x800.jpg HTTP/1.1" 304 0 "-" "Amazon CloudFront" "47.x.x.x, 64.x.x.x"
10.x.x.x - - [08/Feb/2022:15:07:36 +0000] "GET /media/catalog/thing/cache/52aef2ab34f91f508fe37440e98e3131/0/6/06044-alt3-800x800.jpg HTTP/1.1" 304 0 "-" "Amazon CloudFront" "47.x.x.x, 64.x.x.x"
10.x.x.x - - [08/Feb/2022:15:07:36 +0000] "GET /static/version1637195340/frontend/Mgs/thing/en_US/MGS_Mpanel/images/blank.png HTTP/1.1" 200 95 "https://www.thing.com/shop-all/weather-instruments/weather-sensors-and-parts/sensors/indoor-temperature-sensor-and-humidity-gauge.html" "Mozilla/5.0 (Windows NT 6.1; rv:96.0) Gecko/20100101 Firefox/96.0" "47.x.x.x, 64.x.x.x"
10.x.x.x - - [08/Feb/2022:15:07:36 +0000] "GET /media/catalog/thing/cache/19881b0b96ef533dd9941f9c99ec36bf/0/6/06044-alt2-800x800.jpg HTTP/1.1" 304 0 "-" "Amazon CloudFront" "47.x.x.x, 64.x.x.x"
10.x.x.x - - [08/Feb/2022:15:07:36 +0000] "GET /media/catalog/thing/cache/52aef2ab34f91f508fe37440e98e3131/0/6/06044-back-800x800.jpg HTTP/1.1" 304 0 "-" "Amazon CloudFront" "47.x.x.x, 64.x.x.x"
10.x.x.x - - [08/Feb/2022:15:07:36 +0000] "GET /media/catalog/thing/cache/52aef2ab34f91f508fe37440e98e3131/0/6/06044-alt2-800x800.jpg HTTP/1.1" 304 0 "-" "Amazon CloudFront" "47.x.x.x, 64.x.x.x"
10.x.x.x - - [08/Feb/2022:15:07:37 +0000] "GET /index.html HTTP/1.1" 301 169 "-" "ELB-HealthChecker/2.0" "-"
10.x.x.x - - [08/Feb/2022:15:07:37 +0000] "GET /static/version1637195340/frontend/Mgs/thing/en_US/fonts/Pe-icon-7-stroke.woff?d7yf1v HTTP/1.1" 200 58556 "https://www.thing.com/static/version1637195340/_cache/merged/eae680730717479ce11027d7b55a073b.min.css" "Mozilla/5.0 (Windows NT 6.1; rv:96.0) Gecko/20100101 Firefox/96.0" "47.38.95.22, 64.x.x.x"
10.x.x.x - - [08/Feb/2022:15:07:38 +0000] "GET /pub/media/catalog/thing/0/9/09155-phone-800x800.jpg HTTP/1.1" 200 73538 "https://www.thing.com/learn/my-thing" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.2 Safari/605.1.15" "76.x.x.x, 64.x.x.x"
10.x.x.x - - [08/Feb/2022:15:07:38 +0000] "GET /pub/media/catalog/thing/0/2/02082m-phone-hi-res_2021_1.jpg HTTP/1.1" 200 199086 "https://www.thing.com/learn/my-thing" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.2 Safari/605.1.15" "76.x.x.x, 64.x.x.x"
10.x.x.x - - [08/Feb/2022:15:07:38 +0000] "GET /pub/media/catalog/thing/0/2/02077-02041-800x800.jpg HTTP/1.1" 200 144307 "https://www.thing.com/learn/my-thing" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.2 Safari/605.1.15" "76.x.x.x, 64.x.x.x"`

**Comment by drewlearns** [comment]
It appears some of them don't provide a host IP because they are 301 redirects internally.

**Comment by drewlearns** [comment]
Is it possible to grep those out within the command?

**Comment by allinurl** [comment]
@0bi-w6n-K3nobi format works fine for me too:

![2022-02-08 10-43](https://user-images.githubusercontent.com/5005367/153034292-cc90e6c4-a81e-4777-8ebe-30ba53b19051.gif)

You could try ignoring those lines using  `--num-test=0` or you could pre-process the log with awk and add a bogus ip that matches the same format.

**Comment by drewlearns** [comment]
That did the trick! Thank you so much!

**Comment by 0bi-w6n-K3nobi** [comment]
Hi @drewlearns 

Just trick for you:
Use the option `--invalid-requests` for check if incorrect lines are that you hoped.

More details see the man page [here](https://goaccess.io/man#options), at `FILE OPTIONS` section.
