### ISSUE TITLE
cowaxess on Wndows - real time html adds entire log to stats everytime the log is updated

### ISSUE THREAD

**Issue by demifiend9** [allinurl/goaccess#2274]
For example, if I had 100 requests in my log file, the html shows 100 correctly the first time, but when 1 request is added to log html shows 201 total requests.

Goaccess config:
```
real-time-html true
addr 127.0.0.1
port 15564
ws-url stats.example.com:443
log-format CADDY
log-file D:\caddy\logs\example.com.log.json
output D:\caddy\sites\stats.example.com\index.html
```

I'm using cowaxess, the cygwin package of goaccess. I've tried --restore --persist options but the behavior was still the same.

**Comment by allinurl** [comment]
Have you tried running it without --restore --persist? Also please make sure you don't have anything under the /tmp folder.

**Comment by allinurl** [comment]
Hard to tell to be honest. Are you able to test this on a Linux machine?

**Comment by demifiend9** [comment]
I can't right now, but as a workaround I've been using a .bat file to pipe the log into goaccess and that's been working well.

`tail.exe -q -F -n +0 d:/caddy/logs/example.com.log.json | goaccess.exe --config-file=goaccess.conf -`

**Comment by allinurl** [comment]
If you have a chance to run it directly via cygwin, it would be great, just to see if we can isolate the issue to cowaxess or something else. Here's the [**list of packages**](https://goaccess.io/faq#installation) needed on cygwin. Please let me know.

**Comment by demifiend9** [comment]
> If you have a chance to run it directly via cygwin, it would be great, just to see if we can isolate the issue to cowaxess or something else. Here's the [**list of packages**](https://goaccess.io/faq#installation) needed on cygwin. Please let me know.

I just did that, installed cygwin with those packages and compiled goaccess. Still the same bug.

**Comment by TheTitanrain** [comment]
Same issue. But Goaccess adds all logs every second.
![image](https://user-images.githubusercontent.com/1952721/174944880-9e566d55-3156-41df-b43f-4bd708133a7f.png)

**Comment by TheTitanrain** [comment]
https://github.com/allinurl/goaccess/blob/aa45260cfb8a776770f695da0cb560ff4079f1e4/src/goaccess.c#L804

**Comment by TheTitanrain** [comment]
I commented out this line and all logs are not added every second.
https://github.com/allinurl/goaccess/blob/aa45260cfb8a776770f695da0cb560ff4079f1e4/src/goaccess.c#L804

**Comment by allinurl** [comment]
I wonder if the inode for some reason changes on Windows and thus this is being reset to 0. Let me get me hands on a Windows machine today and I can test this out.

**Comment by allinurl** [comment]
Thanks again for sharing those findings. I pushed a commit that should address this issue. Please feel free to build from [**development**](https://github.com/allinurl/goaccess#build-from-github-development) and let me know if that solves the issue on your end. Otherwise, it will be deployed in the upcoming release.

**Comment by TheTitanrain** [comment]
Thanks! The issue is is solved.
