### ISSUE TITLE
Need ability to break down VISITORS data by minute

### ISSUE THREAD

**Issue by ggedde** [allinurl/goaccess#2277]
First off, Thanks so much for such an awesome and amazing application!

Currently I can get the visitors data break down by day or by hour, but would really like to be able to get it by minute as well. At the very least I am looking for every 5 minutes, but I know that many people might need it by minute.  

It would be awesome to just add an option to `--date-spec` for `min` then just append the minute to the data like how the hour is added when you do `--date-spec=hr`.  

So in the end with `--date-spec=min` you would see `202202150259`, etc.

I know that this could cause an issue on the front end GUI as there would be a lot of data to show, but I only need this for the CLI as I just need the JSON data for this. So maybe as a first step this can be added only for the cli and if more requests come from it then you can add it to the GUI later on.

Thanks

**Comment by allinurl** [comment]
This sounds totally doable, like you said, probably it can be added first to the JSON/CSV outputs.

**Comment by ggedde** [comment]
@allinurl Awesome, Thanks

**Comment by allinurl** [comment]
This has been implemented. Please try building from [development](https://github.com/allinurl/goaccess#build-from-github-development) and let me know if it works fine on your end. i.e., `--date-spec=min`. I plan to push it out in the upcoming release. Thanks

**Comment by ggedde** [comment]
Thanks @allinurl, I am not sure if I have time to test from development, but if I do I will give it a try. Thanks
