### ISSUE TITLE
Log format for Lancache log

### ISSUE THREAD

**Issue by Joly0** [allinurl/goaccess#2280]
Hey, i am trying to figure out the log format for lancache (basically a nginx caching dns server)

Here are some examples from the access log file:
`[wsus] 192.168.178.111 / - - - [26/Sep/2021:22:24:12 +0200] "GET /d/msdownload/update/software/defu/2021/09/am_engine_6e3f9e436b6a01de0f94768c358118017fae86a9.exe HTTP/1.1" 206 1048576 "-" "Microsoft-Delivery-Optimization/10.0" "MISS" "au.download.windowsupdate.com" "bytes=4194304-5242879"`

`[steam] 192.168.178.111 / - - - [26/Sep/2021:22:26:44 +0200] "GET /ipv6check HTTP/1.1" 502 182 "-" "Valve/Steam HTTP Client 1.0" "MISS" "ipv6check-http.steamcontent.com" "-"`

`[steam] 192.168.178.111 / - - - [26/Sep/2021:22:26:48 +0200] "GET /appinfo/480/sha/394df648147c92962d8339895e7dbe1cf11ea30f.txt.gz HTTP/1.1" 200 1256 "-" "Valve/Steam HTTP Client 1.0" "MISS" "clientconfig.akamai.steamstatic.com" "-"`

`[steam] 192.168.178.111 / - - - [26/Sep/2021:22:26:48 +0200] "GET /appinfo/570/sha/a5088931c6d3a9e06144fc463dbad334c5667b1f.txt.gz HTTP/1.1" 200 50478 "-" "Valve/Steam HTTP Client 1.0" "MISS" "clientconfig.akamai.steamstatic.com" "-"`

`[steam] 192.168.178.111 / - - - [26/Sep/2021:22:26:48 +0200] "GET /appinfo/92/sha/05b3b2b559e000b02e3f0ce6fc6eb444c5ce2d4f.txt.gz HTTP/1.1" 200 747 "-" "Valve/Steam HTTP Client 1.0" "MISS" "clientconfig.akamai.steamstatic.com" "-"`

`[epicgames] 192.168.178.95 / - - - [15/Feb/2022:19:27:13 +0100] "GET /Builds/Org/o-uvtztrtfjdn3xgrwyhbuwwb5z42mbv/63ed46b9c4964f83baa782aac4d77f7b/default/ChunksV3/28/972745AE7012E686_581531284821C9D0CA61F6B9691BBBE9.chunk HTTP/1.1" 200 994634 "-" "EpicGamesLauncher/13.1.5-18673502+++Portal+Release-Live Windows/10.0.22000.1.768.64bit" "HIT" "fastly-download.epicgames.com" "-"`

**Comment by allinurl** [comment]
Please try this, it should work:

    goaccess access.log --log-format='%^ %h %^[%d:%t %^] "%r" %s %b "%R" "%u" "%C" %^' --date-format=%d/%b/%Y --time-format=%T
