### ISSUE TITLE
Some versions of Firefox browser not detected/reported

### ISSUE THREAD

**Issue by bdheeman** [allinurl/goaccess#229]
Some of the Firefox browser version are not being detected/reported properly. I think, we need to apply some heuristics.

See: http://www.mediafire.com/view/l1d2ujaf793arof/Screenshot-20150327T202215.png

**Comment by allinurl** [comment]
I'll look into this. Thanks for pointing this out.

**Comment by bdheeman** [comment]
You're welcome ☺

**Comment by allinurl** [comment]
This has been fixed and will be pushed out in the upcoming version. Thanks.
