### ISSUE TITLE
[Question] Why does there need to be separate databases for --date-spec?

### ISSUE THREAD

**Issue by ggedde** [allinurl/goaccess#2291]
I assumed that I could use the same database when accessing --date-spec=hr when I already created a database with --date-spec=date. I assumed that all the data for --date-spec=hr would be there in the database from --date-spec=date. However, when I try that it does not work and only shows the results from --date-spec=date instead of hourly. I am using output of json.

It does work if I create 2 separate databases.

Is this by design?
I have another feature request for --date-spec=min. I am also curious about that.
I need to generate a report for all three (date, hr, min) and I am trying to find the most efficient way possible.

Thanks

**Comment by allinurl** [comment]
Good question. When using `--date-spec=<hr|min>`, that data is parsed and stored into the db as specified by that option. In your case, you probably want to create three reports, however, it depends exactly on what you are looking for. If you are mostly interested on the visitors panel metrics, then you could generate it using `--date-spec=min` and then you can post-process the JSON file and strip the date as needed.

I'm working on #117 as we speak, I'm thinking this would give you more flexibility as you will be able to filter by date ranges and correlate all that data.

**Comment by ggedde** [comment]
Thanks @allinurl, creating three different reports and databases is not that big of an issue. So I'll probably keep moving forward with that.

As far as doing the post process I don't think that'll work for my reports. I am only focused on the unique visitors. If hour 1 has four unique visitors and hour 2 has 3 unique visitors, there's no real way to know for sure how many unique visitors there were for hours 1 and 2 as it could be anything between 4 and 7. This is also the same issue between hours and days and that's why I can't just process off of the hours report to get the days numbers. Let me know if that makes sense or if there is something that I am missing.

Thanks

**Comment by allinurl** [comment]
Makes sense. You will need to have goaccess process the log at the granular level.
