### ISSUE TITLE
Token '13' doesn't match specifier '%d'

### ISSUE THREAD

**Issue by azmidotmy** [allinurl/goaccess#2292]
Im trying to reconstruct goaccess log format and have also looked on the other issues but it does not work on my case.
I have also worked on the correct locale.

my current locale LANG
```
$ locale | grep LANG
LANG=en_US.UTF-8
```

This is the my access.log record;
```
$ head -1 access.log
- [13/Mar/2022:03:30:11 -0500] "GET /status HTTP/1.1" 302 226 "-" "ELB-HealthChecker/2.0" % staging.example.com:443 (10.0.3.171) 10.0.3.171 10.0.4.41 "-" "-" "-" "-" "-" 454 5119 262 0
```

And this is the error that I got;
```
$ goaccess access.log --log-format='%u [%d/%m/%Y:%t] \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\" %% %v:%p (%V) %A %a \"%{X-Forwarded-For}i\" \"%{X-Forwarded-Proto}i\" \"%{X-Forwarded-Port}i\" \"%{X-AUSERNAME}o\" \"%{X-ASESSIONID}o\" %I %O %D %T' --date-format=%d/%m/%Y --time-format=%T
Parsed 1 linesproducing the following errors:


Token '13' doesn't match specifier '%d'
```

Thanks.

**Comment by allinurl** [comment]
Please take a look at the man pages [**custom fields**](https://goaccess.io/man#custom-log) for more info, though this should work:

    goaccess access.log --log-format='%e [%d:%t %^] "%r" %s %b "%R" "%u" %^ %v:%^ (%h)  %^"%^" "%^" "%^" "%^" "%^" %^ %^ %D %^' --date-format=%d/%b/%Y --time-format=%T

**Comment by azmidotmy** [comment]
thank you @allinurl for the assistance and the man pages, thats really helpful for me to dig more into the custom fields options.

I have another blockage seems my production servers are showing hostname instead IP Address for the (%h) field, what is the SPECIFIERS that I can use as I cannot use %v anymore because "Token already set for '%v' specifier." will pop-out.

example of access.log from production log as below;

```
- [13/Mar/2022:03:17:16 -0500] "GET / HTTP/1.1" 200 9651 "-" "LogicMonitor InternalService" % prod.example.com:443 (prod.example.com) 10.0.1.143 10.0.2.122 "216.110.00.00, 10.0.2.122" "https" "443" "anonymous" "-" 596 13174 56109 0
```

**Comment by allinurl** [comment]
@azmidotmy assuming `596` is the time served in microseconds (otherwise, feel free to change as needed), then:

    goaccess access.log --log-format='%^ [%d:%t %^] "%r" %s %b "%R" "%u" %^ %^ (%v) %^ %^ ~h{", } %^ %^ %^ "%e" %D %^' --date-format=%d/%b/%Y --time-format=%T

**Comment by azmidotmy** [comment]
Thank you very much @allinurl !

Its working now, looking at the differences, noticed %^ specifier there to replace %v:%^ .

Will playing around with these specifiers with other custom log format so I can get better understanding.

**Comment by allinurl** [comment]
Glad that did it. Closing this, feel free to reopen it if needed.

**Comment by azmidotmy** [comment]
@allinurl 

I played around with the specifiers.

```
- [13/Mar/2022:03:17:16 -0500] "GET / HTTP/1.1" 200 9651 "-" "LogicMonitor InternalService" % prod.example.com:443 (prod.example.com) 10.0.1.143 10.0.2.122 "216.110.1.2, 10.0.2.122" "https" "443" "anonymous" "-" 596 13174 56109 0
```

Same example output as above, I want to pull "anonymous" informations out and placed it in the REMOTE USER (HTTP AUTHENTICATION) panel / %e specifiers but some user id did not shows up.

This is the specifiers that I used.
```
--log-format='%^ [%d:%t %^] "%r" %s %b "%R" “%^” %^ %^ (%v) %^ %^ ~h{", } "%^" "%^" "%e" "%^" %D %^' --date-format=%d/%b/%Y --time-format=%T
```

I attached some screenshot like below, in the blue circle;
<img width="1117" alt="Screenshot 2022-03-28 at 10 53 06" src="https://user-images.githubusercontent.com/9209451/160318767-fe7139c9-fb39-41e0-8f38-7999ab8d5998.png">

**Comment by allinurl** [comment]
@azmidotmy could you please attach a file that contains more lines directly from your access log? Thanks

**Comment by azmidotmy** [comment]
sorry @allinurl , your provided options are workable so I will stick with that.
