### ISSUE TITLE
go-access log format for custom logs

### ISSUE THREAD

**Issue by klaucher** [allinurl/goaccess#2298]
I am getting following error while using go-access with custom log format:
=3820== Token '(Linux;' doesn't match specifier '%h'

Sample log format is as under:
2022-03-29	23:39:57	2103:3072:3a23:d36b:d493:5091:be82:a1df	GET	/www.xxx.co.in/favicon.ico	200	32638	0	"-"	"Mozilla/5.0 (Mobile; LYF/F250D/LYF-F220D-002-06-29-170342;Android; rv:48.0) Gecko/48.0 Firefox/48.0 KAIOS/2.5"	"-"	"-"	"www.xxx.co.in"

I have tried many combinations but failed.
Please help in configuring log-format in /etc/goaccess/goaccess.conf

**Comment by allinurl** [comment]
I'm not sure what that 0 is after the bytes, I assumed it was the time taken to serve the request in seconds with milliseconds resolution, otherwise, please replace the %T specifier with %^. Or take a look at the man page for more [specifiers.](https://goaccess.io/man#custom-log). This should work:

    goaccess access.log --log-format='%d %t %h %m %U %s %b %T "%R" "%u" %^ %^ "%v"' --date-format=%Y-%m-%d --time-format=%T --http-protocol=no

**Comment by klaucher** [comment]
I am getting following error using the above mentioned command.
2022-02-01	06:07:00	2403:4643:4d9b:ec16::6d8b:1905	GET	/www.xyz.co.in/image/icon/download.jpg	200	3968	1	"https://www.xyz.co.in/"	"Mozilla/5.0' 
doesn't match specifier '%d'
I don't know why %d is causing error. First field is date field only. Is the format of date field different?

**Comment by klaucher** [comment]
The fields used in the log format are as under:
Fields: date time cs-ip cs-method cs-uri sc-status sc-bytes time-taken cs(Referer) cs(User-Agent) cs(Cookie) x-wafinfo cs-host

**Comment by allinurl** [comment]
Can you please attach a file with more lines directly from your access log so I can make sure the format will work properly? e.g., `tail -10 access.log > lines.log`

**Comment by klaucher** [comment]
[lines.log](https://github.com/allinurl/goaccess/files/8503634/lines.log)
Please find attached the required file.

**Comment by allinurl** [comment]
This should work, please note that your log is tabbed delimited. Also assumes time taken is in milliseconds.

    goaccess access.log --log-format='%d\t%t\t%h\t%m\t%U\t%s\t%b\t%L\t"%R"\t"%u"\t"%^"\t"%^"\t"%v"' --date-format=%Y-%m-%d --time-format=%T

**Comment by klaucher** [comment]
Thank you so much for the patience and prompt reply.
It worked.

**Comment by allinurl** [comment]
Glad that did the job. Feel free to reopen it if needed.
