### ISSUE TITLE
go-access log format for custom logs [HELP!]

### ISSUE THREAD

**Issue by duoduo-CCIE** [allinurl/goaccess#2299]
Thank you so much for your dedication!
But after checking the manual for a whole day, I still can't learn the secrets in the 'log format'. I am very grateful for help.

1、I still don't get these important metrics: average response time, total response time, and top response time.

![image](https://user-images.githubusercontent.com/74661395/162634872-0ebd0f81-3963-4da5-9f18-d81a3b0cdb5a.png)

![image](https://user-images.githubusercontent.com/74661395/162635333-9e6dff04-0628-4290-b303-ee632aef98ea.png)

Here is my configuration:

nginx: (help with a conversion)
` log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"'
                          '"$connection" "$upstream_addr" "$upstream_status"'
                          '"$upstream_http_content_type"  "$upstream_response_time" "$request_time"'
                          '$http_host:$server_port';`

goaccess:

`time-format %H:%M:%S`
`date-format %d/%b/%Y`
`log-format  %h %e [%d:%t %^] "%r" %s %b "%R" "%u" ~h{," } %^ %^ %^ %T %^`
`log-format COMBINED`

Here is the output log:

> 172.70.143.30 - user007 [11/Apr/2022:01:32:56 +0700] "GET /api/v1.0/server/config HTTP/1.1" 200 1128 "https://XXXXX.tk/test" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.75 Safari/537.36" "XXX.XXX.XXX.XXX""192" "127.0.0.1:8080" "200""application/config"  "0.000" "1.584""XXXXX.tk" : 443

2、X-Forwarded-For field not parsing ?

![image](https://user-images.githubusercontent.com/74661395/162635607-f2c3f8c9-ec15-4872-ba2b-a656ee57c133.png)

**Comment by allinurl** [comment]
Sorry for the delay on my response, I missed this post. Could you please post a few more lines from your access log? It's not very clear the 192 in here  `"XXX.XXX.XXX.XXX""192" "127.0.0.1:8080" "200"`.  Thanks

**Comment by a-v-ebrahimi** [comment]
Hi
I have the same issue with Apache, is it resolved?
