### ISSUE TITLE
Display VirtualHosts for logs 

### ISSUE THREAD

**Issue by simark** [allinurl/goaccess#23]
When I look at the top request files for a log with VirtualHosts, it is not very useful to know about a path if I don't know its associated VirtualHost. Is it possible to display a column with this information? I am using version 0.6 from the Debian repo.

Thanks!

**Comment by allinurl** [comment]
Added the ability to parse virtual hosts and a new panel to display metrics per virtual host. This was shipped in v0.9.5.

As @ottok pointed out, it displays data on a separate panel, e.g.,

     9 - Virtual Hosts                                                         Total: 230/230

     Hits    Vis.      %   Bandwidth Avg. T.S. Cum. T.S. Max. T.S. Data
     ------ ----- ------ ----------- --------- --------- --------- ----
     144909 10684 58.47%    1.99 GiB 325.35 ms  13.10 hr   4.36 mn www.example.com
     46849   9784 18.90%  738.80 MiB 307.65 ms   4.00 hr  56.18  s example.com
     19816   1455  8.00%  326.16 MiB 304.54 ms   1.68 hr  56.67  s www.domain.com
     11464     87  4.63%   54.70 MiB 364.63 ms   1.16 hr  40.06  s mail.googlex.net
     6129      54  2.47%  415.13 KiB  45.00 us 280.85 ms   9.41 ms box.yahoox.com
     4713     520  1.90%   55.66 MiB 208.47 ms  16.38 mn   8.16  s www.example.com.au
     3670     146  1.48%   13.24 MiB   1.08 ms   3.98  s  53.27 ms www2.example.com

#117 should cover the filtering by vhost, and other fields.
