### ISSUE TITLE
Link to website and name in the title

### ISSUE THREAD

**Issue by bdheeman** [allinurl/goaccess#230]
I think, it would be much better if we can replace the "Dashboard" string with something like "Statistics for http://example.com/" and the title like "Example: Server Statistics", the later with help clean names when bookmarking the same for quick access to the reports.

Currently, I do it with help of shell, sed scripting; I need to create html reports via crond.

See: http://www.mediafire.com/view/bv2ljnhr2288jda/Screenshot-20150327T202233.png

**Comment by allinurl** [comment]
I can add the text somewhere at the top. However, `http://example.com/` would need to be the hostname  of the machine being used to analyze the logs or perhaps an option to specify it in the config file? There could be multiple sites per log (virtualhosts). Any Thoughts?

**Comment by bdheeman** [comment]
Can't say anything about others, but for the virtual hosts me and most of hosting providers use separate log files per virtual host. So, better we have an option to pass a hostname via command line a default one in the global configuration file.

Hence, a URL and capitalized nickname can computed from hostname.

**Comment by allinurl** [comment]
This has been implemented. A custom title/header can be set passing:

    --html-report-title='My Awesome Server Web Stats'

Or through the config file.

It will be pushed out in the upcoming version, otherwise feel free to build from [master](http://goaccess.io/download#build).

**Comment by breck7** [comment]
Thank you @bdheeman and @allinurl for solving my 2022 problem in 2015!!! (https://github.com/breck7/pldb/commit/3c4ba099f4f45bd2a4b515c8df8f2610900243de)

**Comment by allinurl** [comment]
@breck7 No, thank you very much for sponsoring GoAccess!
