### ISSUE TITLE
Token '30/Apr/2022' doesn't match specifier '%d'

### ISSUE THREAD

**Issue by PapaV** [allinurl/goaccess#2311]
Please, help. What is my mistake? I tried many options, the result is unchanged

goaccess --date-format="%d/%b/%Y" --time-format="%H:%M:%S" --log-format='%h - - [%d:%t %^] "%r" %s %b "%R" "%u"' nginx-access.log

RESULT:
Token '30/Apr/2022' doesn't match specifier '%d'

LOG:
```

1.2.3.4 - - [30/Apr/2022:10:14:52 +0500] "GET https://subdomain.domain.com/some/params/ HTTP/1.1" 200 15829 "-" "Mozilla/5.0 (compatible; YandexBot/3.0; +http://yandex.com/bots)"
4.3.2.1 - - [30/Apr/2022:10:14:52 +0500] "GET https://domain.com/some/params/?logout= HTTP/1.1" 200 15962 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36" 
```

**Comment by allinurl** [comment]
Seems like your locale is not set to English dates. Please try:

    LANG="en_US.UTF-8" bash -c 'goaccess access.log --log-format=COMBINED'

**Comment by PapaV** [comment]
I have already found this advice. Unfortunately, it didn't help.

**Comment by PapaV** [comment]
Setting LC_TIME to en_US.UTF-8 didn't help either

**Comment by allinurl** [comment]
What's the output of: `locale -a`? also, is your machine running a linux distro with English as the default lang? Thanks

**Comment by PapaV** [comment]
My machine running on FreeBSD with Poland (pl_PL.UTF-8) language as default. As far as I understand, Goaccess uses strftime(). Here is the output of this function:
``
$python 3.8 -c 'import time; print (time.strftime("%d/%b/%Y", time.localtime()))'
03/May/2022
```
locale -a:

```
$ locale -a
C
C.UTF-8
POSIX
af_ZA.ISO8859-1
af_ZA.ISO8859-15
af_ZA.UTF-8
am_ET.UTF-8
ar_AE.UTF-8
ar_EG.UTF-8
ar_JO.UTF-8
ar_MA.UTF-8
ar_QA.UTF-8
ar_SA.UTF-8
be_BY.CP1131
be_BY.CP1251
be_BY.ISO8859-5
be_BY.UTF-8
bg_BG.CP1251
bg_BG.UTF-8
ca_AD.ISO8859-1
ca_AD.ISO8859-15
ca_AD.UTF-8
ca_ES.ISO8859-1
ca_ES.ISO8859-15
ca_ES.UTF-8
ca_FR.ISO8859-1
ca_FR.ISO8859-15
ca_FR.UTF-8
ca_IT.ISO8859-1
ca_IT.ISO8859-15
ca_IT.UTF-8
cs_CZ.ISO8859-2
cs_CZ.UTF-8
da_DK.ISO8859-1
da_DK.ISO8859-15
da_DK.UTF-8
de_AT.ISO8859-1
de_AT.ISO8859-15
de_AT.UTF-8
de_CH.ISO8859-1
de_CH.ISO8859-15
de_CH.UTF-8
de_DE.ISO8859-1
de_DE.ISO8859-15
de_DE.UTF-8
el_GR.ISO8859-7
el_GR.UTF-8
en_AU.ISO8859-1
en_AU.ISO8859-15
en_AU.US-ASCII
en_AU.UTF-8
en_CA.ISO8859-1
en_CA.ISO8859-15
en_CA.US-ASCII
en_CA.UTF-8
en_GB.ISO8859-1
en_GB.ISO8859-15
en_GB.US-ASCII
en_GB.UTF-8
en_HK.ISO8859-1
en_HK.UTF-8
en_IE.ISO8859-1
en_IE.ISO8859-15
en_IE.UTF-8
en_NZ.ISO8859-1
en_NZ.ISO8859-15
en_NZ.US-ASCII
en_NZ.UTF-8
en_PH.UTF-8
en_SG.ISO8859-1
en_SG.UTF-8
en_US.ISO8859-1
en_US.ISO8859-15
en_US.US-ASCII
en_US.UTF-8
en_ZA.ISO8859-1
en_ZA.ISO8859-15
en_ZA.US-ASCII
en_ZA.UTF-8
es_AR.ISO8859-1
es_AR.UTF-8
es_CR.UTF-8
es_ES.ISO8859-1
es_ES.ISO8859-15
es_ES.UTF-8
es_MX.ISO8859-1
es_MX.UTF-8
et_EE.ISO8859-1
et_EE.ISO8859-15
et_EE.UTF-8
eu_ES.ISO8859-1
eu_ES.ISO8859-15
eu_ES.UTF-8
fi_FI.ISO8859-1
fi_FI.ISO8859-15
fi_FI.UTF-8
fr_BE.ISO8859-1
fr_BE.ISO8859-15
fr_BE.UTF-8
fr_CA.ISO8859-1
fr_CA.ISO8859-15
fr_CA.UTF-8
fr_CH.ISO8859-1
fr_CH.ISO8859-15
fr_CH.UTF-8
fr_FR.ISO8859-1
fr_FR.ISO8859-15
fr_FR.UTF-8
ga_IE.UTF-8
he_IL.UTF-8
hi_IN.ISCII-DEV
hi_IN.UTF-8
hr_HR.ISO8859-2
hr_HR.UTF-8
hu_HU.ISO8859-2
hu_HU.UTF-8
hy_AM.ARMSCII-8
hy_AM.UTF-8
is_IS.ISO8859-1
is_IS.ISO8859-15
is_IS.UTF-8
it_CH.ISO8859-1
it_CH.ISO8859-15
it_CH.UTF-8
it_IT.ISO8859-1
it_IT.ISO8859-15
it_IT.UTF-8
ja_JP.SJIS
ja_JP.UTF-8
ja_JP.eucJP
kk_KZ.UTF-8
ko_KR.CP949
ko_KR.UTF-8
ko_KR.eucKR
lt_LT.ISO8859-13
lt_LT.UTF-8
lv_LV.ISO8859-13
lv_LV.UTF-8
mn_MN.UTF-8
nb_NO.ISO8859-1
nb_NO.ISO8859-15
nb_NO.UTF-8
nl_BE.ISO8859-1
nl_BE.ISO8859-15
nl_BE.UTF-8
nl_NL.ISO8859-1
nl_NL.ISO8859-15
nl_NL.UTF-8
nn_NO.ISO8859-1
nn_NO.ISO8859-15
nn_NO.UTF-8
pl_PL.ISO8859-2
pl_PL.UTF-8
pt_BR.ISO8859-1
pt_BR.UTF-8
pt_PT.ISO8859-1
pt_PT.ISO8859-15
pt_PT.UTF-8
ro_RO.ISO8859-2
ro_RO.UTF-8
ru_RU.CP1251
ru_RU.CP866
ru_RU.ISO8859-5
ru_RU.KOI8-R
ru_RU.UTF-8
se_FI.UTF-8
se_NO.UTF-8
sk_SK.ISO8859-2
sk_SK.UTF-8
sl_SI.ISO8859-2
sl_SI.UTF-8
sr_RS.ISO8859-2
sr_RS.ISO8859-5
sr_RS.UTF-8
sr_RS.UTF-8@latin
sv_FI.ISO8859-1
sv_FI.ISO8859-15
sv_FI.UTF-8
sv_SE.ISO8859-1
sv_SE.ISO8859-15
sv_SE.UTF-8
tr_TR.ISO8859-9
tr_TR.UTF-8
uk_UA.CP1251
uk_UA.ISO8859-5
uk_UA.KOI8-U
uk_UA.UTF-8
zh_CN.GB18030
zh_CN.GB2312
zh_CN.GBK
zh_CN.UTF-8
zh_CN.eucCN
zh_HK.UTF-8
zh_TW.Big5
zh_TW.UTF-8
```

**Comment by allinurl** [comment]
Interesting, I just fired up a freebsd machine and it works on my end with those sample lines you posted. Can I ask, what's the output of:

    LANG="en_US.UTF-8" bash -c 'date +"%d/%b/%Y %T"'

Here's what I get on my end:

![2022-05-05 17-53](https://user-images.githubusercontent.com/5005367/167038863-9e3b60c5-cd80-45c9-b1c1-7a2bc5d0f35e.gif)

**Comment by PapaV** [comment]
Problem solved. Decision is replacing LANG to LC_ALL (FreeBSD 13.0-RELEASE-p4)
$LC_ALL="en_US.UTF-8" bash -c 'goaccess nginx-access.log --log-format=COMBINED'

**Comment by allinurl** [comment]
Glad that solved the issue and thanks for posting those findings.

Closing this. Feel free to reopen it if needed.
