### ISSUE TITLE
Token for '%d' specifier is NULL. Custom log

### ISSUE THREAD

**Issue by zanette52** [allinurl/goaccess#2313]
Hey guys,

I'm just starting I hope you understand my question.

My IBM Cloud server logs are failing to get in a valid format into goaccess.

I'm getting the error:

**Token for '%d' specifier is NULL.**

My settings:
**time-format %H:%M:%S
date-format %Y-%m-%d**

Here's an example log:

2022-03-03 15:36:21.135 143.0.86.30 GET https://example-url-dest.com 200 1957057 61.77 https://example-home.com/ Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36 - -y 236001 0 541

**Comment by allinurl** [comment]
Could you please describe each field? e.g., `1957057` `61.77` `236001` `0` `541` Thanks

**Comment by zanette52** [comment]
#Fields: date time cs-ip cs-method cs-uri sc-status sc-bytes time-taken cs(Referer) cs(User-Agent) cs(Cookie) x-Custom x-LogGroup x-disid x-extstatus x-headersize

**Comment by allinurl** [comment]
This should work, let me know if it does:

    goaccess access.log --log-format='%d %t.%^ %h %m %U %s %b %T %R %u %^' --date-format=%Y-%m-%d --time-format=%T -o report.html

**Comment by zanette52** [comment]
Parsed 10 lines producing the following errors:
Token ' ' doesn't match specifier '%d'

**Comment by allinurl** [comment]
For the sample line you posted above, that should work. Can you attach a sample log from your access log? Thanks e.g., 

    tail -10 access.log > sample.log

**Comment by zanette52** [comment]
[sample.log](https://github.com/allinurl/goaccess/files/8788874/sample.log)

Here

**Comment by allinurl** [comment]
This should do it (tabbed delimited), let me know if that works:

    goaccess sample.log --log-format='%d\t%t.%^\t%h\t%m\t%U\t%s\t%b\t%T\t%R\t%u\t%^' --date-format=%Y-%m-%d --time-format=%T -o report.html
