### ISSUE TITLE
Difference unique visitors in HTML and in Console

### ISSUE THREAD

**Issue by fgrue** [allinurl/goaccess#2323]
I'm having a slight issue with the unique visitors, as the count in the console and in the report.html file is hugely different.

In the first picture (console) you can see that the count is 38
![image](https://user-images.githubusercontent.com/105801020/169064349-dbfe1e9e-fe73-442c-b7d2-b35f74671cd2.png)

While in the html file it is at 1365
![image](https://user-images.githubusercontent.com/105801020/169064833-c6756c9f-a2ef-4054-ab84-537177ffb8fa.png)

Does anyone know why there is such a huge discrepancy?

**Comment by allinurl** [comment]
Good question. I see the T.X amount is 0 on the TUI. Are you sure you are using the right format on both sides? also, was the log exactly the same in both runs? (diff  # of total requests is different).

**Comment by fgrue** [comment]
It absolutely was the format problem! If they are the same, the output is identical again. Thanks for your time
