### ISSUE TITLE
Please help with my Apache Log format (including request times)

### ISSUE THREAD

**Issue by amilhub** [allinurl/goaccess#2326]
Hello,

My Apache LogFormat was the following:

    LogFormat "%{X-Forwarded-For}i %l %u %t \"%r\"  %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" varnish
    LogFormat "%{X-Forwarded-For}i %h %l %u %t \"%r\"  %s %b \"%{Referer}i\" \"%{User-agent}i\"" combined-forwarded
    CustomLog /var/log/httpd/access.log varnish
    ErrorLog /var/log/httpd/error.log 

With this, I am able to generate report with goaccess without problems, but I am not fetching the response times so the report is being generated without the AVG. TS / CUM. T.S / MAX. T.S that i need.

I have tried adding the '%D' param in the LogFormat like this:

    LogFormat "%{X-Forwarded-For}i %l %u %t %D \"%r\"  %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" varnish
    LogFormat "%{X-Forwarded-For}i %h %l %u %t %D \"%r\"  %s %b \"%{Referer}i\" \"%{User-agent}i\"" combined-forwarded
    CustomLog /var/log/httpd/access.log varnish
    ErrorLog /var/log/httpd/error.log 

In the /var/log/httpd/access.log I can see this info is now being received, for example:

10.10.49.139 - - [23/May/2022:10:15:17 +0200] **18598** "GET /xxxxx/animations.min.css HTTP/1.1"  200 18468 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:100.0) Gecko/20100101 Firefox/100.0"
10.10.49.139 - - [23/May/2022:10:15:17 +0200] **22010** "GET /xxxxx/appart-custom.js HTTP/1.1"  200 432 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:100.0) Gecko/20100101 Firefox/100.0"
10.10.49.139 - - [23/May/2022:10:15:17 +0200] **13073** "GET /xxxxxdist/scripts/main.js HTTP/1.1"  200 55574 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:100.0) Gecko/20100101 Firefox/100.0"

I am not able to generate a valid Goaccess report that includes the (AVG. TS / CUM. T.S / MAX. T.S) - i understand now this values is being fetched with the '%D'.

Please anybody can help me with the log-format parsing for my case? It will be high appreciated.

Thanks in advance for help.

**Comment by amilhub** [comment]
Hello,

==24275== Token '' doesn't match specifier '%s'
==24275== Errores de Formato - Verifique su formato de log/fecha/hora

With your log-format suggestion gives me this error (about %s status code), is not being parsed correctly (format errors on log/date/time).

Thank you very much again.

**Comment by allinurl** [comment]
Glad to hear it worked. Closing this. Feel free to reopen it if needed.

**Comment by a-v-ebrahimi** [comment]
Great it worked, thanks
