### ISSUE TITLE
Log format Cyberpanel with LiteSpeed

### ISSUE THREAD

**Issue by jonascampos1** [allinurl/goaccess#2329]
I can't find the --log-format for my server

```
"207.46.13.89 - - [28/May/2022:14:26:05 +0000] "GET /movil/ HTTP/1.1" 302 444 "-" "Mozilla/5.0 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)""
"207.46.13.146 - - [28/May/2022:14:26:05 +0000] "GET /ver.noticia.new.php?id=69914 HTTP/1.1" 302 444 "-" "Mozilla/5.0 (iPhone; CPU iPhone OS 7_0 like Mac OS X) AppleWebKit/537.51.1 (KHTML, like Gecko) Version/7.0 Mobile/11A465 Safari/9537.53 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)""
"185.191.171.15 - - [28/May/2022:14:26:05 +0000] "GET /ver.noticia.new.php?id=123446 HTTP/1.1" 200 9049 "-" "Mozilla/5.0 (compatible; SemrushBot/7~bl; +http://www.semrush.com/bot.html)""
"207.46.13.89 - - [28/May/2022:14:26:08 +0000] "GET /movil/ HTTP/2" 200 9283 "-" "Mozilla/5.0 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)""
"207.46.13.146 - - [28/May/2022:14:26:09 +0000] "GET /ver.noticia.new.php?id=69914 HTTP/2" 302 0 "-" "Mozilla/5.0 (iPhone; CPU iPhone OS 7_0 like Mac OS X) AppleWebKit/537.51.1 (KHTML, like Gecko) Version/7.0 Mobile/11A465 Safari/9537.53 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)""
"66.249.70.95 - - [28/May/2022:14:26:10 +0000] "GET /movil/ver.noticia.php?id=112263 HTTP/2" 200 2491 "-" "Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.64 Mobile Safari/537.36 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)""
"207.46.13.12 - - [28/May/2022:14:26:10 +0000] "GET /ver.noticia.new.php?id=93141 HTTP/2" 200 7981 "-" "Mozilla/5.0 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)""
"207.46.13.146 - - [28/May/2022:14:26:10 +0000] "GET /movil/ver.noticia.php?id=69914 HTTP/2" 200 2491 "-" "Mozilla/5.0 (iPhone; CPU iPhone OS 7_0 like Mac OS X) AppleWebKit/537.51.1 (KHTML, like Gecko) Version/7.0 Mobile/11A465 Safari/9537.53 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)""
```

**Comment by jonascampos1** [comment]
"207.46.13.89 - - [28/May/2022:14:26:05 +0000] "GET /movil/ HTTP/1.1" 302 444 "-" "Mozilla/5.0 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)""
"207.46.13.146 - - [28/May/2022:14:26:05 +0000] "GET /ver.noticia.new.php?id=69914 HTTP/1.1" 302 444 "-" "Mozilla/5.0 (iPhone; CPU iPhone OS 7_0 like Mac OS X) AppleWebKit/537.51.1 (KHTML, like Gecko) Version/7.0 Mobile/11A465 Safari/9537.53 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)""
"185.191.171.15 - - [28/May/2022:14:26:05 +0000] "GET /ver.noticia.new.php?id=123446 HTTP/1.1" 200 9049 "-" "Mozilla/5.0 (compatible; SemrushBot/7~bl; +http://www.semrush.com/bot.html)""
"207.46.13.89 - - [28/May/2022:14:26:08 +0000] "GET /movil/ HTTP/2" 200 9283 "-" "Mozilla/5.0 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)""
"207.46.13.146 - - [28/May/2022:14:26:09 +0000] "GET /ver.noticia.new.php?id=69914 HTTP/2" 302 0 "-" "Mozilla/5.0 (iPhone; CPU iPhone OS 7_0 like Mac OS X) AppleWebKit/537.51.1 (KHTML, like Gecko) Version/7.0 Mobile/11A465 Safari/9537.53 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)""
"66.249.70.95 - - [28/May/2022:14:26:10 +0000] "GET /movil/ver.noticia.php?id=112263 HTTP/2" 200 2491 "-" "Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.64 Mobile Safari/537.36 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)""
"207.46.13.12 - - [28/May/2022:14:26:10 +0000] "GET /ver.noticia.new.php?id=93141 HTTP/2" 200 7981 "-" "Mozilla/5.0 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)""
"207.46.13.146 - - [28/May/2022:14:26:10 +0000] "GET /movil/ver.noticia.php?id=69914 HTTP/2" 200 2491 "-" "Mozilla/5.0 (iPhone; CPU iPhone OS 7_0 like Mac OS X) AppleWebKit/537.51.1 (KHTML, like Gecko) Version/7.0 Mobile/11A465 Safari/9537.53 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)""

**Comment by jonascampos1** [comment]
Founded thanks:
'\"%h %l %u %^[%d:%t %^] "\%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"\"'

**Comment by allinurl** [comment]
Please take a look at the [**man page**](https://goaccess.io/man#custom-log) log config specifiers. This should work, though:

    goaccess access.log --log-format='"%h %^[%d:%t %^] "%r" %s %b "%R" "%u""' --date-format=%d/%b/%Y --time-format=%T

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
