### ISSUE TITLE
Segfault when expanding Visitor Hostnames and IPs 

### ISSUE THREAD

**Issue by lachierussell** [allinurl/goaccess#2330]
Hi, I've encounter a segfault issue when expanding the Visitor Hostnames and IPs panel.

```sh
==29663== GoAccess 1.5.7 crashed by Sig 11
==29663==
==29663== VALUES AT CRASH POINT
==29663==
==29663== FILE: /var/log/nginx/archive/sts.mulss.com.access.log
==29663== Line number: 71908
==29663== Invalid data: 0
==29663== Piping: 0
==29663==
==29663==
==29663== Please report it by opening an issue on GitHub:
==29663== https://github.com/allinurl/goaccess/issues
```
```sh
ec2-user@freebsd:~ $ goaccess --version
GoAccess - 1.5.7.
For more details visit: https://goaccess.io/
Copyright (C) 2009-2022 by Gerardo Orellana

Build configure arguments:
  --enable-geoip=mmdb
  --with-getline
  --with-openssl
```

I dug through the logs and found that it crashes on this line (despite the crash log reporting the last line in the file).
`183.192.82.19 - - [10/Apr/2022:12:29:37 +0000] "GET /?fbclid=IwAR2xdmCpdP1Hi7hAodoQMJB5fGX8fQ-4ux_-0HZEwyMfoFyTmh1U8GWkBrQ HTTP/1.1" 200 1256 "https://l.facebook.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.2 Safari/605.1.15"`

My best guess is it's just the line length that's causing the issue. It occurs with a few other similarly long lines. I compiled with --with-getline since this supposedly allows goaccess to allocate beyond 4096 chars. Do you have any ideas?

edit: it's only 308 bytes (I should have picked up on this earlier) so I'm not sure why the allocation would cause issues.

**Comment by allinurl** [comment]
Thanks for reporting this. Could you please share the log/date/time-format that you are using? Also, please feel free to attach your config file.

**Comment by lachierussell** [comment]
Thanks for the quick response!

I'm using the default format options. I'm not using a config file. These formats work most of the time, there's just a few lines that trip it up, like the one above.
```
[x] NCSA Combined Log Format
Log format – %h %^[%d:%t %^] "%r" %s %b "%R" "%u"
Date format – %d/%b/%Y
Time format – %H:%M:%S
```

This line works fine:
`180.150.37.133 - - [30/May/2022:07:00:08 +0000] "GET /Admin/admin4.mp4 HTTP/1.1" 206 1540647 "https://sts.mulss.com/Admin/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1 Safari/605.1.15"`

**Comment by allinurl** [comment]
It's not breaking on my end with those two lines. Are you able to share with me either those 71908 lines from your log or part of it?

Thanks

**Comment by lachierussell** [comment]
Here's 50 lines from the logs that includes the line above (there are several that cause it to crash though).

[error-50.txt](https://github.com/allinurl/goaccess/files/8801055/error-50.txt)

I tried running goaccess from homebrew (goaccess--1.5.7.monterey.bottle.tar.gz) just then too which also failed with the same error.

**Comment by allinurl** [comment]
For some reason it's not breaking on me. Here's what I get:

![2022-05-30 21-13](https://user-images.githubusercontent.com/5005367/171079401-47e99b42-5064-4992-b64d-45b7d26225d1.gif)

Are you running this on a mac? can I ask you to please run it through gdb? e.g.,

```
$ curl tar.goaccess.io/goaccess-1.5.7.tar.gz | tar xvz
$ cd goaccess-1.5.7/
$ ./configure --enable-debug --enable-utf8
$ make
$ gdb --args ./goaccess error-50.txt --log-format='%h %^[%d:%t %^] "%r" %s %b "%R" "%u"' --date-format=%d/%b/%Y --time-format=%T
(gdb) r <enter>
... attempt to crash
(gdb) bt full <enter>
```
Thanks

**Comment by lachierussell** [comment]
Gdb wasn't working for me out of the box. I ran it through Xcode instead (lldb).

Here's the stack trace
```
#1	0x000000010005b205 in xstrdup at src/xmalloc.c:57
#2	0x000000010000c876 in set_dash_metrics at src/gdashboard.c:1363
#3	0x000000010000a3b4 in add_sub_item_to_dash at src/gdashboard.c:1401
#4	0x000000010000a2e1 in load_data_to_dash at src/gdashboard.c:1437
#5	0x00000001000231f7 in allocate_data_by_module at src/goaccess.c:361
#6	0x0000000100021fd5 in allocate_data at src/goaccess.c:376
#7	0x000000010002358e in expand_current_module at src/goaccess.c:523
#8	0x000000010002272a in get_keys at src/goaccess.c:1150
#9	0x000000010001fcb8 in curses_output at src/goaccess.c:1280
#10	0x000000010001f389 in main at src/goaccess.c:1641
```

it crashed here:
``` c
char *
xstrdup (const char *s) {
  char *ptr;
  size_t len;

  len = strlen (s) + 1;  //  <<<  it's probably worth changing strlen to strnlen but I dont think that would have fixed it here
  ptr = xmalloc (len);

  strncpy (ptr, s, len);
  return (ptr);
}
```

variables at crash:
``` c 
s	const char *	NULL	0x0000000000000000
ptr	char *	"0.0   B"	0x00000001011221f0
len	size_t	4295307323
```

xstrdup was called by gdashboard->set_dash_metrics
``` c
1363   idata->metrics->data = xstrdup (data);
```

the variables here:
``` c
dash	GDash **	0x7ff7bfeff3d0	0x00007ff7bfeff3d0
metrics	GMetrics *	0x101404820	0x0000000101404820
    id	uint8_t	'\x02'
    data	char *	""	0x0000000101404880
    method	char *	NULL	0x0000000000000000
    protocol	char *	NULL	0x0000000000000000
    hits_perc	float	0
    visitors_perc	float	0
    bw_perc	float	0
    hits	uint64_t	0
    visitors	uint64_t	0
    bw	GMetrics::(unnamed union)	
    avgts	GMetrics::(unnamed union)	
    cumts	GMetrics::(unnamed union)	
    maxts	GMetrics::(unnamed union)	
module	GModule	HOSTS
totals	GPercTotals	
is_subitem	int	1
idata	GDashData *	0x101122350	0x0000000101122350
meta	GDashMeta *	0x1088083f8	0x00000001088083f8
data	char *	NULL	0x0000000000000000
idx	int *	0x108808458	0x0000000108808458
```

and one call higher in add_sub_item_to_dash
``` c
dash	GDash **	0x7ff7bfeff3d0	0x00007ff7bfeff3d0
item	GHolderItem	
module	GModule	HOSTS
totals	GPercTotals	
i	int *	0x7ff7bfeff3b8	0x00007ff7bfeff3b8
sub_list	GSubList *	0x101404890	0x0000000101404890
iter	GSubItem *	0x1014048b0	0x00000001014048b0
module	GModule	HOSTS
metrics	GMetrics *	0x101404820	0x0000000101404820
id	uint8_t	'\x02'
data	char *	""	0x0000000101404880
*data	char	'\0' 
method	char *	NULL	0x0000000000000000
protocol	char *	NULL	0x0000000000000000
hits_perc	float	0
visitors_perc	float	0
bw_perc	float	0
hits	uint64_t	0
visitors	uint64_t	0
bw	GMetrics::(unnamed union)	
avgts	GMetrics::(unnamed union)	
cumts	GMetrics::(unnamed union)	
maxts	GMetrics::(unnamed union)	
prev	GSubItem_ *	NULL	0x0000000000000000
next	GSubItem_ *	NULL	0x0000000000000000
```

**Comment by lachierussell** [comment]
I haven't tested on linux yet (which I can try later). So far macOS and FreeBSD both seem to crash. They might be sharing libraries but I don't think they're that similar these days.

I'm quite busy for the next fortnight but I'm happy to dig into the codebase after that to see what I can find :)

**Comment by allinurl** [comment]
Thanks a lot for sharing those findings. I was able to reproduce this on a FreeBSD machine. For some reason, `getnameinfo(3)` on mac/BSDs will return `\0` while in Linux does return a `.` (actual value) for some IPs. e.g.,  `host 183.192.82.19`.

I pushed a fix, please feel free to build from [**development**](https://github.com/allinurl/goaccess#build-from-github-development) and let me know if that solves the issue on your end. I'll be pushing this out on the upcoming release.

Thanks again!

**Comment by lachierussell** [comment]
Tested on macOS (12.4) and FreeBSD (13.0), both worked great!

There's nothing quite like discovering that POSIX libraries don't match across OSs.. good catch, and thanks for the quick fix!
