### ISSUE TITLE
log format for redirection logs from nginx proxy manager

### ISSUE THREAD

**Issue by xavier-hernandez** [allinurl/goaccess#2331]
Is this the correct format for the redirection logs from nginx proxy manager?

```
[22/May/2022:00:35:23 -0400] 307 - GET https w.example.ccom "/" [Client 1.1.1.1] [Length 168] [Gzip -] "HetrixTools Uptime Monitoring Bot. https://hetrix.tools/uptime-monitoring-bot.html" "-"
```
```
log_format [%d:%t %^] %^ - %m %^ %v "%U" [Client %h] [Length %b] [Gzip %^] "%u" "%R"
```

**Comment by allinurl** [comment]
Very close, only missing the status code. This should do it:

    goaccess access.log --log-format='[%d:%t %^] %s - %m %^ %v "%U" [Client %h] [Length %b] [Gzip %^] "%u" "%R"' --date-format=%d/%b/%Y --time-format=%T

**Comment by xavier-hernandez** [comment]
Appreciate the quick response!
