### ISSUE TITLE
UNIQUE VISITORS PER DAY - INCLUDING SPIDERS panel not work

### ISSUE THREAD

**Issue by JnuSimba** [allinurl/goaccess#2337]
use `goaccess  access.log -o report.html --real-time-html`, the UNIQUE VISITORS PER DAY - INCLUDING SPIDERS panel not work，but others panels works
![image](https://user-images.githubusercontent.com/5785346/173339733-b8b0e2de-bba9-499f-ac95-5c11eac9814b.png)

goaccess v1.6

**Comment by JnuSimba** [comment]
access log sample :
```119.147.10.239 - - [14/Jun/2022:19:20:28 +0800] "POST /index.php/public/commoncgi/update_time_seed?g_ty=ajax HTTP/1.1" 404 548 "http://test.1.qq.com/" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36"```
log format：
```
The following log format should do it (NCSA Combined Log Format):
%h %^[%d:%^] "%r" %s %b "%R" "%u"

the following date format
%d/%b/%Y

and time format
 %T
```
and some console error：
<img width="740" alt="image" src="https://user-images.githubusercontent.com/5785346/173567887-653da3fb-e94e-4745-a1a1-a5c353982da0.png">

also，what are the recommend access log format set and  goaccess log format set， in order to present  panel data  as much as possible ? thanks

**Comment by allinurl** [comment]
That's strange.. that log format it's working fine for me. Do you get an empty chart even if you reload the page/report? also, does it update the panel after some time or it never updates? 

Also, with your browser's devtools opened, are you able to reload the report (ctrl+shift+r) and look at the network tab, open the websocket request, and can you please post one of the websocket frames?

Thanks

**Comment by allinurl** [comment]
I was looking at this but can't reproduce this on my end. Are you able to consistently reproduce this issue? and would you be able to share with me that log file? Thanks!

**Comment by JnuSimba** [comment]
sorry，the log file has sensitive info. i will close this issue, thanks
