### ISSUE TITLE
Custom JSON nginx log format

### ISSUE THREAD

**Issue by zjcscut** [allinurl/goaccess#2338]
My Nginx log simple as this：

{"@timestamp":"2022-06-15T12:47:10+08:00","clientRealIp":"100.169.0.123","remote_addr":"100.169.0.123","remote_user":"-","time_local":"-","request":"POST /x/y/z HTTP/1.1","status":"200","body_bytes_sent":"53","http_referer":"-","http_host":"x.com","http_user_agent":"Jakarta Commons-HttpClient/3.1","http_x_forwarded_for":"-","upstream_addr":"172.0.0.1:8081","upstream_status":"200","upstream_response_time":"0.010","request_time":"0.011","server_name":"xxx","request_method":"POST","uri":"yyy","scheme":"https","server_port":"443","request_length":"755"}

How can I config the 'log_format' option？Thx

**Comment by allinurl** [comment]
Please take a look at the [**man page**](https://goaccess.io/man#custom-log) for more details. Anyways, this should do it:

    goaccess access.log --log-format='{"@timestamp":"%dT%t+%^","clientRealIp":"%h","remote_user":"%e","request":"%r","status":"%s","http_referer":"%R","http_host":"%v","http_user_agent":"%u","request_time":"%T","request_length":"%b"}' --date-format=%Y-%m-%d --time-format=%T

**Comment by allinurl** [comment]
Closing this, feel free to reopen it if needed.
