### ISSUE TITLE
Real Time HTML report not updating

### ISSUE THREAD

**Issue by ricetim** [allinurl/goaccess#2341]
The real time html report generated by goaccess is not updating as the nginx log file updates.

 I am running: 

`goaccess /var/log/nginx/access.log -o /var/www/goaccess/report.html --real-time-html`

report.html will be written as soon as the command is run, but will not update as access.log is updated. I can confirm that writes are being made to access.log, but report.html remains unchanged until the above command is run again.

Any idea what's going on here? Is there a log or verbose output that I can enable for goaccess to help troubleshoot this issue?

Thank you.

**Comment by ricetim** [comment]
@allinurl same thing. Running the below command will update the report.html file with whatever the current access.log contents are, but then not perform any realtime updates as access.log is changed

`goaccess /var/log/nginx/access.log -o /var/www/goaccess/report.html --real-time-html`

**Comment by ricetim** [comment]
Oh hey, I think I figured it out, perhaps. It looks like report.html only updates if you try to access it from a browser. I was just updating access.log and watching the report.html file and seeing if any changes were made.

Somewhere along the way, it looks like it started to work. The  report is updating as I refresh it in the browser. Fantastic news!

**Comment by allinurl** [comment]
Great to hear it worked. Yes, the actual generated html report won't change, it updates the data via a WebSocket connection and through Javascript the report is visually updated.

**Comment by lzplzp886** [comment]
> Great to hear it worked. Yes, the actual generated html report won't change, it updates the data via a WebSocket connection and through Javascript the report is visually updated.

Hi I wanna ask, what is the right behavior I should expect below, as for now if I wanna see the latest data I must manually refresh the browser to get it: 
1. While I keep the browser running, while the page dynamically updates itself per second(right top counter keeps ticking) or when there's new log data comes to the file.
2. Or I must manually refresh the browser to get the latest report data?

**Comment by allinurl** [comment]
@lzplzp886 the report is updated via a web socket server. This means that whenever new data is appended to the access log, the report will automatically update itself. You don't need to manually refresh the browser (Ctrl+R) for this to happen. The report won't update every second unless new data is appended to the log. So, if there's no new data coming in, the report won't refresh every second. It only updates when there's something new to show.
