### ISSUE TITLE
1.6.1 src/util.c needs _DARWIN_C_SOURCE 200809L for macOS

### ISSUE THREAD

**Issue by Schamschula** [allinurl/goaccess#2345]
When updating the MacPorts Portfile to version 1.6.1 I ran into a build issue in src/util.c

```
src/util.c:520:10: error: implicit declaration of function 'timegm' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
  return timegm (&tmp) - src->tm_gmtoff;
         ^
src/util.c:520:10: note: did you mean 'time'?
/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk/usr/include/time.h:118:8: note: 'time' declared here
time_t time(time_t *);
       ^
1 error generated.

```

I worked around this with the following patch

```
--- src/util.c.orig	2022-06-30 09:17:04.000000000 -0500
+++ src/util.c	2022-07-01 06:00:26.000000000 -0500
@@ -35,6 +35,8 @@
 #define _XOPEN_SOURCE     700
 #define _GNU_SOURCE
 
+#define _DARWIN_C_SOURCE 200809L
+
 #include <arpa/inet.h>
 #include <ctype.h>
 #include <errno.h>
```

however, this probably should be take care of in `configure.ac`

**Comment by allinurl** [comment]
Thanks a lot for reporting this. Looks like _XOPEN_SOURCE was the culprit. It should [**build fine**](https://github.com/allinurl/goaccess/runs/7157980114?check_suite_focus=true) now. Please feel free to build from [**development**](https://github.com/allinurl/goaccess#build-from-github-development) and let me  know if that solves the issue on your end.

**Comment by Schamschula** [comment]
The diff works fine for me! I test built the 1.6.1 source, substituting your patch for mine.

**Comment by allinurl** [comment]
Thanks for letting me know and glad to hear that! I'll be pushing a minor release for this soon.
