### ISSUE TITLE
how to see users isp

### ISSUE THREAD

**Issue by epictz06** [allinurl/goaccess#2347]
Hello , and thank you for developing such a great tool.
is it possible to see how many % of users use what ISP?
like 30% verizon
or 10% o2
something like that.
i couldent find it in google so i asked it here.
best regards.

**Comment by allinurl** [comment]
I believe the ISP data is a paid option from maxmind. However, you could get close by using the IPs panel and passing `-d` to resolve the host names. Take a look at [**goaccess' demo**](https://rt.goaccess.io/?20220630181712#hosts).

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.

**Comment by epictz06** [comment]
> I believe the ISP data is a paid option from maxmind. However, you could get close by using the IPs panel and passing `-d` to resolve the host names. Take a look at [**goaccess' demo**](https://rt.goaccess.io/?20220630181712#hosts).

Hello ,
do you have any refrence from maxmind paid version ? 
i wanted to see if  it will fullfil what i want ( to show me how many % of ip loged is from what isp ) 
or not
could you help me in this?

**Comment by allinurl** [comment]
I believe is this: https://www.maxmind.com/en/geoip2-isp-database

Note that goaccess never implemented this as I don't have access to this db. Nonetheless, if you get your hands on one and are able share it for development, I can look into adding this feature.

**Comment by allinurl** [comment]
GeoIP2 binary MMDB format.

**Comment by epictz06** [comment]
I built an app that get ip data from an API from qrator.net
it take ages to be done but with distribution of ips it will take less time

**Comment by allinurl** [comment]
Got it. It will definitely be much faster via the db file.
