### ISSUE TITLE
How can I pass custom nginx log format to GoAccess

### ISSUE THREAD

**Issue by vidanil89** [allinurl/goaccess#2348]
My nginx custom log format is

    log_format plain_trace '$remote_addr - $remote_user [$time_local] "$request" $status '
                 '$body_bytes_sent "$http_referer" "$http_user_agent" '
                 '"$http_x_forwarded_for" $int_request_id $msec $request_time '
                 '$upstream_connect_time $upstream_header_time $upstream_response_time';

example:
10.81.142.115 - - [30/Jun/2022:05:30:08 +0300] "GET /api/modules/data-hash HTTP/1.1" 200 10 "-" "-" "10.81.142.115" 2e4895b6f9a462e35d60e8126a84fb1b 1656556208.724 0.000 0.000 0.000 0.000

Please help me whith:
time-format
date-format
log_format

**Comment by allinurl** [comment]
This should work:

    goaccess access.log --log-format='%h %^[%d:%t %^] "%r" %s %b "%R" "%u" %^ %^ %^ %^ %^ %^ %T' --date-format=%d/%b/%Y --time-format=%T -o report.html --real-time-html

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
