### ISSUE TITLE
How can I pass custom nginx log format to GoAccess

### ISSUE THREAD

**Issue by AlexBrickLink** [allinurl/goaccess#2349]
Need help parsing custom Nginx log format

log_format                  bldebug '[$time_local] $remote_addr $status $request_length "$request" "$http_cookie" "$http_x_forwarded_for" "$http_x_forwarded_proto"';

**Comment by allinurl** [comment]
Please post a few lines from your access log.

**Comment by AlexBrickLink** [comment]
109.237.103.118 - - [07/Jul/2022:07:51:49 -0400] "\x16\x03\x01\x01D\x01\x00\x01@\x03\x03y\x9A\x17\xC7N\xED\xDF\x0Ff\x9Dx\xF5\xC8\x04l[\xDF\xFB\xF5\xA3`$\x11\x19W\xF9d\x8C\xB8f\xF6\x18 \xB8\x959\xFE=\xA1|\xAAl\x8E\x1D\xCC?\xF2\xF6\x15[\xEB^~\x0F0\xFC\xDB\xB3E\x8A\xF1nC\xE0\xB0\x00b\x13\x02\x13\x03\x13\x01\xC0,\xC00\xC0+\xC0/\xCC\xA9\xCC\xA8\x00\xA3\x00\x9F\x00\xA2\x00\x9E\xCC\xAA\xC0\xAF\xC0\xAD\xC0$\xC0(\xC0" 400 166 "-" "-"
185.254.196.115 - - [07/Jul/2022:07:59:48 -0400] "GET /.env HTTP/1.1" 404 194 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36"
185.254.196.115 - - [07/Jul/2022:07:59:48 -0400] "POST / HTTP/1.1" 403 193 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36"
162.142.125.221 - - [07/Jul/2022:08:01:35 -0400] "GET / HTTP/1.1" 302 154 "-" "-"
162.142.125.221 - - [07/Jul/2022:08:01:35 -0400] "GET / HTTP/1.1" 302 154 "-" "Mozilla/5.0 (compatible; CensysInspect/1.1; +https://about.censys.io/)"
162.142.125.221 - - [07/Jul/2022:08:01:35 -0400] "PRI * HTTP/2.0" 400 166 "-" "-"

**Comment by AlexBrickLink** [comment]
thank you!

**Comment by allinurl** [comment]
Happy to help ;) Closing this. Feel free to reopen it if needed.
