### ISSUE TITLE
not reading the real timed synced file

### ISSUE THREAD

**Issue by rsidhaarth** [allinurl/goaccess#2350]
Hi,

I am trying to sync a log file from a different server to the server where goaccess is installed. And I ran the goaccess in real time with the log file location.

Even when the changes are made to the local file from the remote server, goaccess is not reflecting the changes.

I am able to see the changes in real time when I do tail -f

But not via goaccess logs.

**Comment by allinurl** [comment]
Please post how you are running goaccess.

**Comment by allinurl** [comment]
are you able to see it in real-time in the TUI? e.g.,

     goaccess /home/001/squid.log

**Comment by allinurl** [comment]
Great, so it sounds like a server config issue. Are you accessing the report via https or http? did you open port 7890? also please post a screenshot of your browser's console. Thanks

**Comment by allinurl** [comment]
To output real time data over a TLS/SSL connection, you need to use `--ssl-cert=<cert.crt>` and `--ssl-key=<priv.key>`.

**Comment by allinurl** [comment]
NGINX will serve the report.html, you need goaccess' WebSocket to get real-time data.

You want to use `--date-format=%s` `--time-format=%s` and log-format use %x instead of `%d` and `%t`. e.g., 

    goaccess access.log --log-format='%h %^[%x] "%r" %s %b "%R" "%u"' --datetime-format='%s' --tz=Europe/Berlin --date-spec=min -o report --real-time-html  --ssl-cert=<cert.crt> and --ssl-key=<priv.key>.

**Comment by allinurl** [comment]
Please attach a file with a few lines from your access log. e.g.,

    # tail -10 SQUID.log > sample.log

**Comment by allinurl** [comment]
The following should work, however, you will need to enclose the referrer and the user agent in quotes or some delimiter. 

    goaccess sample.txt --log-format='%x.%^ %L %h TCP_%C/%s %b %m %U %e %^ %M %R %^' --datetime-format=%s

If you enclose those two in quotes, then use

    goaccess sample.txt --log-format='%x.%^ %L %h TCP_%C/%s %b %m %U %e %^ %M "%R" "%u"' --datetime-format=%s

**Comment by allinurl** [comment]
The first format I posted works fine for the sample log you attached. .e.g.,

![2022-07-09-084403_648x408_scrot](https://user-images.githubusercontent.com/5005367/178108504-e07bf42b-61ed-415e-a3a6-df0a88b2f465.png)

As I said, the browser info needs to be properly delimited in your squid.log, otherwise you won't be able to parse that.

**Comment by allinurl** [comment]
This should work:

    goaccess squid.log --log-format='%^="%x.%^" %^="%L" %^="%h" %^="TCP_%C" %^="%s" %^="%b" %^="%m" %^="%U" %^="%e" %^="%^" %^="%M" %^="%R" %^="%u"' --datetime-format=%s --http-protocol=no

![2022-07-09-162255_562x947_scrot](https://user-images.githubusercontent.com/5005367/178123096-f5a20c8c-9211-4eaa-b95e-e39196b7a787.png)

**Comment by allinurl** [comment]
Glad to hear that worked. Closing this, feel free to reopen it if needed.
