### ISSUE TITLE
Stats when rewriting log file on remote sync

### ISSUE THREAD

**Issue by rsidhaarth** [allinurl/goaccess#2351]
Hi,

I am doing real time syncing files from our web server to goaccess server. And we have lots of servers

For now, I did for 4 servers, so all the log files from those servers are available in goaccess server and I am running goaccess by mentioning all the log files. But I am getting wrong data 

How do I confirm?

1) BW in the server is not matching with the goaccess stats
2) We also measure stats via stats plugin provided by the server and it is not matching with goaccess

3) I see 150M+ hits in goacces stats where as I went to each log files and counted the lines

a) 7518
b) 1692
c) 1678
d) 68134

Not sure why gostats gives wrong value. Where it went wrong?

**Comment by allinurl** [comment]
Sounds like a log format issue. Please see your other post #2350. Are you parse only one of those logs, e.g., 1692 and see if you get the same number of lines? Otherwise, feel free to attach that log here and I can take a look.

**Comment by allinurl** [comment]
It sounds like it's overwriting the file each time you synced the log. You need a way to forward your logs to central log server as opposed to copying it over and over again. or you could try mounting it via sshfs and have goaccess read those logs from the mount.

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
