### ISSUE TITLE
Issue with Real Time Reporting

### ISSUE THREAD

**Issue by aodsupport** [allinurl/goaccess#2353]
I have installed GoAccess 1.6.1 from source and enabled debug.  When I build the initial report, it shows data as you would expect via goaccess.html, however, it never updates.  When viewing the console it would bring in the storage, parse the log file, but then just show WebSocket server ready to accept new client connections without anything else. 

After enabling debug, it reports the Headers too long, No headers, Closing.   I have used multiple browsers and clients connecting to the goaccess.html

Any help would be appreciated. 

goaccess --real-time-html -o <path-to>/goaccess.html --log-format=COMBINED --persist --restore --db-path=/var/goaccess -f <path-to-log/access.log

Accepted: 15 [X.X.X.X]
Handling read 15 [X.X.X.X]...
Headers too long 15 [X.X.X.X]...
Broadcasting to 15 [X.X.X.X] No headers. Closing 15 [X.X.X.X]
Closing TCP 15 [X.X.X.X]
Connection Closed.

**Comment by allinurl** [comment]
Interesting... are you passing a cookie? Would you be able to share the request headers from your browser's network panel (perhaps Chrome) to see what the browser is sending? e.g., Thanks

![2022-07-13-164351_457x509_scrot](https://user-images.githubusercontent.com/5005367/178842018-8157ecce-5781-4d0d-93df-830e6f822d84.png)

**Comment by aodsupport** [comment]
Well, I was moving this to a different account on the same server so that I could better demonstrate the problem to you and I discovered the issue appears to be with HTTPS.  If the report.html is accessed via HTTP versus HTTPS then it works properly.

**Comment by allinurl** [comment]
I see. To output real time data over a TLS/SSL connection, you need to use `--ssl-cert=<cert.crt>` and `--ssl-key=<priv.key>`.

**Comment by aodsupport** [comment]
Would the cert and key just mirror whatever the front-end web server is using? i.e domain.com's cert/key pair?

**Comment by allinurl** [comment]
Correct.

**Comment by aodsupport** [comment]
Thank you, I will make the necessary adjustments. I appreciate the quick replies.
