### ISSUE TITLE
Unable to parse source address XFF field

### ISSUE THREAD

**Issue by ghost** [allinurl/goaccess#2354]
My nginx log got http_ x_ forwarded_ The real IP of for,

My nginx configuration is
'$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for" '

My nginx log is

172.23.51.6 - - [15/Jul/2022:19:15:14 +0800] "POST /MOSS/api/participationChance/getChance HTTP/1.1" 200 142 "http://172.23.51.7:8105/MOSS/engine/activity/act_dx-summer_1?tp=&tp1=&refer=" "webkit;Resolution(PAL,720P,1080P)" "173.57.136.164"

The log format of my goaccess configuration is
log_format %h - %^ [%d:%t %^] "%r" %s %b "%R" "%u" "~h"

But the source address of the analyzed result is 0

Please help me answer

**Comment by allinurl** [comment]
Assuming that your XFF field is separated by commas and spaces, then the following should work:

    goaccess access.log --log-format='%^[%d:%t %^] "%r" %s %b "%R" "%u" "~h{ ,}"' --date-format=%d/%b/%Y --time-format=%T

**Comment by riskt** [comment]
Sorry, as you can see, my http_ x_ forwarded_ The for field only has one IP address, so please provide me with an accurate configuration information. It is not feasible to follow the ~h in the official document

**Comment by riskt** [comment]
![image](https://user-images.githubusercontent.com/109352458/179355438-897eab63-1772-4946-a48d-4c76e8b9dda4.png)

**Comment by allinurl** [comment]
The one I posted above works fine for the line you posted. Please post at least 20 lines from your access log so I can make sure you got the right format.

**Comment by riskt** [comment]
This is my log format
172.23.51.6 - - [16/Jul/2022:20:35:29 +0800] "GET /MOSS/template/common/js/qrcode.js HTTP/1.1" 200 33782 "http://172.23.51.7:8105/MOSS/engine/mActivity/dx-summer" "Mozilla/5.0 (X11; U; Linux i686; en-US) AppleWebKit/534.0 (KHTML, like Gecko)" "173.93.24.137"
172.23.51.6 - - [16/Jul/2022:20:35:30 +0800] "GET /MOSS/template/activityTemp_0.25/pages/chest2_0.1/config.js HTTP/1.1" 200 1095 "http://172.23.51.7:8105/MOSS/engine/activity/act_dx-summer_1?tp=&tp1=&refer=" "Mozilla/5.0 (X11; U; Linux i686; en-US) AppleWebKit/534.0 (KHTML, like Gecko)" "173.93.24.137"
172.23.51.6 - - [16/Jul/2022:20:35:30 +0800] "GET /MOSS/template/activityTemp_0.25/pages/chest2_0.1/index.js HTTP/1.1" 200 24283 "http://172.23.51.7:8105/MOSS/engine/activity/act_dx-summer_1?tp=&tp1=&refer=" "Mozilla/5.0 (X11; U; Linux i686; en-US) AppleWebKit/534.0 (KHTML, like Gecko)" "173.93.24.137"

**Comment by allinurl** [comment]
As I posted before, that format should work - give it a shot!

![2022-07-17-184143_684x510_scrot](https://user-images.githubusercontent.com/5005367/179429542-2bfc2ef9-f718-49bf-bd68-26db2df7a669.png)

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it as needed.
