### ISSUE TITLE
XFF field breaks the cache status field

### ISSUE THREAD

**Issue by wfjsw** [allinurl/goaccess#2356]
Version: GoAccess - 1.6.2.

Example log entries:

```
[21/Jul/2022:00:00:06 +0000] [72dfa78678dcb2e7-MAN] 162.158.34.206 5.6.7.8 "GET /status HTTP/2.0" "200" 51 "www.example.com" "https://www.example.com/examplepath" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:99.0) Gecko/20100101 Firefox/99.0" "5.6.7.8" MISS "0.73" 0.066 1021 1541 HTTP/2.0
[21/Jul/2022:00:00:07 +0000] [72dfa78ee9ecb2e7-MAN] 162.158.34.206 5.6.7.8 "POST /status HTTP/2.0" "200" 611 "www.example.com" "https://www.example.com/examplepath" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:99.0) Gecko/20100101 Firefox/99.0" "5.6.7.8" - "1.56" 0.384 1724 2238 HTTP/2.0
[21/Jul/2022:08:45:10 +0000] [72e2a8a94e348865-FRA] 162.158.90.12 5.6.7.8 "GET /test.jpg HTTP/2.0" "200" 181 "www.example.com" "https://www.example.com/examplepath" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:99.0) Gecko/20100101 Firefox/99.0" "5.6.7.8" HIT "2.75" 0.047 1145 1286 HTTP/2.0
```

If I use this format string: 

```
log-format [%d:%t] [%^] %^ %h "%r" "%s" %b "%v" "%R" "%u" "~h{, }" %C "%^" %T %^ %^ %^
```

I'll get an empty cache status panel.

If I use this instead: 

```
log-format [%d:%t] [%^] %^ %h "%r" "%s" %b "%v" "%R" "%u" "%^" %C "%^" %T %^ %^ %^
```

Then the cache status panel will behave normally.

**Comment by allinurl** [comment]
This should work, let me know how it goes:

    goaccess access.log --log-format='[%x] %^ ~h{ } "%r" "%s" %b "%v" "%R" "%u" %^ %C "%T" %^' --datetime-format='%d/%b/%Y:%H:%M:%S %z'

**Comment by allinurl** [comment]
BTW, I wasn't sure which one was %T, so feel free to change it.

**Comment by allinurl** [comment]
Changing `%T` to the next field as you had it.

    goaccess accesslog --log-format='[%x] %^ ~h{ } "%r" "%s" %b "%v" "%R" "%u" %^ %C %^ %T %^' --datetime-format='%d/%b/%Y:%H:%M:%S %z'

**Comment by wfjsw** [comment]
Eh no. I didn't have any issue with datetimes. I have 
```
time-format %H:%M:%S %z
date-format %d/%b/%Y
```
set beforehand.

However the issue is that, when I attempt to handle the `X-Forwarded-For` field (the 7th field from right) I'll lose cache status. Ignoring it is fine.

**Comment by allinurl** [comment]
Did you try what I posted? The format I posted works fine for me. e.g., 

![2022-07-21-084805_658x880_scrot](https://user-images.githubusercontent.com/5005367/180229619-6681420c-d60e-4841-9427-59c21d571c9f.png)

**Comment by wfjsw** [comment]
The nginx log directive is: 

```
log_format  cf  '[$time_local] [$cf_ray] $realip_remote_addr $remote_addr "$request" '
    '"$status" $body_bytes_sent "$http_host" "$http_referer" '
    '"$http_user_agent" "$http_x_forwarded_for" $upstream_cache_status '
    '"$gzip_ratio" $request_time $bytes_sent $request_length $server_protocol';
```

Thus it makes no sense to put `~h{ }` at the place of `$remote_addr`.

![image](https://user-images.githubusercontent.com/2220320/180230595-3d36bbe4-558f-48b8-a124-dd754eff401f.png)

I have no huge issues with the original format strings anyway. However note these `T. S.` field (`%T`) after `"~h{, }"`. They are gone.

The cache statuses are also gone:
![image](https://user-images.githubusercontent.com/2220320/180231324-6f1d14b5-748b-4938-a09b-f0a4a57156af.png)

If I replace the `"~h{, }"` to `"%^"` everything is back to normal:
![image](https://user-images.githubusercontent.com/2220320/180231608-ed6f4a1d-fde2-4d3c-86d5-930b035d5bac.png)

So I suspect there is something broken in `"~h{, }"` that prevents fields after that being parsed.

**Comment by allinurl** [comment]
I guess I'm not following, aren't `162.158.34.206` & `162.158.90.12`  the client ips? You can't use `%h` and `~h` on the log-format. It has to be one or the other one.

**Comment by wfjsw** [comment]
`162.158.90.12` is ip of the proxy. `5.6.7.8` is the real ip extracted by nginx. And there is an additional raw XFF header value.

Yes when `%h` is eliminated this bug no longer appears as well. But I think the side effect caused by using `%h` and `~h` altogether is still unexpected? That is, goaccess is not properly ignoring `~h`  when `%h` is present.

**Comment by allinurl** [comment]
Thanks for reporting this. The issue should be fixed upstream now. Please feel free to build from [**development**](https://github.com/allinurl/goaccess#build-from-github-development) and let me know if that solves the issue on your end.

Also please note that the parser will now attempt to process the XFF even when `%h` has already been set. So if you can get the host field from your log via `%h`, do that — for performance reasons, I'd avoid using `%h` and `~h` together.
