### ISSUE TITLE
Custom config for JSON logs

### ISSUE THREAD

**Issue by timonson** [allinurl/goaccess#2357]
Although I really tried to avoid it, I would like to ask for a config for my JSON scheme, because I was not able to get it done and I would like to use your service. Besides other things, I looked at the examples [here](https://github.com/allinurl/goaccess/issues/1768) for caddy but I couldn't even execute those without an `IPv4/6 is required` error. 

I would also like to encourage you to add some more concrete examples for custom logs, because the [only-text-documentation](https://goaccess.io/man#options) is at least for my understanding sometimes not precise enough. For example, what **exactly** is a *request line from the client*?

Thanks!

```json
{
  "timestamp": "2022-07-26T23:48:18.066Z",
  "request": {
    "hostname": "127.0.0.1",
    "method": "GET",
    "url": "http://localhost:8080/books/123",
    "headers": { "User-Agent": "curl/7.84.0" }
  },
  "status": 404,
  "length": 9,
  "responseHeaders": {
    "X-Response-Time": "1ms",
    "Content-Type": "text/plain;charset=UTF-8"
  },
  "message": null, 
  "user": null, 
  "logger": "default",
  "level": "WARNING"
}
```

Here, `request.hostname` always contains an IP address.

**Comment by allinurl** [comment]
Happy to help. The following should work (as long as the access log has a valid JSON format, e.g., no // comments)

    goaccess access.log --log-format='{"timestamp":"%dT%t.%^","request": {"hostname":"%h","method":"%m","url":"%U","headers":{"User-Agent":"%u"}},"status":"%s","length":"%b","responseHeaders":{"X-Response-Time":"%Lms","Content-Type":"%M;%^"}}' --date-format=%Y-%m-%d --time-format=%T --http-protocol=no

**Comment by timonson** [comment]
Thanks for the quick reply. I am getting this error, although I tried both the installation from the aur and I installed it from *development*:

```
goaccess access.log --log-format='{"timestamp":"%dT%t.%^","request": {"hostname":"%h","method":"%m","url":"%U","headers":{"User-Agent":"%u"}},"status":"%s","length":"%b","responseHeaders":{"X-Response-Time":"%Lms","Content-Type":"%M;%^"}}' --date-format=%Y-%m-%d --time-format=%T --http-protocol=no
Cleaning up resources...
==67108== GoAccess - version 1.6.2 - Jul 27 2022 03:12:33
==67108== Config file: /usr/local/etc/goaccess/goaccess.conf
==67108== https://goaccess.io - <hello@goaccess.io>
==67108== Released under the MIT License.
==67108==
==67108== FILE: access.log
==67108== Parsed 10 lines producing the following errors:
==67108==
==67108== IPv4/6 is required.
==67108== IPv4/6 is required.
==67108== IPv4/6 is required.
==67108== IPv4/6 is required.
==67108== IPv4/6 is required.
==67108== IPv4/6 is required.
==67108== IPv4/6 is required.
==67108== IPv4/6 is required.
==67108== IPv4/6 is required.
==67108== IPv4/6 is required.
==67108==
==67108== Format Errors - Verify your log/date/time format
```

**Comment by allinurl** [comment]
Are you sure your access log looks exactly the same as the sample you posted above? are you able to attach here a file with 20 lines directly from your access log? e.g.,

    # head -20 access.log > test.log

**Comment by timonson** [comment]
[access.log](https://github.com/allinurl/goaccess/files/9194409/access.log)

**Comment by allinurl** [comment]
Your sample above has `hostname`, your log has `remoteHostname`. The following should work:

    goaccess access.log --log-format='{"timestamp":"%dT%t.%^","request": {"remoteHostname":"%h","method":"%m","url":"%U","headers":{"User-Agent":"%u"}},"status":"%s","length":"%b","responseHeaders":{"X-Response-Time":"%Lms","Content-Type":"%M;%^"}}' --date-format=%Y-%m-%d --time-format=%T --http-protocol=no

**Comment by timonson** [comment]
Oh man, my bad, sorry! Now it works. Thank you very much!

**Comment by allinurl** [comment]
No worries, glad that did the job!
