### ISSUE TITLE
Time recognition does not work for me on custom log

### ISSUE THREAD

**Issue by 53845714nF** [allinurl/goaccess#2359]
I have a very simple apache access.log Format, it here a sample:
```
[28/Jul/2022:00:16:21 +0200] „GET /robots.txt HTTP/1.1“ 404 4594
[28/Jul/2022:00:16:25 +0200] „GET /en/blog/foobar/ HTTP/1.1“ 200 5395
[28/Jul/2022:00:16:31 +0200] „GET /en/blog/img/foo.jpg HTTP/1.1“ 200 26420
[28/Jul/2022:00:21:26 +0200] „GET /robots.txt HTTP/1.1“ 404 4594
[28/Jul/2022:00:21:28 +0200] „GET /blog/test%C3%9F/ HTTP/1.1“ 200 5771
```
I have tried to evaluate them with this: `LC_TIME="en_US.UTF-8" bash -c 'goaccess blog_access.log --log-format='[%d:%t %^] „%r“ %>s %b' --date-format=%d/%b/%Y --time-format=%T'`

But I get:
```
Parsed 1 lines producing the following errors:

Token '00:16:21 +0200] „GET /robots.txt HTTP/1.1“ 404 4594' doesn't match specifier '%t'
```

I think the `%T` should work, but it doesn't why?

**Comment by allinurl** [comment]
I see some weird chars when I try to paste those sample lines on my end. Can you please attach a file directly from your access log? e.g.,

     # tail -20 access.log > sample.log

**Comment by 53845714nF** [comment]
Thanks for the quick reply, here is the file:
[sample.log](https://github.com/allinurl/goaccess/files/9221600/sample.log)

**Comment by allinurl** [comment]
You got some strange characters in there. For instance, `"` right after the protocol is not an actual `"` + the spacing before the method. The following should work as long as you add an IP to the log.

    # goaccess sample.log --log-format='[%x] „%m %U %H“ %s %b' --datetime-format='%d/%b/%Y:%H:%M:%S %z'

You could either start logging the ip or add a bogus IP with awk or sed and pipe the output to goaccess.

    # awk '{print $0, "192.168.0.1"}' sample.log | goaccess - --log-format='[%x] „%m %U %H“ %s %b %h' --datetime-format='%d/%b/%Y:%H:%M:%S %z'

![2022-07-29-220847_603x644_scrot](https://user-images.githubusercontent.com/5005367/181870223-05ec55e9-0464-40b7-9038-128a2eedf7ae.png)


Let me know if that helps.

**Comment by 53845714nF** [comment]
Ohh sorry the quotes are in a German style format.

But thanks a lot it worked for me.
