### ISSUE TITLE
debug-file flag

### ISSUE THREAD

**Issue by xavier-hernandez** [allinurl/goaccess#2360]
Hi,

I'm running something similar to below, not sure if I'm doing something wrong here but the debug file gets created as "--debug-file=goaccess.debug" rather than "goaccess.debug". The invalid requests file gets created correctly.

goaccess -l --debug-file=goaccess.debug --invalid-requests=goaccess.invalid --no-global-config --ping-interval=15 --config-file=goaccess.conf

Thanks!

**Comment by allinurl** [comment]
Looks like you are passing `-l` + `--debug-file` which are the same. I'd do one or the other one but not both:

    goaccess --debug-file=goaccess.debug --invalid-requests=goaccess.invalid --no-global-config --ping-interval=15 --config-file=goaccess.conf

**Comment by xavier-hernandez** [comment]
@allinurl thanks that worked. I guess I misunderstood the man page :/

By the way, I saw this as well,--ping-interval≶secs> . It should be =< . Do you want me to open a separate issue for that?

Thanks.

**Comment by allinurl** [comment]
Thanks for letting me know. It should be fixed now :)
