### ISSUE TITLE
Please help me parse the custom nginx log

### ISSUE THREAD

**Issue by DQYXACML** [allinurl/goaccess#2361]
log_format:
`log_format foody '$time_iso8601 | $remote_addr | $remote_user | $request | $status | $body_bytes_sent | $http_referer | $http_user_agent | $request_time | $upstream_response_time | $upstream_connect_time | $upstream_header_time |$http_x_forwarded_for | $geoip_country_code | $host | $upstream_addr';`

sample logs:
[sample.log](https://github.com/allinurl/goaccess/files/9242244/sample.log)

Please help me create log-format.

Thanks

**Comment by allinurl** [comment]
This should do it, let me know:

    goaccess access.log --log-format='%dT%t+%^ | %h | %e | %m %U %H | %s | %b | %R | %u| %T | %^ | %^ | %^ | %v %^' --date-format=%Y-%m-%d --time-format=%T

**Comment by DQYXACML** [comment]
hi, seems can not exec in my centos, it shows `Token '' doesn't match specifier '%h'`, but can exec in my macos. may have some issue with my shell environment? do u have any idea about this


Centos:
CentOS Linux release 7.5.1804 (Core)
Bash version:
GNU bash， 版本 4.2.46(2)-release (x86_64-redhat-linux-gnu)

Mac:
macOS Monterey 12.4
ZSH version:
zsh 5.8.1 (x86_64-apple-darwin21.3.0)

**Comment by allinurl** [comment]
Are you running the same version of goaccess in both machines? also, do both of them have the same locale? and last, are you running it against the same access log?

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it as needed.
