### ISSUE TITLE
How do I set up GoAccess with Caddy reverse proxy?

### ISSUE THREAD

**Issue by marcstae** [allinurl/goaccess#2362]
Hi,
I stumbled over your open source project, and I'm pretty new to selfhosting, therefore I wanted something to see my traffic through my Caddy2 reverse proxy.
Sadly I didn't find any guides on how to set it up with caddy, could you guide me in the right direction on where I should look?

Thanks for your help :)

**Comment by allinurl** [comment]
Hello,

Please take a look at the [**getting started**](https://goaccess.io/get-started) section on how to best install it. Then you can simply run it against your caddy's access log. e.g.,

    # goaccess access.log --log-format=CADDY -o report.html

Then you can open your `report.html` directly in your browser (Ctrl+o) or simply drop it in your document/site root path and access via https://your-domain.com/report.html.

Let me know if you have any additional questions.

**Comment by allinurl** [comment]
BTW, this assumes your Caddy's access log is in a valid JSON format. Otherwise, you can always set your log format under Caddy's [config](https://caddyserver.com/docs/caddyfile/directives/log) file as `log { format json } ...`.

**Comment by marcstae** [comment]
Hey, thanks for your help, so I got GoAccess to work, but I can't get Caddy to output any log data. 

At the moment, my Caddy file looks like this:
```
superchargejs.com {
  log {
    output file /var/log/caddy/superchargejs.com-access.log
    format json
    level INFO
  }
}
service1.domain.ch:443 {
    reverse_proxy localhost:8096
}
service2.domain.ch:443 {
    reverse_proxy 192.168.1.205:3001
}
service3.domain.ch:443 {
    reverse_proxy 192.168.1.169:8008
}
```

Maybe you have some experience with the Caddy reverse proxy and can help me out. :)
What would be the command for the rolling report.html files?

Thanks for your help, greatly appreciated!

**Comment by allinurl** [comment]
Glad you got goaccess to work. 

I haven't set up Caddy as a reverse proxy myself, but maybe this [post](https://github.com/allinurl/goaccess/issues/2270#issuecomment-1036521285) can give you a hint? If it's not spitting out any data, I'd post the question on their [community forum](https://caddy.community/t/v2-common-log-format-not-working/7352).

**Comment by allinurl** [comment]
Any updates on this? Thanks

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
