### ISSUE TITLE
Error occurred at: src/util.c - get_home

### ISSUE THREAD

**Issue by SuperLemons** [allinurl/goaccess#2364]
when i create html report it have a error
Fatal error has occurred
Error occurred at: src/util.c - get_home - 466
Unable to determine the HOME environment variable.

How can I go to fix it

**Comment by allinurl** [comment]
Please upgrade to the latest version of goaccess. Otherwise, please try setting the HOME env variable.

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it as needed.
