### ISSUE TITLE
Cygwin Build Error -- gcc: error: unrecognized command line option ‘-rdynamic’

### ISSUE THREAD

**Issue by skrossner** [allinurl/goaccess#237]
Platform: Windows 7 x64
Cygwin version: 1.7.35 x64

config.log: https://cryptobin.org/w6l691z0
* password: allinurl-goaccess-config.log

make log: https://cryptobin.org/x851d2j0
* password: allinurl-goaccess-make.log

Let me know if you have any questions. Thanks!

**Comment by allinurl** [comment]
Thank you for reporting it, I'm looking into this, I'll follow up as soon as I figure out what's the issue.

**Comment by allinurl** [comment]
Interesting, when I tried it myself, the build succeeded:

    gcc (GCC) 4.9.2, 
    uname -m = i686
    uname -r = 1.7.35(0.287/5/3)
    uname -s = CYGWIN_NT-6.1
    uname -v = 2015-03-04 12:07

However, my build does not compile with `-rdynamic`. If you run `$ ldd --version` what output do you get? Thanks.

**Comment by skrossner** [comment]
`$ ldd --version
ldd (cygwin) 1.7.35
Print shared library dependencies
Copyright (C) 2009 - 2015 Chris Faylor
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
`

It looks like you're compiling with the 32-bit version of GCC whereas I'm using the 64-bit version. Let me know if you have any questions.

**Comment by allinurl** [comment]
This has been fixed. Feel free to build from [dev]([http://goaccess.io/download#build). 

Let me know how it goes. I'll push this in the upcoming version. Thanks!

**Comment by skrossner** [comment]
The fix works. It compiles now. Thanks!
