### ISSUE TITLE
Help with parsing and interpreting these user agents

### ISSUE THREAD

**Issue by CondePrinceduSang** [allinurl/goaccess#2370]
Hello
I am looking for help with parsing these user agents found in my access logs. 

Mozilla/5.0 (Linux; Android 11; BE2025 Build/RKQ1.201217.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/96.0.4664.45 Mobile Safari/537.36 MinuteMaid,gzip(gfe)

GoogleAuth/1.4 (OnePlusN10METRO RKQ1.201217.002); gzip,gzip(gfe),gzip(gfe)

Mozilla/5.0 (Linux; Android 10; SM-A115U Build/QP1A.190711.020; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/94.0.4606.71 Mobile Safari/537.36 MinuteMaid,gzip(gfe)

I have tried parse them on different platforms but I seem to get different results each time. 
What I am trying to figure out is the type of devices of webview platforms are used with these UAs

Thank You all so much!

**Comment by allinurl** [comment]
Can you please share the date/time/log-format that you are currently using? Also, are you getting the wrong results on the exact same log?

**Comment by CondePrinceduSang** [comment]
Hello
Remember you're talking to a non tech person... I ll try to explain. The user agents that I want to parse use Android Webview. The symbol is visible. But your parse agent, shows an actual device with all the definitions. Most of the other UA show the device as being a desktop emulator (see below)
Mozilla/5.0 (Linux; Android 11; BE2015 Build/RKQ1.201217.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/97.0.4692.70 Mobile Safari/537.36
GSA/12.48.23.23.arm64,gzip(gfe)

And then there's another type of UA that simply comes back empty (see below)
GoogleAuth/1.4 (t2q SP1A.210812.016); gzip ,gzip(gfe),gzip(gfe).

Please find below a full date/time/log-format

2022-01-13 03:08:45 Z 3.143.214.41 Login GoogleAuth/1.4 (t2q SP1A.210812.016); gzip ,gzip(gfe),gzip(gfe)

**Comment by allinurl** [comment]
Can you please post exactly what you have and the output you are looking from goaccess so I can try to understand better. Also, please post a screenshot of what goaccess is currently outputting. Thanks

**Comment by allinurl** [comment]
Any updates on this?

**Comment by CondePrinceduSang** [comment]
Hello Gerardo,

I have a situation, someone who had access to my devices and credentials
has been hacking my online accounts among other things. So I started
looking at all my data, including the login entries of my google accounts.
So I have been cross referencing and analyzing the UA that were included
with the logins, especially when the date logs wouldn't match an access
time of mine (when I was on a plane, or the devices were not in use,
etc...).
Some of UA contained the mention "WV" and the analysis returned things like
"via google frontend" which I am trying to understand exactly what it means.

Regarding Github, I am sorry, I am hopeless. I just don't understand how it
works.

Thank you for asking.

**Comment by allinurl** [comment]
Happy to help but I'd need some screenshots of what you are seeing on your end while using goaccess. Thanks

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
