### ISSUE TITLE
Unique Visitors Per Day graphics being hard to read

### ISSUE THREAD

**Issue by jonasdk** [allinurl/goaccess#2377]
I have run GoAccess on data from a period from the 22th of August to the 6th of September but the graph seems to be of by just listing the 05/Sep/2022 for every tick. Any suggestion to what I do wrong?

By the way I run following command to get the report
```
goaccess access-combined.log --log-format='{"timestamp":"%x","client_ip":"%h","host":"%v","url":"%U","request_method":"%m","request_protocol":"%H","request_referer":"%R","request_user_agent":"%u","response_state":"%C-%^","response_status":"%s","response_body_size":"%b","fastly_server":"%e"}' --datetime-format='%Y-%m-%dT%H:%M:%S%z' --tz=UTC --date-spec=min -o report.html
```
<img width="735" alt="Screen Shot 2022-09-07 at 21 58 00" src="https://user-images.githubusercontent.com/85319/188965833-16ef1a64-17fd-4f58-80cf-d7e82587c94e.png">

**Comment by allinurl** [comment]
Please try running it without `--date-spec=min`.
