### ISSUE TITLE
Parse Log with hostname instead of ipv4/ipv6

### ISSUE THREAD

**Issue by pniederlag** [allinurl/goaccess#2378]
I have a log-file where the ip is already resolved and instead of ip has a hostname as a field.

It seems this field is not understood by goaccess. As I understand the hostname field is manadatory, but is it really a requirement to hold an IP? 

`Token 'some.perfect-valid-hostname.example.com' doesn't match specifier '%h'`

Does someone have an advice?

**Comment by pniederlag** [comment]
digging into the source I spotted `--no-ip-validation ` which seems to do the trick

**Comment by allinurl** [comment]
That's right. `--no-ip-validation` will do the job, still you will need to specify `%h` where the ip has been resolved.

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it as needed.
