### ISSUE TITLE
Blank page when html report is generated

### ISSUE THREAD

**Issue by civodul999** [allinurl/goaccess#2379]
Hi,
I would like to use goaccess with html report.

when I'm using the console lik this:
`goaccess /var/log/apache2/access.log -c`
I have a window to choose log format, I select NCSA combined log format, and it's OK, I see a dashboard.

But, when I want to use html report like this : 
`goaccess /var/log/apache2/access.log -o /var/www/report-test.html --log-format=COMBINED`

When I open the report-test.html, it's a white page, I just have the date of the report.

On my terminal, I see this : 

> 
> [SETTING UP STORAGE /var/log/apache2/access.log] {0} @ {0/s}
> 
> Cleaning up resources...
> 

I don't know what to do.

- My php version is 7.3.31
- Goaccess version is 1.6.3
- Debian version is 10.12.

Thank you for your help.

**Comment by allinurl** [comment]
Could you please post the output of your browser's console? Thanks

**Comment by civodul999** [comment]
> Could you please post the output of your browser's console? Thanks

hi, the output is this one : 

`Last Updated: 2022-09-11 15:21:28 +0200

Dashboard`

**Comment by allinurl** [comment]
Can you please post a screenshot of your browser's console (dev tools' console)?

**Comment by allinurl** [comment]
Glad to hear you found the issue.
