### ISSUE TITLE
help with my log/date/time format please

### ISSUE THREAD

**Issue by Keajer** [allinurl/goaccess#238]
68.67.161.151 - GET /ready HTTP/1.1 - /ready - 200 "u status" -  "U Response" - "MSec" 1427761920.280
    204.13.192.83 - GET /ready HTTP/1.1 - /ready - 200 "u status" -  "U Response" - "MSec" 1427761920.280
    204.13.193.119 - GET /ready HTTP/1.1 - /ready - 200 "u status" -  "U Response" - "MSec" 1427761920.280
    204.13.193.38 - POST /rtb/getAd/12 HTTP/1.1 108.15.29.154 /rtb/getAd/12 192.168.23.82:9558 499 "u status" -  "U Response" - "MSec" 1429233379.104
    204.13.192.166 - POST /rtb/getAd/12 HTTP/1.1 50.127.203.219 /rtb/getAd/12 192.168.23.84:9558 499 "u status" -  "U Response" - "MSec" 1429233379.104
    204.13.193.218 - POST /rtb/getAd/12 HTTP/1.1 123.3.163.8 /rtb/getAd/12 192.168.23.84:9558 499 "u status" -  "U Response" - "MSec" 1429233379.104

Thank you very much!

**Comment by allinurl** [comment]
Could you please elaborate a bit more about the format? For instance, which one is the client host?, byte size?

**Comment by Keajer** [comment]
Oh sorry..
please help on error log too..
log_format main '$remote_addr $http_user_agent $request $http_x_forwarded_for $uri $upstream_addr $status "u status" $upstream_status  "U Response" $upstream_response_time "MSec" $msec  ';

    log_format error '"Status" $status "Bytes" $bytes_sent "u Addr:" $upstream_addr  "u status" $upstream_status  "U Response" $upstream_response_time "MSec" $msec  ';

Thank you!

**Comment by allinurl** [comment]
Assuming the last part is the actual date as timestamp, then the following does a partial job. Also, seems like there is no response size in bytes. GoAccess requires at least three fields, valid date, valid ipv4/6, and the request.  It does not support error logs.

    log-format %h %^ %m %U %H %^ %^ %^ %s "%^" %^"%^" %^ "%^" %d.
    date-format %s
    time-format %s

**Comment by allinurl** [comment]
More info about the [custom log](http://dev.goaccess.io/man#custom-log).
