### ISSUE TITLE
Caddy - GoAccess issues

### ISSUE THREAD

**Issue by MehdiKammakh** [allinurl/goaccess#2380]
Dear team, 
I have tried to implement GoAccess to work with Caddy access logs 
I have proceeded by running an apache2 docker container , and inside it running goaccess ( apt-get install goaccess )

>  # goaccess --version
> GoAccess - 1.4.
> For more details visit: http://goaccess.io
> Copyright (C) 2009-2020 by Gerardo Orellana
> 
> Build configure arguments:
>   --enable-utf8
>   --enable-geoip=mmdb
>   --with-openssl

I have followed the setup and running this command : `goaccess /var/logs/caddy/site.fr-access.log -o /usr/local/apache2/htdocs/report.html --real-time-html --log-format=CADDY` and I'm getting an error like this : `Error occurred at: src/parser.c - parse_log - 2777
No time format was found on your conf file.`

also tried this command regarding this issue : https://github.com/allinurl/goaccess/issues/1571#issuecomment-543186858 

`LANG="en_US.UTF-8" bash -c 'goaccess /var/logs/caddy/site-access.log -o /usr/local/apache2/htdocs/report.html --real-time-html --log-format=CADDY'` but nothing special happened 

my caddy config is like this : 
`
site.fr {
        handle {
                reverse_proxy site-hostname:80
        }
  log {
    output file /var/log/caddy/site.fr-access.log
    format json
  }
import common
}
`
Please, if anyone have an idea how to fix this , I will be appreaciate it 
thank you

**Comment by allinurl** [comment]
JSON support was added in 1.4.4. Please use this [**docker image**](https://github.com/allinurl/goaccess#docker) or the official [deb repo](https://github.com/allinurl/goaccess#official-goaccess-debian--ubuntu-repository).

**Comment by allinurl** [comment]
That's correct.

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it as needed.

**Comment by MehdiKammakh** [comment]
I have an issue when mapping Caddy reverse proxy to the container that GoAccess run on 

my Caddy config is : 

```
goaccess.innoyadev.fr {
        handle {
                reverse_proxy p-GoAccess-Apache:7890
                                basicauth {
        InnoyaDev JDJhJDE0JERkQ3hCbWhmemlETUdqNFg4QndhdHVIWVhXenRiRHV1enZXclBPS1VwM3o0MUkyR0RRZUFX
       }
        }
  log {
    output file /var/log/caddy/goaccess.innoyadev.fr-access.log
    format json
  }
}
```
running GoAccess on httpd docker container with this command 
`goaccess /var/logs/caddy/*-access.log -o /usr/local/apache2/htdocs/report.html --real-time-html --log-format=CADDY --daemonize`

GoAccess running correctly inside the container : 

`root@p-GoAccess-Apache:/usr/local/apache2# lsof -i -P -n
COMMAND  PID USER   FD   TYPE    DEVICE SIZE/OFF NODE NAME
httpd      1 root    3u  IPv4 555951236      0t0  TCP *:80 (LISTEN)
goaccess  99 root    8u  IPv4 555949745      0t0  TCP *:7890 (LISTEN)`

when trying accessing **goaccess.innoyadev.fr** , I get 400 request

**Comment by MehdiKammakh** [comment]
@allinurl FYI

**Comment by allinurl** [comment]
Does [**this**](https://github.com/allinurl/goaccess/issues/2270#issuecomment-1036521285) help? It seems to work for this user.
