### ISSUE TITLE
GUI Real time Filters 

### ISSUE THREAD

**Issue by MehdiKammakh** [allinurl/goaccess#2383]
Dear team , 
Is there a GUI filter for dates - log files hostnames ?

**Comment by allinurl** [comment]
It will be able available soon. I'm working on #117 as we speak. Stay [**tuned**](https://twitter.com/goaccess)!

**Comment by allinurl** [comment]
Closing this. [**Stay tuned**](https://twitter.com/goaccess) for this feature.
