### ISSUE TITLE
Support the maxmind GeoLite2 ASN  database

### ISSUE THREAD

**Issue by ollybee** [allinurl/goaccess#2386]
Currently goaccess support the Maxmind country and city databases but not the ASN database

For detecting malicious traffic the ASN database  is most useful in my experience (Cloudflare can give you per ASN stats on paid plans). The country is often too broad, cities is better but it can be hard to be sure if traffic is unwanted. `ASN 666: Popeyes budget colocation` is much easier to eyeball as something you want to block.

**Comment by allinurl** [comment]
Thanks for the suggestion! I totally agree, let me look into this and I'll post back after some findings.

**Comment by allinurl** [comment]
This has been implemented. It will be pushed out in the upcoming release. Stay tuned!

**Comment by allinurl** [comment]
BTW, you will be able to pass multiple dbs. e.g., 

    goaccess access.log --log-format=COMBINED --geoip-database=GeoLite2-ASN.mmdb --geoip-database=GeoLite2-City.mmdb
