### ISSUE TITLE
--html-custom-css and --html-custom-js now require valid paths

### ISSUE THREAD

**Issue by colder** [allinurl/goaccess#2388]
Hello,

Following 5f814c8f18d3470e9a322e8d4ac709b455565c7f, the options for `--html-custom-css` and `--html-custom-js` are now checked to ensure they point to valid paths, even though they will be included as urls in the resulting report.

e.g. the following command:

```
goaccess file.log .. --html-custom-css=/goaccess.css ..
```

will fail because the server generating the report does not have a file there:

```
Fatal error has occurred
Error occurred at: src/options.c - parse_long_opt - 356
Unable to open custom CSS filename: /goaccess.css
```

But the resulting report could be viewed on a website where a `/goaccess.css` exists at the top-level. Alternatively, we could want to specify a plain old url.

How can I generate a report with e.g. a toplevel css / js file then? This new check seems spurious.

Best

**Comment by allinurl** [comment]
Thanks for pointing that out. We could allow URLs as well, would that cover your use case?

**Comment by colder** [comment]
Hello,

Thanks for your quick reply.

My current use-case was css/js paths looking like " /url/to/file", but I would be fine if you supported URLs such as "https://domain/path/to/file" or "//domain/path/to/file" as well. 

Best,

**Comment by allinurl** [comment]
Thanks for the feedback. I've pushed some changes that should address the checking of a path/filename. It will still prevent special html chars to avoid xss stuff. Please feel free to build from [development](https://github.com/allinurl/goaccess#build-from-github-development) and let me know how it goes.

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
