### ISSUE TITLE
Token 'to:' doesn't match specifier '%s'

### ISSUE THREAD

**Issue by adylimmo** [allinurl/goaccess#2389]
Hello everyone, please help goaccess nginx error

**my nginx log**
10.0.3.154 - - [05/Oct/2022:03:35:39 +0700] "POST /v2/auth/refreshToken HTTP/2.0" to: 192.168.200.146:80 422 35 "-" "oxttp/4.5.0" "-" "api.domain.com" upstream_response_time 0.026 msec 1664915739.787 request_time 0.026

**command:**
goaccess cek-access.log --log-format=COMBINED -a -o /usr/share/nginx/html/log-nginx/report-format.html

**error:**
Parsed 1 linesproducing the following errors:

Token 'to:' doesn't match specifier '%s'

Format Errors - Verify your log/date/time format

**Comment by allinurl** [comment]
Sorry for the delay. This should do it (assumes latest version):

    goaccess access.log --log-format='%h %^[%x] "%r" %^ %^ %s %b "%R" "%u" %^ "%v" %^ %^ %^ %^ %^ %T' --datetime-format='%d/%b/%Y:%H:%M:%S %z'

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
