### ISSUE TITLE
 Token doesn't match specifier '%d'

### ISSUE THREAD

**Issue by roshan5690** [allinurl/goaccess#2393]
I am not able to parse the custom logs using goaccess and I am getting following error while parsing.

 Token 'daksldjslss@192.168.0.36 207 repo' doesn't match specifier '%d'

 Command I have used.

 goaccess /home/ubuntu/load-analysis_svn-cache-svn.log -o /home/report.html --log-format='COMBINED'

Log File:

[2022-09-29 10:53:21.353073 +0200] daksldjslss@192.168.0.36 207 repo:/var/www/repos/gtup get-inherited-props /libs/JC6_HMI/tags/BLD-JC6_HMI-1.0.0-025/out r32395 (216 Bytes in 0 Sec)
[2022-09-29 10:53:21.357983 +0200] daksldjslss@192.168.0.36 207 repo:/var/www/repos/gtup checkout-or-export /libs/JC6_HMI/tags/BLD-JC6_HMI-1.0.0-025/out r32395 (600 Bytes in 0 Sec)

**Comment by allinurl** [comment]
Could you please specify what’s the client ip? Also, I assume no user agent nor referrer…

**Comment by roshan5690** [comment]
Following client IP

daksldjslss@192.168.0.36 207 which tying to checkout the repository code.

**Comment by roshan5690** [comment]
Hello, Could you please provide the information how can I parse the custom logs  ?

**Comment by allinurl** [comment]
Untested but please try this:
    
    goaccess access.log log-format=‘[%d %t.%^] %e@%h %s %^ %U %^ %v %M (%b %^ %^ %T%^)’ date-format=%Y-%m-%d time-format=%T

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
