### ISSUE TITLE
Unable to get real-time html working on subdomain with Ghost

### ISSUE THREAD

**Issue by ylanarfi** [allinurl/goaccess#2394]
Hi there,

I'm running Ghost on Ubuntu 20.04 with Digital Ocean's doplet and NGINX. I installed GoAccess with success and I'm able to launch it with the command 

`goaccess access.log --log-format=COMBINED`

However, I'm unable to get real-time html working while generating it with 

`goaccess access.log -o report.html --log-format=COMBINED` 

and move it to _/var/www/html/_ then parses the access log and displays the stats in a real-time HTML report with 

`goaccess access.log -o /var/www/html/report.html --log-format=COMBINED --real-time-html`

I'm using HTTPS so I'm wondering if I should add anything else?

I'm assuming it is something stupid but I can't figure it out, I just get a 404 while trying to open subdomain.domain.ca/report.html (where my ghost installation is).

Am I supposed to put the html file anywhere else than /var/www/html/ ? I'm a bit confused so your help will be much appreciated :) I love the concept tho, thanks for this amazing work!

**Comment by allinurl** [comment]
Hello. Not familiar with ghost but it seems like you can run:

    # ghost ls

It should output where your site lives. As far as https, you will need to pass  --ssl-key=<path/priv.key>  and --ssl-cert=<path/cert.crt>. 

Please let me know if that helps.

**Comment by allinurl** [comment]
If you’re running goaccess on the same server, I’d reuse your site existing certificate and key and pass those paths to goaccess. If you’re running nginx, take a look at your site’s config file.

**Comment by ylanarfi** [comment]
> If you’re running goaccess on the same server, I’d reuse your site existing certificate and key and pass those paths to goaccess. If you’re running nginx, take a look at your site’s config file.

I checked on NGINX and the ssl info are located

**Comment by ylanarfi** [comment]
Hi there!

Is anyone knows how to solve this issue? I'm still blocked :(

Thanks!

**Comment by ylanarfi** [comment]
It does not recognize the ssl option

`goaccess: unrecognized option '--ssl-key=/etc/letsencrypt/blog.arfy.ca/blog.arfy.ca.key`

**Comment by allinurl** [comment]
Please make sure to build using --with-openssl

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
