### ISSUE TITLE
I can't get report with Virtual Host. 

### ISSUE THREAD

**Issue by garion3024** [allinurl/goaccess#2397]
I got a message for 
 **Token '+0000]' doesn't match specifier '%h'**    

My apache log format is 
LogFormat "%v:%p %h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" combinedvhost

I attach my log sample, 

172.31.40.4 - - [13/Oct/2022:08:40:05 +0000] "GET /dashboard/ HTTP/1.1" 304 - "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36"
172.31.9.122 - - [13/Oct/2022:08:40:06 +0000] "OPTIONS /dashboard/noticeCount HTTP/1.1" 200 - "vhost.xxx" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36"
172.31.9.122 - - [13/Oct/2022:08:40:06 +0000] "OPTIONS /pets/getAgeGroup HTTP/1.1" 200 - "vhost.xxx" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36"
172.31.9.122 - - [13/Oct/2022:08:40:06 +0000] "OPTIONS /common/getAllCode HTTP/1.1" 200 - "vhost.xxx" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36"
172.31.9.122 - - [13/Oct/2022:08:40:06 +0000] "OPTIONS /dashboard HTTP/1.1" 200 - "vhost.xxx" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36"
172.31.9.122 - - [13/Oct/2022:08:40:06 +0000] "OPTIONS /dashboard/noticeCount HTTP/1.1" 200 - "vhost.xxx" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36"
172.31.9.122 - - [13/Oct/2022:08:40:06 +0000] "POST /common/getAllCode HTTP/1.1" 200 4212 "vhost.xxx" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36"
172.31.9.122 - - [13/Oct/2022:08:40:06 +0000] "GET /pets/getAgeGroup HTTP/1.1" 200 652 "vhost.xxx" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36"

I didn't get it what's wrong.

**Comment by allinurl** [comment]
How did you run goaccess? Simply using should work:

    goaccess access.log —log-format=COMBINED

**Comment by garion3024** [comment]
I try like this 

`/usr/local/bin/goaccess -f /var/log/httpd/access_log`

and select this 
** NCSA Combined Log Format with Virtual Host**

then I got this message
**Token '+0000]' doesn't match specifier '%h'   **

**Comment by garion3024** [comment]
I made mistake in my log! I found it.
Thank for your answer!
