### ISSUE TITLE
Parsing does not work

### ISSUE THREAD

**Issue by NikitaObukhov** [allinurl/goaccess#2399]
Log file:
"22/Sep/2022:07:00:38" 5.130.148.207 GET "GET /api/language_spokens HTTP/2.0" 

Formats:
--log-format='"%d:%t" %h' --date-format=%d/%b/%Y --time-format=%H:%M:%S

Output:
==1== Token for '%t' specifier is NULL.
==1==
==1== Format Errors - Verify your log/date/time format

**Comment by allinurl** [comment]
Please try the following and let me know how it goes. 
  
    goaccess access.log --log-format='"%d:%t" %h %^ “%r”' --date-format=%d/%b/%Y --time-format=%H:%M:%S
