### ISSUE TITLE
Debian/Ubuntu repository doesn't know utopic or vivid

### ISSUE THREAD

**Issue by ressu** [allinurl/goaccess#240]
The installation instructions refer to the release name with lsb_release. Ubuntu 14.10 which gets listed as Utopic receives 404 from the server, same goes for the soon to be released 15.04 (vivid).

Trusty packages work for Vivid, so quick workaround is to adjust the source line accordingly, but the either the server should be updated or installation instructions adjusted.

**Comment by allinurl** [comment]
Thanks for the heads up on this. Both releases have been added.
