### ISSUE TITLE
How should forwarded for parsing work?

### ISSUE THREAD

**Issue by bkosborne** [allinurl/goaccess#2401]
I'm confused on the expectations for parsing XFF headers.

Here's two sample log lines. The first column is the request IP. Then there is also the forwarded for IPs. Sometimes my server places the client IP in there as the only item. Other times it has other IPs, of which the right-most one is the real client IP.

I think the behavior I want is for goaccess to always look at the right-most IP in the XFF field and use that as the client IP. But can't figure it out.

```
1.1.1.1 - - [13/Oct/2022:18:13:24 +0000] "GET /news HTTP/1.1" 404 49781 "-" "Mozilla/5.0 (compatible; SemrushBot/7~bl; +http://www.semrush.com/bot.html)" vhost=obfuscated host=obfuscated hosting_site=obfuscated pid=2617 request_time=562626 forwarded_for="1.1.1.1" request_id="obfuscated" location="-" 

1.1.1.1 - - [13/Oct/2022:18:13:24 +0000] "GET /news HTTP/1.1" 404 49781 "-" "Mozilla/5.0 (compatible; SemrushBot/7~bl; +http://www.semrush.com/bot.html)" vhost=obfuscated host=obfuscated hosting_site=obfuscated pid=2617 request_time=562626 forwarded_for="3.3.3.3, 2.2.2.2" request_id="obfuscated" location="-" 
```

I've tried this, but it doesn't seem to do anything with the XFF data. Is there supposed to be a panel just for XFF?

```
goaccess access.log --log-format '%h %^ %^ [%d:%t %^] "%r" %s %b "%R" "%u" %^ %^ %^ %^ %^ forwarded_for="~h{, }"' --date-format "%d/%b/%Y" --time-format="%H:%M:%S"
```

**Comment by allinurl** [comment]
Not sure I understand, are you looking to get the client up? 

The general format shows the left-most being the original client ip. 

    X-Forwarded-For: client, proxy1, proxy2

**Comment by bkosborne** [comment]
Right, sorry, that's what I meant. But what I'm confused about is how goaccess parses and presents the XFF data? My log format has both the client IP and the XFF data in separate fields. Is it possible to for goaccess to parse the list of XFF IPs and present them?

**Comment by allinurl** [comment]
If you have both fields, you probably want to use the field that contains the client ip. Do you now which field has the client ip?

**Comment by bkosborne** [comment]
The XFF header will contain it, but it may not be trusted. But you're saying, I should really only tell goaccess to parse one or the other. Goaccess' is just trying to extract the client IP from XFF?

**Comment by allinurl** [comment]
That's correct.

**Comment by bkosborne** [comment]
Thank you
