### ISSUE TITLE
Realtime html does not work with docker-compose logs

### ISSUE THREAD

**Issue by NikitaObukhov** [allinurl/goaccess#2402]
docker-compose logs -f  --tail=100000 --no-log-prefix ssl | docker run -p 7890:7890 --rm -i -e LC_TIME="en_US.UTF-8" allinurl/goaccess -a -o html --log-format=COMBINDED --date-format=%d/%b/%Y --time-format=%H:%M:%S --real-time-html - > report.html

If I try docker-compose logs -f  --tail=100000 --no-log-prefix ssl 2>&1 > access.log and then tail this file - it  works. Seems like the problem is with docker-compose logs

The report is empty. Is it possible to track docker-compose logs with Goaccess? I also dont get why it uses websockets - what is port 7890 for? Who should connect it

**Comment by NikitaObukhov** [comment]
1 tried to redirect docker-compose logs -f ssl | tee /tmp/access.log
and then to run tail -f /tmp/access.log | docker run -p 7890:7890 --rm -i -e LC_TIME="en_US.UTF-8" allinurl/goaccess -a -o html --ws-url=ws://stage.joy-jet.com:7890 --real-time-html --date-format=%d/%b/%Y --time-format=%H:%M:%S - > report.html

The report is generated for only 10 rows from access.log file and newer gets updated. In the Network tools I see websocket connection is established but no messages are received. F5 does not help - I still see only 10 rows.

**Comment by allinurl** [comment]
Any updates on this?

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
