### ISSUE TITLE
exclude-ip not working with Caddy log

### ISSUE THREAD

**Issue by sol2070** [allinurl/goaccess#2403]
Hi, I'm using GoAccess on Ubuntu Server 20.04, and Caddy Server. 
The exclude-ip option seems not to be working with the caddy log. 
Without exclude-ip, everything is fine.
Thanks for this great software!

```
> goaccess /var/log/caddy/psp.log --log-format=CADDY -e --exclude-ip 168.205.14.242

GoAccess - version 1.6.4 - Sep 30 2022 23:35:22
Config file: /etc/goaccess/goaccess.conf

Fatal error has occurred
Error occurred at: src/parser.c - read_log - 2065
Unable to open the specified log file '168.205.14.242'. No such file or directory

```

**Comment by allinurl** [comment]
Thanks. It looks like you are passing -e and —exclude-ip at the same time. Try removing -e and let me know if that works.

**Comment by sol2070** [comment]
> Thanks. It looks like you are passing -e and —exclude-ip at the same time. Try removing -e and let me know if that works.

Oh, yes, it works. I did that before, but as I was trying with an IP range, I didn't notice that the problem was with that range. With a single IP it works. Thank you!

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
