### ISSUE TITLE
custom nginx json format support?

### ISSUE THREAD

**Issue by Colt-crypto** [allinurl/goaccess#2404]
Hi, 
I'm trying to process an access log in the following format:

log_format json 
    '{"time":"$time_iso8601",'
    '"remote_addr":"$remote_addr",'
    '"http_x_forwarded_for":"$http_x_forwarded_for",'
    '"request_method":"$request_method",'
    '"server_protocol":"$server_protocol",'
    '"request_uri":"$request_uri",'
    '"status":$status,'
    '"request_length":$request_length,'
    '"request_time":$request_time,'
    '"body_bytes_sent":$body_bytes_sent,'
    '"bytes_sent":$bytes_sent,'
    '"http_referrer":"$http_referer",'
    '"http_user_agent":"$http_user_agent"}';
    
   Is there a guide somewhere on how to process the input format for custom logs?
   
   Thank you!

**Comment by allinurl** [comment]
Please take a look at this post for more [**details**](https://github.com/allinurl/goaccess/issues/1768#issuecomment-755792463). Otherwise, feel free to post a few lines from your access log and I can take a look.

**Comment by Colt-crypto** [comment]
Thank you for replying, much appreciated.

I think i'm just struggling to get the correct configuration.
Here's a snippet of the log I'm trying to parse, thanks again.

`{"time":"2022-09-27T06:18:57+00:00","remote_addr":"172.31.68.234","http_x_forwarded_for":"206.81.7.133, 172.70.114.69","request_method":"GET","server_protocol":"HTTP/1.1","request_uri":"/leafmailer2.8.php","status":403,"request_length":794,"request_time":0.000,"body_bytes_sent":192,"bytes_sent":394,"http_referrer":"-","http_user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36"}
{"time":"2022-09-27T06:18:58+00:00","remote_addr":"172.31.68.234","http_x_forwarded_for":"206.81.7.133, 172.70.114.69","request_method":"GET","server_protocol":"HTTP/1.1","request_uri":"/mailer.php","status":403,"request_length":787,"request_time":0.000,"body_bytes_sent":192,"bytes_sent":394,"http_referrer":"-","http_user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36"}
{"time":"2022-09-27T06:18:58+00:00","remote_addr":"172.31.68.234","http_x_forwarded_for":"206.81.7.133, 172.70.114.69","request_method":"GET","server_protocol":"HTTP/1.1","request_uri":"/1.php","status":403,"request_length":782,"request_time":0.000,"body_bytes_sent":192,"bytes_sent":394,"http_referrer":"-","http_user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36"}
{"time":"2022-09-27T06:18:59+00:00","remote_addr":"172.31.68.234","http_x_forwarded_for":"206.81.7.133, 172.70.114.69","request_method":"GET","server_protocol":"HTTP/1.1","request_uri":"/k.php","status":403,"request_length":782,"request_time":0.000,"body_bytes_sent":192,"bytes_sent":394,"http_referrer":"-","http_user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36"}`

**Comment by allinurl** [comment]
Sorry for the delay. This should do it:

    goaccess access.log --log-format='{ "time": "%dT%t+%^", "http_x_forwarded_for": "%h,%^", "request_method": "%m", "request_uri": "%U", "server_protocol": "%H", "status": "%s", "request_length": "%b", "request_time": "%T", "http_referrer": "%R", "http_user_agent": "%u" }' --date-format='%Y-%m-%d' --time-format=%T

**Comment by Colt-crypto** [comment]
Thanks again! much appreciated
