### ISSUE TITLE
Use X-Forwarded-For for geo location

### ISSUE THREAD

**Issue by elya5** [allinurl/goaccess#2408]
Hi

is it possible to tell goaccess to use `x-forwarded-for` field for geo location?  Otherwise, it shows the location of the reverse proxy.

I'm using goaccess 1.6 in combination with caddy. This is the current call: 

    goaccess /var/log/caddy/caddy.log --log-format=CADDY \
                                      --ignore-panel=NOT_FOUND  \
                                      --ignore-panel=REFERRING_SITES \
                                      --ignore-panel=MIME_TYPE \
                                      --ignore-panel=TLS_TYPE \
                                      --ignore-panel=STATUS_CODES \
                                      --ignore-panel=HOSTS \
                                      --ignore-panel=VIRTUAL_HOSTS \
                                      -o /var/www/site/stats.html \
                                      --geoip-database /tmp/dbip-city-lite-2022-10.mmdb

**Comment by allinurl** [comment]
Do you have access to the client ip through the XFF field?

**Comment by elya5** [comment]
Yes, that's what I meant. Client IP is in XFF and not in "remote_ip" field of caddy logs.

**Comment by allinurl** [comment]
You should be able to use a custom format with XFF. Please take a look at [**this post**](https://github.com/allinurl/goaccess/issues/2404#issuecomment-1299396352).

**Comment by elya5** [comment]
Thanks, that works :)

For anyone else stumbling over this: In the log-format `"remote_ip":"%h"` needs to be replaced with `"X-Forwarded-For":"%h"`
