### ISSUE TITLE
Parsing does not work

### ISSUE THREAD

**Issue by Paulpatou** [allinurl/goaccess#2409]
Hello,
Sorry to ask this question for the umpteenth time but I can't find a solution for apache log parsing

```
==1== Token '127.0.1.1:443' doesn't match specifier '%h'
==1== Token '127.0.1.1:443' doesn't match specifier '%h'
==1== Token '127.0.1.1:443' doesn't match specifier '%h'
==1== Token '127.0.1.1:443' doesn't match specifier '%h'
==1== Token '127.0.1.1:443' doesn't match specifier '%h'
==1== Token '127.0.1.1:443' doesn't match specifier '%h'
==1== Token '127.0.1.1:443' doesn't match specifier '%h'
==1== Token '127.0.1.1:443' doesn't match specifier '%h'
==1== Token '127.0.1.1:443' doesn't match specifier '%h'
==1== Token '127.0.1.1:443' doesn't match specifier '%h'
```

>127.0.1.1:443 192.168.20.101 - - [18/Oct/2022:09:29:43 +0600] "GET / HTTP/1.1" 302 3783 "-" "Uptime-Kuma/1.11.4"
127.0.1.1:443 192.168.20.101 - - [18/Oct/2022:09:29:43 +0600] "GET /ACC/login HTTP/1.1" 200 6558 "-" "Uptime-Kuma/1.11.4"
127.0.1.1:443 172.30.110.52 - - [18/Oct/2022:09:29:44 +0600] "GET / HTTP/1.1" 302 1541 "-" "Uptime-Kuma/1.11.4"

Thank you for your time

**Comment by kareemmahgoub** [comment]
I think you are having virtualhost variable in your log file "127.0.1.1:443". Try using VCOMBINED in goccess.conf

**Comment by allinurl** [comment]
Sorry for the delay. This should do it.

    goaccess access.log --log-format='%^ %h %^[%x] "%r" %s %b "%R" "%u"' --datetime-format='%d/%b/%Y:%H:%M:%S %z' --tz=Asia/Dhaka
