### ISSUE TITLE
Token 'H' doesn't match specifier '%d'

### ISSUE THREAD

**Issue by adpur** [allinurl/goaccess#2413]
I have several logs being already monitored, however, these logs are being a pain...I'm sure it's something simple.

time-format %H:%M:%S
date-format %d/%b/%Y

log-format %h %^ %^ [%d:%t %^] "%r" %s %b

Log format:
123.128.123.123 - - [26/Jul/2019:20:26:54 -0700] "GET /profile/upload/server/php/ HTTP/1.1" 404 224
204.200.150.25 - - [26/Jul/2019:20:28:34 -0700] "GET /robots.txt HTTP/1.0" 404 208

**Comment by allinurl** [comment]
The common log format should it:

    goaccess access.log --log-format=COMMON

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
