### ISSUE TITLE
Token '09/Jan/2001' doesn't match specifier '%d'

### ISSUE THREAD

**Issue by flashlabs** [allinurl/goaccess#2415]
Hi,

Date format is `%d/%b/%Y` and still getting error `Token '09/Jan/2001' doesn't match specifier '%d'`

Any suggestions what should be the right full log format with dates and times? 🤔 

I'm running app with defaults `goaccess access.log` and then choosing `NCSA Combined Log Format` with defaults:
- `log format` - `%h %^[%d:%t %^] "%r" %s %b "%R" "%u"`
- `date format` - `%d/%b/%Y`
- `time format` - `%H:%M:%S`

Sample log lines:

```
10.0.0.0 - - [09/Jan/2001:00:07:51 +0000] "GET /healthy HTTP/1.1" 418 0 "-" "ELB-HealthChecker/2.0"
10.0.0.0 - - [09/Jan/2001:00:08:02 +0000] "GET /healthy HTTP/1.1" 418 0 "-" "ELB-HealthChecker/2.0"
```

Looks like Combined Log Format, but the `%h %^[%d:%t %^] "%r" %s %b "%R" "%u"` doesn't work 😞 

Any suggestions? 🙏

**Comment by flashlabs** [comment]
Ofc you are right and both of your solutions work!

**Comment by allinurl** [comment]
Glad that solved the issue :) Feel free to reopen it as needed.

**Comment by woodgear** [comment]
seems stil not work for me.
cmd
```
LANG="en_US.UTF-8" bash -c 'goaccess  ./ac.log  -o ./report.html -p ./goaccess.conf'
```
goaccess.conf
```
time-format %T
date-format %d/%b/%Y
log_format [%d/%t %^] %h "%v" "%r"  %s %^ %^  "%u" "%^"  %T %^;
```
ac.log
```
[09/Jan/2023:05:00:09 +0000] 10.0.20.25 "ipaas-esb.sany.com.cn" "POST / HTTP/1.1" 200 200 10.125.53.68:11000 "Apache-HttpClient/4.5.6 (Java/1.8.0_191)" "10.95.10.194" 0.109 0.109
```
error
```
 [PARSING ./ac.log] {0} @ {0/s}
Cleaning up resources...
==3211559== GoAccess - version 1.7 - Jan 10 2023 23:51:30
==3211559== Config file: ./goaccess.conf
==3211559== https://goaccess.io - <hello@goaccess.io>
==3211559== Released under the MIT License.
==3211559==
==3211559== FILE: ./ac.log
==3211559== Parsed 1 lines producing the following errors:
==3211559==
==3211559== Token '09' doesn't match specifier '%d'
==3211559==
==3211559== Format Errors - Verify your log/date/time format
```
i find that is very hard to map/debug the logformat issue,maybe we need more verbose log and more manual...
