### ISSUE TITLE
Token '-' doesn't match specifier '%s'

### ISSUE THREAD

**Issue by dolomiti70** [allinurl/goaccess#2416]
The following error occurs:

/opt/log/proxy-host-4_access.log
Parsed 1 lines producing the following errors:
Token '-' doesn't match specifier '%s'
Format Errors - Verify your log/date/time format

My goacces.conf:

```
time-format %T
date-format %d/%b/%Y
log_format [%d:%t %^] - %s %^ -  %m %^ %v "%U" [Client %h] [Length %b] [Gzip %^] [Sent-to %^] "%u" "%R"
real-time-html true
log-file /opt/log/proxy-host-1_access.log
log-file /opt/log/proxy-host-2_access.log
log-file /opt/log/proxy-host-3_access.log
log-file /opt/log/proxy-host-4_access.log
```

My Log-File:

[13/Nov/2022:12:59:56 +0000] - 304 304 - GET https eins.mydomain.com "/static/js/7228.c717640d.chunk.js" [Client 12.34.56.78] [Length 0] [Gzip -] [Sent-to 192.168.1.123] "Mozilla/5.0 (Linux; Android 13; SM-G930F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Mobile Safari/537.36" "https://eins.mydomain.com/"

**Comment by allinurl** [comment]
Please try:

    goaccess access.log --log-format='[%d:%t %^] %^ %s %^ %^ %m %^ %v "%U" [%^ %h] [%^ %b] [%^] %^"%u" "%R"' --date-format=%d/%b/%Y --time-format=%T --http-protocol=no

**Comment by dolomiti70** [comment]
Thanks for your support but this doesn´t work for me too. The following works:
``
log_format [%d:%t %^] - %^ %s - %m %^ %v "%U" [Client %h] [Length %b] [Gzip %^] [Sent-to %^] "%u" "%R"
``
I changed %^ and %s after the first -

For me this issue can be closed

**Comment by allinurl** [comment]
Make sure you're using the latest version. With the line you posted and the format I posted, it should work. e.g.,

![2022-11-13-113637_481x975_scrot](https://user-images.githubusercontent.com/5005367/201535852-aa69ddfb-22c3-45ac-a248-dbf574da9561.png)

Closing this. Feel free to reopen it if needed.
