### ISSUE TITLE
How to change JSON access logs logformat to goaccess logformat

### ISSUE THREAD

**Issue by kchusak** [allinurl/goaccess#2418]
log_format main                            
'{"timestamp":"$time_iso8601",
  "remote_addr":"$remote_addr",
  "body_bytes_sent":"$body_bytes_sent",
  "bytes_sent":"$bytes_sent",
  "connection":"$connection",
  "connection_requests":"$connection_requests",
  "msec":"$msec",
  "request":"$request",
  "status":"$status",
  "scheme":"$scheme",
  "request_length":"$request_length",
  "request_time":"$request_time",
  "request_method":"$request_method",
  "request_uri":"$request_uri",
  "server_name":"$server_name",
  "server_port":"$server_port",
  "server_protocol":"$server_protocol",
  "http_x_forwarded_for":"$http_x_forwarded_for",
  "http_referrer":"$http_referer",
  "http_user_agent":"$http_user_agent"}';

log_format main '{"timestamp":"$time_iso8601","remote_addr":"$remote_addr","body_bytes_sent":"$body_bytes_sent","bytes_sent":"$bytes_sent","connection":"$connection","connection_requests":"$connection_requests","msec":"$msec","request":"$request","status":"$status","scheme":"$scheme","request_length":"$request_length","request_time":"$request_time","request_method":"$request_method","request_uri":"$request_uri","server_name":"$server_name","server_port":"$server_port","server_protocol":"$server_protocol","http_x_forwarded_for":"$http_x_forwarded_for","http_referrer":"$http_referer","http_user_agent":"$http_user_agent"}';

{"timestamp":"2022-11-14T08:35:11+07:00","remote_addr":"161.200.133.165","body_bytes_sent":"29815","bytes_sent":"30025","connection":"10220223","connection_requests":"6","msec":"1668389711.031","request":"GET /ChulaApp/servlet/studentRequestDocument.servlet.AdminRequestDocInquiryServlet?purpose=print&fromJSP=AdminRequestInquiry2 HTTP/1.1","status":"200","scheme":"https","request_length":"1393","request_time":"0.905","request_method":"GET","request_uri":"/ChulaApp/servlet/studentRequestDocument.servlet.AdminRequestDocInquiryServlet?purpose=print&fromJSP=AdminRequestInquiry2","server_name":"www5.reg.chula.ac.th","server_port":"443","server_protocol":"HTTP/1.1","http_x_forwarded_for":"-","http_referrer":"https://www5.reg.chula.ac.th/ChulaApp/servlet/studentRequestDocument.servlet.AdminRequestDocInquiryServlet","http_user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36"}

**Comment by kchusak** [comment]
Goaccess 
log_format
{"timestamp":"%dT%t+%^", "remote_addr":"%h", "body_bytes_sent":"%^", "bytes_sent":"%^", "connection":"%^", "connection_requests":"%^", "msec":"%^", "request":"%^", "status":"%s", "scheme":"%^", "request_length":"%^", "request_time":"%T", "request_method":"%m", "request_uri":"%^", "server_name":"%^", "server_port":"%^", "server_protocol":"%^", "http_x_forwarded_for":"%^", "http_referrer":"%R", "http_user_agent":"%u"}
Error : 
goaccess: unrecognized option '--{"timestamp":"%dT%t+%^",'

**Comment by kchusak** [comment]
Format Errors - Verify your log/date/time format

**Comment by kchusak** [comment]
# goaccess /var/log/nginx/access.log  -o /var/www/html/report.html --log-format=CADDY
 [PARSING /var/log/nginx/access.log] {0} @ {0/s}
Cleaning up resources...
==22330== GoAccess - version 1.6.5 - Nov  1 2022 00:23:25
==22330== Config file: /etc/goaccess/goaccess.conf
==22330== https://goaccess.io - <hello@goaccess.io>
==22330== Released under the MIT License.
==22330==
==22330== FILE: /var/log/nginx/access.log
==22330== Parsed 10 lines producing the following errors:
==22330==
==22330== IPv4/6 is required.
==22330== IPv4/6 is required.
==22330== IPv4/6 is required.
==22330== IPv4/6 is required.
==22330== IPv4/6 is required.
==22330== IPv4/6 is required.
==22330== IPv4/6 is required.
==22330== IPv4/6 is required.
==22330== IPv4/6 is required.
==22330== IPv4/6 is required.
==22330==
==22330== Format Errors - Verify your log/date/time format

**Comment by allinurl** [comment]
This should do it:

    goaccess access.log --log-format='{ "timestamp": "%dT%t+%^", "remote_addr": "%h", "bytes_sent": "%b", "request": "%r", "status": "%s", "request_time": "%T", "server_name": "%v", "http_referrer": "%R", "http_user_agent": "%u" }' --date-format=%Y-%m-%d --time-format=%T

**Comment by kchusak** [comment]
thank you

Chusak Kongmanee
Director of Information Technology Department
Office of the Registrar
Chulalongkorn University
To. +662-2180018-9<tel:+662-2180018-9>
Fax. +662-2180003<tel:+662-2180003>
Mob. +668-89614987<tel:+668-89614987>
________________________________
จาก: Gerardo O. ***@***.***>
ส่ง: Tuesday, November 15, 2022 9:06:19 PM
ถึง: allinurl/goaccess ***@***.***>
สำเนาถึง: Chusak Kongmanee ***@***.***>; Author ***@***.***>
ชื่อเรื่อง: Re: [allinurl/goaccess] How to change access logs logformat to goaccess logformat (Issue #2418)


This should do it:

goaccess access.log --log-format='{ "timestamp": "%dT%t+%^", "remote_addr": "%h", "bytes_sent": "%b", "request": "%r", "status": "%s", "request_time": "%T", "server_name": "%v", "http_referrer": "%R", "http_user_agent": "%u" }' --date-format=%Y-%m-%d --time-format=%T
