### ISSUE TITLE
Parse custom header containing mobile app version

### ISSUE THREAD

**Issue by dafi** [allinurl/goaccess#2419]
My access.log contains logs in the following format

`127.0.0.1 - - [15/Nov/2022:07:57:31 +0100] "OPTIONS /myurl/lvl1/svc?aa=2022&l=EN HTTP/1.1" 200 150 "https://localhost/" "Mozilla/5.0 (Linux; Android 12; SM-A225F Build/SP1A.210812.016; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/107.0.5304.105 Mobile Safari/537.36 ZKL-v6.4.1-25"`

This is identical to the COMBINED log format but at the end it contains the app version `ZKL-v6.4.1-25`.
I want to generate the reporting containing also this information.

Is this possible?
I tried different log formats without success, I don't paste them here because they generate errors on invalid formats

**Comment by allinurl** [comment]
You'd need some pre-processing, please try this and let me know how it goes:

    awk 'NF>1{print $0" " substr($NF, 1, length($NF)-1)}' log | goaccess - --log-format='%h %^[%d:%t %^] "%r" %s %b "%R" "%u" %v' --date-format=%d/%b/%Y --time-format=%T

![2022-11-17-205602_400x716_scrot](https://user-images.githubusercontent.com/5005367/202606448-8dc24961-98b8-47d9-b4d6-49d4079f2b72.png)

**Comment by dafi** [comment]
> You'd need some pre-processing, please try this and let me know how it goes:
> 
> ```
> awk 'NF>1{print $0" " substr($NF, 1, length($NF)-1)}' access.log | goaccess - --log-format='%h %^[%d:%t %^] "%r" %s %b "%R" "%u" %v' --date-format=%d/%b/%Y --time-format=%T
> ```
> 

Simply awesome!!!
Below the results from the last production log, thank you very much!!!

![goaccess-version](https://user-images.githubusercontent.com/84500/202638204-3d9564ee-b582-4560-bf6a-912f315fef2c.png)

**Comment by allinurl** [comment]
Glad that worked. With a minor tweak, you could filter out those that do not start with "ZKLv". 

Anyways closing this, feel free to reopen it if needed. #117 would probably help with this. Stay tuned!
