### ISSUE TITLE
Custom log format does not parse right

### ISSUE THREAD

**Issue by AWildColin** [allinurl/goaccess#242]
I'm parsing a Tomcat type access log where individual hits look something like the following:

    100.37.29.32 - connector-5346 _100_1 [27/Apr/2015:00:00:07 -0400] "POST /webapps/portal/execute/tabs/tabAction HTTP/1.1" 200 3488 "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.90 Safari/537.36" 6A20C51EA5016D5310F41B74811984E9 0.180 180 3488

Originally, I created the following log-format to parse this:

    log-format %h %^ %^ %^ [%d:%t %^] "%m %r" %s %b "%u" %^ %T %D %^ 

However, I noticed that the "Time served" value for individual hits wasn't being populated correctly. The values were all 0.00 us. Eventually, I was able to fix this by not parsing request times in seconds and replacing that identifier with %^ to ignore the value.

Another bug I observed is that in this format, the object size is listed twice -- between the HTTP status code and user agent string and again at the end of the line. Leaving the %b identifier where it is properly populates the bandwidth value when applicable. However, if I try parsing the object size at the end of the line (e.g. log-format %h %^ %^ %^ [%d:%t %^] "%m %r" %s %^ "%u" %^ %T %D %b), the bandwidth value does not populate correct and everything is 0.00 bytes.

To best parse this log format, I ended up with the following:
    log-format %h %^ %^ %^ [%d:%t %^] "%m %r %H" %s %b "%u" %^ %^ %D %^

To be clear, I'm not presently encountering an issue and I'm simply reporting unexpected behavior when trying to create a custom log format.

**Comment by allinurl** [comment]
Thanks for reporting this! It appears that when both identifies are used  `%T %D` the time served and the bandwidth (in the case of `%T %D %b`) are set to 0. Using only one of them fixes these issues. I'll have a fix for this soon.

**Comment by allinurl** [comment]
This has been fixed. It should now handle cases where `%T %D` appear on the log-format. It will give priority to the one is listed first. Feel free to build from [dev](http://goaccess.io/download#build), otherwise, it will be pushed out in the upcoming release. Thanks again!
