### ISSUE TITLE
Viewing each visit's timestamp?

### ISSUE THREAD

**Issue by figamore** [allinurl/goaccess#2420]
Hello, is there any option to enable a timestamp next to each visitor's visit?

If not, could you point me to which part of the parser/display files need be modified in order to add this functionality?

**Comment by figamore** [comment]
> Not sure I follow, how are you expecting the report to look like? Thanks

For example, under the Visitor Hostnames and IPs table, for each row, it would be helpful to have the visit timestamps next to each IP, or perhaps an expandable dropdown for each row so that I could see all the different times a certain IP made a hit on the server.

Thanks!

**Comment by allinurl** [comment]
Got it. Thanks for the suggestion. **#117** should address this in a much cleaner way. Stay [tuned](https://twitter.com/goaccess?lang=en) as I'm working on it as we speak.

**Comment by allinurl** [comment]
Closing this as it is a dup. [**Stay tuned**](https://twitter.com/goaccess) for this feature coming soon.
