### ISSUE TITLE
Release file can't be found for Ubuntu 22.10

### ISSUE THREAD

**Issue by xorinzor** [allinurl/goaccess#2421]
Following the steps [described here](https://goaccess.io/download#official-repo) results in: 

![image](https://user-images.githubusercontent.com/4212335/203740265-42f4e7bb-c20d-41ef-9a09-025dc0ac4ced.png)

**Comment by allinurl** [comment]
Please try apt update / install again and let me know how it goes. I completely missed it. Thanks a lot for letting me know!

**Comment by xorinzor** [comment]
Yep, works now, thanks :)
