### ISSUE TITLE
Outdated debian repository

### ISSUE THREAD

**Issue by tobias992** [allinurl/goaccess#2423]
The debian repository (https://deb.goaccess.io/ $(lsb_release -cs) main) is very outdated, there is a plan to update? Otherwise i have to update my scripts to compile by myself.

**Comment by allinurl** [comment]
The official deb repo has the latest version, as of this post, v1.6.5. Are you seeing something else?

**Comment by tobias992** [comment]
I have 2 complete updated debian bullseye servers. One have 1.5.3 and the other one 1.5.6 - no updates available.

**Comment by allinurl** [comment]
Glad that worked. Thanks for sharing those findings!
