### ISSUE TITLE
Need help with log format [uwsgi]

### ISSUE THREAD

**Issue by amiguet** [allinurl/goaccess#2424]
Hello,

I'm trying to analyze a uwsgi log file.

Goaccess' log format is quite cryptic... could anybody help me get the right formats for this file? I'd be very grateful!

I tried the formats suggested in #386, but at least the dates are completely wrong.

Here are a couple of lines from the file:

```
[pid: 3492075|app: 0|req: 4282/169885] 54.36.148.22 () {38 vars in 549 bytes} [Mon Nov 28 06:41:16 2022] GET /actus/61476774cb7d6ede781a9b4a => generated 15747 bytes in 24 msecs (HTTP/2.0 200) 2 headers in 82 bytes (1 switches on core 0)
[pid: 3492075|app: 0|req: 4283/169886] 54.36.148.231 () {38 vars in 709 bytes} [Mon Nov 28 06:41:25 2022] GET /resize/uploaded/pictures/4b8ea68f9f6a44c882b7fe0a9e75e621.jpg?v=YUdm_A&w=1024&s=b'Qut9-GQTlTM55BX1xNnZKrGqskA' => generated 122538 bytes in 9 msecs via sendfile() (HTTP/2.0 200) 6 headers in 242 bytes (0 switches on core 0)
[pid: 3492075|app: 0|req: 4284/169887] 185.191.171.21 () {40 vars in 539 bytes} [Mon Nov 28 06:43:31 2022] GET /robots.txt => generated 12511 bytes in 1 msecs (HTTP/1.1 404) 2 headers in 89 bytes (1 switches on core 0)
[pid: 3492075|app: 0|req: 4285/169888] 185.191.171.21 () {40 vars in 677 bytes} [Mon Nov 28 06:43:31 2022] GET /agenda/61b1e344f02ed2de108bc54a => generated 238040 bytes in 206 msecs (HTTP/1.1 200) 2 headers in 83 bytes (2 switches on core 0)
```

**Comment by allinurl** [comment]
Sorry for the delay. This should do it:

    goaccess access.log --log-format='%^] %h %^[%x] %m %U %^(%H %s) %^' --datetime-format='%a %b %d %H:%M:%S %Y' --date-spec=min --ignore-panel=OS --ignore-panel=BROWSERS --ignore-panel=REFERRING_SITES

**Comment by amiguet** [comment]
That seems to work, many thanks! :-)

I had to prefix the command with

```
LANG="en_US.UTF-8"
```

as suggested in #2415 because my local locale (!) doesn't match the locale of the log file.

But other than that it works great. Thanks!

**Comment by allinurl** [comment]
Glad to hear you got it working!
