### ISSUE TITLE
About SPECIFIERS in Custom log 

### ISSUE THREAD

**Issue by mahdiinejatii** [allinurl/goaccess#2429]
Hi
I have 2 questions about that https://goaccess.io/man#custom-log

1. Should all the following 3 fields be used in one command?

‍GoAccess requires the following fields:

a valid IPv4/6 %h
a valid date %d
the request %r

I saw in some links that all 3 did not come in one order, But it is required in the document.

2. Is there any use of duplicate SPECIFIERS in the command?
When we have two parameters with a byte value, Or we have 3 different durations

we can use commands like this?

`goaccess access.log --log-format='{ "time": "%dT%t+%^",  "byte_out": "%b",  "byte_in": "%b", "delivery_duration": "%L", "connection_duration": "%L", "total_duration": "%L"  }' --date-format='%Y-%m-%d' --time-format=%T`

thanks

**Comment by allinurl** [comment]
Hi, regarding your questions.

1. Yes, those fields are required.
2. You can use a specifier multiple times, however, only the last one will prevail.

**Comment by mahdiinejatii** [comment]
about question two:
it's that mean only the last one will be analyzed and shown on the output?  
and others have no effect on output? 

if send or show one example will be great.

**Comment by allinurl** [comment]
That's correct. I'd not use the same specifier multiple times, thus I don't have an example to show. Please pair a field with only one specifier.

**Comment by mahdiinejatii** [comment]
Thanks
