### ISSUE TITLE
Missing development files for the GeoIP library

### ISSUE THREAD

**Issue by derekzhan** [allinurl/goaccess#243]
My os is centos 6 , occer follow errors when i run " ./configure --enable-geoip --enable-utf8" command.

[root@localhost goaccess-0.9]# ./configure --enable-geoip --enable-utf8
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking whether gcc and cc understand -c and -o together... yes
checking for pthread_create in -lpthread... yes
checking for GeoIP_new in -lGeoIP... no
### configure: error: *** Missing development files for the GeoIP library

**Comment by allinurl** [comment]
You probably need to get them from EPEL. This may help: [geoip-devel](http://serverfault.com/questions/372978/installing-geoip-on-centos).

**Comment by derekzhan** [comment]
thxs . resolved

**Comment by lokeshsoni24** [comment]
Install the epel.
yum install ncurses*

This way I resolved issue

**Comment by katapofatico** [comment]
on Ubuntu: `sudo apt-get install libgeoip-dev`

**Comment by bvbmedia** [comment]
For CentOS 6 run:
yum -y install geoip geoip-devel
