### ISSUE TITLE
not able to Parse Custom Formated logs

### ISSUE THREAD

**Issue by h4hardik** [allinurl/goaccess#2431]
Hello, I have custom created a log. I tried all the methods mentioned, but I always get the error: 

**==1967309== Format Errors - Verify your log/date/time format**

my custom pattern : `[%{u}t] [%-m:%l] [pid %P:tid %T] %7F: %E: [client\ %a] %M% ,\ host\ %{Host}i`

command I tried :` goaccess --log-format='[%{u}t] [%-m:%l] [pid %P:tid] %7F: %E: [client\ %a],\ host\ %{Host}' --date-format=%{u}t --time-format=%{u}t error.log --no-ip-validation`

My log file:

`[Wed Dec 14 08:36:48.672072 2022] [php:error] [pid 3081375:tid [client 2600:1004:b0ae:a937:5540:eba0:2d7:1f3e:0] PHP Fatal error:  Uncaught TypeError: implode(): Argument #2 ($array) must be of type ?array, string given in admin.php on line 86, host www.mywebsite.com`

**Comment by allinurl** [comment]
Please note that goaccess peforms well on access logs. Though, you **may** be able to parse some of the error logs. Can you please post a few more lines, I'm curious if all those lines have the same format...

**Comment by h4hardik** [comment]
Thanks @allinurl  , here the more lines

`[Wed Dec 14 08:36:48.672072 2022] [php:error] [pid 3081375:tid [client 204.148.84.42] PHP Fatal error:  Uncaught TypeError: implode(): Argument #2 ($array) must be of type ?array, string given in /var/www/sites/mysite/wp-content/plugins/admin/admin.php:86\nStack trace:\n#0 /var/www/sites/mysite/wp-content/plugins/admin/admin.php(86): content/plugins/admin/admin.php on line 86, host www.newsite.com`

`[Thu Dec 15 06:52:32.249941 2022] [php:error] [pid 4009945:tid [client 136.243.220.213:0] PHP Fatal error:  Uncaught TypeError: call_user_func_array(): Argument #1 ($callback) must be a valid callback, non-static method WP_Feed_Cache::create() cannot be called statically in /var/www/sites/projectx/html/wp-includes/SimplePie/Registry.php:215\nStack trace:\n#0 /var/www/sites/projectx/html/wp-includes/class-simplepie.php(1466): SimplePie_Registry->call('Cache', 'get_handler', Array)\n#n line 215, host www.abc-site.com`

`[Thu Dec 15 07:51:12.971805 2022] [php:error] [pid 4044742:tid [client 157.55.39.28:0] PHP Fatal error:  Uncaught TypeError: array_multisort(): Argument #1 ($array) must be an array or a sort flag in /var/www/sites/px/wp-content/plugins/mh-review-our-firm/mh-review-our-firm.php:492\n, host www.mytteamsite.com`

**Comment by allinurl** [comment]
Please try this (note that it will only work with your last two lines since there's no consistency on the IP and what appears to be a :0 port):

    goaccess error.log --log-format='[%d %t.%^] [%e] [%^[%^ %h:0] %v: %U\\n' --date-format='%a %b %d' --time-format=%T --http-protocol=no --http-method=no --ignore-panel=OS --ignore-panel=BROWSERS --ignore-panel=REFERRING_SITES --ignore-panel=REQUESTS_STATIC --ignore-panel=NOT_FOUND --ignore-panel=STATUS_CODES --date-spec=min --hour-spec=min

Should output something like:

![2022-12-17-215445_655x939_scrot](https://user-images.githubusercontent.com/5005367/208280515-bb3445b9-0a56-4087-b888-a46b7acb5997.png)

**Comment by allinurl** [comment]
@Daniel-Peder This should do it:

    goaccess access.log --log-format='%v %^ %h %^ %^ %d %t %D "%r" %s %b "%R" "%u"' --date-format=%Y-%m-%d --time-format=%T

**Comment by Daniel-Peder** [comment]
@allinurl thanks, it helped

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.

**Comment by h4hardik** [comment]
Thanks @allinurl  , Its really helps lots
