### ISSUE TITLE
Problem when running goaccess with cron

### ISSUE THREAD

**Issue by breck7** [allinurl/goaccess#2432]
I have the following script `updateStats.sh` that works great when I run it manually but fails when run on Ubuntu via cron with `0 * * * * /var/www/html/updateStats.sh`

`cat updateStats.sh`:

```
goaccess /var/log/nginx/access.log -o /var/www/html/nginxDaily.html --log-format=COMBINED --anonymize-ip
zcat -f /var/log/nginx/access.log* | goaccess -o /var/www/html/nginxDailyAll.html --log-format=COMBINED --anonymize-ip
```

`cat cron.log` provides:

```
 [PARSING /var/log/nginx/access.log] {4907} @ {0/s}
Cleaning up resources...

GoAccess - version 1.5.5 - Feb  5 2022 18:37:15
Config file: /etc/goaccess/goaccess.conf

Fatal error has occurred
Error occurred at: src/goaccess.c - initializer - 1457
No input data was provided nor there's data to restore.
```

The first line runs fine. The second line fails.

Any ideas what I'm doing wrong?

**Comment by allinurl** [comment]
Great question. When piping data to goaccess via the cron or pretty much anytime you pipe data in, you will need to add a dash. e.g., 

    zcat -f /var/log/nginx/access.log* | goaccess - -o /var/www/html/nginxDailyAll.html --log-format=COMBINED --anonymize-ip

Let me know if that helps.

**Comment by breck7** [comment]
@allinurl that seemed to work! Thanks so much!

**Comment by allinurl** [comment]
Glad that worked :)

**Comment by StefanSchubert** [comment]
Hi - just run into it and was almost before opening an issue for it. Glad to found the solution among the closed ones. (Can confirm it, too). The behavior though seems strange, if the single ssh command works but not while executed during cron....hm for better understanding can someone explain what is happening here? 

Anyway THX for the solution :-)

**Comment by allinurl** [comment]
@StefanSchubert cron doesn't give a TTY so [`isatty(3)`](https://man7.org/linux/man-pages/man3/isatty.3.html) fails when no filename is passed and thus it won't output a report. A single dash (`-`), with no option, [usually means "read from standard input"](https://unix.stackexchange.com/q/16357/22222). This is a very common convention used by many programs. Hope that helps clarify this.

**Comment by StefanSchubert** [comment]
@allinurl Did it! Thanks for the explanation - I learned something new by it!

**Comment by DasMuelli** [comment]
great explanation. It solves my issues. :-)
