### ISSUE TITLE
GoAccess Html contents are not loading properly

### ISSUE THREAD

**Issue by rexdivakar** [allinurl/goaccess#2433]
![image](https://user-images.githubusercontent.com/15235122/208002326-906f7432-fc67-4ab4-ba5b-a74073d511c1.png)

Html icon assets are not loading properly, kindly help

**Comment by allinurl** [comment]
Are you using the latest version? If yes, what's the output from your browser's console (Ctrl+shift+j)? Thanks

**Comment by rexdivakar** [comment]
ok let me check meanwhile, I'm using nginx so do u have any article on enabling a reverse proxy for goaccess webpage ?

**Comment by allinurl** [comment]
[One more](https://github.com/allinurl/goaccess/issues/1405).

As far as reverse proxy, I'd do a search on the list of issues. It's been asked a few times. e.g., [here](https://github.com/allinurl/goaccess/issues/1280#issuecomment-555447978)

**Comment by allinurl** [comment]
Any updates on this? Thanks

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
