### ISSUE TITLE
Custom log format help - strip URL parameters

### ISSUE THREAD

**Issue by ad5030** [allinurl/goaccess#2434]
Hi,
my $request is _"GET /pix.png?url=/blog/it/2020-04-18-tips-disabling_bluetooth_on_raspberry_pi/,uid=589299321 HTTP/1.1"_ and I want to transform it to _"GET /blog/it/2020-04-18-tips-disabling_bluetooth_on_raspberry_pi/ HTTP/1.1"_ (i.e without **"/pix.png?url="** and without "**,uid=58929xxx"**). 

It's possible to do this ? with a custom log-format for example ... 

NGINX access.log sample : 

```
92.50.87.22 - - [28/Dec/2022:14:44:32 +0000] "GET /pix.png?url=/blog/it/2020-04-18-tips-disabling_bluetooth_on_raspberry_pi/,uid=5892OO61 HTTP/1.1" 200 98 "https://exemple.net/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:108.0) Gecko/20100101 Firefox/108.0"
2.81.89.87 - - [28/Dec/2022:14:44:42 +0000] "GET /pix.png?url=/blog/it/2020-04-18-tips-disabling_bluetooth_on_raspberry_pi/,uid=589299321 HTTP/1.1" 200 98 "https://example.net/" "Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
123.241.138.100 - - [28/Dec/2022:14:44:44 +0000] "GET /pix.png?url=/blog/hi-fi/2020-10-04-naim_audio_nait_2/,uid=589495349 HTTP/1.1" 200 98 "https://example.net/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Safari/605.1.15"
```

Many thank for your help.

**Comment by allinurl** [comment]
#117 will probably help with this (working on it as we speak). However, a simple post-processing should do it:

    sed -n 's/\/pix\.png?url=\(.*\),uid=[[:alnum:]]\+/\1/p' test.log | goaccess - --log-format=COMBINED

![2022-12-28-100048_662x377_scrot](https://user-images.githubusercontent.com/5005367/209839257-59ff9c71-e63b-481d-99c7-3b5dfa992172.png)

**Comment by ad5030** [comment]
Many thank,
A last question ;-) but if now I want in access logs :

92.50.87.22 - - [28/Dec/2022:14:44:32 +0000] "GET /pix.png?url=/blog/it/2020-04-18-tips-disabling_bluetooth_on_raspberry_pi/,uid=5892OO61 HTTP/1.1" 200 98 "https://exemple.net/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:108.0) Gecko/20100101 Firefox/108.0"
2.81.89.87 - - [28/Dec/2022:14:44:42 +0000] "GET /pix.png?url=/blog/it/2020-04-18-tips-disabling_bluetooth_on_raspberry_pi/,uid=589299321 HTTP/1.1" 200 98 "https://example.net/" "Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
123.241.138.100 - - [28/Dec/2022:14:44:44 +0000] "GET /pix.png?url=/blog/hi-fi/2020-10-04-naim_audio_nait_2/,uid=589495349 HTTP/1.1" 200 98 "https://example.net/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Safari/605.1.15"
145.224.77.102 - - [28/Dec/2022:16:47:16 +0000] "GET /aws.n0d3.io.txt HTTP/1.1" 200 12 "-" "curl/7.74.0"

Rq : In this example the last line not have "/pix.png?url=" and ",uid=58929xxx" flag 

The post processing "delete" the last line

**Comment by allinurl** [comment]
Please take a look at sed's [flags](https://linux.die.net/man/1/sed). I think the following should do it:

    sed 's/\/pix\.png?url=\(.*\),uid=[[:alnum:]]\+/\1/g' access.log | goaccess - --log-format=COMBINED

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.

**Comment by ad5030** [comment]
Ok thanks for your help
