### ISSUE TITLE
Link release notes

### ISSUE THREAD

**Issue by bcutter** [allinurl/goaccess#2436]
Could you just add the static link to https://goaccess.io/release-notes in every new release (or label, as releases are not used)?

This way one could easily check what actually has changed in a new version.

**Comment by allinurl** [comment]
Not sure I follow, do you mean the [Changelog](https://raw.githubusercontent.com/allinurl/goaccess/master/ChangeLog) included in the source?

**Comment by bcutter** [comment]
Exactly. Signal word: "inside".

Would be great to see what changed (or at least have a link redirecting to it) without the need to extract sources.

Currently absolutely nothing is shown outside of the box.

![image](https://user-images.githubusercontent.com/13799156/210193326-09ffa77a-f393-47b9-a917-af1b0253fbc7.jpeg)

**Comment by allinurl** [comment]
Got it. Thanks for sharing that feedback. I'll make sure to add the link to the description of the tag in the upcoming release.

**Comment by bcutter** [comment]
Great, thank you. Adding the direct link containing the version anchor (e. g. https://goaccess.io/release-notes#release-1.7) would of course be perfect - but the static one (https://goaccess.io/release-notes) as initially asked is already a huge improvement and should already help a lot (would be totally sufficient for me).

**Comment by allinurl** [comment]
Just an update on this. v1.7.1 is out. Here's the link to the release notes:

https://github.com/allinurl/goaccess/releases/tag/v1.7.1

Closing this. Feel free to reopen it if needed. Thank you!

**Comment by allinurl** [comment]
List of tags:

https://github.com/allinurl/goaccess/tags
