### ISSUE TITLE
Token '09' doesn't match specifier '%d'

### ISSUE THREAD

**Issue by woodgear** [allinurl/goaccess#2439]
take a look in https://github.com/allinurl/goaccess/issues/2415,but it seems stil not work for me.
cmd
```
LANG="en_US.UTF-8" bash -c 'goaccess  ./ac.log  -o ./report.html -p ./goaccess.conf'
```
goaccess.conf
```
time-format %T
date-format %d/%b/%Y
log_format [%d/%t %^] %h "%v" "%r"  %s %^ %^  "%u" "%^"  %T %^;
```
ac.log
```
[09/Jan/2023:05:00:09 +0000] 10.0.20.25 "ipaas-esb.cn" "POST / HTTP/1.1" 200 200 10.125.53.68:11000 "Apache-HttpClient/4.5.6 (Java/1.8.0_191)" "10.95.10.194" 0.109 0.109
```
error
```
 [PARSING ./ac.log] {0} @ {0/s}
Cleaning up resources...
==3211559== GoAccess - version 1.7 - Jan 10 2023 23:51:30
==3211559== Config file: ./goaccess.conf
==3211559== https://goaccess.io - <hello@goaccess.io>
==3211559== Released under the MIT License.
==3211559==
==3211559== FILE: ./ac.log
==3211559== Parsed 1 lines producing the following errors:
==3211559==
==3211559== Token '09' doesn't match specifier '%d'
==3211559==
==3211559== Format Errors - Verify your log/date/time format
```
i find that is very hard to map/debug the logformat issue,maybe we need more verbose log and more manual...

## some confuseing
Token '09' doesn't match specifier '%d'
what does this error mean?
as defined in man strftime 
> %d     The day of the month as a decimal number (range 01 to 31).  (Calculated from tm_mday.)

09 is obvious in 01 to 31..

**Comment by allinurl** [comment]
This should do it:

    goaccess access.log --log-format='[%d:%t %^] %h "%v" "%r" %s %b %^ "%u" %^ %T %^' --date-format=%d/%b/%Y --time-format=%T

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
