### ISSUE TITLE
Make the active panel more obvious

### ISSUE THREAD

**Issue by xrstf** [allinurl/goaccess#244]
When I first used goaccess, I was completely confused as to what panel I currently was on. I was expecting something tmux-like, like a ``*`` or ``>`` in front of the number of the panel. Or a different color for the panel header bar.

Just by accident I found the "Active panel" display in the top right corner 20 minutes later. But even knowing it's there, it's not very comfortable to look at the top right corner of my screen and also at the left side for the list of panels.

A small visual indicator next to the panel name/number would be greatly appreciated. :-)

**Comment by allinurl** [comment]
I'll certainly add this. Thanks for the suggestion!

**Comment by allinurl** [comment]
This has been added. All panels contain `>` to indicate active panel. I added a command line `--hl-header` option to color highlight the active panel. 

Feel free to build from [dev](http://goaccess.io/download#build), otherwise, it'll be pushed out in the upcoming version.

**Comment by xrstf** [comment]
Awesome, I'll wait for the version to arrive in my distribution. Thanks a bunch.
