### ISSUE TITLE
Goaccess does not parse all the file

### ISSUE THREAD

**Issue by cxw620** [allinurl/goaccess#2440]
I updated goaccess yesterday. However, I found that goaccess@1.7 can no longer parse all my log file. 
My log has 830k lines while goaccess only parse the first about 90k lines. I wonder if there's any limitation in goaccess@1.7.
![image](https://user-images.githubusercontent.com/70561268/212608472-53736a3c-36a9-4921-8faf-41f7bd0bea2c.png)

**Comment by allinurl** [comment]
There's no limit other than your machine. Are you persisting from disk?

**Comment by cxw620** [comment]
> There's no limit other than your machine. Are you persisting from disk?

I check my config, and the answer is no. 
It worked well before, and the problem appeared after an upgrade. I'll keep on figuring out the reason.

**Comment by cxw620** [comment]
I downgraded goaccess to 1.6.5, and everything works well with the same comfig. I believe that there's a bug in the latest version of goaccess.

**Comment by liucoj** [comment]
the same for me, after the latest upgrade to version 1.7
Processing only 2-3GBs on 16GB in total (in my case only the first 3 months in 15)

**Comment by allinurl** [comment]
@liucoj are you using the `--geoip-database` option?

**Comment by liucoj** [comment]
> @liucoj are you using the `--geoip-database` option?

Yes, i use:
goaccess apachelog -o fileoutput --log-format=COMBINED  --ignore-crawlers --ignore-panel=REQUESTS_STATIC --geoip-database dbip-city-lite-2022-01.mmdb

**Comment by liucoj** [comment]
> @liucoj are you using the `--geoip-database` option?

I forgot some detail maybe useful for you to understand: 
- I updated it from 1.5.7 to 1.7 on Debian 11
- apache log size is 16GB 
I tried to reinstall it, split apache log files smaller (16x1GB) same result.
Only 3 months of data parsed of 15
thanks for help

**Comment by cxw620** [comment]
What makes me realy puzzled is that when I try download the src code from Github directly and make && make install it, goaccess works!!!

**Comment by liucoj** [comment]
I downgraded goaccess to its prior version that I found on my ISP's repo and now it works again.
Compiling from source is always the best option but in my case I wanted to get rid of installing developer tools and a pre compiled package was the best choice for me.

**Comment by cxw620** [comment]
I confirm that the 1.7 version published at http://deb.goaccess.io does be with the problem. 

In conclusion, **compiling from source** will resolve this issue. Detailed reasons still remain unknown and wait for investigation.

**Comment by allinurl** [comment]
@cxw620 Thanks for sharing those updates. Can I ask, what flags did you pass to `./configure` when building from source?

**Comment by cxw620** [comment]
As shown in README, I always use the following command: 
```
./configure --enable-utf8 --enable-geoip=mmdb
```
