### ISSUE TITLE
Unsure about log file format

### ISSUE THREAD

**Issue by NotoriousBIT** [allinurl/goaccess#2442]
can someone help with the correct command?

`192.0.118.81 - - [06/Jan/2023:00:06:28 +0000] "GET /wp-content/uploads/2016/08/erikran.png HTTP/1.1" 301 194 "-" "Photon/1.0"`

**Comment by allinurl** [comment]
Please try:    

    goaccess access.log --log-format=COMBINED

**Comment by NotoriousBIT** [comment]
Trank you for the quick response. I already tried exactly that, but the unique visitors seem way too high. Even if I exclude crawlers and some IPs.

**Comment by allinurl** [comment]
Are you comparing the numbers to?

**Comment by NotoriousBIT** [comment]
I could lower the number by using `--browsers-file`  and `--unknowns-as-crawlers`.
Is it possible to ignore requests by `ASN type`?
There are a lot of requests with `ASN type | Hosting`, which I would like to exclude..

**Comment by allinurl** [comment]
At this time you can ignore by IP ranges using `-e`. #117 should let you exclude those hits going forward. Working on that feature as we speak.

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
