### ISSUE TITLE
Token '+0000]' doesn't match specifier '%h'

### ISSUE THREAD

**Issue by binarybaron** [allinurl/goaccess#2443]
`mywebsite.net 2.248.91.208 - - [19/Jan/2023:20:25:45 +0000] "GET /test/ HTTP/1.1" 200 97 "-" "node-XMLHttpRequest" "172.18.0.4:8081"`

This is a standard nginx configuration as far as I know. The error I get is the following:
`Token '+0000]' doesn't match specifier '%h'`

**Comment by wphampton** [comment]
Could you share the command you are running to process the logs? Specifically the `--log-format` option.

**Comment by binarybaron** [comment]
I tried `Common Log Format (CLF) with Virtual Host`

**Comment by wphampton** [comment]
Like this? `goaccess access.log --log-format=VCOMBINED`

**Comment by binarybaron** [comment]
Correct

**Comment by allinurl** [comment]
This should do it:

    goaccess access.log --log-format='%v %h %^[%d:%t %^] "%r" %s %b "%R" "%u" %^' --date-format=%d/%b/%Y --time-format=%T

**Comment by binarybaron** [comment]
Thank you!
