### ISSUE TITLE
goaccess: unrecognized option '--hide-referrer=domain.tld'

### ISSUE THREAD

**Issue by DasMuelli** [allinurl/goaccess#2444]
Hello,

i try to get an Script working. Manually running works fine, but at an Cronjob i got an Error.

**Version:**

`GoAccess - 1.7.
For more details visit: https://goaccess.io/
Copyright (C) 2009-2022 by Gerardo Orellana

Build configure arguments:
  --enable-utf8
  --enable-geoip=mmdb
`
**Script:**

`#!/bin/bash
set -x

cd /var/www/serverstats

WORKDIR=/var/www/serverstats/work

    LOGS="/var/log/nginx/access-blog.log*"
    rm --force $WORKDIR/*.* 
    cp $LOGS* $WORKDIR
    gzip -d --force work/*.gz
    cat work/access-blog.*  | \
        grep -v xmlrpc.php     | \
        grep -v wp-json        | \
        grep -v "adminer.php"  | \
        grep -v "robots.txt"   | \
        grep -v "app-ads.txt"  | \
        grep -v "ads.txt"      | \
        grep -v wp-login.php   | \
        grep -v "?author="     | \
        grep -v "wp-includes"  | \
        grep -v "wp-content"   | \
        grep -v "wp-admin"     | \
        grep -v api            | \
        grep -v ".well-known"  | \
        #grep -v "?local_ga_js=" | \
        goaccess  --anonymize-ip  \
                   --persist \
                    --ignore-crawlers \
                     --hide-referrer=dasnetzundich.de \
                        --db-path=/var/www/serverstats/db -o /var/www/serverstats/index.html  --log-format=COMBINED
`
**Debuglog from Cronjob**

`+ cd /var/www/serverstats
+ WORKDIR=/var/www/serverstats/work
+ LOGS='/var/log/nginx/access-blog.log*'
+ rm --force /var/www/serverstats/work/access-blog.log /var/www/serverstats/work/access-blog.log.1 /var/www/serverstats/work/access-blog.log.10 /var/www/serverstats/work/access-blog.log.11 /var/www/serverstats/work/access-blog.log.12 /var/www/serverstats/work/access-blog.log.13 /var/www/serverstats/work/access-blog.log.14 /var/www/serverstats/work/access-blog.log.16 /var/www/serverstats/work/access-blog.log.17 /var/www/serverstats/work/access-blog.log.18 /var/www/serverstats/work/access-blog.log.19 /var/www/serverstats/work/access-blog.log.2 /var/www/serverstats/work/access-blog.log.21 /var/www/serverstats/work/access-blog.log.22 /var/www/serverstats/work/access-blog.log.23 /var/www/serverstats/work/access-blog.log.3 /var/www/serverstats/work/access-blog.log.4 /var/www/serverstats/work/access-blog.log.5 /var/www/serverstats/work/access-blog.log.6 /var/www/serverstats/work/access-blog.log.7 /var/www/serverstats/work/access-blog.log.8 /var/www/serverstats/work/access-blog.log.9
+ cp /var/log/nginx/access-blog.log /var/log/nginx/access-blog.log.1 /var/log/nginx/access-blog.log.10.gz /var/log/nginx/access-blog.log.11.gz /var/log/nginx/access-blog.log.12.gz /var/log/nginx/access-blog.log.13.gz /var/log/nginx/access-blog.log.14.gz /var/log/nginx/access-blog.log.16.gz /var/log/nginx/access-blog.log.17.gz /var/log/nginx/access-blog.log.18.gz /var/log/nginx/access-blog.log.19.gz /var/log/nginx/access-blog.log.2 /var/log/nginx/access-blog.log.21.gz /var/log/nginx/access-blog.log.22.gz /var/log/nginx/access-blog.log.23.gz /var/log/nginx/access-blog.log.2.gz /var/log/nginx/access-blog.log.3 /var/log/nginx/access-blog.log.3.gz /var/log/nginx/access-blog.log.4 /var/log/nginx/access-blog.log.4.gz /var/log/nginx/access-blog.log.5 /var/log/nginx/access-blog.log.5.gz /var/log/nginx/access-blog.log.6.gz /var/log/nginx/access-blog.log.7.gz /var/log/nginx/access-blog.log.8.gz /var/log/nginx/access-blog.log.9.gz /var/www/serverstats/work
+ gzip -d --force work/access-blog.log.10.gz work/access-blog.log.11.gz work/access-blog.log.12.gz work/access-blog.log.13.gz work/access-blog.log.14.gz work/access-blog.log.16.gz work/access-blog.log.17.gz work/access-blog.log.18.gz work/access-blog.log.19.gz work/access-blog.log.21.gz work/access-blog.log.22.gz work/access-blog.log.23.gz work/access-blog.log.2.gz work/access-blog.log.3.gz work/access-blog.log.4.gz work/access-blog.log.5.gz work/access-blog.log.6.gz work/access-blog.log.7.gz work/access-blog.log.8.gz work/access-blog.log.9.gz
+ grep -v xmlrpc.php
+ grep -v wp-json
+ cat work/access-blog.log work/access-blog.log.1 work/access-blog.log.10 work/access-blog.log.11 work/access-blog.log.12 work/access-blog.log.13 work/access-blog.log.14 work/access-blog.log.16 work/access-blog.log.17 work/access-blog.log.18 work/access-blog.log.19 work/access-blog.log.2 work/access-blog.log.21 work/access-blog.log.22 work/access-blog.log.23 work/access-blog.log.3 work/access-blog.log.4 work/access-blog.log.5 work/access-blog.log.6 work/access-blog.log.7 work/access-blog.log.8 work/access-blog.log.9
+ grep -v adminer.php
+ grep -v robots.txt
+ grep -v app-ads.txt
+ grep -v ads.txt
+ grep -v wp-login.php
+ grep -v '?author='
+ grep -v wp-includes
+ grep -v wp-content
+ grep -v wp-admin
+ grep -v .well-known
+ goaccess --anonymize-ip --persist --ignore-crawlers --hide-referrer=domain.tld --db-path=/var/www/serverstats/db -o /var/www/serverstats/index.html --log-format=COMBINED
+ grep -v api
goaccess: unrecognized option '--hide-referrer=domain.tld'`

Whats wrong?

**Comment by allinurl** [comment]
Did you figure it out? Thanks

**Comment by DasMuelli** [comment]
Yes, 

I installed the GoAccess version from debian (1.4) After installing the version from debian (1.7) it works fine.
