### ISSUE TITLE
nginx proxy manager error logs, is this parseable?

### ISSUE THREAD

**Issue by xavier-hernandez** [allinurl/goaccess#2445]
Can this be parsed by GoAccess?

```
2023/01/22 16:49:05 [error] 416#416: *399 access forbidden by rule, client: 1.1.1.1, server: nyc.temp.net, request: "GET /.well-known/acme-challenge/test HTTP/1.1", host: "nyc.temp.net"
2023/01/22 16:49:05 [error] 416#416: *400 access forbidden by rule, client: 1.1.1.1, server: nyc.temp.net, request: "GET /.well-known/acme-challenge/test HTTP/1.1", host: "nyc.temp.net"
2023/01/22 16:49:05 [error] 416#416: *401 access forbidden by rule, client: 1.1.1.1, server: nyc.temp.net, request: "GET /.well-known/acme-challenge/test HTTP/1.1", host: "nyc.temp.net"
2023/01/22 16:58:05 [error] 422#422: *801 access forbidden by rule, client: 1.1.1.1, server: nyc.temp.net, request: "GET /.well-known/acme-challenge/test-jSkzfl3F9zt4Ps HTTP/1.1", host: "nyc.temp.net"
2023/01/22 16:58:05 [error] 422#422: *802 access forbidden by rule, client: 1.1.1.1, server: nyc.temp.net, request: "GET /.well-known/acme-challenge/test-jSkzfl3F9zt4Ps HTTP/1.1", host: "nyc.temp.net"
2023/01/22 16:58:05 [error] 422#422: *803 access forbidden by rule, client: 1.1.1.1, server: nyc.temp.net, request: "GET /.well-known/acme-challenge/test-jSkzfl3F9zt4Ps HTTP/1.1", host: "nyc.temp.net"

```

**Comment by allinurl** [comment]
This should do it (assumes consistency on the log):

    goaccess error.log --log-format='%d %t %^: %^: %h, %^ %v %^"%r" %^' --date-format=%Y/%m/%d --time-format=%T

**Comment by xavier-hernandez** [comment]
@allinurl I appreciate your time.

The NPM logs differ for the same log type for some reason. GETs do not include the upstream while the POSTs do. Is there anything I can do about this? I provided an example below. Thanks again.

2022/06/27 23:25:18 [error] 3952#3952: *1409524 upstream timed out (110: Connection timed out) while connecting to upstream, client: 2.2.2.2, server: r.temp.net, request: "POST /hooks/53453/42342 HTTP/1.1", upstream: "http://1.1.1.1:3000/hooks/4wbfc6XAZQG2Af6b9/NJz8SspXhTcraT4x5D3JdpfoWYTqoaAp2cqx23DegbD6NnZP", host: "r.temp.net"
2023/01/22 16:49:05 [error] 416#416: *399 access forbidden by rule, client: 1.1.1.1, server: x.temp.net, request: "GET /.well-known/acme-challenge/test HTTP/1.1", host: "x.temp.net"

**Comment by allinurl** [comment]
Sorry for the delay, I think this may be the closest to get something out of it. Let me know how it goes:


    goaccess error.log --log-format='%d %t %^: %v, %^: %h, %^ %v %^"%r" %^' --date-format=%Y/%m/%d --time-format=%T --ignore-panel=OS --ignore-panel=BROWSERS --ignore-panel=REFERRING_SITES --ignore-panel=STATUS_CODES --ignore-panel=NOT_FOUND

**Comment by xavier-hernandez** [comment]
@allinurl this works, thanks! Where can I learn more about this syntax, looks somewhat like regex?

**Comment by allinurl** [comment]
It does look like a regex. I'd say the best place is the [man page](https://goaccess.io/man#custom-log), unless you want to dive into the [code](https://github.com/allinurl/goaccess/blob/master/src/parser.c#L1406) :) gdb would be your best friend.

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
