### ISSUE TITLE
How to show requests on an IP on section 5

### ISSUE THREAD

**Issue by fbm-static** [allinurl/goaccess#245]
Hello,

On Visitor Hostnames and IPs is it possible to display what are being requested by a specific IP?

Thanks.

**Comment by allinurl** [comment]
It's not possible right now and although coding this would be fairly easy, I think this should be optional since it could hit the overall performance. There are a couple of requests that would handle this: #201 and #138.

**Comment by allinurl** [comment]
Closing it since issues #201 and #138 are related to this.
