### ISSUE TITLE
Log format help

### ISSUE THREAD

**Issue by danielfdsu** [allinurl/goaccess#2451]
Hello,

I'm trying to configure the following example logs/log_format from nginx in goaccess. I've tried using the nginx2goaccess script with no success.

Please see below:

```
 log_format main '$remote_addr - $remote_user [$time_iso8601_ms] "$request" '
    '$status $body_bytes_sent "$http_referer" '
    '"$http_user_agent" "$http_x_forwarded_for" $request_time';
```

Example logs:
```
172.10.10.10 - - [2023-01-31T00:00:02.146+00:00] "POST /api/v1/endpoint HTTP/1.1" 204 0 "-" "Last%20Night%20Mobile/4107 CFNetwork/1240.0.4 Darwin/20.5.0" "-" 0.034
172.10.10.10 - - [2023-01-31T00:00:02.718+00:00] "GET /api/v1/endpoint HTTP/1.1" 200 4344 "-" "Last%20Night%20Mobile/4107 CFNetwork/1240.0.4 Darwin/20.5.0" "-" 0.056
172.10.10.10 - - [2023-01-31T00:00:03.274+00:00] "POST /api/v1/endpoint HTTP/1.1" 204 0 "-" "Last%20Night%20Mobile/4107 CFNetwork/1240.0.4 Darwin/20.5.0" "-" 0.032
```

**Comment by RafaelHonesto** [comment]
Hello! 
For some reason my apache logs is at JSON format 

Could you help me with which log format I can use to analyze it?

I tried too many log formats like: 

goaccess -f access.log --log-format=%t "%Y-%m-%dT%H:%M:%S.%LZ" %P %f %h %r %q %m %s %u %R 

But it returns that some token doesn't match or something.
 
Here's a log example:

{ "time":"2023-01-31T12:51:05.589Z", "process":"1234", "filename":"/path/to/web/", "remoteIP":"127.0.0.1", "host":"myapp.com", "request":"/js/datatable1/date.js", "query":"","method":"GET", "status":"200", "userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36 Edg/109.0.1518.70","referer":"http://myapp.com/ini/?token=1234="}

**Comment by allinurl** [comment]
@RafaelHonesto This should do it:

    goaccess access.log --log-format='{ "time": "%dT%t.%^", "filename": "%e", "remoteIP": "%h", "host": "%v", "request": "%U", "query": "%q", "method": "%m", "status": "%s", "userAgent": "%u", "referer": "%R" }' --date-format=%Y-%m-%d --time-format=%T --http-protocol=no

**Comment by danielfdsu** [comment]
thanks @allinurl just needed to remove the %T from the end of the format as it errored on that param. All good now
