### ISSUE TITLE
Parsing error with several IP

### ISSUE THREAD

**Issue by fbmx** [allinurl/goaccess#246]
Hello Guys,

I have a problem to parse my nginx log with goaccess,

this i my current log 

    145.226.30.82 - 172.31.0.100 - - [05/May/2015:07:52:16 +0000] "GET /static/images/test_microsite-on-edx-logo.png HTTP/1.1" 404 140 0.000 "http://hec.fbmx.net/courses/HEC/F201/2015_01/progress" "Mozilla/5.0 (Windows NT 6.1; rv:37.0) Gecko/20100101 Firefox/37.0"

> 145.226.30.82 user ip
> 172.31.0.100 load ballancer ip

my config to parse that is log-format %h %^ %^[%d:%t %^] "%r" %s %b "%R" "%u"

so if i run goaccess in panel 5 - Visitors hostnames and IPs
   466 2 3.52%    1.60 MiB 172.31.0.100  
   316 2 2.39%  604.49 KiB 172.31.19.161 

i have only this 2 IPs.

Best.

**Comment by allinurl** [comment]
Hello, the following format works with your access log:

    %h %^[%d:%t %^] "%r" %s %b %T "%R" "%u
    %d/%b/%Y
    %H:%M:%S

Let me know how it goes.

**Comment by fbmx** [comment]
Hi
i tried and is the same, i have the last stable version (0.9)
i'll try with the dev version

**Comment by fbmx** [comment]
i tried with dev version and unfortunately it's doesn't work, 

GoAccess - version 0.9.1 - May  6 2015 03:46:55
                                               Config file: /usr/local/etc/goaccess.conf

                                                                                        Fatal error has occurred
                       Error occured at: src/parser.c - read_log - 1627
                                                                       Unable to open the specified log file. No such file or directory


i checked the file /usr/local/etc/goaccess.conf is there and is on the same group and user, i even do chmod 777 on it

**Comment by fbmx** [comment]
ok so the result is the same with the version 0.9.1,
Maybe you want my log file to check ?

**Comment by allinurl** [comment]
It seems the error you are getting is related to your access log. Are you specifying the path in the config file or using -f? Make sure you can actually read the access log.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        From: fbmxSent: Tuesday, May 5, 2015 23:01To: allinurl/goaccessReply To: allinurl/goaccessCc: Gerardo O.Subject: Re: [goaccess] Parsing error with several IP (#246)i tried with dev version and unfortunately it's doesn't work, 

GoAccess - version 0.9.1 - May  6 2015 03:46:55
                                               Config file: /usr/local/etc/goaccess.conf

                                                                                    Fatal error has occurred
                   Error occured at: src/parser.c - read_log - 1627
                                                                   Unable to open the specified log file. No such file or directory


i checked the file /usr/local/etc/goaccess.conf is there and is on the same group and user, i even do chmod 777 on it

—Reply to this email directly or view it on GitHub.

**Comment by fbmx** [comment]
Sorry my bad it was a stupid error actually, the path of log file wasn't
good

**Comment by allinurl** [comment]
Is it working for you then?

**Comment by fbmx** [comment]
Actually no, but is really strange i put some debug in the function parse_specifier for h and the result is good 

176.179.178.90
61.238.245.70
61.238.245.70
61.238.245.70
61.238.245.70
61.238.245.70
61.238.245.70
61.238.245.70
61.238.245.70
61.238.245.70
176.179.178.90
176.179.178.90
213.173.175.4
213.173.175.4

but in the panel 5 i have only 2 IPs

**Comment by fbmx** [comment]
So i finally found it 
this is the good log format 
log-format %h %^[%d:%t ] %^"%m %U %H" %s %b %T "%R" "%u"

But i suggest to add many verbose message cause there is many line wasn't take by goaccess but i wasn't know, 

if you want i can add a verbose mode and share with you ?

**Comment by allinurl** [comment]
Great, glad it is working now. Feel free to submit a pull request. Thanks.
