### ISSUE TITLE
No input data was provided nor there's data to restore when running in a python srcipt

### ISSUE THREAD

**Issue by xiangnanscu** [allinurl/goaccess#2463]
When I run `cat logs/access.log | /usr/bin/goaccess --log-format='%h [%d:%t %^] "%r" %s %b "%R" "%u" %T' --date-format=%d/%b/%Y --time-format=%T -o html` from shell, it works. 

But when I run from python , it fails with error: `GoAccess - version 1.7 - Jan 1 2023 03:16:59 Config file: /etc/goaccess/goaccess.conf Fatal error has occurred Error occurred at: src/goaccess.c - initializer - 1471 No input data was provided nor there's data to restore.`
```py
#!/usr/bin/env python3
import subprocess


cmd = '''cat logs/access.log | /usr/bin/goaccess --log-format='%h [%d:%t %^] "%r" %s %b "%R" "%u" %T' --date-format=%d/%b/%Y --time-format=%T -o html
'''
def runcmd(command):
    ret = subprocess.run(command,shell=True,stdout=subprocess.PIPE,stderr=subprocess.PIPE,encoding="utf-8",timeout=10)
    if ret.returncode == 0:
        return ret.stdout
    return ret.stderr

print(runcmd(cmd))

```

**Comment by allinurl** [comment]
Did you find the issue? Sounds like you passing `-` to goaccess should solve your issue.

    /usr/bin/goaccess - --log-format='%h [%d:%t %^] "%r" %s %b "%R" "%u" %T' --date-format=%d/%b/%Y --time-format=%T -o html

**Comment by xiangnanscu** [comment]
yes it is. Thanks
