### ISSUE TITLE
goaccess doesn't work in cron

### ISSUE THREAD

**Issue by xiangnanscu** [allinurl/goaccess#2464]
Ubuntu 20.04, Goaccess 1.7
I've a script named `stat.sh`.When I run it from shell `/root/bin/stat.sh`, it works as expectd, 
```sh
#!/bin/sh
echo begin...
/usr/bin/zcat -f -- /root/logs/access* | /usr/bin/goaccess --log-format='%h [%d:%t %^] "%r" %s %b "%R" "%u" %T' --date-format=%d/%b/%Y --time-format=%T -o /root/report.html
echo end...
```
but when I place it in `/etc/crontab`, it just not works, there's no `report.html` found:
```
33 17 * * * root /root/bin/stat.sh
```

**Comment by xiangnanscu** [comment]
the cron log error like:
```
GoAccess - version 1.7 - Jan  1 2023 03:16:59
Config file: /etc/goaccess/goaccess.conf

Fatal error has occurred
Error occurred at: src/goaccess.c - initializer - 1471
No input data was provided nor there's data to restore.
```

**Comment by xiangnanscu** [comment]
seems like goaccess can't receive any data from pipe when running in cron context

**Comment by allinurl** [comment]
cron doesn't give a TTY, so when piping data to goaccess via the cron or pretty much anytime you pipe data in, you will need to add a dash. e.g., 

    /usr/bin/zcat -f -- /root/logs/access* | /usr/bin/goaccess - --log-format='%h [%d:%t %^] "%r" %s %b "%R" "%u" %T' --date-format=%d/%b/%Y --time-format=%T -o /root/report.html

Let me know if that helps.

**Comment by xiangnanscu** [comment]
it works. Thanks a lot!
