### ISSUE TITLE
Apache access.log format - help with right settings

### ISSUE THREAD

**Issue by KapriQ** [allinurl/goaccess#2466]
Hello guys,

Please i have access.log in following format:
`adsl-dyn252.78-98-241.t-com.sk - - [16/Feb/2023:00:00:10 +0100] "GET /sexi-zona HTTP/2.0" 200 24661 "https://www.google.com/" "Mozilla/5.0 (Linux; Android 10; Lenovo TB-X606F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36"`
`adsl-dyn252.78-98-241.t-com.sk - - [16/Feb/2023:00:00:11 +0100] "GET /themes/mydomain/cache/v_8656_251cd6b5ab564d56b7f67578f71cd521_all.css HTTP/2.0" 200 70938 "https://mydomain.sk/sexi-zona" "Mozilla/5.0 (Linux; Android 10; Lenovo TB-X606F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36"`
`adsl-dyn252.78-98-241.t-com.sk - - [16/Feb/2023:00:00:11 +0100] "GET /img/mydomainsk-logo_mobile-1621751882.jpg?1651930482 HTTP/2.0" 200 15200 "https://mydomain.sk/sexi-zona" "Mozilla/5.0 (Linux; Android 10; Lenovo TB-X606F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36"`
`78.98.241.252 - - [16/Feb/2023:00:00:11 +0100] "GET /img/cms/kategorie/sexi_zona_zlava.png HTTP/2.0" 200 57357 "https://mydomain.sk/sexi-zona" "Mozilla/5.0 (Linux; Android 10; Lenovo TB-X606F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36"`

This is my apache config file - /etc/apache2/apache2.conf
`LogFormat "%v:%p %h %l %u %t \"%r\" %>s %O \"%{Referer}i\" \"%{User-Agent}i\"" vhost_combined`
`LogFormat "%h %l %u %t \"%r\" %>s %O \"%{Referer}i\" \"%{User-Agent}i\"" combined`
`LogFormat "%h %l %u %t \"%r\" %>s %O" common`
`LogFormat "%{Referer}i -> %U" referer`
`LogFormat "%{User-agent}i" agent`

Please what would be the right settings?

I have tried:
`goaccess /var/www/html/access.log --log-format='%h %^[%x] "%r" %s %b %^: %D %^"%R" "%u"' --datetime-format='%d/%b/%Y:%H:%M:%S %z' --tz=Europe/Berlin --date-spec=min
`
Got error:
`==356713== Format Errors - Verify your log/date/time format
`
Thanks , and i would like also to see only valid/unique visitors without crawlers / bots.

**Comment by KapriQ** [comment]
I have solved it by adding:
`--no-ip-validation `

**Comment by KapriQ** [comment]
After many tried, i have found that with following additional parse option command i can show the log
`--no-ip-validation`

But is there any way, how to show only unique visitors (Exclude crawlers / bots) like with this command? Because in my case it's not working :( ...
`--ignore-crawlers`

If i parse the output to s**how only bots/crawlers**, it shows **0 VISITORS**: (For example)
`goaccess /var/www/html/access.log --log-format=COMMON --no-ip-validation --crawlers-only -o /var/www/html/admin/report/report.html `


![ggg](https://user-images.githubusercontent.com/31235411/219440165-73c189c7-6edc-417b-b6b7-5d253f8207e3.png)

**Comment by KapriQ** [comment]
Okay, i will answer myself.

 I have installed remoteip mod in apache, and now it seems it works. The problem was the hostname instead of IP.

**Comment by allinurl** [comment]
Sounds like a format issue. This should work for the lines you posted above:

    goaccess access.log --log-format='%h %^[%x] "%r" %s %b "%R" "%u"' --datetime-format='%d/%b/%Y:%H:%M:%S %z' --no-ip-validation

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
