### ISSUE TITLE
Cant figure out how to add time served to log-format

### ISSUE THREAD

**Issue by dbabits** [allinurl/goaccess#2468]
Could you please post, this would be very helpful:
1) Command line and configuration file if any of your live demo instance
2) CustomLog line of your httpd.conf (assuming you are showing Apache log)
3) One line from httpd access.log
* I use goaccess 1.7
* It works successfully with --log-format=COMBINED
* What I'm trying to achieve : add  time served, just like in your demo instance.
* I noted this instruction in your man page and added %D, now I have to use custom log format. Spent days trying to figure out.
```
In order to get the average, cumulative and maximum time served in GoAccess, 
you will need to start logging response times in your web server. 
In Nginx you can add $request_time to your log format, or %D in Apache.
```

This works:
```
cat <<EOF | goaccess --log-format=COMBINED
10.53.233.120 - - [16/Feb/2023:16:27:35 -0500] "GET /path/v1/healthcheck HTTP/1.1" 200 2 "-" "Jersey/2.35 (Apache HttpClient 4.5.1)"
EOF
```

This doesn't work (note number between ] and GET). I tried different variations of patterns between [] :
```
cat <<EOF | goaccess --datetime-format='%d/%b/%Y:%H:%M:%S %z' --log-format='%h %l %u [%d:%t%^] %D "%r" %s %b "%f" "%a"'
10.53.233.120 - - [16/Feb/2023:16:27:35 -0500] 115030 "GET /path/v1/healthcheck HTTP/1.1" 200 2 "-" "Jersey/2.35 (Apache HttpClient 4.5.1)"
EOF
```

I can put %D at the end of the log line if that makes it easier. 
Would be nice to be able to say something like this (conceptually), rather than specifying everything:
```
--log-format=COMBINED+' %D'
```

**Comment by allinurl** [comment]
Please take a look at the [man page](https://goaccess.io/man#custom-log) for details on the specifiers. In any event, this should do it:

    goaccess access.log --datetime-format='%d/%b/%Y:%H:%M:%S %z' --log-format='%h %^[%x] %D "%r" %s %b "%R" "%u"'

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
