### ISSUE TITLE
Custom Log - no data collect

### ISSUE THREAD

**Issue by gonzaechev** [allinurl/goaccess#247]
Hi, i'm parsing a Apache type access log where individual hits look something like the following:

    70.197.7.136 - - [05/May/2015:15:53:12 -0700] "URL: www.xxx.com" "GET /images/xxx.com/en/lotto-logos/3.png HTTP/1.1" 200 8428 /images/xxx.com/en/lotto-logos/3.png "http://www.xxx.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/600.5.17 (KHTML, like Gecko) Version/8.0.5 Safari/600.5.17"

my LogFormat is:

     %h %l %u %t \"URL: %V\"  \"%r\" %>s %b %U \"%{Referer}i\" \"%{User-Agent}i\"

I have a problem to parse with goaccess, in no data show when goaccess ejecuted,  and tried in various ways but it still shows no data.

I could tell me how to parse the log?

Regards!!

**Comment by allinurl** [comment]
Please try the following:

    log-format %h %^[%d:%t %^] "%^" "%r" %s %b %^ "%R" "%u"
    date-format %d/%b/%Y
    time-format %H:%M:%S

**Comment by gonzaechev** [comment]
Hi allinurl, thanks for the quick response

change the format as marked but I still have the same problem, no data is displayed when running goaccess.

Dashboard - Overall Analyzed Requests                                                                                  [Active Panel: Visitors]

  Total Requests  280319 Unique Visitors 0 Referrers    0 Log Size  56.88 MiB
  Failed Requests 280319 Unique Files    0 Unique 404   0 Bandwidth 0.0   B
  Generation Time 2      Excl. IP Hits   0 Static Files 0 Log File  /var/log/httpd/access_log

 1 - Unique visitors per day - Including spiders                                                                                     Total: 0/0
 Hits having the same IP, date and agent are a unique visit

 2 - Top requests (URLs)                                                                                                             Total: 0/0
 Top requests sorted by hits - [avg. time served | protocol | method]
.....

**Comment by gonzaechev** [comment]
Sorry, attach again log format that was not complete...

LogFormat "%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" combined
LogFormat "%h %l %u %t \"%r\" %>s %b" common
LogFormat "%{Referer}i -> %U" referer
LogFormat "%{User-agent}i" agent
LogFormat "%h %l %u %t \"URL: %V\"  \"%r\" %>s %b %U \"%{Referer}i\" \"%{User-Agent}i\"" combinedTrillo

**Comment by gonzaechev** [comment]
The last LogFormat is the one being used in the file to be processed, thanks!

**Comment by allinurl** [comment]
Hello, would you be able to post a few lines from your access log? Feel free to use pastebin.com if needed.

**Comment by gonzaechev** [comment]
Hi allinur!

68.108.158.64 - - [06/May/2015:06:53:34 -0700] "URL: xxx.com"  "GET /css/images/xxx.png HTTP/1.1" 304 - /css/images/xxx.png "http://xxx.com/xxx.php" "Mozilla/5.0 (iPhone; CPU iPhone OS 8_3 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) CriOS/42.0.2311.47 Mobile/12F70 Safari/600.1.4"
187.210.189.241 - - [06/May/2015:06:53:34 -0700] "URL: xxx.com"  "GET /img/mail/1015/xxx.gif HTTP/1.1" 200 16338 /img/mail/1015/xxx.gif "-" "Mozilla/5.0 (iPhone; CPU iPhone OS 8_3 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Mobile/12F70"
190.219.222.164 - - [06/May/2015:06:53:34 -0700] "URL: xxx.com"  "GET /styles.css HTTP/1.1" 200 2398 /styles.css "http://xxx.com/xxx.php?tck_id=wxnxwoazpna" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36"
190.219.222.164 - - [06/May/2015:06:53:34 -0700] "URL: xxx.com"  "GET /img/mail/1/xxx.gif HTTP/1.1" 200 14584 /img/mail/1/xxx.gif "http://xxx.com/xxx.php?tck_id=wxnxwoazpna" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36"
46.107.48.193 - - [06/May/2015:06:53:35 -0700] "URL: xxx.com"  "GET /images_v3/mainlayout/xxx.png HTTP/1.1" 200 65090 /images_v3/mainlayout/xxx.png "http://xxx.com/css_v3/xxx.css?version=20150430_1" "Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.90 Safari/537.36"

**Comment by allinurl** [comment]
The following format does work for me:

    log-format %h %^[%d:%t %^] "%^" "%r" %s %b %^ "%R" "%u"
    date-format %d/%b/%Y
    time-format %H:%M:%S

Did you set it in your config file? or from the command line? This is what I ran from the command line:

    goaccess -f log --no-global-config --log-format='%h %^[%d:%t %^] "%^" "%r" %s %b %^ "%R" "%u"' --date-format='%d/%b/%Y' --time-format='%H:%M:%S'

**Comment by gonzaechev** [comment]
I tried to run it from the command line and the same result. No data displayed

Dashboard - Overall Analyzed Requests                                                         [Active Panel: Visitors]

  Total Requests  501755 Unique Visitors 0 Referrers    0 Log Size  102.10 MiB
  Failed Requests 501755 Unique Files    0 Unique 404   0 Bandwidth 0.0   B
  Generation Time 3      Excl. IP Hits   0 Static Files 0 Log File  /var/log/httpd/access_log

 1 - Unique visitors per day - Including spiders                                                            Total: 0/0
 Hits having the same IP, date and agent are a unique visit.

 2 - Top requests (URLs)                                                                                    Total: 0/0
 Top requests sorted by hits - [avg. time served | protocol | method]

I tried to compile the source on another server to test it and it's the same result.
My server is a Centos 6.x, if I install from "yum" (version 0.8.5-1.el6) the result is different.
......
Fatal error has occurred
Error occured at: goaccess.c - main - 832
Nothing valid to process.

**Comment by allinurl** [comment]
Have you tried running goaccess against the sample lines that you posted above? Using the command line that I previously posted should work. Let me know.

**Comment by allinurl** [comment]
By the way, the format above will work only on v0.9. Previous version do not use the `time-format`. So you want to run it as:

    log-format %h %^[%d:%^] "%^" "%r" %s %b %^ "%R" "%u"
    date-format %d/%b/%Y

**Comment by gonzaechev** [comment]
Hi, i try from the command line according to your post but not worked.



 Dashboard - Overall Analyzed Requests                                                         [Active Panel: Visitors]

  Total Requests  803693 Unique Visitors 0 Referrers    0 Log Size  164.76 MiB
  Failed Requests 803693 Unique Files    0 Unique 404   0 Bandwidth 0.0   B
  Generation Time 16     Excl. IP Hits   0 Static Files 0 Log File  /var/log/httpd/access_log

 1 - Unique visitors per day - Including spiders                                                            Total: 0/0
 Hits having the same IP, date and agent are a unique visit.









 2 - Top requests (URLs)                                                                                    Total: 0/0
 Top requests sorted by hits - [avg. time served | protocol | method]









 3 - Top static requests (e.g. jpg, png, js, css..)                                                         Total: 0/0
 Top static requests sorted by hits - [avg. time served | protocol | method]





 [F1]Help [O]pen detail view  265 - Wed May  6 12:21:52 2015                                       [Q]uit GoAccess 0.9

**Comment by allinurl** [comment]
Did you try only with the 5 lines that you posted above?

**Comment by gonzaechev** [comment]
Hi, had tested only a portion of the log and had not worked, if I try with the lines of the example happens to you if it works!

it is surely something the log does not like

**Comment by allinurl** [comment]
You may need to `tail/head` the log by chunks to find out what lines are different. Are you running it through cat/zcat?

**Comment by gonzaechev** [comment]
Its works!!! missing space on one of the variables
when paste the log and edit, delete one of the spaces

Kinds Regards!!!

old  -  log-format %h %^[%d:%^] "%^" "%r" %s %b %^ "%R" "%u"
new -   log-format %h %^[%d:%t %^] "%^"  "%r" %s %b %^ "%R" "%u"

**Comment by gonzaechev** [comment]
log-format=%h %^[%d:%t %^] "%^"  "%r" %s %b %^ "%R" "%u"

**Comment by gonzaechev** [comment]
mmm, I'm seeing commenting spaces are together are deleted!

**Comment by allinurl** [comment]
Awesome. `%t` works on >v0.9. Closing this. Feel free to reopen it if needed.
