### ISSUE TITLE
I need help with Nginx log format conversion

### ISSUE THREAD

**Issue by jpdoria** [allinurl/goaccess#2472]
Hi, I need help with log format conversion to GoAccess. I tried using the [nginx2goaccess](https://github.com/stockrt/nginx2goaccess) script but it doesn't work on me.

Here's the log format that I'm trying to convert:

```
log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                    '$status $body_bytes_sent "$http_referer" '
                    '"$http_user_agent" "$http_x_forwarded_for"';
```

And here's the sample log:

```
111.22.33.44 - - [21/Feb/2023:00:00:00 +0000] "GET /img/gh-menu-icon.275585e3.svg HTTP/2.0" 200 1402 "https://sub.domain.com/dashboard/offer/999" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36" "11.222.333.44"
```

The command I used to start `goaccess` is:

```
goaccess /mnt/ubuntu*/access.log* -a -o /var/www/goaccess/report.html --log-format '%h - %^ [%d:%t %^] "%r" %s %b "%R" "%u" "%^"' --date-format '%d/%b/%Y' --time-format %T --real-time-html --ws-url wss://goaccess.domain.com:443/ws --origin https://goaccess.domain.com
```

Errors that I'm getting:
- `doesn't match specifier`
- `Format Errors - Verify your log/date/time format`

Thanks!

**Comment by allinurl** [comment]
This should do it:

    goaccess access.log --log-format='%h %^[%x] "%r" %s %b "%R" "%u" %^' --datetime-format='%d/%b/%Y:%H:%M:%S %z' --date-spec=min

![2023-02-22-081739_446x776_scrot](https://user-images.githubusercontent.com/5005367/220647882-6fb43104-b8de-4c4b-ba70-6413907cf25e.png)

**Comment by jpdoria** [comment]
Confirming your solution worked fine on my end. Thanks, @allinurl!
