### ISSUE TITLE
disable-nls breaks build

### ISSUE THREAD

**Issue by assistcontrol** [allinurl/goaccess#2477]
When building with `--disable-nls` and no gettext library:

```
depbase=`echo src/commons.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`; cc -DLOCALEDIR=\"/usr/local/share/locale\" -DHAVE_CONFIG_H -I. -I./src     -O2 -DSYSCONFDIR=\"/usr/local/etc\" -Wall  -Wextra -Wnested-externs -Wformat=2 -g  -Wmissing-prototypes -Wstrict-prototypes  -Wmissing-declarations -Wwrite-strings -Wshadow  -Wpointer-arith -Wsign-compare  -Wbad-function-cast -Wcast-align  -Wdeclaration-after-statement -Wshadow  -Wold-style-definition -O2 -pipe  -I/usr/include -I/usr/local/include -fstack-protector-strong -fno-strict-aliasing  -pthread -MT src/commons.o -MD -MP -MF $depbase.Tpo -c -o src/commons.o src/commons.c && mv -f $depbase.Tpo $depbase.Po
In file included from src/commons.c:44:
./src/labels.h:33:10: fatal error: 'libintl.h' file not found
#include <libintl.h>
         ^~~~~~~~~~~
1 error generated.
*** Error code 1

Stop.
make[3]: stopped in /wrkdirs/usr/ports/sysutils/goaccess/work/goaccess-1.7.1
```

`src/goaccess.c` calls `bindtextdomain()` and `textdomain()` without guarding `ENABLE_NLS`. Similarly, `src/labels.h` includes libintl.h and defines some gettext macros without `ENABLE_NLS` guards.

I patched this up in FreeBSD a while ago but I guess I never upstreamed it. I'm not convinced that the patch to labels.h is correct (it just creates some stubs) so I wanted to check with you. If it looks right I'm happy to create a PR for it.

Patches here: https://github.com/freebsd/freebsd-ports/tree/main/sysutils/goaccess/files

**Comment by allinurl** [comment]
Yeah, that looks good to me. Please feel free to create the PR. Thanks!

**Comment by allinurl** [comment]
Thank you. To ship these changes, I plan to release v1.7.2 over the weekend.
