### ISSUE TITLE
install goaccess error

### ISSUE THREAD

**Issue by dolphin17** [allinurl/goaccess#2488]
when I configure.it's show error: configure: error: Cannot find a library providing tputs
I already install  ncurses-devel
`
./configure --enable-utf8 --enable-geoip=mmdb
`
![image](https://user-images.githubusercontent.com/8563317/224950775-c82f3f7b-bbc0-49ed-83db-9f05c0ea54f6.png)

![image](https://user-images.githubusercontent.com/8563317/224950950-620577c4-de85-45eb-bdad-e7000faeabda.png)

**Comment by allinurl** [comment]
Are you building from tar.gz or upstream (github clone)?

**Comment by dolphin17** [comment]
I use the following steps
```
$ wget https://tar.goaccess.io/goaccess-1.7.1.tar.gz
$ tar -xzvf goaccess-1.7.1.tar.gz
$ cd goaccess-1.7.1/
$ ./configure --enable-utf8 --enable-geoip=mmdb
$ make
# make install
```

**Comment by allinurl** [comment]
Can you try running:

```
# make distclean
# autoreconf -fiv
# ./configure --enable-utf8 --enable-geoip=mmdb
...
```

Let me know if that helps

**Comment by dolphin17** [comment]
Same wrong result
![image](https://user-images.githubusercontent.com/8563317/225177831-4b89e7f2-56f8-49be-b862-9f6d1ea2420a.png)

**Comment by allinurl** [comment]
This may be a centos6 issue as I wasn't able to reproduce this on a vanilla centos7 machine. Have you tried testing this out on a newer machine?

**Comment by allinurl** [comment]
I was able to build goaccess under Centos6 and no issues were found, so this is probably isolated to your environment. Here's the output from a vanilla vagrant centos6. 

The only packages installed were:

```
$ sudo yum groupinstall "Development tools"
$ sudo yum install wget ncurses-devel
```

![2023-03-16 08-44](https://user-images.githubusercontent.com/5005367/225636895-2cbcca50-89d1-416b-9101-b2f246061c86.gif)
