### ISSUE TITLE
ASN Unknown

### ISSUE THREAD

**Issue by Provyzor** [allinurl/goaccess#2489]
Hi!

ASN Unknown. How to configure ASN database location?

**Comment by allinurl** [comment]
Just pass the db file as an option, e.g.,

    goaccess access.log --geoip-database=/path/GeoLite2-ASN.mmdb -o report.html --log-format=COMBINED

You can find the db in multiple places, e.g.,

https://db-ip.com/db/download/ip-to-asn-lite
https://github.com/P3TERX/GeoLite.mmdb

**Comment by allinurl** [comment]
You can use multiple databases as of [v1.7](https://goaccess.io/release-notes#release-1.7). Just point to different files. e.g.,

    goaccess access.log --geoip-database=/path/GeoLite2-ASN.mmdb --geoip-database=/path/GeoLite2-City.mmdb -o report.html --log-format=COMBINED

**Comment by Provyzor** [comment]
Thanks a lot!

**Comment by Provyzor** [comment]
Added on more record with ASN-database to goaccess.conf, nothing changed:

geoip-database /usr/local/share/GeoIP/GeoLite2-City.mmdb
geoip-database /usr/local/share/GeoIP/GeoLite2-ASN

**Comment by allinurl** [comment]
is that an mmdb file?

**Comment by Provyzor** [comment]
Wow! It works!!

Sorry, the file extension missed in config file!

Respect and uvazhuha (something like respect in Russian) to you! 👍

**Comment by allinurl** [comment]
@Provyzor glad that worked! thanks for the kind words as well :)

Closing this, feel free to reopen it if needed.
