### ISSUE TITLE
pattern matching 

### ISSUE THREAD

**Issue by aakash21** [allinurl/goaccess#249]
I am having logs of all servers on logentries and when I try to open it with goaccess it gives me wrong statistics. I want goaccess pattern for logentries log.

**Comment by allinurl** [comment]
Can you please elaborate more about this? What results are you getting and what's supposed to look like? Thanks

**Comment by aakash21** [comment]
i have all my nginx logs downloaded from logentries of my production server and now i am trying to analyse the stats with goaccess but it shows total requests and failed requests equal.

**Comment by allinurl** [comment]
Can you post your a few lines from your access log as well as the log and date format from your goaccess config file?

**Comment by aakash21** [comment]
<14>1 2015-05-12T05:04:05.814315Z ip-10-0-1-170 Nginx-Access-Log - - - hostname=ip-10-0-1-170 appname=Nginx-Access-Log 10.0.1.248 - - [12/May/2015:10:34:05 +0530] "GET /rest/getShowsList?start=0&limit=15 HTTP/1.1" 200 5653 "-" "Dalvik/1.6.0 (Linux; U; Android 4.4.4; GT-I9060I Build/KTU84P)"
<14>1 2015-05-12T05:04:05.814339Z ip-10-0-1-170 Nginx-Access-Log - - - hostname=ip-10-0-1-170 appname=Nginx-Access-Log 10.0.1.248 - - [12/May/2015:10:34:05 +0530] "GET /rest/getexclusivedevicestatus HTTP/1.1" 200 55 "-" "Dalvik/1.6.0 (Linux; U; Android 4.4.3; D5322 Build/19.1.1.C.0.56)"
these are logs from the logentries. 
this are formats which i have used  but can not get results.
log-format "%h %l %u %t \"%r\" %>s %b"
log-format %h %^[%d:%t %^] "%r" %s %b "%R" "%u"

**Comment by allinurl** [comment]
Using goaccess >= v0.9:

    log-date %d/%b/%Y
    log-time %H:%M:%S
    log-format %^ %^ %^ %^ %^ %^ %^ %^ %^ %h %^[%d:%t %^] "%r" %s %b "%R" "%u"

Run goaccess as:

    goaccess -f access.log -p /path/to/goaccess.conf

**Comment by aakash21** [comment]
thnks it done.
and alternate could be that 
goaccess -f /path/to/log -a >report.html
after converting logentries log to nginx log format.

**Comment by allinurl** [comment]
Glad that worked. Feel free to open a new issue if needed. Closing this.
