### ISSUE TITLE
Oracle OHS access log 

### ISSUE THREAD

**Issue by carcalacus** [allinurl/goaccess#2493]
Hello, my log looks like this:

    10.0.228.20 name.surname [24/Mar/2023:14:04:36 +0200] GET /ostuffonent-server/js/components/fslisklinkprocess-flow/model/remoblabladel.js HTTP/1.1 304 - https://spacial.link/specialappl/ Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36 Edg/111.0.1661.41 `**0/16500**`

the part I struggle with is `**0/16500**`   this is basically  `**%T/%D**`  (miliseconds/seconds) duration

my current command:

cat  /upath s/access_log | awk -F '"' {'print $1,$2,$3,$4,$5,$6,$7,$9'} | cut -d " " -f 1,3,4,5,7-11,12-60 | tr -s ' ' | goaccess - --log-format='%h %e [%d:%t %^] %m %U %H %s %b "%R" "%u" ' --date-format=%d/%b/%Y --time-format=%T

I would like to tell goaccess about  `**%T/%D**` part from the log file, I currently ignore this part.

Thanks

**Comment by allinurl** [comment]
To help GoAccess parse your Oracle log file correctly, you may want to consider enclosing the user agent and possibly the request in quotation marks or brackets. This will make it easier for GoAccess to identify where each token ends. e.g.,

    10.0.228.20 name.surname [24/Mar/2023:14:04:36 +0200] "GET /ostuffonent-server/js/components/fslisklinkprocess-flow/model/remoblabladel.js" HTTP/1.1 304 - "https://spacial.link/specialappl/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36 Edg/111.0.1661.41" `**0/16500**`

Once you do that, you should be able to get the format easily.

    goaccess access.log --log-format='%h %^[%d:%t %^] "%r" %s %b "%R" "%u" %^/%D*%^' --date-format=%d/%b/%Y --time-format=%T

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
