### ISSUE TITLE
WebSocket with Apache2 Proxy + SSL gives 101 Switching Protocols then fails

### ISSUE THREAD

**Issue by enigmapr0ject** [allinurl/goaccess#2495]
My configuration files for my site and GoAccess are identical to the guide given in [issue 1789](https://github.com/allinurl/goaccess/issues/1789) and for a few minutes, everything seemed fine - green dot, and the file refreshed every time my browser refreshed. However, looking at the network tab...

![image](https://user-images.githubusercontent.com/55900441/228715553-18737096-e0d5-4a0d-a32c-bc89f76d6f12.png)

Site conf file: 

```
DEFINE serv_name <my domain>
        DEFINE serv_admn user@<my domain>
        DEFINE log_name apache
        DEFINE stat_url <my domain>
        DEFINE serv_url 127.0.0.1
        DEFINE serv_port 7890
        ServerTokens Prod
        SSLStaplingCache "shmcb:${APACHE_LOG_DIR}/stapling-cache(150000)"
        SSLSessionCache "shmcb:${APACHE_LOG_DIR}/ssl_scache(512000)"
        SSLSessionCacheTimeout 300
<VirtualHost *:80 [::]:80>
        ServerName ${serv_name}
        DocumentRoot /var/www/<my domain without the TLD>
        ServerAdmin ${serv_admn}
        RewriteEngine On
        RewriteCond %{SERVER_NAME} =${serv_name}
        RewriteCond %{HTTPS} off
        RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent]
        ErrorLog ${APACHE_LOG_DIR}/${log_name}.error.log
        CustomLog ${APACHE_LOG_DIR}/${log_name}.access.log combined
</VirtualHost>
<VirtualHost *:443 [::]:443>
        ServerName ${serv_name}
        DocumentRoot /var/www/<my domain without the TLD>
        ServerAdmin ${serv_admn}
        ErrorLog ${APACHE_LOG_DIR}/${log_name}.error.log
        CustomLog ${APACHE_LOG_DIR}/${log_name}.access.log combined
### Let's Encrypt Section ###
        SSLEngine On
        SSLCertificateFile /etc/letsencrypt/live/<my domain>/fullchain.pem
        SSLCertificateKeyFile /etc/letsencrypt/live/<my domain>/privkey.pem
        Options -Includes -ExecCGI
        Include /etc/letsencrypt/options-ssl-apache.conf
        ## I am excluding the default Let's Encrypt apache security settings and using the following
        #SSLCipherSuite ECDHE+RSA+AES256+GCM+SHA512:DHE+RSA+AES256+GCM+SHA512:ECDHE+RSA+AES256+GCM+SHA384:DHE+RSA+AES256+GCM+SHA384:ECDHE+RSA+AES256+SHA384:EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH:!aNULL:!eNULL:!EXPORT:!DES:!MD5:!PSK:!RC4
        SSLHonorCipherOrder Off
        #SSLCipherSuite EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH:!aNULL:!eNULL:!EXPORT:!DES:!MD5:!PSK:!RC4
        SSLProtocol All -SSLv2 -SSLv3 -TLSv1 -TLSv1.1
### Deny http1.0 requests ###
        Protocols h2 http/1.1
### Harden Security ###
        ProxyRequests On
        ProxyPreserveHost On
        ProxyTimeout 600
        ProxyReceiveBufferSize 4096
        SSLProxyEngine On
        RequestHeader set Front-End-Https "On"
        ServerSignature Off
        SSLCompression Off
        SSLUseStapling On
        SSLStaplingResponderTimeout 5
        SSLStaplingReturnResponderErrors Off
        SSLSessionTickets Off
        RequestHeader set X-Forwarded-Proto 'https' env=HTTPS
        #Header always set Strict-Transport-Security "max-age=15552000; preload"
        #Header always set X-Content-Type-Options nosniff
        #Header always set X-Robots-Tag none
        #Header always set X-XSS-Protection "1; mode=block"
        #Header always set X-Frame-Options "SAMEORIGIN"
        #Header always set Referrer-Policy "strict-origin-when-cross-origin"
        #Header always set Content-Security-Policy-Report-Only "default-src 'self' https:; font-src 'self' data: ${stat_url} ${serv_name}; media-src 'self' ${stat_url} ${serv_name}; script-src 'self' 'unsafe-inline' ${stat_url} ${serv_name}; style-src 'self' ${stat_url} ${serv_name}; img-src 'self' data: blob: ${stat_url} ${serv_name}; worker-src *; frame-src https:; connect-src 'self' wss: https: ${stat_url} ${serv_name};"
### GoAccess Specific Section ###
        <Location /ws/>
                ProxyPass ws://${serv_url}:${serv_port}/ws/
        </Location>
        <Location /wss/>
                ProxyPass wss://${serv_url}:${serv_port}/wss/
        </Location>
</VirtualHost>
```

goaccess.conf:

```
time-format %T %z
date-format %d/%b/%y
log-format COMBINED
color-scheme 3
config-dialog false
hl-header true
html-prefs {"theme":"bright","perPage":5,"layout":"horizontal","showTables":true,"visitors":{"plot":{"chartType":"bar"}}}
json-pretty-print ture
no-color false
no-column-names false
no-csv-summary false
no-progress false
no-tab-scroll false
with-mouse false
addr 127.0.0.1
daemonize true
origin https://<my domain>
port 7890
pid-file /var/run/goaccess.pid
real-time-html true
ssl-cert /etc/letsencrypt/live/<my domain>/fullchain.pem
ssl-key /etc/letsencrypt/live/<my domain>/privkey.pem
ws-url wss://<my domain>:443/wss/
agent-list true
with-output-resolver true
http-method yes
http-protocol yes
no-query-string false
no-term-resolver false
444-as-404 false
4xx-to-unique-count false
all-static-files false
double-decode false
ignore-crawlers false
crawlers-only false
unknowns-as-crawlers false
ignore-panel REFERRERS
ignore-panel KEYPHRASES
real-os true
```

The network tab shows WSS response to be 101 Switching Protocols that will stay pending for over a minute and then die.

![image](https://user-images.githubusercontent.com/55900441/228715721-4cf914c4-abb3-4653-bdd2-95917125a15b.png)

Am I just being stupid? 😅

**Comment by enigmapr0ject** [comment]
After looking into it, it does seem to autoupdate itself but the Content Download timing for the WSS connection is 1.7 minutes - I thought this was when the max-age or keep alive timer was hit and then it just... dies, but it seems not. I am unsure if this timing is normal.

**Comment by allinurl** [comment]
It's definitely taking quite a while to update, which is a bit odd. It's possible that there might be a configuration issue on the reverse proxy side causing the delay. Have you considered testing it without the reverse proxy to make sure it's working correctly? If everything looks good, you can always add the proxy back in afterwards.

**Comment by enigmapr0ject** [comment]
> It's definitely taking quite a while to update, which is a bit odd. It's possible that there might be a configuration issue on the reverse proxy side causing the delay. Have you considered testing it without the reverse proxy to make sure it's working correctly? If everything looks good, you can always add the proxy back in afterwards.

![image](https://user-images.githubusercontent.com/55900441/229329010-14938dc3-d6b4-4690-bd9a-8b35c1bdafdb.png)

Not sure if I configured this properly with the reverse proxy turned off, however this is what I get: WebSocket connection failed. Even replacing the host domain name with the IP address does not solve the issue, it hangs on "stalled" then gives that failure message. Firewall shows the ports as open, and `netstat -peanut | grep goaccess` as suggested in the issue linked above does indeed show the line it is supposed to:

![image](https://user-images.githubusercontent.com/55900441/229329114-4606058d-2a98-4f1e-94b6-7aafe8118353.png)

Weirdly enough, when I do this with the reverse proxy, I get a second line that shows "ESTABLISHED" and has `127.0.0.1:<random port>` instead of `0.0.0.0:*`.

**Comment by enigmapr0ject** [comment]
![image](https://user-images.githubusercontent.com/55900441/229331247-f6e08af7-6b88-4dcb-86e7-313e4d270cca.png)

Hopefully this helps investigate further.

**Comment by allinurl** [comment]
I'd run it with the bare minimum (not using any of the options in your config file), e.g., assuming goaccess is running on the same server as your web server:

    goaccess access.log --log-format=COMBINED --no-global-config -o report.html --real-time-html --ssl-cert /etc/letsencrypt/live/<my domain>/fullchain.pem --ssl-key /etc/letsencrypt/live/<my domain>/privkey.pem
