### ISSUE TITLE
How can I set my custom JSON log format in GoAccess - version 0.9.4 

### ISSUE THREAD

**Issue by shwetahealthians** [allinurl/goaccess#2499]
log_format main '{"time": $time_local, "request_id": $request_id, "http_x_amzn_trace_id": $http_x_amzn_trace_id, "http_x_forwarded_for": $http_x_forwarded_for, "remote_addr": "$remote_addr",  "http_user_agent": "$http_user_agent", "http_host": "$http_host", "request_method": "$request_method", "request_uri": "$request_uri", "status": $status, "request_time": $request_time, "request_length": $request_length, "body_bytes_sent": $body_bytes_sent, "upstream_addr": "$upstream_addr"}';

    {"time": 04/Apr/2023:12:09:31 +0530, "request_id": c64d2a33dc6a50a80557167656f5b5, "http_x_amzn_trace_id": Root=1-642bc623-07e17d5b218b3429633112, "http_x_forwarded_for": xx.xx.xxx.xxx, "remote_addr": "14.97.214.162",  "http_user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36", "http_host": "xyz.example.com", "request_method": "POST", "request_uri": "/xyz/path/to/url", "status": 200, "request_time": 0.041, "request_length": 3147, "body_bytes_sent": 74, "upstream_addr": "unix:/run/php/php7.1-fpm-2.sock"}

Could you help me ?

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
