### ISSUE TITLE
Pattern won't match log format containing a syslog date format 

### ISSUE THREAD

**Issue by mabushey** [allinurl/goaccess#250]
Sample log with two entries. Only the first is processed:

    May  9 00:00:00 www1 www: 184.57.10.149 - - [09/May/2015:00:00:00 +0000] "GET /sites/all/modules/contrib/colorbox/styles/default/images/controls.png HTTP/1.1" 200 2104 "https://www.site.com/sites/default/files/css/css_YT8ji6OlXsDsFLaBTiURPPMtThJ7WPuG1TDcrKyknKs.css" "Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36"
    May 10 00:00:00 www3 www: 75.101.193.176 - - [10/May/2015:00:00:00 +0000] "GET /taxonomy/term/133/feed HTTP/1.0" 200 719 "-" "rogerbot/1.1 (http://moz.com/help/guides/search-overview/crawl-diagnostics#more-help, rogerbot-crawler+pr2-crawler-37@moz.com)"

time-format %H:%M:%S %z
date-format %d/%b/%Y
log-format %^ %^ %^ %^ %^ %^: %h - - [%d:%t] "%r" %s %b "%R" "%u

**Comment by allinurl** [comment]
Thanks for reporting this. I'm looking into this, I'll post back as soon as I have some news.

**Comment by allinurl** [comment]
Since the date does not use a leading zero, the parser attempts to read a blank space, so in the first case it won't actually grab `09/May/2015`. However, you could use the following if your log contains a `syslog` date:

    log-format %^:%^:%^:%^ %h %^[%d:%t %^] "%r" %s %b "%R" "%u"
    date-format %d/%b/%Y
    time-format %H:%M:%S

Let me know how it goes.

**Comment by mabushey** [comment]
Thank you, that works. I don't understand why.

date-format %d/%b/%Y
time-format %H:%M:%S

This indexes only through the 9th:
log-format %^ %^ %^ %^ %^ %^: %h %^[%d:%t %^] "%r" %s %b "%R" "%u"
and this works:
log-format %^:%^:%^:%^ %h %^[%d:%t %^] "%r" %s %b "%R" "%u"

The one that works seems like it's skipping fields and should be broken. Is there some documentation as to how this matching occurs?

**Comment by allinurl** [comment]
Good question! ​This is how the parser matches those `ignore specifiers`. The first `%^` tells the parser that it should ignore all characters until it finds the character next to `%^`, in the format that you posted is a space char ` `. Then it will do the same thing for the second `%^ `, however, because `9` does not have a leading zero, then the parser will stop before it reaches `9`. 

Since you have `%^ %^ %^ %^ %^ %^: %h` which has 6 spaces, it will consider the line valid.  For the second line, there are only 5 spaces (there is only one space within `May 10`), so the log format pattern won't match.

Hope that helps. I'll add this to the documentation. Thanks for pointing this out.

**Comment by allinurl** [comment]
Expanding on the working pattern `%^:%^:%^:%^ %h `, it works the same way, `:` right next to every `%^` tells the parser that the next expected character is a colon and that we want to ignore everything in between. Somewhat as a positive lookahead on a regex.

**Comment by mabushey** [comment]
Cool, Thank you very much for the explanation. :) I realized that the reality is I was doing things wrong, so I changed to this logging format in NginX:

log_format vhosts '$hostname $remote_addr - $remote_user [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent"';

and then in the syslog conf I added template("$MSG\n") do not include all the extra headers.

Now I'm using log-format %^ %h %^[%d:%t %^] "%r" %s %b "%R" "%u for goaccess.

**Comment by navidurrahman** [comment]
for me it works like this:
```
%^ %^ %^ %^ %^: %h - - [%d:%t %^] [[%^][%^] "%r" "%s" %b "%R" "%u"
```

**Comment by davidsayre** [comment]
The format I'm using to parse poud.log (which derived from syslog format)

`goaccess -f pound.log --log-format='%^ %^ %^ %^ %^: %v %h - - [%d:%t %^] [[%^][%^] "%r" %s %b "%R" "%u"' --time-format='%H:%M:%S' --date-format='%d/%b/%Y'`
