### ISSUE TITLE
Gandi.net - simplehosting - parsing access.log

### ISSUE THREAD

**Issue by RolandTi** [allinurl/goaccess#2501]
Hello, I'm using the simplehosting solution from gandi.net.
I'm in trouble because they use a custom template for access.log : 
```LogFormat "%V %a %l %u %t (%T s) \"%r\" %>s %b \"%{Referer}i\" \"%{User-agent}i\"" vhost_paas```
eg : 
`domain.fr 43.130.00.000 - - [12/Apr/2023:15:07:52 +0000] (0 s) "GET /files/ HTTP/1.1" 404 196 "binance.com" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.85 Safari/537.36"`

So I tried
`goaccess /Volumes/XX/access.log --log-format="%V %a %l %u %t (%T s) "%r" %>s %b "%{Referer}i" "%{User-agent}i"" vhost_paas --datetime-format=%d/%b/%Y:%H:%M:%S %z`
that give me `Token '[10/Apr/2023:06:59:08' doesn't match specifier '%t` I tried many options with --date and --time from previous issues without success.

I'm on a mac, using french locale and installed goaccess with brew.

Thanks in advance.

**Comment by allinurl** [comment]
Please try:

    goaccess access.log --log-format='%v %h %^[%d:%t %^] (%T %^) "%r" %s %b "%R" "%u"' --date-format=%d/%b/%Y --time-format=%T

You may need to use:

    LC_TIME="en_US.UTF-8" goaccess log --log-format='%v %h %^[%d:%t %^] (%T %^) "%r" %s %b "%R" "%u"' --date-format=%d/%b/%Y --time-format=%T

**Comment by RolandTi** [comment]
Hello allinurl ! You're right with the LC_TIME, thank you very much !

**Comment by allinurl** [comment]
@RolandTi Glad that did the job! Let me know if you have any other questions
