### ISSUE TITLE
Working on Ubuntu: File does not exist on the server, how to create it If so, where to upload the same?

### ISSUE THREAD

**Issue by SplendidDigital** [allinurl/goaccess#2513]
Trying to implement GoAccess to my WordPress sites that are hosted on AWS Lightsail (Plesk Ubuntu instance). Here is the [tutorial](https://www.digitalocean.com/community/tutorials/how-to-install-and-use-goaccess-web-log-analyzer-on-ubuntu-20-04) by DigitalOcean I am following:

r/Wordpress - Working on Ubuntu: File does not exist on the server, how to create it
I am stuck on Note: If this file does not exist on the server, ensure to create it first and populate it with the contents of the

goaccess.conf
file on [GitHub](https://github.com/allinurl/goaccess/blob/v1.4/config/goaccess.conf).

Do I need to download the file (could not find any download button below)?

r/Wordpress - Working on Ubuntu: File does not exist on the server, how to create it
If so, where to upload the same?

**Comment by allinurl** [comment]
You have the option to directly execute GoAccess with inline options, eliminating the need to modify the configuration file. For example:

    goaccess /var/log/apache2/access.log --log-format=VCOMBINED

If your log format is customized, you can specify the `--log-format`, `--date-format`, and `--time-format` options accordingly. Please let me know if this information is helpful.
