### ISSUE TITLE
==1975== Format Errors - Verify your log/date/time format

### ISSUE THREAD

**Issue by zwb993** [allinurl/goaccess#2516]
When using GoAccess to analyze log files, this error showing "==1975== Format Errors - Verify your log/date/time format".
command:
`/usr/local/bin/goaccess /var/log/httpd/ssl_access_log --log-format='%h %^[%d:%t %^] "%r" "%s" %b' --date-format=%d/%b/%Y --time-format=%T -o /mnt/redeploy/report.html`
apache Logs:
`10.13.35.24 - - [29/May/2023:08:58:23 +0800] "POST /user-login.html HTTP/1.1" 200 58`

**Comment by allinurl** [comment]
I'd run it as:

    goaccess access.log --log-format=COMMON

**Comment by zwb993** [comment]
it works, thank you!
