### ISSUE TITLE
Can't get goaccess to load custom Apache log format, getting  'IPv4/6 is required.'

### ISSUE THREAD

**Issue by docouto** [allinurl/goaccess#2519]
I posted a comment on [this ](https://github.com/allinurl/goaccess/issues/1652#issuecomment-1580952402) entry, but thought to open a new issue.

I got goaccess installed on WSL running Ubuntu, and I am trying to analyze the following formatted access.log from Apache.

_"[06/May/2023:08:52:58 -0300]" "187.12.179.162" "POST /app/index.php/fila/filaPorPaciente HTTP/1.1" "200" "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36 Edg/112.0.1722.68" "TLSv1.2" "ECDHE-RSA-AES256-GCM-SHA384" "0" "98863"
"[06/May/2023:08:52:58 -0300]" "200.219.243.171" "GET /age_marcar.php?P=age_marcar HTTP/1.1" "200" "46999" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36" "TLSv1.2" "ECDHE-RSA-AES256-GCM-SHA384" "0" "70041"_

My last command trying to get this to work was: 

`goaccess --log-format='"\"%t\" \"%a\" \"%r\" \"%>s\" \"%b\" \"%{User-Agent}i\" %^ "'  --date-format=%d/%b/%Y --time-format=%t accesslogfile.log --no-ip-validation`

This what I get:

![image](https://github.com/allinurl/goaccess/assets/9469339/215aef17-eb17-42fb-bf71-1fce66287838)

I saw @allinurl saying on another issue to build the package with --no-ip-validation, that the case yet? I got goaccess installed using apt-get.

Cheers.

**Comment by allinurl** [comment]
Apologies for the delay, I completely overlooked this post. The following solution should be effective (assuming the last field represents the time taken in microseconds):

    goaccess access.log --log-format='"[%d:%t %^]" "%h" "%r" "%s" "%b" "%u" "%K" "%k" %^ "%D"' --date-format=%d/%b/%Y --time-format=%T

![2023-07-14-080628_759x321_scrot](https://github.com/allinurl/goaccess/assets/5005367/00dcfe06-bd82-4eeb-8072-2516737950ff)

**Comment by docouto** [comment]
Hey @allinurl no worries. 
The way you put it explained what I was missing, thanks for that! It worked like a charm!
