### ISSUE TITLE
HTML report file is not updated after new log appears (docker deployment)

### ISSUE THREAD

**Issue by shalak** [allinurl/goaccess#2522]
To reproduce deploy `goaccess` via `docker-compose.yaml`:

```yam
version: "3"
services:
  caddy:
    image: allinurl/goaccess:latest
    ports:
      - 7890:7890
    restart: unless-stopped
    container_name: goaccess
    volumes:
      - /path/to/config:/config
      - /path/to/caddy/logdir:/caddy
      - /path/to/caddy/sites:/sites
    command: --no-global-config --config-file=/config/goaccess.conf
```

Set up the following `/path/to/config/goaccess.conf`:

```
log-file /caddy/access.log
log-format CADDY
output /sites/report.html
real-time-html true
port 7890
addr 0.0.0.0
```

Host the `/sites/report.html` via caddy and visit the page.

Expected:
- HTML report is updated every second

Actual
- HTML report is updated only on container restart

I did some troubleshooting and I `docker exec`'ed into the `goaccess` container - it sees the `access.log` updating live, but the `report.html` is not updated unless I restart the container.

**Comment by shalak** [comment]
```
# docker exec -it goaccess sh
/ # goaccess --version
GoAccess - 1.7.2.
For more details visit: https://goaccess.io/
Copyright (C) 2009-2023 by Gerardo Orellana

Build configure arguments:
  --enable-geoip=mmdb
  --with-openssl
```

**Comment by allinurl** [comment]
Have you experimented with this docker-compose configuration [file](https://github.com/allinurl/goaccess/issues/2498#issuecomment-1493186538)? Let me know if that helps.

**Comment by shalak** [comment]
From what I see it's no different than my configuration. The only difference in their config:

```
    command: "/var/log/caddy/ezytor.access.log /var/log/caddy/flowgiri.access.log --log-format=CADDY -o /var/www/goaccess/index.html --real-time-html --ws-url=wss://robot-log.besnik.net:443/ws --port=9871"
```

Is that they set a custom ws-url. I'm not using the websocket feature at all, I don't see how this should change anything 🤔 I don't have any `/ws` endpoint exposed anywhere, so I wouldn't even know what to set it to...

The problem they had is because they were passing a shell command (`bash`) to docker entry point, which is already set in the image to `goaccess`, so the only thing you can add are the parameters for said `goaccess` binary.

**Comment by allinurl** [comment]
If you access the container through a shell and execute the command `tail -f /caddy/access.log`, does the log update as expected? Additionally, when you view the report.html, do you see a green dot on the left-side navigation bar? If not, please check the browser's console for any potential error messages.

**Comment by shalak** [comment]
> does the log update as expected?

Yes, it does

> do you see a green dot on the left-side navigation bar

I don't! Ok, we're getting somewhere. The console log says:

```
Firefox can’t establish a connection to the server at wss://goaccess.mydomain.net:7890/.
```

The request itself looks like this:

```
GET
    wss://goaccess.mydomain.net:7890/
Transferred0 B (0 B size)

        
    Accept
        */*
    Accept-Encoding
        gzip, deflate, br
    Accept-Language
        en-US,en;q=0.7,pl;q=0.3
    Cache-Control
        no-cache
    Connection
        keep-alive, Upgrade
    DNT
        1
    Host
        goaccess.mydomain.net:7890
    Origin
        https://goaccess.mydomain.net
    Pragma
        no-cache
    Sec-Fetch-Dest
        websocket
    Sec-Fetch-Mode
        websocket
    Sec-Fetch-Site
        same-site
    Sec-WebSocket-Extensions
        permessage-deflate
    Sec-WebSocket-Key
        <SOME_TOKEN>
    Sec-WebSocket-Version
        13
    Upgrade
        websocket
    User-Agent
        Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/114.0
```

The `goaccess.mydomain.net` resolves to the docker host on which I exposed the 7890 port from goaccess container, and the port seems to be open:

```
$ nmap goaccess.mydomain.net -Pn -p 7890
Starting Nmap 7.94 ( https://nmap.org ) at 2023-06-14 03:52 CEST
Nmap scan report for goaccess.mydomain.net (10.0.0.5)
Host is up (0.0040s latency).

PORT     STATE SERVICE
7890/tcp open  unknown

Nmap done: 1 IP address (1 host up) scanned in 0.03 seconds
```



What can be wrong?

**Comment by allinurl** [comment]
Great! I'm glad that did the job, and thank you for sharing those helpful details.
