### ISSUE TITLE
Can't bind the listener server to IPv4 and IPv6 (dual stack)

### ISSUE THREAD

**Issue by paolokappa** [allinurl/goaccess#2523]
I am trying to figure out if there is a possibility to bind GoAccess, simultaneously, on both IPv4 and IPv6.
Reading the GWSocket documentation, I saw that by default, he listens on port 7890 on all the interfaces, e.g., 127.0.0.1, ::1, etc.
Whereas in the GoAccess documentation, binding is only possible on a stack.
I tried adding a second line with IPv6 but it only gets the last line.
Am I doing something wrong or is it not dual stack for the time being?
Thank you very much for the answer.

Paolo Caparrelli
GOLINE SA
IT Services

**Comment by allinurl** [comment]
Thank you for bringing this up. I have implemented some changes upstream. Could you please build from the [**development**](https://github.com/allinurl/goaccess#build-from-github-development) and see if this resolves the dual stack issue? Please let me know the outcome.

**Comment by paolokappa** [comment]
Hi Gerardo,

I ran the test you suggested, downloading goaccess from GitHub (Development). 
After fixing all the dependencies I restarted the service, which starts regularly but the wss service no longer responds to requests and so, the green dot, remains off of course (it goes neither IPv4 nor in IPv6).
Then I tried changing the binding on the port but nothing.

At the current state and even before it was like that:

######################################
# Server Options
######################################

# Specify IP address to bind server to.
#
#addr 0.0.0.0

So, with the previous version, it binds to the IPv4 of the Ubuntu server but not on the IPv6 address.
With the change you made, it no longer works on either IPv4 or IPv6 :)
So I re-did the rollback and restarted the service and it still works in IPv4...
When you want to do another test tell me and we will try it.

Thanks!

Paolo Caparrelli
GOLINE SA

**Comment by allinurl** [comment]
Have you attempted to establish a connection to https://rt.goaccess.io/ using IPv6? It should handle the connection based on that last commit. If you wish to support dual stack, please utilize `--addr=::` instead of the default `--addr=0.0.0.0`.

**Comment by paolokappa** [comment]
I confirm that with addr :: it works perfectly!
Both in IPv4 and in IPv6.
Maybe you should add this information in the documentation :)
Thank you very much for your help.

Paolo Caparrelli
GOLINE SA

**Comment by allinurl** [comment]
@paolokappa As per your suggestion, I've included notes in the man page for version 1.8. Thank you once again.
