### ISSUE TITLE
`bookworm` debian release missing

### ISSUE THREAD

**Issue by dameyerdave** [allinurl/goaccess#2524]
Since Debian has release `bookworm` the official Debian installation procedure fails with an error similar to 
```
E: The repository 'https://deb.goaccess.io/ bookworm Release' does not have a Release file.
```
It would be nice to add this to your https://deb.goaccess.io site.

Many thanks

**Comment by tobias992** [comment]
Any news here guys?

**Comment by allinurl** [comment]
Sorry for the delay, and thanks for letting me know. Good news! bookworm is now available in the deb repository. Let me know if that works from your end.

**Comment by twiddern** [comment]
On my bookworm machine I see dependency issues

```
$ apt install goaccess 

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 goaccess : Depends: libssl1.1 (>= 1.1.0) but it is not installable
E: Unable to correct problems, you have held broken packages.
```

**Comment by kidzen** [comment]
same here

> On my bookworm machine I see dependency issues
> 
> ```
> $ apt install goaccess 
> 
> Reading package lists... Done
> Building dependency tree... Done
> Reading state information... Done
> Some packages could not be installed. This may mean that you have
> requested an impossible situation or if you are using the unstable
> distribution that some required packages have not yet been created
> or been moved out of Incoming.
> The following information may help to resolve the situation:
> 
> The following packages have unmet dependencies:
>  goaccess : Depends: libssl1.1 (>= 1.1.0) but it is not installable
> E: Unable to correct problems, you have held broken packages.
> ```

+1

**Comment by 4oo4** [comment]
Workaround for now is to either leave `libssl1.1` installed when upgrading to bookworm, or if you accidentally autoremoved it like I did, to install it directly from the .deb (which has no other deps and doesn't seem to conflict with `libssl3`).

https://packages.debian.org/bullseye/amd64/libssl1.1/download

```
wget http://security.debian.org/debian-security/pool/updates/main/o/openssl/libssl1.1_1.1.1n-0+deb11u5_amd64.deb
dpkg -i libssl1.1_1.1.1n-0+deb11u5_amd64.deb
```

**Comment by allinurl** [comment]
Just to double-check, on bookworm, the package should be `libssl3` instead of `libssl1.1`, right?

**Comment by thompol** [comment]
> Just to double-check, on bookworm, the package should be `libssl3` instead of `libssl1.1`, right?

I suppose so. When do you expect a fix to be released?

**Comment by allinurl** [comment]
Feel free to give it a try again; it should work this time. Keep me posted. Thanks!

**Comment by twiddern** [comment]
Can confirm, no dependency issue anymore for the bookworm package. Thank you!

**Comment by allinurl** [comment]
Thanks for the update!
