### ISSUE TITLE
Help with log format 

### ISSUE THREAD

**Issue by KhaiPhanTran** [allinurl/goaccess#2528]
I cannot figure out the format for the httpd in this link
https://gerrit-review.googlesource.com/Documentation/logs.html
I am new to working with log format, is there any resource that can help me with figuring out how to write my own format?

**Comment by allinurl** [comment]
Are you using the exact same format?

    12.34.56.78 [HTTP-4136374] - johndoe [28/Aug/2020:10:02:20 +0200] "GET /a/plugins/metrics-reporter-prometheus/metrics HTTP/1.1" 200 1247498 1900 - "Prometheus/2.13.1"

**Comment by KhaiPhanTran** [comment]
> Are you using the exact same format?
> 
> ```
> 12.34.56.78 [HTTP-4136374] - johndoe [28/Aug/2020:10:02:20 +0200] "GET /a/plugins/metrics-reporter-prometheus/metrics HTTP/1.1" 200 1247498 1900 - "Prometheus/2.13.1"
> ```

Yes, except my time format is in iso format I believe (31227
), which i don't know how to handle.
example: 110.79.165.200 [HTTP-187] - somejenkins [2023-06-11T00:00:00.061+02:00] "GET /a/changes/?q=commit:178236786123ghjgd1e09a&o=ALL_REVISIONS HTTP/1.1" 202 1251 272 - "curl/7.82.1" 18 20 6641936 -

**Comment by allinurl** [comment]
Sorry for taking a while to get back to you. This solution does the trick for me:

    goaccess access.log --log-format='%h [%^] %^ %e [%dT%t.%^] "%r" %s %b %T %R "%u" %^' --date-format=%Y-%m-%d --time-format=%T

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
