### ISSUE TITLE
How to make work in cron

### ISSUE THREAD

**Issue by mabushey** [allinurl/goaccess#253]
This should probably be in the FAQ. 

My cron entry is:

    0 8 * * * /usr/local/bin/goaccess -p /etc/goaccess.conf -f /var/log/`/bin/date +%Y-%m`/nginx/www.access.log > /var/www/html/goaccess.example.com/index.html

It does not work, but if I copy and paste from the 6th field on it runs fine. I have backticks around the date command, I don't know what goofy formatting github is doing.

**Comment by allinurl** [comment]
What output do you get? [This](http://askubuntu.com/a/330717) may help. Let me know if that does it. Thanks.

**Comment by mabushey** [comment]
That link is 100% wrong. Catting the log into goaccess with stdin does NOT work.

This works:
 /usr/local/bin/goaccess -p /etc/goaccess.conf -f /var/log/2015-05/nginx/www.access.log > /var/www/html/goaccess.site.com/index.html

This does not:
/usr/local/bin/goaccess -p /etc/goaccess.conf -f /var/log/`/bin/date +%Y-%m`/nginx/www.access.log > /var/www/html/goaccess.site.com/index.html

I wish goaccess was more friendly to cron runs. Looks like I need to make a php page with a big button that says "run goaccess"

**Comment by mabushey** [comment]
I wish goaccess would just look at /etc/goaccess.conf by default on it's own.

**Comment by allinurl** [comment]
goaccess does look at `%sysconfdir%/goaccess.conf` where `%sysconfdir%` is system dependent. So if `-p` is not used, it fallback to global config file, or it attempts to use the user's config file, i.e., `~/.goaccessrc`.

As far as using `date` in the cron, it actually depends on the particular crob. You could try the following:

    cat access.log | goaccess -p /etc/goaccess.conf > "/srv/www/stats/$(date +\%Y-\%m-\%d).html"

**Comment by allinurl** [comment]
Note, `%sysconfdir%` is either `/etc/`, `/usr/etc/` or `/usr/local/etc/`.

**Comment by mabushey** [comment]
Thank you! This is working:

0 8 * * * /usr/local/bin/goaccess -p /etc/goaccess.conf -f /var/log/$(/bin/date +\%Y-\%m)/nginx/www.access.log > /var/www/html/goaccess.site.com/index.html

My problems were #1: that backticks don't work, but the $() syntax does. #2 I couldn't get "cat /var/log... | " to work, but "-f /var/log/..." does.

All is good, thanks again for your help. :)
