### ISSUE TITLE
GoAccess: Failure to launch (ERR: 1475, 2150, 2195)

### ISSUE THREAD

**Issue by Harleythetech** [allinurl/goaccess#2531]
I'm currently trying to run GoAccess on Termux and everytime i try to launch it, this error is what it returns

```
GoAccess - version 1.7.2 - Apr 18 2023 10:02:21
Config file: /data/data/com.termux/files/usr/etc/goaccess/goaccess.conf

Fatal error has occurred
Error occurred at: src/goaccess.c - initializer - 1475
No input data was provided nor there's data to restore.
```

i don't have any clue as to what this is nor do logs even work.

```
$ goaccess access.log --log-format='%d %t %^: %^: %^: %h, %^: %v, %^: "%r" %^: %^: "%R"' --date-format=%Y/%m/%d --time-format=%T

GoAccess - version 1.7.2 - Apr 18 2023 10:02:22
Config file: /data/data/com.termux/files/usr/etc/goaccess/goaccess.conf

Fatal error has occurred
Error occurred at: src/parser.c - read_log - 2150
Unable to open the specified log file 'access.log'. No such file or directory
```
```
 goaccess access.log -o report.html --real-time-html --addr=192.168.8.102
 [SETTING UP STORAGE access.log] {0} @ {0/s}
GoAccess - version 1.7.2 - Apr 18 2023 10:02:22
Config file: /data/data/com.termux/files/usr/etc/goaccess/goaccess.conf

Fatal error has occurred
Error occurred at: src/parser.c - parse_log - 2195
No time format was found on your conf file.
```
what seems to be the issue?

**Comment by allinurl** [comment]
Based on the error messages you provided, it appears that the access log is missing and your `/data/data/com.termux/files/usr/etc/goaccess/goaccess.conf` file doesn't have the date/time/log format specified. Additionally, it seems like you are encountering different errors. Could you please clarify which specific error you are currently experiencing?

**Comment by Harleythetech** [comment]
The main issue that im currently i experiencing is the error code 1475. every time i want to host a http server to monitor the system perf it just throws this error

```
GoAccess - version 1.7.2 - Apr 18 2023 10:02:21
Config file: /data/data/com.termux/files/usr/etc/goaccess/goaccess.conf

Fatal error has occurred
Error occurred at: src/goaccess.c - initializer - 1475
No input data was provided nor there's data to restore.
```

Note: This is running on termux (ARM)

**Comment by allinurl** [comment]
The error message indicates that you haven't provided a log file or any data that GoAccess can read. Make sure to specify a valid log file for GoAccess to process.

**Comment by Krulle86** [comment]
Same issue here.
If i want to set the format with terminal 
`goaccess access.log -c`

it ends up with
```
GoAccess - version 1.7 - Jan  4 2023 18:36:47
Config file: /etc/goaccess/goaccess.conf

Fatal error has occurred
Error occurred at: src/parser.c - read_log - 2071
Unable to open the specified log file 'access.log'. No such file or directory
```

Where is the file access.log located and is it recommendable to create a new one manually?

**Comment by jemaleddin** [comment]
I am also encountering this error, but only when running from cron. I have a shell script that runs and works on the command line, but throws this exact error under version 1.8:

> GoAccess - version 1.8 - Sep 30 2023 21:41:52
> Config file: /etc/goaccess/goaccess.conf

> Fatal error has occurred
> Error occurred at: src/goaccess.c - initializer - 1475
> No input data was provided nor there's data to restore.

I am running the same command 4 times pointing to different log names and different output files. It’s just zcat piping the files to goaccess with the combined log output format.  Any help would be appreciated.

**Comment by allinurl** [comment]
@jemaleddin, could you please share the precise commands you've been executing? The [error message](https://github.com/allinurl/goaccess/blob/master/src/parser.c#L195) is pretty much indicating that no log was provided. Thanks

**Comment by jemaleddin** [comment]
The command is:

`zcat -f /var/log/nginx/jemal.co.access.log* | goaccess -o /var/www/html/jemal.co/site/stat-report.html --log-format=COMBINED`

And to be super clear, the command runs perfectly fine in.a terminal as my user, as root, etc. - [as seen here](https://jemal.co/stat-report.html).

**Comment by allinurl** [comment]
Please be sure to use the hyphen (`-`) when piping data into goaccess. This will enable it to read from stdin. For example:

    zcat -f /var/log/nginx/jemal.co.access.log* | goaccess - -o /var/www/html/jemal.co/site/stat-report.html --log-format=COMBINED

**Comment by jemaleddin** [comment]
Oh wow - that totally fixed it. I read through the help info on the command line and totally missed that. Thanks so much for much for your assistance -  I really appreciate it!

**Comment by allinurl** [comment]
@jemaleddin Glad that did the job :) Let me know if you have any other questions!
