### ISSUE TITLE
Goaccess error - not showing report.html

### ISSUE THREAD

**Issue by oceanhawk** [allinurl/goaccess#2533]
I am trying to analyse my apache log files with goaccess.

```
url.com - "ProxyBy: 212.25.2.10" - - [16/Jun/2023:06:25:28 +0200] "GET / HTTP/1.1" 303 - "-" "Zabbix" 0 + 127.0.0.1:8080
urlc.om - "ProxyBy: 101.198.0.152" - - [16/Jun/2023:06:25:30 +0200] "GET / HTTP/1.1" 302 20 "url.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_0) AppleWebKit/535.11 (KHTML, like Gecko) Chrome/17.0.963.56 Safari/535.11" 0 + 127.0.0.1:8080
```

When parsing them through with the log format parameter and date-format parameter I am getting this error:

=19527== Token '-' doesn't match specifier '%h'
==19527== Token '-' doesn't match specifier '%h'
==19527== Token '-' doesn't match specifier '%h'
==19527== Token '-' doesn't match specifier '%h'
==19527==
==19527== Format Errors - Verify your log/date/time format

What is the right command to display the contents of the logs in goaccess?

Interestingly enough for the same log format:

```
URL.com - "ProxyBy: 178.197.193.169" - - [19/Jun/2023:06:25:18 +0200] "GET / HTTP/1.1" 303 20 "https://www.google.com/" "Mozilla/5.0 (Linux; Android 13; SAMSUNG SM-G981B) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/21.0 Chrome/110.0.5481.154 Mobile Safari/537.36" 0 + 127.0.0.1:8080
url.com - "ProxyBy: 165.225.94.238" - - [19/Jun/2023:06:25:18 +0200] "GET /uploads/xxxxxxxxxxxxxx_mbs5/24700100/2023W23-de_24700100.pdf?contentID=8bab34b4-c617-4b19-926c-02a5251c376c&zoneID=svg_1 HTTP/1.1" 200 64302 "-" "Mozilla/5.0 (X11; Linux i686 (x86_64)) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36" 0 + 127.0.0.1:8080
```

this command works:

goaccess 1906 --log-format='%v %h %^[%d:%t %^] (%T s) "%r" %s %b "%R" "%u"' --date-format=%d/%b/%Y --time-format=%T -o report1.html

**Comment by allinurl** [comment]
The following works for me, let me know how it goes:

    goaccess access.log --log-format='%v %^: %h" %^[%d:%t %^] "%r" %s %b "%R" "%u" %^' --date-format=%d/%b/%Y --time-format=%T

**Comment by oceanhawk** [comment]
Thank you, that worked!

Any idea, why in my report I get so many failed requests? Even though alot of them are 200,302 etc. Status codes.  I have tried rebuilding with --with-getline, but am getting the same amount of failed requests. 

![image](https://github.com/allinurl/goaccess/assets/87807895/bb1b90a7-5052-49dc-9f8b-d775a91a7db7)

**Comment by allinurl** [comment]
Are you certain that all the lines in the log adhere to a consistent log format? You can also try:

    awk '{ if (length > max) { max = length; line = NR } } END { print "Maximum line length:", max; print "Line number:", line }' file.txt

**Comment by oceanhawk** [comment]
This is the response I am getting when executing the command above:

Maximum line length: 3691
Line number: 29001


No unfortunately there are a lot of crawlers indexing the webserver, and additionally I have requests like this e.g:


IP - - [19/Jun/2023:06:25:06 +0200] "GET /typo3conf/ext/netv_svg_menu/menu_xmlexp/menuexport.xml.php?hyphens=1&branch=4530&authstring=wagner_visuell@QtAAx30LshwrsGEUenETSJldnhv1jK3iyM354VVKgjFgOF4BllnqswKXetKtDDRE&monday=20230619&lang=ge HTTP/1.0" 200 11869 "-" "-" "-"

**Comment by allinurl** [comment]
Without access to the log file, it's difficult to determine the exact cause. If you're encountering numerous invalid requests, one approach could be to extract a smaller subset of lines from your access log and parse them with GoAccess. This can help in identifying any potential issues or patterns.

    tail -50 /var/log/apache2/access.log > sample.log

Then, you should be able to obtain a few invalid lines and make a more accurate determination of the issue. Please feel free to attach the sample log here, and I'll take a look.

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
