### ISSUE TITLE
Token '0' doesn't match specifier '%m' Logs RPM

### ISSUE THREAD

**Issue by gentilsol** [allinurl/goaccess#2537]
Hello 
I have updated today go accsess.

Now i have a problem with the reverse proxy manager logs. 
if i start the container i have this logs:

==87== FILE: /opt/log/proxy-host-1_access.log
==87== Parsed 20 lines producing the following errors:
==87==
==87== Token '0' doesn't match specifier '%m'
==87== Token '1' doesn't match specifier '%m'
==87== Token '4' doesn't match specifier '%m'
==87== Token '4' doesn't match specifier '%m'
==87== Token '0' doesn't match specifier '%m'
==87== Token '0' doesn't match specifier '%m'
==87== Token '0' doesn't match specifier '%m'
==87== Token '0' doesn't match specifier '%m'
==87== Token '0' doesn't match specifier '%m'
==87== Token '0' doesn't match specifier '%m'
==87== Token '0' doesn't match specifier '%m'
==87== Token '0' doesn't match specifier '%m'
==87== Token '0' doesn't match specifier '%m'
==87== Token '0' doesn't match specifier '%m'
==87== Token '0' doesn't match specifier '%m'
==87== Token '0' doesn't match specifier '%m'
==87== Token '0' doesn't match specifier '%m'
==87== Token '0' doesn't match specifier '%m'
==87== Token '0' doesn't match specifier '%m'
==87== Token '0' doesn't match specifier '%m'
==87==
==87== Format Errors - Verify your log/date/time format

can you help me with this issues?

**Comment by allinurl** [comment]
Seems like you might be using the wrong log format. Mind sharing a few lines from your log? I can take a look and help you out.

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
