### ISSUE TITLE
bash: /usr/bin/find: Argument list too long

### ISSUE THREAD

**Issue by CloudShubham** [allinurl/goaccess#2538]
I have about 27000 logs file and need to parse them in one time.
every time i run this command 
goaccess  /home/goaccess/part/2/*.log --log-format='%^ %dT%t.%^ %v %h:%^ %^ %^ %T %^ %s %^ %^ %b "%r" "%u" %k %K %^' -o /var/www/html/index.html --date-format=%Y-%m-%d --time-format=%T

it says 
bash: /usr/bin/find: Argument list too long

please help me....need to do this urgently.

**Comment by allinurl** [comment]
You probably want to cat them all and pipe that to goaccess. e.g.,

    cat /home/goaccess/part/2/*.log | goaccess - --log-format='%^ %dT%t.%^ %v %h:%^ %^ %^ %T %^ %s %^ %^ %b "%r" "%u" %k %K %^' -o /var/www/html/index.html --date-format=%Y-%m-%d --time-format=%T

**Comment by CloudShubham** [comment]
> You probably want to cat them all and pipe that to goaccess. e.g.,
> 
> ```
> cat /home/goaccess/part/2/*.log | goaccess - --log-format='%^ %dT%t.%^ %v %h:%^ %^ %^ %T %^ %s %^ %^ %b "%r" "%u" %k %K %^' -o /var/www/html/index.html --date-format=%Y-%m-%d --time-format=%T
> ```

Ok i will try that

**Comment by 0bi-w6n-K3nobi** [comment]
Hi.

If you use `BASH` Shell must be work. But, `CSH` possibly NOT.

**Comment by allinurl** [comment]
Closing this. Feel free to reopen if necessary.
