### ISSUE TITLE
Getting error in go access

### ISSUE THREAD

**Issue by Arun2536IT** [allinurl/goaccess#2539]
Good afternoon, please help me to solve the issue.

time-format %T
date-format %d/%b/%Y:%T %z
log-format %h %^[%d:%t %^] "%m %U" %s %b "%R" "%u"

my log syntax :

    Jul 26 13:13:49 Host ip hostIP InternalIP - - [26/Jul/2023:13:13:49 +0530] "POST /ajaxfile.php?sFlag=module HTTP/L.1" 200 4 "URL" "Mozilla/5.0 (Windows NT 10.0;‘Win; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safaril537.36"

the error I am receiving :
ubuntu@ip-10-0-0-210:~$ sudo goaccess /var/log/dh/combined.log -o stats.html
 [SETTING UP STORAGE /var/log/dh/combined.log] {0} @ {0/s}
Cleaning up resources...
==788547== GoAccess - version 1.7.2 - Apr  1 2023 00:42:46
==788547== Config file: /etc/goaccess/goaccess.conf
==788547== https://goaccess.io - <hello@goaccess.io>
==788547== Released under the MIT License.
==788547==
==788547== FILE: /var/log/dh/dh_access_logs_combined.log
==788547== Parsed 10 lines producing the following errors:
==788547==
==788547== Token 'Jul' doesn't match specifier '%h'
==788547== Token 'Jul' doesn't match specifier '%h'
==788547== Token 'Jul' doesn't match specifier '%h'
==788547== Token 'Jul' doesn't match specifier '%h'
==788547== Token 'Jul' doesn't match specifier '%h'
==788547== Token 'Jul' doesn't match specifier '%h'
==788547== Token 'Jul' doesn't match specifier '%h'
==788547== Token 'Jul' doesn't match specifier '%h'
==788547== Token 'Jul' doesn't match specifier '%h'
==788547== Token 'Jul' doesn't match specifier '%h'
==788547==
==788547== Format Errors - Verify your log/date/time format

**Comment by allinurl** [comment]
The representation of Host ip, hostIP, and InternalIP is somewhat unclear. Could you please provide the actual lines from your log? Feel free to replace the IPs with local IPs like 192.168.0.1, 192.168.0.2, etc.

**Comment by Arun2536IT** [comment]
this issue is been solved, thanks for your help[

**Comment by allinurl** [comment]
I'm glad that resolved the issue. Happy to help!
