### ISSUE TITLE
Rewind persisted db to remove corrupted entries

### ISSUE THREAD

**Issue by chr15m** [allinurl/goaccess#2540]
I managed to run my background analytics job twice at the same time and now I have a bunch of data for "hits" that appears to be double counted (there is an obvious segment of the chart where the "hits" line is twice the height of before and after). I was wondering if it's possible for me to rewind the persisted database to some date so I can re-run goaccess over the original logfiles to reprocess that data? Thanks so much!

**Comment by allinurl** [comment]
Unfortunately you can't rewind the database. All the data gets aggregated as it's inserted. Do you still have the logs available?

**Comment by chr15m** [comment]
Ok thanks, I'll rebuild using the original logs.
