### ISSUE TITLE
What is %C stand for

### ISSUE THREAD

**Issue by Lvshujun0918** [allinurl/goaccess#2542]
In your manual page, I saw "%C" which means "The cache status of the object the server served." as SPECIFIERS. But I still don't understand what it is refer. I try to use it as Cache-Control(like "no-cache, must-revalidate, max-age=0"), but it didn't work, because in "THE CACHE STATUS OF THE OBJECT SERVED" of the output html, it said "No data on this panel."
I'm using server litespeed and the log is the same as apache, so what is the "%C"SPECIFIERS in Apache LogFormat? I need help, much thanks.
PS: I'm Chinese, so my English maybe poor, sorry.

**Comment by allinurl** [comment]
The cache status pertains to various states that cached data can take on, such as HIT, MISS, STALE, among others. I don't see any cache status in your log though.

**Comment by Lvshujun0918** [comment]
That's it. I missunderstood it. Very thanks!
