### ISSUE TITLE
Support QUIC

### ISSUE THREAD

**Issue by Lvshujun0918** [allinurl/goaccess#2544]
If I use HTTP/3, then the "%{SSL_PROTOCOL}e" will be "QUIC", it hasn't be supported now.

**Comment by allinurl** [comment]
Are you encountering an error message or experiencing any issues? It's worth noting that it should indeed [support](https://github.com/allinurl/goaccess/blob/master/src/gstorage.c#L130) HTTP/3.

**Comment by Lvshujun0918** [comment]
No, I think I don't make it clear. In the output html>"ENCRYPTION SETTINGS(TLS VERSION AND PICKED ALGORITHM) section, I only see something like TLSv1.3 or TLSv1.2 etc. But when using HTTP/3, this value should be QUIC, it is in my log, but don't show on the html. Is it thrown away occasionally? Maybe there is some mistake.

**Comment by Lvshujun0918** [comment]
No, I think I don't make it clear. In the output html>"ENCRYPTION SETTINGS(TLS VERSION AND PICKED ALGORITHM) section, I only see something like TLSv1.3 or TLSv1.2 etc. But when using HTTP/3, this value should be QUIC, it is in my log, but don't show on the html. Is it thrown away occasionally? Maybe there is some mistake.

**Comment by Lvshujun0918** [comment]
![image](https://github.com/allinurl/goaccess/assets/41245552/267d7460-2640-418c-97d5-c4fc25c467d2)

**Comment by Lvshujun0918** [comment]
![image](https://github.com/allinurl/goaccess/assets/41245552/96e14265-616f-4554-9c98-bb4437eddd81)

**Comment by allinurl** [comment]
Please post those lines from your log in here. Thanks

**Comment by Lvshujun0918** [comment]
```
["Wordpress"] [13/Aug/2023:22:34:11 +0800] 115.194.113.5 GET **URL_HIDE** HTTP/1.1 200 **QUIC** TLS_AES_128_GCM_SHA256 "text/html; charset=UTF-8" "-" 47546B 131417us "**REFFER_HIDE**" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36 Edg/115.0.1901.203"
```

**Comment by Lvshujun0918** [comment]
https://github.com/allinurl/goaccess/issues/2542#issuecomment-1670790617
Above is my log format.

**Comment by allinurl** [comment]
Could you share the exact line from your access log? I'm trying to determine whether there are any delimiters around those fields. Feel free to replace the URLs with random ones if necessary.

**Comment by Lvshujun0918** [comment]
Sorry, but I don't understand. Above there are already lines which %{SSL_CIPHER}e is "QUIC", but there are none in my output report.
Whatever, here is my log example.
---
["Cloudreve"] [16/Aug/2023:13:51:00 +0800] 115.192.155.77 GET /service-worker.js HTTP/1.1 200 QUIC TLS_AES_128_GCM_SHA256 "text/javascript; charset=utf-8" "-" 708B 18689us "https://***.cszj.wang/service-worker.js" "Mozilla/5.0 (Windws NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36 Edg/117.0.0.0"

**Comment by allinurl** [comment]
I see. QUIC is not classified as an SSL protocol; rather, it functions as a transport-layer protocol. In the context of goaccess, when it encounters a cipher, it attempts to determine the relevant SSL protocol to ensure accurate reporting. A possible solution would involve utilizing an alternative unused specifier, such as `%e`. e.g,:

    goaccess access.log --log-format='["%v"] [%x] %h %m %U %H %s %^ %e "%M" %^ %bB %Dus "%R" "%u"' --datetime-format='%d/%b/%Y:%H:%M:%S %z'

![2023-08-16-212436_589x544_scrot](https://github.com/allinurl/goaccess/assets/5005367/7cedce6e-1658-4522-a092-ed5a9ff08668)


Let me know if that helps.

**Comment by Lvshujun0918** [comment]
Very thanks, it does work. But I have no idea why %{SSL_CIPHER}e is "QUIC". I will ask somewhere else. By the way, this project is awesome!

**Comment by allinurl** [comment]
I'm glad you found it helpful. [Stay tuned](https://twitter.com/goaccess) for some exciting upcoming changes!
