### ISSUE TITLE
Issue with GoAccess Parsing Log File

### ISSUE THREAD

**Issue by Arun2536IT** [allinurl/goaccess#2546]
Hello,

I'm currently facing an issue while using GoAccess to parse log files. Your assistance in resolving this matter would be greatly appreciated. Here are the details:

Problem:
I'm attempting to analyze a log file using GoAccess (version 1.7.2) on my server. The log file contains entries in the following format:

```
127.0.0.1 10.0.1.147 - - [18/Aug/2023:23:59:10 +0530] "GET /ajaxInventory.php?sFlag=getBatchCurrentStock&_isAjax=true&_csrf_token=d45e783c8ccc9f07828b4c99e7b58fefac2556b034409607f5dc18068865ccb8&iBatchID=250312 HTTP/1.1" 200 17 "https://dummy-url.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36" sFlag=getBatchCurrentStock&_isAjax=true&_csrf_token=d45e783c8ccc9f07828b4c99e7b58fefac2556b034409607f5dc18068865ccb8&iBatchID=250125 HTTP/1.1" 200 18 "https://dummy-url.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36"
- 10.0.1.147 - - [18/Aug/2023:23:59:23 +0530] "GET / HTTP/1.1" 403 199 "-" "ELB-HealthChecker/2.0"
- 10.0.0.78 - - [18/Aug/2023:23:59:23 +0530] "GET / HTTP/1.1" 403 199 "-" "ELB-HealthChecker/2.0"
- 15.207.132.226 - - [18/Aug/2023:23:59:31 +0530] "GET /server-status?auto HTTP/1.1" 200 615 "-" "-"
- 10.0.1.147 - - [18/Aug/2023:23:59:53 +0530] "GET / HTTP/1.1" 403 199 "-" "ELB-HealthChecker/2.0"
- 10.0.0.78 - - [18/Aug/2023:23:59:53 +0530] "GET / HTTP/1.1" 403 199 "-" "ELB-HealthChecker/2.0"
```

I've configured GoAccess using the following settings in my config file:

time-format %H:%M:%S
date_format %d/%b/%Y:%H:%M:%S %z
log_format %h %^[%d] "%r" %s %b "%R" "%u"

Error:
When I run the following command:

sudo goaccess /path/server_logs_20230819.gz.log -o aphc.html

I encounter the following error:
```

[SETTING UP STORAGE /dummy-path/access_logs/aphc_logs_20230819.gz.log] {0} @ {0/s}
Cleaning up resources...
==1241600== GoAccess - version 1.7.2 - Apr  1 2023 00:42:46
==1241600== Config file: /etc/goaccess/goaccess.conf
==1241600== https://goaccess.io - <hello@goaccess.io>
==1241600== Released under the MIT License.
==1241600==
==1241600== FILE: /dummy-path/access_logs/aphc_logs_20230819.gz.log
==1241600== Parsed 10 lines producing the following errors:
==1241600==
==1241600== Token '-' doesn't match specifier '%h'
==1241600== Token '-' doesn't match specifier '%h'
==1241600== Token '-' doesn't match specifier '%h'
==1241600== Token '-' doesn't match specifier '%h'
==1241600== Token '-' doesn't match specifier '%h'
==1241600== Token '-' doesn't match specifier '%h'
==1241600== Token '-' doesn't match specifier '%h'
==1241600== Token '-' doesn't match specifier '%h'
==1241600== Token '-' doesn't match specifier '%h'
==1241600== Token '-' doesn't match specifier '%h'
==1241600==
==1241600== Format Errors - Verify your log/date/time format
```

Steps I've Taken:

Checked the log format, which appears to be correctly configured.
Verified the GoAccess configuration file, which also seems correct.
Request:
I'm seeking assistance in identifying the cause of this error and a possible solution. If there are any suggestions on modifying my log format, configuration, or any other steps to resolve this, I would highly appreciate your insights.

Thank you for your support.

Log File Path: /var/log/aphc/access_logs/aphc_logs_20230819.gz.log

Note: Placeholders for the server IP address and log file path have been used to maintain privacy.

**Comment by allinurl** [comment]
Your log format seems to be inconsistent. Could you explain why there's a dash replacing the first field? It's noticeable that the first line includes an IP address while the subsequent lines do not.

**Comment by Arun2536IT** [comment]
thank you so much, i have solve this problem via removing all the first line from the log file with the ubuntu SED command,
