### ISSUE TITLE
Format Errors -Trying to parse JSON format

### ISSUE THREAD

**Issue by arthurfedorov** [allinurl/goaccess#2548]
Hello, first all I wanna say thanks for that great utility.
Have a Nginx log in json format, example below
`{"timestamp":"2023-08-28T18:22:44+03:00","virtual_host":myhost","remote_addr":"100.64.0.75","request_method":"GET","request_uri":"/api/bots?exchange_kind=","server_protocol":"HTTP/2.0","status_code":200,"body_bytes_sent":5969,"http_referer":"myhost/panel","http_user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36","request_time":0.241}`

Goaccess command, Mac OS Ventura 13.4.1 , installed from brew.
`goaccess -o html -f access.log --log-format='%^:"%dT%t+%^",%^:"%v",%^:"%h",%^:"%m",%^:"%U",%^:"%H",%^:"%s",%^:"%b",%^:"%R",%^:"%u",%^:"%r"' --date-format=%Y-%m-%d --time-format=%T > report.html`

It gave me error, but the error is not obvious to me
```
==13909== Parsed 10 lines producing the following errors:
==13909==
==13909== Token '00,' doesn't match specifier '%s'
==13909== Token '00,' doesn't match specifier '%s'
==13909== Token '00,' doesn't match specifier '%s'
==13909== Token '00,' doesn't match specifier '%s'
==13909== Token '00,' doesn't match specifier '%s'
==13909== Token '00,' doesn't match specifier '%s'
==13909== Token '00,' doesn't match specifier '%s'
==13909== Token '00,' doesn't match specifier '%s'
==13909== Token '00,' doesn't match specifier '%s'
==13909== Token '00,' doesn't match specifier '%s'
==13909==
==13909== Format Errors - Verify your log/date/time format
```
I used this ticket as an example https://github.com/allinurl/goaccess/issues/1195
P.S Is it possible to add more information to the error logs, for debug?

**Comment by allinurl** [comment]
I'm glad you found it helpful. GoAccess indeed provides native JSON parsing. Here's how you can achieve it:

    goaccess access.log --log-format='{"timestamp": "%x", "virtual_host": "%v", "remote_addr": "%h", "request_method": "%m", "request_uri": "%U", "server_protocol": "%H", "status_code": "%s", "body_bytes_sent": "%b","http_referer":  "%R", "http_user_agent": "%u", "request_time": "%T"}' --datetime-format='%Y-%m-%dT%H:%M:%S%z'

![2023-08-28-212205_671x313_scrot](https://github.com/allinurl/goaccess/assets/5005367/8c1feac8-0a62-4e8b-bbd8-c98278c85323)

**Comment by arthurfedorov** [comment]
Thank you for your help, sir @allinurl
