### ISSUE TITLE
log parser fails for %h if value is IPv6 with scope ID ("regular" IPv6 with suffix "percent sign, followed by ID") 

### ISSUE THREAD

**Issue by Abdull** [allinurl/goaccess#2551]
This issue report is for the following goaccess version:
```
# goaccess --version
GoAccess - 1.7.2.
For more details visit: https://goaccess.io/
Copyright (C) 2009-2023 by Gerardo Orellana

Build configure arguments:
  --enable-utf8
  --enable-geoip=mmdb
  --with-getline
  --with-openssl


# apt-cache policy goaccess
goaccess:
  Installed: 1:1.7.2-bullseye
  Candidate: 1:1.7.2-bullseye
  Version table:
 *** 1:1.7.2-bullseye 500
        500 https://deb.goaccess.io bullseye/main amd64 Packages
        100 /var/lib/dpkg/status
     1:1.4-1 500
        500 http://deb.debian.org/debian bullseye/main amd64 Packages
```

During startup, goaccess failed parsing my Apache access log with the following error message:

```
Token 'fe80::a00:27ff:abcd:abc%enp0s8' doesn't match specifier '%h'
```

This is the problematic log file entry:
```
abdull-virtualbox:443 fe80::a00:27ff:abcd:abc%enp0s8 - - [07/Sep/2023:15:58:36 +0200] "GET / HTTP/2.0" 302 360 "-" "curl/7.74.0"
```

`fe80::a00:27ff:abcd:abc%enp0s8` is an IPv6 address **with a scope ID suffix**. **While the percent sign and the trailing rest may look odd, it's actually a valid/well-formed IPv6 address**.

See https://superuser.com/questions/99746/why-is-there-a-percent-sign-in-the-ipv6-address .

**But goaccess 1.7.2 currently does not seem to support this format.**
 

While it should not be relevant for this issue, for completeness this is my custom log format setup:

My custom Apache `LogFormat vhost_combined_requesthost`:

```
# variation of vhost_combined with %v changed to %{Host}i to log the Host header as requested by client
# see https://httpd.apache.org/docs/2.4/mod/mod_log_config.html#formats
##### LogFormat "%v:%p %h %l %u %t \"%r\" %>s %O \"%{Referer}i\" \"%{User-Agent}i\"" vhost_combined

LogFormat "%{Host}i:%p %h %l %u %t \"%r\" %>s %O \"%{Referer}i\" \"%{User-Agent}i\"" vhost_combined_requesthost
```

The `goaccess.conf` log-format configuration to my custom Apache `LogFormat vhost_combined_requesthost`:
```
# ...
time-format %H:%M:%S
date-format %d/%b/%Y
log-format %v %h %^[%d:%t %^] "%r" %s %b "%R" "%u"
# ...
```

**Comment by allinurl** [comment]
This should do it:

    goaccess access.log --log-format='%v:%^ %h\%%^[%x] "%r" %s %b "%R" "%u"' --datetime-format='%d/%b/%Y:%H:%M:%S %z'

![2023-09-07-183238_404x262_scrot](https://github.com/allinurl/goaccess/assets/5005367/9522dde4-a8ea-49de-909a-e8413bf5a0e9)
![2023-09-07-183245_421x126_scrot](https://github.com/allinurl/goaccess/assets/5005367/cbeb4db3-b0b6-4ebd-af2e-ba83bc88fc6b)

**Comment by Abdull** [comment]
> This should do it:
> 
> ```
> goaccess access.log --log-format='%v:%^ %h\%%^[%x] "%r" %s %b "%R" "%u"' --datetime-format='%d/%b/%Y:%H:%M:%S %z'
> ```
> 

Thank you for this suggestion; as it didn't work with my log format, I adapted it in the following way:

```
time-format %H:%M:%S %z
date-format %d/%b/%Y
log-format %v %h%%^ %^[%d:%t] "%r" %s %b "%R" "%u"
```
With `%h` specifying "host (the client IP address, either IPv4 or IPv6)" and `%^` specifying "ignore this field (according to https://goaccess.io/man > _SPECIFIERS_), I assume `%h%%^` stands for "hostfield, immediately followed by a percent character, then immediately ignore everything up until the next space character.

While this log-format allows to parse log entries such as
```
abdull-virtualbox:443 fe80::a00:27ff:abcd:abc%enp0s8 - - [07/Sep/2023:15:58:36 +0200] "GET / HTTP/2.0" 302 360 "-" "curl/7.74.0"
```
successfully, extracting as `%h` the value `fe80::a00:27ff:abcd:abc`, it *only* works when the IPv6 scope ID suffix (such as `%enp0s8`) is present (and ignores/discards the suffix in reports/web interface).

And more relevant, **it fails to parse "normal" log entries with "normal" IP addresses**, i.e. IP addresses without the scope ID suffix.

For example a "normal" log entry such as
```
abdull-virtualbox:443 192.168.0.12 - - [07/Sep/2023:15:58:36 +0200] "GET / HTTP/2.0" 302 360 "-" "curl/7.74.0"
```
will fail to get parsed and will be reported in the `invalid-requests` goaccess parsing error log.
Such "normal" log entries will also cause goaccess to abort startup with the default `num-tests` setting.

So my current workaround is to explicitly set `num-tests 0` to disable the startup log testing.

**Could goaccess be made more robust by accepting IPv6 addresses with scope ID suffixes?**

With goaccess accepting IPv6 addresses with scope ID suffixes, I think the best solution would then be to keep the original value, e.g. `fe80::a00:27ff:abcd:abc%enp0s8` would be reported verbatim as `fe80::a00:27ff:abcd:abc%enp0s8`.

**Comment by allinurl** [comment]
I'm attempting to grasp the reason behind the inconsistency between these two lines. One has `%enp0s8` next to the IPv6, while the other does not. Shouldn't the log format be consistent in your web server?

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.

**Comment by delan** [comment]
> I'm attempting to grasp the reason behind the inconsistency between these two lines. One has `%enp0s8` next to the IPv6, while the other does not. Shouldn't the log format be consistent in your web server?

i think the problem is not that the log format is inconsistent, but rather that only some IPv6 addresses contain a scope ID.
