### ISSUE TITLE
Report for 30 days period: reset unique visitors counter every day

### ISSUE THREAD

**Issue by pozitron57** [allinurl/goaccess#2554]
I want to generate an html report for 30 days and reset unique visitors counter for every day.
I store 30 last Nginx logs. For the moment, I generate month report as follows:

``` bash
filtered_logs=$(mktemp)
month_logs=$(mktemp)

zcat -f /var/log/nginx/access.log /var/log/nginx/access.log.1 /var/log/nginx/access.log.*.gz | \
  grep -v -f /home/slisakov/scripts/exclude-list.txt > "$filtered_logs"

for i in $(seq 1 30)
do
    day=$(date -d "-$i days" '+%d/%b/%Y')
    awk -v date="$day" '$4 ~ date {print}' "$filtered_logs" >> "$month_logs"
done

cat "$month_logs" | goaccess \
  --http-protocol=no \
  --http-method=no \
  --date-spec=day \
  --ignore-panel=HOSTS \
  --ignore-panel=REFERRING_SITES \
  --sort-panel=REQUESTS,BY_VISITORS,DESC \
  --anonymize-ip \
  --ignore-crawlers \
  --log-format=COMBINED \
  --output=/var/www/html/month/index.html -

rm "$filtered_logs"
rm "$month_logs"
```

If there was a visitor visiting the website several days during this period, it will be considered as a one user, while I want the panel `UNIQUE VISITORS PER DAY` to show unique visitors during a day, not month.

**Comment by allinurl** [comment]
Can you please clarify what you mean by "I want to generate an HTML report for 30 days and reset the unique visitors counter every day, but keep the count for 30 days?" I'm not entirely clear on how you intend to reset the counter daily while still maintaining a 30-day count.

**Comment by pozitron57** [comment]
Sorry for not being clear enough.

Here is my panel for unique visitors:
![image](https://github.com/allinurl/goaccess/assets/9392655/af669fde-bf39-4099-9031-5cd7909e41cb)

For example, for September, 12th 
month report shows 800 visitors (logs for the last 30 days);
week report shows 1000 visitors for the September, 12th (logs for the last 7 days);
day report shows 1400 visitors for September, 12th (last full log).

And what I want to nkow is how many unique visitors I had per day while seeing the whole month statistics.

**Comment by allinurl** [comment]
You should be able to hover over the chart and view the daily count of unique visitors. The "UNIQUE VISITORS PER DAY" panel's data column should also display the count of visitors for each day. It's important to note that this count only considers each day's visitors as unique and resets daily, not accumulating visitors from previous days.

**Comment by pozitron57** [comment]
> You should be able to hover over the chart and view the daily count of unique visitors. The "UNIQUE VISITORS PER DAY" panel's data column should also display the count of visitors for each day. It's important to note that this count only considers each day's visitors as unique and resets daily, not accumulating visitors from previous days.

Thanks for reply. I thought that this count doesn't reset daily.
It seems that I have different values (e.g. when hover in month report compared to week report for the same date) due to bugs in my code when I generate the report. Thank you for your time.
