### ISSUE TITLE
nginx-proxy access.log problems with hostname

### ISSUE THREAD

**Issue by Emporea** [allinurl/goaccess#2555]
```
test.example.tld 192.168.178.202 - - [12/Sep/2023:20:03:23 +0200] "POST /storage/1.5/1/storage/tabs?batch=true&commit=true HTTP/2.0" 200 70 "-" "Firefox/117.0 (Linux x86_64) FxSync/1.119.0.20230828231221.desktop" "172.18.0.7:5000"
test.example.tld 192.168.178.202 - - [12/Sep/2023:20:03:29 +0200] "POST /storage/1.5/1/storage/tabs?batch=true&commit=true HTTP/2.0" 200 70 "-" "Firefox/117.0 (Linux x86_64) FxSync/1.119.0.20230828231221.desktop" "172.18.0.7:5000"
test.example.tld 192.168.178.202 - - [12/Sep/2023:20:03:36 +0200] "POST /storage/1.5/1/storage/tabs?batch=true&commit=true HTTP/2.0" 200 70 "-" "Firefox/117.0 (Linux x86_64) FxSync/1.119.0.20230828231221.desktop" "172.18.0.7:5000"
test2.example.tld 192.168.178.202 - - [12/Sep/2023:20:03:41 +0200] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/2.0" 304 0 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/117.0" "172.18.0.6:80"
test2.example.tld 192.168.178.202 - - [12/Sep/2023:20:04:09 +0200] "PUT /ocs/v2.php/apps/user_status/api/v1/heartbeat?format=json HTTP/2.0" 200 175 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/117.0" "172.18.0.6:80"

```
This is what the nginx proxy access.log looks like. Without the hostname at the beginning I can just use the COMBINED log format. But with the hostname at the beginning I get an error.

Do I need to remove the hostname from each line or what is the ideal --log-format for this access.log?

Thank you very much

**Comment by allinurl** [comment]
This should do the job:

    goaccess access.log --log-format='%v %h %^[%x] "%r" %s %b "%R" "%u" %^' --datetime-format='%d/%b/%Y:%H:%M:%S %z'

**Comment by allinurl** [comment]
It's functioning perfectly on my side. Please make sure the locale settings on your system match the log date. You can attempt to run it as follows:

    LC_TIME="en_US.UTF-8" goaccess access.log --log-format='%v %h %^[%x] "%r" %s %b "%R" "%u" %^' --datetime-format='%d/%b/%Y:%H:%M:%S %z'

![2023-09-18-171524_691x359_scrot](https://github.com/allinurl/goaccess/assets/5005367/71ac61fa-67a5-49fb-aef0-8474a20ac274)

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
