### ISSUE TITLE
 I don't have AVG.T.S,  CUM. T.S、MAX. T.S these three columns.  what I should do ？

### ISSUE THREAD

**Issue by senda58** [allinurl/goaccess#2556]
Hello, I have two questions to ask:   **goaccess version 1.7.2**  analysis **nginx log**

 First, why is there no **AVG .T.S  、CUM. T.S、MAX. T.S**  in the indicators I count. What should I do to display these three columns and to show them on each statistics panel?    this is mine like this :

![image](https://github.com/allinurl/goaccess/assets/111741815/fd36ed1c-e75f-4428-8540-e10eca56aba1)

Second, will GoAccess support statistics on other metrics in the future? For example, "View the last 1,000 records and the most visited pages", "List pages with a transmission time of more than 3 seconds, display the first 20", "List pages with a page request time of more than 3 seconds, and count the number of their occurrences, display the top 100" or whether to support the statistics of custom indicators in the future. 

The above questions help me answer them, thank you.

@allinurl  thanks!

**Comment by allinurl** [comment]
Great questions! to obtain the average, cumulative, and maximum time served using GoAccess, you must enable the logging of response times in your web server. For Nginx, you can include `$request_time` in your log format, while in Apache, you can use
`%D` and then enable it in your goaccess' [log-format](https://goaccess.io/man#custom-log).

Yes, #117 should address your second question. This is currently in progress, so please [**stay tuned**](https://twitter.com/goaccess) for updates.

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
