### ISSUE TITLE
Analysing Traffic to sub-domains

### ISSUE THREAD

**Issue by Double5peed** [allinurl/goaccess#256]
Not sure if this is an issue or is not supported however my GoAccess reports do not analyse out the traffic to sub-domains? Data is in the access log however no means of seeing/analysing this traffic

**Comment by allinurl** [comment]
Virtual Hosts are in the to-do list. Please see #23 and #67. Feel free to comment in there if you have any questions/feedback about it. Thanks.

**Comment by Double5peed** [comment]
Thanks, the sub domains in my case are reported in the one 'main' log they are not separated out into separate hosts. Would like to be able to show traffic etc to them.

**Comment by allinurl** [comment]
I see, could please you post a few lines from your log?

**Comment by Double5peed** [comment]
Can I email a sample to you?

**Comment by allinurl** [comment]
Definitely, hello [at] goaccess.io

**Comment by allinurl** [comment]
Got your log. As you mentioned, it does not contain `%V` so no virtual host is reported. Two choices come to mind:

You could either add `%V` to your apache access config and then use `split-logfile` to generate individual reports or grep through your access log for each subdomain and have it output to a file which you could then analyze with goaccess.
