### ISSUE TITLE
Parsing Nginx Log to Goaccess

### ISSUE THREAD

**Issue by Leothomaz1** [allinurl/goaccess#2560]
My nginx loging format is 
log_format  main  '$host $remote_addr - $remote_user [$time_local] $upstream_cache_status "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for" "$gzip_ratio" '
                      '$request_time $upstream_response_time $pipe';

and  goaccess command   Iam running is 

awk '$9=$1":"$9' access.log | goaccess --log-format='%v %h %^[%d:%t %^]%^"%r" %s %b "%R" "%u" "%^" "%^" %T %^' --date-format='%d/%b/%Y' --time-format='%T'

But when I run this I am getting 
Parsed 10 lines producing the following errors:
==20173==
==20173== Token '-' doesn't match specifier '%h'
==20173== Token '-' doesn't match specifier '%h'

**Comment by allinurl** [comment]
Could you provide a few sample lines from your access log for me to review?

**Comment by 0bi-w6n-K3nobi** [comment]
Well... it's work for me too.

@allinurl  always recommends it, me too: 
Please make sure the locale settings on your system match the log date.

`LC_TIME="en_US.UTF-8" goaccess ...`

I hope that be helped you.

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
