### ISSUE TITLE
A long time ago in a galaxy far, far away...

### ISSUE THREAD

**Issue by 0bi-w6n-K3nobi** [allinurl/goaccess#2563]
Hi @allinurl 

I am lost in time... But I'm emerging from the shadows.
The things seem to stop here.

I will try add some ideas and help you to answer simple questions.

Nice to meet you, again!
**`May the force be with you.`**

**Comment by allinurl** [comment]
Welcome back! It's great to hear from you again. Please feel free to take a look at some of those pending issues. I've been getting ready for some exciting updates that are in the works!
