### ISSUE TITLE
mixed JSON access log - conflict `%r` and `%C`

### ISSUE THREAD

**Issue by UnveilTech** [allinurl/goaccess#2566]
Hi,

I'm using the latest 1.8.2 of GoAccess and I'm facing an issue with %r and %C.
in the console "The cache status of the object served" is empty, no info about MISS or HIT.

### extract of the log:
2023-10-05T19:13:26+02:00 10.0.0.20 haproxy[19009]: {"time":1696526006,"latency":50,"client":"10.0.0.2","frontend":"frontHTTP","frontport":80,"backend":"frontHTTP","server":"server1","serverip":"127.0.0.1","size":631,"upload":124,"code":200,"host":"my.example.com","uri":"/assets/js/XHRConnection.js","cached":"MISS"}

### log-format:
%^{"time":%x,"latency":%D,"client":"%h","frontend":"%v","frontport":%^,"backend":"%^","server":"%^","serverip":"%^","size":%b,"upload":%^,"code":%s,"host":"%r","uri":"%U","cached":"%C"}

maybe I miss a point here, so a few help is welcome :o)

thanks,
bye Fred

**Comment by allinurl** [comment]
I'd preprocess the log and keep the JSON string. e.g.,

    awk -F'{"' '{print "{\""$2}' access.log | goaccess - --log-format='{ "time": "%x", "latency": "%D", "client": "%h", "frontend": "%v", "size": "%b", "code": "%s", "host": "%r", "uri": "%U", "cached": "%C" }' --datetime-format=%s --http-protocol=no --http-method=no

![2023-10-07-103503_606x315_scrot](https://github.com/allinurl/goaccess/assets/5005367/73d28ac6-c15e-4715-b461-c5584f1aedba)

**Comment by UnveilTech** [comment]
Hi allinurl,
finally I moved the part "host":"%r" at the end of the line and the %C is now ok

**Comment by UnveilTech** [comment]
let's close the case.

**Comment by allinurl** [comment]
@UnveilTech Glad that worked :)
