### ISSUE TITLE
Tables after the first fail to render properly

### ISSUE THREAD

**Issue by creshal** [allinurl/goaccess#2570]
Tested versions: Goaccess 1.7 (Debian repo), Goaccess 1.8 (upstream repo); using a database originally created with goaccess 1.4.

Running the static HTML export, all tables after the first one fail to load (Firefox, Chrome, latest each):

![image](https://github.com/allinurl/goaccess/assets/1379555/71e93b72-6b42-4319-9fd9-a918d665fe10)

JS Console only gives one vague error:

```
Uncaught TypeError: val is undefined
    fmtValue file:///tmp/report.html#:1
    getObjectCell file:///tmp/report.html#:1
    iterUIItems file:///tmp/report.html#:1
    renderRow file:///tmp/report.html#:1
    renderRows file:///tmp/report.html#:1
    renderDataRows file:///tmp/report.html#:1
    renderFullTable file:///tmp/report.html#:1
    renderTables file:///tmp/report.html#:1
    initialize file:///tmp/report.html#:1
    initialize file:///tmp/report.html#:1
    onload file:///tmp/report.html#:1
report.html:1:1189799
```

Interactive terminal view works, and the bar charts in the HTML also have all the data. I guess one of the 187 million DB entries is corrupted, but… yeah. It's 187 million entries to look through. Any pointers on how to get started?

(After upgrading, I also got an `/var/lib/goaccess/IGLP_LAST_PARSE.db: format signature mismatch` error when trying to re-run exports. I moved the file somewhere else, re-runs gave no parsing errors. That seems unrelated to this issue…?)

**Comment by allinurl** [comment]
Thanks for sharing that. That's an intriguing discovery! Are you passing `--real-time-html`? Can you try hitting Ctrl+U in Chrome to access the `var json_data` JSON object, and then share it here or feel free to send it to my email at hello [at] goaccess.io?

**Comment by creshal** [comment]
The full command line is `goaccess -a  --all-static-files --restore --db-path /var/lib/goaccess --log-format=COMBINED --ignore-crawlers --anonymize-ip -o foo.html`, and then rsync the file to a different machine. As far as I understand, real-time-html would only make it worse…?

The JSON is about 600KiB / 1.8MiB pretty printed, I'll email it to you.

**Comment by allinurl** [comment]
I've pushed a few commits to the upstream repository to resolve the problem you're encountering. Could you please try building from the [development](https://github.com/allinurl/goaccess#build-from-github-development) and see if it resolves the browser issue on your end? Thanks again!

**Comment by creshal** [comment]
Thank you, everything renders fine now. :+1:

**Comment by allinurl** [comment]
@creshal Thanks a bunch for sharing those files; it really helped simplify the debugging process!
