### ISSUE TITLE
STATIC REQUESTS panel shows files despite no static-files defined

### ISSUE THREAD

**Issue by Urvika-gola** [allinurl/goaccess#2573]
Using GoAccess - 1.5.5
OS -  Ubuntu 22.04
Log Type - CLF

I'm experiencing an undesired behavior with the `STATIC REQUESTS` panel. Here's what I've tried and observed:

**What I Did:**
Commented out all the static-file tags in the `goaccess.conf` file.

**Expected Behavior:**
The `STATIC REQUESTS` panel should not display any data, as no static files are defined.
The `REQUESTED FILES` panel should list files of all types of extensions.

**Observed Behavior:**
The `STATIC REQUESTS` panel continues to display files with extensions that are commented out.

**Workaround:**
This issue does not occur if I comment out all but one static-file tag. (By adding an invalid file extension, for example: `static-file ./`) 
With this workaround, the `STATIC REQUESTS` panel correctly displays no files, and all the files appear under `REQUESTED FILES`.

My aim is to have all file types displayed in the `REQUESTED FILES` panel, while completely empty `STATIC REQUESTS` panel, without relying on the workaround of leaving one invalid file extension's static-file tag uncommented.

I'd appreciate any suggestions on resolving this. 
Thank you.

**Comment by allinurl** [comment]
Excellent question. The suggested workaround won't be effective because there's a function called set_default_static_files that utilizes default static extensions in cases where the user hasn't provided a goaccess.conf file. To address this issue without the need to introduce an additional option, the simplest solution would be to append a character to the end of the request, using awk to preprocess the log should solve the issue, e.g.,

First find your request field with:

    $ awk '{ print $8 }' access.log

then you can run something like:

```
$  awk '{if ($8 ~ /\.[^ ]+$/) { $8 = $8 "^" } print}' access.log
website.com:443 192.168.23.27 - - [26/Oct/2023:17:19:32 -0500] "GET /notes.jpg^ HTTP/2.0" 200 23808 "-" "Tiny Tiny RSS/23.10-03e956132 (Unsupported) (https://tt-rss.org/)"
website.com:443 192.168.23.27 - - [26/Oct/2023:17:19:32 -0500] "GET /notes-clean HTTP/2.0" 200 23808 "-" "Tiny Tiny RSS/23.10-03e956132 (Unsupported) (https://tt-rss.org/)"
```

then you can pass that to goaccess as:

    $  awk '{if ($8 ~ /\.[^ ]+$/) { $8 = $8 "^" } print}' access.log | goaccess - --log-format=COMBINED -o output.html

Should output

![2023-10-26-173327_478x154_scrot](https://github.com/allinurl/goaccess/assets/5005367/2625584a-50de-4a6a-9c80-4f35f0e70ff4)

**Comment by Urvika-gola** [comment]
Thank you for pointing out [set_default_static_files()](https://github.com/allinurl/goaccess/blob/master/src/settings.c#L170), I now have a better understanding of what was happening.

I tried your suggestion, it works. Thank you. It was the 7th field in the CLF log file with the path. However, I would like to discuss a few concerns about this suggestion:

1. Running awk on all the logs per line introduces additional overhead.
2. While I am indeed using a configuration file, I have commented out or deleted the `static-file` tags. I believe GoAccess should automatically detect that a config file is being used but no static-file tags are present. And this is what the expected configuration is, and it should not overridden with default values.
3. Adding a caret (^) at the end of the path in the dashboard is not visually appealing. It might lead to errors if we copy the path from the dashboard, as we would then need to manually remove the caret.

(Updated to GoAccess 1.8)

**Comment by allinurl** [comment]
Thanks for bringing this up! I completely agree with you on this. As you mentioned, if it detects the presence of a config file and no static-file options were used, it shouldn't default to the hard-coded options. 

Would you be able to push a PR for this change? It doesn't seem like a particularly difficult change, and most of the adjustments would likely happen within the same [function](https://github.com/allinurl/goaccess/blob/master/src/settings.c#L212), especially focusing on the index of `static-file` using `conf.static_file_idx`.
