### ISSUE TITLE
Token doesn't match specifier '%h' 

### ISSUE THREAD

**Issue by matheuspaleari123** [allinurl/goaccess#2575]
@miraclect This should work, however, please note that goaccess requires a valid IPv4/6, so the second request will be considered invalid as there's a dash in the `%h` field.

    goaccess access.log --log-format='%h %^ %^ %e [%d:%t %^] "%r" %s %b "%R" "%u" %D' --date-format=%d/%b/%Y --time-format=%T

_Originally posted by @allinurl in https://github.com/allinurl/goaccess/issues/1273#issuecomment-431449237_

**Comment by allinurl** [comment]
I'm unsure about your question's specifics. Please don't hesitate to provide additional information as required.

**Comment by grinapo** [comment]
Can I hijack please? Thanks! ;-)

I've tried goaccess, and got various nondescript, and most importantly non-testable errors, usually like:
`==362690== Token '2024-02-17_09:06:32.221+0100' doesn't match specifier '%x'`
or even less like
```
==360445== IPv4/6 is required.                                                                                                                                                                                                                                
==360445==                                                                                                                                                                                                                                                    
==360445== Format Errors - Verify your log/date/time format                                                                                                                                                                                                   
```
It seems debugging log-format is almost impossible, or the documentation is not detailed enough. (Granted, they are not in standard common log format.)

**Suggestion**: is there any way to test format specifiers against patterns?
**Suggestion**: examples for patterns in the docs. (Most of the strftime patterns are obvious, but, for example, how would you parse this datetme: `2024-02-17_09:06:32.221+0100`? I see it doesn't match "specifier %x" which is `--datetime-format '%F_%T.%^%z'` or its various mutations with `%f` or like, but I probably have to generate a sample log to test or go to the source to see why it fails.)

The above problem seems to be that the user don't even know which line was not matched, let alone why, or where the parser have failed.

Thanks for the mic. :grin:

**Comment by allinurl** [comment]
@grinapo Please share a few lines from your log so I can review the format.

**Comment by allinurl** [comment]
@grinapo I was attempting to locate a similar question, but unfortunately, I couldn't recall the solution. Regardless, it's worth mentioning that strftime doesn't support milliseconds in the C implementation. 

Please don't hesitate to suggest how the errors should be handled, or even better, feel free to submit a PR with any changes you believe might improve the experience for users. I'd be more than happy to review them.

The following should do it:

    # goaccess access.log --log-format='%v %h %^ %^ %d_%t.%^ "%r" %s %b "%R" "%u" %^' --date-format=%Y-%m-%d --time-format=%T

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.

**Comment by hjbeckers** [comment]
I have the same problem as in this thread. I hope it is okay to reopen it.

Starting my squid script:

sh bin/squid_goaccess.sh 
Cleaning up resources...
==131187== GoAccess - version 1.9.3 - Jun  1 2024 13:49:08
==131187== Config file: /etc/goaccess/goaccess.conf
==131187== https://goaccess.io - <hello@goaccess.io>
==131187== Released under the MIT License.
==131187==
==131187== FILE: /var/log/squid/access.log
==131187== 10 Zeilen analysiert führen zu folgenden Fehlern:
==131187==
==131187== Token '43 - HIER_DIRECT/87' doesn't match specifier '%x'
==131187== Token '43 - HIER_DIRECT/87' doesn't match specifier '%x'
==131187== Token '43 - HIER_DIRECT/87' doesn't match specifier '%x'
==131187== Token '43 - HIER_DIRECT/87' doesn't match specifier '%x'
==131187== Token '43 - HIER_DIRECT/87' doesn't match specifier '%x'
==131187== Token '43 - HIER_DIRECT/87' doesn't match specifier '%x'
==131187== Token '43 - HIER_DIRECT/0' doesn't match specifier '%x'
==131187== Token '43 - HIER_DIRECT/0' doesn't match specifier '%x'
==131187== Token '43 - HIER_DIRECT/142' doesn't match specifier '%x'
==131187== Token '43 - HIER_DIRECT/87' doesn't match specifier '%x'
==131187==
==131187== Formatfehler – prüfen Sie das Log-/Datums-/Zeitformat

A few lines from /var/log/squid/access.log:

734822363.064     11 192.168.178.21 TCP_TUNNEL/200 3012 CONNECT cdn.adspirit.de:443 - HIER_DIRECT/0.0.0.0 -
1734822369.669   6549 192.168.178.21 TCP_TUNNEL/200 682 CONNECT stats.zum.de:443 - HIER_DIRECT/88.99.253.153 -
1734822384.208  59274 192.168.178.21 NONE_NONE/503 0 CONNECT www.zum.de:443 - HIER_DIRECT/46.4.65.203 -
1734822385.210  60183 192.168.178.21 NONE_NONE/503 0 CONNECT www.zum.de:443 - HIER_DIRECT/46.4.65.203 -
1734822392.218  59231 192.168.178.21 NONE_NONE/503 0 CONNECT www.zum.de:443 - HIER_DIRECT/46.4.65.203 -
1734822392.218  59219 192.168.178.21 NONE_NONE/503 0 CONNECT www.zum.de:443 - HIER_DIRECT/46.4.65.203 -
1734822393.011  60009 192.168.178.21 NONE_NONE/503 0 CONNECT www.zum.de:443 - HIER_DIRECT/46.4.65.203 -
1734822393.095     14 192.168.178.21 TCP_TUNNEL/200 3012 CONNECT cdn.adspirit.de:443 - HIER_DIRECT/0.0.0.0 -
1734822393.111     13 192.168.178.21 TCP_TUNNEL/200 3012 CONNECT cdn.adspirit.de:443 - HIER_DIRECT/0.0.0.0 -
1734822394.590  31523 192.168.178.21 TCP_TUNNEL/200 39 CONNECT www.zum.de:443 - HIER_DIRECT/46.4.65.203 -
1734822399.513  96449 192.168.178.21 TCP_TUNNEL/200 12204490 CONNECT apps.zum.de:443 - HIER_DIRECT/148.251.126.7 -
1734822402.196  85136 192.168.178.21 TCP_TUNNEL/200 797 CONNECT snowflake-broker.torproject.net:443 - HIER_DIRECT/37.218.242.175 -



Start-script for goaccess: 

#/usr/bin/goaccess /var/log/squid/access.log --log-format='%x.%^ %~ %L %h %^/%s %b %m %U %^' --date-format='%Y%m%d' --time-format='%H:%M:%S' --output=/var/www/html/report.html
#LANG="en_US.UTF-8" /usr/bin/goaccess /var/log/squid/access.log --log-format=SQUID --date-format='%Y%m%d' --time-format='%H:%M:%S' # --output=/var/www/html/report.html
/usr/bin/goaccess /var/log/squid/access.log --log-format='SQUID' --date-format='%Y%m%d' --time-format='%H:%M:%S' # --output=/var/www/html/report.html

--> all variants (setting $LANG, using SQUID as --log-format) give the same error


My environment:

# cat /etc/os-release 
PRETTY_NAME="Ubuntu 22.04.5 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.5 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy


Any hints?

**Comment by allinurl** [comment]
@hjbeckers can you please describe those fields?

**Comment by hjbeckers** [comment]
This seems to be the standard squid log format, as defined in /etc/squid/squid.conf

> # The default formats available (which do not need re-defining) are:
> #
> #logformat squid      %ts.%03tu %6tr %>a %Ss/%03>Hs %<st %rm %ru %[un %Sh/%<a %mt
> #logformat common     %>a %[ui %[un [%tl] "%rm %ru HTTP/%rv" %>Hs %<st %Ss:%Sh
> #logformat combined   %>a %[ui %[un [%tl] "%rm %ru HTTP/%rv" %>Hs %<st "%{Referer}>h" "%{User-Agent}>h" %Ss:%Sh
> 

My configuration uses the first "squid" definition. the "ts" is seconds since the Unix-epoch (1970-01-01) and "tu" the milliseconds. You stated in this thread that this item  is not in standard strftime. Could that be the problem? Shall I use one of the definitions "common" or "combined"?

Thanks for your help.

**Comment by hjbeckers** [comment]
Setting the log format to "common", my access_log format changes to:

192.168.178.21 - - [23/Dec/2024:18:35:56 +0100] "CONNECT www.merkur.de:443 HTTP/1.1" 200 1105 TCP_TUNNEL:HIER_DIRECT
192.168.178.21 - - [23/Dec/2024:18:36:38 +0100] "CONNECT newstral.com:443 HTTP/1.1" 200 21457 TCP_TUNNEL:HIER_DIRECT
192.168.178.21 - - [23/Dec/2024:18:38:28 +0100] "CONNECT firefox.settings.services.mozilla.com:443 HTTP/1.1" 200 4455 

But the error messages remain:

sh squid_goaccess.sh
 [PARSING /var/log/squid/access.log] {0} @ {0/s}
Cleaning up resources...
==139378== GoAccess - version 1.9.3 - Jun  1 2024 13:49:08
==139378== Config file: /etc/goaccess/goaccess.conf
==139378== https://goaccess.io - <hello@goaccess.io>
==139378== Released under the MIT License.
==139378==
==139378== FILE: /var/log/squid/access.log
==139378== 10 Zeilen analysiert führen zu folgenden Fehlern:
==139378==
==139378== Token '192' doesn't match specifier '%x'
==139378== Token '192' doesn't match specifier '%x'
==139378== Token '192' doesn't match specifier '%x'
==139378== Token '192' doesn't match specifier '%x'
==139378== Token '192' doesn't match specifier '%x'
==139378== Token '192' doesn't match specifier '%x'
==139378== Token '192' doesn't match specifier '%x'
==139378== Token '192' doesn't match specifier '%x'
==139378== Token '192' doesn't match specifier '%x'
==139378== Token '192' doesn't match specifier '%x'

**Comment by allinurl** [comment]
Give this a shot, it shoud do the job:

    goaccess access.log --log-format='%h %^[%x] "%r" %s %b %^:%v' --datetime-format='%d/%b/%Y:%H:%M:%S %z' --tz=America/New_York --date-spec=min

![2024-12-24-165358_505x318_scrot](https://github.com/user-attachments/assets/424c980b-3582-493e-b7b9-68886f5d2f0e)

**Comment by hjbeckers** [comment]
It works. But I have to use the "common"-variant of squid logging as:

access_log daemon:/var/log/squid/access.log common

Thank you again for your help.

**Comment by allinurl** [comment]
@hjbeckers, happy to hear you got it sorted! If you have any more questions, feel free to reach out.
