### ISSUE TITLE
Help with log/date/time format?

### ISSUE THREAD

**Issue by fmp777** [allinurl/goaccess#2577]
Does this tool not simply take a direct paste from apache LogFormat directive?  Having very difficult time trying to get it to read the apache logs. Would anyone kindly show me where I'm being stupid?

```
www.thedomain.com 41.77.167.16 - - [03/Nov/2023:15:43:50 -0400] "GET /index.html HTTP/2.0" 200 15405 "-" "Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm) Chrome/103.0.5060.134 Safari/537.36"
```

`LogFormat "%{Host}i %a %l %u %t \"%r\" %>s %O \"%{Referer}i\" \"%{User-Agent}i\"" combined`

And no matter what i try it seems to keep choking at `%t` thinking it doesn't match the value where "-" referer is supposed to be

`Token '"-"' doesn't match specifier '%t'  `

I've tried a number of changes based on random issues found here, but can't quite seem to make it happy

```
# goaccess test.log --log-format='%{Host}i %a %l %u %t "%r" %>s %O "%{Referer}i" "%{User-Agent}i"' --time-format="%H:%M:%S %z" --date-format="%d/%b/%Y"
Cleaning up resources...
==3036049== GoAccess - version 1.8.1 - Nov  1 2023 00:20:26
==3036049== Config file: /etc/goaccess/goaccess.conf
==3036049== https://goaccess.io - <hello@goaccess.io>
==3036049== Released under the MIT License.
==3036049==
==3036049== FILE: test
==3036049== Parsed 1 lines producing the following errors:
==3036049==
==3036049== Token '"-"' doesn't match specifier '%t'
==3036049==
==3036049== Format Errors - Verify your log/date/time format
```

**Comment by allinurl** [comment]
This should do it:

    goaccess access.log --log-format='%v %h %^[%x] "%r" %s %b "%R" "%u"' --datetime-format='%d/%b/%Y:%H:%M:%S %z'

[Custom log fields](https://goaccess.io/man#custom-log) is what you are looking for.

![2023-11-04-191005_416x242_scrot](https://github.com/allinurl/goaccess/assets/5005367/a9f4f9ff-9879-412c-8b60-425e21ffc008)

**Comment by allinurl** [comment]
This is now closed - feel free to reopen it if necessary.
