### ISSUE TITLE
Can't see tables on mobile device?

### ISSUE THREAD

**Issue by chrisloftus** [allinurl/goaccess#2578]
![image](https://github.com/allinurl/goaccess/assets/68920/f64f52e2-f52e-4411-8b5f-bc09fe30582c)

**Comment by allinurl** [comment]
You can enable or disable them by selecting or deselecting the "auto hide in small devices" option.


![2023-11-09-182842_268x86_scrot](https://github.com/allinurl/goaccess/assets/5005367/81e8c822-64f7-42af-b925-03741ec48413)

**Comment by chrisloftus** [comment]
> You can enable or disable them by selecting or deselecting the "auto hide in small devices" option.
> 
> 
> 
> 
> 
> ![2023-11-09-182842_268x86_scrot](https://github.com/allinurl/goaccess/assets/5005367/81e8c822-64f7-42af-b925-03741ec48413)
> 
> 

Thanks
