### ISSUE TITLE
Real time stopped working

### ISSUE THREAD

**Issue by chrisloftus** [allinurl/goaccess#2579]
Think it is due to the access.log file filling up and moving to access.log.1 and a new access.log created? I can see new requests coming in in the access log.

My command is:

```
tail -f /var/log/nginx/access.log | goaccess -o /home/admin/<domain>/public/access-log.html --log-format=COMBINED --real-time-html --ws-url=www.<domain>:443/websocket/ --geoip-database=/usr/local/etc/goaccess/GeoLite2-City.mmdb
```

If I quit and restart total requests will go back to 0...

<img width="368" alt="Screenshot 2023-11-10 at 9 42 37 am" src="https://github.com/allinurl/goaccess/assets/68920/240a4c52-06ba-4580-be0e-b46ddf47a3ca">

**Comment by allinurl** [comment]
If you want the `tail` command to keep up with changes in the file, try using tail `-F` instead of tail `-f`. Also note the additional `-` in goaccess.

    tail -F /var/log/nginx/access.log | goaccess - -o /home/admin/<domain>/public/access-log.html --log-format=COMBINED --real-time-html --ws-url=www.<domain>:443/websocket/ --geoip-database=/usr/local/etc/goaccess/GeoLite2-City.mmdb

Or, if you want to keep it super easy, just let goaccess handle it like this:

    goaccess /var/log/nginx/access.log -o /home/admin/<domain>/public/access-log.html --log-format=COMBINED --real-time-html --ws-url=www.<domain>:443/websocket/ --geoip-database=/usr/local/etc/goaccess/GeoLite2-City.mmdb

**Comment by chrisloftus** [comment]
@allinurl Thanks, will try that. The second option won't include the access.log.1 file though will it? That's why I'm having to do it with tail.

**Comment by allinurl** [comment]
Good question! The second choice will maintain the counters no matter how many times the log rotates. It should work just like `tail -F`.

**Comment by chrisloftus** [comment]
@allinurl Thanks, will give it a try when the current tail stops updating.

**Comment by chrisloftus** [comment]
Seems to have fixed it so far. @allinurl Is it possible to filter the stats to a specific day?

**Comment by allinurl** [comment]
@chrisloftus, at the moment, you must preprocess the log using tools such as sed/awk/grep, etc. Refer to the [man page](https://goaccess.io/man#examples) for specific examples. Meanwhile, I'm actively addressing issue #117, so [stay tuned](https://twitter.com/goaccess?lang=en) — It's progressing well.
