### ISSUE TITLE
IIS Format Not Working

### ISSUE THREAD

**Issue by johnjelinek** [allinurl/goaccess#258]
I have a log file:
```
▶ head IIS_150611.log
#Software: Microsoft Internet Information Services 7.5
#Version: 1.0
#Date: 2015-06-11 00:00:01
#Fields: date time s-ip cs-method cs-uri-stem cs-uri-query s-port cs-username c-ip cs(User-Agent) sc-status sc-substatus sc-win32-status time-taken
2015-06-11 00:00:01 172.20.136.48 GET /website/example 80 - 127.0.0.1 MobileTrading/316+CFNetwork/711.1.16+Darwin/14.0.0 200 0 0 36
```

If I use `goaccess` on this log (or any of my logs) it says all of the traffic was failed, but that's not accurate. Do I need to provide a custom parser format?

**Comment by allinurl** [comment]
Looks like you are using a custom format. However, the following should work:

    log-format %d %t %^ %m %r %^ %^ %h %R %s %^ %^ %D
    date-format %Y-%m-%d
    time-format %H:%M:%S

Also, the time-taken seems to be in microseconds, is that right? It looks like the size of the request is missing.

Let me know how it goes.

**Comment by johnjelinek** [comment]
`goaccess -f IIS_150611.log --log-format="%d %t %^ %m %r %^ %^ %h %R %s %^ %^ %D" --date-format="%Y-%m-%d" --time-format="%H:%M:%S"` still doesn't parse correctly. Says all the requests failed.

**Comment by johnjelinek** [comment]
I think the time-taken is in milliseconds, not microseconds

**Comment by allinurl** [comment]
Running the command you posted above against your sample line does run. Does it work if you try to parse only the line posted?

Currently goaccess parses microseconds `%D`  and `%T` for seconds with a milliseconds resolution, e.g., 0.343. I may need to add a milliseconds-only specifier.

**Comment by allinurl** [comment]
I opened an issue to add a milliseconds-only specifier #259 . Closing this. Feel free to reopen it if needed.

**Comment by allinurl** [comment]
This has been implemented. The specifier is `%L` - milliseconds as a decimal number [000, 999].

**Comment by johnjelinek** [comment]
Hmm, not sure that will work in my case. The milliseconds are a whole number in these logs, where something like 15 seconds is 15000.

**Comment by allinurl** [comment]
It should, sorry about the wrong notation, I updated my previous post. It will read a decimal number.

**Comment by soheilpro** [comment]
I created a little script that automatically extracts the proper format from IIS log files:
https://gist.github.com/soheilpro/a34957550b1bd7d42be2

**Comment by allinurl** [comment]
@soheilpro Thanks for posting this. I'll add a link to website.

**Comment by allinurl** [comment]
@soheilpro Added to the site. Thanks again.

**Comment by allinurl** [comment]
@soheilpro Added to the site. Thanks again.

http://goaccess.io/faq#howto-iis

**Comment by soheilpro** [comment]
@allinurl You are very welcome.
