### ISSUE TITLE
Parse SEARCH method

### ISSUE THREAD

**Issue by panos-stavrianos** [allinurl/goaccess#2580]
Hello, I have the following config
```
time-format %T
date-format %d/%b/%Y
log_format [%d:%t %^] %^ %^ %s - %m %^ %v "%U" [Client %h] [Length %b] [Gzip %^] [Sent-to %^] "%u" "%R"
```

example **WORKING** log line

```
[06/Nov/2023:14:52:35 +0200] - 200 200 - GET https .............................
```

example **NOT WORKING** log line

```
[06/Nov/2023:14:52:35 +0200] - 200 200 - SEARCH https .............................
```
The error is 
```
Token 'SEARCH' doesn't match specifier '%m'
```
So I guess the search method is not included as it's not standardized, is there any workaround for now?

**Comment by allinurl** [comment]
You're right; the optimal approach would be to include it in the next version release. Could you contribute by submitting a pull request that adds the SEARCH method [**here**](https://github.com/allinurl/goaccess/blob/master/src/gstorage.c#L93)? I'd be happy to merge it.
