### ISSUE TITLE
Token '[02/Nov/2023' doesn't match specifier '%d'

### ISSUE THREAD

**Issue by pmetras** [allinurl/goaccess#2582]
My logs contain lines like:
`FORWARD: www.example.com 193.183.4.20 - - [02/Nov/2023:00:00:18 +0000] "GET /interactive/here_at_home HTTP/1.1" 301 20 "https://www.google.com/" "Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Mobile Safari/537.36" "-"`

With the goaccess version from the Ubuntu [repository (version 1.5.5?)](https://packages.ubuntu.com/jammy/goaccess), I was able to parse these logs. My configuration file contains the following definitions:
```
time-format %H:%M:%S
date-format %d/%b/%Y
datetime-format %d/%b/%Y:%H:%M:%S %z
log-format FORWARD: %v ~h{, } - %e- [%d:%t %^] "%r" %s %b "%R" "%u" "-"
```

I upgraded the version to 1.8.1, using the [official packages](https://github.com/allinurl/goaccess#official-goaccess-debian--ubuntu-repository) because I need to filter out crawlers. And now goaccess reports syntax errors with the format definition. I'm using:
`LC_TIME="en_US.UTF-8" goaccess -i -m -a -p ./goaccess.conf ./access*` to run it.

The errors:
```
Cleaning up resources...
==12100== GoAccess - version 1.8.1 - Nov  1 2023 00:19:32
==12100== Config file: ./goaccess.conf
==12100== https://goaccess.io - <hello@goaccess.io>
==12100== Released under the MIT License.
==12100==
==12100== FILE: ./access-a.log.1
==12100== Parsed 10 lines producing the following errors:
==12100==
==12100== Token '[02/Nov/2023' doesn't match specifier '%d'
==12100== Token '[02/Nov/2023' doesn't match specifier '%d'
...
==12100==
==12100== Format Errors - Verify your log/date/time format
```

I've tried multiple variants of the format with always a similar format error `Token '[...`. But because of the presence of the character `[` in all errors, it looks like goaccess format parser misinterprets the date definition.

What's wrong?

**Comment by allinurl** [comment]
Please try:

    goaccess access.log --log-format='%^ %v %h %^[%x] "%r" %s %b "%R" "%u" %^' --datetime-format='%d/%b/%Y:%H:%M:%S %z'

**Comment by pmetras** [comment]
Your `log-format` and `datetime-format` work from the command line. If I put these formats in my configuration file, it does not work.

I tried with a minimal configuration file:
```
#time-format %H:%M:%S
#date-format %d/%b/%Y
datetime-format %d/%b/%Y:%H:%M:%S %z
log-format %^ %v %h %^[%x] "%r" %s %b "%R" "%u" %^
```
It works, but as soon as I uncomment the `time-format` specification, goaccess does not recognize the log format.

And if I uncomment both lines, `time-format` and `date-format`, I get the following format error:
```
goaccess -p ./goaccess.conf2 ./access-a.log.1
Cleaning up resources...
==4486== GoAccess - version 1.8.1 - Nov  1 2023 00:19:32
==4486== Config file: ./goaccess.conf2
==4486== https://goaccess.io - <hello@goaccess.io>
==4486== Released under the MIT License.
==4486==
==4486== FILE: ./access-a.log.1
==4486== Parsed 10 lines producing the following errors:
==4486==
==4486== Token '02/Nov/2023:00:00:11 +0000' doesn't match specifier '%x'
==4486== Token '02/Nov/2023:00:00:14 +0000' doesn't match specifier '%x'
...
```

I'm using a configuration file as I set many options and don't want to enter them on the command line. But the following line also shows the error: `goaccess access-a.log.1 --log-format='%^ %v %h %^[%x] "%r" %s %b "%R" "%u" %^' --datetime-format='%d/%b/%Y:%H:%M:%S %z' --time-format='%H:%M:%S' --date-format='%d/%b/%Y'`

**Comment by allinurl** [comment]
I will have to verify this, but you can always:

```
log-format %^ %v %h %^[%d:%t %^] "%r" %s %b "%R" "%u" %^
date-format %d/%b/%Y
time-format %T
```

**Comment by pmetras** [comment]
I continued tests to be sure that goaccess recognize all the fields in our log format. This works:

```
goaccess access-a.log.1 --log-format='FORWARD: %v ~h{, } - %e-%^[%d:%t %^] "%r" %s %b "%R" "%u" %^' --datetime-format='%d/%b/%Y:%H:%M:%S %z' --time-format='%H:%M:%S' --date-format='%d/%b/%Y'
```

This does not work:

```
goaccess access-a.log.1 --log-format='FORWARD: %v ~h{, } - %e- [%d:%t %^] "%r" %s %b "%R" "%u" %^' --datetime-format='%d/%b/%Y:%H:%M:%S %z' --time-format='%H:%M:%S' --date-format='%d/%b/%Y'
```

The difference is `...%e-%^[%d...` instead of `...%e- [%d...`.

**Comment by allinurl** [comment]
Happy to hear it works for you. For me, the one I posted works fine:

![2023-11-21-101455_591x291_scrot](https://github.com/allinurl/goaccess/assets/5005367/b62f914d-9228-45a6-b89f-365d6680670c)

**Comment by allinurl** [comment]
This is now closed - feel free to reopen it if necessary.
