### ISSUE TITLE
Another problem with "specifier '%d'"

### ISSUE THREAD

**Issue by mrlars** [allinurl/goaccess#2583]
Hi everybody, long time and happy user here. 
I'm having troubles with a server from a while, the output is the classical 

`==3742== Token '05/Sep/2023' doesn't match specifier '%d'`

 I'm not able to solve with one of the several solutions and suggestion.

Here is a line of the log, is from Apache:

`xxx.xxx.xxx.xxx - - [30/Sep/2023:06:25:44 +0200] "GET /example/lorem/ HTTP/1.1" 200 4443 "https://www.domain.com/en/" "Mozilla/5.0 (iPhone; CPU iPhone OS 16_6_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.6 Mobile/15E148 Safari/604.1"`

The only approach that is given me another output is this
`goaccess combined.txt  --log-format='FORWARD: %v ~h{, } - %e-%^[%d:%t %^] "%r" %s %b "%R" "%u" %^' --datetime-format='%d/%b/%Y:%H:%M:%S %z' --time-format='%H:%M:%S' --date-format='%d/%b/%Y'  -a > report_access.html`

Resulting in another error
`==3936== Token for '%h' specifier is NULL.`

Someone is able to identify what i'm doing wrong?

**Comment by allinurl** [comment]
For that specific line you posted, this works for me on the latest version:

    goaccess access.log --log-format='%h %^[%x] "%r" %s %b "%R" "%u"' --datetime-format='%d/%b/%Y:%H:%M:%S %z'

![2023-11-26-163204_538x301_scrot](https://github.com/allinurl/goaccess/assets/5005367/6903eb19-ac56-4228-830d-b891cd1053e1)

**Comment by mrlars** [comment]
> For that specific line you posted, this works for me on the latest version:
> 
> ```
> goaccess access.log --log-format='%h %^[%x] "%r" %s %b "%R" "%u"' --datetime-format='%d/%b/%Y:%H:%M:%S %z'
> ```
> 


Thank you @allinurl now I receive this error:

`==1712== Token '19/Oct/2023:06:25:21 +0200' doesn't match specifier '%x'`

**Comment by 63070016** [comment]
2023/11/27 16:07:24 [error] 624#624: *29 FastCGI sent in stderr: "PHP message: PHP Notice:  Trying to access array offset on value of type null in /usr/share/zabbix/include/classes/core/CCookieSession.php on line 194" while reading response header from upstream, client: 68.183.204.205, server: example.com, request: "GET /setup.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/zabbix.sock:", host: "103.29.189.51:8080", referrer: "http://103.29.189.51:8080/"

I have this log and error %d please issue please

**Comment by 63070016** [comment]
2023/11/27 16:07:24 [error] 624#624: *29 FastCGI sent in stderr: "PHP message: PHP Notice: Trying to access array offset on value of type null in /usr/share/zabbix/include/classes/core/CCookieSession.php on line 194" while reading response header from upstream, client: 64.183.202.201, server: example.com, request: "GET /setup.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/zabbix.sock:", host: "102.23.182.51:8080", referrer: "http://102.23.182.51:8080/"

I have this log and error %d please issue please

**Comment by mrlars** [comment]
@63070016 do not hijack my thread :o)

**Comment by allinurl** [comment]
@mrlars Is your system set to English as the locale, for instance using the command `locale -a`? If not, there's a chance that your log may contain dates and months in English while your system is not configured for English. Please execute the goaccess command as follows:

    LC_TIME="en_US.UTF-8"  goaccess access.log --log-format='%h %^[%x] "%r" %s %b "%R" "%u"' --datetime-format='%d/%b/%Y:%H:%M:%S %z'

**Comment by mrlars** [comment]
> @mrlars Is your system set to English as the locale, for instance using the command `locale -a`? If not, there's a chance that your log may contain dates and months in English while your system is not configured for English. Please execute the goaccess command as follows:
> 
> ```
> LC_TIME="en_US.UTF-8"  goaccess access.log --log-format='%h %^[%x] "%r" %s %b "%R" "%u"' --datetime-format='%d/%b/%Y:%H:%M:%S %z'
> ```

and this is the answer! thank you again!

**Comment by allinurl** [comment]
Happy to know that resolved the issue. Closing this for now. If necessary, feel free to reopen it.
