### ISSUE TITLE
Minor issue with CTRL-C in Quick Help dialog

### ISSUE THREAD

**Issue by und3f** [allinurl/goaccess#2584]
If you press CTRL-C during Quick Help dialog the goaccess would print exit message over the dialog
```
SIGINT caught!
Closing  GoAccess...
```
 and keep running.

Steps to reproduce:
1. open goaccess.
2. press `?` for Quick Help dialog.
3. press `CTRL-C`.

**Comment by allinurl** [comment]
Hey, appreciate you flagging this! I've sorted it out and pushed the fix upstream. Could you give it a shot by building from [**development**](https://github.com/allinurl/goaccess#build-from-github-development)? Let me know if it clears up the issue on your end. Thanks!

**Comment by und3f** [comment]
Yeah, the issue don't appear in the latest master.
It is a bit unexpected that CTRL-C works in the main screen, but not in the quick help, but that's might be a question of personal preferences.

**Comment by allinurl** [comment]
Thanks for giving me the heads up!

I agree, it might need a few tweaks to make Ctrl+C, along with pressing 'q', work on the subdialogs. I don't think it would be too hard to implement. Are you familiar with C?

**Comment by allinurl** [comment]
BTW, I see a few ways we could handle Ctrl+C – either to close the subdialog, shut down the whole program, or just leave it as it is, ignoring it for subdialogs. Honestly, I'm leaning towards the latter or simply closing the subdialog. I'm not sure how often someone would really want to close the entire program from a subdialog. What do you think?
