### ISSUE TITLE
Diffrent-reports-analysis

### ISSUE THREAD

**Issue by ismai-can-unsal** [allinurl/goaccess#2585]
Hello,
To analyze the differences between two reports generated by "goaccess" before and after a release, what can I do? I want to see the variances before and after the release.

**Comment by allinurl** [comment]
Are you referring to two concrete HTML reports, or are you discussing two batches of access logs? If it's the former, manual analysis is the only option. If it involves two sets of access logs, tools such as sed, awk, grep, etc., can be used for preprocessing. Alternatively, stay [tuned](https://twitter.com/goaccess) for #117 as it will address your question; we are currently working on it.

**Comment by ismai-can-unsal** [comment]
@allinurl   I want to compare the statistics of two different reports named 'before-release-report.html' and 'after-release-report.html', for example.

**Comment by allinurl** [comment]
Currently, that isn't a viable option. I'm uncertain if implementation is necessary, given that #117 is expected to address much of the search capability and data comparison. I'm closing this for now, but please feel free to suggest any modifications or reopen it if necessary.
