### ISSUE TITLE
==7964== Token '11' doesn't match specifier '%d' ==7964== ==7964== Format Errors - Verify your log/date/time format

### ISSUE THREAD

**Issue by 63070016** [allinurl/goaccess#2586]
2023/11/27 16:07:24 [error] 624#624: *29 FastCGI sent in stderr: "PHP message: PHP Notice: Trying to access array offset on value of type null in /usr/share/zabbix/include/classes/core/CCookieSession.php on line 194" while reading response header from upstream, client: 64.183.202.201, server: example.com, request: "GET /setup.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/zabbix.sock:", host: "102.23.182.51:8080", referrer: "http://102.23.182.51:8080/"

I have this log and error %d please issue please

**Comment by allinurl** [comment]
Refer to [this post](https://github.com/allinurl/goaccess/issues/1856#issuecomment-1244742462) for specific information on actions you can take with goaccess and an error log.

**Comment by allinurl** [comment]
This is now closed - feel free to reopen it if necessary.
