### ISSUE TITLE
help me get 【log-format】 rule

### ISSUE THREAD

**Issue by tinybyhuang** [allinurl/goaccess#2589]
nginx log config:

`
json  '{"timestamp":"$time_iso8601",'
                 '"source":"$http_source",'
                 '"host":"$server_addr",'
                 '"clientip":"$remote_addr",'
                 '"size":$body_bytes_sent,'
                 '"responsetime":$request_time,'
                 '"upstreamtime":"$upstream_response_time",'
                 '"upstreamhost":"$upstream_addr",'
                 '"http_host":"$host",'
                 '"referer":"$http_referer",'
                 '"agent":"$http_user_agent",'
                 '"request":"$request",'
                 '"request_body":"$request_body",'
                 '"response_body":"$resp_body",'
                 '"token":"$http_token",'
                 '"upstream_http_content_type":"$upstream_http_content_type",'
                 '"status":"$status"}'
`

help me get 【log-format】 rule

**Comment by allinurl** [comment]
any updates on this?

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
