### ISSUE TITLE
Add ability to handle time in milliseconds

### ISSUE THREAD

**Issue by allinurl** [allinurl/goaccess#259]
Add specifier that handles time in milliseconds. Currently `%T`  parses the time in seconds with milliseconds precision. Issues related #176 & #258

**Comment by allinurl** [comment]
This has been implemented. The specifier is `%L` - milliseconds as a decimal number [000, 999].

Feel free to build from [master](http://goaccess.io/download#build), otherwise it will be pushed out in the upcoming release.

**Comment by nikmartin** [comment]
To add a follow up to this. does this mean if we have a log in this format:
```
"1435673425692000","180.76.15.137","1","","GET","/blog/data-ownership-in-nitropcr","301","0","0","211000","www.nitropcr.com","","Mozilla/5.0 (compatible; Baiduspider/2.0; +http://www.baidu.com/search/spider.html),gzip(gfe)","AEnB2Uo6_oFt6zlbUfcwodxyyKbvVNHi-PytOKYHJuxBOdWZgwcUe-
```
Where `1435673425692000` is Epoch Microseconds, that time_format is then expressed as `%s%L` ?

**Comment by allinurl** [comment]
@nikmartin In this case `%L` is referring to the time-taken field in a W3C log format. I'll address your log format in #262
