### ISSUE TITLE
RSS feed for GoAccess website updates/releases

### ISSUE THREAD

**Issue by retifrav** [allinurl/goaccess#2590]
A bit surprising that there is no (*I couldn't find it*) RSS feed on the [GoAccess website](https://goaccess.io), so one could subscribe to new releases announcements (*and probably other website updates*). Not complaining, just would be nice to have it.

I see there is a Twitter link, but I'm sure many would agree that Twitter is an inferior media for this purpose comparing with an RSS feed.

**Comment by allinurl** [comment]
Thank you for bringing this up. Have you thought about using the [**tag releases atom**](https://github.com/allinurl/goaccess/tags.atom) in GitHub as an alternative to an official GoAccess.io RSS feed?

**Comment by retifrav** [comment]
Oooh, GitHub tags have a feed! Never knew that, and my RSS client(s) weren't able to discover it either. Should've just asked Google about that, I guess.

Yes, tags feed does the job absolutely, thank you for pointing it out.
This can probably closed then.

**Comment by allinurl** [comment]
No biggie! Good to know it's doing the trick. I wasn't aware of it either until you asked :)
