### ISSUE TITLE
Response time format (seconds vs. milliseconds)

### ISSUE THREAD

**Issue by kasperg** [allinurl/goaccess#2597]
Thanks a bunch for sharing GoAccess. It a great tool which just works! I have a question about response time analysis that I hope someone can help me out solving. 

I have a custom log file with the following format:

`2023-12-20T08:17:21Z GET 200 260.403 ms 2048 kB 15.36% /list/default`

I have tried to parse it using the following command:

`goaccess --datetime-format='%Y-%m-%dT%H:%M:%SZ' --log-format='%x %m %s %T %h %^ %^ %^%r' --no-ip-validation`.

I end up with something like this:

```
 Hits     h% Vis.      v% Avg. T.S. Cum. T.S. Max. T.S. Mtd     Proto    Data
 ---- ------ ---- ------- --------- --------- --------- ------- -------- ----
   17 45.95%    1 100.00%   4.46 mn   1.26 hr   7.46 mn GET     ---      % /list/default
```

As I understand the output Average T.S. (time spent?) is reported in minutes but that does not make sense combined with the response time reported in milliseconds. 

I know that `%T` corresponds to "The time taken to serve the request, in seconds with milliseconds resolution" but if I switch to `%L` (The time taken to serve the request, in milliseconds as a decimal number) I get `0.00 us` in all time columns. I also tried with. `%n` for good measure but that also yielded `0.00 us`.

I wonder if it has to do with `.` or `,` is used as decimal separator? but I could not spot any way to configure this in the documentation.

Notes: Since the log does not have any host name information I (mis)use the `ms` element as the hostname combined with `--no-ip-validation`.

**Comment by allinurl** [comment]
Great question! It appears that you can accomplish this by utilizing `%L` when splitting the `.` to capture the whole number.

    goaccess access.log --datetime-format='%Y-%m-%dT%H:%M:%SZ' --log-format='%x %m %s %L.%^ %h %b %^ %^ %U' --no-ip-validation

Let me know if that helps

**Comment by kasperg** [comment]
That works like a charm! Really appreciate the help.
