### ISSUE TITLE
log format errors

### ISSUE THREAD

**Issue by darvadrasthya** [allinurl/goaccess#2613]
==1790== FILE: c:\laragon\bin\apache\httpd-2.4.54-win64-VS16\logs\access.log
==1790== Parsed 10 lines producing the following errors:
==1790==
==1790== Token for '%b' specifier is NULL.
==1790== Token for '%b' specifier is NULL.
==1790== Token for '%b' specifier is NULL.
==1790== Token for '%b' specifier is NULL.
==1790== Token for '%b' specifier is NULL.
==1790== Token for '%b' specifier is NULL.
==1790== Token for '%b' specifier is NULL.
==1790== Token for '%b' specifier is NULL.
==1790== Token for '%b' specifier is NULL.
==1790== Token for '%b' specifier is NULL.

**Comment by allinurl** [comment]
Please share a few lines from your access log along with the command you use to run goaccess.

**Comment by darvadrasthya** [comment]
i just solved this problem, thankyou for your attention
