### ISSUE TITLE
Geolocatin Sorting

### ISSUE THREAD

**Issue by ifeldshteyn** [allinurl/goaccess#2614]
It looks like sorting doesn't seem to work. This is on 1.8.1

I have it sorted down by **Visitors** but it actually sorts it by **Hits**. 

![image](https://github.com/allinurl/goaccess/assets/36711831/b522496d-0bd7-4cbf-9a59-6bcfe5f1fe02)

**Comment by allinurl** [comment]
Thanks for letting me know. It seems like the sorting is impacting the parent node (continent) but not the child nodes. Can you confirm if this is the case?

**Comment by ifeldshteyn** [comment]
Confirmed. Parent nodes are sorted fine, the child nodes do not.

**Comment by allinurl** [comment]
I've made a commit to fix this issue. Feel free to build from [development](https://github.com/allinurl/goaccess?tab=readme-ov-file#build-from-github-development) and check if it resolves the problem on your end. If not, no worries—it'll be included in the next release, coming soon. [Keep an eye out](https://twitter.com/goaccess?lang=en). Thanks again!
