### ISSUE TITLE
Error appear when installing v1.9

### ISSUE THREAD

**Issue by minhluan259** [allinurl/goaccess#2619]
I got this error when run command make install (Centos 7)
```
make[2]: Entering directory `/tmp/goaccess-1.9'
depbase=`echo src/parser.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
cc -DLOCALEDIR=\"/usr/local/share/locale\" -DHAVE_CONFIG_H -I. -I./src    -O2 -DSYSCONFDIR=\"/usr/local/etc\" -Wall -Wextra -Wnested-externs -Wformat=2 -g -Wmissing-prototypes -Wstrict-prototypes -Wmissing-declarations -Wwrite-strings -Wshadow -Wpointer-arith -Wsign-compare -Wbad-function-cast -Wcast-align -Wdeclaration-after-statement -Wshadow -Wold-style-definition -pthread -MT src/parser.o -MD -MP -MF $depbase.Tpo -c -o src/parser.o src/parser.c &&\
mv -f $depbase.Tpo $depbase.Po
src/parser.c: In function 'ignore_status_code':
src/parser.c:1627:3: error: 'for' loop initial declarations are only allowed in C99 mode
   for (int i = 0; i < conf.ignore_status_idx; i++)
   ^
```

**Comment by allinurl** [comment]
Thanks for the heads-up! It seems like CentOS 7 might be rolling with different compiler versions and settings. I'll sort that out. Meanwhile, as a quick fix, give this a shot:

```
# CFLAGS="-std=c99" ./configure --enable-utf8 --enable-geoip=mmdb
# make
...
```

or you can pass it directly to make:

    # make CFLAGS="-std=c99"

**Comment by minhluan259** [comment]
@allinurl thank you, it's showing another error:
```
cc -DLOCALEDIR=\"/usr/local/share/locale\" -DHAVE_CONFIG_H -I. -I./src    -O2 -DSYSCONFDIR=\"/usr/local/etc\" -Wall -Wextra -Wnested-externs -Wformat=2 -g -Wmissing-prototypes -Wstrict-prototypes -Wmissing-declarations -Wwrite-strings -Wshadow -Wpointer-arith -Wsign-compare -Wbad-function-cast -Wcast-align -Wdeclaration-after-statement -Wshadow -Wold-style-definition -std=c99 -MT src/error.o -MD -MP -MF $depbase.Tpo -c -o src/error.o src/error.c &&\
mv -f $depbase.Tpo $depbase.Po
src/error.c: In function 'setup_sigsegv_handler':
src/error.c:141:20: error: storage size of 'act' isn't known
   struct sigaction act;
                    ^
src/error.c:143:3: warning: implicit declaration of function 'sigemptyset' [-Wimplicit-function-declaration]
   sigemptyset (&act.sa_mask);
   ^
src/error.c:143:3: warning: nested extern declaration of 'sigemptyset' [-Wnested-externs]
src/error.c:144:24: error: 'SA_RESETHAND' undeclared (first use in this function)
   act.sa_flags = (int) SA_RESETHAND;
                        ^
src/error.c:144:24: note: each undeclared identifier is reported only once for each function it appears in
src/error.c:147:3: warning: implicit declaration of function 'sigaction' [-Wimplicit-function-declaration]
   sigaction (SIGSEGV, &act, &old_sigsegv_handler);
   ^
src/error.c:147:3: warning: nested extern declaration of 'sigaction' [-Wnested-externs]
src/error.c:141:20: warning: unused variable 'act' [-Wunused-variable]
   struct sigaction act;
```

**Comment by allinurl** [comment]
I've pushed a commit that's supposed to handle those declarations errors. Could you try building from the [development](https://github.com/allinurl/goaccess?tab=readme-ov-file#build-from-github-development) and check if it resolves the issue on your end? Let me know how it goes. Thanks!

**Comment by minhluan259** [comment]
Thanks, it's solve the issue.

**Comment by narule** [comment]
> @allinurl谢谢，它显示了另一个错误：
> 
> ```
> cc -DLOCALEDIR=\"/usr/local/share/locale\" -DHAVE_CONFIG_H -I. -I./src    -O2 -DSYSCONFDIR=\"/usr/local/etc\" -Wall -Wextra -Wnested-externs -Wformat=2 -g -Wmissing-prototypes -Wstrict-prototypes -Wmissing-declarations -Wwrite-strings -Wshadow -Wpointer-arith -Wsign-compare -Wbad-function-cast -Wcast-align -Wdeclaration-after-statement -Wshadow -Wold-style-definition -std=c99 -MT src/error.o -MD -MP -MF $depbase.Tpo -c -o src/error.o src/error.c &&\
> mv -f $depbase.Tpo $depbase.Po
> src/error.c: In function 'setup_sigsegv_handler':
> src/error.c:141:20: error: storage size of 'act' isn't known
>    struct sigaction act;
>                     ^
> src/error.c:143:3: warning: implicit declaration of function 'sigemptyset' [-Wimplicit-function-declaration]
>    sigemptyset (&act.sa_mask);
>    ^
> src/error.c:143:3: warning: nested extern declaration of 'sigemptyset' [-Wnested-externs]
> src/error.c:144:24: error: 'SA_RESETHAND' undeclared (first use in this function)
>    act.sa_flags = (int) SA_RESETHAND;
>                         ^
> src/error.c:144:24: note: each undeclared identifier is reported only once for each function it appears in
> src/error.c:147:3: warning: implicit declaration of function 'sigaction' [-Wimplicit-function-declaration]
>    sigaction (SIGSEGV, &act, &old_sigsegv_handler);
>    ^
> src/error.c:147:3: warning: nested extern declaration of 'sigaction' [-Wnested-externs]
> src/error.c:141:20: warning: unused variable 'act' [-Wunused-variable]
>    struct sigaction act;
> ```

How to solve it? I have the same problem
