### ISSUE TITLE
Install error CentOS 7

### ISSUE THREAD

**Issue by MaxMaster1984** [allinurl/goaccess#2624]
Centos 7.4
1.81 installed but i cant install 1.9

cc -DLOCALEDIR=\"/usr/local/share/locale\" -DHAVE_CONFIG_H -I. -I./src    -O2 -DSYSCONFDIR=\"/usr/local/etc\" -Wall -Wextra -Wnested-externs -Wformat=2 -g -Wmissing-prototypes -Wstrict-prototypes -Wmissing-declarations -Wwrite-strings -Wshadow -Wpointer-arith -Wsign-compare -Wbad-function-cast -Wcast-align -Wdeclaration-after-statement -Wshadow -Wold-style-definition -pthread -MT src/parser.o -MD -MP -MF $depbase.Tpo -c -o src/parser.o src/parser.c &&\
mv -f $depbase.Tpo $depbase.Po
src/parser.c: In function ‘ignore_status_code’:
src/parser.c:1627:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
   for (int i = 0; i < conf.ignore_status_idx; i++)
   ^
src/parser.c:1627:3: note: use option -std=c99 or -std=gnu99 to compile your code
src/parser.c: In function ‘read_lines_thread’:
src/parser.c:1988:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
   for (int i = 0; i < job->p; i++) {
   ^
src/parser.c: In function ‘process_lines_thread’:
src/parser.c:2051:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
   for (int i = 0; i < job->p; i++) {
   ^
src/parser.c: In function ‘init_jobs’:
src/parser.c:2076:7: error: ‘for’ loop initial declarations are only allowed in C99 mode
       for (int i = 0; i < conf.chunk_size; i++)
       ^
src/parser.c: In function ‘free_jobs’:
src/parser.c:2126:7: error: ‘for’ loop initial declarations are only allowed in C99 mode
       for (int i = 0; i < conf.chunk_size; i++)
       ^
make[2]: *** [src/parser.o] Error 1
make[2]: Leaving directory `/var/log/nginx/123/goaccess-1.9'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/var/log/nginx/123/goaccess-1.9'
make: *** [all] Error 2

**Comment by allinurl** [comment]
Thanks for letting me know. The problem has been fixed upstream and will be part of the next release. If you need it sooner, you can install from the [master branch](https://github.com/allinurl/goaccess?tab=readme-ov-file#build-from-github-development).

**Comment by allinurl** [comment]
The issue has been resolved in the latest version, v1.9.1. Closing this for now. Feel free to reopen it if necessary.
