### ISSUE TITLE
Format Errors since GoAccess 1.9

### ISSUE THREAD

**Issue by onlime** [allinurl/goaccess#2625]
Since having upgraded GoAccess from 1.8.1 to 1.9 (Debian bookworm packages), we're getting a lot of these errors:

```
==3918168==
==3918168== Format Errors - Verify your log/date/time format
```

On some days, this happens every hour (every run, we run goaccess every hour), sometimes just on single runs. It's hard to say on which logfile it happens (need to introduce some more debugging), but it's basically a loop over a couple of `access.log` files, running these `goaccess` commands:

```bash
grep -P " (foo.example.com)( \d+)?$" /var/www/web999/logs/access.log | goaccess - --restore --persist -o /var/www/web999/system/goaccess/foo/2024-02/index.html --db-path /var/www/web2/system/goaccess/foo/2024-02/db/ --keep-last=29
grep -P " (example.com)( \d+)?$" /var/www/web999/logs/access.log | goaccess - --restore --persist -o /var/www/web999/system/goaccess/www/2024-02/index.html --db-path /var/www/web2/system/goaccess/www/2024-02/db/ --keep-last=29
```

all `access.log` use the same Apache log format:

```apache
LogFormat "%h %l %u %t %I %O \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\" %V %p" combined
```

looking like this:

```
1.2.3.4 - - [04/Feb/2024:12:02:15 +0100] 37 16933 "GET /favicon.ico HTTP/2.0" 200 16618 "https://example.com/something" "Mozilla/5.0 (X11; Linux x86_64; rv:122.0) Gecko/20100101 Firefox/122.0" foo.example.com 443
```

In 1.8.1 this was just working fine and `Format Errors - Verify your log/date/time format` error never popped up. Not need to specify `--log-format`, as it was correctly detected.

Any help greatly appreciated!
Thanks, Philip

**Comment by allinurl** [comment]
Please review the details provided in this [**post**](https://github.com/allinurl/goaccess/issues/1683#issuecomment-1922679736) and confirm if it resolves the issue on your side. Planning to deploy the updated release shortly. Appreciate your feedback. Thank you.

**Comment by onlime** [comment]
Hi @allinurl Thanks for your fast response and sorry about not finding time to further debug this. Yes, it seems to have been #1683 related and since having upgraded from 1.9.0 to [1.9.1](https://goaccess.io/release-notes#release-1.9.1) this morning, the `Format Errors` no longer popped up.

Thank you for shipping 1.9.1 that fast!
