### ISSUE TITLE
Error in Custom Log Format with TZ

### ISSUE THREAD

**Issue by npedro3** [allinurl/goaccess#2627]
I have this acess.log file
```

"127.0.0.1" "NULL-AUTH-USER" "05/Feb/2024:11:56:17 +0000" "GET /home/ HTTP/1.1" 200 4379
"127.0.0.1" "NULL-AUTH-USER" "05/Feb/2024:11:56:17 +0000" "GET / HTTP/1.1" 200 4626
"127.0.0.1" "NULL-AUTH-USER" "05/Feb/2024:11:56:17 +0000" "GET /home/ HTTP/1.1" 200 4379
"127.0.0.1" "NULL-AUTH-USER" "05/Feb/2024:11:56:17 +0000" "GET /home/w3.css HTTP/1.1" 200 38114
"127.0.0.1" "NULL-AUTH-USER" "05/Feb/2024:11:56:17 +0000" "GET /home/w3-theme.css HTTP/1.1" 200 1349
"127.0.0.1" "NULL-AUTH-USER" "05/Feb/2024:11:56:17 +0000" "GET /home/build.js HTTP/1.1" 200 812
"127.0.0.1" "NULL-AUTH-USER" "05/Feb/2024:11:56:17 +0000" "GET /home/images/logo_WP10_whitestroke.png HTTP/1.1" 200 3587
"127.0.0.1" "NULL-AUTH-USER" "05/Feb/2024:11:56:17 +0000" "GET /home/webresources/tools/build HTTP/1.1" 200 193
"127.0.0.1" "NULL-AUTH-USER" "05/Feb/2024:11:56:17 +0000" "GET /home/webresources/tools/cacheStatus HTTP/1.1" 200 34
```

and i am try to run the GoAccess using this formats but not working
time-format %H:%M:%S %z
date-format %d/%b/%Y
log-format "%h" "%^" "%d:%t" "%m %U %H" %s %b
Can someone please help me find the right format?

**Comment by allinurl** [comment]
Apologies for the wait! This should do the trick. Keep me posted on how it goes!

    goaccess access.log --log-format='"%h" "%e" "%x" "%r" %s %b' --datetime-format='%d/%b/%Y:%H:%M:%S %z' --date-spec=min --tz=America/New_York

![2024-02-09-180418_617x473_scrot](https://github.com/allinurl/goaccess/assets/5005367/7ad2b7a0-ec29-4ee4-9f1c-e2efe054a83d)

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
