### ISSUE TITLE
TLS settings does not parse

### ISSUE THREAD

**Issue by williamdes** [allinurl/goaccess#2628]
In my nginx log lines I use the format: `{$ssl_protocol/$ssl_cipher}` at the end of the log line
Example: `{TLSv1.2/ECDHE-RSA-AES256-GCM-SHA384}`

My `log-format` rule ends with `{%K/%k}`
I tried inverting the K/k or k/K but it did not change.
But in the html report there is no data for "Encryption".
Can you check why ?

**Comment by allinurl** [comment]
Could you share a few lines from your log directly, along with the log format you're using in GoAccess? Thanks

**Comment by williamdes** [comment]
> Could you share a few lines from your log directly, along with the log format you're using in GoAccess? Thanks

Well, I tried to minimize the log format, but it ended up in encryption working. So I reverted back to the full one and it stopped working. Very weird.

### Works fine

```nginx
log_format special_logs '$remote_addr - $upstream_response_time [$time_local] "$request" {$ssl_protocol/$ssl_cipher}';
```

```
log_format %h - %^ [%d:%t %^] "%r" {%K/%k}
```

### Does not work

```
2a01:eee:bbb:9080::5b7c:4b21 - - [fcde8394d2521f69eb4e0c5a310eafb4][-:-][-][11/Feb/2024:13:59:34 +0000] "GET / HTTP/2.0" 200 22874 "-" "Mozilla/5.0 (Windows NT 10.0; rv:122.0) Gecko/20100101 Firefox/122.0" "-" 0.020 0.019 {TLSv1.3/TLS_AES_256_GCM_SHA384}
2a01:eee:bbb:9080::5b7c:4b21 - - [26dcac69be394426a68ac8d032c6c9d6][-:-][-][11/Feb/2024:13:59:37 +0000] "GET /version HTTP/2.0" 200 17 "-" "Mozilla/5.0 (Windows NT 10.0; rv:122.0) Gecko/20100101 Firefox/122.0" "-" 0.016 0.016 {TLSv1.3/TLS_AES_256_GCM_SHA384}
```

I removed some stuff in the nginx format since it is a bit confidential config. But nothing problematic since in the final log line they where only "-" meaning no value. But that's why in the goaccess log line values are expected.
```nginx
log_format api_logs '$remote_addr - - [$request_id][-:-][-][$time_local] '
    '"$request" $status $body_bytes_sent '
    '"$http_referer" "$http_user_agent" "$http_x_forwarded_for" '
    '$request_time $upstream_response_time '
    '{$ssl_protocol/$ssl_cipher}';
```

```
log-format %h - %^ [%^][%e][%^][%d:%t %^] "%r" %s %b "%R" "%u" "~h" %^ %^ {%K/%k}
```

**Comment by allinurl** [comment]
This is what functions effectively from my side:

    # goaccess access.log --log-format='%h %^[%^][%^][%^][%x] "%r" %s %b "%R" "%u" %^ %T %^ {%K/%k}' --datetime-format='%d/%b/%Y:%H:%M:%S %z' --date-spec=min --tz=America/New_York

![2024-02-11-163154_622x158_scrot](https://github.com/allinurl/goaccess/assets/5005367/11731b59-f442-4a89-9ab0-267ed44b5d93)

**Comment by williamdes** [comment]
I tried with

Works:
```sh
goaccess ./logs.txt --log-format='%h %^[%^][%^][%^][%d:%t %^] "%r" %s %b "%R" "%u" %^ %T %^ {%K/%k}'
```

Also works:
```sh
goaccess ./logs.txt --log-format='%h %^[%^][%^][%^][%d:%t %^] "%r" %s %b "%R" "%u" %^ %^ %^ {%K/%k}'
```

But then I tried to change `"%R"` into `"%r"` it breaks !
So what's about that small change ?

**Comment by allinurl** [comment]
I'm a bit confused about the question, but just to clarify: `%R` refers to the referrer, while `%r` refers to the request.

**Comment by williamdes** [comment]
> I'm a bit confused about the question, but just to clarify: %R refers to the referrer, while %r refers to the request.

If you try exactly my commands you will see that in one case when you use `%R` it works and `%r` it does not.
Maybe there is something in the order of the parsing or code.

**Comment by allinurl** [comment]
I don't find any problems with the two examples you provided, except for `%T`. 

Just to clarify, `%r` represents the request, so substituting it with %R wouldn't be feasible due to validation requirements. However, `%R` doesn't undergo strict validation since it solely pertains to the referrer.

**Comment by williamdes** [comment]
> I don't find any problems with the two examples you provided, except for %T.

Yeah, I will have to fix this. But encryption is not linked to the date, right ?

Anyway, I would say the topic si about K and k and not about all everything else. So could we only consider that 
between

```sh
goaccess ./logs.txt --log-format='%h %^[%^][%^][%^][%d:%t %^] "%r" %s %b "%R" "%u" %^ %^ %^ {%K/%k}'
```
And
```sh
goaccess ./logs.txt --log-format='%h %^[%^][%^][%^][%d:%t %^] "%r" %s %b "%r" "%u" %^ %^ %^ {%K/%k}'
```

The encryption settings should still parse like they did ?

**Comment by allinurl** [comment]
Thanks for letting me know and clarifying the issue. I've pushed a fix to solve it. Please feel free to pull from master or build from [development](https://github.com/allinurl/goaccess?tab=readme-ov-file#build-from-github-development) and let me know if that helps.

**Comment by williamdes** [comment]
Thank you very much, I will try this new commit and let you know
