### ISSUE TITLE
Debug log format methods

### ISSUE THREAD

**Issue by bancore** [allinurl/goaccess#263]
Hello, I'm trying to parse with this settings my custom nginx logs, but without success:
time-format %H:%M:%S %z
date_format %d/%b/%Y:%T
log-format %d %H %^ %h "%r" "%R" "%u" %^ %^ %^ %T %s %b %^

test log string is:
01/Jul/2015:03:03:03 +0000 http admin 127.0.0.1 "GET /status HTTP/1.1" "-" "curl/1.1.1 (x86_64-redhat-linux-gnu)" - 111 . 0.000 200 254 112

goaccess version 0.9.1 starts but no output. Is there any methods to debug "what goaccess see" with my log-format?

**Comment by allinurl** [comment]
Currently there's not an easy way to see which token is not matching the pattern other than debugging the code. I can certainly add this to the to-do list. Thanks for pointing it out.

Anyways, the following works for the sample log you posted:

    log-format %d:%t %^ %^ %^ %h "%r" "%R" "%u" %^ %^ %^ %T %s %b
    date-format %d/%b/%Y
    time-format %H:%M:%S

Let me know how it goes.

**Comment by bancore** [comment]
Thank you for quick answer! It works with your string, looks like %H mean something other for goaccess then just "http"/"https".

**Comment by allinurl** [comment]
Great! At the moment, it does not report metrics for http/https. 

Just opened a new issue #264 for your debugging suggestion.

**Comment by ottok** [comment]
Running latest development master and I have the same problem. It would be really great if goaccess outputted some debug info about why it cannot parse the log.

```
log-format %^ $h %^ %^ [%d:%t %^] "$r" $s $b "$R" "$u" %^ %^ %T
time-format %H:%M:%S
date-format %d/%b/%Y

www.example.com 173.252.110.119 - - [27/Jul/2015:14:57:16 +0300] "GET /wp-content/uploads/2015/07/ScreenHunter_101-Jul.-16-16.28.jpg HTTP/1.1" 200 80567 "-" "facebookexternalhit/1.1 (+http://www.facebook.com/externalhit_uatext.php)" MISS - 0.304
```

"goaccess -c" is a great tool to interactively see and write the config, and it replies "no hits" when it does not work. However if one is unable to manually see the problem if would help if there was more debug output.

**Comment by ottok** [comment]
Ok, solved problem with s/$/%

**Comment by allinurl** [comment]
Great. Yes, #264 should address the missing log/date/time format. Thanks.
