### ISSUE TITLE
 Token '2024/01/12' doesn't match specifier '%h'

### ISSUE THREAD

**Issue by OG-N** [allinurl/goaccess#2639]
Sample complete log

2024/01/12 07:49:25 [error] 944#944: *57 connect() failed (111: Unknown error) while connecting to upstream, client: 102.91.69.213, server: xxx.xxx-sc.org, request: "GET /login HTTP/1.1", upstream: "http://127.0.0.1:7305/login", host: " xxx.xxx-sc.org", referrer: "https:// xxx.xxx-sc.org/login"

**Comment by allinurl** [comment]
What format did you use?

**Comment by OG-N** [comment]
goaccess accesslog --log-format='%h %^[%d:%t %^] "%r" %s %b "%R" "%u" %^' --date-format=%d/%b/%Y --time-format=%T /var/log/nginx/app-error.log.error

**Comment by allinurl** [comment]
It appears to be resembling an access log. Please review the [custom log fields](https://goaccess.io/man#custom-log) to ensure they match with your log.

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
