### ISSUE TITLE
Real Time HTML will the page refresh data automatically or must I refresh on the browser?

### ISSUE THREAD

**Issue by lzplzp886** [allinurl/goaccess#2640]
Great to hear it worked. Yes, the actual generated html report won't change, it updates the data via a WebSocket connection and through Javascript the report is visually updated.

_Originally posted by @allinurl in https://github.com/allinurl/goaccess/issues/2341#issuecomment-1163579010_
            
Hi I wanna ask, what is the right behavior I should expect below, as for now if I wanna see the latest data I must manually refresh the browser to get it:

While I keep the browser running, while the page dynamically updates itself per second(right top counter keeps ticking) or when there's new log data comes to the file.
Or I must manually refresh the browser to get the latest report data?

**Comment by H1r0Sh1mA** [comment]
@lzplzp886 the data counters on page should refresh automatically. In order to do so you need to setup web socket configuration (--wss-url=<[scheme://]url[:port]>) If it is all set up correct, then you will see the green dot under the gear icon on the left-side panel.

**Comment by H1r0Sh1mA** [comment]
@lzplzp886 You could try to debug the problem by lookup in to the browser's dev console.  All the auto requests-responses will be there.

**Comment by rc5hack** [comment]
> when I move the mouse to that dot it shows connected to wss://www.xxx.com:7890

Do you run `goaccess` with docker/docker-compose or not? If yes, maybe you don't exposing ws/wss port properly. Please show how do you run `goaccess` (command, docker-compose yaml config, etc).

**Comment by lzplzp886** [comment]
> @lzplzp886 You could try to debug the problem by lookup in to the browser's dev console. All the auto requests-responses will be there.

Seems no errors on dev console. Everything loaded.

**Comment by lzplzp886** [comment]
> > when I move the mouse to that dot it shows connected to wss://www.xxx.com:7890
> 
> Do you run `goaccess` with docker/docker-compose or not? If yes, maybe you don't exposing ws/wss port properly. Please show how do you run `goaccess` (command, docker-compose yaml config, etc).

Didn't use goaccess :(

**Comment by rc5hack** [comment]
Please show how do you run `goaccess` (full command with all args).

**Comment by allinurl** [comment]
@lzplzp886 As mentioned by @rc5hack, could you please show how you are running GoAccess? Additionally, can you confirm that your access.log is being updated? For example, you can use the `tail -F access.log` command. Also, take a look at the network panel in the browser's developer tools and check the WebSocket (WS) connection. It should display the data flowing through the pipe.

**Comment by lzplzp886** [comment]
> @lzplzp886 As mentioned by @rc5hack, could you please show how you are running GoAccess? Additionally, can you confirm that your access.log is being updated? For example, you can use the `tail -F access.log` command. Also, take a look at the network panel in the browser's developer tools and check the WebSocket (WS) connection. It should display the data flowing through the pipe.

Thanks for the help. I figured it out. So apparently access.log only being updated when request on visitor's side terminated. So I do see the page refreshed automatically after access.log being updated. :)
