### ISSUE TITLE
Token doesn't match specifier '%h' for nginx format

### ISSUE THREAD

**Issue by zengzjie** [allinurl/goaccess#2641]
log_format main  '$remote_addr - $remote_user [$time_local] "$request" '
                              '$request_time $request_length '
                              '$status $body_bytes_sent "$http_referer" '
                              '"$http_user_agent"';

access.log：
10.192.133.81 - - [12/Mar/2024:09:44:22 +0800] "GET /report HTTP/1.1" 0.000 471 404 555 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"

Looking forward to receiving your reply，Thanks

**Comment by allinurl** [comment]
Sorry for the delay. This should work:

    # goaccess access.log --log-format='%h %^[%d:%t %^] "%r" %T %^ %s %b "%R" "%u"' --date-format=%d/%b/%Y --time-format=%T

Let me know how it goes.

**Comment by zengzjie** [comment]
> 抱歉耽搁了。这应该有效：
> 
> ```
> # goaccess access.log --log-format='%h %^[%d:%t %^] "%r" %T %^ %s %b "%R" "%u"' --date-format=%d/%b/%Y --time-format=%T
> ```
> 
> 让我知道事情的后续。

I will try it later，Thank you for your reply

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
