### ISSUE TITLE
Documentation: multiple `--output` options at once

### ISSUE THREAD

**Issue by rc5hack** [allinurl/goaccess#2643]
I experimentally found out that it is possible to parse log once, with just one `goaccess` run, and to save two outputs at once - say HTML and JSON.

E.g.
```sh
goaccess /path/to/log --log-format=COMBINED --output /path/to/report.html --output /path/to/report.json
```

However, this is unclear from the [documentation](https://goaccess.io/man#options):
```
 -o --output=<json|csv|html>

Write output to stdout given one of the following files and the corresponding extension for the output format:

    /path/file.csv - Comma-separated values (CSV)
    /path/file.json - JSON (JavaScript Object Notation)
    /path/file.html - HTML
```

Please consider to add few words on this to documentation.

**Comment by allinurl** [comment]
Thank you for letting me know. I've updated the man pages to include this feature. I'm closing this now, but feel free to reopen it if necessary.
