### ISSUE TITLE
Token for '%d' specifier is NULL.

### ISSUE THREAD

**Issue by jorgearmijo882** [allinurl/goaccess#2646]
Hi, please your help

I have these access_log configuration 

 LogFormat "%{%Y-%m-%dT%T}t%{%z}t %h \"%r\" %>s \"%{Referer}i\" %B \"%{User-Agent}i\" %m " combined

2024-03-13T16:17:11-0500 181.198.57.25 "GET url........ HTTP/1.1" 503 "url................." 507 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36" GET

I try to configure goaccess with these configurations, but i continue have problems to create a report.

time-format %H:%M:%S
date-format %Y-%m-%d

log-format %d{%Y-%m-%dT%H:%M:%S%z} %h %^ "%r" %>s "%{Referer}i" %b "%{User-Agent}i" %m
gg

==1966346== Token for '%d' specifier is NULL.
==1966346== Format Errors - Verify your log/date/time format

**Comment by allinurl** [comment]
Please give this a try, it should get the job done.

    # goaccess access.log --log-format='%dT%t-%^ %h "%r" %s "%R" %b "%u"' --date-format=%Y-%m-%d --time-format=%T

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
