### ISSUE TITLE
Separate iOS from Macintosh devices

### ISSUE THREAD

**Issue by Csardelacal** [allinurl/goaccess#265]
I know that they're both Apple devices, but in my opinion it makes little sense to group them as one big category. Android and Linux are separate, so it would seem reasonable to not include Apple touch devices in the Mac group.

It's less about the rendering capabilities of the devices (which would be almost identical) but about the desktop / mobile segmentation.

Maybe instead add a section with a desktop / mobile ratio?

**Comment by allinurl** [comment]
What version are you using? The two were split in v0.9.1

**Comment by Csardelacal** [comment]
Yeah, seems the machine ran automatic updates during the weekend and the issue is gone. I am running 0.9.1 right now and it seems to work perfectly fine.

Thank you very much again for the great job you're doing with goaccess, and I'll stay on the hunt for new bugs.
