### ISSUE TITLE
libssl1.1 Dependency 

### ISSUE THREAD

**Issue by ash34** [allinurl/goaccess#2650]
Seems the latest goaccess version has a dependency on a libssl version that is no longer available. 

The following packages have unmet dependencies:
 goaccess : Depends: libssl1.1 (>= 1.1.0) but it is not installable
 
This is when trying to install with apt from the official goaccess Ubuntu repo.

libssl3 is the correct version?

**Comment by allinurl** [comment]
Thanks for letting me know about that. Which version of Ubuntu are you using?

**Comment by ash34** [comment]
It’s 23.10

**Comment by allinurl** [comment]
Closing this since it was addressed in version 1.9.2. Please let me know otherwise.
