### ISSUE TITLE
Trying to parse nginx real-time behind a proxy + docker

### ISSUE THREAD

**Issue by idomic** [allinurl/goaccess#2652]
Hi, I'm trying to use goaccess to parse nginx logs.

I've been trying locally:

`tail -F access.log | docker run -v localDir:/app -p 81:81 --rm -i -e LANG=$LANG goaccess -a -o report.html --log-format COMBINED --real-time-html -`

And this works fine, I can see the report.html has some data.
When I try to do it via ECS I get an empty `report.html`
https://young-butterfly-8600.dev.ploomberapp.io/report
https://young-butterfly-8600.dev.ploomberapp.io/logs

Any idea what's wrong? I tried checking the docs for it but couldn't find it.
This is how I'm triggering it:
`goaccess -f /config/log/nginx/access.log -o /config/log/nginx/report.html --real-time-html`
My nginx serves the `report.html` file as part of an alias at `/report`.

I also have a conf where I set the log-format to combined

**Comment by allinurl** [comment]
What results are you seeing in your browser's console? Do you see the green dot next to the hamburger menu? Thanks

**Comment by allinurl** [comment]
If you don't require a real-time report, you can execute it via cron, for example, every hour, to generate a standalone report without the necessity of a websocket. Just omit the `--real-time-html` flag.

**Comment by allinurl** [comment]
It appears that the client is unable to locate the service on that port. While I'm not completely familiar with the configuration you have in place, there have been several questions about this. Please take a look at this example: [GitHub issue #1297](https://github.com/allinurl/goaccess/issues/1297), or just run a search within the issues for `proxy_pass`.

Let me know if that helps.

**Comment by allinurl** [comment]
I'm still seeing the same issue: `WebSocket connection to 'ws://localhost:81/ws/' failed:`. Are you able to observe the green dot on your side?

Regarding the ELB health check, it seems like you could potentially exclude that IP using the `-e 10.0.25.73` flag.

**Comment by allinurl** [comment]
Thanks for passing along that info. I'm glad to hear you got it working. Feel free to reopen if necessary.
