### ISSUE TITLE
goaccess doesn't seem to like hostnames like "localhost"

### ISSUE THREAD

**Issue by jnob1** [allinurl/goaccess#2653]
Parser gives errors like:
       Token 'localhost' doesn't match specifier '%h'
Any way to avoid this?

**Comment by allinurl** [comment]
If a valid IP isn't provided for the `%h` specifier, please utilize the `--no-ip-validation` option.

**Comment by jnob1** [comment]
Thanks! That fixed the issue.

**Comment by allinurl** [comment]
Happy to hear that it worked out. I'll go ahead and close this for now, but feel free to reopen it if needed.
