### ISSUE TITLE
Token '- [03/Apr/2024' doesn't match specifier '%d'

### ISSUE THREAD

**Issue by Xuezenghuigithub** [allinurl/goaccess#2656]
This is an example of my Nginx log:

```
10.232.9.57:10718, 10.232.25.9 = 10.232.25.9 - - [03/Apr/2024:00:00:11 +0800] "GET /api/sample HTTP/1.1" 200 63 "-" "membership/2.1.10 Alamofire/5.0.0-rc.2" "10.232.9.57:10718" 0.011"eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJvbiIsInVzZXJJZCI6MTkxOTU1MSwiaWF0IjoxNzA4NDQzODY1fQ.-73XU5cdMUIvGlyzTz-nEwTDMCGYuJTnsWkyapGQdPg2hhOm6b8l3bsjYEhL9-6rkP1fW2p-teonHI6vs4ECnQ"

10.232.9.57:65052, 10.232.25.7 = 10.232.25.7 - - [03/Apr/2024:00:00:11 +0800] "GET /api/sample HTTP/1.1" 200 1014 "https://servicewechat.com/wxf3ae719fecac9fe9/66/page-frame.html" "Mozilla/5.0 (iPhone; CPU iPhone OS 16_7_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 MicroMessenger/8.0.46(0x18002e2c) NetType/WIFI Language/zh_CN" "10.232.9.57:65052" 0.198"eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJvbiIsInVzZXJJZCI6MjU5NzkyOCwiaWF0IjoxNzEyMDczNjA3fQ.YTPs1KdEVC95T3W_UWL7MUSbitHiqvDEv52Owy0vlaScm_bbhHIDRfs3KlI-t6t552CUrjkVnJRe8fxvn02mNA"
```

This is my Nginx log format:

```
log_format main '$proxy_add_x_forwarded_for = $remote_addr - $remote_user [$time_local] "$request" '
    '$status $body_bytes_sent "$http_referer" '
    '"$http_user_agent" "$http_x_forwarded_for" $request_time'
    '"$http_authorization"';
```

I got the format from nginx2goaccess and changed to this:

```
goaccess access.log --log-format='%^ = %^ - %^ [%d:%t %^] "%r"  %s %b "%R"  "%u" "%^" %T "%^"' --datetime-format='%d/%b/%Y:%H:%M:%S %z' --time-format='%H:%M:%S' --date-format='%d/%b/%Y'
```

But still got this error:

```
==10570== GoAccess - version 1.9.1 - Feb  6 2024 01:27:39
==10570== Config file: /usr/local/Cellar/goaccess/1.9.1/etc/goaccess/goaccess.conf
==10570== https://goaccess.io - <hello@goaccess.io>
==10570== Released under the MIT License.
==10570==
==10570== FILE: error.log
==10570== 已解析 10 行 出现以下错误:
==10570==
==10570== Token '- [03/Apr/2024' doesn't match specifier '%d'
==10570== Token '- [03/Apr/2024' doesn't match specifier '%d'
==10570== Token '- [03/Apr/2024' doesn't match specifier '%d'
==10570== Token '- [03/Apr/2024' doesn't match specifier '%d'
==10570== Token '- [03/Apr/2024' doesn't match specifier '%d'
==10570== Token '- [03/Apr/2024' doesn't match specifier '%d'
==10570== Token '- [03/Apr/2024' doesn't match specifier '%d'
==10570== Token '- [03/Apr/2024' doesn't match specifier '%d'
==10570== Token '- [03/Apr/2024' doesn't match specifier '%d'
==10570== Token '- [03/Apr/2024' doesn't match specifier '%d'
==10570==
==10570== 格式错误 - 请检查你的日志/日期/时间格式
```

**Comment by allinurl** [comment]
Apologies for the delay. This should address the issue:

    # goaccess access.log --log-format='%^= %h %^[%d:%t %^] "%r" %s %b "%R" "%u" "%^" %T"%^' --date-format=%d/%b/%Y --time-format=%T

Or if your log lines are using English date formats but your server is not in an English-language locale, please ensure you use `LC_TIME`:

    # LC_TIME="en_US.UTF-8" goaccess access.log --log-format='%^= %h %^[%d:%t %^] "%r" %s %b "%R" "%u" "%^" %T"%^' --date-format=%d/%b/%Y --time-format=%T

![2024-04-05-192759_501x465_scrot](https://github.com/allinurl/goaccess/assets/5005367/86ec403f-f04f-4d7a-bea5-23ee04b868f4)

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.

**Comment by danshome** [comment]
I'm seeing the same problem...

My ~/.goaccessrc has

time-format %T
date-format %d/%b/%Y

log-format [%d/%b/%Y:%T %z] %h %^ %^ %^ %^ "%r" %s %b "%R" "%u"

My log format in Apache is...

LogFormat "%t %a %l %u %{SSL_PROTOCOL}x %{SSL_CIPHER}x \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\""

Here are a couple lines from my access log...

[06/Jan/2025:00:00:01 -0600] 192.168.0.1 - foo@bar.com TLSv1.3 TLS_AES_256_GCM_SHA384 "POST /secure/MyApp/rest/searchtemplates HTTP/2.0" 200 818 "https://my.domain.com/secure/MyApp/app/my-report/report/5336399" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36"
[06/Jan/2025:00:00:01 -0600] 192.168.0.1 - foo@bar.com TLSv1.3 TLS_AES_256_GCM_SHA384 "GET /secure/MyApp/rest/templatedrawingimage?templateId=94262 HTTP/2.0" 200 50468 "https://my.domain.com/secure/MyApp/app/my-report/report/5336399" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36"
[06/Jan/2025:00:00:01 -0600] 192.168.0.1 - foo@bar.com TLSv1.3 TLS_AES_256_GCM_SHA384 "GET /secure/MyApp/rest/templatedrawingimage?templateId=76477 HTTP/2.0" 200 161043 "https://my.domain.com/secure/MyApp/app/my-report/report/5336399" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36"
[06/Jan/2025:00:00:03 -0600] 192.168.0.2 - - TLSv1.3 TLS_AES_256_GCM_SHA384 "POST /Shibboleth.sso/SAML2/POST HTTP/2.0" 302 518 "https://login.microsoftonline.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 Edg/131.0.0.0"

When I run  goaccess *.log                      

Cleaning up resources...
==21585== GoAccess - version 1.9.3 - Jun  1 2024 00:37:37
==21585== Config file: /Users/danmclaughlin/.goaccessrc
==21585== https://goaccess.io - <hello@goaccess.io>
==21585== Released under the MIT License.
==21585==
==21585== FILE: mylog_20250106-000000_ssl_access.log
==21585== Parsed 10 lines producing the following errors:
==21585==
==21585== Token '06' doesn't match specifier '%d'
==21585== Token '06' doesn't match specifier '%d'
==21585== Token '06' doesn't match specifier '%d'
==21585== Token '06' doesn't match specifier '%d'
==21585== Token '06' doesn't match specifier '%d'
==21585== Token '06' doesn't match specifier '%d'
==21585== Token '06' doesn't match specifier '%d'
==21585== Token '06' doesn't match specifier '%d'
==21585== Token '06' doesn't match specifier '%d'
==21585== Token '06' doesn't match specifier '%d'
==21585==
==21585== Format Errors - Verify your log/date/time format

**Comment by danshome** [comment]
I also tried...

cat ~/.goaccessrc 
date-format %d/%b/%Y
time-format %T %z

# Since date + time (with timezone) is in a SINGLE token, we can parse it with [%x].
log-format [%x] %h %^ %e %K %k "%r" %s %b "%R" "%u"


 goaccess *.log   

Cleaning up resources...
==25633== GoAccess - version 1.9.3 - Jun  1 2024 00:37:37
==25633== Config file: /Users/user/.goaccessrc
==25633== https://goaccess.io - <hello@goaccess.io>
==25633== Released under the MIT License.
==25633==
==25633== FILE: mylog_20250106-000000_ssl_access.log
==25633== Parsed 10 lines producing the following errors:
==25633==
==25633== Token '06/Jan/2025:00:00:01 -0600' doesn't match specifier '%x'
==25633== Token '06/Jan/2025:00:00:01 -0600' doesn't match specifier '%x'
==25633== Token '06/Jan/2025:00:00:01 -0600' doesn't match specifier '%x'
==25633== Token '06/Jan/2025:00:00:03 -0600' doesn't match specifier '%x'
==25633== Token '06/Jan/2025:00:00:03 -0600' doesn't match specifier '%x'
==25633== Token '06/Jan/2025:00:00:03 -0600' doesn't match specifier '%x'
==25633== Token '06/Jan/2025:00:00:03 -0600' doesn't match specifier '%x'
==25633== Token '06/Jan/2025:00:00:03 -0600' doesn't match specifier '%x'
==25633== Token '06/Jan/2025:00:00:03 -0600' doesn't match specifier '%x'
==25633== Token '06/Jan/2025:00:00:03 -0600' doesn't match specifier '%x'
==25633==
==25633== Format Errors - Verify your log/date/time format

**Comment by danshome** [comment]
@allinurl 

This finally worked...

date-format %d/%b/%Y
time-format %T %z

log-format [%d:%t] %h %^ %^ %^ %^ "%r" %s %b "%R" "%u"

**Comment by allinurl** [comment]
@danshome glad that worked!
