### ISSUE TITLE
Visitors geolocation map in v.1.9.2: numbers format on the scale bar under the map

### ISSUE THREAD

**Issue by rc5hack** [allinurl/goaccess#2661]
Thank you for [implementing](https://github.com/allinurl/goaccess/issues/524#issuecomment-2050764436) visitors map, this is great news!

Have just updated to v.1.9.2. The way the numbers (on the scale bar under the map) are separated from each other by dots looks kinda strange. Is this how it should be?

![map](https://github.com/allinurl/goaccess/assets/1535521/ebe426de-3f96-4ffa-9ca2-05a0ac41ccc1)

**Comment by rc5hack** [comment]
Okay, that is font issue. Text in page sources is `58,941.4` (1st dot, 2nd comma), but it looks like 2 dots. 
![digits](https://github.com/allinurl/goaccess/assets/1535521/b737b1bf-eb2a-445b-a61a-82aee9a9953f)

**Comment by allinurl** [comment]
Nice catch on noticing the font difference! How does it look in Chrome?

I'll close this for now since it doesn't seem to be a problem with goaccess. Feel free to reopen it if necessary.

**Comment by rc5hack** [comment]
![chrome](https://github.com/allinurl/goaccess/assets/1535521/3faf09c4-e1e4-4a3e-a912-9c523c1434b7)

- google chrome 123.0.6312.124
- google chrome 124.0.6367.61

the same problem

**Comment by allinurl** [comment]
It seems like an issue with the browser or system font. You could attempt to resolve it by adjusting the browser font settings (though this might not be the solution). GoAccess doesn't directly manage the decimal separator; instead, it relies on the system's `toLocaleString` [function](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString) to handle [this](https://github.com/allinurl/goaccess/blob/master/resources/js/app.js#L224) aspect.
