### ISSUE TITLE
Question about --enable-panel

### ISSUE THREAD

**Issue by tyctor** [allinurl/goaccess#2668]
Hi

just question if i understand correctly man page, I want to generate html report with two panels `VISITORS` and `GEO_LOCATION`
i tryied command 
```
goaccess --output ../report.html ../nginx.access.log --persist --restore --config-file ../goaccess.conf --db-path ../db/ --geoip-database ../geoip/GeoLite2-City_20240412/GeoLite2-City.mmdb --ignore-status=404 --http-protocol=no --http-method=no --enable-panel=VISITORS,GEO_LOCATION --html-prefs='{"theme":"bright","layout":"vertical","showTables":false}'
```
or 
```
goaccess --output ../report.html ../nginx.access.log --persist --restore --config-file ../goaccess.conf --db-path ../db/ --geoip-database ../geoip/GeoLite2-City_20240412/GeoLite2-City.mmdb --ignore-status=404 --http-protocol=no --http-method=no --enable-panel=VISITORS --enable-panel=GEO_LOCATION --html-prefs='{"theme":"bright","layout":"vertical","showTables":false}'
```

but there are all panels in generated report.html, is option `--enable-panel` working for html report?

> --enable-panel=<PANEL>
Enable parsing/displaying the given panel. List of panels:
VISITORS
REQUESTS
REQUESTS_STATIC
NOT_FOUND
HOSTS
OS
BROWSERS
VISIT_TIMES
VIRTUAL_HOSTS
REFERRERS
REFERRING_SITES
KEYPHRASES
STATUS_CODES
REMOTE_USER
CACHE_STATUS
GEO_LOCATION
MIME_TYPE
TLS_TYPE

**Comment by allinurl** [comment]
You might find the `--ignore-panel` option useful since panels are enabled by default. For example, `--ignore-panel=REQUESTS` or `--ignore-panel=REQUESTS_STATIC`. Alternatively, if you only need to visually hide them, you can toggle them on/off directly from the html report by clicking on the circle next to the panel name in the left-hand side navigation bar.

**Comment by tyctor** [comment]
thanks, `--ignore-panel` is working, i missed that

toggle also working, is it possible to toggle panels off in `--html-prefs` ?

**Comment by allinurl** [comment]
You can hide all of them, e.g.,

    {"autoHideTables":true,"layout":"horizontal","perPage":7,"theme":"bright","hiddenPanels":["visitors","requests","static_requests","not_found","hosts","os","browsers","visit_time","vhosts","referrers","referring_sites","keyphrases","status_codes","geolocation","asn","mime_type","tls_type"],"geolocation":{"plot":{"chartType":"wmap"}}}

Closing this. Feel free to reopen it as needed.

**Comment by tyctor** [comment]
Yes, I have similar `hiddenPanels` value, but `STATIC_REQUESTS` and `TIME_DISTRIBUTION` are not hidden

![Capture 2024-04-20 at 11 16 07](https://github.com/allinurl/goaccess/assets/44854182/71212bd6-4c47-4680-9cfc-1dcaaa32d097)
