### ISSUE TITLE
Only 366 Items are returned in JSON and CSV Outputs

### ISSUE THREAD

**Issue by packet-rat** [allinurl/goaccess#267]
## Only 366 Items are returned in JSON and CSV Outputs

***Great Tool! - Thanks for sharing!***

### Use Case:  

Need to extract unique Hosts from 18 Months of Apache Logs with total count of sightings for each IP Address (~18 Gigabytes of raw log data).  

#### Issue

On the basis of documentation reviews I selected ***goaccess*** as my first choice.  Up and running against test data in 15 minutes.  Config file optimized in another 15 minutes.  

Good Job on Tool and Docs!

Unfortunately, it appears I misinterpreted the Documentation regarding Item Limits in Output files.

This may just be Semantics.  Documentation states:

>  NOTES 
> For now, each active window has a total of 366 items. Eventually this will be customizable. ***All these 
> items*** are available by default in the CSV and JSON exports, and as an expandable panel in the 
> HTML report (upper-right corner).

***Is Intent?:***

>  NOTES 
> For now, each active window has a total of 366 items. Eventually this will be customizable. 
> ***These 366 items*** are all available by default in the CSV and JSON exports, and 
> as an expandable panel in the HTML report (upper-right corner).

#### Question:

Is there a way to extend this Item Limit for Hosts (for data extraction only)?

**Comment by allinurl** [comment]
Thanks for clarifying those notes. I've updated the website. Regarding the ability to extend this limit, there's no option right now, it's on the to-do list. However, you could modify line [1542](https://github.com/allinurl/goaccess/blob/74f3dd69e5e2e5df80e1505deda5f75122a6a90f/src/gdashboard.c#L1542) (haven't really tested it, but it should do it):

    h->holder_size = size > MAX_CHOICES ? MAX_CHOICES : size;

to

    h->holder_size = !conf.output_html && size > MAX_CHOICES ? MAX_CHOICES : size;

Note that if you are outputting HTML, browsers might not be able to handle a large amount of data in the report.

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
