### ISSUE TITLE
'Error opening terminal: xterm' using docker image

### ISSUE THREAD

**Issue by valankar** [allinurl/goaccess#2670]
```
valankar@debian /m/s/c/logs> ls -l
total 212
-rw------- 1 valankar valankar 213622 Apr 18 11:22 access.log
valankar@debian /m/s/c/logs> echo $LANG
en_US.UTF-8
valankar@debian /m/s/c/logs> docker run --rm -it -v .:/mnt/logs -e LANG=$LANG allinurl/goaccess /mnt/logs/access.log
Error opening terminal: xterm.
```

Any idea how to fix this?

**Comment by allinurl** [comment]
If you're working with [**Docker**](https://github.com/allinurl/goaccess?tab=readme-ov-file#docker) and want to generate an HTML report, you'll need to use the `-o report.html` option. Otherwise, you'll have to access the container directly. Let me know if that helps.

**Comment by valankar** [comment]
Thanks. I was able to do a build in container image and the binary works for the text console.
