### ISSUE TITLE
Incremental processing of piped data

### ISSUE THREAD

**Issue by tyctor** [allinurl/goaccess#2671]
I use filtering log via `grep` and piping data to `goaccess` because of small memory on server  (as i wrote here #2665)

command looks like this:
```
grep -E -f - radiopunctum.cz.access.log | goaccess --config-file /etc/goaccess.conf --output report.html --persist --restore --db-path db-data
```

it works well for first run, when i run it second time (after 24hours) output report is not updated with new data

i found in man this note:

>  Important
Since piped data works based on a timestamp and there's no way to determine the inode nor the last line parsed, some issues could arise. For instance, a piped log could have multiple consecutive lines with the same timestamp (even at the second level), so it's likely to end up with duplicates entries. However, as a best practice and a reasonable assumption is that in most cases, for incremental log processing, users will parse data directly with goaccess instead of piping it through.

is that mean that i cannot use my command above for updating data? 
how would you recommend modifying the command above to make the update work?
will saving `grep` output to file solve this?

**Comment by tyctor** [comment]
it seems that i looked to wrong numbers, now it is updating, so everything is OK :+1:

**Comment by allinurl** [comment]
It's great to hear that you've resolved it. The piping shouldn't hinder data updates. The note you referred to is mainly for people to understand that piping data and restoring from disk could potentially introduce duplicate records with the exact timestamp. Let me know if you have any other questions.

**Comment by tyctor** [comment]
hmm, command is working but something is weird and i don't undersand what
maybe you can help to explain me this
setup is: above shell command is run by python script, it use `Popen` from python `subprocess` module in `django` management command, it periodically runs command in 15min interval in `while True` loop
and what i am observing i cant explain:

- when i run django command manually from shell, report is updating

- when i run django command and let it update report in that `while True` loop, report data are not updating, only date of report is updated

**Comment by tyctor** [comment]
OMG, solved ... I forgot to put dash as last symbol into command line
and it seems that when i run it manually dash in not needed

anyway, it is working now like a charm
