### ISSUE TITLE
Trying to figure out " Token for '%s' specifier is NULL."

### ISSUE THREAD

**Issue by avonnieda** [allinurl/goaccess#2673]
Hi, looking for advice on this error -  Token for '%s' specifier is NULL. 
   Thank you for any insight you can provide, very excited to get this working!

**goaccess config**
time-format %H:%M:%S
date-format %d/%b/%Y
log-format %h %{%s}t %l %u %t \"%r\" %>s %b %T/%D

**Apache config**
   LogFormat "%h %{%s}t %l %u %t \"%r\" %>s %b %T/%D" response_times
   CustomLog logs/ssl_response_log response_times

**Sample log entries**
192.168.1.5 1713687672 - - [21/Apr/2024:03:21:12 -0500] "GET /foo/bar/bat/service?p_1=036&p_2=ALL&p_3=ALL&p_4=ALL HTTP/1.1" 200 10286 22/22923423
192.168.1.5 1713687696 - - [21/Apr/2024:03:21:36 -0500] "GET /foo/bar/bat/service?p_1=039&p_2=ALL&p_3=ALL&p_4=ALL HTTP/1.1" 200 97772 18/18612738

**Full error**
==2083864== Parsed 10 lines producing the following errors:
==2083864==
==2083864== Token for '%s' specifier is NULL.
==2083864== Token for '%s' specifier is NULL.
==2083864== Token for '%s' specifier is NULL.
==2083864== Token for '%s' specifier is NULL.
==2083864== Token for '%s' specifier is NULL.
==2083864== Token for '%s' specifier is NULL.
==2083864== Token for '%s' specifier is NULL.
==2083864== Token for '%s' specifier is NULL.
==2083864== Token for '%s' specifier is NULL.
==2083864== Token for '%s' specifier is NULL.
==2083864==
==2083864== Format Errors - Verify your log/date/time format

**Comment by pfei5** [comment]
@avonnieda care to share your solution?

**Comment by avonnieda** [comment]
My solution to this problem was to switch from date format such as MON-DD-YYYY HH24:MI:SS to epoch time.
