### ISSUE TITLE
Nginx log format not working in Goaccess

### ISSUE THREAD

**Issue by init-sdrb** [allinurl/goaccess#2676]
This is my nginx access.log format:
**[28/Apr/2024:10:19:40 +0545] "125043" "source_ip" "GET /api/someApi/hello-limit-forr/load-mode HTTP/1.1" 200 145 "https://mysite.com.org/sub/member/search/go-search/111555" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36" "IPADDR" "Dest_ip:7671" "mysite.com.org" "0.002" "0.001"**

I've tried a lot of options but still I am getting  **"Format Errors - Verify your log/date/time format"**

Can somebody help me on this?

_Originally posted by @init-sdrb in https://github.com/allinurl/goaccess/issues/1066#issuecomment-2088786610_

**Comment by allinurl** [comment]
This should do it, just make your the IP with `%h` is the one you are trying to match.

    # goaccess access.log --log-format='[%d:%t %^] %^ "%h" "%r" %s %b "%R" "%u" %^ %^ "%v" "%T" %^' --date-format=%d/%b/%Y --time-format=%T

**Comment by init-sdrb** [comment]
Thank you so much @allinurl it worked like a charm. 
Also, where can i find the description or purpose of different types of log-format parameters so that I can use it for other types of logs as well.

**Comment by init-sdrb** [comment]
Thanks @allinurl , it worked like a charm. 
Also, is it possible to create our own custom dashboard or combine two different sections (e.g. Total number of unique IPs visited a particular site or api). Sorry if this question shouldn't be posted in this thread but just wanted to clear my thoughts on the goaccess customization.
