### ISSUE TITLE
Problem with the Wold Map

### ISSUE THREAD

**Issue by UnveilTech** [allinurl/goaccess#2684]
hello,
Goaccess 1.9.2
here are 2 errors with the World Map, tried with Firefox and Chrome, both latest builds.

downloadable font: Glyph bbox was incorrect (glyph ids 19 32 33 34 37 38 42 44 45 46 52 53 78 79 81 95 96 101 104) (font-family: "fa" style:normal weight:400 stretch:100 src index:0) source: data:application/font-woff;charset=utf-8;base64,d09GRgABAAAAAFxQAAsAAAAAXAQAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAABPUy8yAAABCAAAAGAAAABg … SWNvTW9vbi4ARgBvAG4AdAAgAGcAZQBuAGUAcgBhAHQAZQBkACAAYgB5ACAASQBjAG8ATQBvAG8AbgAuAAAAAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==

Uncaught TypeError: item.bytes is undefined
    mapData http://192.168.4.3:81/goaccess.html:1
    mapData http://192.168.4.3:81/goaccess.html:1
    mapData http://192.168.4.3:81/goaccess.html:1
    updateMap http://192.168.4.3:81/goaccess.html:1
    chart http://192.168.4.3:81/goaccess.html:1
    each http://192.168.4.3:81/goaccess.html:1
    chart http://192.168.4.3:81/goaccess.html:1
    call http://192.168.4.3:81/goaccess.html:1
    renderChart http://192.168.4.3:81/goaccess.html:1
    addChart http://192.168.4.3:81/goaccess.html:1
    renderCharts http://192.168.4.3:81/goaccess.html:1
    initialize http://192.168.4.3:81/goaccess.html:1
    initialize http://192.168.4.3:81/goaccess.html:1
    onload http://192.168.4.3:81/goaccess.html:1
    EventHandlerNonNull* http://192.168.4.3:81/goaccess.html:1
    <anonymous> http://192.168.4.3:81/goaccess.html:1

any ideas ?

have a sexy day

**Comment by UnveilTech** [comment]
additional info:
GoAccess - 1.9.2.
For more details visit: https://goaccess.io/
Copyright (C) 2009-2024 by Gerardo Orellana

Build configure arguments:
  --enable-utf8
  --enable-geoip=mmdb

**Comment by UnveilTech** [comment]
more info:
many IPs are private in the log, some are public, could it be the issue ?

**Comment by UnveilTech** [comment]
we've modified the format to take care the Dst IP.

here is with the Bar view:
<img width="871" alt="bar" src="https://github.com/allinurl/goaccess/assets/14853003/0c16f916-e987-466f-9d50-0ecceddd8915">

here is with the Map view:
<img width="870" alt="map" src="https://github.com/allinurl/goaccess/assets/14853003/04bd4c05-36a4-4fe3-b420-3c800b1961be">

and still the same error on the browser.

**Comment by allinurl** [comment]
I meant if you could send it my way to my email or attach it here so I can try to replicate the issue. Also, please post the log-format, date-format and time-format and any other config settings you are passing/using.

**Comment by UnveilTech** [comment]
data sent to your email...

**Comment by UnveilTech** [comment]
Gerardo,
please close the case, we found the issue.
it was due to the fact we were not using the flag '%b' in the format.
it seems the Wold Map does not work fine if no "TX. Amount".

anyway thanks for your support, appreciated.
have a sexy day.

**Comment by UnveilTech** [comment]
we now have the Map:
![image](https://github.com/allinurl/goaccess/assets/14853003/6bde9b0d-9b3e-426e-83d1-2fba0637533b)
