### ISSUE TITLE
The "Unique Visitors Per Day" pane always showing a single dot

### ISSUE THREAD

**Issue by Zabrane** [allinurl/goaccess#2686]
Hi @allinurl 

I'm struggling with the first pane always showing  a single dot (see below image).

I'm running `GoAccess` on Ubuntu 22.04 LTS:
```bash
# goaccess --version
GoAccess - 1.9.2.
For more details visit: https://goaccess.io/
Copyright (C) 2009-2024 by Gerardo Orellana

Build configure arguments:
  --enable-utf8
  --enable-geoip=mmdb
```

`GoAccess` log format is:
```txt
--log-format='%V %h %^[%d:%t %^] \"%r\" %s %b \"%R\" \"%u\"' --date-format="%d/%b/%Y" --time-format="%T"
```

`Apache` log format is:
```apache
LogFormat "%V %{X-Forwarded-For}i %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" proxy
```
![uniq_visitor](https://github.com/allinurl/goaccess/assets/532544/0f404d3b-8280-4bf0-984d-db2787b0c0fa)

Here is a sample from Apache log:
```apache
www.foxxyme.com 83.99.151.68 - - [30/May/2024:22:32:00 +0200] "GET /bic-bic-cristal-re-new-recharges-stylo-bille-pointe-moyenne-1-0-mm-noir-etui-carton-3_SKU450864.html HTTP/1.1" 200 19813 "-" "Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; GeedoProductSearch; +http://www.geedo.com/product-search.html) Chrome/79.0.3945.88 Safari/537.36"
www.foxxyme.com 66.249.76.70 - - [30/May/2024:22:32:01 +0200] "GET /lipton-lipton-cannette-ice-tea-peche-33-cl_SKU496032.html HTTP/1.1" 200 21302 "-" "Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.6422.141 Mobile Safari/537.36 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"
www.foxxyme.com 69.171.249.6 - - [30/May/2024:22:32:01 +0200] "GET /papeterie/papier/papiers-speciaux/cartes-visite_C102_102010501.html?SearchParameter=%26%40QueryTerm%3D*%26Attr_NbFeuilles%3D15%26ContextCategoryUUID%3DQkIKBQEHg2gAAAFyljMJwFu1%26OnlineFlag%3D1%26%40GroupSize.ManufacturerName%3D0%26%40Rk.Attr_Produit_Vendable_O-N%3Dfalse%255E0%26%40Rk.InStock%3Dtrue%255E100 HTTP/1.1" 200 23708 "-" "facebookexternalhit/1.1 (+http://www.facebook.com/externalhit_uatext.php)"
www.foxxyme.com 193.31.125.248 - - [30/May/2024:22:32:01 +0200] "GET /uni-ball-uni-ball-feutre-technique-uni-pin-serie-1-pointe-biseautee-chisel-coloris-noir_SKU451157.html HTTP/1.1" 200 23490 "-" "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.2 (KHTML, like Gecko) Chrome/22.0.1216.0 Safari/537.2"
```

What's wrong?
Help appreciated. Thanks in advance.

**Comment by Zabrane** [comment]
@allinurl I also noticed two things in my `Unique Visitors Per Day`:

1. I've less entries in the `Panel Options` menu than your [demo](https://rt.goaccess.io/?20240428171914):
![Screenshot 2024-05-30 at 22 47 52](https://github.com/allinurl/goaccess/assets/532544/6c49b63b-66ab-438f-800d-8cdb4626d5f8)

![Screenshot 2024-05-30 at 22 48 53](https://github.com/allinurl/goaccess/assets/532544/79b4215d-948e-4ede-b94b-de9403217219)

2. Only the data is shown without the time (HH:MM:SS)
![uniq_visitor-2](https://github.com/allinurl/goaccess/assets/532544/110f33fb-2369-4509-bab2-7da16df01add)

![Screenshot_2024-05-30_at_22_53_01](https://github.com/allinurl/goaccess/assets/532544/a670d581-d6f3-40c9-84a2-f8d2868f83ef)

**Comment by allinurl** [comment]
The one dot in the graph is that you only have one day's worth of data. If you want to add more specificity, please pass `--date-spec=min`. e.g., 

    # goaccess access.log --log-format=COMBINED -o report.html --date-spec=min

**Comment by Zabrane** [comment]
@allinurl wow ... it worked, thanks.
 
But how about the second remark. Why do I've less  entries in the `Panel Options` menu?

![Screenshot_2024-05-30_at_23_35_07](https://github.com/allinurl/goaccess/assets/532544/387df9db-ce47-412b-98d0-e98778a02852)

**Comment by allinurl** [comment]
There's no  seconds specificity. I'm not sure if it's worth adding; it will change quite quickly. As for columns, are you logging the time served? What server are you running?

**Comment by Zabrane** [comment]
> goaccess access.log --log-format=COMBINED -o report.html --date-spec=min

Why `COMBINED` and not `VCOMBINED`?

**Comment by Zabrane** [comment]
> [...] As for columns, are you logging the time served? What server are you running?

Not sure if I fully understand the question, but yes `Apache` is logging the time  as you can see.
```txt
www.foxxyme.com 83.99.151.68 - - [30/May/2024:22:32:00 +0200] "GET /bic-bic-cristal-re-new-recharges-stylo-bille-pointe-moyenne-1-0-mm-noir-etui-carton-3_SKU450864.html HTTP/1.1" 200 19813 "-" "Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; GeedoProductSearch; +http://www.geedo.com/product-search.html) Chrome/79.0.3945.88 Safari/537.36"
```

**Comment by allinurl** [comment]
Please post a few lines from your access log so I can take a look

**Comment by Zabrane** [comment]
@allinurl  Sure. I did post them on my first post above. Here you are:
```apache
www.foxxyme.com 83.99.151.68 - - [30/May/2024:22:32:00 +0200] "GET /bic-bic-cristal-re-new-recharges-stylo-bille-pointe-moyenne-1-0-mm-noir-etui-carton-3_SKU450864.html HTTP/1.1" 200 19813 "-" "Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; GeedoProductSearch; +http://www.geedo.com/product-search.html) Chrome/79.0.3945.88 Safari/537.36"
www.foxxyme.com 66.249.76.70 - - [30/May/2024:22:32:01 +0200] "GET /lipton-lipton-cannette-ice-tea-peche-33-cl_SKU496032.html HTTP/1.1" 200 21302 "-" "Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.6422.141 Mobile Safari/537.36 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"
www.foxxyme.com 69.171.249.6 - - [30/May/2024:22:32:01 +0200] "GET /papeterie/papier/papiers-speciaux/cartes-visite_C102_102010501.html?SearchParameter=%26%40QueryTerm%3D*%26Attr_NbFeuilles%3D15%26ContextCategoryUUID%3DQkIKBQEHg2gAAAFyljMJwFu1%26OnlineFlag%3D1%26%40GroupSize.ManufacturerName%3D0%26%40Rk.Attr_Produit_Vendable_O-N%3Dfalse%255E0%26%40Rk.InStock%3Dtrue%255E100 HTTP/1.1" 200 23708 "-" "facebookexternalhit/1.1 (+http://www.facebook.com/externalhit_uatext.php)"
www.foxxyme.com 193.31.125.248 - - [30/May/2024:22:32:01 +0200] "GET /uni-ball-uni-ball-feutre-technique-uni-pin-serie-1-pointe-biseautee-chisel-coloris-noir_SKU451157.html HTTP/1.1" 200 23490 "-" "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.2 (KHTML, like Gecko) Chrome/22.0.1216.0 Safari/537.2"
```

**Comment by allinurl** [comment]
It looks like it doesn't align with the `**%T/%D**`. You might want to restart apache. Once you've done that, you can proceed with:

    # goaccess access.log --log-format='%v %h %^[%d:%t %^] "%r" %s %b "%R" "%u" %^/%D' --date-format=%d/%b/%Y --time-format=%T

**Comment by Zabrane** [comment]
@allinurl  one more question if you don't mind. Why I can't see these two panels with my current config even If i'm specifying them in `--enable-panel` :
```text
        --enable-panel=MIME_TYPE \
        --enable-panel=VIRTUAL_HOSTS
```

**Comment by allinurl** [comment]
Assuming you've got the right format, it should work. Please post your config file and the full command you are using.

**Comment by Zabrane** [comment]
@allinurl I don't use a config file (`--no-global-config`). This is my full command line:

```bash
$  goaccess --version
GoAccess - 1.9.2.
For more details visit: https://goaccess.io/
Copyright (C) 2009-2024 by Gerardo Orellana

Build configure arguments:
  --enable-utf8
  --enable-geoip=mmdb
  
$ goaccess -a -q \
        --no-global-config \
        --log-format='%v %h %^[%d:%t %^] "%r" %s %b "%R" "%u" %^/%D' \
        --date-format="%d/%b/%Y" \
        --time-format="%T" \
        --enable-panel=REFERRERS \
        --enable-panel=KEYPHRASES \
        --enable-panel=MIME_TYPE \
        --enable-panel=VIRTUAL_HOSTS \
        --date-spec=min \
        --output=/tmp/goaccess.html \
        /var/lib/apache2.4/log/access.html
```

1. Am i missing something here?
2. Is a config file mandatory?

**Comment by allinurl** [comment]
The log you posted is missing MIME_TYPEs, but everything else should work. Run goaccess as shown below and see the results:

```
# goaccess /var/lib/apache2.4/log/access.html -a --log-format='%v %h %^[%d:%t %^] "%r" %s %b "%R" "%u" %^/%D' --date-format=%d/%b/%Y --time-format=%T -o /tmp/goaccess.html
```

Also, make sure the panels are enabled in the HTML navigation bar on the left. Click the little circle next to each panel name to toggle them on/off.

**Comment by Zabrane** [comment]
Hi @allinurl
Do you need anything else?

**Comment by Zabrane** [comment]
@allinurl  

I've tried `GoAccess - 1.9.2` on macOS but i can't see the MIME_TYPE panels.

![Screenshot 2024-06-01 at 12 20 55](https://github.com/allinurl/goaccess/assets/532544/d5a7da9f-b31f-48ce-81a6-b41044eed50c)


> The log you posted is missing MIME_TYPEs, but everything else should work. Run goaccess as shown below and see the results:

How can I enable MIME_TYPE in my Apache logs?
Help appreciated.

**Comment by Zabrane** [comment]
@allinurl  found it:
```
 %M The MIME-type of the requested resource. (In Apache LogFormat: %{Content-Type}o) 
 ```
 
 It's working. Thanks a lot for these GREAT software and your support.

**Comment by allinurl** [comment]
Great to hear it worked and you found it helpful! If you have any more questions, just let me know.
