### ISSUE TITLE
Goaccess 1.9.2 and 1.9.3 (Those where the ones tested) don't write some panels information that work on CLI

### ISSUE THREAD

**Issue by aalmenar** [allinurl/goaccess#2688]
Hi, 

At the moment i have detected that procesing the logs on CLI i get somewhat correct information:

```
 16 - Geo Location                                                                                                                                                    Total: 5/5

 Hits     h% Vis.     v% Avg. T.S. Cum. T.S. Max. T.S. Data
 ---- ------ ---- ------ --------- --------- --------- ----
 1831 97.03%    8 26.67%   1.76 ms   3.22  s  63.64 ms EU Europe
   56  2.97%   22 73.33%   1.59 ms  88.88 ms   7.27 ms NA North America

17 - ASN                                                                                                                                                           Total: 14/14

 Hits     h% Vis.     v% Avg. T.S. Cum. T.S. Max. T.S. Data
 ---- ------ ---- ------ --------- --------- --------- ----
 1088 57.66%    1  3.33%   1.21 ms   1.32  s   3.68 ms XXXX: ASNX
  474 25.12%    3 10.00%   2.50 ms   1.18  s  30.07 ms YYYY: ASNY
  241 12.77%    1  3.33%   1.45 ms 348.85 ms   4.10 ms 198385: AlpineDC SA
   36  1.91%   15 50.00%   1.20 ms  43.08 ms   7.27 ms 06939: HURRICANE
   19  1.01%    1  3.33%   8.48 ms 161.13 ms  20.30 ms 136787: TEFINCOM S.A.
   12  0.64%    1  3.33%   1.30 ms  15.60 ms   1.49 ms 31898: ORACLE-BMC-31898
    7  0.37%    2  6.67%  28.72 ms 201.01 ms  63.64 ms 08717: A1 Bulgaria EAD

   19 - Encryption settings                                                                                                                                             Total: 3/3

 Hits     h% Vis.     v% Avg. T.S. Cum. T.S. Max. T.S. Data
 ---- ------ ---- ------ --------- --------- --------- ----
 1885 99.89%   29 96.67%   1.75 ms   3.30  s  63.64 ms TLSv1.3
    1  0.05%    1  3.33%   1.26 ms   1.26 ms   1.26 ms TLSv1.2
```

ASN information is correct, Encryption Settings are also correct, but geolocation data only shows continent.

Im executing it passing the three databases (Downloaded today) and the information is available there:

--geoip-database=/var/lib/GeoIP/GeoLite2-City.mmdb --geoip-database=/var/lib/GeoIP/GeoLite2-Country.mmdb --geoip-database=/var/lib/GeoIP/GeoLite2-ASN.mmdb

Also if i add to the command: -o stats/current_report.html to generate a static file with the data, ASN, Encryption and Geolocation set empty panels without the information available on CLI.

**Comment by allinurl** [comment]
Did you press enter on the terminal UI to expand the geolocation panel? Also, can you post a screenshot of what you’re seeing on the HTML report?

**Comment by aalmenar** [comment]
@allinurl Basically this is what i get on the html generated:

![Screenshot](https://github.com/allinurl/goaccess/assets/161029/a8eb5248-456e-49c9-8829-b7f1ea7aac70)

**Comment by aalmenar** [comment]
Apparently after reviewing, somebody here escaped quotes on the log format thats why it stopped working. Im sorry for the inconvenience.
