### ISSUE TITLE
Trying to parse custom nginx log file, logging tls versions

### ISSUE THREAD

**Issue by stoutZero** [allinurl/goaccess#2691]
Nginx Log format:
```
log_format tls_versions '[$time_local] $remote_addr '
                        '$ssl_protocol/$ssl_cipher '
                        '$status $body_bytes_sent '
                        '"$http_referer" "$http_user_agent"';
```

Redacted Example:
```
[10/Jul/2024:21:25:43 +0700] <REDACTED_HOST> TLSv1.3/<REDACTED_TLS_CIPHER> 302 390 "-" "<REDACTED_USER_AGENT>"
```

Tried putting these lines into `~/.goaccessrc`:
```
log-format TLS_VERSIONS '[%d:%t %z] %h %K/%k %s %b "%R" "%u"'
date-format %d/%b/%Y
time-format %H:%M:%S
```

Got these errors instead:
```
==4210== Parsed 10 lines producing the following errors:
==4210==
==4210== Token '' doesn't match specifier '%d'
```

Tried using this command:
`goaccess --log-format='[%d] %h %K/%k %s %b "%R" "%u"' --datetime-format='%d/%b/%Y:%H:%M:%S +%z' --date-spec=min --tz=Asia/Jakarta access.log`

Got this error:
`==4362== Token '10/Jul/2024:21:25:43 +0700' doesn't match specifier '%d'`

It is very difficult to use goaccess to parse a custom nginx log format, which is basically Combined / NCSA format....

**Comment by allinurl** [comment]
You were nearly there. However, please keep in mind that GoAccess needs a request field such as `%r` or `%U`. If you can include that in your log, the following should work (I temporarily substituted `%R` with `%r`):

    # goaccess access.log --log-format='[%x] %h %K/%k %s %b "%r" "%u"' --datetime-format='%d/%b/%Y:%H:%M:%S %z' --tz=America/New_York --date-spec=min

**Comment by stoutZero** [comment]
> You were nearly there. However, please keep in mind that GoAccess needs a request field such as `%r` or `%U`. If you can include that in your log, the following should work (I temporarily substituted `%R` with `%r`):
> 
> ```
> # goaccess access.log --log-format='[%x] %h %K/%k %s %b "%r" "%u"' --datetime-format='%d/%b/%Y:%H:%M:%S %z' --tz=America/New_York --date-spec=min
> ```

This works flawlessly, the ui came up. But there is no way to filter by TLS version, the TLS version is not even shown.
Thanks for your help anyway. Cheers.

**Comment by stoutZero** [comment]
Again, thanks for the help. I'll close this "issue" for you.

**Comment by allinurl** [comment]
Glad that helped. The TLS should show up at the bottom, e.g.,

![2024-07-12-212632_514x116_scrot](https://github.com/user-attachments/assets/0321cb26-b189-4945-aeb3-a8229338abc8)
