### ISSUE TITLE
Unique visitor count too high, parse problem?

### ISSUE THREAD

**Issue by pasztorl** [allinurl/goaccess#2692]
Hi,

I'm using the latest build from goaccess and haproxy.

Haproxy log settings:
```
http-request capture req.hdr(Referer) len 500
http-request set-var(txn.my_var) req.fhdr(User-Agent)
log-format "%si:%sp %ci %t \"%r\" %ST %B %{+Q}[capture.req.hdr(0)] %{+Q}[var(txn.my_var)] %Tr"
```

My accesslog example:
`Jul 20 02:49:46 localhost haproxy[4531]: x.x.x.x:5040 y.y.y.y 20/Jul/2024:02:49:46.785 "GET https://a.b.c/news/by-random?timeRange=3&limit=8 HTTP/2.0" 200 4679 "https://d.e/" "Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Mobile Safari/537.36" 2`

And here is the goaccess cmdline:

`zcat /var/log/haproxy.log-* | ./goaccess /var/log/haproxy.log --log-format='%^ %^ %^ %^ %^ %^ %h %d:%t.%^ "%r" %s %b "%R" "%u" %T' --date-format=%d/%b/%Y --time-format='%H:%M:%S' -o /a/b/c/accesslog.html --real-time-html --port 7891 --ws-url=wss://a.b.c:7890`

We also using plausible, and plausible reports 10k unique visitor while goaccess reports 30k. How goaccess actually count unique visitor? Maybe I use the wrong format for time?

**Comment by allinurl** [comment]
This format should do the job:

    # goaccess access.log --log-format='%^]: %h:%^ %^ %d:%t.%^ "%r" %s %b "%R" "%u" %T' --date-format=%d/%b/%Y --time-format=%T

For more information on how goaccess manages data and its distinctions from other statistical tools, please refer to [this post](https://github.com/allinurl/goaccess/issues/964#issuecomment-350607068), #789, and also [this one](https://github.com/allinurl/goaccess/issues/2343#issuecomment-1171382627). 

Adding to those posts, now with AI-powered detection and privacy blockers becoming more prevalent, even counting visitors through JavaScript is proving to be increasingly challenging. So, I still believe that accuracy relies on the logs, even though we can't always tell if it's a bot or a human for sure.

Let me know if this clarifies things for you.

**Comment by pasztorl** [comment]
thank you very much!
