### ISSUE TITLE
Web socket configuration for real time html report

### ISSUE THREAD

**Issue by notakoder** [allinurl/goaccess#2695]
Goacess is installed on my remote server and I am accessing the goaccess html report from my computer using the server's ip address (xxx.xx.xx.xx). It works! However, the dot on the gear icon on the report isn't green and real time update isn't working. I guess it is because of the web socket configuration. Below is my command.

```
sudo goaccess /var/log/apache2/access-website.com.log --log-format=COMMON --persist --real-time-html -o /var/www/goaccess/index.html --ws-url=http://xxx.xx.xx.xx/goaccess:7890
```

The man says.

> If GoAccess is running on a remote server, the host of the remote server should be specified here. Also, make sure it is a valid host and NOT an http address. 

This is a little confusing because <[scheme://]url[:port]> in these cases is an http address. What is the right address format in my case? Will adding the host name to the server address work?

**Comment by allinurl** [comment]
As you seem to be accessing through HTTP, you can just:

    ws://xxx.xx.xx.xx

or

    sudo goaccess /var/log/apache2/access-website.com.log --log-format=COMMON --persist --real-time-html -o /var/www/goaccess/index.html --ws-url=xxx.xx.xx.xx

By the way, when accessing the report in your browser via an IP address, it should connect automatically without requiring you to specify `--ws-url`.

You can always attempt a telnet connection to verify if it's responding, for instance,

    telnet xxx.xx.xx.xx 7890

**Comment by notakoder** [comment]
The issue is with the port, and I am facing issues opening port 7890.

`$ sudo iptables -A INPUT -p tcp --dport 7890 -j ACCEPT`

```
$ sudo iptables-save
# Generated by iptables-save v1.8.9 (nf_tables) on Tue Jul 23 18:15:42 2024
*filter
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
-A INPUT -p tcp -m tcp --dport 7890 -j ACCEPT
COMMIT
# Completed on Tue Jul 23 18:15:42 2024
```

```
$ sudo iptables -L
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:7890

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         
```

However, 

```
$ nmap localhost -p 7890
Starting Nmap 7.93 ( https://nmap.org ) at 2024-07-23 18:16 UTC
Nmap scan report for localhost (127.0.0.1)
Host is up (0.000096s latency).
Other addresses for localhost (not scanned): ::1

PORT     STATE  SERVICE
7890/tcp closed unknown

Nmap done: 1 IP address (1 host up) scanned in 0.05 seconds
```

I even tried opening the port with nmap

```
$ sudo nmap -open -p 7890 localhost
Starting Nmap 7.93 ( https://nmap.org ) at 2024-07-23 18:17 UTC
Nmap done: 1 IP address (1 host up) scanned in 0.12 seconds
```

Yet, the output for `nmap localhost -p 7890` is still the same as earlier.

**Comment by notakoder** [comment]
Goaccess is installed on a remote server. It does have a static IP address. The code mentioned in my earlier post is done on that machine, using ssh.

Telnet connections from my local system:

```
telnet xxx.xx.xx.xx 7890
Trying xxx.xx.xx.xx...
telnet: Unable to connect to remote host: Connection timed out
```

Telnet connection from the server itself:

```
$ telnet localhost 7890
Trying ::1...
Connection failed: Connection refused
Trying 127.0.0.1...
telnet: Unable to connect to remote host: Connection refused
```

**Comment by notakoder** [comment]
Alright, I managed to open the port. But it doesn't have a service associated with this. 

```
nmap localhost -p 7890
Starting Nmap 7.93 ( https://nmap.org ) at 2024-07-25 09:37 UTC
Nmap scan report for localhost (127.0.0.1)
Host is up (0.00013s latency).
Other addresses for localhost (not scanned): ::1

PORT     STATE SERVICE
7890/tcp open  unknown

Nmap done: 1 IP address (1 host up) scanned in 0.04 seconds
```

Should there be any particular service listening to port 7890 for goaccess to work properly?

**Comment by allinurl** [comment]
You need to ensure that GoAccess is running in the background with the `--real-time-html` option enabled before attempting to connect via telnet on port 7890.

**Comment by notakoder** [comment]
Alright, I am facing some issues establishing a telnet connection on port 7890 from my local machine to the remote machine, even with a service listening to the port. I have tried with two services listening to port 7890: nc (netcat) and goaccess.

This is less of Goaccess problem and more of my distro issue I guess. I am closing this issue for now and will reopen it after I fix the telnet issue.

**Comment by allinurl** [comment]
Sounds good, feel free to reopen it if needed.
