### ISSUE TITLE
How to actually persist?

### ISSUE THREAD

**Issue by notakoder** [allinurl/goaccess#2697]
I have added the `--persist` to my goaccess command. However, if I stop goaccess and run it again (say with new options), I see the report only for the current day (what's available on the log).

Is there any database settings I need to perform for persistent data reporting? Or is my understanding of the --persist option totally wrong?

**Comment by 0bi-w6n-K3nobi** [comment]
Hi @notakoder 

Yeah... off course, do you need more option.
At manual page at [here](https://goaccess.io/man#configuration) at `Persistence Storage Options` can read about this.
So, at first running only `--persist` option is ok. But, for next do need specific `--restore`.
And if you need save data processing at specific location, a place different from `LOGs` location, use `--db-path`.

I hope be clean.

**Comment by notakoder** [comment]
`--restore` does the job. Sorry I missed that in the documentation. Thank you for pointing it out.
