### ISSUE TITLE
Total request more than the actual request

### ISSUE THREAD

**Issue by kys1230** [allinurl/goaccess#270]
nginx log format conf
log_format  main  '$server_name $remote_addr - $remote_user [$time_local] "$request" '
                  '$status $body_bytes_sent "$http_referer" '
                  '"$http_user_agent" "$http_cookie" "$http_x_forwarded_for" "$upstream_addr" "$upstream_status" "$request_time" "$upstream_response_time" '
                  '"$http_version" "$http_deviceId" "$http_deviceType"';
nginx log 

    www.xxx.com 111.111.111.111 - - [15/Jul/2015:00:00:12 +0800] "POST /xxxx/xxxxx HTTP/1.1" 200 79 "-" "ASIHTTPRequest" "xxx=xxx; SESSIONID=xxxxxxx" "-" "192.168.1.12:8080" "200" "0.023" "0.010" "3.0" "xxx-xx-x-x-x" "3" "{\x22Id\x22:123456}"

--

    /usr/local/goaccess-0.9.2/etc/goaccess.conf	  
    time-format %H:%M:%S
    date-format %d/%b/%Y
    log_format %^ %h %^ %^ [%d:%t %^] "%r" %s %b "%R" "%u" "%^" "%^" "%^" "%^" "%T" "%^" "%^" "%^" "%^" "%^"

Total Requests
57,889
Failed Requests
20,080

Total request more than the actual request
Help to look at the format configuration

**Comment by allinurl** [comment]
Please try the following log-format, it should work:

    log-format %^ %h %^[%d:%t %^] "%r" %s %b "%R" "%u" "%^" "%^" "%^" "%^" "%T"

**Comment by kys1230** [comment]
log-format %^ %h %^[%d:%t %^] "%r" %s %b "%R" "%u" "%^" "%^" "%^" "%^" "%T"
 Total Requests  57889 Unique Visitors 0 Referrers    0 Log Size  99.62 MiB
  Failed Requests 57903 Unique Files    0 Unique 404   0 Bandwidth 0.0   B
  Generation Time 0     Excl. IP Hits   0 Static Files 0

log-format %^ %h - %^[%d:%t %^] "%r" %s %b "%R" "%u" "%^" "%^" "%^" "%^" "%T"
  Total Requests  57889 Unique Visitors 1330 Referrers    5 Log Size  99.62 MiB
  Failed Requests 20080 Unique Files    155  Unique 404   4 Bandwidth 261.98 MiB
  Generation Time 1     Excl. IP Hits   0    Static Files 2

**Comment by kys1230** [comment]
Log the number of lines is 37824

**Comment by allinurl** [comment]
How many lines does the log file contain? The log format I posted before works with the sample log you posted.

Have you checked that your access log does not have different set of lines?

**Comment by allinurl** [comment]
Closing this, feel free to re-open it if needed.
