### ISSUE TITLE
confirm config file format for GoAccess config file (for syntax highlighting in Vim)

### ISSUE THREAD

**Issue by meonkeys** [allinurl/goaccess#2700]
I proposed a Vim syntax highlighting definition for GoAccess configuration files: https://github.com/vim/vim/pull/15414

I briefly reviewed `settings.c` and `options.c` and I wanted to confirm a few things about the config file:

1. every config setting is a single-line space-separated key value pair
2. both a key and value are required for a setting: `blah` is invalid, `blah foo` is valid
3. keys _should_ always match `[a-z-]` (this seems to be true by convention, but the code doesn't appear to enforce it)
4. values are any string of characters terminated by end-of-line
5. every line starting with a hash mark is a comment, and skipped/ignored by the config file parser
6. blank lines are skipped/ignored

If I got those mostly right, my patch to Vim should be good enough for reliable syntax highlighting for GoAccess configuration files.

**Comment by allinurl** [comment]
That's accurate, and you make a great point about enforcing the keys to be [a-z-]. I don't see any issues with that approach so far. As you mentioned, there are currently no restrictions on the keys.

Thank you for submitting the patch; it would be fantastic if Vim could integrate it. Please let me know if you have any other questions.

**Comment by meonkeys** [comment]
The patch was accepted!
