### ISSUE TITLE
Static files listed under requests

### ISSUE THREAD

**Issue by Csardelacal** [allinurl/goaccess#271]
For some reason when using nginx with version 0.9.1 the list of static files is empty while image, JS and CSS files appear in the top request URL report.

<img width="511" alt="captura de pantalla 2015-07-17 a las 10 16 15" src="https://cloud.githubusercontent.com/assets/1152823/8743142/e2d694be-2c6c-11e5-83bb-08d1b7a1e4a5.png">

**Comment by Csardelacal** [comment]
Just a quick update. My system just upgraded to 0.9.2 and the issue is still there.

**Comment by allinurl** [comment]
Sounds like no config file was specified. The [config file](https://github.com/allinurl/goaccess/blob/master/config/goaccess.conf#L149) contains the extensions. You can run it with `-p /path/goaccess.conf` if for some reason is not under `%sysconfdir%`.

**Comment by Csardelacal** [comment]
Ok, that fixed it. For some reason my system lost it's config file and I was using a custom one to run it in a cron. Didn't know that you had to specify the static files there.

Maybe some kind of hint in the output would be nice warning that no statics where found. Or even better, if no statics are defined to have some kind of fallback defaults.

Thank you!

**Comment by allinurl** [comment]
Glad that worked. Thanks for pointing that out, I've added a new issue for this #272.
