### ISSUE TITLE
Can the official website and documents of goaccess be open sourced?

### ISSUE THREAD

**Issue by ikxin** [allinurl/goaccess#2716]
I am glad to see such a log analysis tool. I plan to translate its official website and documentation into Chinese to help more people learn and use it. However, I did not find the source code related to the website in the code repository. May I ask if it is open source?

**Comment by allinurl** [comment]
I'm glad you found it useful! It’s definitely open source, and we’d be very grateful if you could help update or contribute to the Chinese translation. You can find the file [here](https://github.com/allinurl/goaccess/blob/master/po/zh_CN.po). If you have any questions, feel free to ask.

**Comment by ikxin** [comment]
@allinurl The Chinese translation in the GoAccess project is already quite complete. In addition, I want to translate the official website https://goaccess.io into Chinese. I found a similar site https://www.goaccess.cc in the search engine, but it has not been updated for a long time. I thought that if the GoAccess official website has open-source code, I could maintain a Chinese document that keeps up to date based on it to help more people in Chinese-speaking areas learn and use GoAccess.

**Comment by ikxin** [comment]
@allinurl What progress has been made?

**Comment by ikxin** [comment]
@allinurl The translation plugin for browsers may be a good idea for plain text, but it is not excellent for websites that contain a lot of code examples, as it is difficult to convey the true meaning of a code snippet. Therefore, I prefer to create a mirror document in Chinese. If it is open source, I can maintain the translation without worrying about outdated content. You can refer to a project I am currently maintaining at https://github.com/zhcndoc, using git to keep the content in sync with the upstream repository.

**Comment by ikxin** [comment]
I'm sorry I didn't receive your reply. I will close this issue for now. If there are any updates later, feel free to contact me anytime.
