### ISSUE TITLE
The Goaccess APT repo is down

### ISSUE THREAD

**Issue by NielsH** [allinurl/goaccess#2726]
Hello,

Since about 30 minutes we can no longer reach the deb.goaccess.io repository:
```
Could not connect to deb.goaccess.io:443 (2001:470:1f10:121::2), connection timed out Could not connect to deb.goaccess.io:443 (172.110.195.161), connection timed out
```

Is there any known issue or maintenance happening at the moment?
Thank you!

**Comment by mlaurense** [comment]
I'm having the same issue here

**Comment by jaromanda** [comment]
In fact, `goaccess.io` itself is down

**Comment by NielsH** [comment]
The repo started working again after about 50 minutes or so. I'll close the issue!

**Comment by allinurl** [comment]
Thank you for letting me know! The service was down while I updated the servers. I **might** need to take them down again briefly, but I’ll aim to keep it quick. It should be back up now, as you’ve noticed. I really appreciate your feedback!
