### ISSUE TITLE
Hostname not accurate

### ISSUE THREAD

**Issue by Zabrane** [allinurl/goaccess#2730]
Hi guys

I'd like to know how `GoAccess v1.9.3` get the `hostname` information as shown in the screenshot?
![goaccess_hostname](https://github.com/user-attachments/assets/83698aac-27d2-4547-88f7-be4ea366022c)

I'm using `GeoLite2-City.mmdb`.
Thanks you

**Comment by 0bi-w6n-K3nobi** [comment]
Hi @Zabrane 

Nice talk with you here.
Perhaps, you may check more carefully at `GOAccess` Live Demo [here](http://rt.goaccess.io/), at same panel `Vistor Hostnames and IPs` .
At one, you can see `City`, `Country` and `ASN`  fields values that are resolved from lookup of Geo database.
But `hostname` are resolved from DNS lookup, like a `host` tool in linux.
So, maybe values seems little bit weird but did chosen by domain owner.
You maybe check, and confirm them, by way for any DNS online resolver.

I hope be clean. Feel free for more asks.

**Comment by Zabrane** [comment]
@0bi-w6n-K3nobi  Thanks. You are definitely right.

**Comment by allinurl** [comment]
@0bi-w6n-K3nobi Great answer, thanks!
