### ISSUE TITLE
Granular generation of html charts in real-time mode

### ISSUE THREAD

**Issue by oddjobz** [allinurl/goaccess#2744]
Hi, quick question; is it possible to generate html for individual charts, and by implication have the websocket connection just update information for individual charts?

Use-case; we would like to be able to display individual / selected live charts on a user dashboard .. are there any options that might make this possible?

**Comment by allinurl** [comment]
You could generate individual reports by using [`--ignore-panel=<PANEL>`](https://goaccess.io/man) and choosing the specific panels you want to view in the report while keeping `--real-time-html`.

**Comment by oddjobz** [comment]
Ok, that sounds like an interesting option, I'll have a play with that.  Many thanks.

**Comment by oddjobz** [comment]
Ok, quite excited by this option, but as I'm embedding within a dashboard I'm thinking there's likely to be a CSS conflict, so I'm wondering if I can just suck the information from the web-socket and use it for a dashboard-native chart/table. Is there any documentation for the WS API or should I go look at the source? (in context the dashboard pulls from other sources using socketio.js)

**Comment by allinurl** [comment]
Looks like the easiest way to grab it is through ws://socket_address:7890 using JS.

**Comment by oddjobz** [comment]
Ok, tvm. I think as per the other issue I'm going to have to grab it server side to get the size down .. :-)
