### ISSUE TITLE
AWS Elastic Load Balancer access log

### ISSUE THREAD

**Issue by ipalo** [allinurl/goaccess#275]
AWS ELB access log has a new format now.

My log looks like this:
```
2015-08-01T00:00:39.092804Z awseb-e-c-AWSEBLoa-IT1XXX1234124 1.22.3.4444:18031 123.33.11.222:80 0.000038 0.543988 0.000071 200 200 0 153373 "GET http://www.site.com:80/api/v2/get HTTP/1.1" "Dalvik/1.6.0 (Linux; U; Android 4.4.2; LG-D605 Build/KOT49I.D60520e)" - -
```
This is the format as looks like in AWS ELB documentation:
```
timestamp elb client:port backend:port request_processing_time backend_processing_time response_processing_time elb_status_code backend_status_code received_bytes sent_bytes "request" "user_agent" ssl_cipher ssl_protocol
```
I tried with
```
log_format %x %^ %h %^ %^ %T %^ %^ %s %^ %b "%m %U %H" "%u" %^ %^
date_format  %Y-%m-%d
```
but this doesn't work.

Can anyone help me?

Thanks!

p.s. i opened this issue and commented the old one https://github.com/allinurl/goaccess/issues/73#issuecomment-127257305

**Comment by allinurl** [comment]
The following works (v0.9.2), just make sure you have a valid IP:

    log-format: %dT%t.%^ %^ %h:%^ %^ %T %^ %^ %^ %s %^ %b "%r" "%u"
    date-format %Y-%m-%d
    time-format %H:%M:%S

**Comment by ipalo** [comment]
It works :+1: 

Thank you @allinurl

**Comment by mostafazh** [comment]
:+1:
