### ISSUE TITLE
Caddy support

### ISSUE THREAD

**Issue by Justman100** [allinurl/goaccess#2754]
I use [Caddy](https://caddyserver.com), but it doesn't seem to be supported as no log format seems to match:

> Format Errors - Verify your log/date/time format

Caddy outputs logs in the following format:

```log
{"level":"info","ts":1731084144.3270802,"logger":"http.log.access","msg":"handled request","request":{"remote_ip":"34.45.54.229","remote_port":"53176","client_ip":"34.45.54.229","proto":"HTTP/1.1","method":"POST","host":"<HOST>","uri":"/","headers":{"Accept":["*/*"],"Connection":["keep-alive"],"Content-Length":["20"],"Content-Type":["application/x-www-form-urlencoded"],"User-Agent":["Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36"],"Accept-Encoding":["gzip, deflate"]}},"bytes_read":0,"user_id":"","duration":0.000024323,"size":0,"status":308,"resp_headers":{"Content-Type":[],"Server":["Caddy"],"Connection":["close"],"Location":["<HOST>"]}}
```

**Comment by Justman100** [comment]
@allinurl

**Comment by allinurl** [comment]
Are you on the latest version of goaccess? If yes, what output do you get with `goaccess access.log --log-format=CADDY`?

**Comment by Justman100** [comment]
> Are you on the latest version of goaccess? If yes, what output do you get with `goaccess access.log --log-format=CADDY`?

Works!

**Comment by allinurl** [comment]
Great! make sure it covers pretty much all the panels and metrics on the report. Let me know if you have any other questions!
