### ISSUE TITLE
Goaccess stops parsing after one second

### ISSUE THREAD

**Issue by norbertrostaing** [allinurl/goaccess#2756]
Hello
I used go access 1.8.1 on my log file to generate an HTML file and it worked great
Since I updated on 1.9.3, I run my parsing with `goaccess access.log -o stats.html`, goaccess runs for one second and then stops.
I have only 3 days of logs (the first three days of the file)

when using the --debug-file option, my debug file contains only "Bye." 

I am probably doing something wrong, can you help me on this ?

my conf file contains : 
```
log-format %h %^[%d:%t %^] "%r" %s %b "%R" "%u"
date-format %d/%b/%Y
time-format %H:%M:%S
```
and here is some samples of my log file
```
54.144.185.255 - - [11/Oct/2024:22:56:49 +0000] "GET /fixtures/mochis/Ablelite/Beam%20620/?C=M;O%3DA HTTP/1.1" 200 3168 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/600.2.5 (KHTML, like Gecko) Version/8.0.2 Safari/600.2.5 (Amazonbot/0.1; +https://developer.amazon.com/support/amazonbot)"
23.21.250.48 - - [11/Oct/2024:22:56:53 +0000] "GET /fixtures/mochis/Ablelite/Beam%20620/?C=M;O%3DD HTTP/1.1" 200 3168 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/600.2.5 (KHTML, like Gecko) Version/8.0.2 Safari/600.2.5 (Amazonbot/0.1; +https://developer.amazon.com/support/amazonbot)"
3.89.170.186 - - [11/Oct/2024:22:56:58 +0000] "GET /fixtures/mochis/Ablelite/Beam%20620/?C=N;O%3DD HTTP/1.1" 200 3169 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/600.2.5 (KHTML, like Gecko) Version/8.0.2 Safari/600.2.5 (Amazonbot/0.1; +https://developer.amazon.com/support/amazonbot)"
107.20.25.33 - - [11/Oct/2024:22:57:01 +0000] "GET /fixtures/mochis/Ablelite/EVA%20150S/?C=D;O%3DA HTTP/1.1" 200 3154 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/600.2.5 (KHTML, like Gecko) Version/8.0.2 Safari/600.2.5 (Amazonbot/0.1; +https://developer.amazon.com/support/amazonbot)"
54.225.181.161 - - [11/Oct/2024:22:57:05 +0000] "GET /fixtures/mochis/Ablelite/EVA%20150S/?C=D;O%3DD HTTP/1.1" 200 3156 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/600.2.5 (KHTML, like Gecko) Version/8.0.2 Safari/600.2.5 (Amazonbot/0.1; +https://developer.amazon.com/support/amazonbot)"
18.206.47.187 - - [11/Oct/2024:22:57:09 +0000] "GET /fixtures/mochis/Ablelite/EVA%20150S/?C=N;O%3DA HTTP/1.1" 200 3156 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/600.2.5 (KHTML, like Gecko) Version/8.0.2 Safari/600.2.5 (Amazonbot/0.1; +https://developer.amazon.com/support/amazonbot)"
```

**Comment by allinurl** [comment]
This should work:

    # goaccess log --log-format=COMBINED

![2024-11-09-180636_559x310_scrot](https://github.com/user-attachments/assets/a87990f1-9bb0-41d5-92ec-08e35c09d5fc)

**Comment by norbertrostaing** [comment]
It's not, I've downgrade to 1.8.1 with same conf file and it works

**Comment by allinurl** [comment]
It seems like there's an issue with your config file. I recommend deleting it and starting from scratch. The screenshot I shared above is from the latest version, v1.9.3. Let me know if that works for you.

**Comment by norbertrostaing** [comment]
I made some tests.
I really don't understand how my config file should be the issue, it works with 1.8.1 but not with 1.9.3 and if I use "--log-format=COMBINED", I have the same issue

### with version 1.8.1 and my config file
command
`wget -O - https://deb.goaccess.io/gnugpg.key | gpg --dearmor | sudo tee /usr/share/keyrings/goaccess.gpg `>/dev/null`

result
[RENDERING /home/wwwroot/logs/blinderkitten.access.log] {1917065} @ {9585/s}
Cleaning up resources...

![image](https://github.com/user-attachments/assets/42528002-aabb-47f9-9419-fd0fcfb81270)

### with version 1.9.3 and my config file
command
`goaccess /home/wwwroot/logs/blinderkitten.access.log -o /home/wwwroot/hazlab/stats.html --ignore-crawlers`

result
[PARSING /home/wwwroot/logs/blinderkitten.access.log] {6144} @ {6144/s}
Cleaning up resources...

![image](https://github.com/user-attachments/assets/395eb265-e114-493f-83f1-1d6f76fb1ff5)

### with version 1.9.3 and log combined
command
`goaccess /home/wwwroot/logs/blinderkitten.access.log -o /home/wwwroot/hazlab/stats.html --ignore-crawlers --log-format=COMBINED`

result
[PARSING /home/wwwroot/logs/blinderkitten.access.log] {6139} @ {6139/s}
Cleaning up resources...

![image](https://github.com/user-attachments/assets/3f1d57b7-b2c1-4dd6-99b7-3e7bc2340a0e)

**Comment by norbertrostaing** [comment]
hum, my log file was "corrupted" on the line 7187 -_-
Sorry for bothering you
