### ISSUE TITLE
Unable to parse traefik json log

### ISSUE THREAD

**Issue by priyankub** [allinurl/goaccess#2757]
Hi,

I keep getting log time date format error with json access logs from traefik. here is what I am using as post arguments in docker:

```
--log-format='{"ClientAddr":"%h:%^","ClientHost":"%^","ClientPort":"%^","ClientUsername":"%^","DownstreamContentSize":"%b","DownstreamStatus":"%^","Duration":"%n","OriginContentSize":"%^","OriginDuration":"%^","OriginStatus":"%s","Overhead":"%^","RequestAddr":"%v","RequestContentSize":"%^","RequestCount":"%^","RequestHost":"%^","RequestMethod":"%m","RequestPath":"%U","RequestPort":"%^","RequestProtocol":"%H","RequestScheme":"%^","RetryAttempts":"%^","RouterName":"%^","ServiceAddr":"%^","ServiceName":"%^","ServiceURL":"%^","SpanId":"%^","StartLocal":"%^","StartUTC":"%dT%t.%^","TLSCipher":"%^","TLSVersion":"%^","TraceId":"%^","entryPointName":"%^","level":"%^","msg":"%^","time":"%^"}'
--date-format='%Y-%m-%d'
--time-format='%H:%M:%S'
```

this is a sample of traefik log:

```
{"ClientAddr":"192.168.11.2:40126","ClientHost":"192.168.11.2","ClientPort":"40126","ClientUsername":"-","DownstreamContentSize":2099,"DownstreamStatus":200,"Duration":1811271,"OriginContentSize":2099,"OriginDuration":1564210,"OriginStatus":200,"Overhead":247061,"RequestAddr":"nzbget.local.example.com","RequestContentSize":154,"RequestCount":103109,"RequestHost":"nzbget.local.example.com","RequestMethod":"POST","RequestPath":"/xmlrpc","RequestPort":"-","RequestProtocol":"HTTP/1.1","RequestScheme":"https","RetryAttempts":0,"RouterName":"https-nzbget-local@docker","ServiceAddr":"172.20.0.47:6789","ServiceName":"nzbget-service@docker","ServiceURL":"http://172.20.0.47:6789","SpanId":"0000000000000000","StartLocal":"2024-11-14T12:49:22.640540732-05:00","StartUTC":"2024-11-14T17:49:22.640540732Z","TLSCipher":"TLS_AES_128_GCM_SHA256","TLSVersion":"1.3","TraceId":"00000000000000000000000000000000","entryPointName":"https","level":"info","msg":"","time":"2024-11-14T12:49:22-05:00"}
{"ClientAddr":"192.168.1.206:47698","ClientHost":"192.168.1.206","ClientPort":"47698","ClientUsername":"-","DownstreamContentSize":491,"DownstreamStatus":200,"Duration":63791537,"OriginContentSize":491,"OriginDuration":63604875,"OriginStatus":200,"Overhead":186662,"RequestAddr":"cloud.example.com","RequestContentSize":0,"RequestCount":103110,"RequestHost":"cloud.example.com","RequestMethod":"GET","RequestPath":"/ocs/v2.php/cloud/user?format=json","RequestPort":"-","RequestProtocol":"HTTP/2.0","RequestScheme":"https","RetryAttempts":0,"RouterName":"https-nextcloud-secure@docker","ServiceAddr":"172.20.0.18:443","ServiceName":"nextcloud@docker","ServiceURL":"https://172.20.0.18:443","SpanId":"0000000000000000","StartLocal":"2024-11-14T12:49:24.642311238-05:00","StartUTC":"2024-11-14T17:49:24.642311238Z","TLSCipher":"TLS_AES_128_GCM_SHA256","TLSVersion":"1.3","TraceId":"00000000000000000000000000000000","entryPointName":"https","level":"info","msg":"","time":"2024-11-14T12:49:24-05:00"}
```

**Comment by allinurl** [comment]
This should get you started:

    $ goaccess log --log-format='{ "ClientAddr": "%h:%^", "OriginStatus": "%s", "RequestAddr": "%v", "RequestMethod": "%m", "RequestPath": "%U", "RequestProtocol": "%H", "time": "%dT%t-%^" }' --date-format='%Y-%m-%d' --time-format=%T --date-spec=min

![2024-11-14-175801_469x315_scrot](https://github.com/user-attachments/assets/4fdb39bd-f0ab-4f23-a90b-95ae6b0e88bd)

**Comment by mrpops2ko** [comment]
> This should get you started:
> 
> ```
> $ goaccess log --log-format='{ "ClientAddr": "%h:%^", "OriginStatus": "%s", "RequestAddr": "%v", "RequestMethod": "%m", "RequestPath": "%U", "RequestProtocol": "%H", "time": "%dT%t-%^" }' --date-format='%Y-%m-%d' --time-format=%T --date-spec=min
> ```
> 
> ![2024-11-14-175801_469x315_scrot](https://private-user-images.githubusercontent.com/5005367/386406437-4fdb39bd-f0ab-4f23-a90b-95ae6b0e88bd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4OTE2MzEsIm5iZiI6MTczMjg5MTMzMSwicGF0aCI6Ii81MDA1MzY3LzM4NjQwNjQzNy00ZmRiMzliZC1mMGFiLTRmMjMtYTkwYi05NWFlNmIwZTg4YmQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMjlUMTQ0MjExWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzE4NzQ0Njk1YjA2ZDQ1ZmQzNWZlOGFmY2Y1M2FjMzcyYWRmM2RkZDIwZjk2NDE0ZTE3MGZhODBlNWEzOTFhYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.3XX5tFQcbD96C1kgmoXfO7pWlFhomptB6AQb8VJoj1Q)

this didn't work for me but i've found this does 

```
cat access.log | docker run --rm -i -v ./report.html:/report.html -e LANG=$LANG allinurl/goaccess -a -o report.html --log-format='{ "ClientAddr": "%h:%^", "OriginStatus": "%s", "RequestAddr": "%v", "RequestMethod": "%m", "RequestPath": "%U", "RequestProtocol": "%H", "time": "%d" }' --date-format='%Y-%m-%dT%H:%M:%SZ' --time-format='%H:%M:%S' --date-spec=min -
```

i'll try and improve it if possible with more useful fields but at least this one is working for now

edit: since i use cloudflare, i've modified it to use the real client ip instead

```
cat access.log | docker run --rm -i -v ./report.html:/report.html -e LANG=$LANG allinurl/goaccess -a -o report.html \
--log-format='{ "ClientHost": "%h", "OriginStatus": "%s", "RequestHost": "%v", "RequestMethod": "%m", "RequestPath": "%U", "RequestProtocol": "%H", "time": "%d", "request_User-Agent": "%u" }' \
--date-format='%Y-%m-%dT%H:%M:%SZ' \
--time-format='%H:%M:%S' \
--date-spec=min \
-
```

edit 2: 

```
cat access.log | docker run --rm -i -v ./report.html:/report.html -e LANG=$LANG allinurl/goaccess -a -o report.html \
--log-format='{ "ClientHost": "%h", "DownstreamStatus": "%s", "DownstreamContentSize": "%b", "RequestHost": "%v", "RequestMethod": "%m", "RequestPath": "%U", "RequestProtocol": "%H", "Duration": "%n", "TLSVersion": "%K", "TLSCipher": "%k", "ClientUsername": "%e", "time": "%d", "request_User-Agent": "%u" }' \
--date-format='%Y-%m-%dT%H:%M:%SZ' --time-format='%H:%M:%S' --date-spec=min -
```


in my traefik.yml file i'm doing

```
accessLog:
  filePath: /var/log/traefik/access.log
  format: json
  filters:
    statusCodes:
      - "200-299" # log successful http requests
      - "400-599" # log failed http requests
  # collect logs as in-memory buffer before writing into log file
  bufferingSize: 10000
  fields:
    headers:
      defaultMode: drop # drop all headers per default
      names:
          User-Agent: keep # log user agent strings
```


i'll keep trying some more to improve it but if anybody else wants to, the [documentation is here](https://goaccess.io/man#custom-log) for which ones could be potential matches

**Comment by priyankub** [comment]
> --log-format='{ "ClientAddr": "%h:%^", "OriginStatus": "%s", "RequestAddr": "%v", "RequestMethod": "%m", "RequestPath": "%U", "RequestProtocol": "%H", "time": "%dT%t-%^" }' --date-format='%Y-%m-%d' --time-format=%T --date-spec=min

I have no idea how I missed your reply. This worked perfectly! It might be helpful if this was added in your documentation so traefik users with json logs could use your awesome tool out of the box.

**Comment by beertje44** [comment]
Thanks for this! For me this worked:

`--log-format='{"ClientHost": "%h", "ClientUsername": "%e", "DownstreamContentSize": "%b", "DownstreamStatus": "%s", "Duration": "%n", "RequestHost": "%v", "RequestMethod": "%m", "RequestPath": "%U", "RequestProtocol": "%H", "request_Referer":"%R", "request_User-Agent": "%u", "time": "%dT%tZ"}' --date-format='%Y-%m-%d' --time-format='%H:%M:%S'`

Couldn't get the TLS part working, I think because Traefik logs only the TLS version like "1.3" and doesn't prefix this with TLS.

The fun part is I have a lot more in my traefik json log and the lines are also dynamic because I log headers and process them with loki/grafana and wazuh, but somehow goaccess just extracts only what is mentioned above and it just works (tm) 👍 

For others: current traefik does seem to put all the fields in alphatical order (uppercase first and them lowercase).

**Comment by mbirth** [comment]
Just to prevent the next person spending an hour wondering why the `log-format` string works on the command line but not in the config file:

> [!NOTE]
> Don't enclose the log-format string in single quotes in the config file. Use e.g.:
> ```
> log-format { "ClientHost": "%h", "ClientUsername": "%e", "DownstreamContentSize": "%b" }
> ```
> Also always use double-quotes for values in the parser string even though the values
> appear as numbers in the JSON log (e.g. for `DownstreamContentSize`).

**Comment by allinurl** [comment]
@mbirth Thanks for pointing this out. You're correct, the shell strips outer quotes on the command line, while the config parser reads them literally. JSON format specifiers also need quotes so the format itself remains valid JSON. I've clarified this on the [man page](https://github.com/allinurl/goaccess/commit/c905b0c99e8cb42db3ad23dd72562044f15939a6).
