### ISSUE TITLE
log-format doesn't work!

### ISSUE THREAD

**Issue by netamirbabaei** [allinurl/goaccess#2759]
@allinurl Hi. I have a problem about that

It's my Nginx log format:
`       log_format main 'Date: [$time_local] | IP: $remote_addr | X_Forwarded_IP: $http_x_forwarded_for | '
                             'Request_Method: "$request_method | Host: "$host" |  URI: $request_uri" | '
                             'Status_code: $status | Response_Size: $body_bytes_sent | '
                             'Refferer: "$http_referer" | User_Agent: "$http_user_agent" ';`

and this is a line about that:
`{"log":"Date: [18/Nov/2024:11:02:03 +0330] | IP: 5.25.140.121 | X_Forwarded_IP: - | Request_Method: \"OPTIONS | Host: \"napi.lastthird.com\" |  URI: /tours/filters\" | Status_code: 204 | Response_Size: 0 | Refferer: \"https://lastthird.com/\" | User_Agent: \"Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Mobile Safari/537.36\" \n","stream":"stdout","time":"2024-11-18T07:32:03.364283382Z"}`

and this is log-format but doesn't work:
`--log-format='{"log":"Date:` [%d/%b/%Y:%H:%M:%S %z] | IP: %h | X_Forwarded_IP: %e | Request_Method: \"%m | Host: \"%v |  URI: %U\" | Status_code: %s | Response_Size: %b | Refferer: \"%R\" | User_Agent: \"%u\"' --date-format=%d/%b/%Y --time-format=%H:%M:%S --real-time-html`

Thsnks for your support!

**Comment by heyainsleymae** [comment]
When specifying your log format, `%d` refers to a date field that matches your specified format, rather than the `strftime` definition of "day of the month as a decimal number". You can also use `%t` when specifying the log format to refer to your specified time format. With those changes, here is the updated `--log-format` flag:
```
--log-format='{"log":"Date: [%d:%t %z] | IP: %h | X_Forwarded_IP: %e | Request_Method: "%m | Host: "%v | URI: %U" | Status_code: %s | Response_Size: %b | Refferer: "%R" | User_Agent: "%u"'
```

This presents a new error:
```
Token '"OPTIONS' doesn't match specifier '%m'
```

I assume that the solution to this would be sorting out the quotation marks and properly escaping them when specifying the log format, but I could be wrong. If I figure anything else out, I will post it here, but I hope the above change is of some help.

**Comment by netamirbabaei** [comment]
I changed Nginx Log format to this:
`        log_format main 'Date: [$time_local] | IP: $remote_addr | X_Forwarded_IP: $http_x_forwarded_for | '
                'Request_Method: "$request_method" | Host: "$host" | URI: "$request_uri" | '
                'Status_code: $status | Response_Size: $body_bytes_sent | '
                'Refferer: "$http_referer" | User_Agent: "$http_user_agent"';`
           
some parts of logs add by docker like \n","stream":"stdout","time":"2024-11-19T11:27:23.107791056Z" at the end of log:
`{"log":"Date: [19/Nov/2024:14:57:23 +0330] | IP: 79.175.131.53 | X_Forwarded_IP: 40.77.167.150, 185.215.232.163 | Request_Method: \"POST\" | Host: \"rapi.lastsecond.ir\" | URI: \"/tours/index\" | Status_code: 200 | Response_Size: 5184 | Refferer: \"-\" | User_Agent: \"Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm) Chrome/116.0.1938.76 Safari/537.36\"\n","stream":"stdout","time":"2024-11-19T11:27:23.107791056Z"}`

and this is the better log format I have found but faced with error:
![Screenshot from 2024-11-20 13-13-12](https://github.com/user-attachments/assets/d1ea633b-87dc-4640-817f-95a6d63ed199)
![Screenshot from 2024-11-20 13-13-12](https://github.com/user-attachments/assets/b59f007c-aa28-4a7e-8110-a11a8167e325)

goaccess /var/lib/docker/containers/2c5eb8ce34c5593fbffbccd734bda70818bae95c7c44cbf3f251693920972d15/2c5eb8ce34c5593fbffbccd734bda70818bae95c7c44cbf3f251693920972d15-json.log -o /opt/goaccess/rep.html --log-format='{"log":"Date: %^[%d:%t %^] | IP: %h | X_Forwarded_IP: %e | Request_Method: \"%m\" | Host: \"%v\" | URI: \"%U\" | Status_code: %s | Response_Size: %b | Refferer: \"%R\" | User_Agent: \"%u\"%^}' --date-format=%d/%b/%Y --time-format=%T --real-time-html

**Comment by allinurl** [comment]
@netamirbabaei It seems like you have a mix of JSON and the actual log within the log. It would be much easier to work with if the log were in a proper JSON format. If you could adjust the format, that would be really helpful.

**Comment by netamirbabaei** [comment]
@allinurl Thanks for your support & help! 

That's Final command and it works :
` jq -r '.log' /var/lib/docker/containers/7ac22b71a4e2beba4dc276fa178d0ced0916ca8ebe8ca27f3fda0e766e1ccce5/7ac22b71a4e2beba4dc276fa178d0ced0916ca8ebe8ca27f3fda0e766e1ccce5-json.log | sudo goaccess - -o /home/user01/code/goaccess/report.html --log-format='Date: %^[%d:%t %^] | IP: %h | X_Forwarded_IP: %^| Request_Method: "%m" | Host: "%v" | URI: "%U" | Status_code: %s | Response_Size: %b | Refferer: "%R" | User_Agent: "%u"' --date-format=%d/%b/%Y --time-format=%T --real-time-html `
