### ISSUE TITLE
Add AWS Elastic Load Balancing log/date/time formats

### ISSUE THREAD

**Issue by allinurl** [allinurl/goaccess#276]
Add AWS ELB to the list of predefined log/date/time formats.

**Comment by allinurl** [comment]
This has been added.

**Comment by narayan1599** [comment]
![Screenshot 2020-03-31 at 4 29 46 PM](https://user-images.githubusercontent.com/43582408/78019359-37062300-736d-11ea-8fa6-ffb586259bcf.png)

**Comment by narayan1599** [comment]
i am getting this error any ref doc

**Comment by allinurl** [comment]
As it says in there, `https 2020-03-30` is not a valid `%d` date. You need to specify a valid log-format.
