### ISSUE TITLE
[Bug] Referrers 0 but Referring Sites is populated

### ISSUE THREAD

**Issue by tebriel** [allinurl/goaccess#2775]
## Description

I have 2 referrers in my `Referring Sites` section but `Referrers` stat at the top of the TUI is `0`.

## Expected Result

`Referrers` would have a value of 2

## Background

Hi! Maybe I'm not quite understanding the data that's trying to be presented. I'm using NGINX and have set the following parsing for my log lines:

```sh
goaccess --log-format='%h %^[%d:%t %^] "%r" %s %b "%R" "%u"' --date-format='%d/%b/%Y' --time-format='%H:%M:%S' /var/log/nginx/access.log
```

I'm running goaccess 1.9.3

```sh
goaccess --version
GoAccess - 1.9.3.
For more details visit: https://goaccess.io/
Copyright (C) 2009-2024 by Gerardo Orellana

Build configure arguments:
  --enable-utf8
  --enable-geoip=mmdb
  --with-openssl
```

I can see referrers in my logs (`"https://forge.frodux.in/assets/js/eventsource.sharedworker.js?v=9.0.2"` for example:

```
45.24.132.65 - - [15/Dec/2024:00:46:55 -0500] "GET /user/events HTTP/2.0" 200 0 "https://forge.frodux.in/assets/js/eventsource.sharedworker.js?v=9.0.2" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 Edg/131.0.0.0"
45.24.132.65 - - [15/Dec/2024:00:47:09 -0500] "GET /user/events HTTP/2.0" 200 417 "https://forge.frodux.in/assets/js/eventsource.sharedworker.js?v=9.0.2" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 Edg/131.0.0.0"
45.24.132.65 - - [15/Dec/2024:01:03:52 -0500] "GET /user/events HTTP/2.0" 200 430 "https://forge.frodux.in/assets/js/eventsource.sharedworker.js?v=9.0.2" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 Edg/131.0.0.0"
45.24.132.65 - - [15/Dec/2024:01:22:33 -0500] "GET /user/events HTTP/2.0" 200 0 "https://forge.frodux.in/assets/js/eventsource.sharedworker.js?v=9.0.2" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 Edg/131.0.0.0"
```

And I can see referrers in my output:

![Screenshot of TUI showing 2 referrers, one url and one ip address](https://github.com/user-attachments/assets/d1f8205c-136b-490f-8cf0-fb24173580d2)

But the Top Level stats show `Referrers 0`

![A screenshot of the stats at the top of the TUI showing many stats, including Referrers as the value 0](https://github.com/user-attachments/assets/2b4a29ae-a7f7-4757-8700-6aea883fb031)

cc @shapr who has also experienced this with his logs (though the same log format so maybe we're both holding it wrong!)

**Comment by allinurl** [comment]
Good question! I believe it's related to the referrers panel, which is disabled by default. You can enable it with the following option:  `--enable-panel=REFERRERS`. Let me know if that works for you!

**Comment by tebriel** [comment]
@allinurl ok awesome thanks! What is that supposed to be hiding? Since I can see the referrers section and the heading?

**Comment by allinurl** [comment]
One displays the full referrer (assuming `--enable-panel=REFERRERS`), while the other shows just the site. For example:

![2024-12-19-205703_652x243_scrot](https://github.com/user-attachments/assets/eddb9d6b-9ecd-4e2e-8ace-f5616aba3f33)

Are you seeing something else?

**Comment by tebriel** [comment]
@allinurl oh that makes sense, I think I just wasn't fully grokking what I was seeing. Thanks so much for the fast and thorough support!
