### ISSUE TITLE
Failed Requests detail.

### ISSUE THREAD

**Issue by m0m0g33k** [allinurl/goaccess#279]
Get the detail of the Failed Requests identified from the log file or STDIN, vía command line and/or in the output to HTML/JSON/CVS.

Awesome could be to know the reason of the failure.

Kind Regards.

**Comment by allinurl** [comment]
I've added the ability to log all invalid requests to a file using --invalid-requests=<filename>. You will need to build from [dev](http://goaccess.io/download#build). Otherwise it will be pushed out in the upcoming release.
