### ISSUE TITLE
no static requests show up

### ISSUE THREAD

**Issue by edovino** [allinurl/goaccess#280]
I use goacces with nginx, with a custom log format.

The nginx config looks like:
```
log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                 '$status $body_bytes_sent "$http_referer" '
               '"$http_user_agent" "$http_x_forwarded_for" "$gzip_ratio" "$request_time"';
``` 
Log lines look like this:
```
192.168.255.8 - - [12/Aug/2015:17:59:53 +0200] "GET /robots.txt HTTP/1.1" 200 55 "-" "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)" "-" "-" "0.000"
```

The corresponding format in '.goaccessrc' is

```
time-format %T
date-format %d/%b/%Y
log-format %h %^ %^ [%d:%t %^] "%r" %s %b "%R" "%u" "^%" "^%" "%T"
```

This works well, except no static resource requests are recognized. The panel remains empty, totals stay at 0.

**Comment by allinurl** [comment]
Sounds like no config file was specified. The config file contains the extensions. You can run it with `-p /path/goaccess.conf` if for some reason is not under `%sysconfdir%`.

Issue #271 addressed this issue. The soon-to-be-released version will include this fix.

**Comment by edovino** [comment]
Yup. That was it - thx!
(I've added the extensions to the .goaccessrc for now)
