### ISSUE TITLE
Please add example of excluding multiple IP's

### ISSUE THREAD

**Issue by mabushey** [allinurl/goaccess#284]
I added three IP's to an exclude-ip line, but none were excluded. The changelog of .8.2 lists "  - Added the ability to ignore multiple IPv4/v6 and IP ranges.", but nowhere does it say the format. I've figured out that a comma separated list is not valid.

**Comment by mabushey** [comment]
Does not work:
exclude-ip 1.2.3.4 1.2.3.5
exclude-ip 1.2.3.4 ## comment here breaks exclusion

Works:
## New York
exclude 1.2.3.4
## San Francisco
exclude 1.2.3.5

So basically on ip (or range) per line, comments on line not allowed.

**Comment by allinurl** [comment]
There are some examples in the [config file](https://github.com/allinurl/goaccess/blob/master/config/goaccess.conf#L250)

I can add them to the man page as well.

**Comment by allinurl** [comment]
Added examples of excluding multiple IP's to the man page + website. Thanks!
