### ISSUE TITLE
CSS/JS files getting grouped w/ regular pages if they have query string

### ISSUE THREAD

**Issue by Brade** [allinurl/goaccess#285]
Just what the tile says. If a URL has a form like http://whatever.com/styles.css?ver=3
it gets grouped in "Requested files (Pages-URL)" rather than "Requested static files (e.g., png, js, css, etc)"

**Comment by Brade** [comment]
Also, font files ending in .woff are getting grouped w/ normal pages too, regardless of query string.

**Comment by allinurl** [comment]
I'll look into static files that contain a query string.

As far as .woff or .svg, it should be grouping them under static files, what version are you running? If you run it against the line below, does it get it right?

    192.168.1.10 - - [27/Aug/2015:18:57:56 -0500] "GET /fonts/fontawesome-webfont.woff HTTP/1.1" 304 239 "-" "Mozilla/5.0 (X11; Linux x86_64) (KHTML, like Gecko) Chrome/44.0.2403.130 Safari/537.36"

**Comment by Brade** [comment]
Using version 0.6 which is the one that installs w/ apt in Ubuntu 14.04

**Comment by allinurl** [comment]
This was fixed on a previous version. I'd recommend installing the latest version, using either the [debian/ubuntu repo](https://github.com/allinurl/goaccess#official-goaccess-debian--ubuntu-repository) or build from [source](https://github.com/allinurl/goaccess#installation).

**Comment by Brade** [comment]
Thanks. Just curious, why is it so tough to update the actual standard Ubuntu release? (Granted, this is a problem for a bunch of projects, not just yours.)

**Comment by allinurl** [comment]
Great question and one that I'm not sure. I think it depends a lot on the maintainer of the package. Someone asked a similar question in [here](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=739719).

**Comment by Brade** [comment]
I should've guessed: a bureaucratic roadblock. Thanks for that link!

**Comment by allinurl** [comment]
Added the ability to parse static files containing a query string. Disabled by default. Can be enabled with `--all-static-files`.

It will be pushed out in the upcoming version.

**Comment by szepeviktor** [comment]
@allinurl with v1.0.2 I still get these static files with query
`/tartalom/themes/mutoberles/bower_components/font-awesome/fonts/fontawesome-webfont.woff?v=4.6.1`

**Comment by szepeviktor** [comment]
@allinurl Could you reopen this one?

**Comment by allinurl** [comment]
@szepeviktor I just ran the following - v1.0.2:

    goaccess -f sample.log --log-format=COMBINED

and I get

![2016-09-13-132104_900x95_scrot](https://cloud.githubusercontent.com/assets/5005367/18486059/3534b9d4-79b5-11e6-9c93-4feae3ac5fd1.png)

Which looks right to me. If you need these two requests under static files, you will need to use `--all-static-files`

**Comment by szepeviktor** [comment]
Excuse me.
I thought *the opposite*.
By adding `all-static-files` static files went under *Static Requests*.

Thank you.

**Comment by allinurl** [comment]
@szepeviktor No worries :) glad that worked out.
