### ISSUE TITLE
Possibility of using glob/regexp to ignore hosts

### ISSUE THREAD

**Issue by styygeli** [allinurl/goaccess#29]
Would be really nice to use either method to move internal hosts/loadbalancers to the ignore list.

something like -e 10._,172._

best would be of course to be able to use CIDR notation:

for example
-e 10/8,172.16/12,192.168/16

**Comment by vanko69** [comment]
I want to exclude an IP and a range of IPs. Can I do it and how? I tried with IP1-IP2,IP3. With multiple -e flags but no luck. I am using version 0.9.

**Comment by allinurl** [comment]
This is possible by using multiple `-e` or `--exclude-ip`:

    goaccess -f access.log --exclude-ip 127.0.0.1 --exclude-ip 192.168.0.1-192.168.0.100 --exclude-ip ::1 --exclude-ip 0:0:0:0:0:ffff:808:804-0:0:0:0:0:ffff:808:808
