### ISSUE TITLE
http://tar.goaccess.io/ contains obsolete tarballs

### ISSUE THREAD

**Issue by cicku** [allinurl/goaccess#290]
ATM the layout:

goaccess-0.9.1.tar.gz	27-Aug-2015 19:24	235K
goaccess-0.9.2.tar.gz	27-Aug-2015 19:24	236K
goaccess-0.9.3.tar.gz	27-Aug-2015 19:24	245K
goaccess-0.9.tar.gz	        27-Aug-2015 19:24	208K
goaccess-0.11.tar.gz	27-Aug-2015 19:24	104K
goaccess-0.12.tar.gz	27-Aug-2015 19:24	104K

However, this doesn't conform to proper versioning rules, 0.11/0.12 > 0.9. And this causes the tracking failed:

https://release-monitoring.org/project/1222/

Can you remove these 2 tarballs? Also they are pretty old I guess(wrong version of 0.1.1 and 0.1.2, right?).

**Comment by allinurl** [comment]
Renamed those. Should be fine now. Thanks

**Comment by cicku** [comment]
Thanks.
