### ISSUE TITLE
percentages don't sum up to 100%

### ISSUE THREAD

**Issue by metionina** [allinurl/goaccess#292]
I'm trying out goaccess for the first time and I've noticed that some modules showing percentages don't sum up to 100% when passing the -e option to goaccess. The full command I'm using is 

zcat --stdout -f /var/log/nginx/access.log* | ag "my_website" | goaccess -e 192.168.1.1

Is this the intended behaviour? If so, what's the right way to filter away visits coming from 192.168.1.1?

**Comment by allinurl** [comment]
That's correct, ignoring ips will still calculate the percentage based off the total number of parsed requests. Should the percentage be taken from the total number of valid requests?

**Comment by metionina** [comment]
Thanks. Yes, I'd like to completely exclude my visits from the percentage calculation. 
So if I have 100 visits but 50 are from me, I'd like to exclude mine and have the 50 remaining visits calculated as 100% of the visits.

**Comment by allinurl** [comment]
This has been changed/fixed. Now it should display the percentages based of **valid** requests. Please rebase from [master](http://goaccess.io/download#build) to test it out. It will be pushed out in this coming week release. Thanks!

**Comment by metionina** [comment]
Thank you! I'll try it out!

**Comment by jrun** [comment]
I'm running a build of master and bumping into this issue when using the HTML output format.

As best I can tell this will fix the issue:
jrun@090ea80917dbb9150afa952dab882934a858b3b6

Maybe a missing bit?

**Comment by allinurl** [comment]
@jrun You are right, I missed that one. I merged your commit.

Thanks for reporting it!
