### ISSUE TITLE
add an option to separate 1000s

### ISSUE THREAD

**Issue by ultratip** [allinurl/goaccess#294]
Hi
could you please add an option to separate 1000s with a comma in the output (HTML)
for large traffic sites, I find it more readable "at-a-first-glance".

e.g. 
Total Requests: 1185736
vs
Total Requests: 1,185,736

many thanks

-Duro

**Comment by allinurl** [comment]
This was implemented in a previous version. See [current report](http://goaccess.io/goaccess_html_report.html?1410179475). 

What version are you using?

**Comment by ultratip** [comment]
mac os x

installed via
brew install --HEAD goaccess

all parsing works well and HTML reports are generated, but
still shows the non separated 1000s

is there a switch I need to enable in the config file ?

many thanks

[logserver.thinkwrap.net:logserver]/usr>find /usr/ -name '*goaccess*' -ls
3331298        8 lrwxr-xr-x    1 logserver        admin                  36 Sep  2 10:01 /usr/local/bin/goaccess -> ../Cellar/goaccess/HEAD/bin/goaccess
2257937        0 drwxr-xr-x    4 logserver        admin                 136 Sep  2 10:01 /usr/local/Cellar/goaccess
3331292      336 -r-xr-xr-x    1 logserver        admin              171076 Sep  2 10:01 /usr/local/Cellar/goaccess/HEAD/bin/goaccess
3331291       32 -rw-r--r--    1 logserver        admin               13123 Sep  2 10:01 /usr/local/Cellar/goaccess/HEAD/etc/goaccess.conf
3331293       48 -rw-r--r--    1 logserver        admin               22002 Sep  2 10:01 /usr/local/Cellar/goaccess/HEAD/share/man/man1/goaccess.1
3331297        8 lrwxr-xr-x    1 logserver        admin                  41 Sep  2 10:01 /usr/local/etc/goaccess.conf -> ../Cellar/goaccess/HEAD/etc/goaccess.conf
2625156        8 -rw-r--r--    1 logserver        admin                1200 Jul  8 15:56 /usr/local/Library/Formula/goaccess.rb
3331300        8 lrwxr-xr-x    1 logserver        admin                  26 Sep  2 10:01 /usr/local/Library/LinkedKegs/goaccess -> ../../Cellar/goaccess/HEAD
3331301        8 lrwxr-xr-x    1 logserver        admin                  23 Sep  2 10:01 /usr/local/opt/goaccess -> ../Cellar/goaccess/HEAD
3331299        8 lrwxr-xr-x    1 logserver        admin                  55 Sep  2 10:01 /usr/local/share/man/man1/goaccess.1 -> ../../../Cellar/goaccess/HEAD/share/man/man1/goaccess.1

![image](https://cloud.githubusercontent.com/assets/13869275/9633291/0ddcc36a-515a-11e5-9930-9614d45736f9.png)

**Comment by allinurl** [comment]
The formatting is done through `LC_NUMERIC`. What output do you get after running: `$ locale`?

You can try changing/setting the env variable for LC_NUMERIC. 

    export LC_NUMERIC="en_US.UTF-8"

use `locale -a` to list the locales available on your system.

**Comment by ultratip** [comment]
excellent, thanks
that did it !
-Duro

**Comment by allinurl** [comment]
Great! You may want to edit `/etc/profile` and add `export LC_NUMERIC="en_US.UTF-8"` so it's for every session.
