### ISSUE TITLE
ELB Managers timing out.

### ISSUE THREAD

**Issue by mjnovice** [allinurl/goaccess#298]
ELB managers timing out ( Gateway Timeout 504 ).
Seeing the logs
[MySQL] 2015/09/11 11:51:50 packets.go:32: unexpected EOF
[MySQL] 2015/09/11 11:51:50 connection.go:108: Invalid Connection
[MySQL] 2015/09/11 11:51:55 packets.go:32: unexpected EOF
[MySQL] 2015/09/11 11:51:55 connection.go:108: Invalid Connection
[MySQL] 2015/09/11 11:52:00 packets.go:32: unexpected EOF
[MySQL] 2015/09/11 11:52:00 connection.go:108: Invalid Connection
[MySQL] 2015/09/11 11:52:05 packets.go:32: unexpected EOF
[MySQL] 2015/09/11 11:52:05 connection.go:108: Invalid Connection
[MySQL] 2015/09/11 11:52:10 packets.go:32: unexpected EOF
[MySQL] 2015/09/11 11:52:10 connection.go:108: Invalid Connection
[MySQL] 2015/09/11 11:52:15 packets.go:32: unexpected EOF
[MySQL] 2015/09/11 11:52:15 connection.go:108: Invalid Connection
[MySQL] 2015/09/11 11:52:20 packets.go:32: unexpected EOF
[MySQL] 2015/09/11 11:52:20 connection.go:108: Invalid Connection
[MySQL] 2015/09/11 11:52:25 packets.go:32: unexpected EOF
[MySQL] 2015/09/11 11:52:25 connection.go:108: Invalid Connection
[MySQL] 2015/09/11 11:52:30 packets.go:32: unexpected EOF
[MySQL] 2015/09/11 11:52:30 connection.go:108: Invalid Connection
[MySQL] 2015/09/11 11:52:35 packets.go:32: unexpected EOF
[MySQL] 2015/09/11 11:52:35 connection.go:108: Invalid Connection
[MySQL] 2015/09/11 11:52:40 packets.go:32: unexpected EOF
[MySQL] 2015/09/11 11:52:40 connection.go:108: Invalid Connection
[MySQL] 2015/09/11 11:52:45 packets.go:32: unexpected EOF
[MySQL] 2015/09/11 11:52:45 connection.go:108: Invalid Connection
[MySQL] 2015/09/11 11:52:50 packets.go:32: unexpected EOF
[MySQL] 2015/09/11 11:52:50 connection.go:108: Invalid Connection
[MySQL] 2015/09/11 11:52:55 packets.go:32: unexpected EOF
[MySQL] 2015/09/11 11:52:55 connection.go:108: Invalid Connection
[MySQL] 2015/09/11 11:53:00 packets.go:32: unexpected EOF
[MySQL] 2015/09/11 11:53:00 connection.go:108: Invalid Connection
[MySQL] 2015/09/11 11:53:05 packets.go:32: unexpected EOF
[MySQL] 2015/09/11 11:53:05 connection.go:108: Invalid Connection
[MySQL] 2015/09/11 11:53:10 packets.go:32: unexpected EOF
[MySQL] 2015/09/11 11:53:10 connection.go:108: Invalid Connection
[MySQL] 2015/09/11 11:53:15 packets.go:32: unexpected EOF
[MySQL] 2015/09/11 11:53:15 connection.go:108: Invalid Connection
[MySQL] 2015/09/11 11:53:20 packets.go:32: unexpected EOF
[MySQL] 2015/09/11 11:53:20 connection.go:108: Invalid Connection

The MySQL pipe connection seems to be broken.

**Comment by allinurl** [comment]
I'm not sure how is this related to goaccess?

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
