### ISSUE TITLE
Referrers URLs "disabled by default": no documentation on how to enable

### ISSUE THREAD

**Issue by RickyRomero** [allinurl/goaccess#304]
I'm trying to figure out how to enable this option:
`Referrers URLs: If the host in question accessed the site via another resource, or was linked/diverted to you from another host, the URL they were referred from will be provided here in this panel. (disabled by default)`

There's no documentation anywhere. How do I turn this on?

**Comment by allinurl** [comment]
By default, the config file specifies `ignore-panel REFERRERS`. You can comment [this line](https://github.com/allinurl/goaccess/blob/master/config/goaccess.conf#L340) out and that should enable it.

I'll add this to the man page. Thanks for the heads up.

**Comment by RickyRomero** [comment]
That worked, thanks for the pointer. :+1:

**Comment by szepeviktor** [comment]
@allinurl It would be nice to have `--no-ignore-panel` to enable a panel per execution.

**Comment by allinurl** [comment]
@szepeviktor `enable-panel` should do that.

**Comment by szepeviktor** [comment]
> Enable parsing/displaying the given panel.

Thank you!
