### ISSUE TITLE
Trouble with Custom Logs

### ISSUE THREAD

**Issue by srguglielmo** [allinurl/goaccess#305]
Not sure if making an issue is the proper place to get help; I didn't see a mailing list or IRC channel on the website.

My logs are in the format:
```
$time_iso8601 $remote_addr $server_name $status $scheme "$request_method $request_uri" "$http_user_agent" "$http_referer"

2015-09-27T10:31:32-04:00 1.2.3.4 domain.com 200 https "GET /" "Mozilla/5.0 (X11; Linux x86_64; rv:42.0) Gecko/20100101 Firefox/42.0" "-"
```

I'm using the following config options
```
time-format %H:%M:%S
date-format %Y-%m-%d
log-format %dT%t%^ %h %^ %s %H "%m %U" "%u" "%R"
```

However, when I run goaccess, I get:
```
GoAccess - version 0.9.4 - Sep  7 2015 19:28:23
Config file: /etc/goaccess.conf

Fatal error has occurred
Error occured at: src/goaccess.c - main - 1033
Nothing valid to process.
```

**Comment by allinurl** [comment]
The following should work with your format:

    log-format %dT%t-%^ %h %^ %s %^ "%m %U" "%u" "%R"
    date-format %Y-%m-%d
    time-format %H:%M:%S

Feel free to post any issues/feedback you may have in here :)

**Comment by allinurl** [comment]
BTW, since you don't have an HTTP request protocol in your logs, you may want to set `http-protocol` to `false` in your config file to avoid outputting `---`.

**Comment by srguglielmo** [comment]
It worked, thank you very much!

I'm planning to modify my logs to add more information (response size, response time, ). I thought the request protocol was http/https? I guess %H is referring to HTTP/1.1 or HTTP/2?

**Comment by allinurl** [comment]
Glad that worked :)

That's right, `%H` is referring to the request protocol. Currently it does not report the URL scheme.

**Comment by qinming23** [comment]
Hello,I also use the same config same as srguglielmo's config.but it doesn't work。the log config is:
log_format  main  '$time_iso8601 $remote_addr $server_name $status $scheme "$request_method $request_uri" "$http_user_agent" "$http_referer"';
the goaccess config in ~/.goaccessrc。
#  vim ~/.goaccessrc
log-format %dT%t-%^ %h %^ %s %^ "%m %U" "%u" "%R"
date-format %Y-%m-%d
time-format %H:%M:%S
My system is CentOS 6.5 x86
My software version is goaccess-0.9.3
When I use command :# goaccess -f /opt/nginx/access4.log -p ~/.goaccessrc
Total Requests  10 Unique Visitors 0 Referrers    0 Log Size  1.57 KiB
  Failed Requests 10 Unique Files    0 Unique 404   0 Bandwidth 0.0   B
  Generation Time 0  Excl. IP Hits   0 Static Files 0 Log File  /opt/nginx/access4.log
Pls Help me.

**Comment by qinming23** [comment]
nginx log like this :  2016-03-10T16:01:45+08:00 101.81.86.177 www.xxxx.com 200 http "GET /Online.html" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:44.0) Gecko/20100101 Firefox/44.0" "http://www.xxxx.com/course.html"

**Comment by qinming23** [comment]
Hi,allinurl
       it worked,thanks for your help。I want add two log_format parameter on nginx,it's $uid_got$uid_set and $http_host replace $server_name. which two goaccess config parameter can be use?If havn't any config parameter can be use,then I must use %^ replace these two goaccess config parameter?

**Comment by allinurl** [comment]
@qinming23 goaccess does not handle at the moment `$uid_got` `$uid_set`. You can use `$http_host` if that serves as your virtualhost. 

Yes, you have to use `%^` to ignore the field(s). Please take a look at the [man page](http://dev.goaccess.io/man#custom-log) for more details on the custom log format.

**Comment by qinming23** [comment]
Thank you

**Comment by leadsec7766** [comment]
My Nginx logs are in the format:

> log_format  main  '$remote_addr - $remote_user [$time_iso8601] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"'
                      '"$upstream_cache_status"'
                      '"$cookie_SHAREJSESSIONID"'
                      ' "$cookie_COOKIE_TAG01"'
                      ' "$cookie_COOKIE_TAG02"'

I'm using the following config options


> time-format %H:%M:%S
> date-format %d/%b/%Y
> log-format %h - %^[%^] "%r" %s %b "%R" "%u" "%^" "%^" "%^" "%^" "%^"

nginx log like this :

> 106.111.179.214 - - [2016-05-13T12:17:28+08:00] "GET /images/hy/register/load.gif HTTP/1.1" 404 4981 "https://www.xxx.com/css/index/index.css" "Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 BIDUBrowser/7.6 Safari/537.36" "-""-""f96705ff-0769-4a0c-a637-78a080c5e290" "06032fa3-6f2b-4803-a3de-950aa63b1587" "-"


But not work，pls help me! ths a lot!

> [root@localhost goaccess-0.9.8]# /usr/local/bin/goaccess -f /root/logs/access.log
> 
> GoAccess - version 0.9.8 - May 13 2016 10:51:54
> Config file: /usr/local/etc/goaccess.conf
> 
> Fatal error has occurred
> Error occured at: src/goaccess.c - main - 1017
> Nothing valid to process. Verify your date/time/log format.

**Comment by leadsec7766** [comment]
Attempt to modify，also error

> log-format %h - %^[%dT%t+%^] "%r" %s %b "%R" "%u" "%^" "%^" "%^" "%^" "%^"

**Comment by leadsec7766** [comment]
change config

> date-format %Y-%m-%d

problem solved

**Comment by allinurl** [comment]
@leadsec7766  The following should work too (bit shorter):

```
log-format %h %^[%dT%t+%^] "%r" %s %b "%R" "%u"%^
date-format %Y-%m-%d
time-format %T
```
