### ISSUE TITLE
Comments in goaccess.conf and variable names differ (dash/underscore)

### ISSUE THREAD

**Issue by fwolfst** [allinurl/goaccess#306]
Hi,

Installed goaccess from official ("goaccess", not canonical) ubuntu repository.

    goaccess --version
    GoAccess - 0.9.4.

`/etc/goaccess.conf` states following:

    # The date_format variable followed by a space, specifies
    # ....
    # date-format %d/%b/%Y

Is it on purpose that the comment refers to a `date_format` (underscore `_`) variable, where the configuration file lists the `date-format` (dash `-`) key?

Same for `log_format`. Noticed while wanting to jump in vim to word under cursor ( `*`) to edit the value.

**Comment by allinurl** [comment]
Good question. Earlier versions would use underscore `_`, then it changed to a dash `-`. For backwards compatibility, you can use both. 

I've updated the config file. Thanks!
