### ISSUE TITLE
Nothing valid to process: something wrong with my logformat?

### ISSUE THREAD

**Issue by ArondeParon** [allinurl/goaccess#308]
Hi,

I am trying the following line with these settings, but keep receiving the "Nothing valid to process" error. I am probably overlooking something.

**Settings:**

    time-format %T
    date-format %d/%b/%Y
    log-format %v %h %l %u %t "%r" %>s %b "%{Referer}i" "%{User-agent}i"

**Log excerpt:**

    hostname.com 66.249.64.111 - - [02/Oct/2015:23:32:07 +0200] "GET /some/obscured/path.jpg HTTP/1.1" 200 31476 "-" "Googlebot-Image/1.0"

Would really appreciate some help. Thanks in advance!

**Comment by allinurl** [comment]
It looks like it's a "NCSA Combined Log Format with Virtual Host". The following should work:

    log-format %^ %h %^[%d:%t %^] "%r" %s %b "%R" "%u"
    date-format %d/%b/%Y
    time-format %H:%M:%S

Let me know how it goes!

**Comment by ArondeParon** [comment]
Thanks! I managed to get it working now, with a slight tweak:

    log-format %v %h %^[%d:%t %^] "%r" %s %b "%R" "%u"
