### ISSUE TITLE
Configuring and compiling GoAccess on FreeBSD 10.1

### ISSUE THREAD

**Issue by dorin21id** [allinurl/goaccess#309]
Hello guys. I am running Freebsd 10.1. I am trying to compile Goaccess with geoIp support.
When I do the configure with geoIP I get:

    checking for GeoIP_new in -lGeoIP... no
    configure: error: *** Missing development files for the GeoIP library

I have the geoip port installed (net/GeoIP)

    root@e5-2620v3x2:/tmp/goaccess-0.9.4 # /usr/local/bin/geoiplookup -f /usr/local/share/GeoIP/GeoLiteCity.dat 8.8.8.8
    GeoIP City Edition, Rev 1: US, CA, California, Mountain View, 94040, 37.386002, -122.083801, 807, 650

Can someone please tell me how to make it work with geoip ?
If I install the goaccess port from freebsd it's version 0.8.5 and it doesn't have geoip support

**Comment by allinurl** [comment]
Try the following:

    # pkg_add -r GeoIP
    # export LDFLAGS=-L/usr/local/lib
    # ./configure --enable-geoip --enable-utf8
    # make
    # make install

**Comment by allinurl** [comment]
Just configured and compiled in FreeBSD 10.1 and the steps above worked fine.

**Comment by dorin21id** [comment]
Damn it. Still the same :( 
[root@e5-2620v3x2 /tmp/goaccess-0.9.4]# /usr/local/bin/geoipupdate.sh
Fetching GeoIP.dat and GeoIPv6.dat...
/usr/local/share/GeoIP/GeoIPupdate.4KwoRT/GeoI100% of  441 kB  840 kBps 00m01s
/usr/local/share/GeoIP/GeoIPupdate.pPQiNn/GeoI100% of  712 kB  836 kBps 00m01s
[root@e5-2620v3x2 /tmp/goaccess-0.9.4]# set env LDFLAGS -L/usr/local/lib
[root@e5-2620v3x2 /tmp/goaccess-0.9.4]# ./configure --enable-geoip
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... ./install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... nawk
checking whether make sets $(MAKE)... yes
checking for gcc... no
checking for cc... cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking for style of include used by make... GNU
checking dependency style of cc... gcc3
checking whether cc understands -c and -o together... yes
checking for pthread_create in -lpthread... yes
checking build system type... x86_64-unknown-freebsd10.1
checking host system type... x86_64-unknown-freebsd10.1
checking whether to build with rdynamic for GNU ld... yes
checking for GeoIP_new in -lGeoIP... no
configure: error: *** Missing development files for the GeoIP library
[root@e5-2620v3x2 /tmp/goaccess-0.9.4]#

**Comment by allinurl** [comment]
Make sure is `setenv LDFLAGS -L/usr/local/lib` and not `set env...`

**Comment by dorin21id** [comment]
It is working now. THANK YOU VERY VERY MUCH !

**Comment by allinurl** [comment]
Glad that worked :)
