### ISSUE TITLE
Consolidated report

### ISSUE THREAD

**Issue by hadisajj2** [allinurl/goaccess#313]
I have a few ngingx log files that I would like to analyze in one report. Is there a way to have goaccess read a few log files in out shot? I found this command on stackoverflow but it didn't do the trick:

zcat access.log.*.gz | goaccess -a -s -b

**Comment by allinurl** [comment]
This seems to be the same question you posted previously #312. The following will parse all `access.log*` files

    sudo sh -c 'zcat -f access.log* | goaccess -a > report.html'

Also, note that -s is not a valid flag, unless you are running a very old version of goaccess.

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
