### ISSUE TITLE
What counts as a "hit"?

### ISSUE THREAD

**Issue by ryanfox** [allinurl/goaccess#314]
Apologies if this is documented somewhere, but I can't seem to find it: what exactly counts as a hit?  Is it a single request?

E.g. if I see a line indicating 1 visitor, 10 hits, is that potentially 1 page with 10 requests made?  Or 10 separate pages requested?

**Comment by allinurl** [comment]
Good question. A hit is a request (line in your log), i.e., 10 requests = 10 hits. An HTTP request with the same IP, date, and the same user agent are considered a unique visit.

For instance, one user can request 100 files = 100 hits, but only 1 visitor (as long as the 100 requests have the same IP, date, and user agent).

**Comment by ryanfox** [comment]
Thanks.  Is there a way to filter hits, e.g. "only requests for *.html" or "only requests for *.jpg"?

**Comment by allinurl** [comment]
You could pre-filter the data (e.g., grep, awk, etc ) and then pipe it to goaccess, e.g.,

    grep -i '*.html' /var/log/apache2/access.log | goaccess

**Comment by allinurl** [comment]
BTW, I updated the man page ([web](http://goaccess.io/man#notes)/term) with this question. Thanks for pointing that out.

Closing this. Feel free to reopen the issue if needed.

**Comment by ryanfox** [comment]
Of course.  Thank you.
