### ISSUE TITLE
Troubles with nginx custom log

### ISSUE THREAD

**Issue by vitich** [allinurl/goaccess#317]
goaccess 0.9.4

    [15/Oct/2015:03:19:12 +0000] 195.58.102.191 - -  "www.example.com" "GET /uk/news/3939842?0.7586556280842541 HTTP/1.1" "200" 946 [0.100 s]  "https://www.example.com/uk/news/" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:40.0) Gecko/20100101 Firefox/40.0"

    time-format %H:%M:%S
    date-format %d/%b/%Y:%H:%M:%S %z
    log-format [%d/%b/%Y:%H:%M:%S %z] %h %^ %^ "%^" "%m %U %H" "%s" [%b]  "%R" "%u"

Also I`ve tried

    log-format [%d:%t] %h %^ %^ "%^" "%m %U %H" "%s" [%b]  "%R" "%u"

Fatal error has occurred
Error occured at: src/goaccess.c - main - 1033
Nothing valid to process.

Help me please with log format
Thank You!

**Comment by allinurl** [comment]
The following works (note you have some extra whitespaces in between some of your fields, e.g., `[0.100 s]  "`):

    time-format %H:%M:%S
    date-format %d/%b/%Y
    log-format [%d:%t %^] %h %^"%^" "%r" "%s" %b [%T %^"%R" "%u"

**Comment by vitich** [comment]
Thank you very much!

**Comment by allinurl** [comment]
Great, closing this.

**Comment by jitenjha11** [comment]
Getting Error message
zcat -f /var/log/apache2/access.log* | goaccess -a -o report.html

GoAccess - version 0.9.4 - Feb  7 2016 10:13:30
Config file: /etc/goaccess.conf

Fatal error has occurred
Error occured at: src/goaccess.c - main - 1033
Nothing valid to process.



sudo -i zcat -f access.log | goaccess -a > report.html
gzip: access.log.gz: No such file or directory

GoAccess - version 0.9.4 - Feb  7 2016 10:13:30
Config file: /etc/goaccess.conf

Fatal error has occurred
Error occured at: src/goaccess.c - main - 1033
Nothing valid to process.

Please send me the command which I want to run it I am not getting its time format and other processes can any share command or changes

**Comment by allinurl** [comment]
@jitenjha11 Please update to the [latest](https://github.com/allinurl/goaccess#build-from-release) version of goaccess  and let me know if that solves the issue.
