### ISSUE TITLE
goaccess considers HTTP/2 protocol to be invalid

### ISSUE THREAD

**Issue by TheDecryptor** [allinurl/goaccess#319]
I found this while trying to parse the log files from the h2o server, which uses a format quite similar to the NCSA default

    127.0.0.1 - - [30/Aug/2015:17:59:34 +1000] "GET /favicon.ico HTTP/2" 200 34066 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:43.0) Gecko/20100101 Firefox/43.0"

Using the default NCSA format, any HTTP/2 requests are mangled by this block of code, https://github.com/allinurl/goaccess/blob/8ba3ba8e5cd600cccf027e3e7f897ee66950a455/src/parser.c#L716-L721, causing the entire request to be marked as "-". Replacing "%r" in the format string with "%m %U %H" makes goaccess go down a different codepath, instead failing here https://github.com/allinurl/goaccess/blob/8ba3ba8e5cd600cccf027e3e7f897ee66950a455/src/parser.c#L693-L700 In this case the entire request is considered invalid and ignored.

**Comment by allinurl** [comment]
Thanks for reporting this issue. It has been added and pushed to master. Feel free to build from [dev](http://goaccess.io/download).

It will be pushed out in the upcoming version pretty soon!

**Comment by TheDecryptor** [comment]
Yep, that's fixed it for me, thanks.
