### ISSUE TITLE
Reduce Spaces (`    `) in HTML report generated

### ISSUE THREAD

**Issue by aphorise** [allinurl/goaccess#320]
This is a rather minor request & may be discarded if its a hassel.

I currently count ~ `1``Kbyte` of excessive over-spacing in the generated HTML report.
Can spaces be reduced or every `4`-`space` substituted by a` tab`?

So for example can [`output.c` - `L482...`](https://github.com/allinurl/goaccess/blob/8ba3ba8e5cd600cccf027e3e7f897ee66950a455/src/output.c#L482-L484) :
```
  "    font-size: 100%%;"
  "    -ms-text-size-adjust: 100%%;"
  "    -webkit-text-size-adjust: 100%%;"
```
be adjusted __to__
```
  "\tfont-size: 100%%;"
  "\t-ms-text-size-adjust: 100%%;"
  "\t-webkit-text-size-adjust: 100%%;"
```
?

**Comment by allinurl** [comment]
We could remove all the leading whitespace, or even replace them with `\t` but will make it difficult to make future changes on the css, I think two spaces should be fine. What do you think?

**Comment by aphorise** [comment]
Perfectly sound! - Not even that huge to be frank -  if you are more comfortable in terms of readability I'd even leave it as is.

I'm a bit over-inclined to hard-tabs in many place - so please feel free to ignore :-D... what about placing a hard-tab character code `0x09` per set of spaces? - putting the tab in the string?

**Comment by aphorise** [comment]
Oh I think `tabs` themselves in CSS are an issue? I may have not fully comprehened what may be affected.

**Comment by allinurl** [comment]
Just pushed a [commit](https://github.com/allinurl/goaccess/commit/2777918afc2f550a30408b7ea4bda01391708d21) to reduce the leading whitespace. It is now to down two spaces. 

Mainly concerned with the readability of the actual `output.c` when it comes to changing those styles.

**Comment by aphorise** [comment]
Great! - thank you once again :+1: :star2:
