### ISSUE TITLE
Can't access to your website from one of the UK ISPs

### ISSUE THREAD

**Issue by timucingelici** [allinurl/goaccess#324]
Your website is up but I can't access it from the following subnet.

109.155.152.0/24

**Comment by allinurl** [comment]
Interesting... is it just timing out? I just cleared some stuff on the firewall, can you please try again?

**Comment by timucingelici** [comment]
Nope, still same.

It looks like the server dropping all the requests from my IP address.

```
tim$ ping goaccess.io
PING goaccess.io (63.231.229.217): 56 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1
Request timeout for icmp_seq 2
```

```
tim$ traceroute goaccess.io
traceroute to goaccess.io (63.231.229.217), 64 hops max, 52 byte packets
 1  192.168.2.1 (192.168.2.1)  1.245 ms  0.884 ms  0.763 ms
 2  192.168.1.254 (192.168.1.254)  2.083 ms  1.753 ms  1.653 ms
 3  * * *
 4  * * *
 5  31.55.185.180 (31.55.185.180)  11.736 ms  7.875 ms  7.668 ms
 6  195.99.127.140 (195.99.127.140)  7.925 ms  8.111 ms  7.807 ms
 7  195.99.127.25 (195.99.127.25)  9.420 ms  8.980 ms  9.985 ms
 8  166-49-211-236.eu.bt.net (166.49.211.236)  8.393 ms
    166-49-211-238.eu.bt.net (166.49.211.238)  8.407 ms  7.889 ms
 9  ixp1-xe-1-0-0-0.us-nyc.eu.bt.net (166.49.208.41)  73.930 ms
    166-49-208-144.eu.bt.net (166.49.208.144)  74.003 ms
    ixp1-xe-1-0-0-0.us-nyc.eu.bt.net (166.49.208.41)  74.181 ms
10  nyc2-brdr-01.inet.qwest.net (63.146.27.193)  75.515 ms  73.719 ms  75.538 ms
11  * * *
12  * * *
13  * * *
14  * * *
^C
```

**Comment by allinurl** [comment]
Strange. Can you try the [development](http://dev.goaccess.io/) copy of the site?

**Comment by timucingelici** [comment]
Nope, no luck again but figured something else. It seems I am not blocked by your server but your provider since I also can't access to 207.109.3.78 (the 11th hop on the traceroute output above)

I've sent an email to them and I'll update this if I hear anything.

Sorry for taking your time for a problem that's not there.

**Comment by allinurl** [comment]
No problem, thanks for letting me know and glad to hear is not a server issue. BTW, does it work if you open it through your phone (assuming a different provider). You may be able to access the site through a [proxy](https://www.google.com/search?q=free+proxy).

Closing this, feel free to post back if you hear anything from the ISP.
