### ISSUE TITLE
GoAccess 0.9.5 crashed by Signal 11

### ISSUE THREAD

**Issue by oscartrollheden** [allinurl/goaccess#326]
==27800== GoAccess 0.9.5 crashed by Signal 11
==27800==
==27800== VALUES AT CRASH POINT
==27800==
==27800== Line number: 236
==27800== Offset: 2
==27800== Invalid data: 160
==27800== Piping: 0
==27800== Response size: 0 bytes
==27800==
==27800== STACK TRACE:
==27800==
==27800== 0 goaccess(sigsegv_handler+0x168) [0x408408]
==27800== 1 /lib/x86_64-linux-gnu/libpthread.so.0(+0x10340) [0x7f07c4025340]
==27800== 2 /lib/x86_64-linux-gnu/libc.so.6(+0x140d54) [0x7f07c3d90d54]
==27800== 3 goaccess(str2enum+0x3c) [0x40761c]
==27800== 4 goaccess(ignore_panel+0x28) [0x414528]
==27800== 5 goaccess() [0x40c311]
==27800== 6 goaccess() [0x40c981]
==27800== 7 goaccess(main+0xbcf) [0x40602f]
==27800== 8 /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf5) [0x7f07c3c71ec5]
==27800== 9 goaccess() [0x406234]
==27800==

**Comment by allinurl** [comment]
Thanks for reporting this. It seems to be the same as issue #323. 

I have pushed a potential fix for this. Please build from [master](http://goaccess.io/download#build) and let me know if that fixes the issue. Thanks.

**Comment by allinurl** [comment]
Closing since it is a duplicate from #327.

**Comment by allinurl** [comment]
This has been fixed. [v0.9.6](http://goaccess.io/) has been released which includes this fix.
