### ISSUE TITLE
Does goaccess has any feature with pageview count or pageview records?

### ISSUE THREAD

**Issue by coverguy** [allinurl/goaccess#329]
Hi,

Would like to check if GoAccess have any pageview counter or pageview record? 

Need your kind output.

Thanks.

**Comment by allinurl** [comment]
You can pipe data into goaccess which gives you a lot of flexibility in terms of what you want to display, so for page views, i.e., `html`, `htm`, `php`, etc.. within the request, you can do something like this:

    awk '$7~/\.html|\.htm|\.php/' /var/log/apache2/access.log | goaccess

Note, `$7` is the request field for the common and combined log format, (without Virtual Host,) if your log includes Virtual Host, then you probably want to use `$8` instead. You can always check which field you are shooting for:

    tail -10 /var/log/apache2/access.log | awk '{print $8}'

**Comment by coverguy** [comment]
Thanks will be waiting for your latest update implementation in future  :)

**Comment by nilsreineke** [comment]
Hey, when i use the given command to get the pageviews my unique visitors decrease. is that possible? should they not be the same?

**Comment by nilsreineke** [comment]
found something because of speaking urls.
`awk '$8~/\.html|\/\"|\.htm|\.php/' access.log | goaccess`
shows more unique visitors and also close to the desired max but still some missing.

**Comment by allinurl** [comment]
@nilsreineke Can you please provide some concrete numbers about this?

**Comment by nilsreineke** [comment]
@allinurl 
in this case:
```
 Dashboard - Overall Analyzed Requests (14/Sep/2018 - 14/Sep/2018)                                                                                                                                                   

  Total Requests  494449 Unique Visitors  16743 Unique Files 1860 Referrers 0
  Valid Requests  494449 Init. Proc. Time 124s  Static Files 1253 Log Size  153.93 MiB
  Failed Requests 0      Excl. IP Hits    0     Unique 404   292  Bandwidth 128.33 GiB
  Log Source      access.log_2018-09-14
```

vs:

` awk '$8~/\.html|\/\"|\.htm|\.php/' access.log_2018-09-14 | goaccess`
```
 Dashboard - Overall Analyzed Requests (14/Sep/2018 - 14/Sep/2018)                                                                                                                                                   [Active Panel: Visitors]

  Total Requests  32790 Unique Visitors  14291 Unique Files 1402 Referrers 0
  Valid Requests  32790 Init. Proc. Time 8s    Static Files 0    Log Size  0.0   B
  Failed Requests 0     Excl. IP Hits    0     Unique 404   78   Bandwidth 331.10 MiB
  Log Source      STDIN
```

so 16743 unique visitors (standard-mode) vs 14291 unique visitors (in PI or PV mode)

**Comment by allinurl** [comment]
It is certainly possible. Think about for instance, a bot that only fetches for a PNG or JPG without hitting an HTML/PHP document. Or hotlinking images, etc. Thus the decrease on the number of unique visitors.
