### ISSUE TITLE
FreeBSD port is out of date

### ISSUE THREAD

**Issue by en90** [allinurl/goaccess#332]
When installed from FreeBSD ports, I got version 0.8.5.

**Comment by allinurl** [comment]
Thanks for reporting this. You will need to contact the maintainer of the port. You can find the info [here](https://www.freshports.org/sysutils/goaccess/).

BTW, you should be able to compile goaccess from [source](http://goaccess.io/download#installation). The only dependency is [ncurses](http://www.freshports.org/devel/ncurses), which should be fairly easy to install. GeoIP is optional.

**Comment by en90** [comment]
Thanks, I sent an e-mail to the port maintainer.
