### ISSUE TITLE
Support for Virtualmin Apache Log Format??

### ISSUE THREAD

**Issue by CanadianJeff** [allinurl/goaccess#336]
```
$ cat /path/to/httpd.conf | grep "LogFormat"
    LogFormat "%h %l %v %V %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" combined
    LogFormat "%h %l %v %V %u %t \"%r\" %>s %b" common
$ exit
```

**Comment by allinurl** [comment]
Can you please post a few lines from your access log?

**Comment by CanadianJeff** [comment]
the only change is the %v %V which is the virtual hostname

the NCSA Standard is to put the %v in front but for some off reason virtualmin is putting it after the %h

as for the %V I am not sure in the logs its showing the same value from %v

so %v and %V are the same

**Comment by CanadianJeff** [comment]
```
66.249.79.94 - vanlug.bc.ca vanlug.bc.ca - [24/Nov/2015:07:00:18 -0800] "GET / HTTP/1.1" 302 20 "-" "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"
66.249.74.69 - vanlug.bc.ca vanlug.bc.ca - [24/Nov/2015:07:00:20 -0800] "GET / HTTP/1.1" 200 8735 "-" "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"
```

**Comment by allinurl** [comment]
The following should work:

    log-format %h %^ %v %^[%d:%t %^] "%r" %s %b "%R" "%u"
    date-format %d/%b/%Y
    time-format %H:%M:%S

**Comment by CanadianJeff** [comment]
I will try thanks

**Comment by CanadianJeff** [comment]
ok looks like thats working thanks

http://djjeff.yourtrap.com/reports/vanlug.bc.ca_report.html

**Comment by allinurl** [comment]
Looks great :+1: 

Closing this, feel free to reopen if needed.
