### ISSUE TITLE
Struggling to determine what's wrong with my log format

### ISSUE THREAD

**Issue by metasim** [allinurl/goaccess#339]
I'm really excited about the prospect of using this too, but struggling with debugging my format strings. (Any tips on how to get more diagnostics out of the tool are appreciated.)

A sample log line is as follows (note the date is a bit different than most standards)

```
localhost - - [2015/Dec/09:15:45:55 -0500] "GET /core/header/header.controller.js HTTP/1.1" 200 1997 "http://localhost:8883/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36"
```

My `.goaccessrc` is as follows

```
time-format %H:%M:%S 
date-format %Y/%b/%d
log-format %h - - [%d:%t %^] "%r" %s %b "%R" "%u"
```

I've been running the tool like this:

    goaccess -f ./my-access.log -p ~/.goaccessrc

I've tried just about every tweak I can think of (including ignoring the date/time fields) and always get this error:

```
GoAccess - version 0.9.6 - Nov 16 2015 02:12:12
Config file: /Users/sfitch/.goaccessrc

Fatal error has occurred
Error occured at: src/goaccess.c - main - 1021
Nothing valid to process. Verify your date/time/log format.
```

Any help is appreciated.

**Comment by allinurl** [comment]
#264 will address debugging format strings. Hope I can get to this asap.

Regarding your log, it seems your `date/time/log-format` are fine. However, goaccess [requires](http://goaccess.io/man#custom-log) a valid IPv4/6 for `%h`.

**Comment by metasim** [comment]
Thanks so much for the reply. I've also tried

    log-format %v - - [%d:%t %^] "%r" %s %b "%R" "%u"

and

    log-format %^ - - [%d:%t %^] "%r" %s %b "%R" "%u"

and

    log-format %^ %^ %^ [%d:%t %^] "%r" %s %b "%R" "%u"

to no avail.

Look forward to what comes of #264. :-)

**Comment by metasim** [comment]
Ah, maybe this is the issue (from the manual):

> GoAccess requires the following fields:
> * a valid IPv4/6 %h
> * a valid date %d
> * the request %r

**Comment by allinurl** [comment]
Glad that worked.

If no config file is passed, i.e., `-p /path/.goaccessrc` then it tries to open the [global config file](https://github.com/allinurl/goaccess/blob/master/src/settings.c#L83), which is usually located under `%sysconfdir%/goaccess.conf`. Last, it will try to open it under `$HOME/.goaccessrc`.

You can try using `--no-global-config` if you have your config file under `$HOME`.

**Comment by metasim** [comment]
Thanks for the help!

**Comment by softmastx** [comment]
These format doesn't work!

time-format %H:%M:%S
date-format %d/%b/%Y
log-format %h - %^ [%d:%t %^]  "%r" %s %b "%R" "%u" %T "%^"


Here my logs format 

Oct 12 06:43:58 sxxxxxxx kernel: [243836.555018] [UFW BLOCK] IN=eth0 OUT= MAC=04:01:6d:82:ca:01:84:c1:c1:81:09:30:08:00 SRC=177.207.38.166 DST=1$
Oct 12 06:45:46 sxxxxxxx kernel: [243944.230518] [UFW BLOCK] IN=eth0 OUT= MAC=04:01:6d:82:ca:01:84:c1:c1:81:09:30:08:00 SRC=89.163.242.228 DST=1$

What is the correct format should be?


Thanks

**Comment by allinurl** [comment]
@softmastx goaccess parses logs coming out from your web server.

**Comment by houssem-alt** [comment]
Hello , sir
i have problem with my log :

Dec 18 10:06:14 apihost01 domain.com-ext x.x.x.x via x.x.x.x -  18/Dec/2018:10:06:05 +0100 GET 200 /app.php   /api/report/campaigns/354/summary.json /var/www/apiv1/web/app.php 0 cpu:6.82 allocatedmem:4
please help

**Comment by allinurl** [comment]
@houssem-alt Please post only your issue only in one thread. I already posted my question to you on the previous issue. Please describe the fields within your log.
