### ISSUE TITLE
Documentation doesn't explain some acronyms

### ISSUE THREAD

**Issue by mdimarino** [allinurl/goaccess#340]
Hello, documentation doesn't mention what means at config file:

*  BY_BW
*  BY_AVGTS
*  BY_CUMTS
*  BY_MAXTS
*  BY_MTHD

Also, time unit "us" means micro seconds?

**Comment by allinurl** [comment]
Hello,

Thanks for pointing that out. I'll make sure to explain these everywhere is applicable.

`BY_` allows the user to specify the metric or field (if present) when sorting panels on the initial load.

    BY_BW    -> Sort by bandwidth
    BY_AVGTS -> Sort by average time served
    BY_CUMTS -> Sort by cumulative time served
    BY_MAXTS -> Sort by maximum time served
    BY_MTHD  -> Sort by http method
    BY_PROT  -> Sort by http protocol

That's right,  `us` is microseconds, `ms` is milliseconds.
