### ISSUE TITLE
AWS ELB log field been used to calculate Avg.T.S.

### ISSUE THREAD

**Issue by mdimarino** [allinurl/goaccess#342]
Hello, when using AWS Elastic Load Balancing log format which field of log lines is being used to calculate Avg.T.S.?

For example, in the following example we have:

    2015-12-08T23:00:03.503476Z load-balancer 184.72.218.56:65170 10.0.0.5:8080 0.000036 0.003329 0.000051 200 200 0 5097 "GET http://[...] HTTP/1.1" "Mozilla/5.001 (windows; U; NT4.0; en-us) Gecko/25250101" - -

There are 3 time fields (http://docs.aws.amazon.com/ElasticLoadBalancing/latest/DeveloperGuide/access-log-collection.html):
* 5th field request_processing_time ( 0.000036 )
* 6th field backend_processing_time ( 0.003329 )
* 7th field response_processing_time ( 0.000051 )

Which one is being used?

Thanks,
Marcello.

**Comment by allinurl** [comment]
Hello, it uses `request_processing_time`. However, if you need to use a different field, you may change `%T` on your [log-format](https://github.com/allinurl/goaccess/blob/master/config/goaccess.conf#L89).
