### ISSUE TITLE
Can goaccess output two or more output one time?

### ISSUE THREAD

**Issue by gxhllj** [allinurl/goaccess#343]
I want to get html output and csv output  one time.
How can I do it ?
Does goaccess support it?

**Comment by allinurl** [comment]
This is not possible, it uses the standard output to print out a report. However, you should be able to run goaccess twice. What's the use case for this?

**Comment by gxhllj** [comment]
Thanks.
We want to see the result by html, and also want to get the data from csv to analyze by our data analyze server.
@allinurl

**Comment by allinurl** [comment]
If you are using the on-disk storage, you could persist the data and parsing it again with goaccess should be pretty fast if you don't pass a new dataset. This is probably the fastest approach right now without consuming a lot of resources. 

v1.0 is taking a different approach on the HTML output, it parses JSON raw data directly so it might be possible to generate a csv and output that as a blob.

**Comment by gxhllj** [comment]
Thanks. 
Please close.

**Comment by allinurl** [comment]
Added the ability to output multiple formats in one run.

In addition, it standardizes the output per issue #53. For instance,
it now supports the following.

goaccess -f access.log -o /www/file.html
goaccess -f access.log -o /www/file.csv
goaccess -f access.log -o /www/file.json

For backwards compatibility, it still supports the following format: 

goaccess -f access.log > /www/file.html
goaccess -f access.log -o csv > /www/file.csv
goaccess -f access.log -o json > /www/file.json
