### ISSUE TITLE
syslog-ng & common log format

### ISSUE THREAD

**Issue by Vaiper** [allinurl/goaccess#345]
Hi everyone,

i have here an strange logformat, thats a combination from syslog-ng and logger

    Dec 18 11:47:48 HOSTNAME LOGGER-TAG: 123.123.123.123 - - [18/Dec/2015:11:47:46 +0100] "POST /URL/URL/BLA HTTP/1.1" 200 7541 2/2126669

have anyone of you an idea how i can put this in the right format in the goaccess.conf?

Thank you!

Best Regards
Sven

**Comment by allinurl** [comment]
Can you please describe what's the field at the end? `2/2126669`

**Comment by Vaiper** [comment]
Hi,

%T/%D

**Comment by allinurl** [comment]
This should work:

    log-format %^: %^: %^: %h %^[%d:%t %^] "%r" %s %b %^/%D
    date-format %d/%b/%Y
    time-format %H:%M:%S

**Comment by allinurl** [comment]
Closing this. Feel free to reopen if needed.

**Comment by meylisso** [comment]
Please tell me what filter to use for correct display. 10.10.1.13 remote host address nginx . 140.82.121.3 client address

Nov 10 12:11:55 10.10.1.13 nginx: 140.82.121.3 - - [10/Nov/2022:12:11:55 +0000] "GET /favicon.ico HTTP/1.1" 200 741 "https://example.com/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36"

**Comment by allinurl** [comment]
@meylisso 

    goaccess access.log --log-format='%^:%^:%^: %h %^[%d:%t %^] "%r" %s %b "%R" "%u"' --date-format=%d/%b/%Y --time-format=%T --date-spec=min
