### ISSUE TITLE
Apache Combined Log Format Not Working on RHEL 5/6

### ISSUE THREAD

**Issue by urmilvinod** [allinurl/goaccess#348]
Hi - 
I am getting following issue on RHEL 5 and 6.

Error (goacccess -f access_log):
=======================================================
GoAccess - version 0.9.7 - Dec 28 2015 16:48:22
Config file: /usr/local/etc/goaccess.conf

Fatal error has occurred
Error occured at: src/goaccess.c - main - 1062
Nothing valid to process. Verify your date/time/log format.

=======================================================
Configuration:
=======================================================
RHEL 5 and 6: 

    Linux  2.6.18-371.6.1.el5 #1 SMP Tue Feb 18 11:42:11 EST 2014 x86_64 x86_64 x86_64 GNU/Linux

Apache Log Format:

    LogFormat "%h %{X-FORWARDED-FOR}i %l %u %t %D \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\" \"%{COOKIE1}C|%{COOKIE2}C|%{COOKIE3}C\"" combined

GoAccess Config:

    time-format %H:%M:%S
    date-format %d/%b/%Y
    log-format %h %^[%d:%t %^] "%r" %s %b "%R" "%u"

=======================================================
Example Access Log:
=======================================================

    97.97.97.97 98.98.98.98 - - [28/Dec/2015:04:02:07 -0500] 561 "HEAD / HTTP/1.0" 403 - "-" "-" "-|-|-"
    97.97.97.97 98.98.98.98, 99.99.99.99 - - [28/Dec/2015:04:02:08 -0500] 168048 "GET /myapp/homePage.html?site_preference=normal HTTP/1.1" 200 56956 "http://www.google.com/goodle.html" "Mozilla/5.0 (iPad; CPU OS 6_1_3 like Mac OS X) AppleWebKit/536.26 (KHTML, like Gecko) Version/6.0 Mobile/10B329 Safari/8536.25" "-|-|-"
    97.97.97.97 98.98.98.98, 99.99.99.99 - - [28/Dec/2015:04:02:09 -0500] 20558 "GET /myapp/resources/js/lib/jquery/jquery.idle-timer-0.9.100511.js HTTP/1.1" 200 3043 "http://www.google.com/homePage.html?site_preference=normal" "Mozilla/5.0 (iPad; CPU OS 6_1_3 like Mac OS X) AppleWebKit/536.26 (KHTML, like Gecko) Version/6.0 Mobile/10B329 Safari/8536.25" "ouweom10qpwasmxa2139128ns:asdlajdasld|-|-"
    97.97.97.97 98.98.98.98, 99.99.99.99 - - [28/Dec/2015:04:02:10 -0500] 8435 "GET /myapp/resources/js/lib/jquery/jquery.cookie.js HTTP/1.1" 200 702 "http://www.google.com/homePage.html?site_preference=normal" "Mozilla/5.0 (iPad; CPU OS 6_1_3 like Mac OS X) AppleWebKit/536.26 (KHTML, like Gecko) Version/6.0 Mobile/10B329 Safari/8536.25" "ouweom10qpwasmxa2139128ns:asdlajdasld|-|-"
    97.97.97.97 98.98.98.98, 99.99.99.99 - - [28/Dec/2015:04:02:10 -0500] 37570 "GET /myapp/resources/js/lib/jquery/jquery-ui-1.8.16.custom.min.js HTTP/1.1" 200 52950 "http://www.google.com/homePage.html?site_preference=normal" "Mozilla/5.0 (iPad; CPU OS 6_1_3 like Mac OS X) AppleWebKit/536.26 (KHTML, like Gecko) Version/6.0 Mobile/10B329 Safari/8536.25" "ouweom10qpwasmxa2139128ns:asdlajdasld|-|-"
    97.97.97.97 98.98.98.98, 99.99.99.99 - - [28/Dec/2015:04:02:10 -0500] 91548 "GET /myapp/resources/js/lib/jquery/jquery-1.7.2.min.js HTTP/1.1" 200 33639 "http://www.google.com/homePage.html?site_preference=normal" "Mozilla/5.0 (iPad; CPU OS 6_1_3 like Mac OS X) AppleWebKit/536.26 (KHTML, like Gecko) Version/6.0 Mobile/10B329 Safari/8536.25" "ouweom10qpwasmxa2139128ns:asdlajdasld|-|-"
    97.97.97.97 98.98.98.98, 99.99.99.99 - - [28/Dec/2015:04:02:10 -0500] 25155 "GET /myapp/resources/js/lib/jquery/jquery.qtip.min.js HTTP/1.1" 200 14352 "http://www.google.com/homePage.html?site_preference=normal" "Mozilla/5.0 (iPad; CPU OS 6_1_3 like Mac OS X) AppleWebKit/536.26 (KHTML, like Gecko) Version/6.0 Mobile/10B329 Safari/8536.25" "ouweom10qpwasmxa2139128ns:asdlajdasld|-|-"
    97.97.97.97 98.98.98.98, 99.99.99.99 - - [28/Dec/2015:04:02:10 -0500] 10254 "GET /myapp/resources/js/lib/jquery/autoellipsis/jquery.autoellipsis-1.0.10.min.js HTTP/1.1" 200 1673 "http://www.google.com/homePage.html?site_preference=normal" "Mozilla/5.0 (iPad; CPU OS 6_1_3 like Mac OS X) AppleWebKit/536.26 (KHTML, like Gecko) Version/6.0 Mobile/10B329 Safari/8536.25" "ouweom10qpwasmxa2139128ns:asdlajdasld|-|-"
    97.97.97.97 98.98.98.98, 99.99.99.99 - - [28/Dec/2015:04:02:10 -0500] 21517 "GET /myapp/resources/js/lib/jquery/jquery.async.js HTTP/1.1" 200 459 "http://www.google.com/homePage.html?site_preference=normal" "Mozilla/5.0 (iPad; CPU OS 6_1_3 like Mac OS X) AppleWebKit/536.26 (KHTML, like Gecko) Version/6.0 Mobile/10B329 Safari/8536.25" "ouweom10qpwasmxa2139128ns:asdlajdasld|-|-"
    97.97.97.97 98.98.98.98, 99.99.99.99 - - [28/Dec/2015:04:02:10 -0500] 14639 "GET /myapp/resources/js/lib/datatables/jquery.dataTables.min.js HTTP/1.1" 200 21068 "http://www.google.com/homePage.html?site_preference=normal" "Mozilla/5.0 (iPad; CPU OS 6_1_3 like Mac OS X) AppleWebKit/536.26 (KHTML, like Gecko) Version/6.0 Mobile/10B329 Safari/8536.25" "ouweom10qpwasmxa2139128ns:asdlajdasld|-|-"

=======================================================

Appreciate a quick suggestion/fix. Thanks

**Comment by allinurl** [comment]
I see that you have `X-FORWARDED-FOR` which is still not supported. However, I'm working to implement this since it is part of issue #78.

If you just need to grab the `%h` part of it, then you can use:

    %h %^[%d:%t %^] %D "%r" %s %b "%R" "%u"

**Comment by allinurl** [comment]
Closing this. Parsing `X-FORWARDED-FOR` will be implemented in #78
