### ISSUE TITLE
GoAccess ignores too big files in Bandwidth sums

### ISSUE THREAD

**Issue by igittigitthub** [allinurl/goaccess#352]
Hello!

I am using version 0.9.7 but my bandwidth sums are wrong.

nginx access log:
```
xxx.xxx.xxx.xxx - - [10/Jan/2016:16:24:47 +0100] "GET /test.7z HTTP/1.1" 200 3830703706 "https://www.facebook.com/" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36"
xxx.xxx.xxx.xxx - - [07/Jan/2016:18:12:46 +0100] "GET /test.7z HTTP/1.1" 200 16318197 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36"
xxx.xxx.xxx.xxx - - [07/Jan/2016:18:12:54 +0100] "GET /test.7z HTTP/1.1" 206 524288 "-" "facebookexternalhit/1.1 (+http://www.facebook.com/externalhit_uatext.php)"
xxx.xxx.xxx.xxx - - [07/Jan/2016:18:12:56 +0100] "GET /test.7z HTTP/1.1" 206 131072 "-" "facebookexternalhit/1.1"
xxx.xxx.xxx.xxx - - [07/Jan/2016:18:13:01 +0100] "GET /test.7z HTTP/1.1" 200 23019253 "https://www.facebook.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36"
xxx.xxx.xxx.xxx - - [07/Jan/2016:18:23:08 +0100] "GET /test.7z HTTP/1.1" 200 3830703706 "https://www.facebook.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36"
```

GoAccess HTML Output specify the bandwidth of the file (test.7z) as 38,14 MiB. But it should be something like 7344 MiB, right? The size of the file test.7z is 3830703706 bytes (3653 MiB). GoAccess is ignoring such a big file in my log file.

**Comment by allinurl** [comment]
Are you running this on a x86-64 machine? I get the following output:

![2016-01-10-181613_438x262_scrot](https://cloud.githubusercontent.com/assets/5005367/12225039/3735c8ce-b7c6-11e5-96b5-b6550ed8029d.png)

**Comment by igittigitthub** [comment]
No. I am running GoAccess on an ARM device (Banana Pi).

Output of lscpu:
```
Architecture:          armv7l
Byte Order:            Little Endian
CPU(s):                2
On-line CPU(s) list:   0,1
Thread(s) per core:    1
Core(s) per socket:    2
Socket(s):             1
Model name:            ARMv7 Processor rev 4 (v7l)
CPU max MHz:           960,0000
CPU min MHz:           144,0000
```

**Comment by allinurl** [comment]
Sounds like an arch thing. Would you be able to test if your compiler supports uint64_t?

Thanks.

**Comment by igittigitthub** [comment]
```
root@banana:~# gcc -dM -E - < /dev/null | grep -i int64
#define __INT64_C(c) c ## LL
#define __UINT64_C(c) c ## ULL
#define __UINT64_MAX__ 18446744073709551615ULL
#define __INT64_MAX__ 9223372036854775807LL
#define __INT64_TYPE__ long long int
#define __UINT64_TYPE__ long long unsigned int
root@banana:~# gcc --version
gcc (Debian 4.9.2-10) 4.9.2
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

Unfortunately I am not a programmer but maybe this is helpful?
> The ARMv7-M architecture used in mbed microcontrollers is a 32-bit architecture, so standard C pointers are 32-bits.

Source: https://developer.mbed.org/handbook/C-Data-Types

**Comment by allinurl** [comment]
Let me get my hands on a raspberry pi this weekend to test it out and I'll post back. 

In the meantime, if you find any additional details, please post them here. Thanks!

**Comment by allinurl** [comment]
This has been fixed. Please build from [development](http://goaccess.io/download#build) and let me know if that works for you.

It will be pushed out on the upcoming release. Thanks for pointing this out!

**Comment by igittigitthub** [comment]
Now GoAccess HTML Output specify the bandwidth of the file (test.7z) as 7,17 GiB. Thanks a lot! (v0.9.7-40-g8dbffe6)

**Comment by allinurl** [comment]
That's great! Thanks again for reporting it!
