### ISSUE TITLE
HTML Report Layout is broken, static files show up in non-static.

### ISSUE THREAD

**Issue by Csardelacal** [allinurl/goaccess#353]
Since 0.9.6 the HTML report has had some weird layout issues. 

* There are several empty columns in the listing.
* Some .js and .png files show up in the non-static files, some do appear properly

<img width="669" alt="captura de pantalla 2016-01-11 a las 17 04 46" src="https://cloud.githubusercontent.com/assets/1152823/12238673/7bb46536-b885-11e5-91ac-8c7ce7c50be9.png">

**Comment by allinurl** [comment]
Interesting... Could you please post a few sample lines from your access log and the log-format that you are currently using, so I can try to replicate this.

Thanks.

**Comment by allinurl** [comment]
@Csardelacal just following up on my previous post:

> Could you please post a few sample lines from your access log and the log-format that you are currently > using, so I can try to replicate this.

Any other details on how to reproduce this will be great too.

**Comment by Csardelacal** [comment]
Hey! Where can I send the log to. It's a production log and although it's no secret I'd rather not post it publicly. ^^;
Am 15.01.2016 13:54 schrieb "Gerardo O." <notifications@github.com>:@Csardelacal just following up on my previous post:


Could you please post a few sample lines from your access log and the log-format that you are currently > using, so I can try to replicate this.


Any other details on how to reproduce this will be great too.

**Comment by allinurl** [comment]
You can send them to hello [at] goaccess.io.

Thanks!

**Comment by Csardelacal** [comment]
Send them via email. I hope that the command line didn't screw it up and that you got them alright! Also sent you a copy of our config file that we're using. Hope that works for you. 

Thank you kindly for looking into it.

**Comment by allinurl** [comment]
This has been fixed. Please build from [development](http://goaccess.io/download#build) and let me know if that fixes the issue for you.

It will be deployed in the upcoming version. Thanks for reporting it!

**Comment by Csardelacal** [comment]
Since I'm running on Ubuntu and go access is installed with apt-get I would rather look into the configuration issue that you mentioned in the commit message than installing the software anew.

Would that be possible? Thank you so much for looking into it though ^^;

**Comment by allinurl** [comment]
Please try using the [latest config file](https://raw.githubusercontent.com/allinurl/goaccess/master/config/goaccess.conf) (recommended). 

Otherwise you can add the following to your config file:

    http-method true
    http-protocol true

**Comment by Csardelacal** [comment]
I fetched the complete file to avoid any further glitches. Thanks for looking into it!
Goaccess has been one awesome little helper for me.
