### ISSUE TITLE
Custom LogFormat does not work

### ISSUE THREAD

**Issue by llrocha** [allinurl/goaccess#354]
One of my Apache configuration is a little different from the ordinary, I needed to add some values that are not so usual, and also changed the date format, but despite the GoAccess allow setting these parameters the setting you created does not seem to work. Is that a bug or am I doing something wrong?
Below the configuration used in Apache:
**LogFormat "% {% Y% m% d% H% M% S t}% a:% p% P% u \"% r \ "%> s% b% D% X" common**

And one entry of log:
**20160108220001 172.19.248.208 :80 3747992 - "GET /scripts/acao.css HTTP/1.1" 200 3218 316 +**

How should I set the GoAccess to accept this value LogFormat?

**Comment by allinurl** [comment]
goaccess uses `strftime` and `strptime` to validate and convert the date to the appropriate format, as far as I remember, strftime does not have a specifier for the date format you are using. Doing a simple `man strftime` should give you the list of specifiers.

However, it seems you could do some preprocessing to your log before piping it into goaccess.

**Comment by llrocha** [comment]
I followed the Apache documentation on http://httpd.apache.org/docs/2.0/mod/mod_log_config.html#formats
Specifically this line:
% ... {format} t The time, in the form given Beheerder by format, Which shouldnt be in strftime (3) format. (Potentially localized).

If I put an equivalent format "strftime" will possibly work?
The answer is NO. 

The equivalent format strftime to what I used is as follows: **%Y%m%d%H%M%S**
So I set
**log_format  %d%t %a :%p %P %u \"%r\" %>s %b %D %X**
**date_format %Y%m%d**
**time_format %H%M%S**

But, when run the GoAccess the answer is: "No valid hits".
What else can I try? Or what is wrong with what I'm doing?

**Comment by allinurl** [comment]
The following works:

    log-format %x %h %^"%r" %s %b %D %^
    date-format %Y%m%d%H%M%S
    time-format %Y%m%d%H%M%S

Note that goaccess does not use the same log-format specifiers as Apache. Please take a look at the [man page](http://goaccess.io/man#custom-log) for more details.

**Comment by llrocha** [comment]
Yes, it work! Thank you.
