### ISSUE TITLE
Error occured at: src/goaccess.c - main - 1062

### ISSUE THREAD

**Issue by KomaBeyond** [allinurl/goaccess#355]
This is configuration in /etc/goaccess.conf:  

    time-format %H:%M:%S  
    date-format %d/%b/%Y  
    log-format %h %^[%d:%t %^] "%r" %s %b %R %U %r  

This is my nginx access log format: xxx.log  

    11.149.133.84 - -  [11/Jan/2016:06:26:57 +0800]   "GET /app/api/user_stream/access?stream_id=135961&_ack=lOtOVHct&from=uuser_c HTTP/1.0"  200  392   "http://www.xxx.cn/user_stream/view?stream_id=135961&_ack=lOtOVHct&biz=uuser_c&zzd_from=uuser_c-iflow&sm_article_id=8007481079721998877&dl_type=3&uc_biz_str=S%3Acustom%7CC%3Aiflow_site%7CK%3Atrue&rd_type=reco&recoid=17949700861332683467"  "Mozilla/5.0 (Linux; U; Android 4.4.2; zh-CN; PE-TL10 Build/HuaweiPE-TL10) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 UCBrowser/10.9.2.712 U3/0.8.0 Mobile Safari/534.30" "114.223.207.131"   

And then when i was run the goaccess command, there is an error occurred like this:  

    GoAccess - version 0.9.7 - Dec 20 2015 17:55:38  
    Config file: /etc/goaccess.conf  

    Fatal error has occurred  
    Error occured at: src/goaccess.c - main - 1062  
    Nothing valid to process. Verify your date/time/log format.  

Please help me, i can't find it out in google.... sorry about that

**Comment by allinurl** [comment]
Assuming there is only one space between fields, e.g., `+0800]   "GET` (two spaces), the following works for the line posted:

    log-format %h %^[%d:%t %^] "%r" %s %b "%R" "%u"
    date-format %d/%b/%Y
    time-format %H:%M:%S

**Comment by KomaBeyond** [comment]
<p>Thanks for your reply, but  i used the log-format style u given to me, it was also didn't work for me.  I think it maybe occurred by the space number or maybe the log-format u given to me is not fit for my nginx access.log.</p>

<p>I checked my nginx access.log, there has about three styles, i paste it in here:</p>
    11.150.139.64 - -  [11/Jan/2016:06:26:16 +0800]   "GET /static/style/light/swiper-3.2.7.min.css HTTP/1.0"  304  0   "http://www.xxx.cn/astr/view?str_id=135950&_ack=KsKXYfqE&biz=uc&zzd_from=uc-iflow&sm_article_id=8151915552073249051&dl_type=3&uc_biz_str=S%3Acustom%7CC%3Aiflow_ncmt%7CK%3Atrue&rd_type=reco&recoid=7683020013464877509"  "Mozilla/5.0 (iPhone; CPU iPhone OS 9_2 like Mac OS X; zh-CN) AppleWebKit/537.51.1 (KHTML, like Gecko) Mobile/13C75 UCBrowser/10.7.11.672 Mobile" "115.194.175.86, 106.39.189.85"
  
    12.175.139.64 - -  [11/Jan/2016:06:26:17 +0800]   "GET /api/str/intelli/collabtive/rec?pageno=1&str_id=135962 HTTP/1.0"  200  1325   "-"  "WT/2.7.7_212/Android/4.4.2/H60-L01/357143418547/wet/nettype:wifi/gps:120.085899,27.792708/city:%E6%B8%A9%E5%B7%9E%E5%B8%82/" "112.12.157.93"  

    13.169.133.54 - -  [11/Jan/2016:06:26:17 +0800]   "GET /favicon.ico HTTP/1.0"  200  2015   "http://www.txx.cn/str/view?str_id=135950&_ack=KsKXYfqE&biz=uc&zzd_from=uc-iflow&sm_article_id=8151915552073249051&dl_type=3&uc_biz_str=S%3Acustom%7CC%3Aiflow_site%7CK%3Atrue&rd_type=reco&recoid=3946812656348015122"  "Mozilla/5.0 (Linux; U; Android 4.4.4; zh-CN; HUAWEI C8817E Build/HuaweiC8817E) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 UCBrowser/10.9.2.712 U3/0.8.0 Mobile Safari/534.30" "124.196.61.237"    

<p>Could i ignore there has how many space numbers between the format style, i just click one space between %U and %r or other, but the program can automatical transition it.</p>

<p>Thanks for your help again. Have a nice day.</p>

**Comment by allinurl** [comment]
This should work for the sample lines you posted.

    log-format %h %^[%d:%t %^]%^"%r"  %s   %b %^"%R" %^"%u"
    date-format %d/%b/%Y
    time-format %H:%M:%S

**Comment by KomaBeyond** [comment]
OK, thanks for your help, now it's worked. But i am still dont't  know why, maybe i need to check the man page more carefully. Thanks!

**Comment by allinurl** [comment]
Glad that worked. 

The issue was the spaces. You can use `%~` if you would like to avoid the use of spaces. Please take a look at the [man page](http://goaccess.io/man#custom-log) for more details.

**Comment by suguojun** [comment]
10.180.115.175 - k00228866 [17/Oct/2016:06:47:21 +0800] "GET /wmcenter/GetDTSData.git/info/refs?service=git-upload-pack HTTP/1.1" 200 310 "-" "git/1.9.0.msysgit.1"0.401
10.74.174.126 - - [17/Oct/2016:06:47:21 +0800] "GET /MicroServicePlatform/ServiceFactoryService.git/info/refs?service=git-upload-pack HTTP/1.1" 200 1432 "-" "git/2.5.3.windows.1"0.031

**Comment by suguojun** [comment]
This is configuration in /etc/goaccess.conf:
log-format %h %^[%d:%t %^] "%r" %s %b "%R" "%u" %^%L
date-format %d/%b/%Y
time-format %H:%M:%S
