### ISSUE TITLE
How to resolve IP to hostname on the HTML report?

### ISSUE THREAD

**Issue by cznyx** [allinurl/goaccess#356]
right now i need open another tool to verify if is a fake spider, if goaccess can display resolve host directly it will help a lot. 

![selection_003](https://cloud.githubusercontent.com/assets/2059267/12295841/35d38ccc-ba47-11e5-8896-bdcd8b186ab2.png)

**Comment by allinurl** [comment]
You should be able to resolve the ip passing `-d`. For instance,

    goaccess -f access.log -d > report.html

**Comment by cznyx** [comment]
thank you for quick response.
and just another one ,is there any way to check the detail of "unknow"
![selection_004](https://cloud.githubusercontent.com/assets/2059267/12296301/34b89a5a-ba4a-11e5-9c67-7d0286037f64.png)
?

**Comment by allinurl** [comment]
Glad that worked.

Currently there's no way to check all the unknowns, usually bots/spiders not listed under [browsers.c](https://github.com/allinurl/goaccess/blob/master/src/browsers.c). In the case of OSS, usually bots won't list the OS in th user agent.

There are plans to have the ability to output all the unknowns to a file. Please see issue #152 for more details. Feel free to post any suggestions as well.
