### ISSUE TITLE
Additions to the default list of static files

### ISSUE THREAD

**Issue by Markus00000** [allinurl/goaccess#357]
Some popular static file extensions are missing from the default list, e.g. `.otf`:

    static-file .otf
    static-file .OTF

There is also .woff2:

    static-file .woff2
    static-file .WOFF2

For example, Adobe distributes their Source Sans Pro fonts in [WOFF 2.0](https://github.com/adobe-fonts/source-sans-pro/tree/2.020R-ro/1.075R-it/WOFF2/OTF). Chrome and Firefox (among others) [support it](http://caniuse.com/#search=woff2).

Even if the goal of the default list is to cover just the most popular extensions, I suggest to add `.otf` and `.woff2`. Otherwise fonts will be split between "Requested Files" and "Static Requests".

If the goal is to be "complete," here are some more extensions to consider:

    static-file .ac3
    static-file .AC3
    static-file .avi
    static-file .AVI
    static-file .bmp
    static-file .BMP
    static-file .bz2
    static-file .BZ2
    static-file .class
    static-file .CLASS
    static-file .csv
    static-file .CSV
    static-file .cue
    static-file .CUE
    static-file .dat
    static-file .DAT
    static-file .doc
    static-file .DOC
    static-file .docx
    static-file .DOCX
    static-file .dts
    static-file .DTS
    static-file .ejs
    static-file .EJS
    static-file .eps
    static-file .EPS
    static-file .exe
    static-file .EXE
    static-file .flv
    static-file .FLV
    static-file .gz
    static-file .GZ
    static-file .img
    static-file .IMG
    static-file .iso
    static-file .ISO
    static-file .jar
    static-file .JAR
    static-file .mid
    static-file .MID
    static-file .midi
    static-file .MIDI
    static-file .mkv
    static-file .MKV
    static-file .mp4
    static-file .MP4
    static-file .mpeg
    static-file .MPEG
    static-file .mpg
    static-file .MPG
    static-file .odp
    static-file .ODP
    static-file .ods
    static-file .ODS
    static-file .odt
    static-file .ODT
    static-file .ogg
    static-file .OGG
    static-file .otf
    static-file .OTF
    static-file .pict
    static-file .PICT
    static-file .pls
    static-file .PLS
    static-file .ppt
    static-file .PPT
    static-file .pptx
    static-file .PPTX
    static-file .ps
    static-file .PS
    static-file .qt
    static-file .QT
    static-file .rar
    static-file .RAR
    static-file .rm
    static-file .RM
    static-file .svgz
    static-file .SVGZ
    static-file .tar
    static-file .TAR
    static-file .tgz
    static-file .TGZ
    static-file .tif
    static-file .TIF
    static-file .tiff
    static-file .TIFF
    static-file .wav
    static-file .WAV
    static-file .webp
    static-file .WEBP
    static-file .woff2
    static-file .WOFF2
    static-file .xls
    static-file .XLS
    static-file .xlsx
    static-file .XLSX
    static-file .zip
    static-file .ZIP

**Comment by allinurl** [comment]
Extensions are now case-insensitive. Also, a more comprehensive list of [static extensions](https://github.com/allinurl/goaccess/blob/master/config/goaccess.conf#L240) has been added. The less common extensions can be uncommented as needed (the size of the list is proportional to the run time).

It will be deployed on the upcoming version. Thanks!
