### ISSUE TITLE
Time distribution by arbitrary refinement

### ISSUE THREAD

**Issue by jody-frankowski** [allinurl/goaccess#360]
Hi,

It would be nice to have an option/key to increase the refinment of the time distribution array.

**Comment by allinurl** [comment]
Could you please elaborate a bit more on this? What would be a use case?

Thanks

**Comment by jody-frankowski** [comment]
I have found that in some cases one hour is too large to draw some conclusions.
Say you have an incident at 9h50 and you want to find out if it might be correlated to apache/nginx.
Since goaccess uses a one hour distribution, a possible event would be flattened over this hour.
Am I being clear?

**Comment by allinurl** [comment]
I can look into this. Just to be sure, the refinement will only affect the time distribution panel.

**Comment by jody-frankowski** [comment]
Awesome. Ok, I don't see another panel that would take advantage from such a feature anyway.

**Comment by yhl3692319** [comment]
so how can i sorted by second to know how many hits in per second in Time distribution

**Comment by allinurl** [comment]
@yhl3692319 The plan is to have a command line option that allows you to set the refinement upfront. I'm shooting to have this done in the upcoming version.

**Comment by yhl3692319** [comment]
thx, now i use `grep $each_uniq_time | goaccess -a` to get the data

**Comment by allinurl** [comment]
This has been implemented and deployed in [version 1.0](https://goaccess.io/).  

It adds a time distribution specificity option. Using the command line `--time-dist-spec=[hr|min]` allows either the use of the whole hour as the time distribution key (default) or a tenth of minute such as `18:2`, `22:5`.

Thanks for the suggestion!

**Comment by jody-frankowski** [comment]
Hi,

I'm using goaccess 1.0.2, and for some unknown reason, I can't seem to find the `--time-dist-spec` option. It isn't documented in the man page, and goaccess throws an error when i try to use it:

```
$ goaccess -f log --time-dist-spec=18:2
goaccess: unrecognized option '--time-dist-spec=18:2'
```

**Comment by allinurl** [comment]
Great question. Actually it changed to `--hour-spec=<hr|min>`.  It sets the time specificity to either hour (default) or min to display the tenth of a minute appended to the hour.

**Comment by jody-frankowski** [comment]
Ok. I now understand better the old name `--time-dist-spec` (and almost think it was better).
I played around with the option, and I would change the man page and change: `to display the tenth of a minute` to `to display the tenth of an hour`.
Do you intend to change the option to refine even more (maybe to the minute). Or is it out of scope for you?

**Comment by allinurl** [comment]
Thanks for pointing how it reads on the man page. I'll update this.

I can certainly refine this option even more, it should be a pretty easy change, however, I'd need to change first the amount of data that it is displayed in some of the panels so if a more refined option is set, then the data would be available for that panel. Right now it shows 366 items (or --max-items) per panel.

**Comment by jody-frankowski** [comment]
Another problem I noticed this week was that the CLI view (I didn't check the web one) with the `--hour-spec=min` option didn't show all the possible time-ranges in the time distribution panel.

**Comment by allinurl** [comment]
Would you be able to post a screenshot or the ranges that are showing up so I can take a look?

**Comment by jody-frankowski** [comment]
Ok my bad, I forgot how to scroll within an expanded panel. Sorry :)

**Comment by AnilVemulapally** [comment]
Hi,
I am using --hour-spec=min option but time distribution is showing like 3:20 3:30  showing 10mins intervals. How to get time distribution of every one minute

**Comment by allinurl** [comment]
@AnilVemulapally Currently there's no option for one minute interval. Feel free to open a new issue requesting this feature. Thanks

**Comment by GsandeepR** [comment]
I am new to goaccess . I used --hour-spec=min ,--hour-spec=hr and generated two reports.But when I see the visitor count in time distribution of both reports ,they are different.With --hour-spec=hr Its giving large value,but the value with --hour-spec=min ,the value is very less.

**Comment by allinurl** [comment]
@GsandeepR `min` will give you the number of visitors by the tenth of a minute, e.g., how many visitors at 13:10, 13:20, 13:30, etc, while `hr` will be by the hour, e.g., 13, 14, 15.

**Comment by GsandeepR** [comment]
![min](https://user-images.githubusercontent.com/16095573/35277119-9c0c1b14-006b-11e8-8478-a89150ccb55d.png)
![hr](https://user-images.githubusercontent.com/16095573/35277120-9c39c50a-006b-11e8-9410-9acaf9e6d155.png)
I understood that --hour-spec=min will give visitors at 13:10,13:20 etc and --hour-spec=hr will give visitors at 13 hour .I am talking about the visitors value change for min and hr. See the attacements,visitors count is dropped when i used --hour-spec=min

**Comment by allinurl** [comment]
I'm not sure I follow. What I see from your attachments is that from 09:00 to 09:59 there are 454 visitors (second image), while the first image shows that there are 89 visitors from 09:00 to 09:09. Does that answer your question?

**Comment by GsandeepR** [comment]
My concern is the number of visitors.How to make sure the results are correct. If I add all the visitors of every tenth minute ,its exceeding the visitors in the hour.Does the difference between them indicates common visitors during every tenth minute?

**Comment by allinurl** [comment]
That's right. It's very likely that when using `--hour-spec=min` the count won't be the same as if you use `--hour-spec=hr`. This is because it's using `09:0`, `09:1` as unique keys to count unique visitors for every tenth of a minute. The count should be pretty accurate though.

**Comment by domruf** [comment]
Any change that there will be an option to use actual minutes, instead of every 'tenth minute', in a future release?

**Comment by allinurl** [comment]
@domruf Sounds very doable. I can look into adding this. Could you please open a new issue so I don't forget? Thanks.
