### ISSUE TITLE
Error occured at: goaccess.c - main - 832

### ISSUE THREAD

**Issue by mikonoid** [allinurl/goaccess#361]
I have goaccess this version. And I have this log format 

    98.167.1.1 | [25/Jan/2016:06:25:03 +0300] | GET /funnel/?esub=PBZYWHpPZzxuCFpPemJsCB1KDmMMCQ8REDsIDW4WA01lW0lYel1P&isp=1 HTTP/1.1 | 200 | 0 | http://imp.com/rndr/MyJane/?esub=PBZIWHpVBFZ9HUAJbm94HFZZDWsVHU0fCHoZByc | Mozilla/5.0 (Linux; Android 4.4.2; RCT6573W23 Build/KOT49H) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/30.0.0.0 Safari/537.36 | 88.7.7.7:80 | 0.011 | 200 | - | imp.com

But when I try parsing log I got this error

GoAccess - version 0.8.3 - Aug 30 2014 07:43:50

> Fatal error has occurred
> Error occured at: goaccess.c - main - 832
> Nothing valid to process.

**Comment by allinurl** [comment]
You won't be able to fully parse the string since the user agent doesn't really look like it has a delimeter. Are you somehow escaping `|` within the user agent?

The following partially works for the log posted above:

    log-format %h %^[%d:%t %^] | %m %U %H | %s | %b | %R | %^
    date-format %d/%b/%Y
    time-format %H:%M:%S

**Comment by mikonoid** [comment]
In version 0.8.3 time format not supported?

**Comment by allinurl** [comment]
The `time-format` variable was added on v0.9

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
