### ISSUE TITLE
How to init at cygwin?

### ISSUE THREAD

**Issue by dwyangd** [allinurl/goaccess#363]
i got error like this:

```
$ ./configure --enable-geoip --enable-utf8
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking for gcc... gcc
checking whether the C compiler works... no
configure: error: in `/tmp/goaccess-0.9.7':
configure: error: C compiler cannot create executables
See `config.log' for more details
```

what should i do?

**Comment by allinurl** [comment]
The following is the list of packages you need prior to install goaccess on cygwin. 

    libGeoIP-devel
    libncurses-devel
    libncursesw10
    gcc-core (C)
    make
    automake
    automake wrapper scripts
    pkg-config

After installing those, build as follow: http://goaccess.io/download#build

**Comment by dwyangd** [comment]
@allinurl yes,i fix error when i download lib!thanks~
