### ISSUE TITLE
Error occured at: goaccess.c - main - Nothing valid to process.

### ISSUE THREAD

**Issue by evemilano** [allinurl/goaccess#365]
Hello! 
I'm using goaccess to track [evemilano](https://www.evemilano.com)'s log but I have some problem :(
Any idea how to solve this?

GoAccess - version 0.8.3 - Oct 24 2014 17:27:50

    Fatal error has occurred
    Error occured at: goaccess.c - main - 832
    Nothing valid to process.

LOG example:

    162.158.151.53 - - [03/Feb/2016:11:02:50 -0500]  "GET /servizi-web-marketing/ HTTP/1.1" 500 278 "https://www.evemilano.com/servizi-seo/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.97 Safari/537.36" 0.128 0.128 . BYPASS
    141.101.105.70 - - [03/Feb/2016:11:02:57 -0500]  "POST /wp-cron.php?doing_wp_cron=1454515377.2718749046325683593750 HTTP/1.1" 200 31 "-" "WordPress/4.4.2; https://www.evemilano.com" 0.156 0.156 . -
    162.158.151.53 - - [03/Feb/2016:11:02:58 -0500]  "GET / HTTP/1.1" 200 15326 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.97 Safari/537.36" 1.437 1.437 . BYPASS

**Comment by allinurl** [comment]
Could you please post the values of your `log-format`, `date-format` and `time-format` from the config file? 

Also, you may want to update to the latest version, v0.8.3 is a bit old :)

**Comment by evemilano** [comment]
Log Format - [c] to add/edit format
%h %^[%d:%^] "%r" %s %b 
Date Format - [d] to add/edit format
%d/%b/%Y 


But I tried all the availables possibilities.

I got goaccess from apt-get install command. How can I get the newest version?

**Comment by allinurl** [comment]
Please try the following (assuming the first value after the agent is `request_time`):

    log-format %h %^[%d:%t %^]  "%r" %s %b "%R" "%u" %T %^
    date-format %d/%b/%Y
    time-format %H:%M:%S

Note: You have an extra space between the time `]` and the request `"`. Also, `time-format` works only on newer versions. 

To get the latest version, uninstall the current (`apt-get remove --purge goaccess`) and then use this [repo](http://goaccess.io/download#official-repo).

**Comment by evemilano** [comment]
Upgraded to the last version

GoAccess - version 0.9.7 - Dec 20 2015 17:55:39

still can't open a default Nginx log :(

**Comment by allinurl** [comment]
If I run the following command against the three lines you posted above, works fine:

    goaccess -f log --log-format='%h %^[%d:%t %^]  "%r" %s %b "%R" "%u" %T %^' --date-format='%d/%b/%Y' --time-format='%H:%M:%S'

Can you please try that against those lines?

**Comment by evemilano** [comment]
it seems a problem related the the log file-name.
I can open the access.log but not name_access.log

**Comment by allinurl** [comment]
Make sure permissions are right on the log file.

**Comment by evemilano** [comment]
ok thanks. 
Is there a way to track only specific user-agent? Googlebot only for example?

**Comment by allinurl** [comment]
You will need to do some pre-processing, e.g.,

    grep -i 'Googlebot' /var/log/apache2/access.log | goaccess -a

**Comment by evemilano** [comment]
Thank you Gerardo for the reply, this could be really useful!
BTW if I type your string (with log location adjusted) I get the help information printed on screen:

GoAccess - 0.9.7

Usage: goaccess [ options ... ] -f log_file [-c][-M][-H][-q][-d][...]
The following options can also be supplied to the command:

Log & Date Format Options
....

It seems the string format is not correct. Any advices? Thanks again :D

**Comment by allinurl** [comment]
Can you please post the output of `goaccess --dcf`?

You could then use that config file and specify the formats. For instance,

```
# goaccess --dcf`
> /etc/goaccess.conf

$ vim /etc/goaccess.conf
> uncomment log-format, date-format and time-format (make sure to use the right formats)

$ grep -i 'Googlebot' /var/log/nginx/access.log | goaccess -a -p /etc/goaccess.conf
```

**Comment by evemilano** [comment]
my goaccess.conf
*****************************

######################################
# Time Format Options (required)
######################################
#
# The hour (24-hour clock) [00,23]; leading zeros are permitted but not required.
# The minute [00,59]; leading zeros are permitted but not required.
# The seconds [00,60]; leading zeros are permitted but not required.
# See `man strftime` for more details
#
# The following time format works with any of the
# Apache/NGINX's log formats below.
#
#time-format %H:%M:%S
#
# Google Cloud Storage or
# The time in microseconds since the Unix epoch.
#
#time-format %f

# Squid native log format
#
#time-format %s

######################################
# Date Format Options (required)
######################################
#
# The date-format variable followed by a space, specifies
# the log format date containing any combination of regular
# characters and special format specifiers. They all begin with a
# percentage (%) sign. See `man strftime`
#
# The following date format works with any of the
# Apache/NGINX's log formats below.
#
#date-format %d/%b/%Y
#
# AWS | Amazon CloudFront (Download Distribution)
# AWS | Elastic Load Balancing
# W3C (IIS)
#
#date-format %Y-%m-%d
#
# Google Cloud Storage or
# The time in microseconds since the Unix epoch.
#
#date-format %f

# Squid native log format
#
#date-format %s

######################################
# Log Format Options (required)
######################################
#
# The log-format variable followed by a space or \t for
# tab-delimited, specifies the log format string.
#
# NOTE: If the time/date is a timestamp in seconds or microseconds
# %x must be used instead of %d & %t to represent the date & time.

# NCSA Combined Log Format
#
#log-format %h %^[%d:%t %^] "%r" %s %b "%R" "%u"

# NCSA Combined Log Format with Virtual Host
#
#log-format %v:%^ %h %^[%d:%t %^] "%r" %s %b "%R" "%u"

# Common Log Format (CLF)
#
#log-format %h %^[%d:%t %^] "%r" %s %b

# Common Log Format (CLF) with Virtual Host
#
#log-format %v:%^ %h %^[%d:%t %^] "%r" %s %b

# W3C
#
#log-format %d %t %h %^ %^ %^ %^ %r %^ %s %b %^ %^ %u %R

# AWS | Amazon CloudFront (Download Distribution)
#
#log-format %d\t%t\t%^\t%b\t%h\t%m\t%^\t%r\t%s\t%R\t%u\t%^

# AWS | Elastic Load Balancing
#
#log-format %dT%t.%^ %^ %h:%^ %^ %T %^ %^ %^ %s %^ %b "%r" "%u"

# Google Cloud Storage
#
#log-format "%x","%h",%^,%^,"%m","%U","%s",%^,"%b","%D",%^,"%R","%u"

# Squid native log format
#
#log-format %^ %^ %^ %v %^: %x.%^ %~%L %h %^/%s %b %m %U

# Virtualmin Log Format with Virtual Host
#
#log-format %h %^ %v %^[%d:%t %^] "%r" %s %b "%R" "%u"

######################################
# UI Options
######################################

# Prompt log/date configuration window on program start.
#
config-dialog false

# Choose among color schemes
# 1 : Default grey scheme
# 2 : Green scheme
#
color-scheme 1

# Color highlight active panel.
#
hl-header true

# Set HTML report page title and header.
#
#html-report-title My Awesome Web Stats

# Turn off colored output. This is the  default output on
# terminals that do not support colors.
# true  : for no color output
# false : use color-scheme
#
no-color false

# Don't write column names in the terminal output. By default, it displays
# column names for each available metric in every panel.
#
no-column-names false

# Disable progress metrics.
#
no-progress false

# Enable mouse support on main dashboard.
#
with-mouse false

# Disable summary metrics on the CSV output..
#
no-csv-summary false

# Custom colors for the terminal output
# Tailor GoAccess to suit your own tastes.
#
# Color Syntax:
# DEFINITION space/tab colorFG#:colorBG# [[attributes,] PANEL]
#
# FG# = foreground color number [-1...255] (-1 = default terminal color)
# BG# = background color number [-1...255] (-1 = default terminal color)
#
# Optionally:
#
# It is possible to apply color attributes, such as:
# bold,underline,normal,reverse,blink.
# Multiple attributes are comma separated
#
# If desired, it is possible to apply custom colors per panel, that is, a
# metric in the REQUESTS panel can be of color A, while the same metric in the
# BROWSERS panel can be of color B.
#
# The following is a 256 color scheme (Monokai palette)
#
#color COLOR_MTRC_HITS     color197:color-1
#color COLOR_MTRC_VISITORS color148:color-1
#color COLOR_MTRC_DATA     color7:color-1
#color COLOR_MTRC_BW       color81:color-1
#color COLOR_MTRC_AVGTS    color247:color-1
#color COLOR_MTRC_CUMTS    color95:color-1
#color COLOR_MTRC_MAXTS    color186:color-1
#color COLOR_MTRC_PROT     color141:color-1
#color COLOR_MTRC_MTHD     color81:color-1
#color COLOR_MTRC_PERC     color186:color-1
#color COLOR_MTRC_PERC     color186:color-1 VISITORS
#color COLOR_MTRC_PERC     color186:color-1 OS
#color COLOR_MTRC_PERC     color186:color-1 BROWSERS
#color COLOR_MTRC_PERC     color186:color-1 VISIT_TIMES
#color COLOR_MTRC_PERC_MAX color208:color-1
#color COLOR_MTRC_PERC_MAX color208:color-1 VISITORS
#color COLOR_MTRC_PERC_MAX color208:color-1 OS
#color COLOR_MTRC_PERC_MAX color208:color-1 BROWSERS
#color COLOR_MTRC_PERC_MAX color208:color-1 VISIT_TIMES
#color COLOR_PANEL_COLS    color242:color-1
#color COLOR_BARS          color186:color-1
#color COLOR_ERROR         color231:color197
#color COLOR_SELECTED      color0:color215
#color COLOR_PANEL_ACTIVE  color7:color240
#color COLOR_PANEL_HEADER  color7:color237
#color COLOR_PANEL_DESC    color242:color-1
#color COLOR_OVERALL_LBLS  color251:color-1
#color COLOR_OVERALL_VALS  color148:color-1
#color COLOR_OVERALL_PATH  color186:color-1
#color COLOR_ACTIVE_LABEL  color7:color237
#color COLOR_BG            color7:color-1
#color COLOR_DEFAULT       color7:color-1
#color COLOR_PROGRESS      color7:color141

######################################
# File Options
######################################

# Specify the path to the input log file. If set, it will take
# priority over -f from the command line.
#
log-file /var/log/nginx/access.log

# Send all debug messages to the specified file.
#
#debug-file debug.log

# Specify a custom configuration file to use. If set, it will take
# priority over the global configuration file (if any).
#
#config-file <filename>

# Log invalid requests to the specified file.
#
#invalid-requests <filename>

# Do not load the global configuration file.
#
#no-global-config false

######################################
# Parse Options
######################################

# Include static files that contain a query string in the static files
# panel.
# e.g., /fonts/fontawesome-webfont.woff?v=4.0.3
#
all-static-files false

# Consider the following extensions as static files
# The actual '.' is required and extensions are case sensitive
#
static-file .css
static-file .CSS
static-file .dae
static-file .DAE
static-file .eot
static-file .EOT
static-file .gif
static-file .GIF
static-file .ico
static-file .ICO
static-file .jpeg
static-file .JPEG
static-file .jpg
static-file .JPG
static-file .js
static-file .JS
static-file .map
static-file .MAP
static-file .mp3
static-file .MP3
static-file .pdf
static-file .PDF
static-file .png
static-file .PNG
static-file .svg
static-file .SVG
static-file .swf
static-file .SWF
static-file .ttf
static-file .TTF
static-file .txt
static-file .TXT
static-file .woff
static-file .WOFF

# Exclude an IPv4 or IPv6 from being counted.
# Ranges can be included as well using a dash in between
# the IPs (start-end).
#
#exclude-ip 127.0.0.1
#exclude-ip 192.168.0.1-192.168.0.100
#exclude-ip ::1
#exclude-ip 0:0:0:0:0:ffff:808:804-0:0:0:0:0:ffff:808:808

# Enable a list of user-agents by host. For faster parsing, do not
# enable this flag.
#
#agent-list false
#agent-list true

# Include HTTP request method if found. This will create a
# request key containing the request method + the actual request.
#
http-method true

# Include HTTP request protocol if found. This will create a
# request key containing the request protocol + the actual request.
#
http-protocol true

# Ignore request's query string.
# i.e.,  www.google.com/page.htm?query => www.google.com/page.htm
#
# Note: Removing the query string can greatly decrease memory
# consumption, especially on timestamped requests.
#
no-query-string false

# Disable IP resolver on terminal output.
#
no-term-resolver false

# Write output to stdout given one of the following formats:
# csv  : A comma-separated values (CSV)
# json : JSON (JavaScript Object Notation)
# html : HTML report
#
#output-format json

# Display real OS names. e.g, Windows XP, Snow Leopard.
#
real-os true

#  Enable IP resolver on HTML|JSON output.
#
with-output-resolver false

# Treat non-standard status code 444 as 404.
#
444-as-404 false

# Add 4xx client errors to the unique visitors count.
#
4xx-to-unique-count false

# Decode double-encoded values.
#
double-decode false

# Ignore parsing and displaying one or multiple status code(s)
#
#ignore-status 400
#ignore-status 502

# Ignore crawlers from being counted.
# This will ignore robots listed under browsers.c
# Note that it will count them towards the total
# number of requests, but excluded from any of the panels.
#
ignore-crawlers false

# Ignore parsing and displaying the given panel.
#
#ignore-panel VISITORS
#ignore-panel REQUESTS
#ignore-panel REQUESTS_STATIC
#ignore-panel NOT_FOUND
#ignore-panel HOSTS
#ignore-panel OS
#ignore-panel BROWSERS
#ignore-panel VISIT_TIMES
#ignore-panel VIRTUAL_HOSTS
ignore-panel REFERRERS
#ignore-panel REFERRING_SITES
ignore-panel KEYPHRASES
#ignore-panel GEO_LOCATION
#ignore-panel STATUS_CODES

# Ignore referers from being counted.
# This supports wild cards. For instance,
# '*' matches 0 or more characters (including spaces)
# '?' matches exactly one character
#
#ignore-referer *.domain.com
#ignore-referer ww?.domain.*

# Sort panel on initial load.
# Sort options are separated by comma.
# Options are in the form: PANEL,METRIC,ORDER
#
# Available metrics:
#  BY_HITS     - Sort by hits
#  BY_VISITORS - Sort by unique visitors
#  BY_DATA     - Sort by data
#  BY_BW       - Sort by bandwidth
#  BY_AVGTS    - Sort by average time served
#  BY_CUMTS    - Sort by cumulative time served
#  BY_MAXTS    - Sort by maximum time served
#  BY_PROT     - Sort by http protocol
#  BY_MTHD     - Sort by http method
# Available orders:
#  ASC
#  DESC
#
#sort-panel VISITORS,BY_DATA,ASC
#sort-panel REQUESTS,BY_HITS,ASC
#sort-panel REQUESTS_STATIC,BY_HITS,ASC
#sort-panel NOT_FOUND,BY_HITS,ASC
#sort-panel HOSTS,BY_HITS,ASC
#sort-panel OS,BY_HITS,ASC
#sort-panel BROWSERS,BY_HITS,ASC
#sort-panel VISIT_TIMES,BY_DATA,DESC
#sort-panel VIRTUAL_HOSTS,BY_HITS,ASC
#sort-panel REFERRERS,BY_HITS,ASC
#sort-panel REFERRING_SITES,BY_HITS,ASC
#sort-panel KEYPHRASES,BY_HITS,ASC
#sort-panel GEO_LOCATION,BY_HITS,ASC
#sort-panel STATUS_CODES,BY_HITS,ASC

######################################
# GeoIP Options
# Only if configured with --enable-geoip
######################################

# Standard GeoIP database for less memory usage.
#
#std-geoip false
#std-geoip true

# Specify path to GeoIP database file. i.e., GeoLiteCity.dat
# .dat file needs to be downloaded from maxmind.com.
#
# For IPv4 City database:
# wget -N http://geolite.maxmind.com/download/geoip/database/GeoLiteCity.dat.gz
# gunzip GeoLiteCity.dat.gz
#
# For IPv6 City database:
# wget -N http://geolite.maxmind.com/download/geoip/database/GeoLiteCityv6-beta/GeoLiteCityv6.dat.gz
# gunzip GeoLiteCityv6.dat.gz
#
# For IPv6 Country database:
# wget -N http://geolite.maxmind.com/download/geoip/database/GeoIPv6.dat.gz
# gunzip GeoIPv6.dat.gz
#
# Note: `geoip-city-data` is an alias of `geoip-database`
#
# geoip-database /usr/local/share/GeoIP/GeoLiteCity.dat

######################################
# Tokyo Cabinet Options
# Only if configured with --enable-tcb=btree
######################################

# GoAccess has the ability to process logs incrementally through the on-disk
# B+Tree database.
#
# It works in the following way:
# - A data set must be persisted first with --keep-db-files, then the same data
#   set can be loaded with --load-from-disk.
# - If new data is passed (piped or through a log file), it will append it to
#   the original data set.
# - To preserve the data at all times, --keep-db-files must be used.
# - If --load-from-disk is used without --keep-db-files, database files will be
#   deleted upon closing the program.

# On-disk B+ Tree
# Persist parsed data into disk. This should be set to
# the first dataset prior to use `load-from-disk`.
# Setting it to false will delete all database files
# when exiting the program.
#keep-db-files true

# On-disk B+ Tree
# Load previously stored data from disk.
# Database files need to exist. See `keep-db-files`.
#load-from-disk false

# On-disk B+ Tree
# Path where the on-disk database files are stored.
# The default value is the /tmp directory.
#
#db-path /tmp

# On-disk B+ Tree
# Set the size in bytes of the extra mapped memory.
# The default value is 0.
#
#xmmap 0

# On-disk B+ Tree
# Max number of leaf nodes to be cached.
# Specifies the maximum number of leaf nodes to be cached.
# If it is not more than 0, the default value is specified.
# The default value is 1024.
#
#cache-lcnum 1024

# On-disk B+ Tree
# Specifies the maximum number of non-leaf nodes to be cached.
# If it is not more than 0, the default value is specified.
# The default value is 512.
#
#cache-ncnum 512

# On-disk B+ Tree
# Specifies the number of members in each leaf page.
# If it is not more than 0, the default value is specified.
# The default value is 128.
#
#tune-lmemb 128

# On-disk B+ Tree
# Specifies the number of members in each non-leaf page.
# If it is not more than 0, the default value is specified.
# The default value is 256.
#
#tune-nmemb 256

# On-disk B+ Tree
# Specifies the number of elements of the bucket array.
# If it is not more than 0, the default value is specified.
# The default value is 32749.
# Suggested size of the bucket array is about from 1 to 4
# times of the number of all pages to be stored.
#
#tune-bnum 32749

# On-disk B+ Tree
# Specifies that each page is compressed with ZLIB|BZ2 encoding.
# Disabled by default.
#
#compression zlib

**Comment by allinurl** [comment]
As I mentioned in my previous post, please make sure to **uncomment** or **add** the following formats to the relevant config file:

```
log-format %h %^[%d:%t %^]  "%r" %s %b "%R" "%u" %T %^
date-format %d/%b/%Y 
time-format %H:%M:%S
```

**Comment by allinurl** [comment]
Closing this. Feel free to reopen if needed.

**Comment by evemilano** [comment]
Hi, I'm back :) I have a problem with real time reporting. If I launch goaccess to report in ssh it runs quite well, but if I launch the real time html report, the parsing of the log freezes and it keeps the socked busy, so I can re-launch it. 
The HTML report has just the main info (log size & so) but all the others fields are empty. Do you know how to solve it? Thanks.

**Comment by allinurl** [comment]
Once goaccess has finished parsing the log, the command line output will remain as you mentioned above. However, the Websocket server should continue running in the background. Please check your browser development tools‎ console for any possible errors being reported. Also please take a look at the https://goaccess.io/faq for more details on how to generate the real time report.

**Comment by evemilano** [comment]
the console says: WebSocket connection to 'ws://www.mysiye.com:7890/' failed: Error in connection establishment: net::ERR_CONNECTION_TIMED_OUT

**Comment by evemilano** [comment]
the console says: 
`WebSocket connection to 'ws://www.mysite.com:7890/' failed: Error in connection establishment: net::ERR_CONNECTION_TIMED_OUT`

I continue here the discussion :)

**Comment by allinurl** [comment]
Have you tried removing www from the address? --ws-host should point to the server address where goaccess is running parsing logs.

**Comment by evemilano** [comment]
I tried with host "evemilano.com" and also with the IP of the webserver running goaccess.

**Comment by allinurl** [comment]
please try using telnet to see if you are able to connect to the server. 

    telnet evemilano.com 7890

Also make sure port 7890 is opened.

**Comment by evemilano** [comment]
`telnet: Unable to connect to remote host: Connection refused`

**Comment by allinurl** [comment]
looks like either the port 7890 is closed or filtered by your firewall or goaccess server is not running (which doesn't seem to be the case from your netstat output above).

**Comment by evemilano** [comment]
There is no firewall. Goaccess should work as a service?
I don't understand if the problem is the closed door or if goaccess stop listening :(

**Comment by allinurl** [comment]
At the moment it doesn't automatically runs as a service. if it's showing up in netstat then it is running and listening for new connections. if it does, then you should be able to telnet for testing. Pressing ctrl+c will terminate goaccess.

Thanks for the posting :)

**Comment by evemilano** [comment]
now netstat doesn't show that port anymore, that's why I asked if I need to run it as service

**Comment by allinurl** [comment]
Nope, you need to run goaccess again.

**Comment by evemilano** [comment]
with goaccess ssh dashboard running, still no 7890 port listening

**Comment by allinurl** [comment]
You need to run it as you did above

    goaccess -f /var/log/nginx/mylog_access.log.1 -o /home/giovanni/www/www.mysite.com/report.html --real-time-html --ws-url=host

It won't work if you output to a terminal.

**Comment by evemilano** [comment]
I did it, but the parsing stops at 99%. After launching the realtime report the port 7890 is running locally, but still can't connect with telnet. Chrome consolle still says

`WebSocket connection to 'ws://evemilano.com:7890/' failed: Error in connection establishment: net::ERR_CONNECTION_TIMED_OUT`

I think I will give up :(

**Comment by allinurl** [comment]
Just wanted to ask if you were able to set the real time feature? Also, I was looking at your `netstat` output, and it appears you have the following:

    tcp 0 0 0.0.0.0:7890 0.0.0.0:* LISTEN 2631/nc

are you running netcat on 7890 and thus unable to bind goaccess to that port?

**Comment by wake-up-neo** [comment]
this might works

> date-format %d/%b/%Y
> log-format %h - %^ [%d:%t %^]  "%r" %s %b "%R" "%u" %T "%^"

**Comment by sg552** [comment]
in my case, the config file is "space sensitive", that is , if in the log file there are 2 space keys between "%r" and "%s", you have to add these 2 space keys in the config file.
