### ISSUE TITLE
Suggestion: distribute with --enable-tcb

### ISSUE THREAD

**Issue by e-ruiz** [allinurl/goaccess#366]
Hi! Thanks for goAccess.

I installed following this instructions:
http://goaccess.io/download#debian

But unfortunatelly, this .deb package was compiled without --enable-tcb=btree, which is necessary to make incremental log analises, right?

So, why not distribute with this functionality enabled?

PS: I know it is possible compile by the source code, [your instructions](http://goaccess.io/download#installation) works very fine.

PS2: I tried by myself to make a .deb package, but is too hard to me, I have no expertise for that. (https://wiki.debian.org/IntroDebianPackaging)

**Comment by bard** [comment]
@e-ruiz try this:

```
$ apt-get source goaccess
$ apt-get build-dep goaccess
```

You'll get a `goaccess-0.6` directory (or similar). Open the `debian/rules` file using your favorite text editor and add the following (careful that dh_auto_configure is preceded by a tab, not spaces):

```

override_dh_auto_configure:
	dh_auto_configure -- --enable-tcb=btree

```

And finally:

```
$ cd goaccess-0.6
$ dpkg-buildpackage -rfakeroot -uc -us
```

This should give you a .deb package ready to install.

**Comment by LeeNX** [comment]
Just run into an issue, where my 8GB server is not big enough to run goaccess report for a month.  
  
Believe btree on disk might help and having it shipped in the standard package would be awesome.

**Comment by allinurl** [comment]
@LeeNX I plan to add this, but first I need to automate the process of adding them to the repo in the least amount of steps. Right now it takes some time to do it, especially for three archs, `arm`, `i386` and `amd64` .

_BTW_, removing the query string `-q` can greatly decrease memory consumption, especially on timestamped requests. You can also use `-g` to use less memory when querying GeoIP data.

**Comment by LeeNX** [comment]
@allinurl Thank you for your damed quick reply!!  
  
Looking at around 150M requests to process for a month report, will test your above shortly and see how much info we might loose, else we will just have to rent a bigger VM for a report ... ;-)

**Comment by LeeNX** [comment]
v1.0 looking so awesome!! Thanks!!  
  
Was really hoping v1.0 would ship with --enable-tcb=btree already compiled in. ```lazy_guy``` ;-)

**Comment by JeroenVanOort** [comment]
Is there anything I, or anyone, can do to make this work?

Not so much from the lazy point of view, but more from the sysadmin view: having a dependency that is mainly used on larger projects compiled in really has an added value.

**Comment by allinurl** [comment]
Alright, I was able to work on this and I got to the point where building goaccess with `--enable-tcb=btree` won't take too long. I plan to start distributing goaccess with on-disk support. I'll post the package details pretty soon.

**Comment by JeroenVanOort** [comment]
Thanks! Looking forward to it.

**Comment by nutella** [comment]
Any ETA for this? Will be great for many sysadm ;)

Thanks...

**Comment by allinurl** [comment]
@nutella I've working on the next release so I haven't had much chance, but I'll have this over the weekend.

**Comment by allinurl** [comment]
It's finally here!!! Here are the details:

    $ echo "deb http://deb.goaccess.io/ $(lsb_release -cs) main" | sudo tee -a /etc/apt/sources.list.d/goaccess.list
    $ wget -O - https://deb.goaccess.io/gnugpg.key | sudo apt-key add -
    $ sudo apt-get update
    $ sudo apt-get install goaccess-tcb

**Note:** Since goaccess requires `libtokyocabinet9`, on-disk support is available from **Trusty+** or **Wheezy+**.

**Comment by allinurl** [comment]
Closing this.

**Comment by LeeNX** [comment]
@allinurl - Thanks, working very nicely, doing some crazy stuff again ... ;-)
