### ISSUE TITLE
Add header module with first and last log dates

### ISSUE THREAD

**Issue by eusonlito** [allinurl/goaccess#368]
It's a important information at first glance without need to expand detailed logs.

Thanks :)

**Comment by allinurl** [comment]
Not sure I follow, are you looking to display the first and last date within the visitors panel?

**Comment by eusonlito** [comment]
Something easy like this

![goaccess-date](https://cloud.githubusercontent.com/assets/644551/12868285/6c1fa012-cd03-11e5-8b99-832db7d4bf14.png)

**Comment by allinurl** [comment]
Got it. I can certainly add that. Thanks for the suggestion!

**Comment by allinurl** [comment]
This has been added.

It will be pushed out in the upcoming version! Otherwise, feel free to build from [development](http://goaccess.io/download#build). Thanks!
