### ISSUE TITLE
FAQ: has hyphens instead of spaces

### ISSUE THREAD

**Issue by srl295** [allinurl/goaccess#372]
Using goaccess 0.6 ( from ubuntu ) - the [FAQ](http://goaccess.io/faq)  lists under the nginx section:
```
time-format %T
date-format %d/%b/%Y
log-format %h %^[%d:%t %^] "%r" %s %b "%R" "%u"
```

but I had to make it time`_`format, date`_`format, log`_`format which matches what the [man page](http://goaccess.io/manual.php#custom-log) says. 

I think the hyphens are used in the command line options, but not the config file. Might consider accepting either.

Related: #136 #164

**Comment by allinurl** [comment]
Hyphenated variables were introduced in version 0.8.1+. So using `date-format` in the config file should be fine as long as you are using an updated version of goaccess. Prior versions use underscore.

I have updated the man page and added a note to the FAQ.

Thanks for pointing this out!

**Comment by srl295** [comment]
Welcome, and thank you!
