### ISSUE TITLE
Trying to use with WordPress on Apache

### ISSUE THREAD

**Issue by DaveyJake** [allinurl/goaccess#379]
I'm currently trying to setup GoAccess with the WordPress default debug.log file.

Is there a custom format for this already available or would I need to create one?

Please let me know.

**Comment by allinurl** [comment]
Is the `debug.log` in WordPress some sort of error log? If you have access log data, you may be able to use goaccess. Could you please post a few lines from your log? Thanks.

**Comment by DaveyJake** [comment]
It is the error log. Here are a couple lines as requested.

`[03-Feb-2016 15:01:13 UTC] PHP Deprecated:  Methods with the same name as their class will not be constructors in a future version of PHP; Sponsors_Pro_Random_Widget has a deprecated constructor in /www/sites/daveyjake/html/wp-content/plugins/wpcm-sponsors-pro/includes/widgets/sponsors-random.php on line 6`
`[03-Feb-2016 15:01:13 UTC] PHP Notice:  Undefined index: FTPHid in /www/sites/daveyjake/html/wp-content/plugins/ftp-access/ftp-access.php on line 32
`

**Comment by allinurl** [comment]
Thanks for posting this. GoAccess can process only server access log records, so it won't work for the error log.

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
