### ISSUE TITLE
Avoiding special run to initialize on-disk store?

### ISSUE THREAD

**Issue by bard** [allinurl/goaccess#382]
If I understand correctly, right now this is needed for incremental parsing:

```
goaccess -f first.log --keep-db-files
```

Followed by:

```
goaccess -f next.log --load-from-disk --keep-db-files
goaccess -f another.log --load-from-disk --keep-db-files
```

Is there a way to avoid the first invocation, and just have the store initialized if it doesn't exist already?

If not, is this a reasonable way of initializing the store?

```
goaccess -f /dev/null --db-path=/path/to/db  --keep-db-files
```

**Comment by allinurl** [comment]
I'm not sure I follow the use case, however, you should be able to do the following against the `first.log`

    goaccess -f first.log --load-from-disk --keep-db-files

If you just want to initialize the store, you could run goaccess as you posted above.

    goaccess -f /dev/null --keep-db-files

Just make sure you have a valid date/time/format in your config file so it won't complain about it.

**Comment by bard** [comment]
> I'm not sure I follow the use case, however, you should be able to do the following against the first.log

 >     goaccess -f first.log --load-from-disk --keep-db-files

With `first.log` I meant to say that this would be the first time that goaccess is run, so db files wouldn't exist, and if I understand the man page correctly, they need to exist before goaccess can be invoked with `--load-from-disk`, no?

```
       --load-from-disk
              Load previously stored data from disk. Database files need to exist. See keep-db-files.
```

**Comment by allinurl** [comment]
You can run goaccess for the first with `--load-from-disk`. e.g.,

    goaccess -f first.log --load-from-disk --keep-db-files

In fact, you can run goaccess as:

    goaccess -f first.log

It will create the database files even if they don't exist. Passing `--load-from-disk` for the first time, it's like a no-op.

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.

**Comment by bard** [comment]
Thank you! It works as you described. Perhaps it's worth checking that man page entry for ambiguity. Then again, if I'm the only one who's misunderstood, PEBKAC. :)

**Comment by allinurl** [comment]
Thanks. I have updated the man page and the site as well.
