### ISSUE TITLE
How to display the request's Virtual Host

### ISSUE THREAD

**Issue by viewpnt** [allinurl/goaccess#383]
When using virtual hosts, is there a way to see what virtual host the info belongs to?
For example, in the Top Request (URLs) panel, I can not see to which virtual host the top urls belongs to.

![unable-to-see-which-virtual-host-the-url-belongs-to](https://cloud.githubusercontent.com/assets/5809755/13457283/f58eec36-e02c-11e5-901e-762046b0f740.png)

**Comment by allinurl** [comment]
Good question. You have to do some pre-processing. For instance, for the following log line, we can do:

    vhost.com:80 104.131.40.139 - - [02/Mar/2016:08:14:04 -0600] "GET /shop/bag-p-20 HTTP/1.1" 200 6715 "http://www.vhost.com/shop/prod-c-4" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:44.0) Gecko/20100101 Firefox/44.0" 7861

You can parse it with goaccess as:

    awk '$8=$1$8' log | goaccess --log-format='%v:%^ %h %^[%d:%t %^] "%r" %s %b "%R" "%u" %D' --date-format='%d/%b/%Y' --time-format='%T'

which will output this:

![2016-03-02-083013_619x48_scrot](https://cloud.githubusercontent.com/assets/5005367/13463242/f9c34cce-e050-11e5-9142-dea5667aa042.png)

BTW, seems you are using the wrong log format. Feel free to post a few lines from your log and I can take look.

**Comment by viewpnt** [comment]
Hi:
Thank you for your time...

I'm using nginx, a sample of the log file is:
```
vhost.com 18X.7X.1X.13X - - [02/Mar/2016:20:19:39 -0600] - "GET / HTTP/1.1" 301 178 "-" "Mozilla/5.0 (compatible; Baiduspider/2.0; +http://www.baidux.com/search/spider.html)" "-" "-" 0.182 - .

anothervhost.com 20X.0.14X.17X - - [02/Mar/2016:20:18:12 -0600] - "GET / HTTP/1.1" 301 178 "-" "Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.2)" "-" "-" 0.000 - .
```
My nginx log format is:
```
log_format  main  '$host $remote_addr - $remote_user [$time_local] $upstream_cache_status "$request" ' 
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for" "$gzip_ratio" '
                      '$request_time $upstream_response_time $pipe';
```
And the goaccess.conf  formats:
```
time-format %H:%M:%S %z
date-format %d/%b/%Y
log-format %v %h - - [%d:%t] %^ "%r" %s %b "%R" "%u" "%^" "%^" %^ %T %^
```
After a lot of head scratching, I came up with that log-format line.

BTW: I see in a lot of examples the following for date:  %^ [%d:%^] 
what does it means? I think it means "ignore" date field, is it so?

Thank you for you valuable help.

**Comment by allinurl** [comment]
OK, the following should work:

    awk '$9=$1":"$9' log | goaccess --log-format='%v %h %^[%d:%t %^]%^"%r" %s %b "%R" "%u" "%^" "%^" %T %^' --date-format='%d/%b/%Y' --time-format='%T'

Yours was pretty close though. Seems you have an extra `%^` before `%T`.

About your question `%^[%d:%^] `. 

For the first `%^[` is telling the parser to ignore everything until it finds a `[`. This pattern is better than having `%h - - [` since one of those fields can actually be something else other than `-`, in that case, goaccess will treat this request as invalid.

For the second part (within the brackets), before, goaccess did not care about the time field, however, now it is required, so you must have `%t`.

**Comment by viewpnt** [comment]
Tank you for your help, everything is ok now.

**Comment by allinurl** [comment]
Glad that worked!
