### ISSUE TITLE
Query string not ignored when using query string specifier

### ISSUE THREAD

**Issue by tkirill** [allinurl/goaccess#384]
Hi!  First of all big thanks for such a great and easy to use tool!

I have a problem with not expected behavior of `-q` flag on v0.9.6. Consider this line from our nginx logs:

    2016-03-01T03:00:41+03:00	example.com	GET	/Login	a=b&c=d	123.123.123.123	Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36	302	0.263

`a=b&c=d` corresponds to [$args](http://nginx.org/en/docs/http/ngx_http_core_module.html#var_args) variable.  This is corresponding goaccess config:

    date-format %Y-%m-%d
    time-format %H:%M:%S
    log-format %dT%t+%^\t%^\t%m\t%U\t%q\t%h\t%u\t%s\t%T

`goaccess -p cfg -f sample -q` gives this URL in Top Requests table: `/Logina=b&c=d`.  There is no `?` between path and query string but even if we add it to the log we still get query string in the table (`/Login?a=b&c=d`).

Isn't it expected to omit what is matched by `%q` when `-q` parameter used?

And there is another little question with this situation.  I can move it to another issue if you want.  As you can see it is possible to have only arguments from query string without `?` in nginx logs.  Maybe add `?` to the content of `%q` in such situations?

**Comment by allinurl** [comment]
Hi, Currently, in order to avoid the overhead of adding the query string to every URL path and then removing it, it does the opposite. It will append it after it has checked that there's no query string to strip. I'm trying to understand the use case on this. Is there any reason why you would like to append it and then remove it?

As far as the question mark `?` at the beginning of the string, I can prepend it if the first character is not `?`. I don't recall if Apache's `%q` already contains `?`...

Thanks.

**Comment by tkirill** [comment]
> I'm trying to understand the use case on this. Is there any reason why you would like to append it and then remove it?

I just wanted to report that query string from `%q` is not removed with `-q` (no query string) parameter.  Here is my use case.  I was experimenting with reports and wrote `log-format` with `%q`.  Then I wanted to see what the report would be without query strings and applied `-q` parameter.  However, query string wasn't removed.

I agree, no real use case here.  After the report was tested I don't need `-q` argument because I have appropriate `log-format`.  So maybe there is no real problem here.

**Comment by allinurl** [comment]
The latest commit adds ensures the '?' is prepended to the query string if it's not present.

Thanks for pointing this out!
