### ISSUE TITLE
UWSGI log format

### ISSUE THREAD

**Issue by mhipo1364** [allinurl/goaccess#386]
Hi

I need some help about my log format, here is my log file which is generated by uwsgi:

`[pid: 22396|app: 0|req: 4924/39480] 193.151.131.150 () {40 vars in 741 bytes} [Sun Mar  6 22:56:30 2016] GET /tracks/14318/details => generated 2566 bytes in 45 msecs (HTTP/1.1 200) 7 headers in 241 bytes (2 switches on core 0)
`

but when I want to get report from `goaccess`, this error appears:

`Fatal error has occurred
 Error occured at: src/goaccess.c - main - 1017
 Nothing valid to process. Verify your date/time/log format.
`

Which format should I use?

**Comment by allinurl** [comment]
The following should work for the sample line you posted:

```
log-format %^] %h %^[%^ %d %t %^] %m %U %^(%H %s) %^
date-format %b %d
time-format %H:%M:%S
```

Let me know how it goes.

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.

**Comment by shreyasnagare** [comment]
> The following should work for the sample line you posted:
> 
> ```
> log-format %^] %h %^[%^ %d %t %^] %m %U %^(%H %s) %^
> date-format %b %d
> time-format %H:%M:%S
> ```
> Let me know how it goes.

This did not work for me. ERROR: 

```
Parsed 1 linesproducing the following errors:

Token 'Feb' doesn't match specifier '%d'

Format Errors - Verify your log/date/time format
```

My log file is in the following format:

```[pid: 2398|app: 0|req: 1075/3223] 128.237.158.26 () {44 vars in 634 bytes} [Mon Feb 18 16:36:03 2019] DELETE /api/apps/subscription => generated 24 bytes in 10 msecs (HTTP/1.1 200) 2 headers in 71 bytes (1 switches on core 0)
```
Can you suggest a [log format for uwsgi](https://uwsgi-docs.readthedocs.io/en/latest/LogFormat.html) which would work for goaccess but still log all the details?
