### ISSUE TITLE
License info is missing

### ISSUE THREAD

**Issue by janis-veinbergs** [allinurl/goaccess#387]
Hello.

It is not clear under which license this code is available. http://goaccess.io/ only states it is open source. However open source also has different licenses.

Please provide license info.

**Comment by allinurl** [comment]
Hello, you can find the license pretty much in every [file](https://github.com/allinurl/goaccess/blob/master/src/gkhash.c#L6) and the [COPYING](https://github.com/allinurl/goaccess/blob/master/COPYING) file. Should this be somewhere else? Thanks.

**Comment by janis-veinbergs** [comment]
Ahh, than you. I suppose it's ok then. Was kind of looking for LICENSE.txt (https://help.github.com/articles/open-source-licensing/). But I suppose this is OK and issue can be closed.

**Comment by allinurl** [comment]
@janis-veinbergs Actually I just deployed a big change. The license has been changed. 

**GoAccess is now under The MIT License (MIT).** 

You can find this within the source code and under  the COPYING file.
