### ISSUE TITLE
Feature: SSL connection and session cookie information

### ISSUE THREAD

**Issue by jamitupya** [allinurl/goaccess#391]
we log all connection information and include the protocol, cypher and other session data in nginx and IIS (e.g. $ssl_protocol/$ssl_cipher/$ssl_session_id/$ssl_session_reused). 

we would like to be able to see when users are still connecting with the insecure cyphers and protocols so we can see usage rates of these to understand adoption rates and other business needs

we use this with logging of cookies to see when we are being scraped and using goaccess would be much nicer

**Comment by allinurl** [comment]
Not sure how the output should look like... 

Could you please elaborate a bit more about the output you expect from goaccess? Also, can you post a few sample lines from your log containing these fields?

Thanks.

**Comment by jamitupya** [comment]
rethinking this i don't know how this would look either. might just build a ELK dashboard instead for this. thanks and i will close this.
