### ISSUE TITLE
about crontab issues

### ISSUE THREAD

**Issue by keithkuk** [allinurl/goaccess#392]
i want to know how to solve the problem when i use the time mission of crontab on centos to creat the html issues , the size of html is 0 .
but i can creat the html with running the goaccess command directly .

this's the shell on crontab  

```
#!/bin/bash
time=$(date +%Y%m%d)
commandStr=`goaccess -f /log/access_log.$time -p ~/.goaccessrc -a > /report/report--$time.html`
$commandStr
```

**Comment by allinurl** [comment]
Which version are you running?

You can also try this:

    commandStr=`cat /log/access_log.$time | goaccess -p ~/.goaccessrc -a > /report/report--$time.html`

**Comment by keithkuk** [comment]
GoAccess - 0.9.8

**Comment by keithkuk** [comment]
the version is GoAccess - 0.9.8

i try your suggest ,  the time mission of crontab creat the html size still be 0 .

**Comment by allinurl** [comment]
Your script does work on a debian machine. Tomorrow I can probably test this on a centos machine.

BTW, you can use `--no-progress` to avoid getting progress metrics. Also, does it work if you run the bash script directly (no through the cron)?

**Comment by keithkuk** [comment]
yes . i run the bash script on the terminal is work ! except the crontab mission . do you try on crontab with the bash script ? or just the command of the goaccess ?

**Comment by allinurl** [comment]
Both. I tried this through the cron and directly from the script. Either way worked fine.

**Comment by allinurl** [comment]
Sorry for the delay on this. I tested this on CentOS 6.5 and I noticed you need to specify the full path, so this worked:

    commandStr=`/usr/local/bin/goaccess -f /log/access_log.$time -p ~/.goaccessrc -a > /report/report--$time.html`

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
