### ISSUE TITLE
Please help me for nginx custom log format issue with goacccess

### ISSUE THREAD

**Issue by miteshwalker** [allinurl/goaccess#394]
Please find my log output for nginx (access.log)

    182.69.143.120 - - [31/Mar/2016:03:10:51 +0530] "GET /api/check_delivery.php?authkey=9450AW2qTKYe453be757c&requestid=36626f6a3530323439383831 HTTP/1.1" control.msg91.com 404 39 "-" "-" "-" "control.msg91.com" "-" to: 10.0.0.62:8080: upstream_response_time 0.003 request_time 0.003

My nginx custom log format :

> $remote_addr - $remote_user [$time_local] "$request" $host'
>                       '$status $body_bytes_sent "$http_referer" '
>                       '"$http_user_agent" "$http_x_forwarded_for" "$server_name"';

and my which i am using in goaccess conf file:

```
time-format %H:%M:%S
date-format %d/%b/%Y
log_format %^[%d:%^] "%r" %s %b "%R" "%u" "%^ %h"
```

and after running this I am getting below error:

```
GoAccess - version 0.9.8 - Mar 31 2016 14:11:22
Config file: /usr/local/etc/goaccess.conf

Fatal error has occurred
Error occured at: src/goaccess.c - main - 1017
Nothing valid to process. Verify your date/time/log format.
```

Please help me out... 
thanks in advance

**Comment by allinurl** [comment]
It seems like the sample log does not match the fields you posted from nginx. After `$body_bytes_sent` there is `"$http_referer"` and `"$http_user_agent"`, then there are a bunch of other fields within quotes?

**Comment by jamitupya** [comment]
i think for your log format this should work;

log_format %h %^ %^ [%d:%t %^] "%r" %v %s %b "%R" "%u" "%^" "%v"  
or
log_format %h %^ %^ [%d:%t %^] "%m %r %H" %v %s %b "%R" "%u" "%^" "%v"

however thats not the log file you have posted.  
this is in the logs also;
"-" to: 10.0.0.62:8080: upstream_response_time 0.003 request_time 0.003

try this;
log_format %h %^ %^ [%d:%t %^] "%r" %v %s %b "%R" "%u" "%^" "%v" "%^" %^ %^:%^: %^ %^ ^% %L  (maybe this works, i'm not 100% sure given the log line provided)

**Comment by miteshwalker** [comment]
Thanks a lot "jamitupya" this entry worked for me:
 log_format %h %^ %^ [%d:%t %^] "%r" %v %s %b "%R" "%u" "%^" "%v"

**Comment by lavanyapallapa** [comment]
Can you please help me with logformat for this:

192.187.110.98 - - [10/Aug/2015:05:51:30 +0000] GET /general/pc/skin HTTP/1.1 "200" 11048 "https://test.test.com/?" "Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; Trident/5.0)" "-"

**Comment by allinurl** [comment]
@lavanyapallapa Try this:

    log-format %h %^[%d:%t %^] %m %U %H "%s" %b "%R" "%u" %^
    date-format %d/%b/%Y
    time-format %T

**Comment by lavanyapallapa** [comment]
Thank you so much.

It worked.

**Comment by singleseeker** [comment]
36.36.121.239 - - [2017-04-05T00:00:12+08:00] "GET /merger?page=3 HTTP/1.1" 200 49913 "https://www.itjuzi.com/merger?page=3" "Mozilla/5.0 (comp
atible; Baiduspider/2.0; +http://www.baidu.com/search/spider.html)" 101.200.106.10 3.020

Any idea about this>? @allinurl

**Comment by allinurl** [comment]
@singleseeker This should work:

```
log-format %h %^[%dT%t+%^] "%r" %s %b "%R" "%u" %^ %T
date-format %Y-%m-%d
time-format %H:%M:%S
```

**Comment by aledbf** [comment]
@allinurl can you help with this custom nginx format?

```
$remote_addr - [$proxy_add_x_forwarded_for] - $remote_user [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent" $request_length $request_time [$proxy_upstream_name] $upstream_addr $upstream_response_length $upstream_response_time $upstream_status
```
sample:
```
35.160.156.22 - 100.96.7.0 - - [27/Apr/2017:13:24:49 +0000] "GET /system/search?query=5682097-3&_=1493299482749 HTTP/1.1" 200 231 "https://my-site.com/" "Mozilla/5.0 (Windows NT 6.1; Trident/7.0; rv:11.0) like Gecko" 599 0.081 100.66.17.56:80 231 0.081 200
```

I already tried distinct format like the next one without success:

```
log-format %h - [%^] - %^ [%d:T%t+%^] "%m %U %H" %s %b "%R" "%u" %^ %T %^ %^ %^ %^
```

Thanks in advance!

**Comment by allinurl** [comment]
@aledbf 

Please try this:

    goaccess log --log-format='%h %^[%d:%t %^] "%r" %s %b "%R" "%u" %^ %T %^' --date-format=%d/%b/%Y --time-format=%T

**Comment by aledbf** [comment]
@allinurl it works. Thanks!

**Comment by dkelbley** [comment]
I have the following NGINX custom log format:
    log_format main '$remote_addr - $remote_user [$time_local]  '
                    '"$request" $status $body_bytes_sent '
                    '"$http_referer" "$http_user_agent" $request_time';

However, I can't get the following syntax to work:
goaccess -f access.log --log-format='%h %^[%d:%t %^] "%r" %s %b "%R" "%u" %T^' --date-format=%d/%b/%Y --time-format=%T

Sample data:
157.55.39.73 - - [29/Jun/2017:00:00:13 -0500]  "GET /channels/usa/photos/2015.jpg HTTP/1.1" 200 15356 "-"

Any thoughts on what I'm doing wrong?
