### ISSUE TITLE
Parsing custom log format

### ISSUE THREAD

**Issue by beloha** [allinurl/goaccess#395]
Hi there!
I need to perform some stats on nginx logs that are provided to me as follows:

`192.168.1.1 -> 192.168.1.2:80 [2016-03-21T06:46:24+0200] "GET /my-app?key1=value1&key2=value2 HTTP/1.1" 200 154 "-" "Java/1.6.0_38" 0.004 0.004`

or as follows in case of failover  

`192.168.1.1 -> 192.168.1.2:80, 192.168.1.3 [2016-03-21T06:46:24+0200] "POST /my-app HTTP/1.1" 502 166 "-" "Java/1.6.0_38" 0.001 0.001, 0.000`

where: 
- 192.168.1.1 is the client application IP
- 192.168.1.2 is one upstream
- 192.168.1.3 is an other upstream 

For the 1st case (let's try to work iteratively...) I tried to configure goaccess with:
- time-format %H:%M:%S%z
- date-format %Y-%m-%d
- log-format %h -> %v %^[%dT%t%^] "%r" %s %b "%R" "%u" %^ %^

Unfortunately I always have the "Nothing valid to process. Verify your date/time/log format." error.
Am I missing something ?

I've goaccess 0.9.8 (re-compiled).
thanks for your help and your time.

**Comment by beloha** [comment]
This configuration works for the 1st case:
- time-format %H:%M:%S%z
- date-format %Y-%m-%d
- log-format %h -> %v [%dT%t] "%r" %s %b "%R" "%u" %^ %^

I'll try to dig more to have it working for the second case

**Comment by beloha** [comment]
well, in fact it works properly. Auto resolve ;-)

**Comment by allinurl** [comment]
Glad that worked. BTW, you could use the following to get `%T` and ignore the two other IPs,

    %h %^[%dT%t] "%r" %s %b "%R" "%u" %T %^
    %Y-%m-%d
    %H:%M:%S%z

**Comment by beloha** [comment]
OK thanks for the tip.
I'll keep the virtual host information, this information provides me the percentage of load in case of failover. So it's valuable for the stats ;-).

my final configuration is following:
`log-format %h -> %v [%dT%t] "%r" %s %b "%R" "%u" %T %^`

**Comment by stockrt** [comment]
I will leave this conversion script here in case someone is looking for how to convert from Nginx log_format config directive to goaccess config: https://github.com/stockrt/nginx2goaccess

**Comment by allinurl** [comment]
@stockrt This is great, thanks for sharing!
