### ISSUE TITLE
Number of analyzed requests vs HTTP status code

### ISSUE THREAD

**Issue by beloha** [allinurl/goaccess#396]
Hello there!

I've created an HTML version of a report.
Under the "Overall Analyzed Requests" I can find the number of valid request among the total request:

> 227 381 / 297 750

I've checked in my nginx logs and indeed I have 297 750 lines.

However, under the "HTTP Status Codes" section, I cannot find the same number:

Visitors	| Hits | %	Bandwidth [ Avg. T.S. | Cum. T.S. | Max. T.S | Status Codes
-------------| ------ | ------------------ | ------------ | -------------- | ------------ | ------------------
32 |	194 435 |	85,51%	| 264,32 MiB| 	1,19  s |	2,69  d| 	1,94 mn |	2xx Success
0	| 19 138| 	8,42%	| 3,37 MiB| 	57,46  s| 	9,27  d| 	2,32 mn| 	4xx Client Error
11| 	11 326| 	4,98%| 	1,98 MiB| 	10,80  s| 	15,16 hr| 	2,76 mn| 	5xx Server Error
31| 	2 482| 	1,09%| 	27,97 MiB| 	2,37 mn| 	4,08  d| 	2,99 hr| 	1xx Informational

I there a reason why I cannot find all my request under the "HTTP Status Codes" section ?

**Comment by beloha** [comment]
Btw, I can see that I have 

>  Failed Requests
> 70 369

So probably, it means that all request are present in the table.

**Comment by beloha** [comment]
Does "Failed Request" mean lines of logs that cannot be parsed ?

**Comment by allinurl** [comment]
That's right, a failed request means it could not be parsed. You can dump all these requests to a log by passing `--invalid-requests=invalids.log`

**Comment by beloha** [comment]
I've found this post that helped me: https://github.com/allinurl/goaccess/issues/295

In fact, due to failover, I sometimes have logs that looks like following:

> 192.168.1.1 -> 192.168.1.2:80, 192.168.1.3:80, a_internal_hostname [2016-03-21T10:02:33+0200] "POST /my-app HTTP/1.0" 502 166 "-" "Java/1.6.0_38" 0.005 0.000, 0.005, 0.000

**Comment by beloha** [comment]
btw, is regexp allowed in log-format ?

**Comment by allinurl** [comment]
Regexp is not allowed in the log-format. Feel free to look at the [custom log fields](http://goaccess.io/man#custom-log) for more info.

Also, you can [build](http://goaccess.io/man#configuration) goaccess using `--with-getline` to parse full line requests instead of a fixed size buffer of 4096.
