### ISSUE TITLE
help with log/time/date format with a custom apache log format

### ISSUE THREAD

**Issue by stefandewal** [allinurl/goaccess#397]
Hi,

i've tested multiple log-format, time-format and date-format but it always returns that i have to check my formats when running goaccess

can some pleas tell my to put in goaccess.conf when i have this logformat in apache:

    LogFormat "%h %v %{%d-%m-%Y %H:%M:%S}t \"%r\" %b \"%{Referer}i\" \"%{User-Agent}i\"" combined

**Comment by allinurl** [comment]
Could you please post a few sample lines from your access log? Thanks.

**Comment by allinurl** [comment]
The following should work give the format above:

    log-format %h %v [%d %t] "%r" %s %b "%R" "%u"
    date-format %d-%m-%Y
    time-format %T

Feel free to reopen if needed.
