### ISSUE TITLE
Show all Visitor Hostnames and IPs

### ISSUE THREAD

**Issue by ejazhashmi** [allinurl/goaccess#401]
Hi,

I want to enable to show all the unique IPS in Hosts sections, currently it shows only Top visitor hosts sorted by hits [, avgts, cumts, maxts]

Can you please guide me how to do it 

Regards
Syed Ejaz

**Comment by allinurl** [comment]
You are correct, right now it shows only the top 366 IPs. Issue #39 will address this in v1.0 (which hope to release soon). However, it will be only available for static reports, e.g., CSV, JSON. 

The reason for that is that displaying all records in real-time output, would considerably degrade the performance of it.

Stay tuned for v1.0 :)

**Comment by allinurl** [comment]
Closing it since  **#39** should address this. Thanks!
