### ISSUE TITLE
Single pass - multiple outputs

### ISSUE THREAD

**Issue by nvtkaszpir** [allinurl/goaccess#402]
It would be awesome to be able to specify multiple formats with information where to output that data.
This way it would be possible to process logs once and get three different output files.

Right now getting html, csv and json output requires parsing the same input three times.
Trying to paralelize it is usually problematic due to memory constraints.

I know this feature would break current functionality (output to stdout).
(I haven't tried on-disk storage, using default in-memory)

**Comment by allinurl** [comment]
Thanks for the suggestion. 

Outputting multiple files formats will be addressed in issue **#343**, the plan is to output an HTML file, and have a UI option to output a CSV or the raw JSON. Thoughts?

As far as parsing multiple log formats and outputting it to one single file, will be added by issue **#213**.

**Comment by nvtkaszpir** [comment]
I think #53 has a good idea about adding `-o file.html`.
Embedding json/csv within html would be an option, but then it would require to add extra tools to extract it from it.

My current use case is to process logs from AWS ELB, that's something about 10~15GB per day. In-memory data storage uses something about 8 ~10GB, and so far memory is a major concern when doing stuff in parallel.

That's why multiple outputs on single pass would be ideal, of course to certain degree.

I also complied goaccess with on-disk storage with default settings - it is something like 4x slower than in memory (no wonder). So now I can parse it slowly once and use database for different formats, or I can execute all three output formats in parallel - much faster but for the cost of memory.

i haven't got time to play with extra parameters for on-disk storage, maybe for the price of memory I could just make things much faster.

Of course for parsing large data sets like month it will require on-disk storage, but then usually it is not needed to get it very fast.

**Comment by allinurl** [comment]
I can certainly look into it and hope I can ship this in v1.0. It shouldn't be too difficult to have this implemented since all outputs consume the same data structure.

As far as the on-disk storage. It's definitely slower than the default storage. As you said, playing with `--cache-*` and `--tune-` can help. At some point, I'll go over this storage and see what can be done to speed it up (keeping in mind that data has to be committed to disk).

**Comment by nvtkaszpir** [comment]
Playing with on-disk storage options really requires deeper knowledge about Tokyo Cabinet in general. From what I have quickly scanned over the internet it usually drills down to the issues with journaled file system beneath. Would need expansion of the docs and some tests.

**Comment by allinurl** [comment]
Added the ability to output multiple formats in one run.

In addition, it standardizes the output per issue #53. For instance,
it now supports the following.

goaccess -f access.log -o /www/file.html
goaccess -f access.log -o /www/file.csv
goaccess -f access.log -o /www/file.json

For backwards compatibility, it still supports the following format: 

goaccess -f access.log > /www/file.html
goaccess -f access.log -o csv > /www/file.csv
goaccess -f access.log -o json > /www/file.json

**Comment by nvtkaszpir** [comment]
does it mean it supports something like this?
```
goaccess -f access.log -o /www/file.html -o /www/file.csv -o /www/file.json
```

**Comment by allinurl** [comment]
That's correct.

**Comment by nvtkaszpir** [comment]
awesome :D
