### ISSUE TITLE
List of geoip deps on GoAccess download/install page for Slackware...

### ISSUE THREAD

**Issue by tallship** [allinurl/goaccess#403]
Thought that I would add some info on GoAccess on Slackware, since this distro isn't mentioned  in the docs and I use GoAccess all the time... so I figured it would be nice to see it listed here.

The list of dependencies for the optional geoip built in at compile time is "GeoIP" for Slackware. For arch, it is listed as "geoip", but for Slackware it is the case sensitive incarnation of maxmind's GeoIP.

The package can be built from the SlackBuild script at:
https://slackbuilds.org/repository/14.1/system/goaccess/?search=goaccess

To build/install with GeoIP, simply pass the following:

    GEOIP=yes ./goaccess.SlackBuild # requires "GeoIP" 

NOTE: to install version 0.9.8 at this time simply change the version number in goaccess.SlackBuild. You must have goaccess-0.9.8.tar.gz in that directory with the .SlackBuild file.

From https://goaccess.io/download (graphic below):

![goaccess-geoip_dep](https://cloud.githubusercontent.com/assets/561994/14655381/e9954dbe-0636-11e6-87b2-51cf73325d13.png)

**Comment by tallship** [comment]
I should probably also include the info on Tokyo Cabinet - 

In Slackware, it is "tokyocabinet" and can be found/built/installed from here:
https://slackbuilds.org/repository/14.1/system/tokyocabinet/

I hope this helps :)

**Comment by allinurl** [comment]
Thanks for posting this. Very helpful!

I have updated the **[download page](https://goaccess.io/download)**, please let me know if it looks right.

**Comment by allinurl** [comment]
Assuming everything looks right. Closing this. Feel free to reopen it if needed.

Thanks again!
