### ISSUE TITLE
Logformat - Apache - ELB

### ISSUE THREAD

**Issue by Asshad** [allinurl/goaccess#404]
Hi there,

I'd like to inquire, I'm facing this issue to generate the output, "Nothing valid to process".
I have done some tweaks on the format but nothing works. Could you please advise?

    Logformat "\"%t\",\"%{X-Forwarded-For}i\",\"%r\",\"%b\",\"%T\",\"%>s\",\"%{Referer}i\",\"%{User-Agent}i\",\"%h\",\"%l\"" LogCustom

**Comment by allinurl** [comment]
Could you please post a few lines from your access log?Thanks.

**Comment by Asshad** [comment]
Thanks for your reply.
Sure, please refer to the those lines. Thanks in advance.

HTTP/1.1","753","0","200","-","Amazon CloudFront","172.18.211.77","-"
"[09/Apr/2016:03:34:58 +0000]","202.74.105.71, 54.640.147.42","GET /wp-content/uploads/2015/11/sfit_fitdialysis2211_py_2-e1448115793203-190x140.jpg HTTP/1.1","-","0","304","-","Amazon CloudFront","172.18.212.88","-"

"[09/Apr/2016:03:34:59 +0000]","203.117.19.195, 54.240.148.89","GET /wp-content/uploads/2015/10/str2_shariljihadistR_ma_1_FORONLINE-100x80.jpg HTTP/1.1","-","0","304","-","Amazon CloudFront","172.18.212.88","-"

"[09/Apr/2016:03:34:57 +0000]","66.249.64.182, 54.240.144.76","GET /entertainment/movies/movie-news/2015/12/16/tedd-chan-keeps-things-fresh-in-whos-your-daddy/ HTTP/1.1","21012","2","200","-","Amazon CloudFront","172.18.212.142","-"

**Comment by allinurl** [comment]
The following should work. 

    log-format "[%d:%t %^]","%h,%^","%r","%b","%T","%s","%R","%u"%^
    date-format %d/%b/%Y
    time-format %H:%M:%S

Let me know how it goes.

**Comment by Asshad** [comment]
Hi, just tried your suggestion, processing for a few seconds then prompt the same out again.

$ goaccess --log-format="[%d:%t %^]","%h,%^","%r","%b","%T","%s","%R","%u"%^ --date-format=%d/%b/%Y --time-format=%H:%M:%S -f ~/Desktop/www.serverlist.com-access_log-20160409

Fatal error has occurred
Error occured at: src/goaccess.c - main - 1033
Nothing valid to process.

**Comment by allinurl** [comment]
Please use single quotes within the log-format

    $ goaccess --log-format='"[%d:%t %^]","%h,%^","%r","%b","%T","%s","%R","%u"%^'

**Comment by Asshad** [comment]
Dandy, it works now. Thanks a lot. You are super awesome!

**Comment by allinurl** [comment]
Glad that worked! 

Stay tuned for the upcoming version!!
