### ISSUE TITLE
XSS

### ISSUE THREAD

**Issue by coruws** [allinurl/goaccess#405]
`cat /var/log/nginx/access.log | goaccess -a > report.html`
then in table `2 - Requested files (Pages-URL)` i see value 
`<td class="d1">/?search=<script>alert(1)</script></td>`
which is executed as a code

**Comment by allinurl** [comment]
Thanks for reporting this. Which version are you using?

**Comment by coruws** [comment]
GoAccess - 0.5

**Comment by allinurl** [comment]
This issue was addressed back in [v0.6](https://github.com/allinurl/goaccess/blob/master/ChangeLog#L320). Please upgrade to the [latest version](https://goaccess.io/download). Also, feel free to use the official [deb repo](https://goaccess.io/download#official-repo).
