### ISSUE TITLE
Please add command-line shortcut for standard log formats

### ISSUE THREAD

**Issue by amichair** [allinurl/goaccess#406]
Currently, one can either specify the full log/date/time format using command-line options, or use the config-dialog option to show the dialog from which several standard formats can be selected. However, the latter only works interactively, and specifically it doesn't work when piping the logs into goaccess (e.g. using zcat with wildcards) - which is extremely common since many systems have log rotation on by default.

It would be useful to add a command line option for selecting one of the standard formats, or maybe reuse the existing log-format option for this, e.g. log-format=combined. This would make it play much better with scripts, aliases, etc. This should of course also imply the date-format and time-format if they are not specified.

Thanks for this awesome tool!

**Comment by allinurl** [comment]
Thanks for the suggestion! I can certainly add this. I hope I can squeeze it on v1.0.

**Comment by allinurl** [comment]
This has been implemented and deployed in [version 1.0](https://goaccess.io/). Thanks!
