### ISSUE TITLE
Please add command-line option to enable a panel

### ISSUE THREAD

**Issue by amichair** [allinurl/goaccess#407]
There is currently an ignore-panel option, but no complementary option for enabling a panel. If all panels were enabled by default this would not be a problem, but in many cases (e.g. when installing on Ubuntu from the standard or goaccess repository) the default configuration disables some of the panels. So please add a command-line option to quickly override this and re-enable them.

**Comment by allinurl** [comment]
Sounds totally doable. I'll work on this. Thanks for posting it.
