### ISSUE TITLE
GoAccess log format for Amazon Simple Storage Service (S3) 

### ISSUE THREAD

**Issue by ahmaddev313** [allinurl/goaccess#408]
Hi,  

I am running goaccess 0.8.5 (this is the latest that can be used with the s3stat python script).  When running via the Python script, or running directly from goaccess I get the following:

```
[ec2-user@ip-XX-XXX-X-XXX goaccess-0.8.5]$ goaccess -f /home/ec2-user/2016-05-04-13-21-15-780444E7C9B1400B.txt

GoAccess - version 0.8.5 - May  4 2016 18:03:56

Fatal error has occurred
Error occured at: goaccess.c - main - 832
Nothing valid to process.
```

This is the what is in the log that I am pointing to (replaced some numbers and letters for security purposes, but kept the same exact format).  BTW, this is a S3/CloudFront log:

    0a318c25bf6098da13317f8e00aeddec696bbfa592d54df1ec849fd99627de75 sco-download-files [04/May/2016:12:11:43 +0000] 22.222.22.22 arn:aws:iam::992889131628:user/firstname.lastname@company.com 8D6CECF94EE0ACBD REST.GET.BUCKET - "GET /sco-download-files?prefix=downloads/fixpacks/&max-keys=100&marker=downloads/fixpacks/company-9.0.0.8151.zip&delimiter=/&encoding-type=url HTTP/1.1" 200 - 37728 - 114 113 "-" "S3Console/0.4" -

In the goaccess.conf file I tried both without editing the file and with the following options:

```
date-format %Y-%m-%d
log-format %d\t%^\t%^\t%b\t%h\t%m\t%^\t%r\t%s\t%R\t%u\t%^
```

I have uncommented this for both goaccess.conf file just in case.  

I am stuck and not sure how to proceed.  Any ideas?

Thank you.

**Comment by allinurl** [comment]
Are your log entry delimited by spaces or tabs?

**Comment by ahmaddev313** [comment]
According to Amazon's doc about 'Log File Format' it states:
"Contain tab-separated values."

http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/AccessLogs.html#LogFileFormat

**Comment by allinurl** [comment]
It seems your log is a bit different than the ones on the amazon site. 

Could you  please explain the fields on your log. It's not clear, especially the ones at end of the string `- 37728 - 114 113 "-" "S3Console/0.4" -` .

Thanks.

**Comment by ahmaddev313** [comment]
Hi.
According to Amazon's doc they show the "S3Console/0.4" in their example log format at the very top section of the page:
http://docs.aws.amazon.com/AmazonS3/latest/dev/LogFormat.html

For the delimiter I think I was wrong previously as this doc states:

"The server access log files consist of a sequence of new-line delimited log records. Each log record represents one request and consists of space delimited fields. The following is an example log consisting of six log records."

This is the log example they have and the format looks just like my logs:

79a59df900b949e55d96a1e698fbacedfd6e09d98eacf8f8d5218e7cd47ef2be mybucket [06/Feb/2014:00:00:38 +0000] 192.0.2.3 79a59df900b949e55d96a1e698fbacedfd6e09d98eacf8f8d5218e7cd47ef2be 3E57427F3EXAMPLE REST.GET.VERSIONING - "GET /mybucket?versioning HTTP/1.1" 200 - 113 - 7 - "-" "S3Console/0.4" -
79a59df900b949e55d96a1e698fbacedfd6e09d98eacf8f8d5218e7cd47ef2be mybucket [06/Feb/2014:00:00:38 +0000] 192.0.2.3 79a59df900b949e55d96a1e698fbacedfd6e09d98eacf8f8d5218e7cd47ef2be 891CE47D2EXAMPLE REST.GET.LOGGING_STATUS - "GET /mybucket?logging HTTP/1.1" 200 - 242 - 11 - "-" "S3Console/0.4" -
79a59df900b949e55d96a1e698fbacedfd6e09d98eacf8f8d5218e7cd47ef2be mybucket [06/Feb/2014:00:00:38 +0000] 192.0.2.3 79a59df900b949e55d96a1e698fbacedfd6e09d98eacf8f8d5218e7cd47ef2be A1206F460EXAMPLE REST.GET.BUCKETPOLICY - "GET /mybucket?policy HTTP/1.1" 404 NoSuchBucketPolicy 297 - 38 - "-" "S3Console/0.4" -
79a59df900b949e55d96a1e698fbacedfd6e09d98eacf8f8d5218e7cd47ef2be mybucket [06/Feb/2014:00:01:00 +0000] 192.0.2.3 79a59df900b949e55d96a1e698fbacedfd6e09d98eacf8f8d5218e7cd47ef2be 7B4A0FABBEXAMPLE REST.GET.VERSIONING - "GET /mybucket?versioning HTTP/1.1" 200 - 113 - 33 - "-" "S3Console/0.4" -
79a59df900b949e55d96a1e698fbacedfd6e09d98eacf8f8d5218e7cd47ef2be mybucket [06/Feb/2014:00:01:57 +0000] 192.0.2.3 79a59df900b949e55d96a1e698fbacedfd6e09d98eacf8f8d5218e7cd47ef2be DD6CC733AEXAMPLE REST.PUT.OBJECT s3-dg.pdf "PUT /mybucket/s3-dg.pdf HTTP/1.1" 200 - - 4406583 41754 28 "-" "S3Console/0.4" -
79a59df900b949e55d96a1e698fbacedfd6e09d98eacf8f8d5218e7cd47ef2be mybucket [06/Feb/2014:00:03:21 +0000] 192.0.2.3 79a59df900b949e55d96a1e698fbacedfd6e09d98eacf8f8d5218e7cd47ef2be BC3C074D0EXAMPLE REST.GET.VERSIONING - "GET /mybucket?versioning HTTP/1.1" 200 - 113 - 28 - "-" "S3Console/0.4" -

The "S3Console/0.4" is apparently the 'HTTP user-agent header'.  The link gives a break down of what each piece in the logs represents.  

So the snippet you asked about should be the following according to the link:

The first "-" indicates there were no "Error Code" for the GET portion of the copy operation.
"37728" is the "Bytes Sent".
The next "-" seems to indicate "Object Size"... I think.  
"114" seems to be the "Total Time" in ms.
"113" seems to be the "Turn-Around Time" in ms.
The 3rd "-" from the your snippet seems to be the "Referrer".  I guess it could not determine it and therefore puts a dash.
"S3Console/0.4" seems to be the "User-Agent".
And the last "-" is supposed to be "Version Id" if one exists.  

When I enabled logging I did not choose any other options.  Actually I don't think I saw any other options.  So right now I pretty much just have default logging enabled, but my log seems to be consistent with what Amazon shows in their doc.

Thank you for your help!

**Comment by allinurl** [comment]
This should work (>= v0.9):

```
log-format %^[%d:%t %^] %h %^"%r" %s %^ %b %^ %L %^ "%R" "%u"
date-format %d/%b/%Y
time-format %H:%M:%S
```

For previous versions, (although, highly recommended to upgrade) you don't need the `time-format`, so you can use:

```
log-format %^[%d:%^] %h %^"%r" %s %^ %b %^ %L %^ "%R" "%u"
date-format %d/%b/%Y
```

Let me know how it goes.

**Comment by ahmaddev313** [comment]
I would have installed the latest but according to s3stat they only support up to v.8.5.
https://pypi.python.org/pypi/s3stat

**Comment by allinurl** [comment]
I see. In that case, you will need to use the second version.

**Comment by ahmaddev313** [comment]
The second version seemed to work!  Thank you very much for your help!

**Comment by allinurl** [comment]
Great! Closing this. Feel free to reopen it if needed.

**Comment by ahmaddev313** [comment]
Hi,
I just wanted to add to this just in case this may benefit anyone who reads it.  

I was able to go back and just use the default 'log-format' and 'date-format' in the goaccess.conf file.

So there are two types of logging that you can enable.  There is one for CloudFront and for S3.  These are completely two different types of logging.  In the issue I was having and the log snippets I was showing previously these were S3 logging, and not CloudFront logging.  The type of info and log format are different for the two. 

After I correctly enabled CloudFront logging (takes up to 12 hours before it kicks in) then I was able to used the CloudFront 'log-format' and 'date-format' that is already in goaccess.conf file.  

That was the difference... hope helps you and anyone else that reads this in the future.

Thank you.
Ahmad

**Comment by abdennour** [comment]
Sometimes, you need to not stick with specific technology: 

```bash
s3 sync s3://my-log-bucket/ logs/
gem install request-log-analyzer
request-log-analyzer -f amazon_s3 --output html --file report.html logs/my-bucket*
open report.html # OSX users
```
