### ISSUE TITLE
Update apt repository packages signature to SHA256 or SHA512

### ISSUE THREAD

**Issue by eusonlito** [allinurl/goaccess#409]
Current error in Ubuntu Xenial repository:

```
W: http://deb.goaccess.io/dists/xenial/InRelease: Signature by key FA0BF24A0F9463670B880EAB742483B7B222C443 uses weak digest algorithm (SHA1)
```

Related information https://wiki.debian.org/Teams/Apt/Sha1Removal

**Comment by allinurl** [comment]
This has been fixed. Please let me know if everything looks right on your side.

Thanks for reporting it!

**Comment by eusonlito** [comment]
Fixed. Thanks!
