### ISSUE TITLE
Geo Location continents' average time served is sum of countries'

### ISSUE THREAD

**Issue by plusCubed** [allinurl/goaccess#412]
Each continent's "average time served" is calculated as the sum of the average time served of each country, rather than the average time served of requests from that continent.

e.g. 
```
North America: Avg T.S: 2.0 s
 |-US Avg T.S: 500 ms
 |-Canada Avg T.S: 500 ms
 |-Mexico Avg T.S:1000 ms
```

**Comment by allinurl** [comment]
If I understand correctly, the continent "average time served" should be:

    sum of the average time served of each country / number of countries within the continent

OR

    (1000 + 500 + 500) / 3

Is that right?

**Comment by plusCubed** [comment]
I don't think that would be correct - that would be the average of averages, in this case putting 1/3 weight on each country's average. I believe what you would need to do is either 

Redo the calculation:
`total time of all requests to continent / total number of requests to continent`

or use the number of requests to each country as the weight (which is really just extrapolating the total time and doing the same thing): 
(`{Country A # of requests} * {Country A average time served} + {B request #} * {B avg t.s.} ... )   / {sum of # of requests of all countries}`

**Comment by allinurl** [comment]
Make sense, so it should yield to the following output:

    Continent Avg. T.S. = (Continent Cum. T.S. /  Continent Hits)

```
 Hits Vis.       %   Bandwidth Avg. T.S. Cum. T.S. Max. T.S. Data                                             
│ ---- ---- ------- ----------- --------- --------- --------- ----                                             
│ 3       2 100.00%    2.62 KiB 318.00 us 956.00 us 702.00 us NA North America                                 
│ 2       1  66.67%   954.0   B 326.00 us 653.00 us 399.00 us  ├─ US United States                             
│ 1       1  33.33%    1.68 KiB 303.00 us 303.00 us 303.00 us  ├─ CA Canada 
```

**Comment by allinurl** [comment]
Alright, this has been fixed according to my previous post.

Closing this. Feel free to reopen it if needed. Thanks for reporting it!
