### ISSUE TITLE
Why my `time served` is not right?

### ISSUE THREAD

**Issue by yhl3692319** [allinurl/goaccess#416]
## my ~/.goaccessrc and /etc/goaccess.conf are like this
```
time_format %H:%M:%S
date_format %d/%b/%Y
log_format %h %^[%d:%t %^] "%r" %s %b "%R" "%u" %^ %T
```
## nginx log
```
10.150.47.138 - - [23/Oct/2014:19:16:23 -0200] "GET /file.php?cid=127 HTTP/1.1" 200 2972 "-" "Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1"3.076
10.150.47.138 - - [23/Oct/2014:19:16:23 -0200] "POST /file.php?cid=127 HTTP/1.1" 200 2947 "-" "Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1)"3.977
```
the time unit of nginx log is second

## excute
`goaccess -p /etc/goaccess.conf -f nginx.log -a >test.html`

and the html shows wrong time server like this
```
Visitors	Hits	%	 Bandwidth	  Avg. T.S.	Cum. T.S.	Max. T.S.	Protocol	Method	Requests 
574	  507,926	 31.64%	33.82 MiB	2.81 mn	992.70  d	16.65 mn	HTTP/1.1	GET	/xxx
2,097	506,768	31.56%	62.84 GiB	3.16 mn	1110.85  d	16.65 mn	HTTP/1.1	GET	/xxx
232	121,294	7.55%	2.40 GiB	5.49 mn	462.58  d	16.65 mn	HTTP/1.1	GET	/axxxx/
```

## what does mn mean ? and is my log format wrong?

**Comment by yhl3692319** [comment]
thx, and i have another question

## what does this mean?

![image](https://cloud.githubusercontent.com/assets/12122851/15360414/0355a59e-1d40-11e6-98c9-fb281b2ee301.png)

`during 18/Dec/2010, it has 1138 visitors asked the website and created 14351 hits, the whole bandwidth is 188.48M, the avg time of each hit is 336.20ms`

do i explain right?

if i am right, the number of visitors is equal the uniq IP? what does the number of visitors come from?

**Comment by allinurl** [comment]
That explanation is right. However, the number of visitors (described below the header title) is made out of hits having the same IP, same date, and same user agent (not just the IP)

**Comment by allinurl** [comment]
Just for the record, the `Max.T.S.` shows that out of all the hits, there was one that took 1.07 minutes (very useful to spot stuff taking too long). `Cum.T.S.`, is simply the summation of all the hits.

**Comment by yhl3692319** [comment]
I see, so if I want to know the number of uniq IP that ask websit on that day, I can get it from https://goaccess.io/goaccess_html_report.html?src=gh#hosts here? just count the lines? or does the hosts show has the limit of numbers?

**Comment by allinurl** [comment]
Good question. The terminal output does show up the number of IPs on the parsed set. 

![2016-05-18-093352_351x23_scrot](https://cloud.githubusercontent.com/assets/5005367/15362668/a0db209c-1cdb-11e6-8d04-db9a8c8b8397.png)

However, the current HTML output does not show this. I'll make sure to add it on the upcoming version 1.0. Thanks for pointing it out.

**Comment by yhl3692319** [comment]
ok， thx, I close this 😄

**Comment by yhl3692319** [comment]
@allinurl hi, if my nginx time format is like this
`10.150.47.138 - - [23/10/2014:19:16:23 -0200] "GET /file.php?cid=127 HTTP/1.1" 200 2972 "-" "Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1"3.076`

how to change my goaccess.conf?

**Comment by allinurl** [comment]
This should do it:

    goaccess -f log --log-format='%h %^[%d:%t %^] "%r" %s %b "%R" "%u"%T' --date-format='%d/%m/%Y' --time-format='%T'

**Comment by yhl3692319** [comment]
@allinurl hi, if i update goaccess to 1.0, the log formate is always right?

**Comment by allinurl** [comment]
The `log-format` is the same.
