### ISSUE TITLE
Set the maximum number of virtual hosts

### ISSUE THREAD

**Issue by holinhot** [allinurl/goaccess#420]
hi, guys i have a logs file 15GB 
i used goaccess statistics good working. but The maximum number of virtual hosts list 366 virtual hosts only i want list all of virtual hosts 
How should I do it
the log file have More than 10,000 virtual hosts
thanks

**Comment by bdheeman** [comment]
Better use separate log files for every virtual host and write cron/shell
scripts to generate stats. That's how I do it.

**Comment by holinhot** [comment]
@bdheeman i know this, but i did not separate log files so  how I do it now can to list all virtual hosts
thanks

**Comment by holinhot** [comment]
@bdheeman this is a Domain Name Parking Server have many domains in one host

**Comment by allinurl** [comment]
v1.0 will have the ability to set a max number of items. However, only the JSON and CSV outputs can be set to output a max greater than the default (366). Stay tuned for this major release, which by the way will be out pretty soon.

**Comment by allinurl** [comment]
Just for the record, this is the same request as issue #39.

**Comment by holinhot** [comment]
@allinurl
0.9.8 csv did not support a max greater than the default (366)? or support in v1.0

**Comment by allinurl** [comment]
@holinhot will be on v1.0 - 0.9.8 does not support it.

**Comment by allinurl** [comment]
This has been implemented and is already out in **[v1.0.](https://goaccess.io/)**.  The maximum can be a number between 1 and n.

Note: Only the CSV and JSON output allow a maximum number greater than the default value of 366 (or 50 in the real-time HTML output) items per panel.

**Comment by holinhot** [comment]
@allinurl thanks how to set maximum number?

**Comment by allinurl** [comment]
`--max-items=15` should do it.
