### ISSUE TITLE
sort can't working 

### ISSUE THREAD

**Issue by holinhot** [allinurl/goaccess#421]
i want Outputs html by VISITORS sort but still by BY_HITS sort

this is code in goaccess.conf
sort-panel VISITORS,BY_DATA,ASC

**Comment by allinurl** [comment]
It does for me on v0.9.8. Are you on the latest version? also, do you want to sort by hits or data? I wasn't too clear from the question above.

![2016-06-07-064423_157x363_scrot](https://cloud.githubusercontent.com/assets/5005367/15856489/4de5d012-2c7b-11e6-9ef0-6b46d1e59b2b.png)

**Comment by holinhot** [comment]
@allinurl i want VISITORS sort not BY_HITS sort your image is BY_HITS sort yes i using v0.9.8

**Comment by allinurl** [comment]
It does sort by VISITORS as well.

![2016-06-09-171307_165x591_scrot](https://cloud.githubusercontent.com/assets/5005367/15948279/730ad644-2e65-11e6-926a-f9b384a0f390.png)

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
