### ISSUE TITLE
open_memstream breaks OS X compatibility

### ISSUE THREAD

**Issue by ilovezfs** [allinurl/goaccess#422]
Unfortunately it seems that https://github.com/allinurl/goaccess/commit/487ef906f8a7c7a7bff807c252c60c4fe2f537ca broke OS X compatibility, since OS X doesn't have `open_memstream`.

One option might be to include http://piumarta.com/software/memstream/ but it would be preferable to just make the code portable, of course.

**Comment by allinurl** [comment]
Do you know if it's not included on all version?  The link below suggests Mac OS X 10.5.

https://www.gnu.org/software/gnulib/manual/html_node/open_005fmemstream.html

**Comment by ilovezfs** [comment]
Yeah, it's all versions. Even FreeBSD didn't get it until 2013: https://github.com/freebsd/freebsd/commits/master/lib/libc/stdio/open_memstream.c

I have the goaccess Homebrew formula working again, but I doubt the other maintainers are going to be overjoyed with this :)
```
diff --git a/Formula/goaccess.rb b/Formula/goaccess.rb
index ad43502..b151921 100644
--- a/Formula/goaccess.rb
+++ b/Formula/goaccess.rb
@@ -1,8 +1,8 @@
 class Goaccess < Formula
   desc "Log analyzer and interactive viewer for the Apache Webserver"
   homepage "https://goaccess.io/"
-  url "http://tar.goaccess.io/goaccess-0.9.8.tar.gz"
-  sha256 "45bea0a2d87130f23869a26b103eb1b752a2b4a5b0f6f210cb6ffe8d7b2a18f1"
+  url "http://tar.goaccess.io/goaccess-1.0.tar.gz"
+  sha256 "000e9fbfbdf541c9d407335e8bdd3105e1e0dd41241e82df4c9477fec04daafe"
 
   bottle do
     sha256 "79c0c79415f5e634afd15c5208bab66eed2e36ad507ad104c508c0885b69c01d" => :el_capitan
@@ -10,12 +10,18 @@ class Goaccess < Formula
     sha256 "fd070338e95c84373b3a70559f35a6afcf89f908af1816235d4b1f6b4ccb5f48" => :mavericks
   end
 
-  head do
-    url "https://github.com/allinurl/goaccess.git"
-    depends_on "autoconf" => :build
-    depends_on "automake" => :build
+  depends_on "autoconf" => :build
+  depends_on "automake" => :build
+
+  # open_memstream is not a portable function
+  # Reported 9 Jun 2016: https://github.com/allinurl/goaccess/issues/422
+  resource "memstream" do
+    url "http://piumarta.com/software/memstream/memstream-0.1.tar.gz"
+    sha256 "6aa89113c93f23027da12356168ce2e28929235e5989f355dcde9e77125a6d4f"
   end
 
+  patch :DATA
+
   option "with-geoip", "Enable IP location information using GeoIP"
 
   deprecated_option "enable-geoip" => "with-geoip"
@@ -25,7 +31,12 @@ class Goaccess < Formula
   depends_on "geoip" => :optional
 
   def install
-    system "autoreconf", "-vfi" if build.head?
+    (buildpath/"src").install resource("memstream")
+    inreplace "src/json.c",
+      "#include \"json.h\"",
+      "#include \"json.h\"\n#include \"memstream.h\""
+
+    system "autoreconf", "-vfi"
     args = %W[
       --disable-debug
       --disable-dependency-tracking
@@ -47,6 +58,22 @@ class Goaccess < Formula
 
     output = shell_output("#{bin}/goaccess --time-format=%T --date-format=%d/%b/%Y --log-format='%h %^[%d:%t %^] \"%r\" %s %b \"%R\" \"%u\"' -f access.log -o json 2>/dev/null")
 
-    assert_equal "Chrome", Utils::JSON.load(output)["browsers"][0]["data"]
+    assert_equal "Chrome", Utils::JSON.load(output)["browsers"]["data"][0]["data"]
   end
 end
+
+__END__
+diff --git a/Makefile.am b/Makefile.am
+index e2a3417..bf63b00 100644
+--- a/Makefile.am
++++ b/Makefile.am
+@@ -94,6 +94,8 @@ goaccess_SOURCES = \
+    src/gwsocket.h      \
+    src/json.c          \
+    src/json.h          \
++   src/memstream.c     \
++   src/memstream.h     \
+    src/opesys.c        \
+    src/opesys.h        \
+    src/options.c       \
+

```

**Comment by allinurl** [comment]
Thank you for pointing this out and for having the formula working again. I'll definitely look into this.

**Comment by ilovezfs** [comment]
You're welcome :)

**Comment by ilovezfs** [comment]
@allinurl FYI https://github.com/Homebrew/homebrew-core/pull/1858

Seems FreeBSD's compiles too.

**Comment by allinurl** [comment]
Good to know that, thanks! 

BTW, I was looking at the formula and it seems to be using `glib` and `pkg-config` which are no longer required, can I remove these two and submit a PR? I'm not entirely sure how Homebrew handles this.

**Comment by ilovezfs** [comment]
@allinurl That would usually be the right thing to do, yes, but I've now already gone ahead and removed those two as part of the same PR, per your guidance.

**Comment by allinurl** [comment]
@ilovezfs That's great, thank you!

**Comment by ilovezfs** [comment]
@allinurl You're welcome. Unfortunately, though, https://github.com/Homebrew/homebrew-core/pull/1858#issuecomment-225107680

**Comment by ilovezfs** [comment]
I've closed the PR since the others would prefer to wait on an upstream fix.

**Comment by allinurl** [comment]
I'm looking into it. Issue #433 is related to this as well. I'm checking if it's worth doing some refactoring in the JSON module or if including the FreeBSD implementation upstream suffices...

**Comment by ilovezfs** [comment]
I'd recommend refactoring for what it's worth.

**Comment by allinurl** [comment]
OK. I ended up refactoring the JSON module to use its own memory buffer. It now compiles fine in OS X or any other platform where `open_memstream(3)` is not available. Please feel free to build from **[development](https://github.com/allinurl/goaccess#build-from-github-development)** and let me know how it goes. I'll push this out in the upcoming version. Thanks again!

**Comment by ilovezfs** [comment]
@allinurl Cool. Glad you got it working. I'll give it a spin.

**Comment by ilovezfs** [comment]
@allinurl it works in my testing. By the way, if I attempt to use `--enable-utf8` it complains about

```
checking for mvaddwstr in -lncursesw... no
configure: error: *** Missing development libraries for ncursesw
```
Any chance you could fix that check to be cross platform?
```
iMac-TMP:~ joe$ nm /usr/lib/libncurses.dylib |grep mvaddwstr
000000000002607d T _mvaddwstr
```

**Comment by allinurl** [comment]
@ilovezfs Thanks for letting me know. Happy to hear it works now. I'm expecting to release v1.0.2 next week.

Interesting, what output do you get with `ncursesw5-config --libs`? Also, do you know where Mac puts the ncursesw header files?

**Comment by ilovezfs** [comment]
The issue is the name of the library. See the lack of a "w" above?

**Comment by allinurl** [comment]
I wonder if it shouldn't be `libncursesw.dylib`? It looks like [macports](https://trac.macports.org/browser/trunk/dports/devel/ncurses/Portfile) creates symlinks.

**Comment by ilovezfs** [comment]
No, brew uses the system ncurses and relegates the separate brew ncurses formula to homebrew/dupes. It is not used in homebrew/core.

Anything that attempts to use the Linux paths on macOS has to be patched or fixed upstream.

**Comment by ilovezfs** [comment]
This is how ugly it can get when upstreams try to use the Linux paths and we have to patch it: https://github.com/Homebrew/homebrew-core/blob/master/Formula/libstfl.rb

**Comment by ilovezfs** [comment]
These are the paths on macOS:
```
iMac-TMP:~ joe$ ls /usr/lib|grep curses
libcurses.dylib
libncurses.5.4.dylib
libncurses.5.dylib
libncurses.dylib
iMac-TMP:~ joe$ ls /usr/include|grep curses
curses.h
ncurses.h
ncurses_dll.h
```

**Comment by allinurl** [comment]
Thanks. Let me get my hands again on a Mac and I'll take a look at this.

**Comment by ilovezfs** [comment]
@allinurl looks like it finds ncurses now. However, as far as I can tell --enable-utf8 and --disable-utf8 don't actually do anything now, since it will link to ncurses either way, which isn't a problem per se, but seems like unintended behavior. Also, none of the "enable-foo" options are echoed during configure so it's hard to see what's going on without poking around in the logs afterward.

**Comment by ilovezfs** [comment]
@allinurl Also, FYI I have reopened https://github.com/Homebrew/homebrew-core/pull/1858 and updated it to 1.0.2
