### ISSUE TITLE
How to enable geoip on a Mac

### ISSUE THREAD

**Issue by godsmustbcrazy** [allinurl/goaccess#426]
Once I have installed it on a Mac using
brew install goaccess

is it possible to enable geoIP ?

**Comment by allinurl** [comment]
From the [formula](https://github.com/Homebrew/homebrew-core/blob/be237a8835298223c9ccb6f9cc9a46ea500738dd/Formula/goaccess.rb), it looks like you can pass `with-geoip`

**Comment by godsmustbcrazy** [comment]
Yes , 
brew uninstall goaccess

then

brew install goaccess --with-geoip


Thanks again

**Comment by godsmustbcrazy** [comment]
Make sure you run 

xcode-select install  

if you get an error while doing this that says "homebrew cannot run c compiled programs" when you run brew install goacess --with-geoip

Mac OsX El-Capitan

**Comment by buluxan** [comment]
hi sir , 

i got this error earlier im enable geoip that mention above

sudo goaccess -f access_log  > report5.html
Password:
Error Opening file /usr/local/var/GeoIP/GeoIP.dat

**Comment by sayan-sibyl** [comment]
I am having this issue with GeoIP

According to the last error ettercap was not able to open the geoip file so I ran these commands
brew install geoip
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
imagemagick imagemagick@6 kubernetes-cli node-build

Warning: geoip 1.6.11 is already installed
Sayans-iMac:~ sayan$ sudo ettercap -G
Password:

ettercap 0.8.2 copyright 2001-2015 Ettercap Development Team

(process:12046): Gtk-WARNING **: Locale not supported by C library.
Using the fallback 'C' locale.

(:12046): Gtk-CRITICAL **: gtk_image_get_pixbuf: assertion 'image->storage_type == GTK_IMAGE_PIXBUF || image->storage_type == GTK_IMAGE_EMPTY' failed
Error Opening file /usr/local/var/GeoIP/GeoIP.dat
Error Opening file /path/to/GeoIP.dat

But still I get the same error and when I click on the GeoIP.dat file in finder according to this path
/usr/local/var/GeoIP/GeoIP.dat & this path
/path/to/GeoIP.dat

Finder shows me this error see the attached screenshot
https://user-images.githubusercontent.com/29756523/28931846-1d2568b8-7895-11e7-91d1-ba62a18bab69.png

**Comment by allinurl** [comment]
@sayan-sibyl are you using goaccess and specifying the path of the .dat file in your config file? e.g., `geoip-database /usr/local/var/GeoIP/GeoLiteCity.dat`

**Comment by allinurl** [comment]
Please configure with GeoIP support:

    ./configure --enable-utf8 --enable-geoip=legacy

and then

    goaccess nginx.access.log -o report.html --log-format=COMBINED

**Comment by dkolitha** [comment]
When I try **brew install goaccess --with-geoip**

I get below warning

Warning: goaccess: this formula has no --with-geoip option so it will be ignored!

**Comment by electricpocket** [comment]
Had to install the free GeoLite2-City mmdb on my Mac to get this to work

brew install goaccess

(N.B. now uses mmdb format of GeoLite)

then visit

https://dev.maxmind.com/geoip/geoip2/geolite2/, signup and download the mmdb version
uncompress the gzipped tar file.
and then tell goaccess where to find it with the --geoip-database  option

goaccess ............--geoip-database ~/Downloads/GeoLite2-City_20200901/GeoLite2-City.mmdb

or even better put it in e.g. /usr/local/share set it up permanently using geoaccess.conf

e.g. /usr/local/shareGeoIP/GeoLite2-City.mmdb
