### ISSUE TITLE
Also display Android version code instead of only codename

### ISSUE THREAD

**Issue by peterdk** [allinurl/goaccess#427]
I would love to see that the Android codename would also contain the version code. It's hard to remember all the codenames, while just seeing that 4.4 is very popular in the log is very handy. I don't know why is opted for displaying the codenames at all, but that might be just me.
Maybe something like "Gingerbread (2.3.3)" instead of "Gingerbread"?

**Comment by allinurl** [comment]
I can certainly add those. The default is to show the codenames, however, you can set `real-os` to `false` in your config file.

Thanks

**Comment by peterdk** [comment]
Ok, thanks. I figured out I can also just edit the source myself to comment the conversion out. But thanks for the config tip.  By the way, your site redirects to the wrong github repo in downloads.

**Comment by allinurl** [comment]
Totally missed that, thanks for the heads-up. It's updated now.

**Comment by allinurl** [comment]
This has been added and just deployed on v1.0.1..

Thanks for posting this!
