### ISSUE TITLE
Nothing valid to process on Nginx configuration

### ISSUE THREAD

**Issue by nitinsareen** [allinurl/goaccess#429]
Below is my log format from nginx configuration
 
## Log Format
  log_format        main '"$proxy_add_x_forwarded_for" $host [$time_local] '
                         '"$request" $status $body_bytes_sent '
                         '$request_length $bytes_sent "$http_referer" '
                         '"$http_user_agent" $request_time "$gzip_ratio"';

/etc/goaccess.conf -
time-format %H:%M:%S
date-format %d/%b/%Y
log-format %h %^[%d:%t %^] "%r" %s %b "%R" "%u"

Thanks for your help

**Comment by nitinsareen** [comment]
Sample logs:-

"115.248.199.60" FQDN [09/Jun/2016:06:25:06 +0000] "POST /api/sdp-app/checkpoint/fetch HTTP/1.1" 200 88 394 1294 "-" "Apache-HttpClient/UNAVAILABLE (java 1.4)" 5.564 "-"
"207.46.13.35" FQDN [09/Jun/2016:06:25:06 +0000] "GET /blog/carpet-cleaning/dummies-guide-vacuuming-carpet HTTP/1.1" 200 18428 325 19541 "-" "Mozilla/5.0 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)" 2.069 "4.23"
"185.135.157.53" FQDN [09/Jun/2016:06:25:10 +0000] "GET / HTTP/1.1" 200 82892 167 83674 "-" "Mozilla/5.0 (Anturis Agent)" 0.347 "-"
"115.248.199.60" FQDN [09/Jun/2016:06:25:13 +0000] "POST /api/sdp-app/checkpoint/fetch HTTP/1.1" 200 88 396 1294 "-" "Apache-HttpClient/UNAVAILABLE (java 1.4)" 1.232 "-"
"5.79.100.165" FQDN [09/Jun/2016:06:25:13 +0000] "GET / HTTP/1.1" 200 82892 167 83678 "-" "Mozilla/5.0 (Anturis Agent)" 0.028 "-"

**Comment by nitinsareen** [comment]
Based on goaccess man pages, updated log-format as - 

log-format %h %^[%d:%t %^] "%r" %s %b %b %b "%R" "%u" "%T"

Ended up with same error!

**Comment by allinurl** [comment]
Your format doesn't look like a standard log, however, this should work:

```
log-format "%h" %^[%d:%t %^] "%r" %s %b %^"%R" "%u" %T %^
time-format %H:%M:%S
date-format %d/%b/%Y
```

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.

**Comment by nitinsareen** [comment]
That worked! Thanks a ton :)
The tool is pretty awesome, hope you can dumb this down for users to fix themselves.
