### ISSUE TITLE
Unable to compile on latest OpenIndiana (open_memstream)

### ISSUE THREAD

**Issue by xen0l** [allinurl/goaccess#433]
I tried to compile goaccess 1.0 on OpenIndiana, but it failed because illumos doesn't provide  open_memstream yet. I created bug report for it: https://www.illumos.org/issues/7092.
The same issue applies to SmartOS and other illumos derivates.

Other things I had to patch were:
-  "Platform not supported" in websocket.h - https://github.com/xen0l/oi-userland/blob/goaccess/components/web/goaccess/patches/websocket.h.patch
- u_int*_t -> uint*_t typecasts in sha1.h - https://github.com/xen0l/oi-userland/blob/goaccess/components/web/goaccess/patches/sha1.h.patch.

Would it be possible to replace open_memstream call with something else given OS X has issues with it, too? As for other fixes, I am more than happy to provide PRs if interested.

**Comment by allinurl** [comment]
Thanks for reporting this. I'm looking into it. I'll probably refactor the JSON module.

If you could submit the PRs for those patches, that would be great! Thank you.

**Comment by xen0l** [comment]
I created PR  #436.

**Comment by Slarky** [comment]
open_memstream() is also not available on Solaris 11.3 (but will be available in Solaris 12)

**Comment by allinurl** [comment]
@Slarky Thanks for reporting it as well. I'm working on refactoring this as it also affects OS X. I'll post back as soon as it is implemented.

**Comment by allinurl** [comment]
OK. I ended up refactoring the JSON module to use its own memory buffer. Now it should compile fine (tested in Solaris 11). Please feel free to build from **[development](https://github.com/allinurl/goaccess#build-from-github-development)** and let me know how it goes. I'll push this out in the upcoming version. Thanks again!

**Comment by xen0l** [comment]
I confirm that it works now, thanks! I have package ready to be commited to OpenIndiana repositories. Any ETA on 1.0.2?

**Comment by allinurl** [comment]
Thanks for posting back. Glad to hear it works! I need to run some tests this week, so if everything goes well, I expect to push it out next week.

Closing this. Feel free to reopen it if needed.
