### ISSUE TITLE
Parsing JSON access log with GoAccess

### ISSUE THREAD

**Issue by miguellopes** [allinurl/goaccess#441]
I'm trying to read some nginx logs which are in json but i'm getting nowhere. I was going to restart the process from the beginning but even that isn't working.
```
date_format %Y/%b/%d
time_format %F
```
Now I was trying to get just the beggining like this

    log_format %^:%^"%dT%t%^"%^

But no luck.
Here is an example:

    { "@timestamp": "2016-03-16T04:45:24-04:00", "remote_addr": "IP", "remote_user": "-", "bytes_sent": "5528", "request_time": "0.000", "status": "200", "method":"GET", "vhost":"vhostdomain.net", "content_type":"text/html", "wp_session":"-", "request": "GET /blog/ HTTP/1.1", "request_method": "GET", "http_referrer": "http://domain.net/", "request_uri": "/blog/", "cache": "-", "connection_requests": "6", "http_x_forwarded_for": "-", "http_user_agent": "Mozilla/5.0 (X11; Linux x86_64; rv:44.0) Gecko/20100101 Firefox/44.0" }

**Comment by allinurl** [comment]
Assuming the JSON entries are in one line, then this works:

    goaccess -f log --log-format='%^: "%dT%t-%^", %^: "%h", %^:%^: "%b", %^: "%T", %^: "%s", %^:%^: "%v", %^:%^:%^: "%r", %^:%^: "%R", %^:%^:%^:%^%^:%^: "%u"' --time-format='%T' --date-format='%Y-%m-%d'

**Comment by miguellopes** [comment]
it works only with the command line on the config file doesn't work..

**Comment by allinurl** [comment]
It works fine as well on the config file. Just make sure they are properly entered:

    time-format %H:%M:%S
    date-format %Y-%m-%d
    log-format %^: "%dT%t-%^", %^: "%h", %^:%^: "%b", %^: "%T", %^: "%s", %^:%^: "%v", %^:%^:%^: "%r", %^:%^: "%R", %^:%^:%^:%^%^:%^: "%u"

**Comment by miguellopes** [comment]
Thanks
