### ISSUE TITLE
Majority of the browsers/OS are unknown

### ISSUE THREAD

**Issue by chetankiran** [allinurl/goaccess#443]
Hi,

In my report i shows that the majority of the browsers and OS are unknown.
Can i know the exact reason for that please?
I saw a ongoing issue with ticket no #152  but, i did not find a proper solution in that.

PFA

![goacess error](https://cloud.githubusercontent.com/assets/19911118/16098389/b1df1ef6-3320-11e6-8e8d-8bdfa888bb08.JPG)

**Comment by allinurl** [comment]
Either you are being hit by a lot of bots not listed in **[here](https://github.com/allinurl/goaccess/blob/master/src/browsers.c#L144)** or you have some sort of API where the agent is not set. I'd grab a sample of `N` lines from your access log and look at the user agent for the majority of them.

Let me know what you find.

**Comment by allinurl** [comment]
Also, judging by the numbers and the chart, only 35 visitors and 158K  hits, it looks like a few visitors (probably bots) are hitting your server.

**Comment by chetankiran** [comment]
Hi,
I went through the logs, and i saw majority of them are hit by bots.

**Comment by allinurl** [comment]
As I expected. Also, if you have enabled `-a` and `-d`, it would be
much easier to determine who is eating up your bandwidth by looking at
the Hosts panel.  The crawlers should be at the top.

**Comment by chetankiran** [comment]
I guess i did not enable -a and -d. Does it has to be enabled in the installation stage only?Or can i do it now?

**Comment by allinurl** [comment]
You can just run goaccess again and let it parse the log.

    goaccess -f access.log -a -d -o report.html

**Comment by chetankiran** [comment]
okay i got you. I have already done (-a) it before.

Thanks a lot for your quick responses.

**Comment by chetankiran** [comment]
Sorry again,

I have a quick question
Can i extract the unique bots from the logs using goaccess?

**Comment by allinurl** [comment]
You can do some pre-processing to the log such as

    grep -Evi 'chrome|firefox|ie|windows|linux|Macintosh' access.log | goaccess -a -d -o report.html

**Comment by chetankiran** [comment]
Okay, Thank you.
