### ISSUE TITLE
How to generate a real-time report for multiple sites 

### ISSUE THREAD

**Issue by neochan78** [allinurl/goaccess#444]
real-time report for multiple sites，what way is better?
The following shell script is OK?

```
for domain in $domainname
do
    goaccess -f $logdir/$domain.access.log -o $htmldir/$domain-rt-report.html --real-time-html --port=$port --ws-url=xxx.xxx.xxx.xxx &
    let port=$port+1
    sleep 3
done
```

**Comment by neochan78** [comment]
OK，thanks

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.

**Comment by windware** [comment]
Can you somehow try to share web socket ports against multiple sites? (Maybe by using URL path like, wss://ws.domain/site.domain ?)

If a site is hosted under CloudFlare, the server can't have too many spare ports.
https://support.cloudflare.com/hc/en-us/articles/200169156-Which-ports-will-CloudFlare-work-with-

**Comment by allinurl** [comment]
@windware Thanks for the suggestion. I do like the idea of somehow sharing a port. Please feel free to open a new issue with this request so I make sure to look into it.
