### ISSUE TITLE
Custom log date and time format for my  log with multiple IPs

### ISSUE THREAD

**Issue by che23** [allinurl/goaccess#445]
Hi,
i am unable to parse the log with the format that i have.
Can you please suggest me the suitable time,log and date format for it.

Here is the log.

    [16/Jun/2016:01:59:57 -0400] "10.210.101.4 115.28.162.132, 60.210.20.244, 10.233.174.212, 50.19.124.104, 10.210.101.4" "HTTPS://www.h.com/day/hot/gb/en/res/book?met=rRt&qAt=1&qChd=0&qCiD=21&qCiMy=59886&qCoD=31&qCoMy=553856&qGRM=0&qPSt=0&qRRSrt=rt&qRf=rr&qRmP=K.O.T.X&qRms=1&qRpn=1&qRpp=12&qSHp=1&qSlH=CYPCG&qHtlC=CYPCG&qSmP=3&qSrt=sBR&qWch=0&srb_u=1" 218 366204 489250 "-" "Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.124 Safari/537.36" "Country_Code=geor=47,country_code=CN,region_code=ZJ,city=HANGZHOU,lat=30.26,long=120.17,timezone=GMT+8,continent=AS,throughput=vhigh,bw=2000,asnum=37963,location_id=0" "CD480243C97EFEE1C8D398DD14E8A48D"

**Comment by allinurl** [comment]
Can you please describe the log format? Which one would be the client's IP?

**Comment by chetankiran** [comment]
below is the httpd log format i had in my conf file

LogFormat "%t \"%h %{X-FORWARDED-FOR}i\" \"%{X-IHG-REQUEST-PROTOCOL}i://%{Host}i%U%q\" %>s %B %D \"%{Referer}i\" \"%{User-Agent}i\" \"%{X-AKAMAI-EDGESCAPE}i\" \"%{JSESSIONID}e\" " accessip
CustomLog "| /usr/sbin/rotatelogs -l /local/logs/apache/ipaccess.%Y%m%d%H%M 7200" accessip

**Comment by che23** [comment]
Hi,
Below is the  log format which I have in my conf file

LogFormat "%t \"%h %{X-FORWARDED-FOR}i\" \"%{X-IHG-REQUEST-PROTOCOL}i://%{Host}i%U%q\" %>s %B %D \"%{Referer}i\" \"%{User-Agent}i\" \"%{X-AKAMAI-EDGESCAPE}i\" \"%{JSESSIONID}e\" " accessip
CustomLog "| /usr/sbin/rotatelogs -l /local/logs/apache/ipaccess.%Y%m%d%H%M 7200" accessip

**Comment by che23** [comment]
Hi,

Below is the  log format which I have in my conf file

LogFormat "%t \"%h %{X-FORWARDED-FOR}i\" \"%{X-IHG-REQUEST-PROTOCOL}i://%{Host}i%U%q\" %>s %B %D \"%{Referer}i\" \"%{User-Agent}i\" \"%{X-AKAMAI-EDGESCAPE}i\" \"%{JSESSIONID}e\" " accessip

**Comment by allinurl** [comment]
If you are using `%{X-FORWARDED-FOR}` and the amount of IPs on that field varies, then so far you won't be able to parse it. This is on the to-do list and is part of issue  #78.

If it's a fixed number of IPs, then you you should be able to parse it with the current version of goaccess.

**Comment by che23** [comment]
Hi, 
The link of IP's as the connection routes through Akamai CDN. Can we at least parse out the first IP? That would be the client IP whereas everything else is just Akamai nodes.

**Comment by allinurl** [comment]
This works:

```
log-format [%d:%t %^] "%h %^" "%U" %s %b %D "%R" "%u" %^
date-format %d/%b/%Y
time-format %H:%M:%S
http-protocol no
http-method no
```
or 

    goaccess -f access.log --log-format='[%d:%t %^] "%h %^" "%U" %s %b %D "%R" "%u" %^' --date-format='%d/%b/%Y' --time-format='%H:%M:%S' --http-protocol=no --http-method=no

**Comment by che23** [comment]
thank you

**Comment by allinurl** [comment]
Glad it worked. Closing this.

**Comment by che23** [comment]
Hi,
Will we be able to parse the second IP from that list of ip addresses on the log?

**Comment by allinurl** [comment]
@che23 you can parse any IP as long as there's a fixed number of them. e.g., `"%^ %h %^"`
