### ISSUE TITLE
Combined log date format help

### ISSUE THREAD

**Issue by bonelifer** [allinurl/goaccess#446]
66.249.65.39 - - [18/Jun/2016:02:03:08 -0400] "GET /board/memberlist.php?mode=viewprofile&u=9619 HTTP/1.1" 200 12671 "-" "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"

**Comment by allinurl** [comment]
Your log format is a combined log format, so this should work:

    log-format COMBINED

or you could run goaccess as:

    goaccess -f access.log --log-format=COMBINED

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
