### ISSUE TITLE
Websocket port for frontend

### ISSUE THREAD

**Issue by pronebird** [allinurl/goaccess#447]
Would be awesome to have separate port option in case if goaccess websocket server runs behind a proxy. I have EC2 instance with nginx that passes requests from /goaccess/websocket directly to localhost:9879.

**Comment by allinurl** [comment]
Are you looking to have an option to specify the port to which the WebSocket constructor accepts on the client side and different to the one the server listens on? e.g.,

Server
 
    goaccess -f access.log --real-time-html ws-url=http://site.com --port=7890 --client-port=9999

Client

    ws://site.com:9999

**Comment by pronebird** [comment]
Yes indeed.

**Comment by allinurl** [comment]
This has been added. Now you can specify the port within `--ws-url`. For instance,

    goaccess -f access.log --real-time-html --ws-url=host:9999 --port=7890

Feel free to build from [**development**](https://github.com/allinurl/goaccess#build-from-github-development), otherwise it will be pushed out in the upcoming release.

**Comment by allinurl** [comment]
Closing this. Thanks.

**Comment by pronebird** [comment]
Amazing! Thank you! 👍

**Comment by madpsy** [comment]
Hey -  which version is this in?  

With 1.0.2 I see if I launch with:

--ws-url=analytics.test.com:7891 --port 7890

The JavaScript reads:

{"url": "analytics.test.com:7891","port": 7890}

Which as far as I can tell uses the 'port' value rather than the URL. 

Thanks

**Comment by allinurl** [comment]
@madpsy, it's on v1.0.2. On the client-side, it should use 7891 and
7890 is used on the server-side.
