### ISSUE TITLE
How can I figure out how much requested files are responsed < 1s, >1s && <2s..

### ISSUE THREAD

**Issue by yhl3692319** [allinurl/goaccess#450]
hi, I want to figure out the response time of  requested files and how much are located in 0~1s, 1s~2s, 2s~3s and so on ?

**Comment by allinurl** [comment]
Are you using Apache or Nginx or something else? You will need to change the log format and add the specific field so it starts logging the response time.

**Comment by yhl3692319** [comment]
@allinurl I use nginx, how can I change my log format and can figure out the response time response time. For example: my nginx log is like this, and I want to get the data like this: `0~1s: 1(33%) request, 1s~2s: 0 request, 2s~3s: 2(67%) requests `

```
10.150.47.138 - - [23/10/2014:19:16:23 -0200] "GET /file.php?cid=127 HTTP/1.1" 200 2972 "-" "Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1"3.076
10.150.47.138 - - [23/10/2014:19:16:23 -0200] "GET /file.php?cid=127 HTTP/1.1" 200 2972 "-" "Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1"2.076
10.150.47.138 - - [23/10/2014:19:16:23 -0200] "GET /file.php?cid=127 HTTP/1.1" 200 2972 "-" "Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1"0.076
```

**Comment by allinurl** [comment]
It seems like you are already logging the response time, however, goaccess won't display the format that you are looking for. However, you could generate a **[JSON](https://goaccess.io/json)** output report and extract the data and display it the way you want to.

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
