### ISSUE TITLE
IIS Web Proxy Log Fields

### ISSUE THREAD

**Issue by rami85** [allinurl/goaccess#454]
I'm trying to read a IIS Web Proxy Log File (https://msdn.microsoft.com/en-us/library/aa503433.aspx).

In my goaccess conf:

`time-format %H:%M:%S`
`date-format %Y-%m-%d`
`log-format %h	%^	%u	%d	%t	%v	%R	%^	%^	%^	%D	%b	%^	%H	%m	%r	%^	%^	%s	%^	%^	%^	%^	%^	%^	%^	%^	%^	%^	%^	%^	%^	%^	%^	%^	%^	%^`

I've a test w3c log file with one request:

`#Software: Microsoft Forefront Threat Management Gateway
#Version: 2.0
#Date: 2015-08-01 00:00:00
#Fields: c-ip	cs-username	c-agent	date	time	s-computername	cs-referred	r-host	r-ip	r-port	time-taken	cs-bytes	sc-bytes	cs-protocol	s-operation	cs-uri	cs-mime-type	s-object-source	sc-status	rule	FilterInfo	cs-network	sc-network	error-info	action	AuthenticationServer	IPS scan result	IPS signature	ThreatName	MalwareInspectionAction	MalwareInspectionResult	UrlCategory	MalwareInspectionContentDeliveryMethod	MalwareInspectionDuration	MalwareInspectionThreatLevel
176.83.125.27 anonymous example.Android.Ex 2015-08-01 00:00:00 CAMEL - example.drd.as.eu	10.90.0.178	6080 16 333 12366 http GET http://example.drd.as.eu/rest/services/FeatureServer/0?f=json text/plain;charset=utf-8 Inet 200 Example(http) Req ID: 0c3dcd9e; Compression: client=Yes, server=No, compress rate=45% decompress rate=0%	External	Local Host	0xc00	Allowed	-	-	-	-	-	-	-	-	0	-`

Each field is separated by tabulation (I don't know how to resolve it in the pattern) and in the agent field some times I can find two words separated by blanks. If you notice in the pattern I would like ignoring the last 18 fields...How I jump to the next register after read '%s'? Is it possible?

Goaccess show me this error:

```
Error occured at: src/goaccess.c - main - 1230
Nothing valid to process. Verify your date/time/log format.
```

Any ideas? Thanks a lot.

Regards

**Comment by allinurl** [comment]
Please try the following:

    goaccess -f log --log-format='%h\t%^\t%u\t%d\t%t\t%^\t%R\t%v\t%^\t%^\t%L\t%b\t%^\t%^\t%m\t%U\t%^\t%^\t%s\t%^' --date-format='%Y-%m-%d' --time-format='%T' --http-protocol=no

Or

```
time-format %H:%M:%S
date-format %Y-%m-%d
log-format %h\t%^\t%u\t%d\t%t\t%^\t%R\t%v\t%^\t%^\t%L\t%b\t%^\t%^\t%m\t%U\t%^\t%^\t%s\t%^
http-protocol no
```

**Comment by rami85** [comment]
Thanks a lot @allinurl, I've solved the problem with your answer without `http-protocol no`.
