### ISSUE TITLE
 Missing development libraries for Tokyo Cabinet Database using Cygwin

### ISSUE THREAD

**Issue by rami85** [allinurl/goaccess#456]
I'm using goaccess through cygwin. Now, I would like store the log data in the b tree.

I've built goaccess with `./configure --enable-utf8 --enable-geoip --enable-tcb=btree`

`checking for tchdbnew in -ltokyocabinet... no`
`configure: error: *** Missing development libraries for Tokyo Cabinet Database`

I've compiled Tokyo Cabinet by cygwin correctly with `make install`. It has generated a new folder called tokyocabinet-1.4.48.

any idea to configure correctly goaccess?

Thanks a lot. Regards

**Comment by allinurl** [comment]
Did you configure tokyo as shown below?

    ./configure --prefix=/usr --enable-off64 --enable-fastest

**Comment by rami85** [comment]
yes @allinurl:

`$ ./configure --prefix=/usr --enable-off64 --enable-fastest`

#================================================================
\# Configuring Tokyo Cabinet version 1.4.48 (fastest) (off64).
#================================================================
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.exe
checking for suffix of executables... .exe
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking whether byte ordering is bigendian... no
checking for main in -lc... yes
checking for main in -lm... yes
checking for main in -lpthread... yes
checking for main in -lrt... yes
checking for main in -lz... yes
checking for main in -lbz2... yes
checking for main in -ltokyocabinet... yes
configure: WARNING: old version of Tokyo Cabinet was detected
checking for stdlib.h... (cached) yes
checking for stdint.h... (cached) yes
checking for unistd.h... (cached) yes
checking dirent.h usability... yes
checking dirent.h presence... yes
checking for dirent.h... yes
checking regex.h usability... yes
checking regex.h presence... yes
checking for regex.h... yes
checking glob.h usability... yes
checking glob.h presence... yes
checking for glob.h... yes
checking pthread.h usability... yes
checking pthread.h presence... yes
checking for pthread.h... yes
checking zlib.h usability... yes
checking zlib.h presence... yes
checking for zlib.h... yes
checking bzlib.h usability... yes
checking bzlib.h presence... yes
checking for bzlib.h... yes
configure: creating ./config.status
config.status: creating Makefile
config.status: creating tokyocabinet.pc
#================================================================
\# Ready to make.
#================================================================

**Comment by rami85** [comment]
`$ make`

#================================================================
\# Ready to install.
#================================================================

**Comment by rami85** [comment]
`$ make install`

`mkdir -p /usr/include
cp -Rf tcutil.h tchdb.h tcbdb.h tcfdb.h tctdb.h tcadb.h /usr/include
mkdir -p /usr/lib
cp -Rf libtokyocabinet.a libtokyocabinet.so.9.11.0 libtokyocabinet.so.9 libtokyocabinet.so /usr/lib
mkdir -p /usr/bin
cp -Rf tcutest tcumttest tcucodec tchtest tchmttest tchmgr tcbtest tcbmttest tcbmgr tcftest tcfmttest tcfmgr tcttest tctmttest tctmgr tcatest tcamttest tcamgr /usr/bin
mkdir -p /usr/libexec
cp -Rf tcawmgr.cgi /usr/libexec
mkdir -p /usr/share/tokyocabinet
cp -Rf COPYING ChangeLog doc tokyocabinet.idl /usr/share/tokyocabinet
mkdir -p /usr/share/man/man1
cd man && cp -Rf tcutest.1 tcumttest.1 tcucodec.1 tchtest.1 tchmttest.1 tchmgr.1 tcbtest.1 tcbmttest.1 tcbmgr.1 tcftest.1 tcfmttest.1 tcfmgr.1 tcttest.1 tctmttest.1 tctmgr.1 tcatest.1 tcamttest.1 tcamgr.1 /usr/share/man/man1
mkdir -p /usr/share/man/man3
cd man && cp -Rf tokyocabinet.3 tcutil.3 tcxstr.3 tclist.3 tcmap.3 tctree.3 tcmdb.3 tcmpool.3 tchdb.3 tcbdb.3 tcfdb.3 tctdb.3 tcadb.3 /usr/share/man/man3
mkdir -p /usr/lib/pkgconfig
cp -Rf tokyocabinet.pc /usr/lib/pkgconfig
[ "$UID" = 0 ] && PATH=/sbin:/usr/sbin:/usr/local/bin:/usr/bin:/cygdrive/c/ProgramData/Oracle/Java/javapath:/cygdrive/c/Windows/system32:/cygdrive/c/Windows:/cygdrive/c/Windows/System32/Wbem:/cygdrive/c/Windows/System32/WindowsPowerShell/v1.0:/cygdrive/c/Program Files/nodejs:/cygdrive/e/Software/phantomjs.exe:/cygdrive/c/Program Files/FME:/cygdrive/e/Software/FMESERVER/Utilities/jre/bin/client:/cygdrive/e/Software/FMESERVER/Server/fme:/cygdrive/e/Software/FMESERVER:/cygdrive/e/Software/FME:/cygdrive/e/Software/FME 64:/cygdrive/c/Program Files/ESET/ESET Endpoint Antivirus ldconfig 2>/dev/null || true`

#================================================================
\# Thanks for using Tokyo Cabinet.
#================================================================

**Comment by allinurl** [comment]
I just tested and it works on my cygwin instance.

```
  Prefix         : /usr/local
  Package        : goaccess
  Version        : 1.0.1
  Storage method : On-disk B+ Tree Database (Tokyo Cabinet)
  GNU getline    : no
  Compiler flags :  -pthread
  Linker flags   : -ltokyocabinet -lncurses -lpthread   -lz -ltokyocabinet -lrt -lc
  Bugs           : goaccess@prosoftcorp.com

```

Are you building from development (git clone)? or from the tar source? If it's from dev, you will need to run the following after installing btree

```
$ autoreconf -fiv
$ ./configure --enable-tcb=btree
$ make
# make install
```

**Comment by rami85** [comment]
I'm building both (goaccess and Tokyo Cabinet) from tar.

I think Both of them are build correctly, at least, when I run the `make install`, I don't show any error.

In my directory I've two folders: goaccess-1.0.1 and tokyocabinet-1.4.48. I've tried to put tokyocabinet inside goaccess folder but it is the same.

I'm a bit lost. How I show my goaccess configuration instance like you?

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.

**Comment by elproducto** [comment]
Getting the following error trying to make TokyoCabinet.  Not sure if this is due to memory allocations or something else.

```
$make
cat myconf.c tcutil.c md5.c tchdb.c tcbdb.c tcfdb.c tctdb.c tcadb.c > tokyocabinet_all.c
gcc -c -I. -I/usr/include -I/home/user/include -I/usr/local/include -DNDEBUG -D_GNU_SOURCE=1 -D_REENTRANT -D__EXTENSIONS__ -D_MYFASTEST -D_FILE_OFFSET_BITS=64 -D_MYNOZLIB -D_MYNOBZIP -D_TC_PREFIX="\"/usr\"" -D_TC_INCLUDEDIR="\"/usr/include\""
-D_TC_LIBDIR="\"/usr/lib\"" -D_TC_BINDIR="\"/usr/bin\"" -D_TC_LIBEXECDIR="\"/usr/libexec\"" -D_TC_APPINC="\"-I/usr/include\"" -D_TC_APPLIBS="\"-L/usr/lib -ltokyocabinet -lrt -lpthread -lm -lc \"" -g -O2 -std=c99 -Wall -fPIC -pedantic -fsigned-char -O3
-fomit-frame-pointer -fforce-addr -minline-all-stringops tokyocabinet_all.c
tokyocabinet_all.c:1:0: warning: -fPIC ignored for target (all code is position independent)
 /*************************************************************************************************
 ^
tokyocabinet_all.c: In function ‘tcbdbremoverec.isra.21’:
tokyocabinet_all.c:19392:59: warning: ‘vsiz’ may be used uninitialized in this function [-Wmaybe-uninitialized]
       TCREALLOC(rec, rec, sizeof(*rec) + rec->ksiz + psiz + vsiz + 1);
                                                           ^

cc1: out of memory allocating 1048576 bytes after a total of 10092544 bytes
make: *** [Makefile:72: tokyocabinet_all.o] Error 1
```
