### ISSUE TITLE
Integration with Pi-Hole

### ISSUE THREAD

**Issue by xlr8sys** [allinurl/goaccess#460]
I'm trying to use this interface with Pi-Hole on Debian Jessie, regardless of the combination of Date, Time and Log I select to start it always fails The same way:

```
Fatal error has occurred 
Error occurred at: screen/go access.c - main -1230
Nothing valid to process. Verify your date/time/log format.
```

I really think the dashboard from GoAccess is way better (design/functionality) than the standard view in Pi-Hole but the frustration to get it up and running is killing me!
If it can be used with virtually any web server, I wonder what is the case for such issues in my testing with Pi-Hole or what am I doing wrong that it simply doesn't work?

If I run trail -f /var/log/pinhole.log in terminal it successfully show the real time traffic from the log...

**Comment by allinurl** [comment]
Can you please post a few lines from you access log so I can take a look at the log format? Thanks.

**Comment by xlr8sys** [comment]
you guys are quick!!! thank you for the prompt response...

this is a block from the log file

Jul  2 00:04:42 dnsmasq[545]: /etc/pihole/gravity.list ssw.live.com is 10.0.1.7
Jul  2 00:05:53 dnsmasq[545]: query[A] p12-bookmarks-current.edge.icloud.apple-dns.net from 10.0.1.2
Jul  2 00:05:53 dnsmasq[545]: forwarded p12-bookmarks-current.edge.icloud.apple-dns.net to 208.67.220.220
Jul  2 00:05:53 dnsmasq[545]: forwarded p12-bookmarks-current.edge.icloud.apple-dns.net to 208.67.222.222
Jul  2 00:05:53 dnsmasq[545]: query[A] webdav.facebook.com from 10.0.1.2
Jul  2 00:05:53 dnsmasq[545]: forwarded webdav.facebook.com to 208.67.220.220
Jul  2 00:05:53 dnsmasq[545]: reply webdav.facebook.com is <CNAME>
Jul  2 00:05:53 dnsmasq[545]: reply api.facebook.com is <CNAME>
Jul  2 00:05:53 dnsmasq[545]: reply star.c10r.facebook.com is 31.13.73.1
Jul  2 00:05:53 dnsmasq[545]: reply p12-bookmarks-current.edge.icloud.apple-dns.net is 17.248.138.75
Jul  2 00:06:06 dnsmasq[545]: query[A] guzzoni.apple.com from 10.0.1.2
Jul  2 00:06:06 dnsmasq[545]: forwarded guzzoni.apple.com to 208.67.220.220
Jul  2 00:06:06 dnsmasq[545]: reply guzzoni.apple.com is <CNAME>
Jul  2 00:06:06 dnsmasq[545]: reply origin.guzzoni-apple.com.akadns.net is <CNAME>
Jul  2 00:06:06 dnsmasq[545]: reply st14p01sa.guzzoni-apple.com.akadns.net is 17.174.1.5
Jul  2 00:06:06 dnsmasq[545]: query[A] play.itunes.apple.com from 10.0.1.2
Jul  2 00:06:06 dnsmasq[545]: forwarded play.itunes.apple.com to 208.67.220.220
Jul  2 00:06:07 dnsmasq[545]: reply play.itunes.apple.com is <CNAME>
Jul  2 00:06:07 dnsmasq[545]: reply play-cdn.itunes-apple.com.akadns.net is <CNAME>
Jul  2 00:06:07 dnsmasq[545]: reply itunes.apple.com.edgekey.net is <CNAME>
Jul  2 00:06:07 dnsmasq[545]: reply e673.e9.akamaiedge.net is 23.202.82.217
Jul  2 00:06:07 dnsmasq[545]: query[A] init.itunes.apple.com from 10.0.1.2
Jul  2 00:06:07 dnsmasq[545]: forwarded init.itunes.apple.com to 208.67.220.220
Jul  2 00:06:07 dnsmasq[545]: reply init.itunes.apple.com is <CNAME>
Jul  2 00:06:07 dnsmasq[545]: reply init-cdn.itunes-apple.com.akadns.net is <CNAME>
Jul  2 00:06:07 dnsmasq[545]: reply itunes.apple.com.edgekey.net is <CNAME>
Jul  2 00:06:07 dnsmasq[545]: reply e673.e9.akamaiedge.net is 23.202.82.217
Jul  2 00:06:08 dnsmasq[545]: query[A] xp.apple.com from 10.0.1.2
Jul  2 00:06:08 dnsmasq[545]: forwarded xp.apple.com to 208.67.220.220
Jul  2 00:06:08 dnsmasq[545]: reply xp.apple.com is <CNAME>
Jul  2 00:06:08 dnsmasq[545]: reply xp.itunes-apple.com.akadns.net is <CNAME>
Jul  2 00:06:08 dnsmasq[545]: reply mt-ingestion-service-mr22.itunes.apple.com is <CNAME>
Jul  2 00:06:08 dnsmasq[545]: reply mt-ingestion-service-mr22.itunes-apple.com.akadns.net is 17.110.234.28
Jul  2 00:06:08 dnsmasq[545]: reply mt-ingestion-service-mr22.itunes-apple.com.akadns.net is 17.110.232.46
Jul  2 00:06:08 dnsmasq[545]: reply mt-ingestion-service-mr22.itunes-apple.com.akadns.net is 17.110.234.27
Jul  2 00:06:08 dnsmasq[545]: reply mt-ingestion-service-mr22.itunes-apple.com.akadns.net is 17.110.232.45
Jul  2 00:07:36 dnsmasq[545]: query[A] 15-courier.push.apple.com from 10.0.1.2
Jul  2 00:07:36 dnsmasq[545]: forwarded 15-courier.push.apple.com to 208.67.220.220
Jul  2 00:07:36 dnsmasq[545]: forwarded 15-courier.push.apple.com to 208.67.222.222

The official page for pi-hole definitions of the log file
https://pi-hole.net/faq/how-do-i-read-and-interpret-the-log-file/
i hope this helps!

**Comment by allinurl** [comment]
Unfortunately, in this case, GoAccess won't be able to help since they appear to be DNS queries and not web server requests. GoAccess is a web log analyzer.

**Comment by allinurl** [comment]
Closing this.
