### ISSUE TITLE
Command line options to set HTML theme and panels per page

### ISSUE THREAD

**Issue by MelkorLord** [allinurl/goaccess#462]
Hi,

Currently, when we generate an HTML report, the theme and number of panels per page are respectively hardcoded to "dark" and "10".

It would be nice to have command line arguments to pre-set them. Dark theme is hard to read for some people (and they're tired of changing it everytime they access the reports) and 10 lines are oftenly not enough to get a clear view of what's going on.

Thanks

**Comment by allinurl** [comment]
Right now it should be saving your settings, i.e., per-page and theme in your browser localStorage, so you shouldn't need to be setting this up every time you access the report (assuming the report is in same domain). 

However, I do agree that having the ability to set this in the command line would be nice. I can certainly add these options. Thanks for the suggestion!

**Comment by allinurl** [comment]
This has been implemented. It will be deployed soon in the upcoming version. Stay tuned!

A valid JSON object is required. It allows the ability to customize each panel plot. See example below.

    goaccess -f access.log --html-prefs='{"theme":"bright","perPage":5,"layout":"horizontal","showTables":true,"visitors":{"plot":{"chartType":"bar"}}}'

**Comment by chang-zhao** [comment]
It would be great if perPage could be set a bit larger, at least through command line or config file (like 32 or even 50).

Thank you in advance if you would do it. =)

**Comment by allinurl** [comment]
@chang-zhao Have you tried setting the value perPage to 32 or 50 under `html-prefs`? e.g., [config file](https://github.com/allinurl/goaccess/blob/master/config/goaccess.conf#L150)
