### ISSUE TITLE
Ubuntu 16 apache 2 error log format probleme

### ISSUE THREAD

**Issue by mikecastrodemaria** [allinurl/goaccess#464]
I try read my error log, but get error on format, who can drive me to the good direction ?
My error log is like this :
[Thu Jul 07 09:51:13.817201 2016] [:error] [pid 5250] [client x.x.x.x:xxxxx] PHP Notice:  Undefined variable: ... etc

what are the value for : 
```
--log-format="%h %^[%d:%^] \"%r\" %s %b \"%R\" \"%u\""
--date-format=%{%d %b %Y}
--time-format=%{%T}t.%{msec_frac}t
```

Thanks for help

**Comment by allinurl** [comment]
GoAccess does not parse error logs, it's designed to parse access logs only.
