### ISSUE TITLE
Option --html-report-title is always suffixed with timestamp

### ISSUE THREAD

**Issue by MelkorLord** [allinurl/goaccess#466]
Hi,

The option --html-report-title="some title" is always suffixed with the report generation timestamp in the ```<title>``` HTML tag which is not desirable.

It even creates confusing situations. For example, I'm generating new HTML reports with past data on a day-by-day basis. As so, I set the option --html-report-title="Web stats for YYYY.MM.DD" and the result is really confusing to read on the browser.

For a report of say 2016.06.01 generated "now", the title displayed in the browser tab is : 
"Web stats for 2016.06.01 - 2016-07-08 05:17:21"

Could it be possible to remove that timestamp? The "Last Updated" info within the report is enough to get the needed information without being confusing at all. Thanks.

**Comment by allinurl** [comment]
I think it makes sense to remove the timestamp from the title. I'll change that. Thanks!

**Comment by allinurl** [comment]
I've changed this. It won't display the timestamp within the title tag. Feel free to build from [development](https://github.com/allinurl/goaccess#build-from-github-development), otherwise it will be pushed out in the upcoming version.

Thanks!
