### ISSUE TITLE
GoAccess writes all output to stderr

### ISSUE THREAD

**Issue by MelkorLord** [allinurl/goaccess#467]
Hi,

There should be a separation between normal output (ie: Parsing... [nnn] [xxx/s]) and error messages with stdout and stderr.

I'm using GoAccess within a wrapper script and I'd like to capture only the errors output instead of all the "normal" (ie: non error) output.

**Comment by allinurl** [comment]
Currently you can disable the progress metrics using `--no-progress`.

**Comment by MelkorLord** [comment]
Apologies for missing that! As a long time Unix user, I searched the man page for "--quiet" and such which suppresses all output but errors. Consider this issue closed :-)

**Comment by allinurl** [comment]
No worries. I think it's great you brought this up in case somebody else has the same question.

**Comment by mcnesium** [comment]
I still think this is an issue. Running v1.5.5 using `-no-progress` option I still see one line of output:

    Cleaning up resources...

This is obviously not an error and should therefore not be written to stderr.

I am trying to run GoAccess in a cronjob, so I need to have the process be completely silenced, if everything works well. With all its output being sent to stderr, I would need to silence it by doing `goaccess … 2>/dev/null` . But this would then also silence real errors, e.g. when a logfile was not found.
