### ISSUE TITLE
Absence of data is treated as an error !

### ISSUE THREAD

**Issue by MelkorLord** [allinurl/goaccess#471]
Hi,

(with a valid goaccess.conf file)
```
echo '' | goaccess -o foobar.html
Parsing... [0] [0/s]
GoAccess - version 1.0.2 - Jul  7 2016 18:31:10
Config file: /etc/goaccess/goaccess.conf

Fatal error has occurred
Error occured at: src/goaccess.c - main - 1230
Nothing valid to process. Verify your date/time/log format.
```

This is wrong! This should produce a report with all numbers at "0" instead of no report + an error message.

I generate reports on a day by day basis with various conditions to give different points of view of the same logs data.

There are numerous reasons why in normal situations this sould work.
- No one came visit the site :-)
- Every request is filtered out by --exclude-ip
- stdin is filtered (ie: grep) and there was no match

So "no data" is **really different** from "bad data" (ie: wrong log format) and they should be treated differently. Thanks.

**Comment by allinurl** [comment]
I agree on this. However, since it should let the user know if in fact the time/date/log format are not matching the log entries, then I'll 'merge' this with issue #264.

Please keep this open so I can look into it.

Thanks.

**Comment by vishnuraja126** [comment]
Hi,
    I/m getting an error like this in virtual server..

 sudo goaccess -f /var/log/nginx/access.log

GoAccess - version 1.0.2 - Jul  4 2016 19:44:08
Config file: /etc/goaccess.conf

Fatal error has occurred
Error occured at: src/goaccess.c - main - 1230
Nothing valid to process. Verify your date/time/log format.
And my date/time/log formats are
time-format %H:%M:%S
date-format %d/%b/%Y
log-format %v:%^ %h %^[%d:%t %^] "%r" %s %b "%R" "%u"

**Comment by allinurl** [comment]
Please open a new issue and post a few lines from your access log so I can take a look.

**Comment by allinurl** [comment]
This has been implemented. I added the ability to show which token didn't match log/date/time pattern.

This also ensures that in the absence of data, its output is not  treated as error but instead it produces an empty report.

Feel free to build from [**development**](https://goaccess.io/download#build) to test it. It will be pushed out in the upcoming release.
