### ISSUE TITLE
keep-db-file option unrecognised

### ISSUE THREAD

**Issue by madpsy** [allinurl/goaccess#475]
Version GoAccess - 0.9.4 (Shipped with Ubuntu 16.04)

When trying to use the keep-db-file option, either as a command line parameter or in the config, goaccess reports:

goaccess: unrecognized option '--keep-db-files'

**Comment by madpsy** [comment]
Tested with 1.0.2 and issue still exists.

**Comment by allinurl** [comment]
You need to build goaccess with --enable-tcb=btree for the on-disk storage to be enabled.

**Comment by madpsy** [comment]
That worked thanks... shame the Ubuntu package negates it.

**Comment by allinurl** [comment]
Glad that worked. Feel free to use the [oficcial deb repo ](https://github.com/allinurl/goaccess#official-goaccess-debian--ubuntu-repository)(default hash tables).

**Comment by madpsy** [comment]
Thanks - appreciated.

Would I be correct in saying using btree is the only way to maintain previous stats if the current log file has been rotated? I.e. the log file which is parsed by goaccess gets rotated so goaccess needs to store previous processed logs, else having to use a single file would mean it would be uncontrollably large.

Losing the file handle on the log is something I've not tested yet, but  I presume goaccess will need restarted one way or another.

**Comment by allinurl** [comment]
That's correct. The btree is the only way to do incremental log processing.
