### ISSUE TITLE
'COLOR_WHITE' undeclared

### ISSUE THREAD

**Issue by rebroad** [allinurl/goaccess#480]
This and many other variables are undeclared when compiling the latest HEAD on raspbian. Other variables include 'COLORS', 'A_BOLD', 'A_UNDERLINE', 'A_NORMAL', 'A_REVERSE', 'A_BLINK', 'WINDOW'.

**Comment by allinurl** [comment]
Sounds like ncurses is missing. Have you tried:

    $ sudo apt-get install libncurses5-dev libncursesw5-dev
    $ cd goaccess
    $ autoreconf -fiv
    $ ./configure --enable-geoip --enable-utf8
    $ make
    $ sudo make install

**Comment by allinurl** [comment]
I've pushed a fix for [this](https://github.com/allinurl/goaccess/commit/0460a5466ece2388759735b0da3d57a2935965ec). Feel free to build from [development](https://github.com/allinurl/goaccess#build-from-github-development).

Thanks for reporting it!
