### ISSUE TITLE
Cant see the Android device on the apache logs 

### ISSUE THREAD

**Issue by buluxan** [allinurl/goaccess#481]
hi morning in here indonesia ,

i just wanna inform regarding the operating system after i generating .html , looks goaccess cant detect the android device , because i didnt see it on the capture below 
could u pls assist me

thx a lot

![screen shot 2016-07-28 at 2 45 48 am](https://cloud.githubusercontent.com/assets/7418412/17189869/b400b898-546d-11e6-9979-e9fe8928e28b.png)

**Comment by allinurl** [comment]
Are you sure you have Android devices in your log? Can you post the output of (change as needed):
 
    grep -i 'Android' /var/log/apache2/access.log

**Comment by buluxan** [comment]
let me check first on the logs

**Comment by allinurl** [comment]
@buluxan so you did not find any Android devices?

**Comment by buluxan** [comment]
yes didnt find it , looks need to discuss with developer 


thx u anyway

**Comment by allinurl** [comment]
Closing this.
