### ISSUE TITLE
Timestamp with timezone

### ISSUE THREAD

**Issue by vbrandl** [allinurl/goaccess#482]
I'm trying to parse some access logs in the following format:
```
1.2.3.4 - - 01/Jan/1990:00:00:00 +0100 "GET /some/site.html HTTP/1.1" 200 13630 "-" "the_user_agent"
```
and I've got a problem with the timezone offset.
I tried using `time-format %H:%M:%S %z` but that way, goaccess doesn't match any line at all.
I have to give the logformat like this:
```
log-format %h - - %d:%t +0100 "%r" %s %b "%R" "%u"
```
and `time-format %H:%M:%S` for goaccess to work properly, but this workaround is no solution for me, since I got different time offsets in the logs, e.g +0100, +0200, ..., so I cannot have the offset hardcoded in my log format pattern. Sure I could just ignore the offset by using `%^` but that would make the data wrong.
How can I parse the timestamp correctly?

**Comment by allinurl** [comment]
Please try:

    log-format %h %^ %^ %d:%t %^ "%r" %s %b "%R" "%u"

**Comment by vbrandl** [comment]
It is working with `%^`, but that way, `01/Jan/1990:00:00:00 +0100` and `01/Jan/1990:00:00:00 +0200` would be treated as if they were the same, which they aren't or am I missing something?

**Comment by allinurl** [comment]
At the moment, goaccess doesn't make use of the timezone. However, if you still want to add it to the log/time-format, you can use:

    log-format %h %^ %^ %d:%t %^ "%r" %s %b "%R" "%u"
    time-format %H:%M:%S %Z

**Comment by vbrandl** [comment]
Ah ok I didn't know, goaccess doesn't use the timestamp. That explains the problem. Thank you and great work BTW ;)

**Comment by allinurl** [comment]
Glad it worked :)
