### ISSUE TITLE
Crash with invalid GeoIP data file

### ISSUE THREAD

**Issue by MelkorLord** [allinurl/goaccess#485]
Hi,

Trying various scenarios in a test environment, I found out that GA crashes in a very particular case. My ```/etc/goaccess.conf```` mentions ```geoip-database /tmp/GeoLiteCity.dat```

For a simple test, a simple ```touch /tmp/GeoLiteCity.dat``` which crashes GA execution.

The question is: Who's crashing? "libGeoIP.so" itself or GA not correctly handling returned data from the lib?

**Comment by allinurl** [comment]
Thanks for reporting this. I'm looking into it and will report back asap.

**Comment by allinurl** [comment]
Unfortunately it is an issue on libGeoIP itself. There's no way to detect invalid files, for instance,

```
#include "GeoIP.h"

int main() {
  GeoIP * gi = GeoIP_open("file.txt", GEOIP_MEMORY_CACHE);

  /* Unable to detect invalid files at load, unfortunately. */
  if (gi == NULL) {
    fprintf(stderr, "Error opening database\n");
    return 1;
  }

  /* segfaults here... */
  const char * country = GeoIP_country_code_by_addr(gi, "24.24.24.24");
  if (country != NULL) {
    fprintf(stderr, "Error database\n");
    return 1;
  }
  return 0;
}
```

Issue #283 plans to implement GeoIP2, so I'm hoping this issue was address in geoip v2. As far as the right `.dat` file, did you try the steps listed [**here**](https://github.com/allinurl/goaccess/blob/master/config/goaccess.conf#L559)?

**Comment by MelkorLord** [comment]
Hi,

Ok then, it's cleary a libGeoIP issue so I'll close this bug-report.

As of the right ```.dat``` file no worries, **correct** GeoIP setup is working fine. As you can see in the initial report, this was a simple test with a mere ```touch``` on a file. On Debian-like distros, there's this nice package ```geoip-database-contrib``` which downloads the current DB as well as setting up a cron job to refresh the DB each month.

**Comment by allinurl** [comment]
Thanks for pointing out `geoip-database-contrib`, was not aware of it :)
