### ISSUE TITLE
Option to remove "Last updated" info on reports

### ISSUE THREAD

**Issue by MelkorLord** [allinurl/goaccess#486]
Hi,

> Programming today is a race between software engineers striving to build bigger and better idiot-proof programs, and the Universe trying to produce bigger and better idiots. So far, the Universe is winning.
**Rick Cook**

Users are users right? Their job is to drown in a glass of water... (sigh!)

As I stated in most of my previous posts, I generate purely static HTML reports for the users to view on a one per day basis. Guess what? they're confused... They have hardtime wrapping their head around a very simple concept : To have the full stats on any given day, the report must be generated the NEXT day!

So, viewing the HTML report for "2016.08.01", there's an infobox on the right saying "Last updated: 2016-08-02 xx:xx:xx" and this confuses them!

Would it be possible to add an option to not show this field? like --no-last-updated-field

I've manually patched already generated reports and the very simple following fix works perfectly : 

```
.pull-right h4 {
  display: none;
}
```

Thanks

**Comment by allinurl** [comment]
This has been implemented. The option is `--no-html-last-updated`. It will be pushed out in the upcoming release. Otherwise, feel free to build from [development](https://github.com/allinurl/goaccess#build-from-github-development). Thank!
