### ISSUE TITLE
Display data in MB, GB instead of MiB, GiB

### ISSUE THREAD

**Issue by rageface** [allinurl/goaccess#489]
Hello, is there a way to display output in Megabytes and Gigabytes instead of default Gibibyte units?

I can't find the option on the manual.

Thanks in advance.

**Comment by allinurl** [comment]
Hello, currently there's no way to change the units. However, I can certainly look into it. It should also be part of issue #178.

As a side note, simply changing it to mb/gb should be fairly easy, just need to edit the following three [lines](https://github.com/allinurl/goaccess/blob/master/src/util.h#L36) and build again.

**Comment by rageface** [comment]
Thanks a lot, it would be awesome if you can add that option someday. At this moment i'll change those lines and rebuild.
