### ISSUE TITLE
Configuring and compiling GoAccess on FreeBSD 10.3

### ISSUE THREAD

**Issue by dorin21id** [allinurl/goaccess#494]
Hello

Having some issues compiling in freebsd 10.3
let me tell you the steps I've taken
```
pkg install GeoIP glib pkgconf
Updating FreeBSD repository catalogue...
FreeBSD repository is up-to-date.
All repositories are up-to-date.
Checking integrity... done (0 conflicting)
The most recent version of packages are already installed

setenv LDFLAGS -L/usr/local/lib
./configure --enable-geoip

Your build configuration:

  Prefix         : /usr/local
  Package        : goaccess
  Version        : 1.0.2
  Storage method : In-memory Hash Database (Default)
  GNU getline    : no
  Compiler flags :  -pthread
  Linker flags   : -lncurses -lGeoIP -lpthread  -L/usr/local/lib
  Bugs           : goaccess@prosoftcorp.com

make
./src/commons.h:38:10: fatal error: 'GeoIP.h' file not found
#include <GeoIP.h>
         ^
1 error generated.
*** Error code 1

Stop.
make[1]: stopped in /tmp/test/goaccess-1.0.2
*** Error code 1
```
Do you guys have any ideea what I could do ?

**Comment by dorin21id** [comment]
@allinurl  could you please help ?

**Comment by allinurl** [comment]
I don't have access to a FreeBSD machine right now. However, one thing I can say is that you don't need glib.

Please try from upstream:

# pkg install GeoIP
# export LDFLAGS=-L/usr/local/lib
# ./configure --enable-geoip --enable-utf8
# make
# make install

**Comment by dorin21id** [comment]
/tmp/test/goaccess-1.0.2 # export LDFLAGS=-L/usr/local/lib
export: Command not found.

**Comment by dorin21id** [comment]
before using setenv LDFLAGS -L/usr/local/lib I couldn't even do the configure because if would say I do not have geoIP. after setenv I get past the configure but cannot make

**Comment by dorin21id** [comment]
In case this helps let me show you the configure output

root@e5-2620v3x2:/tmp/test/goaccess-1.0.2 #  ./configure --enable-geoip
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... ./install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... nawk
checking whether make sets $(MAKE)... yes
checking for gcc... no
checking for cc... cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking for style of include used by make... GNU
checking dependency style of cc... gcc3
checking whether cc understands -c and -o together... yes
checking for pthread_create in -lpthread... yes
checking build system type... x86_64-unknown-freebsd10.3
checking host system type... x86_64-unknown-freebsd10.3
checking whether to build with rdynamic for GNU ld... yes
checking for GeoIP_new in -lGeoIP... yes
checking for refresh in -lncurses... yes
checking for library containing tputs... none required
checking for ncurses/ncurses.h... no
checking for ncurses.h... yes
checking for curses.h... yes
checking for socket in -lsocket... no
checking for gethostbyname in -lnsl... no
checking how to run the C preprocessor... cc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking arpa/inet.h usability... yes
checking arpa/inet.h presence... yes
checking for arpa/inet.h... yes
checking fcntl.h usability... yes
checking fcntl.h presence... yes
checking for fcntl.h... yes
checking for inttypes.h... (cached) yes
checking limits.h usability... yes
checking limits.h presence... yes
checking for limits.h... yes
checking locale.h usability... yes
checking locale.h presence... yes
checking for locale.h... yes
checking netdb.h usability... yes
checking netdb.h presence... yes
checking for netdb.h... yes
checking netinet/in.h usability... yes
checking netinet/in.h presence... yes
checking for netinet/in.h... yes
checking stddef.h usability... yes
checking stddef.h presence... yes
checking for stddef.h... yes
checking for stdint.h... (cached) yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking for strings.h... (cached) yes
checking sys/socket.h usability... yes
checking sys/socket.h presence... yes
checking for sys/socket.h... yes
checking sys/time.h usability... yes
checking sys/time.h presence... yes
checking for sys/time.h... yes
checking for unistd.h... (cached) yes
checking for an ANSI C-conforming const... yes
checking for ptrdiff_t... yes
checking whether struct tm is in sys/time.h or time.h... time.h
checking for int64_t... yes
checking for int8_t... yes
checking for off_t... yes
checking for size_t... yes
checking for uint32_t... yes
checking for uint64_t... yes
checking for uint8_t... yes
checking for _LARGEFILE_SOURCE value needed for large files... no
checking for working memcmp... yes
checking whether time.h and sys/time.h may both be included... yes
checking for sys/time.h... (cached) yes
checking for unistd.h... (cached) yes
checking for alarm... yes
checking for working mktime... no
checking whether lstat correctly handles trailing slash... yes
checking whether stat accepts an empty string... no
checking for strftime... yes
checking for working strtod... yes
checking for floor... no
checking for gethostbyaddr... yes
checking for gethostbyname... yes
checking for gettimeofday... yes
checking for malloc... yes
checking for memmove... yes
checking for memset... yes
checking for mkfifo... yes
checking for realloc... yes
checking for realpath... yes
checking for regcomp... yes
checking for select... yes
checking for setlocale... yes
checking for socket... yes
checking for strcasecmp... yes
checking for strchr... yes
checking for strcspn... yes
checking for strdup... yes
checking for strerror... yes
checking for strncasecmp... yes
checking for strpbrk... yes
checking for strrchr... yes
checking for strspn... yes
checking for strstr... yes
checking for strtol... yes
checking for strtoull... yes
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/config.h
config.status: executing depfiles commands

Your build configuration:

  Prefix         : /usr/local
  Package        : goaccess
  Version        : 1.0.2
  Storage method : In-memory Hash Database (Default)
  GNU getline    : no
  Compiler flags :  -pthread
  Linker flags   : -lncurses -lGeoIP -lpthread  -L/usr/local/lib
  Bugs           : goaccess@prosoftcorp.com

**Comment by allinurl** [comment]
You may need to compile without GeoIP. I won't have access to a freebsd box until next week though.

**Comment by dorin21id** [comment]
That is not an option :( we need it for the stats from varnish. I will try to figure it out myself. If you have any thoughts i will also check this thread. Thank you

**Comment by allinurl** [comment]
I'd say it very likely a lib geoip config issue on you machine. This was cross-platform tested.

**Comment by dorin21id** [comment]
I just did a pkg remove geoip then installed GeoIP-1.6.9 from ports net/GeoIP. Issue is the same :(

**Comment by dorin21id** [comment]
found a way to make it work:
root@e5-1620v3:/tmp/goaccess-1.0.2 # find / -name "GeoIP.h"
/usr/local/include/GeoIP.h
root@e5-1620v3:/tmp/goaccess-1.0.2 # cp /usr/local/include/GeoIP.h /tmp/goaccess-1.0.2/src/

in case anyone else has this problem

**Comment by allinurl** [comment]
OK, I finally got my hands on a FreeBSD machine. Here's what I did to build goaccess:

    # pkg install GeoIP
    # /usr/local/bin/geoipupdate.sh
    -- just to check where is the lib and header
    # find / -name '*GeoIP*' -print
    # ./configure CFLAGS="-I/usr/local/include" LDFLAGS="-L/usr/local/lib" --enable-utf8 --enable-geoip
    # make
    # make install

This was done on a 

    FreeBSD  10.3-RELEASE FreeBSD 10.3-RELEASE #0 r297264

**Comment by dorin21id** [comment]
Your solution is cleaner than mine. Thank you

**Comment by allinurl** [comment]
Closing this. Thanks!
