### ISSUE TITLE
goaccess 1.0.2 on OSX El Capitan

### ISSUE THREAD

**Issue by cooker47** [allinurl/goaccess#495]
Installed using Homebrew. 
Having configuration issues trying to get a "live" (updated in place) web page.
My goaccess.conf contains a line "real-time-html true".
Trying to connect from different browsers using ws://0.0.0.0:7890, having tried http://localhost:7890, etc., firewall off, and so on.
On the face of it this should be very simple to do, and I am wondering what I am misreading or not seeing in the docs. 
Is anybody else doing this on OSX?

**Comment by allinurl** [comment]
The process of generating a real-time HTML report is very similar to the process of creating a static report.

Just generate a static report and place the output html file under your web server www public folder.

    # goaccess -f access.log -o /usr/share/nginx/www/rt.goaccess.io/report.html --real-time-html --ws-url=host 

Upon opening the generated report in your browser, the report will try to establish a WebSocket connection to the host specified by --ws-url=host. Note that the host should point to the location where GoAccess is running and parsing logs. Also, make sure host is a valid host and should not contain http on it.

If you don't use --ws-url, it will attempt to establish the WebSocket connection to localhost, which means that GoAccess should be running on your local machine (the same machine running the browser)

Also, feel free to post any error message from the browser dev tools.

**Comment by allinurl** [comment]
Is it safe to close this? or are you still having issues with it?

**Comment by cooker47** [comment]
Thanks for the further explanation.
I got it to work with goaccess 1.0.2. 
I'd been having problems with 0.9.8 earlier.
