### ISSUE TITLE
add support to timezone

### ISSUE THREAD

**Issue by flyisland** [allinurl/goaccess#496]
right now, we have to use "%^" to ignore the timezone like "+0800". but it'll be confused while the web server used UTC format for the request time.

**Comment by allinurl** [comment]
Thanks for suggesting this. Can you please elaborate a bit more how the timezone should be displayed in goaccess and the use case you have in mind?

**Comment by flyisland** [comment]
my suggestion:
1. goaccess uses UTC internally
2. provide `timezone` setting in UI

**Comment by allinurl** [comment]
I'm not sure I follow. Are you looking to convert the given log time to a specific timezone? which panel would be affected with this change? Right now goaccess simply uses/displays the date and time that the access log has on it.

**Comment by flyisland** [comment]
"08/Aug/2016:16:49:16 +0800" and "08/Aug/2016:08:49:16 +0000" actually are the same time, but will be different in goaccess since goaccess will simply ignore the `timezone` field.

I sometimes have to use goaccess to analyze the performance of websites which with different datetime format setting, ignoring the `timezone` will be confused in some situation.

**Comment by allinurl** [comment]
Got it. I'll look into this. Thanks for the reply!

**Comment by ray-moncada** [comment]
How do I set the timezone when creating an HTML report?

**Comment by allinurl** [comment]
@ray-moncada are you asking about the last updated time zone? or for each metric? If the latter, then it uses the tz from your access log.

**Comment by iskandarsaleh** [comment]
hi, @allinurl 
would you mind that i have example log like this : 
2020/07/20 14:53:27.396 [I] [inquiry.go:47]  Request Inquiry QRIS:  {"dataQr":"https://support.lenovo.com/qrcode?sn=PF11UNLP&mtm=80XK0052ID","issuer":"JATxxx","custAccount":"0812xxx"}

how can i setting this kind of log to view on goaccess 

for now i get error : goaccess: unrecognized option '--3' 

thanks before


regards

**Comment by allinurl** [comment]
@iskandarsaleh seems like there's no valid IP. goaccess requires a valid IPv4/6, a request and date/time.

**Comment by alaskapublic** [comment]
> @allinurl This is my scenario. The server time is +0000, my local is time is -0500. When goaccess static report is generated, is there a way to have the report show my local time zone?

I'll second this issue. 

Server time is in UTC, and local time is -8 or -9 depending on Daylight Savings Time.
Problem is that the logs are all shifted by 8 or 9 hours. 

This makes it problematic when looking at:
Unique visitors per day,
Time Distribution

Is it possible to add a TimeZone flag when running GoAccess so that upon ingesting the logs or creating the report it will shift the date/time the X amount of hours? (I don't think it wouldn't be feasible to do it in the GUI due to the date's shifting when the time changes.) 

Thanks.
Piet

**Comment by lucasteinke** [comment]
I saw #1104 but apparently there's still some changes to be done as the time zones didn't get parsed correctly for my current application. There's also no mention of a time zone variable on https://goaccess.io/man#options, so I guess this hasn't been implemented yet. @millsjustin @allinurl?

**Comment by allinurl** [comment]
Thanks for the heads up! It's not implemented yet, but let me work on this in the next few days and I'll post back.

**Comment by allinurl** [comment]
Finally this has been implemented. Please build from [**development**](https://github.com/allinurl/goaccess#build-from-github-development) and let me know how that goes. Here's how it works:

Given a sample log request:

    dot.com:80 192.168.0.1 - - [24/Jun/2022:22:14:26 -0500] "GET /robots.txt HTTP/1.1" 200 304 "-" "BacklinkCrawler (http://www.backlinktest.com/crawler.html)" 1232

We run goaccess with two new options, `--datetime-format=<date_time_format>` and `--tz=<timezone>`. e.g.,

    # goaccess access.log --log-format='%v:%^ %h %^[%x] "%r" %s %b "%R" "%u" %D' --datetime-format='%d/%b/%Y:%H:%M:%S %z' --tz=Europe/Berlin --date-spec=min

**NOTE:** We use `%x` inside `--log-format` to specify the date and time and capture the UTC offset (see `strptime`). Also, `--tz` expects the canonical timezone name, e.g., `Europe/Berlin` or `America/Chicago` or `Africa/Cairo` or `Japan` or `Asia/Shanghai` or `Asia/Seoul`. If the timezone is invalid, the output will be in GMT.

![2022-06-24-062713_665x167_scrot](https://user-images.githubusercontent.com/5005367/175525459-e3eae6d4-633b-4183-af61-8b2df6f2db69.png)

**Comment by PaddyPat** [comment]
Any tipps, howto handle caddy epoche time format with gmt + 2

Example epoche time: 1657046018.3796463


caddy-goaccess-1  | ==1== FILE: /data/access.log
caddy-goaccess-1  | ==1== Parsed 10 lines producing the following errors:
caddy-goaccess-1  | ==1==
caddy-goaccess-1  | ==1== Token 'el":"info","ts":1657005103' doesn't match specifier '%x'
caddy-goaccess-1  | ==1== Token 'el":"info","ts":1657005103' doesn't match specifier '%x'
caddy-goaccess-1  | ==1== Token 'el":"info","ts":1657005103' doesn't match specifier '%x'
caddy-goaccess-1  | ==1== Token 'el":"info","ts":1657005103' doesn't match specifier '%x'
caddy-goaccess-1  | ==1== Token 'el":"info","ts":1657005103' doesn't match specifier '%x'
caddy-goaccess-1  | ==1== Token 'el":"info","ts":1657005103' doesn't match specifier '%x'
caddy-goaccess-1  | ==1== Token 'el":"info","ts":1657005103' doesn't match specifier '%x'
caddy-goaccess-1  | ==1== Token 'el":"info","ts":1657005103' doesn't match specifier '%x'
caddy-goaccess-1  | ==1== Token 'el":"info","ts":1657005103' doesn't match specifier '%x'
caddy-goaccess-1  | ==1== Token 'el":"info","ts":1657005103' doesn't match specifier '%x'
caddy-goaccess-1  | ==1==
caddy-goaccess-1  | ==1== Format Errors - Verify your log/date/time format
caddy-goaccess-1  | Cleaning up resources...

**Comment by allinurl** [comment]
@PaddyPat You will need to set `--datetime-format` to %s as that's what Caddy uses (see `man strptime`). e.g.,

access.log

```
{"level":"info","ts":1651059867.9669144,"logger":"http.log.access.log0","msg":"handled request","request":{"remote_ip":"172.70.126.198","remote_port":"17446","proto":"HTTP/2.0","method":"GET","host":"auth.samcro1967.net","uri":"/auth/assets/google-webfonts/fonts/roboto-v20-latin-500.woff2","headers":{"Origin":["https://auth.samcro1967.net"],"Sec-Fetch-Site":["same-origin"],"Cdn-Loop":["cloudflare"],"Cf-Ipcountry":["US"],"Sec-Ch-Ua-Mobile":["?0"],"Accept-Language":["en-US,en;q=0.9"],"Accept-Encoding":["gzip"],"X-Forwarded-Proto":["https"],"Sec-Fetch-Mode":["cors"],"Sec-Fetch-Dest":["font"],"User-Agent":["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36"],"Sec-Ch-Ua-Platform":["\"Windows\""],"Cf-Ray":["70274e6e69f72ad6-ORD"],"Cf-Visitor":["{\"scheme\":\"https\"}"],"Sec-Ch-Ua":["\" Not A;Brand\";v=\"99\", \"Chromium\";v=\"100\", \"Google Chrome\";v=\"100\""],"Accept":["*/*"],"Referer":["https://auth.samcro1967.net/auth/assets/google-webfonts/roboto.css"],"Cookie":[],"Cf-Connecting-Ip":["71.86.152.82"],"X-Forwarded-For":["71.86.152.82"]},"tls":{"resumed":false,"version":772,"cipher_suite":4865,"proto":"h2","server_name":"auth.samcro1967.net"}},"user_id":"","duration":0.000351604,"size":15872,"status":200,"resp_headers":{"Etag":["j5VqMRVAR9G2Untj2y7PDzpGPyQ="],"Cache-Control":["max-age=7200"],"Server":["Caddy"],"Content-Type":["font/woff2"]}}
{"level":"info","ts":1651059868.0079823,"logger":"http.log.access.log0","msg":"handled request","request":{"remote_ip":"172.70.126.244","remote_port":"54526","proto":"HTTP/2.0","method":"GET","host":"auth.samcro1967.net","uri":"/auth/assets/line-awesome/fonts/la-solid-900.woff2","headers":{"Accept-Encoding":["gzip"],"Cf-Ray":["70274e6e69f62ad6-ORD"],"X-Forwarded-Proto":["https"],"Cf-Visitor":["{\"scheme\":\"https\"}"],"Sec-Fetch-Mode":["cors"],"Cookie":[],"Sec-Fetch-Site":["same-origin"],"Cdn-Loop":["cloudflare"],"X-Forwarded-For":["71.86.152.82"],"Sec-Ch-Ua":["\" Not A;Brand\";v=\"99\", \"Chromium\";v=\"100\", \"Google Chrome\";v=\"100\""],"Sec-Ch-Ua-Mobile":["?0"],"User-Agent":["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36"],"Sec-Ch-Ua-Platform":["\"Windows\""],"Accept":["*/*"],"Accept-Language":["en-US,en;q=0.9"],"Cf-Connecting-Ip":["71.86.152.82"],"Sec-Fetch-Dest":["font"],"Referer":["https://auth.samcro1967.net/auth/assets/line-awesome/line-awesome.css"],"Cf-Ipcountry":["US"],"Origin":["https://auth.samcro1967.net"]},"tls":{"resumed":false,"version":772,"cipher_suite":4865,"proto":"h2","server_name":"auth.samcro1967.net"}},"user_id":"","duration":0.041859575,"size":96752,"status":200,"resp_headers":{"Cache-Control":["max-age=7200"],"Server":["Caddy"],"Content-Type":["font/woff2"],"Etag":["idlTHAxwqHUd_4PBkXuqsfFqIHE="]}}
```

Analyze with:

    goaccess access.log --date-spec=min --datetime-format='%s' --tz=Europe/Berlin --log-format='{"ts":"%x.%^","request":{"remote_ip":"%h","proto":"%H","method":"%m","host":"%v","uri":"%U","headers":{"User-Agent":["%u","%^"]},"tls":{"cipher_suite":"%k","proto":"%K"}},"duration":"%T","size":"%b","status":"%s","resp_headers":{"Content-Type":["%M"]}}'

**Comment by allinurl** [comment]
After playing around with the Unix time, I noticed a bug that would perform the timezone conversion twice. 

I just pushed a fix for this. Please feel free to test it out by building from [**development**](https://github.com/allinurl/goaccess#build-from-github-development) and let me know if that looks right on your end. I plan to push this out soon in the upcoming release. Thanks.

**Comment by PaddyPat** [comment]
I've tryed it (use goaccess in docker with goaccess.conf)

```
date-spec min
datetime-format %s
tz Europe/Berlin
log-format {"ts":"%x.%^","request":{"remote_ip":"%h","proto":"%H","method":"%m","host":"%v","uri":"%U","headers":{"User-Agent":["%u","%^"]},"tls":{"cipher_suite":"%k","proto":"%K"}},"duration":"%T","size":"%b","status":"%s","resp_headers":{"Content-Type":["%M"]}}
```

This looks well, but not at top right corner.

![2022-07-06 07_51_00-](https://user-images.githubusercontent.com/11161270/177478746-8387bb01-791a-49a0-a52d-23ab6958fe8b.jpg)

Thanks for your help!
Maybe, I've seen you can change in Caddyfile by logging the time format:

```
(log_to_file) {
        log {
               level INFO
               format json {
                       time_format     **common_log**
               }
                output file /data/access.log {
                        roll_size 100mb
                        roll_keep 10
                        roll_keep_for 720h
                }
        }
}
```

**Comment by PaddyPat** [comment]
I've tryed it (use goaccess in docker with goaccess.conf)

```
date-spec min
datetime-format %s
tz Europe/Berlin
log-format {"ts":"%x.%^","request":{"remote_ip":"%h","proto":"%H","method":"%m","host":"%v","uri":"%U","headers":{"User-Agent":["%u","%^"]},"tls":{"cipher_suite":"%k","proto":"%K"}},"duration":"%T","size":"%b","status":"%s","resp_headers":{"Content-Type":["%M"]}}
```

This looks well, but not at top right corner.

![2022-07-06 07_51_00-](https://user-images.githubusercontent.com/11161270/177478746-8387bb01-791a-49a0-a52d-23ab6958fe8b.jpg)

Thanks for your help!

FYI: I've seen, you can change in Caddyfile the logging time format:

**time_format     common_log**

```
(log_to_file) {
        log {
               level INFO
               format json {
                       time_format     common_log
               }
                output file /data/access.log {
                        roll_size 100mb
                        roll_keep 10
                        roll_keep_for 720h
                }
        }
}
```

Log format common_log:

```
{"level":"info","ts":"06/Jul/2022:06:35:42 +0000","logger":"http.log.access.log11","msg":"handled request","request":{"remote_ip":"192.168.1.23","remote_port":"53205","proto":"HTTP/2.0","method":"GET","host":"portal.xyz.de","uri":"/static/media/roboto-v29-latin-900.153ba331.woff2","headers":{"Sec-Ch-Ua":["\".Not/A)Brand\";v=\"99\", \"Microsoft Edge\";v=\"103\", \"Chromium\";v=\"103\""],"Sec-Ch-Ua-Platform":["\"Windows\""],"Accept":["*/*"],"Sec-Fetch-Dest":["font"],"Referer":["https://portal.xyz.de/static/css/main.c88e903b.chunk.css"],"Sec-Ch-Ua-Mobile":["?0"],"User-Agent":["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.66 Safari/537.36 Edg/103.0.1264.44"],"Accept-Encoding":["gzip, deflate, br"],"Origin":["https://portal.xyz.de"],"Sec-Fetch-Site":["same-origin"],"Sec-Fetch-Mode":["cors"],"Accept-Language":["de,de-DE;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6"],"If-None-Match":["W/\"3d6c-17fc15d1000\""],"Dnt":["1"],"If-Modified-Since":["Fri, 25 Mar 2022 13:56:16 GMT"]},"tls":{"resumed":false,"version":772,"cipher_suite":4865,"proto":"h2","server_name":"portal.xyz.de"}},"user_id":"","duration":0.001834299,"size":0,"status":304,"resp_headers":{"Referrer-Policy":["strict-origin-when-cross-origin"],"X-Xss-Protection":["1; mode=block"],"Set-Cookie":[],"X-Content-Type-Options":["nosniff"],"X-Powered-By":["Express"],"Accept-Ranges":["bytes"],"Date":["Wed, 06 Jul 2022 06:35:42 GMT","Wed, 06 Jul 2022 06:35:41 GMT"],"Cache-Control":["public, max-age=0"],"Last-Modified":["Fri, 25 Mar 2022 13:56:16 GMT"],"Etag":["W/\"3d6c-17fc15d1000\""],"Permissions-Policy":["interest-cohort=()"],"Server":["Caddy"],"X-Frame-Options":["SAMEORIGIN"]}}
{"level":"info","ts":"06/Jul/2022:06:35:42 +0000","logger":"http.log.access.log11","msg":"handled request","request":{"remote_ip":"192.168.1.23","remote_port":"53209","proto":"HTTP/1.1","method":"GET","host":"portal.xyz.de","uri":"/socket","headers":{"Accept-Language":["de,de-DE;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6"],"Sec-Websocket-Extensions":["permessage-deflate; client_max_window_bits"],"User-Agent":["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.66 Safari/537.36 Edg/103.0.1264.44"],"Origin":["https://portal.x.ch"]yz.de,"Sec-Websocket-Version":["13"],"Accept-Encoding":["gzip, deflate, br"],"Sec-Websocket-Key":["FlwdVbtI3zn8LVOCfsREbA=="],"Connection":["Upgrade"],"Pragma":["no-cache"],"Cache-Control":["no-cache"],"Upgrade":["websocket"]},"tls":{"resumed":true,"version":772,"cipher_suite":4865,"proto":"http/1.1","server_name":"portal.xyz.de"}},"user_id":"","duration":0.412531777,"size":0,"status":200,"resp_headers":{"X-Content-Type-Options":["nosniff"],"X-Xss-Protection":["1; mode=block"],"Upgrade":["websocket"],"Connection":["Upgrade"],"Sec-Websocket-Accept":["EDKwiEm3F+INIHiVyblrQMJGmxk="],"X-Frame-Options":["SAMEORIGIN"],"Permissions-Policy":["interest-cohort=()"],"Set-Cookie":[],"Server":["Caddy"],"Date":["Wed, 06 Jul 2022 06:35:41 GMT"],"Referrer-Policy":["strict-origin-when-cross-origin"]}}

```
--

caddy-goaccess-1  | ==1== Token '06/Jul/2022:06:35:42 +0000' doesn't match specifier '%x'
caddy-goaccess-1  | ==1== Token '06/Jul/2022:06:35:42 +0000' doesn't match specifier '%x'
caddy-goaccess-1  | ==1== Token '06/Jul/2022:06:35:42 +0000' doesn't match specifier '%x'
caddy-goaccess-1  | ==1== Token '06/Jul/2022:06:35:42 +0000' doesn't match specifier '%x'
caddy-goaccess-1  | ==1== Token '06/Jul/2022:06:35:42 +0000' doesn't match specifier '%x'
caddy-goaccess-1  | ==1== Token '06/Jul/2022:06:35:42 +0000' doesn't match specifier '%x'

goaccess.conf:

log-format {"ts":**"%x"**,"request":{"remote_ip":"%h","proto":"%H",...
--

Thanks for your help!

**Comment by allinurl** [comment]
@PaddyPat `--datetime-format='%d/%b/%Y:%H:%M:%S %z'` should do it for your new format.
