### ISSUE TITLE
segmentation fault in argument parsing

### ISSUE THREAD

**Issue by claudeha** [allinurl/goaccess#499]
There seems to be a crash issue in `read_option_args()` when goaccess is given bad options (-H and -M without corresponding required arguments):

    $ goaccess -f input.log -a -H -M --real-os > output.html &> /dev/null
    ==31433== GoAccess 1.0.2 crashed by Sig 11
    ==31433==
    ==31433== STACK TRACE:
    ==31433==
    ==31433== 0 goaccess(sigsegv_handler+0x17a) [0x40a7ca]
    ==31433== 1 /lib/x86_64-linux-gnu/libpthread.so.0(+0xf8d0) [0x7fa0f91998d0]
    ==31433== 2 goaccess(read_option_args+0x206) [0x413956]
    ==31433== 3 goaccess(main+0xaf) [0x40ff7f]
    ==31433== 4 /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf5) [0x7fa0f8e00b45]
    ==31433== 5 goaccess() [0x407e29]
    ==31433==
    ==31433== Please report it by opening an issue on GitHub:
    ==31433== https://github.com/allinurl/goaccess/issues

I suspect this isn't caught properly by getopt because H and M occur twice in `short_options[]`, the second time without an argument specifier:
https://github.com/allinurl/goaccess/blob/aad9ce076ad9afd440ddcf7fca347d09449e33b0/src/options.c#L51-L55

**Comment by allinurl** [comment]
Thanks for reporting it. This was fixed on issue #473. Building from development should address this. Otherwise it will be pushed out in the upcoming version.

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
