### ISSUE TITLE
realtime html and zcat

### ISSUE THREAD

**Issue by TAiS46** [allinurl/goaccess#500]
Hi there,

how can I use -real-time-html with zcat?

my current command is the following:
`sudo zcat -f /var/log/nginx/bla.log /var/log/nginx/foo.log | sudo goaccess -o /var/www/stats/report.html --real-time-html`

it creates the report.html but has no websocket running.
using this command without zcat and `-f *.log` works perfectly.

also is there a way to start goaccess on boot / as deamon?

**Comment by allinurl** [comment]
Hello,

Great question, currently goaccess disables the real-time functionality when reading from stdin. This will be addressed on issues #428 and filtering in #117. In the meantime, a workaround is to output to a new log file and use that to feed goaccess.

As far as starting goaccess as a service, there are a few ways of doing this, please take a look at this [**post**](http://blog.sudoask.com/run-goaccess-as-service-use-systemd/). 

Let me know if that helps.

**Comment by TAiS46** [comment]
Maybe it will be possible in a new version to add two files to goaccess without using zcat.
Like `goaccess -f file1.log file2.log -o report.html --real-time-html`

For one log file --real-time-html work without any issues.

**Comment by allinurl** [comment]
Thanks for the suggestion! Actually #459 is also part of it. I'm hoping I can get to this in one of the upcoming versions. Closing this for now as it will be addressed in one of the issues mentioned above. Stay tuned.

**Comment by allinurl** [comment]
@TAiS46 I've pushed a [commit](https://github.com/allinurl/goaccess/commit/c6bdee378195332f5464472fa45d7a32b9cbe1fc) that enables the ability to output live stats from a stream or an unclosed STDIN, i.e., tail -f as well as parsing multiple logs in live mode:

    goaccess --log-format=COMBINED access.log access.log.1 -o report.html --real-time-html

or

    tail -f access.log | goaccess --log-format=COMBINED -

or even

    tail -f access.log | goaccess --log-format=COMBINED -o report.html --real-time-html -

It also opens the possibility for live data filtering from the pipe such as:

    tail -f access.log | grep -i 'firefox' | goaccess --log-format=COMBINED -

Feel free to build from [master](https://github.com/allinurl/goaccess#build-from-github-development) to test this out, otherwise it will be pushed out in the upcoming release. Thanks.

**Comment by ningappa** [comment]
is there ay way to  make it work with zcat and websocket.?

`zcat -f /var/log/apache2/access* |  goaccess --log-format=COMBINED -o /var/www/html/report.html --real-time-html --ws-url=server.ip -p /etc/goaccess.conf`

**Comment by allinurl** [comment]
@ningappa `zcat` will probably close the pipe once it has finished reading the logs, you probably want to parse the current log by passing it to goaccess instead and use zcat for previous logs. Note, this hasn't been pushed out, but will be pushed out in the upcoming release, e.g.,

    zcat -f /var/log/apache2/access.log.* | goaccess --log-format=COMBINED -o /var/www/html/report.html --real-time-html --ws-url=server.ip -p /etc/goaccess.conf /var/log/apache2/access.log -

**Comment by allinurl** [comment]
@ningappa Just pushed a commit that should allow you to run the command I posted above (_live stats and zcat_). Feel free to build from [**development**](url) to this out before is shipped in the upcoming version.

**Comment by ningappa** [comment]
@allinurl thanks. it's working. :+1:
