### ISSUE TITLE
Add ws-protocol option

### ISSUE THREAD

**Issue by jkroepke** [allinurl/goaccess#502]
Refer #474

I want to run goacces via https, too. Since goaccess can't handle https, I want to use my nginx proxy to offloading ssl, which is pretty easy:

```
if ($http_upgrade = "websocket") {
  proxy_pass http://localhost:8090;
}
```
goaccess hardcoding the websocket protocol to ws://:

```var socket = new WebSocket('ws://' + str);```

I want simply to use wss://.

**Comment by allinurl** [comment]
Just to be clear here, are you looking to have an option to use either `ws` or `wss`? e.g., 

    --ws-protocol=ws|wss

where the JS code would look like:

    var socket = new WebSocket('wss://' + str);

**Comment by jkroepke** [comment]
Yes. SSL offloading will be handled by nginx.

**Comment by allinurl** [comment]
This has been implemented. However, instead of using another command line option, you can specify ws|wss within the --ws-url option. For instance,

     --ws-url=ws://goaccess.io                
     --ws-url=wss://goaccess.io             
     --ws-url=goaccess.io                       
     --ws-url=ws://goaccess.io:9999

**Comment by allinurl** [comment]
BTW, feel free to build from [development](https://github.com/allinurl/goaccess#build-from-github-development). Otherwise, it will be pushed out in the upcoming release.
