### ISSUE TITLE
Binary package depends on dev lib

### ISSUE THREAD

**Issue by szepeviktor** [allinurl/goaccess#503]
`Depends: libc6 (>= 2.7), libncursesw5 (>= 5.5-5~), libgeoip-dev (>= 1.4.8)`

Please consider depending on libgeoip1 if it is necessary at all.

All the best!

**Comment by allinurl** [comment]
This has been changed. New version has been [**deployed**](https://goaccess.io/).

**Comment by szepeviktor** [comment]
Thanks.
