### ISSUE TITLE
Add a oneshot option

### ISSUE THREAD

**Issue by jkroepke** [allinurl/goaccess#504]
Hi,

I want replace my awstats with this super cool tool. We have many virtual hosts and I don't have the ressource to run goaccess multiple times. 

If I write all vhosts to one log, I can not filter the stats by one virtual hosts. 

Its posible to run goaccess with oneshot to generate an html file? So I can run this tool cron-like like awstats until the virtual host filter is there.

**Comment by allinurl** [comment]
It is possible to generate an html file in one shot and deduce some stats from the vhost panel. However, if you are looking to get one full report per vhost, then you will need to parse one by one. As you said, this should be covered when #117 is implemented.
