### ISSUE TITLE
Where is the default config file path?

### ISSUE THREAD

**Issue by virtualdreams** [allinurl/goaccess#505]
I build goaccess from src with ./configure --enable-geoip --enable-utf8
After build, i run goaccess --dcf and get:

No default config file found.
You may specify one with `-p /path/goaccess.conf`

Jep, thats helpful. Not. How to specify the the default config path/file or where search for it? I don't mean the -p option. Missing documentation about!

Please help :)

**Comment by allinurl** [comment]
Did you actually install it with `# make install` or just `make`? You need to fully install it from source so that it knows where `SYSCONFDIR` is pointing to.

Also, take a look at the [FAQ](https://goaccess.io/faq) for details on where the configuration file is located.

**Comment by virtualdreams** [comment]
I do just make, no make install, because i copy the binary to the target machine...
I try make install on my build machine.

**Comment by allinurl** [comment]
You will need a full `make install`. I haven't tested if copying the binary to a different machine will do it. Otherwise, you will need to fully install it directly on the target machine.

**Comment by virtualdreams** [comment]
Copying goaccess after make install to /usr/local/bin/ and the config file to /usr/local/etc/ on the target machine works perfectly.

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
