### ISSUE TITLE
merging log files across load-balanced webservers

### ISSUE THREAD

**Issue by clueo8** [allinurl/goaccess#506]
Is goaccess intelligent enough to be able to merge access logs across multiple load-balanced web servers?  I tried pipping over 1GB of logs across 8 web servers to it and it ran over 24 hours and didn't export an html report, the "number/s" just slowly decreased... Not sure if that was the right thing to do.  Or should I just generate 8 reports and then add them all up to get a total...?

**Comment by allinurl** [comment]
goaccess will merge all data logs that you pipe into it and it will output one report out of the whole dataset. e.g.,

    # zcat -f access.log* | goaccess

Can you please post how you are running goaccess and how you are feeding the logs to it? Depending on your machine, but 1GB log should go pretty fast.

**Comment by clueo8** [comment]
I was cd'ed into a parent folder which contained sub-folders (one for each server; containing its access logs within) and then ran this from the parent folder:

zcat */access.log* | goaccess -o ~/report.html

Not sure if the first "*" caused any issues with it; I did that so that it would go into the sub folder... Each server had around 100 log files in it's sub-folder...

**Comment by allinurl** [comment]
I believe `zcat` won't be able to do that (haven't tested), however, I'll try this, it should work:

    find . -type f -name "*.log" -exec cat {} + | goaccess --log-format=VCOMBINED -o ~/report.html

assumes the following structure

```
.
├── server1
│   └── access.log
├── server2
│   └── access.log
├── server3
│   └── access.log
└── server4
    └── access.log
```

**Comment by clueo8** [comment]
I believe that will work, but my logs were so large, it just was taking forever, thanks!
