### ISSUE TITLE
src/parser.c

### ISSUE THREAD

**Issue by hdatma** [allinurl/goaccess#510]
When parsing a log line, matching failures ought to be sent to /dev/stderr. 
This helps both devs and users.

**Comment by hdatma** [comment]
example:

log_format custom  '[$time_iso8601] [CLIENT:] [$remote_addr] [$geoip_latitude,$geoip_longitude] [$geoip_city] [$geoip_city_country_code] [$http_user_agent] [$ssl_protocol] [$ssl_cipher] [subject: $remote_user] [verb: $request_method] [object: $request] [$query_string] [$http_referer] [SERVER:] [$status] [$body_bytes_sent bytes] [$request_time seconds]';

[2016-09-04T17:51:07+02:00] [CLIENT:] [157.55.39.21] [38.0000,-97.0000] [-] [US] [Mozilla/5.0 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)] [TLSv1.2] [ECDHE-RSA-AES256-SHA384] [subject: -] [verb: GET] [object: GET /robots.txt HTTP/1.1] [-] [-] [SERVER:] [200] [244 bytes] [0.000 seconds]

time-format %H:%M:%S%^
date-format %Y-%m-%d
log-format [%dT%t] [CLIENT:] [%h] [%^,%^] [%^] [%^] [%u] [%H] [%^] [subject: %^] [verb: %m] [object: %U] [%q] [%R] [SERVER:] [%s] [%b bytes] [%L seconds]

GoAccess - version 1.0.2 - Jul  5 2016 09:55:48
Config file: /etc/goaccess.conf
Fatal error has occurred
Error occured at: src/goaccess.c - main - 1230
Nothing valid to process. Verify your date/time/log format.

**Comment by allinurl** [comment]
Thanks for pointing this out. It will be addressed on issue #264.
