### ISSUE TITLE
unknown wechat browser 

### ISSUE THREAD

**Issue by hynnet** [allinurl/goaccess#514]
unknown wechat browser :

"Mozilla/5.0 (iPhone; CPU iPhone OS 9_0_1 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Mobile/13A404 MicroMessenger/6.3.23 NetType/WIFI Language/zh_CN"

**Comment by allinurl** [comment]
So is `MicroMessenger` the name of the browser? Thanks

**Comment by allinurl** [comment]
This has been added as `MicroMessenger`. Thanks.
