### ISSUE TITLE
Compress HTML output - script and style tags

### ISSUE THREAD

**Issue by hdatma** [allinurl/goaccess#518]
Notes from using 
https://code.google.com/archive/p/htmlcompressor/

> java -jar /opt/htmlcompressor.jar --remove-intertag-spaces --remove-surrounding-spaces=max --remove-link-attr --remove-script-attr --simple-bool-attr --compress-css --output "${filename}-min.html" "${filename}.html"

reductions obtained from local tests, in bytes:

624028 -> 525397
516752 -> 443984
410946 -> 364242

**Comment by allinurl** [comment]
For this, I'll need to write a custom script (probably using sed/awk) to minify style and script tags, so when the code gets compiled, it automatically compress the whole output.

**Comment by JeroenVanOort** [comment]
May I ask why one would want to do this? I understand that compression has benefits when working with high traffic sites where performance is non-negotiable. But please enlighten me on why you would want to use it on static HTML files that are only viewed by a site administrator.

**Comment by allinurl** [comment]
@JeroenVanOort You are right. I think there is minimal gain on this. However, I'll keep this open  for now and see how much it can be done without spending too much time on it.

**Comment by allinurl** [comment]
This has been implemented. It will be pushed out in the upcoming release. Thanks
