### ISSUE TITLE
GoAccess Dockerfile

### ISSUE THREAD

**Issue by francislavoie** [allinurl/goaccess#520]
Just found this tool, looks brilliant!

I was hoping to use this along with Caddy to watch the access logs in my docker-compose stack. I found there was a couple very outdated third party implementations.

https://github.com/diyan/goaccess-docker
https://github.com/joelchen/goaccess

Both of these are pre-1.0.0. I was hoping for an official Docker image with support for running and watching the Caddy logs in realtime.

Thanks

**Comment by francislavoie** [comment]
I did build myself a Dockerfile which works fine for just processing one-off files for now, but I can't get realtime working. I'm not sure how to make the `goaccess` command run in the foreground.

```Dockerfile
FROM alpine:3.4

MAINTAINER Francis Lavoie <lavofr@gmail.com>

ENV goaccess_version=1.0.2
ENV build_deps='go build-base ncurses-dev'

RUN set -x && \
    apk add --update ncurses $build_deps && \
    wget -O /tmp/goaccess.tar.gz http://tar.goaccess.io/goaccess-$goaccess_version.tar.gz && \
    tar -xzvf /tmp/goaccess.tar.gz -C /tmp && \
    cd /tmp/goaccess-$goaccess_version && \
    ./configure --enable-utf8 && \
    make && \
    make install && \
    apk del $build_deps && \
    rm -rf /var/cache/apk/* /tmp/goaccess*

ADD ./goaccess.conf /usr/local/etc/goaccess.conf

EXPOSE 7890

ENTRYPOINT ["goaccess"]
```

Usage:
Make sure you have a `goaccess.conf` file in the same dir, it gets copied into the container.
Build with `$ docker build -t goaccess .`
Do stuff `$ cat access.log | docker run -i goaccess > access.html`

**Comment by allinurl** [comment]
Thanks for sharing this! Were you able to get the real-time report working?

**Comment by francislavoie** [comment]
Yeah - see the edit at the bottom. Problem is though, I need to generate
the HTML somewhere on the host first right now with this setup. I'll
probably expand on it and make a repo with Caddy to serve the HTML and
proxy the websockets.

**Comment by allinurl** [comment]
One of the things I need to do is to daemonize a process so it won't stick to a TTY as it is right now. 

I'll play with the docketfile you posted here. Also, I didn't know about Caddy, look pretty interesting :+1:

**Comment by brandon099** [comment]
@allinurl or @francislavoie: Any progress on this, or need any help testing? I've got a Docker-Compose stack as well that I'd like to include GoAccess with 😃

**Comment by allinurl** [comment]
@brandon099 are you asking about the docker file? I have not had the chance to look at daemonizing a process, but I can bump this up in the to-do list, it shouldn't be to bad though. Any help is always welcome :)

**Comment by francislavoie** [comment]
I haven't touched this since either, I ended up just setting up netdata and not doing anything with my logs for this project. Still interested in a proper solution but I don't have much time to allocate to it.

**Comment by brandon099** [comment]
Yeah I was asking about the Dockerfile. If you could bump up the daemonized process functionality on the to-do list, I can certainly work on the Dockerfile piece when that's done!

Thanks for your work on this, it's an awesome project!

**Comment by allinurl** [comment]
@brandon099 I just added `--daemonize` command line option to run goaccess as a [daemon](https://github.com/allinurl/goaccess/commit/d7796129dca51f9adea0a38fe8ae8a47cffdebb1) (if `--real-time-html` enabled). It will be shipped in the upcoming version.
