### ISSUE TITLE
Get latency metric

### ISSUE THREAD

**Issue by arjm** [allinurl/goaccess#522]
Hi,

GoAccess tool is great and easy to use, however it lacks documentation. I am unable to figure out the way to measure latency of my calls (and extend it to see 90p, 99p latency). How do I measure it?

Appreciate developers' response.

**Comment by allinurl** [comment]
Hello there,  to get the average, cumulative and maximum time served in GoAccess, you will need to start logging response times in your web server. In Nginx you can add `$request_time` to your log format, in Apache, you may use `%D`. Then restart the server.

Once your access logs contain the response time, you will need to use one of the served time [**specifiers**](https://goaccess.io/man#custom-log) in goaccess' log-format variable. i.e., `%D` for Apache or `%T` for Nginx.

Let me know if that helps.

**Comment by allinurl** [comment]
Quoting an email from @arjm 

> Thanks Gerardo! I figured it out, and it worked flawlessly. 

I've added a note to the [**man page**](http://dev.goaccess.io/man#custom-log). Closing this.
