### ISSUE TITLE
Add Visitors Geolocation Map

### ISSUE THREAD

**Issue by watermelonjuice** [allinurl/goaccess#524]
GoAccess currently displays visitor city and country under Visitor Hostnames and IPs. Creating a new module with map displaying location of visitors will be a great enhancement.

This can be broken down into two types of maps. Current Visitors similar to Google's Analytics Real Time and Historical Visitors.

**Comment by allinurl** [comment]
I can look into this. However, I wonder if you need a real-time geolocation map considering that GoAccess displays all its panels in real-time (as opposed to Google Analytics where the majority of the data is not real-time)... Thoughts?

**Comment by watermelonjuice** [comment]
By "real time" what is meant is limiting it to the past 20 minutes or 1 hour.

**Comment by allinurl** [comment]
Got it. I actually plan to add the ability to filter complete datasets, issue #117 should handle time/date ranges in real time.

Thanks for the suggestion! Please keep this open so I can look into it.

**Comment by Natsec** [comment]
Hi, I just started using GoAccess two days ago and it is a wonderful tool, amazing work.
Is there anything new/planned about this feature ?

**Comment by allinurl** [comment]
@Natsec Certainly there's still a plan to add this, just haven't got the chance to work on this specific issue. The plan is to implement a d3.js map and probably with the option to have the bar/line charts in addition to the map.

**Comment by AcidRain9** [comment]
Is it implemented yet? I can’t seem to find it

**Comment by allinurl** [comment]
@AcidRain9 unforgettably it hasn't. stay tuned!

**Comment by floviolleau** [comment]
Hi,

Any hopes that it will be implemented?

Thanks for developing this great tool!

**Comment by allinurl** [comment]
@floviolleau It will. Looking into it. [Stay tuned.](https://twitter.com/goaccess)

**Comment by samularity** [comment]
Hy, any news on that? 
It would be awesome to have a city level map like this (circles in one colour)
<img src="https://github.com/allinurl/goaccess/assets/6522373/896ce06c-e95e-4ca2-a925-66eecebbffbd"  alt="map" style="float:right" width="300" height="250"/> 
[img src: https://www.zeemaps.com/blog/radius-map/]

**Comment by allinurl** [comment]
@samularity, alright, so I was just checking out how to make this work, and it doesn't seem too complicated, at least for a basic version. We probably need to add a new GeoJSON file to the report and tweak the current charts a bit. Do you know your way around JS and D3?

**Comment by samularity** [comment]
> @samularity, Do you know your way around JS and D3?
unfortunately not

**Comment by allinurl** [comment]
If I can't add it in an early release, I'll include it in v2.0. Stay [tuned for updates](https://twitter.com/goaccess).

**Comment by allinurl** [comment]
This feature has been added and it will be included in the upcoming release. [**Stay tuned**](https://twitter.com/goaccess) You'll still have the choices for area and bar charts available.

Don't hesitate to create a new issue if you encounter any problems with this. Thanks again!
