### ISSUE TITLE
http 500 error with report.html

### ISSUE THREAD

**Issue by anselal** [allinurl/goaccess#525]
Hi,
I am running goaccess v1.0.2. I create a static html file, since my server is running with SSL, with the followinf command:

`goaccess -f access.log -a /vhosts/selalmaz.xyz/report.html`

When I open the file in my browser https://selalmaz.xyz/report.html I see nothing and I get an HTTP 500 error on my apache log file. Any other files are working just fine on my host, for ex. https://selalmaz.xyz/foo.html

Can you give me a hand on this ?

**Comment by allinurl** [comment]
It seems like you are missing the `-o`, please try:

    goaccess -f access.log -a -o /vhosts/selalmaz.xyz/report.html

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
