### ISSUE TITLE
Report only shows breakdown on Android but not iOS

### ISSUE THREAD

**Issue by tiznull** [allinurl/goaccess#526]
## Problem:

If you generate a report derived from Mobile Devices data, then iOS is only classified by device type, whereas Android has every version broken down.

In the log I parsed, iOS shows version numbers. But Goaccess did not parse them as expected.
## Expected Result:

If the reader views the OS report, the same version breakdown that appears for Android Devices (Shows Version and Device) would also be visible iOS Devices.
## Output from report using log data (sample below)

![image](https://cloud.githubusercontent.com/assets/4011347/18738372/09d4bbe4-8050-11e6-89f1-3c675242ac9d.png)
## Sample data from log:

0.0.0.0 - - [08/Jan/2016:05:40:58 -0000] "GET /index.html" 200 - - "Mozilla/5.0 (iPad; **CPU OS 9_1** like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Mobile/13B143 (5442293344)"
0.0.0.0 - - [08/Jan/2016:05:41:00 -0000] "GET /index.html" 200 - - "Mozilla/5.0 (iPad; **CPU OS 9_2** like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Mobile/13C75 (5341655216)"
0.0.0.0 - - [08/Jan/2016:05:41:01 -0000] "GET /index.html" 200 - - "Mozilla/5.0 (**iPad; CPU OS 9_2** like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Mobile/13C75 (5895339392)"

**Comment by allinurl** [comment]
I'll add this. Thanks for pointing this out!

**Comment by tiznull** [comment]
Thank you!

**Comment by tiznull** [comment]
Let me know if you need a larger dataset to test with. I can create an excerpt for you.

**Comment by allinurl** [comment]
This has been [**added**](https://github.com/allinurl/goaccess/commit/ca365f917e3b9cdf87819e2fba8761140e60d491). Now it ensures every version of iOS is broken down under the OS panel.

Feel free to build from [**development**](https://github.com/allinurl/goaccess#build-from-github-development), otherwise it will be deployed soon in the upcoming version.
