### ISSUE TITLE
help to construct log-format 

### ISSUE THREAD

**Issue by Scofields** [allinurl/goaccess#527]
Please, help to construct log-format for my config.

# nginx.conf

    log_format api.xx.com 'v1{]api.xx.com{]$request{]HHvDHAMjq2I{]$year$month$day $hour$minute$second{]$status{]-]$request_time_usec{]$body_bytes_sent{]$bytes_sent{]$remote_addr{]$http_x_forwarded_for{]$http_referer{]-{]$http_user_agent{]-{]$uid{]$http_via{]v1';

# access.log
    v1{]api.xx.com{]POST /api/app/novelUpdate.m?a=1&cid=eef_easou_book&version=002&os=android&udid=69A7503DE9EEDA688BCF8C47B1B01424&appverion=1032&ch=blp1375_14135_001&statId=cQf8j5ORw1Zh4Gd8wIS261cG9ZbjG HTTP/1.1{]HHvDHAMjq2I{]20160922 155158{]200{]-{]169531{]160{]398{]117.136.61.73{]-{]-{]-{]Dalvik/2.1.0 (Linux; U; Android 5.1.1; Redmi Note 3 MIUI/V7.9.9.0.LHOCNCL){]-{]{]-{]v1

**Comment by allinurl** [comment]
Interesting format you got there... This should work:

    goaccess -f access.log --log-format='%^]%v{]%r{]%^{]%d %t{]%s{]%-{]%D{]%^{]%b{]%h{]%^{]%R{]%^{]%u{%^' --date-format='%Y%m%d' --time-format='%H%M%S'

**Comment by Scofields** [comment]
![image](https://cloud.githubusercontent.com/assets/5830141/18772004/18d16576-8176-11e6-9a16-dd6a54fef558.png)
it's  not work  and how to debug ?

**Comment by allinurl** [comment]
It does work for the line you posted above. Please make sure your access log looks has the exact same format as the sample line posted above.

**Comment by allinurl** [comment]
![2016-09-22-212406_746x326_scrot](https://cloud.githubusercontent.com/assets/5005367/18772241/ea6f14fa-810a-11e6-9574-e5f99407a6b4.png)

**Comment by Scofields** [comment]
Thanks,
update GoAccess 0.9.3 to  GoAccess 1.0.2
it's work

**Comment by allinurl** [comment]
Great to hear that! Closing this.
