### ISSUE TITLE
Add option to see crawlers/bots only stats

### ISSUE THREAD

**Issue by chhantyal** [allinurl/goaccess#529]
There is very useful option `--ignore-crawlers`. However, I would like to request another option which is just opposite of above `--crawlers-only`.
I am trying to investigate sudden increase in bots/crawlers traffic for for a web server and it seems currently there is no way to check bots only stats. 

And thank you for this great piece of software. Works really great.

**Comment by allinurl** [comment]
I agree on this. I'll add this option. Thanks!

**Comment by allinurl** [comment]
The option `--crawlers-only` has been added. It will be pushed out in the upcoming version.

Thanks!
