### ISSUE TITLE
GoAccess can't parse the logs for HTTP Live

### ISSUE THREAD

**Issue by andygr** [allinurl/goaccess#530]
Hello,

I have some issues while i am trying to parse the logs for the live HTTP. Also i merged the nginx logs but GoAccess can read only 3 days (instead of 15).

The config in Nginx.conf is;

    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;
    log_format main '$remote_addr - $remote_user [$time_local] "$request" $status $bytes_sent "$server_name" "$http_referer" "$http_user_agent"';

A sample log from Nginx is:

    82.34.69.231 - - [02/Oct/2016:22:33:34 +0100] "GET /report.html HTTP/1.1" 304 0 "http://savannacdn.com/" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:49.0) Gecko/20100101 Firefox/49.0"

The config in GoAccess.conf is:

    time-format %H:%M:%S
    date-format %d/%b/%Y
    log-format %h %^[%d:%t %^] "%r" %s %b "%R" "%u"

At the moment i am using  logresolvemerge.pl to merge all the logs and i am just parsing one file:
logresolvemerge.pl /var/log/nginx/access.log* > all_access.log

The issues that i am facing are:
1) By using this command to parse the logs:

    goaccess -f /var/log/nginx/all_access.log  -o  /usr/share/nginx/www/report.html --real-time-html

I am getting this: (stays at this state, is this ok?)
Parsing... [4,278] [0/s]

The websocket is listening:

    tcp        0      0 127.0.0.1:7890          0.0.0.0:*               LISTEN

And i can telnet:
```
telnet localhost 7890
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
```

2) The merged log file have logs from 14/09/2016 to 02/10/2016 but the report.html have only from 30/09-02/10

![2016-10-02_23-42-03](https://cloud.githubusercontent.com/assets/1921610/19024384/530f9ab0-88fa-11e6-81a4-c85fb92e98b4.png)

Thank you in advance for your time and help
Andrew

**Comment by allinurl** [comment]
Can you please confirm you have all of these dates? Please post the output of:

    awk '{print $4}' /var/log/nginx/all_access.log | awk '{print substr($1,2,11); }' | sort -u | uniq

**Comment by andygr** [comment]
Hello,
this is result i got:

 awk '{print $4}' /var/log/nginx/all_access.log | awk '{print substr($1,2,11); }' | sort -u | uniq
01/Oct/2016
02/Oct/2016
12/Sep/2016
13/Sep/2016
14/Sep/2016
15/Sep/2016
16/Sep/2016
17/Sep/2016
18/Sep/2016
19/Sep/2016
20/Sep/2016
21/Sep/2016
22/Sep/2016
23/Sep/2016
24/Sep/2016
25/Sep/2016
26/Sep/2016
27/Sep/2016
28/Sep/2016
29/Sep/2016
30/Sep/2016

**Comment by andygr** [comment]
The URL for the report is: http://savannacdn.com/report.html

**Comment by allinurl** [comment]
I get:

> The content that you are trying to access are Geo-Restricted.

BTW, are you using v1.0.2? and how many dates do you see on the visitors panel? do you see all of them?

**Comment by andygr** [comment]
I opened the CDN, should be ok now
Yes i am using the v1.0.2 and i can see 544 visitors, I believe should be more but i am not 100% sure.
Does GoAccess, get the date from the log file? (as per the awk command?)

**Comment by allinurl** [comment]
Got it. In your case, GoAccess did parse the whole log, but since you're using the real-time functionality, it displays only the last 50 records (days) per panel. However, your specificity is set to hours, so it's displaying the last 50 hours instead, thus `30/Sep/2016 - 02/Oct/2016`.

The 544 visitors should be right - `Hits having the same IP, date and agent are a unique visit`.

**Comment by andygr** [comment]
Thank you for the explanation, is there a way to present more data on the dashboard?

**Comment by allinurl** [comment]
The 50 items on the real-time report is a fixed limit to avoid hitting the browser's performance. However, you can generate a static report (without `--real-time-html`), which by default will output 366 items.

There's also the flag `--max-items=<num>` which  sets the maximum number of items to display per panel. The maximum can be a number between 1 and n. 

**Note**: Only the CSV and JSON output allow a maximum number greater than the default value of 366 (or 50 in the real-time HTML output) items per panel.

**Comment by andygr** [comment]
If i use this command, will generate the static report?
goaccess -f /var/log/nginx/all_access.log -a > /usr/share/nginx/www/report.html

When i am trying to generate a report, i am getting this:
Parsing... [4,211] [0/s]

Is this normal because is listening the websocket?

**Comment by allinurl** [comment]
That should work, or,

    goaccess -f /var/log/nginx/all_access.log -a -o /usr/share/nginx/www/report.html

The output is normal in any output report, you can disable the progress with `--no-progress`.

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it as needed.
