### ISSUE TITLE
Puzzled with custom nginx format

### ISSUE THREAD

**Issue by huehnerhose** [allinurl/goaccess#533]
Hi, I am totally puzzled why I always get "no valid hits found"

    62.XXX.XXX.XXX - nginxCookie_www=VMgzClZLGttaiR6FAw2BAg==; nginxCookie_session=5deaf50a604c4eb3a651989508a295767d6e5f4a - 05/Oct/2016:06:53:12 +0200 - 200 - "POST /api/FOO HTTP/1.1" - "-" - "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko" - "-"

and as format:

     | Log Format - [c] to add/edit format         
     | %h - %^ - %d:%t - %s - %r - %^ - \"%u\" - %^
     | Date Format - [d] to add/edit format        
     | %d/%b/%Y                                                                              
     | Time Format - [t] to add/edit format        
     | %H:%M:%S %z                                 

I checked and retried and tried and rechecked a lot of variantions on the format strings. Any advice greatly appreciated!

**Comment by allinurl** [comment]
Can I ask you which field is the size of the response (bytes)? or if you can post your web server format would be great. Thanks

**Comment by huehnerhose** [comment]
I am afraid I don't have this field. Is it essential for goaccess to analyze the logs? I didn't see it in the documentation as required. (No doubt it would be a "nice" bit of information...)

**Comment by allinurl** [comment]
It's not required, but handy :) This should work (feel free to replace `"%R"` with `%^` if it's not the referrer):

    %h %^ %^ %^ %^ %d:%t %^ %^ %s %^ "%r" %^ "%R" %^ "%u"
    %d/%b/%Y
    %H:%M:%S

**Comment by huehnerhose** [comment]
ah great, this works! 
So I'll take dashes has to be treated as "fields" from that. 

Thanks!

**Comment by allinurl** [comment]
Glad that worked — That's right, you could consider dashes as fields. However, it is possible to do some skipping like moving to the next char such as:

    %h %^; %^ %^ %d:%t %^ %^ %s %^ "%r" %^ "%R" %^ "%u"

That assumes your log format has always a `;` at that position.
