### ISSUE TITLE
Unite several reports in one

### ISSUE THREAD

**Issue by konungrl** [allinurl/goaccess#537]
Greeting again, sir. 
I have a question. Is there any way to unite several reports in one big? 
I.e. i have report_mon, report_tue, .. report_sun. At the end of the week i need smth like report_week_1 that has all data from this 7 reports.
I know that i can do "cat access.log.* > goaccess " but it takes all memory because logs are too heavy.

**Comment by allinurl** [comment]
Hello, it sounds like you probably want to use the [**on-disk storage**](https://goaccess.io/man#storage), either to parse the whole week worth of logs or you can do [**incremental log processing**](https://goaccess.io/man#examples).

For the on-disk tree, you can get it from the official deb repo with (if you are using ubuntu/debian):

    apt-get install goaccess-tcb

 or you will need to compile from source, e.g.,

```
$ ./configure --enable-utf8 --enable-geoip --enable-tcb=btree 
$ make 
# make install

```

Let me know if you have any questions about this.

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
