### ISSUE TITLE
Unable to use Apache's "remote user" field

### ISSUE THREAD

**Issue by barry-luijten** [allinurl/goaccess#538]
Hi,

I would like to use goaccess to gather statistics per authenticated user. I am using Apache's standard NCSA combined log format:
"%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-agent}i\""
In this format, %u (field #3) represents the username, but goaccess does not allow me to specify this field in a standard or custom log format (%u is already used for "user agent"). I have searched the man page and the issues in this github repo, but could only find examples where people are ignoring this field (by using %^ as the field's placeholder).
I guess this is a feature request, but I hope it's just a question ;)

Best regards,
Barry

**Comment by allinurl** [comment]
Hi Barry,

That's right, currently the user field it's ignored. However, recently issue **#516** came up with the same request. I'll implement this and post back as soon as it is out. Thanks for the suggestion as well.

**Comment by barry-luijten** [comment]
Thanks Gerardo, apparently I did not search well enough ;)!

**Comment by allinurl** [comment]
This has been implemented (commit: [**1c2750b**](https://github.com/allinurl/goaccess/commit/1c2750ba0419a79b71642ac29956f1f4028a2bb3)). It will be deployed in the upcoming release (pretty soon).

Feel free to build from [**development**](https://github.com/allinurl/goaccess#build-from-github-development) if needed.
