### ISSUE TITLE
Unable to open fifo in: Permission denied.

### ISSUE THREAD

**Issue by benwah** [allinurl/goaccess#539]
I'm running into this error on a Vagrant machine running Debian Jessie. This happens when I enable "--real-time-html" option:

```bash
www-data@jessie:~/goaccess$ goaccess -f /var/log/nginx/access.log.1 -o /var/www/goaccess/index.html  --real-time-html

GoAccess - version 1.0.2 - Sep 25 2016 18:44:17
Config file: /etc/goaccess.conf

Fatal error has occurred
Error occured at: src/websocket.c - ws_openfifo_in - 1830
Unable to open fifo in: Permission denied.

www-data@jessie:~/goaccess$ 
```

This does not happen with root user. Any idea what's going on?

**Comment by benwah** [comment]
Agh - Ok I fixed it.

WS_PIPEIN is hard-coded to /tmp/wspipein.fifo and WS_PIPEOUT to /tmp/wspipeout.fifo. Because I ran with root before, www-data user didn't have permission to open them. Just rm those files and run command once again.

**Comment by allinurl** [comment]
That's great it worked :) I just opened a new issue #540 to add a command line option to set these two since it's already possible in [gwsocket.](https://github.com/allinurl/gwsocket#command-line--config-options). 

Thanks.
