### ISSUE TITLE
How to uninstall GoAccess from source [tar.gz]

### ISSUE THREAD

**Issue by gregzed** [allinurl/goaccess#542]
How to completly remove if I installed with these commands

$ wget http://tar.goaccess.io/goaccess-1.0.2.tar.gz 
$ tar -xzvf goaccess-1.0.2.tar.gz 
$ cd goaccess-1.0.2/ 
$ ./configure --enable-geoip --enable-utf8 
$ make 
$ make install

**Comment by allinurl** [comment]
# make uninstall

**Comment by gregzed** [comment]
Yes thank you
