### ISSUE TITLE
Real Time report error

### ISSUE THREAD

**Issue by tlearyus** [allinurl/goaccess#543]
Am trying to generate a real time report but keep getting an error

This is the command I am using on Centos running Cloud Linux 

    goaccess -f /usr/local/apache/logs/access_log -o /usr/share/nginx/www/rt.goaccess.io/report.html --real-time-html --ws-url=http://northcoastinternet.com.au/report.html --log-format=COMBINED

What am I doing wrong? IS the host URL correct? tried without setting that but not sure what URL i need to use to access the real time report on?

**Comment by allinurl** [comment]
Please take a look at the [FAQ](https://goaccess.io/faq), how to generate a real-time report.

In your case, it seems you are almost there, however, don't need http on the `ws-url` option. Please try:

    goaccess -f /usr/local/apache/logs/access_log -o /usr/share/nginx/www/rt.goaccess.io/report.html --real-time-html --ws-url=northcoastinternet.com.au --log-format=COMBINED

That assumes `northcoastinternet.com.au` or `182.160.142.26` is the server where GoAccess is parsing access logs and that you have port 7890 opened. 

Also, v1.0.2 does not support accessing the report via HTTPS, so when you access the report through your browser, you will need to do it through HTTP.  Issue #474 will address this soon.

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.

**Comment by tlearyus** [comment]
Hi i just tried your suggestion and it parses the report no problem but nothing happens (blank page) when i visit northcoastinternet.com.au:7890 or 182.160.142.26:7890

i tried both your suggestion outputting to your shared folder and also mine outputting to the goaccess folder on my server. Port 7890 is open on my firewall and restarted iptables to be sure.

goaccess -f /usr/local/apache/logs/access_log -o /usr/share/nginx/www/rt.goaccess.io/report.html --real-time-html --ws-url=northcoastinternet.com.au --log-format=COMBINED

goaccess -f /usr/local/apache/logs/access_log -o /root/goaccess-1.0.2/report.html --real-time-html --ws-url=northcoastinternet.com.au --log-format=COMBINED

How do i specify the location the report.html gets saved in?

**Comment by allinurl** [comment]
You can output to your documentroot, or to the same path you did with this [**report**](northcoastinternet.com.au/report.html). The report is placed in the path specified with `-o`, for instance,  `-o /usr/share/nginx/www/rt.goaccess.io/report.html`

I just opened the report above and I checked the browser dev tools and I got this:

    WebSocket connection to 'ws://host:7890/' failed: Error in connection establishment: net::ERR_NAME_NOT_RESOLVED

So it seems you are specifying an invalid host in `--ws-url`. Try `--ws-url=<SERVER_IP>`and check your browser console for any possible errors.

**Comment by tlearyus** [comment]
i give up, can't get it working after a week of trying.
