### ISSUE TITLE
Need help with log-format for a apache behind a load-balancer

### ISSUE THREAD

**Issue by bodkov** [allinurl/goaccess#544]
I have difficulties to figure out which log-format directive I have to use for this Apache Logformat directive:

    "%{X-Forwarded-For}i %h %l %u %t %D \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\""

The server is behind a load balancer and the log files look something like this:

    XXX.XXX.XXX.XXX, XXX.XXX.XXX.XXX XXX.XXX.XXX.XXX - - [14/Oct/2016:17:05:26 +0200] 15622 "GET /style/css/css.css HTTP/1.1" 200 842 "-" "Proxy sfe HttpClient"

I have worked my way through issue #78 but none of the examples work.

**Comment by allinurl** [comment]
The following should do it:

    goaccess -f log --log-format='%h,| %^[%d:%t %^] %D "%r" %s %b "%R" "%u"' --date-format='%d/%b/%Y' --time-format='%T'

Please note that support to parse the `X-Forwarded-For` field is not out yet (coming out soon). You will need to build from [**development**](https://github.com/allinurl/goaccess#build-from-github-development) to get this feature.

**Comment by bodkov** [comment]
It's working with the development version! Thanks!
