### ISSUE TITLE
Display analytics for one specific VirtualHost

### ISSUE THREAD

**Issue by josephernest** [allinurl/goaccess#546]
Let's `goaccess -f access.log` with 1 week of logs. The panel `> 9 - Virtual Hosts` displays:
```
 Hits   Vis.      %   Bandwidth Data
 ------ ---- ------ ----------- ----
 ...
 11089   290  5.83%    4.14 MiB www.sitea.com
 4873    348  2.56%  443.20 MiB www.siteb.com
 2606   1258  1.37%  465.10 MiB www.sitec.com
 2159    454  1.14%  193.24 MiB www.sited.com
```

**How to ask GoAccess to display analytics for `sitea.com` only, for each day (without exiting goaccess and doing a CLI command) ?**

Example:

    www.sitea.com   oct-18       56 visits
    www.sitea.com   oct-17       36 visits
    www.sitea.com   oct-16       192 visits
    ...

**Comment by allinurl** [comment]
Currently not possible without doing some preprocessing (e.g., grep, awk, etc), however, **#117** will definitely cover this. In fact, the filtering feature is the next big update that GoAccess will get, both in the HTML side and the terminal side :)

**Comment by josephernest** [comment]
Thanks for this answer @allinurl!
Do you already have a beta test version that has this feature? I'd love to test this, because without this, I can't use GoAccess (I have 10 virtualhosts and I need to see which traffic comes from where)
Congrats again for this tool!

**Comment by allinurl** [comment]
Unfortunately no beta yet. Stay tuned though, I expect this to come soon!

**Comment by mohsen** [comment]
Isn't this yet available? I need to filter output only for a single host and ignore the rest lines of access log file.

**Comment by allinurl** [comment]
@mohsen Working on [#117](https://github.com/allinurl/goaccess/issues/117#issuecomment-1015917684) as we speak. Stay tuned as it will be out rather sooner than later.
