### ISSUE TITLE
Display full URL for a referrer

### ISSUE THREAD

**Issue by josephernest** [allinurl/goaccess#547]
In the `Referring sites` view:
```
 > 11 - Referring Sites
 Hits Vis.      %   Bandwidth Data
 ---- ---- ------ ----------- ----
 3       3  0.02%    1.05 KiB abc.com
 3       1  0.02%   30.12 KiB test.com
 3       1  0.02%   30.12 KiB test3.com
 2       2  0.01%   49.29 KiB www.google.com
```

is it possible to ask GoAccess to show more details about a precise line?

e.g. for the line ` 3       1  0.02%   30.12 KiB test3.com` I would like to know:

* when it has been visited
* which exact URL has been visited on my website
* which is the exact referrer URL ( `http://test3.com/...`)

Is it possible?

**Comment by allinurl** [comment]
#117 should address this.

For now, you can do some pre-processing such as:

    # awk '$1~/test3.com/' /var/log/apache2/access.log | goaccess

That assumes your virtualhost is the first field on your log.  It's best to check which field you are shooting for, e.g.:

    # tail -10 /var/log/apache2/access.log | awk '{print $1}'

**Comment by josephernest** [comment]
Thank you very much.
