### ISSUE TITLE
speed issue for goaccess 1.0.2 vs 0.9.8

### ISSUE THREAD

**Issue by arrfab** [allinurl/goaccess#549]
Hi,
We updated a node with goaccess 1.0.2 (to test another issue, but I'll create a different bug report) and it seems we suffer from a huge speed issue between the two versions (on the same node, same log file) : 
* with 0.9.8 : 
```
time goaccess -f /home/stats/${vhost}-combined.log > /home/stats/$(hostname)-${vhost}.html
Parsing... [309,466] [61,893/s]
real	0m5.613s
user	0m5.522s
sys	0m0.096s
```

* with 1.0.2:
```
time goaccess -f /home/stats/${vhost}-combined.log > /home/stats/$(hostname)-${vhost}.html
Parsing... [313,354] [12,052/s]
real	0m26.511s
user	0m25.338s
sys	0m1.139s
```

Reverting to 0.9.8 is then showing back the performances from before

Platform : CentOS 7.x (updated) / x86_64

Let me know if you need something else to troubleshoot that issue

**Comment by allinurl** [comment]
Due to the real-time functionality, some refactoring was done to the parser, however, the different shouldn't be that much. Did you build it to use the default hash tables? 

This is what I'm getting:

```
goaccess-0.9.8# time ./goaccess -f /var/log/apache2/access.log -p config/goaccess.conf > report.html
Parsing... [385,103] [35,009/s]
real    0m11.164s
user    0m11.045s
sys     0m0.100s
```

```
goaccess-1.0.2# time ./goaccess -f /var/log/apache2/access.log -p config/goaccess.conf > report.html
Parsing... [385,905] [32,158/s]
real    0m12.892s
user    0m12.793s
sys     0m0.076s
```

**Comment by arrfab** [comment]
oh, I reused some spec files from Fedora to rebuild for CentOS 7 but they changed the %configure line in the spec file : 

* 0.9.8 : 
%build
autoreconf -fiv
%configure --enable-debug --enable-geoip --enable-utf8
make %{?_smp_mflags}

* 1.0.2 : 
%build
autoreconf -fiv
%configure --enable-debug --enable-geoip --enable-utf8 --enable-tcb=btree --with-getline
%make_build

So I guess I need to build it without "--enable-tcb=btree " .. let me test that with a rebuild/modified .spec

**Comment by arrfab** [comment]
I confirm that it works now, but wondering why they added "--enable-tcb=btree" option by default

This is what I get now :
time goaccess -f /home/stats/${vhost}-combined.log > /home/stats/$(hostname)-${vhost}.html
Parsing... [309,327] [61,865/s]]
real    0m6.174s
user    0m6.076s
sys     0m0.080s

For reference, here are the built pkgs : 
https://cbs.centos.org/koji/packageinfo?packageID=4472

**Comment by allinurl** [comment]
Glad that worked. I'm not why, but thanks for changing this!
