### ISSUE TITLE
JSON is not valid? (%09 in logs)

### ISSUE THREAD

**Issue by pawelrosada** [allinurl/goaccess#550]
Hello.

I have problem with json output in goaccess. 
When parsing log looks like:

`192.168.1.1 - - [16/Oct/2016:00:04:35 +0200] "GET /%09/index.php?grupa=3&dzi=1322405905&id_menu=35 HTTP/1.1" 404 226 "" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:32.0) Gecko/20100101 Firefox/32.0"
`
I receives in output json:
`{"general": {"date_time": "2016-10-20 10:54:37","total_requests": 1,"valid_requests": 1,"failed_requests": 0,"generation_time": 0,"unique_visitors": 0,"unique_files": 0,"excluded_hits": 0,"unique_referrers": 0,"unique_not_found": 1,"unique_static_files": 0,"log_size": 196,"bandwidth": 226,"log_path": "test.log"},"visitors": {"metadata": {"bytes": {"count": 226,"max": 226,"min": 226},"visitors": {"count": 0,"max": 0,"min": 0},"hits": {"count": 1,"max": 1,"min": 1}},"data": [{"hits": {"count": 1,"percent": 100.00},"visitors": {"count": 0,"percent": 0.00},"bytes": {"count": 226,"percent": 100.00},"data": "20161016"}]},"requests": {"metadata": {"bytes": {"count": 0,"max": 0,"min": 0},"visitors": {"count": 0,"max": 0,"min": 0},"hits": {"count": 0,"max": 0,"min": 0}},"data": []},"static_requests": {"metadata": {"bytes": {"count": 0,"max": 0,"min": 0},"visitors": {"count": 0,"max": 0,"min": 0},"hits": {"count": 0,"max": 0,"min": 0}},"data": []},"not_found": {"metadata": {"bytes": {"count": 226,"max": 226,"min": 226},"visitors": {"count": 0,"max": 0,"min": 0},"hits": {"count": 1,"max": 1,"min": 1}},"data": [{"hits": {"count": 1,"percent": 100.00},"visitors": {"count": 0,"percent": 0.00},"bytes": {"count": 226,"percent": 100.00},"method": "GET","protocol": "HTTP/1.1","data": "\/\	\/index.php"}]},"hosts": {"metadata": {"bytes": {"count": 226,"max": 226,"min": 226},"visitors": {"count": 0,"max": 0,"min": 0},"hits": {"count": 1,"max": 1,"min": 1}},"data": [{"hits": {"count": 1,"percent": 100.00},"visitors": {"count": 0,"percent": 0.00},"bytes": {"count": 226,"percent": 100.00},"data": "192.168.1.1"}]},"os": {"metadata": {"bytes": {"count": 226,"max": 226,"min": 226},"visitors": {"count": 0,"max": 0,"min": 0},"hits": {"count": 1,"max": 1,"min": 1}},"data": [{"hits": {"count": 1,"percent": 100.00},"visitors": {"count": 0,"percent": 0.00},"bytes": {"count": 226,"percent": 100.00},"data": "Windows","items": [{"hits": {"count": 1,"percent": 100.00},"visitors": {"count": 0,"percent": 0.00},"bytes": {"count": 226,"percent": 100.00},"data": "Windows 7"}]}]},"browsers": {"metadata": {"bytes": {"count": 226,"max": 226,"min": 226},"visitors": {"count": 0,"max": 0,"min": 0},"hits": {"count": 1,"max": 1,"min": 1}},"data": [{"hits": {"count": 1,"percent": 100.00},"visitors": {"count": 0,"percent": 0.00},"bytes": {"count": 226,"percent": 100.00},"data": "Firefox","items": [{"hits": {"count": 1,"percent": 100.00},"visitors": {"count": 0,"percent": 0.00},"bytes": {"count": 226,"percent": 100.00},"data": "Firefox\/32.0"}]}]},"visit_time": {"metadata": {"bytes": {"count": 226,"max": 226,"min": 226},"visitors": {"count": 0,"max": 0,"min": 0},"hits": {"count": 1,"max": 1,"min": 1}},"data": [{"hits": {"count": 1,"percent": 100.00},"visitors": {"count": 0,"percent": 0.00},"bytes": {"count": 226,"percent": 100.00},"data": "00"}]},"referring_sites": {"metadata": {"bytes": {"count": 0,"max": 0,"min": 0},"visitors": {"count": 0,"max": 0,"min": 0},"hits": {"count": 0,"max": 0,"min": 0}},"data": []},"geolocation": {"metadata": {"bytes": {"count": 0,"max": 0,"min": 0},"visitors": {"count": 0,"max": 0,"min": 0},"hits": {"count": 0,"max": 0,"min": 0}},"data": []},"status_codes": {"metadata": {"bytes": {"count": 226,"max": 226,"min": 226},"visitors": {"count": 0,"max": 0,"min": 0},"hits": {"count": 1,"max": 1,"min": 1}},"data": [{"hits": {"count": 1,"percent": 100.00},"visitors": {"count": 0,"percent": 0.00},"bytes": {"count": 226,"percent": 100.00},"data": "4xx Client Error","items": [{"hits": {"count": 1,"percent": 100.00},"visitors": {"count": 0,"percent": 0.00},"bytes": {"count": 226,"percent": 100.00},"data": "404 - Not Found: Requested resource could not be found"}]}]}}`

JSON is not valid. 
Specifically line:
`"data": "\/\	\/index.php"`

Goaccess run command:
`goaccess -p goaccess.conf -f test.log -g -q -o json > test2.json`

Any ideas?

**Comment by allinurl** [comment]
Thanks for reporting this. It has been fixed. Feel free to build from [**development**](https://github.com/allinurl/goaccess#build-from-github-development). I'll push this out in the upcoming release.

**Comment by pawelrosada** [comment]
Thanks :)
