### ISSUE TITLE
goacces cron job not working

### ISSUE THREAD

**Issue by etomarat** [allinurl/goaccess#551]
Hello! If i run sh manually, output files was created and updated, but from cron job is not. How cat i fix it?

my `crontab`:
```
*/5 * * * * /home/monitoring/go_update.sh >> /home/monitoring/crontab.log
```

my `go_update.sh`:
```
#!/bin/sh
echo "start"
now=$(date +"%T")
echo "Current time : $now"
zcat /home/monitoring/logs-store/localway-prod-portal/localway-prod-portal.*.gz | goaccess -p /home/monitoring/.goaccessrc -a
echo "finish"
```

`cat crontab.log`:
```
start
Current time : 20:05:01
finish
```

part of `~/.goaccessrc`:
```
output-format /home/monitoring/goaccess/index.html
output-format /home/monitoring/goaccess/status.json
```

Thanx a lot!

**Comment by allinurl** [comment]
Can you please try using absolute paths, e.g. (assuming goaccess is under: `/usr/bin`):

    zcat /home/monitoring/logs-store/localway-prod-portal/localway-prod-portal.*.gz | /usr/bin/goaccess -p /home/monitoring/.goaccessrc -a

**Comment by allinurl** [comment]
Also, make sure the script is executable. 

    chmod +x /home/monitoring/go_update.sh

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.

**Comment by etomarat** [comment]
Thanx! Its work!
