### ISSUE TITLE
Is it possible to Export output in date vice

### ISSUE THREAD

**Issue by bentech4u** [allinurl/goaccess#553]
HI

i have a setup of goaccess generating logs of previous days by using cron job. so the output in goaccess is showing in a format as like starting from this month 1st to till previous day.

is it possible to generate date vice  report from goaccess frontend? instead of generating from command line.

Regards,
Ben

**Comment by allinurl** [comment]
If I follow correctly, you are trying to export a JSON report but you would like to filter by dates from the front end instead of the command line?

**Comment by bentech4u** [comment]
yea, compared to that generating from command line is better with specific dates logs

**Comment by allinurl** [comment]
Got it. Currently not possible, but issue **#117** will address this, it will be the next big update that GoAccess will get, both in the HTML side and the terminal side. Stay tuned!

**Comment by bentech4u** [comment]
HI

thanks for the update. 

please let me know when the major release will release.

Regards,
Ben
