### ISSUE TITLE
Wrong BW usage calculated

### ISSUE THREAD

**Issue by arrfab** [allinurl/goaccess#554]
Hi,
Not sure if that's an Apache/httpd log issue or a goaccess one.
Using goaccess-1.0.2 and when generating reports, it for example (for one of the vhosts on that system) calculates that BW usage was 401 TiB
While , at the switch/server port (zabbix monitoring) we calculated that it sent out (all traffic included, so raw data, not only httpd) ~43TB
Happy to help diagnosing the issue :-)

**Comment by allinurl** [comment]
Interesting, just to make sure is not a conversion issue, would you be able to generate a JSON report and ensure the vhost has the right number of bytes (401 TiB)?

Just to be sure, you can run this to get the total bytes (assuming bytes are followed by status):

    cat apache.log | perl -e 'my $sum=0; while(<>) { my ($traffic) = m/\[.+\] ".+" \d+ (\d+)/; $sum += $traffic}; print "$sum\n"'

**Comment by allinurl** [comment]
No worries, glad you were able to figured it out. Perhaps zabbix is calculating it based on compressed data? Issue #182 might help as well.

**Comment by arrfab** [comment]
No, Zabbix (at the interface level directly at the host) is calculating raw bytes leaving/entering the network interface, and we got confirmation from the DC people managing the switch on which that host is connected that it matches with what Zabbix says. So clearly something is b0rken at the Apache log level, but after some research, it seems lot of people are reporting that %B vs %b issue for 206 partial requests/range and so advice to use %O from http://httpd.apache.org/docs/2.4/mod/mod_logio.html
Probably worth mentioning here and also after some testing

**Comment by allinurl** [comment]
Thanks for posting this, definitely useful to know that!
