### ISSUE TITLE
Operating Systems and Browsers are 100 percent unknown

### ISSUE THREAD

**Issue by jubalh** [allinurl/goaccess#555]
I am using git version b6b47d3bc7d0cf38745d32a3ad262bab87dbb7fe.
I tried with both my apache and nginx logs and in both cases 'Operating System' and 'Browsers' are 100% unknown. Am I missing something here? Maybe I need to enable something in apache/nginx to log this?

**Comment by allinurl** [comment]
Sounds like a log config issue. Can you please post a few lines from your access log and the log format that you are using? Thanks

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.

**Comment by jubalh** [comment]
It's standard apache and nginx logs. I will see that I can get an example the next time I have access.

**Comment by allinurl** [comment]
This should do it:

    log-format COMBINED

**Comment by treetrnk** [comment]
I'm having this same issue with just Apache (on Arch Linux). Uncommenting `log-format COMBINED` did not fix the problem. [Here is my current config file](https://pastebin.com/b84HFJYT). Any ideas?

**Comment by allinurl** [comment]
@treetrnk Please comment out the log-format you are using and use the NCSA Combined Log Format:

    log-format %h %^[%d:%t %^] "%r" %s %b "%R" "%u"

Make sure no other `log-format` lines are uncommented.

**Comment by treetrnk** [comment]
That didn't take care of it either. Everything is still showing as unknown.

**Comment by allinurl** [comment]
@treetrnk please post/attach a few lines from your access log and I can take a look.

**Comment by treetrnk** [comment]
[Here are the logs](https://pastebin.com/EC2K5Skp).

I originally was using the common log format, but even after switching to the format you suggested, everything is showing up as unknown.

Thanks for taking a look.

**Comment by allinurl** [comment]
@treetrnk Assuming the first three lines were not meant to be there, I was able to run goaccess v1.2 using the NCSA Combined Log Format. This worked for me, (I got rid of the first three lines though)

    goaccess sample.log --log-format=COMBINED

Here's the output

![2017-09-21-071014_559x489_scrot](https://user-images.githubusercontent.com/5005367/30694914-b123fd0a-9e9b-11e7-9f8c-d3347a382a69.png)
