### ISSUE TITLE
Unique visitors

### ISSUE THREAD

**Issue by strang3r** [allinurl/goaccess#556]
I'm not quite sure if this should be considered an issue, an enhancement request or a simple question...it's sort of a mixture of all three.  The enhancement request may tie in with "Ability to aggregate visitors by month #139".

I need to be able to count unique visitors over a time period, say a week or a month.  Currently visitors are considered unique based on a combination of IP, date and user agent string, I need uniqueness to be based off of IP and user agent string only. It would be great if there was an option to do this, perhaps you could consider this for a future enhancement.

I am attempting to implement these changes on my own but I have not done any prior C programming so my skills are lacking.  I modified the get_uniq_visitor_key function in parser.c as follows:

```
get_uniq_visitor_key (GLogItem * logitem)
{
  char *ua, *key;
  size_t s1, s2;

  ua = deblank (xstrdup (logitem->agent));

  s1 = strlen (logitem->host);
  s2 = strlen (ua);

  /* includes terminating null */
  key = xmalloc (s1 + s2 + 2);

  memcpy (key, logitem->host, s1);

  key[s1] = '|';
  memcpy (key + s1 + 1, ua, s2 + 1);

  free (ua);
  return key;
}
```

This seems to have worked for some of the statistical data such as those for the HOSTS, OS, BROWSERS and GEO_LOCATION panels, but not for the VISITORS or VISIT_TIMES panels or for T_UNIQUE_VIS value in the dashboard.  There may be other panels but those are the ones I am interested it.  

There appears to be several keys used for data and my lack of C skills is making it difficult for me to pinpoint what I need to change.  If you could point me in the right direction I'd certainly appreciate it.

While looking at this I also notice that the value for visitors is different for each of the panels.  Here are the values I see when using an unmodified version of goaccess (v1.0.2) for data over a 1 day period:

```
DASHBOARD (Unique Visitors): 24,897
VISITORS: 24,897
HOSTS: 24,897
OS: 24,761
BROWSERS: 24,830
VISIT_TIMES: 69,709
GEO_LOCATION: 24,892
```

I expected the visitor count to be consistent across all panels.  Is this working as designed or is this an issue?  Can you help me understand the variance?

Any help is appreciated!

Thanks.

**Comment by allinurl** [comment]
Great questions and thanks for the suggestion of having a custom unique key. Please open a new issue for this feature so I can take a look into it.

As far as customizing the unique function, the following should do it:

```
static char *
get_uniq_visitor_key (GLogItem * logitem)
{
  char *ua, *key;

  ua = deblank (xstrdup (logitem->agent));

  key = malloc (snprintf (NULL, 0, "%s|%s", logitem->host, ua) + 1);
  sprintf (key, "%s|%s", logitem->host, ua); 

  free (ua);
  return key; 
}
```

Currently the way the visitors count works is by generating a unique key composed of `IP/date/UA` done by the `get_uniq_visitor_key()` function. Then each panel creates its own unique key based on at least one metric (the data field). 

For instance, the visitors panel uses `gen_visitor_key()`. This key is then appended to the `IP/date/UA` key which produces the unique count per unique data metric.

Given the example you posted above:

```
1 Overall (Unique Visitors) : 24,897
2 VISITORS                  : 24,897
3 HOSTS                     : 24,897
4 OS                        : 24,761
5 BROWSERS                  : 24,830
6 VISIT_TIMES               : 69,709
7 GEO_LOCATION              : 24,892

==

1 The overall unique count  is based on the visitors panel unique count.
2 VISITORS     -> `key(IP/date/UA+date)`.
3 HOSTS        -> `key(IP/date/UA+host)`.
4 OS           -> `key(IP/date/UA+os)`.
5 BROWSERS     -> `key(IP/date/UA+browser)`.
6 VISIT_TIMES  -> `key(IP/date/UA+time)`.
7 GEO_LOCATION -> `key(IP/date/UA+country)`.
```

As you noted on your post, the total visitors count in one panel can differ from other panels. Here is why: Assume, if you have a total of 7 unique visitors in your overall count, but seven of them visited only 1 file, then the total visitors on the requested files panel would be 1 instead of 7. 

Now let's think about the case where you have a total of 7 unique visitors in the overall count,  those 7 visitors visited your web server at 3 different times, 12am, 1pm, 2pm. Out of the 7 visitors, 1 visitor hit your server at 12am, 1 hit your server at 1pm and all of them hit it at 2pm. If you add up all of the visitors on that panel,  it yields to a total of 9 visitors (the column count you are seeing).

One thing to **highlight** is that the maximum number of visitors an item within a panel can have is equal or less than the overall unique visitors count.

Let me know if that helps.

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.

**Comment by strang3r** [comment]
Thank you for your update, I really appreciate it!  I will open a separate issue with the enhancement request for you consideration at another time.

Your explanation of the visitors count for each panel makes sense.  You say the maximum number of visitors an item within a panel can have is equal or less than the overall unique visitors count.  Do you mean to say it would be equal or *more* than the overall unique visitors count?  I ask because that would align with your example (9 column count for 7 unique visitors).  This would also make sense for the column counts I'm seeing for the likes of VISIT_TIMES (a higher value makes sense to me).  

What caught my attention initially is that some of the values are *less* than the unique visitors count.  In my sample data the OS, BROWSER and GEO_LOCATION panels all return a visitor count less than the total unique visitors.  I am assuming this happens if the the data metric can't be identified.  In my case specifically, the OS or browser could not be parsed from the UAS or the IP address is not listed in the geoip db.  Would that be right?

The changes to the `get_uniq_visitor_key ()` function goes a long way to providing the information I am looking for, it is just missing the most important part...the total unique visitor count (based on the new unique visitor key).  It looks like the value is generated from the `get_str_visitors ()` function which gets the size of unique maps of the VISITORS module (assocative array?).  If I could get this function to return a count of `logitem->uniq_key` values this should give me what I need, but I can't figure out if these values are stored in an array anywhere outside the module list.  I feel like the answer is right in front of me but I just cant see it.  Is there a simple way to have the overall unique count reflect the total number of unique visitors keys?

Cheers!

**Comment by strang3r** [comment]
I think I have things working.  I found the `ht_unique_keys` hash which, I believe, stores the unique keys generated by the `get_uniq_visitor_key ()` function.  The overall unique visitor count appears to be set in two places, `ui.c` (for the ncurses interface) and `json.c` (for the html output).  In order to retrieve the size of the hash in those two files I created a variable (unique_visitor_count) which I declared in `gkhash.h` and set in `gkhash.c`.  I think by your standards it's probably a bit of a dirty hack but it does appear to be working for me.  I have included the diff's below, if you see anything glaringly wrong let me know.

Thanks for the help, awesome application BTW.

[gkhash.h.diff.txt](https://github.com/allinurl/goaccess/files/567325/gkhash.h.diff.txt)
[gkhash.c.diff.txt](https://github.com/allinurl/goaccess/files/567326/gkhash.c.diff.txt)
[ui.c.diff.txt](https://github.com/allinurl/goaccess/files/567327/ui.c.diff.txt)
[json.c.diff.txt](https://github.com/allinurl/goaccess/files/567328/json.c.diff.txt)
[parser.c.diff.txt](https://github.com/allinurl/goaccess/files/567319/parser.c.diff.txt)

**Comment by allinurl** [comment]
Glad it worked out! Your changes look right to me. However, If you are using the csv output, you probably want to look at that file.

Regarding your question where some values are less than the overall unique visitors count. This can occur if a 404 is found. You can try using `--4xx-to-unique-count`, which should give you a consistent count. Let me know.

One thing I just noticed, is that unknown GeoLocations are not shown, which means that if there are unknown locations, the unique count will be less than the overall count. I'll push a fix for this so it does not skip it. Thanks for pointing it out.

**Comment by hopewise** [comment]
So, isn't there an option to customize key using command line to aggregate visitors per month?

**Comment by allinurl** [comment]
@hopewise not sure this is priority, can you share how you plan to use this? Thanks

**Comment by hopewise** [comment]
its all statistics, we just need to know how many visitors were for a specific route at previous year at monthly level.
