### ISSUE TITLE
Feed Wrangler

### ISSUE THREAD

**Issue by omz13** [allinurl/goaccess#557]
To the list of Feed-reader-as-a-service (in `src/browsers.c`), could you kindly add "Feed Wrangler"?

Here is a log file extract so you have an idea what the request looks like.

```
NNN.NNN.NNN.NNN - [30/Oct/2016:17:17:17 +0000] "GET /feed.xml HTTP/1.1" 200 124016 "-" "Feed Wrangler/1.0 (1 subscriber; feed-id=394524; http://feedwrangler.net; Allow like Gecko)"
```

**Comment by allinurl** [comment]
This has been added. It will be pushed out in the upcoming version.

Thanks!
