### ISSUE TITLE
Load a list of crawlers from a text file

### ISSUE THREAD

**Issue by n0ego** [allinurl/goaccess#560]
It will be quite useful to be able to load a list of crawlers from a text file. It gives users more options to add/edit the list without the need to build from source. [https://github.com/allinurl/goaccess/issues/125#issuecomment-257722947](url)

**Comment by szepeviktor** [comment]
Broken link above.
Working one: https://github.com/allinurl/goaccess/issues/125#issuecomment-257722947

**Comment by allinurl** [comment]
v1.3 has been released. It includes the ability to specify a custom list of browsers using --browsers-file=<path>. Please take a look at the sample file [**here**](https://github.com/allinurl/goaccess/blob/master/config/browsers.list).
