### ISSUE TITLE
Missing data metrics from OS and BROWSER panels

### ISSUE THREAD

**Issue by strang3r** [allinurl/goaccess#562]
There appears to be missing data metrics from the OS and BROWSER panels.  I have done some manual comparisons and included my findings below.

I modified the `get_uniq_visitor_key()`, `gen_visitor_key()`, `gen_host_key()`, `gen_os_key()`, `gen_browser_key()` and `gen_geolocation_key()` functions to add a printf statement to record the generated keys so I could manually parse the output.  Here are the print statements so you can see the key structure:

```
printf("uniq_visitor_key: %s\n", key);
printf("visitor_key: %s|%s\n", logitem->uniq_key, logitem->date);
printf("host_key: %s|%s\n", logitem->uniq_key, logitem->host);
printf("browser_data_key: %s|%s\n", logitem->uniq_key, logitem->browser);
printf("browser_root_key: %s|%s\n", logitem->uniq_key, logitem->browser_type);
printf("os_data_key: %s|%s\n", logitem->uniq_key, logitem->os);
printf("os_root_key: %s|%s\n", logitem->uniq_key, logitem->os_type);
printf("geolocation_data_key: %s|%s\n", logitem->uniq_key, logitem->country);
printf("geolocation_root_key: %s|%s\n", logitem->uniq_key, logitem->continent);
```

I then executed Goaccess with the following command:
`cat 7day.log | ./goaccess -o 7day_stock.html > 7day_stock.out`

Notes:
- ignore-crawlers was set to false and 4xx-to-unique-count was set to true in goaccess.conf (see attached for complete configuration file).
- 7day.log is a log file with 7 days of data and 23745454 lines

After completion, I separated the keys into individual files as follows:

```
#grep uniq_visitor_key 7day_stock.out | sed 's/uniq_visitor_key: //g' | sort -u > 7day_stock.uniq_visitor_key
#egrep '^visitor_key' 7day_stock.out | sed 's/visitor_key: //g' | sort -u > 7day_stock.visitor_key
#grep host_key 7day_stock.out | sed 's/host_key: //g' | sort -u > 7day_stock.host_key
#grep os_data_key 7day_stock.out | sed 's/os_data_key: //g' | sort -u > 7day_stock.os_data_key
#grep os_root_key 7day_stock.out | sed 's/os_root_key: //g' | sort -u > 7day_stock.os_root_key
#grep browser_data_key 7day_stock.out | sed 's/browser_data_key: //g' | sort -u > 7day_stock.browser_data_key
#grep browser_root_key 7day_stock.out | sed 's/browser_root_key: //g' | sort -u > 7day_stock.browser_root_key
#grep geolocation_data_key 7day_stock.out | sed 's/geolocation_data_key: //g' | sort -u > 7day_stock.geolocation_data_key
#grep geolocation_root_key 7day_stock.out | sed 's/geolocation_root_key: //g' | sort -u > 7day_stock.geolocation_root_key
```

Here are the final counts:
```
# wc -l 7day_stock*_key
   160786 7day_stock.browser_data_key
   160786 7day_stock.browser_root_key
   160786 7day_stock.geolocation_data_key
   160786 7day_stock.geolocation_root_key
   160786 7day_stock.host_key
   160786 7day_stock.os_data_key
   160786 7day_stock.os_root_key
   160786 7day_stock.uniq_visitor_key
   160786 7day_stock.visitor_key
```

The total number of keys is equal to the total number of uniq_visitor_keys.  The overall unique visitors reported in the summary panel matches the uniq_visitor_key count and the counts and values align for the VISITORS and HOSTS panels...so far so good. Things start to get interesting when looking at the OS and BROWSER panels...

Visitor values reported in HTML output:
```
Operating Systems: 160237

108,063 (67.21%)   Windows
17,406 (10.83%)    iOS
13,055 (8.12%)     Macintosh
11,938 (7.42%)     Unknown
7,307 (4.54%)      Android
1,153 (0.72%)      Linux
601 (0.37%)        Unix-like
345 (0.21%)        Chrome OS
11 (0.01%)         Others
1 (0.00%)          BSD
```

The total counts don't match up when looking at the OS root keys:

```
# cat 7day_stock.os_root_key | awk -F\| '{print $4}' | sort | uniq -c | sort -nr
 108618 Windows
  17572 iOS
 13205 Macintosh
  11938 Unknown
   7313 Android
   1154 Linux
    622 Unix-like
    345 Chrome OS
     15 Others
      4 BSD
```

A closer look at BSD (since the data set is small) reveals some curiosities...

Expanding BSD shows details about the single entry:
`1 (0.00%)   OpenBSD`

4 entries exist in OS root keys:
```
# egrep '\|BSD' 7day_stock.os_root_key
24.138.27.35|20160606|Mozilla/5.0(PlayStation43.50)AppleWebKit/537.78(KHTML,likeGecko)|BSD
24.89.229.12|20160611|Mozilla/5.0(X11;OpenBSDamd64;rv:46.0)Gecko/20100101Firefox/46.0|BSD
66.244.241.35|20160607|Mozilla/5.0(X11;FreeBSDamd64;rv:47.0)Gecko/20100101Firefox/47.0|BSD
66.244.241.35|20160608|Mozilla/5.0(X11;FreeBSDamd64;rv:47.0)Gecko/20100101Firefox/47.0|BSD
```

The matching entries exist in OS data keys:
```
# egrep 'OpenBSD|FreeBSD|PlayStation' 7day_stock.os_data_key
24.138.27.35|20160606|Mozilla/5.0(PlayStation43.50)AppleWebKit/537.78(KHTML,likeGecko)|PlayStation
24.89.229.12|20160611|Mozilla/5.0(X11;OpenBSDamd64;rv:46.0)Gecko/20100101Firefox/46.0|OpenBSD
66.244.241.35|20160607|Mozilla/5.0(X11;FreeBSDamd64;rv:47.0)Gecko/20100101Firefox/47.0|FreeBSD
66.244.241.35|20160608|Mozilla/5.0(X11;FreeBSDamd64;rv:47.0)Gecko/20100101Firefox/47.0|FreeBSD
```

OpenBSD, FreeBSD and PlayStation were detected, but FreeBSD and PlayStation were excluded from the list.

A closer look at "Others" shows similar results...

Expanding Others shows details about the 11 entries:
`11 (0.01%)   BlackBerry`

15 entries exist in the OS root keys:
```
# egrep '\|Others' 7day_stock.os_root_key
142.167.90.67|20160606|BlackBerry-STV100-3/6.0.1|Others
142.68.160.143|20160606|BlackBerry-STV100-3/6.0.1|Others
173.237.107.117|20160608|ApacheOpenOffice/4.1.2|Others
184.151.61.173|20160607|Mozilla/5.0(BlackBerry;U;BlackBerry9900;en)AppleWebKit/534.11(KHTML,likeGecko)Version/7.1.0.1047MobileSafari/534.11|Others
184.151.61.173|20160608|Mozilla/5.0(BlackBerry;U;BlackBerry9900;en)AppleWebKit/534.11(KHTML,likeGecko)Version/7.1.0.1047MobileSafari/534.11|Others
209.128.15.254|20160605|Mozilla/5.0(BlackBerry;U;BlackBerry9900;en)AppleWebKit/534.11(KHTML,likeGecko)Version/7.1.0.1047MobileSafari/534.11|Others
24.114.99.77|20160609|BlackBerry-STV100-3/6.0.1|Others
68.171.246.129|20160607|Mozilla/5.0(BlackBerry;U;BlackBerry9780;en)AppleWebKit/534.8(KHTML,likeGecko)Version/6.0.0.666MobileSafari/534.8|Others
68.171.246.13|20160607|Mozilla/5.0(BlackBerry;U;BlackBerry9780;en)AppleWebKit/534.8(KHTML,likeGecko)Version/6.0.0.666MobileSafari/534.8|Others
68.171.246.132|20160607|Mozilla/5.0(BlackBerry;U;BlackBerry9780;en)AppleWebKit/534.8(KHTML,likeGecko)Version/6.0.0.666MobileSafari/534.8|Others
68.171.246.147|20160607|Mozilla/5.0(BlackBerry;U;BlackBerry9780;en)AppleWebKit/534.8(KHTML,likeGecko)Version/6.0.0.666MobileSafari/534.8|Others
68.171.246.15|20160607|Mozilla/5.0(BlackBerry;U;BlackBerry9780;en)AppleWebKit/534.8(KHTML,likeGecko)Version/6.0.0.666MobileSafari/534.8|Others
68.171.246.152|20160607|Mozilla/5.0(BlackBerry;U;BlackBerry9780;en)AppleWebKit/534.8(KHTML,likeGecko)Version/6.0.0.666MobileSafari/534.8|Others
74.82.68.144|20160607|Mozilla/5.0(BlackBerry;U;BlackBerry9790;es)AppleWebKit/534.11(KHTML,likeGecko)Version/7.1.0.865MobileSafari/534.11|Others
74.82.68.160|20160607|Mozilla/5.0(BlackBerry;U;BlackBerry9790;es)AppleWebKit/534.11(KHTML,likeGecko)Version/7.1.0.865MobileSafari/534.11|Others
```

The matching entries exist in OS data keys:
```
# egrep 'BlackBerry|Apache' 7day_stock.os_data_key
142.167.90.67|20160606|BlackBerry-STV100-3/6.0.1|BlackBerry-STV100-3/6.0.1
142.68.160.143|20160606|BlackBerry-STV100-3/6.0.1|BlackBerry-STV100-3/6.0.1
173.237.107.117|20160608|ApacheOpenOffice/4.1.2|Apache
184.151.61.173|20160607|Mozilla/5.0(BlackBerry;U;BlackBerry9900;en)AppleWebKit/534.11(KHTML,likeGecko)Version/7.1.0.1047MobileSafari/534.11|BlackBerry
184.151.61.173|20160608|Mozilla/5.0(BlackBerry;U;BlackBerry9900;en)AppleWebKit/534.11(KHTML,likeGecko)Version/7.1.0.1047MobileSafari/534.11|BlackBerry
209.128.15.254|20160605|Mozilla/5.0(BlackBerry;U;BlackBerry9900;en)AppleWebKit/534.11(KHTML,likeGecko)Version/7.1.0.1047MobileSafari/534.11|BlackBerry
24.114.99.77|20160609|BlackBerry-STV100-3/6.0.1|BlackBerry-STV100-3/6.0.1
68.171.246.129|20160607|Mozilla/5.0(BlackBerry;U;BlackBerry9780;en)AppleWebKit/534.8(KHTML,likeGecko)Version/6.0.0.666MobileSafari/534.8|BlackBerry
68.171.246.13|20160607|Mozilla/5.0(BlackBerry;U;BlackBerry9780;en)AppleWebKit/534.8(KHTML,likeGecko)Version/6.0.0.666MobileSafari/534.8|BlackBerry
68.171.246.132|20160607|Mozilla/5.0(BlackBerry;U;BlackBerry9780;en)AppleWebKit/534.8(KHTML,likeGecko)Version/6.0.0.666MobileSafari/534.8|BlackBerry
68.171.246.147|20160607|Mozilla/5.0(BlackBerry;U;BlackBerry9780;en)AppleWebKit/534.8(KHTML,likeGecko)Version/6.0.0.666MobileSafari/534.8|BlackBerry
68.171.246.15|20160607|Mozilla/5.0(BlackBerry;U;BlackBerry9780;en)AppleWebKit/534.8(KHTML,likeGecko)Version/6.0.0.666MobileSafari/534.8|BlackBerry
68.171.246.152|20160607|Mozilla/5.0(BlackBerry;U;BlackBerry9780;en)AppleWebKit/534.8(KHTML,likeGecko)Version/6.0.0.666MobileSafari/534.8|BlackBerry
74.82.68.144|20160607|Mozilla/5.0(BlackBerry;U;BlackBerry9790;es)AppleWebKit/534.11(KHTML,likeGecko)Version/7.1.0.865MobileSafari/534.11|BlackBerry
74.82.68.160|20160607|Mozilla/5.0(BlackBerry;U;BlackBerry9790;es)AppleWebKit/534.11(KHTML,likeGecko)Version/7.1.0.865MobileSafari/534.11|BlackBerry
```

Only entries classified as "BlackBerry" were included in the results, BlackBerry-STV100-3/6.0.1 and Apache where excluded.

The missing entries are not included in the "Others" or "Unknown" categories since the root and data keys for Unknown align (as does the total result counts) and "Other" is comprised of the 11 data keys matching "BlackBerry":
```
# egrep '\|Unknown' 7day_stock.os_root_key | awk -F\| '{print $4}' | sort | uniq -c | sort -nr
  11938 Unknown
# egrep '\|Unknown' 7day_stock.os_data_key | awk -F\| '{print $4}' | sort | uniq -c | sort -nr
  11938 Unknown
# egrep '\|Others' 7day_stock.os_root_key | awk -F\| '{print $4}' | sort | uniq -c | sort -nr
     15 Others
```

Narrowing down the missing entries for the larger data sets could prove to be a challenge, hopefully the information above is enough to point you in the right direction.  There are a couple of obvious ones missing though...

Expanding the Windows category shows the following entries:
```
   44,589 (27.73%)   Windows 7
   42,454 (26.40%)   Windows 10
   11,553 (7.19%)    Windows 8.1
   4,750 (2.95%)     Windows Vista
   2,475 (1.54%)     Windows 8
   2,006 (1.25%)     Windows XP
   196 (0.12%)       bingbot/2.0
   23 (0.01%)        Windows XP x64
   17 (0.01%)        Windows 2000
```

Compared to the parsed counts:
```
# egrep '\|Windows' 7day_stock.os_data_key | grep -v Unknown | awk -F\| '{print $4}' | sort | uniq -c | sort -nr
  44627 Windows 7
  42944 Windows 10
  11568 Windows 8.1
   4750 Windows Vista
   2479 Windows 8
   2006 Windows XP
     23 Windows XP x64
     17 Windows 2000
      5 Windows NT
      2 Windows RT
      1 Windows NT 4.0
      1 Windows 98
```

Windows 98, Windows NT 4.0, Windows RT and Windows NT are all excluded from the results.  The total counts don't match in mosts cases.

Similary, data is missing from the BROWSERS panel...

Vistor values reported in HTML output:
```
Browsers 160605
60,531 (37.65%) MSIE
36,349 (22.61%) Chrome
18,937 (11.78%) Safari
16,703 (10.39%) Firefox
12,045 (7.49%)  Unknown
8,103 (5.04%)   Others
```

```
# cat 7day_stock.browser_root_key | awk -F\| '{print $4}' | sort | uniq -c | sort -nr
  60686 MSIE
  39590 Chrome
  21443 Safari
  17592 Firefox
  12047 Unknown
   8290 Others
    898 Crawlers
    141 Opera
     95 Feeds
      3 Game Systems
      1 Podcasts
```

I think crawlers are excluded from the list, but included in the counts (when ignore-crawlers is set to false), so that explains why "Crawlers" don't appear in the results, but there are several non-crawler browsers missing from the list, including Opera:

```
# egrep '\|Opera' 7day_stock.browser_root_key  | wc -l
141
# for i in `egrep '\|Opera' 7day_stock.browser_root_key | sed 's/|Opera$//' `; do grep $i 7day_stock.browser_data_key ; done | awk -F\| '{print $4}' | sort | uniq -c | sort -nr
     57 Opera/37.0.2178.54
     26 Opera/38.0.2220.29
     13 Opera/37.0.2178.43
     10 Opera/36.0.2130.65
      6 Opera/36.0.2130.75
      6 Opera/12.17
      6 Opera/12.02
      4 Opera/37.0.2178.54 (Edition Campaign 67)
      2 Opera/38.0.2220.29 (Edition Campaign 67)
      2 Opera/37.0.2178.32
      2 Opera/17.0.1241.45
      2 Opera/12.15
      1 Opera/37.0.2178.54 (Edition Campaign 34)
      1 Opera/37.0.2178.43 (Edition Campaign 67)
      1 Opera/22.0.1471.50
      1 Opera/18.0.1284.63
      1 Opera/11.64
```

Goaccess appears to be categorizing the browsers correctly, but they are excluded from the lists:

```
# egrep '\|Podcasts' 7day_stock.browser_root_key | wc -l
1
# for i in `egrep '\|Podcasts' 7day_stock.browser_root_key | sed 's/|Podcasts$//' `; do grep $i 7day_stock.browser_data_key ; done | awk -F\| '{print $4}' | sort | uniq -c | sort -nr
      1 iTunes/11.4
```
```
# egrep '\|Game Systems' 7day_stock.browser_root_key | wc -l
3
# for i in `egrep '\|Game Systems' 7day_stock.browser_root_key | sed 's/|Game Systems$//' `; do grep $i 7day_stock.browser_data_key ; done | awk -F\| '{print $4}' | sort | uniq -c | sort -nr
      1 Xbox One
      1 Valve Steam
      1 PlayStation
```
```
# egrep '\|Feeds' 7day_stock.browser_root_key | wc -l
95
# for i in `egrep '\|Feeds' 7day_stock.browser_root_key | sed 's/|Feeds$//' `; do grep $i 7day_stock.browser_data_key ; done | awk -F\| '{print $4}' | sort | uniq -c | sort -nr
     59 Thunderbird/45.1.1
     11 Thunderbird/38.7.2
      8 Thunderbird/38.8.0
      4 Thunderbird/45.1.0
      4 Thunderbird/31.7.0
      2 Thunderbird/45.0
      2 Thunderbird/38.4.0
      2 Netvibes
      1 Thunderbird/38.7.0
      1 Thunderbird/38.5.1
      1 Thunderbird/31.6.0
```
```
# egrep '\|Others' 7day_stock.browser_root_key | wc -l
8290
# for i in `egrep '\|Others' 7day_stock.browser_root_key | sed 's/|Others$//' `; do grep $i 7day_stock.browser_data_key ; done | awk -F\| '{print $4}' | sort | uniq -c | sort -nr
   8769 Mozilla/5.0
    126 Safari/601.6.17
     40 Mozilla/4.0
     36 Safari/601.5.17
     25 Dalvik/1.6.0
     19 Dalvik/2.1.0
     15 SeaMonkey/2.40
     15 Safari/601.1
     11 Links
     11 BlackBerry
      9 HuaweiSCL-L04
      8 Safari/601.3.9
      8 HuaweiY530-U051
      8 HuaweiY330-U05
      7 check_http/v2.1.1
      7 check_http/v2.0.3
      6 SeaMonkey/2.29.1
      6 Safari/601.4.4
      6 curl/7.17.1
      5 HuaweiY536A1
      4 Safari/601.2.7
      3 BlackBerry-STV100-3/6.0.1
      2 YaBrowser/13.10.1500.9323
      2 Safari/601.1.56
      2 Safari/537.86.5
      2 Safari/534.59.10
      2 Safari/11601.6.17
      1 YaBrowser/16.4.1.8949
      1 Vivaldi/1.2.490.39
      1 Safari/600.1.4
      1 Safari/600.1.25
      1 Safari/537.86.6
      1 Safari/537.85.17
      1 Safari/537.78.2
      1 HuaweiY300-0151
      1 CriOS/46.0.2490.85
      1 Chrome/51.0.2704.79
      1 Apache
```

In the case of "Others" only "Mozilla/5.0" appears under the expanded list:
8,103 (5.04%)   Mozilla/5.0

The total visitor count does not match the "Mozilla/5.0" entries in the complete list.

Expanding the MSIE category shows the following entries:
```
36,988 (23.00%) MSIE/11.0
14,096 (8.77%)  Edge/13.10586
4,894 (3.04%)   MSIE/7.0
1,822 (1.13%)   MSIE/9.0
1,112 (0.69%)   MSIE/8.0
1,050 (0.65%)   MSIE/10.0
569 (0.35%)     Edge/12.10240
```
```
# egrep '\|MSIE' 7day_stock.browser_root_key | wc -l
60686
# for i in `egrep '\|MSIE' 7day_stock.browser_root_key | sed 's/|MSIE$//' `; do grep $i 7day_stock.browser_data_key ; done | awk -F\| '{print $4}' | sort | uniq -c | sort -nr
  37064 MSIE/11.0
  14097 Edge/13.10586
   4895 MSIE/7.0
   1822 MSIE/9.0
   1113 MSIE/8.0
   1050 MSIE/10.0
    569 Edge/12.10240
     27 MSIE/6.0
     19 IEMobile/11.0
     12 MSIE/9.11.10586.0
      9 IEMobile/10.0
      3 MSIE/9.11.9600.18053
      3 MSIE/5.01
      3 IEMobile/7.0
      1 MSIE/9.10
      1 Edge/14.14316
      1 Edge/14.14291
```

Again, the numbers don't match and there are several browsers missing (MSIE/6.0, IEMobile/11.0, MSIE/9.11.10586.0, IEMobile/10.0, MSIE/9.11.9600.18053, MSIE/5.01, IEMobile/7.0, MSIE/9.10, Edge/14.14316 and Edge/14.14291)

Similar results can be seen with the remaining browsers on the list, the totals do not align and there are browsers missing from the expanded list.

As you can see, there is important information missing from the data metrics.  Hopefully I have provided you with enough details to pinpoint the cause.  If I can help, let me know.

[7day_stock.html.txt](https://github.com/allinurl/goaccess/files/572183/7day_stock.html.txt)
[goaccess.conf.txt](https://github.com/allinurl/goaccess/files/572187/goaccess.conf.txt)

**Comment by strang3r** [comment]
Interesting development...

I am currently attempting to implement changes to use a different uniq_visitor_key (as detailed in #556).  My changes appeared to work but I noticed that the visitor percentages calculated for each panel were incorrect.  The reason for this is that the calculations were using the result of `ht_get_size_uniqmap (VISITORS)` which essentially equals the total number of unique IP+Date+UA+Date entries regardless of the defined uniq_visitor_key.  In my most recent change I modified the `init_json_output()` function to set `totals.visitors` to equal the total count of unique visitors based on my custom key.  After compiling and reprocessing the data I am seeing much more data in the OS and BROWSER panels.  They don't appear to be 100% complete but many of the missing elements are showing up (including FreeBSD and Playstation under BSD and most of the Opera browsers that were missing from the stock build).

The most recent code change probably does not directly relate to this development, but I thought it would be worth mentioning.

**Comment by allinurl** [comment]
Thanks for posting these findings. Just to be sure, you are referring to the unique visitors count across different panels, correct?

**Comment by allinurl** [comment]
OK, I have pushed a [**commit**](https://github.com/allinurl/goaccess/commit/bbd651b94fc418a86f515859cb28a1b985878df0) that should fix this issue. Here's where the flaw was: When the unique visitor key, composed of `IP|DATE|UA` is inserted, a numeric unique key on the hash is returned, which then is concatenated with the numeric key returned by the composition of `IP|DATE|UA|DATA_FIELD`. For example:

```

+-----------------+---------------------------------------+-----+
| IP|DATE|UA      | 10.10.10.10|10/Oct/2012|Firefox       | 137 |
+-----------------+---------------------------------------+-----+
| IP|DATE|UA|DATA | 10.10.10.10|10/Oct/2012|Firefox|Spain |  11 |
+-----------------+---------------------------------------+-----+

uniq_key (concatenate both) = 13711
```

However, that would conflict with the following example:

```

+-----------------+---------------------------------------+------+
| IP|DATE|UA      | 10.10.10.10|10/Oct/2012|Chrome        | 1371 |
+-----------------+---------------------------------------+------+
| IP|DATE|UA|DATA | 10.10.10.10|10/Oct/2012|Chrome|France |    1 |
+-----------------+---------------------------------------+------+

uniq_key (concatenate both) = 13711
```

Both will have the same key, therefore the unique visitor total won't match the overall unique visitors count (if it's applicable). 

Just for reference, I'll quote what I posted on #556:

> The total visitors count in one panel can differ from other panels. Here is why: Assume, if you have a total of 7 unique visitors in your overall count, but seven of them visited only 1 file, then the total visitors on the requested files panel would be 1 instead of 7.
> 
> Now let's think about the case where you have a total of 7 unique visitors in the overall count, those 7 visitors visited your web server at 3 different times, 12am, 1pm, 2pm. Out of the 7 visitors, 1 visitor hit your server at 12am, 1 hit your server at 1pm and all of them hit it at 2pm. If you add up all of the visitors on that panel, it yields to a total of 9 visitors (the column count you are seeing).
> 

The following panels should be the same total visitors count as the overall visitors count (assumes`--4xx-to-unique-count`).

```
VISITORS
HOSTS
OS
BROWSERS
GEOLOCATION
```


Give it a shot and let me know how it goes. Thanks for pointing out this issue.

**Comment by strang3r** [comment]
The data metrics appear to be complete, at least all the values that I noticed were missing are now included and the total visitor count equals the overall unique visitor value on the VISITORS, HOSTS, OS, BROWSER and GEOLOCATION panels.  Nice work!

Your welcome for the info, I'm happy I could help!

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed. BTW [v1.1](https://goaccess.io/release-notes) just went out :)
