### ISSUE TITLE
Persistent storage feature not built into Debian packages

### ISSUE THREAD

**Issue by AndiDog** [allinurl/goaccess#563]
TCB_BTREE is off by default. Is it possible to add `--enable-tcb=btree` to the Debian build to always get that feature? Or is more work to be done?

**Comment by allinurl** [comment]
Running `sudo apt-get install goaccess-tcb` should get you the btree version. Please take a look at https://goaccess.io/download for more details.

**Comment by AndiDog** [comment]
Sorry, must have overlooked that in the README. Thanks! Working fine now.
