### ISSUE TITLE
Add an id attribute to all html result fields

### ISSUE THREAD

**Issue by ottok** [allinurl/goaccess#566]
Currently the markup for the _total requests_ field is `<h3 class="" style="padding-top: 0;">872,248</h3>`. The value is here, but there is no `id` attribute, so it is difficult to fetch the value from the html report in an automated fashion.

If would be nice if the markup by default was something like `<h3 id="total-requests" class="" style="padding-top: 0;">872,248</h3>`. There are use cases where people might want to parse the results from an existing HTML file instead of regenerating the report as JSON.

I am happy to implement this myself, test and send a pull request. Just give me a thumbs up and some pointers where to start and I'll code it.

**Comment by allinurl** [comment]
That sounds good to me and I'd be happy to merge the PR :)

You could simply use the current JSON object overall key, e.g., `total_requests`, `valid_requests`, etc as the id and then add a new attribute to this [object](https://github.com/allinurl/goaccess/blob/master/resources/js/app.js#L261) and add it to the [template](https://github.com/allinurl/goaccess/blob/master/resources/tpls.html#L9).

Let me know if that helps. Thank you!

**Comment by ottok** [comment]
Looking at the source I just realized that a JSON data dump is embedded in the HTML report. To the value is already there, in `var json_data` as value `"total_requests": 872248`.

**Comment by allinurl** [comment]
Yes, it is bootstrapped into the document. You can pass `--json-pretty-print` to get a prettier JSON output in the HTML report.

**Comment by ottok** [comment]
I'll implement the `id` anyway since it can be useful for CSS rules too. Expect a patch in a few days :)

**Comment by ottok** [comment]
Wow, that was easy. Coded, built and tested to work as expected.
