### ISSUE TITLE
Request: 500 error list panel

### ISSUE THREAD

**Issue by BluGeni** [allinurl/goaccess#568]
Very similar to the "404 or Not Found: " panel I would love to see which files are getting 500 errors the most.

**Comment by allinurl** [comment]
#117 will address this in a nicer way. However, right now you can achieve this by doing this:

    # awk '$9~/500/' access.log | goaccess

Some examples [here](https://github.com/allinurl/goaccess#files--status-codes)

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
