### ISSUE TITLE
Display the unique IP count

### ISSUE THREAD

**Issue by jaywayjayway** [allinurl/goaccess#569]
HI, on the  dashboard, how to show Unique IP  on the  Overall Analyzed Requests .

**Comment by allinurl** [comment]
The terminal output does show up the number of unique IPs (upper-right corner on the Hosts panel). I can certainly add this to the HTML output. Please keep this open so I can look into it.

**Comment by jaywayjayway** [comment]
@allinurl  great !! I will be amazing ..

**Comment by allinurl** [comment]
This has been added. It will be pushed out in this week release.
