### ISSUE TITLE
--no-progress doesn't work

### ISSUE THREAD

**Issue by gemal** [allinurl/goaccess#570]
using 1.0.2 `--no-progress` doesn't seems to work

**Comment by allinurl** [comment]
Just tested this out and it does seem to work on my side. Are you getting some sort of error message?

**Comment by gemal** [comment]
I use
`/bin/goaccess --time-format "%H:%M:%S" --date-format "%d/%b/%Y" --log-format "%v %h %^ %^ [%d:%t %^] \"%r\" %s %b \"%R\" \"%u\" %D" --http-method --no-progress`

**Comment by allinurl** [comment]
What output are you getting and what output do you expect to get?

Currently the `--no-progress` option disables the number of lines parsed and the lines per second count. This is especially useful when outputting through the cron.

**Comment by gemal** [comment]
if I use:
```
[root@xx]# cat /di_access.log | /bin/goaccess --time-format "%H:%M:%S" --date-format "%d/%b/%Y" --log-format "%v %h %^ %^ [%d:%t %^] \"%r\" %s %b \"%R\" \"%u\" %D" --http-method --no-progress > /dev/null
Parsing... [6,705] [3,352/s]6,705] [6,705/s]
```

it does the progress

**Comment by allinurl** [comment]
I see. This is because `--http-method` is thinking `--no-progress` is the argument passed. The issue is in this [else](https://github.com/allinurl/goaccess/blob/master/src/options.c#L668) condition. I'll look into it. For now, you can use:

    cat /di_access.log | /bin/goaccess --time-format "%H:%M:%S" --date-format "%d/%b/%Y" --log-format "%v %h %^ %^ [%d:%t %^] \"%r\" %s %b \"%R\" \"%u\" %D" --no-progress --http-method=yes > /dev/null

**Comment by gemal** [comment]
ahhh ok
I will change my command

**Comment by allinurl** [comment]
Looking at the code, there's nothing to fix in here, since it's completely valid to pass `--no-progress` or pretty much any other string as an argument of `--http-method`.  Simply passing `yes|no` as the required argument of `--http-method` should fix this issue.
