### ISSUE TITLE
Does Geo Location can  get city status ？

### ISSUE THREAD

**Issue by jwh5566** [allinurl/goaccess#573]
hello！
first, thanks for the tool！
I download GeoLiteCity City database，modify the config well，but generate the html is also don't have city, how to resolve problem.

**Comment by allinurl** [comment]
Here are the steps to get the city field working (For IPv4 City database):

```
# mkdir -p  /usr/local/share/GeoIP/
# cd  /usr/local/share/GeoIP/
# wget -N http://geolite.maxmind.com/download/geoip/database/GeoLiteCity.dat.gz
# gunzip GeoLiteCity.dat.gz
```

Then edit your goaccess config file and add

    geoip-database /usr/local/share/GeoIP/GeoLiteCity.dat 

or run it as:

    goaccess -f /var/log/nginx/access.log --geoip-database=/usr/local/share/GeoIP/GeoLiteCity.dat

**Comment by jwh5566** [comment]
thanks ! I already get it ok!

**Comment by allinurl** [comment]
Great. Closing this.
