### ISSUE TITLE
--fifo-in and --fifo-out options doesn't work

### ISSUE THREAD

**Issue by koztya** [allinurl/goaccess#575]
I try to use GoAccess to generate realtime html. It works fine with default values for fifo (i.e. when I do not use these options).
If I add any of these options, i.e. --fifo-in/out then it just silently exit (with return code 0).
Also it lives 3 new pipes, i.e.:
I use: `--fifo-in=/tmp/ws1.fifo` `--fifo-out=/tmp/ws2.fifo`
then after silent exit I see these 3 new files:
`/tmp/ws1.fifo /tmp/ws2.fifo` AND `/tmp/wspipeout.fifo`

I tried to use stable version and version from git.

**Comment by allinurl** [comment]
Thanks for reporting this. It has been fixed. Feel free to build from [**development**](https://goaccess.io/download#build). Otherwise, it will be pushed in the upcoming version.

**Comment by koztya** [comment]
is this issue fixed at 1.2 version?
I used development version from December - and it worked fine.
now I tried to use new 1.2 version - and the same problem as before - silent exit.

**Comment by allinurl** [comment]
It certainly works. Just ran a quick test as:

    goaccess access.log -o out.html --real-time-html --fifo-in=/tmp/prod.in --fifo-out=/tmp/prod.out --log-format=VCOMBINED

Make  sure the binary you are using is v1.2. `whereis goaccess` may help.
