### ISSUE TITLE
File output doesn't work in Ubuntu 14.04 with goaccess, goaccess-tcb works

### ISSUE THREAD

**Issue by wojtha** [allinurl/goaccess#576]
I've upgraded to goaccess v1.1.1 today from v1.0.6 and I am unable to save the HTML, CSV, JSON on Ubuntu 14.04 with standard goaccess package. It seems to be parsing the input, it reports the progress but at the end there is no file written. Furthermore I can get into interactive mode but I am stuck, cannot switch panes and cannot quit correctly from here. 

When I change the standard goaccess package to goaccess-tcb the export works but it is 10 times slower than standard goaccess. With goaccess I am getting parsing speed around 30,000 while with goaccess-tcb I am getting 2,700 records/s). So it is kinda workaround for me now, but I am waiting ages for the result. 

```
$ uname -a
Linux shokaku 4.8.3-x86_64-linode76 #1 SMP Thu Oct 20 19:05:39 EDT 2016 x86_64 x86_64 x86_64 GNU/Linux

$ sudo apt-cache policy goaccess
goaccess:
  Installed: 1:1.1.1
  Candidate: 1:1.1.1
  Version table:
 *** 1:1.1.1 0
        500 http://deb.goaccess.io/ trusty/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by allinurl** [comment]
Thanks for reporting this. Can you please post how are you running goaccess? and if you could attach/post your config file would be great. Thanks!

**Comment by wojtha** [comment]
The process is still running... the current progress looks like this:

```
$ sudo goaccess -f /var/log/nginx/access.log.1 -o /home/inm/report-2016-11-22.csv
Parsing... [2,861,063] [1,454/s]
```

**Comment by wojtha** [comment]
I have found these two config files: `.goaccessrc` and `/etc/goaccess.conf`
[goaccess.conf.txt](https://github.com/allinurl/goaccess/files/609161/goaccess.conf.txt)
[goaccessrc.txt](https://github.com/allinurl/goaccess/files/609162/goaccessrc.txt)

**Comment by allinurl** [comment]
Just ran a quick test on 14.04 x64 and was able to output any of the stdout formats and navigate in the terminal output as well. So I'm thinking it might be an isolated issue. Can you please try outputting to the current path or /tmp?

    goaccess -f /var/log/nginx/access.log.1 -p /etc/goaccess.conf --log-format=COMBINED -o a.html -o b.json -o c.csv

**Comment by wojtha** [comment]
```
sudo goaccess -f /var/log/nginx/access.log.1 -p /etc/goaccess.conf --log-format=COMBINED -o a.html -o b.json -o c.csv
```
Nothing
```
sudo goaccess -f /var/log/nginx/access.log.1 -p /etc/goaccess.conf --log-format=COMBINED -o /tmp/a.html -o /tmp/b.json -o /tmp/c.csv
```
Nothing as well.

However when I changed the input file from yesterdays log file (1.2GB) to today's log file (400MB) which is smaller I get the output! So it is file size/memory related or there is something in the log which causes parser to fail.

**Comment by allinurl** [comment]
I see, can you check `dmesg` and see if perhaps the machine is running out of memory?

**Comment by wojtha** [comment]
```
Out of memory: Kill process 3032 (goaccess) score 210 or sacrifice child
Killed process 3032 (goaccess) total-vm:675588kB, anon-rss:556596kB, file-rss:0kB, shmem-rss:0kB
```

Yep ☹️ 

I have run `free -h` in the meantime and it reporting only 60MB of free RAM . Before I was observing memory via htop without sudo and it was reporting that machine is using 1,3 GB out of 2,0 GB so I didn't think it is the cause.

@allinurl Sorry for the false alert and thank you for your time and fast feedback!

**Comment by allinurl** [comment]
No worries :) Take a look at [**this**](https://github.com/allinurl/goaccess/issues/572#issuecomment-260968331) post, it may help if you still want to use the in-memory storage.
