### ISSUE TITLE
goaccess: unrecognized option '--enable-panel'

### ISSUE THREAD

**Issue by alxbob** [allinurl/goaccess#578]
I installed goaccess on centos 7 with yum but i want to enable visit times panel but when i try goaccess --enable-panel i get this : 

    goaccess: unrecognized option '--enable-panel'

So i don't have access to visit times panel config : `#ignore-panel VISIT_TIMES` is commented

**Comment by allinurl** [comment]
Which version are you running? Also make sure you have a time specifier `%t` in your log-format and is matching your log entries. Otherwise, please attach your config file.

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
