### ISSUE TITLE
Reporting REMOTE_USERs

### ISSUE THREAD

**Issue by abecede753** [allinurl/goaccess#580]
I recently fell in love with this project. One thing I can't get working is having a report about the REMOTE_USERs of my web site.

My web server is Apache, and I'm using the standard "combined" log format for my log file.

In goaccess, I chose this Log Format Configuration:

     %h %^ %e [%d:%t %^] "%r" %s %b "%R" "%u"

Now goaccess shows me lots of stuff, but I am still missing any kind of information about my users. They are of course in the apache log file.

Here's an example line of the apache log:

    213.208.145.120 - abe.cede [01/Dec/2016:09:52:09 +0000] "GET /r/racelist/ HTTP/1.1" 200 5134 "https://www.abe-cede.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.98 Safari/537.36"

Any idea how I can get some kind of report for my users?

**Comment by allinurl** [comment]
Are you using the latest version (>=1.1)? I just tried your log format and it does report it.


    goaccess -f log --date-format='%d/%b/%Y' --log-format='%h %^ %e [%d:%t %^] "%r" %s %b "%R" "%u"' --time-format=%T

![2016-12-01-063913_295x87_scrot](https://cloud.githubusercontent.com/assets/5005367/20794287/27f532e8-b791-11e6-8660-15a4d151d128.png)

**Comment by abecede753** [comment]
Oh, that was the reason! I am using goaccess from Centos repository (v 1.0.2). Going to install it from source. Thank you for your quick reply!

**Comment by abecede753** [comment]
Yep, confirmed. Works great. Back to the documentation on how to handle multiple log files and how goaccess stores old data which isn't in the current logfiles anymore. Thanks for this nice package! (Especially the cool html/svg output!)

**Comment by allinurl** [comment]
Glad that worked and that you found it useful :)
