### ISSUE TITLE
Export to HTML, personnal issue (or inattention…)

### ISSUE THREAD

**Issue by point-barre** [allinurl/goaccess#581]
Hi,

Sorry for the trouble,
I must do something wrong or misconfigured but unfortunately i can't figure it out.
It will surely be obvious for you :

I'm using the 1.1.1 version.
Here is my single line test file from an Apache 2.4.7 log.
[test.txt](https://github.com/allinurl/goaccess/files/624919/test.txt)

When i simply execute :

    goaccess -f test.txt

The configuration prompt automatically open, i choose "NCSA Combined Log Format",
it works like a charm.

Then, to make an HTML export i do :

    goaccess -c -f test.txt -o test.html

The prompt doesn't open and i get :

    No time format was found on your conf file.

So i tried this (the pattern that should match "NCSA Combined")

    goaccess --log-format='%h %^[%d:%t %^] "%r" %s %b "%R" "%u"' --date-format='%d/%b/%Y' --time-format='%H:%M:%S' -f test.txt -o test.html

And i get this error :

    Token '+0100]' doesn't match specifier '%h'

This is where i can't understand why the %h(ost) is pointing to the timezone.
I attempted several combinations without success.
If you have any idea, i would be really pleased.
Thanks.

**Comment by allinurl** [comment]
Please try adding `--no-global-config`. You probably have a different format in your config file.

**Comment by point-barre** [comment]
Merci beaucoup !
I knew the answer would be in your well-documented man page..
I guess this is not a great idea to work while having the flu.
Thanks again.

**Comment by allinurl** [comment]
Glad it worked!
