### ISSUE TITLE
real-time-html not working

### ISSUE THREAD

**Issue by virtualdreams** [allinurl/goaccess#583]
I try the real-time-html part, but i didn't get to work.

> goaccess -f /var/log/nginx/access.log -o /srv/www/goaccess/index.html --real-time-html --ws-url=my.server.lan

This command create the index.html with the actual parsed data. But if i press F5 in firefox, no new data appears. (New data ist written)

Command line hangs with (it's ok i think):
> Parsing... [0] [0/s]

Firefox prints the following
> 13:14:40.901 Die Verbindung zu ws://my.server.lan:7890/ wurde unterbrochen, während die Seite geladen wurde. 1 stats.my.server.lan:1154:15

> var socket = new WebSocket(str);

What i do wrong?

**Comment by allinurl** [comment]
Are you accessing through an https connection? 

Also, please make sure the port 7890 is opened. There is no need for pressing F5, it should automatically refresh as data is appended to the access.log. If you can post a screenshot of your browser and the browser console would be great.

**Comment by virtualdreams** [comment]
No, no https in use. Her are the screenshots: FF, FF Console and Putty

![ff_console](https://cloud.githubusercontent.com/assets/3603832/20861463/7fc6a658-b991-11e6-9d39-5a51e6c7dfac.png)
![ff_site](https://cloud.githubusercontent.com/assets/3603832/20861465/8297c5a6-b991-11e6-8927-60b2efdb7cb5.png)
![putty](https://cloud.githubusercontent.com/assets/3603832/20861468/853bbdb2-b991-11e6-8a82-502576399535.png)

**Comment by virtualdreams** [comment]
Some 2 more screens from telnet and lsof.
![putty_telnet](https://cloud.githubusercontent.com/assets/3603832/20861555/6ca0000e-b993-11e6-8515-d253e56eb271.png)
![putty_lsof](https://cloud.githubusercontent.com/assets/3603832/20861556/6e2051b8-b993-11e6-8737-d9fcc08ed3a4.png)

**Comment by allinurl** [comment]
Are you using some sort of [CSP](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy) on your webserver? or firewall/plugin in your machine/browser? Could you please try on a different browser?

**Comment by virtualdreams** [comment]
No firewall, no csp (LAN).
I have tried in IE11 and Edge, the same result as in FF.

**Comment by virtualdreams** [comment]
IE11 Console message: SCRIPT12152: WebSocket Error: Network Error 12152, Der Server lieferte eine ungültige oder unbekannte Rückmeldung.

**Comment by allinurl** [comment]
It seems to be an isolated issue since I can't replicate it on my side, tested on FF (win/linux). You could try running goaccess on a localhost machine and parse a few lines of your access log, e.g.,

    goaccess -f test.log --log-format=COMBINED -o report.html --real-time-html

 and open the generated report using `file:///home/user/report.html`

Are you behind a proxy? and are you serving both, the generated report and running goaccess on the same server? also, would you be able to share the address where I can see the report? (if it's ok, feel free to send it through email - hello at goaccess.io)

**Comment by virtualdreams** [comment]
No proxy. Goaccess and nginx on the same machine. If i add "wss://" to --ws-url, IE establish a connection to the server but no nothing get updated. I see the connection with "lsof -i". FF dont like this protocol and timeoute. If i remove "wss://", both will fail.

I will try share you a address to the report, but not before monday or tuesday.

I will also try this scenario at work.

Have you a windows build of goaccess? Otherwise i must build it on Win8/Cygwin.

**Comment by virtualdreams** [comment]
I set report and websocket address to the same hostname, now it works magically in IE11, Edge and Firefox. *Confused*

**Comment by allinurl** [comment]
Do you mean `--ws-url=samehost` and opening the report as `http://samehost.com`? I know that the connection gets refused if the websocket hostname is different than the one being served by the web server, but only on TLS connections.

BTW, to use `wss`. you need to build with `--with-openssl` and use `--ssl-cert=<path/cert.crt>` and `--ssl-key=<path/priv.key>`.

**Comment by virtualdreams** [comment]
Yep, thats what i mean. Report "http://subdomain.address" and socket "subdomain.address". Since i do that, it works. I don't no why ist now works. The whole day, the error exists...

The "wss://" was just a try. I have seen somewhere on stackoverflow.

**Comment by allinurl** [comment]
That's odd, just tested this as

    goaccess -f test.log --log-format=COMBINED -o report.html --real-time-html --ws-url=192.168.1.10

and opened the report using `http://domain.com/report.html` and did work (FF 49.0.1). 

In any event, is it safe to close this then?

**Comment by virtualdreams** [comment]
Yes, we can close it for now. I repoen it, if this error reappears. Thank your for your help and time. :)
