### ISSUE TITLE
Date doesn't update in real time reports

### ISSUE THREAD

**Issue by virtualdreams** [allinurl/goaccess#584]
The header "Overall Analyzed Requests (05/Dec/2016 - 05/Dec/2016)" shows the date range from first time parsing, while the date in the top right corner is updated instantly "Last Updated: 2016-12-06 08:20:30 +0100".

Why not create a blank report without initial data and update the report completly from the websocket?

Just run goaccess with a file input and the real-time flags without define a output file, to run as websocket server?

**Comment by allinurl** [comment]
It looks like the time range is not part of the JSON data coming though the WebSocket. I can look into this.

As far as a blank report, wouldn't this be the same as #582?

**Comment by virtualdreams** [comment]
Yes, looks the same :)

**Comment by allinurl** [comment]
This has been fixed. It will be pushed out in the upcoming version. Thanks again for reporting it!
