### ISSUE TITLE
How to config Goaccess in CentOS with tokyocabinet?

### ISSUE THREAD

**Issue by n0ego** [allinurl/goaccess#586]
Hi

Is there any equivalence/plan to release an equivalence of goaccess-tcb for CentOS or do we need to build from source in order to use tokyocabinet?

Many thanks.

**Comment by allinurl** [comment]
For now you will have to build from [**source**](https://goaccess.io/download#installation).

As far as the rpm repo, I can look into it, however, it would probably be until a tool like aptly adds support to it. Please open a new issue for the  rpm repo.

**Comment by allinurl** [comment]
I'll check `createrepo`, I may be able to use it if the process is not as elaborate as creating a deb repo.

**Comment by n0ego** [comment]
I'm looking at creating a rpm package which enables tokyocabinet with goaccess just now. If I can help with anything re rpm repo please let me know.

**Comment by allinurl** [comment]
Thanks for the offering. Let me take a look at building an rpm repo and I'll post back as soon as I have some news.
