### ISSUE TITLE
Ability to load browsers from a text file

### ISSUE THREAD

**Issue by AlexWillison** [allinurl/goaccess#588]
Currently, crawlers and bots can only be excluded by adding them to the 'browsers.c' file before compiling GoAccess.  That being said, new ones are constantly showing up.

Instead of recompiling, would it be possible to have a text-based list of IPs that are referenced when generating the HTML report?  This would be more easily modifiable, and not require recompiling or generating a new TokyoCabinet database.

**Comment by allinurl** [comment]
Thanks for suggesting this. I definitely plan to add this, it will be part of issue #560.

**Comment by allinurl** [comment]
Closing this as I'm adding on #560. Thanks again!
