### ISSUE TITLE
Parsing counter Real time Monitoring Over SSL

### ISSUE THREAD

**Issue by InvokerFury** [allinurl/goaccess#589]
Hey Sir,
I am new for goacces..
thx for create this awesome tools,
i wanna ask you about real time monitoring via ssl

i run this command then always stuck in parsing like this
![tes](https://cloud.githubusercontent.com/assets/24584431/21217407/941a1d1e-c2de-11e6-8657-581db541713b.JPG)

why always parsing? can you help me with this..
i really new sir.. and i am sorry for my english

Thanks in advance

**Comment by allinurl** [comment]
The parser first reads as many lines there are in your access log. Then the counter you see will stay there and the real-time server kicks in and parse further requests without necessarily updating the counter. If you don't want to see this, you can run goaccess with the `--no-progress` flag.

**Comment by InvokerFury** [comment]
thank you sir for your reply..
but when i add --no-progress i see this ..
![tes2](https://cloud.githubusercontent.com/assets/24584431/21225410/4d081604-c303-11e6-9aa1-d5e519cc0cca.JPG)

what should i do? 
Thanks in advance

**Comment by allinurl** [comment]
That looks fine to me. Are you expecting something different?

**Comment by InvokerFury** [comment]
thx sir for your reply..

i just want to know if i already done make this real time?

here server statistic..
![tes](https://cloud.githubusercontent.com/assets/24584431/21235165/3bdb3d00-c328-11e6-99b3-6032b785e3bf.JPG)

Thx for help sir...

**Comment by allinurl** [comment]
from the screenshot, it looks like it's not. The little circle on the left (next to the gear icon) should be green if it's in real-time mode.

Also, it looks like you are using the wrong parameter for ws-url. You need to use a valid host or IP. For instance, `--ws-url=server_host` or `--ws-url=IP`. You do not need to use http(s) in ws-url.

**Comment by InvokerFury** [comment]
once again thank sir for your reply,

you mean like this sir:
--ws-url=100.100.100.100/reportaplikasi.html 

can you explain to me sir what its mean "stopping websocket server" ?
Thanks

**Comment by allinurl** [comment]
It should be something like:

    --ws-url=192.168.1.100

That IP would be the address of the server where GoAccess is running. Also make sure port 7890 is opened and you have a valid TLS/SSL certificate.

Pressing CTRL+C would stop the websocket server or if you have an invalid certificate. You can build with --enable-debug to see any possible error messages. e.g.,

    ./configure --enable-geoip --enable-utf8 --enable-debug

**Comment by InvokerFury** [comment]
Greats..
awesome.. thank you sir for your help..

God Bless You.. 
Regards..
From here with love

**Comment by InvokerFury** [comment]
![image](https://cloud.githubusercontent.com/assets/24584431/21254044/5515fb08-c395-11e6-84fd-45ae27bfccf6.png)
still didnt work sir..
please help me

**Comment by InvokerFury** [comment]
hy sir.. now everythink its ok

But when i access it to browser .. goaccess cant load my log..
log size is 15mb
![image](https://cloud.githubusercontent.com/assets/24584431/21254899/2bb6bad0-c39b-11e6-9f5c-22f278a13a7d.png)

stuck in this sir.. please your help..
thanks in advance

**Comment by allinurl** [comment]
Please take a look at the browser's console for any possible errors. Also, please try a different browser and see if it's not a plugin causing the issue.

**Comment by InvokerFury** [comment]
here the browsers console say sir..
what should i do? 

![image](https://cloud.githubusercontent.com/assets/24584431/21263906/f6f7e874-c3cb-11e6-8f1d-978bbe093c1e.png)

**Comment by InvokerFury** [comment]
![image](https://cloud.githubusercontent.com/assets/24584431/21263996/5c6073ca-c3cc-11e6-9479-d440018109ef.png)
here sir the log

**Comment by allinurl** [comment]
It looks like a certificate issue. Please make sure the certificate matches the same domain/subdomain used for the wss connection as well as the URL that you are using to load the report in the browser.

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
