### ISSUE TITLE
Having an option to use window.location.hostname for the websocket

### ISSUE THREAD

**Issue by daneshka** [allinurl/goaccess#590]
Instead of having localhost by default or passing the host with --ws-url,
It would be great to use the host dynamically from where the user opens the HTML file.

In my case I use GoAccess in a docker (behind NGINX docker), I don't have any clue about whats would be the host name in the production/test environment.

**Comment by allinurl** [comment]
I totally agree with this request. I'll make sure to change this. Thanks!

**Comment by allinurl** [comment]
This has been changed. It should now default to `window.location.hostname`. It will be pushed out in the upcoming release. Thanks!
