### ISSUE TITLE
Possible bug when passing in an excluding IP list

### ISSUE THREAD

**Issue by n0ego** [allinurl/goaccess#593]
There seems to be a bug when passing in an excluding IP list.
`$ goaccess -f myfile.log` => work fine
```
$ grep -v "`cat goaccess_exclude_list.txt`" myfile.log | goaccess

GoAccess - version 1.1.1 - Dec 14 2016 00:17:21
Config file: No config file used

Fatal error has occurred
Error occured at: src/goaccess.c - set_curses - 1261
No time format was found on your conf file.
```
However, the following works fine.
```
$ grep -v "`cat goaccess_exclude_list.txt`" myfile.log > test.log
$ goaccess -f test.log
```
The goaccess_exclude_list.txt file contains a list of IP addresses, one IP per line.

**Comment by allinurl** [comment]
It looks like you are not using a config file. Did you fully install it using `make install`? Otherwise if you are piping a log, you need to specify the config log with `-p /path/log/goaccess.conf` and make sure you actually have log/date/time format.

**Comment by n0ego** [comment]
@allinurl You were right. I was piping to pass in log data so needed to specify -p /etc/goaccess.conf and time/date format.

Many thanks.

P/s: perhaps this could be included in the man page for future reference.

**Comment by allinurl** [comment]
That's great it worked. Thanks for pointing that out. I have added a note to the [**man page**](https://goaccess.io/man#options).
