### ISSUE TITLE
Unable to output real-time-html

### ISSUE THREAD

**Issue by unclecat** [allinurl/goaccess#596]
use this command

    # goaccess -f access.log -o /usr/share/nginx/www/rt.goaccess.io/report.html --real-time-html --ws-url=host 

and it appears
Parsing... [0] [0/s]
wait for a long time

**Comment by allinurl** [comment]
Can you please try parsing your log without outputting to stdout and see if that outputs some data to the terminal? i.e.,

    goaccess -f access.log --log-format=COMBINED

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
