### ISSUE TITLE
Correct date/time/log format for mysql-slow.log

### ISSUE THREAD

**Issue by towfiqpiash** [allinurl/goaccess#597]
When I run this: `goaccess -f mysql-slow.log ` , I get following error: 

```
GoAccess - version 1.0.2 - Nov  3 2016 15:46:39
Config file: /usr/local/etc/goaccess.conf
Fatal error has occurred
Error occured at: src/goaccess.c - main - 1230
Nothing valid to process. Verify your date/time/log format.
```

What would be the appropriate date/time/log format for mysql-slow.log ?

**Comment by allinurl** [comment]
GoAccess is a web log analysis tool, not a general data visualization tool. Take a look at netdata, it may offer what you are looking for.

**Comment by towfiqpiash** [comment]
Thanks for your suggestion
