### ISSUE TITLE
dom.storage.enabled

### ISSUE THREAD

**Issue by hdatma** [allinurl/goaccess#601]
For security reasons, we enforce Firefox's dom.storage.enabled to false. Firefox renders the stats page, but an ugly list of of urls appears at the bottom, and the console returns "TypeError: localStorage is null". 

By comparison, if dom.storage.enabled is true, the console returns "SecurityError: The operation is insecure".

**Comment by allinurl** [comment]
I set `dom.storage.enabled` to false and opened the report and it does look normal. Where are you seeing the list of URLs?

**Comment by allinurl** [comment]
Since I'm not able to replicate it, I'm closing this. Feel free to reopen it with additional comments as needed.
