### ISSUE TITLE
Qcloud CDN Log format help (%Y%m%d%H%M%S)

### ISSUE THREAD

**Issue by sofire** [allinurl/goaccess#604]
log

> 

```
20161227210131 223.104.185.75 img.xxx.com /images/h5-dingding/banner1.png 134594 122 1046 200 NULL 1455 "NULL" "(null)" GET HTTP/1.1 miss
```

config
```
date-format %Y%m%d
time-format %H%M%S
log-format %d%t %h %^ %r %b %^ %^ %s %R %D "%u" "(%^)" %m %H %^
```

date and time can not parse correctly. 
If i use shell(like awk ) to add a space in log,  it's ok.

thank you

**Comment by allinurl** [comment]
I'd need to look at this format, `%x` handles this type of date/time format, but only if `%s` or `%f` are used. I'll post back as soon as I have some news. Thanks.

**Comment by allinurl** [comment]
So I got the chance to look at this and it is currently possible to parse this format.

    goaccess -f access.log --log-format='%x %h %v %U %b %^ %^ %s %^ %D "%u" "%R" %m %H %^' --date-format=%Y%m%d%H%M%S --time-format=%Y%m%d%H%M%S

or

```
date-format %Y%m%d%H%M%S
time-format %Y%m%d%H%M%S
log-format %x %h %v %U %b %^ %^ %s %^ %D "%u" "%R" %m %H %^
```

Feel free to reopen it if needed.
