### ISSUE TITLE
Cant Parse Custom Logs

### ISSUE THREAD

**Issue by LordNykon** [allinurl/goaccess#606]
I'm trying to get goaccess working. 
I have log lines like:

    Jan  3 08:53:57 server-1a-01 server-1a-01.fqdn.fqdn.fqdn.fqdn.com nginx: "111.111.111.111" "111.111.111.111" "111.111.111.111" "-" [03/Jan/2017:08:53:57 +0000] "POST /path1/path2/device/path3/path4/path5/path6/fetch HTTP/1.1" -> "127.0.0.1:8083" 200 220 "-" "Go-http-client/1.1" 0.088 0.088 . "CID|part1part2|part3"

I have tried the below format but I was unable to pull any hits
`                            Log Format  %^ %^ %h %^[%d:%^] "%r"	%s %b "%R" "%u" 
                             Date Format -  %b %d                                                    
                             Time Format - %H:%M:%S                                               
`

Thank you in advance for your help

**Comment by allinurl** [comment]
Can you please describe each of the log format fields?

**Comment by LordNykon** [comment]
`log_format '$http_x_forwarded_for - $remote_addr - $remote_user [$time_local] "$request" -> "$upstream_addr" $status $body_bytes_sent "$http_referer" "$http_user_agent" $request_time $upstream_response_time $pipe "$http_x_conversation_id"';`

**Comment by allinurl** [comment]
goaccess -f access.log --log-format='%^"%h" %^[%d:%t %^] "%r" %^"%^" %s %b "%R" "%u" %T %^' --date-format=%d/%b/%Y --time-format=%T

OR

```
log-format %^"%h" %^[%d:%t %^] "%r" %^"%^" %s %b "%R" "%u" %T %^
date-format %d/%b/%Y
time-format %T
```

**Comment by LordNykon** [comment]
Thanks for the quick response I am going to run some test and see if this take care of it

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.

**Comment by LordNykon** [comment]
Good Afternoon we are taking another look at go access, I was able to get this to work but I a having to removed the entire first part of the messages because it was not properly ignoring this

goaccess -f /var/log/messages --log-format='%^ %^ %^ %^ %^ %^: %^ %^ "%h" %^[%d:%t %^] "%r" %^"%^" %s %b "%R" "%u" %T %^' --date-format=%d/%b/%Y --time-format=%T

I saw https://github.com/allinurl/goaccess/issues/250 was the almost same issue is there a simplification or work around for the 6 ignore fields '^%; unfortunately didn't work when we were hoping it would ignore everything before the colon and we are unfortunately not in a position to change our logging format as was the previous fix.

**Comment by allinurl** [comment]
Can I ask you to please post several lines from your `/var/log/messages` log? That way I can make sure the format would work. Thanks.

**Comment by LordNykon** [comment]
Sure 

Mar  4 03:33:01 server-1-01 server-1-01.node.south.test.business.com nginx: "-" "-" "192.168.1.27" "-" [04/Mar/2017:03:33:01 +0000] "GET /em/websocket/ZZZZ/G HTTP/1.1" -> "10.100.1.1:443" 101 4 "-" "-" 0.094 0.092 . "-"
Mar  4 03:33:08 server-1-01 server-1-01.node.south.test.business.com nginx: "-" "-" "192.168.1.27" "-" [04/Mar/2017:03:33:08 +0000] "GET /em/websocket/XXXX/H HTTP/1.1" -> "10.100.1.2:443" 101 4 "-" "-" 0.100 0.099 . "-"
Mar  4 03:33:17 server-1-01 server-1-01.node.south.test.business.com nginx: "-" "-" "192.168.1.160" "-" [04/Mar/2017:03:33:17 +0000] "GET /em/websocket/XXXX/I HTTP/1.1" -> "10.100.1.1:443" 101 4 "-" "-" 0.095 0.094 . "-"
Mar  4 03:33:31 server-1-01 server-1-01.node.south.test.business.com nginx: "-" "-" "192.168.1.160" "-" [04/Mar/2017:03:33:31 +0000] "GET /em/websocket/ZZZZ/I HTTP/1.1" -> "10.100.1.2:443" 101 4 "-" "-" 0.093 0.091 . "-"
Mar  4 03:33:34 server-1-01 server-1-01.node.south.test.business.com nginx: "-" "-" "192.168.1.27" "-" [04/Mar/2017:03:33:34 +0000] "GET /em/websocket/ZZZZ/G HTTP/1.1" -> "10.100.1.1:443" 101 4 "-" "-" 0.091 0.090 . "-"
Mar  4 03:33:39 server-1-01 server-1-01.node.south.test.business.com nginx: "-" "-" "192.168.1.160" "-" [04/Mar/2017:03:33:39 +0000] "GET /em/websocket/ZZZZ/I HTTP/1.1" -> "10.100.1.2:443" 101 4 "-" "-" 0.093 0.092 . "-"
Mar  4 03:33:50 server-1-01 server-1-01.node.south.test.business.com nginx: "-" "-" "192.168.1.160" "-" [04/Mar/2017:03:33:50 +0000] "GET /em/websocket/XXXX/I HTTP/1.1" -> "10.100.1.1:443" 101 4 "-" "-" 0.094 0.093 . "-"
Mar  4 03:34:04 server-1-01 server-1-01.node.south.test.business.com nginx: "-" "-" "192.168.1.27" "-" [04/Mar/2017:03:34:04 +0000] "GET /em/websocket/ZZZZ/I HTTP/1.1" -> "10.100.1.2:443" 101 4 "-" "-" 0.088 0.087 . "-"
Mar  4 03:34:10 server-1-01 server-1-01.node.south.test.business.com nginx: "-" "-" "192.168.1.27" "-" [04/Mar/2017:03:34:10 +0000] "GET /em/websocket/ZZZZ/G HTTP/1.1" -> "10.100.1.1:443" 101 4 "-" "-" 0.093 0.092 . "-"

**Comment by allinurl** [comment]
From your post above, you have `$http_x_forwarded_for`, so is the third field always the host `%h`? or could there be a case where the first field is the host and the rest of the fields would be emptied? 

Can you please explain the multiple ways in which `$http_x_forwarded_for` can vary? If possible please attach a text file with multiple log entries.

**Comment by LordNykon** [comment]
The logs do not vary and we are getting the output we want, we are just curious if there a cleaner way of ignoring the syslog portion of the message.

**Comment by allinurl** [comment]
This should do it:

    goaccess access.log --log-format='%^"-" "-" "%h"  %^[%d:%t %^] "%r" %^"%^" %s %b "%R" "%u" %T %^' --date-format=%d/%b/%Y --time-format=%T

**Comment by LordNykon** [comment]
Great that works well I appreciate your help!
