### ISSUE TITLE
-bash: /usr/bin/goaccess: No such file or directory

### ISSUE THREAD

**Issue by stormyqq** [allinurl/goaccess#607]
I did everything mentioned as following

```
$ wget http://tar.goaccess.io/goaccess-1.1.1.tar.gz
$ tar -xzvf goaccess-1.1.1.tar.gz
$ cd goaccess-1.1.1/
$ ./configure --enable-geoip --enable-utf8
$ make
$ make install
```

but when I am gonna use goaccess command it shows
-bash: /usr/bin/goaccess: No such file or directory

**Comment by stormyqq** [comment]
I fixed it. I think it's better if you changed your instructions as this.

$ wget http://tar.goaccess.io/goaccess-1.1.1.tar.gz
$ tar -xzvf goaccess-1.1.1.tar.gz
$ cd goaccess-1.1.1/
$ ./configure --prefix=/usr --enable-geoip --enable-utf8 
$ make
# make install

then the goaccess file install in this location
/usr/bin/
and therefore we can use the "goaccess" command from any directory.

**Comment by stormyqq** [comment]
http://i.imgur.com/O6zgYSh.png

**Comment by allinurl** [comment]
Glad that solved it. 

I can add a note about `--prefix` to the docs, however, I'll keep the instructions as they are, leaving it to the users if they want to change it. .
