### ISSUE TITLE
GoAccess counts log file again and again

### ISSUE THREAD

**Issue by m4ntic0r** [allinurl/goaccess#608]
I have a problem with Goaccess 1.1.1 + Nginx and I can not solve it ..

I want my statistics to be saved over the entire period (with keep db files)

My first command:

    goaccess -e 127.0.0.1 -e 192.168.2.0-192.168.2.255 -f /var/log/nginx/proxy.log.1 -a -o /var/www/html/stats/stats.html --keep-db -files --db-path /root/goaccess_database/db

My second command: (also the command for the crontab)

    goaccess -e 127.0.0.1 -e 192.168.2.0-192.168.2.255 -f /var/log/nginx/proxy.log -a -o /var/www/html/stats/stats.html --load-from-disk --keep -db-files --db-path /root/goaccess_database/db

My problem is every time the second command is executed, it counts the complete statistics and values from proxy.log. The statistics in stats.html double every time my cronjob runs? I dont get it..

Can anyone pls help me?

**Comment by allinurl** [comment]
The second command will append the content from `proxy.log` to the previously parsed `proxy.log.1` data. 

Now, if you are parsing the same log twice and using `--load-from-db` then it will duplicate the entries. This will be addressed in #334

**Comment by m4ntic0r** [comment]
ok thanks.
i have now a solution for me.

i run goaccess once a day via shell script and i have changed my nginx logrotate from weekly to daily.
the script is called in the nginx logrotate config after "prerotate".
i think the "sharedscripts" parameter in logrotate config is important, too, so the script will only run one time.

**Comment by allinurl** [comment]
Glad that worked!

Stay tuned for the upcoming fix #334.
