### ISSUE TITLE
Error occured at: src/parser.c - parse_log - 2554

### ISSUE THREAD

**Issue by stormyqq** [allinurl/goaccess#609]
```
goaccess -f access.log -o /usr/share/nginx/www/rt.goaccess.io/report.html --real-time-html --ws-url=host

GoAccess - version 1.1.1 - Jan  5 2017 00:03:28
Config file: No config file used

Fatal error has occurred
Error occured at: src/parser.c - parse_log - 2554
No time format was found on your conf file.
```

So I gave it the custom location as apparently it doesn't read the file from /usr/etc/goaccess.conf instead some local location, but still I can't proceed. 

```
goaccess -f access.log -o /usr/share/nginx/www/rt.goaccess.io/report.html --real-time-html --ws-url=host  -p --config-file=/usr/etc/goaccess.conf

GoAccess - version 1.1.1 - Jan  5 2017 00:03:29
Config file: --config-file=/usr/etc/goaccess.conf

Fatal error has occurred
Error occured at: src/settings.c - get_config_file_path - 128
Unable to open the specified config file. No such file or directory
```

Honestly, I am not sure this does even work in ubuntu, the setting up phase is so frustrating, and time consuming and confusing. I am not a linux pro, so I hope you can make a proper tutorial or something for ubuntu 16.04.1

**Comment by allinurl** [comment]
It looks like you are using the flag twice, try:

    goaccess -f access.log -o /usr/share/nginx/www/rt.goaccess.io/report.html --real-time-html --ws-url=host -p  /usr/etc/goaccess.conf

Make sure you have the log/date/time format set under `/usr/etc/goaccess.conf`

**Comment by stormyqq** [comment]
Is this correct? because this also makes to throw an error as this 

`goaccess -f access.log -o /usr/share/nginx/www/rt.goaccess.io/report.html --real-time-html --ws-url=host -p  /usr/etc/goaccess.conf

GoAccess - version 1.1.1 - Jan  5 2017 01:11:14
Config file: /usr/etc/goaccess.conf

Fatal error has occurred
Error occured at: src/parser.c - read_log - 2515
Unable to open the specified log file. No such file or directory
`


`
######################################
# Time Format Options (required)
######################################
#
# The hour (24-hour clock) [00,23]; leading zeros are permitted but not required.
# The minute [00,59]; leading zeros are permitted but not required.
# The seconds [00,60]; leading zeros are permitted but not required.
# See `man strftime` for more details
#
# The following time format works with any of the
# Apache/NGINX's log formats below.
#
time-format %H:%M:%S
#
# Google Cloud Storage or
# The time in microseconds since the Unix epoch.
#
#time-format %f

# Squid native log format
#
#time-format %s

######################################
# Date Format Options (required)
######################################
#
# The date-format variable followed by a space, specifies
# the log format date containing any combination of regular
# characters and special format specifiers. They all begin with a
# percentage (%) sign. See `man strftime`
#
# The following date format works with any of the
# Apache/NGINX's log formats below.
#
date-format %d/%b/%Y
#
# AWS | Amazon CloudFront (Download Distribution)
# AWS | Elastic Load Balancing
# W3C (IIS)
#
#date-format %Y-%m-%d
#
# Google Cloud Storage or
# The time in microseconds since the Unix epoch.
#
#date-format %f

# Squid native log format
#
#date-format %s

######################################
# Log Format Options (required)
######################################
#
# The log-format variable followed by a space or \t for
# tab-delimited, specifies the log format string.
#
# NOTE: If the time/date is a timestamp in seconds or microseconds
# %x must be used instead of %d & %t to represent the date & time.

# NCSA Combined Log Format
log-format %h %^[%d:%t %^] "%r" %s %b "%R" "%u"

# NCSA Combined Log Format with Virtual Host
log-format %v:%^ %h %^[%d:%t %^] "%r" %s %b "%R" "%u"

# Common Log Format (CLF)
log-format %h %^[%d:%t %^] "%r" %s %b

# Common Log Format (CLF) with Virtual Host
log-format %v:%^ %h %^[%d:%t %^] "%r" %s %b

# W3C
#log-format %d %t %h %^ %^ %^ %^ %r %^ %s %b %^ %^ %u %R

# Squid native log format
#log-format %^ %^ %^ %v %^: %x.%^ %~%L %h %^/%s %b %m %U

# AWS | Amazon CloudFront (Download Distribution)
#log-format %d\t%t\t%^\t%b\t%h\t%m\t%^\t%r\t%s\t%R\t%u\t%^

# Google Cloud Storage
#log-format "%x","%h",%^,%^,"%m","%U","%s",%^,"%b","%D",%^,"%R","%u"

# AWS | Elastic Load Balancing
#log-format %dT%t.%^ %^ %h:%^ %^ %T %^ %^ %^ %s %^ %b "%r" "%u"

# AWSS3 | Amazon Simple Storage Service (S3)
#log-format %^[%d:%t %^] %h %^"%r" %s %^ %b %^ %L %^ "%R" "%u"

# Virtualmin Log Format with Virtual Host
#log-format %h %^ %v %^[%d:%t %^] "%r" %s %b "%R" "%u"


`

**Comment by allinurl** [comment]
Please specify the right path to your access log. e.g., `/var/log/apache2/access.log`.

Also, make sure `-o` has the right path for the output report. And `--ws-url` has the right IP/host of your server (where GoAccess is running). 

    goaccess -f /var/log/apache2/access.log -o $HOME/report.html --real-time-html --ws-url=host -p /usr/etc/goaccess.conf

Take a look at the [**FAQ**](https://goaccess.io/faq#html-report) and the [**man page example**](https://goaccess.io/man#examples) for more details about the real time HTML output.

**Comment by stormyqq** [comment]
Thanks. I solved it. I forgot that I changed the name of the access file when installing a virtual host. :) 👍

**Comment by allinurl** [comment]
Great! Closing this. Feel free to reopen it if needed.

**Comment by Harbir123** [comment]
goaccess /var/log/apache2/access/log -o /usr/share/nginx/html/your_site/report.html --real-time-html

GoAccess - version 1.2 - Feb  8 2018 12:00:31
Config file: /usr/local/etc/goaccess.conf

Fatal error has occurredParsing... [0] [0/s]
Error occured at: src/parser.c - read_log - 2669
Unable to open the specified log file. No such file or directory

I am still getting the same error

**Comment by Harbir123** [comment]
please solve this

**Comment by allinurl** [comment]
@Harbir123 sounds like you may have the wrong path to your access log. Are you sure there's a slash `/` after `access` and not a period? e.g.,

    /var/log/apache2/access.log
