### ISSUE TITLE
Feature request: Quit after processing.

### ISSUE THREAD

**Issue by skorokithakis** [allinurl/goaccess#613]
A nice use case would be to have logrotate run goaccess before rotating the nginx logs. Correct me if I'm wrong, but there's currently no way to tell goaccess to just process the log files and exit when done. A `--process-and-exit` option would be nice. This would also alleviate the problem with #334, as log files would always be processed exactly once for this specific use case.

**Comment by allinurl** [comment]
If you are outputting to a terminal, there's no way to right now to exit goaccess after parsing the log. However, if you are outputting to an html file (no real-time), it will parse it and goaccess will exit. 

I agree that running goaccess right before rotating the log should alleviate the issue of parsing the same log twice. Are you outputting to the terminal and thus you are suggesting `--process-and-exit`?

**Comment by skorokithakis** [comment]
No, I'm not outputting anywhere now. What I want to do is process the log to enter the lines in the database and exit, so I can delete/archive the log but still open goaccess later (loading from the db) and see the analysis of the lines in the log.

I guess I can output an html file to /dev/null or something as a workaround, though.

**Comment by allinurl** [comment]
Got it. I've [added this option](https://github.com/allinurl/goaccess/commit/dcc5bbdc43dca14bf1f41ad7f04a46115d47cd26), it should now parse the given log and exit. Feel free to build from [**development**](https://goaccess.io/download#build), otherwise it will be pushed out in the upcoming release. Thanks!

**Comment by skorokithakis** [comment]
Fantastic, thank you! Could you also comment on #334?

**Comment by allinurl** [comment]
I'll definitely comment on #334, just let me think a bit more about the solution you proposed.
