### ISSUE TITLE
unrecognized option '--keep-db-files'

### ISSUE THREAD

**Issue by Tassleh0ff** [allinurl/goaccess#614]
Hi, I just installed goaccess 1.1.1 from sources, everything seems good except --keep-db-files option seems not working and returns unrecognized option exception.

> [root@drakaris tmp]# which goaccess
/usr/local/bin/goaccess
[root@drakaris tmp]# /usr/local/bin/goaccess --version
GoAccess - 1.1.1.
For more details visit: http://goaccess.io
Copyright (C) 2009-2016 by Gerardo Orellana
[root@drakaris tmp]#
[root@drakaris tmp]# /usr/local/bin/goaccess -f access_log -o output.html --keep-db-files
/usr/local/bin/goaccess: unrecognized option '--keep-db-files'
[root@drakaris tmp]#

**Comment by Tassleh0ff** [comment]
My fault, I got to compile with btree support.

**Comment by Jorilx** [comment]
May I suggest to change the error message to something like "goaccess compiled without btree support"?

**Comment by allinurl** [comment]
@Jorilx Thanks for the suggestion. Actually btree is going away in the upcoming version. It will have on-disk support by default.
