### ISSUE TITLE
Issues with custom log format and X-Forwarded-For (XFF)

### ISSUE THREAD

**Issue by thomasfeichter** [allinurl/goaccess#615]
I have a log format starting as follows
`"111.111.111.111" example.com ...`
but when the request comes via Cloudflare it looks as follows
`"111.111.111.111, 222.222.222.222" example.com ...`
where the second IP can be ignored as it is an IP from Cloudflare.
The problem is that I can only get either of the two working, but the log file contains both variations.

Any hints would be highly appreciated.
Thanks!

**Comment by allinurl** [comment]
For the following sample log:

    "88.6.2.1, 185.43.4.4" [13/Sep/2016:22:17:50 +0200] "GET /url HTTP/1.1" 200 1586 "http://www.example.com" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/601.7.7 (KHTML, like Gecko) Version/9.1.2 Safari/601.7.7"
    "89.6.2.1" [14/Sep/2016:22:17:50 +0200] "GET /url HTTP/1.1" 200 1586 "http://www.example.com" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/601.7.7 (KHTML, like Gecko) Version/9.1.2 Safari/601.7.7"
    "90.6.2.1, 185.43.4.4, 10.10.10.2" [15/Sep/2016:22:17:50 +0200] "GET /url HTTP/1.1" 200 1586 "http://www.example.com" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/601.7.7 (KHTML, like Gecko) Version/9.1.2 Safari/601.7.7"

This format should do it:

    goaccess -f log --log-format='"%h,|" %^[%d:%t %^] "%r" %s %b "%R" "%u" "%T"' --date-format=%d/%b/%Y --time-format=%T

**Comment by thomasfeichter** [comment]
Thank you for the speedy reply.
Unfortunately this way all vhosts using Cloudflare are not included in the report and weirdly from all other vhosts the first letter is missing e.g. www.example.com is logged as ww.example.com.

Here are two log entries:
`
"11.25.11.53, 17.68.33.17" vhost1.com [10/Jan/2017:16:47:00 +0630] "GET / HTTP/1.1" 200 12166 663 12594 "-" "Mozilla/4.0..." 0.000 "4.15"
"10.25.140.240" vhost2.com [10/Jan/2017:16:47:26 +0630] "GET / HTTP/1.1" 200 13036 542 13464 "http://facebook.com/" "Mozilla/5.0..." 0.000 "4.63"
`

Here is the explanation for the fields:
https://github.com/omega8cc/provision/blob/master/http/Provision/Config/Nginx/server.tpl.php#L176

...and the format I am currently testing with:
log-format "%h,|" %v [%d:%t %^] "%r" %s %^ %^ %b "%R" "%u" %T "%^"

**Comment by allinurl** [comment]
Skipping `%v` appear to work, e.g.,

    goaccess -f test.log --log-format='"%h,|" %^[%d:%t %^] "%r" %s %^ %^ %b "%R" "%u" %T %^' --date-format=%d/%b/%Y --time-format=%T

However, I'll look into why `%v` is not being parsed properly.

**Comment by allinurl** [comment]
Thanks again for report this issue. I have pushed a [**commit**](https://github.com/allinurl/goaccess/commit/c6b99dd39a3e8ea518c3bd7c05e1b346aab875ba) that addresses this format and how the XFF field is parsed. I made a post about this #632.

In your case, this should do it:

    goaccess -f test.log --log-format='~h{", } %v %^[%d:%t %^] "%r" %s %^ %^ %b "%R" "%u" %T %^' --date-format=%d/%b/%Y --time-format=%T

or 

```
log-format ~h{", } %v %^[%d:%t %^] "%r" %s %^ %^ %b "%R" "%u" %T %^
date-format %d/%b/%Y
time-format %T
```

Let me know how it goes.

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.

**Comment by thomasfeichter** [comment]
Thanks, tested it and is working well!
