### ISSUE TITLE
Show certain countries as UNKNOWN

### ISSUE THREAD

**Issue by stormyqq** [allinurl/goaccess#616]
http://i.imgur.com/Cckte4d.png

I am from srilanka, and it shows my IP address from an unknown country. It used to work, but recently I uninstalled apache/geoip, and installed only the nginx and geoip back. 

I used these commands to install geoip, please let me know if there is any issue with it

```
wget http://www.maxmind.com/download/geoip/api/c/GeoIP-latest.tar.gz
tar xzvf GeoIP-latest.tar.gz
cd GeoIP-1.6.0
./configure && make && make install

apt-get install libgeoip-dev
apt-get install php-geoip php7.0-dev libgeoip-dev
```

```
wget http://geolite.maxmind.com/download/geoip/api/perl/Geo-IP-1.36.tar.gz
tar -xzvf Geo-IP-1.36
cd Geo-IP-1.36
perl Makefile.PL
make
make test
make install

```

**Comment by allinurl** [comment]
This seems to be an issue with your GeoIP DB. Have you tried running to see if it can find the Country for that IP address?

    geoiplookup 112.134.x.x

**Comment by stormyqq** [comment]
yeah it doesn't show the country, but if I tried an US ip then it shows the country.

**Comment by stormyqq** [comment]
I tried a couple of foreign IPs (like china, japan) to see whether they work or not, and they indeed work. I remember it used to work for my country too. so I presume their database doesn't contain all the IP address of my country. :(

**Comment by allinurl** [comment]
That's right. You can try using one of the latest databases from [**maxmind**](https://dev.maxmind.com/geoip/legacy/geolite/) and follow [**this**](https://github.com/allinurl/goaccess/blob/master/config/goaccess.conf#L605) in order to use it in goaccess.

**Comment by stormyqq** [comment]
okay I found. It seems like I had an older version of geoip database installed in "/usr/local/share/GeoIP/" where both "geoiplookup" command and goaccess search for the database, and apparently when I used the above commands it installs the geoip database in  "/usr/share/GeoIP/". hope this is may helpful to someone who had the same problem. It seems like the same problem I had earlier.
