### ISSUE TITLE
HTML pipes to terminal but doesn't output html file after parsing

### ISSUE THREAD

**Issue by randycochran** [allinurl/goaccess#618]
Trying both relative and absolute paths on a local file, still no export. Both run and I get output of the HTML in terminal, but no export file. Tried with and without sudo thinking it was a permissions thing, no difference.

    Chinmoys-MacBook-Pro:/ randycochran$ sudo goaccess -f /Users/randycochran/Desktop/logs/ssl_access.log -o /Users/randycochran/Desktop/logs/report.html

Chinmoys-MacBook-Pro:logs randycochran$ sudo goaccess -f ssl_access.log -o report.html

Screencap:
<img width="697" alt="screen shot 2017-01-11 at 12 26 33 pm" src="https://cloud.githubusercontent.com/assets/7914311/21859430/9672caee-d7fa-11e6-8c32-71bec3dd908e.png">

**Comment by allinurl** [comment]
Which version are you running? Prior to 1.0, you will need to use redirection, e.g.,

    sudo goaccess -f /Users/randycochran/Desktop/logs/ssl_access.log > /Users/randycochran/Desktop/logs/report.html

**Comment by randycochran** [comment]
Ah yes... it was whatever downloaded using brew install goaccess - apparently the package isn't updated there? That would appear to be the problem, as it's v 0.9.7. Thanks for clarification, it now works!

**Comment by allinurl** [comment]
Glad that solved it.

It does look like it's the [**latest**](https://github.com/Homebrew/homebrew-core/blob/6ecfe9a78b88ab4630b32ba351b8a6592debb8d2/Formula/goaccess.rb) though. Not sure why is pulling v0.9.7 for you. Maybe doing a `brew update`?

**Comment by randycochran** [comment]
I'll try to update now or install via the download/make process. Thanks again!
