### ISSUE TITLE
Error Traversing Database for ipnum = <number> - Perhaps database is corrupt?

### ISSUE THREAD

**Issue by lancelink** [allinurl/goaccess#620]
I just tried goaccess now, working fine in few runs. All is well until I put it in cron to automate the generation of html reports. After just few minutes, I started getting this error

Error Traversing Database for ipnum = 2086011038 - Perhaps database is corrupt?

```
==54559== GoAccess 1.1.1 crashed by Sig 11
==54559==
==54559== VALUES AT CRASH POINT
==54559==
==54559== Line number: 1
==54559== Offset: 0
==54559== Invalid data: 0
==54559== Piping: 1
==54559== Response size: 34767 bytes
==54559==
==54559==
==54559== Please report it by opening an issue on GitHub:
==54559== https://github.com/allinurl/goaccess/issues
```

I am reading multiple log files when the error happened. Now even I feed small size log file, the error persist. My config file is almost the default except Time, Date, and Log format were just specified. Can you help me in any way? Thanks!

**Comment by allinurl** [comment]
Interesting. If you don't mind, can I ask you to please run it through gdb to see where exactly is crashing:

```
$ curl tar.goaccess.io/goaccess-1.1.1.tar.gz | tar xvz
$ cd goaccess-1.1.1/
$ ./configure --enable-debug --enable-tcb=tcb --enable-geoip --enable-utf8
$ make
$ gdb --args ./goaccess -f access.log -p /your/configfile/goaccess.conf
(gdb) r <enter>
(gdb) bt full <enter>
```

Thanks

**Comment by allinurl** [comment]
Also, please post how you are running goaccess and preferably your config file too. Thanks

**Comment by allinurl** [comment]
This appears to be an issue with GeoIP. Replacing the current geoip database or updating it should address this issue.

**Comment by audioscavenger** [comment]
EXACTLY - THANKS - for some reason, my nginx trashed this message since yersterday and you guessed it: /usr/share/GeoIP/GeoIP.dat file was empty. A failed upgrade maybe?
`sudo apt-get --reinstall install geoip-database`
