### ISSUE TITLE
Real time updates of Overall Analyzed Requests.

### ISSUE THREAD

**Issue by NiftyMist** [allinurl/goaccess#621]
Is there a way that already exist the have the Overall Analyzed Requiters section of the .html document to update in real time?

**Comment by allinurl** [comment]
The overall analyzed request section is updated real-time as shown in the [**demo**](http://rt.goaccess.io/?20161230103857).

**Comment by NiftyMist** [comment]
well first of all, I'm noticed that we are running 1.0.2.  What is the best way to update with little down time?

**Comment by allinurl** [comment]
v1.0.2 should also update that section real-time. You will need to restart goaccess after building the newest version. Easiest way to update is probably using the [**official repo**](https://goaccess.io/download#official-repo).

**Comment by NiftyMist** [comment]
Is that info correct?  I'm unable to resolve deb.goaccess.io.

**Comment by allinurl** [comment]
It's correct. Is it timing out for you?

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
