### ISSUE TITLE
How to display the full referrer?

### ISSUE THREAD

**Issue by kaihendry** [allinurl/goaccess#626]
https://s.natalian.org/2017-01-17/1484619788_2558x1393.png

How can I see what pages were referred to? Isn't it better also to show the full URL of the referring page?

I'm using `for i in logs/*.gz; do zcat < $i; done | goaccess --log-format=CLOUDFRONT -o report.html` & GoAccess - 1.1.1

**Comment by allinurl** [comment]
It seems like you need to enable the referrers panel. Commenting [**this**](https://github.com/allinurl/goaccess/blob/master/config/goaccess.conf#L459) line out in your config file should do it.

**Comment by kaihendry** [comment]
Thanks, I prefer not to mess around with external configs since I use the same script on multiple environments. Why isn't `--enable-panel=REFERRERS` say the default with CLOUDFRONT? Anything else that should be typically enabled to make best use of the CloudFront logs I have?

Furthermore I find it very confusing I see a "Geo location" panel when for example `#enable-panel GEO_LOCATION` is commented out in the system config.

**Comment by allinurl** [comment]
There's no way right now to have a set of default options based on the select log-format. A simple solution  is to have a config file (e.g., `/etc/goaccess.cloudfront`) specific to your log format, e.g., `CLOUDFRONT` and just specify that config file from the command line, e.g.,

    for i in logs/*.gz; do zcat < $i; done | goaccess --log-format=CLOUDFRONT -o report.html -p 
/etc/goaccess.cloudfront

I agree. It's confusing having both, `enable-panel ` and `ignore-panel `. I think I'll make `ignore-panel ` an alias of `enable-panel ` just for backwards compatibility and use `enable-panel ` only to avoid confusion.

**Comment by kaihendry** [comment]
I am still trying to avoid external configuration files. I don't follow. ignore-panel === enable-panel?! What the?

My complaint is that I am seeing these panels in report.html despite them being commented out the config.

**Comment by allinurl** [comment]
See #407 for details on why --enable-panel was added. 

I'm not sure I follow, in the screenshot you posted, the REFERRERS panel is not shown, so I assumed you wanted to enable it and thus you need to make sure `ignore-panel REFERRERS` is commented out. If `ignore-panel` is commented out, the panel will be displayed regardless the status of `enable-panel REFERRERS`.

**Comment by kaihendry** [comment]
Let me summarise my state:

https://s.natalian.org/2017-01-17/1484619788_2558x1393.png has 'referring sites' showing.. misses details like who the referrers are. To fix IIUC I set ignore-panel REFERRERS, which confusingly shows a new panel with the referrers.

https://s.natalian.org/2017-01-17/1484624085_2558x1393.png shows "Geo location" despite `#enable-panel GEO_LOCATION` being set in my configuration.

**Comment by allinurl** [comment]
By the default and regardless a config file exists, goaccess enables all panels. So in order to allow the user to _ignore_ parsing and displaying some panels, the option `--ignore-panel` was added. 

However, since the `REFERRERS` panel is disabled by default at the config file level, then you need to comment that line out so it can be shown.

For your second point, and as mentioned on the first line, goaccess enables all panels, so it doesn't matter if you uncomment `--enable-panel` since it's already enabled by default.

`enable-panel` becomes useful if you have panels ignored and you would like to enable them in the command line.

**Comment by kaihendry** [comment]
Ok so I'm set with `for i in logs/*.gz; do zcat < $i; done | goaccess --enable-panel=REFERRERS --log-format=CLOUDFRONT -o report.html` Ok!

**Comment by allinurl** [comment]
Glad that did it. I should've mentioned that on my first comment :)
