### ISSUE TITLE
Goaccess opens files in write or append mode

### ISSUE THREAD

**Issue by Tester98** [allinurl/goaccess#628]
See this, if an access log being monitored by goaccess tries to rotate the file, some bad things happens. This is probably because of goaccess opens log file in write mode or append mode, please see this https://github.com/mholt/caddy/issues/1363

**Comment by allinurl** [comment]
goaccess does not open the log in in write mode nor append mode. It does it in read mode. [**Here's**](https://github.com/allinurl/goaccess/blob/e42ac72965b419dafe736d7a4c75226471209a47/src/parser.c#L2314) where it attempts to open it.

I monitor access logs with goaccess and have logrotate doing its job on the logs without any issues so far. As mentioned on the other thread, it sounds like it may be lumberjack?

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
