### ISSUE TITLE
date/time/log format does not match

### ISSUE THREAD

**Issue by mayou33** [allinurl/goaccess#629]
Hi

my nginx  log format :

```
log_format  main    '$time_local-$status-$bytes_sent-$request_time-$http_x_forwarded_for-$remote_addr-$server_addr-$upstream_addr-$request_method-$scheme://$host$uri?$query_string-$server_protocol-$ssl_protocol-$http_referer-$http_user_agent-$gzip_ratio-$http_cookie';
```
GoAccess - 1.1.1

```
vi /usr/local/etc/goaccess.conf 
date_format  %d/%b/%Y
log-format  %d:%^-%s-%b-%T-%h-%h-%h-%h-%m-%^-%^-%U?%q-%H-%^-%R-%u-%-%^
```

run it as

    goaccess -d -f   access.log     

get

```
Parsed 10 lines producing the following errors:

Token '' doesn't match specifier '%h'

Format Errors - Verify your log/date/time format
```

How to set the parameter that log-format？

SPECIFIERS is too few
https://goaccess.io/man

**Comment by allinurl** [comment]
Please post a few lines from your access log. Thanks

**Comment by mayou33** [comment]
I'm sorry, I forgot to write it 。
#
20/Jan/2017:17:25:25 +0800-200-254-0.000---192.168.15.187-172.172.210.5---GET-http://172.172.210.5/status?--HTTP/1.1-----Mozilla/5.0 (Windows NT 6.1; 
Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36----

#

**Comment by mayou33** [comment]
by the way,   $time_local  Change to  $time_iso8601  
How to set the parameter that log-format？

**Comment by mayou33** [comment]
2017-01-22T11:44:47+08:00-200-257-0.000---192.168.15.187-172.172.210.5---GET-http://172.172.210.5/status?--HTTP/1.1-----Mozilla/5.0 (Windows NT 6.1; W
in64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36----

**Comment by allinurl** [comment]
The following partially works for the line you posted above. 

Note that it makes the assumption that the client IP is the first from the XFF and that there are three `---` between the host (if you can post a few more sample lines with varying data would help). 

However, you will need to delimit the user agent by quotes and escape as necessary in order for goaccess to parse OSs/Browsers.

    goaccess -f log --log-format='%dT%t+%^-%s-%b-%T---%h-%^---%m-%U-%H-%^-%R-%u-%^' --date-format='%Y-%m-%d' --time-format=%T

**Comment by mayou33** [comment]
thinks ,I'm trying

**Comment by mayou33** [comment]
1.  nginx log_format
#
log_format  main2    '$time_iso8601-$status-$bytes_sent-$request_time-$http_x_forwarded_for-$remote_addr-$server_addr-$upstream_addr-$request_method-$scheme://$host$uri?$query_string-$server_protocol-$ssl_protocol-$http_referer-$http_user_agent-$gzip_ratio-$http_cookie';
##
2.  nginx log
#
2017-01-22T17:28:36+08:00-404-325-0.001-42.56.76.11-120.27.143.11-172.173.200.3-172.173.200.243:80-GET-http://www.baidu.com/apple-touch-
icon-precomposed.png?--HTTP/1.1-----MobileSafari/602.1 CFNetwork/808.2.16 Darwin/16.3.0---acw_tc=AQAAAN4Hd2JrAgQADEw4KkbrDSJnC1hU

3.goaccess.conf 
time-format %T
date_format  %Y-%m-%d
log-format     %dT%t+%^-%s-%b-%T-%h-%^-%^-%^-%m-%U--%H-%^-%R-%u-%^

4. that is ok

5   Little regret

Token '220.181.51.108, 103.18.208.171' doesn't match specifier '%h'
Token '41.114.163.91, 157.255.128.22' doesn't match specifier '%h'

**Comment by mayou33** [comment]
sorry,
 I see 
"Change X-Forwarded-For (XFF) specifiers #632"

thinks

**Comment by allinurl** [comment]
The following works for the line you just posted (you will need to compile from [**development**](https://goaccess.io/download#build) to build against #632), 

    goaccess -f access.log --log-format='%dT%t+%^-%s-%b-%T-~h{-:}-%^-%m-%U?-%q-%H-%^-%R-%u-%^' --date-format='%Y-%m-%d' --time-format=%T

**Note**, it won't work with previous lines. It looks like you have some inconsistencies with the hyphens that you need to fix before properly parsing it. You **should** definitely delimit and escape some of the fields such as the request, user agent and referrer.

**Comment by mayou33** [comment]
ok    think you very much
