### ISSUE TITLE
How to represent ISO date-time format?

### ISSUE THREAD

**Issue by laymonk** [allinurl/goaccess#635]
How does one represent the combined ISO DateTime+TZ format in goaccess?  

The format is like:  %Y-%m-%dT%H:%M:%S+TZ

**Notes:**
* There is a literal 'T' between the Day and Hour fields, to indicate the beginning of the time fields
* There is a literal '+' between the Second and Timezone fields
* Timezone is represented with 4-digit number: UTC is 0000 

[Apache's custom log directive equivalent](https://httpd.apache.org/docs/2.2/mod/mod_log_config.html) for this is {%Y-%m-%dT%H:%M:%S%z}t

[awstats equivalent](http://www.awstats.org/docs/awstats_config.html#LogFormat) is:
%time5    - Date and time with format iso: yyyy-mm-ddThh:mm:ss, with optional timezone specification (ignored)

I have been looking through your [custom log doc](https://goaccess.io/man#custom-log) but cannot see how to represent the literal characters and the timezone.   

Thanks in advance ..

**Comment by allinurl** [comment]
Timezone is currently not being used, so you can simply use:

```
log-format %dT%t+%^ %h... rest of log-format...
time-format %T
date-format %Y-%m-%d
```

**Comment by laymonk** [comment]
Million thanks for the super fast response .. I even learnt something new about how goaccess expects the log format to be specified from your examples above. 

I will give this a go asap  .. 

best regards

**Comment by laymonk** [comment]
One more question, please .. 

How to represent traffic load-balanced  across a clustered website .. ?

eg: 

```
#server1
%dT%t+%^ <cluster-fqdn> <server1-ip> %h

#server2
%dT%t+%^ <cluster-fqdn> <server2-ip> %h
```

**Comment by allinurl** [comment]
You will need to fetch those logs from each server, e.g., sshfs, rsyslog (centralized logging server), etc. And then parse them locally with goaccess.

BTW, if you need help with the log/date/time format, feel free to post a few lines from your access log and I can take a quick look.

**Comment by laymonk** [comment]
@allinurl, thanks again for the quick response ..  

The point of my question was to seek suggestion on log format (not on how to assemble/collate the log files from the respective cluster servers). 

More specifically, how do I represent cluster-server hostname/ip-address?  I presume that '%v' will match the cluster-fqdn  .. 

As an example, in apache2 custom log format, this could be represented as %A (or %A:%p) .. awstats offers %cluster ..

**Comment by allinurl** [comment]
@laymonk If I understand your question, `%h` and `%v` is probably what you need to use. As I said, feel free to post a few sample lines from your access log and I can take a quick look at the  log/date/time format.

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
