### ISSUE TITLE
Log Format and Keyphrases from Referrer issue...

### ISSUE THREAD

**Issue by david-bla** [allinurl/goaccess#636]
Hi, first I'm not quite familiar with log format patterns.

I'm running Ubuntu 16.04 and Apache2.4. The log entries are like this:

    1.2.3.4 - - [23/Jan/2017:20:58:06 +0100] "GET /my-folder/my-subfolder/file.extension HTTP/1.1" 200 234567 "https://my-domain.tld/my-site/" "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko"

I already tried to specify `--log-format=COMBINED` or or build the format patters by myself 
BUT after spending some time i realized my changes have no effect :/ it happens absolutely nothing.
There is no uncommented log-format statement in /etc/goaccess.conf.

I just rememberd a message the first times using goaccess, like "you had to specify log-format pattern" ... any idea?

**Comment by allinurl** [comment]
Since you haven't uncommented the log format in your config file, can you please try:

    goaccess -f access.log --log-format=COMBINED --no-global-config

**Comment by david-bla** [comment]
thank you, its working!
but why? ive tried to specify log format combined in config with no effect...

btw, if i run with --no-global-config there is a additional graph (whith is empty)  called "Keyphrases from Google's search engine"  how i get this data?

tank you in advance

**Comment by allinurl** [comment]
If you uncomment this [line](https://github.com/allinurl/goaccess/blob/master/config/goaccess.conf#L102) from your config file, it should do it. Otherwise please post your config file relevant parts.

"Keyphrases from Google's search engine" should automatically fill out as long as there are keyphrases within the referrer.

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
