### ISSUE TITLE
Custom log format for my nginx log

### ISSUE THREAD

**Issue by snithyashree** [allinurl/goaccess#637]
Hi,

Please find my nginx log below.

    0.001 0.001 [23/Jan/2017:04:06:22 -0800] GET /app/ajs/xxxx.js HTTP/1.1 304 0 "hostname" "https://refererurl" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36" "-" 988 - 10.x.x.x -  4710110 31 10.x.x.x -

**Comment by allinurl** [comment]
Can you please post which field is which? Thanks.

**Comment by snithyashree** [comment]
hi Allinurl,

This is the log format,

log_format  main  '$request_time $upstream_response_time [$time_local] $request $status $body_bytes_sent "$host" "$http_referer" "$http_user_agent" "$gzip_ratio" $request_length $http_client_ip $remote_addr $remote_user  $connection $connection_requests $upstream_addr $upstream_cache_status';

**Comment by allinurl** [comment]
This does it:

    log-format %T %^ [%d:%t %^] %m %U %H %s %b "%v" "%R" "%u" %^ %^ %^ %h %^
    date-format %d/%b/%Y
    time-format %T

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
