### ISSUE TITLE
Current log-format does not report bandwidth

### ISSUE THREAD

**Issue by ajoyoommen** [allinurl/goaccess#638]
Version 0.9.4

[NGINX] Logs parsed with `%h %^[%d:%t %^] "%r" %s %b` do not report any bandwidth. Bandwidth is always 0.0 B.

This is a sample log that was parsed successfully (without bandwidth):

    XX.XXX.XXX.XXX - - [23/Jan/2017:05:11:08 +0000] "GET /static/bootstrap/css/bootstrap.css HTTP/1.1" 200 142288 "https://example.com/extra-parameters" "Mozilla/5.0 (Linux; U; Android 5.1; en-US; Atom 2 Build/LMY47D) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 UCBrowser/ Mobile Safari/534.30" "-"

**Comment by allinurl** [comment]
This should do it:

    goaccess -f log --log-format=COMBINED

or 

```
log-format %h %^[%d:%t %^] "%r" %s %b "%R" "%u"%^
date-format %d/%b/%Y
time-format %T
```

**Comment by ajoyoommen** [comment]
goaccess -f log --log-format=COMBINED

does not read the bandwidth. But 

    log-format %h %^[%d:%t %^] "%r" %s %b "%R" "%u"%^

reads the bandwidth.

**Comment by allinurl** [comment]
You will need the latest version for `--log-format=COMBINED` to fully read the log. Feel free to update [**here**](https://goaccess.io/download).
