### ISSUE TITLE
How to get more precise Geolocation section ?

### ISSUE THREAD

**Issue by maxpv** [allinurl/goaccess#641]
Hello,

First thanks for this amazing tool.

I wanted to know if there is anyway to get more precise geo location section by command line ?
Detailing geolocation by country or by town for example.

**Comment by allinurl** [comment]
You should be able to get the continent, country and city by specifying the GeoIP-City DB with `--geoip-database`.  [**Here**](https://github.com/allinurl/goaccess/blob/master/config/goaccess.conf#L609) are the details on how to do this.

**Comment by allinurl** [comment]
BTW, support for GeoIP2 has been added per **#283**. Feel free to test it out, it will be pushed out in the upcoming version.

Closing this, feel free to reopen it as needed.

**Comment by maxpv** [comment]
Great news, thanks for the awesome job.
