### ISSUE TITLE
Can't configure with --enable-geoip on OS X

### ISSUE THREAD

**Issue by HiTechKoke** [allinurl/goaccess#642]
Great tool.  Got it up and running on a Mac - Yosemite 10.10.5 but had to remove the --enable-geoip configuration.  Read up and downloaded the .dat files and installed them.. now when I run configure I get an error:

```
root# ./configure --enable-geoip --enable-utf8
...
...
checking for GeoIP_new in -lGeoIP... no
configure: error: *** Missing development files for the GeoIP library
```

I searched around the web but couldn't find anything definitive and most posts were pretty old.  In my case I'm using GoAccess to review some log files from another server and this is from my mobile laptop so I don't want to install anything extra if I don't have to.  I'm assuming having GeoIP enabled will help identify locations, City or Country but only one database .dat can be used month the 3 versions available as noted in the configuration file.

**Comment by allinurl** [comment]
That's right, so far you can only use one database, #594 will address this. As far as installing goaccess with geoip, it might be best to use homebrew to do this, from the [**formula**](https://github.com/Homebrew/homebrew-core/blob/6ecfe9a78b88ab4630b32ba351b8a6592debb8d2/Formula/goaccess.rb), you should be able to run 

    # brew install goaccess --with-geoip

Now, if you are looking to install geoip from source, then I'd try (haven't tested on OS X):

    # curl http://www.maxmind.com/download/geoip/api/c/GeoIP-latest.tar.gz | tar xvz
    # cd GeoIP-1.6.0/
    # ./configure
    #  make
    # make install

then build goacces with `--enable-geoip` and use `--geoip-database=/path/GeoLiteCity.dat` to get country and city.

BTW, soon I'll be pushing out a commit that enables GeoIP2.

**Comment by HiTechKoke** [comment]
tks for the quick response... downloaded the GeoIP source and it compiled and installed without issue.  I then tried to build goaccess again but still get the same error.

root# ./configure --enable-geoip --enable-utf8
...
checking for GeoIP_new in -lGeoIP... no
configure: error: *** Missing development files for the GeoIP library

**Comment by allinurl** [comment]
Are you building goaccess from upstream (github)?

**Comment by HiTechKoke** [comment]
I am using the download from the web site... http://tar.goaccess.io/goaccess-1.1.1.tar.gz

**Comment by allinurl** [comment]
It seems like OS X requires some additional steps, please take a look at [**this**](http://superuser.com/questions/303460/is-there-a-way-to-install-geoip-from-source-code-on-mac-os-x) post. Also this [**formula**](https://github.com/Homebrew/homebrew-core/blob/ba0aa68066a89c0654152aba22819736b06987af/Formula/geoip.rb) may help.

**Comment by HiTechKoke** [comment]
I finally solved the following configure error in my MacOS Yosemite environment when trying to combine with the GeoIP library. That error is

configure: error: *** Missing development files for the GeoIP library

A few things I found that were needed in my Yosemite environment.

Install Homebrew from here...
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)”

I needed automake installed for a later that gets stuck without it.

brew install automake

Get the legacy Geo Databases here:  

http://dev.maxmind.com/geoip/legacy/geolite/

They are in the .dat format and make sure they are installed according to this page 
http://dev.maxmind.com/geoip/legacy/install/country/

These are not the databases located here http://dev.maxmind.com/geoip/geoip2/geolite2/ which are in a different format

The .dat files I have in /usr/local/share/GeoIP are as follows.  I copied and renamed the GeoLiteCity.dat to GeoIPCity.dat
 
-rw-r--r--@ 1 root  wheel   1062137 Feb  4 09:20 GeoIP.dat
-rw-r--r--@ 1 root  wheel  17775436 Feb  4 10:54 GeoIPCity.dat
-rw-r--r--@ 1 root  wheel  17775436 Jan 29 10:01 GeoLiteCity.dat

Read some good tips here on getting the geoiplookup code working which is key to everything.  It’s in this thread

http://superuser.com/questions/303460/is-there-a-way-to-install-geoip-from-source-code-on-mac-os-x

and the code is here:  

http://www.maxmind.com/download/geoip/api/c/GeoIP-latest.tar.gz
Configure / Make / Make install and now test the geoiplookup tool to verify it can resolve an IP / Domain to a Country.

Set these env variables as they will help going forward. 

export LIBRARY_PATH=$LIBRARY_PATH:/usr/local/lib
export C_INCLUDE_PATH=$C_INCLUDE_PATH:/usr/local/include

Now I determined in needed to get the GeoIP Legacy C API code in order to build and install the libGeoIP library needed for GoAccess compilation to use the GeoIP database.

That code is here:

https://github.com/maxmind/geoip-api-c

Make sure to run bootstrap prior to configure as this creates the configure file. You’ll need to have automake already in
installed to get a configure shell script.  After the configure / make / make install you need to make sure the geoiplookup command works which indicates you have the right .dat Geo libraries in the right locations which will then get you back to compiling GoAccess successfully. Looking at the test src files helped me also on what .dat files it needed overall.

Make sure the libGeoIP libraries are in  /usr/local/lib

Now you can get back to GoAccess as you should be able to use configure with the enable-geoip flag as follows without any errors:

./configure --enable-geoip --enable-utf8

Now the make and make install should work.  That C_INCLUDE_PATH export from above was needed to find the <GeoIP.h> file.
The proof this finally all worked was when running goaccess created a Geo Location pane that had regional and country locations in the html output file I specified.

I likely missed some things along the way above and it was messy but I got it to work.  Your mileage may vary and maybe this will help somebody.

**Comment by allinurl** [comment]
Thanks for the great post and all the details, glad you got it to work :)

Closing this.
