### ISSUE TITLE
No unique visitors graph

### ISSUE THREAD

**Issue by Eberx** [allinurl/goaccess#643]
I'm using goaccess 1.1.1 and monitoring nginx log but there is no graph on unique visitors.

![screenshot from 2017-01-30 09 39 45](https://cloud.githubusercontent.com/assets/6083306/22410240/72ca9790-e6d0-11e6-9a78-cff48494abf6.png)

**Comment by allinurl** [comment]
Looks like a log-format issue. Can you please post a few lines from your access log and the log-format that you are using?

**Comment by Eberx** [comment]
This is my log. and I used following formats

cat example-access.log* | goaccess --no-global-config --log-format='%h
%^[%d:%T %^]  %s "%r" %b %^ "%u" "%R" %^ %^ %^' --date-format='%d/%b/%Y'
--time-format='%T' -o /var/www/web/report.html

**Comment by allinurl** [comment]
Looks like you got the time wrong there, try this:

    cat example-access.log* | goaccess --no-global-config --log-format='%h %^[%d:%t %^] %s "%r" %b %^ "%u" "%R" %^' --date-format='%d/%b/%Y' --time-format='%T' -o /var/www/web/report.html

**Comment by Eberx** [comment]
I got error

root@kickseed:~/logs# cat example-access.log* | goaccess --no-global-config
--log-format='%h %^[%d:%t %^] %s "%r" %b %^ "%u" "%R" %^'
--date-format='%d/%b/%Y' --time-format='%T' -o /var/www/web/report.html
Parsed 10 lines producing the following errors:

Token '' doesn't match specifier '%s'
Token '' doesn't match specifier '%s'
Token '' doesn't match specifier '%s'
Token '' doesn't match specifier '%s'
Token '' doesn't match specifier '%s'
Token '' doesn't match specifier '%s'
Token '' doesn't match specifier '%s'
Token '' doesn't match specifier '%s'
Token '' doesn't match specifier '%s'
Token '' doesn't match specifier '%s'

Format Errors - Verify your log/date/time format

**Comment by Eberx** [comment]
Thank you very much. It is working now. double spaces have in front of %s.

**Comment by allinurl** [comment]
Glad that worked.
