### ISSUE TITLE
How to do realtime graphs with history saving option.

### ISSUE THREAD

**Issue by bentech4u** [allinurl/goaccess#644]
Hi,

i tried my best level to figureout how to implement realtime graph.

i used below command :+1: 

    # goaccess -f /var/log/httpd/access_log -o /usr/local/share/piwik/report.html --real-time-html --ws-url=212.43.0.66

but the page is not refreshing.

i have environment which runs centos 7 with firewall and selinux enabled.

what all things i need to do to get live repots ?

>Regards,
Ben

**Comment by bentech4u** [comment]
i enabled 7890 and it started working now.

how can i save data to local file.i need atleast one month report to be load

**Comment by allinurl** [comment]
For incremental log processing, or just data persistence, you will need to build with btree for on-disk support.

$ wget http://tar.goaccess.io/goaccess-1.1.1.tar.gz
$ tar -xzvf goaccess-1.1.1.tar.gz
$ cd goaccess-1.1.1/
$ ./configure --enable-utf8 --enable-geoip --enable-tcb=btree
$ make
# make install

Then please take a look at the [**man page**](https://goaccess.io/man#examples) for incremental log processing.

**Comment by bentech4u** [comment]
HI

thanks for the info.

"If --load-from-disk is used without --keep-db-files, database files will be deleted upon closing the program."

i enabled both on my configuration file and default directory set to /tmp . but while closing the program, the file is getting deleted

**Comment by allinurl** [comment]
Did you enable them in the config file or command line? If you did in the command line, try passing: 

    # goaccess -f access_log --no-global-config --keep-db-files --load-from-disk -o report.html --real-time-html --ws-url=212.43.0.66

**Comment by bentech4u** [comment]
HI

i enabled options in the configuration file.
currently i am giving only below. all other parameters given in config file 
# goaccess  --real-time-html --ws-url=212.43.0.66

**Comment by allinurl** [comment]
Did it work? Before you quit goaccess, do you see the files under /tmp? and after you quit goaccess, are the files still in /tmp? Make sure you built with `--enable-tcb=btree`.

**Comment by bentech4u** [comment]
hi

yes i compiled with --enable-tcb=btree . i can able to see 2 files under /tmp with 0K in size. , when i close the program, those files are  vanishing

**Comment by allinurl** [comment]
That's odd, there should be many more files in `/tmp`. Can you please attach your config file and the output of 

    goaccess -s

as well as the following output when goaccess is running 

    ls -lath /tmp

**Comment by bentech4u** [comment]
HI

[root@centos ~]# goaccess -s
Built using Tokyo Cabinet On-Disk B+ Tree.

[root@centos tmp]# ls -lath /tmp
total 20K
prw-r--r--.  1 root root    0 Feb  2 09:33 wspipein.fifo
prw-r--r--.  1 root root    0 Feb  2 09:27 wspipeout.fifo


[goaccess.zip](https://github.com/allinurl/goaccess/files/746985/goaccess.zip)

**Comment by allinurl** [comment]
Got it. In your config file, make sure you use `db-path /tmp/` (note the trailing forward slash) otherwise, you will be putting them in the root `/` directory. 

BTW, you may want to delete the files from the root directory if they're there.

**Comment by bentech4u** [comment]
Ok,

i will add like /tmp/ . but those files are already generated under /tmp and nothing under /root i guess

i will check and update you

**Comment by allinurl** [comment]
I meant root as the highest directory in the hierarchy, not under `/root`, only `/`.

**Comment by bentech4u** [comment]
HI

i have changed to /tmp/ and the tcb files are generated under /tmp.

but my current issue is i cannot able to see realtime graphs and it was working before

**Comment by allinurl** [comment]
Again, please post the command you are running. Also if using `--ws-url=host`, note that  the host part should point to the location where GoAccess is running and parsing logs. Also, make sure host is a valid host and should not contain http on it.

And post the URL of your report and I can take a look if there is something wrong from the client side.

**Comment by bentech4u** [comment]
HI

it is working now.

and this is the command to run 

 /usr/local/bin/goaccess --real-time-html --ws-url=212.43.0.66 &

i was enabled below options and that time realtime was not working

#fifo-in /tmp/wspipein.fifo

# Path to write named pipe (FIFO).
#
#fifo-in /tmp/wspipeout.fifo

commented out and restarted goaccess, real time started working

**Comment by allinurl** [comment]
Glad that worked. Yes, issue #575 addressed this issue, which will be pushed out in the upcoming version. Thanks for pointing it out. Closing this, feel free to reopen it if needed.

**Comment by bentech4u** [comment]
thank u soo much for your help.
