### ISSUE TITLE
+0100]' doesn't match specifier '%h'

### ISSUE THREAD

**Issue by RoqueCampos** [allinurl/goaccess#645]
Dear Friends, 

I did a research through all the issues, but nothing solved my problem.

I'm using goaccess 1.1.1 with apache 2.4,  and I only can make it work when I use the --log-format=COMBINED  option. But I really need the --log-format=VCOMBINED because I need the information for the virtualhosts. 

That's the command I'm using:

`goaccess -f /var/log/apache2/access.log  --log-format=VCOMBINED --no-global-config`

That is an entry of my Apache access log file:

`www.xxxxxx.com:80 46.229.168.73 - - [31/Jan/2017:09:44:00 +0100] "GET /showthread.php?s=ff10fb2cebe47ec51e598eb4c6eb0b8f&t=14607 HTTP/1.1" 301 738 "-" "Mozilla/5.0 (compatible; SemrushBot/1.2~bl; +http://www.semrush.com/bot.html)"
`

And I receive following error message:

`+0100]' doesn't match specifier '%h'`

I request apologizes again If the solution is to obvious, but I'm missed.

Thank you in advance,

**Comment by allinurl** [comment]
goaccess -f /var/log/apache2/access.log --log-format=VCOMBINED --no-global-config

Works for me. Do you have a config file under `~/goaccessrc`, that's the second place goaccess will check for a config file?

**Comment by RoqueCampos** [comment]
Dear allinurl,

I double checked all my configurations, and it was a mistake in my side. I was using a wrong configuration in my /sites-available/conf files for the log format.

It seems it is working now. I request apologizes.

Thankyou

**Comment by allinurl** [comment]
No worries. Glad that worked :)
