### ISSUE TITLE
Fixed percent issue when calculating visitors field in JSON/CSV output

### ISSUE THREAD

**Issue by allinurl** [allinurl/goaccess#648]

**Comment by allinurl** [comment]
This has been fixed. The issue was occurring in the visitors column as displayed below.

![2017-02-02-185157_507x257_scrot](https://cloud.githubusercontent.com/assets/5005367/22575011/8295bd6c-e978-11e6-8fda-556fe29866cb.png)


It will be pushed out in the upcoming version.

**Comment by amatriain** [comment]
:+1:
