### ISSUE TITLE
Change percentage calculation to be based on the total within each panel

### ISSUE THREAD

**Issue by allinurl** [allinurl/goaccess#649]

**Comment by allinurl** [comment]
[**Updated**](https://github.com/allinurl/goaccess/commit/8e9e3a995a59fcf13077ff669cf1fc8563fdc93b). It should now calculate the percent for hits/visitors/bandwidth given the total of each of those columns instead of using the total from the overall panel.

It will be shipped in the upcoming release.

**Comment by amatriain** [comment]
:+1:
