### ISSUE TITLE
Global config seems to override arguments?

### ISSUE THREAD

**Issue by danwashusen** [allinurl/goaccess#652]
OS: Ubuntu 14.04.5 LTS
Version: 1.1.1

I spent hours trying to diagnose why I wasn't getting response times in the report output despite it working in my local dev environment. After a bunch of trial error I added the '--no-global-config' argument and it worked in both environments. Turns out the test machine had a /etc/goaccess.conf...

It seems like the global config (/etc/goaccess.conf) 'log-format' takes precedence over the same value provided as an argument '--log-format=...'. If a user goes to the effort of providing the value as an argument shouldn't it be used over the value in global config?

/etc/goaccess.conf
```
time-format %T
date-format %d/%b/%Y
log-format %h %^[%d:%t %^] "%r" %s %b "%R" "%u"
```

Command I was testing with:
`cat foo.log | /usr/bin/goaccess [--no-global-config] --no-progress -q -r --time-format='%T' --date-format='%d/%b/%Y' --log-format='%h [%d:%t %^] "%r" %s %b "%R" "%u" %^ %T' --json-pretty-print -o ~/GoAccessReportPlugin.json`

Great tool btw! :)

**Comment by allinurl** [comment]
Thanks for reporting this! I was able to reproduce this on my side. I'll post back as soon as I push a fix for it.

**Comment by allinurl** [comment]
This has been fixed. The command line arguments take priority now over a config file. It will be pushed out in the upcoming version. 

Thanks again!
