### ISSUE TITLE
Dashboard showing data only for one day

### ISSUE THREAD

**Issue by a1501272** [allinurl/goaccess#654]
Hi, i have one small error. My dashboard is only showing today's data from my server, but i woudl like to see overall data. Like from whole time what server has been running. I dont know if this is right section to ask help, move or delete if needed.  http://imgur.com/a/YD76R here is picture off how it is showing in terminal.
Else Goaccess is working fine

**Comment by allinurl** [comment]
Are you rotating the log every day? If you are, you could change to monthly. However, you should still be able to run:

    zcat -f /var/log/apache2/access.log* | goaccess

BTW, if you are using putty, you may want to change the color setting to display bold text (dark columns in goaccess). Select Change Settings > Window > Colours and make sure "Indicate bolded text by changing" > "The colour" is checked.

**Comment by a1501272** [comment]
I don't think i'm rotating the log everyday. I'm kinda new to these things and learning just.  I used to run goaccess with command: goaccess -f /var/log/apache2/access.log -a and it showed only daily statics but with that your command it's showing overtime data, so thank you! But now it is still showing daily data in html form. To generate html page i use command :  goaccess -f /var/log/apache2/access.log -a -o report.html so there must be wrong with that..? when i tried  zcat -f /var/log/apache2/access.log* | goaccess -a -o report.html it gave error http://imgur.com/a/XmN41

**Comment by allinurl** [comment]
Seems like it can't write to your output directory. Since you are under `/var/www/html/`, you will need to use sudo with goaccess as well:

    sudo zcat -f /var/log/apache2/access.log* | sudo goaccess -a -o report.html

**Comment by a1501272** [comment]
Yea i tried even with sudo but it will give same error as without sudo

**Comment by allinurl** [comment]
Can you please try outputting to your user directory:

    sudo zcat -f /var/log/apache2/access.log* | goaccess -a -o ~/report.html

Also, can you please post the whole error message.

**Comment by a1501272** [comment]
i got it working now! had to use chown to the file path, and now it works. Last questing, does it automatically  update the current day. I mean like if today it's 10.2 and it is showing it, but do it tomorrow show 11.2, without doing that sudo zcat -f /var/log/apache2/access.log* | sudo goaccess -a -o report.html agen?

**Comment by allinurl** [comment]
Glad that solved it.

To answer your question, no, you won't get the report updated that way. You will need to keep  goaccess running for that to happen. You will need to run it like:

    goaccess -f /var/log/apache2/access.log -a -o report.html --real-time-html --ws-url=your_server_ip

Make sure to open port 7890. Please take a look at the [**examples**](https://goaccess.io/man#examples) section or the [**FAQ**](https://goaccess.io/faq#html-report) for additional details.

**Comment by mooleshacat** [comment]
zcat worked for me. Thanks @allinurl :)

I use mine in a cronjob:

```*/5 * * * * /usr/bin/zcat -f /var/log/nginx/access.combined.log* | /usr/local/bin/goaccess -o /var/www/html/report.html --log-format=COMBINED```
