### ISSUE TITLE
Goaccess live not updating

### ISSUE THREAD

**Issue by cbaptista** [allinurl/goaccess#655]
Hi,
I installed Goaccess to monitor the logs generated by a reverse proxy (pound), but I can not see real-time statistics.
The page is not updated with the new entries. It is necessary to stop and start the goaccess for the statistics to be updated.

The command line I use is:

    goaccess --date-format = "% d /% b /% Y" --time-format = "% H:% M:% S" --log-format = "% v% h% % P% s% b% -f pound.log --real-time-html --ws-url = goaccess.io --addr = xxx.xxx.xxx.xxx -o /var/www/html/report.html

Any suggestion?
Thank you.
Carlos

**Comment by szorg** [comment]
1) You're missing a quote after the end of your log format.
2) If that doesn't work, try removing the spaces (example --ws-url=goaccess.io` instead of `--ws-url = goaccess.io`

**Comment by allinurl** [comment]
@cbaptista Also, please ensure you are using a valid `--ws-url` and a valid `--log-format`. e.g.,

    goaccess -f pound.log -o /var/www/html/report.html --real-time-html --ws-url=your_server_ip_where_goaccess_is_running --log-format VCOMBINED

Feel free to post a few lines from your access log to verify the log format. Also, port 7890 must be open.

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.

**Comment by rumski20** [comment]
I think I'm experiencing the same issue as @cbaptista.  
I'm using the following command to run goaccess:  
 `sudo zcat /var/log/apache2/access.log.*.gz | goaccess -f /var/log/apache2/access.log /var/log/apache2/access.log.1 - -o /var/www/html/monitoring/index.html --real-time-html --ws-url=wss://data.nrri.umn.edu:7890 --daemonize`

What I'm hoping this does is extract the older compressed logfiles, pipe that to goaccess as well as using the uncompressed logs. It should generate a continuously updated HTML report. And I want it to run in the background as well so I don't have to leave a terminal session open.

This does indeed produce an HTML report, but it does not get updated.  It is the same statistics and date as when I first ran the command yesterday.

I'm also having trouble confirming that port 7890 is open after I run the command.  
`sudo netstat -tulpn | grep 7890` returns nothing.

Please advise.
