### ISSUE TITLE
is there any way to generate bandwidth report for a week

### ISSUE THREAD

**Issue by bentech4u** [allinurl/goaccess#658]
HI

is there any way to generate bandwidth report for a week

my goaccess is running with local DB support and it's plotting live. 

Regards,
Ben

**Comment by bentech4u** [comment]
currently goaccess is running with 

/usr/local/bin/goaccess --real-time-html --ws-url=212.43.0.66 

and when i tried to generate csv alogin with that, i got below

_[root@centos tmp]# /usr/local/bin/goaccess -o csv > /tmp/1.csv
Parsing... [0] [0/s]
GoAccess - version 1.1.1 - Jan 30 2017 16:08:00
Config file: /usr/local/etc/goaccess.conf

Fatal error has occurred
Error occured at: src/websocket.c - ws_socket - 2682
Unable to set bind: Address already in use._

**Comment by allinurl** [comment]
If you would like to run a second instance, you will need to use a different config file so it doesn't attempt to run another real-time report. Try the following (replace the log-format value as needed)

     goaccess -f access.log -o report.csv --log-format=COMBINED --no-global-config

**Comment by bentech4u** [comment]
HI

thanks for the information.

yes my log format is combined only. will it take data from existing database files under /tmp ?

**Comment by allinurl** [comment]
It's up to you how you want goaccess to process the log. If you want to use the /tmp/ files, then you can indicate that, else you need to use a different path. You can copy the existing config file and remove all the real-time data variables/values and use `-p` to specify the new config file.

     goaccess -f access.log -o report.csv --log-format=COMBINED --no-global-config -p /your_new/config.file

**Comment by bentech4u** [comment]
hi

goaccess --load-from-disk with existing db files is possible? insted of feeding again access.log ?

**Comment by bentech4u** [comment]
i issued 

zcat -f access* | goaccess -o /tmp/log/report.csv --log-format=COMBINED --no-global-config


but the csv file is not yest generated

**Comment by allinurl** [comment]
You can't use the same database files while another instance is using the files. You will need to use different db files or stop the other instance first.

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
