### ISSUE TITLE
Combined LogFormat not working in GNU/LINUX 2.6.32

### ISSUE THREAD

**Issue by mitcydf** [allinurl/goaccess#662]
Hi, I have specified the following in httpd.conf file:
LogFormat "%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" combined
CustomLog logs/kahena_log combined

But, no log statements are being written into kahena_log.
Could you please let know if there is anything missing?

**Comment by allinurl** [comment]
Are you asking about goaccess log-format? Otherwise please look at the [apache's documentation](http://httpd.apache.org/docs/current/mod/mod_log_config.html) for it.

**Comment by mitcydf** [comment]
Hi Gerardo,
I have configured exactly as mentioned in the Apache documentation but it still does not seem to work. Could you please let know if there is anybody else that I need to reach out to if it is an Apache issue?
Thanks,Mitcy 

    On Wednesday, February 15, 2017 2:42 PM, Gerardo O. <notifications@github.com> wrote:
 

 Are you asking about goaccess log-format? Otherwise please look at the apache's documentation for it.—

**Comment by allinurl** [comment]
I'm not sure I follow your question/issue. Are you having issue with goaccess? If you are, please any error messages you are getting and a few lines from your current access log. Thanks.

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
