### ISSUE TITLE
goaccess: unrecognized option '--real-time-html'

### ISSUE THREAD

**Issue by ningappa** [allinurl/goaccess#663]
Hi
I installed  latest version v1.1.1 goaccess using following command. 
```
git clone https://github.com/allinurl/goaccess.git
autoreconf -fiv
./configure --enable-geoip --enable-utf8
make
make install
```

I tried using it by using following command

`goaccess -f /var/log/apache2/access.log -o /var/www/html/report.html --real-time-html --ws-url=server.ip -p /etc/goaccess.conf`

Got error : 
**`goaccess: unrecognized option '--real-time-html'`**

Please help. i want to access it through browser for real time data.

**Comment by allinurl** [comment]
Did you have a previous version installed? Can you please run `goaccess -V`?

BTW, since you are building from master, you will need to pass `legacy` to `--enable-geoip` (or geoip2)

    ./configure --enable-geoip=legacy --enable-utf8

**Comment by ningappa** [comment]
I'm trying it for first time, 
```
root@ubuntu:~# goaccess -V
GoAccess - 1.1.1.
For more details visit: http://goaccess.io
Copyright (C) 2009-2016 by Gerardo Orellana

```

I tried 
`./configure --enable-geoip=legacy --enable-utf8`

It gave error 

> *** Missing development files for the GeoIP library


**to solve** this installed  libgeoip-dev

`sudo apt-get install libgeoip-dev`

and then 
```
./configure --enable-geoip=legacy --enable-utf8
make
make install
```
and then 

`goaccess -f /var/log/apache2/access.log -o /var/www/html/report.html --real-time-html --ws-url=server.ip -p /etc/goaccess.conf
`
**# Awesome.** It worked. I'm loving this tool

thanks alot.
