### ISSUE TITLE
Format Errors - Verify your log/date/time format

### ISSUE THREAD

**Issue by Cr0iX** [allinurl/goaccess#668]
Hello,
I cannot get it to work with my logformat. So i hope you guys can help me. I've tried VCOMBINED and VCOMMEN but doesnt work.

**My logformat is:**
LogFormat "%v - %h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" comonvhost

**and looks like this:**
www.site.com - 123.123.123.123 - - [21/Feb/2017:15:48:23 +0100] "HEAD / HTTP/1.1" 200 - "http://www.site.com" "Mozilla/5.0+(compatible; UptimeRobot/2.0; http://www.site.com/)"

**I use this goaccess command:**
goaccess -f /var/log/httpd/access_log --log-format="%v - %h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" --date-format='[%d/%b/%Y' --time-format='%H:%M:%S'

and get this error:
Token '[21/Feb/2017:03:33:25' doesn't match specifier '%t'

Regards
Cr0iX

**Comment by allinurl** [comment]
This should do it:

    goaccess -f /var/log/httpd/access_log --log-format='%v %^ %h %^[%d:%t %^] "%r" %s %b "%R" "%u"' --date-format=%d/%b/%Y --time-format=%T

**Comment by Cr0iX** [comment]
Thank you very much !

**Comment by milhangit** [comment]
@allinurl  my Log format is below on Nginx, can you assist as im getting the same error.


-------------------------------------------
  log_format  main    '$remote_addr - $remote_user [$time_local] $request '
                        '"$status" $body_bytes_sent "$http_referer" '
                        '"$http_user_agent" "$http_x_forwarded_for"';
    log_format  bytes   '$body_bytes_sent';
