### ISSUE TITLE
Browser and Opreating System Data is not showing in Dashboard.

### ISSUE THREAD

**Issue by BipinBahuguna** [allinurl/goaccess#670]
Hello Team,

Can you please help me get the browser and os data in goaccess dashboard.
Attaching screen shot for the reference. browser and os data showing unknown

![browser](https://cloud.githubusercontent.com/assets/11075169/23270694/90784760-f9a9-11e6-889d-67bf8c4a27f9.PNG)
Thanks,

**Comment by allinurl** [comment]
Please attach a few lines from your access log to determine which log-format you need. Thanks.

**Comment by BipinBahuguna** [comment]
Below is the access log entry.

10.3.45.5 - - [23/Feb/2017:04:30:57 -0500] "GET /etc/designs/alecensa/images/alecensa/splash/btn-splash-arrow.png HTTP/1.1" 200 1229 "https://www.example.com/tel:18882494918" "Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; Trident/5.0)"

**Comment by allinurl** [comment]
This should do it:
    
     goaccess -f access.log --log-format=COMBINED

or uncomment [this line](https://github.com/allinurl/goaccess/blob/master/config/goaccess.conf#L102) from your config file:

    log-format=COMBINED

**Comment by BipinBahuguna** [comment]
Tried it but still no browser and os data is coming its showing unknown

**Comment by allinurl** [comment]
For the log line you posted above works fine. Do you have mixed log formats in your access.log?

**Comment by BipinBahuguna** [comment]
Worked fine with below combination.

log-format %h %^[%d:%t %^] "%r" %s %b "%R" "%u"
log-format COMBINED
