### ISSUE TITLE
Track downloads separately from static files

### ISSUE THREAD

**Issue by djay** [allinurl/goaccess#674]
It is useful to be able to track pdfs, docs, mkv, mp3 etc separately from css,js etc. It would also be useful to make use of a logged mimetype instead of just using extensions. Ideally it would be nice to combine this with custom panels (#515) so I could have a docs panel, video panel + whatever other combination of ext, mimetype, url?
AWStats has a downloads section.

**Comment by allinurl** [comment]
I agree that having the ability to add custom panel would be great, and probably would solve your suggestion above.

As far as tracking pdfs, etc, you already should be able to add your custom extensions to your config file, please take a look at [**this section**](https://github.com/allinurl/goaccess/blob/master/config/goaccess.conf#L528). Thanks.

**Comment by djay** [comment]
Hi. Thanks I know I can add extra extensions. I should have made the requirements clearer. I need to track downloads like docs in a way that doesn’t include css/js etc which aren’t really downloads. So if I take out css/js etc from static file extensions I would get what I want right? Does that affect any other stats if I do this?

**Comment by allinurl** [comment]
You can certainly remove them from your config file and they will appear in the requests panel instead of the static panel. Like you said, implementing #515 will let you add custom panels.

**Comment by allinurl** [comment]
Closing this since it'll be addressed on #515. Feel free to reopen it if needed.
