### ISSUE TITLE
supervisord configuration for use of zcat with multiple log files and websocket

### ISSUE THREAD

**Issue by ningappa** [allinurl/goaccess#676]
I want to control  goaccess from supervisord for real-time web reports. What should be the command? would be great and helpful if you add an example supervisord configuration.

this is command with supervisord 

`zcat -f /var/log/apache2/access.log.* | goaccess --log-format=COMBINED -o /var/www/html/report.html --real-time-html --ws-url=server.ip -p /etc/goaccess.conf /var/log/apache2/access.log -`

thanks in advance :)

**Comment by allinurl** [comment]
A few days ago I pushed a commit that enables the ability to parse multiple logs and have live stats as well as the ability to pipe data such as `tail -f`and still have a real-time report. This will be deployed in the upcoming version. However, if you are building  from master, then you can run the command you posted, i.e.,

    zcat -f /var/log/apache2/access.log.* | goaccess --log-format=COMBINED -o /var/www/html/report.html --real-time-html --ws-url=server.ip -p /etc/goaccess.conf /var/log/apache2/access.log -

I'll be updating the docs pretty soon before deployment occurs.

**Comment by ningappa** [comment]
@allinurl i did make it work with supervisord.

supervisord configuration file
/etc/supervisor/conf.d/supervisord-goaccess.conf
```
[program:goaccess]
command = /home/goaccess/init.sh
autostart=true
autorestart=true
stderr_logfile=/var/log/myapi.err.log
stdout_logfile=/var/log/myapi.out.log
user=root
```
/home/goaccess/init.sh

```
#!/bin/bash

exec zcat -f /var/log/apache2/access* | goaccess --log-format=COMBINED -o /var/www/html/report.html --real-time-html --ws-url=singledeploy44.com /var/log/apache2/access.log -

```

```
supervisorctl reread
supervisorctl update
```

Now goaccess will be running in background and controlled by supervisord.

you can add these two files as example for running using supervisord.

**Comment by allinurl** [comment]
That's great!! btw, if you want goaccess to run as a daemon, you can use `--daemonize`.

Thanks for posting this, I'll add it to the docs before the new version is released.
