### ISSUE TITLE
Ability to parse empty X-Forwarded-For (XFF) (w/o IP)

### ISSUE THREAD

**Issue by Tassleh0ff** [allinurl/goaccess#679]
Hi, I'm trying to solve many invalid requests caused by records starting with "-" because in some case my reverse proxy do not pass the host ip address.

This is a log example (the last field is the reverse proxy internal address):
```
- - unauthenticated [07/Mar/2017:09:23:46 +0100] "GET /context/resources/file.js HTTP/1.1" 200 - 10.10.10.200
- - unauthenticated [07/Mar/2017:09:23:46 +0100] "GET /context/resources/file.html HTTP/1.1" 200 - 10.10.10.200
```

This is the goaccess syntax I'm using:
`goaccess --log-format='~h{, } %^ %e [%d:%t %^] "%r" %s %b %^' --date-format='%d/%b/%Y' --time-format='%T' --invalid-requests=/tmp/goaccess-invalid.log`

All records are perfectly analyzed except those starting with "-".

Is there any way to analyze also these records for hits statistics?

Thanks

**Comment by allinurl** [comment]
There's no way right now to analyze these records since the parser does check for a valid IPv4/6. Is not having an IP fairly common on a reverse proxy setup?

If it is, perhaps making an exception may do it... however, if we go that way, the visitors count won't be as accurate as having an IP.

**Comment by Tassleh0ff** [comment]
To be honest it's not so common, this is an exception, but I think it will be useful an extra option for define a default ip address in case %h (or ~h) is not valid or empty.
Or perhaps an extra log-format variable to define a second log field in case host address is missing or invalid.

Just an idea for future feaures :)

Thanks for your answer

**Comment by allinurl** [comment]
Thanks, I can add an option to specify a dummy but valid IP.

**Comment by thor0215** [comment]
Are there still plans to offer support for this?  I have a use case where our Tomcat web servers are behind a load balancer.  Normal user traffic has the XFF, but cluster traffic between the tomcat nodes do not.  Having an option like the one mentioned about would allow me to see both sets of traffic together.

**Comment by allinurl** [comment]
@thor0215 Per this [commit](https://github.com/allinurl/goaccess/commit/127c6165bbf67a4476128511b29f4bfceff7d62a#diff-c1f9cca172a4d29eaff6871779b7a7fc), can you please try using `--no_ip_validation` and see if that solves the issue for you.

**Comment by allinurl** [comment]
Closing this as --no-ip-validation has been implemented.
