### ISSUE TITLE
A New Feature - Adapting Squid Access Log

### ISSUE THREAD

**Issue by msarmadi** [allinurl/goaccess#68]
People often use apache log analyzers for their cache servers as well. 
A good idea is to have squid access log adapted or having a document/howto for those users in which we show them how to use goaccess for that purpose.

**Comment by tombatossals** [comment]
Hi, I have some experience with squid, with some servers running on it, and it would be incredible to parse the logs with goaccess. I can try to help with this task, can you describe that "request string" needed? Which would be the equivalent in an nginx or apache log?

**Comment by allinurl** [comment]
Depending on your log, you should already be able to parse squid logs. The request string should be either `%r` or `%U`, for instance:

    "GET /home.php HTTP/1.1"

or only:

    /home.php

Thanks

**Comment by tombatossals** [comment]
Hi, thanks for the response. I'm almost there, but maybe you can give me another advice.

I have enabled the squid combined log format, this can be accomplished adding this directive to the squid.conf configuration file

```
logfile /var/log/squid/access.log combined
```

Which format the log this way (I'm describing the fields):

```
%source_ip_address %username_from_ident %username [%localtime] "%request_method %request_url HTTP/%request_protocol" %http_status %total_size "%referer" "%user_agent" %squid_request_status:%squid_hierarchy_status
```

For example, this line of log has been generated with this format:

```
10.229.21.164 - username [27/May/2015:10:02:47 +0200] "GET http://tiendas.mediamarkt.es/js/tlg_js.cfm? HTTP/1.1" 200 1452 "http://tiendas.mediamarkt.es/martes-night-show?utm_source=newsletter&utm_medium=email&utm_campaign=MNS26" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.81 Safari/537.36" TCP_MISS:HIER_DIRECT
```

But goaccess is unable to detect anything with this format, I have tried a lot of custom formats trying to adapt it to the previously described squid log, but always says me "No valid this". Any hint of where the problem can be?

**Comment by allinurl** [comment]
This does it:

    goaccess -f /var/log/squid/access.log --log-format='%h %^[%d:%t %^] "%r" %s %b "%R" "%u"' --time-format='%T' --date-format='%d/%b/%Y'

**Comment by tombatossals** [comment]
OMG, it works! It was a time-format issue, I was searching in a totally different direction.

That's fantastic, thanks so much for your help. I'm going to take some screenshots showing the resulting reports .

**Comment by allinurl** [comment]
Glad that worked out well. Feel free to share some results :)

**Comment by tombatossals** [comment]
Here it is, I attach two screenshots of the goaccess HTML report generated from an squid server.

![goaccess01](https://cloud.githubusercontent.com/assets/124169/7862395/e93d48cc-0555-11e5-81fb-0a565709c378.png)
![goaccess02](https://cloud.githubusercontent.com/assets/124169/7862396/e93f6620-0555-11e5-8514-1d17b8119b2e.png)

It's really easy to have it working.

squid.conf:
```
logfile /var/log/squid/access.log combined
```

goaccess.conf or .goaccessrc
```
log-format %h %^[%d:%t %^] "%r" %s %b "%^" "%u"
date-format %d/%b/%Y
time-format %T
```

And that's all!

**Comment by allinurl** [comment]
The ability to parse Squid native access.log format has been added. Here's the log format to use:

    log-format %d.%^ %~ %^ %h %^/%s %b %m %U %^
    date-format %s
    time-format %s

Notice the `%~` specifier, which moves forward through a log string until a non-space char is found.

**Comment by neroxyr** [comment]
Thanks @allinurl , this did it!
