### ISSUE TITLE
Pipe log to GoAccess not working in cronjob without hyphen

### ISSUE THREAD

**Issue by spy1986** [allinurl/goaccess#680]
**In Cronjob:**
In version 1.1.1 the following call worked in cronjob:
`zgrep -h '\[07/Mar/2017' /var/log/apache2/access.log.gz |  goaccess --no-progress -q > /path/to/file.html`

In version 1.2 this call works only when I insert a hyphen to goaccess:
`zgrep -h '\[07/Mar/2017' /var/log/apache2/access.log.gz |  goaccess - --no-progress -q > /path/to/file.html`
If the hyphen is not used, I get the help output (goaccess without args)

**Terminal**
In bash terminal both variants work well

Thanks

**Comment by allinurl** [comment]
Thanks for reporting this. The hyphen is now required in v1.2 if used from the cron. This fixes #647.

**Comment by spy1986** [comment]
Ok, Thanks

**Comment by TCB13** [comment]
@allinurl is this supposed to happen even indirectly? I'm using cron to run a bash script that will run `goaccess` and I have this issue... See #711. Thank you!
