### ISSUE TITLE
Option to disable individual charts in HTML output

### ISSUE THREAD

**Issue by sleddoggy** [allinurl/goaccess#681]
Some data is (IMO) better presented in a table rather than a chart. For example, in the 'Requested Files (URLs)' panel (in an HTML report) the chart isn't really helpful. The table is.

It would be nice to have options to disable charts per panel.

As a first-time contributor here I'd like to say a big thanks for goaccess :)

**Comment by allinurl** [comment]
Thanks for suggesting this! I can certainly add it as a panel option. Though, I'm curious, is there a better option than the current bar/line chart to visually represent this specific panel's data?

**Comment by allinurl** [comment]
This has been implemented. The option will be listed under: **Panel Options** within each panel. The JSON structure looks like:

```
{
    "theme": "darkGray",
    "perPage": 7,
    "layout": "horizontal",
    "autoHideTables": true,
    "visitors": {
        "chart": true,
        "plot": {
            "chartType": "bar"
        }
    }
}
```

Feel free to build from [**development**](https://github.com/allinurl/goaccess#build-from-github-development). Otherwise, it will be pushed out in the upcoming version.
