### ISSUE TITLE
GoAccess 1.2 - GeoIP not working?

### ISSUE THREAD

**Issue by SeLLeRoNe** [allinurl/goaccess#682]
Hi everyone, 
I just downloaded the latest GoAccess stable version 1.2 but i noticed an error with GeoIP.

The error is:
/usr/local/goaccess/bin/goaccess: unrecognized option '--geoip-database'

So i tryed to re-configure it and i can see that --enable-geoip (which is specified in the help as valid command) result to don't work somehow.
In the build summary i've got:
Geolocation    : N/A

As a side not, GeoIP functionality was working fine in version 1.1.1

Any hint?

Thanks
Best regards
Andrea

**Comment by allinurl** [comment]
Please make sure to specify the GeoIP version, either `legacy` or `geoip2`, e.g.,

    $ ./configure --enable-utf8 --enable-geoip=legacy

**Comment by SeLLeRoNe** [comment]
Ok, thanks.
How would i recognize if i have GeoIP2?

**Comment by allinurl** [comment]
How did you install geoip in your machine? you probably want to look at the packages available in your distro and from there you can determine which package you need or have installed.

**Comment by SeLLeRoNe** [comment]
Oh, right.. sometimes I come up with very dumb question :D I'm using 1.5 so i guess legacy it's fine :)

Thanks
