### ISSUE TITLE
GoAccess as a system service

### ISSUE THREAD

**Issue by SeLLeRoNe** [allinurl/goaccess#684]
Hi,
not sure if can be usefull or not. I am not that expert on GIT to pretend to push some changes and possibly make a mess so i write it here.

I've just created the systemd service file to start GoAccess as a service (using the conf file as place where to put all the configurations).

Here it is:
```
[Unit]
Description=GoAccess Live Log Analyzer

[Service]
Type=simple
ExecStart=/usr/local/goaccess/bin/goaccess
ExecStop=/bin/kill -9 ${MAINPID}
PrivateTmp=false

[Install]
WantedBy=multi-user.target

```

The file should be stored in: /etc/systemd/system/goaccess.service
And should be loaded with:  systemctl daemon-reload

As you can see it is set for my installation which is in /usr/local/goaccess, feel free to change it to match the prefix provided in the "configure" step.

Using the Systemd don't require goaccess to be started with --daemonize (i've tryed, it result in error because systemd will provide a PID but GoAccess will create a new one, maybe sort of a bug).

Hope will be usefull to someone, to me it is, but it will be even more when i'll be able to parse multiple logs file with exlude list so i'll not have to worry about it anymore :D 

Best regards
Andrea

**Comment by allinurl** [comment]
Thanks for posting this. I'm sure it will be helpful to some folks :) I'll keep it open for some time just as a reference.

**Comment by SeLLeRoNe** [comment]
You're very welcome, the less i can do is contribute when i can ^^

Well i guess you can include in the code and set the path during the Make process without installing it during the make install, so it will stay in the source folder in something like /init for users who want to use it :)

Best regerds
Andrea

**Comment by myopenflixr** [comment]
Just came across this post. Thanks @SeLLeRoNe. This works so much better than creating a cron job to start GoAccess!

**Comment by Fieel** [comment]
Hello, any news on using a service to read multiple data from all logs?

**Comment by allinurl** [comment]
@Fieel can you expand a bit more on what you are trying to do? thanks

**Comment by Fieel** [comment]
I'd love GoAccess to read more logs, not just the latest ones, so I can see data from, say, last month.

Every time my Raspberry Pi webserver reboots the data shown resets

**Comment by allinurl** [comment]
@Fieel are you looking to have incremental stats? You can try using the on-disk storage instead of in-memory. Note that the current implementation is being replaced with something more robust.

**Comment by Fieel** [comment]
@allinurl yeah, i'd love to have incremental stats along with a realtime html page with data, is it possible with the on-disk storage?

So you're working on a more robust on-disk storage that will replace the current implementation? If so, i'm interested!

**Comment by allinurl** [comment]
@Fieel Yes, Please take a look at the [**configuration**](https://goaccess.io/man#configuration) options for on-disk storage. Yes, this is on the works, hoping the next release will have this done. Stay tuned though.

**Comment by michaelsmoody** [comment]
Just wanted to say thank you. This is helpful. I could have created my own, but copying/pasting was easier.

For those who might desire to use a custom config file, change this (modified the path, as my environment has it installed in /bin):

`ExecStart=/bin/goaccess`

To:

`ExecStart=/bin/goaccess -p /usr/local/etc/goaccess.conf`

**Comment by angun33** [comment]
Any idea how I do this but using ssh?
As in running this command in systemd:

```
ssh -t username@server 'tail -f -n +1 /var/log/nginx/access.log' | goaccess -o /path/to/report.html --real-time-html -
```

**Comment by allinurl** [comment]
@angun33 I'd use sshfs to mount the remote log and use systemd or `--daemonize` to run goaccess.
