### ISSUE TITLE
sort by country or city

### ISSUE THREAD

**Issue by stavros-liaskos** [allinurl/goaccess#687]
Currently I am able to view info about the country at "VISITOR HOSTNAMES AND IPS" table only.

Is there a configuration already to add a new table i.e "COUNTRIES" like in "GEO LOCATION" table but with countries?

Using:
 - Vagrant machine
- `./configure  --enable-geoip=mmdb` 
- with GeoLite2-Country.mmdb
- exporting to html.

BTW great tool!

**Comment by allinurl** [comment]
Currently the Geolocation panel should list countries that visited your server. The [**demo**](http://rt.goaccess.io/) displays this panel at the bottom of the page. Is that what you are looking for?

**Comment by stavros-liaskos** [comment]
I guess you are referring to "GEO LOCATION" table? If so, then no that's not what I want. Almost. I want the same but country specific. I am looking for something that will list the countries instead of continents. For example (in a poor copy paste format from html):

1	705,129 (58.18%)	101,762 (61.69%)	9.26 GiB (68.79%)	415.51 ms	3.39 d	1.23 h	UK
2	410,542 (33.87%)	33,606 (20.37%)	3.22 GiB (23.90%)	557.34 ms	2.65 d	5.05 m	Germany
3	51,287 (4.23%)	16,161 (9.80%)	361.81 MiB (2.63%)	507.70 ms	7.23 h	5.00 m	Greece
4	21,476 (1.77%)	8,792 (5.33%)	463.83 MiB (3.37%)	139.37 ms	49.89 m	1.65 m	Japan

Is there a configuration to do that? Or am I missing something already implemented?

**Comment by stavros-liaskos** [comment]
Never mind. Found it. The continent is clickable.. Nice!

**Comment by allinurl** [comment]
That's right. Pretty much any panel with the little caret ▶ on the first column is expandable.

**Comment by stavros-liaskos** [comment]
BTW I am using [Vimium](https://chrome.google.com/webstore/detail/vimium/dbepggeogbaibhgnhhndojpepiihcmeb?hl=en). This should generate a button on any link or clickable item. That's why I failed to find the carets at first.

**Comment by IzzySoft** [comment]
Got me confused as well. So let me add, though in nCurses there's no "click", same applies here – let's say it's "enter-able" :wink:
