### ISSUE TITLE
Setting up a custom Apache log format with GoAccess

### ISSUE THREAD

**Issue by evertonevaristo** [allinurl/goaccess#690]
Hello Guys, could you help-me setup my goaccessrc file?

My access log has the following sample:

`kepler007.xxxxx.com 10.55.23.99 - [13/Mar/2017:00:06:18 -0300] "GET /server-status?auto HTTP/1.1" 200 1769 438 "-" "-" "curl/7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.19.1 Basic ECC zlib/1.2.3 libidn/1.18 libssh2/1.4.2"`

+Apache log format

LogFormat "%v %h %u %t \"%r\" %>s %b %D \"%{X-Forwarded-For}i\" \"%{Referer}i\" \"%{User-Agent}i\""            common

**Comment by allinurl** [comment]
Are you using the `X-Forwarded-For` field? If you are, can you please post a few lines containing some IPs.

**Comment by evertonevaristo** [comment]
@allinurl in this log we don't have any line with IP's

```
kepler007.xxxxxxx.com 10.55.3.999 - [13/Mar/2017:09:51:17 -0300] "GET /server-status?auto HTTP/1.1" 200 1781 690 "-" "-" "curl/7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.19.1 Basic ECC zlib/1.2.3 libidn/1.18 libssh2/1.4.2"
kepler007.sodexhopass.com.br 10.55.0.204 - [13/Mar/2017:09:51:23 -0300] "GET /server-status?auto HTTP/1.1" 200 1781 322 "-" "-" "curl/7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.19.1 Basic ECC zlib/1.2.3 libidn/1.18 libssh2/1.4.2"
kepler007.xxxxxx.com 10.55.23.99 - [13/Mar/2017:09:51:29 -0300] "GET /server-status?auto HTTP/1.1" 200 1782 346 "-" "-" "curl/7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.19.1 Basic ECC zlib/1.2.3 libidn/1.18 libssh2/1.4.2"
kepler007.xxxxxxxxx.com 10.55.2.24 - [13/Mar/2017:09:51:35 -0300] "GET /server-status?auto HTTP/1.1" 200 1782 278 "-" "-" "curl/7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.19.1 Basic ECC zlib/1.2.3 libidn/1.18 libssh2/1.4.2"
```

**Comment by allinurl** [comment]
This should do it (no XFF):

    goaccess access.log --log-format='%v %h %^[%d:%t %^] "%r" %s %b %D "%R" "%u"' --date-format=%d/%b/%Y --time-format=%T

**Comment by evertonevaristo** [comment]
strange... @allinurl now i got the error:

`Unknown option `--'.`

**Comment by allinurl** [comment]
Which version are you using? Also, can you please post the command you are using and attach your config file. Thanks.

**Comment by evertonevaristo** [comment]
@allinurl 

command:
![image](https://cloud.githubusercontent.com/assets/3372284/23995352/f51e834e-0a27-11e7-804b-b4c1a6b813e6.png)

version:

![image](https://cloud.githubusercontent.com/assets/3372284/23995374/140d8476-0a28-11e7-8da5-4a8adc7eeb68.png)


config file:

![image](https://cloud.githubusercontent.com/assets/3372284/23995382/1fb2cd2c-0a28-11e7-968d-331854b0f181.png)

**Comment by allinurl** [comment]
You will need to update to the latest version for some of those log specifiers. More info in the [download page](https://goaccess.io/download).

**Comment by evertonevaristo** [comment]
now it's woking @allinurl .

I had installed the in my local machine (under Linux Subsystem for Windows), after the upgrade, i'm able to visualize the logs.

Thanks in advance!
