### ISSUE TITLE
make with error "use of undeclared identifier 'GEOIP_MEMORY_CACHE'" on MacOS

### ISSUE THREAD

**Issue by leezhm** [allinurl/goaccess#691]
I had install GeoIP-1.6.0 for source and then make goaccess source, got the following error infomation

`
src/options.c:666:17: error: use of undeclared identifier 'GEOIP_MEMORY_CACHE'
  conf.geo_db = GEOIP_MEMORY_CACHE;
                ^
src/options.c:682:21: error: use of undeclared identifier 'GEOIP_STANDARD'
      conf.geo_db = GEOIP_STANDARD;
`

and build env is 

`
MacOS 10.12.3 

> $ gcc -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin16.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
`

**Comment by allinurl** [comment]
It seems like OS X requires some additional steps, please take a look at [**this**](http://superuser.com/questions/303460/is-there-a-way-to-install-geoip-from-source-code-on-mac-os-x) post. Also this [**formula**](https://github.com/Homebrew/homebrew-core/blob/ba0aa68066a89c0654152aba22819736b06987af/Formula/geoip.rb) may help.

Also [**this question**](https://github.com/allinurl/goaccess/issues/642#issuecomment-277485512) may be related.

**Comment by leezhm** [comment]
@allinurl I install geoip from source and it worked well.

`
> $ geoiplookup 8.8.8.8                                                                  
GeoIP Country Edition: US, United States
GeoIP City Edition, Rev 1: US, CA, California, Mountain View, 94035, 37.386002, -122.083801, 807, 650
GeoIP ASNum Edition: AS15169 Google Inc.
`

`
> $ make install
Making install in libGeoIP
 .././install-sh -c -d '/usr/local/lib'
 /bin/sh ../libtool   --mode=install /usr/bin/install -c   libGeoIP.la '/usr/local/lib'
libtool: install: /usr/bin/install -c .libs/libGeoIP.1.dylib /usr/local/lib/libGeoIP.1.dylib
libtool: install: (cd /usr/local/lib && { ln -s -f libGeoIP.1.dylib libGeoIP.dylib || { rm -f libGeoIP.dylib && ln -s libGeoIP.1.dylib libGeoIP.dylib; }; })
libtool: install: /usr/bin/install -c .libs/libGeoIP.lai /usr/local/lib/libGeoIP.la
libtool: install: /usr/bin/install -c .libs/libGeoIP.a /usr/local/lib/libGeoIP.a
libtool: install: chmod 644 /usr/local/lib/libGeoIP.a
libtool: install: ranlib /usr/local/lib/libGeoIP.a
 .././install-sh -c -d '/usr/local/include'
 /usr/bin/install -c -m 644 GeoIP.h GeoIPCity.h '/usr/local/include'
Making install in apps
 .././install-sh -c -d '/usr/local/bin'
  /bin/sh ../libtool   --mode=install /usr/bin/install -c geoiplookup geoiplookup6 '/usr/local/bin'
libtool: install: /usr/bin/install -c .libs/geoiplookup /usr/local/bin/geoiplookup
libtool: install: /usr/bin/install -c .libs/geoiplookup6 /usr/local/bin/geoiplookup6
make[2]: Nothing to be done for `install-data-am'.
Making install in test
make[2]: Nothing to be done for `install-exec-am'.
make[2]: Nothing to be done for `install-data-am'.
Making install in man
make[2]: Nothing to be done for `install-exec-am'.
 .././install-sh -c -d '/usr/local/share/man/man1'
 /usr/bin/install -c -m 644 geoiplookup6.1 geoiplookup.1 '/usr/local/share/man/man1'
/Applications/Xcode.app/Contents/Developer/usr/bin/make  install-data-hook
cat geoiplookup.1 | sed s,DATADIR,/usr/local/share/GeoIP, > /usr/local/share/man/man1/geoiplookup.1
cat geoiplookup6.1 | sed s,DATADIR,/usr/local/share/GeoIP, > /usr/local/share/man/man1/geoiplookup6.1
make[2]: Nothing to be done for `install-exec-am'.
 ./install-sh -c -d '/usr/local/lib/pkgconfig/'
 /usr/bin/install -c -m 644 geoip.pc '/usr/local/lib/pkgconfig/'
`

**Comment by allinurl** [comment]
The issue looks like it's missing (or pointing to the right place) `LIBRARY_PATH` or `C_INCLUDE_PATH` so goaccess can't find GeoIP. I don't have a Mac at the moment to test this out, but please make sure they are properly set and pointing to the right location.

**Comment by allinurl** [comment]
Were you able to set this up?

**Comment by leezhm** [comment]
@allinurl No, I am busy to do something else, and will try it next week!

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
