### ISSUE TITLE
How to install GoAccess on-disk package from deb repo?

### ISSUE THREAD

**Issue by crsleeth** [allinurl/goaccess#692]
Hello I installed goaccess from the official Ubuntu repo:
```
$ echo "deb http://deb.goaccess.io/ $(lsb_release -cs) main" | sudo tee -a /etc/apt/sources.list.d/goaccess.list
$ wget -O - https://deb.goaccess.io/gnugpg.key | sudo apt-key add -
$ sudo apt-get update
$ sudo apt-get install goaccess
```
It has been working wonderfully so far. I am running it via auto updating HTML. However, I'd like the data logged to disk and I can't seem to get that working via the repo package. I first installed libtokyocabinet-dev. The second step seems to be to run: `./configure --enable-utf8 --enable-geoip --enable-tcb=btree` however I don't know where to find the "configure" binary this is referring to from the repo install. `find / -name "configure"` results in nothing. Am I supposed to enable these triggers via /etc/goaccess.conf? Is it documented anywhere how to do that?

**Comment by allinurl** [comment]
There are two options, one is to build it from source as specified [here](https://github.com/allinurl/goaccess#installation) and use  

    ./configure --enable-utf8 --enable-geoip=legacy --enable-tcb=btree

The other and easiest is to use the **deb repo** as you did above but use `goaccess-tcb` instead

```
$ echo "deb http://deb.goaccess.io/ $(lsb_release -cs) main" | sudo tee -a /etc/apt/sources.list.d/goaccess.list
$ wget -O - https://deb.goaccess.io/gnugpg.key | sudo apt-key add -
$ sudo apt-get update
$ sudo apt-get install goaccess-tcb
```

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
