### ISSUE TITLE
Should probe ~/.goaccessrc first

### ISSUE THREAD

**Issue by wavexx** [allinurl/goaccess#693]
By default, goaccess tries to read the global configuration file, and only load the user configuration file if that's missing. This is not how normal *nix utility behave. On main distributions, the global configuration file is generally provided as a guideline, meaning that ~/.goaccessrc will be never scanned.

It would be more user-friendly to switch the probing order to ~/.goaccessrc -> /syspath/goaccess.conf

**Comment by allinurl** [comment]
I agree. Thanks for submitting this PR.
