### ISSUE TITLE
Console not showing information that's in web interface - bandwidth, visitors, etc

### ISSUE THREAD

**Issue by tomwaldnz** [allinurl/goaccess#697]
I've just started running GoAccess on my AWS web server, Nginx as the web server.

The web interface shows information like bandwidth, cumulative time served, average time served, visitors, etc.
![web](https://cloud.githubusercontent.com/assets/8381145/24169873/ca4bfbcc-0ee3-11e7-847a-1b780a76d3e4.png)

The console version however leaves those fields blank.
![console](https://cloud.githubusercontent.com/assets/8381145/24169876/ce0b54ce-0ee3-11e7-8b11-2c7b9f0363d1.png)

Does anyone know why this is, or how to fix it?

**Comment by allinurl** [comment]
It looks like you are using putty, you probably want to change the color setting in putty to display bold text (dark columns in goaccess). 

Select `Change Settings` > `Window` > `Colours` and make sure `The colour` is checked under "Indicate bolded text by changing".

**Comment by tomwaldnz** [comment]
Thanks, that worked :) So easy when that's point out.
