### ISSUE TITLE
Custom log format and unique visitor/OS/Browser data

### ISSUE THREAD

**Issue by nostalgia4891** [allinurl/goaccess#698]
hi all, 

i need exact Unique Visitors and OS/Browser info.

if i set log-format 1, dashboard print visitor(O, exact),    OS/Browser info(O, unknown).

    log-format 1 : log-format %h %l %u %^[$d:%t:%^] $D \"%r\" %s %b \"%R\" \"%{User-Agent}i\"

if i set log-format 2, dashboard print visitor(O, inexact), OS/Browser info(O)

    log-format 2 : log-format %h %^ %^[$d:%t:%^] $D \"%r\" %s %b \"%R\" \"%u\"

This is my weblog 

    12.34.56.789 - - [22/Mar/2017:09:10:06 +09:00] 407 "GET / HTTP/1.1" 200 97 "-" Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.1;..........
    12.34.56.789 - - [22/Mar/2017:09:10:06 +09:00] 74276 "GET /abcd/loginview.web  HTTP/1.1" 200 208767 "http://goaccess.co.kr/" Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.1;..........
    12.34.56.789 - - [22/Mar/2017:09:10:06 +09:00] 14965 "GET /abcd/resource/css/test.css  HTTP/1.1" 200 16823 "http://goaccess.co.kr/abcd/loginview.web" Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.1;..........

**Comment by allinurl** [comment]
For the few lines you posted above, this should work:

    log-format %h %^[%d:%t %^] %D "%r" %s %b "%R" "%u"
    date-format %d/%b/%Y
    time-format %T

or 

    goaccess access.log --log-format='%h %^[%d:%t %^] %D "%r" %s %b "%R" "%u"' --date-format=%d/%b/%Y --time-format=%T

**Comment by nostalgia4891** [comment]
Thank you. 
but some (max)visitor count - VISITOR HOSTNAMES AND IPS - show 2.
is that possible?

**Comment by allinurl** [comment]
I'm not sure I follow your questions. What would you like to show? and what's showing up now?

**Comment by nostalgia4891** [comment]
i had check ip and browser, os info in my log file.
then..
specific ip(12.34.56.78) use 2 browser(MSIE 7.0, MISE 8.0)
so.. (max)visitor count seems print number '2'
Is that right?

**Comment by allinurl** [comment]
That's sounds right. 1 IP, same date and 2 different UAs = 2 unique users.

**Comment by nostalgia4891** [comment]
thank you for your reply. 
thank you for understanding my bad english.
have a nice day ^^

**Comment by allinurl** [comment]
no problem at all :) glad that answered your question.
