### ISSUE TITLE
Unable to configure GoAccess with --enable-geoip=geoip2

### ISSUE THREAD

**Issue by matrix0610** [allinurl/goaccess#699]
Hi There;
I got an issue with GeoIP2, after install GeoIP2 from this link : https://github.com/maxmind/libmaxminddb
everything config in default
I built with params: 
`./configure --prefix=/etc/goaccess --enable-utf8 --enable-geoip=geoip2 --enable-tcb=btree --with-openssl --with-getline`

config log:
```
Your build configuration:

  Prefix         : /etc/goaccess
  Package        : goaccess
  Version        : 1.2
  Dynamic buffer : yes
  Geolocation    : N/A
  Storage method : On-disk B+ Tree Database (Tokyo Cabinet)
  TLS/SSL        : yes
  Compiler flags :  -pthread
  Linker flags   : -lnsl -ltokyocabinet -lncursesw -lcrypto -lssl -lpthread   -lz -lbz2 -ltokyocabinet -lrt -lc
  Bugs           : goaccess@prosoftcorp.com
```

In my config file : 
`geoip-database /usr/local/share/GeoIP/GeoLite2-City.mmdb`
But when i run for my test, i got an error message:

> goaccess: unrecognized option '--geoip-database'

i've read the manual but can't figure out this issue.Please help me!

**Comment by allinurl** [comment]
My bad, the docs had `geoip2` instead of `mmdb`. I'll correct this. Please try to configure goaccess as:

    ./configure --prefix=/etc/goaccess --enable-utf8 --enable-geoip=mmdb --enable-tcb=btree --with-openssl --with-getline

Thanks for reporting this!

**Comment by matrix0610** [comment]
Yeah! It works now.
Thanks
