### ISSUE TITLE
not able to use goaccess with nginx main log format

### ISSUE THREAD

**Issue by nishaadvirkud** [allinurl/goaccess#70]
Dear Sir,

I am not able to use goaccess (0.7) with nginx "main" log format. Please suggest.
Please find below log format :+1: 

1.2.3.4 - - [30/Dec/2013:04:02:14 +0530]  "POST /abc/url/of/test.jsp HTTP/1.1" 404 886 ["192.168.1.177:1800" "0.009" "0.009"]"http://www.abc.com/abc/cl_2-c_3919-pr_1496211-i_1915638-b_57/vy408019_bml.html" "Mozilla/5.0 (iPad; CPU OS 7_0_4 like Mac OS X) AppleWebKit/537.51.1 (KHTML, like Gecko) Version/7.0 Mobile/11B554a Safari/9537.53" "-"

Please suggest.

Thanks and regards,
Nishad Virkud.

**Comment by ssbarnea** [comment]
Please reopen this, goaccess should be able to parse nginx access logs without having to configure anything on them. nginx is one of the most used web servers and it doesn't make any sense not to be able to detect its format.

**Comment by allinurl** [comment]
@ssbarnea It does parse the default Nginx log format (NCSA extended/combined log format).  Either by choosing this log option from the configuration dialog `-c` or by adding it to the config file.

**Comment by nishaadvirkud** [comment]
Thanks for your response friends.
