### ISSUE TITLE
Add support for multiple languages

### ISSUE THREAD

**Issue by NengWan** [allinurl/goaccess#701]
the web interface is so cool !   can I change the display language?

**Comment by allinurl** [comment]
Currently there are no other languages available. However, this is coming! It will probably need to be implemented using [`gettext`](https://www.gnu.org/software/gettext/)

There are a couple of pull requests ([**French**](https://github.com/allinurl/goaccess/pull/453) and [**Chinese**](https://github.com/allinurl/goaccess/pull/457)) that I need to merge and add gettext support to them.

**Comment by allinurl** [comment]
This has been implemented. As of this post, French and Spanish have been added. If you would like to collaborate in adding a different language, please see take a look at [**this post**](https://github.com/allinurl/goaccess/issues/858#issuecomment-320257517) and I'll be happy to merge it for the upcoming version.

**Comment by tellustheguru** [comment]
I have translates GoAccess to Swedish, how do I send it to you?

**Comment by allinurl** [comment]
@tellustheguru Thanks for offering to translate it to Swedish. Please submit a PR so I can merge it here. Here you can find the [steps](https://github.com/allinurl/goaccess/issues/858#issuecomment-320257517) to do the translation if needed.

Let me know if you have any questions. Thanks!
