### ISSUE TITLE
Loadbalancer Custom LogFormat 1.1.1 vs 1.2

### ISSUE THREAD

**Issue by jrharalson** [allinurl/goaccess#702]
In testing an upgrade from 1.1.2 to 1.2 I'm running into an error with the Log Format

> Error: 
> 
> Parsed 10 lines producing the following errors:
> 
> IPv4/6 is required.
> IPv4/6 is required.
> IPv4/6 is required.
> IPv4/6 is required.
> IPv4/6 is required.
> IPv4/6 is required.
> IPv4/6 is required.
> IPv4/6 is required.
> IPv4/6 is required.
> IPv4/6 is required.
> 
> Format Errors - Verify your log/date/time format

Test Cases:  5 different logs examples (based on an Apache Web Server, but custom log format)

Just by switching between "goaccess install directories" 
     1.1.2 --- working for months, same config, same test logs today (snippet below) SUCCESS
     1.2 -- installed today, same config setting, same test logs today (snippet below) FAILS with error listed above 

Config settings: 
    time-format %Y-%m-%d-%H.%M.%S
    date-format %Y-%m-%d-%H.%M.%S
    log-format %h,%x,%s,%b,%D,%^,"%m","%r","%q","%R","%u","%^","%^","%^","%^"

Tried other settings: 
    time-format %H.%M.%S
    date-format %Y-%m-%d
    log-format %h,%d-%t,%s,%b,%D,%^,"%m","%r","%q","%R","%u","%^","%^","%^","%^"

Sample log entry: 

    5.5.5.5 = load balancer IP valid
    6.6.6.6 = X-Forwarded-For, but noticed I've skipped this in the config for now

```
5.5.5.5,2017-03-12-00.00.29,301,231,182,-,"GET","GET / HTTP/1.1","","-","Mozilla/5.0 (Windows; U; Windows NT 5.1; zh-CN; rv:1.9b4) Gecko/2008030317 Firefox/3.0b4","6.6.6.6","-","-","-"
5.5.5.5,2017-03-12-00.00.29,301,231,1049,-,"GET","GET / HTTP/1.1","","-","Mozilla/5.0 (Windows; U; Windows NT 5.1; zh-CN; rv:1.9b4) Gecko/2008030317 Firefox/3.0b4","6.6.6.6","-","-","-"
5.5.5.5,2017-03-12-00.00.33,200,3974,1605,-,"GET","GET /sureroute-test-object.html HTTP/1.1","","-","-","6.6.6.6, 6.6.6.6","-","-","-"
```

**Comment by allinurl** [comment]
This should do it (v1.2):

    goaccess access.log --log-format='%^,%x,%s,%b,%D,%^,"%^","%r","%^","%R","%u", ~h{, "} %^' --date-format=%Y-%m-%d-%H.%M.%S --time-format=%Y-%m-%d-%H.%M.%S

**Comment by jrharalson** [comment]
Thanks for the reply. 

Doesn't seem to change the error results unfortunately. I've tried a few variations as well 

log-format %^,%x,%s,%b,%D,%^,"%^","%m","%r","%r","%q","%R","%u",~h{, "}"%^","%^","%^"

   "%u",~h{, "}"%^",
   "%u","~h{, "}"%^",
   "%u",~h{, },"%^",

I'm actually fine with skipping the XForwardedFor processing in favor of the 1st IP slot 5.5.5.5 for now.  Though I can't see to get that working either. 

Thanks again for your time

**Comment by allinurl** [comment]
The following works on v1.2 for the three lines you posted above.

    goaccess access.log --log-format='%h,%x,%s,%b,%D,%^,"%^","%r","%^","%R","%u"%^' --date-format=%Y-%m-%d-%H.%M.%S --time-format=%Y-%m-%d-%H.%M.%S

![2017-03-24-131712_649x236_scrot](https://cloud.githubusercontent.com/assets/5005367/24307842/b9ddf626-1093-11e7-9283-6ab90dfff9d5.png)

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
