### ISSUE TITLE
goaccess v1.2 does not work at all from a crontab

### ISSUE THREAD

**Issue by foxmask** [allinurl/goaccess#703]
Hi,

since v1.2 my crontab dont work at all .

The log of the crontab display the help of goaccess instead of dealing with my log file

here is my crontab 

    0 1 	* * *  root /bin/zcat /var/log/nginx/service.log.*.gz |/usr/bin/goaccess -g -a -o /path/to/report.html

when I run that by hand it's working fine.

**Comment by allinurl** [comment]
Please make sure to use a single dash `-`, e.g.,

    /bin/zcat /var/log/nginx/service.log.*.gz |/usr/bin/goaccess -g -a -o /path/to/report.html -

**Comment by foxmask** [comment]
Yes ! Thanks :)
