### ISSUE TITLE
Releases shall contain amd64 binaries at least for Dockerfile

### ISSUE THREAD

**Issue by julianxhokaxhiu** [allinurl/goaccess#705]
In order to make sure that the Dockerfile can actually be made based on your release lifecycle, I need that you actually build up the binary and attach them to the releases ( either also as .tar.gz or direct binaries ) so I could update then the Dockerfile.

Ping me back when you started to do that. For eg. see https://github.com/bcicen/ctop/releases

**Comment by allinurl** [comment]
Can it be directly from goaccess' [download page](http://tar.goaccess.io/goaccess-1.2.tar.gz)? Right now you can find the tar.gz from  github's [releases](https://github.com/allinurl/goaccess/releases/tag/v1.2) page, but I'd prefer if it's directly from goaccess' site.

**Comment by julianxhokaxhiu** [comment]
Sorry, I forgot about it :) I'll try to take a look later then. Thank you!

**Comment by julianxhokaxhiu** [comment]
@allinurl I had a chance to see your download page but you're just giving away the source code to be built, where I am talking about an *already built* binary. This is neither available on your website ( versioned if possible ), neither from the releases page here.

Any idea when one of the two will be available?

**Comment by allinurl** [comment]
@julianxhokaxhiu, thanks for looking into this. I'm curious why #[**311**](https://github.com/allinurl/goaccess/issues/311#issuecomment-289244333) used v1.1.1, it seems Alpine has v1.2 already, shouldn't that solve the issue in 311?

**Comment by julianxhokaxhiu** [comment]
It may be that the docker was built before Alpine having the package updated.

Check the docker logs on Docker hub, otherwise just retrigger another build, ai'm pretty sure it will be solved automatically :)

**Comment by julianxhokaxhiu** [comment]
Checking at the Docker status page, of your latest build, it seems that Alpine is still loading 1.1.1 version. I highly suggest to start releasing binaries ( at least amd64 ) in order to include them in your Docker, so you can align releases with Docker instances.

**Comment by allinurl** [comment]
I can certainly start releasing binaries, but before doing (and to avoid having an extra layer of stuff to maintain), I wondering if it's possible to use the [official goaccess' repo](https://github.com/allinurl/goaccess#official-goaccess-debian--ubuntu-repository) and extract the binaries from there? Not sure, but [logstash](https://github.com/docker-library/logstash/blob/bad127e3f5912e5fdbff825e4ac832b725bd0c8d/5/Dockerfile#L35) appears to be using their own repo?

**Comment by julianxhokaxhiu** [comment]
Well I have to be honest: we could use even the source to run it like in interpretation way, but I think to make the docker smaller we could also go for just including the binary without even using any base go docker image.

We are talking about a couple of MB ( or even less ) vs about 20MB between toolchain, basic distro packages, etc. which in the end will not also provide a fully performance enhanced binary.

Also, the interpretation way should just be used for development and not production. You source package delivered through the website is just the source code, not the binary output of it.

How much overhead would this add to you? We can also think about using travis to do this for you, and letting him trigger the docker hub repository for doing the build on top of the binary.

Really long shot, but it's fully automated.

**Comment by allinurl** [comment]
Thanks. I'll add the binaries over the weekend. Would it work to have them under https://goaccess.io?

**Comment by julianxhokaxhiu** [comment]
Sure, would be even better! Ping me when it's done :)

**Comment by allinurl** [comment]
Binaries can be found [**here**](https://bin.goaccess.io/). Let me know if that works. Thanks!

**Comment by julianxhokaxhiu** [comment]
Is the url still working? I've tried to access it now, and it seems it doesn't work.

**Comment by allinurl** [comment]
It's no longer active. Since Alpine now uses v1.2 (edge), then I don't think we need the binaries anymore, but thanks for all the work though :)

**Comment by julianxhokaxhiu** [comment]
Fine then :D If you think we need to improve the Docker then, feel free to reopen this issue :)

Best regards!
