### ISSUE TITLE
Display warning if access log is empty

### ISSUE THREAD

**Issue by sentabi** [allinurl/goaccess#706]
I setup goaccess but somehow i forgot to add access_log on my nginx server block. When run
```
goaccess /var/log/nginx/access.log
# OR 
goaccess -f /var/log/nginx/access.log
```
didn't complaint access.log file is empty. goaccess just quit after execute these command.
```
goaccess /var/log/nginx/access.log -o report.html
```
above command just echo  `/var/log/nginx/access.log` without any warning.

I'd love if `goaccess` give warning if log is empty, so we know whats wrong :)

**Comment by allinurl** [comment]
If your log is empty, goaccess used to error out, now it will output an empty report. This change was part of issue #471.
