### ISSUE TITLE
Homebrew unable to open GeoIP2 database (v1.2)

### ISSUE THREAD

**Issue by chouti** [allinurl/goaccess#707]
I've installed goaccess via homebrew by using

`brew install goaccess --with-geoip`

when try to parse log files with geoip2 database, error message prompt:

```
Fatal error has occurred
Error occured at: src/geoip2.c - init_geoip -92
Unable to open GeoIP2 database: ~/GeoIP/GeoLiteCity.dat
```
Do I need to change my build configure or change the geoip database?

**Comment by allinurl** [comment]
It looks like the Homebrew Formula [**upstream**](https://github.com/Homebrew/homebrew-core/blob/a5c40252316eb37f52cd68768040c3c33897721a/Formula/goaccess.rb) is not specifying the GeoIP version. It has to be either `--enable-geoip=legacy` or `--enable-geoip=mmdb` (GeoIP2).

**Comment by chouti** [comment]
I've uninstall goaccess from homebrew, and clone from git repository.

this time I've configured as --enable-geoip=mmdb

After installed, I've tried follow commands

`goaccess PATH-TO-MY-LOGFILE --geoip-database PATH-TO-GEOIP-DATABASE`

still, i got:

```
Fatal error occurred
Error occured at: src/geoip2.c - init_geoip - 92
Unable to open GeoIP2 database: PATH-TO-GEOIP-DATABASE
```

**Comment by allinurl** [comment]
Please make sure you are using the right GeoIP2 databases found [**here**](http://dev.maxmind.com/geoip/geoip2/geolite2/) and that you have proper permissions on the files.

**Comment by chouti** [comment]
Well, my bad.

At first, I've using GeoLiteCity.dat which listed in the config file.

After I switched to using GeoLite2-City.mmdb which download from maxmind.com

**Comment by allinurl** [comment]
I"ll update the docs and config file. Thanks for the heads up!
