### ISSUE TITLE
How can I get notified after large amount of file parsed when using daemonize

### ISSUE THREAD

**Issue by chouti** [allinurl/goaccess#709]
Currently I have about 30GB log files in total, and divided into 3 different instances. I've use:

`goaccess -f /product1/log/* -o /var/www/html/product1.html --real-time-html --ws-url=192.168.0.1 --port=7890 --dp-path=/tmp/product1/ --keep-db-files --load-from-disk --daemonize --fifo-in=/tmp/product1.in --fifo-out=/tmp/product1.out`

`goaccess -f /product2/log/* -o /var/www/html/product2.html --real-time-html --ws-url=192.168.0.1 --port=7891 --dp-path=/tmp/product2/ --keep-db-files --load-from-disk --daemonize --fifo-in=/tmp/product2.in --fifo-out=/tmp/product2.out`

`goaccess -f /product3/log/* -o /var/www/html/product1.html --real-time-html --ws-url=192.168.0.1 --port=7892 --dp-path=/tmp/product3/ --keep-db-files --load-from-disk --daemonize --fifo-in=/tmp/product3.in --fifo-out=/tmp/product3.out`

In my understanding it will look a long time to parse log files since I didn't ignore any panel in my config file. But my question is how can I got notified when everything was ready?

When I look into `http://192.168.0.1:7890/product1.html` browser always return me a blank page(not 404).

**Comment by allinurl** [comment]
The only way right now is to use a tool like `top` or the like and see if goaccess is utilizing your CPU. Once it has finished, you will notice that CPU utilization for that process goes down substantially.

As far as notifications, I could add some sort of alert option, e.g., `--on-load=email:some@domain.com`, but then I assume users may want a bunch of other alerts aside from on-load. I'm not sure yet how goaccess should handle and trigger these alerts. Any thoughts?

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
