### ISSUE TITLE
Can I have the opportunity to filter already parsed html report with dates. 

### ISSUE THREAD

**Issue by chouti** [allinurl/goaccess#710]
Hello, it's me again.
I'd like to ask if we have the opportunity to filter real time html report with `start_date` and `end_date` arguments.

Since real time html report got more and more information day by day, it would be useful if we can select specific time period and look deep into it.

**Comment by allinurl** [comment]
#117 will add some nice filtering options. Though, it's still in the works.

For now you should be able to so some pre-processing, with tools like sed, awk, etc. Please take a look at [**this section**](https://github.com/allinurl/goaccess#working-with-dates).

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
