### ISSUE TITLE
Question mulitple log sources

### ISSUE THREAD

**Issue by LordNykon** [allinurl/goaccess#715]
Is there a way to have goaccess centralized so that it can read simultaneously from multiple log sources on different servers? Or if I have my logs forwarded to a single logstore can I ignore certain sources?

Thanks!

**Comment by allinurl** [comment]
Forwarding to a single logstore and ignoring entries by vhost should do it. grep/sed/awk would do the ignoring part.

**Comment by LordNykon** [comment]
Syntactically how would that look? 

goaccess -f "/var/log/messages-test | grep '10.100.10.1'"

**Comment by allinurl** [comment]
# tail -f -n +0 access.log | grep --line-buffered 'vhost_to_ignore' | goaccess --log-format=COMBINED -

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
