### ISSUE TITLE
FR: Ability to use goaccess over https

### ISSUE THREAD

**Issue by goldencut** [allinurl/goaccess#719]
It seems goaccess (--real-time-html) can't be used currently over https (WebSocket connection to 'wss://localhost:7890/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED).   As almost all production systems use https (unconditional redirect) by default then maybe a way could be devised to provide https support for goaccess?

BR,
G.

**Comment by allinurl** [comment]
GoAccess does provide wss support. Did you configure goaccess with `--with-openssl`? How are you running goaccess?

**Comment by goldencut** [comment]
Hi, I installed latest from goaccess.io to the server I wanted to monitor and ran `goaccess -f /var/log/apache2/public_access.log -o /var/www/goa/index.html --real-time-html --ssl-cert=/etc/letsencrypt/live/mydomain.com/cert.pem --ssl-key=/etc/letsencrypt/live/mydomain.com/privkey.pem` or `goaccess -f /var/log/apache2/public_access.log -o /var/www/goa/index.html --real-time-html --ws-url=localhost`. I got the page up but it doesn't update. I have Apache rewrite so everything switches to https immediately. Googling the problem took me to http://stackoverflow.com/questions/38710438/ which claims that Goaccess doesn't work over https. If it works I would really like to know how to do it.

**Comment by allinurl** [comment]
Please try using `wss://` as part of your `--ws-url` and make sure you pass the right host (the server that's running goaccess and probably not the machine containing the browser to open the report, i.e., localhost), e.g.,:

    goaccess /var/log/apache2/public_access.log -o /var/www/goa/index.html --real-time-html --ssl-cert=/etc/letsencrypt/live/mydomain.com/cert.pem --ssl-key=/etc/letsencrypt/live/mydomain.com/privkey.pem --ws-url=wss://your_server_host:7890

**Comment by goldencut** [comment]
Do I understand correctly that every client that views Goaccess page from myserver.com needs to be able to access myserver.com:7890 also, so besides 443 I have to open port 7890 for everyone (who needs to access Goaccess page) in my firewall?  Ie client opens browser to myserver.com:443/goa and that page tries to actually connect to myserver.com:7890 to pull live data? Isn't that insecure to have 7890 open for the world or make iptables rules for everyone who needs to view Goaccess page?

**Comment by allinurl** [comment]
It is correct that every client that wants to see your goaccess report needs to establish a connection to the WebSocket server running on myserver.com through whatever port you choose to use (defaults to 7890). So yes, you need to set a rule in your firewall (iptables) to open that port. 

The HTML document (report) is served using your webserver through port 443, but the WebSocket Secure connection (wss) will be served on port 7890.

I believe it's possible to do the TLS layer through a reverse proxy to circumvent goaccess wss connection, haven't tried this myself though.

**Comment by allinurl** [comment]
Were you able to run the report over https & wss?

**Comment by goldencut** [comment]
I'm trying to run G on another server now and 'tail -f' over ssh on the server I want to monitor (ssh root@myserver.tld 'cat /var/log/apache2/public_access.log' | goaccess -a -). Is that possible?

**Comment by allinurl** [comment]
Certainly doable, preferably you are using your ssh keys to access the remote server. e.g.,

    ssh -t user@host 'tail -f /var/log/apache2/access.log' | goaccess --log-format=VCOMBINED

**Comment by allinurl** [comment]
Closing this. Feel free to comment or reopen it if needed.

**Comment by goldencut** [comment]
Not sure if it's working or not. I ssh to my server and run: `nohup sh -c "ssh -t -troot@myotherserver.tld tail -F /var/log/apache2/public_access.log | goaccess" &` (I use -t -t since sometimes nohup.out complains about not allocating pseudo-terminal; -F since I have logrotate on that other server) but it doesn't look like goaccess would stay active. When I kill the process and re-run goaccess the homepage gets sometimes (often I kill the old ssh-tail-goaccess process, start a new one and nothing appears - no data and status is "UNDEFINED — UNDEFINED") refreshed  with new data but after that no new data seems to appear. What I might be doing wrong?

**Comment by allinurl** [comment]
I wouldn't recommend running goaccess on your local machine if you plan to keep it in the background i.e., `&`, you are better off mounting the logs on your local machine using something like sshfs and then parsing it with goaccess or even better having a centralize log server, e.g., rsyslog. 

It sounds like the issue you are having is keeping the connection opened or even establishing one to the remote server. GoAccess simply reads whatever is in the pipe. I'd try checking if you are actually getting data by removing the pipe and goaccess from  the command line and keeping only tail.

**Comment by goldencut** [comment]
Just running the ssh and tailing works. But piping it to goaccess doesn't seem to work, netcating to server 7890 connects (gives just black). Can't use sshfs because I can't restart server at the moment (after installing sshfs+fuse). That remote server is already forwarding rsyslog to this server, including apache log, but goaccess can't parse the log file (token doesn't match...) since it's not pure apache log but a mixed log (all that goes to syslog on that remote server). Don't know how I can parse out the apache log entries from the composite log and write it to a separate file for goaccess to use.

**Comment by allinurl** [comment]
I'd start with the basics of running goaccess against a sample log in your local machine and make sure you can access from the outside world with live stats. If that works and if you still want to run it on a different machine then you should be able to tail the log and pipe the output to goaccess.  You can try using a single dash to let goaccess know it should read from the pipe.

As I said before, if tail is constantly streaming data, then goaccess should just take that data and process it. I'm running a few instances where data is being piped for months and haven't had any bumps. Check if data is not being buffered from the remote server.

You can certainly try parsing the syslog with goaccess, but it's likely you will get a bunch of invalid requests (not related to apache). e.g.,

    Apr 25 19:00:29 servername apache: test.domain.com:80 192.168.181.111 - - [25/Apr/2017:19:00:29 +0500] "GET /file.xz HTTP/1.1" 200 406 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0" 400

and run it as

    goaccess syslog --log-format='%^:%^:%^: %v:%^ %h %^[%d:%t %^] "%r" %s %b "%R" "%u" %D' --date-format=%d/%b/%Y --time-format=%T --num-tests=0

**Comment by goldencut** [comment]
Thanks for all your help. For some reason I can't get it to work.  It might have something to do with the servers I'm working with. As I've run out of time currently I'll leave it at that. But as soon I have time I'll try again and might start asking silly questions again here... :P

**Comment by allinurl** [comment]
No worries. Feel free to reopen it anytime.
