### ISSUE TITLE
Token 'ns528252.ip-158-69-241.net' doesn't match specifier '%h'

### ISSUE THREAD

**Issue by HiTechKoke** [allinurl/goaccess#720]
I've been running goaccess successfully for a while but once in a while I get this error and it bails out:

Token 'ns528252.ip-158-69-241.net' doesn't match specifier '%h'

I have to get rid of these log file lines in order for it to parse the larger program... those log files start with..

ns528252.ip-158-69-241.net - - [31/Mar/2017:06:06:41 -0600] "GET .........

The goals command line I am running is:

goaccess -f $kpaccesslog -a -o $monthly_html_access_file

In looking at the formatting of these lines that break it they seem to be of the same style and layout of 99% of the others so I am not sure how to debug the issue.  Love this program and what it does and have been running it fine for a few months previous.

**Comment by allinurl** [comment]
GoAccess requires a valid IPv4/6 for `%h`. It seems like you are resolving the IP to a host and then parsing the log with GoAccess. If you are doing this, you will need to preserve the IP for GoAccess to work as expected. 

Feel free to post a few samples lines from your access log and so I can take a look at this.

**Comment by HiTechKoke** [comment]
Tks for the quick reply.  Actually this is the Raw access file from the ISP, Westhost,  and they started doing this conversion in their log files a few months ago and that conversion is growing to very few raw IPs are being put in the file.   This is causing me all kinds of fits in other places.  Here's some samples lines...

`ns528252.ip-158-69-241.net - - [31/Mar/2017:06:06:49 -0600] "GET /phpBB3/profile.php?mode=editprofile HTTP/1.1" 404 599 "http://www.kokaneepower.org/" "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko"
ns528252.ip-158-69-241.net - - [31/Mar/2017:06:06:49 -0600] "GET /phpBB3/memberlist.php?mode=viewprofile&u= HTTP/1.1" 200 8041 "http://www.kokaneepower.org/phpBB3/ucp.php?mode=register&agreed=true&iscanyesno=yeswecan&step=2&coppa=0" "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko"
ns528252.ip-158-69-241.net - - [31/Mar/2017:06:06:56 -0600] "POST /phpBB3/ucp.php?mode=register&coppa=0 HTTP/1.1" 200 14914 "http://www.kokaneepower.org/phpBB3/ucp.php?mode=register&agreed=true&iscanyesno=yeswecan&step=2&coppa=0" "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko"
crawl-66-249-66-47.googlebot.com - - [31/Mar/2017:06:07:18 -0600] "GET /phpBB3/viewtopic.php?f=1&t=513 HTTP/1.1" 200 23760 "-" "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"
msnbot-157-55-39-111.search.msn.com - - [31/Mar/2017:06:08:33 -0600] "GET /derbiesdet.php?code=20150718 HTTP/1.1" 200 18993 "-" "Mozilla/5.0 (iPhone; CPU iPhone OS 7_0 like Mac OS X) AppleWebKit/537.51.1 (KHTML, like Gecko) Version/7.0 Mobile/11A465 Safari/9537.53 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)"
185.25.32.38 - - [31/Mar/2017:06:11:41 -0600] "GET /robots.txt HTTP/1.1" 403 - "-" "robots"
185.25.32.38 - - [31/Mar/2017:06:11:44 -0600] "GET /phpBB3/viewforum.php?f=10 HTTP/1.1" 403 - "-" "magpie-crawler/1.1 (U; Linux amd64; en-GB; +http://www.brandwatch.net)"
crawl-66-249-66-244.googlebot.com - - [31/Mar/2017:06:13:54 -0600] "GET / HTTP/1.1" 200 38533 "-" "Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.96 Mobile Safari/537.36 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"
crawl-66-249-66-47.googlebot.com - - [31/Mar/2017:06:14:04 -0600] "GET /phpBB3/viewtopic.php?f=1&t=635 HTTP/1.1" 200 9861 "-" "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"
crawl-66-249-66-53.googlebot.com - - [31/Mar/2017:06:21:32 -0600] "GET /phpBB3/viewtopic.php?f=1&t=404 HTTP/1.1" 200 22106 "-" "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"
crawl-66-249-66-53.googlebot.com - - [31/Mar/2017:06:28:04 -0600] "GET /phpBB3/viewtopic.php?f=1&t=759 HTTP/1.1" 200 12074 "-" "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"
108-252-120-131.lightspeed.mtryca.sbcglobal.net - - [31/Mar/2017:06:29:31 -0600] "GET / HTTP/1.1" 200 38533 "-" "Mozilla/5.0 (iPhone; CPU iPhone OS 9_3_2 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13F69 Safari/601.1"
108-252-120-131.lightspeed.mtryca.sbcglobal.net - - [31/Mar/2017:06:29:32 -0600] "GET /include/css3menu1/style.css HTTP/1.1" 200 3013 "http://www.kokaneepower.org/" "Mozilla/5.0 (iPhone; CPU iPhone OS 9_3_2 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13F69 Safari/601.1"
ns528252.ip-158-69-241.net - - [31/Mar/2017:06:06:49 -0600] "GET /phpBB3/profile.php?mode=editprofile HTTP/1.1" 404 599 "http://www.kokaneepower.org/" "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko"
ns528252.ip-158-69-241.net - - [31/Mar/2017:06:06:49 -0600] "GET /phpBB3/memberlist.php?mode=viewprofile&u= HTTP/1.1" 200 8041 "http://www.kokaneepower.org/phpBB3/ucp.php?mode=register&agreed=true&iscanyesno=yeswecan&step=2&coppa=0" "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko"
ns528252.ip-158-69-241.net - - [31/Mar/2017:06:06:56 -0600] "POST /phpBB3/ucp.php?mode=register&coppa=0 HTTP/1.1" 200 14914 "http://www.kokaneepower.org/phpBB3/ucp.php?mode=register&agreed=true&iscanyesno=yeswecan&step=2&coppa=0" "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko"
crawl-66-249-66-47.googlebot.com - - [31/Mar/2017:06:07:18 -0600] "GET /phpBB3/viewtopic.php?f=1&t=513 HTTP/1.1" 200 23760 "-" "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"
msnbot-157-55-39-111.search.msn.com - - [31/Mar/2017:06:08:33 -0600] "GET /derbiesdet.php?code=20150718 HTTP/1.1" 200 18993 "-" "Mozilla/5.0 (iPhone; CPU iPhone OS 7_0 like Mac OS X) AppleWebKit/537.51.1 (KHTML, like Gecko) Version/7.0 Mobile/11A465 Safari/9537.53 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)"
185.25.32.38 - - [31/Mar/2017:06:11:41 -0600] "GET /robots.txt HTTP/1.1" 403 - "-" "robots"
185.25.32.38 - - [31/Mar/2017:06:11:44 -0600] "GET /phpBB3/viewforum.php?f=10 HTTP/1.1" 403 - "-" "magpie-crawler/1.1 (U; Linux amd64; en-GB; +http://www.brandwatch.net)"
crawl-66-249-66-244.googlebot.com - - [31/Mar/2017:06:13:54 -0600] "GET / HTTP/1.1" 200 38533 "-" "Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.96 Mobile Safari/537.36 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"
crawl-66-249-66-47.googlebot.com - - [31/Mar/2017:06:14:04 -0600] "GET /phpBB3/viewtopic.php?f=1&t=635 HTTP/1.1" 200 9861 "-" "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"
crawl-66-249-66-53.googlebot.com - - [31/Mar/2017:06:21:32 -0600] "GET /phpBB3/viewtopic.php?f=1&t=404 HTTP/1.1" 200 22106 "-" "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"
crawl-66-249-66-53.googlebot.com - - [31/Mar/2017:06:28:04 -0600] "GET /phpBB3/viewtopic.php?f=1&t=759 HTTP/1.1" 200 12074 "-" "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"
108-252-120-131.lightspeed.mtryca.sbcglobal.net - - [31/Mar/2017:06:29:31 -0600] "GET / HTTP/1.1" 200 38533 "-" "Mozilla/5.0 (iPhone; CPU iPhone OS 9_3_2 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13F69 Safari/601.1"
108-252-120-131.lightspeed.mtryca.sbcglobal.net - - [31/Mar/2017:06:29:32 -0600] "GET /include/css3menu1/style.css HTTP/1.1" 200 3013 "http://www.kokaneepower.org/" "Mozilla/5.0 (iPhone; CPU iPhone OS 9_3_2 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13F69 Safari/601.1"
 `

**Comment by HiTechKoke** [comment]
What is interesting is that goaccess handles these converted IP to domain names in all the other cases in the raw files except for this set of lines:

ns528252.ip-158-69-241.net - - [31/Mar/2017:06:06:41 -0600] "GET /phpBB3/ HTTP/1.1" 200 21185 "http://www.kokaneepower.org/" "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko"
ns528252.ip-158-69-241.net - - [31/Mar/2017:06:06:42 -0600] "GET /phpBB3/memberlist.php?mode=viewprofile&u=4&sid=766336da07c810396668d50b2badfbce&order=DESC&sk=c&sd=d HTTP/1.1" 200 8075 "http://www.kokaneepower.org/" "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko"
ns528252.ip-158-69-241.net - - [31/Mar/2017:06:06:43 -0600] "GET /phpBB3/index.php HTTP/1.1" 200 18309 "http://www.kokaneepower.org/" "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko"
ns528252.ip-158-69-241.net - - [31/Mar/2017:06:06:44 -0600] "GET /phpBB3/profile.php?mode=editprofile HTTP/1.1" 404 599 "http://www.kokaneepower.org/" "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko"
ns528252.ip-158-69-241.net - - [31/Mar/2017:06:06:45 -0600] "GET /phpBB3/ucp.php?mode=register&sid=766336da07c810396668d50b2badfbce HTTP/1.1" 200 6618 "http://www.kokaneepower.org/" "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko"
ns528252.ip-158-69-241.net - - [31/Mar/2017:06:06:46 -0600] "GET /phpBB3/ucp.php?mode=register&agreed=true&iscanyesno=yeswecan&step=2&coppa=0 HTTP/1.1" 200 8853 "http://www.kokaneepower.org/phpBB3/ucp.php?mode=register&sid=766336da07c810396668d50b2badfbce" "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko"
ns528252.ip-158-69-241.net - - [31/Mar/2017:06:06:47 -0600] "GET /phpBB3/memberlist.php?mode=leaders&order=DESC&sk=c&sd=d HTTP/1.1" 200 8071 "http://www.kokaneepower.org/" "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko"
ns528252.ip-158-69-241.net - - [31/Mar/2017:06:06:48 -0600] "GET /phpBB3/index.php HTTP/1.1" 200 18309 "http://www.kokaneepower.org/" "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko"
ns528252.ip-158-69-241.net - - [31/Mar/2017:06:06:49 -0600] "GET /phpBB3/profile.php?mode=editprofile HTTP/1.1" 404 599 "http://www.kokaneepower.org/" "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko"
ns528252.ip-158-69-241.net - - [31/Mar/2017:06:06:49 -0600] "GET /phpBB3/memberlist.php?mode=viewprofile&u= HTTP/1.1" 200 8041 "http://www.kokaneepower.org/phpBB3/ucp.php?mode=register&agreed=true&iscanyesno=yeswecan&step=2&coppa=0" "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko"
ns528252.ip-158-69-241.net - - [31/Mar/2017:06:06:56 -0600] "POST /phpBB3/ucp.php?mode=register&coppa=0 HTTP/1.1" 200 14914 "http://www.kokaneepower.org/phpBB3/ucp.php?mode=register&agreed=true&iscanyesno=yeswecan&step=2&coppa=0" "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko"

If I remove just them then the file will process accordingly so something in this series seems to set it off and then I get ... 

Parsed 10 lines producing the following errors:

Token 'ns528252.ip-158-69-241.net' doesn't match specifier '%h'
Token 'ns528252.ip-158-69-241.net' doesn't match specifier '%h'
Token 'ns528252.ip-158-69-241.net' doesn't match specifier '%h'
Token 'ns528252.ip-158-69-241.net' doesn't match specifier '%h'
Token 'ns528252.ip-158-69-241.net' doesn't match specifier '%h'
Token 'ns528252.ip-158-69-241.net' doesn't match specifier '%h'
Token 'ns528252.ip-158-69-241.net' doesn't match specifier '%h'
Token 'ns528252.ip-158-69-241.net' doesn't match specifier '%h'
Token 'ns528252.ip-158-69-241.net' doesn't match specifier '%h'
Token 'ns528252.ip-158-69-241.net' doesn't match specifier '%h'

Format Errors - Verify your log/date/time format

**Comment by allinurl** [comment]
I'd ask your hosting provider to either add a new field for the IP or not to resolve them.

GoAccess won't handle all cases though, only those where an IP is found, for instance, in the blob posted above, the following lines will be parsed:

```
185.25.32.38 - - [31/Mar/2017:06:11:41 -0600] "GET /robots.txt HTTP/1.1" 403 - "-" "robots"
185.25.32.38 - - [31/Mar/2017:06:11:44 -0600] "GET /phpBB3/viewforum.php?f=10 HTTP/1.1" 403 - "-" "magpie-crawler/1.1 (U; Linux amd64; en-GB; +http://www.brandwatch.net)"
185.25.32.38 - - [31/Mar/2017:06:11:41 -0600] "GET /robots.txt HTTP/1.1" 403 - "-" "robots"
185.25.32.38 - - [31/Mar/2017:06:11:44 -0600] "GET /phpBB3/viewforum.php?f=10 HTTP/1.1" 403 - "-" "magpie-crawler/1.1 (U; Linux amd64; en-GB; +http://www.brandwatch.net)"
```

**Comment by HiTechKoke** [comment]
Unfortunately the ISP won't do this as I asked as these servers serve many businesses so there is no individual control that I can have.  I'm not sure what their motivation was to do this other then maybe IPV6 addresses which they wanted to convert to something parseable.

What is weird though is all the other domain converted lines, roughly 19K lines does work ok if I remove these first 11 lines.   What is unique in that string vs the others that is failing?   I could send you the full log file for testing if you want and you could see that it does work when eliminating these lines.

**Comment by allinurl** [comment]
The way goaccess verifies this is by looking at the first 10 lines, if one of the lines is parsed correctly, then it assumes the log-format is fine and it will continue to parse the whole log. If it fails on those 10 lines, it will exit and display the error messages you posted above.

If you are looking to parse the whole log without the initial test, you can use `--num-tests=0` (not recommended), but most likely you will end up with a bunch of invalid requests and a few valid ones.

**Comment by HiTechKoke** [comment]
ok will try that... what is still odd is that if those offending lines are not in the first 10 then goaccess will parse them without any further error and produce the HTML file.    I extract out a daily access file by date out of the master log file and it gave me these errors...

Token 'crawl-66-249-73-50.googlebot.com' doesn't match specifier '%h'
Token 'crawl-66-249-65-238.googlebot.com' doesn't match specifier '%h'
Token '107-223-212-23.lightspeed.sntcca.sbcglobal.net' doesn't match specifier '%h'
Token '107-223-212-23.lightspeed.sntcca.sbcglobal.net' doesn't match specifier '%h'
Token '107-223-212-23.lightspeed.sntcca.sbcglobal.net' doesn't match specifier '%h'
Token '107-223-212-23.lightspeed.sntcca.sbcglobal.net' doesn't match specifier '%h'
Token '107-223-212-23.lightspeed.sntcca.sbcglobal.net' doesn't match specifier '%h'
Token '107-223-212-23.lightspeed.sntcca.sbcglobal.net' doesn't match specifier '%h'
Token '107-223-212-23.lightspeed.sntcca.sbcglobal.net' doesn't match specifier '%h'
Token '107-223-212-23.lightspeed.sntcca.sbcglobal.net' doesn't match specifier '%h'

which I am guessing are from the first 10 line test.   Now if I run the same goaccess command on the cumulative monthly file where these same lines would be located towards the end of the file then it does not complain and works, since there was nothing in the first 10 of the monthly that caused it to error out.  After the first 10 test if it finds something it may not like in terms of format does it just ignore the line?   I am getting a nice monthly consistent html file in the end if it can get past the first 10 lines.

**Comment by allinurl** [comment]
That's correct, after the first 10, it will ignore the line and count it as "Invalid Request" and the parsing will continue until the end of line.

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
