### ISSUE TITLE
Cannot figure out log format

### ISSUE THREAD

**Issue by victorgonal** [allinurl/goaccess#722]
Hi!

I´ve been trying since yesterday to figure out the right log format to display the data in the dashboard but I can only see the amount of requests made.

This is an example of my log:

`255.255.255.255 - - [07/Apr/2017:06:51:47 +0000] "GET /wp-content/plugins/wpeddit-plugin-SE/css/img/sprite-reddit.HLCFG7U22Hg.png HTTP/1.1" 304 - "http://www.xxx.com/2016/08/14/xxx-xxx-xxx/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.79 Safari/537.36 Edge/14.14393"`

And this is what I tried in my config with no luck at all:

```
log-format %h %^[%d:%t%^] "%^" "%r" %s %b %^ "%R" "%u"
date-format %d/%b/%Y
time-format %H:%M:%S
```

Any ideas of what I could do?

Thanks

**Comment by allinurl** [comment]
The format looks like a `COMBINED` format, this should do it:

```
log-format %h %^[%d:%t %^] "%r" %s %b "%R" "%u"
date-format %d/%b/%Y
time-format %T
```

or simply

    goaccess access.log --log-format=COMBINED

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it as needed.
