### ISSUE TITLE
docker: where can I find the RootDocument for http request

### ISSUE THREAD

**Issue by davask** [allinurl/goaccess#724]
Hi,

running:
```
docker run --name=goaccess --restart=always -d \
-p 65533:8080 \
-v /home/user/conf/goaccess.conf:/etc/goaccess.conf \
-v /home/user/data:/srv/data \
allinurl/goaccess
```
Will make goaccess to run properly, however I have a 400 error on http://\<localhostip\>:65533/

What do you use to serve http request and where is located the DocumentRoot directory ?

thanks

**Comment by allinurl** [comment]
Great question. GoAccess doesn't have a WebServer built-in, so you will need to share a volume with another Docker container that can serve the generated HTML report.

**Comment by davask** [comment]
is there any chance to implement an http server to it ? to avoid another container ?

**Comment by allinurl** [comment]
I think the original reason behind not implementing a web server in GoAccess is that if you are analyzing access logs, it's likely you have a web server around that can be used to serve the report. Not sure yet if we should add this though. Implementing it shouldn't be too bad since most of the plumbing it's already in the WebSocket server, it just hasn't been an issue so far.

**Comment by davask** [comment]
the architecture I want to use is explained in this issue #734.
In this case the apache2 server that deliver goaccess report is not a server I want to monitor
As well, I m not sure a web app apache2 server should deliver a report aside to an app

**Comment by allinurl** [comment]
There are [several](https://github.com/search?q=topic%3Ahttp-server&type=Repositories) light-weight webserver options that you can throw into the container. Using supervisor you can even run it within the same container. Or even better, you don't need to run the report through a webserver but simply open it in your browser as a regular html file, i.e.., `file:///`. 

At some point I may add a built-in web server into GoAccess, however, there are several items in the to-do list that need to be implemented before I get to this. Feel free to open a new issue for this.

**Comment by davask** [comment]
Thanks.

I'll have a look at supervisor
