### ISSUE TITLE
Filter request url from into log file

### ISSUE THREAD

**Issue by sarastef** [allinurl/goaccess#725]
Hi I want to know if it's possible to filter the request URL from a log file that's means If I could Know what functionality the user use of my application since the url?

**Comment by allinurl** [comment]
You can certainly filter the URL doing some pre-processing. Are you looking to ignore certain lines or show only certain lines matching a pattern? Can you post a few lines from your log?

**Comment by sarastef** [comment]
This is an example 
192.X.X.X - - [07/Apr/2017:08:59:34 +0200] "POST /name_user/index.php?m=customerOffer&xxxxxxx HTTP/1.1" 200 108 "http://192.x.x/name_user/index.php?m=projects&xxxxx" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:50.0) Gecko/20100101 Firefox/50.0"
I tried to use this command
 awk '$7 ~ /m=customerOffer/'  /var/log/nginx/access.log | goaccess -a -o report.html
just for to know what url uses the functionality customerOffer but Now my question is If I could modifie the report for each user that's means If I could know what functionality  is the most used for each user and Could I change the interface just for to show these information because in general I can see in the report all the information but I can't identify  for each it for each user or for each functionality

**Comment by allinurl** [comment]
I'm not sure I follow. From your log entry, how can you identify your customer? Also, I'm not sure what you mean with "what functionality is the most used". GoAccess by default displays the requests that are hit the most and thus the must "used". 

If you can please give a few more examples on how the report should look like and what data are you trying to filter would be great.

**Comment by sarastef** [comment]
I want that in my report I will be able to change my results by client, that means the interface could be more interective. So for example  If I can insert a select tag for to show my custumers from data base and with one option show wich functionality is the most used for each customer. For functionality , I want say that's the module that I use in theURL. 
For example m=projects  where is my functionality and I can find in my URL
192.X.X.X - - [09/Apr/2017:08:59:34 +0200] "POST /name_user/index.php?m=projects &xxxxxxx HTTP/1.1" 200 108 "http://192.x.x/name_user/index.php?m=projects&xxxxx" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:50.0) Gecko/20100101 Firefox/50.0"
and I can filter all the URL that use this module on the request with this command:
awk '$7 ~ /m=projects /'  /var/log/nginx/access.log | goaccess -a -o report.html

pdt: my english is not well :(

**Comment by allinurl** [comment]
If I understand correctly, you would like to enter a search term in the report UI and display only data that matches that search term. If this is what you are looking for, then **#117** will address this.

Right now the only way to filter your data is by doing some pre-processing using tools such `awk`, `grep`, `sed`, etc and then piping the output to goaccess.

**Comment by sarastef** [comment]
Ok thanks, Now I tried to generate my report  from a first page in php but my question is  when I use 
shell_exec('goaccess /var/log/nginx/log_file -o /var/www/report.html'); 
For to execute a command of linux , but I realize with shell_exec return an string. So it's doesn't work
How Can I generate a report using a command goacces from php?

**Comment by allinurl** [comment]
Haven't tested this, but can you please try adding a single dash, e.g., 

    shell_exec('/usr/bin/goaccess /var/log/nginx/log_file -o /var/www/report.html -');

**Comment by sarastef** [comment]
I did but It doesn't work, I dont know why. I suposse  this command should be execute when the page.php is called by the server but It doesn't work

**Comment by allinurl** [comment]
What output are you getting?

**Comment by sarastef** [comment]
nothing,
I try to do a simple test. For example I want to generate a report.html from php  and when I click a button I want to see my report
This is my test.php
<?php
$output=shell_exec('/usr/bin/goaccess /var/log/nginx/log_file -o /var/www/report.html -');
$path = 'reports/report.html';
echo "<form action='$path '><input type='submit' value='report'/></form>";
?>

**Comment by allinurl** [comment]
This sounds like a permissions issue. Please take a look at your web server error log. You should be able to read the access log from your web server, e.g., `www-data` and GoAccess should have permissions to write to the folder owned by www-data.

**Comment by sarastef** [comment]
yes, I tried to change that Now I have (ls -l)
-rwxrwxr-x  1 root         www-data     67541099 avril  7 14:38  file.log
but I don't know how to do for to give permissions to GoAccess

**Comment by allinurl** [comment]
This should do it. You will need to work out a button to generate the report though.

```
<?php
$path = '/tmp/report.html';
$output = shell_exec('/usr/bin/goaccess /home/user/access.log -o ' . $path . ' --log-format=VCOMBINED');
echo file_get_contents($path);
```

**Comment by sarastef** [comment]
I tried to do that but  always I have a problem with shell_exec,
it says: Warning: file_get_contents(/tmp/report.html): failed to open stream: No such file or directory in /var/www/test.php on line 4 

I think it's about -log-format=VCOMBINED , too  because when I tried to execute this command
 /usr/local/bin/goaccess /var/log/nginx/access.log.1 -o ' . /tmp/report.html . ' --log-format=VCOMBINED 
it say : 
/var/log/nginx/access.log.1
Parsed 10 lines producing the following errors:

Token '+0200]' doesn't match specifier '%h'
Token '+0200]' doesn't match specifier '%h'
Token '+0200]' doesn't match specifier '%h'
Token '+0200]' doesn't match specifier '%h'
Token '+0200]' doesn't match specifier '%h'
Token '+0200]' doesn't match specifier '%h'
Token '+0200]' doesn't match specifier '%h'
Token '+0200]' doesn't match specifier '%h'
Token '+0200]' doesn't match specifier '%h'
Token '+0200]' doesn't match specifier '%h'

Format Errors - Verify your log/date/time format
But when I execute just:
 /usr/local/bin/goaccess /var/log/nginx/access.log.1 -o ' . /tmp/report.html . '
 I don't have error message but it doesn't generate a report.html

**Comment by allinurl** [comment]
The example I posted above worked for me knowing that www-data can write/read from /tmp and can read the access.log.

1. Make sure you have the right format. The example I posted above with VCOMBINED was applicable to me. You need to use your own log format.
2. As I said before, please look at your syslog and nginx's error.log, it will output the error you are encountering. 
3. Ensure `www-data` can read the `access.log`.
4. Ensure `www-data` can read/write from `/tmp/`.

I'm closing this since it's not an issue with goaccess, but related to your server environment. Though, feel free to post back if you have any other questions.

**Comment by allinurl** [comment]
BTW, you can always use the real-time functionality of goaccess if you would like to keep an updated version of the report. Please take a look at the [**FAQ**](https://goaccess.io/faq#html-report).
