### ISSUE TITLE
live report from today --real-time-html

### ISSUE THREAD

**Issue by askart** [allinurl/goaccess#729]
How i can generate live report from today? if i specify `-f access.log`, it will just read from this file, I need something like this:

    grep —no-filename $(date +"%d/%b/%Y") access.log --real-time-html

is this possible?

**Comment by allinurl** [comment]
It is possible if you are using v1.2. You can run something like: 

    tail -f -n +0 /var/log/apache2/access.log | grep `date +"%d/%b"` --line-buffered | goaccess --log-format=VCOMBINED -o report.html --real-time-html

**Comment by askart** [comment]
thx
