### ISSUE TITLE
Can't parse custom logs for Amazon Load Balancer

### ISSUE THREAD

**Issue by brycefujii** [allinurl/goaccess#73]
Can someone help provide custom log and date format that I need to use?

My logs look something like this:
"92.247.242.238" - - [13/Jan/2014:13:47:03 -1000] "GET /blog/governor-releases-83-9-million-for-university-of-hawaii-campuses/ HTTP/1.1" 200 40513 "http://site.com/" "Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/28.0.1500.71 Safari/537.36"

Thank You!

**Comment by ipalo** [comment]
AWS ELB access log has a new format now.

My log looks like this:
```
2015-08-01T00:00:39.092804Z awseb-e-c-AWSEBLoa-IT1XXX1234124 1.22.3.4444:18031 123.33.11.222:80 0.000038 0.543988 0.000071 200 200 0 153373 "GET http://www.site.com:80/api/v2/get HTTP/1.1" "Dalvik/1.6.0 (Linux; U; Android 4.4.2; LG-D605 Build/KOT49I.D60520e)" - -
```
This is the format as looks like in [AWS ELB documentation](https://docs.aws.amazon.com/ElasticLoadBalancing/latest/DeveloperGuide/access-log-collection.html):
```
timestamp elb client:port backend:port request_processing_time backend_processing_time response_processing_time elb_status_code backend_status_code received_bytes sent_bytes "request" "user_agent" ssl_cipher ssl_protocol
```

I tried with
```
log_format %x %^ %h %^ %^ %T %^ %^ %s %^ %b "%m %U %H" "%u" %^ %^
date_format  %Y-%m-%d
```
but this doesn't work.

Can anyone help me?

Thanks!
