### ISSUE TITLE
Server locked (outgoing flood)

### ISSUE THREAD

**Issue by davask** [allinurl/goaccess#730]
Hi,

My server have been locked because of an outgoing flood from goaccess.

Any idea why that might happen ?

**Comment by allinurl** [comment]
I'm not sure I follow, what do you mean locked because of an outgoing flood? A lot of data going out from your server?

**Comment by davask** [comment]
I m not sure why, but i have been blocked for that reason from the port used by goaccess which was active at that time




david asquiedge









On Mon, Apr 10, 2017 at 5:08 PM +0200, "Gerardo O." <notifications@github.com> wrote:












I'm not sure I follow, what do you mean locked because of an outgoing flood? A lot of data going out from your server?

**Comment by davask** [comment]
I m not sure why, but i have been blocked for that reason from the port used by goaccess which was active at that time
the log message that I have is 

```shell

2017-04-10 10:20:56 = DDOS from IP 163.172.35.42 (attack ID 377304): protocols : tcp, targets: 43.241.50.22/32, sports: Dynamic (1024-65535), dports

```

**Comment by allinurl** [comment]
Did your hosting/server company block you? Were you able to get the live report working and suddenly stopped updating?  From the log you posted above, it looks like some sort of firewall is setting this for you. You can always change the port in your goaccess config file. e.g.,

    port 7891

**Comment by davask** [comment]
Did your hosting/server company block you? yes
Were you able to get the live report working and suddenly stopped updating? I don t understand

**Comment by allinurl** [comment]
You probably want to talk to your server company, not sure if there's anything goaccess can do other than changing ports.

**Comment by davask** [comment]
Okay, so based on my talk with my server company I ll have to investigate howver I don t know how to.
Any advises or tuto or tools to recommand ?

**Comment by allinurl** [comment]
Are you on a vps? or managed server? If you are on a vps, then I'd assume you have full control of it so it *should* be easier to know what's going on. If it's some sort of managed server, then your server company probably knows more about this.  I'd check what services you are running and start from there. Also check your iptables rules and see what might be causing the block.

**Comment by davask** [comment]
Thks,

I m on dedicated server.

I ll follow your advises. thks
