### ISSUE TITLE
Clarification of options for secure source code download?

### ISSUE THREAD

**Issue by maxfelsher** [allinurl/goaccess#735]
I'm looking to install GoAccess on a distribution that doesn't have the program available in its package manager (RHEL), so it looks like I'll have to compile from source. The current instructions suggest downloading from http://tar.goaccess.io/goaccess-1.2.tar.gz. I'd prefer not to run code from a file that could be altered as it travels over the Internet without any way to tell.

I tried just changing the scheme of that URL to `https`, but the certificate is invalid (it's only good for bin.goaccess.io, not tar.goaccess.io). I also looked around for a checksum of some sort that I could at least use to verify the downloaded file but didn't find anything along those lines.

I did notice that releases are available from https://github.com/allinurl/goaccess/releases, so I'm thinking using https://github.com/allinurl/goaccess/archive/v1.2.tar.gz might be my best bet. Is that the recommended approach?

**Comment by allinurl** [comment]
Thanks for the heads up on this. Please try again. It should let you do it through https.

**Comment by maxfelsher** [comment]
That works, thanks! https://tar.goaccess.io/goaccess-1.2.tar.gz now has a valid certificate.

**Comment by allinurl** [comment]
Glad to hear that! I'll update the website as well.
