### ISSUE TITLE
Log format issues with VCOMBINED format

### ISSUE THREAD

**Issue by geek1011** [allinurl/goaccess#738]
Command line args: `-log-format '%v:%^ %h %^[%d:%t %^] "%r" %s %b "%R" "%u"' --time-format '%H:%M:%S' --date-format '%d/%b/%y'`

Sample log:
````
subdomain.example.com 192.168.2.11 - [16/Apr/2017:10:00:39 -0400] "GET /path/to/page HTTP/2.0" 200 12598 "http://referrer.example.com/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0"
````

Error: `Token '-0400]' doesn't match specifier '%h'`

I have tried many different format strings, but it never seems to work.

Thanks in advance!

**Comment by allinurl** [comment]
Please try this:

    goaccess access.log --log-format='%v %h %^[%d:%t %^] "%r" %s %b "%R" "%u"' --date-format=%d/%b/%Y --time-format=%T

**Comment by geek1011** [comment]
Thanks so much! It worked. I think it would be a good idea to add documentation for the format somewhere. Also, another questionL what does `%^` mean?
