### ISSUE TITLE
List all requests hitting a specific page

### ISSUE THREAD

**Issue by SammDu** [allinurl/goaccess#739]
### Problem & Feature Request
I'd like to see all traffic hitting a specific url (or page, file, address; whatever you call it) in a list, so I can know who visited the specific page, or practically, did somebody visit the page that I told him to ;-)
I mean bot's are annoying AF and making noise, while I just want to see valuable statistics to pages that I actually made for people to visit (e.g. interest analysis, etc). You do have a list of URLs that are being visited, but I'd like to be able to click into the url listing, and see the actual requests w/ ip addresses.
So yeah, that's basically my problem.
#### `grep` pre-filtering
That's kindda obvious, use grep to filter out requests hitting the url, then hand it over to GoAccess;   
***But*** I'm having problems with that -- I'm not an advanced linux user...and I've no clue how to do "tripple piping"...here's a practical example:
```
zcat access.log.*.gz | goaccess access.log access.log.1 - -a -o full-report.html
```
That's the command I currently use to generate report; But adding grep?
```
grep -i 'interesting_page' zcat access.log.*.gz | goaccess access.log access.log.1 - -a -o intro-report.html
```
That didn't work :-(

**Comment by allinurl** [comment]
Thanks for the suggestion. #117 will add the ability to filter from the UI. 

As far as pre-filtering, you should be able to do the following:

    zgrep -h -i 'interesting_page'  access.log* | goaccess -a -o intro-report.html -

**Comment by SammDu** [comment]
Thanks bro it works! :-)
