### ISSUE TITLE
Help goaccess on Docker

### ISSUE THREAD

**Issue by vmdao** [allinurl/goaccess#740]
Hi Pro,
I use goaccess on docker, i flow document install. but not run web report.
I use NGINX as a WebSocket Proxy for app. Help me?
Thank you Pro!

**Comment by allinurl** [comment]
I'm not sure I understand the issue you are having. Have you checked [**this**](https://goaccess.io/download#docker) section?

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
