### ISSUE TITLE
--real-time-html doesn't start using latest master

### ISSUE THREAD

**Issue by dcherniv** [allinurl/goaccess#742]
Hello
I have the following problem:
When i start goaccess with 
`goaccess -f /var/log/squid/access.log -o /usr/share/nginx/html/index.html --real-time-html --ws-url=192.168.1.170`
I doesn't run, just quits right away.
My squid log format looks like this: 
`192.168.1.250 - - [23/Apr/2017:13:39:35 -0400] "CONNECT console.aws.amazon.com:443 HTTP/1.1" 403 4043 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0" TCP_DENIED:HIER_NONE
192.168.1.250 - - [23/Apr/2017:13:39:37 -0400] "CONNECT detectca.easysol.net:443 HTTP/1.1" 403 4037 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0" TCP_DENIED:HIER_NONE`
When i run without --real-time-html and without -o, ncurses ui displays so i think its able to parse it.
Debug log just says Bye.
I use log-format COMBINED in the goaccess.conf.

I'm using latest master. Anything obvious i'm missing here. Just to add more strangeness sometimes it starts, when i completely reboot my test server. 
I haven't had the same issue with goaccess 1.0.x from EPEL repos.

**Comment by allinurl** [comment]
Can you please post a screenshot of the issue? Also, please take a look at dmesg just to be sure it's not crashing. Thanks

**Comment by dcherniv** [comment]
Sure thing. Repo version output: 
`[root@squid-1 ~]# goaccess --version
GoAccess - 1.0.2.
For more details visit: http://goaccess.io
Copyright (C) 2009-2016 by Gerardo Orellana
[root@squid-1 ~]# goaccess 
Unable to open fifo out: No such device or address.
Parsing... [4,385] [0/s]
Accepted: 182 192.168.1.250
Active: 1

^CSIGINT caught![root@squid-1 ~]# 
`
Everything working as expected. I can connect to 192.168.1.170:8080 with no problems.
Relevant config options:
`log-format COMBINED
config-dialog false
hl-header true
json-pretty-print false
no-color false
no-column-names false
no-csv-summary false
no-progress false
no-tab-scroll false
with-mouse false
port 7890
real-time-html true
ws-url 192.168.1.170
log-file /var/log/squid/access.log
agent-list false
with-output-resolver false
http-method yes
http-protocol yes
output-format /usr/share/nginx/html/index.html
no-query-string false
no-term-resolver false
444-as-404 false
4xx-to-unique-count false
all-static-files false
double-decode false
ignore-crawlers false
ignore-panel REFERRERS
real-os true
`
This is latest from master. Works every other time.
`
[root@squid-1 goaccess]# /usr/local/bin/goaccess 
WebSocket server ready to accept new client connections
^[[A^C
SIGINT caught!
Closing GoAccess...
Stopping WebSocket server...
[root@squid-1 goaccess]# /usr/local/bin/goaccess 
[root@squid-1 goaccess]# ps aux | grep goac
root     14931  0.0  0.0 112648   964 pts/0    R+   22:58   0:00 grep --color=auto goac
[root@squid-1 goaccess]# 
`
Sometimes it takes even longer to fire up:
`
[root@squid-1 goaccess]# tail  /var/log/squid/access.log

192.168.1.250 - - [23/Apr/2017:22:58:34 -0400] "CONNECT console.aws.amazon.com:443 HTTP/1.1" 403 4043 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0" TCP_DENIED:HIER_NONE
192.168.1.250 - - [23/Apr/2017:22:58:37 -0400] "CONNECT ssl.gstatic.com:443 HTTP/1.1" 403 4022 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0" TCP_DENIED:HIER_NONE
192.168.1.250 - - [23/Apr/2017:22:58:37 -0400] "CONNECT www.gstatic.com:443 HTTP/1.1" 403 4022 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0" TCP_DENIED:HIER_NONE
192.168.1.250 - - [23/Apr/2017:22:58:37 -0400] "CONNECT www.gstatic.com:443 HTTP/1.1" 403 4022 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0" TCP_DENIED:HIER_NONE
[root@squid-1 goaccess]# /usr/local/bin/goaccess 
[root@squid-1 goaccess]# /usr/local/bin/goaccess 
[root@squid-1 goaccess]# /usr/local/bin/goaccess 
[root@squid-1 goaccess]# /usr/local/bin/goaccess 
[root@squid-1 goaccess]# /usr/local/bin/goaccess 
[root@squid-1 goaccess]# /usr/local/bin/goaccess 
[root@squid-1 goaccess]# /usr/local/bin/goaccess 
[root@squid-1 goaccess]# /usr/local/bin/goaccess 
[root@squid-1 goaccess]# /usr/local/bin/goaccess 
[root@squid-1 goaccess]# /usr/local/bin/goaccess 
[root@squid-1 goaccess]# /usr/local/bin/goaccess 
WebSocket server ready to accept new client connections
`

**Comment by allinurl** [comment]
So if I understand correctly and from what you just posted, goaccess runs but you can't access the report in real-time? If this is the case, have you checked your browser's console? Usually if it's unable to connect to the websocket server it will display some sort of error.

From the post above, you hit Ctrl+c to quit goaccess. I'm not sure what you mean with "sometimes it takes longer to fireup". Can you please post the steps to reproduce the issue you are having? Thanks.

**Comment by dcherniv** [comment]
> So if I understand correctly and from what you just posted, goaccess runs but you can't access the report in real-time? 
Well, no. goaccess doesn't start at all. If you look at the  very last snippet, i try to start it repeatedly and get nothing. Finally it starts and prints WebSocket server ready to accept new client connections.

To reproduce:
1. Build from latest master.
2. Take this snippet and paste into a log file you want to run goaccess against:
`192.168.1.250 - - [23/Apr/2017:22:58:34 -0400] "CONNECT console.aws.amazon.com:443 HTTP/1.1" 403 4043 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0" TCP_DENIED:HIER_NONE
192.168.1.250 - - [23/Apr/2017:22:58:37 -0400] "CONNECT ssl.gstatic.com:443 HTTP/1.1" 403 4022 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0" TCP_DENIED:HIER_NONE
192.168.1.250 - - [23/Apr/2017:22:58:37 -0400] "CONNECT www.gstatic.com:443 HTTP/1.1" 403 4022 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0" TCP_DENIED:HIER_NONE
192.168.1.250 - - [23/Apr/2017:22:58:37 -0400] "CONNECT www.gstatic.com:443 HTTP/1.1" 403 4022 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0" TCP_DENIED:HIER_NONE`
3. Run goaccess with the below options:
`log-format COMBINED`
`config-dialog false`
`hl-header true`
`json-pretty-print false`
`no-color false`
`no-column-names false`
`no-csv-summary false`
`no-progress false`
`no-tab-scroll false`
`with-mouse false`
`port 7890`
`real-time-html true`
`ws-url 192.168.1.170`
`log-file /var/log/squid/access.log`
`agent-list false`
`with-output-resolver false`
`http-method yes`
`http-protocol yes`
`output-format /usr/share/nginx/html/index.html`
`no-query-string false`
`no-term-resolver false`
`444-as-404 false`
`4xx-to-unique-count false`
`all-static-files false`
`double-decode false`
`ignore-crawlers false`
`ignore-panel REFERRERS`
`real-os true`
4. try to run: /usr/local/bin/goaccess If it starts CTRL+C it and try again. It will start failing to start. No process running, no output printed just drops back to the shell. Then after a while it might start again.

**Comment by allinurl** [comment]
I wasn't able to reproduce this on my side with the steps you posted above. Other than the input/output path, everything else in the config file is the same. Here's my output:

![out](https://cloud.githubusercontent.com/assets/5005367/25365610/7fc18a2a-292f-11e7-81c3-d973f4e64c00.gif)

BTW, did you build with btree (on-disk) support? or in-memory storage? Are you able to test it on a different machine?

**Comment by allinurl** [comment]
@dcherniv were you able to run it on a different machine?

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
