### ISSUE TITLE
Debian packaging files or howto

### ISSUE THREAD

**Issue by szepeviktor** [allinurl/goaccess#744]
Would it be possible to add Debian packaging files to this repo?

There is an outdated but properly written one on debian.org
http://http.debian.net/debian/pool/main/g/goaccess/goaccess_0.9.4-1.debian.tar.xz

**Comment by szepeviktor** [comment]
I would contribute. Satisfying lintian always seems to be a good idea.

```
I: goaccess: hardening-no-fortify-functions usr/bin/goaccess
I: goaccess: spelling-error-in-binary usr/bin/goaccess occured occurred
I: goaccess: spelling-error-in-binary usr/bin/goaccess Diable Disable
E: goaccess: unstripped-binary-or-object usr/bin/goaccess
W: goaccess: hardening-no-relro usr/bin/goaccess
I: goaccess: hardening-no-bindnow usr/bin/goaccess
I: goaccess: hardening-no-pie usr/bin/goaccess
E: goaccess: debian-changelog-file-missing-or-wrong-name
W: goaccess: new-package-should-close-itp-bug
E: goaccess: no-copyright-file
E: goaccess: extended-description-is-empty
W: goaccess: unknown-section default
I: goaccess: unknown-field-in-control vendor
I: goaccess: unknown-field-in-control license
E: goaccess: manpage-not-compressed usr/share/man/man1/goaccess.1
W: goaccess: manpage-has-errors-from-man usr/share/man/man1/goaccess.1 323: warning [p 5, 9.2i]: cannot adjust line
```

**Comment by allinurl** [comment]
Not sure what do you mean with "add Debian packaging files to this repo?"?

**Comment by szepeviktor** [comment]
In #743 I have to repackage goaccess as I refrain from keeping single file on my servers.

How do you generate the Debian package?

**Comment by allinurl** [comment]
I see, you can try using fpm, or aptly, the former being pretty easy to use.

**Comment by szepeviktor** [comment]
Thank you I like raw things.

Would you welcome a /debian directory?

**Comment by allinurl** [comment]
Sorry, I'm not sure what do you mean with a debian directory. Are you trying to build a deb package? and use that in your server?

**Comment by szepeviktor** [comment]
Yes, see #746

**Comment by FedericoCeratto** [comment]
FYI the official Debian packaging is hosted at https://anonscm.debian.org/cgit/collab-maint/goaccess.git
