### ISSUE TITLE
Strange bot name

### ISSUE THREAD

**Issue by szepeviktor** [allinurl/goaccess#747]
echo '141.101.76.152 - - [24/Apr/2017:04:51:25 +0000] "GET /wp-content/uploads/2014/03/14-182x300.png HTTP/1.1" 200 64049 "Client-IP:5.255.250.75" "Mozilla/5.0 (compatible; YandexImages/3.0; +http://yandex.com/bots)"' | goaccess ...

```
 > 7 - Browsers                                                                       

 Hits      h% Vis.      v%   Bandwidth Data
 ---- ------- ---- ------- ----------- ----
 1    100.00%    1 100.00%   62.55 KiB Crawlers           ||||||||||||||||||||||||||||
 1    100.00%    1 100.00%   62.55 KiB  ├─ Images/3.0     ||||||||||||||||||||||||||||
```

How does goaccess know that `YandexImages/3.0` is a crawler? (not found in source)
Why does it list it as `Images/3.0`?

**Comment by allinurl** [comment]
Thanks for report this and great question. There is an [**entry**](https://github.com/allinurl/goaccess/blob/master/src/browsers.c#L261) in the array that it's parsing the UA from the line posted above. I've pushed a [commit](https://github.com/allinurl/goaccess/commit/34c83a4624825bbe05be02f0d92d17aa0d3375fe) that should take care of Yandex crawlers. 

BTW, I'm hoping to do some refactoring on the UA/browsers detection code which I'm hoping will recognize more crawlers.

**Comment by szepeviktor** [comment]
Thank you.

This is the full list https://yandex.com/support/webmaster/robot-workings/check-yandex-robots.xml
Basically "Yandex" + something.
