### ISSUE TITLE
'AM_PROG_MKDIR_P' macro is deprecated

### ISSUE THREAD

**Issue by szepeviktor** [allinurl/goaccess#748]
During creating the Dockerfile for Debian packaging:

configure.ac:20: warning: The 'AM_PROG_MKDIR_P' macro is deprecated, and its use is discouraged.
configure.ac:20: You should use the Autoconf-provided 'AC_PROG_MKDIR_P' macro instead,
configure.ac:20: and use '$(MKDIR_P)' instead of '$(mkdir_p)'in your Makefile.am files.

**Comment by allinurl** [comment]
I don't see any `AM_PROG_MKDIR_P` macro under configure.ac. How are you building this?

**Comment by szepeviktor** [comment]
https://github.com/allinurl/goaccess/blob/master/configure.ac#L20
It may be in another macro.

**Comment by szepeviktor** [comment]
I am using Debian helpers to build it.
https://github.com/szepeviktor/debian-server-tools/blob/master/package/docker-backport-goaccess.sh

**Comment by allinurl** [comment]
`AM_GNU_GETTEXT_VERSION([0.19])` would probably solve the warning. However, Ubuntu precise still has v0.18 which is still supported, so I can't bump this up. Thanks for the heads up on this.
