### ISSUE TITLE
Changing time scale in real time report

### ISSUE THREAD

**Issue by superciccio14** [allinurl/goaccess#751]
Hello there, I'm using GoAccess to analyze a bunch of Apache log files.

Is there a way to change the time scale of charts of real time html report? For example, in your demo http://rt.goaccess.io/?20170421134619 data are displayed with an hourly scale. 

In my settings I have:
```
time-format %H:%M:%S
date-format %d/%b/%Y
log-format %h %^[%d:%t %^] "%r" %s %b "%R" "%u"
```
but data are displayed on a daily scale. Can I switch to a hours or minutes?

**Comment by allinurl** [comment]
You can certainly display the Visitors panel hourly using

    date-spec hr

and for the Time Distribution panel, you can use

    hour-spec min

**Comment by superciccio14** [comment]
Uh...!? Neat! I'm so sorry, I hadn't seen that options...

Thank you for your great job guys! :+1:
