### ISSUE TITLE
Add BLEXBot as a known web crawler

### ISSUE THREAD

**Issue by davidjkrause** [allinurl/goaccess#753]
User Agent it is using is:

Mozilla/5.0 (compatible; BLEXBot/1.0; http://webmeup-crawler.com/)

Seems like a legitimate crawler, and requests made by it should be classified to follow the --crawlers-only or --ignore-crawlers command line options.

Could probably do a pull request if needed, looks like just a one-line change to add.

**Comment by allinurl** [comment]
Thanks for the heads up on this. This has been [added](https://github.com/allinurl/goaccess/commit/1871ed1753c7e2fcf468253f5a64855bca48cfd8).

BTW, I'm hoping to do some refactoring on the UA/browsers detection code which I'm hoping will recognize more crawlers.
