### ISSUE TITLE
Session expiration when counting unique visitors

### ISSUE THREAD

**Issue by szepeviktor** [allinurl/goaccess#755]
What duration does goaccess consider as 1 session when counting visitors?

**Comment by allinurl** [comment]
HTTP requests containing the same IP, the same date, and the same user agent are considered a unique visitor. There's no concept of session when counting unique visitors.

**Comment by szepeviktor** [comment]
Thanks.

So If I visit a site at 06:01 and at 16:59 that will count as two hits and one visitor?

**Comment by allinurl** [comment]
That's correct. Just note that the hits counter can be more than 2 if there are static files when loading the site.

**Comment by szepeviktor** [comment]
> if there are static files when loading the site.

Thank you.
I usually use a CDN.

**Comment by MIvanchev** [comment]
Hey, I just wanna ask, because this is relevant for me right now, would you consider adding support for an option which specifies a timeout separating unique visits? I.e. <n> seconds/minutes/hours between visits triggers a new unique visit.

**Comment by allinurl** [comment]
@MIvanchev #2669 appears to be the same request. What are your thoughts on that?

**Comment by MIvanchev** [comment]
@allinurl Yes, it appears to be semantically the same, only difference being @jlmenut wanted a longer period and I need a shorter one. IMO there is also a somewhat problematic issue with the current approach if the requests start arriving around midnight. Considering the general interest I'll meditate a bit on your proposed solution and think about how to extend it.
