### ISSUE TITLE
How to load new html-prefs and set them as default?

### ISSUE THREAD

**Issue by sarastef** [allinurl/goaccess#756]
I'm trying to uncomment this section of goaccess.conf
`html-prefs {"theme":"bright","perPage":10,"layout":"vertical","showTables":true,"visitors":{"plot":{"chartType":"bar"}}}`
because I want to the number of item per page will be 10 and the orientation of a panel: vertically by default in my report html. But It doesn't work I tried with this command
`goaccess  access.log -o /var/www/report.html --html-prefs='{"theme":"bright","perPage":10,"layout":"vertical","showTables":true,"visitors":{"plot":{"chartType":"bar"}}}'`
but nothing change in my report

**Comment by allinurl** [comment]
Great question. GoAccess makes use of localStorage in your browser. So if you load the report once, then next time it will load the same preferences from localStorage. To use the new specified preferences, you will need to clear your localStorage.

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.

**Comment by rc5hack** [comment]
To debug html-prefs changing without manually clearing your localStorage, you also could use "private browsing" mode in your browser (in Firefox: Shift + CTRL + P (on Windows/Linux), Shift + ⌘ + P (on macOS), in other browsers: google for it).
