### ISSUE TITLE
Not showing hours and minutes in Unique visitors panel real time

### ISSUE THREAD

**Issue by agustin013** [allinurl/goaccess#758]
Hello, the problem I have is that I can not see in the graph unique visitors the hour and minute ranges, I have tried almost everything that is here and it did not work, I leave the command to raise and a fragment of the access log, besides an attachment.

Thanks

![goaccesstime](https://cloud.githubusercontent.com/assets/26903511/25748051/1a1968a6-3180-11e7-8e3f-fe10c86ffcbf.png)

`187.92.82.235 - - [05/May/2017:13:42:23 +0000] "GET /web/79565750/js/xxx.wpd HTTP/1.1" 200 1483 "http://xxxxxxxxxxxxxxxxxxxxxxx" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36"`

`goaccess -f /var/log/goaccess/brgo_access.log -o /var/www/html/goaccess/report.html --real-time-html --ws-url=xxxxxxxxx`

`time-format %H:%M:%S
date-format %d/%b/%Y
date-format %d/%b/%Y`

**Comment by allinurl** [comment]
Please use `--date-spec=hr` to set the date specificity to hours and `--hour-spec=min` to set the time specificity to minutes in the Time Distribution panel.

**Comment by agustin013** [comment]
Thanks! it's works!
Gracias
