### ISSUE TITLE
browser-view feature request

### ISSUE THREAD

**Issue by stephanfriedrich** [allinurl/goaccess#759]
Hi, thx for developing goaccess.
im using it with nginx. what do you think about these browser features and is this possible to implement, or is there a technical reason why not?

1] - merge different subdomain logs into one output.html and show results by sub-domain
2] - filter ALL information chats by one unique visitor

**Comment by allinurl** [comment]
1. You should be able right now to merge all subdomain los into one html report e.g.,

    goaccess subdomain1.access.log subdomain2.access.log

2. If I understand correctly, #117 should let you do the filtering, for instance, specifying a host/IP and get the results only for the matching criteria.

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if my previous post does not address your question.
