### ISSUE TITLE
Detect JOSM as a Browser instead of a generic Crawler

### ISSUE THREAD

**Issue by SanderH** [allinurl/goaccess#760]
I'm running a GeoServer instance for serving WMS and WMTS imagery for my website, but more importantly as background layers in the OpenStreetMap editor JOSM.

In the access log they appear as:

```
"JOSM/1.5 (12006 en) Windows 10 64-Bit Java/1.8.0_131"
"JOSM/1.5 (11826 nl) Windows 7 64-Bit Java/1.8.0_131"
"JOSM/1.5 (12067 nl) Linux Ubuntu 16.10 Java/1.8.0_121"

```
In the report these are visible as Crawler (>90%).
Can you let JOSM appear as Browser instead?

**Comment by allinurl** [comment]
I'm not sure I understand, is JOSM an actual browser used by a user or a some sort of bot from OpenStreetMap hitting the server?

**Comment by SanderH** [comment]
It's not really an browser, but [JOSM](https://josm.openstreetmap.de/) is editing tool used by actual end-users. Users use the imagery (from http servers) within JOSM to know where to draw highways/buildings/... and then upload to the OpenStreetMap database.
It's definitely not a crawler and I think is best represented as a browser.

**Comment by allinurl** [comment]
Per this [commit](https://github.com/allinurl/goaccess/commit/86225c8e1683681066d87813a19f108baaeacc33), JOSM should be now under the browser's category. It will be push out in the upcoming release.
