### ISSUE TITLE
Custom log format with XFF and tab/space delimited

### ISSUE THREAD

**Issue by thushan85** [allinurl/goaccess#762]
Hi @allinurl 

What's the right log format for the following access log. I have tried many but still not worked. 

    [03/May/2017:23:58:18 -0400]	127.0.0.1	127.0.0.1	200	4876	GET /appQuery?query=monitorServer HTTP/1.0	273	-	-

Format:

    LogFormat in apache config: "%t   %{X-Forwarded-For}i %a  %>s %D  %r  %B  %{Referer}i %{User-Agent}i" combined

Goaccess verion 1.2

**Comment by allinurl** [comment]
It looks like you have a mix of spaces and tabs delimiting the log. I'd recommend using a consistent format. However, this should do it:

    goaccess access.log --log-format='[%d:%t %^]\t~h{\t}\t%s\t%D\t%m %U %H\t%b\t%R\t%u' --date-format=%d/%b/%Y --time-format=%T

**Comment by thushan85** [comment]
Thank you very much @allinurl  It worked...!!!!
