### ISSUE TITLE
Avg.T.S, Cum. T.S, and Max T.S. Columns Not Showing

### ISSUE THREAD

**Issue by sero323** [allinurl/goaccess#767]
I have the following log format in my apache configuration...
```
LogFormat "%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-agent}i\"" combined-time
CustomLog /var/www/access.log combined-time
```

In the goaccess.conf file I am using the following log format...
```
# NCSA Combined Log Format
log-format %h %^[%d:%t %^] "%r" %s %b "%R" "%u"
```

But the Avg.T.S, Cum. T.S, and Max T.S. is not in the apache access log. Am I missing something in my apache configuration to show the times?

**Comment by allinurl** [comment]
You will need to add `%D` to your Apache's LogFormat, e.g., 

    LogFormat "%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-agent}i\" %D" combined-time

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
