### ISSUE TITLE
Need some help with apache2 error log format

### ISSUE THREAD

**Issue by ovizii** [allinurl/goaccess#772]
I have one virtualhost with these 2 log files I'd like ot parse by goaccess ideally at the same time. 

     ErrorLog /var/www/domain.tld/logs/error.log
     CustomLog /var/www/domain.tld/logs/access.log "combined"

goaccess access.log works fine but error.log can't be figured out by goaccess with any of the default options when the config dialogue pops up.

sample from error_log
`[Wed May 17 10:18:36 2017] [error] [client 51.254.252.83] File does not exist: /var/www/domain.tld/public_html/favicon.ico, referer: http://www.domain.tld/report.html`

![james ict-consult co za 2017-05-17 10 28 05](https://cloud.githubusercontent.com/assets/837902/26145111/91e7a216-3aeb-11e7-894c-23b84df90a03.png)

I am able and willing to change my vhost log formats if someone has a suggestions which makes this command work: 
`goaccess access.log error.log`

**Comment by allinurl** [comment]
Right now you can't parse two different formats, #213 will address that. If you would like to simply try parsing the error.log, you could try:

    goaccess error.log --log-format='[%^ %d %t %^] [%^] [%^ %h] %^: %U, %^: %R' --time-format=%T --date-format='%b %d' --http-protocol=no --http-method=no

**Comment by ovizii** [comment]
Thanks, that worked just fine! 

Any idea how to modify my vhost logging settings to be able to parse those two separate access and error log files

**Comment by allinurl** [comment]
If you are using Apache >= 2.4, then please take a look at [ErrorLogFormat](https://httpd.apache.org/docs/2.4/mod/core.html#errorlogformat), you may need to introduce some empty fields such as user agent since it looks like there isn't a specifier for it.

**Comment by ovizii** [comment]
Thanks!

**Comment by julienduthoit** [comment]
Just in case, I had the current ErrorLogFormat myself without any configuration  
`[Sat Jan 20 13:10:00.299537 2018] [authz_core:error] [pid 29922] [client 127.0.0.1:18555] AH01630: client denied by server configuration: /var/www/site/xmlrpc.php, referer: https://site.fr/example.php`

I solved it with the current --log-format 
`goaccess /var/log/apache2/error.site.log --log-format='[%^ %d %t.%^ %^] [%^] [%^] [%^ %h:%^] %^: %U, %^: %R'`

**Comment by neilborromeo** [comment]
It keeps on asking the log format

**Comment by Houssem99** [comment]
I have problem with log 
any help Please 

Oct  8 11:55:59 server2 server2-access 92.184.124.86 - - [08/Oct/2020:00:00:12 +0200] "GET /wikiTek/info/tests.php" 200 6953 "https://wikiTek.com" "Mozilla/5.0 (iPhone; CPU iPhone OS 11_2_5 like Mac OS X) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0 Mobile/15D60 Safari/604.1"

**Comment by allinurl** [comment]
@Houssem99 This should do it:

    goaccess access.log --log-format='%^ %^ %^ %^ %v %h %^[%d:%t %^] "%m %U" %s %b "$R" "%u"' --date-format=%d/%b/%Y --time-format=%T --http-protocol=no

**Comment by Pol52** [comment]
Hey, I am trying to parse this
`
[Thu Jun 09 06:07:04 2005] [notice] LDAP: Built with OpenLDAP LDAP SDK`

but when I use a similar config to the previously suggested formats
`
--log-format='[%^ %d %t %^] [%^] %M' --time-format=%T --date-format='%b %d' --http-protocol=no --http-method=no`

I get
```

IPv4/6 is required.

Format Errors - Verify your log/date/time format
```
What am I missing?

**Comment by allinurl** [comment]
@Pol52 As it says there, IPv4/6 is required.
