### ISSUE TITLE
Error while using --real-time-html

### ISSUE THREAD

**Issue by niranjfantain** [allinurl/goaccess#773]
![still loading](https://cloud.githubusercontent.com/assets/6571935/26147822/588bbcce-3b12-11e7-846b-095d2375e0c4.png)
I have used this command to generate the html
**sudo goaccess /var/log/nginx/access.log -o report.html --real-time-html**

Once the html is served via nginx rocket.js is blocking to load the html rendering

I am using cloudflare for hosting

Note: The html generated without --real-time-html works good

May i know the reason and some way to fix this

PFA, the console log for reference

**Comment by xobs** [comment]
I was noticing that problem today.  If you look at the debugger, you might find that it's hitting an access error.

Are you serving your site over https?  If so, you will have to specify --ws-url=wss://[domain] to goaccess, as Firefox wants to connect using "wss://" when viewing https sites.

**Comment by niranjfantain** [comment]
@xobs as you said i have added --ws-url and generated the html file, but still same stuff exist

**Comment by allinurl** [comment]
In your browser's console, what output are you getting? Please make sure port 7890 is opened and that you are using the latest version of goaccess. (As of this post, v1.2)

**Comment by niranjfantain** [comment]
@allinurl 7890 is opened, also i am at the latest version 1.2

**Comment by allinurl** [comment]
@niranjfantain In your browser's console, what output are you getting?

**Comment by niranjfantain** [comment]
@allinurl and @xobs  now i am able to get the reports realtime, i have added --ssl-cert and --ssl-key
