### ISSUE TITLE
shell_exec does not work correctly when using "awk" before generating report

### ISSUE THREAD

**Issue by nhochong** [allinurl/goaccess#776]
Hi Support,

I'm facing the problem with "awk" and "goaccess"

**My PHP script**:
```
$cmd = "awk '$7 ~ /schedule/' /var/logs/httpd/access_log* | goaccess -a -o /var/www/html/log/generate_report.html"
$output = shell_exec($cmd);
```

**Error Log**:

> AH01215: awk: cmd. line:1: (FILENAME=/var/logs/httpd/access_log-20170508 FNR=126) fatal: print to "standard output" failed (Broken pipe)

This issue only happens when output of "awk" is input of "goaccess", because when I use 
another "awk" instead of "goaccess", it still works well. Ex:

    $cmd = "awk '$7 ~ /schedule/' /var/logs/httpd/access_log* | awk '{gsub(/[\/]+/,"/",$7); print }'"

So, there is any way to fix this issue? Thank you so much.

Looking forward to knowing your response.

**Comment by nhochong** [comment]
Hi Support,

Thank you so much for your contribute.

I have resolved this issue by myself.

My solution: write filtered record to a new file before generating the report from the new file.

Script:
// Filter logs
$cmd = "awk '$7 ~ /schedule/' /var/logs/httpd/access_log* > /var/logs/httpd/filtered_log"
shell_exec($cmd);

// Generate report
$cmd = "goaccess /var/logs/httpd/filtered_log -a -o /var/www/html/log/generate_report.html"
shell_exec($cmd);

Let me know if you have a better solution for this :)

Thanks again.

**Comment by allinurl** [comment]
Using

```
$cmd = "awk '$7 ~ /schedule/' /var/logs/httpd/access_log* | goaccess -a -o /var/www/html/log/generate_report.html"
$output = shell_exec($cmd);
```

what output do you get? Also please try adding a single dash `-` to let goaccess know it should read from a pipe. e.g., 

    $cmd = "awk '$7 ~ /schedule/' /var/logs/httpd/access_log* | goaccess -a -o /var/www/html/log/generate_report.html -"

**Comment by nhochong** [comment]
Hi Support,

Amazing, your suggestion ( a single dash) works perfectly. But, seems when running command directly on the server, it still work correctly even with or without a single dash. Anyway, it's my mistake and thank you so much for your help :). I very appreciate it. I will close this question now.

**Comment by allinurl** [comment]
@nhochong Glad that worked :) Running it through shell_exec and awk probably does not give you a terminal and thus the dash is needed.
