### ISSUE TITLE
Google search string missing https referrer

### ISSUE THREAD

**Issue by neftha** [allinurl/goaccess#777]
I wondered why some Google search phrases were missing.

Added
`!(strstr (ref, "https://www.google.")) &&`
after line 571 in src/parser.c to get the missing keyphrases shown in the report.

**Comment by allinurl** [comment]
Interesting, can you please post the output of both, missing and not missing? Also, if you can post the actual lines from your access log will be great.

**Comment by neftha** [comment]
Single line logfile (ip and search phrase anonymized):

`fd00:52b3:dd11:be36:e9d3:86f9:33ed:f4d4 - - [08/Apr/2017:22:51:02 +0200] "GET /some-redacted-url/ HTTP/1.1" 200 14849 "https://www.google.de/search?q=Some+Name+Searchme&rls=org.mozilla%3Ade%3Aofficial&tbm=isch&oq=Some+Name+Searchme&gs_l=mobile-heirloom-serp.3...7246.10304.0.10823.10.9.0.1.1.0.272.1527.0j6j3.9.0....0...1c.1.34.mobile-heirloom-serp..4.6.857.zYY6olwAWeo" "Mozilla/5.0 (Android; Mobile; rv:32.0) Gecko/32.0 Firefox/32.0"`

Without change: 0 keyphrases found
With the additional line in parser.c: 1 keyphrase found

I've got a few Google search referrers with  http://www.google.de/search?q=  in the logs, but more with https://... - so in real logfile, many keyphrases were missing.

**Comment by allinurl** [comment]
Thanks for pointing this out. I didn't think Google would be sending keyphrases over https. 

I have pushed a commit that should address this. Feel free to build from development, otherwise it will be pushed out in the upcoming release.

**Comment by ITwrx** [comment]
i was wondering if this has been merged yet and/or when a release might include it. 
thanks

**Comment by allinurl** [comment]
@ITwrx It has been merged. The upcoming release it's delayed, I still need to address a few bugs. Though, feel free to build from [**development**](https://github.com/allinurl/goaccess#build-from-github-development) if needed.

**Comment by ITwrx** [comment]
cool, thanks!
