### ISSUE TITLE
Clarify that %U and %r are incompatible in log format strings in documentation

### ISSUE THREAD

**Issue by groja** [allinurl/goaccess#780]
I'm trying this tool out to see if it fits a use case I'm looking at, and was attempting to use a custom format string. This contained both %U and %r, and I was getting the following error:

Token already set for '%r' specifier.

Having looked at the underlying code and then re-examined the documentation with this in mind, I can see that %U,  %m and %q are alternatives for building up the equivalent of %r when a standard request format isn't used, and the reason I get that error is that %U writes into the same variable as %r in parser.c, and the latter checks the variable hasn't already been written to when it parses a line.

The incompatibility of the variables seems reasonable, but it would be useful if it was explicit in the documentation (the man page, https://goaccess.io/man#custom-log) that you should either use %r OR %U,  %m and %q. The later statement that goaccess requires the use of %r could also specify "or %U,  %m and %q".

**Comment by allinurl** [comment]
Thanks for pointing that out. I have updated the [**docs**](https://goaccess.io/man#custom-log). Please take a look at it and let me know if that helps.

**Comment by groja** [comment]
Yes, that makes it clearer, thanks!
