### ISSUE TITLE
Problem Report html parsin Log over syslog

### ISSUE THREAD

**Issue by nachero** [allinurl/goaccess#782]
Hi everyone,
I have some trouble parsing a log over rsyslog
I have an Apache server with rsyslog sending the log every 10 seconds to a centralized server.
I want to parse the Log in the centralized server but the report.html doesn't work fine, only parse until the moment i start to parse,( doesnt work the real-time-html option).
another thing is that the normal report ( in terminal) work fine.

Any idea?

May 22 23:59:26 HOST access_log: IP - - [22/May/2017:23:59:15 -0300] "GET /site/all/testing/4312.png HTTP/1.1" 200 397625 "-" "Apache-HttpClient/UNAVAILABLE (java 1.4)"

log-format %^ %^ %^ %v %^ %h %^[%d:%t %^] "%r" %s %b "%R" "%u" 

I'm using this Log format, and is parsing ok in terminal, but when i add the " -o /var/www/html/goaccess/report.html" and stop to work fine.

Thanks in advance.

**Comment by allinurl** [comment]
What output do you get when using `--real-time-html`? If you are able to see the generated report, please take a look at your browser's console (Ctrl+shift+j in Chrome) and see if there's an error.

**Comment by nachero** [comment]
Thanks,
I had not permission to access to the ws 7890 port from my PC.
Sorry

**Comment by allinurl** [comment]
Glad that worked! Closing this, feel free to reopen it if needed.
