### ISSUE TITLE
make failed

### ISSUE THREAD

**Issue by mezorba** [allinurl/goaccess#785]
Hello,

I am trying to install goaccess 1.2 from source but i can not be succeded yet.
I tried with two different server (CentOS 6.9 centos-release-6-9.el6.12.3.x86_64 and CentOS 7 centos-release-7-2.1511.el7.centos.2.10.x86_64) but every time i am stucking on step;

gcc -O2 -DSYSCONFDIR=\"/usr/local/etc\" -Wno-long-long -Wall -W -Wnested-externs -Wformat=2 -Wmissing-prototypes -Wstrict-prototypes -Wmissing-declarations -Wwrite-strings -Wshadow -Wpointer-arith -Wsign-compare -Wbad-function-cast -Winline -Wcast-align -Wextra -Wdeclaration-after-statement -Wno-missing-field-initializers -pthread -rdynamic  -o goaccess src/base64.o src/browsers.o src/color.o src/commons.o src/csv.o src/error.o src/gdashboard.o src/gdns.o src/gholder.o src/gmenu.o src/goaccess.o src/gslist.o src/gstorage.o src/gwsocket.o src/json.o src/opesys.o src/options.o src/output.o src/parser.o src/settings.o src/sha1.o src/sort.o src/ui.o src/util.o src/websocket.o src/xmalloc.o  src/gkhash.o    -lnsl -lncursesw -lpthread
make[1]: Leaving directory /root/goaccess-1.2

I tried with different configurations but i did not be succeded. My latest configuration is;
`Your build configuration:

  Prefix         : /usr/local
  Package        : goaccess
  Version        : 1.2
  Dynamic buffer : no
  Geolocation    : N/A
  Storage method : In-memory Hash Database (Default)
  TLS/SSL        : no
  Compiler flags :  -pthread
  Linker flags   : -lnsl -lncursesw -lpthread
  Bugs           : goaccess@prosoftcorp.com`

And my error message after make command;

In file included from src/gkhash.c:40:
src/gkhash.h: In function ‘ins_is32’:
src/gkhash.h:43: warning: inlining failed in call to ‘kh_resize_is32’: call is unlikely and code size would grow
src/gkhash.h:43: warning: called from here
src/gkhash.h:43: warning: inlining failed in call to ‘kh_resize_is32’: call is unlikely and code size would grow
src/gkhash.h:43: warning: called from here
src/gkhash.h: In function ‘ht_insert_meta_data’:
src/gkhash.h:53: warning: inlining failed in call to ‘kh_resize_su64’: call is unlikely and code size would grow
src/gkhash.h:53: warning: called from here
src/gkhash.h:53: warning: inlining failed in call to ‘kh_resize_su64’: call is unlikely and code size would grow
src/gkhash.h:53: warning: called from here
src/gkhash.h: In function ‘ht_insert_agent’:
src/gkhash.h:51: warning: inlining failed in call to ‘kh_resize_igsl’: call is unlikely and code size would grow
src/gkhash.h:51: warning: called from here
src/gkhash.h:51: warning: inlining failed in call to ‘kh_resize_igsl’: call is unlikely and code size would grow
src/gkhash.h:51: warning: called from here
src/gkhash.h: In function ‘ht_insert_maxts’:
src/gkhash.h:45: warning: inlining failed in call to ‘kh_resize_iu64’: call is unlikely and code size would grow
src/gkhash.h:45: warning: called from here
src/gkhash.h:45: warning: inlining failed in call to ‘kh_resize_iu64’: call is unlikely and code size would grow
src/gkhash.h:45: warning: called from here
gcc -O2 -DSYSCONFDIR=\"/usr/local/etc\" -Wno-long-long -Wall -W -Wnested-externs -Wformat=2 -Wmissing-prototypes -Wstrict-prototypes -Wmissing-declarations -Wwrite-strings -Wshadow -Wpointer-arith -Wsign-compare -Wbad-function-cast -Winline -Wcast-align -Wextra -Wdeclaration-after-statement -Wno-missing-field-initializers -pthread -rdynamic  -o goaccess src/base64.o src/browsers.o src/color.o src/commons.o src/csv.o src/error.o src/gdashboard.o src/gdns.o src/gholder.o src/gmenu.o src/goaccess.o src/gslist.o src/gstorage.o src/gwsocket.o src/json.o src/opesys.o src/options.o src/output.o src/parser.o src/settings.o src/sha1.o src/sort.o src/ui.o src/util.o src/websocket.o src/xmalloc.o  src/gkhash.o    -lnsl -lncursesw -lpthread
make[1]: Leaving directory `/root/Downloads/goaccess-1.2'

Can you help me about this?

**Comment by mag250** [comment]
Those are warnings, so build was done...
You need to make
`$ make install`

I would recommend first doing a test  with
```
$ mkdir -p /tmp/PKG
$ make install DESTDIR=/tmp/PKG/
```
