### ISSUE TITLE
HTML Report CSS styles in Opera 45

### ISSUE THREAD

**Issue by AlexRogalskiy** [allinurl/goaccess#786]
http://rt.goaccess.io/?20170531150753

Opera	45.0.2552.881
System:	Windows 10 64-bit (WoW64)

CSS breakout at http://rt.goaccess.io/?20170531150753

![image](https://cloud.githubusercontent.com/assets/3901898/26645124/b837e53e-463f-11e7-8e23-b3b639afa43e.png)

**Comment by allinurl** [comment]
Thanks for reporting this. Have you tried clearing your cache? I tested this out on Win7, Opera 45.0.2552.888 (PGO) and it works fine.

**Comment by allinurl** [comment]
Just wanted to check in and see if it clearing your cache and restarting your browser fixed the issue? Thanks

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
