### ISSUE TITLE
Parse successful but not date/time information in panels

### ISSUE THREAD

**Issue by ilk** [allinurl/goaccess#787]
Issue:

Parsing is successful but all time related panels are empty. For example "UNIQUE VISITORS PER DAY" or TIME DISTRIBUTION

Example log line:

```
2017-05-31 15:53:20.361572599 +0200 CEST [router] method=GET path="/foo?bar=xxx" 
host=foo.io request_id=0e3d2799-d92e-42fd from="10.12.0.1" protocol=http status=200
duration=0.012s bytes=2128 referer="http://example.com" user_agent="Go-http-client/1.1"
```

Goaccess call:

 ```
goaccess -f test.log --log-format='%d %f %^ %^ %^ method=%m path="%r" %^ %^ from="%h" %^ 
status=%s duration=%T bytes=%b referer="%R" user_agent="%u"' --date-format='%F' 
--time-format='%H:%M:%S.%N' -o index.html
```

Any ideas?

**Comment by allinurl** [comment]
This should do it:

    goaccess access.log --log-format='%d %t.%^=%m %^="%U" %^=%v %^= %^="%h" %^= %^=%s %^=%Ts %^=%b %^="%R" %^="%u"' --date-format='%Y-%m-%d' --time-format='%T' --http-protocol=no

**Comment by ilk** [comment]
Thx, works.
