### ISSUE TITLE
goaccess parsing not working

### ISSUE THREAD

**Issue by ivanionut** [allinurl/goaccess#788]
Hi,
I use for several time goaccess and it has always worked.

Lately _(after updating it via git)_ it does not work. When I run logs with this command, this happens:

`sudo zcat -f /opt/nginx/logs/www.website.it/access.log.*.gz | goaccess --ignore-crawlers -a -d -o /var/www/goaccess.website.it/www.website.it.html`

![goaccess](https://hostr.co/file/bmMqPAuUzqOb/goaccess.gif)

**Comment by allinurl** [comment]
It looks like you are resolving IPs to hosts using `-d`. From the image you posted, goaccess must be trying to resolve them. You should give it some time (probably some minutes) or don't use `-d`.

Also, if you are piping data into goaccess, it's best practice to use a single dash `-`, especially if you are running it from the cron. e.g., 

    sudo zcat -f /opt/nginx/logs/www.website.it/access.log.*.gz | goaccess --ignore-crawlers -a -d -o /var/www/goaccess.website.it/www.website.it.html -

**Comment by ivanionut** [comment]
Great! Now works. 🏆😀

What is the alternative with single dash for `--ignore-crawler?`

**Comment by allinurl** [comment]
Glad that worked. Currently there's no single dash option.

Closing this. Feel free to reopen it if needed.
