### ISSUE TITLE
Issue with real time html in remote server 

### ISSUE THREAD

**Issue by thushan85** [allinurl/goaccess#790]
Hi,
I have a problem with real time html. GoAccess is running on a remote server and  report is not updating real time.

I have found following error message on firebug

    VM2464:35 WebSocket connection to 'ws://thushan-goaccess-ws.dev.xxxx.com:7890/' failed: Error in connection establishment: net::ERR_CONNECTION_TIMED_OUT

As well as my web application access (url) via proixy which is running on the remote server.

It would be great if you can help me on this.

Thanks in advance.

**Comment by allinurl** [comment]
Have tried opening port 7890? 

Also, recently a PR was submitted that fixed an issue when parsing the host header upon opening a WebSocket connection. So if your domain contains the sub string `get`, then you will need to build from development to apply this patch. This will be pushed out in the upcoming version.

**Comment by thushan85** [comment]
Yes I have verified that 7890 is working (checked telnet). 

Actually url just a proxy pass to specific port on the server.

**Comment by allinurl** [comment]
If  the WS server is running on 7890 but all clients from outside go through proxy on client port then you can specify that port using --ws-url. e.g., 

    goaccess access.log --real-time-html --ws-url=thushan-goaccess-ws.dev.xxxx.com:9999 --port=7890

**Comment by thushan85** [comment]
Hi @allinurl 

Thanks for the help. Proxy server is not support for web sockets. I could resolved it by creating tunnel over ssh to remote server.
Thanks
