### ISSUE TITLE
[docker] Dockerfile to build from CWD

### ISSUE THREAD

**Issue by coldfix** [allinurl/goaccess#792]
If cloning the git repo and subsequently running `docker build . -t goaccess` I would expect the image to build from the checkout rather than using the apk package.

Based on #520 plus some trial and error, I have managed to create a corresponding `Dockerfile`:

```Dockerfile
FROM alpine:edge
LABEL maintainer "Julian Xhokaxhiu <info@julianxhokaxhiu.com>"

COPY . /goaccess
WORKDIR /goaccess

ENV build_deps="build-base ncurses-dev autoconf automake git gettext-dev"

RUN apk update && \
    apk add -u tini ncurses libintl gettext $build_deps && \
    autoreconf -fiv && \
    ./configure --enable-utf8 && \
    make && \
    make install && \
    apk del $build_deps && \
    rm -rf /var/cache/apk/* /tmp/goaccess/*

EXPOSE 7890

ENTRYPOINT ["/sbin/tini", "--", "goaccess", "--no-global-config", "--config-file=/srv/data/goaccess.conf"]
```

This also needs a patch to the `configure.ac`:

```diff
diff --git a/configure.ac b/configure.ac
index 6e0d5a5..3f14ab2 100644
--- a/configure.ac
+++ b/configure.ac
@@ -18,7 +18,8 @@ AC_PROG_CC
 AM_PROG_CC_C_O
 
 AM_GNU_GETTEXT([external])
-AM_GNU_GETTEXT_VERSION([0.18])
+AM_GNU_GETTEXT_VERSION([0.19])
+AC_CHECK_LIB([intl], [libintl_dgettext])
 
 # pthread
 AC_CHECK_LIB([pthread], [pthread_create], [], [AC_MSG_ERROR([pthread is missing])])

```

I'm not sure whether the modification of the automake script is safe (I don't know anything about autotools). I didn't see big advantage of using supervisor (docker partly takes that role, right?) nor the other customizations in `Dockerfile_src/` (it's easier to modify the dockerfile if you want to change the data directory), so I left these out for now. If you're interested, I can send a pull-request (with just the build recipe modified, if desired). I post this an issue, so others can see the code in any case. Feel free to close.

**Comment by allinurl** [comment]
So far the Dockerfile appears to be working fine, however, I like the idea of building directly from source without depending on the apk. Issue #705 talks about this as well. It's my understanding that supervisord will let you run multiple services in a container, I'm not entirely sure what are the advantages of running goaccess that way though.  

The concern that I have is that we would need to update ` AM_GNU_GETTEXT_VERSION` since there are still distros shipping 0.18, e.g., Debian 7 lts or Trusty. Could we get away without this update?

**Comment by coldfix** [comment]
It seems that 0.18 works fine too.

I changed the version to 0.19 while trying to get it to work due to the following warnings which appeared only on 0.18:

```
-configure.ac:20: warning: The 'AM_PROG_MKDIR_P' macro is deprecated, and its use is discouraged.
-configure.ac:20: You should use the Autoconf-provided 'AC_PROG_MKDIR_P' macro instead,
-configure.ac:20: and use '$(MKDIR_P)' instead of '$(mkdir_p)'in your Makefile.am files.
```

Later got it working by adding the `AC_CHECK_LIB` line and didn't check again whether the change was actually required, sorry.

**Comment by allinurl** [comment]
Great to know that. So yeah, feel free to submit a PR and I can play with it. Also, if you can please write the details on how to build it and perhaps a few examples on how to run the image. Thanks.
