### ISSUE TITLE
Log format for Amazon LoadBalancer

### ISSUE THREAD

**Issue by pilgrim2go** [allinurl/goaccess#793]
Hi,

Does goaccess support Amazon Loadbalancer access log?

Regards,
Van

**Comment by pilgrim2go** [comment]
By using following format 
```
goaccess --log-format='%^ %dT%t.%^ %^ %h:%^ %^ %T %^ %^ %^ %s %^ %b "%r" "%u"' --date-format='%Y-%m-%d' --time-format='%T'
```
I can analyze ALB logs for now.
FYI, just add `%^` from the one in https://github.com/allinurl/goaccess/issues/424

**Comment by allinurl** [comment]
Does the log format looks something like this?

    2015-05-13T23:39:43.945958Z my-loadbalancer 192.168.131.39:2817 10.0.0.1:80 0.000073 0.001048 0.000057 200 200 0 29 "GET http://www.example.com:80/ HTTP/1.1" "curl/7.38.0" - -
