### ISSUE TITLE
Installing on Windows Error

### ISSUE THREAD

**Issue by bmcgin** [allinurl/goaccess#794]
I am trying to install on Windows.  Make is showing an error:

src/options.c: In function ‘read_option_args’:
src/options.c:666:17: error: ‘GEOIP_MEMORY_CACHE’ undeclared (first use in this function)
   conf.geo_db = GEOIP_MEMORY_CACHE;
                 ^
src/options.c:666:17: note: each undeclared identifier is reported only once for each function it appears in
src/options.c:682:21: error: ‘GEOIP_STANDARD’ undeclared (first use in this function)
       conf.geo_db = GEOIP_STANDARD;
                     ^
make[1]: *** [Makefile:592: src/options.o] Error 1
make[1]: Leaving directory '/home/goAccess/goaccess-1.2'
make: *** [Makefile:359: all] Error 2

Did I do something wrong?

**Comment by allinurl** [comment]
Did you install `libGeoIP-devel`? Here's the [**list**](https://goaccess.io/faq#installation) of packages needed on a Cygwin installation.

**Comment by bmcgin** [comment]
I did double check and it is installed.

![capture](https://cloud.githubusercontent.com/assets/1210018/26786258/d9d3f97a-49ba-11e7-95c7-fa1a55196ab4.PNG)

**Comment by allinurl** [comment]
Thanks for reporting this. 

I've pushed a commit that should fix this issue. It was due to <GeoIP.h> conflicting with goaccess' geoip.h. Feel free to build from [**development**](https://github.com/allinurl/goaccess#build-from-github-development), otherwise it will be pushed out in the upcoming version.

**Comment by allinurl** [comment]
@ttk Thanks, I've added `gettext-devel` to the [**FAQ**](https://goaccess.io/faq#installation).
