### ISSUE TITLE
Unable to parse log v0.9.4 - Nothing valid to process.

### ISSUE THREAD

**Issue by K0ZL1K** [allinurl/goaccess#796]
When im trying to parse the file with html file, im getting this error.

```
Parsing... [1,949] [0/s]
GoAccess - version 0.9.4 - Feb  7 2016 10:13:30
Config file: /etc/goaccess.conf

Fatal error has occurred
Error occured at: src/goaccess.c - main - 1033
Nothing valid to process.

```

Any help please ? 

Thank you

**Comment by allinurl** [comment]
Looks like you have an invalid log/date/time format. I'd recommend upgrading to the latest version, v1.2 - it will display the reason why is unable to process the log.

**Comment by K0ZL1K** [comment]
ok, i will try it ! 

Will let you know after that.

Thank you

**Comment by K0ZL1K** [comment]
Update solved this problem ! 

Thank you for hint. 

Have nice day
