### ISSUE TITLE
Amazon Application Load Balancer (alb) access log format

### ISSUE THREAD

**Issue by zhibolau** [allinurl/goaccess#797]
Hi,

could you plz add log, date,time formats for alb access log?
like:

    h2 2017-06-04T10:09:08.594592Z app/elbhhhhhFront/7dalllllllla2d31a2b 99.203.0.7:7900007 10.999900.4.77:80 0.000 -1 -1 400 - 702 0 "POST https:/vent?timestamp=1.4965709xxxxx_channel=gp HTTP/2.0" "Dalvik/2.) NewsArticle/3.5.1" ECDHESHA256 T1.2 arn:aws:elasticloadbalancing:us-east-1:25095b3c2 "Root=1-5933dc44-07d638"

thank you.

ps: i am using this:
but it does not work:
```

 %dT%t.%^ %^ %h:%^ %^ %T %^ %^ %^ %s %^ %b "%r" "%u"
 %num %d-%b-%Y    
 %H:%M:%S.%f 
```

**Comment by allinurl** [comment]
Can you please describe all the fields you got there? Thanks.

**Comment by zhibolau** [comment]
http://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-access-logs.html

Right here
Thanks !


Gerardo O. <notifications@github.com>于2017年6月5日 周一19:42写道：

**Comment by allinurl** [comment]
This does the job:

    goaccess log --log-format='%^ %dT%t.%^ %v %h:%^ %^ %T %^ %^ %s %^ %b %^ "%r" "%u" %^' --date-format='%Y-%m-%d' --time-format=%T

**Comment by zhibolau** [comment]
worked！
many thanks

**Comment by lupoalberto12** [comment]
It works very fine.
Thank you @allinurl .
Bye!

**Comment by cuipengfei** [comment]
Haha, that was a lot of thanks.

Thanks!

**Comment by FernandoMiguel** [comment]
was this ever merged?

**Comment by allinurl** [comment]
@FernandoMiguel You can find the AWS load balancer format [**here**](https://github.com/allinurl/goaccess/blob/master/config/goaccess.conf#L87)

**Comment by aittam** [comment]
@allinurl uhm but the log format in the file you are [linking](https://github.com/allinurl/goaccess/blob/master/config/goaccess.conf#L87) is actually not the one you [posted](https://github.com/allinurl/goaccess/issues/797#issuecomment-306370715) some comments above.
The second one does work perfectly with AWS Application Load Balancer. Is it the one in [here](https://github.com/allinurl/goaccess/blob/master/config/goaccess.conf#L87) for AWS Classic Load Balancer maybe?
