### ISSUE TITLE
formatting issue with goaccess and customized haproxy

### ISSUE THREAD

**Issue by tsauce** [allinurl/goaccess#798]
Format below is customized and I'm getting some issues trying to read it. Any suggestions ?
Sample:

    Apr 16 03:30:01 localhost haproxy[9830]: [9830] [1492313401.408] 6/6/6/0/2/0/0 0/0/0/3/3 ---- 10.64.57.13:47226 10.64.57.11:80 10.67.28.21:9090 xpress - - "POST /1.0/apps/asdfasdf/inbox/users/SBBSBB/channels/NorthSouth HTTP/1.1" 200 apisvr:stgapi01 - {8.123.123.123|sng.example.com} - req_size=391 resp_size=341

Running with thef following:

    goaccess --date-format='%d/%b/%Y' --time-format='%H:%M:%S' -q --log-format='%^  %^ %^:%^:%^ %^ %^[%^]: [%^] [%^] %^/%^/%^/%^/%^/%^/%^ %^/%^/%^/%^/%^ %^ %^:%^ %^:%^ %^:%^ %^ %^ %^ "%r" %s %^:%^ %^ {%h|%^} %^ %^ %^' -f haproxy.log

Any help would be greatly appreciated.

**Comment by tsauce** [comment]
When i run that command i see:

A valid date is required.

**Comment by allinurl** [comment]
Please try this, it should do the job:

    goaccess access.log --log-format='%^[ %^[ %^[%x.%^] %^"%r" %s %^ %^{%h|%v} %^=%b %^' --date-format=%s --time-format=%s

**Comment by tsauce** [comment]
Sweet! This works :) Thanks allinurl
