### ISSUE TITLE
hours (visits per day hour, 00-01.. 23-00)

### ISSUE THREAD

**Issue by abgit** [allinurl/goaccess#8]
Another counter and will group hits by hour of day they occur.
Very useful on analytics to study the best hours to apply some strategy.

00: X hits
01: Y hits
..
23: Z hits

What do you think?

**Comment by allinurl** [comment]
The time distribution panel has been implemented. e.g., 00-23

It will be pushed out in the upcoming version, which will be out pretty soon :)

**Comment by deseven** [comment]
Thanks!
