### ISSUE TITLE
Updating GoAccess Homebrew Formula

### ISSUE THREAD

**Issue by millsjustin** [allinurl/goaccess#800]
I think the homebrew formula needs to be updated to match the new ```--enable-geoip=<legacy|mmdb>``` build configurations.

As it stands installing from homebrew with the ```--with-geoip``` option does nothing.

I tried editing the formula and compiling/installing with ```geoip``` and ```--enable-geoip=legacy``` but I got build errors. Then I changed the dependency from ```geoip``` to ```libmaxminddb``` and installed with ```--enable-geoip=mmdb``` and it compiled and installed correctly.

I can help out with this if you would like, but I don't know the process for updating a Homebrew formula.

**Comment by allinurl** [comment]
Thanks for pointing that out and reporting this. It would be great if you could update the formula. I believe you can find it [**here**](https://github.com/Homebrew/homebrew-core/blob/c61e9fc8db79666d0cf7b5036b98e1d5a8ca7ccf/Formula/goaccess.rb) and [here](https://github.com/Homebrew/homebrew-core) are the instructions on how to edit it.

Please submit a PR to the Homebrew/homebrew-core repo, they should be able to merge that.

**Comment by millsjustin** [comment]
I submitted a pull request to homebrew-core with an updated formula.

https://github.com/Homebrew/homebrew-core/pull/14373

**Comment by allinurl** [comment]
Thanks for submitting this. Hopefully they merge it soon! I'll keep an eye on it.

Closing this. Feel free to reopen it if needed.
