### ISSUE TITLE
Piping working only with root?

### ISSUE THREAD

**Issue by froger-me** [allinurl/goaccess#802]
Hello,
I want to generate a real-time html report filtered by date, showing the last 24 hours.

Running the following as the apache user works (report generated - not filtered):
`goaccess /var/log/virtualmin/domain.com_access_log -o /home/user/public_html/goaccess/monitor.html --real-time-html`

Running the following as the apache user works (output of sed, access log filtered):
`sed -n '/'$(date '+%d\/%b\/%Y' -d '24 hours ago')'/,$ p' /var/log/virtualmin/domain.com_access_log`

Running the following as root works (report generated - filtered):
`sed -n '/'$(date '+%d\/%b\/%Y' -d '24 hours ago')'/,$ p' /var/log/virtualmin/domain.com_access_log | goaccess -o /home/user/public_html/goaccess/monitor.html --real-time-html`
edit: the report does not belong to user, and does not update in real time

Running the following as the apache user DOES NOT work (shows goaccess options list/help):
`sed -n '/'$(date '+%d\/%b\/%Y' -d '24 hours ago')'/,$ p' /var/log/virtualmin/domain.com_access_log | goaccess -o /home/user/public_html/goaccess/monitor.html --real-time-html`

As the examples above show, user can:
- write to /home/user/public_html/goaccess/
- read /var/log/virtualmin/domain.com_access_log

Could you please point me to the right direction\?

**Comment by allinurl** [comment]
A few things I'd suggest trying:

1. Please try adding a single dash to goaccess so it knows it should read from the pipe. e.g.,

```
sed -n '/'$(date '+%d\/%b\/%Y' -d '24 hours ago')'/,$ p' /var/log/virtualmin/domain.com_access_log | goaccess -o /home/user/public_html/goaccess/monitor.html --real-time-html -
```

2. What's the output of running the following command as the apache user?
```
sed -n '/'$(date '+%d\/%b\/%Y' -d '24 hours ago')'/,$ p' /var/log/virtualmin/domain.com_access_log
```

3. Are you able to create a file as the apache user under that directory?

```
sed -n '/'$(date '+%d\/%b\/%Y' -d '24 hours ago')'/,$ p' /var/log/virtualmin/domain.com_access_log > /home/user/public_html/goaccess/
```

4. I'd start with the basics, try reading the file directly from goaccess as the apache user and see if it works or checking the output you get, e.g.,
```
goaccess /var/log/virtualmin/domain.com_access_log -o /home/user/public_html/goaccess/monitor.html --real-time-html
```

**Comment by froger-me** [comment]
Hi allinurl,

Thank you for the quick answer. It was the single dash to read through the pipe.


My bad, it was in the documentation... As it was working with the root user, I didn't think about going back and check. Sorry for the trouble.
Moreover, --real-time cannot work because the source of the log read is the result of sed, which contrary to the access_log file itself doesn't change over time - it's the one time result of the sed command -_-' ; not sure why I didn't think of it.

**Comment by allinurl** [comment]
Glad you were able to figure it out.

If you are looking for real-time filtering, please take a look at the examples using `tail -f` on the [**man page**](https://goaccess.io/man#examples). 

Closing this, feel free to reopen it if needed.
