### ISSUE TITLE
Log format matching problem

### ISSUE THREAD

**Issue by Kinganmi** [allinurl/goaccess#806]
```
20170608130017 222.94.248.183 xfzdl2.haowanyou.com /PalaceM2_cn_cn/S180039901/HttpRoot/1.2.2/31.pkg?17060807 236388 120 2 206 NULL 54 "NULL" "0-" GET HTTP/1.1 hit
20170608130157 	117.169.78.10 xfzdl2.haowanyou.com /PalaceM2_cn_cn/S180049901/HttpRoot/1.2.6/2.pkg?17060807 770998 1465 1046 206 NULL 75 "NULL" "0-" GET HTTP/1.1 hit
```

`goaccess -f qcloudcdn.log --log-format='%d%t %h %v %U %b %~ %~ %s %R %T "%u" "%~" %H %~' --date-format='%Y%m%d' --time-format='%H%M%S' -d -a > test.html`

**I use this order to analyze the generated html, no content, please help to see if it is wrong, Tks**

**Comment by allinurl** [comment]
This should do it:

    goaccess access.log --log-format='%x %h %v %U %b %^ %^ %s %R %L "%u" %^ %m %H %^' --date-format=%Y%m%d%H%M%S --time-format=%Y%m%d%H%M%S

**Comment by Kinganmi** [comment]
**The problem has been resolved, thank you very much for your reply, TKS**
