### ISSUE TITLE
goaccess 1.2 for alpine in docker seems not support TLS/SSL

### ISSUE THREAD

**Issue by pityonline** [allinurl/goaccess#807]
Hi, I'm running a docker from **allinurl/goaccess**, `docker logs xxx` shows this message:

```
/usr/bin/goaccess: unrecognized option: ssl-cert
2017-06-14 13:32:56,321 INFO exited: goaccess (exit status 1; not expected)
2017-06-14 13:32:56,321 INFO exited: goaccess (exit status 1; not expected)
2017-06-14 13:32:57,322 INFO gave up: goaccess entered FATAL state, too many start retries too quickly
2017-06-14 13:32:57,322 INFO gave up: goaccess entered FATAL state, too many start retries too quickly
```

So I executed the following command in the container, and I got these infomation:

```
/opt # goaccess --ssl-key
goaccess: unrecognized option: ssl-key
/opt # goaccess --ssl-cert
goaccess: unrecognized option: ssl-cert
/opt # goaccess --ssl-key
goaccess: unrecognized option: ssl-key
/opt # goaccess -V
GoAccess - 1.2.
For more details visit: http://goaccess.io
Copyright (C) 2009-2016 by Gerardo Orellana
/opt # cat /etc/issue
Welcome to Alpine Linux 3.6
Kernel \r on an \m (\l)
```

Please check if this version was compiled without `--with-openssl` option? Thanks.

**Comment by allinurl** [comment]
Thanks for pointing this out. From the [**APKBUILD**](https://git.alpinelinux.org/cgit/aports/tree/main/goaccess/APKBUILD?h=3.6-stable) file, it looks like it was not built with SSL/TLS support. Please feel free to submit a PR or an issue on the [**Alpine aports repo**](https://github.com/alpinelinux/aports).

**Comment by allinurl** [comment]
Just adding a note, the new Docker build should let you do this. Please refer to the [**Docker instructions**](https://github.com/allinurl/goaccess#docker).
