### ISSUE TITLE
IIS custom log format

### ISSUE THREAD

**Issue by zhibolau** [allinurl/goaccess#809]
hi

could u plz tell me the formats for this iis log? i have tried others, but none of em worked for me. thanks in advance

```
#Fields: date time s-ip cs-method cs-uri-stem cs-uri-query s-port cs-username c-ip cs(User-Agent) sc-status sc-substatus sc-win32-status time-taken
2017-06-09 00:48:08 165.216.54.132 POST /kkkA/_sadf_bas/asdfI/Prasdfsdfasdfver.sasdc - 80 - 165.223.53.234 - 401 0 0 15
```

i tried below but i got :

```
+------------------------------------------------------------------+
| Token '0' doesn't match specifier '%s'                    |
| Token '1' doesn't match specifier '%s'                    |
| Token '0' doesn't match specifier '%s'                    |
| Token '0' doesn't match specifier '%s'                    |
| Token '0' doesn't match specifier '%s'                    |
| Token '1' doesn't match specifier '%s'                    |
| Token '0' doesn't match specifier '%s'                    |
| Token '0' doesn't match specifier '%s'                    |
| Token '0' doesn't match specifier '%s'                    |
| Token '1' doesn't match specifier '%s'                    |
+------------------------------------------------------------------+
```
goaccess formats

```
log-format %d %t %^ %m %U %q %^ %^ %h %u %R %s %^ %^ %L
time-format %H:%M:%S
date-format %Y-%m-%d
```

**Comment by allinurl** [comment]
Please try this:

    goaccess log --log-format='%d %t %^ %m %U %q %^ %e %h %u %s %^ %^ %L' --date-format=%Y-%m-%d --time-format=%T --http-protocol=no --ignore-panel=REFERRING_SITES

**Comment by zhibolau** [comment]
WORKED LIKE A CHARM!!!!!!!!!!

**Comment by leticiaalmeida** [comment]
Hi,
I'm having a similar issue trying to parse my IIS log, I'm not getting the Time Taken in the graphs.
I have this format:
#Fields: date time s-ip cs-method cs-uri-stem cs-uri-query s-port cs-username c-ip cs(User-Agent) sc-status sc-substatus sc-win32-status time-taken
2017-07-11 00:00:01 XXX.XXX.X.XXX POST /dsjsk fmt=json 443 - XXX.XX.XX.XX Apache-HttpClient/UNAVAILABLE+(java+1.4) 200 0 0 7971
And I've tried goaccess -f log --log-format='%d %t %^ %m %U %q %^ %e %h %u %s %^ %^ %L' --date-format=%Y-%m-%d --time-format=%T --http-protocol=no --ignore-panel=REFERRING_SITES
Can someone help me with that?
