### ISSUE TITLE
Unable to open fifo out: No such device or address. 

### ISSUE THREAD

**Issue by jcfromkc** [allinurl/goaccess#811]
I'm using Centos 7. I just installed GoAccess on a fresh new web server running Apache. When I run the command 

goaccess -f /var/log/httpd/access_log -o /var/www/html/report.html --real-time-html

I receive the following error message. 

Unable to open fifo out: No such device or address.

I'm able to go to mydomain.com/report.html and see a snapshot of my stats. Its not real-time as shown in your example. 

I ran across an article that said to run --enable-debug but I don't know where and how to run this command. When I append it to the "goaccess -f /var/log/httpd/access_log -o /var/www/html/report.html --real-time-html" command it gives me an error message. 

Is GoAccess compatible with Centos 7? If so, will you please point me in the right direction to get past this error message?

Thx, JC

**Comment by allinurl** [comment]
Which version are you using? I believe this may have been fixed on a previous release.

**Comment by jcfromkc** [comment]
I used 

yum install goaccess -y

to install it using the repo.

**Comment by allinurl** [comment]
Please try using the latest version. Here are the [**instruction**](https://goaccess.io/download#installation) to build from source.

**Comment by jcfromkc** [comment]
It appears to be working now!!! Thank you for your assistance. 

Below are the commands I used on Centos 7 to get it working. 

yum groupinstall "Development tools"
yum install GeoIP-devel
yum install ncurses*

wget http://tar.goaccess.io/goaccess-1.2.tar.gz
tar -xzvf goaccess-1.2.tar.gz
cd goaccess-1.2/
./configure --enable-utf8 --enable-geoip=legacy
make
make install

/usr/local/etc/goaccess.conf

(Uncommented)
time-format %H:%M:%S
date-format %d/%b/%Y
log-format %h %^[%d:%^] "%r" %s %b "%R" "%u"

goaccess -f /var/log/httpd/access_log -o /var/www/html/report.html --real-time-html

Thank you for creating this amazing program and supporting it!! 

Thanks again, JC

**Comment by allinurl** [comment]
Glad that worked! Closing this.

**Comment by willhains** [comment]
I'm having this same issue with GoAccess 1.2. Can it run alongside Apache?

**Comment by allinurl** [comment]
@willhains It should work alongside with Apache. I'd say please update to v1.3 and try again. Please also ensure you have a valid certificate if using an encrypted connection and that you are using `wss`. Also, take a look at the browser's console and see what's reporting.
