### ISSUE TITLE
Incorrect time on Real-Time HTML Report

### ISSUE THREAD

**Issue by jcfromkc** [allinurl/goaccess#812]
The real-time HTML stats show the time as Last Updated: 2017-06-16 17:34:33 +0000.

On Centos 7 when I run "timedatectl" it shows:

Local time: Fri 2017-06-16 13:12:46 CDT
Universal time: Fri 2017-06-16 18:12:46 UTC
RTC time: Fri 2017-06-16 13:12:46
Time zone: America/Chicago (CDT, -0500)
NTP enabled: yes
NTP synchronized: yes
RTC in local TZ: yes
DST active: yes

How do I correct the Time Zone for GoAccess? 

Thanks for all your help..

**Comment by allinurl** [comment]
The time displayed in your report is the localtime of your machine. What's the output of `date`?

**Comment by jcfromkc** [comment]
Fri Jun 16 13:39:04 CDT 2017

**Comment by jcfromkc** [comment]
Please close. A server reboot fixed this issue.
