### ISSUE TITLE
Can't build from git (gettext)

### ISSUE THREAD

**Issue by albjeremias** [allinurl/goaccess#814]
```
make  all-recursive
make[1]: Entering directory '/home/ajeremias/git/goaccess'
Making all in po
make[2]: Entering directory '/home/ajeremias/git/goaccess/po'
test ! -f ./goaccess.pot || \
  test -z "fr.gmo" || make fr.gmo
make[3]: Entering directory '/home/ajeremias/git/goaccess/po'
rm -f fr.gmo && : -c --statistics --verbose -o fr.gmo fr.po
mv: cannot stat ‘t-fr.gmo’: No such file or directory
Makefile:169: recipe for target 'fr.gmo' failed
make[3]: *** [fr.gmo] Error 1
make[3]: Leaving directory '/home/ajeremias/git/goaccess/po'
Makefile:206: recipe for target 'stamp-po' failed
make[2]: *** [stamp-po] Error 2
make[2]: Leaving directory '/home/ajeremias/git/goaccess/po'
Makefile:788: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/ajeremias/git/goaccess'
Makefile:495: recipe for target 'all' failed
make: *** [all] Error 2

```

**Comment by allinurl** [comment]
Please try installing `gettext-dev`. Let me know if that fixes the issue.

**Comment by albjeremias** [comment]
sorry i cant find it... i have gettext installed!
`$ apt-cache search gettext | grep gettext
autopoint - The autopoint program from GNU gettext
gettext - GNU Internationalization utilities
gettext-base - GNU Internationalization utilities for the base system
gettext-doc - Documentation for GNU gettext
gettext-el - Emacs po-mode for editing gettext .po files
libgettextpo-dev - GNU Internationalization library development files
libgettextpo0 - GNU Internationalization library
libgettext-ant-tasks-java - Java classes for internationalization (i18n) - Ant tasks
gettext-lint - Collection of tools for checking PO and POT files
libghc-hgettext-dev - Gettext bindings for haskell
libghc-hgettext-doc - Gettext bindings for haskell; documentation
libghc-hgettext-prof - Gettext bindings for haskell; profiling libraries
i18nspector - checking tool for gettext POT, PO and MO files
libgettext-commons-java - Java classes for internationalization (i18n)
liblocale-gettext-perl - module using libc functions for internationalization in Perl
liblocale-maketext-gettext-perl - Perl module bridging gettext and Maketext localization frameworks
liblocale-po-perl - Perl module for manipulating .po entries from GNU gettext
libgettext-ocaml - OCaml internationalization shared library
libgettext-ocaml-dev - OCaml internationalization library
php-gettext - read gettext MO files directly, without requiring anything other than PHP
po-debconf - tool for managing templates file translations with gettext
poedit - gettext catalog editor
poedit-dbg - gettext catalog editor (debug)
python-polib - Python library to parse and manage gettext catalogs
python-polib-doc - Python library to parse and manage gettext catalogs (documentation)
python3-polib - Python 3 library to parse and manage gettext catalogs
potool - program to aid manipulation of gettext po files
ruby-fast-gettext - Fast GetText implementation for Ruby
ruby-gettext - gettext for Ruby
smarty-gettext - Gettext plugin enabling internationalization in Smarty
`

**Comment by allinurl** [comment]
I don't see `gettext` on the list. Please try this:

    sudo apt-get install libncursesw5-dev libgeoip-dev autoconf autotools-dev gettext autopoint  

and then 

```
$ git clone https://github.com/allinurl/goaccess.git
$ cd goaccess
$ autoreconf -fiv
$ ./configure --enable-utf8 --enable-geoip=legacy
$ make
# make install
```

**Comment by albjeremias** [comment]
it works now...
```bash
The following extra packages will be installed:
  libasprintf-dev libcroco3
Suggested packages:
  gettext-doc
The following NEW packages will be installed:
  gettext libasprintf-dev libcroco3
```
damn.. i tottaly missed it.. it was just gettex... ! thanks! great tool! 👍
