### ISSUE TITLE
Unable to parse log data for custom log

### ISSUE THREAD

**Issue by vijaynaik90** [allinurl/goaccess#815]
Hi,

I am trying to parse Apache Access Logs:
This is my log definition in Apache: 

    %T %D %h %l %u %t %r %s %b %{Referer}i %{User-Agent}i

I am using the following log-format in Goaccess conf file: 

```
log-format %T %D %h %^[%d:%t %^] %m %U %H %s %b %R %u
date-format %d/%b/%Y
time-format %H:%M:%S
```

This is an example log entry from it:

    0.002 2 10.10.10.10 - - [15/Jun/2017:00:00:13 +0000] POST /xyz/org/12/atmosphere/test?checkGlobal=true&checkUser=false&is_passive_request=true HTTP/1.1 200 37 https://abc.xyz.co/ Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.xxxx.xxx Safari/xxx.xx

I am getting **Format Errors - Verify your log/date/time format**

Any idea how to get this to work?

**Comment by allinurl** [comment]
You can try this, however, you won't be able to get the user agent part. If you want to parse the user agent, you will need to have some delimiters around the string, e.g., `"`. I'd also recommend doing the same thing for the referrer and request parts.

    goaccess access.log --log-format='%T %^ %h %^%^[%d:%t %^] %m %U %H %s %b %R %u %^' --date-format=%d/%b/%Y --time-format=%T

**Comment by allinurl** [comment]
Actually you can parse the UA, just run:

    goaccess access.log --log-format='%T %^ %h %^%^[%d:%t %^] %m %U %H %s %b %R %u' --date-format=%d/%b/%Y --time-format=%T

Still, I'd also recommend adding the delimiters around these fields.

**Comment by vijaynaik90** [comment]
Thanks for the reply. It works now! I will keep in mind to add delimiters around the fields as you suggested.
