### ISSUE TITLE
Upload a video on how to setup real-time web stats with GoAccess

### ISSUE THREAD

**Issue by alisafari2017** [allinurl/goaccess#816]
hi 
please install in a video for ubuntu 16.04 and config web browser for run goaccess-1.2 .upload in youtube.

thank you...

**Comment by allinurl** [comment]
Are you having specific questions about configuring real-time HTML stats? Please take a look at the [**FAQ**](https://goaccess.io/faq#html-report) real-time section for more details.

**Comment by allinurl** [comment]
[**This**](https://www.youtube.com/watch?v=OrktSIJJNmg) may give a bit of a hint.I'll post back if a video comes up. Closing this.
