### ISSUE TITLE
date format not working?

### ISSUE THREAD

**Issue by pescobar** [allinurl/goaccess#817]
Hi 

I am trying to parse this apache log with goaccess

```
myvhostdomain.com 50.184.242.221 - - [21/Jun/2017:06:42:16 +0200] "GET /html_contents/css/bootstrap.css HTTP/1.1" 200 127358 "http://myvhostdomain.com/fcgi/xxx" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36"
```

Using this config:

```
log-format %v %h %^ %^ [%d:%t] "%m %U %H" %s %b "%R" "%u"
date-format %d/%h/%Y
time-format %H:%M:%S %z
```

Doing some checks about the log format it seems correct to me

```
$> (date +"%d/%h/%Y:%H:%M:%S %z")
22/Jun/2017:12:51:02 +0200
```

But when I try to parse the log file with goaccess it says the results are for January instead of June. See the attached screenshot:

![goaccess screenshot](https://image.ibb.co/iN5g7k/goaccess.png)

Am I doing something wrong? or is this a bug? I am using GoAccess - 1.2 . Thanks in advance for your help.

**Comment by allinurl** [comment]
Thanks for reporting this. I've pushed a [commit](https://github.com/allinurl/goaccess/commit/5630e301b0aac13a2924fa62a3c98525a4e2f8db) that fixes this issue. Feel free to build from [**development**](https://github.com/allinurl/goaccess#build-from-github-development), otherwise it will be pushed out in the upcoming version.

**Comment by pescobar** [comment]
thanks for the quick fix @allinurl 

do you have any estimation about when the new version will be published?

**Comment by allinurl** [comment]
I'm actually behind on this release. I need to fix a couple more bugs and I'll push it out. Stay tuned :)
