### ISSUE TITLE
Add the ability to handle integer HTTP status codes and -

### ISSUE THREAD

**Issue by zhibolau** [allinurl/goaccess#821]
Hi Bro,

I got tcp listener aws elb log like this:
2017-06-19T06:00:41.850756Z kkk 333.87.128.7:61620 199.18.0.105:443 0.000391 0.000009 0.000012 - 500 688 5471 "- - - " "-" - -
2017-06-19T06:00:41.850756Z kkk 333.87.128.7:61620 199.18.0.105:443 0.000391 0.000009 0.000012 404 - 688 5471 "- - - " "-" - -

As you may notice, in these two lines of logs, the http status code field could be an integer or '-' in the same log file. Now dealing with this situation, I have to set this filed as %^ to ignore it. Could you please add a specifier to handle both integer and '-'?

Thank you in advance.

Best,

Supporter

**Comment by allinurl** [comment]
@zhibolau If it doesn't have a status code, should that be a valid request? How should goaccess handle this? Right now it considers this as an invalid request and ignores it.

**Comment by zhibolau** [comment]
Hi
though the request does not have status code, request is valid. 

thanks
