### ISSUE TITLE
Requests are reducing over time

### ISSUE THREAD

**Issue by stavros-liaskos** [allinurl/goaccess#822]
Question:
I am using goAccess for a production site I have live for some months now.
Furthermore, I have a script that parses the log files and uploads the html report.
Initially everything was working great. On my last report update, I noticed that the requests are actually less for a longer amount of time.

Given that:
1. logs are generated by the apache in an excellent production server from a big enterprise
2. I actually parsed them one by one and the sum is the same small number
3. nothing changed in my script

Could you think of a reason why this happens?

My script for parsing logs:
```bash
ssh <username>@server zcat $APP_PATH'access.http.log.*.gz' >> file.log
ssh <username>@server zcat $APP_PATH'access.https.log.*.gz' >> file.log

ssh <username>@server 'cat '$APP_PATH'access.http.log' >> file.log
ssh <username>@server 'cat '$APP_PATH'access.http.log.1' >> file.log
ssh <username>@server 'cat '$APP_PATH'access.https.log' >> file.log
ssh <username>@server 'cat '$APP_PATH'access.https.log.1' >> file.log

goaccess file.log -o /var/www/ngcc_report.html
```
Logs:
```bash
 $ls -1
access.http.log
access.http.log.1
access.http.log.2.gz
access.http.log.3.gz
access.http.log.4.gz
access.http.log.5.gz
access.https.log
access.https.log.1
access.https.log.2.gz
access.https.log.3.gz
access.https.log.4.gz
access.https.log.5.gz
access.https.log.6.gz
# + error logs
```
Stats:
First 3 months: ~45000 total requests
Last update (first 3 months + 2 more): ~23000 total requests

**Comment by allinurl** [comment]
I'm not sure I follow, do you mean that the number of requests shown in goaccess is decreasing after parsing the concatenated file (file.log)? 

Which storage are you using (`goaccess -s`)? Also can you please verify that the number of requests in your file.log matches the number of requests displayed in goaccess, e.g., `wc -l file.log`? Thanks.

**Comment by stavros-liaskos** [comment]
You can ignore this. GoAccess was right. Also Awstats.
It was strange but I got 1/3 of the total visits in 1/15 of the total time the site was up. 
Apache deleted the logs for these first days so the total requests drop significantly.
