### ISSUE TITLE
Debian stretch is out

### ISSUE THREAD

**Issue by szepeviktor** [allinurl/goaccess#823]
Please consider adding stretch support to deb.goaccess.io
Thanks.

**Comment by szepeviktor** [comment]
Maybe depending on `libssl1.1`

**Comment by allinurl** [comment]
You should be able to pull goaccess from the official repo using stretch. I already have a patch for  libssl1.1, I just need to test it out and I'll push it out soon.

**Comment by szepeviktor** [comment]
> You should be able to pull goaccess from the official repo using stretch.

Thank you.
Do you mean by using `deb http://deb.goaccess.io/ jessie main` ?

**Comment by szepeviktor** [comment]
BTW the <kbd>websocket-server</kbd>may be not appropriate.

**Comment by glic3rinu** [comment]
Hi guys, any update on this one? upgrading to stretch is painful if you are using the TCB version

**Comment by allinurl** [comment]
Alright, I've built v1.2 for stretch. Please give this a shot per this [**instructions**](https://goaccess.io/download#official-repo) and let me know if that solves the issue. Thanks!

**Comment by szepeviktor** [comment]
Thank you. It work.

Please consider adding `--enable-tcb=btree` as in [the official Debian package](https://anonscm.debian.org/cgit/collab-maint/goaccess.git/tree/debian/rules#n10).

**Comment by szepeviktor** [comment]
Actually on top of the Debian package this is my packaging script which adds UTF-8 support and higher MAX_IGORE_IPS: https://github.com/szepeviktor/debian-server-tools/blob/master/package/docker-backport-goaccess.sh

**Comment by allinurl** [comment]
@szepeviktor Not sure I understand, running `apt-get install goaccess-tcb` should let you download the btree version.

Is that a patch to increase MAX_IGNORE_IPS? If it is, could you please send a PR so I can merge it?

**Comment by szepeviktor** [comment]
> running apt-get install goaccess-tcb should let you download the btree version.

I didn't know about that!

**Comment by szepeviktor** [comment]
That *patch* changes [64](https://github.com/allinurl/goaccess/blob/b89f50865fa0718fd3151c0288e5d32364a71702/src/settings.h#L38) to 1152.

Have anyone ever complained about raising it??
[I exclude big CDN-s and monitoring IP-s.](https://github.com/szepeviktor/debian-server-tools/blob/master/webserver/goaccess.sh#L18)

**Comment by allinurl** [comment]
@szepeviktor If your patch it's only about increasing the number of `MAX_IGNORE_IPS`, I just pushed a [commit](https://github.com/allinurl/goaccess/commit/4bbe73dc9de1533e29da0b18424dd179c2b984f1) that do so. Thanks for the heads up!

**Comment by szepeviktor** [comment]
Thank you. 

-- 
+36204242498
Ezen a készüléken sok az elütés. 
Elnézést!
