### ISSUE TITLE
Feed HAProxy logs to GoAccess using remote Rsyslog

### ISSUE THREAD

**Issue by jazzl0ver** [allinurl/goaccess#824]
Just wanted to share how to show realtime stats from remote HAProxy servers with GoAccess.
HAProxy server settings (rsyslog v5):
```
# cat /etc/haproxy/haproxy.cfg
global
    log 127.0.0.1:514 local0
...
# cat /etc/rsyslog.d/haproxy.conf
$ModLoad imudp
$UDPServerRun 514
$MaxMessageSize 64k
$template Haproxy,"%timegenerated%%msg%\n"
local0.=info @mygoaccesshost
local0.=info -/var/log/haproxy/haproxy.log;Haproxy
local0.notice -/var/log/haproxy/haproxy-status.log;Haproxy
local0.* ~
```
GoAccess server (rsyslog v8):
```
# cat /etc/rsyslog.d/haproxy.conf
$ModLoad imudp
$UDPServerRun 514
$MaxMessageSize 64k
$ModLoad omuxsock
$OMUxSockSocket /tmp/haproxy.sock
$template Haproxy,"%timegenerated%%msg%\n"
$OMUxSockDefaultTemplate Haproxy
local0.info :omuxsock:
local0.* stop

# crontab -l
@reboot /usr/bin/goaccess - --port=7890 -o /var/www/html/report.html --keep-db-files --load-from-disk --db-path=/var/lib/goaccess/ --compression bz2 --real-time-html --daemonize < <(/usr/bin/socat -u UNIX-RECV:/tmp/haproxy.sock -)
```
For some reason socat does not live long, so I had to add this line to the crontab:
```
0 0 * * * killall goaccess; killall socat; /usr/bin/goaccess - --port=7890 -o /var/www/html/report.html --keep-db-files --load-from-disk --db-path=/var/lib/goaccess/ --compression bz2 --real-time-html --daemonize < <(/usr/bin/socat -u UNIX-RECV:/tmp/haproxy.sock -)
```

**Comment by allinurl** [comment]
Awesome, thanks for sharing this. I'll keep it open for sometime so it serves as a reference!

**Comment by jazzl0ver** [comment]
Thank you man for the awesome tool!

**Comment by atomi** [comment]
Are you using `option httplog clf` in haproxy.conf?

I'm trying to just read an haproxy.log file using cli `goaccess haproxy.log` and using `option httplog clf` and I get invalid token terrors. I also tried just `$template Haproxy,"%msg%\n"`

**Comment by allinurl** [comment]
@atomi Sounds like a log-format issue. Can you please describe the fields from your sample log above?

**Comment by atomi** [comment]
It's default CLF. My intent is to not use custom log formats.

http://cbonte.github.io/haproxy-dconv/1.6/configuration.html#4-option%20httplog
> clf       if the "clf" argument is added, then the output format will be
          the CLF format instead of HAProxy's default HTTP format. You can
          use this when you need to feed HAProxy's logs through a specific
          log analyser which only support the CLF format and which is not
          extensible.

**Comment by allinurl** [comment]
@atomi this should do it (assuming clf and ignoring the rest of the fields):

    goaccess haproxy.log --log-format='%h %^[%d:%t %^] "%r" %s %b %^' --date-format=%d/%b/%Y --time-format=%T

There's no default haproxy log-format so far. Do you know how the default log-format looks like? I can probably add it to the predefined list.

**Comment by atomi** [comment]
> There's no default haproxy log-format so far. Do you know how the default log-format looks like? I can probably add it to the predefined list.

Shouldn't the haproxy clf format work with the existing predefined clf parser in goaccess?

**Comment by allinurl** [comment]
The default clf in goaccess looks for \0 or a LF (Line feed, '\n'), however, the haproxy log has some additional fields after the number of bytes read.
