### ISSUE TITLE
Include HTTP 429 Too many Requests?

### ISSUE THREAD

**Issue by tsauce** [allinurl/goaccess#825]
Would it be possible to include HTTP code 429 Too many requests?

**Comment by allinurl** [comment]
This has been added. It will be pushed out in the upcoming version. Thanks!

**Comment by tsauce** [comment]
Gerardo,

Are you going to cut a new version that includes this HTTP 429 in the
tar.gz version located here:  http://tar.goaccess.io/goaccess-1.2.tar.gz
anytime in the near future ?

**Comment by allinurl** [comment]
Certainly I will. I'm in the process of implementing #334 and if by then I'm unable to reproduce #708, I will be pushing out the next version soon, especially since this release is way behind - the upcoming release will ship this request.

**Comment by tsauce** [comment]
Thanks much! In the meantime the workaround was to just compile from latest
master.

Having these stats makes forecasting so much better. Thanks much amigo!
