### ISSUE TITLE
NGINX Combined Log Format

### ISSUE THREAD

**Issue by dkelbley** [allinurl/goaccess#827]
I have the following NGINX custom log format:
```
log_format '$remote_addr - $remote_user [$time_local]  "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent" $request_time';
```
However, I can't get the following syntax to work:
```
goaccess -f access.log --log-format='%h %^[%d:%t %^] "%r" %s %b "%R" "%u" %T^' --date-format=%d/%b/%Y --time-format=%T
```
Sample data:
```
127.55.39.73 - - [29/Jun/2017:00:00:13 -0500] "GET /channels/usa/photos/2015.jpg HTTP/1.1" 200 15356 "-"
```
Any thoughts on what I'm doing wrong?

**Comment by allinurl** [comment]
The sample line you posted doesn't have enough fields to match the log format from nginx (no UA, referer, request time). Do most of the lines in your access log look like the one you posted above? Are you sure you are not using some other log_format in your nginx config file?

**Comment by dkelbley** [comment]
Good point!  Let's try this sample data instead...

84.201.133.54 - - [29/Jun/2017:00:00:13 -0500]  "GET /usa/video_files/f4cbb696-c030-4f81-b17d-9d6c00b42c31.mp4 HTTP/1.1" 200 99048 "-" "Mozilla/5.0 (compatible; YandexVideoParser/1.0; +http://yandex.com/bots)" 0.570

62.138.14.39 - - [29/Jun/2017:00:00:13 -0500]  "GET /es/2015-kit/photos/21 HTTP/1.1" 200 16407 "-" "Linguee Bot (http://www.linguee.com/bot; bot@linguee.com)" 4.100

69.191.249.201 - - [29/Jun/2017:00:00:13 -0500]  "GET /en-US/usa/releases HTTP/1.1" 200 18843 "-" "BLP_bbot/0.1" 0.064

40.77.167.132 - - [29/Jun/2017:00:00:13 -0500]  "GET /CA/coupe-12?page=1460 HTTP/1.1" 200 15446 "-" "
Mozilla/5.0 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)" 2.623

**Comment by allinurl** [comment]
Please note the extra space you have between the date and the first quote of the request. This should work:

    goaccess access.log --log-format='%h %^[%d:%t %^]  "%r" %s %b "%R" "%u" %T' --date-format=%d/%b/%Y --time-format=%T

**Comment by dkelbley** [comment]
Many thanks for all of your help and assistance!  This is exactly what I needed!!!!!!!!!!
