### ISSUE TITLE
gzip: stdout: Broken pipe

### ISSUE THREAD

**Issue by thushan85** [allinurl/goaccess#828]
Hi @allinurl 

I'm getting an error when I'm using zcat

Command: zcat  [path_to access_log_file.gz] | goaccess  

Error: gzip: stdout: Broken pipe

It would be great if you can help on this

Thank you!

**Comment by allinurl** [comment]
@thushan85 Did you set your log-format, date-format and time-format variables? If you did and your config file is being loaded, then,  I'd need to more info on how to reproduce this from my side. 

1. Are you using bash or something else? 
2. Does it work sometime or it fails all the time?
3. Which version of goaccess are using and your system as well? If not in v1.2 of goaccess, please update to the latest.
4. Please attach your config file.

**Comment by thushan85** [comment]
Hi @allinurl 

Complete command
`zcat -f /home/thushan/data/access_log_files/accesslog_06272017.gz | /home/thushan/goaccess/bin/goaccess --log-format='COMBINED'  --date-format='%d/%b/%Y'  --time-format='%T' -a -o /home/thushan/analyzer/data/html/out.html --hour-spec=min`

1.  Yes I'm using a nodejs app to execute goaccess tool 
(use `require('child_process').exec `to execute cli commands)

2. Yes It's working fine when I start my app in interactive mode (e.g `node app.js`) But it doesn't work with PM2 or forever mode.

3. Goaccess version is v1.2

Thanks you for the quick response :)

**Comment by allinurl** [comment]
Thanks for the reply. I'm not sure if nodejs is giving you a terminal, but I'd try adding a single dash to goaccess so it knows that it should read from the pipe. e.g. (note the dash at the end),

    zcat -f /home/thushan/data/access_log_files/accesslog_06272017.gz | /home/thushan/goaccess/bin/goaccess --log-format='COMBINED' --date-format='%d/%b/%Y' --time-format='%T' -a -o /home/thushan/analyzer/data/html/out.html --hour-spec=min -

Let me know if that helps

**Comment by thushan85** [comment]
Hi @allinurl 

It's worked for me. It's a miracle fix..:). Thank you very much. Actually what does happen by adding single dash to the end?

Thank you again :+1:

**Comment by allinurl** [comment]
Glad that did it! 

The `-` single dash was added recently per convention to let goaccess know that it should read from the standard input. There's a more detailed explanation on issue #647.

**Comment by xiaoqiang1999** [comment]
> Thanks for the reply. I'm not sure if nodejs is giving you a terminal, but I'd try adding a single dash to goaccess so it knows that it should read from the pipe. e.g. (note the dash at the end),
> 
> ```
> zcat -f /home/thushan/data/access_log_files/accesslog_06272017.gz | /home/thushan/goaccess/bin/goaccess --log-format='COMBINED' --date-format='%d/%b/%Y' --time-format='%T' -a -o /home/thushan/analyzer/data/html/out.html --hour-spec=min -
> ```
> 
> Let me know if that helps

I have a similar problem，when running the nodejs program with PM2, goaccess cannot read data from the pipeline:
``shell
zcat access.log.gz | goaccess -o xxx.json // Spawn method error for nodejs: Error: write EPIPE
``
At first I thought it was a PM2 problem,
Now, when I add '-', goaccess works! Thank you very much!
``shell
zcat access.log.gz | goaccess -o xxx.json -
``

我也有类似的问题，当使用PM2运行nodejs程序时，goaccess无法从管道中读取数据：
``shell
zcat access.log.gz | goaccess -o xxx.json // nodejs的spawn方法报错：Error: write EPIPE
``
一开始我以为是PM2的问题，
当我添加“-”时，goaccess正常工作了！非常感谢你！
``shell
zcat access.log.gz | goaccess -o xxx.json -
``
