### ISSUE TITLE
Can't seem to get logformat to match what I have

### ISSUE THREAD

**Issue by tnetservices** [allinurl/goaccess#831]
I can't seem to get logformat to match what I have.

Output:
`105.224.241.57 [105-224-241-57.south.dsl.telkomsa.net] - - [26/Jun/2017:20:34:46 +0000] "GET /favicon.ico HTTP/1.1" 200 2238 "https://www.tnet.com/home/files/config.txt" "Mozilla/5.0 (X11; Linux armv7l) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.84 Safari/537.36"`

Which is defined in my configuration as:
`CustomLog       /www/logs/vhost.combined "%a [%h] %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-agent}i\""`

**Comment by allinurl** [comment]
Please try:

    goaccess access.log --log-format='%h %] %^[%d:%t %^] "%r" %s %b "%R" "%u"' --date-format=%d/%b/%Y --time-format=%T

**Comment by tnetservices** [comment]
Bingo... thanks!
