### ISSUE TITLE
segfault with tcb on docker

### ISSUE THREAD

**Issue by coldfix** [allinurl/goaccess#832]
goaccess crashes on startup when built with `--enable-tcb=btree` in alpine OS docker environment (migrated from #795).

Use the following Dockerfile to build a goaccess image from the current working directory:

```Dockerfile
FROM alpine:edge

COPY . /goaccess
WORKDIR /goaccess

ARG TCB=tokyocabinet-1.4.48
ARG TCB_URL=http://fallabs.com/tokyocabinet/$TCB.tar.gz

ARG test_deps="bash vim"
ARG build_deps="build-base ncurses-dev autoconf automake git gettext-dev wget"
ARG runtime_deps="tini ncurses libintl gettext zlib libbz2 zlib-dev bzip2-dev"

RUN apk update && \
    apk add -u $runtime_deps $build_deps $test_deps && \
    ([ -d $TCB ] || wget $TCB_URL && tar -xzf $TCB.tar.gz) && \
    cd $TCB && ./configure --prefix=/usr --enable-off64 --enable-fastest && \
    make && make install && cd .. && \
    autoreconf -fiv && \
    ./configure --enable-utf8 --enable-tcb=btree && \
    make && \
    make install && \
    cd /

EXPOSE 7890

ENTRYPOINT ["/sbin/tini", "--"]
CMD ["goaccess", "--no-global-config", "--config-file=/srv/data/goaccess.conf", "-l", "/srv/data/logfile.txt"]
```

(it is modified/simplified a bit for testing, so please don't integrate this directly into master)

Assuming it is saved in the root directory of goaccess as `Dockerfile.tcb` it can be built as follows:

```bash
docker build -t goaccess_tcb -f Dockerfile.tcb .
```

Now, setup configuration files for testing:

```bash
mkdir -p srv/{data,logs,report}

cp /var/log/nginx/access.log srv/logs

cat <<EOF >srv/data/goaccess.conf
time-format %H:%M:%S
date-format %d/%b/%Y
log-format %h %^[%d:%t %^] "%r" %s %b "%R" "%u"
log-file /srv/logs/access.log
output /srv/report/index.html

keep-db-files true
load-from-disk true
db-path /srv/data/
EOF
```

Upon running as follows:

```
docker run \
    -v `pwd`/srv:/srv \
    --name goaccess_tcb \
    goaccess_tcb
```

It shows the following error:

```
==5== GoAccess 1.2 crashed by Sig 11
==5==
==5== VALUES AT CRASH POINT
==5==
==5== Line number: 0
==5== Offset: 0
==5== Invalid data: 0
==5== Piping: 0
==5== Response size: 0 bytes
==5==
==5==
==5== Please report it by opening an issue on GitHub:
==5== https://github.com/allinurl/goaccess/issues
```

It could very well be that the error occurs due to some fault in my install process or config file.

Otherwise, it might also be an issue, specifically occuring in the alpine-os environment. In this case, It might be useful to switch into the docker container and try things interactively.

## Docker/Debug

I have compiled a few notes for convenience (I tend to forget the exact commands, have to look them up or remember which folders should go where, etc...):

Run container interactively:

```
docker rm goaccess_tcb
docker run \
    -v `pwd`/srv:/srv \
    --name goaccess_tcb \
    -it goaccess_tcb bash
```

and then run goaccess/inspect logfiles/install packages/rebuild/... from there, e.g.:

```
# apk add -u PACKAGE
# goaccess --no-global-config -p /srv/data/goaccess.conf -l /srv/data/logfile.txt
```

Alpine Package index: https://pkgs.alpinelinux.org/packages

Best, Thomas

**Comment by allinurl** [comment]
The on-disk storage issue has been addressed. It now supports native on-disk persistence storage (no dependencies). New command line options are `--persist`, `--restore`, `--keep-last=<num_days>`. It also adds the ability to re-parse the same log(s) without counting data twice (see #334 or for exact details [**this post**](https://github.com/allinurl/goaccess/issues/334#issuecomment-272317226)).

This will be pushed out in the upcoming release. However, it would be great if you could test this out before deployment by building from [**development**](https://github.com/allinurl/goaccess#build-from-github-development).

Closing this as fixed. Feel free to post back as needed.
