### ISSUE TITLE
How to set GoAccess live web user interface

### ISSUE THREAD

**Issue by ofog-bartar** [allinurl/goaccess#834]
Hello;
I wanted to know if I can have the web active monitoring for goaccess from the web browser. (i.e dashboard)
right now I am trying to have apache access logs html file generated but I get this:
```
goaccess  --no-global-config -f /var/log/apache2/new_megapaper_access.log > report.html

GoAccess - version 1.2 - Mar  7 2017 06:40:58
Config file: No config file used

Fatal error has occurred
Error occured at: src/parser.c - parse_log - 2705
No time format was found on your conf file.

```

I tried with all variable and no luck. (I don't have /etc/goaccess.conf)
Plz advise! 
thanks

**Comment by allinurl** [comment]
Yes, you certainly can. Please take a look at the [**FAQ**](https://goaccess.io/faq#html-report) and [**Man**](https://goaccess.io/man#examples) page for more details and examples. Feel free to post any questions you may have.

**Comment by ofog-bartar** [comment]
GoAccess - version 1.2 - Mar  7 2017 06:40:58
Config file: /etc/goaccess.conf

Fatal error has occurred
Error occured at: src/parser.c - parse_log - 2705
No time format was found on your conf file.

**Comment by ofog-bartar** [comment]
I guess I need a way to tell goaceess what kind of log file that is. (which is Apache acess log.)

**Comment by allinurl** [comment]
That's right, under ` /etc/goaccess.conf` please set, `log-format`, `date-format` and `time-format` based on your access log format. Feel free to post a few lines from your access log if you need help to figure the log-format.

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it as needed.

**Comment by Jamalc0m** [comment]
same issue here, the tool is installed on mac and trying to access the apache log on ubuntu through ssh.

**Comment by allinurl** [comment]
@Jamalc0m Please post a few sample lines from your log and I'll post the command you need to run to get it working.

**Comment by Jamalc0m** [comment]
Here you go
Gecko/62.0 Firefox/62.0"
162.158.150.25 - - [25/Oct/2018:15:29:55 +0300] "GET /CodeIgniter3/js/spectragram.min.js HTTP/1.1" 200 2390 "https://cccc.com/CodeIgniter3/" "Mozilla/5.0 (Android 6.0.1; Mobile; rv:62.0) Gecko/62.0 Firefox/62.0"
162.158.150.7 - - [25/Oct/2018:15:29:56 +0300] "GET /CodeIgniter3/js/smooth-scroll.min.js HTTP/1.1" 200 3099 "https://cccc.com/CodeIgniter3/" "Mozilla/5.0 (Android 6.0.1; Mobile; rv:62.0) Gecko/62.0 Firefox/62.0"
::1 - - [25/Oct/2018:15:29:56 +0300] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.18 (Ubuntu) OpenSSL/1.0.2g (internal dummy connection)"
162.158.150.115 - - [25/Oct/2018:15:29:56 +0300] "GET /CodeIgniter3/js/scripts.js HTTP/1.1" 200 13679 "https://cccc.co/CodeIgniter3/" "Mozilla/5.0 (Android 6.0.1; Mobile; rv:62.0) Gecko/62.0 Firefox/62.0"
::1 - - [25/Oct/2018:15:29:57 +0300] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.18 (Ubuntu) OpenSSL/1.0.2g (internal dummy connection)"
::1 - - [25/Oct/2018:15:29:58 +0300] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.18 (Ubuntu) OpenSSL/1.0.2g (internal dummy connection)"
::1 - - [25/Oct/2018:15:29:59 +0300] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.18 (Ubuntu) OpenSSL/1.0.2g (internal dummy connection)"
::1 - - [25/Oct/2018:15:30:00 +0300] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.18 (Ubuntu) OpenSSL/1.0.2g (internal dummy connection)"
::1 - - [25/Oct/2018:15:30:01 +0300] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.18 (Ubuntu) OpenSSL/1.0.2g (internal dummy connection)"
::1 - - [25/Oct/2018:15:30:02 +0300] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.18 (Ubuntu) OpenSSL/1.0.2g (internal dummy connection)"
::1 - - [25/Oct/2018:15:30:03 +0300] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.18 (Ubuntu) OpenSSL/1.0.2g (internal dummy connection)"
::1 - - [25/Oct/2018:15:30:04 +0300] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.18 (Ubuntu) OpenSSL/1.0.2g (internal dummy connection)"
::1 - - [25/Oct/2018:15:30:05 +0300] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.18 (Ubuntu) OpenSSL/1.0.2g (internal dummy connection)"
::1 - - [25/Oct/2018:15:30:06 +0300] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.18 (Ubuntu) OpenSSL/1.0.2g (internal dummy connection)"
::1 - - [25/Oct/2018:15:30:07 +0300] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.18 (Ubuntu) OpenSSL/1.0.2g (internal dummy connection)"
::1 - - [25/Oct/2018:15:30:08 +0300] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.18 (Ubuntu) OpenSSL/1.0.2g (internal dummy connection)"
::1 - - [25/Oct/2018:15:30:09 +0300] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.18 (Ubuntu) OpenSSL/1.0.2g (internal dummy connection)"
::1 - - [25/Oct/2018:15:30:10 +0300] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.18 (Ubuntu) OpenSSL/1.0.2g (internal dummy connection)"
::1 - - [25/Oct/2018:15:30:11 +0300] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.18 (Ubuntu) OpenSSL/1.0.2g (internal dummy connection)"
::1 - - [25/Oct/2018:15:30:12 +0300] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.18 (Ubuntu) OpenSSL/1.0.2g (internal dummy connection)"
::1 - - [25/Oct/2018:15:30:13 +0300] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.18 (Ubuntu) OpenSSL/1.0.2g (internal dummy connection)"
::1 - - [25/Oct/2018:15:30:14 +0300] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.18 (Ubuntu) OpenSSL/1.0.2g (internal dummy connection)"
::1 - - [25/Oct/2018:15:30:15 +0300] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.18 (Ubuntu) OpenSSL/1.0.2g (internal dummy connection)"
::1 - - [25/Oct/2018:15:30:16 +0300] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.18 (Ubuntu) OpenSSL/1.0.2g (internal dummy connection)"
::1 - - [25/Oct/2018:15:30:17 +0300] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.18 (Ubuntu) OpenSSL/1.0.2g (internal dummy connection)"
::1 - - [25/Oct/2018:15:30:18 +0300] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.18 (Ubuntu) OpenSSL/1.0.2g (internal dummy connection)"
::1 - - [25/Oct/2018:15:30:19 +0300] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.18 (Ubuntu) OpenSSL/1.0.2g (internal dummy connection)"
::1 - - [25/Oct/2018:15:30:20 +0300] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.18 (Ubuntu) OpenSSL/1.0.2g (internal dummy connection)"
::1 - - [25/Oct/2018:15:30:21 +0300] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.18 (Ubuntu) OpenSSL/1.0.2g (internal dummy connection)"
162.158.150.49 - - [25/Oct/2018:15:30:53 +0300] "GET /CodeIgniter3/ HTTP/1.1" 200 7709 "https://cccc.co/CodeIgniter3/" "Mozilla/5.0 (Android 6.0.1; Mobile; rv:62.0) Gecko/62.0 Firefox/62.0"
92.112.19.217 - - [25/Oct/2018:15:31:47 +0300] "GET / HTTP/1.1" 200 543 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/601.7.7 (KHTML, like Gecko) Version/9.1.2 Safari/601.7.7"
172.68.62.115 - - [25/Oct/2018:15:32:20 +0300] "GET / HTTP/1.1" 200 522 "https://github.com//cccc" "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:63.0) Gecko/20100101 Firefox/63.0"
172.68.62.49 - - [25/Oct/2018:15:32:21 +0300] "GET /favicon.ico HTTP/1.1" 404 507 "-" "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:63.0) Gecko/20100101 Firefox/63.0"
162.158.154.136 - - [25/Oct/2018:15:41:41 +0300] "GET /CodeIgniter3/welcome/features HTTP/1.1" 200 7713 "https://www.cccc.co/CodeIgniter3/pricing" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.92 Safari/537.36"

**Comment by allinurl** [comment]
@Jamalc0m 

    goaccess access.log --log-format=COMBINED

**Comment by Jamalc0m** [comment]
Same thing, it's not working it keep loading at this 

<img width="1326" alt="screen shot 2018-10-25 at 5 13 32 pm" src="https://user-images.githubusercontent.com/8554119/47506731-5d22bc00-d879-11e8-818d-04585955081e.png">

**Comment by Jamalc0m** [comment]
ssh -t -t root@xxxxxx 'tail -f /var/log/apache2/access.log' | goaccess --log-format=COMBINED

**Comment by Jamalc0m** [comment]
HI @allinurl,
did you manage to fix the issue ?
Thanks,

**Comment by allinurl** [comment]
Haven't got the chance, working on another issue with higher priority. I'll look into this asap. Thanks

**Comment by Jamalc0m** [comment]
Thanks a lot!
