### ISSUE TITLE
Running in Docker container behind nginx-proxy, white screen on real-time-HTML

### ISSUE THREAD

**Issue by jski** [allinurl/goaccess#835]
Hello,

I have your container running as part of my [nginx-proxy](https://github.com/jwilder/nginx-proxy) setup, and I can get the report.html output just fine, but when I try to go get to the realtime HTML output, it's a white screen.  Important bits of the setup included below, can you please help me discern what I'm doing wrong?

**Compose to bring up container:**

  goaccess:
    image: allinurl/goaccess
    container_name: goaccess
    expose:
      - "7890"
    environment:
      - VIRTUAL_HOST=goaccess.mydomain.com
      - VIRTUAL_PORT=7890
      - VIRTUAL_PROTO=http
    volumes:
      - "/opt/goaccess/data:/srv/data"
      - "/opt/goaccess/html:/srv/report"
      - "/var/log/nginx:/srv/logs:ro"
      - "opt/goaccess/data/"

**Config file:**

time-format %H:%M:%S
date-format %d/%b/%Y
log-format %v %h %^ %^ [%d:%t %^] "%m %q %H" %s %D "%U" "%u"
log-file /srv/logs/access.log
output /srv/report/index.html
real-time-html true

**Stdout/stderr from the docker container:**

Parsing... [30] [0/s]
.. [845] [0/s]
WebSocket server ready to accept new client connections

**Comment by allinurl** [comment]
Sounds like the browser is not able to establish a connection to the WebSocket server. Please take a look at your browser's console (Ctrl+Shift+j in Chrome) and post back any error messages that may appear in there. Thanks.

**Comment by allinurl** [comment]
@jskii Any updates on this?

**Comment by jskii** [comment]
Hey @allinurl. Sorry for the delay.

Nothing showing in the console whatsoever, excepting a 400 for favicon.ico for the subdomain.

**Comment by allinurl** [comment]
@jskii Since I haven't played with nginx-proxy, would you be able to post exactly the steps to set it up  and how you run goaccess through it? that way I can try to reproduce the problem from my side. Thanks.

**Comment by xbgmsharp** [comment]
Similar issue. I'm running the docker Goaccess and access it via an Ngnix reverse proxy.
To replicate run the docker Goaccess images and configure a Nginx a similar reverse proxy
```
server {
        listen 443;
        server_name www.site.com
        location / {
             proxy_pass http://localhost:7890/;
             proxy_set_header Host $host;
             proxy_redirect http://localhost:7890/ /;
        }
}
```

When accessing the URL via Nginx i get an error 400 with no log.
```
curl https://www.site.com
< HTTP/1.1 400 Bad Request
< Server: nginx
< Content-Length: 0
```

I try using different ``origin`` and ``ws-url`` in the ``goaccess.conf`` with no luck.

Would you happen to have sample config of reverse proxy for Nginx or Apache?
