### ISSUE TITLE
Customize crawlers

### ISSUE THREAD

**Issue by Mageti** [allinurl/goaccess#838]
Hello,
Would it be possible to add a configuration field to add custom crawlers ?
When I activate the "ignore-crawlers" option, I still see some that are not taken into account in https://github.com/allinurl/goaccess/blob/master/src/browsers.c
Maybe, it would be interesting to have a additional configuration field to add custom string to consider user-agent matching the string as crawler.
What do you think ?

**Comment by allinurl** [comment]
Thanks for the suggestion! **#560** will add the ability to load additional crawlers. Also, I'm working on some refactoring that hopefully will detect more legitimate crawlers. The latter will probably be pushed out in the upcoming version.

Closing this since it's a duplicate from the other.
