### ISSUE TITLE
Specifying target log file does not prevent loading of file specified in configuration

### ISSUE THREAD

**Issue by mqudsi** [allinurl/goaccess#839]
Running goaccess 1.2:

I have a massive access log (28GiB) configured in the goaccess configuration file, but want to analyze a subsection of this file exported to disk via `goaccess -f`.

Calling `goaccess -f /tmp/somelog` either loads `/tmp/somelog` in addition to the file specified in the goaccess config or else loads only the path specified in the goaccess config (it is hard to tell without waiting for it to load the 28GiB).

In all cases, calling `goaccess --no-global-config -f /tmp/somelog` works, but of course, I lose all configuration settings (not just the path to the log).

**Comment by allinurl** [comment]
You can copy the global config file, remove the log input from there and use the new config with `-p`, e.g.,

    goaccess /tmp/somelog -p goaccess.bkp.conf

**Comment by allinurl** [comment]
Closing this since currently it's possible to use a secondary config file. Feel free to reopen it if needed.

**Comment by mqudsi** [comment]
Thanks for responding.

Would you be open to a PR that disabled the access log parameter of the config file if `-f` was supplied? Logically (and consistent with most other apps) command line arguments override configuration file parameters.

**Comment by allinurl** [comment]
I'll certainly welcome the PR :)
