### ISSUE TITLE
Mastodon User-Agent

### ISSUE THREAD

**Issue by John-Shaft** [allinurl/goaccess#841]
Hi,

would it be possible to detect [Mastodon](https://en.wikipedia.org/wiki/Mastodon_(software)) instances User-Agent ? It is detected as `Unknown` in both OS & Browser panels

It looks like : 

`http.rb/ruby_version (Mastodon/Mastodon_version; +http://mastodon.instance.url/)`

eg.

```
http.rb/2.2.2 (Mastodon/1.4.7; +http://mastodon.social/)
http.rb/2.2.2 (Mastodon/1.4.4; +http://framapiaf.org/)
http.rb/2.2.2 (Mastodon/1.4.3; +http://mamot.fr/)
```

Such UA is seen when a Mastodon user post an url : all instances seeing it will make a GET and/or HEAD request to the ressource.

2 interesting things in this UA : Mastodon version and the instance URL. My guess (but I may be wrong :) ) is that it may be spilt into two \: 

In the OS panel, report Mastodon version
```
Mastodon
 |`- 1.4.4
 |`- 1.4.7
 |`- 1.4.3
```

In the browser Panel, detect it as a Crawler \:
```
Crawlers  
  |`- Googlebot/2.1
  |`- Twitterbot/1.0
...
  |`- Mastodon +http://mastodon.social/
  |`- Mastodon +http://framapiaf.org/
...
```

**Comment by John-Shaft** [comment]
On second thought it should be reported as Unix-like in the OS panel, like Googlebot

```
Unix-like
 |`- Mastodon/1.4.4
 |`- Mastodon/1.4.7
 |`- Mastodon/1.4.3
```

**Comment by allinurl** [comment]
Thanks. This has been added to the list of crawlers and unix-like under the OS panel. It will be pushed out in the upcoming version or feel free to build from [**development**](https://github.com/allinurl/goaccess#build-from-github-development).

**Comment by John-Shaft** [comment]
Works, just fine. Thanks ! 👍
