### ISSUE TITLE
Error generating html report using v0.9.4 and --log-format option

### ISSUE THREAD

**Issue by kabeza** [allinurl/goaccess#844]
Hi
I've installed GoAccess 0.9.4 in my Ubuntu Server 17.04. I could not install the ppa nor latest version due connection problems. I also have an Apache server with the default access.log

The thing is that when I run goaccess from commandline, the popup appears, choose log format (CLF) and all shows fine:

![imagen_762](https://user-images.githubusercontent.com/274856/28339584-e8ea351a-6be2-11e7-9d14-a3358e69fdf7.jpg)

The problem is when I run from console

    cat /var/log/apache2/access.log | goaccess --log-format COMMON -p /etc/goaccess.conf > "/var/www/html/stats/$(date +\%d-\%m-\%Y).html" 

I get this (the file is generated but empty)

![imagen_763](https://user-images.githubusercontent.com/274856/28339687-4c8e64ce-6be3-11e7-9bdc-9aa03267ff14.jpg)

Any clues? Thanks

**Comment by allinurl** [comment]
`--log-format` was introduced on [**v1.0**](https://goaccess.io/release-notes#release-1.0). Please upgrade to the latest version. What connection error did you get? Did you try using the official [**deb repo**](https://github.com/allinurl/goaccess#official-goaccess-debian--ubuntu-repository)?

**Comment by kabeza** [comment]
Hi @allinurl 
Before anything, the server has a very restricted internet connection. I cannot install the ppa and also cannot make/install the latest version from source. 
Do you know if I could get the 1.2 deb package from here (or maybe another place)?
https://launchpad.net/~alex-p/+archive/ubuntu/goaccess

**Comment by kabeza** [comment]
PS: solved by installing that 1.2 deb package. All working fine now. Please erase the complete issue if needed. Thanks

**Comment by allinurl** [comment]
Glad that worked!
