### ISSUE TITLE
Need instruction for NGINX Docker installation

### ISSUE THREAD

**Issue by ppKrauss** [allinurl/goaccess#847]
The https://goaccess.io/download#docker  (and all other examples at README) use `apache2` as parameter... How to do the something for NGINX?

**Comment by allinurl** [comment]
```
docker run --restart=always -d -p 7890:7890 \
  -v "/srv/goaccess/data:/srv/data"         \
  -v "/srv/goaccess/html:/srv/report"       \
  -v "/var/log/apache2:/srv/logs"           \
  --name=goaccess allinurl/goaccess
```

`"/var/log/apache2"` it's just the path where your web server access logs reside and will be mounted on the `/srv/logs` volume. You should be able to replace `apache2` with `nginx` (assuming that's the path of your access logs on your server)

**Comment by ppKrauss** [comment]
Thanks @allinurl (!) for your reply.  My `ls /srv`  is empty and `ls /var/log/` shows many files,

```
alternatives.log       auth.log.3.gz          dpkg.log.1      kern.log.4.gz     php7.0-fpm.log.2.gz  ....
.... apache2                ... mysql...             php7.0-fpm.log.6.gz  ... auth.log               
....       nginx             ....
```

Shows apache2 and nginx, but I need only NGINX... Can I use

```sh
docker run --restart=always -d -p 7890:7890 \
  -v "/srv/goaccess/data:/srv/data"         \
  -v "/srv/goaccess/html:/srv/report"       \
  -v "/var/log/nginx:/srv/logs"           \
  --name=goaccess allinurl/goaccess
```   
? Is it?

**Comment by allinurl** [comment]
Make sure /var/log/nginx/ contains the access log you want to analyze. If it does, then the command you posted above should do it.

**Comment by ppKrauss** [comment]
Thanks @allinurl , yes (!) a lot of log files, `ls  /var/log/nginx`

```
access.log       ... access.log.12.gz  ...  access.log.3.gz  ...
```
So, my recommendation is to add some comment about "replace apache2 with nginx" at README instructions, to avoid "fears" of potential users.

**Comment by ppKrauss** [comment]
Seems ok for `docker run -... 7890:7890 ...` , returning a big key, *900d8......*.

But, hum... **How to see it?** Is not `http://localhost:7890`?

Trying `wget localhost:7890` and it is returning
```
--2017-07-20 14:58:20--  http://localhost:7890/
Resolving localhost (localhost)... 127.0.0.1
Connecting to localhost (localhost)|127.0.0.1|:7890... connected.
HTTP request sent, awaiting response... No data received.
Retrying.

--2017-07-20 14:58:21--  (try: 2)  http://localhost:7890/
Connecting to localhost (localhost)|127.0.0.1|:7890... connected.
HTTP request sent, awaiting response... No data received.
Retrying.
....
```

**Comment by allinurl** [comment]
Added a note to the Docker section.

The report will live under `/srv/goaccess/html` or whatever the mounting point you used.

**Comment by ppKrauss** [comment]
Hi @allinurl , good point (!)... Hum... My `ls /srv/goaccess/html`, after run, is empty, how to generate the HTMLs?

**Comment by allinurl** [comment]
Did you set your config file? It requires at least the following options: `log-format`, `log-date`, `log-time`, `log-file`, `output` and optionally `real-time-html`. Then just run

```
docker build . -t allinurl/goaccess
docker run --restart=always -d -p 7890:7890 \
  -v "/srv/goaccess/data:/srv/data"         \
  -v "/srv/goaccess/html:/srv/report"       \
  -v "/var/log/apache2:/srv/logs"           \
  --name=goaccess allinurl/goaccess
```

**Comment by ppKrauss** [comment]
Now I using copy/paste of your config at https://github.com/allinurl/goaccess#docker and **it is there!**

http://stats.oficial.news/

I used also (perhaps another clue for NGINX dummies),

```sh
server {
        server_name  stats.oficial.news;

        root  /srv/goaccess/html;
        index index.html index.htm;

        location / {
                try_files $uri $uri/ =404;
        }
} # end server
```

-----

Problem: how to check (query for *docker  allinurl/goaccess*) my HTML index place?
At the config (that I copy/paste) not say that is `/srv/goaccess/html/index.html`  and is `output /srv/report/index.html`.

**Comment by allinurl** [comment]
Are you trying to create a different volume map? In your config file, you should be using:

    output /srv/report/report.html
    log-file /srv/logs/access.log
    real-time-html true
    log-format specify_your_log_format_here
    log-date specify_your_date_format_here
    log-time specify_your_time_format_here

**Comment by ppKrauss** [comment]
@allinurl ,

It is only an inconsistency, because folder ` /srv/report/` not exists, and my index.htm is at `/srv/goaccess/html/index.html` ... Inconsistency with my `/srv/goaccess/data/goaccess.conf`: 

```
log-format %h %^[%d:%t %^] "%r" %s %b "%R" "%u"
time-format %T
date-format %d/%b/%Y
log-file /srv/logs/access.log
output /srv/report/index.html
real-time-html true
```

**Comment by allinurl** [comment]
Thanks for pointing this inconsistency. It has been corrected on the website's [**Docker**](https://goaccess.io/download#docker) section. 

Were you able to sort everything out with GoAccess and Docker?

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it as needed.
