### ISSUE TITLE
Suggestion, a plug-and-play Docker first!

### ISSUE THREAD

**Issue by ppKrauss** [allinurl/goaccess#848]
The page `https://goaccess.io/download#docker` have no instruction about "plug-and-play" for dummies... But README at [allinurl/goaccess#docker](https://github.com/allinurl/goaccess#docker) show perhaps a clue, *"There is also a prebuilt docker image that can be run without cloning the git repository..."*. So, it is real plug-and-play?

And other "for dummies" instructions as "How to test it"?  is the installed service at localhost?  Can change the localhost port to 1234?

----

As it is the last instruction I need to destroy all my work (eg. at  #847) to return to simplest and test the basic... Ideal is to show at README and  site **the most simple first**.

**Comment by allinurl** [comment]
Not sure I follow what you are requesting. The steps on https://github.com/allinurl/goaccess#docker should get you to the point where the report is generated and updated in real-time (if you choose to). The prebuilt docker image is going away in favor of building from upstream per #792

**Comment by allinurl** [comment]
Were you able to build goaccess as indicated above?

**Comment by ppKrauss** [comment]
Hi @allinurl , Yes, it is running (!). I can't express an avaliation about #792 because I am not a Docker expert... If it is plug-and-play, will better tham all installation process.

**Comment by allinurl** [comment]
Let me take a look at your other opened issue #847 and make sure the instructions listed on the site and the README.md are correct. 

As I mentioned on my previous post, the prebuilt docker image is going away in favor of building from upstream per #792. If the need for a prebuilt docker image comes, then we can certainly added back. For now I'm closing this. Thanks for the suggestion though.
