### ISSUE TITLE
Please do not return an error code when reading an empty log file

### ISSUE THREAD

**Issue by elboulangero** [allinurl/goaccess#850]
I use GoAccess to parse the logs generated by Apache on Debian. Logrotate is part of the picture with the default configuration, which means that every day a new, empty log file is created, and the old one is renamed.

I run GoAccess in a cron task every hour, so every day it will parse an empty file. The Cron line looks like that.

    @hourly goaccess --load-from-disk --keep-db-files -f /var/log/apache2/jekyll_vhosts_access.log -o /srv/www/default/goaccess/hacking.html

So every day, GoAccess reads an empty log file at some point. Since it returns an error code (`1`), Cron sends me a notification email. That's the usual and expected behavior from Cron when a job fails.

Does it sound OK to return `0` when reading an empty log file ? Currently I have a site with very low traffic, the log file can remain empty the whole day, so Cron spams me every hour, that's a pain...

I know that this topic is fresh on your mind, I've seen some issues related, so you must know what's best to do.

Cheers !

**Comment by allinurl** [comment]
Are you on the latest version v1.2? This was addressed on #471. Can you please post the output you are getting when the log the empty. Thanks

**Comment by elboulangero** [comment]
Yep, it's version 1.2, installed from your repository.

```
# cat /etc/apt/sources.list.d/goaccess.list 
deb http://deb.goaccess.io/ jessie main
# goaccess --version 
GoAccess - 1.2.
For more details visit: http://goaccess.io
Copyright (C) 2009-2016 by Gerardo Orellana
```

And here's the output I get with an empty log file.

```
# du -h /var/log/apache2/ghost_vhosts_access.log
0	/var/log/apache2/ghost_vhosts_access.log
# goaccess --load-from-disk --keep-db-files -f /var/log/apache2/ghost_vhosts_access.log  -o /srv/www/default/goaccess/globetrotting.html
/var/log/apache2/ghost_vhosts_access.log
# echo $?
1
```

**Comment by allinurl** [comment]
This must be a regression. Let me look into this and push a fix for it. Thanks!

**Comment by allinurl** [comment]
This has been fixed. Please feel free to build from [**development**](https://github.com/allinurl/goaccess#build-from-github-development) to test this out. Otherwise it will be pushed out in the upcoming release.

**Comment by allinurl** [comment]
Closing this. Feel free to reopen if needed.

**Comment by elboulangero** [comment]
Thanks for looking into that, I'll feedback when the next release lands on the apt repository :)

**Comment by artur-a-brylka** [comment]
The problem still exists in version 1.2 when using several log files:

    log-file /home/xxx/nginx-log-disk/internet_access.log
    log-file /home/xxx/nginx-log-disk/internet_app6_access.log
    **log-file /home/xxx/nginx-log-disk/intranet_dashboard_access.log**
    log-file /home/xxx/nginx-log-disk/intranet_access.log
    log-file /home/xxx/nginx-log-disk/intranet_app6_access.log

It stops always at the first empty log file:

~/nginx-log-disk $ ls -n
total 32
-rw-rw-r--    1 555      555            932 Jan 26 09:20 internet_access.log
-rw-rw-r--    1 555      555              0 Jan 26 09:17 internet_app6_access.log
-rw-rw-r--    1 555      555           1035 Jan 26 09:20 internet_error.log
-rw-rw-r--    1 555      555            223 Jan 26 09:22 intranet_access.log
-rw-rw-r--    1 555      555              0 Jan 26 09:17 intranet_app6_access.log
**-rw-rw-r--    1 555      555              0 Jan 26 09:17 intranet_dashboard_access.log**
-rw-rw-r--    1 555      555            252 Jan 26 09:22 intranet_error.log
drwxrwS---    2 0        555          16384 Jan 26 09:17 lost+found
**~/nginx-log-disk $ goaccess -o /home/oneapi/www/html/index.html
/home/oneapi/nginx-log-disk/intranet_dashboard_access.log**

**Comment by artur-a-brylka** [comment]
Problem still exists in v1.2 when using multiple log-files

    log-file /home/xxx/nginx-log-disk/internet_access.log
    log-file /home/xxx/nginx-log-disk/internet_app6_access.log
    log-file /home/xxx/nginx-log-disk/intranet_dashboard_access.log
    log-file /home/xxx/nginx-log-disk/intranet_access.log
    log-file /home/xxx/nginx-log-disk/intranet_app6_access.log

~/nginx-log-disk $ ls -n
total 48
-rw-rw-r--    1 555      555           1538 Jan 26 10:02 internet_access.log
**-rw-rw-r--    1 555      555              0 Jan 26 10:05 internet_app6_access.log**
-rw-rw-r--    1 555      555           1529 Jan 26 09:41 internet_error.log
-rw-rw-r--    1 555      555            432 Jan 26 09:48 intranet_access.log
-rw-rw-r--    1 555      555            864 Jan 26 10:09 intranet_app6_access.log
-rw-rw-r--    1 555      555            223 Jan 26 09:48 intranet_dashboard_access.log
-rw-rw-r--    1 555      555            477 Jan 26 09:48 intranet_error.log

_~/nginx-log-disk $ goaccess -o /home/xxx/www/html/index.html
/home/xxx/nginx-log-disk/internet_app6_access.log
~/nginx-log-disk $
~/nginx-log-disk $ goaccess --version
GoAccess - 1.2.
For more details visit: http://goaccess.io
Copyright (C) 2009-2016 by Gerardo Orellana_

**Comment by allinurl** [comment]
@artur-a-brylka This should be fixed. Did you build from development?

**Comment by artur-a-brylka** [comment]
@allinurl No, I use the tar.gz in my dockerfile:
_RUN wget http://tar.goaccess.io/goaccess-1.2.tar.gz
RUN tar -xzvf goaccess-1.2.tar.gz
WORKDIR /home/oneapi/goaccess-1.2
RUN ./configure --enable-utf8 --enable-geoip
RUN make
RUN make install_

But I can switch to git if the development branch is currently the only workaround.

**Comment by allinurl** [comment]
@artur-a-brylka Please do so. I'm behind on the deploying the upcoming release, but the fix will be there as soon as it is out.
