### ISSUE TITLE
Export html report error at no time format was found(Run at cygwin)

### ISSUE THREAD

**Issue by 2000mdc** [allinurl/goaccess#853]
Dear, 
Anyone could help to fix on this (version 1.2)?

I have re-configured the date format as mentioned by allinurl:

    # export LANG='en_US-utf-8' 

When i try to export the html report, the error occurred as below:

```
"Fatal error has occurred
Error occurred at: src/parser.c - parse_log - 2732
no time format was found on your conf file."
```

Any suggestion, please?

Thank you!

**Comment by allinurl** [comment]
Please post a few lines from your access log and the date/log/time formats that you are using. Also what's your locale/language? Thanks.

**Comment by 2000mdc** [comment]
@allinurl Have fixed out the error following what you have suggest in the other issue solution as:
--log-format=COMBINED
But how can I prevent to input this command everytime when I want to export the html report?(Also the date format error)
Looking forward to your advice. Thank you very much~~

**Comment by 2000mdc** [comment]
@allinurl The access log is nginx, and the log format configure which I choose is NCSA combined log format. The error is shown as:
“ Token '26/Jul/2017' doesn't match specifier 'd%' ”
My location is China and the operation system language is CN.
Thanks

**Comment by allinurl** [comment]
You can add `export LANG='en_US-utf-8'` to your `~/.bashrc` file so you don't have to do it every time you ssh into the machine.

Also, to make things easier, you can add `log-format COMBINED` to your goaccess config file.

Let me know if that helps.

**Comment by 2000mdc** [comment]
@allinurl Sorry buddy，it's my first time to use goccess on cygwin or linux. I will try to make it happen. It will be appreciated that you give me a advice where I can get some reference. Thanks

**Comment by allinurl** [comment]
Once goaccess has been installed, you can run `goaccess --dcf`to find out where your config file is, then add/uncomment `log-format COMBINED` to it. You can find this in the [man page](https://goaccess.io/man).

**Comment by 2000mdc** [comment]
@allinurl Thank you very much. I have tested. It works. one more easy way, it just need to delet the"#" at the beginning of the command line, just as the time-format/date-format setting below:
![image](https://user-images.githubusercontent.com/25577770/28786494-f8c04c54-764b-11e7-8427-7f503619ca88.png)
