### ISSUE TITLE
Running GoAccess from CLI displays command options

### ISSUE THREAD

**Issue by Denisfor** [allinurl/goaccess#854]
Hello, 
when I launch the goaccess command like "goaccess /var/log/apache2/access.log -a -o report.html" on OSX 10.12,  only list of commands appears.
any ideas ?
regards,
Denis

**Comment by allinurl** [comment]
Are you on the latest version? `goaccess -V`

**Comment by Denisfor** [comment]
version is 0.9.6 !

**Comment by allinurl** [comment]
Please upgrade to the [latest](https://goaccess.io/download#distro) version OR you can run it as:

    goaccess -f /var/log/apache2/access.log -a > report.html

**Comment by Denisfor** [comment]
It works with the command -f , thanks a lot :)
