### ISSUE TITLE
Feature Request: Spanish translation

### ISSUE THREAD

**Issue by kabeza** [allinurl/goaccess#858]
Hi
I'd just wanted to know how difficult could be to translate goaccess (terminal program and web reports) into spanish?
Maybe creating some .po files and then the terminal and/or web reports take those strings and generate the output in the desired language?
Maybe a new command line parameter for setting "es-ES" language and then take those translations...

PS: I'm available to translate it into spanish

**Comment by allinurl** [comment]
Thanks for offering to translate it to Spanish. Actually all the i18n plumbing has been done (gettext) and it'll be out in the next release (French is almost done). [**Here**](https://github.com/allinurl/goaccess/blob/master/src/labels.h) are the labels that need to be translated.

These are the steps:

1. Add `es` to the po/LINGUAS
2. Create a `po/es.po` file and add all your translations in there. See [fr.po](https://github.com/allinurl/goaccess/blob/master/po/fr.po)
3. run `intltool-update es` inside the po folder
4. run `intltool-update --pot`
5. Please submit a PR so I can merge it here.

If your locale is set to `es-ES`, goaccess output will automatically display its content in Spanish.

Let me know if you have any questions. Thanks!

**Comment by kabeza** [comment]
Thanks Gerardo.
I've forked, cloned locally and following instructions

One question, because I'm not a very experienced tech.
What does this mean? T.S.

![imagen_794](https://user-images.githubusercontent.com/274856/28975122-40f75402-790f-11e7-86db-14b054cf5ee7.jpg)

**Comment by allinurl** [comment]
No worries. T.S. = Time Serve (The time taken to serve the request)

**Comment by allinurl** [comment]
Thanks. The #859 PR added Spanish translation. 

I'll look into wrapping or truncating some of the long labels in the config dialog.
