### ISSUE TITLE
Debian 9 apt source.list

### ISSUE THREAD

**Issue by wxprofessor** [allinurl/goaccess#860]
ran into an issue using your debian repository... here is the output after goaccess.list was added.. the newest should be 1.2? :)

```
--snip--
Err:9 http://deb.goaccess.io $(lsb_release/-cs) amd64 Packages
  404  Not Found
Ign:10 http://deb.goaccess.io $(lsb_release/-cs) Translation-en_US
--snip--
Reading package lists... Done
W: The repository 'http://deb.goaccess.io $(lsb_release Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch http://deb.goaccess.io/dists/$(lsb_release/-cs)/binary-amd64/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.
root@box:/etc/apt# apt-get install goaccess
Reading package lists... Done
Building dependency tree       
Reading state information... Done
goaccess is already the newest version (1:0.9.4-1+b1).
0 upgraded, 0 newly installed, 0 to remove and 4 not upgraded.
root@box:/etc/apt# 
```

**Comment by allinurl** [comment]
It looks like there's typo in your `/etc/apt/sources.list.d/goaccess.list`. Can you please make sure it reads `deb http://deb.goaccess.io stretch main` instead of `'http://deb.goaccess.io $(lsb_release Release' `.

Also, please note that due to the version of openssl (**#716**), stretch is currently not supported through the debian repo (until the upcoming release). You will need to build goaccess from [**source**](https://github.com/allinurl/goaccess#installation). You can give it a shot though.

**Comment by wxprofessor** [comment]
>It looks like there's typo in your 
>/etc/apt/sources.list.d/goaccess.list. Can you please make sure it 
>reads deb http://deb.goaccess.io stretch main instead of 
>'http://deb.goaccess.io $(lsb_release Release'.
>

fixed...

i'll try the manual compile.. the current debian version appears to be 
(from the main repository -- the new version did not install as you said 
):

goaccess --version
GoAccess - 0.9.4.
For more details visit: http://goaccess.io
Copyright (C) 2009-2015 GNU GPL'd, by Gerardo Orellana
>
>

which works well... just wanted to see if you added any new toys and try 
the html generation :)


cheers,

--patrick

**Comment by wxprofessor** [comment]
cudos geraldo :)

very well written config... this is a new box, config runs along and 
says hey, you don't have the dev libs for ncursesw, so install it... I 
do and

~/util/goaccess-1.2$ goaccess --version
GoAccess - 1.2.
For more details visit: http://goaccess.io
Copyright (C) 2009-2016 by Gerardo Orellana



now to see how the autogen html looks like :)



cheers,

--patrick

**Comment by allinurl** [comment]
`libncursesw5-dev` is what you want to install. A lot has changed from 0.9.4. Here are the [**release notes**](https://goaccess.io/release-notes).

**Comment by allinurl** [comment]
For examples, please take a look at the [**man page**](https://goaccess.io/man#examples).

**Comment by wxprofessor** [comment]
both were already done (why I complimented you on the good configure 
code) .. would show you the results, but not in a public forum :)


..

**Comment by allinurl** [comment]
Thanks! Glad to hear that :) You can always shoot me an email via hello [at] goaccess . io.

Closing this. Feel free to reopen it if needed.
