### ISSUE TITLE
Feature request: add --pidfile <file> to go along with --daemonize

### ISSUE THREAD

**Issue by vizcay** [allinurl/goaccess#862]
It will be great if it will be possible for goaccess to write it's PID to a file when running with --daemonize. This is an standard practice for daemon monitoring, for example I want GoAccess running 24/7 in my VPS and being able to connect to it for watching the live web report (behind HTTPS and basic authentication). Im writing a medium article about that configuration (GoAccess live with nginx  HTTPS & basic auth as a reverse proxy to it for security; the only missing piece is being able to monitor it with monit or another daemon watcher). Thanks for goaccess = ).

**Comment by allinurl** [comment]
Thanks for suggesting this! It has been implemented. Please feel free to build from [**development**](https://github.com/allinurl/goaccess#build-from-github-development), otherwise it will be shipped in the upcoming version.

**Comment by allinurl** [comment]
Just for the record, this option was renamed from `--pidfile=<path>` to `--pid-file=<path>`.

**Comment by rallep71** [comment]
hi at all, 
Issue pid file...

goaccess.conf

daemonize true
pid-file /var/run/goaccess.pid
real-time-html true

goaccess -o /etc/nginx/html/log/index.html --real-time-html
goaccess: unrecognized option '--pid-file'

goaccess -V
GoAccess - 1.2.
For more details visit: http://goaccess.io
Copyright (C) 2009-2016 by Gerardo Orellana

THX

**Comment by allinurl** [comment]
@rallep71 You will need to build from [development](https://github.com/allinurl/goaccess#build-from-github-development) in order to use the `pid-file` option.

**Comment by rallep71** [comment]
THX for replay

**Comment by rallep71** [comment]
THX for Information
