### ISSUE TITLE
date/time/log format does not match

### ISSUE THREAD

**Issue by bobhsu** [allinurl/goaccess#863]
Hi

1. nginx log format :

`log_format  main    '$remote_addr - $remote_user [$time_local] $request_time $upstream_response_time "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent" "$http_x_forwarded_for"'`

2. nginx log

`192.168.0.1 - root [08/Aug/2017:15:06:01 +0800] 0.067 0.067 "GET /phpmyadmin/ HTTP/1.1" 200 3632 "http://192.168.0.1/phpmyadmin/index.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36" "-"`

GoAccess - 1.2.

`vi /usr/local/etc/goaccess.conf`
`date-format  %d/%b/%Y`
`log-format  %h %^ %v [%d:%t %^] %x %^ "%r" %s %b "%R" "%u" "~h"`

run it as

` goaccess -d -f access.log`

get

`Token already set for '%x' specifier.`

How to set the parameter that log-format？
SPECIFIERS is too few
[https://goaccess.io/man](https://goaccess.io/man)

**Comment by bobhsu** [comment]
It will run okay

`log-format %h %^ %v [%d:%t %^] %^ %^ "%r" %s %b "%R" "%u"`

**Comment by allinurl** [comment]
Please use:

    goaccess access.log --log-format='%h %^ %e [%d:%t %^] %T %^ "%r" %s %b "%R" "%u"' --date-format=%d/%b/%Y --time-format=%T
