### ISSUE TITLE
Why goaccess need on-disk B+tree database?

### ISSUE THREAD

**Issue by MM629** [allinurl/goaccess#864]
Seems this on-disk database is useless, is that right?

**Comment by allinurl** [comment]
If you can fit your dataset in memory, then you're golden, no need for on-disk db.

**Comment by BarbzYHOOL** [comment]
To save ram I guess.

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.

**Comment by MM629** [comment]
Yes. I got it. 
But the problem is how can I apply some filter to on-disk database ? Like I just want to see the requests from a exactly ip address or a given time range.

**Comment by allinurl** [comment]
A filtering tool would be your friend here, e.g.,

    grep `date +"%d/%b"` /var/log/apache2/access.log | grep '192.168.0.1' | goaccess --log-format=COMBINED

#117 would do this without the need of these filtering tools.

**Comment by MM629** [comment]
That's why I ask this question. Cuz in my thought goaccess should be support many kinds of filter on on-disk database. That would be nice for non-IT guys 👍 :)

Thank You Boss.
