### ISSUE TITLE
Can't make browser realtime work, it's always static

### ISSUE THREAD

**Issue by BarbzYHOOL** [allinurl/goaccess#865]
Had same issue as this one https://github.com/allinurl/goaccess/issues/737 but the error was a bit different (but similar idea). I typed the commands but couldn't make it work, it's just static. I don't even understand what's the point of opening the 7890 port but did it.
My apache config points to the right file but with <VirtualHost *:80> 

Does it auto refresh by refreshing the browser page ? I'm really lost with real time browser report.

**Comment by allinurl** [comment]
The report gets the data through a Web Socket connection and it does not do a page refresh thus you need to have the port opened.

Can you please post the command you are running and the whatever output you are getting in your browser's console (Ctrl+Shift+j in Chrome). Also please make sure you are running the latest version. [**Here**](https://goaccess.io/faq#html-report) are some additional details.

**Comment by BarbzYHOOL** [comment]
Had same error on chrome : 
"failed: Error in connection establishment: net::ERR_CONNECTION_TIMED_OUT"

I've followed every tutorial I could find and the FAQ too.

The commands I used : 
```
goaccess /var/log/apache2/other_vhosts_access.log -o report.html --real-time-html --ws-url=ws://IP:7890
goaccess /var/log/apache2/other_vhosts_access.log -o report.html --real-time-html --ws-url=ws://subdomain.domain.com:7890
goaccess /var/log/apache2/other_vhosts_access.log -o report.html --real-time-html --ws-url=IP:7890
goaccess /var/log/apache2/other_vhosts_access.log -o report.html --real-time-html --ws-url=subdomain.domain.com:7890
```

And same with the "-f" flag.

**Comment by allinurl** [comment]
Timeout means it can't reach the WebSocket server. So please make sure to open this port in your server. Also, you shouldn't really need to specify --ws-url, unless goaccess is running on a different machine than the one serving the HTML report (where your apache server is running), so you can omit that option.

**Comment by BarbzYHOOL** [comment]
Yep, finally found what was the problem and yes it was a networking problem :)

If someone asks again, tell him to try to "telnet address.com 7890"
