### ISSUE TITLE
OpenSSL 1.1 support

### ISSUE THREAD

**Issue by TheJJ** [allinurl/goaccess#866]
On current archlinux with the [`goaccess-ssl`](https://aur.archlinux.org/packages/goaccess-ssl/) package, the build fails because of:

```
configure:4165: checking for SSL_library_init in -lssl
configure:4190: gcc -o conftest  -pthread   conftest.c -lssl  -lpthread  >&5
/tmp/ccCmpW2t.o: In function `main':
conftest.c:(.text+0xa): undefined reference to `SSL_library_init'
```

The reason may be missing support for the newer openssl version, as noted in ponylang/ponyc#1838.

Please add openssl 1.1 support.

**Comment by allinurl** [comment]
Thanks for reporting this. This has been added per [**this**](https://github.com/allinurl/goaccess/commit/76b44fc82cc146b3cb0b8113dc056363d288af23) commit and request **#591**. It will be shipped in the upcoming version. Feel free to build from [**development**](https://github.com/allinurl/goaccess#build-from-github-development) to test this out.

**Comment by TheJJ** [comment]
Damnit, didn't see it :) Thanks!
