### ISSUE TITLE
Squid 3.1.25 - Format Errors - Verify your log/date/time format

### ISSUE THREAD

**Issue by darvinrivera** [allinurl/goaccess#872]
```
goaccess /var/log/squid3/access.log
Parsed 10 lines producing the following errors:

Token '43 teresa' doesn't match specifier '%x'
Token '43 teresa' doesn't match specifier '%x'
Token for '%x' specifier is NULL.
Token for '%x' specifier is NULL.
Token '43 noemia' doesn't match specifier '%x'
Token '43 noemia' doesn't match specifier '%x'
Token '43 noemia' doesn't match specifier '%x'
Token for '%x' specifier is NULL.
Token '43 felix' doesn't match specifier '%x'
Token '43 felix' doesn't match specifier '%x'

Format Errors - Verify your log/date/time format
```
My Squid Log file:
```
1504299321.712  54269 10.21.48.14 TCP_TUNNEL/200 639 CONNECT fb-s-c-a.akamaihd.net:443 yulaxi.gonzalez FIRSTUP_PARENT/10.20.0.40 -
1504299321.820  90631 10.20.33.64 TCP_TUNNEL/200 3364 CONNECT bam.nr-data.net:443 dailer.ribas HIER_DIRECT/162.247.242.21 -
1504299322.060    848 10.20.6.131 TCP_TUNNEL/200 531 CONNECT live.github.com:443 juan.mejias HIER_DIRECT/192.30.253.124 -

```
My Squid config:

vim /etc/squid/squid.conf
# TAG: Log File
cache_access_log stdio:/var/log/squid3/access.log
```

My GoAccess Config:
```
vim /etc/goaccess.conf
# Squid native log format
#
time-format %s

# Squid native log format
#
date-format %s

# Squid native log format
log-format %^ %^ %^ %v %^: %x.%^ %~%L %h %^/%s %b %m %U

log-format SQUID
```

**Comment by allinurl** [comment]
Please post a few lines from your squid access log.

**Comment by darvinrivera** [comment]
1504299321.712  54269 10.21.48.14 TCP_TUNNEL/200 639 CONNECT fb-s-c-a.akamaihd.net:443 yulaxi.gonzalez FIRSTUP_PARENT/10.20.0.40 -
1504299321.820  90631 10.20.33.64 TCP_TUNNEL/200 3364 CONNECT bam.nr-data.net:443 dailer.ribas HIER_DIRECT/162.247.242.21 -
1504299322.060    848 10.20.6.131 TCP_TUNNEL/200 531 CONNECT live.github.com:443 juan.mejias HIER_DIRECT/192.30.253.124 -

**Comment by allinurl** [comment]
Please also describe what each field is and how the fields are delimited (i.e., space, tab).

**Comment by darvinrivera** [comment]
Delimited by space.
From https://wiki.squid-cache.org/Features/LogFormat
Resumen
Therefore, an access.log entry usually consists of (at least) 10 columns separated by one ore more spaces:

    time: A Unix timestamp as UTC seconds with a millisecond resolution. 
    duration: The elapsed time considers how many milliseconds the transaction busied the cache. 
    client: address The IP address of the requesting instance, the client IP address. 
    result codes: This column is made up of two entries separated by a slash. 
    bytes: The size is the amount of data delivered to the client. 
    request method: The request method to obtain an object. 
    URL: This column contains the URL requested.
    user: The eighth column may contain the user identity for the requesting client.
    hierarchy code: The hierarchy information consists of three items:
    type: The content type of the object as seen in the HTTP reply header. 

```
time          duration  client    result codes  bytes request  URL                      user              hierarchy code           type
1504299321.712  54269 10.21.48.14 TCP_TUNNEL/200 639 CONNECT fb-s-c-a.akamaihd.net:443 yulaxi.gonzalez FIRSTUP_PARENT/10.20.0.40 -

**Comment by allinurl** [comment]
The following should do it, however, you will need to build from [**development**](https://github.com/allinurl/goaccess#build-from-github-development) since a commit was pushed upstream that fixed an issue with the `~` specifier:

    goaccess access.log --log-format='%x.%^ %~%L %h %^/%s %b %m %U %e %^' --time-format='%s' --date-format='%s' --http-protocol=no

**Comment by darvinrivera** [comment]
goaccess /var/log/squid3/access.log --log-format='%x.%^ %~%L %h %^/%s %b %m %U %e %^' --time-format='%s' --date-format='%s' --http-protocol=no
```
Parsed 10 lines producing the following errors:

Token '' doesn't match specifier '%h'
Token '' doesn't match specifier '%h'
Token '' doesn't match specifier '%h'
Token '' doesn't match specifier '%h'
Token '' doesn't match specifier '%h'
Token '' doesn't match specifier '%h'
Token '' doesn't match specifier '%h'
Token '' doesn't match specifier '%h'
Token '' doesn't match specifier '%h'
Token '' doesn't match specifier '%h'

Format Errors - Verify your log/date/time format

**Comment by allinurl** [comment]
Did you build from development? If you did, did you uninstall the previously installed version? Otherwise you will get the error you just posted.

**Comment by darvinrivera** [comment]
I used Official GoAccess' Debian/Ubuntu Repository.

**Comment by allinurl** [comment]
As I mentioned above, a fix was pushed to the git repository that addresses an issue with the `~` specifier, so you will need to install goaccess from [**development**](https://github.com/allinurl/goaccess#build-from-github-development)  until the new release is shipped out. 

Note, you may need to run `apt-get remove --purge goaccess` and install from dev.

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
