### ISSUE TITLE
Support for GeoIPASNum

### ISSUE THREAD

**Issue by adamziaja** [allinurl/goaccess#873]
Please add support for GeoIPASNum, to do not only check countries but also ASN.

**Comment by allinurl** [comment]
Have you tried using  `--geoip-database=<path>`?

**Comment by TomHetmer** [comment]
I'm trying to use GeoLite2-ASN.mmdb (http://geolite.maxmind.com/download/geoip/database/GeoLite2-ASN.tar.gz) converted with
https://github.com/sherpya/geolite2legacy 
./geolite2legacy.py -i GeoLite2-ASN-CSV.zip -o out -d
>Database type ASN - Blocks IPv4 - Encoding: utf-8
>wrote 539584-node trie with 435523 networks (64472 distinct labels) in 23 seconds

GoAccess displays just an empty panel.

**Comment by allinurl** [comment]
@TomHetmer Do you have any docs about this database?

**Comment by TomHetmer** [comment]
I think it's this https://dev.maxmind.com/geoip/geoip2/geolite2-asn-csv-database/

From the CSV files
```
network,geoname_id,registered_country_geoname_id,represented_country_geoname_id,is_anonymous_proxy,is_satellite_provider,postal_code,latitude,longitude,accuracy_radius
1.0.0.0/24,8349238,2077456,,0,0,5107,-34.7825,138.6106,100
1.0.1.0/24,1811017,1814991,,0,0,,24.4798,118.0819,50
1.0.2.0/23,1811017,1814991,,0,0,,24.4798,118.0819,50
```

```
network,autonomous_system_number,autonomous_system_organization
1.0.0.0/24,13335,"Cloudflare, Inc."
1.0.4.0/22,56203,Gtelecom-AUSTRALIA
1.0.16.0/24,2519,"ARTERIA Networks Corporation"
1.0.64.0/18,18144,"Energia Communications,Inc."
1.0.128.0/17,23969,"TOT Public Company Limited"
1.1.1.0/24,13335,"Cloudflare, Inc."
1.1.8.0/24,4134,"No.31,Jin-rong Street"
```

So just the columns are different and it should show both the AS number and the AS name.
It looks like there's no need to construct a radix tree, the lookup should be the same as for regular Maxmind City DBs.

**Comment by jurvi** [comment]
@TomHetmer @allinurl Any update on this one? Or maybe some workaround was found? This would be amazing enhancement to GoAccess. I was just trying to do this exact same thing using GeoLite2 ASN database, but the HTML report just shows empty Country information when doing e.g:

goaccess mini.log --log-format=COMMON --geoip-database=GeoLite2-ASN.mmdb -o report.html

**Comment by allinurl** [comment]
#2386 

This has been implemented. It will be pushed out in the upcoming release. Stay tuned!

You will be able to pass multiple dbs. e.g., 

    goaccess access.log --log-format=COMBINED --geoip-database=GeoLite2-ASN.mmdb --geoip-database=GeoLite2-City.mmdb
