### ISSUE TITLE
bingbot/2.0 under Windows OS

### ISSUE THREAD

**Issue by szepeviktor** [allinurl/goaccess#874]
Could it be that bingbot/2.0 appears under Windows OS?

`Mozilla/5.0 (iPhone; CPU iPhone OS 7_0 like Mac OS X) AppleWebKit/537.51.1 (KHTML, like Gecko) Version/7.0 Mobile/11A465 Safari/9537.53 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)`

**Comment by allinurl** [comment]
Yes it does. I believe that was part of this [**commit**](https://github.com/allinurl/goaccess/commit/41deaed4a3e54ee10a2a47ceb4348b9ab48402ec).  Shouldn't it be?

**Comment by szepeviktor** [comment]
Oh!

So you suspect bing run on a Windows server?

**Comment by szepeviktor** [comment]
Yes.

> Bingbot assumes Windows because Microsoft. Its all Windows over there.
