### ISSUE TITLE
How can I see request url per time?

### ISSUE THREAD

**Issue by greenfrog82** [allinurl/goaccess#875]
I'm new to goaccess.
I have some apache server logs. And I've generated report.html file with the following command.
```
$ goaccess https_access.log.2017-08-29-15_25_20 -a > report.html
```
And I saw the report.html on chrome. But I did find 'request url per time'.
Do not support this feature which is request url per time?

**Comment by allinurl** [comment]
Are you looking to display the time taken to process a request? If you do you probably want to use `%D` in your log format, else feel free to post a few lines from your access log and the log-format you are using and I can take a look.

**Comment by greenfrog82** [comment]
Thank u for ur comment.
I've found that option about %D of apache log-format few minutes ago.
But I can't check it after applied log %D.
I will comment after check it out ASAP.

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.

**Comment by allinurl** [comment]
@abdulmutal You would need to log that from your web server. For apache you would use `%D`.

**Comment by abdulmutal** [comment]
Thanks for your Response
