### ISSUE TITLE
Custom log format for Nginx and GoAccess

### ISSUE THREAD

**Issue by buluxan** [allinurl/goaccess#876]
hi ,

i got this error below when i generate to .html is there any configuration that i missed on goaccess.conf  ? 

Token '[05/Sep/2017:06:25:05' doesn't match specifier '%h'
Token '[05/Sep/2017:06:25:20' doesn't match specifier '%h'
Token '[05/Sep/2017:06:25:21' doesn't match specifier '%h' 

here's my custom logs : 
===================
log_format upstreamlog '[$time_local] $remote_addr - $remote_user - $server_name to: $upstream_addr: $request upstream_response_time $upstream_response_time msec $msec request_time $request_time';

**Comment by allinurl** [comment]
Please post a few lines from your access log.

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if you are still having this issue along with a few lines from your access log.

**Comment by anamika-m** [comment]
Sep  9 06:39:01 thunder CRON[16142]: pam_unix(cron:session): session opened for user root by (uid=0)

Please provide log,date and time format

**Comment by allinurl** [comment]
@anamika-m please note that goaccess is a web log (access.log) analyzer, so you won't be able to parse that string.

**Comment by anamika-m** [comment]
Mar  1 06:30:58 gw kernel: [782740.844689] FORWARD-New-Connection: IN=eth1 OUT=eth1 MAC=2c:41:38:88:45:35:d4:85:64:16:54:62:08:00 SRC=172.16.0.30 DST=172.17.13.114 LEN=60 TOS=0x00 PREC=0x00 TTL=254 ID=1646 PROTO=ICMP TYPE=8 CODE=0 ID=5 SEQ=6250 

Please provide log,date and time format

**Comment by allinurl** [comment]
@anamika-m Try this, it should work:

    goaccess your.log --log-format='%d %t %^ %v: %^ %U: %^ %^ %^ %^=%h %R %^=%b %^ %^ %^=%L %^' --date-format='%b %e' --time-format=%T --ignore-panel=BROWSERS --ignore-panel=OS --ignore-panel=STATUS_CODES --ignore-panel=REFERRING_SITES --ignore-panel=REQUESTS_STATIC --ignore-panel=NOT_FOUND --http-method=no --http-protocol=no
