### ISSUE TITLE
Output html gets always overridden

### ISSUE THREAD

**Issue by Winniepooh1** [allinurl/goaccess#877]
Hello,

I would like to append the data of my log to my existing html, but though specified --load-from-disk option it overrides my whole history. Here is what I've done:

1. Create html file from compressed logs with:
`zcat find /var/log/nginx -name "access.log.*.gz" | goaccess - -o /var/www/test/goaccess/17-09-goaccess.html --keep-db-files --db-path /home/user/goaccess_db/`
The html file looks fine and the db files are in the folder goaccess_db.

2. Append data of last log to existing html file:
`goaccess -f /var/log/nginx/access.log.1 -o /var/www/test/goaccess/17-09-goaccess.html --load-from-disk --keep-db-files --db-path /home/user/goaccess_db`
This one overrides the whole history with only the data of access.log.1. Also all db files were stored directly in my home folder instead of /home/user/goaccess_db. I've followed exactly the last example of the man page (https://goaccess.io/man#examples). What is wrong here?

Regards

**Comment by allinurl** [comment]
Which version are you running? Your use case looks fine to me, so can I ask you for step 2 to just load and keep the db files without appending new data, i.e.,

    goaccess --load-from-disk --keep-db-files --db-path /home/user/goaccess_db

That should load on the terminal output only the data that you stored in step 1. Let me know if that's the case.

**Comment by Winniepooh1** [comment]
I've installed version 1.2. When I just execute your command after step 1 I get the data from step 1.

**Comment by allinurl** [comment]
If you only parse step 2 without step 1, how many requests do you get?

    goaccess /var/log/nginx/access.log.1 -o /var/www/test/goaccess/17-09-goaccess.html

It's possible that access.log.1 contains the majority of top requests, and therefore what you are seeing is most of the requests from access.log.1, and buried deep under, most of the requests from the previous parse. Please parse both sets individually and take note of the number of total requests and then make sure that it's in fact adding up to the total. 

Also, you can test it out with a much smaller data sets or even with different data sets. Feel free to post some screenshots as needed.

**Comment by Winniepooh1** [comment]
I've found the cause for the overwriting and the files inside my home folder: 

The specified db-path needs a trailing slash. So instead of `--db-path /home/user/goaccess_db` it needs to be `--db-path /home/user/goaccess_db/`. Now the new log file gets appended without any problems.

**Comment by allinurl** [comment]
Nice catch! Glad that solved the issue.
