### ISSUE TITLE
Parse Squid Access.log (pfSense)

### ISSUE THREAD

**Issue by rduarte** [allinurl/goaccess#880]
Hello,

I've tried options created on #68 but it isn't working for me.

Here my access.log:
`
1505241568.659   9307 192.168.13.169 TCP_TUNNEL/200 2904 CONNECT clients4.google.com:443 - HIER_DIRECT/172.217.29.206 -
1505241568.721  11613 192.168.13.87 TCP_TUNNEL/200 252 CONNECT apis.google.com:443 - HIER_DIRECT/172.217.29.206 -
1505241568.790      1 192.168.13.147 TAG_NONE/503 0 CONNECT graph.facebook.com:443 - HIER_NONE/- -
1505241568.791    780 192.168.100.86 TCP_MISS/206 141234 GET http://au.download.windowsupdate.com/c/msdownload/update/software/secu/2017/09/ndp46-kb4040973-x64_5da041181051d83e3aad0950ef4b5c7db58520f7.exe - HIER_DIRECT/2.16.188.146 application/octet-stream
1505241568.856     32 192.168.13.74 TCP_MISS/200 680 HEAD http://ds.download.windowsupdate.com/v11/2/microsoftupdate/redir/v6-muredir.cab? - HIER_DIRECT/13.107.4.50 application/vnd.ms-cab-compressed
1505241568.871    587 192.168.20.140 TCP_MISS/200 8559 GET http://www.worldsurfleague.com/events/2017/mct/1935/hurley-pro-at-trestles/liveround? - HIER_DIRECT/142.54.228.135 application/json
1505241568.901      1 192.168.20.127 TCP_DENIED/403 4203 POST http://redirectme.zapto.org:1004/is-ready - HIER_NONE/- text/html
1505241568.991    874 192.168.13.56 TCP_MISS/206 159303 GET http://au.download.windowsupdate.com/c/msdownload/update/software/secu/2017/09/windows6.1-kb4040980-x64_7d1538408fee60e0ece693c43c27d97d2ede5c85.cab - HIER_DIRECT/2.16.188.146 application/vnd.ms-cab-compressed
1505241569.013   2767 192.168.13.32 TCP_TUNNEL/200 332843 CONNECT audio-fa.scdn.co:443 - HIER_DIRECT/151.101.92.246 -
1505241569.045   3700 192.168.13.32 TCP_MISS/200 669241 GET http://nlds299.cdnak.neulion.com/nlds/wsl/t242551/as/live/t242551_hd_3000/20170912/18/3832.mp4 - HIER_DIRECT/201.76.0.105 video/mp4
`

In the goaccess.conf, i´ve uncommented the lines of squid:

```
time-format %s
date-format %s
log-format %^ %^ %^ %v %^: %x.%^ %~%L %h %^/%s %b %m %U
log-format SQUID
```

But, when a run the command, i've got this:

```
goaccess access.log -a -o report.html
access.log [0] [0/s]
Parsed 10 lines producing the following errors:

Token '/go' doesn't match specifier '%x'
Token '/nlds299' doesn't match specifier '%x'
Token '/bstatic' doesn't match specifier '%x'
Token '/media' doesn't match specifier '%x'
Token '/bstatic' doesn't match specifier '%x'
Token '/redirectme' doesn't match specifier '%x'
Token '/dmd' doesn't match specifier '%x'
Token for '%x' specifier is NULL.
Token '/bstatic' doesn't match specifier '%x'
Token '/governadorcelsoramos' doesn't match specifier '%x'

Format Errors - Verify your log/date/time format
```

What is wrong? Can someone help?

Thanks!

**Comment by allinurl** [comment]
Can you instead of posting a few lines from your access log, please attach them as a file? Also, are they delimited by tab or spaces? Thanks.

**Comment by rduarte** [comment]
[access.log.txt](https://github.com/allinurl/goaccess/files/1297075/access.log.txt)

**Comment by allinurl** [comment]
The following should work. However, you will need to build from [**development**](https://github.com/allinurl/goaccess#build-from-github-development) in order to get goaccess to parse your log.

    goaccess squid.log --log-format='%x.%^ %~%D %h %^/%s %b %m %U %^' --date-format=%s --time-format=%s --http-protocol=no --ignore-panel=OS --ignore-panel=BROWSERS --ignore-panel=REFERRERS --ignore-panel=REFERRING_SITES --ignore-panel=KEYPHRASES

Also, this assumes your second field is the time taken to serve the request, in microseconds.

**Comment by rduarte** [comment]
It´s works! Thanks!

**Comment by ipetruniv** [comment]
[squid.log.tar.gz](https://github.com/allinurl/goaccess/files/2118334/squid.log.tar.gz)
Hello. I'm trying to generate a similar squid log file (attached), but get en error:

Parsed 1 linesproducing the following errors:
Token '-' doesn't match specifier '%h'

I'm using development build of goaccess.
Could you please help me to form correct options?

**Comment by allinurl** [comment]
@ipetruniv Please try this, it should do it:

    goaccess access.log --log-format='%h %^[%d:%t %^] "%r" %s %b "%R" "%u" %v' --date-format=%d/%b/%Y --time-format=%T

**Comment by ipetruniv** [comment]
Hello

Thank you - works !!!


---
Best regards
Igor
