### ISSUE TITLE
Haproxy Log Format and GoAccess

### ISSUE THREAD

**Issue by robertoamoreno** [allinurl/goaccess#881]
Any idea what the format would be to make this work in haproxy 

https://github.com/jvehent/haproxy-aws#haproxy-logging

    log-format [%pid]\ [%Ts.%ms]\ %ac/%fc/%bc/%bq/%sc/%sq/%rc\ %Tq/%Tw/%Tc/%Tr/%Tt\ %tsc\ %ci:%cp\ %fi:%fp\ %si:%sp\ %ft\ %sslc\ %sslv\ %{+Q}r\ %ST\ %b:%s\ "%CC"\ "%hr"\ "%CS"\ "%hs"\ req_size=%U\ resp_size=%B

E.g

    Mar 14 17:14:51 localhost haproxy[14887]: [14887] [1394817291.250] 10/5/2/0/3/0/0 48/0/0/624/672 ---- 1.10.2.10:35701 10.151.122.228:443 127.0.0.1:8000 logger - - "GET /v1/ HTTP/1.0" 404 fxa-nodejs:nodejs1 "-" "{||ApacheBench/2.3|over-100-active-connections,over-100-connections-in-10-seconds,high-error-rate,high-request-rate,|47B4176E:8B75_0A977AE4:01BB_5323390B_31E0:3A27}" "-" "" ireq_size=592 resp_size=787

**Comment by allinurl** [comment]
Try the following, it should do it.

    goaccess access.log --log-format='%^[ %^[ %^[%x.%^] %^ %^/%^/%^/%^/%L %^ %h:%^"%r" %s %v %^ "%u|%^" %^ %^ %^ %^=%b' --date-format=%s --time-format=%s

**Comment by robertoamoreno** [comment]
Looks like that is better Virtual Hosts is picking up as  backend name and server name not the virtual  host

**Comment by allinurl** [comment]
I don't see a virtualhost field from the docs you posted above. You can always get rid of `%v` if it doesn't exist, though.

**Comment by robertoamoreno** [comment]
Opps I modified mine a little 
[%pid]\ [%Ts.%ms]\ %ac/%fc/%bc/%bq/%sc/%sq/%rc\ %Tq/%Tw/%Tc/%Tr/%Tt\ %tsc\ %ci:%cp\ %fi:%fp\ %si:%sp\ %ft\ %sslc\ %sslv\ %{+Q}r\ %ST\ %b:%s\ "%CC"\ "%hr"\ "%CS"\ "%hs"\ req_size=%U\ resp_size=%B

**Comment by robertoamoreno** [comment]
Ohh i see %{+Q}r\  so that show hostname 

%{+Q}r: HTTP request, between double quotes

{www.domain.com||||Mozilla/5.0 (compatible; AhrefsBot/5.2; +http://ahrefs.com/robot} 
 Might need to change config

**Comment by allinurl** [comment]
Can you please post a few lines from your actual access.log?

**Comment by robertoamoreno** [comment]
@allinurl Sent you an email with a private gist as it has server info =)

**Comment by allinurl** [comment]
Give this a shot:

    goaccess access.log --log-format='%^[ %^[ %^[%x.%^] %^ %^/%^/%^/%^/%L %^ %h:%^"%r" %s %^ %^ {%v|%^|%^|%^|%u} %^ %^ %^=%b' --date-format=%s --time-format=%s

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.

**Comment by monotek** [comment]
if this works can you add it to the --log-format option please?

**Comment by allinurl** [comment]
@monotek I can certainly add it, however, I'm not sure if @robertoamoreno's log-format is the standard or a custom one. Any idea?

**Comment by monotek** [comment]
just tested it. does not work :-(
Log looks like:

`Jan 31 16:14:00 hostname haproxy[3850]: 111.111.111.222:60032 [31/Jan/2018:16:13:10.740] ext_ssl ssl_sni/local 8/0/50102 647 -- 1919/1225/1225/1225/0 0/0`

**Comment by nebkas** [comment]
Sorry for bringing it up after so long time. Does someone have an actual example for the haproxy cfg file and the config of goaccess log format ?

**Comment by allinurl** [comment]
@nebkas are you able to share a few lines from your haproxy log?

**Comment by nebkas** [comment]
I set the log formats like in this example:
https://serverfault.com/questions/764098/haproxy-log-custom-format-for-goaccess


```
Feb  1 08:01:31 lb haproxy[25760]: 142.132.147.110:80 216.218.206.67 [01/Feb/2022:08:01:27.875] "GET / HTTP/1.1" 405 135 "{|}"
Feb  1 08:06:43 lb haproxy[25760]: 216.218.206.67:25986 [01/Feb/2022:08:06:43.668] RPC-8545/1: SSL handshake failure
Feb  1 09:12:48 lb haproxy[25760]: 142.132.151.60:80 45.146.165.37 [01/Feb/2022:09:12:44.872] "GET / HTTP/1.1" 405 135 "{|Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36}"
Feb  1 10:01:40 lb haproxy[25760]: 45.146.165.37:59110 [01/Feb/2022:10:01:18.579] RPC-8545/1: SSL handshake failure
Feb  1 10:23:46 lb haproxy[25760]: 142.132.148.188:80 192.241.206.152 [01/Feb/2022:10:23:44.722] "GET / HTTP/1.1" 405 119 "{|Mozilla/5.0 zgrab/0.x}"
Feb  1 10:39:46 lb haproxy[25760]: 45.146.165.37:55376 [01/Feb/2022:10:39:24.323] RPC-8545/1: SSL handshake failure
Feb  1 10:54:35 lb haproxy[25760]: 142.132.151.60:80 109.98.215.75 [01/Feb/2022:10:54:35.180] "POST / HTTP/1.1" 200 230 "{|Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36}"
Feb  1 10:54:35 lb haproxy[25760]: 142.132.148.188:80 109.98.215.75 [01/Feb/2022:10:54:35.180] "POST / HTTP/1.1" 200 214 "{|Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36}"
Feb  1 10:54:35 lb haproxy[25760]: 142.132.147.110:80 109.98.215.75 [01/Feb/2022:10:54:35.176] "POST / HTTP/1.1" 200 236 "{|Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36}"
Feb  1 11:21:51 lb haproxy[25760]: 142.132.147.110:80 45.146.165.37 [01/Feb/2022:11:21:49.318] "GET / HTTP/1.1" 405 135 "{|Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36}"
```

**Comment by allinurl** [comment]
@nebkas Sorry for the delay, this should do it:

    goaccess access.log --log-format='%^]: %h:%^[%d:%t.%^] "%r" %s %b "%u"' --date-format=%d/%b/%Y --time-format=%T
