### ISSUE TITLE
Custom nginx log-format and GoAccess

### ISSUE THREAD

**Issue by Changer0914** [allinurl/goaccess#888]
log_format main
              '$time_iso8601|$http_x_forwarded_for|$http_host|$request|'
               '$status|$request_time|$body_bytes_sent|$http_referer|'
               '$upstream_addr|$upstream_response_time'

log sample

    2017-09-19T00:00:04+08:00|192.168.0.9|192.168.0.85:8080|GET /UserSystem/ParkingLeaseInformation/v1_2/getParkingLeaseInformationBylicensePlateNumber.do?licensePlateNumber=%E4%BA%ACNE68N8&leaseParkId=476901 HTTP/1.0|200|0.026|686|-|192.168.0.141:8080|0.024

thank you

**Comment by allinurl** [comment]
I see you have `$http_x_forwarded_for` in your second field, how are your IP delimited for that field?

**Comment by Changer0914** [comment]
This IP is real client IP, who call the api.

**Comment by allinurl** [comment]
Assuming there's only one IP for that field, this should do it:

    goaccess access.log --log-format="%dT%t+%^|%h|%v|%r|%s|%T|%b|%R|%^" --date-format=W3C --time-format=%T --ignore-panel=OS --ignore-panel=BROWSERS

**Comment by Changer0914** [comment]
O le, thank you!
