### ISSUE TITLE
GoAccess.io seems down (as of sep 20, 9:43 AM Eastern time)

### ISSUE THREAD

**Issue by aravindhsampath** [allinurl/goaccess#889]
Website seems to have gone down. 
I'm using Google cache to read the homepage...

**Comment by fenollp** [comment]
All .IOs look down!

**Comment by allinurl** [comment]
It's up from where I'm accessing. http://downforeveryoneorjustme.com/goaccess.io. Can you check without Google cache?

**Comment by aravindhsampath** [comment]
Works now. Just checked.

**Comment by allinurl** [comment]
Great! Thanks for reporting it!

**Comment by allinurl** [comment]
Just posting some additional info [**here**](https://news.ycombinator.com/item?id=15293578)
