### ISSUE TITLE
goaccess.io not opening/loading?

### ISSUE THREAD

**Issue by LeeNX** [allinurl/goaccess#890]
Greetings ...  
  
 Seems that goaccess.io might have lapsed, because I can't visit https://goaccess.io/ nor resolve deb.goaccess.io  
```
W: Failed to fetch http://deb.goaccess.io/dists/trusty/InRelease

W: Failed to fetch http://deb.goaccess.io/dists/trusty/Release.gpg  Could not resolve 'deb.goaccess.io'

W: Some index files failed to download. They have been ignored, or old ones used instead.
```
I am sure it's a small oversight?

**Comment by allinurl** [comment]
Thanks for reporting this. It looks like this may be at the Root zones for io domains. #889 also raised this issue. Some info [**here**](https://news.ycombinator.com/item?id=15293578).

**Comment by LeeNX** [comment]
@allinurl - Thanks, did not see the other repo ... Was thinking it might also be linked to #883   
  
But it seems you have this sorted.

**Comment by allinurl** [comment]
This appears to be resolved. Closing this. Thanks again!
