### ISSUE TITLE
Token 'HTTPS' doesn't match specifier '%H'

### ISSUE THREAD

**Issue by Kinganmi** [allinurl/goaccess#892]
``` 
20170920145951 112.4.154.81 xfzdl2.haowanyou.com /PalaceM2_cn_cn/S180049901/HttpRoot/1.2.6/0_23.pkg?17082918 2177457 120 1046 206 NULL 60003 "NULL" "36992816-" GET HTTPS hit
 ```

```
goaccess -f 1.txt --log-format='%x %h %v %U %b %^ %^ %s %R %L "%u" %^ %m %H %^' --date-format=%Y%m%d%H%M%S --time-format=%Y%m%d%H%M%S -d -a > test.html
```

Token 'HTTPS' doesn't match specifier '%H'

Pls help me

GoAccess - 1.2

**Comment by allinurl** [comment]
Close, however, HTTPS is not a valid protocol, this should do it:

    goaccess access.log --log-format='%x %h %v %U %b %^ %^ %s %R %L "%u" %^ %m %^' --date-format=%Y%m%d%H%M%S --time-format=%Y%m%d%H%M%S --http-protocol=no

**Comment by Kinganmi** [comment]
TKS
