### ISSUE TITLE
How to list out static contents hosted in a subdomain in the goaccess report? 

### ISSUE THREAD

**Issue by stormyqq** [allinurl/goaccess#895]
I have this domain nucuta.com and my images are hosted in cdn.nucuta.com. I enabled access_log directory  in both files in nginx. so, even though in the access.log file it shows the requests to images are logged, it doesn't show in the goaccess report in "STATIC REQUESTS" section. so how I am gonna list the requests to static contents hosted this cdn.nucuta.com in goaccess report? thanks.!

**Comment by allinurl** [comment]
Can you please post a few lines from your access.log that contain static requests and not showing in goaccess? Thanks.

**Comment by stormyqq** [comment]
Strangely these records don't show, but static contents served from the main domain appear in the report, and they are exactly like these except the directory starts with wp-content. 

then again I am not sure it's a problem with these records or because I enabled logging of that subdomain today. yeah I forgot to enable logging of cdn.nucuta.coma subdomain, but I enabled it today and sent the requests to these static files and then generated the report but they don't appear still. I dunno why. this problem is quite strange, because I don't see any difference between the following records, and the records of wp-content folder. 

[x.x.x.x - - [24/Sep/2017:23:37:14 +0530] "GET /2017/08/google-drive-logo-new-551x300.png HTTP/2.0" 200 21821 "-" "Mozilla/5.0 (Win
dows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36"

x.x.x.x - - [24/Sep/2017:23:37:54 +0530] "GET /2017/05/watch-397227_1920-e1495719751424-640x480.jpg HTTP/2.0" 404 647 "-" "Mozilla
/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36"

x.x.x.x - - [24/Sep/2017:23:37:59 +0530] "GET /2017/06/HomeKitLogo-e1498174778783-272x182.png HTTP/2.0" 200 23335 "-" "Mozilla/5.0
 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36"](url)

**When the file is in wp-content folder.** 

```
x.x.x.x  - - [24/Sep/2017:23:44:01 +0530] "GET /wp-content/uploads/2017/07/Cucoin600px.png HTTP/2.0" 200 253000 "-" "Mozilla/5.0 (W
indows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36"

```

**Comment by allinurl** [comment]
GoAccess shows the top 365 records or 50 in the real-time report, so it's possible these static files don't account to make it to the top list. One thing you could do is to check how many instances of one of these static files there are, e.g., `grep '/2017/06/HomeKitLogo-e1498174778783-272x182.png' cnd.log | wc -l`and see if there are enough hits to make it to the top. You can also extract these hits and check if goaccess is putting them in the right panel.

**Comment by stormyqq** [comment]
It says when typing the exact command.

```
:~# grep '/2017/06/HomeKitLogo-e1498174778783-272x182.png' cnd.log | wc -l
grep: cnd.log: No such file or directory
0
```

**Comment by allinurl** [comment]
`cnd.log` was the example filename, in your case, please use your access log that contains all the records from the cdn  domain.

**Comment by stormyqq** [comment]
Oh yeah xD right. It returned this one.

```
grep '/2017/08/google-drive-logo-new-551x300.png' /var/log/nginx/access.log | wc -l
7

```

I guess that explains the culprit then.  Thanks.!
