### ISSUE TITLE
nginx reverse proxy now working but why ?

### ISSUE THREAD

**Issue by mertcangokgoz** [allinurl/goaccess#898]
Hello

I'm trying to run it as a reverse proxy for nginx but I can not go from the white page i see always http 400 Error 

my reverse proxy config

```
upstream websocket {
        server 127.0.0.1:8022;
}

location /status/ {
    proxy_pass http://wsbackend;
    proxy_http_version 1.1;
}
```

goaccess 

```
goaccess -f /var/log/nginx/access.log -o index.html --real-time-html --addr=127.0.0.1 --port=8022
```

how can i fix this situation.

**Comment by allinurl** [comment]
If GoAccess is running behind a proxy, you could set the client side to connect to a different port by specifying the host followed by a  colon and the port.  e.g., `--ws-url=YOUR_IP:8022` and keep goaccess' port as `--port=7890`.

Also, just for testing purposes, you can test the connection via telnet to the ws server. e.g.,

    # telnet 127.0.0.1 8022

**Comment by MertcanGokgoz** [comment]
Thank you for the answer but I can not run again, I see a white page and http 400 error again

```
Request Method:GET
Status Code: 400 
```

note: I use SSL on my connections

goaccess param

```
goaccess -f /var/log/nginx/access.log -o index.html --real-time-html --ws-url=127.0.0.1:8022 --port=7890
```

just want to run local, I will proxy from local to client side connection

**Comment by allinurl** [comment]
Which version of goaccess are you running? also, were you able to telnet as I commented above? Please try telneting to ports 8022 and 7890 and post the output here. Also, please post the output of your browser's console. Thanks

**Comment by MertcanGokgoz** [comment]
params

```
goaccess -f /var/log/nginx/access.log -o index.html --real-time-html --ws-url=127.0.0.1:8022 --port=7890
```

Now work telnet port 7890 

```
root@local:~# telnet 127.0.0.1 7890
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.
```

port 8022 output

```
root@local:~# telnet 127.0.0.1 8022
Trying 127.0.0.1...
telnet: Unable to connect to remote host: Connection refused
```

Browser output

![capture](https://user-images.githubusercontent.com/8042604/30886166-c8c6bcfe-a31e-11e7-9d9a-eb9a3e1135ee.JPG)

Get Response output

```
Request URL:https://mertcangokgoz.com/status/
Request Method:GET
Status Code:400 
Remote Address:[2400:cb00:2048:1::681f:5319]:443
Referrer Policy:no-referrer-when-downgrade
Response Headers
cf-cache-status:MISS
cf-ray:3a497ab2dc2f3d25-CPH
date:Tue, 26 Sep 2017 21:57:30 GMT
server:cloudflare-nginx
status:400
strict-transport-security:max-age=15552000; includeSubDomains; preload
vary:Accept-Encoding
x-content-type-options:nosniff
Request Headers
:authority:mertcangokgoz.com
:method:GET
:path:/status/
:scheme:https
accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
accept-encoding:gzip, deflate, br
accept-language:en-US,en;q=0.8,tr;q=0.6
cache-control:max-age=0
cookie:__cfduid=d346825c57f0f2963700af134e2ed2ed11505863041; _ga=GA1.2.1186602595.1505863043; _gid=GA1.2.1074626446.1505863043
dnt:1
upgrade-insecure-requests:1
user-agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36
```

**Comment by allinurl** [comment]
You probably want to try using wss as you are using https, OR you can try simply using http. e.g.,

    goaccess /var/log/nginx/access.log -o index.html --real-time-html --ws-url=wss://mertcangokgoz.com  --ssl-cert=<cert.crt> --ssl-key=<priv.key>

Also, please build from [**development**](https://github.com/allinurl/goaccess#build-from-github-development), several commits ago a fix was pushed that addressed a 400 status code when upgrading the connection. Let me know if that solves the issue, you probably want to play with the ports you've got opened too. My advise would be to start from the basics, e.g., try without the proxy setup and see if you can reach the machine where goaccess is running and then build up from there.

If that doesn't solve the issue, please post the whole nginx reverse proxy config and I can try to set up one from my side.

**Comment by MertcanGokgoz** [comment]
I wanted to run it but it did not, a good idea came to mind I'm getting a report in 6 hours using crontab and publish it 

example: https://mertcangokgoz.com/static/

👍
