### ISSUE TITLE
go get support

### ISSUE THREAD

**Issue by mqudsi** [allinurl/goaccess#899]
It would be nice if goaccess could be installed via the increasingly more popular `go get ...` command, which downloads the source, compiles, and makes available in `PATH` the target repo.

**Comment by allinurl** [comment]
Does it need to be a go app for that work?

**Comment by TerraTech** [comment]
@mqudsi **go**access is not a Go program, it is written in C.  So far, the building experience has been very straightforward and most distro's have it packaged.

I did find one bug though with Gentoo's ebuild, that I need to report in regards to ```--enable-geoip```.  They only offer the legacy geoip, therefore the ebuild needs to be updated to ```--enable-geoip=legacy```.  More succinctly:  ```$(use_enable geoip geoip legacy)```.

**Comment by TerraTech** [comment]
Gentoo bug report filed:  https://bugs.gentoo.org/632212

**Comment by allinurl** [comment]
Thanks for clarifying that and filing the Gentoo bug! Closing this as it appears `go get` is strictly for go programs.
