### ISSUE TITLE
UI: goto beginning, goto end

### ISSUE THREAD

**Issue by TerraTech** [allinurl/goaccess#902]
On the report.html page, in addition to the goto prev (<) and goto next (>), it would be nice if there were goto beginning (<<) and goto end (>>).  One one report, the "VISITOR HOSTNAMES AND IPS" has 366 line items.

e.g.: **<<** **<** **>** **>>**

I've seen some UI's use:  **<** **>** **<<** **>>**

**Comment by millsjustin** [comment]
Implemented in #1102.

**Comment by allinurl** [comment]
Closing this. Thanks!
