### ISSUE TITLE
Disable "Parsing..." spinner bar

### ISSUE THREAD

**Issue by TerraTech** [allinurl/goaccess#903]
I plan on adding a switch to disable the "Parsing..." bar (with included spinner).  It seems the ```--no-progress``` switch does not suppress it.

Initial question is should the ```--no-progress``` switch suppress it as well?

If not, then my initial thoughts are to add:  ```--no-parsing-spinner```

That will be tested for in: ```ui_spinner_create()``` and ```end_spinner()```, and if set they will return immediately.  However, I'm still carefully looking at the flow to see if there are better places to disable this progress bar.

I would like to have it suppressed as I pump logs through ```pv``` to show progress.
```sh
pump_logs | pv -l -F "${log} %b/$(getHuman ${cnt} %r%a %p %t %e" -s "${cnt}" | goaccess ...
```

**Comment by TerraTech** [comment]
Ok, I did add that, but it raises another question.  If the switch ```--process-and-exit``` is thrown, should ncurses even be initialized?  I ask because I did suppress the "Parsing..." progress bar, but when it runs, the screen clears and the pv output runs on the 8th line down.

**Comment by allinurl** [comment]
Just tested this and works fine. I think having separate flags as your commit does makes sense to me. I assume some folks may want the spinner but not the progress metrics. The only thing I'd add is that it disables both, the parsing spinner and progress metrics.

As far as where to disable this, I'd probably do it in the same functions you did.

Merged, closing this.
