### ISSUE TITLE
fgetline()/fgets() is causing grief for ssh piped logs

### ISSUE THREAD

**Issue by TerraTech** [allinurl/goaccess#911]
Some log files that I deal with are massive, therefore I have written a Go pipeline where a designated goaccess processing server pulls in the remote server log file for processing.

To simplify:   
 ```ssh foo@example.com cat access.log.gz | gunzip -c | pv | goaccess ... --process-and-exit -f -```

This one took some time to hunt down, because I made the faulty assumption that goaccess was really using glibc's getline() since I ```./configure --with-getline ...``` configured it to do so.  So initially I was looking in the wrong direction.  :(

It goes very much sideways at this point, because the fgets() returns NULL with errno==EAGAIN.  There is a race on the stdin pipe and goaccess wins that race every time with no convention for handling any tumbleweeds that roll by fgets().
https://github.com/allinurl/goaccess/blob/49febb5e63126c8d0e0f60c77ed5f8ffdb9d7a1e/src/parser.c#L2590

As a quick way to test if I could change the race winner, I threw goaccess under the bus by running it under ```... | strace -f -owtf goaccess ...```.  At that point, the ssh side won the race against goaccess's fgets() call.

Thinking about it, this may explain why in some rare cases, the following (local file) processing pipeline was failing to process some log files:
```gunzip -c access.log.gz | pv | goaccess ... --process-and-exit -f -```

I see that the getline() alternative replacement fgetline() was added in:  https://github.com/allinurl/goaccess/commit/10302f686b15b29031804dadc8b2cb57036be7f4

Right now, I'm working on a fix whereby testing if running under ```--process-and-exit```, and if so, then catch the ```errno==EAGAIN``` and ```continue;``` since it won't be running in interactive mode.  Preliminary testing shows the fix to be working for my ```--process-and-exit``` case.

@allinurl You will most likely want to look at the PR fix and augment (or refactor) it for the *interactive* case.

**Comment by allinurl** [comment]
Thanks for catching this. Let me try to reproduce this on my side and I'll merge it later today. Just to be sure, this occurs randomly upon ssh'ing into a remote machine and piping data into goaccess, which then fails with a blank report/output? i.e.,

    ssh foo@example.com cat access.log.gz | gunzip -c | pv | goaccess --process-and-exit -

**Comment by TerraTech** [comment]
For me, it wasn't random - if there was no data (yet) in the pipe for fgets() to read, it would exit out of the while{} loop (errno==EAGAIN) and continue on to do nothing.  Basically it acted like I was piping in a zero sized log file.

Ever since I patched this, I have been able to consistently process both (via ssh) remote and local log files with no problems.
