### ISSUE TITLE
Slow terminal keyboard input while tailing via SSH and having local goaccess parse from the pipe

### ISSUE THREAD

**Issue by rigelhope** [allinurl/goaccess#914]
I'm using goaccess v1.2 from the repo 
on a headless debian stretch
in a tmux v2.1 session
using a pipe from stdin, whose source is tail -f from a remote server
(whew!)

ive found that keyboard input is not just slow, much slower than anything else i'm running on the same server but also that keyboard-input such as tab, cursor, pgup/dn inputs are just getting lost.

looking at 'top', the goaccess process is competing occasionally with other processes running on the same server for the resource-usage spot, but still using <1% of cpu and RAM both, so it's not recource-hogging or memory-leaking, by any means. i can stream HD video from the same server with  few interruptions, so processing text seems trivial resource-wise by comparison.

I'm not sure where to start debugging this, i am (embarassingly) unfamiliar with C, so some help troubleshooting would be appreciated.

**Comment by allinurl** [comment]
Thanks for reporting this. 

Have you tried running goaccess without tmux? Just curious if it has something to do it with it. Also, how many requests per sec are you getting? would this be a really busy server? I ask this cause currently the TUI doesn't run its own thread and therefore if you are getting a bunch of requests per sec, then goaccess has to split the time between processing the log and the keyboard inputs.

**Comment by rigelhope** [comment]
it is an exceedingly slow server, a few hundreds-to-thousands of requests per day. if it were highly trafficked i would not have thought it all that strange.

i'll try it without tmux and report back.

one thing i also notice is that when i 'q'to quit, it does not send me directly back to the shell. this is repeatable, that it requires a 'q' to exit goaccess, but that just sends me to a process without any output to stdin. i have to ^C in order to get back to a command line.

report without tmux will be forthcoming.

**Comment by allinurl** [comment]
One thing to note is that `tail -f` will keep the pipe opened even when goaccess has already exited. Same issue for instance, `tail -f syslog | grep -q 'cron'` tail will exit on SIGPIPE, however it will only get SIGPIPE until an extra byte is written to the tail'd file. SIGTERM, SIGINT (Ctrl+c) should close tail fine though.

**Comment by rigelhope** [comment]
ah, that explains the hang-on-goaccess-exit issue. noted.

as for the rest, really not sure where to start. suggestions welcome.

**Comment by allinurl** [comment]
I'd suggest trying the following:

1. Try running goaccess with a static log (no data being appended) and see how's the response.
2. Can you run goaccess directly against the log without `tail -f`. e.g., `goaccess access.log --log-format=COMBINED`
3. Can you try running some other ncurses program on the same server, e.g., htop
4. Do you have some other machine available where you can test this out as well?

Thanks.

**Comment by rigelhope** [comment]
unable to reproduce issue with either static log file (1), or when using a separate process to continuously mirror the log file locally (again using tail -f) but without a pipe to goaccess. other ncurses programs do not display this behavior

i think that the pipe-only thing probably does narrow things down a bit, but i think i need to do more reading about the guts of bash input redirectors before i could offer a reason why that might be.

**Comment by allinurl** [comment]
Can you please post the exact command you are using so I can try to reproduce this on my side? and any additional steps that may help to replicate this behavior. Thanks

**Comment by rigelhope** [comment]
ssh $user@$remote_site -i $custom_key_location 'tail -f /remote/path/to/logfile' | goaccess - --log-format=COMBINED

**Comment by allinurl** [comment]
Thanks. I was able to reproduce this on my side. Let me see what I find and I'll post back.

**Comment by allinurl** [comment]
ssh -t -t $user@$remote_site -i $custom_key_location 'tail -f /remote/path/to/logfile' | goaccess - --log-format=COMBINED

This forces a tty on the ssh session so this should address this issue.

Per ssh's man

> -t        Force pseudo-terminal allocation.  This can be used to execute arbitrary screen-based programs on a remote machine, which can be very useful, e.g. when implementing menu services.  Multiple -t options force tty allocation, even if ssh has no local tty.

Please let me know if that solves the issue you were experiencing.

**Comment by allinurl** [comment]
My bad, I was testing this assuming goaccess was installed on the remote machine, e.g., 

    ssh -t -t root@host 'tail -f /var/log/apache2/access.log | goaccess - --log-format=VCOMBINED'

I'll look into it.

**Comment by allinurl** [comment]
This should be fixed. Please update to v1.4.2. Should work with:

    ssh -n root@server 'tail -f /var/log/apache2/access.log' | goaccess - --log-format=COMBINED

**Note**, SSH requires `-n` so GoAccess can read from stdin.

Closing this. Feel free to reopen it if needed.
