### ISSUE TITLE
cloudfront x-edge-location not present in report

### ISSUE THREAD

**Issue by jfc-evs** [allinurl/goaccess#915]
When using cloudfront logs type it would be great to have statistics on x-edge-location
I do not see this value in any report (html, csv or json)

**Comment by allinurl** [comment]
Are you looking to have a dedicated panel that displays this metric? or should this metric be part of an existing panel? 

BTW, a quick workaround and if you are not using the virtualhost panel, you can simply use %v to display the x-edge-location.

**Comment by jfc-evs** [comment]
%v is ok 
I changed goaccess.conf using :

# AWS | Amazon CloudFront (Download Distribution)
log-format %d\t%t\t%v\t%b\t%h\t%m\t%^\t%r\t%s\t%R\t%u\t%^

virtual host panel display the info but it is not exported in my csv file ?
