### ISSUE TITLE
nginx log_format for NCSA w/ Virtual Host

### ISSUE THREAD

**Issue by kawaii** [allinurl/goaccess#916]
I'm using the default nginx log_format currently:
```
log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';
```
What needs to be added to this (I tried adding `$host` at the start before `$remote_addr` but it still didn't like it) in order to use the NCSA /w Virtual Host option? Thanks! :)

**Comment by allinurl** [comment]
Please post a few lines from your access log in order to determine goaccess log format. You can also try [**this script**](https://github.com/stockrt/nginx2goaccess) to find this out.

**Comment by kawaii** [comment]
```
00.000.000.00 - - [14/Oct/2017:18:53:16 -0400] "GET REDACTED HTTP/2.0" 200 905 "REMOVED REFERRER" "Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36"
```
This is my current format. :)

**Comment by kawaii** [comment]
Ah, I've resolved the issue just now myself, was missing the expected : after the VHOST. :)
