### ISSUE TITLE
--max-items ignored when running goaccess within php

### ISSUE THREAD

**Issue by Ealireza** [allinurl/goaccess#917]
hi , 
when i run go access on bash 
/usr/bin/goaccess --max-items=1024  --keep-db-files --load-from-disk --db-path=/root/stats/ --output /root/test.csv

it working  , and 1024 item generate on output .
but when i run in using php 

<?
exec ('/usr/bin/goaccess --max-items=1024  --keep-db-files --load-from-disk --db-path=/root/stats/ --output /root/test.csv');
?>
it ignore --max-items and use 365

**Comment by allinurl** [comment]
How are you running it in PHP?

**Comment by Ealireza** [comment]
i run it using exec , 
after editing source files , i set value on source code and compile ..

my problem solved .

**Comment by allinurl** [comment]
This issue should be fixed per this [commit](https://github.com/allinurl/goaccess/commit/2fb119c95545ad8662deafaacdbd804be4e18a87). It will be pushed out in the upcoming release.
