### ISSUE TITLE
Journald support

### ISSUE THREAD

**Issue by FedericoCeratto** [allinurl/goaccess#922]
Journald is becoming popular and requires journalctl to extract and parse logs instead of reading files on disk. Goaccess could fetch logs from it.

**Comment by allinurl** [comment]
Are these web server requests? Could you please post a some lines from your journalctl that you would like goaccess to parse?

**Comment by allinurl** [comment]
@FedericoCeratto Any notes on this? Thanks

**Comment by FedericoCeratto** [comment]
journald can contain logs from webservers. Some examples:

nginx conf: `access_log syslog:server=unix:/dev/log;`

```
journalctl -u nginx.service --since today
journalctl -u nginx.service --since today -o json
```
There's a handful of -o flags for journalctl

Example output:
```
myhost nginx: 192.30.xxx.xx - - [03/Nov/2017:15:54:59 +0000] "GET /badges/debian/testing/neovim/version.svg HTTP/1.1" 200 933 "-" "github-camo (bacd3d5b)"
```

**Comment by allinurl** [comment]
Wouldn't this work?

    journalctl -u nginx.service --since today | goaccess

**Comment by allinurl** [comment]
Assuming `journalctl -u nginx.service --since today` simply outputs web server requests, then it should be totally doable to pipe the output into goaccess and configure the log-format accordingly. Closing this, feel free to reopen it if needed.
