### ISSUE TITLE
Slackware Build Updated to 1.2

### ISSUE THREAD

**Issue by slackhead** [allinurl/goaccess#924]
Hi

I just wanted to let you know that I've just submitted goaccess 1.2 to slackbuilds.org. It will probably be week before it's approved.

The current link is here:
https://slackbuilds.org/repository/14.2/system/goaccess/
And this will remain the same when 1.2 is up.

Cheers.

**Comment by allinurl** [comment]
This is great :) Thanks submitting and sharing this! Looks like it's up already in 14.2.
