### ISSUE TITLE
Scan gzipped log files

### ISSUE THREAD

**Issue by FedericoCeratto** [allinurl/goaccess#925]
It would be nice if goaccess could scan gzipped log files and perhaps ignore them if they contain old data (in comparison to the contents of the database)

**Comment by allinurl** [comment]
You should be able to parse gzipped log files using `zcat` or `gunzip`. As far as ignoring old data, would this be the same as what has been proposed on #334?

**Comment by allinurl** [comment]
Sorry, I'm still not sure I understand, can't you achieve this by scanning your gzipped log files with `zcat /var/log/nginx/access.log* | goaccess -`?

**Comment by FedericoCeratto** [comment]
@allinurl I replied to #334 - perhaps we can move the conversation there and close this issue.

**Comment by allinurl** [comment]
I agree, ignoring old data sounds like a dup of #334. Closing this. Thanks for bringing this up!

**Comment by prologic** [comment]
You can do something like this:

```
for logfile in /var/log/caddy/access/*.log.gz; do zcat "$logfile" | goaccess --persist --db-path /var/lib/goaccess --agent-list --with-output-resolve
r --jobs 2 --log-format caddy --geoip-database /etc/caddy/GeoLite2-City.mmdb -o /var/www/report.html; done
```

**Comment by allinurl** [comment]
@prologic thanks for sharing that!
