### ISSUE TITLE
Suppress Google Chrome translate

### ISSUE THREAD

**Issue by TerraTech** [allinurl/goaccess#929]
Is anyone else experiencing Google Chrome wanting to "Translate this page" on the generated reports?  I have seen firsthand reports that Chrome is trying to translate ```Maltese ==> English```.  I've tried it on different machines with same result.

@allinurl Would you be open to a PR that tweaks the head and adds:
```
<meta name="google" content="notranslate">
<meta http-equiv="Content-Language" content="en">
```

**Comment by allinurl** [comment]
I'm open to merge that PR. One thing to note is that it may not always be `en` though, the upcoming release is shipping i18n support (through `gettext`). French and Spanish have already been added. We may need to add the content language somewhere in [here](https://github.com/allinurl/goaccess/blob/master/src/output.c#L222).

**Comment by TerraTech** [comment]
I'm just going to start with "en" and other languages can be dynamically wired in later.  At least this will anchor where it needs to be done at.

**Comment by TerraTech** [comment]
Initial tests are positive and Google Chrome is no longer popping up the "Translate this page" dialog.  :)
