### ISSUE TITLE
NGINX as reverse proxy + Apache 2

### ISSUE THREAD

**Issue by spinoz4** [allinurl/goaccess#931]
Hi folks. 

I have a reverse NGINX proxy and a virtual host on apache 2.  How I config the following apache 2's log format on goacess?

`LogFormat "%h (%{X-Forwarded-For}i) %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-agent}i\"" combined_with_forwarded_for
`

Example output:

`192.168.XX.X (14.139.155.214) - - [01/Nov/2017:08:03:14 -0500] "GET /archlinux/iso/2017.11.01/archlinux-2017.11.01-x86%5F64.iso HTTP/1.1" 200 548405248 "-" "Transmission/2.84"`

Thank you,
S.

**Comment by allinurl** [comment]
Do you know how IPs are delimited in the `X-Forwarded-For` field (assuming you can get multiple IPs in there)?

**Comment by spinoz4** [comment]
I can get multiple IPs indeed, but I don't know how IPs are delimited. Will the reverse proxy configuration helps?
If it helps in something is this:

```
proxy_pass_header Authorization;
proxy_pass http://$upstream;
proxy_set_header Host $host;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_http_version 1.1;
```

**Comment by allinurl** [comment]
> $proxy_add_x_forwarded_for the “X-Forwarded-For” client request header field with the $remote_addr variable appended to it, separated by a comma.

So this should work:

    goaccess access.log --log-format='%^ ~h{,"() } %^[%d:%t %^] "%r" %s %b "%R" "%u"' --date-format=%d/%b/%Y --time-format=%T

**Comment by spinoz4** [comment]
It works! Thank you so much.

**Comment by allinurl** [comment]
Glad that worked :)
