### ISSUE TITLE
Please provide direct download links for deb-packages

### ISSUE THREAD

**Issue by malaire** [allinurl/goaccess#932]
It would be really useful to provide direct download links for deb-packages at https://goaccess.io/download, if user wants to install them manually, since http://deb.goaccess.io/pool does NOT support browsing directories.

e.g. for current version links are
http://deb.goaccess.io/pool/main/g/goaccess/goaccess_1.2_amd64.deb
http://deb.goaccess.io/pool/main/g/goaccess-tcb/goaccess-tcb_1.2_amd64.deb

**Comment by allinurl** [comment]
Thanks for pointing that out. It should now let you browse https://deb.goaccess.io/pool

**Comment by malaire** [comment]
Thank you, browsing works now.
