### ISSUE TITLE
Installing on CentOS: Missing Dependencies

### ISSUE THREAD

**Issue by srguglielmo** [allinurl/goaccess#936]
Hello,

I am installing GoAccess from source on CentOS 7. As per the documentation, I have installed the following packages:

- ncurses-devel
- geoip-devel
- tokyocabinet-devel
- openssl-devel
- "Development Tools" yum group

I am configuring GoAccess with: `./configure --enable-utf8 --enable-geoip=mmdb`

However, the output is as follows:

> ./configure --enable-utf8 --enable-geoip=mmdb 
> checking for a BSD-compatible install... /bin/install -c
> checking whether build environment is sane... yes
> checking for a thread-safe mkdir -p... /bin/mkdir -p
> checking for gawk... gawk
> checking whether make sets $(MAKE)... yes
> checking for gcc... gcc
> checking whether the C compiler works... yes
> checking for C compiler default output file name... a.out
> checking for suffix of executables... 
> checking whether we are cross compiling... no
> checking for suffix of object files... o
> checking whether we are using the GNU C compiler... yes
> checking whether gcc accepts -g... yes
> checking for gcc option to accept ISO C89... none needed
> checking for style of include used by make... GNU
> checking dependency style of gcc... gcc3
> checking whether gcc and cc understand -c and -o together... yes
> checking for pthread_create in -lpthread... yes
> checking build system type... x86_64-unknown-linux-gnu
> checking host system type... x86_64-unknown-linux-gnu
> checking whether to build with rdynamic for GNU ld... yes
> checking for MMDB_open in -lmaxminddb... no
> configure: error: 
>     *** Missing development files for libmaxminddb library.

Am I missing a package or doing something else wrong?

Thanks

**Comment by srguglielmo** [comment]
I found the issue. I had to install the `libmaxminddb-devel.x86_64` package as well. Maybe this should be added to the docs for CentOS?

Thanks!

**Comment by allinurl** [comment]
This has been added to the [download](http://goaccess.io/download) page. Thanks for heads up!
