### ISSUE TITLE
Trying to match pattern on custom web server log (syslog)

### ISSUE THREAD

**Issue by MohamedAlaa** [allinurl/goaccess#937]
Hello, I've been trying to match the pattern without success.

sample from my syslog:

```
Nov  3 00:02:37 cd-msite-central1-201705121615-4xql cd_msite: [03/Nov/2017:00:02:37 +0000] viejo-m.segundamano.mx (130.211.3.134) "GET / HTTP/1.1" (403) 321 "-" "GoogleHC/1.0" "130.211.3.134" Upstream(10.68.0.65:80 0.145 321)
```

my log format in nginx:

```
[$time_local] $server_name ($client_ip) "$request" ($status) $body_bytes_sent "$http_referer" "$http_user_agent" "$client_forwarded" Upstream($upstream_addr $upstream_response_time $upstream_response_length)
```

Thanks a lot in advance.
Mohamed.

**Comment by allinurl** [comment]
This should do it:

    goaccess access.log --log-format='%^[%d:%t %^] %v (%h) "%r" (%s) %b "%R" "%u" %^ %^ %T %^' --date-format=%d/%b/%Y --time-format=%T

**Comment by MohamedAlaa** [comment]
Thanks a lot @allinurl for your quick reply. but I'm getting an error:

```
goaccess: unrecognized option `--refox/50.0"'
```

**Comment by allinurl** [comment]
Did you copy the exact command as above. It seems you added something else as well to the command line and thus that message. Perhaps `Firefox/50.0`?

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it as needed.
