### ISSUE TITLE
Parsing IBM WebSeal 6.1.1 logs (Tivoli Access Manager)

### ISSUE THREAD

**Issue by FrankieReds** [allinurl/goaccess#939]
Hi.
I'm trying to parse IBM WebSeal logs without success,

The log record is in this format:
    _ip_address_client_ - _username_ dd/mm/yyyy:hh:mm:ss +0200 "_url request_" _status_code_ _bytes_

Notice that the "-" and "+200" characters in second and fifth position are fixed

I've personalized the log-format parameter in this way:
```
%h - %e %d:%t %^ "%r" %s %b
and --date-format=%d%b%Y
```

but I get the message:

Parsed 10 lines producing the following errors:
Token '_all my original log record_' doesn't match specifier '%h'
.................
.................

It would seem that all the entire log record is parsed with %h specifier, without consider every single word. 
Where I am wrong?
Thank you.

**Comment by allinurl** [comment]
Can you please post a few lines from your access log so I can take a look? Thanks.

**Comment by FrankieReds** [comment]
Sure.
Here are some lines:

10.54.136.177 - C012065 25/Oct/2017:14:11:04 +0200 "POST /bpm/notification/cometd/connect HTTP/1.1" 200 58 -
10.54.32.73 - C077062 25/Oct/2017:14:11:35 +0200 "GET /was85/autenticazione/login.jsp HTTP/1.1" 200 8227 -
77.43.29.122 - e677350e 25/Oct/2017:14:11:33 +0200 "POST /wass/LAMPO/lampo?discaricoConfirm HTTP/1.1" 200 10013 -

Thanks.

**Comment by allinurl** [comment]
This should do it:

    goaccess access.log --log-format='%h %^ %v %d:%t %^ "%r" %s %b %^' --date-format=%d/%b/%Y --time-format=%T

**Comment by FrankieReds** [comment]
Yes, this works fine!
Thank you for your support. 
Best regards.
