### ISSUE TITLE
Ability to ignore crawlers

### ISSUE THREAD

**Issue by allinurl** [allinurl/goaccess#94]
Add a command line option to ignore crawlers.

**Comment by AndroAndrei** [comment]
what are crwalers exactly in the report.

**Comment by allinurl** [comment]
@AndroAndrei good question, anything on this [list](https://github.com/allinurl/goaccess/blob/master/src/browsers.c#L125) marked as "Crawlers".

**Comment by AndroAndrei** [comment]
allright,good!!!

**Comment by strk** [comment]
I'm passing --ignore-crawlers but I still see Crawlers in the "Browsers" graph. Is this expected ? Or can it be due to the --restore option, loading crawlers data from db ?

**Comment by allinurl** [comment]
@strk, restore will definitely bring those crawlers back since it literally just loads the database from its previous state—it doesn’t reprocess anything that was already parsed.
