### ISSUE TITLE
Implement a command line argument to show the configure options at compile time

### ISSUE THREAD

**Issue by ms217** [allinurl/goaccess#940]
As subject is suggesting it.
Afaik GoAccess doesn't support this. At least I haven't found this option in the latest stable 1.2 release.

An example with NGINX: I can check the configure arguments when I issue "nginx -V".
I need this for a GoAccess implementation into a webadministration panel.

**Comment by millsjustin** [comment]
Duplicate of #1068.
Implemented in #1101.

**Comment by allinurl** [comment]
Closing this. Thanks!
