### ISSUE TITLE
$remote_user auth tracking

### ISSUE THREAD

**Issue by jaredvacanti** [allinurl/goaccess#941]
I am using Nginx combined [log_format](http://nginx.org/en/docs/http/ngx_http_log_module.html#log_format) (log-format %h %^ %e [%d:%t %^] %^ "%r" %s %b "%R" "%u") but cannot get a remote_user panel to show. My exact setting is:

`goaccess --log-format='%h %^ %e [%d:%t %^] %^ "%r" %s %b "%R" "%u"' --date-format=%d/%b/%Y --time-format=%T -f /var/log/nginx/access.log`

but this will not show a panel for `remote_user`. I am using Ubuntu 14.04 LTS with GoAccess - 0.9.4 and nginx version: nginx/1.10.3 (Ubuntu). Is there some additional setting I need to pass to enable this panel?

**Comment by allinurl** [comment]
`%e` was introduced in v1.1. You probably want to upgrade to the [**latest**](https://goaccess.io/download#official-repo) version.

**Comment by jaredvacanti** [comment]
Thanks - this worked. For completeness I had installed with `apt-get goaccess`.
