### ISSUE TITLE
~/.goaccessrc ignored

### ISSUE THREAD

**Issue by minusf** [allinurl/goaccess#942]
```
$ goaccess -V
GoAccess - 1.2.
For more details visit: http://goaccess.io
Copyright (C) 2009-2016 by Gerardo Orellana

$ echo $HOME
/home/user
$ ls $HOME/.goaccessrc
/home/user/.goaccessrc

$ goaccess /var/log/nginx/access.log

GoAccess - version 1.2 - Jul 23 2017 03:05:48
Config file: /etc/goaccess.conf

Fatal error has occurred
Error occured at: src/goaccess.c - set_curses - 1394
No time format was found on your conf file.
```

**Comment by allinurl** [comment]
Thanks for reporting this. This has been fixed upstream. Can you please try to build from [**development**](https://github.com/allinurl/goaccess#build-from-github-development) and see if that solves the issue for you?

**Comment by minusf** [comment]
sorry for the duplicate, searched only the open issues..
i am limited to centos EPEL repos at work, but i am sure eventually i will see this fixed :}

**Comment by allinurl** [comment]
No worries. Thanks again!
