### ISSUE TITLE
Nginx (reverse) proxy with goaccess on https+wss for real-time-html

### ISSUE THREAD

**Issue by jaredvacanti** [allinurl/goaccess#943]
I can't get real-time reports to work properly behind an Nginx proxy when Nginx & `goaccess` are running on the same machine.

I am on `Ubuntu 14.04 LTS`, `nginx/1.10.3`, and `GoAccess - 1.2.`. 

Here is my `/etc/goaccess.conf` (stripped of comments):

```
time-format %H:%M:%S
date-format %d/%b/%Y
log-format '%h %^ %e [%d:%t %^] %^ "%r" %s %b "%R" "%u"'

config-dialog false
hl-header true
json-pretty-print false
no-color false
no-column-names false
no-csv-summary false
no-progress false
no-tab-scroll false
with-mouse false


addr 127.0.1.1
daemonize true
origin https://server-logs.example.org
port 8010
real-time-html true
ssl-cert /etc/letsencrypt/live/server-logs.example.org/fullchain.pem
ssl-key /etc/letsencrypt/live/server-logs.example.org/privkey.pem
ws-url wss://server-logs.example.org:8080/ws/


log-file /var/log/nginx/access.log

agent-list false
with-output-resolver false
http-method yes
http-protocol yes
output-format /var/www/server-logs.example.org/html/index.html
no-query-string false
no-term-resolver false
444-as-404 false
4xx-to-unique-count false
all-static-files false
double-decode false
ignore-crawlers false
crawlers-only false
ignore-panel REFERRERS
ignore-panel KEYPHRASES

real-os true

static-file .css
static-file .js
static-file .jpg
static-file .png
static-file .gif
static-file .ico
static-file .jpeg
static-file .pdf
static-file .txt
static-file .csv
static-file .zip
static-file .mp3
static-file .mp4
static-file .mpeg
static-file .mpg
static-file .exe
static-file .swf
static-file .woff
static-file .woff2
static-file .xls
static-file .xlsx
static-file .doc
static-file .docx
static-file .ppt
static-file .pptx
static-file .iso
static-file .gz
static-file .rar
static-file .svg
static-file .bmp
static-file .tar
static-file .tgz
static-file .tiff
static-file .tif
static-file .ttf
static-file .flv
```

This is my Nginx conf file for the websocket component: 

```
map $http_upgrade $connection_upgrade {
        default upgrade;
        '' close;
    }

server {
        listen 8080 ssl;

        location /ws/ {
                proxy_pass http://127.0.1.1:8010;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection $connection_upgrade;
        }

        ssl_certificate /etc/letsencrypt/live/server-logs.example.org/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/server-logs.example.org/privkey.pem; 

}
 ```

`netstat` will show the goaccess server running with

```
$ sudo netstat -tulpn
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.1.1:8010          0.0.0.0:*               LISTEN      1347/goaccess
```

and `telnet` can connect to the server:

```
$ telnet 127.0.1.1 8010
Trying 127.0.1.1...
Connected to 127.0.1.1.
Escape character is '^]'.
```

Now, the `wss` will always time out after 60 seconds. The static page is loading fine and the configuration is working from that page (by testing if changing the `ws-url` actually makes adjustments on the client side -- it does). 

Not sure how to proceed - any ideas?

**Comment by jaredvacanti** [comment]
I'm getting an error when trying to connect to the websocket on my client side: 

`WebSocket connection to 'wss://server-logs.example.org:8080/ws/' failed: Error during WebSocket handshake: Unexpected response code: 502`

I have successfully used an echo server on with this same proxy setting on this machine... is there a way to debug what `goaccess` is processing? I passed `--invalid-requests=req.log` and am not seeing any data appended.

**Comment by jaredvacanti** [comment]
Sorry for spam - this is a proxy issue not one with `goaccess` - my recommendation is to make sure all protocols match (https + wss) on all sides, otherwise `goaccess` will (correctly) refuse the connection.

**Comment by allinurl** [comment]
Sorry for the late response. Were you able to set this up? Please feel free to post the findings. Otherwise, I can try to set up a reverse proxy using Nginx and see if I can reproduce the issue. Thanks.
