### ISSUE TITLE
real-time report doesn't seem to update

### ISSUE THREAD

**Issue by aaron-hanson** [allinurl/goaccess#949]
I initially couldn't get it to run on port 7890 so I edited the conf to use 7891.  I then ran it like so:

`sudo goaccess /var/log/nginx/access.log -o /var/www/mysite/access.html --log-format=COMBINED --real-time-html`

It reported:  WebSocket server ready to accept new client connections.  

ps shows the process still running:

`ps -ef | grep goaccess`
`root      4398  1988  0 19:11 pts/0    00:00:00 sudo goaccess /var/log/nginx/access.log -o /var/www/mysite/access.html --log-format=COMBINED --real-time-html`
`root      4399  4398  2 19:11 pts/0    00:00:00 goaccess /var/log/nginx/access.log -o /var/www/mysite/access.html --log-format=COMBINED --real-time-html`

Then, browsing to `https://myhost/access.html` shows the report, but it doesn't seem to be updating as new traffic hits my log.  Any ideas?

**Comment by allinurl** [comment]
Can you please post the output from your browser's console? Also, make sure to open the port if you are behind NAT or firewall. You can also test the connection using telnet:

    telnet myhost 7891

**Comment by aaron-hanson** [comment]
Thanks, port wasn't opened properly.  Working great now.
