### ISSUE TITLE
Custom Log format of access log help

### ISSUE THREAD

**Issue by saudkh** [allinurl/goaccess#950]
Can someone help me with the below format? 

    000.admin.net 000.000.000.000 - 2012909 [20/Nov/2017:09:08:00 +0000] (0 s) "GET /images/logo_brand.png HTTP/1.1" 200 8087 "https://000.admin.net/css/screen-default.css" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0"

**Comment by allinurl** [comment]
This should do it:

    goaccess access.log --log-format='%v %h %^[%d:%t %^] %^(%T %^"%r" %s %b "%R" "%u"' --date-format='%d/%b/%Y' --time-format=%T --enable-panel=REFERRERS --enable-panel=KEYPHRASES

**Comment by saudkh** [comment]
That worked beautifully! thank you

**Comment by allinurl** [comment]
Glad that worked :)
