### ISSUE TITLE
custom log format

### ISSUE THREAD

**Issue by lee-ji-eun** [allinurl/goaccess#951]
im install apache in /opt, 
apache/conf/httpd.conf
<IfModule log_config_module>
    #
    # The following directives define some format nicknames for use with
    # a CustomLog directive (see below).
    #
    LogFormat "%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" combined
    LogFormat "%h %l %u %t \"%r\" %>s %b" common

    <IfModule logio_module>
      # You need to enable mod_logio.c to use %I and %O
      LogFormat "%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\" %I %O" combinedio
    </IfModule>

    #
    # The location and format of the access logfile (Common Logfile Format).
    # If you do not define any access logfiles within a <VirtualHost>
    # container, they will be logged here.  Contrariwise, if you *do*
    # define per-<VirtualHost> access logfiles, transactions will be
    # logged therein and *not* in this file.
    #
    CustomLog "logs/access_log" common

    #
    # If you prefer a logfile with access, agent, and referer information
    # (Combined Logfile Format) you can use the following directive.
    #
    #CustomLog "logs/access_log" combined
</IfModule>

-------------------------------------------------------------------
and httpd-vhosts.conf
add ErroLog, CutomLog every vhost, under format
ErrorLog "logs/{folder name}-error_log"
CustomLog "logs/{folder name}-access_log" combined

result /apache/logs file name
{folder name}-access_log
{folder name}-error_log
{folder name}-access_log-20171121
{folder name}-error_log-20171121

open log file
ip - 22/Nov/2017:10:56:25 +0900 ~
but, /etc/goaccess.conf date-format 
%b -> not Nov, change my country language

so, where is edit /etc/goaccess.conf format?

i want that each /home/ folders in web server is goaccess to report_{folder name}.html

**Comment by allinurl** [comment]
You can run 

    goaccess --dcf

To find out where the default config file is located. Otherwise you can place a copy of [this](https://raw.githubusercontent.com/allinurl/goaccess/master/config/goaccess.conf) in ~/.goaccessrc and run goaccess as:

    goaccess access.log -p ~/.goaccessrc

You can create your custom output filename, e.g., 

    goaccess access.log -o report_`date +%F_%H-%M-%S`.html 

OR

    goaccess access.log -o report_${PWD##*/}.html

**Comment by allinurl** [comment]
Any updates on this?

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
