### ISSUE TITLE
please!! how is the log format for my apache log format

### ISSUE THREAD

**Issue by hardlick** [allinurl/goaccess#953]
logFormat in apache:

LogFormat "%{X-Forwarded-For}i %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" varnishcombined

**Comment by hardlick** [comment]
![image](https://user-images.githubusercontent.com/1672644/33221433-84aa2100-d11d-11e7-9f8c-7f7754455b0a.png)

not show unique visitor

**Comment by hardlick** [comment]
this is the output of access.log:

68.53.71.200 - - [24/Nov/2017:11:20:17 -0600] "POST /admin/messages/fnGetMessages?jsoncallback=jQuery21100750561944935858_1511543416726 HTTP/1.1" 200 153 "http://websales.tornadobus.com/sales/sale/index" "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0"

the log format on:
sudo nano /usr/local/etc/goaccess.conf

log-format %h %^[%d:%t %^] "%r" %s %b

**Comment by hardlick** [comment]
i have more failed request, 
my logFormat in apache:
LogFormat "%{X-Forwarded-For}i %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" varnishcombined

and log format in goaccess conf:
log-format %h %v %u %^[%d:%t %^] "%r" %s %b  "%R" "%u"

any ideas?

**Comment by allinurl** [comment]
Can you please attach several lines from your access log so I can take a look? Thanks.

**Comment by hardlick** [comment]
Examples:
68.213.240.70 domaininc.com - [25/Nov/2017:16:13:40 -0600] "GET /sales/sale/listAgentsByTerm?term=EL+PRI&guid=366fbe2d-e223-247f-5f5e-15bf561b5233 HTTP/1.1" 200 97 "http://domaininc.com/sales/sale/index" "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0

192.30.187.117 domaininc.com - [25/Nov/2017:16:13:38 -0600] "GET /sales/sale/index HTTP/1.1" 200 43801 "http://domaininc.com/admin/welcome/index" "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0"

68.213.240.70 domaininc.com - [25/Nov/2017:16:13:32 -0600] "GET /sales/sale/index HTTP/1.1" 200 51262 "http://domaininc.com/reports/passenger/index" "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0"

192.30.187.117 domaininc.com - [25/Nov/2017:16:13:32 -0600] "GET /admin/welcome/index HTTP/1.1" 200 19735 "http://domaininc.com/public/login" "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0"

23.20.45.221 - - [25/Nov/2017:16:13:30 -0600] "POST /public/ApiFriendly/getTravels HTTP/1.1" 200 6405 "-" "Wan (Contact carrier-ops@Wa.com for issues)"

99.45.222.196 - - [25/Nov/2017:16:13:30 -0600] "GET /media/fonts/raleway500.woff HTTP/1.1" 304 418 "https://websales.com/min/b=media/css&f=websale/redcoach/1.11.1/jquery-ui-1.11.1.custom.css,jquery.countdown.min.css,ubrowser/browser-detectih.min.css?version=1511269071" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36

**Comment by allinurl** [comment]
This works for the given lines, give it a shot!

    goaccess access.log --log-format='%h %v %^[%d:%t %^] "%r" %s %b "%R" "%u"' --date-format='%d/%b/%Y' --time-format=%T --enable-panel=REFERRERS --enable-panel=KEYPHRASES

**Comment by hardlick** [comment]
Thanks a lot!, its works!

**Comment by zolaahihi** [comment]
Cool guide hehe :D

**Comment by develforever** [comment]
Hi, this may be  helpful information: 
> ~hThe host (the client IP address, either IPv4 or IPv6) in a X-Forwarded-For (XFF) field. 

https://goaccess.io/man

**Comment by svastal** [comment]
Can you help me?

**Comment by allinurl** [comment]
@svastal Please try:

    goaccess access.log --log-format='%h %^[%d:%t %^] "%r" %s %b %D %^ "%R" "%u"' --date-format=%d/%b/%Y --time-format=%T

**Comment by svastal** [comment]
Thank you!
But there was different problem. The point was old goaccess version. Debian 9.9 (stretch) doesn't have the latest version of GoAccess in the default packages. It starts working after changing repository on official GoAccess.
