### ISSUE TITLE
Unable to open

### ISSUE THREAD

**Issue by ikaroweb** [allinurl/goaccess#954]
Hi,
I've this issue when i try to create a report.

goaccess -f /home/websitename/logs/access_log -a -o  --log-format=COMBINED /home/websitename/htdocs/report.html --real-time-html
Parsing... [0] [0/s]
GoAccess - version 1.2 - Oct 29 2017 18:03:51
Config file: /usr/local/etc/goaccess.conf

Fatal error has occurred
Error occured at: src/parser.c - read_log - 2669
Unable to open the specified log file. No such file or directory

Few lines of my log
xx.xx.xx.xx - - [27/Sep/2017:11:24:52 +0200] "GET /robots.txt HTTP/1.1" 404 208
xx.xx.xx.xx - - [27/Sep/2017:11:24:53 +0200] "GET / HTTP/1.1" 302 -

Thanks

**Comment by allinurl** [comment]
You need to specify the name of the output log after -o, e.g.,

    goaccess /home/websitename/logs/access_log -a -o /home/websitename/htdocs/report.html --log-format=COMBINED --real-time-html

**Comment by ikaroweb** [comment]
Parsed 10 lines producing the following errors:

Token for '%b' specifier is NULL.
Token for '%b' specifier is NULL.
Token for '%b' specifier is NULL.
Token for '%b' specifier is NULL.
Token for '%b' specifier is NULL.
Token for '%b' specifier is NULL.
Token for '%b' specifier is NULL.
Token for '%b' specifier is NULL.
Token for '%b' specifier is NULL.
Token for '%b' specifier is NULL.

Format Errors - Verify your log/date/time format

**Comment by allinurl** [comment]
Please use the common log format instead of combined.

    goaccess /home/websitename/logs/access_log -a -o /home/websitename/htdocs/report.html --log-format=COMMON --real-time-html

**Comment by ikaroweb** [comment]
Fine, now works thanks :)
