### ISSUE TITLE
Use GoAccess as a parser only and output basic data

### ISSUE THREAD

**Issue by x0v** [allinurl/goaccess#958]
@allinurl 
Is there an option in Goaccess by which I could be able to only get parsed results of log not the dashboard reports.

like this
Input
```
122.162.224.206 - - [11/Nov/2008:11:39:32 +0530] "GET /logs/ HTTP/1.1" 200 522 "http://in.1.p1.in.webhosting.yahoo.com/pdlogs" "Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1)" "qualtrapharma.com"
```
Output
```
 ip_address                 date_time  http_status  server_response  \
122.162.224.206 2008-11-11 11:39:03+00:53          200              522   

                                         referer method resource  protocol  \
http://in.1.p1.in.webhosting.yahoo.com/pdlogs    GET   /logs/  HTTP/1.1   

  device_brand device_model   os_family user_agent_browser  
         None         None  Windows XP                 IE  
```

**Comment by allinurl** [comment]
Great question! You should be able to get something very similar through the [**JSON**](https://goaccess.io/json) output.

**Comment by x0v** [comment]
Thanks for a reply, but Is it not possible to use only the parser output ? because 
1. it does not exactly generates parsed output.
2. Even if it does to some extent, it also calculates some statistics, which takes a little extra processing time.

I am finding ways if I could reduce that processing time and get the required output.

In short, I want to use only the parsing capability of goaccess.

**Comment by allinurl** [comment]
It doesn't have such capability. If you need something simple, I think you can add a basic function that reads the content of [`raw_data`](https://github.com/allinurl/goaccess/blob/master/src/goaccess.c#L280) and dumps it into an output file.

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.

**Comment by x0v** [comment]
Sorry for delayed reply 
thanks it was useful.
