### ISSUE TITLE
Multiple HAProxy files piped to live html goaccess will terminate the application

### ISSUE THREAD

**Issue by metrofox** [allinurl/goaccess#959]
Hello,

I'm trying to tail 2 HAProxy files into goaccess to monitor some traffic but it seems the application terminates after some seconds and it only parses a very small quantity of data, sometimes it will not even write any data into the output html file. Here's how I'm running it:

tail -qf HAProxy01/HAProxy.log HAProxy02/HAProxy.log | goaccess -o /var/www/html/haproxy.html --real-time-html --log-format='%^]%^ %h:%^ [%d:%t.%^] %^/%^/%^/%^/%L/%^ %s %b %^ %^ %^ %v "%r"' --date-format='%d/%b/%Y' --time-format='%H:%M:%S' -

echo $? returns 0

Formats are taken from: https://github.com/allinurl/goaccess/issues/374
Here's another issue I followed: https://github.com/allinurl/goaccess/issues/600

Also: is it possible to update/refresh the page after n seconds instead of every time a new entry is pushed? I think lots of I/O actions will be performed in my case, which is very resource consuming.

Thanks in advance!

**Comment by allinurl** [comment]
Does it work if you pipe only one log instead of two?

Currently it's not possible to set the update/refresh rate, but can I ask you to please open a new issue and I can certainly look into it. Thanks.

**Comment by metrofox** [comment]
I tried piping one log only, it behaves the same. 
It quits immediately, or it gets stuck or it only writes one entry into the HTML and then quits:

[Immediate exit]
root@syslog:/var/log/remote# time tail -qf HAProxy01/HAProxy.log | goaccess -o /var/www/html/haproxy.html --real-time-html --log-format='%^]%^ %h:%^ [%d:%t.%^] %^/%^/%^/%^/%L/%^ %s %b %^ %^ %^ %v "%r"' --date-format='%d/%b/%Y' --time-format='%H:%M:%S' -

real    0m0.004s
user    0m0.000s
sys     0m0.000s

[Stuck, HTML contains all 0; the log contains new entries]
time tail -qf HAProxy01/HAProxy.log | goaccess -o /var/www/html/haproxy.html --real-time-html --log-format='%^]%^ %h:%^ [%d:%t.%^] %^/%^/%^/%^/%L/%^ %s %b %^ %^ %^ %v "%r"' --date-format='%d/%b/%Y' --time-format='%H:%M:%S' -
^C

real    0m53.607s
user    0m0.000s
sys     0m0.004s

[Write one entry into the HTML and then quits]
time tail -qf HAProxy01/HAProxy.log | goaccess -o /var/www/html/haproxy.html --real-time-html --log-format='%^]%^ %h:%^ [%d:%t.%^] %^/%^/%^/%^/%L/%^ %s %b %^ %^ %^ %v "%r"' --date-format='%d/%b/%Y' --time-format='%H:%M:%S' -

real    0m3.986s
user    0m0.000s
sys     0m0.000s

**Comment by allinurl** [comment]
That's strange, first, can I ask you to verify that the log-format is actually matching your access log? just run goaccess straight against the log, e.g.,

    goaccess HAProxy01/HAProxy.log --log-format='%^]%^ %h:%^ [%d:%t.%^] %^/%^/%^/%^/%L/%^ %s %b %^ %^ %^ %v "%r"' --date-format='%d/%b/%Y' --time-format='%H:%M:%S'

If that works, can you also verify that `tail -qf HAProxy01/HAProxy.log` is actually dumping data? you can try piping data to another tool, e.g., `tail -qf HAProxy01/HAProxy.log | more`.  In addition, please try outputting to the command line instead of the HTML report.

    tail -f HAProxy01/HAProxy.log | goaccess - --log-format='%^]%^ %h:%^ [%d:%t.%^] %^/%^/%^/%^/%L/%^ %s %b %^ %^ %^ %v "%r"' --date-format='%d/%b/%Y' --time-format='%H:%M:%S'

**Comment by metrofox** [comment]
Both logs piped to ncurses work fine, the application will not quit:
tail -qf HAProxy01/HAProxy.log HAProxy02/HAProxy.log | goaccess -

I can see it quits when new entries from tail are piped into goaccess with the following command:

tail -qf HAProxy01/HAProxy.log HAProxy02/HAProxy.log | goaccess -o /var/www/html/haproxy.html --real-time-html -

When a new entry is met the goaccess exits.

**Comment by allinurl** [comment]
I was playing with this and I wasn't able to replicate this on my side. If the report is generated, do you see the green circle near the hamburger icon? can you please post the output from your browser's console?

Also, are you on v1.2? if you are, can you please build from [**development**](https://github.com/allinurl/goaccess#build-from-github-development) and see if that solves the issue. Thanks.

**Comment by allinurl** [comment]
Any updates on this? Thanks.

**Comment by metrofox** [comment]
Hi @allinurl 

Sorry for the late answer, by the way:
![image](https://user-images.githubusercontent.com/177062/33912663-aec01132-df8e-11e7-9106-352963d26b9b.png)
This is the error I got with the **stable** version 1.2

Now, I've just compiled from source and it's working fine! Thank you!

**Comment by allinurl** [comment]
Glad to hear that building from upstream solved the issue. Quick question, does your domain contain the word "get" somewhere within it? Just want to know which commit fixed the issue... 

Thanks. Closing this.

**Comment by metrofox** [comment]
Mmm no, if you're talking about the content of /etc/hostname: then no, it does not contain any *get* within it.

By the way it is full of GET methods (and so words) inside my HAProxy file:

`Dec 12 23:23:22 HAProxy02 haproxy[4019]: [...]  - - ---- 1/1/0/0/0 0/0 "GET /v1/healthcheck?recursive=true HTTP/1.1"`

I don't know if the above can help..

Thanks a lot for your support @allinurl !
