### ISSUE TITLE
Understand Matching Expressions for a Custom Log?

### ISSUE THREAD

**Issue by fbaptista** [allinurl/goaccess#962]
Is there any way to see why a Regex isn't matching? 

Original Access log format:

    LogFormat "%a %t \"%r\" %>s %I %b \"%{Referer}i\" \"%{User-Agent}i\" \"%{BALANCER_WORKER_ROUTE}e\" %{JSESSIONID}C \"%{Age}o\" %D" logrp 

1 line of :

    10.253.15.35 [07/Dec/2017:16:12:44 -0300] "POST /site/aproxypgeservices_services HTTP/1.1" 200 16948 4877 "-" "Jakarta Commons-HttpClient/3.1" "asespprodproxypge2:full-ha-server" - "-" 430778

go-access format isn't matching time-taken:  

    %h [%d:%t %^] \"%r\" %>s %^ %b \"%^\" \"%^\" \"%^\" %^ \"%^\" %D

-- Loved this tool

**Comment by allinurl** [comment]
Please try this:

    goaccess access.log --log-format='%h [%d:%t %^] "%r" %s %^ %b "%R" "%u" "%^" %^ "%^" %D' --date-format=%d/%b/%Y --time-format=%T

I think the `%>s` was the issue in this case.

**Comment by fbaptista** [comment]
Thanks a lot for your help buddy, 
still doen't take the "time-taken" field

![image](https://user-images.githubusercontent.com/5215781/33771710-cf7e06ee-dc10-11e7-8c65-3bcd4d24e97b.png)

**Comment by allinurl** [comment]
This is what I get from the line you posted above:



![2017-12-08-091540_621x173_scrot](https://user-images.githubusercontent.com/5005367/33771923-8356c994-dbf8-11e7-9625-f748f2683bde.png)

Can you please post a few more lines so I can look into it? Thanks.

**Comment by fbaptista** [comment]
sure! the full log (3 lines) is now attached: 


10.253.15.35 [07/Dec/2017:16:12:44 -0300] "POST /ProxyPGE/aproxypgeservices_services HTTP/1.1" 200 16948 4877 "-" "Jakarta Commons-HttpClient/3.1" "asespprodproxypge2:full-ha-server" - "-" 430778
10.253.15.35 [07/Dec/2017:16:13:44 -0300] "POST /ProxyPGE/aproxypgeservices_services HTTP/1.1" 200 16948 4877 "-" "Jakarta Commons-HttpClient/3.1" "asespprodproxypge2:full-ha-server" - "-" 335778
10.253.15.35 [07/Dec/2017:16:14:44 -0300] "POST /ProxyPGE/aproxypgeservices_services HTTP/1.1" 200 16948 4877 "-" "Jakarta Commons-HttpClient/3.1" "asespprodproxypge2:full-ha-server" - "-" 534778


[RPAppliance_access.log](https://github.com/allinurl/goaccess/files/1543023/RPAppliance_access.log)

**Comment by fbaptista** [comment]
I am using goaccess 1.2 will update just in case. ...

**Comment by allinurl** [comment]
Might be an issue with your log. If I open it from my side, I don't get a request per line, but only one line containing multiple entries. e.g.,

    vim RPAppliance_access.log

**Comment by fbaptista** [comment]
oh dear....
vim shows a ^M on the EOL...

using dos2unix still doesn't work, but now I will be closer. 
thanks a lot buddy!

**Comment by andreig09** [comment]
I tried it changing the `%>s` for an `%s` and it worked.

Thanks a lot!

(I'm working on this with @fbaptista by the way)
