### ISSUE TITLE
Log format support request

### ISSUE THREAD

**Issue by technotarek** [allinurl/goaccess#963]
I'm embarrassed I can't figure out the correct log format using the specifiers :( Can you help?

    website.com:80 172.68.65.128 - - [04/Dec/2017:06:30:29 -0500] "GET /apple-touch-icon-180x180-precomposed.png HTTP/1.1" 304 153 "https://website.com/browse" "Mozilla/5.0 (Linux; Android 6.0.1; SAMSUNG SM-G900P Build/MMB29M) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/6.2 Chrome/56.0.2924.87 Mobile Safari/537.36"

I've tried about 100 permutations of this:

    %v:%^ %h %^ %^ [%d:%t %^] "%r" %s %b "%R" "%u"

I'm getting: Token '-' doesn't match specifier '%h'

Many, many thanks in advance.

**Comment by allinurl** [comment]
Looks like a COMBINED with virtual host, please give this a shot:

    goaccess access.log --log-format=VCOMBINED --enable-panel=REFERRERS --enable-panel=KEYPHRASES

**Comment by technotarek** [comment]
Thanks for the quick response. I had tried that as well, but no luck. Now that I look at the full error, it looks like the issue is deeper. Here's my command string:

`goaccess /var/log/apache2/other_vhosts_access.log -o /var/www/report.html --log-format=VCOMBINED --enable-panel=REFERRERS --enable-panel=KEYPHRASES`

Here's the error:

```
/var/log/apache2/access.log
Parsed 10 lines producing the following errors:

Token '-' doesn't match specifier '%h'
...
```

**Why is it referencing a different log file than I submitted in the command string?** I've confirmed the log file reference in the command exists at the specified location and has read permissions for all.

**Comment by allinurl** [comment]
interesting, I think this is issue was addressed upstream. However, try adding `--no-global-config`

    goaccess --no-global-config /var/log/apache2/other_vhosts_access.log -o /var/www/report.html --log-format=VCOMBINED --enable-panel=REFERRERS --enable-panel=KEYPHRASES

**Comment by technotarek** [comment]
Voila. That did the trick. Does that mean that goaccess.conf was overriding my execution command? Is the log file to parse specified in the .conf? Just curious.

Thank you!

**Comment by allinurl** [comment]
Glad that did it. That's right. You can try to build from [**development**](https://github.com/allinurl/goaccess#build-from-github-development), I believe that was address a while back and let me know if that solves the issue. The log file to parse can also be specified in the conf file.
