### ISSUE TITLE
View details of per virtual host (filtering)

### ISSUE THREAD

**Issue by ppc52776** [allinurl/goaccess#965]
Hi Developers,
Thanks for this great application, it really helps me a lot.
There are many virtual hosting in my server. 
Is it possible to view the detail of one selected virtual host ?
Thanks.

**Comment by allinurl** [comment]
Certainly, awk, grep, sed are your friends for this, e.g. (assuming your vhost is the first field),

    awk '$1~/dev.domain.com/' access.log | goaccess --log-format=VCOMBINED -

**Comment by ppc52776** [comment]
Thanks a lot. :smile:
