### ISSUE TITLE
Trying to match pattern on Nginx web server log

### ISSUE THREAD

**Issue by srliuhao** [allinurl/goaccess#970]
Hello, I've been trying to match the pattern without success.

sample from my log:
`{"@timestamp":"2017-12-23T22:00:01+08:00","host":"10.1.1.4","clientip":"114.249.210.176","size":83311,"responsetime":0.062,"referer":"http://mytest.com/perio/articleList.do?page=1&pageSize=100","agent":"Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; InfoPath.2; .NET4.0C)","status":"200"}`

my log-format is:
` {%^:"%d\T%^",%^,%^:"%h",%^:"%b",%^:%L,%^:"%q",%^:"%u",%^:"%s"}`

the error is: 
> goaccess: unrecognized option '--.NET'

**Comment by allinurl** [comment]
It looks like you are missing the request part which is required by goaccess. If you use the referrer part as the request, then you could use:

    goaccess access.log --log-format='%^:"%dT%t+%^",%^,%^:"%h",%^:%b,%^:%T,%^:"%r",%^:"%u",%^:"%s"' --date-format="%Y-%m-%d" --time-format=%T -M no -H no

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
