### ISSUE TITLE
Multiple log files via goaccess.conf?

### ISSUE THREAD

**Issue by dmhendricks** [allinurl/goaccess#971]
Greetings,

I'm using the Docker image under Plesk and creating containers for users that want to use it. This means no command-line access. The Apache log files are separated by protocol (`access_log` and `access_ssl_log`).

However, in `goaccess.conf`, it appears that I can only specify one `log-file`. For my site, I chose HTTPS traffic since my entire site is HTTPS. However, it would be nice if I could configure `goaccess.conf` to process both `access_log` and `access_ssl_log` for users that have mixed.

Is this possible via the config file? (again, shared hosting environment - limited or no SSH access for users).

Thank you,
Daniel

**Comment by allinurl** [comment]
Great question. It should let you specify multiple `log-file` variables in the configuration file. e.g.,

    log-file /var/log/access.log
    log-file /var/log/access_ssl.log

Please let me know if that solves the issue for you.

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
