### ISSUE TITLE
Error occured at: src/parser.c - read_log - 2669

### ISSUE THREAD

**Issue by yuanlily** [allinurl/goaccess#972]
When I want to use goaccess to analyse my log file, the following error occurs. How to solve this problem? 

goaccess <access.log> -o <output html> real-time-html

GoAccess - version 1.2 - Dec 21 2017 06:35:41
Config file: /usr/local/etc/goaccess.conf

Fatal error has occurred
Error occured at: src/parser.c - read_log - 2669
Unable to open the specified log file. No such file or directory

**Comment by allinurl** [comment]
Sounds like it can't find your access log. 

Have you made sure you have the right path to your access log and that you have the right permission to read the log?

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.

**Comment by netham91** [comment]
Facing the same issue. Running using:
`
    goaccess -f -log-file=/var/log/nginx/access.log -c
`
It opens the box to config and then gives error "Unable to open the specified log file. No such file or directory"

**Comment by allinurl** [comment]
@netham91 Please take a look at the [**examples**](https://goaccess.io/man#examples) in the man page. Your command should be:

    goaccess /var/log/nginx/access.log -c
