### ISSUE TITLE
Trying to match pattern: Django application log pattern

### ISSUE THREAD

**Issue by parthyz** [allinurl/goaccess#974]
I have tried W3C log format for the matching below sample log and it shows the below error. I am unable to fix this now.  Any idea how to fix this - please help?

Log format sample:
2017-10-16 04:35:16,379 - WARNING - test - Active Directory: Failed login for user abcd

Error :
Format Errors - Verify your log/date/time format:
Token '04:35:16,379' doesn't match specifier '%t'

**Comment by allinurl** [comment]
GoAccess is a web log analyzer. It looks like your log is not a web log though.

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
