### ISSUE TITLE
real time HTML output

### ISSUE THREAD

**Issue by Fieel** [allinurl/goaccess#978]
Hello,

i created a page for displaying my nginx data in real time. I didn't manage to make it work real time as of now because i really don't know how, even following your instructions.

This works, though:
`sudo goaccess -f /var/log/nginx/access.log -a > /var/www/nginx_monitor/index.html`

How do i make my data real time?

**Comment by 0x69676f72** [comment]
try `goaccess access.log -o /var/www/html/report.html --log-format=COMBINED --real-time-html `

**Comment by Fieel** [comment]
From https://goaccess.io/faq#configuration :

> How do I generate a real-time HTML report?
The process of generating a real-time HTML report is very similar to the process of creating a static report.
>Just generate a static report and place the output html file under your web server www public folder. You need to add a couple of additional real-time flags. The use of --real-time-html is required.
 ># goaccess access.log -o /usr/share/nginx/www/rt.goaccess.io/report.html --real-time-html

That's not correct. --real-time-html is not working and is not even listed in the manual nor the -help command text.

What am i missing here?

**Comment by 0x69676f72** [comment]
in your case,
`goaccess  /var/log/nginx/access.log -o /var/www/nginx_monitor/index.html --log-format=COMBINED --real-time-html `

**Comment by Fieel** [comment]
@0x69676f72 I get this error:
`goaccess: unrecognized option '--real-time-html'`

**Comment by 0x69676f72** [comment]
hum, how did you install?
try sudo apt-get install -y goaccess

**Comment by Fieel** [comment]
I'm working on a Raspberry Pi with Raspbian lite OS, apparently the  latest goaccess package in the package list is 0.9 which is quite old. Didn't even support the real-time html i think.

Anyways, i purged everything with
`sudo apt-get purge goaccess`
and manually reinstalled using the direct link [here](https://goaccess.io/download):
`$ wget http://tar.goaccess.io/goaccess-1.2.tar.gz
$ tar -xzvf goaccess-1.2.tar.gz
$ cd goaccess-1.2/
$ ./configure --enable-utf8 --enable-geoip=legacy
$ make
# make install`

Kept having problems, i didn't have 'geoIP nor ncurses installed so i google and found this useful thread right here on github: 
[geoIP](https://github.com/allinurl/goaccess/issues/852)
`$ wget https://github.com/maxmind/geoip-api-c/releases/download/v1.6.11/GeoIP-1.6.11.tar.gz
$ tar -xzvf GeoIP-1.6.11.tar.gz
$ cd GeoIP-1.6.11
$ ./configure
$ make
# make install`
or
`# apt get install libncursesw5-dev libgeoip-dev`

[ncursesw](https://github.com/allinurl/goaccess/issues/102)
`sudo apt-get install libncursesw5-dev`

**Comment by Fieel** [comment]
Aaand it's working! Thank you all for your help, people from those months-old github threads too lol.

**Comment by Fieel** [comment]
![capture](https://user-images.githubusercontent.com/11167635/34463228-f8594230-ee54-11e7-9b4c-7e50017fd852.JPG)

**Comment by Fieel** [comment]
This is the command i'm running:

`sudo goaccess /var/log/nginx/access.log -o /var/www/nginx_monitor/index.html --log-format=COMBINED --real-time-html --ws-url=ws://192.168.1.2:7890
`
#what i did
/var/log/nginx/access.log                       --> my nginx log
/var/www/nginx_monitor/index.html     --> my output .html file, i can access this through a subdomain
--real-time-html                                     --> enable realtime
--ws-url                                                  --> raspberry LAN ip address : port 7890
                                                                     (sudo ufw allow 7890 to open the doors)
--log-format=COMBINED                     --> idk what this does

**Comment by 0x69676f72** [comment]
Perhaps you want to isolate the problem by reporting an exported log.

`go access /var/log/nginx/access.log -o report.html --log-format=COMBINED `

that works?

**Comment by 0x69676f72** [comment]
open report.html double clicking RaspBian browser

**Comment by Fieel** [comment]
Turns out my websites weren't logging stuff properly so of course I didn't see any update
