### ISSUE TITLE
Multiple BTree databases

### ISSUE THREAD

**Issue by jabiertxof** [allinurl/goaccess#982]
Hi, I have a server with multiple virtualhosts with separate log for each. Is posibol set a persitent BTree database for easch virual host?
Thanks in advance.

**Comment by TerraTech** [comment]
Sure, via the ```--db-path``` switch.  Just process each virtual host's log files independently rooted in their own goaccess processing directory tree.

**Comment by jabiertxof** [comment]
Thanks!!!
