### ISSUE TITLE
Custom Log Format with X-Forwarded-For

### ISSUE THREAD

**Issue by zoso65** [allinurl/goaccess#984]
Hi 

I have a problem with my apache's access log parsing by goaccess.
my LogFormat in apache is:

    LogFormat "\"%{X-Forwarded-For}i\" %l %u %t \"%r\" %>s %O \"%{Referer}i\" \"%{User-Agent}i\"" combined

in goaccess i set the log-format like this:

    log-format "%{X-Forwarded-For}i" %l %u %t "%r" %>s %O "%{Referer}i" "%{User-Agent}i"

and i run goaccess with this options:

    goaccess -f /var/log/apache2/access.log

i get this error:

```
**Token '"GET' doesn't match specifier '%t'**
**Token 'like' doesn't match specifier '%t'**
**Token '"GET' doesn't match specifier '%t'**
**Token '"GET' doesn't match specifier '%t'**
```

**Format Errors - Verify your log/date/time format**

my log file is like this:

    66.66.69.69" - - [31/Dec/2017:06:56:16 +0330] "GET /company/Detail/16018/%D8%A2%D8%B1%D9%85%D8%A7%D9%86%20%D9%85%D8%AD%DB%8C%D8%B7%20%D9%BE%D8%A7%DA%A9%20%D8%A7%DB%8C%D8%B1%D8%A7%D9%86%DB%8C%D8%A7%D9%86 HTTP/1.1" 200 11029 "-" "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)

can you please help me how to set log-format in goaccess to parse my logs with X-Forwarded-For enabled?

Thanks.

**Comment by allinurl** [comment]
Can you please post a few more lines from your access log so I can take a look? Thanks

**Comment by allinurl** [comment]
Any updates on this? Can you please clarify if the client IP is enclosed within double quotes? and if there can be more than one IP and how are these delimited? Thanks.

**Comment by zoso65** [comment]
yes it's in double quotes.

**Comment by allinurl** [comment]
This should do it.

    goaccess access.log --log-format='"%h" %^[%d:%t %^] "%r" %s %b "%R" "%u"' --date-format=%d/%b/%Y --time-format=%T

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
