### ISSUE TITLE
goaccess custom log format

### ISSUE THREAD

**Issue by kiranpkosti** [allinurl/goaccess#985]
Hi all,

we are using the apache webserver with below log format.

    LogFormat "%h %{True-Client-IP}i %l %u %t \"%m %{REALREQ}e %H\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\" \"%{Cookie}i\" \"%{cookie}n\" %{UNIQUE_ID}e \"%r\" %X %D" Custom

when we try accessing the monitoring of Logs via Goaccess Log monitoring tool, we are unable to get the true-client IP ,

can you please help how to create the custom log format for goaccess for accessing the access logs of apache webserver ?

Thanks in advance,

**Comment by allinurl** [comment]
Can you please post a few lines from your access log so I can take a look? Thanks

**Comment by zoso65** [comment]
"91.98.215.125" - - [31/Dec/2017:09:04:20 +0330] "GET /templates/template_fa/assets/images/my-logo.png HTTP/1.1" 200 3775 "http://mydomain.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:56.0) Gecko/20100101 Firefox/56.0"
"91.98.215.125" - - [31/Dec/2017:09:04:20 +0330] "GET /statics/images/category/1511265302._ID4_4.gardeshgari,mohajerat.jpg HTTP/1.1" 200 103022 "http://mydomain.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:56.0) Gecko/20100101 Firefox/56.0"
"91.98.215.125" - - [31/Dec/2017:09:04:20 +0330] "GET /statics/images/category/1511253218._ID1_1.ghaza.jpg HTTP/1.1" 200 25196 "http://mydomain.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:56.0) Gecko/20100101 Firefox/56.0"
"91.98.215.125" - - [31/Dec/2017:09:04:20 +0330] "GET /statics/images/category/1511264942._ID1_2.jpg HTTP/1.1" 200 17283 "http://mydomain.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:56.0) Gecko/20100101 Firefox/56.0"
"91.98.215.125" - - [31/Dec/2017:09:04:21 +0330] "GET /statics/images/category/1511264727._ID1_2.jpg HTTP/1.1" 200 21486 "http://mydomain.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:56.0) Gecko/20100101 Firefox/56.0"
"91.98.215.125" - - [31/Dec/2017:09:04:21 +0330] "GET /statics/images/category/1511254176._ID3_2.ab,bargh.jpg HTTP/1.1" 200 51914 "http://mydomain.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:56.0) Gecko/20100101 Firefox/56.0"
"91.98.215.125" - - [31/Dec/2017:09:04:21 +0330] "GET /statics/images/category/1511263242._ID1_1.amlak,sakhto%20saz.jpg HTTP/1.1" 200 19086 "http://mydomain.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:56.0) Gecko/20100101 Firefox/56.0"
"91.98.215.125" - - [31/Dec/2017:09:04:21 +0330] "GET /statics/images/category/1514634444._ID1_1.amniyati.png HTTP/1.1" 200 110592 "http://mydomain.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:56.0) Gecko/20100101 Firefox/56.0"
"91.98.215.125" - - [31/Dec/2017:09:04:21 +0330] "GET /statics/images/category/1511263771._ID1_2.jpg HTTP/1.1" 200 22912 "http://mydomain.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:56.0) Gecko/20100101 Firefox/56.0"
"91.98.215.125" - - [31/Dec/2017:09:04:21 +0330] "GET /statics/images/category/1511254024._ID2_3.jpg HTTP/1.1" 200 29463 "http://mydomain.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:56.0) Gecko/20100101 Firefox/56.0"
"91.98.215.125" - - [31/Dec/2017:09:04:21 +0330] "GET /statics/images/category/1511263919._ID1_2.jpg HTTP/1.1" 200 20327 "http://mydomain.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:56.0) Gecko/20100101 Firefox/56.0"
"91.98.215.125" - - [31/Dec/2017:09:04:21 +0330] "GET /statics/images/category/1511253779._ID1_1.madan.jpg HTTP/1.1" 200 20545 "http://mydomain.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:56.0) Gecko/20100101 Firefox/56.0"
"91.98.215.125" - - [31/Dec/2017:09:04:21 +0330] "GET /templates/template_fa/assets/images/favicon.png HTTP/1.1" 200 1678 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:56.0) Gecko/20100101 Firefox/56.0"
"91.98.215.125" - - [31/Dec/2017:09:04:22 +0330] "GET /statics/images/article/90.90.16291361_tmp.png HTTP/1.1" 200 9466 "http://mydomain.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:56.0) Gecko/20100101 Firefox/56.0"
"91.98.215.125" - - [31/Dec/2017:09:04:22 +0330] "GET /statics/images/article/90.90.200759327_tmp.png HTTP/1.1" 200 8856 "http://mydomain.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:56.0) Gecko/20100101 Firefox/56.0"
"91.98.215.125" - - [31/Dec/2017:09:04:23 +0330] "GET /templates/template_fa/bower_components/font-awesome/fonts/fontawesome-webfont.woff2 HTTP/1.1" 200 77461 "http://mydomain.com/templates/template_fa/bower_components/font-awesome/css/font-awesome.min.css" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:56.0) Gecko/20100101 Firefox/56.0"
"91.98.215.125" - - [31/Dec/2017:09:04:29 +0330] "GET /index/event/ HTTP/1.1" 200 6215 "http://mydomain.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:56.0) Gecko/20100101 Firefox/56.0"
"91.98.215.125" - - [31/Dec/2017:09:04:42 +0330] "GET /aboutus HTTP/1.1" 200 5211 "http://mydomain.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:56.0) Gecko/20100101 Firefox/56.0"
"91.98.215.125" - - [31/Dec/2017:09:04:43 +0330] "GET /templates/template_fa/assets/css/style.css?v=84588 HTTP/1.1" 200 37424 "http://mydomain.com/aboutus" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:56.0) Gecko/20100101 Firefox/56.0"

**Comment by zoso65** [comment]
This is my accesslog samble.
Thanks

**Comment by allinurl** [comment]
Please try:

    goaccess access.log --log-format='"%h" %^[%d:%t %^] "%r" %s %b "%R" "%u"' --date-format=%d/%b/%Y --time-format=%T

**Comment by zoso65** [comment]
It works with this format.
Thank you so much.

**Comment by augustinonline** [comment]
Hi,
can anyone help on this log format [
10.247.0.2 - - [07/Mar/2019:23:58:57 -0500] XIH2kQryBjAAADqBoQcAAAG7 "GET /lbcheck.html HTTP/1.1" 200 33 612
10.247.0.2 - - [07/Mar/2019:23:58:58 -0500] XIH2kgryBjAAAEWSlZ8AAAA- "GET /lbcheck.html HTTP/1.1" 200 33 846
10.247.0.2 - - [07/Mar/2019:23:59:00 -0500] XIH2lAryBjAAAEWSlb0AAAAj "GET /lbcheck.html HTTP/1.1" 200 33 804
10.247.0.3 - - [07/Mar/2019:23:59:00 -0500] XIH2lAryBjAAAEbTbqEAAATY "GET /lbcheck.html HTTP/1.1" 200 33 594
10.247.0.2 - - [07/Mar/2019:23:59:00 -0500] XIH2lAryBjAAAEWSlcEAAADN "GET /lbcheck.html HTTP/1.1" 200 33 575

**Comment by augustinonline** [comment]
Hi,
Can anyone help on the log format for the below access log.

10.247.0.2 - - [07/Mar/2019:23:58:57 -0500] XIH2kQryBjAAADqBoQcAAAG7 "GET /lbcheck.html HTTP/1.1" 200 33 612
10.247.0.2 - - [07/Mar/2019:23:58:58 -0500] XIH2kgryBjAAAEWSlZ8AAAA- "GET /lbcheck.html HTTP/1.1" 200 33 846
10.247.0.2 - - [07/Mar/2019:23:59:00 -0500] XIH2lAryBjAAAEWSlb0AAAAj "GET /lbcheck.html HTTP/1.1" 200 33 804
10.247.0.3 - - [07/Mar/2019:23:59:00 -0500] XIH2lAryBjAAAEbTbqEAAATY "GET /lbcheck.html HTTP/1.1" 200 33 594
10.247.0.2 - - [07/Mar/2019:23:59:00 -0500] XIH2lAryBjAAAEWSlcEAAADN "GET /lbcheck.html HTTP/1.1" 200 33 575

**Comment by houssem-alt** [comment]
I , have problem with my log :


Dec 18 10:06:14 apihost01 domain-ext x.x.x. via x.x.x.x-  18/Dec/2018:10:06:05 +0100 GET 200 /app.php   /api/report/campaigns/354/summary.json /var/www/apiv1/web/app.php 0 cpu:6.82 allocatedmem:4

**Comment by allinurl** [comment]
@houssem-alt please describe each field from your access.log. Thanks

**Comment by houssem-alt** [comment]
Dec 18 10:06:14 apihost01 domain.com-ext x.x.x.x via x.x.x.x - 
18/Dec/2018:10:06:05 +0100 GET 200 /app.php 
/api/report/campaigns/354/summary.json /var/www/apiv1/web/app.php 0 
cpu:6.82 allocatedmem:4

**Comment by allinurl** [comment]
@houssem-alt as I mentioned above, please describe what each field means.

**Comment by houssem-alt** [comment]
Dec 18 10:06:14 apihost01 dialog.apis.edatis.com-ext 158.255.69.87 via 83.136.214.164 -  18/Dec/2018:10:06:05 +0100 GET 200 /app.php   /api/report/campaigns/354/summary.json /var/www/apiv1/web/app.php 0 cpu:6.82 allocatedmem:4

I try this command :+1: 
goaccess access.log --log-format=COMBINED -a -o acces.html

Parsed 1 linesproducing the following errors:

Token 'Dec' doesn't match specifier '%h'

Format Errors - Verify your log/date/time format
Thanks

**Comment by allinurl** [comment]
@houssem-alt To help you out, I'd need to know what the following fields are:

    /app.php /api/report/campaigns/354/summary.json /var/www/apiv1/web/app.php 0 cpu:6.82 allocatedmem:4

**Comment by houssem-alt** [comment]
in fact these are centralized logs with rsyslog

**Comment by allinurl** [comment]
This should do it:

    goaccess access.log --log-format='%^ %^ %^ %^ %v %h %^ %^ %^ %d:%t %^ %m %s %U %R %^ %L %^' --date-format=%d/%b/%Y --time-format=%T --ignore-panel=OS --ignore-panel=BROWSERS

**Comment by houssem-alt** [comment]
@allinurl   thank you very much sir .

**Comment by houssem-alt** [comment]
Hello again, please,
I still have problems with these two log files I need your help Thanks to you cordially


Feb  1 11:09:00 webhost07 houssem.v7.digi.com: [Thu Feb 01 11:09:00.756041 2018] [:error] [pid 29413] [client 83.136.214.179:48578] PHP Notice:  Trying to get property of non-
object in /var/www/V7/src/Dialog/Extension/Twig/DialogExtension.php on line 302

--------------------------------------------------------------------------------------------------------------------

Feb  1 09:49:15 webhost07 houssem.v7.digi.com: 37.71.178.6 - - [01/Feb/2018:09:49:14 +0100] "GET /dialog/reporting/parameter HTTP/1.0" 200 8738 "https://houssem.v7.digi.com/d
ialog/reporting/emailing/home" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36"

**Comment by allinurl** [comment]
@houssem-alt you can't parse error logs.

**Comment by houssem-alt** [comment]
@allinurl , Ok ,
and for this log , 
Feb  1 09:49:15 webhost07 houssem.v7.digi.com: 37.71.178.6 - - [01/Feb/2018:09:49:14 +0100] "GET /dialog/reporting/parameter HTTP/1.0" 200 8738 "https://houssem.v7.digi.com/d

**Comment by allinurl** [comment]
@houssem-alt seems it's missing the end part?

**Comment by houssem-alt** [comment]
### **This my log , :** 

Feb  1 09:49:58 webhost07 dialog.v7.houssem.com: 196.203.219.155 - - [01/Feb/2018:09:49:58 +0100] "GET /dialog/campaign HTTP/1.0" 200 27570 "https://1042066294.v7.houssem.com/dia
log/reporting/emailing/home" "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:58.0) Gecko/20100101 Firefox/58.0"

**Comment by allinurl** [comment]
@houssem-alt 

    goaccess log --log-format='%^ %^ %^ %^ %^ %v %h %^[%d:%t %^] "%r" %s %b "%R" "%u"' --date-format=%d/%b/%Y --time-format=%T

**Comment by houssem-alt** [comment]
@allinurl  thank you in advance sir :+1:

**Comment by houssem-alt** [comment]
@allinurl  Hello sir ,
How to monitor multiple websites with 'goaccess’？ , I tested to execute two log in parallel with the command --real-time I got an error as preview below
Config file: /etc/goaccess.conf

Fatal error has occurred
Error occurred at: src/websocket.c - ws_socket - 2782
Unable to set bind: Address already in use.

**Comment by houssem-alt** [comment]
@allinurl , it's good problem solved, thanks in advance :)

**Comment by allinurl** [comment]
@houssem-alt https://github.com/allinurl/goaccess/issues/625#issuecomment-272905761
