### ISSUE TITLE
Need help with custom squid log 

### ISSUE THREAD

**Issue by xventil** [allinurl/goaccess#987]
I have a setup working reading the squid log, but now i was asked to change the epoch from squid log files to human readble date and time.. so my logs now are like this

    04/Jan/2018:17:41:13 -0000 - FIN 10.XXX.XX.XXX 403 PARENT_HIT 403 FIN 10.XXX.XXX.XXX 10.XXX.XX.XX 0.140

can anyone please help me. thanks in advance

**Comment by allinurl** [comment]
Were you using goaccess before with a different date/time format? The date/time format should be the default `--date-format=%d/%b/%Y` and `time-format=%T`. Though, goaccess requires the requested file part from the log.

**Comment by allinurl** [comment]
Any updates on this?

**Comment by xventil** [comment]
Sorry for the delay on the answer...
this was what i placed on conf, and worked
log-format %x.%^ %~ %L %h %^/%s %b %m %U %^
and date and time format - %s

got my boss to drop the time conversion.

thank you for the help, and sorry again for the long time in replying
