### ISSUE TITLE
https issue -'load unsafe script'

### ISSUE THREAD

**Issue by jpdentone** [allinurl/goaccess#992]
my site redirects to HTTPS so when I try to run

    # /usr/local/bin/goaccess access.log -o /var/www/html/report.html --real-time-html --ssl-cert=/etc/nginx/ssl/fullchain.pem --ssl-key=/etc/nginx/ssl/privkey.pem

chrome shows a blank page and I have the option to run 'load unsafe script', I click there and goaccess loads and everything seems ok but that kills the https

is this a bug or im doing something wrong ?

**Comment by allinurl** [comment]
What's the output from Chrome's console? Also, I'm not sure I understand what you mean with "everything seems ok but that kills the https"? Thanks.

**Comment by jpdentone** [comment]
I meant that it loads with unsecure HTTPS message https://puu.sh/z0K9e/38a17d8591.png -- which is not big deal for me but just wondering is there is a fix for this or if this is how it works

chrome console error:
Mixed Content: The page at 'https://www.abc.xyz/report.html' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://www.abc.xyz:7890/'. This request has been blocked; this endpoint must be available over WSS.

Uncaught DOMException: Failed to construct 'WebSocket': An insecure WebSocket connection may not be initiated from a page loaded over HTTPS.

**Comment by allinurl** [comment]
Please use:

    goaccess access.log -o /var/www/html/report.html --real-time-html --ssl-cert=/etc/nginx/ssl/fullchain.pem --ssl-key=/etc/nginx/ssl/privkey.pem
 --ws-url=wss://www.abc.xyz:7890

**Comment by jpdentone** [comment]
that fixed

thanks
