### ISSUE TITLE
Am I turning spiders off correctly?

### ISSUE THREAD

**Issue by yobyot** [allinurl/goaccess#993]
Hello.

I wonder what I might be doing wrong and would appreciate any pointers. As you can see in the image below but, as you can see, the real-time HTML report specifically says it includes spiders.

I'm starting like this:

`goaccess /path-to/access.log -o /path-to-webserver-root/report.html --log-format=COMBINED --real-time-html --daemonize --geoip-database=/path-to-geoip/GeoLite2-City.mmdb`

Thanks.

![2018-01-15_18-51-57](https://user-images.githubusercontent.com/14332263/34965917-d15aa03e-fa25-11e7-93d8-5cc8628881b0.png)

**Comment by allinurl** [comment]
Please try passing `--ignore-crawlers`, e.g.,

    goaccess /path-to/access.log --ignore-crawlers -o /path-to-webserver-root/report.html --log-format=COMBINED --real-time-html --daemonize --geoip-database=/path-to-geoip/GeoLite2-City.mmdb

**Comment by allinurl** [comment]
Closing this. Feel free to reopen as needed.
