### ISSUE TITLE
Time Distribution Y-Axis Description seems to be wrong 

### ISSUE THREAD

**Issue by rascrasc** [allinurl/goaccess#999]
Panel Time Distribution
Option Area Spline & Bandwidth shows wrong Y Axis Data 

It seems that table cell width is too small, so first character(s) of values on Y-axis is  hidden.

![time-y-axis-display-err](https://user-images.githubusercontent.com/12645606/35281089-5b3a2ad6-0052-11e8-85b7-4c7414041f65.png)

**Comment by allinurl** [comment]
Thanks for reporting this. I've pushed a [**fix**](https://github.com/allinurl/goaccess/commit/1c6a702f860b34b5c9bb8612aeff63288e298db4) for this. Please build from [**development**](https://github.com/allinurl/goaccess#build-from-github-development) and let me know if that solves the issue for you. Thanks!

**Comment by rascrasc** [comment]
Thanks for fast fix!
But still some pixel are eaten on larger numbers. ;-)

![goaccess-time-dist-err2](https://user-images.githubusercontent.com/12645606/35329565-a1f78fdc-0100-11e8-8a87-b435b2df8025.png)

**Comment by allinurl** [comment]
Please do a pull --rebase and let me know if that solves the issue. Thanks!

**Comment by allinurl** [comment]
Closing this. Feel free to reopen it if needed.
